### ISSUE TITLE
allow mixins to have entities as children, then when using the mixin, children will be injected

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1000]
```html
<a-assets>
  <a-mixin id="frame">
    <a-box position="0 1 0"/>
    <a-box position="1 0 0"/>
    <a-box position="0 0 1"/>
    <a-box position="1 0 1"/>
  </a-mixin>
</a-assets>

<a-entity mixin="frame">
  <!-- All of the boxes will be injected here. -->
</a-entity>
```

**Comment by RangerMauve** [comment]
What order will it go in? mixin1, mixin2, entity? Or entity, mixin1, mixin2?

**Comment by ngokevin** [comment]
Mixins are applied left-to-right. So right mixin trump the left ones.

Entity attributes trump attributes applied by mixins.

**Comment by ngokevin** [comment]
I am not sure what to do if you apply multiple mixins with children. Could either *replace*, or *merge*.

**Comment by ngokevin** [comment]
Being mixins, it seems more predictable to merge

**Comment by cvan** [comment]
as I'm sure you know, this is reinventing templates lol. you do have to make `a-mixin` inert (behind the scenes, it should extend `<template>`) or else a bunch of custom elements are going to get prematurely called and callbacks called and events fired and so on.

**Comment by cvan** [comment]
if I have `<a-entity mixin="frame">`, you're going to inject a bunch of elements (event delegation now again needed for `<a-event>`, btw).

then suppose some other elements get inserted. or some JS modifies some attributes - or some elements inside have `mixin`s themselves. the HTML is going to change.

and then if I set `<a-entity mixin="">`, what happens? do you remove everything?

**Comment by ngokevin** [comment]
Yeah, it provides a subset of the feature set of templates. But it doesn't try to do any custom element registration or parameter passing. It solves the most basic use case of templates, I have something, and I want to copy/paste it.

I'd expect removing the mixin to remove that was everything injected. It's a bit of an edge case. But removing vanilla mixins at the moment doesn't do anything right now anyways.

I'm not worried about ```a-event```. Mixins are a first-class citizen, ```a-event``` is not. ```a-event``` will still work anyways since it applies the listener to the parent node. We never really agreed as a team on its place within A-Frame so it's almost even on the chopping block let alone getting in the way of core implementation.

```html
<a-entity mixin="frame">
  <a-event></a-event>
  <!-- Elements injected here. -->
</a-entity>
```

**Comment by cvan** [comment]
`<!-- Elements injected here. -->`

you're going to have to keep track of where that element is (that's what the `<a-root>` was for)

**Comment by cvan** [comment]
> We never really agreed as a team on its place within A-Frame so it's almost even on the chopping block let alone getting in the way of core implementation.

I don't remember having a team discussion on mixins

**Comment by RangerMauve** [comment]
On the topic of merging vs replacing, I agree that it'd be more useful to merge.

Also, it'll be funny to see the first issue with recursive mixins causing crashes.

**Comment by ngokevin** [comment]
this isn't templating, it's not taking attributes and templating them so you don't need a-root. If we want to support removal, we can just assign data attribute

Mixins weren't created in a vacuum though. There was more than one set of eyes on it. Maybe not the whole team, but at least some agreement

**Comment by ngokevin** [comment]
note i'm not 100% sold on this idea yet since it does provide a subset of template logic. but it could be useful for simple copy/paste common sets of entities or mixing in animations

**Comment by ngokevin** [comment]
https://github.com/ngokevin/aframe-template-component
