### ISSUE TITLE
With Live Reload, browser indicates page is in loading state in Anime UI scene

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1001]
[http://localhost:9000/examples/showcase-anime-UI/](http://localhost:9000/examples/showcase-anime-UI/)

The throbber in both Firefox and Chrome keeps throbbing, indicating some network traffic. But the Consoles' Network tabs don't seem to indicate such.

I reproduced in both Firefox and Chrome with Live Reload enabled (which is the default in `scripts/budo.js`).

Doesn't happen when I manually disable Live Reload in `scripts/budo.js`.

Can't seem to reproduce with other scenes.

**Comment by ngokevin** [comment]
budo replace should fix
