### ISSUE TITLE
Documentation on animation is misleading

### ISSUE THREAD

**Issue by belen-albeza** [aframevr/aframe#1003]
Currently transformations are applied using the object's center as origin, instead of world's `0,0,0`.

However, in https://aframe.io/docs/core/animation.html we can read:

> [...] to define a 5-meter orbit on an entity about the Y-axis that takes 10 seconds, we can offset the position and animate the rotation. [...]
>
> ```html
<a-entity position="5 0 0" rotation="0 0 0">
  <a-animation attribute="rotation"
               to="0 360 0"
               dur="10000"
               fill="forwards"
               repeat="indefinite"></a-animation>
</a-entity>
>```

What this produces is for the entity to rotate over the Y axis over its own center while remaining at `5,0,0`, and not *orbiting*. See [this example on JSfiddle](https://jsfiddle.net/ew7b34x7/)

To achieve an orbit, users must nest entities and set the orbit radius as a position in the nested entity. See [this example](https://jsfiddle.net/ew7b34x7/1/):

```html
<a-entity>
  <a-animation attribute="rotation"
    to="0 360 0"
    dur="10000"
    ease="linear"
    repeat="indefinite"></a-animation>
  <a-sphere position="5 0 0" radius="1">
</a-entity>
 ```

I can make a PR with the changes to the docs if you wish so.

PS: Of course, it would be great if users could define the origin of transformations as an attribute of the animation / entity.

**Comment by ngokevin** [comment]
Good catch.

I address that here. https://github.com/aframevr/aframe/pull/988

Want to copy-and-paste what I have there to the current A-Frame docs?
