### ISSUE TITLE
Add loading indicator

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#1004]
Some scene objects (like models) with lots of geometry or texture data take a while to load.  It would be nice to have some kind of loading indicator so that the user knows that the scene is still loading that would otherwise look broken.

This scene particularly takes long to load:
![image](https://cloud.githubusercontent.com/assets/1560884/13185453/1dfd68b8-d6f6-11e5-922e-c3054f0cd0db.png)

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe/issues/423

**Comment by ngokevin** [comment]
if you're using dev branch, it should be perceivably faster.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/issues/925
