### ISSUE TITLE
Errors when including a-frame at the end of body.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#1005]
It only seems to properly load when I stuff it into the head of the document.   

This is what I get otherwise:

![image](https://cloud.githubusercontent.com/assets/1560884/13187513/4b011a1c-d700-11e5-9355-40de9679ee46.png)

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe/issues/485

**Comment by caseyyee** [comment]
Darn!   I swear I searched for these :P

**Comment by ngokevin** [comment]
like finding a needle in a haystack. luckily i've read through the issues list like 10 times.
