### ISSUE TITLE
360 Video on mobile

### ISSUE THREAD

**Issue by philspitlerSF** [aframevr/aframe#1007]
I can't get the 360 video example to work on my iPhone.

https://aframe.io/examples/showcase/videosphere/

I tried Chrome, Safari and FireFox.

I also tried my own 

http://www.philspitler.com/test/VR/360.html

Neither of which play video on mobile.

**Comment by ngokevin** [comment]
Thanks for filing. We have a lot filed on this:

- https://github.com/aframevr/aframe/issues/316#issuecomment-170182397
- https://github.com/aframevr/aframe/pull/988/files#diff-c90a11d27e2d2b84de947d5d1dbb5f0aR36

**Comment by sarthakdas** [comment]
uhh I still can't get it to work

**Comment by SteveX** [comment]
sarthakdas I do have this working with the current a-frame version, but I can't provide an example until I get some time off my day job.

In a nutshell I am transcoding to m4v, using the start button technique to satisfy the user interaction requirement (play then pause a short video asset to the a-video), then switching the video asset src whenever the video needs to change. That seems to work well.

**Comment by machenmusik** [comment]
the example has been updated recently, 
and should include click-to-play behavior now

if you're saying 
https://aframe.io/examples/showcase/videosphere/
doesn't work, 
can you provide more information? 
e.g. browser, phone model, OS version

if you're saying your own code doesn't work,
but the new example does,
feel free to remix the example...
