### ISSUE TITLE
iOS pin-to-homescreen modal if video is detected and auto-set webkit inline attr on the video

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1008]

**Comment by cvan** [comment]
Thanks

**Comment by cvan** [comment]
see https://github.com/aframevr/aframe/issues/316#issuecomment-209147896:

> @Chocap Safari for iOS provides an option to pin a web page to the iOS homescreen; [see this comment above for an image showing it](https://github.com/aframevr/aframe/issues/316#issuecomment-184896858)
> 
> ![image](https://cloud.githubusercontent.com/assets/203725/14478467/c30b5704-00ca-11e6-899c-a5830ccf8b82.png)
> 
> There's actually a whole open-source library that adds a modal that makes it more obvious:
> 
> http://cubiq.org/add-to-home-screen
> https://github.com/cubiq/add-to-homescreen
> 
> I considered it, but I'm thinking it'd be overkill to add to A-Frame. Someone could create a third-party A-[Frame component](https://aframe.io/docs/core/component.html) ([see this curated list of community components](https://github.com/aframevr/awesome-aframe#components)).

**Comment by ngokevin** [comment]
OK. Can transfer this task to third-party. We have this task logged somewhere else so I can close.
