### ISSUE TITLE
Request: A-Frame on desktop with stereo-graphics but without headset 

### ISSUE THREAD

**Issue by stumpelrilz** [aframevr/aframe#1009]
I would like to use a-frame in the desktop browser (firefox)

- without headset

- with a stereo monitor/tv (preferably line-interleaced left/right separation)

- with the possibility to view stereo-3d images, e.g. side-by-side JPEGs or MPOs created by stereo photo cameras.

I tried it with Firefox nightly (47.0a1), but when I click on the "start vr" icon there happens nothing, except that the icon dissapears.

As said, I have no headset connected. I could have access to a Zeiss Cinemizer Oled. Is this suppurted as well ? AFAIK this behaves like a stereo capable monitor.

**Comment by stumpelrilz** [comment]
Additional information:
I use firefox with Linux with Nvidia gfx-driver.
"glxgears -stereo" renders with stereo-3d on my monitor, so maybe firefox' Web-GL could use this also.

**Comment by mattpolicastro** [comment]
I may be out of my depth on this particular topic, but it seems like WebVR only supports [two device types at the moment:](http://mozvr.github.io/webvr-spec/webvr.html#devtypes) the HMDVRDevice and PositionSensorVRDevice. While I'd think it possible to add stereoscopic monitors as a device type, I don't know if A-Frame is the right place to get it added. Have you looked into the WebVR [Reddit/Slack/mailing list?](http://mozvr.com/#community)?

**Comment by stumpelrilz** [comment]
Thank you for the information. I will try in the MozVR mailing list.

My first thought was that a-frame could make the output e.g. using canvas and mix the left and right image as needed. But probably a-frame is one or more layers too high.

**Comment by mattpolicastro** [comment]
Of course. As I said, I may be out of my depth with what actually renders and positions the stereoscopes, but it's a worthwhile discussion.

**Comment by ngokevin** [comment]
try out https://github.com/oscarmarinmiro/aframe-stereo-component by @oscarmarinmiro

and then you can try `document.querySelector('a-scene').renderer = document.querySelector('a-scene').stereoRenderer`

**Comment by sompylasar** [comment]
@ngokevin How is stereoscopic rendering possible now in A-Frame without a headset? There's [no longer `stereoRenderer`](https://github.com/aframevr/aframe/pull/1740) exposed from `a-scene`.

The https://github.com/oscarmarinmiro/aframe-stereo-component is about a different thing: how to render certain objects to show up only for one eye or the other.

**Comment by sompylasar** [comment]
Update: found this hack https://github.com/aframevr/aframe/issues/1919 
> Hacky way is to set `document.querySelector('a-scene').isMobile` to `true` and remove the orientation modal overlay.

But it doesn't work as intended, causes ```Uncaught (in promise) Error: Failed to enter VR mode (`requestPresent`): No VR hardware found.```

Using desktop Chrome with WebVR enabled via flags (`chrome://flags/#enable-webvr`). Will try disabling it.

**Comment by sompylasar** [comment]
No, the same error with `chrome://flags/#enable-webvr` disabled and `isMobile` set to `true` to hack A-Frame to make it use the stereoscopic renderer:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

A-Frame Version: 0.7.1 (Date 18-10-2017, Commit #0da6cf4)
three Version: ^0.87.0
WebVR Polyfill Version: ^0.9.36

Uncaught (in promise) Error: Failed to enter VR mode (`requestPresent`): No VR hardware found.
```

Obviously, I don't have the VR hardware connected.

**Comment by sompylasar** [comment]
This WebVR emulator Chrome extension helped (with `chrome://flags/#enable-webvr` disabled): https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil/related
