### ISSUE TITLE
Videosphere framerate much lower than source video

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe#1012]
Only getting a few frames per second on a modern PC / Nvidia 970 system both on desktop monitor and via Rift DK2. All other a-frame examples work smoothly except for this. I tried navigating to the source mp4 video and it plays back fine at a high framerate so it's not the source image. Is it just me or are there known performance issues with videosphere?

Referring to this https://aframe.io/examples/showcase/

Update, tried another site and this site works at full framerate so it may be something to do with the aframe example itself:
http://x627.com/vr-gif/
much better (smooother) on my machine than the above

Using firefox nightly  47.0a1 (2016-02-21)

**Comment by ngokevin** [comment]
Firefox has poor video texture perf
