### ISSUE TITLE
Figure out why budo's Live Reload hangs sometimes

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#102]
oooof

**Comment by cvan** [comment]
mattdesl/budo#79 is closed. budo's ecstatic is gone. and I haven't seen this even in the days before budo's ecstatic dependency was removed.

**Comment by dmarcos** [comment]
Budo's Live Reload still hangs on Windows. It takes a long time to reload and if the page is reloaded manually it takes about a minute to get the page loaded.

**Comment by mattdesl** [comment]
Hmm any Windows pc or is it some specific combination of Windows/node/npm? I will try to reproduce.

**Comment by mattdesl** [comment]
Hey @dmarcos, I just tested with latest budo (8.0.2) on Windows 10 Home with npm@3 and node@4.2.5. Testing on `dev` branch with `npm run dev`.

The initial boot-up time for budo is ~7 seconds, but after that LiveReload feels pretty instant.

Getting a lot of 404s in the HTTP logs and some issue with `snazzy`, not sure if related.

If you can reproduce on a small test case can you please post an issue to `budo`. Thanks!

**Comment by cvan** [comment]
I'm starting to see this again on Mac OS X. Very strange. I've filed #934 to check new budo and bump.

**Comment by ngokevin** [comment]
Accidentally closed during merge

**Comment by ngokevin** [comment]
replacing https://github.com/aframevr/aframe/pull/1671
