### ISSUE TITLE
HLS m3u8 video stream does not work with a-videosphere Safari 9 and  iOS 9 mobile Safari

### ISSUE THREAD

**Issue by acylum** [aframevr/aframe#1021]
While .mp4 does work as a video source for a-videosphere,   HLS m3u8 video stream does not.

**Comment by abuisine** [comment]
+1

**Comment by liuxiaoyue** [comment]
+1

**Comment by dmarcos** [comment]
I believe this is a limitation of iOS not being able to copy pixels from a m3u8 stream to a texture. Have you seen any WebGL/Three.js demo rendering one? I haven't. I flag this as an iOS platform limitation and not an aframe bug. Please reopen if you find a working example of WebGL rendering a m3u8 stream.

**Comment by liuxiaoyue** [comment]
this is not  a limitation of iOS,i find a example that can play, but, Internal testing products，so i can't public sorry!

**Comment by yangfan1122** [comment]
I have the same problem, and I already spent 2 weeks. Should I just wait APPLE to change it?
