### ISSUE TITLE
Is it possible to support 3d 360 video with a-videosphere?

### ISSUE THREAD

**Issue by acylum** [aframevr/aframe#1022]
I would like to view 3D 360 video using a-videosphere.  Here is an example video (side-by-side).

http://hosting.360heros.com/3D360Video/3D360/Demo3-House/3DH-Take1-Side-By-Side-1920x960.mp4

**Comment by ngokevin** [comment]
There was a WIP at https://github.com/aframevr/aframe-core/pull/768 , will revisit later.

**Comment by ngokevin** [comment]
try out https://github.com/oscarmarinmiro/aframe-stereo-component by @oscarmarinmiro
