### ISSUE TITLE
Able to change environment

### ISSUE THREAD

**Issue by dlnkprs** [aframevr/aframe#1023]
Hi all, 

I want to tell a image-based story in VR, by using multiple images with sound following each other. It should be so that the user can "click" or gaze at an object to see a new image with new sounds (to achieve viewing from another perspective). One solution could be redirecting to a new page with new html, but I don't see a possibility to add those interactions. Is it possible to achieve this? 

Or is it possible to fade from one a-scene to another?

Thanks,
Dylan

**Comment by dmarcos** [comment]
When do you say an image what do you exactly mean? An image floating in the user's field of view? A completely different scene? For the former you can now show/hide entities based on user interactions. For the latter we will be soon supporting multiple ```a-scene``` elements on the same page.

**Comment by dlnkprs** [comment]
I'm sorry, it's the latter: different scenes. 
So it would be possible to gaze at an object and change (show/hide) entities like a-sky and a-entity with sound? That would create a new "scene".

**Comment by nylki** [comment]
You should be able to do somthing like:
```
<a-entity id="scene1">
<a-box> </a-box>
<a-model> </a-model>
// etc.
</a-entity>

<a-entity id="scene2" visible=false>
<a-image> </a-image>
<a-model> </a-model>
// etc.
</a-entity>
```

And then listen for click/gaze on an entity in `scene1`, where you could trigger an `a-animation` to fade the first scene out, and the second scene in (by animation the `visible` attribute on each scene).

**Comment by dlnkprs** [comment]
Alright, I tried something with the advice above. I currently have this (sorry for the markup, can't seem to get it right in github):
`<a-entity id="scene1" opacity="1">
        <a-sky src="https://farm8.staticflickr.com/7252/7019363969_a80a5d6acc_o_d.jpg" rotation="0 -90 0" ></a-sky>
        <a-entity visible="false" id="voiceover" geometry="primitive: plane" sound="src: radioactive.mp3; autoplay: true"></a-entity>
        <a-animation attribute="opacity" begin="2000" to="0"></a-animation>
      </a-entity>`

`     <a-entity id="scene2" opacity="0">
        <a-sky src="https://farm5.staticflickr.com/4144/5097827282_88e4de0f65_o_d.jpg" rotation="0 -90 0" ></a-sky>
        <a-entity visible="false" id="voiceover" geometry="primitive: plane" sound="src: stressed.mp3; autoplay: true"></a-entity>
        <a-animation attribute="opacity" begin="2000" to="1"></a-animation>
      </a-entity>`

It looks good and after two seconds scene1 changes to opacity of 0, but scene2 doesn't change from 0 to 1. So what I have is the entity from scene2 is being displayed all the time and nothing visually happens (in the code the opacity changes).

**Comment by nylki** [comment]
@dlnkprs btw. I just updated my code above to include cursor/click behaviour.

**Comment by dlnkprs** [comment]
@nylki thank you for the code provided. It works perfectly. Even with sound being played only when clicked: 

`<a-cube color="red" position="-2 0 0" onclick="start1()" sound="src: radioactiveshort.mp3; on: click"> </a-cube>`

However the fuse doesn't work. It's essential for the experience (not having to leave the environment to touch the screen on mobile). Is there a way to achieve the following effect? (recorded from JauntVR app)

![Image of Yaktocat](http://i.giphy.com/3o6gb181K4CMOUoLQI.gif)

**Comment by nylki** [comment]
@dlnkprs a-frame is still in heavy development, so it should work in the future, but I noticed some glitched with the fuse cursor as well.

You may want to try the dev branch though, I did a small demo for you with the *fuse* cursor:
http://codepen.io/anon/pen/pyzjPL

**Comment by ngokevin** [comment]
Yea, there's also http://codepen.io/team/mozvr/pen/RrxgwE for Cursor with Visual Feedback.

And yeah, there are many ways to do transitions. One way we did before is to create a black mask entity that fades in when transitioning, and you change the scene during the transition.

**Comment by ngokevin** [comment]
For now, use <a-entity camera> instead of <a-camera> to get fuse working

**Comment by coleholyoake** [comment]
Hi @dlnkprs, do you mind me asking how you did that animation around the button? I really like that experience! Cheers. (sorry I know it's off topic)

**Comment by ngokevin** [comment]
@coleholyoake Something similar to http://codepen.io/team/mozvr/pen/RrxgwE but you can animation the theta-length/geometry.thetaLength rather than the scale

**Comment by coleholyoake** [comment]
Cool thanks heaps @ngokevin
