### ISSUE TITLE
getAttribute('rotation') on cameras returns null unless look-controls is added

### ISSUE THREAD

**Issue by belen-albeza** [aframevr/aframe#1024]
If calling `getAttribute('rotation')` on a camera, it returns `null` unless the camera element has the attribute `look-controls`.

Example: https://jsfiddle.net/mqt8dtLL/

I don't know if this is expected behavior, but if it's not a bug at least it would be nice to have it documented.

**Comment by dmarcos** [comment]
look-controls changes the rotation of the camera by modyfing the rotation attribute. If the rotation attribute is not defined on the entity getAttribute will return null. This is how dom attributes behave. I consider this expected behavior

**Comment by ngokevin** [comment]
Actually the expected behavior is `{ x: 0, y: 0, z: 0 }`

But this has since been fixed on the dev branch for a-camera

**Comment by belen-albeza** [comment]
Thanks @ngokevin 

One question, I'm tinkering with A-frame and reporting the bugs I'm seeing. Do you prefer me reporting bugs over the latest release, or over the `dev` branch? 

Cheers!

**Comment by ngokevin** [comment]
You can report either, and then I can help confirm whether it has been fixed or not. I think at the moment, I prefer people use the `dev` branch as it feels more stable than master.
