### ISSUE TITLE
Add ability to apply mixins to template instances

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#103]
Enables devs to apply mixins with template instances. We foresee that it will be most commonly for materials (as is true of mixins in general).

In the following example, both cubes should be the same shade of blue:

```html
<vr-assets>
    <vr-mixin id="wall" color="#0c99d5"></vr-mixin>
</vr-assets>
<vr-scene>
    <vr-cube mixin="wall" width="2" depth="2" height="2" position="0 0 0"></vr-cube>
    <vr-cube color="#0c99d5" width="2" depth="2" height="2" position="3 0 0"></vr-cube>
</vr-scene>
```

**Comment by ngokevin** [comment]
Templates in their current form are no longer on the roadmap.
