### ISSUE TITLE
Investigate VREffect regression in three.js

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1030]
https://github.com/ngokevin/three-dev/blob/master/examples/js/effects/VREffect.js is on [`d4cdb01`](https://github.com/mrdoob/three-dev/commit/d4cdb01)
https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js is on [`85c4922`](https://github.com/mrdoob/three-dev/commit/85c4922)

https://github.com/mrdoob/three.js/blob/65d161e/examples/js/effects/VREffect.js is bad
https://github.com/mrdoob/three.js/blob/a17ea05/examples/js/effects/VREffect.js is good

See screenshots:

![screenshot 2016-02-25 22 47 17](https://cloud.githubusercontent.com/assets/203725/13345395/5cfadd6c-dc13-11e5-87e3-efcb746fa0a8.png)
![screenshot 2016-02-25 22 59 57](https://cloud.githubusercontent.com/assets/203725/13345409/751dd57a-dc13-11e5-9b2f-9f0f35098e24.png)

@dmarcos / @ngokevin: would you be able to look at this soon? I assume this requires filing an issue against three.js. I discovered this in testing @toji's changes to three.js for the new WebVR API.

**Comment by ngokevin** [comment]
Did you bump your three.js?

**Comment by ngokevin** [comment]
I'm going to take a gamble and say that your local three.js was behind. Reopen if I'm wrong :)

<img width="1434" alt="screen shot 2016-02-25 at 11 38 27 pm" src="https://cloud.githubusercontent.com/assets/674727/13346127/fc68caa8-dc18-11e5-83e5-10dfe6091d0e.png">

**Comment by cvan** [comment]
> I'm going to take a gamble and say that your local three.js was behind. Reopen if I'm wrong :)

ah, okay that changed `VREffect` actually depended on changes made in r74. didn't realise that. just pointed to `three@r74` instead of `three-dev` in `aframe-core` and everything works. thanks! :smile:
