### ISSUE TITLE
In dev branch, animations are always triggered after loading

### ISSUE THREAD

**Issue by belen-albeza** [aframevr/aframe#1032]
Currently in `dev` branch (at least in the built version under `dist`) animations are always triggered when the scene loads, regardless of `begin` attribute. After one run, the animation behaves as expected (i.e. triggered only by the event in `begin`).

This is not happening in the latest official release.

Example of animation:

```
<a-animation attribute="scale" begin="play" dur="500" direction="alternate" repeat="1" from="1 1 1" to="1 2 1"></a-animation>
```

Live example: https://jsfiddle.net/Lc42h36f/1/

**Comment by ngokevin** [comment]
Can you try with an event that is not `play`? I think entities will emit `play` when they are attached.

**Comment by ngokevin** [comment]
Confirmed, don't use the `play` event name. This will be documented later. https://jsfiddle.net/yL0cozoh/
