### ISSUE TITLE
add `end` attribute (similar to `begin`) to a-animation to specify when to stop animation

### ISSUE THREAD

**Issue by nylki** [aframevr/aframe#1036]
Right now, there can be conflicting animations running. Imagine you have two animations:
- a animation that triggers on `click` that has a duration of 4 seconds and scales an element up
- another animation that triggers on `mouseleave` and scales that element back to its original size in 1 second

Once the user clicks on the element, the element animates, eg. 2 seconds, but then the user decides to cancel the zoom/scale by moving the cursor out. The second animation then triggers and scales the element back to the initial size. So far so good.

However, the first animation is still running in the background! And will eventually fullfil its animation by setting the element to the increased scale, Which results in a strange flicker because the other element scales down. etc.

I propose automatically cancel sibling animations that modify the same attribute.
Additionally, there could be a `cancel-other` attribute to `animation` that simply cancels other animations in the same scope.

**Comment by ngokevin** [comment]
Probably an `end` attribute? Similar to `begin`

**Comment by msimpson** [comment]
I would imagine the `end` attribute needs to support multiple events, as well. For instance, given #857, this type of scenario will inevitably surface:

```
<a-animation
    attribute="opacity" begin="mouseenter" to="1" dur="1000"
    end="mouseleave, custom-stop-event, ...">
</a-animation>
<a-animation attribute="opacity" begin="mouseleave" to=".25" dur="1000"></a-animation>
```
