### ISSUE TITLE
Support 'multipart/x-mixed-replace' mimetype ( video feeds )

### ISSUE THREAD

**Issue by kvarga** [aframevr/aframe#1037]
It would be great if videos could be streamed to aframe instead of the entire file. Is this possible?

**Comment by ngokevin** [comment]
Have not experimented with streaming. It would be nice if someone could give it a shot and write an A-Frame component to stream a video feed into a texture.

**Comment by t-io** [comment]
+1

**Comment by ngokevin** [comment]
Would leave this for a third-party A-Frame component + JS library
