### ISSUE TITLE
add array property type

### ISSUE THREAD

**Issue by JoshGalvin** [aframevr/aframe#1038]
It would be nice to be able to register custom property types. This would enable things like 

```javascript
  schema: {
      enabled: { default: true },
      templates: { type: 'array', default: [] },
      timing: { type: 'range', default: [0, 50] }
    },
```

**Comment by JoshGalvin** [comment]
Having to do ...

```javascript
    schema: {
      enabled: { default: true },
      templates: { default: '' },
      timing: { default: '0 50' }
    },

    update() {
      this.data.templatesReal = this.data.el.split(' ');
      this.data.timingReal = this.data.el.split(' ');
    },
```

**Comment by ngokevin** [comment]
You can define custom `parse` and `stringify` methods to effectively create one-off types. That should work well: http://codepen.io/team/mozvr/pen/yeEQNG

I previously thought of it at https://github.com/aframevr/aframe/issues/881, but we agreed that it would get messy if there were lots of components registering types into the global space, it'd be hard to tell what was a built-in type and what was third-party. Let me know what you think.

**Comment by JoshGalvin** [comment]
Thanks! Please consider adding an array default type though.

**Comment by ngokevin** [comment]
Definitely, I had that in mind, never filed it.

**Comment by ngokevin** [comment]
Feel free to PR that, should be simple. Function to split on comma, function to join with comma, then a small test.

**Comment by JoshGalvin** [comment]
I'll get that together tonight or tomorrow. Thanks again.

**Comment by ngokevin** [comment]
Thanks!
