### ISSUE TITLE
Webpack build errors when requiring Aframe

### ISSUE THREAD

**Issue by shea-hawkins** [aframevr/aframe#1040]
Hello!

There are build errors when requiring aframe in a JS file after installing via npm (for use with something like aframe-react). Lines 10-14 in 'aframe-core\lib\three.js' have requirements for aframe's local npm installation of three-dev, pointing to '../node_modules/three-dev'. However, when aframe is installed via npm, three-dev is installed in the project's node_modules, causing the below errors:

ERROR in ./~/aframe-core/lib/three.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/three-dev/examples/js/loaders/OBJLoader in C:\Personal Items\Projects\episode-one\node_modules\aframe-core\lib
 @ ./~/aframe-core/lib/three.js 10:0-66

ERROR in ./~/aframe-core/lib/three.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/three-dev/examples/js/loaders/ColladaLoader in C:\Personal Items\Projects\episode-one\node_modules\aframe-core\lib
 @ ./~/aframe-core/lib/three.js 11:0-70

ERROR in ./~/aframe-core/lib/three.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/three-dev/examples/js/controls/VRControls in C:\Personal Items\Projects\episode-one\node_modules\aframe-core\lib
 @ ./~/aframe-core/lib/three.js 13:0-68

ERROR in ./~/aframe-core/lib/three.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/three-dev/examples/js/effects/VREffect in C:\Personal Items\Projects\episode-one\node_modules\aframe-core\lib
 @ ./~/aframe-core/lib/three.js 14:0-65

Removing the '../node_modules' from the requirement works for my case. Will this still allow the project to build when installed without npm?

**Comment by ngokevin** [comment]
On dev branch of A-Frame `aframevr/aframe#dev`, the bundle will be prebuilt so no build step will be required.
