### ISSUE TITLE
requiring from NPM with webpack gives warning "This seems to be a pre-built javascript file "

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1041]

**Comment by csampson** [comment]
Seeing the same thing:

```
WARNING in ./~/aframe/dist/aframe.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/aframe/dist/aframe.js 1:479-486
```

**Comment by michaltakac** [comment]
Fix this by adding this into your webpack config under `module`:

```javascript
module: {
    noParse: [
      /node_modules\/aframe\/dist\/aframe.js/, // for aframe from NPM
      /node_modules\/cannon\/build\/cannon.js/, // for aframe-extras from NPM
    ],
    loaders: [
    // ... your loaders here ...
    ]
}
```

**Comment by ngokevin** [comment]
Thanks! I created a Stackoverflow question so hopefully this can get found later: http://stackoverflow.com/questions/39768099/how-to-ignore-seems-to-be-a-pre-built-javascript-file-try-to-require-the-orig/39768100#39768100

**Comment by iMerica** [comment]
For those still seeing this error: Using the full absolute file path to the file `aframe-master.js` in your node_modules should work. For example:

```
noParse: [
    '/node_modules/aframe/dist/aframe-master.js',
]
```

Tested on:
- "aframe": "^0.5.0"
- "aframe-react": "^4.2.4"
- "webpack": "^1.13.1"
