### ISSUE TITLE
Add stereoscopic pano example

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1047]
Per http://threejs.org/examples/#webvr_stereo_pano

**Comment by ngokevin** [comment]
Do we want one in the core repo if the component that enables this is not? https://github.com/oscarmarinmiro/aframe-stereo-component

**Comment by dmarcos** [comment]
This is well served by 3rd party components. Stereo panos are not very common in the wild. We can revisit this later if it there's more demand.
