### ISSUE TITLE
Let vec3 parser accept arrays

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1048]
https://github.com/aframevr/aframe/blob/dev/src/utils/coordinates.js#L5

`setAttribute('position', [1, 2, 3]);`

**Comment by masom** [comment]
Seems to work on latest dev.

```
    let position = new THREE.Vector3(0, 0, 0);
    this.el.setAttribute('position', position);
```

**Comment by dmarcos** [comment]
It's just a coincidence:

You can do  ```this.el.setAttribute('position', { x: 1, y: - 2;  z: 6 });```

It happens that ```three.js``` stores the coordinate values on the x, y and z attributes as well.

**Comment by ngokevin** [comment]
Ah, okay sweet. Someone was saying it didn't work with Vector3s.

Still need to get it to work with arrays.

**Comment by masom** [comment]
Cool, I'll add support for arrays.

**Comment by dmarcos** [comment]
What's the value of adding support for arrays? An array has implicit information on what position corresponds to each coordinate. I pretty much prefer to always see { x: 1, y: 2, z: 5 }. I think arrays don't add much and potentially introduce bugs.

**Comment by masom** [comment]
:+1:

**Comment by ngokevin** [comment]
```Vector3``` carries implicit information on what position corresponds to each coordinate...

**Comment by ngokevin** [comment]
The benefit is that it's a more compact data structure for something that's going to be typed over and over. Much easier to type since `{x: 0, y: 1, z: 3}` uses keys from all over the keyboard back-and-forth.

**Comment by dmarcos** [comment]
No. it doesn't. The coordinates are labeled with x, y, z. In an array the correspondence is positional and totally implicit. You can easily mess up the indices and pass the wrong thing.

**Comment by dmarcos** [comment]
Typing is not something you want to optimize for on API design:

1. Code is write once ready many. You have to optimize for legibility and understanding and reduce cognitive load.
2. Autcompletion on modern IDE's makes typing a non issue.

**Comment by RangerMauve** [comment]
As a dev who's been doing some hobby game creation, I'm pretty used to indexes in arrays of three items being used for `[x, y, z]` co-ordinates, so I it'd be useful; to have.

**Comment by ngokevin** [comment]
Though when you instantiate a Vector3, you are passing x, y, z in order. There's no difference in using an array shorthand and the precedence that three.js has made on this:

```new THREE.Vector3(1, 5, 7)```

```new THREE.Vector3.apply(this, [1, 5, 7])```

**Comment by dmarcos** [comment]
That you are used to it doesn't mean is a good design decision. Also a-frame targets an audience that it's not familiarized with graphics / game development.

**Comment by meta-meta** [comment]
In math too, you have a Euclidean vector defined by the order of components. It's never [z, y, x]. The order is pretty much consistent across the board.

**Comment by dmarcos** [comment]
Math is not a good example of consistent and terse notation either.

**Comment by ngokevin** [comment]
three.js does it, and it's [been requested](https://github.com/ngokevin/aframe-react/issues/12). Having built lots of scenes and components, you can feel having to create XYZ objects over and over gets irritating.

There's no potential for bugs. The only case is if a developer does `setAttribute('position', [1, 2, 3])`, it gets converted to an XYZ object. It's completely external.

**Comment by dmarcos** [comment]
I really don't think an array adds much value. It's just more code to maintain and extra risk for bugs when managing your local variables and passing them around. There's less chance to make a mistake when you are forced to be explicit { x: -1, y: 0, z: -4 }

**Comment by ngokevin** [comment]
Even in A-Frame, we are already making it implicit ```position="0 1 2"```...

**Comment by ngokevin** [comment]
It does add value. Lots of developers that are actually using A-Frame (including me) say it would improve our workflows.

**Comment by ngokevin** [comment]
The XYZ order already implicit in A-Frame, three.js, WebGL, math, our heads. There's no need to make this explicit.

**Comment by dmarcos** [comment]
```position="0 1 2"``` is just for backwards compatibility to be able to pass strings to ```setAttribute```. When using the DOM inspector there's no option. I would get rid of the string notation if I could.

**Comment by ngokevin** [comment]
It's not just for backwards compatibility, that's the API design when people are writing scenes in HTML.

**Comment by dmarcos** [comment]
Still backwards compatibility. You cannot write HTML attributes as objects.

**Comment by dmarcos** [comment]
When writing code is always better to be explicit. Have you never messed up with the order of the arguments in a function? This is why I like objective C and its labeled parameters.

**Comment by ngokevin** [comment]
Sure we can, it could have been ```position="x: 5; y: 10; z:15"```, but we didn't because it's annoying to define something so commonly accepted explicitly.

**Comment by ngokevin** [comment]
That rule doesn't apply in this caseIt's not always better to be explicit if it doesn't make sense to. There's precedence in A-Frame. The way we define single-property schemas is very implicit.

**Comment by dmarcos** [comment]
Typing on the DOM inspector is a real pain so it's sensible to have a more compact notation. Also when manipulating the DOM on a text editor and DOM inspector you're writing the values directly. There's no chance that you have an array manipulated somewhere else that you have to keep track the origin and state.

**Comment by ngokevin** [comment]
How can we address these points in favor of an array?

- XYZ order is universally accepted in A-Frame, Unity three.js, WebGL, shaders, game development, math, our heads.
- Many developers are saying their workflows would improve if they could pass an array. 

An umbrella argument of "explicit is better than implicit" isn't really a strong enough argument either. There's already precedence of favoring implicitness for ergonomics in A-Frame.

**Comment by dmarcos** [comment]
Because we're forced to by legacy systems, mainly the DOM inspector and the string nature of DOM attributes. It's not a decision we would make without those constrains. In JS world those limitations don't apply.

**Comment by dmarcos** [comment]
I still have to understand why arrays improve workflows more than the risks they introduce. There could be some marginal value on but it doesn't pass the the cost / benefit test.

**Comment by ngokevin** [comment]
I'm not really worried about the DOM inspector or DOM. I just want to be consistent with the fact that XYZ order is already universally accepted as arguments in universally all of math and development.

I'm willing to let it go because you're right, it's fairly marginal. But it would be an enhancement nonetheless

**Comment by ngokevin** [comment]
On the other hand, I can imagine people writing all sorts of helpers to convert XYZ objects to arrays within their projects, which would be a little riskier than ensuring + testing it ourselves.

**Comment by ngokevin** [comment]
I'm going to leave this open as *needs answers* since it's not quite resolved. But won't take action yet.

**Comment by dmarcos** [comment]
Is this our first public flame war? I guess we're a real open source project now :)

**Comment by ngokevin** [comment]
Yeah, it's like our [own mini Rust int/uint](https://internals.rust-lang.org/t/restarting-the-int-uint-discussion/1131) :)

**Comment by ngokevin** [comment]
For now, you can do in your projects:

```js
function v (x, y, z) {
  return {x: x, y: y, z: z};
}
setAttribute('position', v(1, 2, 3));
```

**Comment by ngokevin** [comment]
I'll close this for now. One way to do things keeps things simpler. The helper is above pretty simple.
