### ISSUE TITLE
[meta] fewer github labels

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1051]
The amount we have is a bit overwhelming, and we have so many labels, that they lose their usefulness due to the noise. Ones that I pay attention to (having scoured through issues tons of times) and I think we should keep from most important to least:

PRs:

- needs review
- needs changes
- needs rebase
- needs answers
- work in progress

Issues:

- easy
- feature request
- perf
- regression
- bug

**Comment by cvan** [comment]
go for it. whichever works best for you. I took inspiration from React's labels.

**Comment by ngokevin** [comment]
only i'm allowed to take inspiration from react :tongue:

**Comment by ngokevin** [comment]
down to 15, will see how we use labels before removing/adding more

**Comment by dmarcos** [comment]
The labels above look good
