### ISSUE TITLE
Reports of Wakelock not working on Android device

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1057]
Reported on A-Frame Slack in `#issues` room by @leemark.

> I am experiencing an issue where my screen times out/goes to sleep in android chrome, in VR mode.
> android 5.1, moto g lte (motorola xt1045), chrome 48.0.2564.95

Could be related to 7d1ab4ca

**Comment by ngokevin** [comment]
This was fixed on the dev branch: https://github.com/aframevr/aframe/issues/875

0.1.x doesn't have this fix so people will experience it

**Comment by cvan** [comment]
ah, sweet - thanks. can you tell @ml in Slack?

**Comment by leemark** [comment]
:thumbsup: Thank you!

**Comment by scottlittle** [comment]
Wakelock is not working for me either: Nexus 5X, Android 6.0.1, Chrome 58.3029.21, A-Frame 0.5.0
