### ISSUE TITLE
Scene components listed in `defaultComponents` get initialised twice in Chrome (or with native Custom Elements support?)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1059]
When a component is defined as a key in `defaultComponents`, the component's `init` method gets called twice.

Reproduced with `<a-scene>` for `canvas`, `keyboard-shortcuts`, and `vr-mode-ui`.

**Comment by ngokevin** [comment]
You sure? Only getting it once the anime UI

<img width="1306" alt="screen shot 2016-03-01 at 6 51 10 pm" src="https://cloud.githubusercontent.com/assets/674727/13449275/a2a299e4-dfde-11e5-8703-5e05ee44a772.png">

<img width="678" alt="screen shot 2016-03-01 at 6 51 15 pm" src="https://cloud.githubusercontent.com/assets/674727/13449274/a2a279aa-dfde-11e5-8118-cfc494d02b09.png">

**Comment by cvan** [comment]
sorry, I didn't mention. reproducible in Chrome + new Chromium builds only:

<img width="727" alt="screenshot 2016-03-01 19 11 13" src="https://cloud.githubusercontent.com/assets/203725/13449542/59feea32-dfe1-11e5-8db6-55ee94272146.png">

**Comment by ngokevin** [comment]
OK I see

**Comment by mkungla** [comment]
**I bumped to same problem with 0.7.0.**

Component init is called twice when primitive has `component` under `defaultComponents` and mapping keys to same `component`
