### ISSUE TITLE
stare-controls (rotate around look-at object with camera)

### ISSUE THREAD

**Issue by subsumo** [aframevr/aframe#1068]
Calculate distance to object & move camera around object with fixed distance

**Comment by subsumo** [comment]
Apologies - forgot to label (feature request)

**Comment by ngokevin** [comment]
Thanks for requesting. This doesn't seem like it will be a core feature, but you can write your own A-Frame component to do anything you want: http://ngokevin.com/blog/aframe-component/

Or sounds like you might be able to use an animation and rotate the camera in a circle.

**Comment by donmccurdy** [comment]
@subsumo if you wanted to take a shot at this, a small component wrapping THREE.js's [Orbit Controls](https://github.com/mattdesl/three-orbit-controls) might be the way to go.

**Comment by subsumo** [comment]
Thanks guys, I'm on it
