### ISSUE TITLE
npm install aframe installs package with not-found problems in index.js

### ISSUE THREAD

**Issue by alexcheninfo** [aframevr/aframe#1070]
I just did `npm install aframe` and I get the following errors:

```
ERROR in ./~/aframe/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./package in E:\alex\istaging-viewer\node_modules\aframe
 @ ./~/aframe/index.js 3:10-30

ERROR in ./~/aframe/~/aframe-core/src/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../package in E:\alex\istaging-viewer\node_modules\aframe\node_modules\aframe-core\src
 @ ./~/aframe/~/aframe-core/src/index.js 16:10-31
```

The error is right there isn't any `./package` folder. As for she other error, I'm not sure what's going on.

(As you can see in this screenshot: http://stackoverflow.com/questions/35763019/why-is-that-i-can-import-one-npm-package-and-not-the-other-webpack-setup the folder doesn't exist).

Do I have to do something else aside of `npm install aframe`?

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe/issues/1069
