### ISSUE TITLE
a-frame logo example doesn't look good in VR mode

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1074]
Due to the camera FOV.

**Comment by cvan** [comment]
@caseyyee opened a PR to try to tackle this back in December: https://github.com/aframevr/aframe/pull/286

**Comment by ngokevin** [comment]
Going to WONTFIX as we won't be showing this on the homepage anymore (instead use the MagicaVoxel FPS one). It was good while it lasted!
