### ISSUE TITLE
add uniform type for tracking an element's position (e.g., camera for eye)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1085]

**Comment by dmarcos** [comment]
Maybe also viewport size like shader toy. Should those be new schema types?

**Comment by ngokevin** [comment]
Let's create some shaders and see what's useful :)

**Comment by ngokevin** [comment]
Yeah I think these would be built-in schema types.

**Comment by dmarcos** [comment]
A shader we need is a neat animation for the loader spinner. The loader should not use any assets ( textures, models, sounds...) so it loads super quick. It has to be self contained within the aframe library.

**Comment by ngokevin** [comment]
Would be good for placeholder for loading models.

Don't think we can use shaders for the spinner blocking scene load. Because that depends on rendering, and we are blocking rendering until assets load. A simple image or data URI would do, it could also function as the "click to play" placeholder.

**Comment by dmarcos** [comment]
We can create a ```loader```  ```scene component` that creates it's own renderer and render loop independent to the scene one.

**Comment by ngokevin** [comment]
Yeah, I guess it is good to have the loading screens support VR too.

**Comment by dmarcos** [comment]
@ngokevin anything we want to still do here?
