### ISSUE TITLE
test/investigate asset blocking not working

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1089]
@mayognaise says her assets loaded in 9s, but it waited until the timeout of 1m40s to start render.

**Comment by mayognaise** [comment]
Thank you!

**Comment by dmarcos** [comment]
I've pushed the panoexplorer example to gh-pages with a timeout of 100s and everything works as expected http://swimminglessonsformodernlife.com/aframe/examples/test-panoexplorer/
I

@mayognaise Do you have a simple test case that reproduces the problem?

**Comment by ngokevin** [comment]
I played with some examples, increasing and lowering the timeout. Things work as expected. Going to clear it from a blocker, but will investigate more once we get a reproducing test case.

**Comment by ngokevin** [comment]
Not producible
