### ISSUE TITLE
Investigate updating component props via DOM inspector parsing twice.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1091]
![double](https://cloud.githubusercontent.com/assets/674727/13542690/5ac3f842-e219-11e5-8afc-f573cd38e0a7.gif)

**Comment by dmarcos** [comment]
Is this still an issue?

**Comment by ngokevin** [comment]
I think so. It's not a big deal because we're trying to make DOM Inspector obsolete, but it could reveal a hidden bug.

<img width="536" alt="screen shot 2016-08-03 at 6 10 15 pm" src="https://cloud.githubusercontent.com/assets/674727/17387113/8ebebe8a-59a5-11e6-8a86-220776f0b7ce.png">

**Comment by darkwing** [comment]
I just tried this out on the same example and only received one message.  I tried modifying the `material` on an `a-mixin` and it triggered multiple times, but we probably expect it to trigger on everything using said mixin.

**Comment by ngokevin** [comment]
^
