### ISSUE TITLE
Can't disable video loop

### ISSUE THREAD

**Issue by gzholdak** [aframevr/aframe#1105]
There's no option to disable video loop. Please add `loop="false"`.

**Comment by ngokevin** [comment]
If you are inlining the URL to the material component (as the ```<a-video/sphere>``` elements) do, then the video element created will loop by default. I will document this.

It is recommended to provide your own video element:

```html
<a-assets>
  <video id="my-video" src="vid.mp4">
</a-assets>

<a-video src="#my-video>
```

**Comment by ngokevin** [comment]
Added to doc list at https://github.com/aframevr/aframe/issues/1072
