### ISSUE TITLE
Have a better way of stringifying selector/selectorAll property types.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1113]
If we do ```el.setAttribute('look-at', cameraElement)```, how do we reflect that in the DOM?

Currently, we check if there's an ID and use that. Can we come up with a unique identifier for elements? Maybe the element's ```object3D``` uuid.

**Comment by dmarcos** [comment]
I don't think seeing the uuid is very useful. Other options:
1. Assign an id to the element if there's not one already.
2. Show nothing on the DOM inspector if there's no id.

**Comment by ngokevin** [comment]
That'd be interesting, auto-assigning IDs. Maybe ```data-aframe-id="randomly-generated-hash"```  and then for selector props we do ```[data-aframe-id="randomly-generated-hash"]``` as the reflected selector

**Comment by ngokevin** [comment]
Stringifying is no longer important unless in debug mode. And we have the Inspector.
