### ISSUE TITLE
Templates that just wrap elements need to appear in the document before `<vr-scene>`

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#112]
I was trying to do create a template element to just simply wrap `<vr-object>` because I don't like the name:

```html
<!doctype html>
<html>
  …
  <body>
    <vr-scene>
      …
      <vr-pano-nav>
        <vr-pano-link></vr-pano-link>
      </vr-pano-nav>
    </vr-scene>
    <template is="vr-template" element="vr-pano-link" url="https://mozvr.github.io/aframe-core/examples/panoexplorer/images/city.jpg" type="link">
      <vr-object geometry="primitive: plane; width: 1.0; height: 1.0" material="url: ${url}"></vr-object>
    </template>
    <template is="vr-template" element="vr-pano-nav">
    </template>
  </body>
</html>
```

But that didn't work:

<img width="1405" alt="screenshot 2015-10-29 02 07 22" src="https://cloud.githubusercontent.com/assets/203725/10814260/148fdcc4-7de2-11e5-97f2-e91dc1f011fa.png">

Some weird stuff is happening with the `nodeready` events I think. But, moving the <template> _above_ the `<vr-scene>` did the trick.

Need to investigate and fix this.

**Comment by ngokevin** [comment]
Templates in their current form are no longer on the roadmap.
