### ISSUE TITLE
selectorAll property type should convert nodeList to array

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1129]
Follow up to @legendtang's https://github.com/aframevr/aframe/pull/1099

**Comment by cvan** [comment]
I know the naming is unrelated, but perhaps could call it just `query` à la `xtag.query`:

https://x-tag.github.io/

![image](https://cloud.githubusercontent.com/assets/203725/13662508/e4c1ce54-e64f-11e5-84c3-5bd005169f49.png)

**Comment by legendtang** [comment]
@cvan But `x-tag` requires additional polyfills for mainstream browsers for now. Maybe too early to use this name?

**Comment by cvan** [comment]
@cvan But x-tag requires additional polyfills for mainstream browsers for now. Maybe too early to use this name?

I was not suggesting to use X-Tag, just using its method names as inspiration/prior art. And we are already using a polyfill for Custom Elements: https://github.com/WebReflection/document-register-element - I've heard bugs with the polyfill, and we have an issue (#567) on file to investigate if the more "popular" [WebComponentsJS Custom Elements polyfill](https://github.com/webcomponents/webcomponentsjs/tree/master/src/CustomElements) fixes the bugs/inconsistencies we've seen between native and polyfilled.

**Comment by ngokevin** [comment]
Hard to tell whether you are selecting one element or multiple with ```query```. And I think selector/selectorAll is easier to get what it means. (query)selector/selectorAll are in the browser and probably make a stronger for "prior art".

**Comment by cvan** [comment]
yeah, I think that's a good point. though jQuery seems to handle this fine - `$()` vs `$()[0]`. I've always liked `$` vs `$$`. but, the naming you have is fine.

**Comment by ngokevin** [comment]
Yeh. This is for property types though, not for actually running queries.
