### ISSUE TITLE
Transparent textures now have white background with THREE.js dev

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1130]
There may be no cause for alarm, and it's likely just a THREE.js regression I hope. But I noticed this issue testing THREE.js' [`dev`](https://github.com/mrdoob/three.js/tree/dev) branch, so I thought I'd file.
### on THREE.js [`r74`](https://github.com/mrdoob/three.js/tree/r74)

<img width="1440" alt="screenshot 2016-03-09 23 51 38" src="https://cloud.githubusercontent.com/assets/203725/13662764/c663976a-e651-11e5-8af7-a9284fb2404a.png">
### on THREE.js [`dev`](https://github.com/mrdoob/three.js/tree/dev)

<img width="1435" alt="screenshot 2016-03-09 23 39 52" src="https://cloud.githubusercontent.com/assets/203725/13662552/2e91e0b4-e650-11e5-8c41-f6f00161c309.png">

**Comment by cvan** [comment]
I noticed this with three.js examples too, not just our scenes. Perhaps this is filed as https://github.com/mrdoob/three.js/issues/8259 (PR https://github.com/mrdoob/three.js/pull/8279/files)?

**Comment by ngokevin** [comment]
We're on r83 with no issues now.
