### ISSUE TITLE
Inline videos do not load in experimental WebVR Chromium builds

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1133]
Try loading http://localhost:9000/examples/primitives-video/ in the [experimental WebVR Chromium builds](https://drive.google.com/folderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ&usp=sharing#list).

Doesn't work on older deprecated Mac WebVR Chromium builds neither. Works fine in Chrome stable though.

**Comment by ngokevin** [comment]
Dupe https://github.com/aframevr/aframe/issues/917
