### ISSUE TITLE
0.2.0+ docs megathread

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1146]
Keep track of things we should document further. Megathread so we don't have individual issues for small parts or typos we should document or fix.

- [ ] animation + cursor

**Comment by K4orta** [comment]
I think there is a typo in the Animations documentation for the fading cube example.

Currently:
```html
<a-entity id="fading-cube" geometry="primitive: box" material="opacity: 1">
  <a-animation attribute="material.opacity" begin="fade" to="2 2 2"></a-animation>
</a-entity>
```

The `to="2 2 2"` should be `to="0"` or `to="0.0"` I think?

I can throw up a PR to fix it.

**Comment by ngokevin** [comment]
Yeah can you pr? Thanks!

**Comment by ngokevin** [comment]
Don't think we need to an issue for this. If you find something, PR it! :)
