### ISSUE TITLE
Asset loading event fires twice for one asset

### ISSUE THREAD

**Issue by autonome** [aframevr/aframe#1154]
Description: I added a loading event listener on <a-assets> per @ngokevin's advice, and received two events even though I had one asset.

Also, we should clearly define whether adding a listener on a-assets sends a notification for each loaded asset or a single one once all assets are loaded.

- A-Frame Version: master
- Platform/Device: Mac OS X, Firefox Dev Edition 46

Code:

``<a-assets>
  <a-asset-item id="n-obj" src="nefertiti.obj"></a-asset-item>
</a-assets>``

``<script>
  document.querySelector('a-assets').addEventListener('loaded', function() {
    console.log('assets loaded')
  });
</script>``

**Comment by ngokevin** [comment]
Expected: one single event once all assets loaded

**Comment by autonome** [comment]
Btw, I changed networks from slow (office) to fast (home) and I cannot
reproduce this in a fast network. Even more interesting, I'm loading the
asset from the localhost webserver.

**Comment by ngokevin** [comment]
Thanks, this is fixed: https://github.com/aframevr/aframe/commit/5728902d29cc73b12269f41d5417ae92ab63ae77

**Comment by autonome** [comment]
Thanks :D
