### ISSUE TITLE
mixins + materials with different shader do not work

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1163]
Description: Complains about shader being undefined. http://codepen.io/team/mozvr/pen/jqMGEq?editors=100 or if I check out the most recent dist, there is no error, but it doesn't work

- A-Frame Version: master
- Platform/Device: All

**Comment by dmarcos** [comment]
This PR fixes the issue https://github.com/aframevr/aframe/pull/1159

**Comment by ngokevin** [comment]
This is with your PR, I checked it out.

**Comment by ngokevin** [comment]
One issue is single-property shader schemas. Need to:

- Allow schemaless shader (e.g., ```schema: {}```) if it doesn't take any properties. It is being treated as single-prop schema.

**Comment by ngokevin** [comment]
If shader does not have schema ({} or empty), it will be treated as single-prop schema. Then I was having issues where `material="shader: flat"` was getting parsed to a string rather than object. Then it was unable to find the shader.
