### ISSUE TITLE
Original event does not propagate to nodes

### ISSUE THREAD

**Issue by bnolan** [aframevr/aframe#1165]
It'd be great if the [original event](https://developer.mozilla.org/en/docs/Web/Events/click) (with shiftKey, screenX, screenY) was passed to the node that registers for `onClick` as an `originalEvent` property. I tried adding this to `cursor.js` but thought you might have a better idea of how to do this?

**Comment by bnolan** [comment]
Something like:

      document.querySelector('a-entity').addEventListener('click', (e) => {
        alert(e.originalEvent.shiftKey);
      });

To detect when someone shift-clicks on an element, or uses the second mouse button, etc.

**Comment by ngokevin** [comment]
You can listen to window click in parallel, the entity's "click" can mean different things, but not necessarily associated to a hardware mouse
