### ISSUE TITLE
animation.stop() should consider fill value

### ISSUE THREAD

**Issue by IagoLast** [aframevr/aframe#1168]
With the current code when an animation is removed from a component the animated property is set to the initial value.

This behavior could not be the desired one in some cases, i.e: when you want to stop an animation before it ends keeping the property value. Maybe I´m wrong and there is a better way for doing this, let me know in that case.

See https://github.com/IagoLast/totem for a working example when this feature could be used.
(Note that totem uses a modified a-frame version where the `setInitialValue` line was commented.)

**Comment by dmarcos** [comment]
@IagoLast  Does setting fill="backwards" / fill="forwards" do what you need? 

https://aframe.io/docs/core/animation.html#Fill

**Comment by ngokevin** [comment]
That won't do. We have code that always resets to initial value on ```.stop()```.

**Comment by dmarcos** [comment]
Maybe ```stop``` should consider the fill value.

**Comment by IagoLast** [comment]
@dmarcos yep, for me this would be the expected behavior
