### ISSUE TITLE
a-frame runs poorly on high-end android devices

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1171]
Description: Slow, laggy for A-Frame. Pure three.js (circa. r70) is fine.

- A-Frame Version: 0.1.3
- Platform/Device: Android mobile (S6, Note 4, Note 5)

**Comment by gzholdak** [comment]
I'm experiencing the same issue on iPhone 5.

**Comment by ngokevin** [comment]
Bad performance on iPhone 5 is expected as it runs nearly 4-year old hardware. We haven't come up with an official list of supported devices yet, but iPhone 5 is too old to become on that list (especially since the screen would be too small for VR).

**Comment by gzholdak** [comment]
@ngokevin, fair enough.

**Comment by bryik** [comment]
How slow is "laggy"? <30 FPS?

**Comment by dmarcos** [comment]
What demo exaclty? content with video? Scenes with lots of geometry? Lots of different textures? This issue is not actionable.

**Comment by ngokevin** [comment]
Every demo. Like 15 FPS. Is that actionable?

**Comment by ngokevin** [comment]
I will get more information later, but it's pretty widespread and easily noticable.

**Comment by bryik** [comment]
@ngokevin hmm, I get >30 FPS with Anime UI on my HTC One M8 using Chrome. However, I did notice instability (browser crashes) and stuttering with Firefox.

**Comment by ngokevin** [comment]
@bryik thanks for testing, glad to know it's not on all Android. Don't think this is actionable, @dmarcos pointed out Android accelerometer hardware might not provide data very quickly.
