### ISSUE TITLE
VR mode not working on dev build (mozvr/aframe)

### ISSUE THREAD

**Issue by alexcheninfo** [aframevr/aframe#1172]
Here's a working example (it's using the version of aframe installed with `npm install mozvr/aframe#dev`:

https://desolate-island-90618.herokuapp.com/#!/

It has the same structure as the official Panorama example: https://aframe.io/aframe/examples/template-sky/

But if you click the VR button while on a phone, you just see one image instead of two.

Is this a bug or there's something wrong with my setup?

**Comment by cvan** [comment]
@alexcheninfo We've [deprecated](https://github.com/aframevr/aframe/tree/dev#a-frame) the `dev` branch. We are doing all work in `master` now. [The new docs](https://github.com/aframevr/aframe/blob/master/docs/guide/getting-started.md#npm) reflect that, but we haven't pushed them live to https://aframe.io/docs/ yet.

Sorry for the confusing. VR mode should be working for you just fine on `master`.

**Comment by ngokevin** [comment]
i..e, ```npm install aframevr/aframe```

**Comment by alexcheninfo** [comment]
I did `npm install aframevr/aframe`. It works. Thanks again, this is one of the fastest-replying repos.
