### ISSUE TITLE
Double click for navigating after adding aframe.min.js

### ISSUE THREAD

**Issue by ahmedadham88** [aframevr/aframe#1187]
I'm using Angular 2 and did npm install aframe --save-dev to include it in my node_modules.

In the index.html I include the script <script src="node_modules/aframe/dist/aframe.min.js"></script>

and I use aframe in one of my htmls as follows: 
<a-scene>
    <a-sky src="image_location.jpg" rotation="0 -130 0"></a-sky>
</a-scene>

- A-Frame Version: "^0.1.3"
- Platform/Device: Tried it on MacOS and Ubuntu 14.4

**Comment by dmarcos** [comment]
Can you be a bit more precise about the problem? What do you exactly mean by "double click for navigating"? Do you mean "enter VR"?

**Comment by ahmedadham88** [comment]
For navigating through my application generally. Instead of clicking once on any button I have to click twice to go to the next page regardless if it has the VR image or not.

Anyway, I upgraded the version of aframe from 0.1.3 to 0.2.0-rc1 that was added two days ago. And now it doesn't do it anymore.

Thanks,

Ahmed

**Comment by dmarcos** [comment]
When you say navigating through your application what do you exactly mean? Can you point to an a-frame example where the same problem reproduces?

**Comment by ahmedadham88** [comment]
So the flow is as follows:
1) running the home page 
2) clicking on a button to go to the html that has the a-frame tags and shows me the VR photo.
3) There are some other pages of info and static data non a-frame related

Using 0.1.3 version of aframe, once the script is included in my index.html. The whole application becomes slower and I should click on the button twice to navigate to the a-frame image.

**Comment by dmarcos** [comment]
I still don't understand what the problem is. Can you share a link so we can look into it?

**Comment by ngokevin** [comment]
Don't include A-Frame twice. Either NPM install it, or include it as a script tag.
