### ISSUE TITLE
Some A-Frame scenes load improperly in Edge on Windows

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1188]
**Description:**

Heard reports of A-Frame scenes not loading in IE10. Makes sense to not support <= IE9. But perhaps IE10 is worth addressing. In my tests, scenes load fine in Edge on Windows 8.1 + Windows 10.

- A-Frame Version: 0.1.0 (on https://aframe.io/examples/)
- Platform/Device: IE10 on Windows

**Comment by bryik** [comment]
A second data point for Windows 10 with Edge:

- Most run fine (e.g. Hello World).
- Anime UI loads but from a [different perspective](https://drive.google.com/file/d/0B9kmhkXbM5H8WDF0OWFjVVoxWWs/view?usp=sharing) (?). A similar thing happens with the "Shopping" and "Logo" demos.
- Cursor & Hover runs, but the cube does not change when I look at it (as it does on Chrome).

**Comment by dmarcos** [comment]
IE 10? As far as I know IE 10 does not even support WebGL. Can we close this?

**Comment by cvan** [comment]
Who's using IE 10 and why trying to load WebGL/VR scenes?

<hr>

@bryik: the [Anime UI](https://drive.google.com/file/d/0B9kmhkXbM5H8WDF0OWFjVVoxWWs/view) issue I've encountered once or twice. Very peculiar.

**Comment by dmarcos** [comment]
@cvan In the original description you mention IE 10

**Comment by dmarcos** [comment]
I'm going to close this. IE 11 does not even have complete support for CustomEvents http://caniuse.com/#feat=customevent.
