### ISSUE TITLE
Add equirectangular/cube toggle sky primitive

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#120]
We like the simplicity of a `<a-sky>` template over separate (and more abstract) `<a-skysphere>` and `<a-skycube>` templates. However a combined approach will necessitate a way for devs to specify which type they want to use.

We envision something like the following:
- `type=""` Options are `sphere` or `cube`. Default is `sphere`.
- Other attributes then depend on the type.
- If sphere, user can specify `segments-width`, `segments-height`, `radius`, etc.
- If cube, user can specify `size`
- In both cases, user can specify `src`. 
  - For `sphere`, it must be the path to an image asset. 
  - For `cube`, it must be the path to a directory containing top, bottom, left, right, front, back images.
    - Note: this is subject to change, depending on what we do in core for cube map handling.

JS inside the template then handles the switching between types.

**Comment by PixelPartner** [comment]
For VR use it would be convinient to also support stereoscopic skies or to add a similar a-entity that supports this.

**Comment by ngokevin** [comment]
Will stick to https://github.com/aframevr/aframe/issues/45
