### ISSUE TITLE
add intensity property to ambient light

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1201]
**Description:** three.js r74 introduced intensity property on ambient light https://github.com/mrdoob/three.js/pull/7621 . Add that to the light component.

- A-Frame Version: master 
- Platform/Device: all

**Comment by MichaelRupertDev** [comment]
I'll grab this

**Comment by BhasinParth** [comment]
im in

**Comment by MichaelRupertDev** [comment]
@BhasinParth, this is a really simple task, should be done in a matter of minutes, I don't think we need two people on it, however, I can show you my changes if you'd like.

**Comment by BhasinParth** [comment]
ok great,all the best buddy

**Comment by MichaelRupertDev** [comment]
PR: https://github.com/aframevr/aframe/pull/1270
