### ISSUE TITLE
Using ID and class selectors inside templates leads to conflicts when there are multiple instances of the same template in the scene

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#121]
When creating multiple instances of the same template, we hit an issue with selectors inside those templates conflicting. I discovered this while creating the the video, image and sky templates, which use `<video>` and `<img>` elements plus IDs / classes. 

I had a bunch of image template instances. Each with a unique src image specified. But they were all showing the same image. Because each template instance contained an <img> instance with the same id="image".

Solution would be to encapsulate selector scope to template? Or randomize template ID/classes?

**Comment by ngokevin** [comment]
Swapping out the current implementation of templates with primitives.
