### ISSUE TITLE
deallocate geometries and materials when no longer in use

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1215]
**Description:** Possibly on entity detach and we detect that its geometry, material, and/or texture are no longer in use. iOS crashing sometimes due to running out of memory. One test case is to have one photosphere with six panos, and switching back and forth them a lot.

http://mrdoob.github.io/three.js/examples/webgl_test_memory.html

- A-Frame Version: master
- Platform/Device: all

**Comment by dmarcos** [comment]
this can be tricky. Imagine a geometry that switches textures on hover state. A texture might be not temporarily but there's intent to use it often. We might need a flag on the assets so a devs can opt in to cache some of the textures. They know how the textures will be used.

**Comment by ngokevin** [comment]
Call `geometry.dispose` and `material.dispose` in geometry/material components on `remove()`.

We can iterate on this later by perhaps having a disposal system or including adding logic to the texture system.
