### ISSUE TITLE
increase default segments in geometry component

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1216]
**Description:** The low number of default segments causes lots of jagged/low-poly shapes, like octagons instead of circles. Which is fine to allow, but by default a circle primitive should look like an actual circle. The default should be at least 25-36 rather than 8.

- A-Frame Version: master
- Platform/Device: all

**Comment by dmarcos** [comment]
Fixed on https://github.com/aframevr/aframe/pull/1241

**Comment by dmarcos** [comment]
Kept open for other shapes
