### ISSUE TITLE
organize examples

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1217]
**Description:** Everything in the examples directory is under one level, though we have multiple categories. We have asset folders prefixed with underscores in this directory as well. We should:

- Put all examples under one more directory respective to their category. For example, ```examples/showcase-composite``` would become ```examples/showcase/composite```.
- Move all assets under the directory of their respective example. For example, ```ui/1.png``` should move to ```examples/showcase/curved-mockups``` since it is being used in that example only. This helps keep track of which asset belongs to which example, and if an example is removed, then it ensures the related assets are as well.
- Optionally, very commonly-used assets (at least three uses) live in an ```examples/assets``` folder.

- A-Frame Version: master

**Comment by BhasinParth** [comment]
I'm in

**Comment by dmarcos** [comment]
@BhasinParth go ahead!

**Comment by BhasinParth** [comment]
the folders are arranged now but I'm unable to give the respective images in the folders

**Comment by BhasinParth** [comment]
Also, where do I have to upload the updation?

**Comment by dmarcos** [comment]
@BhasinParth What's the problem exactly? You should move the images under the directory of each example unless they're shared by multiple of them.

**Comment by BhasinParth** [comment]
Got it, thanks @dmarcos, after doing this where do I have to upload the updated file?
currently its in my PC

**Comment by dmarcos** [comment]
@BhasinParth you have to open a Pull Request against the master branch. https://help.github.com/articles/using-pull-requests/

**Comment by ngokevin** [comment]
Going to work on this.

**Comment by ngokevin** [comment]
#1394
