### ISSUE TITLE
setActiveCamera for three.js cameras

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe#1218]
**Description:**: Before it was possible to call ```sceneEl.setActiveCamera(threejsCamera)``` to activate a non-aframe camera. This was used by the editor to insert a custom perspective camera.
Now it's necessary to include a ```newCameraEl```. Maybe we should change the code to accept just a three.js camera? or do I need to create a editor-camera element and insert into the scene?

- A-Frame Version: v0.2.0-rc1

Related to https://github.com/aframevr/aframe-editor/issues/59

**Comment by fernandojsg** [comment]
In the meanwhile I just created an empty camera element and use it in the call.
```javascript
var cameraEl = document.createElement('a-entity');
cameraEl.setAttribute('camera', 'active: false');
var camera = editor.camera;
...
sceneEl.systems.camera.setActiveCamera(cameraEl, camera);
```

**Comment by ngokevin** [comment]
Yeah, we should be trying to use entities in the public API whenever possible so that it is consistent and the A-Frame markup accurately reflects the state of the scene.

**Comment by fernandojsg** [comment]
Ok, perfect!
