### ISSUE TITLE
Add `color` attribute to images template

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#122]
Want to be able to specify just a color for an image template. Handy for stubbing layouts out quickly, without having to apply an image. 

Challenge is that specifying a `src` on a material (even if `src` is empty), seems to negate the color. So we'll either need to update core to still show a color if `src` is empty, or include JS inside the template to only add `src` to material if the template `src` attribute contains a value.

**Comment by cvan** [comment]
@ngokevin: can we handle this in PR #883?

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
