### ISSUE TITLE
Prefix component-emitted event names by component name

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1224]
**Description:** Have a method that automatically prefixes event names emitted on an entity by a component, by the component name. For example:

```Component.emit('click');``` would do ```this.el.emit(this.name + '-' + eventName)```. So in the cursor component, `click` would turn to `cursor-click` automatically.

- A-Frame Version: master
- Platform/Device: all

**Comment by cvan** [comment]
I like this idea

**Comment by ngokevin** [comment]
I think we will leave it up to the component to decide that. But sometimes it's a good idea.
