### ISSUE TITLE
Add hack to allow pseudo-fullscreen in Chrome and Firefox for iOS

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1231]
**Description:**

WebKit does not support the Fullscreen API. In Safari for iOS, fullscreen can be emulated using `<meta name="apple-mobile-web-app-capable" content="yes">` (which A-Frame already injects if `meta[name="apple-mobile-web-app-capable"]` doesn't already exist on the page).

Chrome and Firefox for iOS unfortunately do not support such a method of pseudo-fullscreen. In both browsers though, as you scroll down on a page, the chrome navbar disappears. But because we are `preventDefault`-ing on `touchmove` on the `canvas` and the `html` has `position: fixed` styles, this doesn't work. I have a WIP branch that sets iOS-only styles that adds a bunch of `padding-bottom` to the `html` element and then when the user swipes down, it works.

Calling `window.scrollTo` or setting `document.body.scrollTop` doesn't seem to work. I'll have to investigate that some more though. That'd be the "ideal hack."

**Comment by cvan** [comment]
As stated above, Firefox for iOS (like Chrome for iOS) hides the chrome nav bar when a user scrolls down the page. Safari for iOS hides the chrome nav bar in landscape if `<meta name="apple-mobile-web-app-capable" content="yes">` exists on the page. We should get Firefox for iOS to do the same pseudo-fullscreen behaviour if `<meta name="mobile-web-app-capable" content="yes">` exists on the page (which is what Chrome 32-39 used before using the W3C manifest: https://developer.chrome.com/multidevice/android/installtohomescreen#fallback).

We should file a bug for Firefox for iOS to do this.

**Comment by Drewwit** [comment]
Cvan, have you published with WIP build that adds the padding to the bottom of the html? I'm having the same issue on a build that we are about to go public, and while not ideal, at least being able to "swipe" to remove the URL bar is better than the offset (low) stereoscopic rendering due to the URL bar

**Comment by renhyl** [comment]
For those interested, the temp/crude solution as described is to create scrolling and that gets rid of address bar.

for example 

`var html = document.getElementsByTagName('HTML');
html[0].style.position = 'initial';
                        html[0].style.overflow = 'scroll';
                        var canvas = document.querySelector('.a-canvas');
                        canvas.style.top = '1000px';`

**Comment by MagicIndustries** [comment]
Is anything being done on this? It's quite a critical problem for us.

**Comment by cvan** [comment]
This issue can be fixed in A-Frame's dependency, [`webvr-polyfill`](https://github.com/googlevr/webvr-polyfill). When this issue is properly addressed and fixed, this will also be fixed in A-Frame too: googlevr/webvr-polyfill#114

**Comment by MagicIndustries** [comment]
@cvan Unfortunately unless I'm reading it wrong that PR only seems to add support to what's already there for android webviews. We are trying to fix the full screen / urlbar issue on ios in safari and chrome (on iphone 5/SE, though i believe the reason chrome doesn't work is different to why safari doesn't work)

**Comment by cvan** [comment]
@MagicIndustries you can do "Add to Homescreen" on iOS. Do you have a URL of your site andcau explain the user flow and what you're expecting vs. encountering. On a related note, have you seen these comments?

* https://github.com/aframevr/aframe/issues/316#issuecomment-209147896
* https://github.com/aframevr/aframe/issues/316#issuecomment-212608703
* https://github.com/aframevr/aframe/issues/316#issuecomment-219181039

**Comment by MagicIndustries** [comment]
@cvan Thanks for that - yeah we've already added that add to home screen component, and that works, we're just trying to find ways with less friction.

For anyone else coming across this, this is what we've found definitively:

*IOS on iphone 5, 5S, SE*
- Chrome and Firefox and safari all refuse to hide their url bars / go full screen 

*IOS on iphone 6+*
- Chrome and Firefox still refuse to hide their url bars / go full screen
- Safari works great and hides the url bars

*Android on various*
- Chrome, Firefox and Samsung browsers work great and hide their url bars.

We've tried all the hacks - scrollTo, the hack mentioned in the @renhyl 's comment above, and everything else we could find online. There's currently no proper solution to this on iOS, other than to use the pin to homescreen option - whereupon full screen works just fine.

We also came across some weirdness implementing @renhyl 's code above as it would work to hide the scrollbars, but exiting VR was buggy and sometimes impossible. All in all it detracts from the user experience and we decided pinning was the least friction causing option.

Our app is in latest A-Frame, and ios versions were 9 and 10.

**Comment by johnnyshankman** [comment]
@ngokevin @cvan we shouldn't need to leverage the homescreen in this scenario. I have a working demo doing in-browser with inline video + audio etc. on iOS10 very smooth. The only caveat is it can't autoplay on page load because of the lack of user gesture.

My only issue is that iOS chrome does not get rid of the URL bar when going landscape *or* when going into VR mode. This simultaneously causes the renderer to squash and look weird. I cannot recreate the issue using Chrome's simulator for iPhones.

**Comment by blairmacintyre** [comment]
I'll add that even hacks that go fullscreen on the iphone 6/6s/7 will sometimes not work on the 6plus and 7plus.  Because Apple treats the plus as some sort of super-mini iPad (it's like the worst of both worlds, I hope the iPhone8 acts like a phone, not like this).
