### ISSUE TITLE
Auto detect format of model

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#124]
Users should not have to manually specify the file format of a model (eg obj, collada, etc). 

In the current model template we provide a format attribute, defaulted to `format="collada"`. That's good enough for View Source, where we'll only be using Collada files, but we can't make that assumption for release. Novice users may very well try to drop obj files into their scenes, and shouldn't have to know about format="obj" for them to work.

A potential implementation:

* Maintain a format attribute
* If no format is specified, automatically apply the correct format based on src file extension
* If format is defined use that instead.

**Comment by sirkitree** [comment]
Auto-detection would be great in the case of objects. A stop gap might also be to document the valid options. Currently https://aframe.io/docs/primitives/a-model.html tells us that the default is collada but without looking at [the code](https://github.com/aframevr/aframe-core/pull/315/files#r42915419) we don't know that you need to specify `format="obj"`.

Possible duplicate? https://github.com/aframevr/aframe-core/issues/45

**Comment by sirkitree** [comment]
Along with this, the mtl file is often separate with an object file and there is no component/attribute documented with the model entity/tag on how to specify the mtl.

**Comment by sirkitree** [comment]
ref: https://github.com/aframevr/aframe-site-dev/pull/102

**Comment by donmccurdy** [comment]
I've been looking into loading a `.obj` with a `.mtl`: threejs gives example loaders [OBJMTLLoader.js](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/OBJMTLLoader.js) and [MTLLoader.js](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/MTLLoader.js). Haven't got it working just yet but I don't think it should be too complicated to have the material component accept a `.mtl` file as its `src` attribute, if that seems like a good approach? Not sure how many formats you want the core library to support, though, or if this makes sense to include by default.

**Comment by sirkitree** [comment]
So far I've tried 

```html
material="https://raw.githubusercontent.com/bitgridio/models/gh-pages/lullabot/Body.mtl"
```
and 
```html
material="src: https://raw.githubusercontent.com/bitgridio/models/gh-pages/lullabot/Body.mtl"
```
within a-model. Full example:
```html
<a-model 
  src="https://raw.githubusercontent.com/bitgridio/models/gh-pages/lullabot/Body.obj" 
  material="src: https://raw.githubusercontent.com/bitgridio/models/gh-pages/lullabot/Body.mtl" 
  position="0 0 -2" 
  format="obj">
</a-model>
```

**Comment by donmccurdy** [comment]
@sirkitree a-model only supports [a few attributes](https://aframe.io/docs/primitives/a-model.html). You may want to look into using a-entity directly (see [a-model implementation](https://github.com/aframevr/aframe/blob/master/elements/templates/a-model.html)). That's enough to specify a color for your `.obj`, for example.

I got a `.mtl` working, but it took changes to aframe-core. [Example here](https://github.com/donmccurdy/aframe-core/commit/06ff9f7dda1e13d370e952cd0bbcbd93f1051236). Not sure if it makes sense to drop both MTLLoader and OBJMTLLoader into aframe-core, so this might need to be a separate primitive or component for `.mtl` support.

**Comment by ngokevin** [comment]
We have separate components for `obj-model` and `collada-model`. Will have separate primitives as well `a-obj-model` and `a-collada-model`
