### ISSUE TITLE
'Unknown component property' warning

### ISSUE THREAD

**Issue by jarmitage** [aframevr/aframe#1255]
**Description:**

Loading an empty scene:

`
<a-scene stats="true" id="scene">
      <a-assets id="assets"></a-assets>
</a-scene>
`

Causes following warning:

`2016-03-24 18:19:53.958 aframe.js:258 core:schema:warn Unknown component property:  +0ms`

- A-Frame Version: 0.2.0
- Platform/Device: Chrome Desktop

**Comment by ngokevin** [comment]
I believe this has been fixed. Thanks!
