### ISSUE TITLE
?ui=false no longer works to hide Enter VR button

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1260]
**Description:**

https://aframe.io/aframe/examples/animation-aframe-logo/?ui=false hides the "Enter VR" button. Check https://aframe.io/

On `master` http://localhost:9000/examples/animation-aframe-logo/?ui=false no longer hides the UI button. I still see the `getUrlParameter` method in `utils`, but it's not used anywhere.

- A-Frame Version: `master`
- Platform/Device: all

**Comment by ngokevin** [comment]
Or just disable the VR mode UI for that example specifically.

**Comment by cvan** [comment]
> Or just disable the VR mode UI for that example specifically.

I could. you don't think it's useful for other folks. I have a local branch to allow disabling and listening for messages by `postMessage`.
