### ISSUE TITLE
Video materials should display poster attribute

### ISSUE THREAD

**Issue by jarmitage** [aframevr/aframe#1271]
`<video>` assets can contain a `poster` attribute specifying an image to be displayed before the video has loaded, or before it has been played.

When adding a video as a material `src`, it would be beneficial if the material could look for and display the  `poster` image. This should allow for the `src` attribute to be left empty when the video is not playing, so that memory is not used to load a video that is not being played.

The current workaround is to use an additional `<img>` asset containing the `poster` image, and to dynamically switch the material `src` to the `<video>` `src` when needed.

**Comment by ngokevin** [comment]
This can be application behavior. Use a video element in `<a-assets>`, listen to its events, and show an image texture on an entity in the meantime

**Comment by cvan** [comment]
I'd like to work on this. Especially when videos take a while to load (which is pretty much always), having a black screen while the video loads (or having to manually apply an image texture yourself), it's just not ideal default behaviour.

The HTML5 `<video>` tag already supports the [`poster` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-poster) (not just used on default HTML5 players, but it's used by YouTube/Vimeo players too).

So, like you have `<video poster="poster.png" src="poster.mp4">`, A-Frame devs could just similarly do `<a-videosphere poster="poster.png" src="poster.mp4">`.

Would be fantastic!

**Comment by ngokevin** [comment]
This can be handled application level. Show image, when video ready, toggle the visible.
