### ISSUE TITLE
Canvas component: Width and Height properties don't seem to apply 

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#1289]

**Comment by ngokevin** [comment]
Note that they are percentages.

**Comment by enjalot** [comment]
this example shows the width/height of the injected canvas being ignored, as well as the width/height percentages not working
http://blockbuilder.org/enjalot/bff45307d120a5b2f53e

**Comment by ngokevin** [comment]
Looks like the scene resizing is overwriting it
