### ISSUE TITLE
.objs fail to load when they have line elements in them

### ISSUE THREAD

**Issue by bnolan** [aframevr/aframe#1291]
**Description:**

Can't render this obj model, because it has `l` lines.
[cardboard.obj.zip](https://github.com/aframevr/aframe/files/193041/cardboard.obj.zip)

The error message in the console:

Uncaught Error: Unexpected line: l 2 1

It should be safe to ignore these elements, they seem to be output erroneously by the blender obj export, but its a pain having to tell users to delete the lines in a text editor.

**Comment by ngokevin** [comment]
We use `THREE.OBJLoader` so it might be an issue with that: http://threejs.org/docs/#Reference/Loaders/OBJLoader

**Comment by cvan** [comment]
If that's the case, I'd like to make a pull request to three.js to fix that. I'll do this.
