### ISSUE TITLE
remove stringifying to DOM in most cases, have getAttribute access a cache rather than from DOM

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1311]
**Description:** Stringification to DOM, and using the DOM to fetch data is one of the bottlenecks in perf.

We only want to stringify to DOM if the DOM inspector is open (still want to debounce that) or a flag is set. This may affect integration with other libraries, in which case the flag can be turned on.

**Comment by bnolan** [comment]
How are we testing performance gains here? Just against the performance-test scene? Be interesting to get some before / after metrics. Also - please make sure the flag can be turned on, because the editor needs it. ;)

**Comment by dmarcos** [comment]
@bnolan look at https://github.com/aframevr/aframe/pull/1323
