### ISSUE TITLE
Camera position is "jumping" and becoming uncontrollable.

### ISSUE THREAD

**Issue by clement-igonet** [aframevr/aframe#1314]
**Description:**

- A-Frame Version: https://aframe.io/releases/0.2.0/aframe.min.js
- Platform/Device: Linux Mint 2 "Betsy" - MATE (64-bit) - firefox 44.0.2

When using `aframe-keyboard-controls`, and logging camera postion at runtime, the camera position is jumping and becoming uncontrolable.

All the code is in the attached file.
[earth0.txt](https://github.com/aframevr/aframe/files/198523/earth0.txt)

**Comment by donmccurdy** [comment]
I think this is a problem with my [aframe-keyboard-controls](https://github.com/donmccurdy/aframe-keyboard-controls/) code, not A-Frame, but I've just updated it for A-Frame v0.2.0, so maybe try that:

https://cdn.rawgit.com/donmccurdy/aframe-keyboard-controls/v1.0.0/dist/aframe-keyboard-controls.min.js

(it isn't jumping for me, anyway, deliberately adding enough `console.log()`s to reduce the framerate.)

Cheers

**Comment by clement-igonet** [comment]
I don't see the bug anymore, and it has became so responsive!
You are such a good guy, and it's a pleasure to work with a-frame.
Coming from x3dom, they're is no comparison !
