### ISSUE TITLE
Downsample 2:1 on retina displays?

### ISSUE THREAD

**Issue by bnolan** [aframevr/aframe#1325]
**Description:**

I tried out aframe on a macbook 12", it rendered at about 10-15fps. Would it be worth testing `window.devicePixelRatio > 1` and setting the canvas resolution to half the screen resoltuion, so that it only renders at half the resolution, then upsamples? It should get us banging against 60fps again, with some degradation in quality.

Ideally this would be autodetected, so that if you have retina + a strong GPU, it doesn't downsample.

**Comment by bnolan** [comment]
I did some experimentation, and calling `renderer.setSize`, you can dynamically downsample the scene. In a similair way to how valve are reducing the render resolution to make sure you stay at 90fps, you could do the same with aframe. People are used to netflix dynamically reducing the resolution when the network is congested, hopefully they would see adaptive downsampling the same way in aframe.

**Comment by ngokevin** [comment]
Sounds awesome. Could you publish an example so we could try it out? As a separate component would be cool so people can try it out in the meantime.

**Comment by jonikorpi** [comment]
No progress on this yet I guess? Even a manual option would be great to have. Even for non-VR use. 

Example scenario: laptop attached to a 4K monitor.

**Comment by dirkk0** [comment]
This seems to be one way to achieve this, and if you got to extremes you even have an artistic effect. :-)
https://jsfiddle.net/dirkk0/0fdzqcsk/

**Comment by intensr** [comment]
progress on this ?

**Comment by dmarcos** [comment]
It's not a priority at the moment. @intensr Can you describe your use case?

**Comment by intensr** [comment]
I'm developing on a 2016 Retina MBP for Smartphone/Daydream VR devices. Of course you want to preview your progress on the MBP screen but when I do so the MBP is constantly stressed out to render the scene (literally melting) and I still just get low fps. My current workaround is to use a 72dpi external monitor which normalizes the situation so I think its ok for me for now. The only problem is that the MBP loses its mobility but yeah somehow more of a luxury problem at the moment I guess.

**Comment by ngokevin** [comment]
There is now `renderer.maxCanvasWidth` and `renderer.maxCanvasHeight`
