### ISSUE TITLE
support easy way of passing three.js lights/fog uniforms to a-frame shaders

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1326]
**Description:**

Find a way to make these three.js uniforms available to shaders in A-Frame: https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/UniformsLib.js

To automatically include light/fog uniforms into shaders. Perhaps:

``` js
AFRAME.registerShader('test', {
  lights: true,
  fog: true,
  schema: {
  }
});
```

For my city, I created a road shader and wanted to pass fog to it. And for this skin shader I'm trying to work with, I need lights/fog.

**Comment by ngokevin** [comment]
wontfix for now, i'd just create my own shader component

**Comment by donmccurdy** [comment]
I thought this happened automatically, since we're using ShaderMaterial and not RawShaderMaterial? See: https://threejs.org/docs/#api/materials/ShaderMaterial.uniforms

have not checked on which are considered "built in uniforms" though.

**Comment by ngokevin** [comment]
See the lights/fog properties in those docs e.g.,  'Defines whether this material uses lighting; true to pass uniform data related to lighting to this shader. Default is false.'.
