### ISSUE TITLE
Serve source map for production bundle, not development bundle

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1328]
We shouldn't necessarily assume that folks using the minified bundle don't want source maps. I hate to list/maintain a third bundle, but it could be quite useful. I could be convinced otherwise.

**Comment by cvan** [comment]
Actually, I gave this some thought. I noticed that the libraries on [jsdelivr](https://www.jsdelivr.com/) have source maps for the minified, not development, versions ([example](https://github.com/jsdelivr/jsdelivr/tree/master/files/phaser/2.4.6)).

We already have source maps if you're doing local development in this `aframe` repo. This is because the bundle the local dev server uses (`/build/aframe.js`) contains an inlined source map. (Remember that the `budo` server has middleware to route `/dist/aframe.js` to `/build/aframe.js` - for ease of development + testing for `/examples/`).

In the [`dist` npm script](https://github.com/aframevr/aframe/blob/master/package.json#L11), we probably need to add to [`uglifyjs` the `--in-source-map` flag](https://github.com/mishoo/UglifyJS2#usage).

**Comment by ngokevin** [comment]
We're talking about `aframe.min.js` that has inline source maps right? Not sure we need this.:

- Has anyone requested it? I wouldn't use it, personally.
- The exorcised source map is there and it works. That seems to solve the use case.
- I haven't seen many projects have a minified bundle with inline sourcemaps.
- Introducing a third bundle complicates things, and some people may accidentally used the minified bundle with inline source maps.

**Comment by cvan** [comment]
> * Has anyone requested it? I wouldn't use it, personally.

Just because nobody requested it doesn't mean devs aren't encountering issues with cryptic minified errors. On other projects I've worked on and projects I've seen in the wild, folks have dealt with it for years because source maps didn't exist, or people didn't/don't know what source maps were.

> The exorcised source map is there and it works. That seems to solve the use case.

It actually solves the wrong use case. If you see in my previous comment, I say that we shouldn't add a third bundle. We should instead be correcting where source maps are included. Instead of having a source map for development bundle -> Browserify source, we should remove that one and have a source map for production bundle -> development bundle. Sorry if that was unclear.

> Introducing a third bundle complicates things, and some people may accidentally used the minified bundle with inline source maps.

If you read my comment above, I mention that our _budo_-compiled version (`/build/aframe.js`) contains an inline source map, not our `releases`/`dist`s.

I'm not suggesting an inline source map. I'm suggesting a comment to the external source map (see the very last line of development bundle, [`aframe.js`](https://raw.githubusercontent.com/aframevr/aframe-site/master/themes/aframe/source/releases/0.2.0/aframe.js) - and [`phaser.min.js`](https://github.com/jsdelivr/jsdelivr/blob/master/files/phaser/2.4.6/phaser.min.js#L27) for good measure). 
).

To reiterate, the only change I'm suggesting is moving

```js
//# sourceMappingURL=aframe.map
```

from `dist/aframe.js` to `dist/aframe.min.js`. And having that source map be generated from `dist/aframe.js`, __not__ from the Browserify entry point, `src/index.js`.

And, just so you know, the `//# sourceMappingURL=` comment for external source maps actually means the source maps are loaded asynchronously and only when the user's Developer Tools are _open_, source maps are supported, and source maps are enabled (which is the default, unless a user overrides this).

For reasons above, I'm not recommending adding a third bundle.

> I haven't seen many projects have a minified bundle with inline sourcemaps.

Nearly every single library on cdnjs and jsdelivr have source maps for the minified bundles. How often would you try to debug a jQuery error in production `ReferenceError: a is undefined`?

Hope that all makes sense. Sorry, this would probably be easier to explain in person. It's complicated! But the change I'm suggesting is easy peasy - and very helpful.

**Comment by ngokevin** [comment]
OK, I forgot and thought the source map we had was for the minified bundle. Got confused since it's weird to have a source map only for the non-minified bundle. That sounds good.
