### ISSUE TITLE
Add parameter type for maps

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe#1329]
**Description:** Currently the maps parameters are treated as simple strings, eg:

```
    src: { default: '' },
    envMap: { default: '' },
```

We should give them a proper type, `texture` ?, `map` ?

**Comment by ngokevin** [comment]
We do have a `src` type that allows `url()` or selector values, that automatically parses a URL.

What would be a use case for wanting to differentiate? I do know that we need a texture type for shaders, so this might tie into that.

**Comment by fernandojsg** [comment]
Yes, shaders one use case, also the editor, to know which widget to show, right now I'm just showing a textbox so the user could write `#selector` or `url()` but it's not very user-friendly :smile:

**Comment by fernandojsg** [comment]
@ngokevin any updates on this? I need a way to know if the parameter is a `map` to use the correct widget in the editor, currently `src` and `envMap` are just strings. Maybe we could just add the `map` type even if it will be parsed `string`?
