### ISSUE TITLE
Rename `defaultAttributes` in extras/primitives to `defaultComponents`

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1330]
**Description:** For primitives, we specify a set of default components in the primitive definition. These are named defaultAttributes, but it would be more correct to call them defaultComponents. A simple grep job.

**Comment by msimpson** [comment]
@ngokevin 
I can do this now if you want. I don't want to break anything in progress, though.

**Comment by ngokevin** [comment]
OK. If possible, we could deprecate `defaultAttributes` for one version. So `defaultAttributes` still work, but everything is renamed to `defaultComponents`. If we detect `defaultAttributes`, just set `defaultComponents` to `defaultAttributes`.
