### ISSUE TITLE
Document common issues with using .MTL files

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1337]
**Description:**

Document in the `obj-model` component docs that if an MTL isn't working and you don't see your texture applied correctly, you have to dig into the MTL file to check out that all the paths are correct and that all related assets are where they should be.

**Comment by donmccurdy** [comment]
+1. If we identify the most common issues, we could even write a drag-and-drop MTL validator perhaps. Or, really less validation than just warning about things THREE.MTLLoader doesn't support.

**Comment by risbansal** [comment]
I want to help.

**Comment by Utopiah** [comment]
- check path (e.g. relative vs absolute)

**Comment by donmccurdy** [comment]
There is a [3D Models • Troubleshooting](https://aframe.io/docs/0.5.0/introduction/models.html#troubleshooting) section in the documentation now; I think this issue can be closed if we just add a link from the `obj-model` docs.

That said, please feel free to improve these docs with PRs! :)
