### ISSUE TITLE
Animation demos are no longer working as expected.

### ISSUE THREAD

**Issue by JohnRodney** [aframevr/aframe#1341]
**Description:**
  On Current master branch previously working animation examples no longer behave as expected.
- A-Frame Version:  Master
- Platform/Device:  All

Evidence:
1. Checkout Master
2. `npm run dev`
3. Visit animation unfold example.

Expected: Each plane should individually animate delayed from each other.
Seen: The next two planes to animate appear to be 'attached' and share rotation values until the next one is kicked off.

Maybe this behavior is now expected with the updates to primitives and the example code should be updated?

**Comment by JohnRodney** [comment]
Aframe-logo animation: the flat plane connecting the Slants in the A is no longer positioned appropriately as well.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/1339 will fix it
