### ISSUE TITLE
Add three-model or json-model?

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#1342]
Thoughts on adding a `three-model` loader for the THREE.js JSON format? It's not as bleeding-edge as glTF (and I'd love to see that get traction) but since THREE.JSONLoader and THREE.ObjectLoader are bundled with THREE.js by default, it wouldn't add much cruft.

[Work In Progress](https://github.com/donmccurdy/aframe-extras/blob/master/src/loaders/three-model.js)

The format also [supports animation](https://sandbox.donmccurdy.com/vr/animation/), although I don't completely understand THREE.js's new animation system.

**Comment by ngokevin** [comment]
I also have a json loader in one of my side repos. I was thinking of creating a repo for all the loader components

**Comment by donmccurdy** [comment]
Oh cool. Can't find it but nbd, I want to try loading some of the 3 Dreams of Black examples. They might be an older format though.

**Comment by ngokevin** [comment]
I have it at https://github.com/ngokevin/respecular/blob/master/assets/components/json-model.js

Might do: https://github.com/aframevr/aframe/issues/1342 since there are so many loaders

**Comment by msj121** [comment]
@donmccurdy As per gltf getting traction, someone has created a gltf component: https://github.com/xirvr/aframe-gltf

https://github.com/aframevr/aframe/pull/1469

**Comment by donmccurdy** [comment]
Ok, yeah I think we can close this in favor of gltf.
