### ISSUE TITLE
Blank rectangle that hide all at about z=10000

### ISSUE THREAD

**Issue by clement-igonet** [aframevr/aframe#1348]
**Description:**
When elevation is near 10000 units, a blank rectangle hide scene objects.

To reproduce the bug, go back (down arrow) just a little bit with that example: http://codepen.io/anon/pen/zqpxEN?editors=1011
- A-Frame Version: latest
- Platform/Device: LMDE 2 (Betsy)

**Comment by ngokevin** [comment]
Thanks for filing.

Might have to do with the scale? I tried shrinking the map to 10x10 and moved the camera to z=5, and it looks better.

**Comment by vincentdesmares** [comment]
Is this a depth buffer problem? If yes, this should be a good hint for a fix: http://threejs.org/examples/webgl_camera_logarithmicdepthbuffer.html

**Comment by ngokevin** [comment]
Increase camera.far
