### ISSUE TITLE
New default `BufferGeometry` regressed Shadows and Fog example 

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1367]
**Description:**

Commit [`bfd0934`](https://github.com/aframevr/aframe/commit/bfd0934) (`default to BufferGeometry for all geometries (fixes #633)`) seems to have changed (regressed?) the __Spheres & Fog__ example:

[local (`bfd0934`)](http://localhost:9000/examples/showcase-spheres-and-fog/) vs. [`bfd0934~1`](https://aframe.io/aframe/examples/test-fog/)

<a href="http://localhost:9000/examples/showcase-spheres-and-fog/"><img src="https://cloud.githubusercontent.com/assets/203725/14453872/35fc3bcc-004c-11e6-9835-a9399f6c3487.png" alt="bad" title="bad" width="47%"></a> &nbsp; <a href="https://aframe.io/aframe/examples/test-fog/"><img src="https://cloud.githubusercontent.com/assets/203725/14453871/35fbc6f6-004c-11e6-930d-e510dd3a2fed.png" alt="good" title="good" width="47%"></a>

<div style="clear: right"></div>

Should this be the expected rendering based on the default now, or no?

- A-Frame Version: [`bfd0934`](https://github.com/aframevr/aframe/commit/bfd0934)
- Platform/Device: All/Any

**Comment by ngokevin** [comment]
half-dupe https://github.com/aframevr/aframe/issues/1341

already fixed on master https://github.com/aframevr/aframe/pull/1339
