### ISSUE TITLE
Examples not working on Firefox Nightly with `dom.webcomponents.enabled;true`

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#137]
I'm seeing a ```No THREE.js found.``` error. It works on Chrome.
http://cl.ly/image/3s0O1X0k352J

**Comment by cvan** [comment]
Non issue once we merge @ngokevin's PR #883 that introduces the newfangled primitives wherein `a-template` is removed. See relevant issue #930 re: reintroducing templates.
