### ISSUE TITLE
sceneEl.canvas not available in initial component.update()

### ISSUE THREAD

**Issue by andreasplesch** [aframevr/aframe#1370]
**Description:**
- A-Frame Version: 0.2.0-rc1
- Platform/Device: FF 38.7

Working on a thick line component using THREE.Meshline at http://codepen.io/anon/pen/MyQrdK I would like to use the dimensions of the current scene canvas within the update function.
However, the canvas does yet not exist when update() is called first.
@donmccurdy on slack came up with a functional workaround using the "loaded" scene event which we used here:
http://codepen.io/anon/pen/vGdwoq
I also tried to register the component only after the scene "loaded" event is fired but then the registered component was not retroactively applied to entities with the new component even after a scene.reload. Here is a page where I commented out things which were not working:
http://andreasplesch.github.io/aframe-pages/test/meshline/

Is there a way to trigger the update() function globally across the scene ? 
Would it be possible for aframe to call init() and update() the first time only after a canvas is created ?

**Comment by ngokevin** [comment]
You can do ```sceneEl.addEventListener('render-target-loaded')``` or `render-started`

Maybe we should just rename that to `canvas-loaded`.

**Comment by andreasplesch** [comment]
Thanks, this should be helpful.

I was sort of looking towards not to have to use event listeners.

Is there a way to trigger a component's update() function globally across the scene ?
Would it be possible for aframe to call components' init() and update() the first time only after a canvas is created ?

**Comment by andreasplesch** [comment]
Here is a way to force an update of all components of a selection of entities:

```
var all_meshlines = document.querySelectorAll('a-entity[meshline]'); // choose selector
[...all_meshlines].forEach(function(entity){
  
  entity.updateComponents();
  
});
```

**Comment by ngokevin** [comment]
Yeah, there're lot of ways to do that. I don't really have a recommended way of doing that yet.

**Comment by andreasplesch** [comment]
It took me a while to find the updateComponents() method. Should it be documented ?

**Comment by ngokevin** [comment]
That isn't really public API. So what is the use case for forcing an update? Currently, `update` is called when the component's data changes. When would you need to call `update` when the component data has not changed? You can use `tick` to update in the background if that works, or use events.

**Comment by andreasplesch** [comment]
My use case was that the components uses canvas.width in its update . So I want to update when the canvas becomes available or when there is a change in size using events outside of the component.

**Comment by ngokevin** [comment]
OK, you should use the event listeners for when the canvas is loaded or resize. From within the component.

**Comment by andreasplesch** [comment]
Is there an example ?

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/blob/master/src/components/look-controls.js#L77

**Comment by andreasplesch** [comment]
Thanks. Will take me a while to understand what is happening there. Why consider updateComponents() not public ?

**Comment by ngokevin** [comment]
Because you shouldn't have to force updates outside of the component. It should be handled by the component.

**Comment by andreasplesch** [comment]
It does make sense to keep all in the component, and thanks to the example I see how to use events there, with bind.
