### ISSUE TITLE
Port mayognaise/aframe-mouse-cursor-component to standard cursor component, rename current cursor to "cardboard cursor"

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1375]
**Description:** 

For true VR experiences, standard cursor should be mouse cursor like http://threejs.org/examples/webgl_interactive_draggablecubes.html

The current cursor component is meant more for Cardboard, which many of us don't want to be the primary VR experience.

@mayognaise's mouse cursor component is pretty inline with this. You move the mouse cursor, and it will project raycaster depending on the coordinate on the canvas. To look around, you use the HMD. 

There should be pointer lock upon entering VR mode so that we can create custom cursor appearances.

Should bounce off the raycaster component. Just like the current Cardboard cursor does.

Recent raycaster work https://github.com/aframevr/aframe/pull/1196 was a stepping stone to exactly this.

**Comment by ngokevin** [comment]
Would be awesome if @mayognaise could tackle this. Else it'll be until I get around to it.

**Comment by mayognaise** [comment]
@ngokevin okay ill work on it :)

**Comment by ngokevin** [comment]
We'll keep it separate for now, and solve with component consumption story next cycle.

**Comment by jordanpapaleo** [comment]
Hi!  Where can I follow the progress of this integration?  Thanks - Jordan
