### ISSUE TITLE
Clone `src` property type to `map` property type, have it return video/img elements rather than strings when possible

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1377]
**Description:** 

If value specified by the texture/map property type is a selector to an img/video, then don't do `getAttribute`, just return the `<img>` or `<video>`. That way the texture system won't have to create a new img/video element and do duplicate loading.

**Comment by ngokevin** [comment]
@fernandojsg What do you think about the name `texture` vs. `map`?

`texture` is possibly more intuitive to A-Frame developers. `map` is technically more accurate.

If we use `texture`, would it be odd to have `{heightMap: {type: 'texture'}}`?

**Comment by ngokevin** [comment]
Also `three.js` refers to them as `t` for texture uniforms (sampler2D), might want to match that. Even though it uses `map` for material properties.

**Comment by fernandojsg** [comment]
I use to prefer `map` over `texture`, maybe for a simple diffuse texture/map they could be used the same way, but when you talk about `normal map`, `envmap`, `bump map`, and so on, it's more accurate and coherent as you'll find more references both in libraries, engines, and 3d programs.

**Comment by machenmusik** [comment]
i believe https://github.com/aframevr/aframe/pull/2129 fixes regression in master by doing this for `video` elements (bug introduced when thia was redone for `canvas`) - are we saying this should also be done for `img` elements here?

**Comment by ngokevin** [comment]
This has been done. `asset` property type returns `<img>`/`<video>`/`<canvas>` down.
