### ISSUE TITLE
AR Mode

### ISSUE THREAD

**Issue by loving1** [aframevr/aframe#1378]
**Description:**

I've started doing some of the coding for AR mode (I just need to add button functionality).  What would be the best way to adapt this? 

loving1.github.io/webvr-polyfill/examples/basic/ 

- A-Frame Version:
- Platform/Device: Lumenora, A/VR Platform

**Comment by ngokevin** [comment]
Do you mean AR, or VR? Also that isn't A-Frame, so it seems this issue doesn't belong in this repo.

You could just do `<a-box ...><a-animation .../></a-box>` if you want to do that in A-Frame.
