### ISSUE TITLE
Consider inverting registerPrimitive mappings

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#1385]
Interested in getting your thoughts on this. I have a relatively simple use case for `<a-grid/>` that doesn't quite work because of the mapping order.

**Use case:**

``` javascript
/**
 * Flat grid.
 */
module.exports = {
  defaultAttributes: {
    geometry: {
      primitive: 'plane',
      width: 75,
      height: 75
    },
    rotation: {x: -90, y: 0, z: 0},
    material: {
      src: 'url(../../assets/grid.png)',
      repeat: '75 75'
    }
  },
  mappings: {
    width: 'geometry.width',
    depth: 'geometry.depth',
    src: 'material.src'
  }
};
```

You can't actually adjust the size of the grid above, because `width` really needs to map to **both** `geometry.width` and `material.repeat.x`, and the same for `depth`. I see two ways to fix this:

**Idea 1: Array Mapping Targets**

``` javascript
  mappings: {
    width: ['geometry.width', 'material.repeat.x'],
    depth: ['geometry.depth', 'material.repeat.y']
    src: 'material.src'
  }
```

**Idea 2: Invert Mappings**

``` javascript
  mappings: {
    'geometry.width': 'width',
    'material.repeat.x': 'width',
    'geometry.depth': 'depth',
    'material.repeat.y': 'depth',
    src: 'material.src'
  }
```

Anyway this is sort of a broken example (`repeat.x` / `repeat.y` don't even work, it needs to be `"75 75"` as a string, but inverting the mappings might also open up more interesting possibilities down the road:

``` javascript
mappings: {
  'geometry.width': 'width',
  'geometry.depth': 'depth'
  'material.repeat': function (data) {
    return (data.width / data.density) + ' ' + (data.depth / data.density);
  }
}
```

**Comment by ngokevin** [comment]
I think option 1 is more readable.

We do have a `transforms` attribute though that does what the second case you're talking about, though it might need some discussion/expansion.

**Comment by ngokevin** [comment]
I think there'd be a `grid` component that can take a width and map it to both versus being magic within the primitive. That also goes in hand with de-emphasize the power and use of primitives a bit.
