### ISSUE TITLE
A-Frame energy impact on MacBook Pro core i7 enormous

### ISSUE THREAD

**Issue by martinboerma** [aframevr/aframe#1386]
**Description:**

The energy impact on my laptop when accessing a website that uses A-Frame is enormous. Both CPU and Graphics are being cooled to the max. Check included screenshots for details.

This counts for Firefor Nightly but also for other browsers.

Any idea what can cause this?

Cheers,
Martin

<img width="1655" alt="screen shot 2016-04-19 at 20 44 49" src="https://cloud.githubusercontent.com/assets/11924339/14651364/f4d9bbea-066f-11e6-9618-da457dc21d69.png">
<img width="1489" alt="screen shot 2016-04-19 at 20 45 47" src="https://cloud.githubusercontent.com/assets/11924339/14651365/f4dfa5dc-066f-11e6-9e75-f7dd7eee75e5.png">

- A-Frame Version:
- Platform/Device: MacBook Pro 2014, 16GB, Core i7, Intel Iris Pro 1536

**Comment by dmarcos** [comment]
How does it compare to other WebGL content? Have you done your test with any three.js demo?

**Comment by martinboerma** [comment]
Yes same result. Is this expected behavior, inherent to WebGL? Or is it my config that need resetting?

**Comment by dmarcos** [comment]
Interactive WebGL applications are demanding and the browser adds overhead on top of that. There's indeed room for improvement on the browsers side. I'm going to close this since this is not an aframe specific issue. It would better to file it against Firefox or Chrome :)
