### ISSUE TITLE
noticeable lagging in gyro responsiveness compared to oculus apps on same device. 

### ISSUE THREAD

**Issue by ejnaren** [aframevr/aframe#1393]
**Running a MozVR example (ie. https://mozvr.github.io/panorama-viewer/) is much slower than running a native oculus app with the same functionality on the same device. The result is heavy lagging and motion sickness.**

Note: I am currently testing to pinpoint the reason and will respond here if I find it.

- A-Frame Version: Unknown. The version running the mentioned example in april 2016.
- Platform/Device: Chrome for Android / Samsung Galaxy S6.

**Comment by ngokevin** [comment]
This is a limitation of Android.

GearVR has special IMU (internal measurement units) within the headset that it can retrieve faster data from. For Android browsers, we are limited to device orientation API which is much slower.

**Comment by ejnaren** [comment]
I am not so sure about that.
I tried today the twgl library and that has no issue with lag on the same device, browser.

I tried this link: 
http://pano-dev.autodesk.com/pano.html?url=jpgs/ecead6d6-ef44-450c-ad9b-229bad61c0ad

It works very responsively.
