### ISSUE TITLE
time uniform does not work. Look at test-shaders example.

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#1397]
The noise shader is not being animated.

**Comment by ngokevin** [comment]
It works for me.

**Comment by ngokevin** [comment]
Try restarting your server. It works Firefox/Chrome.

**Comment by Apus21** [comment]
Businss address PRIVIEGED-LOKION1355
pong22077@gmail.vom

**Comment by Apus21** [comment]
you display name is shown to buyers on your amazon listngs and on your Seller profile you van chanr didsplay name = Displayname
