### ISSUE TITLE
Stagger animations not supported.

### ISSUE THREAD

**Issue by JohnRodney** [aframevr/aframe#1401]
if you do a `<a-animation begin="200" dur="1000" repeate="indefinite">` then the repeated will also stagger its delay by 200 milliseconds making it impossible to stagger a animation through a group.

Suggested that an animation should ignore the delay after the first run on the animation if it is set to repeat the animation.

**Comment by msimpson** [comment]
This makes me wonder whether there should be a separate `delay` instead of overloading begin, as well.

**Comment by ngokevin** [comment]
I think that would be pragmatic.

**Comment by ngokevin** [comment]
We've deprecated a-animation. Try https://github.com/ngokevin/kframe/tree/master/components/animation and file issues, and component will be merged in in the future.

The component won't take into account the delay on subsequent runs. If you do want delay on subsequent runs, you can control the anim with a bit of JS
