### ISSUE TITLE
intersectedEl is null error

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1403]
**Description:**

```
// Emit intersected on intersected entity per intersected entity.
    intersections.forEach(function emitEvents (intersection) {
      var intersectedEl = intersection.object.el;
      intersectedEl.emit('raycaster-intersected', {el: el, intersection: intersection});
    });
```

reported by @drakon58

- A-Frame Version: master
- Platform/Device:

**Comment by msimpson** [comment]
I see this when using the `obj-model` component. The `intersection.object` returned by the `raycaster` doesn't have an associated `el` inside even though it's being set `onload` inside [`obj-model`](https://github.com/aframevr/aframe/blob/master/src/components/obj-model.js#L50) through the [`setObject3D`](https://github.com/aframevr/aframe/blob/58bbdaf05bfe4d3564a4e8ec85c6806e6197bf25/src/core/a-entity.js#L40) method.

However, upon closer inspection, it seems that `el` is only being set in the `THREE.Group` wrapping the loaded object. Whereas the `raycaster` is only concerned with returning the `Mesh` inside that group which is missing an `el`.

Maybe this can be solved inside the `obj-model` component, and others like it, by removing the `Group` wrapper.
