### ISSUE TITLE
Textures not loading

### ISSUE THREAD

**Issue by bnolan** [aframevr/aframe#1407]
**Description:**

Every second time I refresh the page, the textures do not load. I get this error message in the console - but I'm not sure it's related.

<img width="867" alt="screen shot 2016-04-24 at 2 31 19 pm" src="https://cloud.githubusercontent.com/assets/17499/14770556/54ba3c58-0a29-11e6-8b51-0ea84dbff094.png">
<img width="611" alt="screen shot 2016-04-24 at 2 31 49 pm" src="https://cloud.githubusercontent.com/assets/17499/14770557/54ba9824-0a29-11e6-965c-9e0518f5a884.png">

- A-Frame Version: 0.2.0
- Platform/Device: Chrome

**Comment by bnolan** [comment]
It loads perfectly every time in firefox, so maybe just a chrome bug?

**Comment by ngokevin** [comment]
Can you show a bit of code?

**Comment by bnolan** [comment]
It's only happening in my editor but I'll try make a minimal repro step, or just show you it running.

**Comment by bnolan** [comment]
This seems to be a [three.js issue](https://github.com/mrdoob/three.js/issues/8666).
