### ISSUE TITLE
declarative-events are splitting the property name and not value.

### ISSUE THREAD

**Issue by JohnRodney** [aframevr/aframe#1425]
The docs for declarative-events read as so:

```
<a-entity id="cube" mixin="cube"></a-entity>
<a-entity>
  <a-event name="click" property="material.color" target="#cube" value="red"></a-event>
</a-entity>
```

The code applies this by doing: 

```
if (attributeName.indexOf('.') !== -1) {
  attributeSplit = attributeName.split('.');
  targetEl.setAttribute(attributeSplit[0], attributeSplit[1],
                                   attributeValue);
  continue;
}
```

The issue here is `attributeName` is `property` and `attributeValue` is `material.color`.

There are two possible solutions is either changing the docs to do
```
<a-entity>
  <a-event name="click" "material.color"="red"></a-event>
</a-entity>
```

Or updating the code to look for the property's value and then do an attribute split on it then get the actual value from the value property.

Maybe other approaches are possible as well.  Just was able to adjust the code in both these ways to get it working locally.

**Comment by ngokevin** [comment]
I am proposing https://github.com/ngokevin/aframe-event-set-component as the alternative to deprecate declarative events.

**Comment by ngokevin** [comment]
Declarative events deprecated. Event Set should work
