### ISSUE TITLE
requiring aframe from nodejs

### ISSUE THREAD

**Issue by RolandBrake** [aframevr/aframe#1429]
i got this error when i require aframe using node: referenceError window is not defined any help?

- A-Frame Version:0.2.0
- Platform/Device:windows 7 64

**Comment by dmarcos** [comment]
AFRAME is not expected to work on nodejs. It's a front end library

**Comment by RolandBrake** [comment]
if aframe is not expected to work on node why the library exist in node package manager?

**Comment by ngokevin** [comment]
NPM is heavily used these days for frontend dependency management for use with Browserify or Webpack.

**Comment by RolandBrake** [comment]
so the require directive for Browserify not for nodejs?

**Comment by ngokevin** [comment]
Yeah, or with Webpack. Not Node.
