### ISSUE TITLE
"Enter VR" button + text is misleading

### ISSUE THREAD

**Issue by bright-star** [aframevr/aframe#1432]
**Description:**

I'm somewhat baffled. `webvr-polyfill` is in the package dependencies, but the VR button in the examples invariably reports `Your browser does not support WebVR. To enter VR, use a VR-compatible browser or a mobile phone.`

Isn't this exactly what the polyfill is supposed to alleviate? I can run the webvr-polyfill samples in the same browser with no trouble.
- A-Frame Version: d969ecb7
- Platform/Device: Google Chrome 50.0.2661.94 (64-bit) (OSX 10.11.4)

**Comment by msimpson** [comment]
@talexand 
You'll need an experimental version of Chrome in which you can enable the WebVR feature from flags (or terminal/command-line). They can be found here: https://webvr.info/get-chrome/

**Comment by msimpson** [comment]
I believe the intent of that polyfill is to make WebVR experiences compatible with normal desktop and laptop computers by allowing mouse and keyboard usage in place of owning a VR headset. A JavaScript polyfill would never be capable of bridging a hardware support gap between the browser and the headset.

To use WebVR with an actual VR headset you'd need to get a compatible browser from here: https://webvr.info/

**Comment by cvan** [comment]
Yes, we've known this for a bit but haven't addressed it. We need to clarify this. Sorry about this.

**Comment by dmarcos** [comment]
The button should show a full screen icon instead of the googles.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/issues/1060

**Comment by talexand** [comment]
I'm not familiar with the underlying implementation details, but the [webvr-polyfill](https://github.com/borismus/webvr-polyfill) definitely allows you to use at least a cardboard mount with a mobile device that includes an accelerometer.

Try https://toji.github.io/webvr-samples/03-vr-presentation.html?polyfill=1 on desktop Chrome (stable): you will see "Enter VR" and clicking it will get you the split render you expect to see.

**Comment by ngokevin** [comment]
The text is gone for now.
