### ISSUE TITLE
iPhone doesn't show the 360 Video 

### ISSUE THREAD

**Issue by nhirata** [aframevr/aframe#1442]
**Description:**
1. go to https://aframe.io/examples/showcase/videosphere/
Expected: title of 360 Video, video of city scape in motion.
Actual: black screen with no title

- A-Frame Version: 0.2
- Platform/Device: iPhone 6s / iOS 9.3.1

**Comment by nhirata** [comment]
need to look to see if it's the format or size that's causing the issue : 
dmarcos also pointed me to : https://aframe.io/faq/#Why-does-my-video-not-play-on-mobile

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe/issues/316
