### ISSUE TITLE
Aframe examples do not seem to work with Oculus SDK 1.3.2, Chromium, and DK2 headset

### ISSUE THREAD

**Issue by nhirata** [aframevr/aframe#1445]
**Description:**
1. set up Dk2 headset with SDK 1.3.2 
2. launch Chromium
3. go to aframe.io
4. go to examples
5. try entering vr mode

expected : enter vr mode
actual : your browser does not support vr mode

- A-Frame Version: v0.2
- Platform/Device: windows 10, dk2

Note: 
going to vr mode @ http://quake3.webvr.io/ does work.

**Comment by ngokevin** [comment]
Which Chromium? Brandon's builds use WebVR API 1.0. Chromium doesn't have WebVR. For the former, it's a WIP with a PR up now, for the latter can't do anything about that

**Comment by nhirata** [comment]
Brandon's build using WebVR API 1.0; found out that it's a WIP.

**Comment by ngokevin** [comment]
Yeah https://github.com/aframevr/aframe/pull/1423

diego has been testing it on multiple devices. working on the iOS part atm
