### ISSUE TITLE
Display video inline without an iframe

### ISSUE THREAD

**Issue by wsteele** [aframevr/aframe#1449]
**Description:**
- A-Frame Version:
- Platform/Device: OS X Chrome & Firefox

Am I missing something?  I've tried everything to get a videosphere to play inline on a webpage without putting it in an iframe.  When I put the code in my site the videosphere always fills the entire page, which I do not want.  Can this be done or am I just banging my head against a brick wall?

**Comment by ngokevin** [comment]
We're actively working on this. https://github.com/aframevr/aframe/pull/1322 helped, and we're doing some extra stuff right now

**Comment by ngokevin** [comment]
http://stackoverflow.com/questions/38380912/why-is-my-video-or-videosphere-not-playing-on-mobile-in-a-frame-vr
