### ISSUE TITLE
Setting of shortcut icon / favicon

### ISSUE THREAD

**Issue by chriscar** [aframevr/aframe#1450]
I think it would be better to not set the A-Frame favicon per default. If I set the favicon in HTML, sometimes the A-Frame icon and sometimes my own icon show up.

- A-Frame Version: 0.2.0
- Platform/Device: Google Chrome

**Comment by ngokevin** [comment]
Where is this happening?

**Comment by chriscar** [comment]
http://dev2.ideaspacevr.org/testing

**Comment by ngokevin** [comment]
We don't set any favicon iirc

**Comment by donmccurdy** [comment]
Also being set in [this demo](https://sandbox.donmccurdy.com/vr/walking/) - 

https://github.com/aframevr/aframe/blob/faddf6f3323cf634f3d5c68837eb4b39ad0fd064/src/core/scene/metaTags.js#L9

(i don't have my own favicon set though, so in my case I don't mind A-Frame providing the icon)

**Comment by chriscar** [comment]
I the only reference to the A-Frame logo is:

```
var MOBILE_HEAD_TAGS = module.exports.MOBILE_HEAD_TAGS = [
  Meta({name: 'viewport', content: 'width=device-width,initial-scale=1,maximum-scale=1,shrink-to-fit=no,user-scalable=no,minimal-ui'}),

  // W3C-standardised meta tags.
  Meta({name: 'mobile-web-app-capable', content: 'yes'}),
  Meta({name: 'theme-color', content: 'black'}),
  Link({rel: 'icon', sizes: '192x192', href: 'https://aframe.io/images/aframe-logo-192.png'})
];
```

**Comment by ngokevin** [comment]
OK, we should probably remove that.

**Comment by cvan** [comment]
if you set a `<link rel="icon">`, we won't inject our own. is this an issue?

**Comment by alexcheninfo** [comment]
I'm having the same problem. And the favicon is stuck in my app, I can't use my own. I've cleaned my cache and tried everything. Strangely, this only happens in Firefox and IE. I explain the issue here: http://stackoverflow.com/questions/37312783/favicon-only-showing-up-in-chrome

**Comment by cvan** [comment]
@alexcheninfo sorry about this. opened PR #1477. it should get merged very soon 😄

**Comment by alexcheninfo** [comment]
@cvan Okay, thanks for the quick reply!

**Comment by tomsride** [comment]
Hi, I still have this issue on all my iOS browsers on a iPad (Chrome, Mozilla and Safari). I have set 
    <link rel="icon" href="design/xyz.png">
on the head - and it seems to overwrite it.
