### ISSUE TITLE
Animationend event cannot be listened to in a component

### ISSUE THREAD

**Issue by chriscar** [aframevr/aframe#1451]
this.el.addEventListener('animationend', function() {

});

does not work in a component. Even not in a component assigned to an a-animation entity.

Whereas

document.addEventListener('animationend', function() {

});

works anywhere.

- A-Frame Version: 0.2.0
- Platform/Device: all

**Comment by ngokevin** [comment]
Animations don't take components. I imagine this will work:

```html
<ent yourlistener>
  <anim/>
</ent>
```
