### ISSUE TITLE
consider renaming geometry.primitive to geometry.type

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1457]
**Description:**

With the `registerGeometry` API, a variety of geometries can be registered that won't have to be geometric primitives (e.g., text, extrude, svg)

Smaller reasons would consistency with three.js API as Geometry objects have a `type` and simpler wording.

**Comment by donmccurdy** [comment]
This sounds more consistent to me, but isn't `type` reserved?

**Comment by msimpson** [comment]
@donmccurdy 
Doesn't seem to be according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_keywords_as_of_ECMAScript_6).

**Comment by donmccurdy** [comment]
@msimpson haha oh, right – well not reserved by the language, by otherwise employed by the schema definition: https://aframe.io/docs/core/component.html#Schema

would be a breaking change, but i suppose the schema could use `__type` instead

**Comment by msimpson** [comment]
@donmccurdy 
Oh ... missed that.

**Comment by ngokevin** [comment]
Or alternatively if we detect an attribute that is not type/default/parse/stringify, then we switch it to multi-property.

**Comment by ngokevin** [comment]
Actually, `type` is not reserved. If `type`'s value is a string, then it will be single-prop. If it is an object `type: { type: 'string' }` then it is multi-prop.

**Comment by dmarcos** [comment]
I think type is ambiguous and carries a different meaning in a programming context. Primitive is commonly used in many 3D packages: [3D Studio] (http://docs.autodesk.com/3DSMAX/15/ENU/3ds-Max-Help/files/GUID-66152BDE-BA64-423F-8472-C1F0EB409E16.htm), [Maya] (https://knowledge.autodesk.com/support/maya-lt/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/MayaLT/files/GUID-6D21314A-54AD-41D4-AFC0-AAED13CD50A6-htm.html), [Blender] (https://wiki.blender.org/index.php/Doc:2.4/Manual/Modeling/Meshes/Primitives)

**Comment by ngokevin** [comment]
In 3D programs, the word primitives is used to create geometric primitives, yes. But three.js geometries don't have to be geometric primitives. 

It's what three.js refers to their geometry types. No one is going to confuse geometry component type with programming types. Better the possibility of being ambiguous than being incorrect anyways.

**Comment by dmarcos** [comment]
type is not descriptive enough in this context. let's move on

**Comment by ngokevin** [comment]
I made points and counterpoints. If you want to close it, it would be copacetic to address them rather than brushing them off.

**Comment by dmarcos** [comment]
I think renaming does not bring any benefit. it's changing for the shake of changing and type is a very ambigous word and used in other contexts. primitive is a common word used in computer graphics https://en.m.wikipedia.org/wiki/Geometric_primitive

**Comment by ngokevin** [comment]
OK. The main exception I was thinking of was text, SVG, and extrude, but if they're the minority, and we're okay with `<a-entity geometry="primitive: text">`, this isn't too big of a deal.

**Comment by dmarcos** [comment]
text should probably be a separate component.

**Comment by dmarcos** [comment]
and svg as well

**Comment by ngokevin** [comment]
You could, but then you don't get free geometry merging, caching, buffering, and automatic memory management provided by the geometry component.
