### ISSUE TITLE
"translate" attribute has no effect

### ISSUE THREAD

**Issue by iKoala** [aframevr/aframe#1461]
No matter which value I set to translate, it has no effect.

`<a-box color="#FFF" radius="3"
position="0 0 0"
roughness="10"
translate="0 5 0"></a-box>`

- A-Frame Version: #master/dist/aframe.js
- Platform/Device: Chrome on Mac

**Comment by msimpson** [comment]
@iKoala 
Hmm. I can't seem to find any evidence in the code that this would have ever worked. There don't seem to be any geometries which actually support the translate property.

**Comment by iKoala** [comment]
@msimpson Thanks for the information, I think it's the reason which translate property doesn't work.
I didn't notice this change because I tested the same code with 0.2 version and it worked fine but it doesn't work in master branch.
Now I have to find out how to work with the pivot point but I can't any document related to the new pivot point changes.

**Comment by msimpson** [comment]
@iKoala 
I found an example in `aframe/examples/animation/pivots/index.html` that ngokevin added since the change. That may give some insight, but there doesn't seem to be any updated documentation as of yet.

**Comment by iKoala** [comment]
@msimpson 
Thanks again! I am closing this because I think this isn't a real issue.
