### ISSUE TITLE
Consider allowing configurable systems with schema

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1464]
**Description:**

Allow configuration of systems through the DOM like we have for components. 

For example to adjust physics gravity `<a-scene physics="gravity: 9.8">`

Or Websocket server `<a-scene multiuser="http://myserver.5000">`

**Comment by ngokevin** [comment]
Currently, all systems are initialized before the scene has initialized. So systems currently cannot do `getAttribute` to retrieve data. Having a schema and data initialization in place would allow systems to access scene data. Having this issue with the broadcast component+system

**Comment by wizgrav** [comment]
maybe a proxy component could handle this by passing it's data to the system when the component inits?

**Comment by donmccurdy** [comment]
I'm using a proxy component (exactly like @wizgrav's suggestion) for physics. Works OK but that means the system will be only half-initialized while its components are loading. One possible fix would be initializing a-scene components before the rest (is there a defined order now?).

**Comment by msimpson** [comment]
> is there a defined order now?

I was curious about this, myself.

**Comment by wizgrav** [comment]
Explicit ordering for the initialization order of components is not implemented yet but there's a relevant discussion about it here https://github.com/aframevr/aframe/issues/1152

**Comment by ngokevin** [comment]
Yeah, I have been using proxy components as well. 

I think we do initialize systems before components ATM.

A schema would solve problems.
