### ISSUE TITLE
<scene debug> should work. But only <scene debug="true"> works

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1466]
**Description:**

debug mode enables serialization of component data to the DOM. if this is on, you will be able to see DOM updates like with animations or setAttributes. This is done in `<a-entity>` code. Grep for  `isDebugMode`

- A-Frame Version: master

**Comment by dmarcos** [comment]
We should fix the single property parsing to return the default value if the corresponding DOM attribute is an empty string
