### ISSUE TITLE
Error in Aframe.io doc (entity.html) 

### ISSUE THREAD

**Issue by kliang3** [aframevr/aframe#1470]
Example for getComputedAttribute (attr) is incorrect. It reads 
   `entity.getAttribute('geometry')`
when it should be 
   `entity.getComputedAttribute('geometry')` 

- A-Frame Version: 0.2.0
- Platform/Device:

**Comment by ngokevin** [comment]
Thanks for catching. Can you click edit on github at bottom of docs page
