### ISSUE TITLE
be able to control `tick` order

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1480]
**Description:**

@donmccurdy's controls API needs to ensure that `controls` to run before `velocity`. I believe this is common in game engines to do stuff in certain order like physics, drawing, inputs.

**Comment by dmarcos** [comment]
We can use the dependencies API to express that.

**Comment by ngokevin** [comment]
So when we add a behavior, internally sort it based off dependency tree? Might get hairy when you have complex dependencies and there is no good ordering to put it. 

`tickPriority: 2` might be more easier to reason. At least, it'd be simpler to implement than a sorting algorithm. And we can store it easily `behaviors: {0: [components with tick 0], 1: [components with tick 1]}`

**Comment by dmarcos** [comment]
The behaviors API does not solve either the case of complex dependencies. You will have to have a sorting logic that resolves priority conflicts with several components depending on a common dependency. I think the logic would be as complicated as the implicit sorting based on the dependency tree.

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe/issues/2186
