### ISSUE TITLE
Request: Apply single-value scale attribute should apply to X,Y & Z

### ISSUE THREAD

**Issue by flukeout** [aframevr/aframe#1481]
**Description:**
If I want to make my object half of its original size, it would be nice to set the scale attribute as one value like ``scale=".5"``. Currently this will only scale the object along the X axis, so I have to use ``scale=".5 .5 .5"``. I think it would be handy if there is only a single value to assume that it is meant to apply to all three axes.

- A-Frame Version: Latest
- Platform/Device: Desktop Chrome

**Comment by ngokevin** [comment]
Thanks for filing. This is also filed at https://github.com/aframevr/aframe/issues/451
