### ISSUE TITLE
Keyboard controls can become sticky

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#1484]
When moving around with ASWD controls, it's easy to accidentally hit caps lock or shift.   This dispatches a different `keyCode` and causes the previous keypress to become sticky.

See:
https://github.com/aframevr/aframe/blob/master/src/components/wasd-controls.js#L146

Maybe we should use the char instead?

- A-Frame Version: https://github.com/aframevr/aframe/commit/71896dd3c9ecb58737534cb3f901297c748f7855
- Platform/Device: desktop

**Comment by ngokevin** [comment]
Was also filed at https://github.com/aframevr/aframe/issues/1479

**Comment by caseyyee** [comment]
Oops yes!
