### ISSUE TITLE
Sometimes textures are not displayed on Chrome mobile.

### ISSUE THREAD

**Issue by justvova** [aframevr/aframe#1488]
**Description:**
When you first open the page , some objects are displayed without texture using Chrome Mobile for Android . When updating page bug disappears .
Textures disappear at random : there is no connection between the object geometry or shader type and bug.
Most often disappears texture element <a-sky>. With the disappearance of the texture object becomes white.

In version 0.1 a bug wasn't observed.
- A-Frame Version:0.2
- Platform/Device:Android 5 and 6 / Xperia Z / Samsung galaxy S7 Edge

**Comment by dmarcos** [comment]
Can you provide an example?

**Comment by dmarcos** [comment]
I'm no able to reproduce this. @justvova please reopen if you can provide a test case that illustrates the problem.
