### ISSUE TITLE
Allow `<a-event>` to be used inside `<a-asset-item>`

### ISSUE THREAD

**Issue by msimpson** [aframevr/aframe#1489]
This may have been requested before, but I can detail a complete use case which may be helpful for further discussion. @ngokevin recently added the `data` attribute to his `aframe-template-component` to help solve my JSON loading scenario. Given that addition, I was able to reach the following solution:
```
AFRAME.registerComponent('manifest', {
  schema: {
    src: { default: '' },
    assets: { default: [] }
  },

  init: function () {
    var el    = this.el;
    var data  = this.data;
    var name  = data.src.substr(1);
    var asset = document.querySelector(data.src);

    asset.addEventListener('loaded', function() {
      data.assets = JSON.parse(asset.data).assets;
      el.setAttribute('template', 'src: #images; data: manifest');
    });
  }
});
```
```
<a-scene>
  <a-assets>
    <a-asset-item id="manifest-data" src="assets/manifest.json"></a-asset-item>
    <script id="images" type="text/x-nunjucks-template">
      {% for i in range(0, assets.length) %}
        <a-image src="assets/images/{{ assets[i] }}"></a-image>
      {% endfor %}
    </script>
  </a-assets>

  <a-entity position="0 0 0" manifest="src: #manifest-data"></a-entity>
</a-scene>
```
But as you can see, I'm forced to attach the `template` component only after the `mainfest-data` asset has actually loaded due to the timing of the `template` components rendering. This is understandable given what it accomplishes, however the need for the `manifest` component to act as a `loaded` and data bridge could be reduced, and eventually removed, if `<a-event>` was usable inside an `<a-asset-item>`. The result would become more like this:
```
<a-scene>
  <a-assets>
    <a-asset-item id="manifest-data" src="assets/manifest.json">
      <a-event name="loaded" target="#container" template="src: #images; data-src: #manifest-data"></a-event>
    </a-asset-item>
    <script id="images" type="text/x-nunjucks-template">
      {% for i in range(0, assets.length) %}
        <a-image src="assets/images/{{ assets[i] }}"></a-image>
      {% endfor %}
    </script>
  </a-assets>

  <a-entity id="container" position="0 0 0"></a-entity>
</a-scene>
```
Of course the `data-src` attribute would need to be added to the `template` component as well, but allowing events in this manner would be a step in the right direction. Also, I have only scratched the surface in regard to asset loading in this framework. So this may not even be possible given the lifecycle at hand.

**Comment by ngokevin** [comment]
I created a `template-set` component: https://github.com/ngokevin/staryu/blob/master/components/template-set.js when I was loading data from an API.

https://github.com/ngokevin/staryu/blob/master/index.html#L26

**Comment by msimpson** [comment]
@ngokevin 
Thanks for the quick reply. I'll use that pattern, instead. You should publish that separately, too; it's quite useful.

**Comment by ngokevin** [comment]
Yeah, I guess I can add it as sugar to the template component.
