### ISSUE TITLE
Asset uploader failing to upload

### ISSUE THREAD

**Issue by jremi** [aframevr/aframe#1495]
**Description:**
I am trying to upload assets using the asset uploader but getting failure. 

Just says, "Can't Upload"

What am i doing wrong?

If someone wants to utilize A-Frame and will need to have on-going assets uploaded, what is the best option to do this? I would like to just upload them to my Amazon S3 and then have A-Frame look at them as the src for when using for example <a-sky> tag, but seems to produce CORS issue.

**Comment by jremi** [comment]
Nevermind I got it working!

**Comment by ngokevin** [comment]
What'd you do?

**Comment by jremi** [comment]
I was unable to get the asset uploader to work.... I ended up uploading my panorama images to Amazon S3 and was able to use them as the src and this worked fine.

**Comment by dmarcos** [comment]
@cvan any ideas?
