### ISSUE TITLE
component data for scene not parsing when doing getAttribute

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1496]
**Description:**

`<a-scene mycomponent="a: 1; b: 2">`

`sceneEl.getAttribute('mycomponent')` returns a string

- A-Frame Version: master
- Platform/Device:

**Comment by dmarcos** [comment]
It seems to work for me on current master:

![Parsing](https://s3.amazonaws.com/f.cl.ly/items/2P2m3U1j1r0z3I0j2w2B/Image%202016-06-02%20at%2010.35.08%20AM.png?v=ea5ae139)

**Comment by ngokevin** [comment]
This is for the scene.

**Comment by ngokevin** [comment]
I think I was trying to do this for systems. https://github.com/aframevr/aframe/issues/1464 is the solution
