### ISSUE TITLE
Aframe fails to initialize a-scene with HTML Imports

### ISSUE THREAD

**Issue by Pupix** [aframevr/aframe#1498]
Hello!
While trying to import `aframe.js` through HTML Imports the following error pops up when trying to use an `<a-scene>`:
```
Uncaught TypeError: scenes[i].initSystem is not a function                       aframe.js:57800
```

[Here's a plunker with the reproduction.](https://plnkr.co/edit/h0flsQImNllFLWskNkde?p=preview) Open console to see the error.

Cheers.

- A-Frame Version: 0.2.0
- Platform/Device: Chrome 50 / Windows 10

**Comment by msimpson** [comment]
Not so sure this will happen considering, "[Firefox will not ship HTML Imports.](https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports)"

More information:
https://bugzilla.mozilla.org/show_bug.cgi?id=877072#c89
https://platform-status.mozilla.org/#html-imports

**Comment by trusktr** [comment]
Yep, Custom Element imported via JavaScript are the way to go!

**Comment by ngokevin** [comment]
Yeah, no HTML Imports coming.

Also try https://github.com/ngokevin/aframe-template-component which can load external HTML.
