### ISSUE TITLE
Cannot set property target  at  "use strict" mode 

### ISSUE THREAD

**Issue by reutopiaer** [aframevr/aframe#1516]
**Description:**
src/utils/index.js:21 Uncaught TypeError: Cannot set property target of #<Event> which has only a getter
- A-Frame Version:  0.1.6
- Platform/Device:window10/chrome

**Comment by dmarcos** [comment]
@reutopiaer How did you get that error message? Can you provide an example? Can you try with aframe 0.2.0?

**Comment by dmarcos** [comment]
@reutopiaer Please reopen if you can provide additional information
