### ISSUE TITLE
Trigger animation by another entity

### ISSUE THREAD

**Issue by yairbr** [aframevr/aframe#1517]
Hi, 
I am trying to trigger animation of an entity by clicking on another entity.
What i am really trying to create is some tool-tip when my cursor hover on an entity.
Is there a way to perform that?

thanks.

**Comment by ngokevin** [comment]
You could write a component that emits an event on another entity when you receive a certain event:

```html
<a-event event-pass="on: click; emit: show-tooltip; target: #my-target">
```

https://aframe.io/docs/core/component.html
