### ISSUE TITLE
the model file render will get an error on cursor hover

### ISSUE THREAD

**Issue by PromeYang** [aframevr/aframe#1518]
**Description:**

```
<a-assets>
    <a-asset-item id="untitled-scene" src="model/untitled-scene.dae"></a-asset-item>
</a-assets>
<a-entity collada-model="#untitled-scene">
    <a-event name="mouseenter" scale="4 1 6"></a-event>
</a-entity>
```

Uncaught TypeError: Cannot read property 'emit' of undefined

at line 57766

emitEvents	@	aframe.js:57766
tick	@	aframe.js:57764
(anonymous function)	@	aframe.js:61484
value	@	aframe.js:61482
value	@	aframe.js:61507

- A-Frame Version: 2.x
- Platform/Device: all

**Comment by ngokevin** [comment]
dupe/fixed on master https://github.com/aframevr/aframe/pull/1497
