### ISSUE TITLE
Consider adding `on-end` and `on-compete` properties to `<a-animation>`

### ISSUE THREAD

**Issue by msimpson** [aframevr/aframe#1530]
Both `animationstart` and `animationend` are essentially useless without a proxy component to dive into the event data. You simply cannot employ either of these events in a sane manner from the `begin` or `name` properties of the `<a-animation>` or `<a-event>` elements, respectfully.

Therefore, I propose adding an `on-end` and `on-complete` to the `<a-animation>` element. The `on-complete` property specify one or more event names which emit using the same logic as `animationend`. While `on-end` would specify on or more event names which emit `onStop` of the internal `Tween`, only; covering those animations which ended abruptly via the new `end` property of the `<a-animation>` element.

If this is agreeable, I can craft a PR.

**Comment by ngokevin** [comment]
For now, I think I'd rather we create a general event-proxying component than add more features into the animation system. That component might be useful in other cases. I feel the animation system right now is becoming unsustainable.

**Comment by msimpson** [comment]
Okay. I'll try to attach the problem from that direction, instead.

**Comment by msimpson** [comment]
@ngokevin FYI, this is what I'm using now:
```
  document.registerElement('a-event-proxy', {
    prototype: Object.create(AFRAME.ANode.prototype, {
      attachedCallback: {
        value: function() {
          this.el = this.parentNode;
          this.el.addEventListener(this.getAttribute('name'), this.handler.bind(this));
        }
      },

      handler: {
        value: function(event) {
          var conditions = this.getAttribute('matches');
          if (conditions) conditions = AFRAME.utils.styleParser.parse(conditions);
          for (key in conditions) 
            if (event.detail.target.getAttribute(key) === conditions[key])
              this.emit(this.getAttribute('emit'));
        }
      },

      detachedCallback: {
        value: function() {
          this.el.removeEventListener(this.getAttribute('name'), this.handler);
        }
      }
    })
  });
```
```
<a-animation begin="fade-out" attribute="material.opacity" fill="forwards" from="1" to="0" dur="2000"></a-animation>
<a-animation begin="fade-in"  attribute="material.opacity" fill="forawrds" from="0" to="1" dur="100"></a-animation>
<a-event-proxy name="animationend" matches="begin: fade-out" emit="fade-in"></a-event-proxy>
```

**Comment by ngokevin** [comment]
I recommend trying to go through the component system. It is less asynchronous (going through the DOM system), becomes composable, and is easier to work with since you can just do `setAttribute` rather than `createElement + append + setAttributes + wait`.

**Comment by msimpson** [comment]
Can you place a components on `<a-animation>` elements? If so, that would be perfect in this case.

**Comment by ngokevin** [comment]
Nope. `animationend`/`animationstart` events bubble so they should be available to listen to on the parent entity. To select tie the proxying to the specific animation, you could maybe use a selector.

**Comment by msimpson** [comment]
Okay. I'll give that a go, instead.
