### ISSUE TITLE
Mesh: Cone doesn't render properly

### ISSUE THREAD

**Issue by h0r0man** [aframevr/aframe#1534]
*Blender:*

<img width="633" alt="screen shot 2016-06-02 at 20 21 54" src="https://cloud.githubusercontent.com/assets/2571888/15756054/cf69cfc8-28ff-11e6-9476-dfe037031038.png">

*Aframe:*

<img width="822" alt="screen shot 2016-06-02 at 20 22 32" src="https://cloud.githubusercontent.com/assets/2571888/15756057/d2a98ac0-28ff-11e6-8f43-b6efc6f3e06c.png">

If you want to recreate the issue using Blender: Create > Cone > File > Export > COLLADA > Export Data Options > Selection Only

- A-Frame Version: 0.2.0
- Platform/Device: Google Chrome 50 (Desktop OS X)
- Blender: 2.77

**Comment by dmarcos** [comment]
It exports properly for me following your instructions. Make sure that you don't have any strange illumination in your blender scene.
<img width="822" alt="screen shot 2016-06-02 at 20 22 32" src=https://s3.amazonaws.com/f.cl.ly/items/2i171Q1F0F3p0X2m0B1b/Image%202016-06-24%20at%201.17.21%20PM.png">

Please reopen if you have any additional information
