### ISSUE TITLE
Camera position is set each frame even with no movement

### ISSUE THREAD

**Issue by tbalouet** [aframevr/aframe#1535]
In the "wasd-controls" component, the update function retrieves a movementVector, and update the camera in consequence. But it doesn't check if the movement vector is null, in which case the camera position shouldn't be affected, right?

It's starting line 58500 in dist/aframe.js

- A-Frame Version: tot
- Platform/Device: google chrome 50

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/1904
