### ISSUE TITLE
______BufferGeometry ➡️  BufferGeometry change breaking extras physics

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#1538]
Question related to #1338, I follow that BufferGeometry is more efficient than standard Geometry, but, why is creating a BoxGeometry first and converting it to BufferGeometry better than just creating a BoxBufferGeometry? Are the _____BufferGeometry subclasses less efficient than BufferGeometry?

Physics for aframe-extras have broken against aframe/master – [I construct CANNON.Shape instances by looking at the THREE.js geometry](https://github.com/donmccurdy/aframe-extras/blob/master/lib/CANNON-mesh2shape.js#L29-L50) type. ____BufferGeometry is useable, but there's not much to go on with plain BufferGeometry instances.

**Comment by donmccurdy** [comment]
If BufferGeometry really is preferable, we could work around this by preserving the original `geometry.parameters` values (geometry type, cylinder radius, etc.) in the new geometry's `userData`.

**Comment by ngokevin** [comment]
There is a `buffer: false` option, but preserving the original geometry data sounds harmless. Let's do it.
