### ISSUE TITLE
Different texture quality in release/v0.2.0 and master branch

### ISSUE THREAD

**Issue by iKoala** [aframevr/aframe#1541]
I tried to play with the [Composite Example](https://aframe.io/examples/showcase/composite/) in the project and found that texture quality is different between the v0.2.0 release version and master branch when in VR Mode on Mobile, both iOS and Android.

In release/v0.2.0, the texture quality is fine and working properly in VR Mode on Mobile.
In master branch, the texture quality is downgraded and all images are blur in VR Mode on Mobile.

I made two html pages which have the same source code but includes the two different versions of Aframe framework.

- A-Frame Version: v0.2.0
- Platform/Device: VR Mode on Mobile
- Description: Fine texture quality
- [Composite Example with release/v0.2.0](http://bit.ly/1U8Zk8r)

---

- A-Frame Version: master branch
- Platform/Device: VR Mode on Mobile
- Description: Texture quality is downgraded, images are blur
- [Composite Example with branch/master](http://bit.ly/1UCAqg0)

**Comment by ngokevin** [comment]
Something to do with pixel ratio or the WebVR polyfill.

**Comment by ngokevin** [comment]
Was able to fix this by modifying VREffect to use `window.devicePixelRatio` instead of `1`. Not sure the implications or intentions though.

**Comment by cvan** [comment]
@dmarcos was wrestling with this. I think he knows what's up. and there's some discussion in the [webvr-polyfill issues](https://github.com/borismus/webvr-polyfill/issues) too.

**Comment by ngokevin** [comment]
I was able to fix it by changing the BUFFER_SCALE to 1 and having VREffect use the set pixel ratio. But need to compare performance.

**Comment by iKoala** [comment]
May I have some sample code on how to change BUFFER_SCALE without modifying the source code?
Thanks in advance!

**Comment by iKoala** [comment]
@ngokevin Thanks for the response and code fix, however, I found it doesn't really solve the issues. I take 3 screenshots for your comparisons.

Composite example with release/v0.2.0:
![composite-v0 2](https://cloud.githubusercontent.com/assets/1382555/16764491/0bd31976-4861-11e6-903a-fcf23daacaf4.png)

Composite example with master + fix pixel ratio:
![composite-master fix](https://cloud.githubusercontent.com/assets/1382555/16764511/1d65e128-4861-11e6-938e-a910c1efeed4.png)

Composite example with master (no fix pixel ratio patch):
![composite-master nofix](https://cloud.githubusercontent.com/assets/1382555/16764519/284e85d6-4861-11e6-80fe-8e1ca0ad1014.png)

**Comment by ngokevin** [comment]
@mkungla has been doing some investigation and said:

> Problem with The Perspective cameras and how these are created and updated

> And function fovToProjection, fovPortToProjection, fovToNDCScaleOffset do not give exact results they should always

> Problem with The Perspective cameras and how these are created and updated

> And function fovToProjection, fovPortToProjection, fovToNDCScaleOffset do not give exact results they should always

>  As I see then 0.2.0 you used `THREE.StereoCamera` instead of `THREE.VREffect`

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/1701

**Comment by dmarcos** [comment]
#1701 has addressed the issue.

**Comment by ngokevin** [comment]
Continued https://github.com/aframevr/aframe/issues/1735
