### ISSUE TITLE
0.2.0 Docs - broken formatting

### ISSUE THREAD

**Issue by armthethinker** [aframevr/aframe#1542]
Two of the pages in the 0.2.0 docs are wrongly formatted. They have been fixed on the master branch. Github won't let me change them when I'm looking at the 0.2.0 tag, because I'm not on a branch. If someone points me in the right direction, I'm happy to fix it.

[https://aframe.io/docs/0.2.0/primitives/a-ring.html](https://aframe.io/docs/0.2.0/primitives/a-ring.html)
[https://aframe.io/docs/0.2.0/components/geometry.html](https://aframe.io/docs/0.2.0/components/geometry.html)

- A-Frame Version: 0.2.0

**Comment by ngokevin** [comment]
Yeah. When we versioned the docs, this was the compromise, not easily being able to push small revisions. We can fix this by updating the tag with the fixes. Perhaps I will have to do a weekly manual update...

**Comment by ngokevin** [comment]
We might have to just leave 0.2.0 like that, but 0.3.0 going forward we are cherry-picking fixes
