### ISSUE TITLE
Introduce event/Promise for when `THREE.VREffect` is done querying VR displays

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1546]
**Description:**

It's possible that you may call `scene.enterVR()` and it won't work because [`THREE.VREffect`](https://github.com/mrdoob/three.js/blob/fdca37f/examples/js/effects/VREffect.js) hasn't finished [its async logic](https://github.com/mrdoob/three.js/blob/fdca37f/examples/js/effects/VREffect.js#L49-L58).

This means that when you try to call `scene.enterVR()`, it calls `this.effect.requestPresent()`, which throws `No VR hardware found.`.

I have to actually call `navigator.getVRDisplays` myself and hope that when that resolves, `THREE.VREffect`'s `navigator.getVRDisplays` call has resolved and the `VRDisplay`(s) are detected and ready to be used.

https://github.com/aframevr/aframe/blob/f43ad9bd/src/core/scene/a-scene.js#L217
- A-Frame Version: f43ad9bd
- Platform/Device: all

**Comment by ngokevin** [comment]
Marked help wanted to just add `rendererready` event at the end of setupRenderer.

**Comment by ngokevin** [comment]
vr effect no longer used
