### ISSUE TITLE
Create a `torus` primitve

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#155]
https://github.com/MozVR/aframe-core/blob/93f1bdc/src/components/geometry.js#L88-L92

**Comment by CodingFree** [comment]
I think that this is fixed:
    <a-entity geometry="primitive: torus" position="1.5 3 0"></a-entity>
Result:
![Torus](http://imgur.com/lbYjR1J.png)

**Comment by dmarcos** [comment]
Yep. We already have a torus

**Comment by dmarcos** [comment]
Reopening. We do have a torus primitive geometry but this issue refers to a primitive ```a-torus```
