### ISSUE TITLE
getComputedAttribute fails when called from a system init method

### ISSUE THREAD

**Issue by amberroy** [aframevr/aframe#1561]
`getComputedAttribute` returns the same thing as `getAttribute` when called from a system `init` method.  

Reason for this behavior is `a-entity.getComputedAttribute` only applies mixins and defaults if the attribute is a component.  It checks if the attribute is a component via `this.components`, and the components haven't been attached yet when system `init()` is run.  

Or maybe this is intended behavior, and the workaround is to not rely on schema defaults when accessing a component via a system?

**Comment by ngokevin** [comment]
removed getComputedAttribute
