### ISSUE TITLE
Compatible devices for VR mode

### ISSUE THREAD

**Issue by mrtomnguyen** [aframevr/aframe#1562]
**Description:**
just curious about when tablets like Nexus 7 will be supported for VR mode.
currently, there is misalignment between the split screens. I'm assuming bc its not supported yet.

- A-Frame Version: 0.2.0
- Platform/Device:
Nexus 7 - Android 6.0.1

**Comment by dmarcos** [comment]
What do you mean by misalignment between split screens? Anyways, I don't think VR mode is useful in a tablet form factor. There are no holders in the market that fit tablets.

**Comment by mrtomnguyen** [comment]
I have the Dive 7 using with Nexus 7. 
In VR mode, i see double. Can't seem to get it aligned. Ive tested with other VR sites and they work. 
Just wanna confirm that this is something related to the framework.

**Comment by tinchoforever** [comment]
+1 On Nexus 7, en Chrome I see not only the Vr Mode but also I'm not able to move using gyroscope :(
I have a patch to detect Tablet, but is not enough for using the gyroscope, any Ideas?

**Comment by tinchoforever** [comment]
Actually this happens on a Nexus 9 too.

**Comment by tinchoforever** [comment]
http://codepen.io/tinchoforever/pen/ZLyEbj  This on a tablet (nexus 7 or 9) or Ipad should be 1) Enabling by default devicemotion camera 2) on vr mode, go full screen. On Aframe 2.0, 1) works and 2) says your device doesn't support webvr mode.  I have been checking Google WebVr Poly and it works there perfectly. My guess is that this is something inside how Aframe decides to use VR Mode and Gyroscope Control of the Camera by default.

**Comment by tinchoforever** [comment]
And here with Aframe 2 
http://codepen.io/tinchoforever/pen/ggROwL

**Comment by tinchoforever** [comment]
Aframe 4
![aframe-4](https://cloud.githubusercontent.com/assets/719504/22203403/acb54944-e14b-11e6-81d3-f91fe1efd0aa.gif)
Aframe 2 
![aframe-2](https://cloud.githubusercontent.com/assets/719504/22203404/acb68f66-e14b-11e6-977a-a68580f60e8f.gif)

**Comment by tinchoforever** [comment]
In Aframe 4, I'm only enable to move the camera using touch but no movement.

**Comment by tinchoforever** [comment]
The expected behavior should be
1) Vr Mode should go to full screen on tablets.
2) Moving camera with Device Motion should be default on tablets too.

**Comment by tinchoforever** [comment]
I've opened a proper ticket for this. 
https://github.com/aframevr/aframe/issues/2309
