### ISSUE TITLE
Shader (Material Component) Doesn't Animate

### ISSUE THREAD

**Issue by softpunch** [aframevr/aframe#1563]
**Description:**
The shader component refuses to animate. 

For example:

```html
<a-sky color="#73F7DD" shader="standard">
<a-animation attribute="shader" begin="2000" from="standard" to="noise"></a-animation>
</a-sky>
```

When I run that, at 2000ms, nothing changes.

I've tried animating `attribute="material"` as well, with no luck.

I can animate other sky components, 
and each individual shader works fine as a sky component, 
but the shader type won't animate.

As a work-around, I can make a second sky entity with a different shader type and animate the visibility settings of each sky entity. However, I'm not sure if the invisible shader is costing GPU. 

Let me know if I'm missing something obvious here--I'm relatively new to A-Frame.

- A-Frame Version: 0.2.0
- Platform/Device: OSX 10.11, Chrome (Macbook Pro)

**Comment by ngokevin** [comment]
I don't think animations is the proper solution. Try creating a delay-set component:

```
AFRAME.registerComponent('delay-set', {
  schema: {
    component: {type: 'string'},
    delay: {default: 2000},
    property: {type: 'string'}
    value: {type: 'string'}
  }

  init: function () {
    var data = this.data;
    var el = this.el

    setTimeout(function () {
      el.setAttribute(data.attribute, data.property, data.value);    
    }, data.delay);
  }
});
```

```html
<a-sky color="#73F7DD" delay-set="component: material; property: shader; to: flat"></a-sky> 
```

**Comment by softpunch** [comment]
@ngokevin thanks for the suggestion, and I think you're right about a delay-set component.

However, I can't seem to implement the one you suggested. 
Tweaked a minor comma issues or two, but still no luck.
Tried using it on other components, which also didn't work.
I assume it's a minor error in the script somewhere? 

FYI: The component script is in the body of the page, above the a-scene.
(I registered another custom component in that area and it worked fine, 
I assume that's a reasonable way to do it.)

I super appreciate your help on this, by the way.

```html
<script>
AFRAME.registerComponent('delay-set', {
  schema: {
    component: {type: 'string'},
    delay: {default: 3000},
    property: {type: 'string'},
    value: {type: 'string'}
  },

  init: function () {
    var data = this.data;
    var el = this.el;

    setTimeout( function () {
      el.setAttribute(data.attribute, data.property, data.value);    
     }, data.delay);
  }
})
</script>
```
```html
<a-sky color="#73F7DD" delay-set="component: material; property: shader; value: noise"></a-sky> 
```

**Comment by ngokevin** [comment]
Oops, should be data.component, not data.attribute

```js
<script>
AFRAME.registerComponent('delay-set', {
  schema: {
    component: {type: 'string'},
    delay: {default: 3000},
    property: {type: 'string'},
    value: {type: 'string'}
  },

  init: function () {
    var data = this.data;
    var el = this.el;

    setTimeout( function () {
      el.setAttribute(data.component, data.property, data.value);    
     }, data.delay);
  }
})
</script>
```

**Comment by softpunch** [comment]
SWEET!

We are in business.

**Comment by ngokevin** [comment]
Nice. Found out GitHub comments are not a good environment for coding :)
