### ISSUE TITLE
`Fog: false` only works with `shader: flat`

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#1572]
**Description:**

I found that `fog: false` wasn't working with the following:

```html
 <a-scene fog="type: linear; color: #AAB; far: 30; near: 0">
    <a-entity geometry="primitive: sphere; radius: 50" material="src: url(../_skies/greencubes.png); side: back; fog: false;"></a-entity>
 </a-scene>
```

However, `<a-sky>` plus `material="fog: false"` *was* working, so I dug into the sky primitive [source](https://github.com/aframevr/aframe/blob/master/src/extras/primitives/primitives/a-sky.js), and found it was using `shader: flat`

So I added `shader: flat` to my entity, and everything works:

```html
<a-scene fog="type: linear; color: #AAB; far: 30; near: 0">
    <a-entity geometry="primitive: sphere; radius: 50" material="src: url(../_skies/greencubes.png); shader: flat; side: back; fog: false;"></a-entity>
</a-scene>
```

I feel we should call this out in the [docs](https://aframe.io/docs/0.2.0/components/fog.html).

- A-Frame Version: master
- Platform/Device: OSX El Capitan, Chrome 51

**Comment by ngokevin** [comment]
three.js says `fog` property should work with either material. Is it because of `side: back` vs. `scale="1 1 -1"?

**Comment by ngokevin** [comment]
OK, I see the problem. We weren't setting fog on MeshStandardMaterial despite documenting it.
