### ISSUE TITLE
How To  Load *.fbx File?

### ISSUE THREAD

**Issue by HUKE1987** [aframevr/aframe#1573]
**Description:** How To Load *.fbx

- A-Frame Version:0.2
- Platform/Device:chrome,firefox ie....

Thank You

**Comment by donmccurdy** [comment]
@HUKE1987 you'll probably want to convert it to another format, THREE.js support for `.fbx` is limited. You can do use a Blender to do this, or upload the model to Clara.io and export it as `.obj`, `.dae`, etc.

**Comment by dmarcos** [comment]
As @donmccurdy said. You should convert your FBX to a format better suited for real time applications. FBX was designed as an exchange format for design applications.
