### ISSUE TITLE
videoEl.crossOrigin should be set to 'use-credentials' instead of true?

### ISSUE THREAD

**Issue by Biao** [aframevr/aframe#1576]
https://github.com/aframevr/aframe/blob/54a171c4d1e145fe3e71713263c54b7229346fc3/src/systems/material.js#L262 
 https://github.com/aframevr/aframe/blob/54a171c4d1e145fe3e71713263c54b7229346fc3/src/systems/material.js#L292
This seems to prevent protected videos from loading.

**Comment by jcarpenter** [comment]
We hit this issue hosting prototypes w/ mp4's on Google Cloud Storage. Recommend either exposing as a setting, or setting default to `use-credentials`. I can't speak to potential downsides. Everything *seems* to work as expected with this config.
