### ISSUE TITLE
Videosphere cannot swipe down/up on mobile

### ISSUE THREAD

**Issue by xiaottang2** [aframevr/aframe#1577]
Please check [my demo site](http://www.watertalkgame.com:3000/demo.html)

As I was accessing the site using my iPhone6s(iOS9.3.2), I notice that I CANNOT swipe up/down to watch the video in a different angle, but I CAN swipe horizontally.

However, as you should notice, swiping up/down is ok when using desktop

Thank you

- A-Frame Version:  0.2.0
- Platform/Device:  iPhone6s(iOS9.3.2),

**Comment by dmarcos** [comment]
It's intentional. Letting the user move up and down on mobile becomes disorienting quickly in combination with the phone sensors. It also makes the scene unusable in a headset because the vertical axis won't match the real orientation of user's head.

**Comment by pandapondering** [comment]
I think it'll be useful to allow users without a headset to swipe up and down to look up and down. Is there a way to enable that ?
