### ISSUE TITLE
.gitattributes with export-ignore for release archives

### ISSUE THREAD

**Issue by mkungla** [aframevr/aframe#1578]
Shouldn't this repo use .gitattributes to have bit cleaner release archives?

**Possible contents could be:**
````
# Exclude git files and other files starting with .
.* export-ignore
# As in .npmignore
examples export-ignore
test export-ignore
````
> Besides these suggested above almost everything besides `dist` `LICENSE` and some essential files could be ignored, since that won't affect `npm` and usage of release archives becomes handy only when you want to use browser files in production. As in development you would never use release archives anyway!

- A-Frame Version: *
- Platform/Device: *

**Comment by ngokevin** [comment]
Good idea, could you add one for us?

**Comment by mkungla** [comment]
Sure

**Comment by mkungla** [comment]
Could be then

````
.* export-ignore
*.html
docs export-ignore
examples export-ignore
scripts export-ignore
src export-ignore
tests export-ignore
vendor export-ignore
package.json
ORGANIZATION.md
````

**Comment by mkungla** [comment]
See [Example Tag 0.2.0](https://github.com/mkungla/aframe/releases/tag/0.2.0) release archives for example what release archives would contain. I can create a pull request as soon it's confirmed that only `dist/*`,`README.md`, `LICENSE` should be included in release archives.
