### ISSUE TITLE
Consider aframe 0.2.1 release with updated Three.JS or other features?

### ISSUE THREAD

**Issue by richardanaya** [aframevr/aframe#1579]
There's some pretty detrimental bugs related to the version of threeJS that prevent proper material decoding of collada.

WebVR also doesn't work properly on the 0.2.0 release.

**Comment by dmarcos** [comment]
I suggest that you move to master that wil be 0.3.0 soon (1-2 weeks) We prefer to focus on getting 0.3.0 rather on a 0.2.1

**Comment by richardanaya** [comment]
Oh wow! That is soon. Thanks

**Comment by ngokevin** [comment]
Yeah, would be less overhead to go straight to 0.3.0. `master` is available in the meantime.
