### ISSUE TITLE
equirectangular photo is skewed. Not displaying correctly

### ISSUE THREAD

**Issue by mladenp** [aframevr/aframe#1580]
I imported equirectangular photo correctly but its displaying a little wrong, i can't explain whats wrong exactly but you can see it on screenshot.

Here is aframe version :http://imgur.com/Tg50DSt
And here is how it looks on Ricoh THETA website: http://imgur.com/eqfCzaV

Theta360 uses three.js and WebGL too but their image looks better.

**Comment by ngokevin** [comment]
It seems Ricoh knows how to orient the image based on EXIF data. You can adjust the rotation of the skysphere `rotation="0 0 30"` or something

**Comment by mladenp** [comment]
Ok, i'll try that, it definitely looks like that is my problem. 
Thanks, will report what i found.
