### ISSUE TITLE
setAttribute on a camera's rotation doesn't work

### ISSUE THREAD

**Issue by ammuench** [aframevr/aframe#1583]
Been trying to set rotation on a camera after it's been moved using setAttribute.  Every time I apply a value, be it a string ("0 0 0") or an object ({x: 0, y: 0, z: 0}), the value won't update or change.  Editing things like position work fine.  Rotation is the only one causing an issue

[Example](https://butt.githubusercontent.com/assets/2099658/16422311/8c0fb7c4-3d1d-11e6-9aca-d4bec1f1239f.png)

For reference, the HTML structure for Camera is:
```
<a-entity>
	<a-camera id="camera" position="0 1.75 2" rotation="0 0 0">
		<a-cursor color="#2E3A87"></a-cursor>
	</a-camera>
</a-entity>
```

- A-Frame Version: 0.2.0
- Platform/Device: Chrome 51.0.2704.103 (Official Build) (64-bit)

**Comment by ngokevin** [comment]
Try setting on a wrapper entity.

```html
<a-entity rotation="SET THIS"><a-camera></a-camera></a-entity>
```
