### ISSUE TITLE
Setting position or rotation by passing object into setAttribute does not work.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#159]
![image](https://cloud.githubusercontent.com/assets/1560884/11157953/9de21504-8a09-11e5-9c9c-6742145aec07.png)

Looks to be an issue only with template objects (eg. vr-cube)

Works fine on standard vr-object entities.

**Comment by staus** [comment]
Adding to this
If you set position like `camera.setAttribute('position', 'y: 1');` it'll result in `position="NaN 1 0"`

**Comment by fernandojsg** [comment]
@staus you could use ```camera.setAttribute('position','y',1);```

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
