### ISSUE TITLE
support dot-property: `setAttribute('material.color', 'red')`

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1592]
**Description:**

I've had to do this multiple times when I want a component to take a component property name in the form of dot syntax. I've had to repeat `split` behavior often.

- https://github.com/aframevr/aframe/blob/master/src/extras/primitives/registerPrimitive.js#L119
- https://github.com/aframevr/aframe/blob/master/src/extras/declarative-events/index.js#L91
- https://github.com/aframevr/aframe/blob/master/src/core/a-animation.js#L470
- https://github.com/aframevr/aframe/blob/master/src/core/a-animation.js#L525
- https://github.com/ngokevin/aframe-event-set-component/blob/master/index.js#L80

**Comment by dmarcos** [comment]
I think it breaks the API consistency and simplicity. There's already a way to change a property of a component. A function that takes a string argument and the behavior changes completely based on a `.` character is too much abuse and contortion.

**Comment by ngokevin** [comment]
How about a util?

**Comment by ngokevin** [comment]
I've had to do it for https://github.com/ngokevin/aframe-firebase-component/blob/master/index.js#L186 too.

```js
function setComponentProperty (el, attr, value, delimiter) {
   if delimiter in attr, split it, and set
   if delimiter not in attr, then do normal
}
```

**Comment by ngokevin** [comment]
Util complete

- AFRAME.utils.entity.setComponentProperty
- AFRAME.utils.entity.getComponentProperty
