### ISSUE TITLE
Consider standard interaction event names

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1593]
**Description:**

Earlier, I changed `click` to `cursor-click` for the cursor component to know where the event comes from.

But if we want to support multiple interaction mechanisms (mouse, gaze, controller), should we come up with standard event names such that developers only have to listen to one event (`click` vs. `cursor-click` + `trigger`)? Right now, we have "mousedown" even though you might not be using a mouse, should we keep those old names?

Example names:

- `cursor-click`, `trigger` -> `click`
- `cursor-mouseenter` -> `hoverenter`
- `cursor-mouseleave` -> `hoverleave`
- `cursor-mousedown` -> `clickdown`
- `cursor-mouseup` -> `clickup`

**Comment by donmccurdy** [comment]
I'm especially interested in controller events. That may need to be distinct from cursor/mouse events though. Oculus Touch controllers in unity include three types of events: [Button, Touch, and Near Touch](https://developer.oculus.com/documentation/game-engines/latest/concepts/unity-ovrinput/#unity-ovrinput-usage-buttontouchneartouch). 

I would imagine those translating to:

* `gamepadbuttondown` / `gamepadbuttonup`
* `controller-touchstart` / `controller-touchstop`
* `controller-neartouchstart` / `controller-neartouchstop`

Little verbose but meh. The "Near Touch" events potentially come into play with physics, where you want to be able to push objects around but also 'grab' them with a button press. Grabbing is hard if the thing rolls away every time you make contact. :)

**Comment by dmarcos** [comment]
yes, please standard event names. Those ```cursor-*``` have been bothering me.

**Comment by ngokevin** [comment]
What should we name them, should they interoperate with controller event names?
