### ISSUE TITLE
Problem injecting a new camera and keeping the default one

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe#1600]
**Description:** In the editor I inject a new camera entity that will be used as the perspective camera for the viewport. But I want to keep the default camera added in the scene, like most of the examples have.
But the problem is that the default camera will be deleted as soon as a new active camera appears in the scene:
https://github.com/aframevr/aframe/blob/4ca3b7c5b6b1c3c7bf6043cbbd40b80e7a423aab/src/systems/camera.js#L76

To test it, just opening one example and running the following code will change the new active camera and delete the default one:
```javascript
var editorCameraEl = document.createElement('a-entity');
editorCameraEl.id = 'editor-camera';
editorCameraEl.isEditor = true;
editorCameraEl.setAttribute('camera', {far: 10000, fov: 50, near: 1, active: true});
document.querySelector('a-scene').appendChild(editorCameraEl);
```

We should be able to keep the default camera somehow, ideas?

**Comment by ngokevin** [comment]
Perhaps the Editor can copy the camera and re-add it.

**Comment by fernandojsg** [comment]
I completely forgot about this. Yes, probably I'll just copy and readd it with some tag to prevent the editor to export it when saving the scene.
