### ISSUE TITLE
Cursor on Model crashes AFrame

### ISSUE THREAD

**Issue by msj121** [aframevr/aframe#1603]
**Description:**
Pretty much as a camera with cursor intersects a model the system fails. Tried it with simplified demo scene from the aframe.io website.

http://codepen.io/msj121/pen/AXrxkE

```
raycaster.js:98 Uncaught TypeError: Cannot read property 'emit' of undefinedemitEvents 
@ raycaster.js:98 tick 
@ raycaster.js:96 (anonymous function) 
@ a-scene.js:291 value 
@ a-scene.js:289 value 
@ a-scene.js:314
```
- A-Frame Version: Master
- Platform/Device: Chrome

**Comment by ngokevin** [comment]
Should be fixed now?

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/6be3725d548e5f071b0ec19a534d6235643ee525

**Comment by msj121** [comment]
Thanks
