### ISSUE TITLE
Phone orientation is not taken into account to move camera in tot version

### ISSUE THREAD

**Issue by tbalouet** [aframevr/aframe#1604]
**Description:**
When using the last version (top of tree) of aframe on mobile, the non-VR mode doesn't allow the user to move his phone around in "magic window" mode, you have to use your finger and moving up/down is not possible.
A version to check it out is here:
http://codepen.io/thomasbalou/pen/rLwQrY
- A-Frame Version:
top of tree
- Platform/Device:
Samsung Galaxy S6 with Chrome 51

**Comment by cvan** [comment]
I can confirm that your scene is broken Not sure which version you are using but it's not 0.2.0 and it's not master (`861c369`). Try https://github.com/aframevr/aframe/blob/master/dist/aframe.js / https://cdn.rawgit.com/aframevr/aframe/master/dist/aframe.js.

When I forked your scene and used `<script src="https://cdn.rawgit.com/aframevr/aframe/master/dist/aframe.js"></script>` instead, it worked on mobile.

I wish we included a `sha`, not just the `package.json` version in the bundle.

**Comment by tbalouet** [comment]
Indeed it does, maybe you fixed a bug in-between? Anyway everything's fine now, thanks!
