### ISSUE TITLE
WebVR Polyfill "No DPDB device match." error in Android webview

### ISSUE THREAD

**Issue by anthonybarsotti** [aframevr/aframe#1606]
I'm currently trying to get an Aframe project running in a React Native Webview and running into errors reminiscent of the ones discussed here: https://github.com/borismus/webvr-boilerplate/issues/111

I've tried this in three separate emulated devices (Nexus 5, Nexus 6P and Galaxy S6 all running Android 6.0) and each of them produce the following error stack:

![screen shot 2016-07-05 at 2 07 29 pm](https://cloud.githubusercontent.com/assets/4313386/16595303/892b69f0-42bc-11e6-874c-ea37fb0686d3.png)

**Comment by dmarcos** [comment]
The webvr polyfill uses a device database to determine the resolution that the polyfilled version of the `getEyeParamers` will return. The `navigator.userAgent` string must contain the device model name that matches the one in the database. In the case of a nexus 5 is `Nexus 5` (https://github.com/borismus/webvr-polyfill/blob/master/src/dpdb/dpdb-cache.js#L182)
It looks it's a problem with the polyfill database or your emulator not containing the correct device model name for those devices. There's nothing that we can do on the a-frame side.
