### ISSUE TITLE
Primitive defaults should not override mixins

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1609]
**Description:**

`<a-box mixin="red">` will be white because the default component will do a direct `setAttribute`

**Comment by ngokevin** [comment]
The code is in `src/extras/primitives/primitives.js`.

What we need to do is:

- On `attachedCallback` when we do the initial sync of attributes, we must check for mixins.
- Query selector for each mixin applied, and then you can do `mixin.componentAttrCache` to grab the properties that the mixin defines.
- Then we doing the initial sync of attributes, do **not** sync properties that are defined within the mixins.
- Tests.

Marked as `easy` meaning `help wanted`, but this level of issue is intermediate skill.

**Comment by dmarcos** [comment]
We can have another label `contribute` \ `contributor friendly` \`contributions welcome` and `easy` / `medium` / `hard`

**Comment by ngokevin** [comment]
Maybe, combined?

`helpwanted-easy`
`helpwanted-medium`
`helpwanted-hard`

**Comment by dmarcos** [comment]
we can use spaces in the labels. `help wanted (easy)` `help wanted (hard)`

**Comment by ngokevin** [comment]
Fixed
