### ISSUE TITLE
Collada Model Positions defer in Cardboard Mode

### ISSUE THREAD

**Issue by marcelvoss95** [aframevr/aframe#1612]
**Description:**
My Collada Model objects are displayed in different places depending on if i watch them in "normal" mode or in vr mode.
- A-Frame Version: Newest available in this repository
- Platform/Device: OnePlus 2, Chrome Browser

**Comment by ngokevin** [comment]
I think this is the issue: https://github.com/aframevr/aframe/issues/1715
