### ISSUE TITLE
Consider API to unset/reset a property: `removeAttribute(componentName, propertyName)`

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1614]
**Description:**

Reset a component property to its default, removing its defined value.

```
el.removeAttribute('material', 'src');  // Remove a texture.
el.removeAttribute('geometry', 'height');  // Reset height.
el.removeAttribute('light', 'color');  // Reset color.
```

Here is a snippet from the Editor that does this.

```
      if (value === null || value === undefined) {
        var parameters = entity.getAttribute(componentName);
        delete parameters[propertyName];
        entity.setAttribute(componentName, parameters);
      }
```

**Comment by ngokevin** [comment]
@dmarcos Feedback?

**Comment by dmarcos** [comment]
It looks reasonable. should we overload `removeAttribute` or make a new method `resetAttribute`  e.g: `el.resetAttribute('material');` `el.resetAttribute('material','color')`

**Comment by ngokevin** [comment]
OK. I'd overload to reduce API surface, and it matches the overloading of `setAttribute`.
