### ISSUE TITLE
Spot light position bug

### ISSUE THREAD

**Issue by FrederickDesimpel** [aframevr/aframe#1624]
the cone of a spot light seems to be a unit higher then it's origin :
http://www.frederickdesimpel.be/test/webVR/Aframe/spot-bug.jpg

**Comment by FrederickDesimpel** [comment]
not sure if it is the spotlight itself that is in the wrong place or the editor's cone visualisation.

**Comment by msimpson** [comment]
Is this related to #1621?

**Comment by FrederickDesimpel** [comment]
no this is just about the position of the object

**Comment by FrederickDesimpel** [comment]
it has to do with the editor, position in aframe is correct.

**Comment by fernandojsg** [comment]
@FrederickDesimpel can I have the example scene that you're using in your screenshot to test it on the editor?

**Comment by FrederickDesimpel** [comment]
@fernandojsg i don't seem to have it around anymore... should be easy to recreate, it was just a spotlight and a sphere to check it's position...

can't seem to get into the editor anymore for the moment, so i can't recreate it now.

**Comment by FrederickDesimpel** [comment]
@fernandojsg i have a scene that clearly shows the problem:

http://www.frederickdesimpel.be/test/webVR/Aframe/test11-spot-showbug-spotPos.html

the yellow line is from the light aframe element position, the white light is from the position of the light attached to it's object3D. it is exactly one unit too high.

**Comment by FrederickDesimpel** [comment]
Made a temporary fix [here](https://github.com/aframevr/aframe/issues/1728). The functionality to the end user should be as expected. The real cause can be hunted upon later...

**Comment by ngokevin** [comment]
fixed
