### ISSUE TITLE
lookat component doesn't work with spotlight

### ISSUE THREAD

**Issue by FrederickDesimpel** [aframevr/aframe#1625]
A spotlight entity doesn't orient itself with a lookat component.

**Comment by FrederickDesimpel** [comment]
Looks like the threejs spotlight has a .target object. Either the orientation and lookat components will have to take this into account ( which would nicely abstract this away from the user), or an additional component that sets this target is required

**Comment by FrederickDesimpel** [comment]
been playing a bit with a quick spottarget component... if the spotlight.target is added as a child of the light, and it's pos set to  0 0 -1 orientation works as expected ( with the spot pointed along it's -z axis)

**Comment by msimpson** [comment]
I've been having some of these same issues when using `SpotLight` from THREE, in general. There seems to be a lot of confusion and discussion about using targets and both @BenJenkinson and @WestLangley left comments detailing a history of these issues [here](https://github.com/mrdoob/three.js/issues/7132#issuecomment-154400735) and [here](https://github.com/mrdoob/three.js/issues/5870#issuecomment-69117498), respectively.

I don't know if that's going to be of any help, however.

**Comment by FrederickDesimpel** [comment]
by adding the light.target to a given object, you get tracking for free :-)

I'm almost done with a component for (spot) light targets. Will have to check if it works for directional lights too, which also have a .target.

**Comment by ngokevin** [comment]
@FrederickDesimpel Would love if you could add a target property (type `selector`) for the light component.

**Comment by FrederickDesimpel** [comment]
I'll look into it. To have all the options you need a seperate component, but maybe the basics of it can be included in the light component yes.

Maybe tagetobject (selector) and a targetoffset, so you can also give a coordinate in worldpos (relative to scene if you don't specify an object.

And have it default to be added to the light itself, with an offset of (0 0 -1), so it looks down -Z and regular rotation works

been a while ie worked on that... will have to see if all that can be added to light component in a clear way

**Comment by FrederickDesimpel** [comment]
Works like a charm now: https://github.com/aframevr/aframe/pull/1728

**Comment by ngokevin** [comment]
spotlight.target added, thanks!
