### ISSUE TITLE
Performance problems on tour app - am I doing something wrong?

### ISSUE THREAD

**Issue by rafaeleyng** [aframevr/aframe#1626]
**Description:**

**The scenario**:

I'm developing a "virtual tour" application with a-frame. The core of my app is basically a `<a-scene>` with `<a-assets>`, a single `<a-sky>` and some (1 to 3, depending the situation) `<a-image>` used for navigation purposes. On every navigation I just change the sky `src` attribute with the id of another asset.

I'm using React to organize my scene in components: one for the scene itself (together with assets and camera), a child component for the room (with the sky and the nav elements) and a nav component.

For the assets, for each room, I put in `<a-assets>` the image for that particular room, and the image for all the possible rooms that can be reached from that one (to prefetch them). Since I'm using React to help me here, I keep an array of all the assets that were already put in `<a-assets>`, and I only add to it the ones that never were loaded. So I start with, say, 5 assets (nav images, current room sky, next room sky), and as I navigate, more assets are put in `<a-assets>`, but the ones that are already there are never touched. So, at the end of the tour, I might have about 15-20 assets in `<a-assets>`.

I have around 15 different "rooms" (so 15 sky images). The sky images range from 500kb to 2mb. My nav images are always with the same src, and it is a small png image (less than 100KB).

Each sky image is only being loaded once and not making any more requests (100% sure, checked on browser and on server), but my navigation image gets loaded once and then on every navigation it makes the request again, but with 304 status. Could not find a way to overcome this, but it shouldn't be a big problem.

The components are behaving well, so I'm not having several renderings of my react components for each transition or something like that.

**The problem**:

I have a major performance problem testing the app in my Android phone (Motorola Moto X, 2nd generation, 2GB of RAM) with Chrome. After around 10-20 transitions between rooms (in some rooms I don't have an option besides going back to the previous room), the transitions begin to get slower and slower, to the point where I focus to my nav element and my phone freezes, so I need to restart it. I tried Firefox on my phone but the Firefox will crash every time a few seconds after loading the app. Firefox even crashes with the oficial [hello world demo](https://aframe.io/examples/showcase/helloworld/), so I don't think that this is my problem exclusively.

In my computer (MacBook Air, 4GB of RAM, i5 CPU), I can run my app with much more stuff on it and everything runs fine. I've added [gifs](https://github.com/mayognaise/aframe-gif-shader) in my navigations, [text](https://github.com/ngokevin/aframe-text-component), audio (a different audio for each room) and [mouse-cursor](https://github.com/mayognaise/aframe-mouse-cursor-component) and I had no problem running my app. Although, when I navigate about 20 times between rooms, the RAM consumption gets bigger than 500MB with all this stuff, and 200MB-300MB without it (as simple as when I get the crash on mobile).

**Conclusion**:

It would be really nice to receive some suggestions about what I might be doing wrong. I can show some code if my description is not enough and if you think that would be helpful, but I think my description was pretty complete.

- A-Frame Version: 0.2.0
- Platform/Device: critical on mobile (Chrome 51.0.2704.81, Firefox 47.0), bad in desktop (Chrome 51.0.2704.103)

**Comment by rafaeleyng** [comment]
I just found this app: https://aframe.io/blog/syria/
I'll try to figure out what they are doing, because they don't seem to have the performance problems that I described, even though my app is simpler than that.

**Comment by JohnRodney** [comment]
@rafaeleyng hey I built an app very recently that did the exact same thing you are working on.  I know I ran into a simular issue though I can't remember exactly how I fixed it.  Do you have a repo I can look through your code to help you with the issue?

I think ultimately I had ended up doing 8 different sky's and preloading the assets on them then used show - hide to toggle which one you were in.  This ended up not leading to crashes though I never tried as high as 20 assets.

I also used curved-images as my navigation component and a combination of cardboard tap and look at mechanisms to trigger the scene change.  If your code is proprietary I may not be able to help look through and find an answer, but I remember when I kept changing the source on the same sky that I was having the "appearance" of a memory leak where the RAM continually got larger.  When I toggled between seperate sky's I hit a max roof that memory never got higher (around 250mb)

**Comment by rafaeleyng** [comment]
Forgot to mention, to play with the app you should just run:

```
npm install
npm start
```

**Comment by JohnRodney** [comment]
@rafaeleyng Cool I'm at work at the moment I looked around the code but nothing jumped out at me.  I'll try to clone it down and run later.  But you might figure out the issue before then 😄.

**Comment by rafaeleyng** [comment]
@JohnRodney (or should I say Daryl from TWD?), you suggestion DID work. I cannot thank you enough, man!

On the other hand, this seems to me a very random solution. I would like to have a better understanding on why this works.

The downside is that since all my `<a-sky>` are in the DOM when the React app is mounted, I need all my assets in the DOM also, so my prefetch now has become pointless.

But I'll try another approach: put my `<a-sky>` as needed, and once they are in the DOM, never remove them. This way I can use the assets lazy-load/prefetch.

**Comment by JohnRodney** [comment]
@rafaeleyng honestly I didn't like the solution either.  I was just on a deadline to get that walkthrough working by a certain day for the apartment complex that wanted it.  Because of that digging further into the why's behind this weren't an option.  

If you want to keep this issue open as you further deep dive the reason's I think that is very reasonable.  Hopefully I can get some time this afternoon to look into it myself now that I do have a bit more time to readdress the issue.

I'll probably instead of cloning yours just come up with the minimum example to show it and start deep diving the aframe source.

Good to hear you have it working well now though 😄 
Happy coding!

**Comment by rafaeleyng** [comment]
So @JohnRodney , my current solution is: I put a `<a-sky>` in the DOM for each visited room. If I am in that room, then the entity holding the sky is visible, otherwise, not. Keeping one `<a-sky>` for each src, and never changing the source was the solution, but not putting all of them at once in the DOM was my way to delay loading all the assets.

I'm in the same situation that you was, so I'm not very happy either, but the deadline ain't getting further. Closing because I think my issue was solver, thanks to your help.

(I'm also putting my repo as private, because it should be).

**Comment by JohnRodney** [comment]
@rafaeleyng no worries sorry we didn't get a more in depth solution to this. I know I had asked @ngokevin about this before but we never got to the bottom of it.  Maybe texture caching isn't working as expected.

**Comment by Javier-Machin** [comment]
hey @rafaeleyng  and @JohnRodney , any of you happen to remember how you solved this? Even if its a naive or not pretty solution I'm willing to listen to it.

My issue is very similar to what you guys encountered back then, making certain elements visible make the page crash and refresh.

I have 3 rooms, I only keep visible the one where the camera is on, I travel to other rooms by doing a fade to black, teleport the camera, and fade in. It works perfectly fine in desktop but it isn't stable in phones (iphone to be specific).

Sometimes it crashes while loading a different room, some others when fading in a somewhat complex model after an interaction... I'm loading all assets using the provided Aframe asset manager.
