### ISSUE TITLE
Docs for position component - Y axis incorrect?

### ISSUE THREAD

**Issue by mike7ant** [aframevr/aframe#1628]
**Description:**

Docs for 'position' component state the following for the y axis: "Positive Y Axis extends down.".  I believe the positive Y axis actually points up, which would be the expected orientation for right-handed coordinates.

- A-Frame Version:
0.2.0
- Platform/Device:
Any

**Comment by ngokevin** [comment]
Yes, should be up :)

**Comment by ngokevin** [comment]
Fixed thanks!
