### ISSUE TITLE
Adding cursor to any example results in this.object3D is undefined.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#163]
![image](https://cloud.githubusercontent.com/assets/1560884/11162869/d0e0ff00-8a69-11e5-9aed-5d4712b39ff3.png)

![image](https://cloud.githubusercontent.com/assets/1560884/11162870/e043259a-8a69-11e5-8626-30940fa3c616.png)

**Comment by ngokevin** [comment]
No longer an issue I believe, or at least primitives will solve this.
