### ISSUE TITLE
Make stats colour more readable

### ISSUE THREAD

**Issue by allanweir** [aframevr/aframe#1630]
When debugging the frame rate on an iOS device, if the frame rate is less than 30 the text is red against the pink background making it difficult to read. Can the background or the text colour be more contrasting?

- A-Frame Version: 0.2.0
- Platform/Device: iPhone 6s iOS 9.3

![framerate](https://cloud.githubusercontent.com/assets/2892400/16763026/fd54f4f6-481e-11e6-85d2-db02423d6504.jpg)

**Comment by FrederickDesimpel** [comment]
i second that.

now with the editor coming, maybe style it more like the editor gui ?

i may try something later this week...

**Comment by ngokevin** [comment]
Thanks, PR is open

**Comment by FrederickDesimpel** [comment]
I know this is closed, but.. the red text is still unreadable.

**Comment by ngokevin** [comment]
PR welcome!

**Comment by kevinzwh** [comment]
I opened a PR to try to solved this by highlighting red text with a white background to make it more visible & readable. Take a look at #1874!

Before:
![screen shot 2016-08-29 at 9 15 06 pm](https://cloud.githubusercontent.com/assets/7256178/18075899/ef7b9a26-6e2d-11e6-9ebe-ec6811f1f098.png)

After:
![rstatcolorchange](https://cloud.githubusercontent.com/assets/7256178/18075901/f508268a-6e2d-11e6-9e01-e1b194b4b1df.gif)

**Comment by ngokevin** [comment]
Also look into using text shadows

**Comment by kevinzwh** [comment]
Sure @ngokevin 

I played around with a few arrangements with text shadows and here's an approach I found:

Red text backed by a composite white text shadow (10 levels of shading)
![rstatcolorchange5](https://cloud.githubusercontent.com/assets/7256178/18115678/1f2afa3c-6ef6-11e6-9be5-19e894677ae1.gif)


Its similar to my original attempt with the white text background, but less agressive with shadowing where it needs to be. What do you think?

**Comment by ngokevin** [comment]
Thanks for playing with it! Seems like we still have room to decrease the shadow a bit and still be readable?

**Comment by kevinzwh** [comment]
Definitely! How's this @ngokevin ? Lowered the overall blur radius to 1/3 the size of the last example and kept about the same shadow density to maintain readability.

![rstatcolorchange7](https://cloud.githubusercontent.com/assets/7256178/18138133/32cb99b0-6f60-11e6-8c08-33a49aa9b380.gif)

```css
/*Text Shadow Values*/
0px 0px 0px #b70000, 0px 0px 1px #ffffff, 0px 0px 1px #ffffff, 0px 0px 2px #ffffff, 0px 0px 2px #ffffff, 0px 0px 3px #ffffff, 0px 0px 3px #ffffff, 0px 0px 4px #ffffff, 0px 0px 4px #ffffff

**Comment by ngokevin** [comment]
Looks better :)

**Comment by kevinzwh** [comment]
Cool! I went ahead and opened a PR for this new solution in #1880

**Comment by kevinzwh** [comment]
Revisiting this issue now that https://github.com/spite/rstats/pull/24 is merged in to rstats. Thoughts on how to proceed @ngokevin? :)

**Comment by ngokevin** [comment]
Great! We can copy and paste the new rStats into A-Frame. And add a class to style it in `src/style/rStats.css` using `.rs-counter-base.alarm`

**Comment by kevinzwh** [comment]
Cool, just opened https://github.com/aframevr/aframe/pull/1885 for this!

**Comment by ngokevin** [comment]
thanks!
