### ISSUE TITLE
A-Frame 0.4.0 Dependencies update

### ISSUE THREAD

**Issue by mkungla** [aframevr/aframe#1635]
As dependencies where update last time around release of 0.2.0 then it would be wise to check over and update these for 0.4.0 since only some got updated for 0.3.1. Since some dependency updates may fix some issues, introduce new issues and some dependencies currently used are about become deprecated (or have their dependencies which are about to become deprecated)!

<table>
<caption><h3>Dependencies (Last updated @ 20 Aug 2016)</h3></caption>
<thead><tr><th>Package</th><th>Currently used </th><th>Latest Version</th><th>To be used for 0.4.0</th></tr></thead>

<tbody>

<tr>
<td><b>browserify-css</b></td>
<td><code>0.8.4</code></td>
<td><code>0.9.1</code></td>
<td>:grey_question: </td>
</tr><tr><td></td><td colspan="3">
This update adds a onFlush option and  bug fixes for `processRelativeUrl` and few other BUGS
<br>
</td></tr>

<tr>
<td><b>debug</b></td>
<td><code>^2.2.0</code></td>
<td><code>2.2.0</code></td>
<td><code>^2.2.0</code></td>
</tr><tr><td></td><td colspan="3">
No changes there
</td></tr>

<tr>
<td><b>deep-assign</b></td>
<td><code>^2.0.0</code></td>
<td><code>2.0.0</code></td>
<td><code>^2.0.0</code></td>
</tr><tr><td></td><td colspan="3">
No changes there
</td></tr>

<tr>
<td><b>document-register-element</b></td>
<td><code>#8ccc532b7</code> </td>
<td><code>1.0.0</code></td>
<td>:grey_question: </td>
</tr><tr><td></td><td colspan="3">
Should not use commits as dependency
<a href="https://github.com/WebReflection/document-register-element/pull/55"  target="_blank">WebReflection/document-register-element/pull/55</a>
</td></tr>

<tr>
<td><b>object-assign</b></td>
<td><code>^4.0.1 = 4.1.0</code> </td>
<td><code>4.1.0</code></td>
<td>:grey_question: </td>
</tr><tr><td></td><td colspan="3">
Current semver uses currently latest release
</td></tr>

<tr>
<td><b>present</b></td>
<td><code>0.0.6</code> </td>
<td><code>1.0.0</code></td>
<td>:grey_question: </td>
</tr><tr><td></td><td colspan="3">
No changes in code just 0.0.6 is considered to be 1.0.0
</td></tr>

<tr>
<td><b>promise-polyfill</b></td>
<td><code>^3.1.0 = 3.1.0</code> </td>
<td><code>6.0.1</code></td>
<td>:grey_question: </td>
</tr><tr><td></td><td colspan="3">
This update will add unhandled rejection warnings to the console. Removes non standard functionality of passing multiple params to Promise.all. You must pass an array now. You must change this code
<pre>
Promise.all(prom1, prom2, prom3);
// to
Promise.all([prom1, prom2, prom3]);
<pre>
adds support for subclassing, and fixes quite some BUGS and replace deprecated code!

</td></tr>

<tr>
<td><b>style-attr</b></td>
<td><code>^1.0.2 = 1.2.0</code> </td>
<td><code>1.2.0</code></td>
<td>:grey_question: </td>
</tr><tr><td></td><td colspan="3">
Current semver uses currently latest release
</td></tr>

<tr>
<td><b>three</b></td>
<td><code>^0.76.1</code> </td>
<td><code>0.81.0</code></td>
<td>:grey_question: </td>
</tr><tr><td></td><td colspan="3">
0.76.1 -> 0.81.0 has ~75 bug fixes<br>
A-Frame tests pass with `0.77.1` and fail with any newer version
<pre>
// FAILED TESTS:
material > update
material system > texture caching > loadImage
</pre> </td></tr>

<tr>
<td><b>tween.js</b></td>
<td><code>^15.0.0 = 15.0.0</code> </td>
<td><code>16.3.5</code></td>
<td>:grey_question: </td>
</tr><tr><td></td><td colspan="3">
15.0.0 -> 16.3.4 has ~30 bug fixes 
16.3.5 fixes some BUGS
</td></tr>

<tr>
<td><b>webvr-polyfill</b></td>
<td><code>0.9.15</code> </td>
<td><code>0.9.18</code></td>
<td>:grey_question: </td>
</tr><tr><td></td><td colspan="3">
Support VRLayer bounds configuration,<br>
Set the quaternion to be looking in the -z direction by default<br>
Fix predistortion bug.
</td></tr>
 	
</tbody>  
</table>

**Comment by mkungla** [comment]
My suggestion would be a milestone 0.3.1, which would aim to upgrade the aframe dependencies, so that these would not delay release of 0.3.0 even more, but any further work and moving toward 0.4.0 would have updated dependencies.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/bd1bdd8159e0f947bdebc01d66d5e12361733960
