### ISSUE TITLE
cursor is a reticle

### ISSUE THREAD

**Issue by FrederickDesimpel** [aframevr/aframe#1636]
Not really an issue but... Wouldn't it be better to rename the cursor component to reticle, and have a regular cursor component as well ?

**Comment by dmarcos** [comment]
@FrederickDesimpel What's would a regular cursor component be?

**Comment by ngokevin** [comment]
Could be with the mouse: https://github.com/mayognaise/aframe-mouse-cursor-component/

**Comment by ngokevin** [comment]
Reticle makes sense, though it would be a lot of work for everyone to rename. Perhaps we can do this when we start extracting out prescriptive components and we can have both names work for a while.

**Comment by FrederickDesimpel** [comment]
yeah, a regular cursor would be the louse cursor when on desktop...

Or come to think of it... in VR you can have both a gaze reticle, and a virtual mouse cursor if someone makes a vr ui component with a 'mouse' or for instance text area cursor..

renaming might indeed be cumbersome, but the longer you wait...

**Comment by ngokevin** [comment]
I think it would be too much effort to rename. For consolation, `reticle` is an uncommon word, and `gaze cursor` is somewhat a common term nowadays.
