### ISSUE TITLE
Inject Twitter player tag

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1641]
**Description:**

Embedded A-Frame scenes (iframe) within Twitter if the `twitter:player` metatag is set. See if we can inject that metatag with info from window.location.

https://twitter.com/guri_vr/status/751870382219599872
- A-Frame Version:
- Platform/Device:

**Comment by wizgrav** [comment]
should this be implemented as a component/system?

**Comment by ngokevin** [comment]
Yeah. If it should be configurable/toggleable, it should be a component.

**Comment by kevinzwh** [comment]
I'm gonna try to take a look into this

**Comment by ngokevin** [comment]
Cool. I think this doesn't have to be a component/system. It can just be a module that is always run when the scene attaches. I would also check whether Twitter player metatags already exist before creating them.

**Comment by ngokevin** [comment]
I think this isn't possible because Twitter will fetch statically.

**Comment by kevinzwhuang** [comment]
@ngokevin yeah pretty much! 
If it was possible, we'd have to do some weird stuff to the DOM to add a <meta> tag (then also some verification step), which, as a concern, might be better left off for the user to take care of themselves.
