### ISSUE TITLE
DDS texture support?

### ISSUE THREAD

**Issue by Pupix** [aframevr/aframe#1646]
**Description:**
As of now passing a .dds `src` to a material will cause the component to interpret it as a video and not work properly.

Is there any intention of implementing DDS support into aframe?

In the meantime is there any workaround to get .dds files to load properly?

Thanks!

**Comment by ngokevin** [comment]
Hi,

You can write a component that wraps the DDSLoader (https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/DDSLoader.js).

https://aframe.io/docs/core/component.html

**Comment by Pupix** [comment]
So I guess that's a `no` on a first-party implementation.

Gonna go the custom component route then, thanks.

**Comment by ngokevin** [comment]
We aim to keep the first-party list of components to must-haves. Since we can't maintain every possible feature out there. This lets other people be module owners of components. In the next version, we will lazy-load curated components so they will seem first-party. (call them second-party).

**Comment by JunkYardRobotBoy** [comment]
@Pupix 
Was wondering if you got this to work? I'm trying to wrap my head around it and can't load in the .dds texture at all. Any help would be most appreciated

**Comment by Pupix** [comment]
@JunkYardRobotBoy I've made a custom component as kevin suggested. 
Something like this

```js
AFRAME.registerComponent('texture', {

    /** CONFIG ***/

    schema: {
        src: { type: 'src' }
    },

    /** LIFECYCLE ***/

    init() {
        this.texture = null;

        this._loader = new THREE.DDSLoader();
    },

    update() {

        this.texture = this._loader.load(this.data.src);

        // Do whatever with this.texture here
    }

});

```


and use it like so

```js
const entity = document.createElement('a-entity');

entity.setAttribute('texture', `src: url(${paths.texture})`);
window.scene.appendChild(entity)
```
