### ISSUE TITLE
Directly setting transformation matrix

### ISSUE THREAD

**Issue by BSVogler** [aframevr/aframe#1659]
Hi!
A frame looks like a really good framework, but I have some issues with the API.
I see that there are only position, rotation and scale attributes but no transform matrix. There are many cases where handling this data as one transform matrix is quite easier (currently having such a case myself).
I guess internally these are combined to a transform matrix, so this should only be an API extension.
However I see a problem with this because then the parameters position, rotation and scale are interlinked with the transform matrix.
Is this intended design or just some missing feature?
- A-Frame Version: 0.2.0
- Platform/Device: -

**Comment by ngokevin** [comment]
If it helps, A-Frame is just a three.js framework and what it does is copies the values on pos/rot/scale onto the `THREE.Object3D`.

There is an `.applyMatrix()` method on that object, though that's internal. You could write a higher-order component that takes a transform matrix and sets appropriate value on the position/rotation/scale components.

**Comment by BSVogler** [comment]
@ngokevin 
Thanks. It seems I have to dig a bit deeper to do this via three.js. Writing a higher order component sounds like a good alternative but a bit unnecessary to decompose a matrix to then compose it again.

**Comment by dmarcos** [comment]
There could be a `matrix` component that internally decomposes to rotation, position and scale but not sure it should be part of the core.

**Comment by ngokevin** [comment]
Yeah, I would just apply the matrix to the Object3D.

**Comment by trusktr** [comment]
> Yeah, I would just apply the matrix to the Object3D.

In this case other components like those provided by `networked-aframe` don't react to changes, as in modifying the transform of an Object3D directly won't sync over the network. `networked-aframe` only works when using the a-frame APIs directly to update data and avoiding the underlying Three.js objects (f.e. only using `setAttribute('position', ...)`.

**Comment by ngokevin** [comment]
Networked-aframe should not assume transforms are only updated thru transforms and provide some sort of detection such as dirty flags or wrapping of object3d methods

**Comment by ngokevin** [comment]
Only updated thru aframe setattribute*

**Comment by LukeTOBrien** [comment]
@ngokevin  I really hate it when people close issue that are really good, you just added the `feature request` label and then deleted the issue ???

Anywho... I would like to apply [SVG matrix transformations](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform) to my entities.  
I have this transformation for eg `matrix(0.87110687,-0.4910935,0.63587824,0.77178939,0,0)`.  
I think it would be cool to have this as an attribute directly in the HTML, or as a Mixin.

**Comment by dmarcos** [comment]
Performance is paramount and we recommend modifying matrix, rotation, position and scale accessing THREE directly. Specially if updated on the `tick` method every frame. Using `setAttribute` involves string parsing and type checking that is costly. That's why the issue was closed. Notice that you can still implement your own `matrix` component that takes SVG transformations and applies it to the entity.

**Comment by LukeTOBrien** [comment]
mmm.. but A-Frame does have inbuilt [position](https://aframe.io/docs/1.0.0/components/position.html), [rotation](https://aframe.io/docs/1.0.0/components/rotation.html) and [scale](https://aframe.io/docs/1.0.0/components/scale.html) components, so `matrix` is a reasonable request.  
These attributte do not apply on `tick`, just on `init` - Nobody said anything about `tick`.

I just wanna apply some funky matrix transformations on startup.
