### ISSUE TITLE
Enable "Pano Explorer" acid test scene

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#166]
This scene has to be fully functional for us to release A-Frame. In run up to launch we will measure progress and QA against it.

Required functionality outlined at: 

https://docs.google.com/spreadsheets/d/1Kd70yf1EMYeffY5E1Ql-PtHqH8UWVThvRzXLxLUnPyI/edit#gid=496443426

**Comment by ngokevin** [comment]
issue is old, but looks good now
