### ISSUE TITLE
Consider creating repo(s) for model components.

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#1662]
Carrying over discussion from https://github.com/donmccurdy/aframe-extras/pull/68 –

Should we create an `aframe-model-components` repo for various models, or separate repos for each? If we do it in a tree-shakeable way I might prefer a single repo.

There doesn't seem much point in my owning the repo personally, because (1) the model components are just thin wrappers, and (2) the API for animations and events really should be agreed on and consistent.

**Comment by ngokevin** [comment]
Also need guaranteed caching.

**Comment by ngokevin** [comment]
Also to hook into `<a-asset-item>` and not refetch, instead grabbing from THREE.XHRLoader cache.

**Comment by donmccurdy** [comment]
Closing this, because:

1. There are fewer reliable formats than I 'd expected.
2. Maintaining extra loaders in `aframe-extras.loaders` is working well enough
3. Workflows for getting to glTF feel like a better long-term plan than many loaders
