### ISSUE TITLE
`mouseenter` event doesn't work anymore. What should I use instead?

### ISSUE THREAD

**Issue by rafaeleyng** [aframevr/aframe#1667]
**Description:**

I was using aframe 0.2.0 in my app, but now I installed it pointing to commit 733ab959bf3f930cb3ed508a4552f8d5ba2da781 to try the fix introduced by #1629.

I had a handler for `mouseenter` on an `<a-image>`, but now it is not triggered anymore. What should I use instead?

- A-Frame Version: 0.2.0 to 733ab959bf3f930cb3ed508a4552f8d5ba2da781
- Platform/Device: Chrome 51.0.2704.106 desktop on Mac

**Comment by rafaeleyng** [comment]
I was looking through https://github.com/ngokevin/aframe-event-set-component but it doesn't to seem the right way. I don't want to set properties, I want to perform some action.

**Comment by ngokevin** [comment]
I recommend https://github.com/ngokevin/aframe-event-set-component

You could also use `<a-event type="mouseenter">` but that is deprecated.

**Comment by ngokevin** [comment]
Sorry, I misunderstood.

**Comment by rafaeleyng** [comment]
I was using it via JS, like:

```
this.refs.navEntity.addEventListener('mouseenter', this.handleEnterNav)
```

**Comment by ngokevin** [comment]
Use this commit https://github.com/aframevr/aframe/commit/43cfbc0c18cc1da1d2d0230f75643fdfb2252a28

We renamed the event to cursor-mouseenter, but then we renamed it back. The commit you are using did not have the updated `dist` to reflect the event name revert.

**Comment by rafaeleyng** [comment]
Nice, I'm trying to install it again since you answered me, but for some reason, `npm install` takes forever to install when pointing directly to Github:

```
    "aframe": "aframevr/aframe#43cfbc0c18cc1da1d2d0230f75643fdfb2252a28",
```

Is there a reason why you guys don't publish to npm when you bump the dist?

**Comment by ngokevin** [comment]
GitHub was down earlier.

We currently don't consider the `dist` bumps official releases. We could publish, but then it'd send the wrong message and expectations that they are releases. We just bump it for convenience for people that want to try it.

**Comment by rafaeleyng** [comment]
Understood.

I still wasn't able to try, I'm stuck trying to install it:

![image](https://cloud.githubusercontent.com/assets/4842605/17153789/9b8a1468-5354-11e6-83cd-96b7779d264c.png)

I know this is not aframe related, but I'd appreciate any hint while I'm searching for a solution.

**Comment by rafaeleyng** [comment]
It seems to be network related...
