### ISSUE TITLE
Please add vertices prop to Mesh

### ISSUE THREAD

**Issue by michael829** [aframevr/aframe#1673]
**Description:**

- A-Frame Version:master
- Platform/Device:all

I know set Gemotry.vertices to null is well for performance. but some times i want align entitys on the vertices. this can be very useful..
So, is there any way to get the vertices? or add a callback at later version??
Thanks!~~
: P

**Comment by donmccurdy** [comment]
@michael829 In standard Geometry objects, an array of THREE.Vector3 elements are in `geometry.vertices`. In BufferGeometry, which A-Frame uses, the vertices are still available but flattened out:

```
var vertices = geometry.attributes.position.array;

/*
[
  x1, y1, z1,
  x2, y2, z2,
  x3, y3, z3,
  ...
]
*/
```

If you need THREE.Vector3 instances, you'd need to re-create them from that array. If you're just hoping to align things to the edges of the shape, also check out [geometry.computeBoundingbox()](http://threejs.org/docs/index.html?q=geometry#Reference/Core/Geometry), which is faster.

**Comment by michael829** [comment]
yeah...you're great!~~ I've found the position prop but don't know it flattened outt!
Haha...thank you...
