### ISSUE TITLE
navigator.getGamepads() error on safari, both IOS and MacOS

### ISSUE THREAD

**Issue by michael829** [aframevr/aframe#1674]
**Description:**

On IOS and Mac OS, safari browser!! There is no 'navigator.getGamepads()' function! so this cause html could not run properly! In my html file, there is only a "a-sky" entity. very simple~

code in aframe.js:
`/**
 * Tracked controls system.
 * It maintains a list with the available tracked controllers
 */
module.exports.System = registerSystem('tracked-controls', {
  init: function () {
    var self = this;
    this.controllers = [];
    if (!navigator.getVRDisplays) { return; }
    navigator.getVRDisplays().then(function (displays) {
      if (displays.length > 0) {
        self.vrDisplay = displays[0];
      }
    });
  },

  tick: function () {
    //var gamepads = navigator.getGamepads();  <== error in here!
    var gamepads = navigator.getGamepads?navigator.getGamepads():[]; <== run well!
    var gamepad;
    var controllers = this.controllers = [];
    var i;
    for (i = 0; i < gamepads.length; ++i) {
      gamepad = gamepads[i];
      if (gamepad && gamepad.pose) { controllers.push(gamepad); }
    }
  }
});`

- A-Frame Version:master
- Platform/Device: iphone 6s and Mac book pro, safari

**Comment by dmarcos** [comment]
This bug has been [fixed](https://github.com/aframevr/aframe/blob/master/src/systems/tracked-controls.js#L20)

 You just have to bumb the dist `npm run dist`
