### ISSUE TITLE
Lots of "Unknown component property" warnings after using 43cfbc0 version

### ISSUE THREAD

**Issue by rafaeleyng** [aframevr/aframe#1676]
**Description:**

After pointing my aframe version to commit `43cfbc0` as suggested on #1667, a lot of warnings and an error started to appear:

![image](https://cloud.githubusercontent.com/assets/4842605/17179141/77c6abc8-53ee-11e6-93a1-ee94c8d45114.png)

I tried reading the code that logs this warning, changelog and commit messages, but didn't figured out what should I change in my code to address that.

Despite the warnings and error, my app is working exactly the same, I didn't noticed any problems.

Any hint on what should I change?

- A-Frame Version: commit 43cfbc0 (after 0.2.0, but before 0.3.0)
- Platform/Device: only tested on Chrome desktop for Mac

**Comment by dmarcos** [comment]
Do you see the same warnings with any of the examples? If not can you provide a simple test that reproduces your problem? Thanks

**Comment by ngokevin** [comment]
sorry, try bumping straight to master https://github.com/aframevr/aframe/blob/master/dist/aframe.min.js
