### ISSUE TITLE
Can't play sound on iOS

### ISSUE THREAD

**Issue by rafaeleyng** [aframevr/aframe#1684]
**Description:**

I cannot get audio to play on iOS, both on Safari and Chrome.

What I tried:

- `autoplay` directly on the component. #1463 made me think right away that this wouldn't work. But #1463 description implies that it wouldn't work for Chrome for Android, but it **does** work for me.

- using `entity.components.sound.play()`, both with a setTimeout and with user events.

Both approaches worked properly in Chrome for Android and desktop browsers (Chrome, Safari and Firefox). In Firefox for Android, my app crashes even before I could try the audio, but that is just information, I'm not focusing on Firefox.

I inspected the iOS Safari console and network tabs with remote debug and there wasn't any error or something.

Also, as a side note, I tried the [a-wakens demo](http://ngokevin.github.io/a-wakens/), and it worked on: 

- Chrome, Safari and Firefox (desktop), Firefox (Android)

but didn't work on:

- Chrome (Android), Safari and Chrome (iOS)

So, I'm pretty much clueless about how to get audio to play on iOS and would appreciate some tips.

- A-Frame Version: 0.2.0
- Platform/Device: iOS 9.3.2, iPhone 6, both Safari and Chrome 51

**Comment by ngokevin** [comment]
Hi, I moved to http://stackoverflow.com/questions/38645716/cant-play-sound-on-ios because I think this is a question and a matter of figuring out how to use WebAudio on mobile, rather than A-Frame issue.

**Comment by rafaeleyng** [comment]
Thanks @ngokevin

**Comment by antesberger** [comment]
Is there any solution for this problem by now? I have:
- video without sound in iOS Safari
- sound and no video when I pin in it to the homescreen
- video and sound from other sources than the video in Chrome (Dektop)
- no problems in Safari (Desktop)

**Comment by johnnyshankman** [comment]
@antesberger i only get video without sound on iOS Safari. Downloading to homescreen gives me sound and video.

My big issue is that in iOS Safari even if I write my own sound handlers I get complains from some global component about the `poolSize` that I don't get on desktop. @ngokevin is there a default poolSize that gets set only on mobile?

I can't figure out how to identify which entity is playing the sound and has the default pool size. Frankly I'm confused as to how Aframe is even aware I'm playing these audio files, as this warning occurs even when the `<audio>` are outside the `<a-scene>` and `<a-assets>`

**Comment by johnnyshankman** [comment]
```
components:sound:warn All the sounds are playing. If you need to play more sounds simultaneously consider increasing the size of pool with the `poolSize` attribute. +8s
```
