### ISSUE TITLE
Reconsider not restoring camera position on exiting VR (although rotation makes sense)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1685]
**Description:**

If an experience has teleportation involved in a fairly large map, it would be weird to teleport around in VR, exit VR, and find that you started back at the beginning.

**Comment by dmarcos** [comment]
In a teleportation experience you would wrap the camera in an entity to move it around or you will collide with the headset updates. The wrapping entity position won't be restored.

**Comment by ngokevin** [comment]
Sounds good!
