### ISSUE TITLE
Can a-sky support any degree, not only 360?

### ISSUE THREAD

**Issue by mrFranklin** [aframevr/aframe#1694]
**Description:**
Can 'a-sky' support any degree, not only 360?  
for example: 180 degree. and then, the mouse can only drag the area of the 180 degree.
thanks very much!

- A-Frame Version:
- Platform/Device:

**Comment by ngokevin** [comment]
Try playing with the `theta-length`. `<a-sky theta-length="180">`

**Comment by mrFranklin** [comment]
I just try this, but it doesn't have any effect... please for some help, thank you!
<a-sky id="background" src="plan.jpg" theta-length="180">

**Comment by mrFranklin** [comment]
the code is:
<a-sky id="background" src="plan.jpg" theta-length="180">

**Comment by mrFranklin** [comment]
```
<a-sky id="background" src="plan.jpg" theta-length="180">
```

**Comment by ngokevin** [comment]
Can you ask on http://stackoverflow.com/questions/tagged/aframe with more details for help? Thanks!

**Comment by seanlis** [comment]
Hi.
I encountered the same problem with 0.3.2 version.
 ``<a-sky theta-length="90" src="#sky"></a-sky>`` has no effect.
But the following works:
```<a-entity geometry="primitive: sphere; thetaLength: 90; radius: 5000; segmentsWidth: 64; segmentsHeight: 20" scale="1 1 -1" material="src: #sky; shader: flat"></a-entity>```
