### ISSUE TITLE
No sound on IOS

### ISSUE THREAD

**Issue by FulvioRomanin** [aframevr/aframe#1695]
I was triggering an animation with sound, exactly using

    document.querySelector('#gruppo_uno').addEventListener('sound-ended', function(){
           document.querySelector('#vignetta1_arrow_up').setAttribute('visible','true');
        });

but on IOS sound-ended does not even seem to work, and i don't seem to get any audio playing.

I tried even with simpler stuff like 

```
  <a-scene>
  <a-entity sound="src: assets/audio/03.vignetta3.mp3; autoplay: true"></a-entity>
</a-scene>

```
but i get no sound from IOS. Any idea?

- A-Frame Version: 0.2.0
- Platform/Device: IOS

**Comment by dmarcos** [comment]
Safari Mobile requires user action to play a sound.
