### ISSUE TITLE
how can i Relative Rotation sky but button stop on that 

### ISSUE THREAD

**Issue by liuwaichung** [aframevr/aframe#1697]
how can i Relative Rotation sky but button stop on that  ?

<a-sky id="sky"  rotation="0 -60 0" radius="5000" color="#fff" >
         <a-animation attribute="rotation" from="0 1.5 0" to="0 -358.5 0" begin="0" dur="160000" repeat="infinite" easing="linear"></a-animation>
         </a-sky>

but the button will move with the sky !!
thanks so much

**Comment by mkungla** [comment]
@liuwaichung can you ask this via SO http://stackoverflow.com/questions/ask/?tags=aframe

**Comment by dmarcos** [comment]
Issues are for `bugs` and `feature` requests.
