### ISSUE TITLE
Hand-controls events being attached twice

### ISSUE THREAD

**Issue by bryik** [aframevr/aframe#1704]
**Description:** I think the hand-controls component is adding events twice, once during a [manual "addEventListeners()" call](https://github.com/aframevr/aframe/blob/master/src/components/hand-controls.js#L27) in init() and a second time when play() is called after update().

Also the ["stop()" method](https://github.com/aframevr/aframe/blob/master/src/components/hand-controls.js#L34) should be "pause()", right?

I can do a PR, if desired.

- A-Frame Version: master
- Platform/Device: all

**Comment by ngokevin** [comment]
Good catch. The call should be removed from `init()`. And IMO, the addEventListeners/removeEventListeners methods should be removed and put into `play()`/`pause()` directly because it implies they're used somewhere else. And yeah, it should be `pause()`.

**Comment by bryik** [comment]
OK, I'll make the changes and do a PR.
