### ISSUE TITLE
On desktop without headset, fullscreen icon does not indicate that the scene is VR capable.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1708]
**Description:**

Since we removed the modal and switched it to a fullscreen icon, there is no indication that the scene is VR-capable. Imagine the case where someone Tweets an A-Frame scene, and someone who opens up the scene on desktop does not know much about WebVR. The fullscreen icon alone makes it look like a plain 3D experience.

The primary solution I can think of is to re-introduce the modal that linked people to the Mozilla VR website. As most WebVR scenes today are built with A-Frame, this Enter VR CTA is important to introduce users to WebVR and how to consume it. We can add a referrer to the link so we can gain metrics whether people are engaging with it, but we can't assume it's not helpful yet.

Another solution would be an icon that conveys both that a headset is not connected, but fullscreen can still be entered. When a headset *is* connected, then the icon changes to just the Goggles.

**Comment by darkwing** [comment]
The goggles icon is a must, IMO.  Users don't care what it takes to get the 3D experience, full screen or not -- they want to be promised VR.

**Comment by ngokevin** [comment]
@dmarcos said he will revert the fullscreen icon.

**Comment by mkungla** [comment]
@ngokevin does #1712 closing this?

**Comment by ngokevin** [comment]
Yes, solved! I still have some reservations behind removing the modal since it trades off user experience for reduced maintenance and less code. Perhaps that can be a separate component.
