### ISSUE TITLE
Components panel does not update properly

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#1709]
1. When switching selected entities. I'm switching from an entity that has a geometry and a material to a light entity that doesn't have them. The geometry and material components still show in the panel ![switching](https://d3vv6lp55qjaqc.cloudfront.net/items/1u0M1p201g2L3q2O3K2c/Screen%20Recording%202016-08-02%20at%2006.18.18%20PM.gif?v=f47050f7)

2. If a an entity is selected and I click somewhere in the scene to deselect it the components panel is not reset: ![reset](https://d3vv6lp55qjaqc.cloudfront.net/items/1u0M1p201g2L3q2O3K2c/Screen%20Recording%202016-08-02%20at%2006.18.18%20PM.gif?v=f47050f7)

**Comment by ngokevin** [comment]
Wrong repo
