### ISSUE TITLE
The scene looks zoomed in after exiting VR on mobile

### ISSUE THREAD

**Issue by mayognaise** [aframevr/aframe#1714]
on Mobile, after exit VR mode (stereo view), the scene looks like zoomed in.
This only happens on master branch. `0.2.0` works fine.

- A-Frame Version: master branch
- Platform/Device: Mobile

**Comment by dmarcos** [comment]
If you are on iOS rotate the phone so the canvas resizes appropriately. That's some quirk on the canvas iOS resize logic on device orientation changes where the resize event is not triggered. It affects 0.2.0 too and the `webvr-polyfill` examples.

**Comment by mayognaise** [comment]
hi @dmarcos, do you know any example page for `webvr-polyfill`?

I just made a video to reproduce the issue:
[http://cl.meowyo.com/gsbq](http://cl.meowyo.com/gsbq)

The link is referred by [http://188.166.232.247/aframe/composite-master.htm](http://188.166.232.247/aframe/composite-master.htm)

**Comment by mayognaise** [comment]
Hi I tried rotating the phone to landscape and back to portrait.
The scale seems to work but the position is still off.
[test](http://cl.meowyo.com/gs8G)

**Comment by dmarcos** [comment]
With that polyfill example you pointed out I  also see viewport size issues on my iphone6 Plus. ![viewportSize](https://d3vv6lp55qjaqc.cloudfront.net/items/3R0a1k3B2v003C0R3A47/Image%202016-08-04%20at%2012.57.40%20PM.png?v=958d8255)

**Comment by mayognaise** [comment]
I see. Do you think the polyfill got regression?

**Comment by dmarcos** [comment]
There's a known bug in webkit where `WebGL based canvases composite incorrectly after changing size` https://bugs.webkit.org/show_bug.cgi?id=152556

**Comment by dmarcos** [comment]
That's the root cause of these bugs. As far as I know 0.2.0 was also affected. On my iphone 6 Plus I had to trigger an orientation change cycle for the canvas to resize correctly after exiting VR mode.

**Comment by mayognaise** [comment]
can you try this page with your phone how it goes, please?
https://pocktvr.io/user/5722b6ffc406d91100170f5f/574f363baf8be111002b7b5a
- click vr button in top right
- rotate as landscape
- rotate as portrait
- exit vr
My 5s iPhone has no issue.. the Aframe version is 0.2.0

**Comment by ngokevin** [comment]
I'm looking to see what we can do for the canvas resize issues on iOS. It doesn't reproduce for 0.2.0, but does easily for master.
