### ISSUE TITLE
Consider lowering default userHeight a tad.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1717]
**Description:**

From googling around, the average eye height is 1.44 meters (inclusive female + male). We currently set to 1.8.

- A-Frame Version:
- Platform/Device:

**Comment by mkungla** [comment]
Average male eye height: 1630mm and female eye height 1505mm which makes average 1567mm.
So I think something like 1.6 would be better than 1.4x

**Comment by ngokevin** [comment]
Yeah, seems so.

Source:

http://www.firstinarchitecture.co.uk/average-male-and-female-dimensions/ - 1.56
