### ISSUE TITLE
Fix broken asset uploader

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1719]
**Description:**

We've exceed our Uploadcare limits. When I talked to the Uploadcare team several months back, they agreed to give us free storage and bandwidth if we link to them somewhere from the A-Frame site, docs, etc. We still haven't done that yet, but it's on file: aframevr/aframe-site#236

Talked to @ngokevin about this. We can sneak it in somewhere in the aframe.io site redesign.

The action item is really aframevr/aframe-site#236, but I'm filing this issue here because the code lives in this repo: https://github.com/aframevr/aframe/tree/master/examples/uploader

**Comment by ngokevin** [comment]
fixed
