### ISSUE TITLE
WASD control behaves oddly on Codepen with master

### ISSUE THREAD

**Issue by bryik** [aframevr/aframe#1729]
**Description:** 

With 0.2.0 I can click on the window and walk around with the WASD keys. But with master, control stays with the editor often resulting in WASD characters being added to code accidentally. Autorun makes this extra frustrating.

Master: http://codepen.io/bryik/pen/dXgQdQ

0.2.0: http://codepen.io/bryik/pen/yJRQKr

- A-Frame Version: master
- Platform/Device: Desktop Chrome/Codepen

**Comment by bleonard252** [comment]
I would imagine this is an issue regarding CodePen and not A-Frame.

**Comment by bryik** [comment]
@bleonard252 I don't think so, Codepen works fine with A-Frame 0.2.0.

**Comment by bleonard252** [comment]
Oh, yeah. Then maybe it's priority? Idk

**Comment by ngokevin** [comment]
For anyone looking, the code is in `src/components/wasd-controls.js`

**Comment by bryik** [comment]
Hmm, adding [a camera with wasd-controls but no look-controls](http://codepen.io/bryik/pen/AXNvYZ) fixes the issue. 

I guess the problem is with look-controls?

**Comment by ngokevin** [comment]
Some time within the last twelve days of bumping the dist, this has been fixed.

I tried a couple examples in CodePen using the latest master that I generated locally, WASD works again.

**Comment by bryik** [comment]
Are you sure this is fixed? I'm still experiencing the problem with the latest dist: https://codepen.io/bryik/pen/bZzXGP

**Comment by ngokevin** [comment]
Weird

**Comment by ngokevin** [comment]
@bryik lemme know if this works for you https://github.com/aframevr/aframe/pull/1797

**Comment by bryik** [comment]
@ngokevin Do you have a link I could try? How do I test it?

**Comment by ngokevin** [comment]
Re-working on it, another test shows it didn't work. So flaky :0

**Comment by bryik** [comment]
Dang. The only other clue I came across was that the problem does not occur with the [dist from 26 days ago](https://github.com/aframevr/aframe/blob/43cfbc0c18cc1da1d2d0230f75643fdfb2252a28/dist/aframe.js). Not sure if that helps.

Codepen: https://codepen.io/bryik/pen/XKOXWg

**Comment by ngokevin** [comment]
OK here's one where I remove `event.preventDefault()` in look controls canvas mousedown https://codepen.io/ngokevin/pen/AXNZwV

**Comment by bryik** [comment]
Ya, that works!
