### ISSUE TITLE
How to define the width height and position of web play in video and videosphere?

### ISSUE THREAD

**Issue by Mike2100** [aframevr/aframe#1730]
**Description:**
When I use video and videosphere in HTML5. I want to specify the width,height and position of the video player.  But It can't work. The web browser also shows the full screen and the video can be dragged any direction.
Who can help me? Thanks a lot
.
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>360 Video</title>
    <meta name="description" content="360 Video — A-Frame">
    <script src="js/aframe.js"></script>
  </head>
  <body> <div style="width:300px; height:200px;">
    <a-scene>
     
      <a-assets>
    
        <video id="video" src="https://ucarecdn.com/bcece0a8-86ce-460e-856b-40dac4875f15/"
               autoplay loop height="200" width="300" controls="controls" ></video>
      </a-assets>

      <a-videosphere src="#video" rotation="0 180 0"></a-videosphere>
    
    </a-scene>  </div>
  </body>
</html>

- A-Frame Version: 0.2.0
- Platform/Device:  PC computer

**Comment by dmarcos** [comment]
Issues are for bugs and feature requests. Please use stackoverflow for usage questions
