### ISSUE TITLE
Question: Does the VideoSphere work on Android and iOS?

### ISSUE THREAD

**Issue by jensvdh** [aframevr/aframe#1731]
**Description:**

Hi, I could not get the VideoSphere demo to work on Android or iOS devices. Is that a current limitation to the aframe.js library or is the demo code out of date? 

Specifically this one:
https://aframe.io/examples/showcase/videosphere/

I'd love to use aFrame for 360 video on mobile devices.

- A-Frame Version: Any
- Platform/Device: iOS, Android

**Comment by ngokevin** [comment]
It's a limitation of mobile browsers, not A-Frame

http://stackoverflow.com/questions/38380912/why-is-my-video-or-videosphere-not-playing-on-mobile-in-a-frame-vr/38380941#38380941
