### ISSUE TITLE
renderer resolution is blurry on desktop

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1733]
**Description:**

1. Open the Cube example.
2. See it is blurry.
3. window resize fixes it.

- A-Frame Version: master
- Platform/Device: desktop

### Blurry on desktop

<img width="1306" alt="screen shot 2016-08-09 at 3 29 03 pm" src="https://cloud.githubusercontent.com/assets/674727/17535856/073dedbe-5e46-11e6-9302-e0aa3e9db1cf.png">

### After resize

<img width="1126" alt="screen shot 2016-08-09 at 3 29 06 pm" src="https://cloud.githubusercontent.com/assets/674727/17535858/0816708a-5e46-11e6-936e-14349cbddcd1.png">

**Comment by ngokevin** [comment]
No longer reproducing for me.

**Comment by ngokevin** [comment]
Actually it still is. 

This is part of https://github.com/aframevr/aframe/issues/1735 and fixed by https://github.com/aframevr/aframe/pull/1747

**Comment by ngokevin** [comment]
### Blurry on desktop

<img width="1306" alt="screen shot 2016-08-09 at 3 29 03 pm" src="https://cloud.githubusercontent.com/assets/674727/17535856/073dedbe-5e46-11e6-9302-e0aa3e9db1cf.png">

### After resize

<img width="1126" alt="screen shot 2016-08-09 at 3 29 06 pm" src="https://cloud.githubusercontent.com/assets/674727/17535858/0816708a-5e46-11e6-936e-14349cbddcd1.png">

**Comment by ngokevin** [comment]
This might be because we are delaying default camera injection until the scene is loaded? 

https://github.com/aframevr/aframe/pull/1724
https://github.com/aframevr/aframe/issues/1754

**Comment by mkungla** [comment]
@ngokevin that is the issue for sure sine when I add `<a-camera></a-camera>` to composite  then it renders ok so problem is with default camera

**Comment by ngokevin** [comment]
OK thanks, i can come up with a fix
