### ISSUE TITLE
low mobile resolution in VR mode (iOS) 

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1735]
**Description:**

https://github.com/aframevr/aframe/pull/1701 addressed it somewhat, but compared to 0.2.0, the resolution is still degraded.

This is probably webvr-polyfill issues, but need to fix it somehow for the release.

### iOS (iPhone 6) / A-Frame 0.2.0

![img_3567](https://cloud.githubusercontent.com/assets/674727/17494244/b5823d32-5d68-11e6-8783-47898ccbcce1.PNG)

### iOS (iPhone 6) / A-Frame Master

![img_3568](https://cloud.githubusercontent.com/assets/674727/17494245/b583c062-5d68-11e6-98c4-da01bf0f31f1.PNG)

- A-Frame Version: master
- Platform/Device: iOS

**Comment by dmarcos** [comment]
This is a polyfill problem. The polyfill decides what size the canvas is going to have based on a data base of devices. The size is returned via `getEyeParameters`.

**Comment by ngokevin** [comment]
Yeah, I noted it is part of the polyfill and marked `needs dependencies fixed`. For now, we should hack the polyfill to get the behavior as it was before.

**Comment by dmarcos** [comment]
Also the polyfill introduces distortion so the image is going to look distorted on your display when not looked through the lenses.

**Comment by dmarcos** [comment]
I notice that the resolution values of the polyfill are also conservative. A compromise between image quality vs performance? Performance takes priority over image quality

**Comment by ngokevin** [comment]
Yeah, but it is a serious decrease in image quality with no noticeable performance gain on our example scenes. The decrease in resolution doesn't seem worth the distortion when testing side-by-side.

**Comment by dmarcos** [comment]
You also have an iphone 6.

**Comment by ngokevin** [comment]
We've been recommending latest smartphones for Cardboard (last two generations). That would be minimum iPhone 6.

**Comment by dmarcos** [comment]
I would change the title of this bug and remove artifacts. What you call artifacts are the effects of the distortion.

**Comment by iKoala** [comment]
I made the issue #1541 in another thread and I notice the same thing.
I tested v0.2.0 and the latest master branch in various devices, iPhone 6, Samsung Note 6, Redmi Note 4g and Samsung S6 with Google Cardboard. They all give the same result as @ngokevin testing.
As you guys mentioned it's the problem from webvr-polyfill but I think this is an important bug to A-Frame too.
My team has been trying to build a demo site with A-Frame but we really can't accept the display quality from the master branch, especially for text display. It's almost unreadable when the font size isn't huge enough on the screen.
It may increase the performance on mobile but I believe the current image quality isn't enough for quality production.

**Comment by mkungla** [comment]
@ngokevin and @dmarcos . perhaps aframe should enable us to set which camera effect is used when in vr mode. Since I have feeling that `THREE.VREffect` with distortion can't bring the comparable quality in detail as `THREE.StereoCamera` did in 0.2.0.

Something like 
`<a-scene vr-effect="default">`
`<a-scene vr-effect="stereo">`
if that makes sense.

**Comment by dmarcos** [comment]
We did not use `THREE.StereoCamera` in 0.2.0. The distortion is not done by `THREE.VREffect` is done natively by the browser or by the polyfill.

**Comment by mkungla** [comment]
@dmarcos hm some reason I false idea that 0.2.0 used stereo camera by how that looked and prop stereoRenderer but now checking it's clear. 

> with distortion can't bring the comparable quality in detail as THREE.StereoCamera

translates to then that the distortion made by polyfill to render HQ requires more memory than most mobile browser allow per tab

**Comment by ngokevin** [comment]
Flat desktop also has low resolution, the buffer scale patch fixes it.

**Comment by ngokevin** [comment]
Never mind, separate issues.

**Comment by xaddict** [comment]
I would like to reopen this, as it's still a problem on iOS 9 and below.

**Comment by mkungla** [comment]
Yes that is known issue at this point that resolution of VR effect on any mobile is quite low
Related #1873

**Comment by protyze** [comment]
This seems definitely not entirely fixed yet. Also on iOS 10 when you switch to VR-Mode when holding the Phone in Portrait-Mode.

I can reproduce it with the following example on an iPhone 6S with iOS 10 like this:

1. Open "https://aframe.io/examples/showcase/sky/" in Safari.
2. Hold your Phone in Portrait Mode & Switch to VR-Mode
3. Hold you Phone now in Landscape Mode --> you will see Blurry Textures
4. Quit VR-Mode
5. Hold your Phone in Landscape Mode & Switch to VR-Mode
6. Perfectly Sharp Textures

Is this still being addressed currently? Let me know if I can help in any way.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/issues/2008
