### ISSUE TITLE
THREE.WebGLRenderer.render: camera is not an instance of THREE.Camera.

### ISSUE THREAD

**Issue by darkwing** [aframevr/aframe#1739]
Seeing this on everything on master.

**Comment by mkungla** [comment]
@darkwing could you edit please your issue and  review the [guidelines](https://github.com/aframevr/aframe/blob/master/CONTRIBUTING.md) for contributing to this repository. 
Missing information about OS/Browser!

**Comment by darkwing** [comment]
Closing this as I no longer see it, may have been a caching issue.
