### ISSUE TITLE
Consider polyfilling NodeList Array methods (e.g., `filter`, `forEach`, `map`)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1752]
**Description:**

Newest versions of Chrome have already implemented this. Not sure about FF. But it would be ergonomic for developers to be able to use the Array methods rather than `for` loops. Not sure if we should modify NodeList prototype, or contain within the custom elements like `a-node`.

Looping in @darkwing

**Comment by darkwing** [comment]
Supposedly the likes of `forEach` and `map` are supported by all major browsers.  Might want to wait until after 0.3.0 to switch though, as we'll want to do lots of testing https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Browser_compatibility

**Comment by ngokevin** [comment]
That's the Array.forEach documentation, not NodeList :)

**Comment by darkwing** [comment]
Oh FFS, got passed around with links.  nm.

**Comment by ngokevin** [comment]
Gonna close, I don't think A-Frame should handle this.
