### ISSUE TITLE
At first load texture is blurred 

### ISSUE THREAD

**Issue by mkungla** [aframevr/aframe#1753]
If you check `/examples/showcase/composite/` seems that some of last PR's and not #1747 `BUFFER_SCALE` but some other result for me that in first load texture is totally blurred as soon as I resize it ok. 

1. Onload
![blur](https://cloud.githubusercontent.com/assets/15878458/17537067/499c8e0c-5ea2-11e6-8400-c3a5c033bef9.png)
2. After resize window
![ok](https://cloud.githubusercontent.com/assets/15878458/17537075/60598dca-5ea2-11e6-8ecc-e9f804e61b18.png)

- A-Frame Version: master
- Platform/Device: Linux / FF Developer Edition

**Comment by ngokevin** [comment]
Duplicate (also on the milestone) https://github.com/aframevr/aframe/issues/1733
