### ISSUE TITLE
Introduce third-party component using Service Workers to cache everything defined in `<a-assets>`

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1759]
**Description:**

It'd be beautiful if all assets in every scene were automatically cached by service workers.

Or perhaps cache everything fetched by three.js loaders in general. We should be able to hook into everything that three.js loaders fetch (which is stored in THREE.Cache).

[Service Workers: Cache then Network](https://serviceworke.rs/cache-then-network_index_doc.html)

**Comment by mkungla** [comment]
Just to keep it mind that with `audio` and `video` `THREE.Cache` can cause problems since you can't modify `ArrayBuffer` after it is attached so you may ran into.
>   Uncaught InvalidStateError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': Cannot set buffer after it has been already been set

**Comment by donmccurdy** [comment]
Service Workers act as HTTP request interceptors, and can choose to resolve a request with data from IndexedDB immediately? Seems like that could be cleanly separated from AFRAME, aside from registering some sort of cache-clearing mechanism.

**Comment by cvan** [comment]
> Service Workers act as HTTP request interceptors, and can choose to resolve a request with data from IndexedDB immediately?

That's one use case, yep. You could create a "synthetic"/mock REST API.

I think Service Workers are more useful here as a pass-through cache: upon requested, if the resource matches a certain host, path, and/or extension, cache the resource after the response has been fulfilled. Also, selectively caching resources that will be used often and not change - that's also a great use case. Or, even if they are used often, the Fetch + Cache APIs are super powerful when used within a Service Worker. There are lots of interesting use cases, especially for WebVR. The obvious end goal being to have a completely offline VR experience, but the low-hanging fruit is obviously quicker loading times with aggressive caching.

IME, a Service Worker for A-Frame scenes is not premature optimisation. But, YMMV, definitely.

Also, IMO, there should be multiple configuration options. Caching the resources (and invalidating them appropriately) can make all the difference in the network response time. Offline is obviously a great goal to have in mind, but at least to start, scenes will load *drastically* faster with default/smart Service Workers that can be enabled. (I had some decent luck with Service Worker-ify-ing [DrawVR](http://drawvr.com/)'s scenes and was messing around with them for the [Holodeck Club](https://github.com/holodeck-club/holodeck-club.github.io/)).

[sw-toolbox](https://github.com/GoogleChrome/sw-toolbox/blob/master/recipes/cache-expiration-options/service-worker.js) IME works pretty well without having to write a ton of boilerplate code.

* https://googlechrome.github.io/samples/service-worker/custom-offline-page/
* https://googlechrome.github.io/samples/service-worker/selective-caching/
* https://googlechrome.github.io/samples/service-worker/prefetch/
* https://serviceworke.rs/
* https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker#service-worker-recipes
* https://github.com/holodeck-club/holodeck-club.github.io/blob/d274e3c/common/assets/js/lib/webvr-commander.js#L35-L41, https://github.com/holodeck-club/holodeck-club.github.io/d274e3c/master/sw.js
* https://github.com/fxos-components/serviceworkerware
* https://github.com/googlechrome/sw-toolbox

**Comment by cvan** [comment]
Here are the related issues for the https://aframe.io site (aframevr/aframe-site#110) and the Examples we show there (aframevr/aframe-site#110).

**Comment by ngokevin** [comment]
What do you think about an opt-out API?

```html
<a-assets sw-cache-ttl="3">  <!-- Invalidate in 3 days. -->
  <img id="myTexture" src="texture.png">  <!-- Will get cached by default. -->
  <a-asset-item id="myModel" src="myModel.obj" sw-cache="false">  <!-- Will not get cached. -->
</a-assets>
```

**Comment by Coder206** [comment]
@ngokevin I like it, flexibility is always welcome in my opinion.

**Comment by donmccurdy** [comment]
My two reservations about an opt-out API would be:

1. Users should be able to fork and/or add custom modules to the SW, since a site only gets one. Physics would also seriously benefit from SW, which I haven't configured with aframe-extras.physics yet, but it's definitely a goal.
2. For opt-out – I don't think it's possible to both install and run a SW from the same script; you need to invoke `navigator.serviceWorker.register('/sw.js')` and then that file needs to just be there. This makes Browserify and Webpack dev workflows pretty incompatible. So the current add-aframe.js-and-go would need to be replaced with more of a prescriptive boilerplate.

**Comment by cvan** [comment]
I would definitely have the units for expiry not be in days - need to be way more granular (even preferable to be in sec or ms).

**Comment by cvan** [comment]
> 2. For opt-out – I don't think it's possible to both install and run a SW from the same script; you need to invoke `navigator.serviceWorker.register('/sw.js')` and then that file needs to just be there. This makes Browserify and Webpack dev workflows pretty incompatible. So the current add-aframe.js-and-go would need to be replaced with more of a prescriptive boilerplate.

We can document this. And it can be optional. Also, see https://github.com/GoogleChrome/sw-precache. TBH, it's probably asking some library maintainers (maybe folks on the Polymer team?) how they plan on maintaining SW.

What I would do is just make it really easy to opt-in with config settings (which IMO we should have on `require('aframe')`/`window.AFRAME` - and have the `sw.js` URL easy to download (or pull from npm).

<hr>

This is part of a larger discussion that I'll postpone having in this issue, but I've been thinking about Webpack for a while now. and it seems like it might help us do some nice custom builds with ease. and the size savings seem to be quite significant. I was a Browserify proponent back in the day, but the "flavour of the month" seems to have something to it. We can discuss in another build.

Thanks for all the feedback, y'all. Appreciated.

**Comment by Coder206** [comment]
@cvan Does this affect my work in https://github.com/aframevr/aframe-site/issues/110 and https://github.com/aframevr/aframe-site/issues/111 ?

**Comment by cvan** [comment]
@Coder206 nope, this can be totally different. I would try aframevr/aframe-site#110 first and then see which best practices you can borrrow for aframevr/aframe-site#111 (which technically could live in this repo [aframevr/aframe]). Or it could be part of a hexo pre-deploy script, whichever.

**Comment by Coder206** [comment]
@Coder206 Noted!

**Comment by cvan** [comment]
Relevant: Relevant: https://medium.com/@addyosmani/offline-storage-for-progressive-web-apps-70d52695513c

**Comment by cvan** [comment]
Btw, I filed #951 back in Feb. Do you want to keep that open? My inclination is to have this issue be for investigating SW and writing an opt-in component. And then #951 would be for including an example of using aforementioned component. Sound good?

**Comment by ngokevin** [comment]
yeah sounds good

**Comment by delapuente** [comment]
My fork of A-Frame now includes a Service Worker you can check in https://delapuente.github.io/aframe

The experiment allows revisiting demos offline after you already visited it while online, including the index of all demos.

Some of the current problems include:
  - [ ] Dealing with 360º video since cache API does not store 206 ranged responses. 
  - [ ] Adding the SW to the dev workflow in a non-intrusive way. Perhaps caching assets but not js files during development.
  - [ ] Improving first visit experience by pre-caching assets for VR experiences we know the user will visit sooner than later.

Regarding the last problem, I'm worried about space. VR demo experiences tend to be ephemeral but bandwidth consumers. Assets weight is why I prefer to be lazy when pre-caching.

**Comment by ngokevin** [comment]
would leave as a separate generator tool for a-assets and can link from docs

meanwhile https://www.supermedium.com/blog/service-workers
