### ISSUE TITLE
Clearly state browser support in docs / Embed caniuse into Support docs

### ISSUE THREAD

**Issue by darkwing** [aframevr/aframe#1761]
A quick docs search didn't provide information about browser support.  It would be cool to provide a minimum browser version alongside the device / mobile support in FAQ.

We should also consider adding a brief device/mobile support block to the Docs "Overview" page as people will probably want to know this before getting started.

**Comment by ngokevin** [comment]
We mention it at:

https://aframe.io/docs/master/guide/device-and-platform-support.html

and I believe the new FAQ will lead to this page as well. I deferred to caniuse and iswebvrready because the browser support will be changing outside of the scope of A-Frame.

**Comment by ngokevin** [comment]
Although just briefly. I suppose I could highlight it more with a Browser Support section

**Comment by darkwing** [comment]
I agree with CanIUse as a general rule but people look for browser names at a glance, and since the WebVR spec probably chances fairly slowly, it may be worth adding the browser names as keywords.

**Comment by darkwing** [comment]
Your link 404s for me, btw

**Comment by mkungla** [comment]
Heard that  WebVR API will  be put into [caniuse](http://caniuse.com/). It would be difficult to maintaining own browser list and keep it up to date.

**Comment by donmccurdy** [comment]
@mkungla that'd be really nice in combination with https://caniuse.bitsofco.de/

**Comment by ngokevin** [comment]
https://aframe.io/docs/0.8.0/introduction/vr-headsets-and-webvr-browsers.html#what-is-webvr

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/b610a2f76537e506d69ea046a803af0d3007d1bb
