### ISSUE TITLE
Embed more CodePens within documentation

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1763]
**Description:**

We currently show examples as code/text in every page. It would be nice to also embed CodePens so people can play with the examples.

Not sure how we maintain visual quality of the examples though. We might want a visual style guide. And a simplicity bar for the examples.

**Comment by dmarcos** [comment]
Can we just embed aframe scenes?

**Comment by ngokevin** [comment]
We could, but users wouldn't be able to play with them (e.g., change some values and see the effects).

**Comment by dmarcos** [comment]
That's what the inspector is for :). We have to make the inspector work with embedable / multiple scenes

**Comment by ngokevin** [comment]
This is more for code documentation and learning to code A-Frame. Inspector could help you see the effects of changing property values, but CodePen would be good for explaining HTML/JS bits.

**Comment by ngokevin** [comment]
Embedded scenes work, don't like to rely on a service.
