### ISSUE TITLE
Add link of CONTRIBUTING.md in README.md

### ISSUE THREAD

**Issue by gurumukhi** [aframevr/aframe#1764]
@ngokevin can you please suggest what can I write on with the link?

e.g. Interested in contributing to A-Frame? Check [A-Frame contributors document](CONTRIBUTING.md).

**Comment by ngokevin** [comment]
Perhaps:

```
## Contributing

Check out the [Contributing Guide](CONTRIBUTING.md)!

## License
```

**Comment by gurumukhi** [comment]
https://github.com/aframevr/aframe/pull/1767
