### ISSUE TITLE
Grammar error in Docs FAQ

### ISSUE THREAD

**Issue by Haydos585** [aframevr/aframe#1772]
There is currently a grammar error in the FAQ documentation.

Currently the text says: _"Why does my asset (e.g., image, video, model) not loading?"_

I think it should be changed to either:
Why _is_ my asset (e.g., image, video, model) not loading?
or
Why does my asset (e.g., image, video, model) not _load_?

**Comment by mkungla** [comment]
@Haydos585 you can to PR with changes!?

**Comment by Haydos585** [comment]
@mkungla - Yep, I'll do it today. Because it's such a small change I wasn't sure if it's worthy of a pull request or just a quick change. PR incoming!

**Comment by ngokevin** [comment]
there's an edit button at bottom of docs that makes it super simple in case you didn't catch it
