### ISSUE TITLE
Update showcase and boilerplates

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1773]
**Description:**

I was working within a [separate aframe-boilerplates repository](https://github.com/aframevr/aframe-boilerplates). After about a week of thinking, it'd be best to move them into the A-Frame repository to consolidate. 

My idea on how we'd work on examples:
### Showcase

The **Showcase** consists of examples that are easy to learn from, demonstrate features, **and** demonstrate use cases. Essentially the type of examples in `aframe-boilerplates` will live here. Showcase examples that are not easy to learn from (anime UI) or demonstrate use cases (anime UI, composite, curved mockups) will be moved out.

Examples that I imagine would soon live in Showcase:
- Model (from MagicaVoxel)
- 360 Image
- 360 Video
- 360 Image Gallery
- Audio Visualizer
- Multiuser
- Tracked Controllers
- Ball Throw
- Painter
- Shooter
- Dodgeball (Arena)

The showcase will have a package.json to be published to NPM. The A-Frame site can automatically install them to showcase on the homepage with source code + links.

The condition would be that examples allow for some "second-party components" (i.e., third-party components we approve). They won't have to be committed into the repo or installed, I have them linking to npmcdn (e.g., `<script src="https://npmcdn.com/aframe-firebase-component@3.0.0">`).

Each example would have a **guide/case study** on how it was built in the `README.md`. I can have the aframe-site consume these and add it to the docs automatically.
### Boilerplates

Since the new showcase act as boilerplates, we can get rid of the `boilerplates/` folder.
### Organization

I would also consolidate the `primitives/`, `performance`, and `animation/` into `test/`. That way the showcase isn't hidden away in a folder. I'd also move all `assets/` to the `assets` repo. The new folder structure would look like:

```
aframe/
  examples/
    360-image/
      AFRAME_SITE.yml (metadata)
      components/
      index.html
      README.md
    360-image-gallery/
    360-video/
    ball-throw/
    index.html
    painter/
    shooter/
    test/
```

**Comment by dmarcos** [comment]
Yeah boilerplates are complete mini applications that illustrate a speficic application of a-frame

**Comment by dmarcos** [comment]
Tests show a specific feature in isolation. They can be more abstract than showcases. The purpose of these is simple working examples we can point people too and also for our manual integration tests

**Comment by ngokevin** [comment]
This issue is a bit too broad to tackle. Will try over time to have these out, maybe via Glitches and some in the A-Frame School.
