### ISSUE TITLE
a-entity merge attribute

### ISSUE THREAD

**Issue by mkungla** [aframevr/aframe#1778]
Thoughts about if there would be `a-entity` attribute `merge` which would behave as `geometry.mergeTo`,  with difference that you set it on parent?

So instead of writing

``` html
<!-- or using mixin -->
<a-assets>
  <a-mixin id="merge" geometry="mergeTo:#parent; skipCache: true; buffer: false"></a-mixin>
</a-assets>
<a-entity id="parent"></a-entity>
<a-entity mixin="merge"></a-entity>
<a-entity mixin="merge"></a-entity>
```

you could set `merge` attribute on parent `<a-entity>` and merge all it's children

``` html
<a-entity id="parent" merge>
  <a-entity></a-entity>
  <a-entity></a-entity>
</a-entity>
```

**Comment by dmarcos** [comment]
I don't see how to make a  generic `merge` attribute have any sort of predictable behavior. Some entities might have geometries others won't... What happens in that case? In the context of a geometry at least the user is explicitly saying what she wants. Generic merging and grouping could be better implemented in higher level tools. I'm going to close this and please reopen if someone has any good ideas on how to implement this.
