### ISSUE TITLE
Automated grammar check for documentation

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1785]
**Description:**

All of our docs and guides are in `docs/`. It would be cool to have a script check grammar/typos across all the docs.

Examples:
- https://github.com/robinvdvleuten/gingerbread
- Prose checkers: https://github.com/btford/write-good / https://github.com/ngokevin/engrish

**Comment by Coder206** [comment]
@ngokevin This issue interests me. Can I help?

**Comment by dmarcos** [comment]
@Coder206 go for it

**Comment by Coder206** [comment]
@ngokevin I am thinking that the script could be executed by NodeJS when running `npm start` and then shows in the output the grammar errors and typos. Any thoughts?

**Comment by mkungla** [comment]
I have feeling that should not be as part of `npm start` (`npm run dev`) .
Seeing that more as independent script which maybe executed as  part of `npm run precommit`, but that's just a thought.

**Comment by Coder206** [comment]
@mkungla I understand your point. I agree, that would be a better way of doing it.

**Comment by cvan** [comment]
[Grammarly](https://www.grammarly.com/) is also quite good

**Comment by Coder206** [comment]
@cvan Perhaps we could try it and compare with @ngokevin's suggestions to see which works best.

**Comment by ngokevin** [comment]
Grammarly is a browser extension, we're looking for something we can run as a script on our files

**Comment by cvan** [comment]
I know, was just suggesting it because I know a lot of companies and schools use it (so it's probably decent). I've used it with some luck a few times. As for automated scripts, I saw the one you wrote, which is cool, and I'm sure there are many, many others out there. I'm sure y'all have done your research. I found these links, if they're of any help:

https://github.com/mrmarbles/wordsworth
https://www.chromium.org/developers/design-documents/extensions/proposed-changes/spellcheck-api
http://codepen.io/aecend/pen/rOebQq

**Comment by ngokevin** [comment]
thanks for the research. so far i think gingerbread looks the most complete, although it relies on an external service. most of our doc typos so far have been grammatical in nature rather than spelling

**Comment by Coder206** [comment]
@cvan Thanks, it's appreciated :)

**Comment by Coder206** [comment]
@ngokevin I have been experimenting with Gingerbread and it has been pretty inaccurate on correcting the errors of the MD files in docs. Upon every new line, it wants a capital letter and it tried to change `<a-scene>` to `<a-scan>`.

**Comment by ngokevin** [comment]
Thanks for experimenting! Maybe we can trim code snippets?

```
var gingerbread = require('gingerbread');

var text = readFileSync('blah.md', 'utf-8').contents;
cleanedText = removeCodeSnippets(file);

gingerbread(cleanedText, function (error, text, result, corrections) {
  // result contains 'The smell of flowers brings back memories.'
});
```

This includes inline code blocks (separated by backticks) as well as entire code blocks (separated by triple backticks).

**Comment by Coder206** [comment]
@ngokevin Great idea! Should we also trim all the `.md` files stuff like `#`?

**Comment by ngokevin** [comment]
Yeah, and the YAML headers. And links. It will take some fine tuning, but would be useful to many other projects too.

**Comment by achukavya** [comment]
I want to work on this..

**Comment by ngokevin** [comment]
wontfixing unless someone has an easy idea
