### ISSUE TITLE
browserify-istanbul obfuscates code and make test debugging imposible

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#1793]
`browserify-istanbul` and `codecov` should only run in a travis environment

**Comment by dmarcos** [comment]
@mkungla do you know how can we make `browserify-istanbul` only run in travis but not on desktop?

**Comment by mkungla** [comment]
@dmarcos yes there is multiple ways how to move coverage to CI or attach it to `npm run test:ci` so you could still generate local coverage if you want.

**Comment by ngokevin** [comment]
I fixed by using the CI env var.

**Comment by mkungla** [comment]
@ngokevin there is no coverage generated at all now
