### ISSUE TITLE
"Composite" example throws many `WebGL: texImage2D` errors in Firefox

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1801]
**Description:**

[http://localhost:9000/examples/showcase/composite/](http://localhost:9000/examples/showcase/composite/)

In Firefox Nightly (51.0a1 [2016-08-04]):

![image](https://cloud.githubusercontent.com/assets/203725/17686473/a4b441da-6321-11e6-8437-271c2dec43ad.png)

And 256 errors in Chrome:

![image](https://cloud.githubusercontent.com/assets/203725/17686485/b60349b8-6321-11e6-89a3-19ab28aa2d79.png)
- A-Frame Version: 115cecc
- Platform/Device:
  Google Chrome Version 52.0.2743.116 (64-bit)
  Firefox Nightly (51.0a1 [2016-08-04]) (64-bit)
  Mac OS X

**Comment by cvan** [comment]
Also, that `THREE.WebGLRenderer.render: camera is not an instance of THREE.Camera.` error - I see that one in several other examples too. Should I file a separate issue for that one?

**Comment by ngokevin** [comment]
I think your server is serving outdated builds for the issues you've filed so far. Can you double check?

**Comment by cvan** [comment]
The THREE.js error is gone in Chrome and the `Offscreen-For-WebGL` errors in Chrome seem to happen periodically. I can get them to trigger every dozen or so refreshes - and in other scenes too. 

Anyway, I can confirm ton of errors in Firefox still persist with the latest changeset:

![image](https://cloud.githubusercontent.com/assets/203725/17686561/7c04cb46-6322-11e6-9fc3-b1a726891d07.png)

**Comment by ngokevin** [comment]
The offscreen errors might be legit, although very minor. Maybe nothing to render for a couple frames as the assets load or something.

I don't get the errors in Firefox. Will leave it open though.

**Comment by mkungla** [comment]
**Firefox Developer Edition** here

![screenshot from 2016-08-16 06-18-52](https://cloud.githubusercontent.com/assets/15878458/17686960/9ee9ffc6-6379-11e6-9063-6c4bb4f85030.png)

**Comment by ngokevin** [comment]
Might be texture power of two resizing

**Comment by cvan** [comment]
> Might be texture power of two resizing

Thought so at first, but there are no POT three.js warnings like there are in other scenes:

![screen shot 2016-08-15 at 8 33 55 pm](https://cloud.githubusercontent.com/assets/203725/17687158/a159cd88-6327-11e6-833a-abc79c407fd1.png)

**Comment by dmarcos** [comment]
I cannot reproduce any of the problems described above. The only message I still get is three instances of `Error: WebGL warning: texImage2D: Conversion requires pixel reformatting.` on Firefox. It seems that the textures are following a slow path in Firefox: 

![slow path](https://d3vv6lp55qjaqc.cloudfront.net/items/0m1B062X362H1E3o3C1C/Image%202017-05-11%20at%204.50.30%20PM.png?X-CloudApp-Visitor-Id=222920&v=d4d3e86e)

I don't think there's anything actionable on the a-frame side of things. There's already a gecko bug tracking these conversion issues https://bugzilla.mozilla.org/show_bug.cgi?id=1246410

**Comment by cvan** [comment]
yeah, it appears fixed.

FWIW, there are a lot more warnings on Mac:

<img width="1261" alt="screen shot 2017-05-12 at 1 12 59 am" src="https://cloud.githubusercontent.com/assets/203725/25989248/33206996-36b0-11e7-925d-d712812f1f21.png">

I assume either WebGL bugs caused by three.js or just underlying platform bugs in Gecko.

**Comment by dmarcos** [comment]
Those are legit use of extensions that for whatever reason are not available on Firefox for Mac. Those should be fixed on the gecko side
