### ISSUE TITLE
Look-controls inconsistent in Chrome (vs. Firefox) when mouse-dragging over browser chrome

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1802]
**Description:**
1. Load [http://localhost:9000/examples/boilerplate/panorama/](http://localhost:9000/examples/boilerplate/panorama/)
2. Click toward the top of the scene.
3. Drag upward toward the top of the browser chrome.
4. Release your mouse.
5. Return back to the same general area in the scene.

Try these steps in both Chrome and Firefox to see the difference. IMO, Firefox's behaviour feels right; it's what I expected.
- A-Frame Version: 115cecc
- Platform/Device: Google Chrome Version 52.0.2743.116 (64-bit), Firefox Nightly (51.0a1 [2016-08-04]) (64-bit); Mac OS X

**Comment by darkwing** [comment]
This can be removed with https://github.com/aframevr/aframe/pull/1913 right @ngokevin ?

**Comment by ngokevin** [comment]
nope that's different look-at vs. look-controls behavior

**Comment by ngokevin** [comment]
Closing because I think this issue is too minor

**Comment by cvan** [comment]
> Closing because I think this issue is too minor

It's still an issue. If you reproduce this in the right steps, you can experience the weirdness with the movement of the scene. Often times it happens when I'm just normally mouse-dragging and then bam 💥!
