### ISSUE TITLE
opacity attribute for a-entity 

### ISSUE THREAD

**Issue by fuleinist** [aframevr/aframe#1809]
**Description:**
Is there a way to have opacity attribute on  a-entity so all objects included can be hide and show triggered by an animation?

- A-Frame Version: 0.2.0
- Platform/Device: All

**Comment by dmarcos** [comment]
You do `entityEl.setAtrribute('visible', true / false);`

**Comment by theredwillow** [comment]
This doesn't allow for opacity animations. I'd like to be able to fade in and out constructed entities.
