### ISSUE TITLE
examples on aframe.io try to load resources from localhost?

### ISSUE THREAD

**Issue by marianoguerra** [aframevr/aframe#1811]
**Description:** trying to see examples on https://aframe.io/examples/showcase/hello-world/ but they don't load, the dev console shows errors of requests trying to load files from localhost, like: 

    Blocked loading mixed active content “http://localhost:9000/examples/boilerplate/hello-world/”
    Blocked loading mixed active content “http://localhost:4000/examples/index.json”

in the top of the html file (ctrl+u) there are some urls pointing to localhost:

      data-site-base-url="http://localhost:4000"
      data-site-root-path="/"
      data-site-home-url="http://localhost:4000/"
      data-lib-home-url="http://localhost:9000"
      data-lib-examples-url="http://localhost:9000/examples"

- A-Frame Version: the one deployed in aframe.io
- Platform/Device: firefox nightly, ubuntu 16.04

**Comment by ngokevin** [comment]
This has been fixed. Thanks for reporting!
