### ISSUE TITLE
Consider serving `docs/` as rendered Markdown HTML w/ A-Frame's local dev server

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1818]
Using something like [`markserv`](https://github.com/f1lt3r/markserv) as a dev dependency.

So you don't have to stand up both the `aframe-site` repo _and_ this `aframe` repo.

A very nice-to-have (but, of course, low-priority) feature.

**Comment by ngokevin** [comment]
sounds good

**Comment by MichaelRupertDev** [comment]
Looking at this one.
