### ISSUE TITLE
Recording scenes

### ISSUE THREAD

**Issue by Coder206** [aframevr/aframe#1822]
I would like to see the ability to record and add additional cameras to scenes and export the views. Something similar to NVIDIA's ANSEL.

**Comment by ngokevin** [comment]
You can use the CubeCamera from three.js: http://threejs.org/docs/api/cameras/CubeCamera.html

And something like grabbing the render output from a renderer using the camera: http://stackoverflow.com/questions/15558418/how-do-you-save-an-image-from-a-three-js-canvas

I haven't done this yet so I don't have specifics. But you can definitely research, and it would be cool to see someone do it.

**Comment by cvan** [comment]
Relevant links:
https://hacks.mozilla.org/2016/04/record-almost-everything-in-the-browser-with-mediarecorder/
https://mozdevs.github.io/MediaRecorder-examples/

Could easily build an A-Frame component using the `MediaRecorder` API (in very few lines too).

**Comment by ngokevin** [comment]
I think this is for 360 recording or recording from an external in-scene camera, rather than a screencap.

**Comment by Coder206** [comment]
@cvan @ngokevin was right I am definitely interested in your that too
