### ISSUE TITLE
360 Video and Panorama cannot show

### ISSUE THREAD

**Issue by Hongbo-Miao** [aframevr/aframe#1833]
Go here https://aframe.io/

These two demo cannot show

- 360 Video https://aframe.io/examples/showcase/videosphere/
- Panorama https://aframe.io/examples/showcase/sky/

**Comment by ngokevin** [comment]
Fixed by @cvan, thanks!

**Comment by Hongbo-Miao** [comment]
You are welcome, looks awesome!

**Comment by mountainguan** [comment]
videosphere only can show on PC browser.

**Comment by cvan** [comment]
Also see #316 and https://aframe.io/docs/0.3.0/introduction/faq.html#why-does-my-video-not-play-on-mobile for more info.
