### ISSUE TITLE
Build with Components Tutorial needs editing

### ISSUE THREAD

**Issue by i3games** [aframevr/aframe#1838]
**Description:**

- A-Frame Version: 0.3.0
- Platform/Device: any

The description of the "update-raycaster" is component is confusing, especially as this is the second tutorial beginners will be reading. Without diving deep into the source of [the image gallery boilerplate](https://github.com/aframevr/360-image-gallery-boilerplate) it is impossible to understand. Most crucial, there is no mention of the element the component is attached to. The "set-image component" should have more explanation as well. 

I can try a documentation update / pull request if desired and not already in the works.

**Comment by ngokevin** [comment]
Thanks, I agree, it needs an iteration. I'm trying to get more boilerplates into the repo each with a guide so this guide will be de-emphasized.

**Comment by i3games** [comment]
I think the sequence of tutorials is quite good. One for HTML, one for using / writing components and one for MagicaVoxel which I'm looking into right now.  Just needs some more detail on the components.

**Comment by ngokevin** [comment]
thanks, we've just remove that section since we had a patch that makes it no longer necessary.

i will try to get a guide some time about detailed case studies on writing different kinds of components
