### ISSUE TITLE
Configuring the cursor's raycaster does not work (component ordering/dep bug)

### ISSUE THREAD

**Issue by bryik** [aframevr/aframe#1841]
**Description:** The documentation says we can ["customize the raycasting pieces of the cursor...by changing the raycaster component properties"](https://aframe.io/docs/0.3.0/components/cursor.html#configuring-the-cursor-through-the-raycaster-component). But attempting to restrict the cursor to a certain class using the raycaster's 'objects' property does not work (all entities remain active).

CodePen: https://codepen.io/bryik/pen/VjRgyk
- A-Frame Version: 0.3.0
- Platform/Device: Chrome/Windows

**Comment by bryik** [comment]
This may be caused by confusion between the raycaster created by the cursor (as a dependency) and the raycaster added in markup.

I had the same problem with the vive-cursor component and "solved" it by having the raycaster's 'objects' property set by the vive-cursor component during initialization.

**Comment by ngokevin** [comment]
I got it working in https://github.com/aframevr/aframe/pull/1845

I wonder if it's a component initialization order issue.

**Comment by bryik** [comment]
>I wonder if it's a component initialization order issue.

Putting the raycaster component before the cursor component [works as it should]( https://codepen.io/bryik/pen/PzAGRa).

The code sample on the cursor's doc page could be amended, but ideally the order wouldn't matter.

**Comment by ngokevin** [comment]
fixed
