### ISSUE TITLE
Order in obj-model & material components affects result

### ISSUE THREAD

**Issue by feiss** [aframevr/aframe#1848]
I'm trying to use an OBJ model without MTL, and specify the material by hand, using a `material` component. If I put the obj-model first:

``` html
<a-entity obj-model="obj: #my_model" material="color:#ff0000"></a-entity>
```

the material is ignored, and a default material is added (checked with inspector). But if I swap the order and put the material component first:

``` html
<a-entity material="color:#ff0000" obj-model="obj: #my_model" ></a-entity>
```

...the correct material is applied
- A-Frame Version: 0.3.0
- Platform/Device: Chromium + Windows + HTC Vive

**Comment by ngokevin** [comment]
Thanks for catching this.

The `obj-model` component has an initialization dependency on the `material` component. But it seems that it's not being honored?

**Comment by ngokevin** [comment]
fixed
