### ISSUE TITLE
Suggestion: Can we add "nod" and "shake" events bind to camera?

### ISSUE THREAD

**Issue by fuleinist** [aframevr/aframe#1849]
This is very common in other VR framework (e.g. https://www.assetstore.unity3d.com/en/#!/content/23585). So it will be triggered if the camera nod or shake for more than 3 times. 

It can be very useful to track head gestures. and gather user feedback without a controller.

**Comment by dmarcos** [comment]
Thanks for the feedback. Those events should be provided by an external component. They are out of the scope for aframe core.
