### ISSUE TITLE
GearVR camera is the wrong height

### ISSUE THREAD

**Issue by andygill** [aframevr/aframe#1856]
**GearVR camera height incorrect:**
- A-Frame Version: 3.0
- Platform/Device: GearVR
## To reproduce
- Install browser inside GearVR Oculus homepage
- Turn on WebVR (using `internet://webvr-enable`)
- goto https://aframe.io/
- click to enter VR.

You are at height 0, the floor, not 1.8, like Carboard and 2D screen versions.

I see in the documentation: https://aframe.io/docs/0.3.0/components/camera.html

_"When not in VR mode, userHeight translates the camera up to simulate human height. The injected camera has this set to 1.8 (meters). When entering VR, this height offset is removed such that the absolute position return from the VR headset is used. This is very convenient for experiences that work both in and out of VR, as well as making experiences look decent from the monitor as opposed to clipping the ground if the headset was resting on the ground."_

So I suspect that we need a special case for fixed-position headsets, like the GearVR, to use the 1.8.

**Comment by ngokevin** [comment]
Crap, thanks.

**Comment by ngokevin** [comment]
Here's a workaround:

```js
AFRAME.registerComponent('gearvr-height-fix, {
  dependencies: ['position'],

  init: function () {
    if (!AFRAME.utils.isGearVR) { return; }
    var position = this.el.getComputedAttribute('position');
    position.y += 1.6;
    this.el.setAttribute('position', position);
  }
});
```

```html
<a-entity gearvr-height-fix>
  <a-camera></a-camera>
</a-entity>
```

**Comment by msj121** [comment]
Will this be fixed in the future by default without the component? Or should I put this into my scenes from now on.

**Comment by poshaughnessy** [comment]
I think AFRAME.utils.isGearVR should be AFRAME.utils.isGearVR(), otherwise it's just checking for the existence of the function (and so it returns true for other browsers).

Does this workaround need a component, or could it perhaps be simplified with something like:

```
if (AFRAME.utils.isGearVR()) {
    cameraEntity.setAttribute('position', '0 1.8 0');
}
```

Like @msj121 I am worried about this breaking in the future though. Also, it fixes your height in fullscreen mode, but it breaks your starting height when viewing inside the initial Gear VR browser frame.

**Comment by ngokevin** [comment]
@poshaughnessy Fixed to call `isGearVR()` correctly. 

Will get around to a proper fix.
