### ISSUE TITLE
Stats not working as intended

### ISSUE THREAD

**Issue by BSVogler** [aframevr/aframe#1865]
**Description:**
I added stats to my scene as described in the [documentation example](https://aframe.io/docs/0.3.0/components/stats.html). Previously it was working but with the enabled stats module I only get this empty stats window.

- A-Frame Version: 0.3.0
- Platform/Device: Mac Os Safari 9.1.2

- Reproducible Code Snippet or Demo URL [highly encouraged]:
```
<a-scene stats/>
...
</a-scene>
```

![bildschirmfoto 2016-08-27 um 12 27 20](https://cloud.githubusercontent.com/assets/801818/18026768/a4e84d16-6c51-11e6-87ec-b77294d3375b.png)

**Comment by BSVogler** [comment]
Error message in log:

> [Error] TypeError: window.performance.getEntriesByName is not a function. (In 'window.performance.getEntriesByName("render-started")', 'window.performance.getEntriesByName' is undefined)
> 	e (aframe.min.js:229:110)
> 	(anonyme Funktion) (aframe.min.js:285:4944)
> 	t (aframe.min.js:285:514)
> 	l (aframe.min.js:285:4902)
> 	tick (aframe.min.js:111:1160)
> 	(anonyme Funktion) (aframe.min.js:149:5477)
> 	forEach
> 	value (aframe.min.js:149:5442)
> 	value (aframe.min.js:149:5619)
> 	(anonyme Funktion)
> 	e (aframe.min.js:149:4922)
> 	(anonyme Funktion) (aframe.min.js:149:5028)
> 	dispatchEvent
> 	fireEvent (aframe.min.js:271:805)
> 	(anonyme Funktion) (aframe.min.js:139:2526)
> 	map
> 	value (aframe.min.js:139:2491)
> 	(anonyme Funktion) (aframe.min.js:139:1207)
> 	promiseReactionJob

**Comment by Zeouterlimits** [comment]
Weird, it seems that Safari doesn't support that part of the WebAPI?

Verified that Safari does not support this function: [https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByName](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByName)

Chrome  52.0.2743.116 output:
```
window.performance.getEntriesByName("render-started")
[]
```

Firefox 48.0.1 output:
```
window.performance.getEntriesByName("render-started")
Array [  ]
```

Safari 9.1.2 (11601.7.7) output:
```
window.performance.getEntriesByName()
TypeError: window.performance.getEntriesByName is not a function. (In 'window.performance.getEntriesByName()', 'window.performance.getEntriesByName' is undefined)
```

**Comment by darkwing** [comment]
Good catch @BSVogler ! PR submitted!
