### ISSUE TITLE
Sound broken in >0.3?

### ISSUE THREAD

**Issue by dirkk0** [aframevr/aframe#1866]
**Description:**

Sound seems to be broken in Versions higher than 0.3.
If you change the pen below to 0.2.0, sound works.

Error messages are either
"'Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document':"
or 
"components:sound:warn Audio source was not specified with `src` +0ms"
if the file is local.

- A-Frame Version: 0.3.x
- Platform/Device: Ubuntu/Chromium and MacOSX/Chrome
- Reproducible Code Snippet or Demo URL [highly encouraged]: http://codepen.io/dirkk0/pen/GqVyqA

Thanks!

Best,
  Dirk

**Comment by darkwing** [comment]
Just tested cited demo and got sound in both Chrome and Firefox (on OS X)

**Comment by dirkk0** [comment]
Sorry, the pen had the 0.2.0 lib included (propably because of Autosave).
Could you please try again?

**Comment by darkwing** [comment]
Ahh, your `src` attribute needs to be `src: url('path/to/mp3')`

**Comment by dirkk0** [comment]
still doesn't work for me ... could you fork a pen?

**Comment by darkwing** [comment]
http://codepen.io/darkwing/pen/OXKKpg

**Comment by dirkk0** [comment]
Cool, thanks!
Ah ok, it's: `src: url(path/to/mp3)` then.
Is this the desired behaviour? Why did it change?

**Comment by dirkk0** [comment]
Yes, it is:
https://aframe.io/docs/0.3.0/components/sound.html
I came across the 0.2.0 documentation via Google. :-/
Closing this now.
