### ISSUE TITLE
Include controller/hand models in the builds

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1879]
**Description:**

The current `vive-controls` / `hand-controls` components require the assets served from the CDN. This adds the possibility for downtime, mistakes in case we ever accidentally modify/move those files, and now requires online connection. People can download the files and point the components to the URLs, but that requires a step. While they're in the core, we should include those JSON files via Browserify.

**Comment by dmarcos** [comment]
Should we do this now or wait until we can see a lot of people are using those models? Do we have data from the CDN?

**Comment by fernandojsg** [comment]
I believe most of the current users doesn't have a vive, and the increase of the size in the build could be also a problem, I would wait until we get more people using them

**Comment by ngokevin** [comment]
OK, they're pretty fat. Vives will have connection almost always anyways.
