### ISSUE TITLE
Dynamic src attribute broken in 0.3.0

### ISSUE THREAD

**Issue by vrimaginar** [aframevr/aframe#1881]
We are using a dynamic source attribute to the video tag and that's not working anymore in version 0.3.0. The reason we do this is to stream different bitrate and or resolution video to client devices. The error is: TypeError: r is null, 	

...ossorigin")?e:(r=e.getAttribute("src"),r.indexOf("://")===-1?e:extractDomain(r)=...

I suppose it has something to do with the error handling for wrong formatted src attributes implemented a couple of days ago (#899).

Question: can we have the implmentation back from 0.2.0 where a src attribute was not mandated in the video tag? 

- A-Frame Version: 0.3.0
- Platform/Device: all
- Reproducible Code Snippet or Demo URL [highly encouraged]:

<a-scene>
     <a-assets>
         <video id="#video"/>
     </a-asset>
     <a-videospehere src="#video"/>
</a-scene>

       [javascript to determine device/os]
       video =  document.getElementById('video');
       source = document.createElement('source');
			
	source.setAttribute('src', src);
	video.appendChild(source);
	video.play();

The above is simpliflied code (there should be some code there???)

**Comment by ngokevin** [comment]
If you use 0.3.0 stable, then #899 shouldn't apply. Are you using master or stable 0.3.0?

**Comment by vrimaginar** [comment]
We use 0.3.0 stable and the difference with 0.2.0 is that there seems to be an added check if the src attribute exists and if not it throws the above error. In 0.2.0 there was no check for the src attribute in the video tag (assets --> video).

**Comment by ngokevin** [comment]
I see. Will think about how to resolve that.

You can do a workaround by using entities.

`<a-entity geometry="primitive: plane" material>`

When you are ready, set the material src:

`el.setAttribute('material', 'src', 'url(myvideo.mp4)');`

**Comment by vrimaginar** [comment]
I wonder if autoplay works on the workaround you propose. I will try and see if that works. And by the way, thank you (and the other on the team) for a great framework and the effort you put in it.

**Comment by ngokevin** [comment]
This was introduced in https://github.com/aframevr/aframe/pull/1789

Need to update that code to not error if there's not a `src`

**Comment by ngokevin** [comment]
Fixed thanks
