### ISSUE TITLE
Cursor events don't fire correctly when multiple objects intersect the path

### ISSUE THREAD

**Issue by ryanbetts** [aframevr/aframe#1882]
In Aframe 0.3.0 the mouse events do not fire correctly when multiple objects intersect the raycaster/cursor. Unfortunately, this makes the cursor events unusable for any UI that has overlapping objects. This worked as expected in 0.2.0. 

Demo of the bug in 0.3.0: https://codepen.io/ryanbetts/pen/yaLVGL
Demo of it working in 0.2.0: https://codepen.io/ryanbetts/pen/bwGgoG

**Comment by ryanbetts** [comment]
I've fixed the bug and added to the Cursor test example. Everything seems pretty stable now. Let me know if everything looks okay.

**Comment by mountainguan** [comment]
<a-sky> and <a-entity> has a conflict.I want to using <a-sky> as my scene background and then create some 360 degree VR button.
