### ISSUE TITLE
The renderer size shouldn't depend on the window size

### ISSUE THREAD

**Issue by tbalouet** [aframevr/aframe#1884]
I just tried an aframe experiment with the Vive. Having the Chrome console open, the display size on PC screen was reduced, and I noticed the quality in the headset was worse than usual. It seems that the renderer size depends on the size of the original window. It should depend on the hardware (if PC=>Full HD, if smartphone=>HD) instead.
Try launching an aframe on the Vive with a very small browser window to reproduce
- A-Frame Version: 0.3
- Platform/Device: Windows 10 with HTC Vive on Google Chromium 53.0.2744.0 (64bit)
- Reproducible Code Snippet or Demo URL [highly encouraged]: any aframe demo (like https://aframe.io/examples/showcase/composite/)
  ![image](https://cloud.githubusercontent.com/assets/5400381/18213049/8e2cba72-7146-11e6-9201-c593c21a979a.png)

**Comment by dmarcos** [comment]
Thanks for reporting this. In principle the rendered size  when entering VR should be the one reported by the webvr API. More preciscely `vrDisplay.getEyeParameters`. This is managed by `VREffect`. I need to check how the window size is influencing the renderer size

**Comment by dmarcos** [comment]
This also reproduces on Firefox Nightly

**Comment by ngokevin** [comment]
don't think is an issue anymore?
