### ISSUE TITLE
Raycaster is not suitable for dynamic scenes

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#1886]
`refreshObjects` is only called on update https://github.com/aframevr/aframe/blob/master/src/components/raycaster.js#L47

If objects are added to the scene dynamically that match the query provided to the raycaster they won't be picked up

**Comment by ngokevin** [comment]
Component to update the raycaster when dynamic objects are added: https://github.com/aframevr/360-image-gallery-boilerplate/blob/master/components/update-raycaster.js

**Comment by ngokevin** [comment]
But listening to `child-attached` and check it against the selector sounds good.

**Comment by dmarcos** [comment]
That's a hack. Those functions are not part of the public API

**Comment by ngokevin** [comment]
You can improve it, but I previously intended it to be public since there wasn't any smart logic to check for dynamic entities: https://aframe.io/docs/0.3.0/components/raycaster.html#methods
