### ISSUE TITLE
No attribute named easing in a-animation, just easin

### ISSUE THREAD

**Issue by Utopiah** [aframevr/aframe#1888]
**Description:**
According to the [documentation](https://aframe.io/docs/0.3.0/core/animations.html#easing) the **easing** attribute controls the pace of an animation. Yet if one uses **easing** and not **easin** in an Aframe scene the entire scene blocks.

- A-Frame Version: at least 0.2 and 0.3
- Platform/Device: all
- Reproducible Code Snippet or Demo URL [highly encouraged]: http://jsbin.com/xaqumi/edit?html,output

**Comment by ngokevin** [comment]
bounce isn't a valid easing function, you have to prefix with ease-in or ease-out or ease-in-out

**Comment by Utopiah** [comment]
Correct, thanks, not sure how I managed to miss than especially since I used easing before without issues ;)
