### ISSUE TITLE
a-videosphere to accept 360 video from youtube src

### ISSUE THREAD

**Issue by fuleinist** [aframevr/aframe#1889]
Since a-videosphere is 

> an entity that prescribes a large sphere with the html5 video texture mapped to the inside

. Is it possible to render youtube embeded iframe texture instead?

**Comment by vrimaginar** [comment]
You can retrieve te url of a video with the youtube api. See https://developers.google.com/youtube/js_api_reference#Retrieving_video_information and look at the player.getVideoUrl():String function.

**Comment by fuleinist** [comment]
Thanks but the youtube video url is still not playable in video tag

**Comment by ngokevin** [comment]
Not quite possible, at least it won't be out of the box: http://stackoverflow.com/questions/36298195/how-to-render-youtube-videos-as-a-texture-in-a-frame?s=1|5.0516

**Comment by fuleinist** [comment]
@ngokevin  I did manage to use mediaelement.js and add a youtube flat video into the scene, but not as  a videosphare. 

Based on what youtube provided, seems the only ways is to render their iframe as a sphere.
