### ISSUE TITLE
Description of the vox file format

### ISSUE THREAD

**Issue by dpisarenko** [aframevr/aframe#1891]
Is there any detailed description of the VOX file format, apart from the [MagicalVoxel](https://ephtracy.github.io/index.html?page=mv_vox_format) page?

Do the links below refer to the VOX format used in MagicalVoxel?

* [Voxlap Voxel Model File](http://fileinfo.com/extension/vox)
* [Ken's Voxlap 6 Model File](http://fileinfo.com/extension/kv6)

On the homepage of [Ken Silverman](http://advsys.net/ken/build.htm) I found the following description of the file format.

> What's the .VOX file format?
> 
> Both SLABSPRI & SLAB6 support a simpler, uncompressed voxel format using the .VOX file extension. (See the documentation that comes with those programs.) The .VOX format is simple enough to fit a description of it right here. Here's some C pseudocode:
> 
> long xsiz, ysiz, zsiz;          //Variable declarations
> char voxel[xsiz][ysiz][zsiz];
> char palette[256][3];
> 
> fil = open("?.vox",...);
> read(fil,&xsiz,4);              //Dimensions of 3-D array of voxels
> read(fil,&ysiz,4);
> read(fil,&zsiz,4);
> read(fil,voxel,xsiz*ysiz*zsiz); //The 3-D array itself!
> read(fil,palette,768);          //VGA palette (values range from 0-63)
> close(fil);
> In the voxel array, use color 255 to define your empty space (air). For interior voxels (ones you can never see), do not use color 255, because it will prevent SLABSPRI from being able to take advantage of back-face culling.

Is it correct? Is the VOX file format described here the same as the one used by MagicalVoxel/AFrame?

**Comment by ngokevin** [comment]
Not sure. A-Frame doesn't depend on .VOX though, and suggested exports from MagicaVoxel is OBJ (or at least PLY).
