### ISSUE TITLE
The image in <a-assets> is not loaded at the first time on iOS devices

### ISSUE THREAD

**Issue by wendywy0660** [aframevr/aframe#1894]
**Description:** The image in a-assets is not loaded at the first time and have to refresh the page to get it working. The problem is only on iOS device.
- A-Frame Version: 0.3.1
- Platform/Device: iOS
- Reproducible Code Snippet or Demo URL [highly encouraged]: https://jsfiddle.net/s2ct3ztn/

**Comment by dmarcos** [comment]
I cannot reproduce this on A-Frame 0.5.0 and iOS 10.3.1. Please reopen if this is still an issue.
