### ISSUE TITLE
a-videosphere: Mouse controls are backwards (allow option to reverse drag look)

### ISSUE THREAD

**Issue by brianblakely** [aframevr/aframe#1896]
**Description:**

I would expect the image to move like everything else on the Web: in the opposing direction to my drag.  That behavior is more tactile.  Currently, the sphere POV follows the mouse drag.

I performed internal tests before opening this ticket.  All users pulled down on the mouse to look up.
- A-Frame Version: 0.3.1
- Platform/Device: Desktop
- Reproducible Code Snippet or Demo URL [highly encouraged]: N/A

**Comment by ngokevin** [comment]
Made this for now: https://github.com/ngokevin/kframe/tree/master/components/reverse-look-controls
