### ISSUE TITLE
Only one 'click' event is emitted when fusing on an entity

### ISSUE THREAD

**Issue by mattrei** [aframevr/aframe#1897]
In the current implementation, when fusing on an entity only the *first* successful fusing is emitting a 'click' event on that entity. 
When not leaving the entity with the cursor no more fusing will be done. Clicking with the mouse propagates of course further 'click' events.

My expectation would be that also fusing several times on an entity should be processed by AFrame. Sso that a fusing is the same as a mouse click.

Thanks

- A-Frame Version: 3.0.0
- Platform/Device: any

**Comment by ngokevin** [comment]
That'd be weird since if you stare at something, it'd keep clicking it.

you can copy/paste the cursor component to customize it though https://github.com/aframevr/aframe/blob/master/src/components/cursor.js
