### ISSUE TITLE
Document the build system in the README: `build` vs. `dist`

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#19]

**Comment by ngokevin** [comment]
We are documenting dist, don't think we have to worry about the build/ dir anymore as Budo does magic stuff

**Comment by cvan** [comment]
> We are documenting dist, don't think we have to worry about the build/ dir anymore as Budo does magic stuff

hopefully, that's fine - it's kind of weird to look in the `.html` files and see it pointing to `dist/`, but hopefully it affects only the contributors.
