### ISSUE TITLE
SRC attribute in animation

### ISSUE THREAD

**Issue by lavorato** [aframevr/aframe#1901]
Hello folks. I don't know if is a bug, but I'm trying to understand how could I change the entity SRC in an animation. I'm using the 3.0 version. 

With my code the entity material is empty.

`<a-entity id="parent" geometry="primitive: plane; width: 0.1; height: 0.1;rotation:0 0 0" position="0 -1 -1" material="src: #menu_hamburger; shader: flat; transparent:true; depth: 1; opacity: 1"><a-animation begin="mouseenter" attribute="material.src" from="#menu_hamburger" to="#menu_mais" dur="1000"></a-animation><a-animation attribute="material.opacity" begin="mouseenter" to="0.5" dur="100"></a-animation><a-animation attribute="material.opacity" begin="click" to="0" dur="100"></a-animation><a-animation attribute="material.opacity" begin="mouseleave" to="1" dur="100"></a-animation></a-entity>`

**Comment by cvan** [comment]
```js
<a-entity id="parent" geometry="primitive: plane; width: 0.1; height: 0.1;rotation:0 0 0" position="0 -1 -1" material="src: #menu_hamburger; shader: flat; transparent:true; depth: 1; opacity: 1">
  <a-animation begin="mouseenter" attribute="material.src" from="#menu_hamburger" to="#menu_mais" dur="1000"></a-animation>
  <a-animation attribute="material.opacity" begin="mouseenter" to="0.5" dur="100"></a-animation>
  <a-animation attribute="material.opacity" begin="click" to="0" dur="100"></a-animation>
  <a-animation attribute="material.opacity" begin="mouseleave" to="1" dur="100"></a-animation>
</a-entity>
```

**Comment by lavorato** [comment]
Hello @cvan! Thanks for your answer but the problem is still the same. Best!

**Comment by ngokevin** [comment]
Try this https://github.com/ngokevin/aframe-event-set-component for setting things in response to events when you don't need to tween.

**Comment by lavorato** [comment]
Huge Thanks @ngokevin the component worked! Best.
