### ISSUE TITLE
webkit-playsinline not working in iOS10

### ISSUE THREAD

**Issue by fuleinist** [aframevr/aframe#1906]
**Description:**
webkit-playsinline not working in iOS10. videosphere was working perfectly fine but now will only start video in iOS full screen player. seems to be a bug from Apple?
- A-Frame Version: 0.3.1
- Platform/Device: iPhone6

**Comment by brianblakely** [comment]
I believe the attribute is no longer prefixed, so perhaps try using `playsinline`

**Comment by fuleinist** [comment]
Thanks Brian, added playsinline and it start to work

However webkit-playsinline is still specified in
https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html.
Don't know where it went wrong still.

**Comment by fuleinist** [comment]
I have also noticed the video will still play with
only webkit-playsinline in most of the in app webviews.

**Comment by ngokevin** [comment]
Thanks for the prefix-removal information, might have to update some information. In `<a-assets>`, we automatically fix up all tags with `crossorigin`, we could do something similar for playsinline.

**Comment by fuleinist** [comment]
@ngokevin  also noticed the video will not auto play in mobile iOS unless muted.

try to fire play() in js but still no luck.

**Comment by brianblakely** [comment]
The blog goes over all of this in detail:

https://webkit.org/blog/6784/new-video-policies-for-ios/

**Comment by ngokevin** [comment]
> The same technique can be used to render into a WebGL context. Note in this example that a user gesture–the click event–is required, as the <video> element is not in the DOM, and thus is not visible. 

So maybe need a click or pin-to-homescreen still?

**Comment by brianblakely** [comment]
Yeah, most rich content involving video will still need a click.

This is how to detect whether you need to show a "play" button or something:

https://developers.google.com/web/updates/2016/03/play-returns-promise

**Comment by cvan** [comment]
> Thanks for the prefix-removal information, might have to update some information. In `<a-assets>`, we automatically fix up all tags with `crossorigin`, we could do something similar for playsinline.

we already do for `webkitplaysinline` [here](https://github.com/aframevr/aframe/blob/a578f6fd/src/systems/material.js#L282) and [here](https://github.com/aframevr/aframe/blob/a578f6fd/src/systems/material.js#L317). just need to now add another attribute for `playsinline`.

the click-to-play policies previously existed before iOS 10. and those were tracked in a separate issue (#316), but it was decided that a third-party component would could be responsible for introducing a "play" button if we detect any video or audio on the page. see these comments too: https://github.com/aframevr/aframe/issues/316#issuecomment-212608703
https://github.com/aframevr/aframe/issues/316#issuecomment-219181039

I'd recommend just adding the `webkit-playsinline` attribute in `material.js` where we are already setting `playsinline`. And then file a separate issue for the "play button" for autoplay media that requires a user-initiated action. Keep in mind that not every browser on iOS has this restriction; I don't expect Safari for iOS 10 to change, but Chrome may and [Firefox will](https://github.com/mozilla/firefox-ios/pull/1651).

**Comment by caraya** [comment]
Just for reference. This is a blog post from Apple regarding the changes in `playsinline` for iOS 10 

https://webkit.org/blog/6784/new-video-policies-for-ios/

**Comment by dmarcos** [comment]
@caraya Thanks! Are we ok in iOS now then? :)

**Comment by caraya** [comment]
That was the only information I found about why playsinline is no longer prefixed and what policies to follow to make it play. 

Also considering that Desktop Safari doesn't have the same restrictions as iOS does it makes sense to review the article to see if there are additional changes to make

**Comment by pdnellius** [comment]
Hm. I'm still not able to get this working using the following:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Video Test</title>
    <meta name="description" content="Video Test">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script>
    <script type="text/javascript">

    </script>
  </head>
  <body>
    <a-scene>
        <a-assets>
          <video id="video" src="./assets/video/IMG_1040.MOV" width="1080" height="1920" webkit-playsinline playsinline muted></video>
        </a-assets>
      <a-video src="#video" position="0 0 -4" rotation="0 0 -90" width="4.8" height="2.7"></a-video>
      <a-plane position="0 -4 0" rotation="-90 0 0" width="10" height="10" color="pink"></a-plane>
      <a-sky color="skyblue"></a-sky>
    </a-scene>
  </body>
</html>
```

**Comment by cvan** [comment]
try converting your video codes. you can use `ffmpeg` to do that:

```sh
ffmpeg -i IMG_1040.MOV img_1040.mp4
```

**Comment by pdnellius** [comment]
@cvan , 

Sorry, should've put that in my original post. This is an issue on Safari on both desktop 10.1.1 and iOS 10.3.2. 

I tried converting as you suggested above, but even after pinning it to the homescreen, I'm still getting black boxes.

**Comment by cvan** [comment]
@pdnellius can you link me to your video source so I can take a look?

**Comment by pdnellius** [comment]
@cvan ,

So to gut-check myself, I just ran this on a live server (on a real, public domain), rather than locally, and it works. For anyone moving forward - if you check this on macOS using a PHP -S server, it will not work.

**Comment by cvan** [comment]
oh, yeah, you're probably hitting this [CORS bug on WebKit/Safari](https://bugs.webkit.org/show_bug.cgi?id=135379). I've got some code that I'll be making a PR to `aframe` for that works, but, again, it's just a workaround. it is a known, and unfortunate, WebKit bug.

**Comment by machenmusik** [comment]
That CORS workaround is only functional for MP4, not HLS for example (and may force entire MP4 loading rather than streaming, which may be problematic in some cases?)

**Comment by cvan** [comment]
@machenmusik have you tried using MPEG-DASH instead of HLS? it's supported on iOS Safari. HLS is going to be deprecated anyway.

**Comment by machenmusik** [comment]
Last I tried (not super recently) DASH did not play with iOS 10 mobile safari... do you have a working example?

**Comment by pdnellius** [comment]
Has anyone been able to trigger audio? 

If I remove the `muted` attribute from the `<video>` element, I am unable to play the video. Adding an `onclick` trigger (via a cube or something), with `videoName.play()` gives an error in iOS 10.

**Comment by cvan** [comment]
What error do you see on iOS? The CORS error in the console, or something different?

**Comment by pdnellius** [comment]
Markup:
```
    <a-scene>
    	<a-entity position="0 .6 4">
    	    <a-camera>
    	        <a-entity id="mycursor" cursor="fuse: true; fuseTimeout: 500; max-distance: 30;"
    	        position="0 0 -5"
    	        geometry="primitive: ring"
    	        material="color: blue; shader: flat">
    	        </a-entity>
    	    </a-camera>
    	</a-entity>
    	<!-- "button" -->
    	<a-entity id="audio-trigger-button" geometry="primitive: box" material="color: red" position="0 0 -2"></a></a-entity>
        <a-assets>
          <video id="video" src="./assets/video/vid-audio.mp4" width="1080" height="1920" ></video>
         </a-assets>
      <a-video src="#video" position="0 0 -4" rotation="0 0 -90" width="4.8" height="2.7"></a-video>
      <a-video src="#video" position="-4 0 0" rotation="0 90 -90" width="4.8" height="2.7"></a-video>
      <a-video src="#video" position="4 0 0" rotation="0 -90 -90" width="4.8" height="2.7"></a-video>
      <a-video src="#video" position="0 0 4" rotation="0 0 -90" width="4.8" height="2.7"></a-video>
      <a-video position="0 -3 0" rotation="-90 0 0" width="10" height="10" color="pink"></a-video>
      <a-sky color="skyblue"></a-sky>
    </a-scene>
    <script>

    var button = document.getElementById('audio-trigger-button');
    var testVideo = document.getElementById('video');
    button.onclick = function() {
    	console.log('button clicked');
    	testVideo.play();
    }
    </script>
```
Error:
`SecurityError (DOM Exception 18): The operation is insecure.`

**Comment by machenmusik** [comment]
you need user gesture to trigger media playback that has audio when using mobile safari, and gaze selection doesn't count as a user gesture to the browser, you need touch event or touch-generated click

**Comment by JstnEdr** [comment]
I'm not sure if this is directly related to this issue, but I'm having trouble triggering audio on iOS devices. I'm listening for click events that play audio assets. I'm curious is anyone else is having a similar issue on iOS devices?

**Comment by cvan** [comment]
> I'm not sure if this is directly related to this issue, but I'm having trouble triggering audio on iOS devices. I'm listening for click events that play audio assets. I'm curious is anyone else is having a similar issue on iOS devices or if you know of a solution?

which audio codec is the sound encoded with? if you're listening for `click` events, the user-gesture requirement should be met. can you share a URL of your project?
