### ISSUE TITLE
in vr mode on iphone,all of the images is very blurry

### ISSUE THREAD

**Issue by yjfeng** [aframevr/aframe#1908]
**Description:**
in vr mode on iphone,all of the images is very blurry,but is very clear in vr mode on android.example:
1.https://github.com/aframevr/aframe/blob/master/examples/boilerplate/panorama/index.html
2.https://aframe.io/examples/showcase/composite/
- A-Frame Version:all version
- Platform/Device:iphone
- Reproducible Code Snippet or Demo URL [highly encouraged]:

**Comment by ngokevin** [comment]
Hi, thanks for filing. We made a tradeoff between resolution and working around a canvas resizing issue.

This should be cleared in iOS 10. Here's a workaround (with disadvantages): http://stackoverflow.com/questions/39305663/why-is-a-frame-0-3-0-resolution-low/39305668#39305668

**Comment by yjfeng** [comment]
Thanks,ngokevin, I have tested it in ios10, the images is clear in vr mode,but I use workaround you mentioned above,I add code before a-frame,but the image still broken in vr mode in ios9. sample is here:
http://www.modx.com.cn/vr/test2.html
