### ISSUE TITLE
Port primitive templates to be in JS instead of templates

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#191]
It's faster and let's us do cool defaults/heuristics without having to resort to template logic.

I have a branch of this working for cubes. I'd like to finish porting the other primitives to use it, and I'll open a PR then.

**Comment by cvan** [comment]
Where we left off: https://github.com/jcarpenter/aframe/commits/primitives

**Comment by cvan** [comment]
see PR #883

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
