### ISSUE TITLE
Bump `webvr-polyfill` for latest Chromium builds (WebVR v1.2)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#1918]
**Description:**

When https://github.com/borismus/webvr-polyfill/pull/149 is closed, we ought to update the version of `webvr-polyfill` referenced in the `package.json`.

**Comment by cvan** [comment]
From @jbroberg on the WebVR #help-and-bugs Slack channel:

> **[jamesbroberg]** having some issues w/ latest firefox nightly (either 51a or 52a) not presenting to rift…. i just get a black screen, e.g. any of the webvr samples such as http://threejs.org/examples/#webvr_video
> **[jamesbroberg]** anyone seeing this?
> **[cvan]** @jamesbroberg: sorry to hear! which date of Firefox Nightly are you using? and are you using a DK2 or CV1 Rift? also, any JS errors in the Console?
> **[jamesbroberg]** latest and greatest as of today but also went back and grabbed a 51a version from a few days back
> **[jamesbroberg]** im seeing it in my own code as well, i saw `@smus` pushed a change to webvr-boilerplate that addressed the  "TypeError: Argument 1 of VRDisplay.requestPresent can't be converted to a sequence.” i was seeing for a bit (presume from the change to Web VR 1.0/1.1) but I’m getting the black screen too with my 360 video player.
> **[jamesbroberg]** nothing super useful on the console, i’m using a CV1
> **[jamesbroberg]** @cvan date on firefox nightly is 2016-09-19. here is an example that works w/ latest webvr chromium but blackscreens w/ latest nightly when presenting to rift. https://stage.metacdn.com/r/v/vorjbrr/GKIb3Gc/embed
> **[jamesbroberg]** only relevant log i see is the vrdisplaypresentchange
> **[jamesbroberg]** onVRDisplayPresentChange_ vrdisplaypresentchange { target: Window → embed, isTrusted: true, currentTarget: Window → embed, eventPhase: 2, bubbles: true, cancelable: true, defaultPrevented: false, timeStamp: 12322.541407047604, originalTarget: Window → embed, explicitOriginalTarget: Window → embed, NONE: 0 }

**Comment by cvan** [comment]
I'm assuming this is related to https://github.com/borismus/webvr-polyfill/pull/149, but I'm not entirely sure because he's using Firefox Nightly. Haven't compared yet.

More from @jbroberg:

> **[jamesbroberg]** Ok. I don't use aframe but I do use the latest release version of polyfill.
> **[jamesbroberg]** Oh and @tojiro 's webvr samples don't have this issue and they use his branch of polyfill so there is another data point
> **[jamesbroberg]** thanks for looking into this @cvan ! I'm trying to stay on top of these changes :)

**Comment by dmarcos** [comment]
The polyfill is now at `0.9.231: 

https://github.com/aframevr/aframe/blob/master/package.json#L46
