### ISSUE TITLE
Cheat the framework to think desktop has side by side VR capabilities

### ISSUE THREAD

**Issue by randohinn** [aframevr/aframe#1919]
Is there a method I could use, to cheat the A-Frame framework, to think that a desktop browser (Raspberry Pi's for this case), is compatible with side-by side VR? This would be such a useful thing for non-mobile devices.

**Comment by randohinn** [comment]
@aframevr anything?

**Comment by ngokevin** [comment]
Missed this question. Do you want to render in stereoscopic without VR capabilities, or are you interested in using accelerometers and gyroscopes of a Raspberry Pi? Can you explain the use case more?

**Comment by randohinn** [comment]
@ngokevin Technically, that's both. I need it to render stereoscopically on a device without VR capabilities, as desktop browsers identify themselves, and I want to later pass in custom accelerometer values to the framework. On a rPi.

**Comment by ngokevin** [comment]
The code that determines whether to use VREffect is `if (checkHeadsetConnected() || this.isMobile)`. 

`checkHeadsetConnected` ultimately depends on having a `VRDisplay` https://w3c.github.io/webvr/#interface-vrdisplay and setting the orientation to something that's not a zero vector.

Hacky way is to set `document.querySelector('a-scene').isMobile` to `true` and remove the orientation modal overlay. 

You can check how the WebVR polyfill does it too https://github.com/googlevr/webvr-polyfill which does it for smartphones, you can do something similar for the Pi.

**Comment by ngokevin** [comment]
Leave this open for maybe an API to force stereo rendering.

**Comment by randohinn** [comment]
@ngokevin Thanks, will look into it.

**Comment by ngokevin** [comment]
I'd stand with just hacking it and set `isMobile` to cheat it

**Comment by sompylasar** [comment]
The `isMobile` hack no longer works. https://github.com/aframevr/aframe/issues/1009#issuecomment-342028445

**Comment by skrichten** [comment]
Can we please re-open since the isMobile hack no longer works?

**Comment by dmarcos** [comment]
It was a hack that might have worked just by coincidence. What is the use case for stereo rendering in desktop?

**Comment by skrichten** [comment]
Development while you don't have access to a VR device.  It is helpful to see what the actual output will look like.

**Comment by dmarcos** [comment]
The position of the camera is going to be similar in VR and 2D mode. What value do you extract from stereo rendering and distortion without a headset? What kind of content you're developing? Mono rendering is usually enough for object positioning. There is a Web extension that simulate VR hardware (https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil?hl=en) for that purpose.

**Comment by skrichten** [comment]
I simply need to see the actual output, and others have also requested it.  "Similar", is just not enough for my case.  I'm not sure the web extension will work for me as I am using Electron.

**Comment by dmarcos** [comment]
@skrichten Can you be more specific about your use case? Why is mono rendering not accurate enough for testing? Can you present on VR hardware from an Electron context? This is not a trivial feature to implement and maintain over time. I’m just trying to understand the problem we are trying to solve.

**Comment by skrichten** [comment]
Mono rendering is not accurate enough because I need to manage exactly what is visible from a static camera position.  The distortion causes that to be a little different from the mono view.  I don't see any reason why using electron would prevent presentation on VR hardware, but maybe I'm missing something?

**Comment by dmarcos** [comment]
@skrichten What headsets are you supporting? Distortion and field of view are hardware specific. If you want accuracy you would need to exactly simulate the characteristics of heach headset. Random or generic stereo rendering and distortion won’t solve your problem if what you need is precision.

**Comment by skrichten** [comment]
Thanks, I only need to support Oculus Rift.

**Comment by dmarcos** [comment]
Also notice that WebVR is only available on Chrome Canary behind a flag. I have no experience with Electron and how they update the version of Chromium / Blink they ship.

**Comment by dmarcos** [comment]
Chrome only supports Vive at the moment.

**Comment by dmarcos** [comment]
You can use Firefox but you cannot then use Electron.

**Comment by skrichten** [comment]
Of course.  I will look into using firefox in kiosk mode or something.  Is there a firefox extension to simulate VR hardware?

**Comment by dmarcos** [comment]
There’s nothing I know of that simulates hardware if accuracy is what you need. You mention you want to simulate a static camera position. Just make sure that the approach is useful since we people are never completely static. The fine adjustments you do assuming a static point of view might not be perceived by a real user. I would recommend to test on real hardware if accuracy is a top priority for you.

**Comment by claytongulick** [comment]
I actually have a use case for this too. I need to be able to render content directly to one eye or the other, and I need to be able to debug this to make sure it's working correctly. This is pretty challenging to do with aframe right now.
