### ISSUE TITLE
How can i add a loading effect before all assets loaded in aframe

### ISSUE THREAD

**Issue by terryleee** [aframevr/aframe#1921]
**Description:**

i need add a loading effect before aframe render the whole scene, it looks nothing related in our document, any ideas?

- A-Frame Version: 0.2.0
- Platform/Device: iOS

**Comment by darkwing** [comment]
Appears to have been re-asked here:

http://stackoverflow.com/questions/39586429/how-can-i-add-a-loading-effect-before-all-assets-are-loaded
