### ISSUE TITLE
Investigate optimize-js for Speed

### ISSUE THREAD

**Issue by darkwing** [aframevr/aframe#1924]
https://github.com/nolanlawson/optimize-js

Provides hints for JS engines for optimized parse speed.  Most notably a massive speed improvement for Three.js, our underlying technology.

**Comment by darkwing** [comment]
Thanks to @AdaRoseEdwards for finding this!

**Comment by cvan** [comment]
See https://github.com/nolanlawson/optimize-js#benchmarks and https://nolanlawson.github.io/optimize-js/. Would be interesting to test an optimize-js three.js build and measure. Additionally, it'd be cool if we created an A-Frame benchmark they could include on that list.

**Comment by gurumukhi** [comment]
hi @darkwing, @cvan. How can a newbie work on this? Is this about creating two a-frame scenes with and without optimize-js and see the different in load-times?

**Comment by ngokevin** [comment]
Will just leave as is. Don't know if the extra build step is worth it and can come with surprises. It doesn't look to be maintained nor adopted.
