### ISSUE TITLE
Objects and templates inside `<vr-camera>` do not inherit camera position/rotation

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#193]
In the following example, the image renders correctly (appears in front of the user, floating slightly above and to left of center of screen. But as soon as user moves via WASD or look, the nested element is decoupled, floating on it's own.

```
<vr-camera position="0 0 0" near="0.1">
    <vr-image position="-0.3 0.2 -1" src="images/title-1.png" width="0.2" height="0.1" ></vr-image>
</vr-camera>
```

Checked with both templates and objects, and result is the same.

**Comment by ngokevin** [comment]
I believe this works now.
