### ISSUE TITLE
Optional fullscreen option (for webviews/cordova)

### ISSUE THREAD

**Issue by hugohil** [aframevr/aframe#1933]
Hi!

I'm building a WebVR app for mobile using Apache Cordova and, obviously, aframe. This app will systematically be used with HMD on, so I wanted to have the VR mode enabled at startup. I used the `enterVR()` method, but I get a `Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture.` warning that prevents me from doing so. The thing is cordova already handles the fullscreen stuff, so I really do not need it to be enabled.

Is there already some option or property to disable this behaviour for specific kind of case like mine ? If not, I'd be happy to help if you would point me out to the right direction. I've looked a bit into aframe sources and couldn't find any reference to the actual method call that triggers this fullscreen API.

Thanks !
- A-Frame Version: `0.3.0`
- Platform/Device: Samsung Galaxy S7 / Cordova
- Reproducible Code Snippet or Demo URL:

Simply open [an example](https://aframe.io/examples/) in your (Android) mobile browser, plug it in your computer and [open the console](https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging). Type `document.querySelector('.a-enter-vr-button').click()` and feel my sorrow 😢

**Comment by ngokevin** [comment]
The call is at https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L170

Is it a harmless warning, or does it prevent stereo mode (one render for each eye)? Is there a way to detect a fullscreen/native/pinned context?

**Comment by hugohil** [comment]
Thank you !

If this is ok with you, I can do a PR that would basically just add a `noFullScreenVR` property to the `a-scene` entity and check for it before calling the `requestFullScreen`.

The warning does prevent the stereo mode. I'm not sure I understand what you mean by `detect a fullscreen/native/pinned context` though :/

**Comment by ngokevin** [comment]
I mean is there a smarter way to automatically handle it without having to create a property? "If this app is in Cordova, don't fullscreen".

**Comment by hugohil** [comment]
Well, this is not only cordova related. For instance, this could be useful for other hybrid mobile app frameworks, but also for nw.js or Electron. In fact, any web app that can run outside a proper "browser" and thus can handle at a higher level the process of making the page fullscreen.

Couldn't we just check `window.innerHeight === window.screen.height` ? I think this would be a correct way to detect if the app is already in fullscreen or not. What do you think ?

**Comment by ngokevin** [comment]
Yeah, perhaps that'd work. Can you confirm that'd work on hybrid mobile apps?

**Comment by hugohil** [comment]
After some research and attempts in aframe, found out this is related to webvr-polyfill. Also found that [someone raised the issue in June](https://github.com/borismus/webvr-polyfill/issues/114) and bumped it.

**Comment by ngokevin** [comment]
Might be some work on A-Frame side to fix this too.

**Comment by ngokevin** [comment]
#1940 fixed
