### ISSUE TITLE
No export API  to listen loader/request loading progress ?

### ISSUE THREAD

**Issue by lslzl3000** [aframevr/aframe#1937]
How to listen e.g. OBJ loader loading progress?
We know all loaders in aframe were using THREE.XHRLoader( url, onLoad, onProgress, onError ), which has 'onProgress' to handle XHR progress event. But in aframe, loaders just call THREE.XHRLoader( url, onLoad) with first two vars. Giving us no API to handle loading progress.

I think we need add some apis to do that.

**Comment by drryanjames** [comment]
+1

**Comment by ngokevin** [comment]
We use the XHRLoader at https://github.com/aframevr/aframe/blob/master/src/core/a-assets.js#L90 ... just need to add a hook there.
