### ISSUE TITLE
Enter VR button is not working on Android WebView

### ISSUE THREAD

**Issue by andymartinwork** [aframevr/aframe#1940]
**Description:**
- A-Frame Version: aframe-v0.3.0.js
- Platform/Device: Android WebView
- Reproducible Code Snippet or Demo URL [highly encouraged]:

A-Frame used to work fine in version 0.2.0
My app runs by default in fullscreen.

When I try clicking on the Enter VR button this error is output in the console:

`a-scene.js:175 Uncaught (in promise) Error: Failed to enter VR mode (`requestPresent`): Unable to present.(…)enterVRFailure @ a-scene.js:175`

**Comment by andymartinwork** [comment]
Possibly related to:  #1933

**Comment by andymartinwork** [comment]
Also related to https://github.com/borismus/webvr-polyfill/issues/114

**Comment by andymartinwork** [comment]
This might be a tricky one. Even bypassing the fullscreen problem, then a problem with the orientation lock not being available on the webview, I get this error:

```
10-02 18:20:35.161 12227-12805/com.vrambling.vrambling E/ACodec: [OMX.Exynos.vp9.dec] ERROR(0x90000012)
10-02 18:20:35.161 12227-12805/com.vrambling.vrambling E/ACodec: signalError(omxError 0x90000012, internalError -2147483648)
10-02 18:20:35.161 12227-12804/com.vrambling.vrambling E/MediaCodec: Codec reported err 0x90000012, actionCode 0, while in state 6
10-02 18:20:35.171 12227-12299/com.vrambling.vrambling E/cr_media: Failed to queue input buffer
                                                                   java.lang.IllegalStateException
                                                                       at android.media.MediaCodec.native_queueInputBuffer(Native Method)
                                                                       at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2165)
                                                                       at org.chromium.media.MediaCodecBridge.queueInputBuffer(MediaCodecBridge.java:359)
10-02 18:20:35.171 12227-12805/com.vrambling.vrambling E/ACodec: [OMX.Exynos.vp9.dec] ERROR(0x90000012)
10-02 18:20:35.171 12227-12805/com.vrambling.vrambling E/ACodec: signalError(omxError 0x90000012, internalError -2147483648)
10-02 18:20:35.171 12227-12804/com.vrambling.vrambling E/MediaCodec: Codec reported err 0x90000012, actionCode 0, while in state 0
10-02 18:20:35.171 12227-12805/com.vrambling.vrambling E/ACodec: [OMX.Exynos.vp9.dec] ERROR(0x90000012)
10-02 18:20:35.171 12227-12805/com.vrambling.vrambling E/ACodec: signalError(omxError 0x90000012, internalError -2147483648)
10-02 18:20:35.171 12227-12804/com.vrambling.vrambling E/MediaCodec: Codec reported err 0x90000012, actionCode 0, while in state 0
```

Not really sure what to do with that one...

**Comment by oscarmarinmiro** [comment]
Just the same thing happens to me (same console output) + "Enter-VR" not possible in Chrome 4.2 on an Android LG 5. However with Chrome 4.3 (Beta) works ok...

**Comment by andymartinwork** [comment]
I think that is because Chrome Beta supports the WebVR 1.0 spec and prod does not.

Eventually, the webview will support the spec, but there will still be problems with a-frame because of the fullscreen indicator and orientation lock code.

**Comment by mn-martin** [comment]
This is still broken in v0.4.0 and on the master branch. In v0.2.0 it was working perfectly.

**Comment by andymartinwork** [comment]
0.4.0 has a nicer message: `Uncaught (in promise) Error: Failed to enter VR mode (requestPresent): No VR hardware found.`

**Comment by andymartinwork** [comment]
It didn't work because the calls to go into fullscreen failed, and then orientation lock. You can't control these things with javascript because they are app settings.
Both of them are in the correct settings of course. The fix here is to disable the fullscreen and orientation checks when in a webview. The same will apply to iOS.

**Comment by andymartinwork** [comment]
This is because the WebView doesn't support vrDisplay, and aframe doesn't support browsers that don't support vrDisplay.

A potential fix is to use a-frame 0.2.0 code for presenting as a fallback.

**Comment by dmarcos** [comment]
Sorry, I don't understand the problem. Chrome (not the Chromium WebVR builds), Firefox (not Nightly), Edge or Safari don't support VRDisplay and a-frame works fine. The polyfill should kick in in all those cases. What's different in a webview?

**Comment by dmarcos** [comment]
We don't do Android development in the a-frame team so we cannot test webviews easily. If someone can investigate and provide a fix we will take it

**Comment by andymartinwork** [comment]
Sorry, I'm not very familiar with the codebase. Where is the polyfill located?

**Comment by andymartinwork** [comment]
OK, looks like a simple fix for the webvr-polyfill project. I will submit a pull request with them and keep this bug open to make sure we update the dependency on a-frame.

**Comment by andymartinwork** [comment]
Hmm, it looks like the changes were submitted and denied. WTF.

https://github.com/googlevr/webvr-polyfill/pull/175

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/2345
