### ISSUE TITLE
debounce componentchanged event, or find a way to limit/toggle it

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1941]
**Description:**

In the animation stress test, it's a perf hit.

<img width="363" alt="screen shot 2016-09-26 at 5 28 58 pm" src="https://cloud.githubusercontent.com/assets/674727/18856326/bbfec0e6-840e-11e6-99be-28badce3405e.png">

**Comment by ngokevin** [comment]
Perhaps only emit the event if something has subscribed to it. Then introduce an API.

`el.subscribeComponentChanged(function () {...})`

**Comment by ngokevin** [comment]
Or deprecated it, and recommend to just call `getAttribute` on each tick. That might be more performant/sync.

**Comment by dmarcos** [comment]
What about if you want to listen on a parent for changes on a specific components in the children?

**Comment by ngokevin** [comment]
Has since been throttled.
