### ISSUE TITLE
Entity.flushToDOM() does not flush default component at default value (e.g, position)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1944]
**Description:**

Component.flushToDOM() is working.

**Comment by donmccurdy** [comment]
Repro details? Testing on `examples/test/cursor/` with:

```js
cameraEl.components.position.flushToDOM()
```

... seems to be working as expected.

**Comment by ngokevin** [comment]
The Entity flush to DOM is

```cameraEl.flushToDOM()```

the component level works as expected

**Comment by donmccurdy** [comment]
Oops, yeah I read that backwards. In both cases, though, it's working fine for me on camera's position and rotation.

**Comment by ngokevin** [comment]
OK it works. Might've been confused since default components like `position` don't flush `0 0 0`
