### ISSUE TITLE
Make System prototype inherit from Component prototype

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#1947]
**Description:**

I've found cases where we want to be able to update systems (e.g., `enemy` system). Since systems already have schema/play/pause/init/data...with update, they will have the same API as components. We should be able to reuse the prototypes, but maintain the same registration API + system-to-component referencing

**Comment by fernandojsg** [comment]
:+1: I run into the same problem while developing the `decal` system for the a-shooter.

**Comment by wizgrav** [comment]
It's definately needed, I've hacked the update() functionality in the postproc PR but reusing the Component prototype makes more sense

**Comment by ngokevin** [comment]
Considering instead https://github.com/aframevr/aframe/issues/2071
