### ISSUE TITLE
Consider adding #hacktoberfest label for the month

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#1951]
... to the existing 'help wanted' issues. [Details here](https://hacktoberfest.digitalocean.com/).

**Comment by ngokevin** [comment]
So we just add that, and email them to feature it?

**Comment by donmccurdy** [comment]
Not sure what's involved in getting featured, but the JavaScript section is pretty short so it's certainly worth a try.

Just adding the label would be enough to appear in the [Browse More Projects on GitHub](https://github.com/search?l=&q=state%3Aopen+label%3Ahacktoberfest&ref=advsearch&type=Issues&utf8=%E2%9C%93) list that they link to.

**Comment by ngokevin** [comment]
Emailed them but they weren't interested in featuring.

**Comment by ngokevin** [comment]
Funny thing was that Mozilla is sponsoring Octoberfest 😆
