### ISSUE TITLE
Read xmpmeta data

### ISSUE THREAD

**Issue by steven10172** [aframevr/aframe#1952]
While using A-Frame for a panoramic image I noticed that the image wasn't rotating properly. After some investigation I noticed that it wasn't reading the xmpmeta data to figure out the correct orientation.

Here is an example: http://codepen.io/steven10172/pen/vXJZzE
Here is the desired behavior: http://www.joshuanaylor.com/pannellum/

The pannellum library has a method [(method source)](https://github.com/mpetroff/pannellum/blob/master/src/js/pannellum.js#L445L535) that reads the tags on the image to see what the proper heading, horizon pitch, and horizon roll should be set to.

**Comment by steven10172** [comment]
This also looks like it does the correction calculations: https://github.com/mpetroff/pannellum/blob/master/src/js/libpannellum.js#L464L490

**Comment by ngokevin** [comment]
A community component would be good for this that would take an image URL or `<img>` selector and add rotation based on the xmpmeta.

**Comment by ngokevin** [comment]
Will close this in favor of a separate third-party component.
