### ISSUE TITLE
ios 9.3.5 safari can't full screen

### ISSUE THREAD

**Issue by mountainguan** [aframevr/aframe#1953]
**Description:**
In ios 9.3.5 safari couldn't full screen.Safari's tab bar and title bar still on it.So vr mode seems not good.

- A-Frame Version:0.3.0 & 0.3.1
- Platform/Device:iPhone6plus ios 9.3.5 safari
- Reproducible Code Snippet or Demo URL [highly encouraged]:http://www.fanoi.com/webvr/release/index.html

**Comment by mountainguan** [comment]
Finally I found that safari with more than one tab would fail to full screen.

**Comment by ngokevin** [comment]
you have to go to your safari settings and set it to hide

**Comment by gamecubate** [comment]
Sorry but set what to hide? I've got the same problem with 0.3.0 and iOS Safari. Title and tab bars stay on always. I'm still running on iOS 9.3.5 (same as above report).

**Comment by ngokevin** [comment]
Try setting window.scrollTop to 0?

**Comment by gamecubate** [comment]
Will try. Thanks.

**Comment by derhuebiii** [comment]
Same problem here. Also not with the examples on aframe.io.

Testing with WebVR Sampels it works though. I also tried to copy the meta tags from there, didn't help:
```
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
```

Is there any solution?

**Comment by gamecubate** [comment]
The Safari devs (and Apple?) is to blame for this and I don't see what the people behind aframe can do to fix it. That said, I've worked around the problem by saving all (aframe) sketches to the home screen on my iPhone. After which all is well. You might want to close this issue.

**Comment by derhuebiii** [comment]
@gamecubate 
I don't agree, as said if I use those examples: https://webvr.info/samples/ I am able to get to fullscreen (in Safari). I can still drag the navigation bar by dragging the page, but at least initially it is in fullscreen. So there seems to be a way, right? I didn't manage to figure out how though.

**Comment by derhuebiii** [comment]
I found a workaround for everyone who is interested:
https://github.com/aframevr/aframe/issues/2577#issuecomment-296100258
