### ISSUE TITLE
setAttribute not working in 0.30 for dynamically created elements.

### ISSUE THREAD

**Issue by masterofshapes** [aframevr/aframe#1956]
**Description:**
I'm appending elements to my "a-scene" dynamically. When I try to setAttribute for position or various other aframe component properties nothing changes.  Whats weird is when I switched to aframe 0.2.0 it works. 

html: 
```html
<head>
  <!-- aframe.js -->
  <!-- custom_components.js -->
  <!-- script_that_appends_elements_to_scene.js -->
</head>
<body>
  <a-scene> <!--<a-entity id="spawnedContent">---appended elements go here -------</a-entity>  --> </a-scene>
  
</body>
'''
inside my script:
var container = document.createElement('a-entity');
$(container).appendTo( "#spawnedContent");
container.setAttribute('position','0 0 -10');

- A-Frame Version: 0.3.0
- Platform/Device: desktop

**Comment by ngokevin** [comment]
i'd recommend setAttr before appending

**Comment by masterofshapes** [comment]
Just tried, same result in 0.3.0
![aframe](https://cloud.githubusercontent.com/assets/4534991/19017286/5f2c4102-87e9-11e6-9383-8e0d967ceca5.PNG)

but when i switch to 0.2.0
![aframe2](https://cloud.githubusercontent.com/assets/4534991/19017293/8696b66e-87e9-11e6-9228-5883580b1708.PNG)

**Comment by ngokevin** [comment]
i see, that's expected. here ya go. http://stackoverflow.com/questions/39719445/why-is-the-html-dom-not-updating-in-a-frame

**Comment by masterofshapes** [comment]
Thanks!
