### ISSUE TITLE
leaveCurrentIntersection() is not defined etc.

### ISSUE THREAD

**Issue by rong1129** [aframevr/aframe#1959]
Function leaveCurrentIntersection() on [this line](https://github.com/aframevr/aframe/blob/37c33d2cc88de369feff7027f3d1e24b305ef496/src/components/cursor.js#L106) doesn't exist. I changed it to clearCurrentIntersection(), it seemed working. 

Probably unrelated to this, but [this line](https://github.com/aframevr/aframe/blob/37c33d2cc88de369feff7027f3d1e24b305ef496/src/components/cursor.js#L139) doesn't seem right either as clearCurrentIntersection() doesn't take any argument.

BTW, not sure if anyone tried this component with raycaster as described [here](https://aframe.io/docs/0.3.0/components/cursor.html#configuring-the-cursor-through-the-raycaster-component), the object selector doesn't work.
 
- A-Frame Version: master
- Platform/Device: all
- Reproducible Code Snippet or Demo URL [highly encouraged]:

**Comment by ngokevin** [comment]
Thanks, I think there were some merge conflicts. Will get that fixed.

**Comment by rong1129** [comment]
Regarding the raycaster issue, I looked a little further at it, and this line looks suspicious

https://github.com/aframevr/aframe/blob/master/src/core/a-entity.js#L358
 
> self.initComponent(component, undefined, true);

It looks like that the raycaster component was initialized as a dependency, and the above line initialized it without its attributes. If that's right, chances are many other components may also be initialized without their attributes.

**Comment by dmarcos** [comment]
Component dependencies don't have attributes. They could but the current API only allows to define the list of dependencies to guarantee an order of initialization. If the component is also defined in the entity we call `updateComponent` with the proper data defined in the DOM attribute:

https://github.com/aframevr/aframe/blob/master/src/core/a-entity.js#L425

**Comment by ryanbetts** [comment]
Gonna take a look at this right now!

**Comment by ngokevin** [comment]
Thanks Ryan, my bad for regressing it!
