### ISSUE TITLE
Docs: Incorrect Markdown for Code Formatting on Defining Your Own Geometry Section

### ISSUE THREAD

**Issue by skilfullycurled** [aframevr/aframe#1960]
**Description:**

Hi, 

The top and bottom of the code in the following section of the documentation is being rendered as text.

https://aframe.io/docs/0.2.0/components/geometry.html#defining-your-own-geometry

I don't think it's markdown else I would offer some solutions, but aesthetically speaking it should look like this.

```
AFRAME.registerComponent(‘my-geometry’, { // Called on component attach and data update. 

    update: function () { // Grab the mesh. 
             var mesh = this.el.getOrCreateObject3D(‘mesh’, THREE.Mesh);  // Provide your own geometry.
             var geometry = mesh.geometry = new THREE.Geometry();
             geometry.vertices.push(
                       new THREE.Vector3(-10,  10, 0),
                       new THREE.Vector3(-10, -10, 0),
                       new THREE.Vector3( 10, -10, 0) );

               geometry.faces.push(new THREE.Face3(0, 1, 2));
               geometry.computeBoundingSphere();

      }, 
      remove: function () {  // Called on component detach. 
            this.el.getObject3D(‘mesh’).geometry = new THREE.Geometry(); 
      } 
});

```

Thanks!

**Comment by ngokevin** [comment]
Thanks for filing. Before we weren't versioning our docs, so there wasn't an easy way to pull in typo fixes. Now there is, so going forward this shouldn't be an issue. We'll just have to leave pieces of 0.2.0 with typos.
