### ISSUE TITLE
Number of Vive examples not working

### ISSUE THREAD

**Issue by JonathanZWhite** [aframevr/aframe#1964]
I'm running into the issue where when I toggle on VR mode, I'm just getting a blank white screen and no data is set to the Vive. I tested this issue with a number of demos:

I'm running into a blank white screen when I toggle on VR mode on some of the Vive examples. In addition, no video data is sent to my Vive. AFrame's APainter works but the following demos do not: 

https://apps.tlt.stonybrook.edu/hanoi/
http://tbaloo.com/tumbvr
https://ngokevin.github.io/aframe-draw/

Is this an issue on my end? Or was there an update that caused an issue with these VR demos? I ran into the issue locally as well using AFrame version 0.3.1. I'm also using Chromium version 55.0.2869.0.

**Comment by ngokevin** [comment]
The newest version of Chromium uses WebVR 1.1 API.

Latest bleeding edge A-Frame addresses this: https://github.com/aframevr/aframe/tree/master/dist

Sorry about that, need to communicate that somehow!

**Comment by JonathanZWhite** [comment]
@ngokevin That worked like a charm. Thanks 🎉

**Comment by SBUtltmedia** [comment]
Hi, I made the Towers of Hanoi game (https://apps.tlt.stonybrook.edu/hanoi/) and just updated to A-Frame 0.3.2, and everything is working with the Vive once again. Just putting a note here for future reference 😃
