### ISSUE TITLE
[feature request] text 

### ISSUE THREAD

**Issue by Hongbo-Miao** [aframevr/aframe#1966]
I saw the demos are all using images to show text. It will be great to have something like text box.

**Comment by donmccurdy** [comment]
Hi @Hongbo-Miao – try the list of [community-made A-Frame components](https://github.com/aframevr/awesome-aframe#components). You probably want [one](https://github.com/bryik/aframe-bmfont-text-component) [of](https://github.com/maxkrieger/aframe-textwrap-component) [these](https://github.com/ngokevin/aframe-text-component). Showing text in WebGL is a bit complex, and different approaches are better for different things, so it has been left out of the core library so far.

**Comment by Hongbo-Miao** [comment]
Thanks, that is very helpful!

**Comment by ngokevin** [comment]
I like using https://github.com/bryik/aframe-bmfont-text-component

Whether that should be standard I am not sure. Currently, it's the solution that works and looks the best. It might be nice to have it out of the box. But other solutions like html-to-canvas might win out?

**Comment by Hongbo-Miao** [comment]
@ngokevin Thanks! Those are very helpful suggestions. It will be great to add these in the the A-Frame document.

Feel free to close this if need.

**Comment by ngokevin** [comment]
We should consider having a basic sample text implementation (I like @bryik's) as part of the standard lib. This way if third-party components want to add text for whatever reason (debug, labels), they don't have to depend on a third-party text component or consider how to package that in.

**Comment by bryik** [comment]
Apparently, [ReactVR will use SDF font text](https://youtu.be/8BHOztuaj-4?t=16m33s). 

Displaying text is a common need, so it would be nice for A-Frame to have a built-in solution. Though @donmccurdy has a point about "different approaches [being] better for different things"; e.g. HTML-to-canvas for foreign languages.

Downsides to bmfont-text:

- character set is limited
	
- my implementation is hackey and the dependencies are complex
	
- components (color, opacity, fog) do not work 'natively'
	
- [offset](https://github.com/bryik/aframe-bmfont-text-component/issues/14) and other issues

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/2200
