### ISSUE TITLE
Two A-Frames in a page are not allowed?

### ISSUE THREAD

**Issue by ymcheung** [aframevr/aframe#1969]
- A-Frame Version: 0.3.0
- Platform/Device: OSX/Chrome 53

Hello, 
Thanks for the fantastic product for VR/360!

I would like to show 2 A-Frames as a slideshow by using Slick Slider.
But nothing showed, and I removed Slick Slider, leaving just 2 basic sets of A-Frames with "embedded" attribute. The situation remained the same. 

Do A-Frame restrict only 1 in a page?
(For just 1, it works well!)

Thank you!

**Comment by ngokevin** [comment]
Doesn't work yet https://github.com/aframevr/aframe/issues/916 ... it'll be non-trivial to support that actually.

For presentations, I've been detaching the current scene and appending new one when I change slides. Also consider I-Frames.
