### ISSUE TITLE
<a-scene> affects next page's <a-scene> location

### ISSUE THREAD

**Issue by Hongbo-Miao** [aframevr/aframe#1970]
- A-Frame Version: 0.3.0
- Platform/Device: 56.0.2884.0 canary (64-bit)
- Reproducible Code Snippet or Demo URL:

I am using A-Frame with Angular 2.
http://plnkr.co/edit/NQhc7aQ9WmTmNEZFkHpA?p=preview

All images on page 1, 2 and 3 are supposed to be at the center of the screen.

When you drag the image on page 1, and then go to page 2. The location of image on page 2 will be affected (not in the center of the screen),  which is wrong.

Then when you go back page 3, the image is at the center of the screen which is correct.

So the issue is that `<a-scene>` will affect and only affect next page's `<a-scene>` position.

**Comment by ngokevin** [comment]
Not quite sure what's going on, there's too much stuff sitting on top of A-Frame, it's hard to debug (Angular 2, routers, typescript, es6, multiple scenes).

**Comment by Hongbo-Miao** [comment]
Let me do a small test without Angular 2

**Comment by ngokevin** [comment]
Any updates? I am not sure this is actionable unless we have more details.

**Comment by ngokevin** [comment]
Will close without a test case for now
