### ISSUE TITLE
Raycaster emit events on VideoSphere

### ISSUE THREAD

**Issue by masterofshapes** [aframevr/aframe#1976]
**Description:**
Trying to get the raycaster to emit events on videosphere but so far it never works. 

`document.querySelector('#video_sphere').addEventListener('click', function (evt) { console.log("video sphere clicked); });`

- A-Frame Version: 0.3.0
- Platform/Device: desktop

**Comment by ngokevin** [comment]
Are you using the cursor component or raycaster? Cursor component adds the click events.

Either way, check the raycaster max distance is sufficient (videosphere has 5000m radius, so set to 5000+)
