### ISSUE TITLE
'raycaster-intersection' passes a reference to this.intersectedEls

### ISSUE THREAD

**Issue by ryanbetts** [aframevr/aframe#1977]
**Description:**

'raycaster-intersection' passes a reference to this.intersectedEls array. This means if a developer does something destructive, it breaks the behaviour of the raycaster. Should pass a copy of the array instead.

- A-Frame Version: master
- Platform/Device: all
- Reproducible Code Snippet or Demo URL [highly encouraged]:

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/1978
