### ISSUE TITLE
Chromium sending error on iFrames without allowvr

### ISSUE THREAD

**Issue by tbalouet** [aframevr/aframe#1979]
In the aframe.io examples, as the content is displayed in iframes, you need to add "allowvr" to the iframe attribute, otherwise you get the following error:
```
 DOMException: Access to VR devices is not allowed in this context.
```

- A-Frame Version: 0.3.2
- Platform/Device: Chromium 55.0.2869.0 (64-bit)
- Reproducible Code Snippet or Demo URL [highly encouraged]:
You can see it in the console for this web page:
https://aframe.io/examples/showcase/spheres-and-fog/

**Comment by ngokevin** [comment]
Fixed thanks!

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-site/commit/30671e75783c18ce7692001d9a8aacf0399f2c10
