### ISSUE TITLE
Aframe 0.3.2 Black Screen Linux Ubuntu Chrome Browser

### ISSUE THREAD

**Issue by dbradleyfl** [aframevr/aframe#1980]
**Description:**
Fails to show even hello world example,

http://imgur.com/a/b9fAg

- A-Frame Version: 0.3.2

- Platform/Device: 
elementary OS 0.4 Loki (64-bit), elementary OS 0.4 Loki (64-bit), 
Google Chrome	54.0.2840.59 (Official Build) (64-bit)
Revision	5b2f167ccdaed3f1a90ec1084715fbb91b8d25b0-refs/branch-heads/2840@{#726}
OS	Linux 
JavaScript	V8 5.4.500.31

- Reproducible Code Snippet or Demo URL [highly encouraged]:
https://aframe.io/examples/showcase/helloworld/

JS console:

A-Frame Version: 0.3.2
index.js:64three Version: ^0.76.1
index.js:65WebVR Polyfill Version: 0.9.15
three.js:24764THREE.WebGLRenderer 76
three.js:28591THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.

**Comment by dbradleyfl** [comment]
Works with same system but Firefox browser. Same warnings in js console.

**Comment by ngokevin** [comment]
Do three.js examples work?

**Comment by dbradleyfl** [comment]
Can't believe I didn't think to check that. None of the three.js examples work either. I guess its a chrome browser issue on Linux / Ubuntu / Elementary OS.

**Comment by dbradleyfl** [comment]
For anyone that runs into this:

http://askubuntu.com/questions/299345/how-to-enable-webgl-in-chrome-on-ubuntu
