### ISSUE TITLE
Animation End not stopping animation

### ISSUE THREAD

**Issue by msj121** [aframevr/aframe#1981]
I cannot get the "end" attribute in a-animation to stop the animation...

Currently i have the following Pen demonstrating the behaviour:
http://codepen.io/msj121/pen/obmvrE?editors=1111

The current code is as follows:

```
<a-cube position="-1 0.5 1" rotation="0 45 0" width="1" height="1" depth="1" color="#4CC3D9">
    <a-animation begin="mouseenter" end="mouseleave" attribute="rotation" repeat="10" easing="linear" dur="1000" direction="alternate" from="0 0 0" to="45 45 45"></a-animation>
</a-cube>
```

It does not work even if manually emitting the events as shown on codepen.

**Comment by msj121** [comment]
Calling: stop() on the animation itself does indeed work, though it jumps to the end animation instead of stopping in the middle or finishing the animation. That can look very glitchy, but that is an enhancement.

**Comment by msj121** [comment]
Calling a-animation.data, doesn't show an "end" value.

**Comment by ngokevin** [comment]
We've deprecated a-animation. Try https://github.com/ngokevin/kframe/tree/master/components/animation and file issues, and component will be merged in in the future.
