### ISSUE TITLE
Raycast from mouse cursor

### ISSUE THREAD

**Issue by theDrGray** [aframevr/aframe#1983]
**aframe 0.3.0**
Im trying to raycast from mouse location opposed to the center of camera. Is there a way to implement this currently? Ive moved my cursor to the mouse location and can "click" when I align the mouse and center of camera over my object. 

I found this component, but it is for pre raycaster functionality. 
https://github.com/mayognaise/aframe-mouse-cursor-component

Im going to keep pushing on it and working on my own component, but wanted to ask if anyone has had any success. 

Thanks

**Comment by ngokevin** [comment]
The mouse cursor component should work.

https://github.com/jesstelford/aframe-click-drag-component does similar as does the https://github.com/aframevr/aframe-inspector

The three.js demo has a draggable objects demo too
