### ISSUE TITLE
PS4 browser compatibility with aframe

### ISSUE THREAD

**Issue by vrimaginar** [aframevr/aframe#1986]
Is Aframe compatible with the PS4? The PS4 UX seems to be based on webgl for the most part from what I read but I can not load sky spheres with equirectangular photo's in the web browser. The web browser is based on webkit. The vr symbol appears in the lower right by the way.

It would be nice to get this to work because of the PSVR headset release.

Version I tested was 0.2.0.

**Comment by ngokevin** [comment]
Depends on their browser's WebGL/WebVR support. If it can't load a simple skysphere, there's something up with their browser.

**Comment by ngokevin** [comment]
Let me know how three.js examples load

**Comment by bryik** [comment]
[This guy](http://blog.greggant.com/posts/2016/04/07/exploring-and-developing-for-the-ps4-browser.html) says the PS4's browser does not support WebGL (blog post from April 7th, 2016).

FWIW, PsVita definitely doesn't work (tried it myself a few days ago).

**Comment by ngokevin** [comment]
Would have to wait for a WebGL-compatible browser from PS.

**Comment by jpryne** [comment]
The PS4 actually scores the highest among consoles in WebGL speed, yet Sony appears to be blocking WebGL content purely out of some morbid fear that PS4 users might play with Xbox users.

![](http://i.imgur.com/JO0wWsE.png)
