### ISSUE TITLE
Making A-Frame work without exposing globals on Window

### ISSUE THREAD

**Issue by Zacqary** [aframevr/aframe#1989]
Caveat: I'm new to A-Frame and don't understand all the implications of why this design decision was made. But I'm approaching it trying to incorporate A-Frame into an existing Webpack application where we're trying to avoid adding `window.stuff` and instead keep everything scoped inside the modules that use them.

The `window.AFRAME` global runs counter to that pattern.

I know it's possible to `import AFRAME from 'aframe'` in an individual module, so that we don't have to introduce a new global to our `.eslintrc`. But that doesn't prevent `AFRAME` from being exposed as a global at all, and opens us up to all the possible bugs and issues that come with that.

The problem with changing this, from what I understand, is that the ecosystem depends on `AFRAME` existing as a global; i.e., third-party components don't need to be ES6 or CommonJS modules that `import AFRAME from 'aframe'` or `var AFRAME = require('aframe')` — they just work. And that's necessary for making third-party components available in environments that don't use NPM or a module system, and everything needs to be imported with `<script>` tags.

I'm coming from the React world where third party components are pretty much all released as NPM modules, but I know that a lot of them also release versions that are backwards-compatible with `<script>` tagging.

Anyway, the last thing I want to be is the ES6 hipster bursting into this community and demanding we all do things differently around here, but I'm interested in knowing what people's thoughts are on this issue. I can see how it'd be a breaking change to make A-Frame conform to the hip new module patterns, but in codebases that use things, attaching a global can be a pretty big concern.

**Comment by ngokevin** [comment]
I'm experienced with npm and ES6 modules and Browserify/Webpack/UMD workflows so I understand. A-Frame is pretty large scope, it's VR in your browser, I think that warrants a global. Think of it as the global `window` of VR.

I used to prescribe components when installed through `npm` do:

```
var AFRAME = require('aframe');
AFRAME.registerComponent('foo', require('my-component'));
```

But I preferred less work for developers so they can just require and go. For your linter, you can do `/* global AFRAME */`. And there's not much of a consequence of exposing a singleton as a global, traditionally, it might feel bad because applications used to put *everything* in global.

**Comment by Zacqary** [comment]
Yeah, I guess the debate about whether *some* things can be globals, or if *nothing* can be a global, is philosophical in a Webpack 1.x context. What I'm concerned about is that A-Frame in its current form won't allow me to tree-shake.

Obviously to take full advantage of that I'd need to be able to `import { registerComponent } from 'aframe'` which is a bigger issue, but I think with an async bundle loader I can still defer loading the whole A-Frame library until after the page with A-Frame calls gets loaded.

Or maybe it'd just wait to attach it to the global until after, and then it'd be fine if it's still hanging around if the user clicks away from that part of the app. But it's still not something I have to worry about with most other large frameworks in the NPM ecosystem that aren't attaching themselves to the window.

Maybe it's not an urgent change; aside from some early tree-shaking build systems I can't off the top of my head come up with a killer app for switching over entirely to the module pattern. As those mature, though, I think it could be more of a pressing issue.

**Comment by ngokevin** [comment]
Don't think we can do much as A-Frame is and should be used as a frontend library where a window is available. I think it is requirable from Node now though.
