### ISSUE TITLE
components, working fine in aframe 0.2.0 no longer work in 0.3.0 or 0.3.2

### ISSUE THREAD

**Issue by kaosbeat** [aframevr/aframe#1993]
**Description:**
my components, working fine in aframe 0.2.0 no longer work in 0.3.0 or 0.3.2 
more than that, the "happyface example" works in firefox on 0.3.0, not in 0.3.2

I have no clue why upgrading break them. I get no feedback in the error console...

- A-Frame Version: 0.3.0, 0.3.2 
- Platform/Device: chrome/firefox on mac
- Reproducible Code Snippet or Demo URL [highly encouraged]:

http://64.137.164.54:3000/0.3.2
http://64.137.164.54:3000/0.3.0
http://64.137.164.54:3000/0.2.0

**Comment by ngokevin** [comment]
Try defining your components before `<a-scene>`
