### ISSUE TITLE
Sound in 360 video not tracked

### ISSUE THREAD

**Issue by vrimaginar** [aframevr/aframe#2001]
The sound in a 360 degree video is not tracked. If you make a video with the Gear 360 and play it in the Gear VR the Oculus software is tracking the sound when you move your head. Is this possible with Aframe?

**Comment by ngokevin** [comment]
You can take the stereo sound source from the video and use the positional sound component for left and right, perhaps?

**Comment by vrimaginar** [comment]
So, demux video and sound and position both in the same direction with Aframe? I guess it would work if both are in sync when the video and sound start playing. I will experiment with it, thanks.

I wonder if the Gear 360 records binaural sound.

**Comment by ngokevin** [comment]
The 360 devices are focused on images rather than video capture, so I'd be surprised. The videos you saw were maybe professionally produced with binaural mics and rigs?

**Comment by vrimaginar** [comment]
No they were not taken with professional rigs .When you take a video with the Gear 360 it has sound tracking in the Gear VR (I have both). However the video's don't have sound tracking on youtube, for instance. I did see a video once taken with the LG 360 cam that had sound tracking on youtube.

But I think you're right in saying that they don't have binaural recording capacities.

**Comment by ngokevin** [comment]
I recommend demuxing the audio from video and place the sounds where you want with the positional sound component.
