### ISSUE TITLE
Add to README: browser support badges or link to "Device & Platform Support" docs page

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#2004]
It would be nice if there were some [browser badges](https://github.com/substack/browser-badge#example) in the [`README`](https://github.com/aframevr/aframe#a-frame). Or a link to the [Devices & Platform Support docs page](https://aframe.io/docs/0.3.0/introduction/device-and-platform-support.html) could suffice.

**Comment by rttomlinson** [comment]
Hello, I'm new to contributing to open source software. How can I help with this and who do I contact?

**Comment by ngokevin** [comment]
Hi, check out this contributing guide https://github.com/aframevr/aframe/blob/master/CONTRIBUTING.md and some of the other issues in the repo. Welcome and thanks!

**Comment by rttomlinson** [comment]
Found the Contributing guidelines right after I posted that. My bad and thanks!

**Comment by ngokevin** [comment]
thanks!
