### ISSUE TITLE
rename aframe master builds in dist

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2007]
**Description:**

In `dist/` folder, I think everyone doesn't see `aframe.min.js` are the unstable builds.

Rename to like `aframe-master.min.js`

**Comment by dmarcos** [comment]
What about `aframe-dev.min.js` or `aframe-unstable.min.js`?

**Comment by ngokevin** [comment]
`aframe-dev` works. Will break various toy projects using `rawgit/aframe/dist/aframe.min.js` but better earlier than later.
