### ISSUE TITLE
"var src = src =" should be "var src =" in a-assets.js

### ISSUE THREAD

**Issue by takahirox** [aframevr/aframe#2015]
**Description:**

Hi, I'm new to A-Frame.

I think this line

https://github.com/ngokevin/aframe/blob/5af7916d8460d7f5ecc61fcdcbc9bf6d3afb6f0e/src/core/a-assets.js#L86

    var src = src = this.getAttribute('src');

should be

    var src = this.getAttribute('src');

correct?

If I'm right, I'll make PR to fix.

**Comment by ngokevin** [comment]
yeah that's a bug, can you fix it? thanks!

**Comment by takahirox** [comment]
I see, I'll make PR, thanks!
