### ISSUE TITLE
timer - how to smoothly update scene

### ISSUE THREAD

**Issue by lgp698asd** [aframevr/aframe#2028]
**Description:**
try write a clock or timer
- A-Frame Version: 0.3.0
- Platform/Device: Desktop Chrome
- Reproducible Code Snippet or Demo URL [highly encouraged]:

``` js
function ttimer(){
  var options = {
    hour: 'numeric',
    minute: 'numeric',
    second: 'numeric'
  };
  var el_ttimer=document.querySelector('#a-ttimer');
  var d = new Date();
  el_ttimer.setAttribute('text', 'text: '+d.toLocaleString("ru", options)+'; font: Droid Sans Mono; size: .77;');
}
setInterval(ttimer, 1000);
```

``` html
<a-entity a-ttimer position="-12 0 -5" id="a-ttimer"></a-entity>
```
# question

how update text smoothly? timer for example
how create new primitives in scene smoothly?
have you best practice for it?

ps
thanks

**Comment by ngokevin** [comment]
You can ask on StackOverflow.

I posted and answered it at:

http://stackoverflow.com/questions/40336251/how-do-i-add-a-tick-timer-clock-or-behavior-to-my-scene-that-runs-continuousl/40336252#40336252
