### ISSUE TITLE
on `ctrl +alt + s` scene does not appear in screenshot image

### ISSUE THREAD

**Issue by micahstubbs** [aframevr/aframe#2029]
**Description:**

- A-Frame Version: master - `<script src="https://rawgit.com/aframevr/aframe/master/dist/aframe.min.js"></script>`
- Platform/Device: `Chromium Version 55.0.2842.0 (64-bit) Aug 29 WebVR build`, `Windows 10`, `HTC Vive`, `Steam VR Oct 10 Build`
- Reproducible Code Snippet or Demo URL [highly encouraged]:
`index.html` from:
[http://bl.ocks.org/micahstubbs/8b86aabbae0c849d9e12f39d7df10eae](
![image](https://cloud.githubusercontent.com/assets/2119400/19845042/44bd496a-9ef0-11e6-95c5-6708d2eefc98.png)
)

good news 😃 when I `<ctrl> + <alt> + s` while in VR mode, aframe produced an image file for me and saved it in my windows downloads folder.

bad news 😅 it doesn't look like it's an image of my scene.  just all black (Windows preview)or all white (in Chrome) depending on how I open it 

[screenshot-a-frame - bl ocks - d3-1477891143292.png](https://cloud.githubusercontent.com/assets/2119400/19844999/e11b1a68-9eef-11e6-8e72-0b9621e433e8.pn)
![screenshot-a-frame - bl ocks - d3-1477891143292](https://cloud.githubusercontent.com/assets/2119400/19844999/e11b1a68-9eef-11e6-8e72-0b9621e433e8.png)

**Comment by micahstubbs** [comment]
one more blank screenshot image, this time taken from normal 2D mode, not in VR
`screenshot-a-frame - bl ocks - d3-1477959291419.png`
![screenshot-a-frame - bl ocks - d3-1477959291419](https://cloud.githubusercontent.com/assets/2119400/19875915/307d19b4-9f8e-11e6-84cc-cf05211d302c.png)

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/aca4f90584a78262e9567c6b67d2aec74878027f

**Comment by micahstubbs** [comment]
👍
