### ISSUE TITLE
allow configure textures, separate texture component from material

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2032]
**Description:**

Lots of properties for THREE.Texture at https://threejs.org/docs/?q=texture#Reference/Textures/Texture , how to expose these in a clean way for each kind of map?

Maybe a texture property type?

```
material="map: [src: #texture; anisotropy: 1.1; flipY: true]"
```

Or a indirect route?

```
material="map: #texture__map"
texture__map="src: #texture; anisotropy: 1.1; flipY: true"
```

**Comment by ngokevin** [comment]
Looking at https://aframe.io/docs/master/components/material.html#built_in_materials and how there are multiple map types trying to expose every texture properties for each one, it seems necessary for a separate texture component. @dmarcos toyed with this before.

**Comment by bryik** [comment]
In Three.js, "renderer.getMaxAnisotropy()" makes it easy to set anisotropy to the max supported value. I wasn't sure how to do this in A-Frame and often set it to 16 (the value for my GPU). Something like ```anisotropy: max;``` or ```anisotropy: auto;``` would be nice.

[Anisotropy example (16x vs default)](https://bl.ocks.org/bryik/a82893253ea55f401af114778bc5453b).

**Comment by ngokevin** [comment]
I think this will be important as currently, we have to create a different property on the material component for each type of map, duplicating a lot of the texture setup. The standard shader has:

- ambientOcclusionMap
  - intensity
  - repeat
  - offset
- displacementMap
  - intensity
  - repeat
  - offset
- normalMap
  - intensity
  - repeat
  - offset
- map (src)
  - intensity
  - repeat
  - offset

Then what if we want to add a new texture property, like configure the wrapping or flip? We'd have to add it to each single one, and in the code, we'd have to duplicate logic.

A separate texture/map component would be cleaner. It could have its own system for caching. You just define a texture component, and reference from the material (or any other) component.

```material="map: [map__texture]" map__texture="src: #textureImg; anisotropy: 1.1; flipY: true"```

And alternative, allow inline definition


```material="map: [src: #textureImg; anisotropy: 1.1; flipY: true]"```

**Comment by donmccurdy** [comment]
I'm not 100% sure whether I like this any better, but for discussion's sake here's a counter-proposal. No integration with the existing `material` component, just a separate `texture-config` component that modifies properties of the object it's attached to, whether there's a `material` component or a model of some kind.

```
<a-entity obj-model="obj: url(...); mtl: url(...);"
          texture__emissive="map: emissive;
                             src: url(emissive.png);
                             flipY: false;>
</a-entity>
```

If `src` is omitted, it would just modify the existing texture on that object, if any.

Potentially more complicated if this is a model with multiple meshes. Apply to them all? Allow a `name` selector?

**Comment by donmccurdy** [comment]
I think my concern with the original proposal is that it's verbose and requires changes to the schema, for a case where I (personally) would probably just define the THREE.Material in a component.

Like, I'm not going to want fine-grained control over textures on a cube geometry, and if it's a custom mesh then why not package textures with that? Where I might want this would be to, say, add an emissive channel to something exported from MagicaVoxel ([example](https://twitter.com/donrmccurdy/status/838971043909894145)) and in that case there would be no `material` component to begin with.

**Comment by machenmusik** [comment]
after the last set of custom shader changes, do we still have the issues originally described?  multi-texture custom shaders should be easily doable now...

**Comment by donmccurdy** [comment]
I wasn't thinking of this issue as being specific to custom shaders; seems valid even for the default three.js material types. But whether the issue is common enough to be worth a component (or schema changes) in core at this point I'm not sure.

Example: MagicaVoxel doesn't export an emissives channel, so I threw together [this component](https://github.com/donmccurdy/webvr-experiments/blob/master/3-postprocessing/components/material-map.js) yesterday to add that. Could have done this in Maya or Blender, of course, but eh. Or maybe you want to enable/disable emissive when something turns on, etc.

**Comment by ngokevin** [comment]
Maybe this could be done more internally by having a texture property type of some sort that gets mixed into the material just for code quality (easier caching of identical textures, easier handling of updates).

**Comment by donmccurdy** [comment]
Maybe I'm not sure what problem you want to solve, sorry.

My working assumption is that very few developers will use things like `aoMap` with the `material` component, much less `aoMap.flipY`, because the `material` component isn't very compatible with custom models and occlusion maps of primitive geometry aren't very interesting.

But if there's something about the current implementation that would benefit from cleanup then please go ahead. :)

**Comment by ngokevin** [comment]
I want to solve manually implementing multiple different texture property types for each type of map and be able to easily add more texture property types to each.

I also want to improve texture caching, in memory and for the GPU. TextureLoader handles network caching, not memory and not sending duplicate texture data to GPU. We currently cache textures if they have the same `src` and same `repeat`, but there are much more texture properties to take into account.

I agree though that perhaps these property types aren't important for the basic material component, and they could just be imported using glTF.

**Comment by machenmusik** [comment]
@donmccurdy right, I had gone to the assumption that those interested in such things would go directly to custom shader and avoid `material` altogether

**Comment by ngokevin** [comment]
I'll close this then in favor of more of a code quality / refactor route without affecting the API to descope this.
