### ISSUE TITLE
Dependent instantiations do not correctly populate data

### ISSUE THREAD

**Issue by GavanWilhite** [aframevr/aframe#2033]
Its appear that `init()` is getting called with `this.data` not populated when it is early-instantiated via the dependency logic.

`this.data.foo` will be undefined in `init()` for this entity `<a-entity component-that-is-depended-on="foo: bar" component-with-dependency></a-entity>`

https://github.com/aframevr/aframe/blob/master/src/core/a-entity.js#L358

My guess is that the solution may end up involve retrieving the `attrValue` if `isDependency` is `true` before calling this:
https://github.com/aframevr/aframe/blob/master/src/core/a-entity.js#L331

**Comment by ngokevin** [comment]
Here's a test I wrote, it oddly passes:

```js
+     test('initializes defined dependency component', function (done) {
+       var el = document.createElement('a-entity');
+
+       registerComponent('root', {
+         dependencies: ['dependency']
+       });
+
+       registerComponent('dependency', {
+         schema: {foo: {type: 'string'}},
+         init: function () {
+           assert.equal(this.data.foo, 'bar');
+           delete components.root;
+           delete components.dependency;
+           done();
+         }
+       });
+
+       // Create entity all at once with defined dependency component and component.
+       el.setAttribute('dependency', 'foo: bar');
+       el.setAttribute('root', '');
+       this.el.appendChild(el);
+     });
```

Any suggestions for this test case?

**Comment by GavanWilhite** [comment]
Investigating..

**Comment by GavanWilhite** [comment]
So here is a example for the issue: http://codepen.io/team/altspacevr/pen/395fe11ce0019dba71d64ba6ccc39507/?editors=1000

Trying to play with your test to tell. The reverse order from what you have there is the issue I am pointing at. I tried flipping the order of your calls, but that doesn't affect the test. My guess is that it may have something to do with how the HTML is parsed vs JS setAttribute calls.

**Comment by ngokevin** [comment]
OK thanks! I'll try to inject raw HTML as string then.
