### ISSUE TITLE
reports of browser entering fullscreen instead of VR 

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2034]
**Description:**

We currently check for a non-zero pose (orientation) with utils.checkHeadsetConnected to determine whether to enter fullscreen or VR. Something in newer builds might have regressed that

- A-Frame Version: v0.3.2
- Platform/Device: Latest Firefox Nightly

**Comment by dmarcos** [comment]
I can't reproduce this. I just tested on Nightly with a-frame master.

**Comment by ngokevin** [comment]
I believe @cvan reported this in Slack. I'll double check too.

**Comment by cvan** [comment]
Yep, I get this quite often. Every time I try to get reproducible steps, I have to restart my browser and it magically works again. Will keep an eye outz

**Comment by dmarcos** [comment]
Is this a problem with A-Frame or Firefox? Does the problem reproduce with non a-frame content?

**Comment by dmarcos** [comment]
I'm not sure if there's anything actionable here. There is a known regression on Firefox due to `e10s` but we cannot do much on the a-frame side.

**Comment by ngokevin** [comment]
OK, will just keep our eyes out in our QA cycle (with FF Nightly w/ disabled e10s) until we get solid info

**Comment by cvan** [comment]
This was definitely not due to e10s issues; this was much earlier. Feel free to close until there are more reports
