### ISSUE TITLE
Unusable after trying to save using "V" | Lot of bright blue light

### ISSUE THREAD

**Issue by rabimba** [aframevr/aframe#2037]
**Description:**

When you are inside A Painter and click "V" to automatically save a snippet of the painting. Immediately after 2-3 seconds the user experiences a lot of bright vertical and horizontal lines inside Vive which makes the application unplayable. This is NOT reflected in the external monitor. Only inside the VIVE. Was reliably reproducible in the version I tested till day before yesterday.

- A-Frame Version:

Using https://aframe.io/a-painter/ (date: 28-30 November)

- Platform/Device:

HTC Vive / Chromium Sep 23 version.

- Reproducible Code Snippet or Demo URL [highly encouraged]:

Can't.
The device used is VR Ready setup from Mozilla Berlin office. With Chromium downloaded and configured on 27th October.

**Comment by ngokevin** [comment]
moved to a-painter https://github.com/aframevr/a-painter/issues/156
