### ISSUE TITLE
Original url('srcPath') string is not maintained in element

### ISSUE THREAD

**Issue by mflux** [aframevr/aframe#2038]
**Description:**

I'm writing a A-Frame DOM->JSON scene save/loader.

OBJ-Models that have property "obj: url(assets/asset.obj)" (and mtls) get their sources trimmed. When iterating through the elements, you get something like this:

    Object {mtl: "assets/asset.mtl", obj: "assets/asset.obj"}

When loading this back as an element by doing:
    element.setAttribute( propertyName, propertyObject );

A-frame will throw an error:

    aframe.js:62939 Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': 'assets/BlackCW_Rand_LOD0.mtl' is not a valid selector.

This is because 

1. The url('') part is stripped and

2. This function

    function assetParse (value) {
      var parsedUrl = value.match(/\url\((.+)\)/);
    ...

is too lax with matching url() and when that fails it looks for an element id immediately. 

What I think A-Frame should do is match the url('') part, then if that fails, match the hashtag ('#') part for an existing element, then finally if all else fails, simply load the argument as the url.

Either that, or provide the original, unmodified string with the url('') in-tact. 

- A-Frame Version: Master
- Platform/Device:
- Reproducible Code Snippet or Demo URL [highly encouraged]:

**Comment by ngokevin** [comment]
I think that sounds good. I don't imagine needing non-ID selectors for assets.
