### ISSUE TITLE
Fix `hovered` mixin state so it works with template instances

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#204]
> Created new example Interactions scene in A-Frame that hits this issue. PR is here #199 
> 
> In that scene I've applied a mixin to a template. It appears that the template will successfully take the initial value of the mixin (eg `scale="1 0.5 1"`). But the template does not respond to subsequent hovered states.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
