### ISSUE TITLE
Incorrect Axes when VR view has been openen second time

### ISSUE THREAD

**Issue by lalok** [aframevr/aframe#2042]
I implemented a vr menu that is loaded from local assets folder. When this site is loaded for the first time, everything is fine. But every time I enter this screen a second time, the axes are incorrect and the whole scene is rotated. Than I have to kill the application and from now it works again but only once.

It is irrelevant which content I use, the problem remains. I also tried to clear the local cache of the web view, but the problem still remains.

Is this a known bug?

- A-Frame Version: 0.3.2 (also tried with 0.3.0 and 0.3.1)
- Platform/Device: Nexus 6 with Android 6.0.1, Samsung Galaxy S7 Android 6.0.1, Oneplus X with Android 5.1.1
- Used XWalkView from XwalkProject to display the content

**Comment by gurumukhi** [comment]
I didnt face this problem with my project hosted at https://gurumukhi.github.io/vr-ram/. Tried on sony xperia z3c. Am I missing anything here?

**Comment by mkungla** [comment]
I experienced similar issue with 0,3.x, but none of the later versions of a-frame so I think that issue could be closed.

**Comment by dmarcos** [comment]
I cannot reproduce either with any modern A-Frame version.
