### ISSUE TITLE
Navigation bar stays visible in screen (even in VR mode)

### ISSUE THREAD

**Issue by kevindh89** [aframevr/aframe#2046]
**Description:**
On the iPhone SE, VR mode won't go to fullscreen. The navigation bar stays visible (see screenshot).
This problems occurs in Chrome as well as Safari. 

![screenshot-iphone-se](https://cloud.githubusercontent.com/assets/1700302/19977502/1643ff78-a1f4-11e6-8b90-56dc2d902106.jpg)

- A-Frame Version: 0.3.0
- Platform/Device: iOS10 / iPhone SE
- Reproducible Code Snippet or Demo URL [highly encouraged]: https://aframe.io/examples/showcase/sky/

**Comment by ngokevin** [comment]
Try setting `window.scrollTop to 0

**Comment by kevindh89** [comment]
Thanks for your response!

I recreated the A-Frame example to play around with setting window.scrollTop to 0.
It didn't work out for me.. Ended up with this piece of code (demo: http://vr.kevindh.nl):

`<html>
<head>
  <title>A-frame example</title>
  <script src="https://aframe.io/releases/0.3.0/aframe.min.js"></script>
</head>

<body>
  <a-scene>
    <a-sky src="R0010471.JPG" rotation="0 -130 0"></a-sky>
  </a-scene>

  <script type="text/javascript">
  var scene = document.querySelector('a-scene');
  scene.addEventListener('enter-vr', (event) => {
    window.scrollTop = 0;
  });
  </script>
</body>
</html>`

Still showing the navigation bar in VR mode like this:

<img width="654" alt="screen shot 2016-11-10 at 22 38 31" src="https://cloud.githubusercontent.com/assets/1700302/20195363/87c06996-a796-11e6-8852-195f459618ae.png">

Any ideas?
From this point I'm pretty unsure what to do, but if I can do anything to contribute to solve this problem.. I'm happy to help.

**Comment by ngokevin** [comment]
Well, it's a Safari problem. If you can find any solutions such as http://stackoverflow.com/questions/24889100/ios-8-removed-minimal-ui-viewport-property-are-there-other-soft-fullscreen , that'd be great...else we recommend more recent hardware/software.

**Comment by dmarcos** [comment]
I believe the only reliable way to get fullscreen on Safari Mobile (behavior is slightly different based on device / screen side) is by pinning the site to the home screen. I believe there's no additional action that we can take on the A-Frame side. Just hoping that iOS cooperates a bit better in the future.
