### ISSUE TITLE
Add mirroring modes for VR

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#2049]
It would be nice to offer a different set of mirroring options with VR:

![view-modes](https://cloud.githubusercontent.com/assets/1560884/19981721/4edb8876-a1c0-11e6-8bee-eef236ffb496.png)

**Comment by jellix79** [comment]
It would be so great to have it!

**Comment by dmarcos** [comment]
Since 0.8.0 there's a spectator mode for the camera component https://aframe.io/docs/0.8.0/components/camera.html#properties_spectator

I have not seen much demand for the reduced mode. Should it be part of the core or an advance feature provided by external components?

**Comment by machenmusik** [comment]
The way I have seen reduced modes used lately is for webcam image insertion when not set up to do full mixed reality capture.  So maybe mono-full spectator with optional webcam p-in-p would be nice for that

**Comment by dmarcos** [comment]
We have now a spectator mode for `Mono-full` / `Spectator-full` described above. We have not seen much demand for the other modes and can be explored as 3rd party components. Closing for now.
