### ISSUE TITLE
Confusing documentation about asset load events

### ISSUE THREAD

**Issue by jbjw** [aframevr/aframe#2057]
https://aframe.io/docs/master/core/asset-management-system.html#events

I understand that A-Frame nodes can emit a 'loaded' event, so that makes sense for `<a-asset-item>`, but then the documentation says "Images are a standard DOM element so we can listen to the standard DOM events." and then refers to a same-named 'loaded' event. I'm unaware of any standard DOM event 'loaded', only 'load'. Are the HTML <img> elements in <a-assets> augmented with a special A-Frame 'loaded' event which we should use, or should we stick with standard DOM event 'load'?

If the former, then the language should be changed from "Images are a standard DOM element so we can listen to the standard DOM events." to something like "A-Frame extends standard DOM elements, so we can listen to the 'loaded' event that nodes in A-Frame emit when they have finished loading.

If the latter, then the event name [here](https://aframe.io/docs/master/core/asset-management-system.html#lt-img-gt) should be changed to 'load'.

This is my first GitHub issue, please let me know of any mistakes.

- A-Frame Version: master, 0.3.2, 0.3.0

**Comment by ngokevin** [comment]
thanks! it should be load
