### ISSUE TITLE
consider adding system handlers for when one of its component are attached/detached

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2067]
**Description:**

```js
entityAttached: function (el, componentData) {

},

entityDetached: function (el, componentData) {

}
```

**Comment by donmccurdy** [comment]
`entityAttached` vs `componentAttached`?

**Comment by ngokevin** [comment]
Not fleshed out yet, but probably entity. The entity is now managed by the system. You could possible do neat stuff like specifying two components, and matching entities that only have *both* of those components (e.g., `enemy` + `dead`).

**Comment by donmccurdy** [comment]
This could be done nicely with mutation observers:

```js
var observer = new MutationObserver((mutations) => console.log(mutations));

observer.observe(sceneEl, {
  attributes: true,
  subtree: true,
  attributeFilter: ['foo']
});
```

Except that sadly it won't catch `foo__1`.

**Comment by ngokevin** [comment]
wontfixing for now. Prefer systems to be dumb/aliased components that get initialized first.
