### ISSUE TITLE
Enhancement: Add Matrix4 Property Type

### ISSUE THREAD

**Issue by james-h-stephens** [aframevr/aframe#2069]
Addition of the Matrix4 property type for creation of Matrix4 objects to assist in the creation of quaternions.

**Comment by donmccurdy** [comment]
@james-h-stephens working on this, but also there is a `vec4` property type that [works well for quaternions](https://github.com/donmccurdy/aframe-physics-system/blob/master/src/components/math/quaternion.js).

**Comment by foobar404** [comment]
@dmarcos can we close this? Seems like its already been completed twice.
