### ISSUE TITLE
FPS stats in VR mode

### ISSUE THREAD

**Issue by feiss** [aframevr/aframe#2077]
Performance stats inside VR mode is really needed. Just a FPS counter attached to the headset tracking, in a corner of the screen, or even just a small quad with a color code indicating if fps > 90 (green) or not: orange ( >= 80 ),  red ( <80 )..

**Comment by Utopiah** [comment]
Would be good to keep it coherent with existing stats component i.e. make the in VR mode display the situation (FPS at least) cf https://github.com/aframevr/aframe/blob/master/src/components/scene/stats.js#L29

**Comment by machenmusik** [comment]
see #2162

**Comment by ngokevin** [comment]
https://github.com/ngokevin/kframe/tree/master/components/fps-counter#aframe-fps-counter-component
