### ISSUE TITLE
Generate dev/master dist/ builds on commit (or nightly)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2083]
**Description:**

Should detect that the commit contains actual code or dependency changes.

**Comment by ngokevin** [comment]
On every commit to A-Frame (detecting changes to `src/` or `package.json`), the bot should run:

1. `git pull --rebase origin master`
2. `npm run dist`
3. Update the version in package.json to append the `-devX` (e.g., `version: "0.4.0-dev22"`)
4. `git commit -m "Update master build, 0.4.0-dev13 (https://rawgit.com/aframevr/aframe/<HASH>/dist/aframe-master.min.js)" && git push origin master`

This will:

1. Rebase
2. Generate the updated `-master` builds
3. Make it such that users of these A-Frame builds will see the version in their console
4. Push the build with helpful messages on which build it is and a rawgit URL to use the build

**Comment by ngokevin** [comment]
WIP https://github.com/ngokevin/afro

**Comment by donmccurdy** [comment]
+1 for reflecting unstable version in `AFRAME.version` and/or console printout.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/8ad5261ce62a0044bef648cdf1a01a86b8d979b2

https://github.com/ngokevin/a-frobot

I will update it to bump the package.json for the version + a daily update of the READMEs.
