### ISSUE TITLE
srcLoader.validateSrc returns `video` for selectors

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe#2089]
**Description:** When 
- A-Frame Version: master
- Reproducible Code Snippet or Demo URL [highly encouraged]: http://codepen.io/fernandojsg/pen/KNMgGW

```html
<a-assets>
  <img id="bulletDecal" src="https://feiss.github.io/a-shooter-assets/images/decal0.png" crossOrigin="anonymous">  
</a-assets>
```

```javascript
function loadImageCb (src) {
  console.log('Image!', src);
}

function loadVideoCb (src) {
  console.log('Video!', src);
}

AFRAME.utils.srcLoader.validateSrc('#bulletDecal',loadImageCb, loadVideoCb);
AFRAME.utils.srcLoader.validateSrc('https://feiss.github.io/a-shooter-assets/images/decal0.png',loadImageCb, loadVideoCb);
```

Will output:
```
Image! https://feiss.github.io/a-shooter-assets/images/decal0.png
Video! #bulletDecal
```

I believe it's because the changes on this commit as we're not taking care of the selector anymore, and `validateImageUrl` expect an url as `src`, but we're passing a selector in this example.
https://github.com/aframevr/aframe/commit/ab9c71f4e5d07ace0ea17696cf64aa78f84c030c#diff-729d7016997fd0bed786c47760b73244

**Comment by dmarcos** [comment]
It seems that the logic that checks for an selector is gone from the `validateSrc` function

**Comment by ngokevin** [comment]
What was the use case of calling `validateSrc` directly? Currently, the property type extracts the `src` from `img/video` elements so a URL is always passed to `validateSrc` in the material system.

**Comment by fernandojsg** [comment]
It's from the decals system I'm working on. It's basically replicating the updateMap that you've in materials to apply it to custom geometry:

```javascript
...
  init: function () {
    var data = this.data;

    this.numDecals = 0;
    this.decals = [];
    this.oldestDecalIdx = 0;
    this.textureSrc = null;

    this.geometry = new THREE.PlaneGeometry(1, 1);
    this.material = new THREE.MeshBasicMaterial({
      transparent: true,
      color: '#24CAFF',
      depthTest: true,
      depthWrite: false,
      polygonOffset: true,
      polygonOffsetFactor: -20
    });

    this.updateMap();
  },

  updateMap: function () {
    var src = this.data.src;
    AFRAME.utils.srcLoader.validateSrc(src, function(){console.log('text')}, function(){console.log('video')});

    if (src) {
      if (src === this.textureSrc) { return; }
      // Texture added or changed.
      this.textureSrc = src;
      this.sceneEl.systems.material.loadTexture(src, {src: src}, setMap.bind(this));
      return;
    }

    // Texture removed.
    if (!this.material.map) { return; }
    setMap(null);

    function setMap (texture) {
      this.material.map = texture;
      this.material.needsUpdate = true;
    }
  },

  update: function (oldData) {
    this.updateMap();
  },
...
```

**Comment by ngokevin** [comment]
What is `src`? If you use a proper property type (`asset`), all selectors should have been resolved to a URL.

**Comment by fernandojsg** [comment]
Ouch! my fault 👼 I forgot to set the type. I've just created a PR (https://github.com/aframevr/aframe/pull/2090) to remove the selector references in the comment on that function, to prevent future misunderstandings :)
