### ISSUE TITLE
360 Video playback slow in iOS 10.2, aframe 0.3.2 VR mode

### ISSUE THREAD

**Issue by theDrGray** [aframevr/aframe#2091]
As the title says, video playback on mono 360 video on both safari/chrome is laggy/slow when in VR mode. Plays back fine on all other devices and in non VR mode on both browsers (ios safari, ios chrome). 

I saw that in the previous versions the poor quality vr mode on ios was due to an issue in safari with resize. The quality in this versions (.3.2) vr mode on ios is much better. Only issue I've noticed so far is VR mode video playback.

- A-Frame Version: 0.3.2
- Platform/Device: iOS 10.2 Safari/Chrome, iPhone 6s Plus, 
- Reproducible Code Snippet or Demo URL [highly encouraged]: Will provide a stripped down link ASAP

**Comment by theDrGray** [comment]
Creating a simplified version of my site showed me that its not 0.3.2 but something in the rest of my site (1 video sphere, 5 image spheres, and 26 2D videos that can be triggered to play on planes within the 3D scene). Playback of just my video sphere in 0.3.2 is smooth. 

Something must have changed. Going to chase that down and will followup.

**Comment by dmarcos** [comment]
@theDrGray I'm going to close this. Please reopen if you think it's a problem with a-frame
