### ISSUE TITLE
Oculus Touch integration

### ISSUE THREAD

**Issue by jamessteininger** [aframevr/aframe#2092]
**Description:**

- A-Frame Version: 0.3.2
- Platform/Device: Windows/Oculus Touch
- Reproducible Code Snippet or Demo URL [highly encouraged]: Get https://aframe.io/a-painter/ to work with Oculus Touch controller models and input.

**Comment by dmarcos** [comment]
Oculus touch has to be first supported in browser in order for us to support it.

**Comment by machenmusik** [comment]
see https://github.com/aframevr/aframe/pull/2132
