### ISSUE TITLE
Video and Videosphere Don't Load in Chromium

### ISSUE THREAD

**Issue by JonathanGrant** [aframevr/aframe#2093]
**Description:**
When I try to load the example video scene from https://aframe.io/examples/showcase/videosphere/ I just get a black screen on Chromium. 
- A-Frame Version: 0.3.2
- Platform/Device: Chromium
- Reproducible Code Snippet or Demo URL [highly encouraged]:
Here's my console output
<img width="304" alt="aframeconsole" src="https://cloud.githubusercontent.com/assets/6880862/20282519/e100f176-aa69-11e6-81b7-c1a4bc92f8ba.PNG">

**Comment by ngokevin** [comment]
Make sure your codec is compatible with Chromium, which only has FOSS codecs.

**Comment by JonathanGrant** [comment]
How can I do this?

Hack Prius,
Hack Love,
Hack Life.
-J
facebook.com/HackLifePrius

**Comment by ngokevin** [comment]
Will look into it.

**Comment by machenmusik** [comment]
isn't this due to stock Chromium lack of support for H264 / MP4?

**Comment by ngokevin** [comment]
Yeah. The actionable thing to do here is to convert that A-Frame example video to a friendlier codec.

**Comment by JonathanGrant** [comment]
Thanks guys! When the stable Chrome has WebVR abilities, will I be able to play this codec?

**Comment by machenmusik** [comment]
yes - and supposedly there is some tricky way you can roll your own custom chromium build for testing that enables them

**Comment by JonathanGrant** [comment]
Can you please link me to wherever you heard that?

**Comment by dmarcos** [comment]
@JonathanGrant You can try any a-frame scene on regular Chrome and see if the video plays. (https://aframe.io/examples/showcase/videosphere/ plays fine) You won't be able to enter VR but at least you know if it's a problem with the video codec or something else.
