### ISSUE TITLE
make sure that camera.userHeight still applies in Oculus seated mode

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2099]
**Description:**

I will set up my Rift and check this out tomorrow 

See if we can use WebVR API features like defined height, or standing/seated booleans

**Comment by ngokevin** [comment]
@dmarcos If you're free, I'm not working on this yet.

**Comment by dmarcos** [comment]
I'm not sure I understand the problem. I believe that `userHeight` should not apply on `seated mode`. @ngokevin is that your assumption too?

**Comment by ngokevin** [comment]
That's true now that I think about it. Will re-open if I run into any issues QAing for CV1.
