### ISSUE TITLE
download links on main github page are broken

### ISSUE THREAD

**Issue by softpunch** [aframevr/aframe#2111]
![screen shot 2016-11-17 at 10 25 43 pm](https://cloud.githubusercontent.com/assets/19437970/20417650/e08f7d0e-ad14-11e6-9359-05b67f5a5204.png)

![screen shot 2016-11-17 at 10 26 10 pm](https://cloud.githubusercontent.com/assets/19437970/20417656/e64499dc-ad14-11e6-98f4-0205b12dd697.png)

**Comment by ngokevin** [comment]
thanks!
