### ISSUE TITLE
Add arraybuffer <a-asset-item>

### ISSUE THREAD

**Issue by takahirox** [aframevr/aframe#2112]
**Description:**

I think letting \<a-asset-item> support arraybuffer will be useful for components.
Actually \<a-mmd> I'm working on needs MMD assets data downloaded as arraybuffer.

https://github.com/takahirox/a-mmd

IMO, it's a good idea that \<a-asset-item> supports `responseType` (or just `type`?) attribute like this.

    <a-asset-item id="model" responseType="arraybuffer" src="model.pmd"></a-asset-item>

Adding `XHRLoader.setResponseType()` right before calling `XHRLoader.load()` can enable this feature.

https://github.com/aframevr/aframe/blob/96df6c1f22fdf72c392be710d945bb9e8684b05c/src/core/a-assets.js#L99-L113

    var self = this;
    var src = this.getAttribute('src');
    var responseType = this.getAttribute('responseType');
    if (!responseType) { responseType = 'text'; }
    fileLoader.setResponseType(responseType);
    fileLoader.load(src, function handleOnLoad (response) {
      THREE.Cache.files[src] = response;
      self.data = response;
      setTimeout(function load () { ANode.prototype.load.call(self); });
    }, ....

**Comment by takahirox** [comment]
I'll make a PR if this update sounds good to you guys.

**Comment by ngokevin** [comment]
In cases like these, you would document your component to prescribe certain response types. Would there ever be an issue where two components are expecting different response types on the same asset?

**Comment by takahirox** [comment]
I plan to write document to describe which attribute should be downloaded
as arraybuffer for my component.

If two components attempt to download the same assets as different type,
the type will be the first attempting response type because of THREE.Cache
(if THREE.Cache is enable. It should be enabled for pre-downloading).

But I don't think it won't be a problem in general
because there may be no case that an asset is needed as two or more different types.

If we wanna avoid this conflict issue,
it may be one of the ways to keep the cache with url + response type key.
