### ISSUE TITLE
Feature Request - Form Controls

### ISSUE THREAD

**Issue by jarodium** [aframevr/aframe#2114]
**Description:**
I would like to suggest some degree of implementation of form controls ou input controls for that matter.
I am aware that VR input is in its very early stages ( leapmotion ) but the framework could branch out a spec for that. 

- A-Frame Version: Any
- Platform/Device: Any
- Reproducible Code Snippet or Demo URL [highly encouraged]: N/A

Regards

**Comment by dmarcos** [comment]
What do you exactly mean by form controls?

**Comment by dmarcos** [comment]
Can you describe a use case?

**Comment by fuleinist** [comment]
something like this? https://fuleinist.github.io/aframe-vr-survey/

**Comment by jarodium** [comment]
@fuleinist yes. Something of the kind.
@dmarcos imagine a 360º CMS in which a user can view and input stuff.

For example from 0º to 90º ( approx ) we see a listing. From 90º to 180º we can input data in the form. From 180º to X we can edit another record or navigate to other page. We have only to shift our heads in the direction of what we want to do in the CMS.

BTW: This does not have anything to do with Aframe, but with speech recognition available in the browser we can also add some degree of control in this "vrCMS" xD

**Comment by fuleinist** [comment]
Thumb up for VR CRM : )  It's probably achievable even with a Wordpress
Plugin,  just need someone to develop it.

**Comment by ngokevin** [comment]
Widgets and interactions can be accomplished through application-level or community components, does not need to be part of the core.
