### ISSUE TITLE
Idea: <a-star> component

### ISSUE THREAD

**Issue by fuleinist** [aframevr/aframe#2115]
It would be great to add <a-star> component with embeded webgl shader as per can be found in http://stars.chromeexperiments.com/

@ngokevin maybe something like your https://github.com/ngokevin/kframe/tree/master/components/sun-sky/ without the sky : )

**Comment by ngokevin** [comment]
try https://www.npmjs.com/package/aframe-star-component

**Comment by fuleinist** [comment]
@ngokevin Thanks for sharing.

Unfortunately This component is only 2d and has not been updated for sometime : (
