### ISSUE TITLE
Unable to test with `npm link aframe`

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2116]
When testing packages against upcoming releases, or against patches to aframe, I use `npm link`. For many packages this just works, and changes to the lib are automatically pulled into the code that depends on it. For A-Frame, I need to run `npm run dist` after each change, since Browserify/Webpack point at a built file.

On master branch now, it looks like `npm run dist` builds `aframe-master.js` instead of `aframe.js`, so I don't know how to flush an update through my NPM dependencies anymore, without manually renaming files.

Ideas on how to test changes quickly? Is there an NPM script that builds `aframe.js` without doing a bunch of release stuff, or should we add one?

- A-Frame Version: master

**Comment by ngokevin** [comment]
Good catch, the package.json should point to `aframe-master.js` now.

**Comment by ngokevin** [comment]
I remember we don't point it to `index.js` because since it's built with Browserify, any requiring libraries would have to pull in Browserify-CSS and build steps. Any way around that?

**Comment by donmccurdy** [comment]
Ah that was it. Tried the `browserify.transform` field in package.json?  Supposedly consumers of the module don't need to know about the transform if it's declared there. https://github.com/substack/browserify-handbook#browserifytransform-field

**Comment by ngokevin** [comment]
We do have that declared. Will need to try again to remember what was the hold-up, if there was any.

**Comment by ngokevin** [comment]
I believe even if Browserify transforms are declared, Webpack consumers have to be handled as well?

**Comment by donmccurdy** [comment]
Yeah, i don't know if there's any bundler-agnostic way to do CSS. 😕
