### ISSUE TITLE
Update tween.js version. Tween is using a deprecated package that has DoS issue.

### ISSUE THREAD

**Issue by pankajnathani** [aframevr/aframe#2122]
Latest version of aframe v0.3.2 uses tween.js v15.0 which is more than a year old. 

I am getting npm warnings because few of the dependent packages are very old and has security issues:

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

Here is dependency tree of packages.

tween.js@15.0.0 
│ │ ├─┬ gulp@3.9.1 
│ │ │ ├── archy@1.0.0 
│ │ │ ├── deprecated@0.0.1 
│ │ │ ├─┬ gulp-util@3.0.7 
│ │ │ │ ├── array-differ@1.0.0 
│ │ │ │ ├── array-uniq@1.0.3 
│ │ │ │ ├── beeper@1.1.1 
│ │ │ │ ├─┬ dateformat@1.0.12 
│ │ │ │ │ ├── get-stdin@4.0.1 
│ │ │ │ │ └─┬ meow@3.7.0 
│ │ │ │ │   ├─┬ camelcase-keys@2.1.0 
│ │ │ │ │   │ └── camelcase@2.1.1 
│ │ │ │ │   ├─┬ loud-rejection@1.6.0 
│ │ │ │ │   │ └─┬ currently-unhandled@0.4.1 
│ │ │ │ │   │   └── array-find-index@1.0.2 
│ │ │ │ │   ├── map-obj@1.0.1 
│ │ │ │ │   ├─┬ normalize-package-data@2.3.5 
│ │ │ │ │   │ ├── hosted-git-info@2.1.5 
│ │ │ │ │   │ ├─┬ is-builtin-module@1.0.0 
│ │ │ │ │   │ │ └── builtin-modules@1.1.1 
│ │ │ │ │   │ └─┬ validate-npm-package-license@3.0.1 
│ │ │ │ │   │   ├─┬ spdx-correct@1.0.2 
│ │ │ │ │   │   │ └── spdx-license-ids@1.2.2 
│ │ │ │ │   │   └── spdx-expression-parse@1.0.4 
│ │ │ │ │   ├─┬ read-pkg-up@1.0.1 
│ │ │ │ │   │ └─┬ read-pkg@1.1.0 
│ │ │ │ │   │   ├─┬ load-json-file@1.1.0 
│ │ │ │ │   │   │ └── strip-bom@2.0.0 
│ │ │ │ │   │   └── path-type@1.1.0 
│ │ │ │ │   ├─┬ redent@1.0.0 
│ │ │ │ │   │ ├── indent-string@2.1.0 
│ │ │ │ │   │ └── strip-indent@1.0.1 
│ │ │ │ │   └── trim-newlines@1.0.0 
│ │ │ │ ├─┬ fancy-log@1.2.0 
│ │ │ │ │ └── time-stamp@1.0.1 
│ │ │ │ ├─┬ gulplog@1.0.0 
│ │ │ │ │ └── glogg@1.0.0 
│ │ │ │ ├─┬ has-gulplog@0.1.0 
│ │ │ │ │ └── sparkles@1.0.0 
│ │ │ │ ├── lodash._reescape@3.0.0 
│ │ │ │ ├── lodash._reevaluate@3.0.0 
│ │ │ │ ├─┬ lodash.template@3.6.2 
│ │ │ │ │ ├── lodash._basecopy@3.0.1 
│ │ │ │ │ ├── lodash._basetostring@3.0.1 
│ │ │ │ │ ├── lodash._basevalues@3.0.0 
│ │ │ │ │ ├── lodash._isiterateecall@3.0.9 
│ │ │ │ │ ├─┬ lodash.escape@3.2.0 
│ │ │ │ │ │ └── lodash._root@3.0.1 
│ │ │ │ │ ├── lodash.restparam@3.6.1 
│ │ │ │ │ └── lodash.templatesettings@3.1.1 
│ │ │ │ ├─┬ multipipe@0.1.2 
│ │ │ │ │ └── duplexer2@0.0.2 
│ │ │ │ ├── object-assign@3.0.0 
│ │ │ │ ├── replace-ext@0.0.1 
│ │ │ │ ├─┬ through2@2.0.1 
│ │ │ │ │ └─┬ readable-stream@2.0.6 
│ │ │ │ │   └── isarray@1.0.0 
│ │ │ │ └─┬ vinyl@0.5.3 
│ │ │ │   └── clone-stats@0.0.1 
│ │ │ ├─┬ liftoff@2.3.0 
│ │ │ │ ├─┬ fined@1.0.2 
│ │ │ │ │ ├── lodash.assignwith@4.2.0 
│ │ │ │ │ ├── lodash.isempty@4.4.0 
│ │ │ │ │ └─┬ parse-filepath@1.0.1 
│ │ │ │ │   ├─┬ is-absolute@0.2.6 
│ │ │ │ │   │ └─┬ is-relative@0.2.1 
│ │ │ │ │   │   └─┬ is-unc-path@0.1.1 
│ │ │ │ │   │     └── unc-path-regex@0.1.2 
│ │ │ │ │   ├── map-cache@0.2.2 
│ │ │ │ │   └─┬ path-root@0.1.1 
│ │ │ │ │     └── path-root-regex@0.1.2 
│ │ │ │ ├── flagged-respawn@0.3.2 
│ │ │ │ ├── lodash.isplainobject@4.0.6 
│ │ │ │ ├── lodash.isstring@4.0.1 
│ │ │ │ └── lodash.mapvalues@4.6.0 
│ │ │ ├── minimist@1.2.0 
│ │ │ ├─┬ orchestrator@0.3.8 
│ │ │ │ ├── end-of-stream@0.1.5 
│ │ │ │ └── sequencify@0.0.7 
│ │ │ ├── pretty-hrtime@1.0.3 
│ │ │ ├── tildify@1.2.0 
│ │ │ ├─┬ v8flags@2.0.11 
│ │ │ │ └── user-home@1.1.1 
│ │ │ └─┬ vinyl-fs@0.3.14 
│ │ │   ├── defaults@1.0.3 
│ │ │   ├─┬ glob-stream@3.1.18 
│ │ │   │ ├── glob@4.5.3 
│ │ │   │ ├─┬ glob2base@0.0.12 
│ │ │   │ │ └── find-index@0.1.1 
│ │ │   │ ├── ordered-read-streams@0.1.0 
│ │ │   │ └── unique-stream@1.0.0 
│ │ │   ├─┬ glob-watcher@0.0.6 
│ │ │   │ └─┬ gaze@0.5.2 
│ │ │   │   └─┬ globule@0.1.0 
│ │ │   │     ├─┬ glob@3.1.21 
│ │ │   │     │ ├── graceful-fs@1.2.3 
│ │ │   │     │ └── inherits@1.0.2 
│ │ │   │     ├── lodash@1.0.2 
│ │ │   │     └─┬ minimatch@0.2.14

**Comment by mikebolt** [comment]
Gulp is no longer a dependency of Tween.js. It was a development-only dependency. Tween.js is a 100% standalone JavaScript file.

It should be safe to update. I just released [version 16.4](https://github.com/tweenjs/tween.js/releases) through Github, but it won't be on npm until @sole updates it.

**Comment by ngokevin** [comment]
I's fine to have an old version of a dep lib. Upgrading it won't do much, but I plan to replace tween with anime anyways.
