### ISSUE TITLE
Video autoplays and loops

### ISSUE THREAD

**Issue by paddeee** [aframevr/aframe#2126]
Adding `<a-video>` or `<a-videosphere>` primitives in the latest master version results in the video playing automatically and looping with seemingly no way to override this behaviour.

- A-Frame Version: Master
- Platform/Device: Windows 10/ Chromium

`<a-scene>
    <a-assets>
        <video src="assets/video/test.webm" preload="auto" id="who"></video>
    </a-assets>
    <a-video id="Video"
             src="#who"
             height="0.6"
             width="1.2"
             position="0 2 -1">
    </a-video>
</a-scene>`

**Comment by machenmusik** [comment]
can you see if this is fixed by https://github.com/aframevr/aframe/pull/2129 ?

**Comment by paddeee** [comment]
Thanks machenmusik. 

Yes, can confirm that this has fixed the issue. Works as expected again.
