### ISSUE TITLE
Audio Visualization "View Source" link is broken

### ISSUE THREAD

**Issue by JonathanGrant** [aframevr/aframe#2127]
**Description:**
When you click View Source in the audio visualizer example, you are taken to a link that Github says does not exist.
- A-Frame Version:
- Platform/Device:
- Reproducible Code Snippet or Demo URL [highly encouraged]:

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-site/commit/661b154dd1e16f417625050ad18989a66fef49e6

fixed, thanks!
