### ISSUE TITLE
Camera is facing directly down in Chrome + Safari Dev Tools mobile emulators

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#213]
I remember working with @dmarcos on figuring out these mobile issues. Somewhere in https://github.com/MozVR/aframe-core/blob/dev/src/core/a-scene.js I presume this is happening.

<img width="1552" alt="screenshot 2015-11-24 00 57 24" src="https://cloud.githubusercontent.com/assets/203725/11362151/c7458bac-9246-11e5-878f-6d5537163eb9.png">

[http://localhost:9001/examples/panoexplorer/](http://localhost:9001/examples/panoexplorer/)

**Comment by dmarcos** [comment]
If this is still an issue it will have to be handle in the polyfill.
