### ISSUE TITLE
add utils.throttleTick to be called once every X ms

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2136]
**Description:**

Common case to only want to call a tick behavior on an interval rather than every frame.

```js
AFRAME.registerComponent('foo', {
  tick: utils.throttleTick(function (t, dt) {
  
  }, 500);
});
```

This would keep track of last time the function ran, and wait 500 ms before calling again.

**Comment by mikebolt** [comment]
The code looks good to me.

You may want to use window.performance.now for a more precise timestamp. We wrote [a polyfill](https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L72) for window.performance.now in tween.js.

Also, this could be useful for tween.js. I might borrow this code.

**Comment by machenmusik** [comment]
(@ngokevin this is done right?)

**Comment by ngokevin** [comment]
Added
