### ISSUE TITLE
Component naming silently failing

### ISSUE THREAD

**Issue by Utopiah** [aframevr/aframe#2139]
**Description:**  A component named _namedcomponent_ get registered and works whereas _NamedComponent_ or _namedComponent_ silently fails.

- A-Frame Version: master
- Platform/Device: desktop Firefox stable
- Reproducible Code Snippet or Demo URL [highly encouraged]: http://jsbin.com/jovuwut/edit?html,output

**Comment by mikebolt** [comment]
Add this code:

    var mm = document.getElementById('metameta');
    console.log(mm.attributes);

The resulting NamedNodeMap only contains "namedcomponent". HTML ignores the capitalization of attributes. You can use the capitalized version and register a lower-case component, but not visa-versa.

There is no fix, but the code can and should produce a warning, and this should be documented.

**Comment by ngokevin** [comment]
Warning added.
