### ISSUE TITLE
Compress skies images

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#214]
__`2.64 MB`__ https://github.com/aframevr/aframe/blob/master/examples/showcase/composite/lake.jpg
__`149 KB`&nbsp;&nbsp;__ https://github.com/aframevr/aframe/blob/master/examples/showcase/composite/portland.png
__`379 KB`&nbsp;&nbsp;__ https://github.com/aframevr/aframe/blob/master/examples/showcase/composite/sculpture-tex.jpg

**Comment by gasolin** [comment]
@cvan seems the links are broken

**Comment by cvan** [comment]
@gasolin thanks - updated the links in the first comments

**Comment by cvan** [comment]
also filed #1420 for other images that could use some compression. (many others have already been crushed/compressed.)
