### ISSUE TITLE
[0.4.0] #2108 incorrectly returns empty object when default value is `null`

### ISSUE THREAD

**Issue by jesstelford** [aframevr/aframe#2140]
**Description:**

- A-Frame Version: `master` (#2108)
- Platform/Device: All
- Reproducible Code Snippet or Demo URL [highly encouraged]:

When setting a component schema such as:

```javascript
schema: {
  foo: {
    type: 'string',
    default: null,
  }
}
```

The values set on `this.data` don't reflect the default `null`, instead, we end up with an empty object.

The problem is introduced by [this line](https://github.com/dmarcos/aframe/blob/53eae6d00a6eca53e494b6e3f2887251a36549a3/src/core/component.js#L334):

```javascript
data[key] = typeof defaultValue === 'object' ? utils.extend({}, defaultValue) : defaultValue;
```

The `utils.extend` returns a new empty object.

---

## The Fix

Instead, it should check to see if it's actually an object, maybe via one of these two methods:

```javascript
data[key] = Object.prototype.toString.call(defaultValue) === '[object Object]' ? utils.extend({}, defaultValue) : defaultValue;
```

or

```javascript
data[key] = (defaultValue.constructor && defaultValue.constructor === Object) ? utils.extend({}, defaultValue) : defaultValue;
```

Personally; I prefer the first option as it protects against the mutable `.constructor` property being modified by userland code.

---

_Edit_: Am happy to open a PR; just give the :+1: for one of the two solutions above, and I'll get it done.

**Comment by dmarcos** [comment]
What about this one?
````javascript
data[key] = typeof defaultValue === 'object' && defaulValue !== null? utils.extend({}, defaultValue) : defaultValue;
````

**Comment by jesstelford** [comment]
That works too :)

There's nothing else that reports `typeof` as `'object'` which we'd need to special-case here too?

**Comment by dmarcos** [comment]
Well this another case:
````javascript
typeof [] === 'object'
````
But if we have an array as default it would be a single property schema and it would not run the line you pointed out. Your proposals are good but I think mine it's a bit more explicit and easier to understand. @jesstelford You're more than welcome to submit a PR if you want to take this. Can you add a test to cover for the bug?

**Comment by donmccurdy** [comment]
@dmarcos @jesstelford I've filed a bug separately but of the suggestions so far, only one handles arrays correctly:

```js
data[key] = (defaultValue.constructor && defaultValue.constructor === Object) ? utils.extend({}, defaultValue) : defaultValue;
```

See also, [is-plain-object](https://github.com/jonschlinkert/is-plain-object/blob/master/index.js).

Default values may be arrays whether it's a single-property schema or not, so I don't think there's an easy out there.

**Comment by donmccurdy** [comment]
Although, IMHO, primitive types `string` (or `int`, `number`, ...) should be non-nullable and either cast to an empty string, or throw an error when assigned a non-string default value like `null`. But that's personal preference and not really the question here. :)
