### ISSUE TITLE
When/where to update shader uniforms?

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2147]
**Description:**

Let's say I've got a custom shader that depends on the camera's position:

```js
const glsl = require('glslify');

AFRAME.registerShader('myShader', {
  schema: {
    vCameraPosition: { type: 'vec3', is: 'uniform' }
  },
  vertexShader: glsl.file('./my-shader.vertex.glsl'),
  fragmentShader: glsl.file('./my-shader.fragment.glsl')
});
```

I'll need to update `vCameraPosition` on every frame, but the shader itself doesn't have a `tick()` lifecycle method. So I can do that by adding a new component, instead:

```js
AFRAME.registerComponent('myShaderUpdater', {
  tick: function (t, dt) {
     el.components.material.material.uniforms.vCameraPosition.value.set(...);
  }
});
```

That works, but there's also no guarantee that the camera (or any other components my shader depends on) have already ticked. In practice, the shader ends up 1 frame behind.

Any suggestions on a better way to update uniforms? Some ideas:

1. Declare order/priority of components (sounds complicated).
2. Use a system (do systems always tick after components?).
3. Add support for `tick` lifecycle method to the shader itself, which should be invoked later than components.

**Comment by wizgrav** [comment]
1. a fast easy way to provide some order would be adding a tock() method on components. All tocks() would be guaranteed to run after ticks(). Post processing doesn't need changes to the core, I'm currently implementing it on top of regular master.

2. This is the only choice for your case right now.

3. This would be great and would simplify the implementation of complex materials, like using procedurally generated textures etc

**Comment by donmccurdy** [comment]
Closing this / not any sort of urgent.
