### ISSUE TITLE
Screenshot should be a camera component, not a scene component

### ISSUE THREAD

**Issue by Utopiah** [aframevr/aframe#2148]
**Description:** I started to work on an MR component attaching the camera to a controller then planning to take screenshots through that secondary camera. Sadly it seems the screenshot component is implicit or rather only assumes one camera. It works in most case but in this specific one, which I believe is quite interesting it doesn't.

- A-Frame Version: master
- Platform/Device: Chromium + Vive
- Reproducible Code Snippet or Demo URL [highly encouraged]: http://jsbin.com/qujuzaz/edit?html,output

**Comment by ngokevin** [comment]
Alternatively, pass a selector for the camera

**Comment by dmarcos** [comment]
The screenshot component should always operate on the active camera. There's maybe oportunity for a `point-and-shoot` component

**Comment by ngokevin** [comment]
Yeah, probably a different feature. Like a literal camera component that you can hold and see a preview.
