### ISSUE TITLE
Animation are not working properly on experimental webvr enabled chrome builds

### ISSUE THREAD

**Issue by discordianfish** [aframevr/aframe#2150]
Hi,

I wanted to play around with a-frame animations and things looked in stable chrome (54.0.2840.9), but when I switched to the webvr enabled chrome build from https://webvr.info/get-chrome/ my animations stopped working properly. They still did something, but no smooth animation. Best see for yourself, can be reproduced with the anime ui example as well: https://aframe.io/examples/showcase/anime-UI/.

**Comment by discordianfish** [comment]
(Quite possible this is a webvr issue in chrome, I just can't say. /cc @toji)

**Comment by Sebkasanzew** [comment]
It stopped working in the latest chrome build for WebVR from 29th Oktober 2016.
In the release from the 23rd of September 2016 animations are working fine: https://drive.google.com/drive/folders/0BzudLt22BqGRbHdGOTdiaTBkZXM

**Comment by mikebolt** [comment]
This might be the issue ([source](https://docs.google.com/document/d/1dP9m3WLh2lsBs9jJ9LRwv1l0AtuBQAqGLAV-fUbtz2U)):

> The timestamp passed to the requestAnimationFrame callback is off by a factor of 1000, the function erroneously receives microseconds instead of milliseconds.

This will definitely mess up tween.js.

**Comment by ngokevin** [comment]
Yeah, that's the issue. Fall back to the September 23rd builds for now.

**Comment by machenmusik** [comment]
see #2207 and #2217
