### ISSUE TITLE
Official videosphere demo does not work on mobile

### ISSUE THREAD

**Issue by edzis** [aframevr/aframe#2152]
- A-Frame Version: 0.3.2
- Platform/Device:
    - iOS 10.10 / iPod touch
    - iOS 9.3.5 / iPhone 5
    - android 6.0.1 / Samsung Galaxy S6 / Chrome 
- Reproducible Demo URL: https://aframe.io/examples/showcase/videosphere/

I am following the instructions of adding to home screen, launching the home screen app but I get a black screen in place of video. Same result also without using home screen.

With remote debugger I get a lot of instances of this:
`[Warning] Invalid timestamps detected. Time step between successive gyroscope sensor samples is very small or not monotonic (aframe.js, line 55911, x24)`

When entering VR mode I get another error:
```
[Error] TypeError: null is not an object (evaluating 'link.nextElementSibling')
	getDestNavLink (examples.js:64)
	(anonymous function) (examples.js:29)
```

I know this has been discussed on #316, but all the constraints mentioned there have been fulfilled, yet it does not work.

**Comment by mloparco** [comment]
I am having the same issue, same black screen, in fact have ~never~ been able to get <a-videosphere> to work on mobile (iOS 10.x). Followed all instructions verbatim, including adding the metatag, inline-video, pin to home screen, etc. in all permutations. What are we missing here?

**Comment by innovativemonsters** [comment]
I am having the same issue. Any chance it is a problem with the CDN? I mean... it shouldn't, but I can't figure out whats wrong at all. Desktop mode works fine.

**Comment by fuleinist** [comment]
https://github.com/aframevr/aframe/issues/1846

**Comment by ufon** [comment]
up

**Comment by ip** [comment]
Probably this happens because the video file should be served from the same origin - this is how mobile Safari works. Here video file is served from CDN domain.

**Comment by ngokevin** [comment]
Can merge this with #1846. We hide the videosphere demo on mobile for these reasons, and I don't have the answers. Lately, people have been getting inline video to work on iOS somehow. If you have any hints, check them in at #1846.
