### ISSUE TITLE
vue.js / nuxt.js with a-frame not loading properly

### ISSUE THREAD

**Issue by 7ammer** [aframevr/aframe#2155]
Hello!

I'm trying to get vue/nuxt.js working in tandem with a-frame however a-frame isn't loading properly. Sometimes the scene loads other times it loads content from one template but not from another on other occasions it just doesn't load at all. It looks like the two libraries are racing each other while loading.

Does anyone kmow how to get a-frame working with nuxt.js / vue?

Cheers :)

**Comment by ngokevin** [comment]
We'd need a simple test case that would reproduce an issue for A-Frame. Not sure what would happen with Nuxt (never used) + Vue
