### ISSUE TITLE
CORS error when doing inline URLs

### ISSUE THREAD

**Issue by msj121** [aframevr/aframe#2156]
When adding a url as such:

`<a-sphere material="src:url(...)"></a-sphere>`

I get: 

> No 'Access-Control-Allow-Origin' header is present on the requested resource

Is it possible that inline urls could be made to allow for crossorigin as  a property of the material?

Reposted here (in case it is not a bug): https://stackoverflow.com/questions/40955781/cors-inline-material-for-aframe

**Comment by ngokevin** [comment]
Server side issue, the server did not allow CORS on the resource

**Comment by msj121** [comment]
I actually DO have CORS setup on my amazon server. It works correctly when the file is added as part of the <a-assets> with crossorigin attribute.

`<img id="alibrary" src="https://s3.amazonaws.com/..." crossorigin="anonymous">`

The problem is when I try to set the url on the object itself not in a-assets:

`<a-image src="url(...)" position="0 0 -2" width="2" height="2"></a-image>`

I get the following error:
> XMLHttpRequest cannot load https://s3.amazonaws.com.... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin is therefore not allowed access.

**Comment by msj121** [comment]
Personally I don't care too much as I use the <a-assets> as a workaround, but I have experienced CORS issues when using the url on the object directly.

**Comment by ngokevin** [comment]
You should double check CORS is not set up as referenced by:

> No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by ngokevin** [comment]
OK, will need to double check the XHR has CORS set. I believe it should, we set it on the XHRLoader (soon to be named FileLoader).

**Comment by msj121** [comment]
If your request doesn't specify an Origin header, S3 won't include the CORS headers in the response.

**Comment by codechikbhoka** [comment]
is the issue solved ? I am facing the same problem

**Comment by bhibi** [comment]
still on problem

**Comment by codechikbhoka** [comment]
@bhibi I solved the problem I was facing. Can you elaborate your case ?

**Comment by bhibi** [comment]
thx @codechikbhoka i had some problem with adding image, .jpg file work flawless but i cant add my .png image with transparent background.

**Comment by KhaledGabr** [comment]
I guess I am having the same error, when I put the image link using imgix ( a service similar to cloudinary ) directly in the page everything works, however when I put it in the aframe tag, it doesn't work
`<a-scene>
  <a-sky src="https://example.imgix.net/example/example.jpg?lossless=True" rotation="0 0 0"></a-sky>
</a-scene>
`
This is all what I have in the page, a simple 360 image served from an external source over HTTPS.
Please help me fix this error.
Thanks in advance.

**Comment by codechikbhoka** [comment]
what happens is, when you request a resource from a third party, you have to mention the origin tag in the request. Then only that third party will send you response with Access-Control-Allow-Origin header. So to do this in aframe, you should add crossorigin=anonymous in your img item in your a-asset.

This should work: 

<a-scene>

  <a-assets>
    <img id="advertisement" src="ad.png" crossorigin="anonymous">
  </a-assets>

  <a-plane src="advertisement"></a-plane>

</a-scene>

**Comment by KhaledGabr** [comment]
@codechikbhoka Thank you so much Vivek, That solved it for me!

**Comment by ngokevin** [comment]
Using an `<img>` in `<a-assets>` without crossorigin should work since A-Frame will auto-inject that.

I wonder about the inline URL piece though

**Comment by ngokevin** [comment]
I've did an extra set of cross origin on the TextureLoader for inline URLs, maybe that will help even though we overrode the prototype already https://github.com/aframevr/aframe/pull/2544

**Comment by ngokevin** [comment]
Check if that works. https://rawgit.com/aframevr/aframe/ee12d49/dist/aframe-master.min.js

**Comment by alwell-kevin** [comment]
@ngokevin Using the asset management system did not fix the issue. 

```
<a-assets>
        <img id="asset-scene-url" src="{{location.scene_img_url}}">
<a-assets>

  <a-sky ng-click="print()" src="#asset-scene-url"></a-sky>
```

Where location.scene_img_ur is an s3 asset with CORS enabled. Issue still remains.

**Comment by EnoahNetzach** [comment]
@ngokevin the problem with **Chrome** (and **Safari**) is probably within [this piece of code](https://github.com/aframevr/aframe/blob/16679ab3518d7d07b4c61abd7817d2ca5098da60/src/utils/src-loader.js#L91-L103).

It "checks" that the to-be-loaded src is indeed an image, without setting the `crossOrigin` value. The browser then probably caches the received headers and since it was NOT requested with the `Origin` header, the `Access-Control-Allow-Origin` header is not present in the cached response.

Then it proceeds to load the image (using **three.js**' `ImageLoader`), but since this time the `crossOrigin` is set (`"anonymous"` by default) and the header is not set in the cache, the browser cancels it because of *CORS*.

**Comment by einfochips1** [comment]
@codechikbhoka not able to access your solution. could you please resend it?
https://gist.github.com/codechikbhoka/3c0135b88ec1fd876377d091a19f92df url is not accessible.

Thanks in advance

**Comment by joselevelsup** [comment]
I am still getting trouble with this. I can not use both the inline and `crossorigin` method from an S3 bucket. I have used Aframe React, Vanilla Aframe (mostly `a-image`), the asset system using `<img src=whatever crossorigin="anonymous" />`, and I tried to apply a texture to a plane to try and render out my image but I am not succeeding.

**Comment by Besnuggs** [comment]
Is there a way to bypass this with an inline URL on <a-image> and not use the asset-management-system? I'm experiencing this exact issue on a React based application using the aframe-react-assets plugin, and I'd like to avoid any needless data flow to an image that technically isn't Static, but rather a user selected image from my database that needs to be requested.  

Thank you in advance.

**Comment by nealoke** [comment]
I also have the issue where the image loads fine in a regular `img` tag but when aframe tries to load it, it gives me the CORS error... Same as @joselevelsup and @Besnuggs 

It is from s3 bucket as well...

@Besnuggs did you find a solution?

**Comment by Besnuggs** [comment]
Hey @nealoke 

I'm afraid not.  I did solve my issue, but I ultimately connected Redux to a separate file containing the a-assets and the img tags I wanted to load, and simply passed in the srcs as the component mounted. And, although this has helped with rendering my images from AWS, CORS still interferes with the loading of some images that are loading elsewhere (not from AWS) - but would otherwise load just fine as inline URLs in the a-image tag.

**Comment by maxleonard** [comment]
Made it work.. Make sure you use an uppercase 'A' in your `imageElement.setAttribute('crossorigin', 'Anonymous');`
