### ISSUE TITLE
Attaching raycaster to an entity with vive-controls causes crash (master)

### ISSUE THREAD

**Issue by bryik** [aframevr/aframe#2158]
**Description:** @sirkitree [reported](https://github.com/bryik/aframe-vive-cursor-component/issues/2) yesterday that using the vive-cursor component with A-Frame master causes a crash. I thought this was a problem with the component at first, but adding A-Frame's own raycaster component to an entity with vive-controls causes the same crash.

- A-Frame Version: master
- Platform/Device: Desktop
- Reproducible Code Snippet or Demo URL [highly encouraged]: 

[CodePen With master](https://codepen.io/bryik/pen/womdvL) (crash).

[CodePen With 0.3.2](https://codepen.io/bryik/pen/XNERmR) (runs fine).

**Comment by sirkitree** [comment]
Thanks for filing here @bryik!

**Comment by machenmusik** [comment]
does this still occur with latest master?

**Comment by bryik** [comment]
Nope, the master CodePen example no longer crashes. Seems this was fixed!

**Comment by bryik** [comment]
I think it's back. Adding `raycaster` to an entity with `vive-controls` causes Nightly to crash with A-Frame 0.5.0.

[Example](https://codepen.io/bryik/pen/BRMjxB).

Console dump:

![image](https://cloud.githubusercontent.com/assets/12419712/26369957/466d0636-3fc4-11e7-857f-33285031a153.png)

**Comment by ngokevin** [comment]
Regression from probably non-recursive raycaster changes, checking it out.

**Comment by machenmusik** [comment]
@ngokevin did you see this while working on laser-controls PR?  I assume you were using vive -- trying to understand if it is a core issue or an interaction with other components folks are using

**Comment by ngokevin** [comment]
Yes. In the `examples/cursor-projection/` that loads an OBJ model. Errors on 2D desktop too.

**Comment by bryik** [comment]
That example CodePen I posted earlier does not crash when [master is used instead of 0.5.0](https://codepen.io/bryik/pen/VbgmXw). Fixed by [this PR](https://github.com/aframevr/aframe/pull/2696), I take it. 

Thanks @ngokevin!
