### ISSUE TITLE
Loading textures for custom shaders in registerShader schema

### ISSUE THREAD

**Issue by alfa256** [aframevr/aframe#2159]
**Description:**
Right now there is no way to register a src to be loaded as a texture to be sampled by a custom shader.

Something like this or any variation would be nice:

```
    diffusetex: { type: 'src', is: 'uniform' }
    normalmap: { type: 'src', is: 'uniform' }
```

- A-Frame Version: 0.4.0
- Platform/Device: any

This might be also related to #2147

**Comment by donmccurdy** [comment]
To do this, I think we just need the shader registration to recognize an additional type for textures. Specifically THREE.Texture → 't' in THREE.ShaderMaterial uniforms.

**Comment by machenmusik** [comment]
yes, or you can replace the default init/update handling and handle uniforms yourself.  will see if i can post an example

**Comment by machenmusik** [comment]
```
    // this shader uses offset and repeat

    AFRAME.registerShader('offset-repeat', {
        schema: {
            // the texture source (probably a video)
            src: {type: 'map'},
            // texture parameters
            offset: {type: 'vec2', default: {x: 0, y: 0}},
            repeat: {type: 'vec2', default: {x: 1, y: 1}}
        },

        uniforms: {
            // the texture value (once the texture source is loaded, update)
            map: { type: 't', value: null },
            // texture parameters
            offset: {type: 'vec2', value: {x: 0, y: 0}},
            repeat: {type: 'vec2', value: {x: 1, y: 1}}
        },

        init: function(data) {

            this.material = new THREE.ShaderMaterial({

                uniforms: this.uniforms,

                vertexShader: this.vertexShader,

                fragmentShader: this.fragmentShader

            });
        },



        update: function (data) {
            AFRAME.utils.material.updateMap(this, data);
            this.uniforms.map.value = this.material.map;
            this.uniforms.offset.value = data.offset;
            this.uniforms.repeat.value = data.repeat;
        },



        vertexShader: [
          'varying vec2 vUV;',
          'void main(void) {',
          '  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);',
          '  vUV = uv;',
          '}'
        ].join('\n'),

        fragmentShader: [
          'uniform sampler2D map;',
          'uniform vec2 offset;',
          'uniform vec2 repeat;',
          'varying vec2 vUV;',
          'void main() {',
          '  gl_FragColor = texture2D(map, vec2(vUV.x / repeat.x + offset.x, vUV.y / repeat.y + offset.y));',
          '}'
        ].join('\n')
    });
```

**Comment by ngokevin** [comment]
Yeah, I'd just use the ShaderMaterial API directly.

**Comment by machenmusik** [comment]
(might be worth making updateMap more broadly reusable for these purposes, but for single texture this is simpler)

**Comment by donmccurdy** [comment]
Hm. ok textures are pretty pretty critical if there's going to be a registerShader API at all. I don't think this is the right line at which to ask people to switch from registerShader to using THREE.ShaderMaterial.

**Comment by ngokevin** [comment]
I think if we were to continue building the registerShader API, then yeah, texture support is mandatory. But I don't see the need for an API that tightly wraps ShaderMaterial, there's a lot of work for A-Frame to handle all of the uniform types and hiding three.js API. I'd rather registerShader just prescribe you to create a material through three.js.

**Comment by ngokevin** [comment]
There's an issue filed to reconsider the API to be less hands on and more flexible.

**Comment by machenmusik** [comment]
if type 'map' worked properly out of the box, my example would have been literally just schema and shaders, which was where i thought the line was (and should be).

**Comment by donmccurdy** [comment]
> I think if we were to continue building the registerShader API, then yeah, texture support is mandatory. But I don't see the need for an API that tightly wraps ShaderMaterial, there's a lot of work for A-Frame to handle all of the uniform types and hiding three.js API. I'd rather registerShader just prescribe you to create a material through three.js.

Ok. Yes I like either of those directions, just not the grey area in the middle of the spectrum. 🙂

**Comment by ngokevin** [comment]
Not just maps, we'd have to support a lot more things like all the uniform types and shader material parameters like fog or lights.

**Comment by LarkinArt** [comment]
I'm quite new to aFrame, looking to write a simple fragment shader that animates a texture. If I'm following this thread correctly, registerShader is likely to continue to evolve so my best bet is to use registerComponent and work directly with the threejs ShaderMaterial API?

**Comment by donmccurdy** [comment]
@LarkinArt Whether `registerShader()` will evolve or be deprecated is TBD, I think, but in either case I would work directly with THREE.ShaderMaterial within a component, yes. [Here's an example](https://github.com/donmccurdy/webvr-experiments/blob/master/1-portal/components/transient-material.js#L19-L48).

**Comment by LarkinArt** [comment]
Many thanks!

**Comment by machenmusik** [comment]
I like the way that example just uses THREE values without worrying about types, maybe that passthrough type plus map (texture) should be the limit of what registerShader() is willing to do

**Comment by machenmusik** [comment]
#2199
