### ISSUE TITLE
Consider Calling "dispose()" on Texture when removing

### ISSUE THREAD

**Issue by protyze** [aframevr/aframe#2166]
**Description:**
When removing the src-Attribute of the material-component or when removing the entire material component from an entity, the texture remains in memory.

This causes memory leaks (especially on mobile) when dealing with a lot and/or large textures. THREE.js will remove a texture from memory when "dispose()" is called on it.

Like this:
this.el.object3DMap.mesh.material.map.dispose();

Example:

http://lab.immersiveweb.ch/aframe/

Click on the left box: Removes Material (Texture count in stats remains the same)
Click on the right box: Disposes Texture and then removes Material (Texture count in stats drops)

Should we consider adding this behaviour into the Material-Component?

- A-Frame Version: 0.3.2
- Platform/Device: All
- Reproducible Code Snippet or Demo URL [highly encouraged]: http://lab.immersiveweb.ch/aframe/

**Comment by ngokevin** [comment]
Have the `src/systems/material.js` keep a running count of usage for each texture. When a material component detaches, it'll call the system's `unregisterMaterial`. In that system's method, check how many other entities are using that texture. If there are none, then call `texture.dispose` on it.

**Comment by tsotneguti** [comment]
@ngokevin Can you please post a step by step guide how to fix this problem? I can't quite follow your above answer. Thanks

**Comment by donmccurdy** [comment]
The issue was fixed by https://github.com/aframevr/aframe/issues/2686. No need to do anything, the fix will be released with A-Frame 0.6.0.

**Comment by tsotneguti** [comment]
@donmccurdy  Thanks but why on npm is still the old 0.5 version?
https://www.npmjs.com/package/aframe

**Comment by dmarcos** [comment]
@tsotneguti because 0.6.0 has not released yet 😄
