### ISSUE TITLE
Handling custom event

### ISSUE THREAD

**Issue by Zergus** [aframevr/aframe#2172]
As I understood, one-way event handling between two components should look like:
```
//component A
document.querySelector('#componentB').emit('custom', {}, false);

//componentB
this.el.addEventListener('custom', function (event) {
  //event is new some native event
})
```

Confusion for me is ```event``` parameter. As I saw, it should actually respond with ```{name, data}``` but received object with bunch of private data.

What is the way to properly handle event between components? 

- A-Frame Version: 0.4.0

**Comment by donmccurdy** [comment]
@Zergus the value of `data` will be passed in `event.detail`. Example:

```js
el.emit( 'actionstart', {value: 2} );
el.addEventListener( 'actionstart', function (event) {
  console.log( event.detail.value ); // 2
});
```

This is similar to the native [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) `detail` property.

**Comment by Zergus** [comment]
Probably I've become too comfort with event system with same input-output. As input to trigger is ```{ name, data }```, output suggested would be ```{ event, data }``` where event containing own properties and data is link to event.data. Anyway thanks for great framework.
