### ISSUE TITLE
How to add a fullscreen button on mobile?

### ISSUE THREAD

**Issue by AdrienPoupa** [aframevr/aframe#2174]
**Description:**

Hello,

Currently on a mobile device I can only enter in the VR mode. I can't enter on the classic regular fullscreen mode, which is disturbing because I would like to hide the address bar like in desktop fullscreen option. Why don't we have both icons like in Google's VR script?

https://storage.googleapis.com/vrview/index.html?image=https://i.imgur.com/lOKJwUy.jpg

I have tried the hack `window.scrollTo(0,1);` with no luck.

It seems to be relative to #1060 but I did not found how to do it.

- A-Frame Version: latest
- Platform/Device: Android device
- Reproducible Code Snippet or Demo URL [highly encouraged]: https://aframe.io/examples/showcase/sky/

**Comment by ngokevin** [comment]
Make a button that calls requestFullScreen. https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by AdrienPoupa** [comment]
Thanks!
