### ISSUE TITLE
TWEEN animation duration broken in Mozilla Nightly

### ISSUE THREAD

**Issue by Zergus** [aframevr/aframe#2175]
After trying to implement continuous and dynamic animation, I've come so solution via TWEEN:

```
AFRAME.registerComponent('camera-seeker', {
    	init() {

    		let el = this.el;
			this.CAMERA = document.querySelector('#player');
    		this.newCords = {};
    		this.seekAnim = new AFRAME.TWEEN.Tween(this.el.getAttribute('rotation'))
    			.easing(AFRAME.TWEEN.Easing.Linear.None)
    			.onUpdate(function () {
    				el.setAttribute('rotation', { x: this.x, y: this.y, z: this.z });
    			});
    	},
    	tick () {
    		this.seekAnim.to(this.CAMERA.getAttribute('rotation'), 5000).start();
    	}
    });
```

I've tested example from TWEEN github: 

```
    init() {

    		var coords = { x: 0, y: 0 };
			var tween = new TWEEN.Tween(coords)
			    .to({ x: 100, y: 100 }, 1000)
			    .onUpdate(function() {
			        console.log(this.x, this.y);
			    })
			    .start();

	    	requestAnimationFrame(animate);

			function animate(time) {
			    requestAnimationFrame(animate);
			    TWEEN.update(time);
			}
    }
```
Everything looks more less in Chrome, but in Nightly, duration seems to be awkward:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5468045/21119988/c4dfa030-c0cd-11e6-8f9c-c88915e42e4d.gif)
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/5468045/21120040/043b54cc-c0ce-11e6-9c7a-a091d719410e.gif)

For some reason TWEEN skipping animation framerate and any animation via TWEEN executes regardless duration set.

**Working perfectly without AFRAME, only TWEEN appended in header:**
![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/5468045/21120314/529eb5c2-c0cf-11e6-82a9-07346b342e31.gif)

In all examples I've build a-frame with both older and latest versions of tween.

- A-Frame Version: 0.4.0
- Platform/Device: Windows 10, Nightly 53.0a1 (2016-12-12) (64-bit)

**Comment by mikebolt** [comment]
I suspect the issue is related to the errors that appear in Firefox but not in Chromium. requestAnimationFrame isn't guaranteed to be called 60 times per second. It looks like some computationally expensive code (resizing a texture) had a higher priority than requestAnimationFrame. Try delaying the code by a second or two and see if that fixes the problem. 

I also strongly recommend resizing the texture yourself, so that it doesn't slow down the client in the future.

**Comment by fernandojsg** [comment]
I'm facing the same problem, and it's not related to expensive code, for example:
```javascript
var tween = new TWEEN.Tween({ alpha: 1.0 })
  .to({alpha: 0.0}, 1000)
  .onComplete(function () {
    console.log('completed');
  })
  .onUpdate(function () {
    console.log('updated', this.alpha);
  }).start();
```

Chromium:
![chromium](https://cloud.githubusercontent.com/assets/782511/23704941/9a365c66-0407-11e7-8a78-678a99f7e0a1.gif)

Firefox release:
![firefox](https://cloud.githubusercontent.com/assets/782511/23704952/a11fd0ac-0407-11e7-9dff-21249b164d06.gif)

Firefox Nightly:
![nightly](https://cloud.githubusercontent.com/assets/782511/23704959/a7f59aa6-0407-11e7-8eb4-ee0c40cd4266.gif)

But If I run the same on the console from one of the examples of the current TWEEN.js release on nightly, it works as expected:

![nightlytween](https://cloud.githubusercontent.com/assets/782511/23705038/fb9a6fce-0407-11e7-90c8-38bc6a532cfc.gif)

Maybe it's tme to update TWEEN? /cc @dmarcos @ngokevin

**Comment by fernandojsg** [comment]
I've just tried to update to `16.6.0`  and the problem is still there :\ it's really strange because if I run the same code on the tween examples it works but if I run on the console with AFRAME injected it doesn't

**Comment by fernandojsg** [comment]
After discussing with @dmarcos it seems that there's a problem with the `TWEEN.update(time)` in https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L446.

Logging the `time` value on chromium seems to be consistent:
![image](https://cloud.githubusercontent.com/assets/782511/23706422/6ae696cc-040e-11e7-875e-9e751468698a.png)

While in nightly it seems to jump abruptly:
![image](https://cloud.githubusercontent.com/assets/782511/23706478/a1d26b20-040e-11e7-8f67-8fb3b09a871b.png)

**Comment by fernandojsg** [comment]
FWIW if we call `TWEEN.update()`, it will use it own timer (https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L52) and it seems to work correctly both in the examples and in the code pasted before.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/6a4bd10d4ac4b018ba7abea72532f8c4b0bc22c4
