### ISSUE TITLE
Build APK using cordova, can't see videosphere working

### ISSUE THREAD

**Issue by Charton100774** [aframevr/aframe#2176]
Hi,
I want to build an APK using cordova, were i'm using the A-frame videosphere asset. I know that Chrome doesn't support A-Frame videospheres completely for now, but I hoped that it would be working with an APK. 
But there is my problem : I can hear the sound of my video running but i can only see a white screen displayed on my mobile when i start the APK. Clicking, reloading, moving around, nothing closes this screen...
Maybe Android does not support A-Frame videospheres too ?
If you could bring me more information about my problem, it would be great :)
Thank you !

**Comment by MLescaudron** [comment]
Hi,

A-frame videosphere asset work fine on Chrome.
The problem is Chrome does not allow auto play on Android. Only the users can start the video with gestures.
But you can find many workaround on Google ;)

**Comment by mkungla** [comment]
@Charton100774 you should ask that via stackoverflow http://stackoverflow.com/questions/ask/?tags=aframe

**Comment by ThibaultAr** [comment]
Hi @Charton100774 , sorry to up this post but I encountered the same problem using cordova and I can't find solution on stackoverflow or web in general :/ 
So I would want know if you have the answer or if you have open a stackoverflow issue that I missed ?
