### ISSUE TITLE
Does player supports Adaptive streaming?

### ISSUE THREAD

**Issue by ronit-kadwane** [aframevr/aframe#2177]
If it does supports Adaptive streaming then Can you please provide adaptive streaming supported videos for testing?

**Comment by donmccurdy** [comment]
I'm not too familiar with this, but I think [adaptive streaming tends to require extra libraries](http://stackoverflow.com/questions/28529383/why-do-i-need-dash-js-for-streaming-mpeg-dash-videos), like dash.js. If you set all of that up, it could certainly be possible to use with THREE.js or A-Frame. But, I haven't seen anyone implement this yet, and I don't think we're able to provide videos for testing sorry.

**Comment by machenmusik** [comment]
latest master needs #2129

**Comment by mkungla** [comment]
@ronit-kadwane #2129 is merged does that solve it for you?

**Comment by kfarr** [comment]
As long as media source extensions are supported it is possible to build a component that could support adaptive streaming. I would not suggest this be part of A-Frame core. So the answer would be no, A-Frame video elements do not support adaptive bitrate streaming out of the box but it would be possible for a third-party component to provide that functionality.

**Comment by ngokevin** [comment]
Yes, this feature would be left as a component and to extra libraries.
