### ISSUE TITLE
Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by salmanfarisvp** [aframevr/aframe#2178]
while am trying to Local Installation and Development via 
`git clone git@github.com:aframevr/aframe.git` 
but stuck here 
```
Cloning into 'aframe'...
Permission denied (publickey).
fatal: Could not read from remote repository.
``
OS :- windows 10

**Comment by donmccurdy** [comment]
@salmanfarisvp You may not have a public key attached to your GitHub account: that would prevent cloning from git@ URLs. You can fix that [with these instructions](https://help.github.com/articles/error-permission-denied-publickey/#verify-the-public-key-is-attached-to-your-account).

Alternatively, try cloning from the HTTPS version of the URL:

```
git clone https://github.com/aframevr/aframe.git
```

**Comment by salmanfarisvp** [comment]
thanks @donmccurdy , now working fine
