### ISSUE TITLE
<a-animation> fails if y component of `to` is in scientific notation

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#2180]
`AFRAME.utils.coordinates.stringify` will produces scientific notation for values near zero. If this ends up in a `y` component of the `to` for a `position` animation, the object will vanish with the console error:

>THREE.Color: Unknown color -0.5 1e-11 -1

The values in the error are the stringified position coordinates. 

The animation works normally if this number notation appears in `x` or `z` but not `y`

- A-Frame Version: 0.3.2, 0.3.0
- Platform/Device: Chromium WebVR 55; Chrome 55
- Reproducible Code Snippet or Demo URL: http://codepen.io/anon/pen/pNQqOR (watch the box)

I saw when searching to see if this had been reported already that `<a-animation>` may be on a deprecation path, so this issue may not be worth addressing

**Comment by mikebolt** [comment]
Here's the problem:

https://github.com/aframevr/aframe/blob/master/src/core/a-animation.js#L378

https://github.com/aframevr/aframe/blob/master/src/utils/coordinates.js#L4

https://github.com/aframevr/aframe/blob/master/src/core/a-animation.js#L382

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/2475 should fix
