### ISSUE TITLE
When adding a-obj-model at runtime, position attribute not respected

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe#2181]
**Description:**
When adding a "a-obj-model" element to the DOM during runtime, the position attribute does not appear to be respected and the resulting model is placed at 0 0 0 instead of the specified position value.

- A-Frame Version: 0.4.0
- Platform/Device: PC / Vive
- Reproducible Code Snippet or Demo URL [highly encouraged]:

This is a snippet from my code (which uses jquery, not tested with vanilla js), note the workaround at the end and the comments. All attributes passed to the appendObject function are strings.

```
       function appendObject(id, file, scale, position, rotation, scale) {
         console.log(position);
         $('<a-obj-model />', {
           id: id,
           class: 'city object children',
           position: position,  // doesn't seem to do anything
           scale: scale,
           rotation: rotation,
           scale: scale,
           file: file,
           src: '#' + file + '-obj',
           mtl: '#' + file + '-mtl',
           appendTo : $('#city')
         });
        document.getElementById(id).setAttribute("position", position); // this does set position 
       }

**Comment by ngokevin** [comment]
I believe this was fixed by not having the default component override the set value.
