### ISSUE TITLE
aframe 0.4.0 via npm install reports wrong version

### ISSUE THREAD

**Issue by nylki** [aframevr/aframe#2185]
**Description:**

- A-Frame Version: 0.4.0
- Platform/Device: Firefox 50.0.2 / Fedora 24
- The `console.log('A-Frame Version:', pkg.version);` in line 64967 of aframe reports version 0.3.2

How to reproduce:

- `npm install aframe`
-  include `<script src="./node_modules/aframe/dist/aframe.min.js"></script>` in your body or head.
- open site in browser and open the console

**Comment by ngokevin** [comment]
See https://github.com/aframevr/aframe/tree/master/dist#release-builds for build information. Include the master or v0.4.0 version instead.
