### ISSUE TITLE
Idea for relative `tick()`ordering.

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2186]
Had an idea for one way of solving the issues of #1564, #1437, and #2147, potentially with a simpler API. Instead of having any sort of global dependency resolution, tick/tock, or custom update cycle for shaders...

```js
// API
sceneEl.addTick(Number order, Function fn);
sceneEl.removeTick(Number order, Function fn);

// Constants
AFRAME.Phase = {
  PRE_TICK: 500,
  TICK: 1000,
  POST_TICK: 1500,
  POST_RENDER: 2000
};

// Usage
sceneEl.addTick(AFRAME.Phase.PRE_TICK + 1, function (t, dt) {
  // ...
});
```

The goal here is that component authors can still hook into the A-Frame scene lifecycle, without adding much complexity to the core library itself. Callbacks could be added by components, shaders, or just global code. 

/cc @ngokevin @wizgrav @dmarcos

**Comment by jeromeetienne** [comment]
i like this idea. i even got an implementation of this. ok it is 2y old and in pure three.js. but it shows how simple the implementation can be.

https://github.com/jeromeetienne/threex.loop/blob/master/threex.loop.js#L114

**Comment by donmccurdy** [comment]
Closing this out as there have been other suggestions and no clear consensus. Currently I'm using something like this for physics, with my own custom system driving the event loop, and that works well for my needs.
