### ISSUE TITLE
Browserify / husky causing issues with A-Frame as dependency

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2187]
My actual build involves Browserify + Karma etc., but simplified steps to reproduce the issue:

1. Install `aframe` as dep:

```shell
npm i aframe
```

2. Create fake test: 

```js
// test.js
require('aframe');
console.log('done');
```

3. Attempt to serve test file:

```shell
browserify test.js -o output.js
```

4. Error:

```
Error: Cannot find module 'envify' from '/Users/donmccurdy/Desktop/test/node_modules/aframe'
    at /Users/donmccurdy/.nvm/versions/node/v6.2.2/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/donmccurdy/.nvm/versions/node/v6.2.2/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/donmccurdy/.nvm/versions/node/v6.2.2/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/donmccurdy/.nvm/versions/node/v6.2.2/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/donmccurdy/.nvm/versions/node/v6.2.2/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/donmccurdy/.nvm/versions/node/v6.2.2/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
```

5. Attempt to debug

```
cd node_modules/aframe
npm i
```

6. [husky](https://github.com/typicode/husky) installs A-Frame's precommit git hook into my parent package, and it runs on future commits. 😐

***

In retrospect, what I should have done was just `npm i envify`, but it would be great if we could remove the need. Is there a way to mark envify as a browserify dependency for production?

***

- A-Frame Version: 0.4.0

**Comment by ngokevin** [comment]
I moved envify to dependencies.

I'm not sure how to fix husky

**Comment by donmccurdy** [comment]
Ok thanks, I'll give that a try. I don't think there's any need to change husky if the Browserify transform dependencies are there by default; running `npm i` inside of a dependency's folder isn't a normal situation at all, AFAIK.

**Comment by ngokevin** [comment]
OK. The envify issue probably justifies a follow up npm release of 0.4.1 or something, will try to plan that.
