### ISSUE TITLE
Using embedded and vr-mode-ui="enabled: false throws cannot read property error

### ISSUE THREAD

**Issue by alexcheninfo** [aframevr/aframe#2198]
**Description:**

- A-Frame Version: 0.4
- Platform/Device: Windows
- Reproducible Code Snippet or Demo URL [highly encouraged]: http://codepen.io/alexcheninfo/pen/YpgjQX

If you use `embedded` and  `vr-mode-ui="enabled: false"` simultaneously, you get: 

`aframe.min.js:103Uncaught (in promise) TypeError: Cannot read property 'classList' of null(…)`

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/2193

**Comment by alexcheninfo** [comment]
@ngokevin Got it. Thanks.
