### ISSUE TITLE
Error in the primitive description doc

### ISSUE THREAD

**Issue by tbalouet** [aframevr/aframe#2204]
In the docs, you declare function extendDeep and then use the function extend, which isn't declared yet, so the code wouldn't work
![image](https://cloud.githubusercontent.com/assets/5400381/21445323/d2ce0708-c8b7-11e6-9ec4-0e66d5edd415.png)

- A-Frame Version:
- Platform/Device:
- Reproducible Code Snippet or Demo URL [highly encouraged]:

**Comment by imgntn** [comment]
looks like this is fixed -- maybe there's an older version in cache? 

https://github.com/aframevr/aframe/pull/2146
![capture](https://cloud.githubusercontent.com/assets/843228/21603277/c5cfa97a-d150-11e6-9a5e-30c620e2e785.JPG)

**Comment by thoragio** [comment]
This issue should be closed. `extendDeep()` is shown correctly in the example (like in the screenshot above from @imgntn).
