### ISSUE TITLE
Unlike normal entities, primitives do not have this.el.sceneEl

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#2205]
**Description:**
Unlike normal entities, primitives do not have this.el.sceneEl

- A-Frame Version: 0.4.0
- Platform/Device: Windows Chrome browser
- Reproducible Code Snippet or Demo URL [highly encouraged]:

compare <a-plane src="..."> to <a-entity material="src:..."> in debugger; missing sceneEl causes texture load failure for example

**Comment by machenmusik** [comment]
IIRC, this was trying to use a-text primitive...

**Comment by machenmusik** [comment]
... although I may be wrong, definitely something I tried using in the holiday gallery I put together

**Comment by machenmusik** [comment]
looks like someone in Slack questions channel is having similar issue witj a-sky, maybe that was it...

**Comment by mkungla** [comment]
@machenmusik can you provide reproducible code/?

**Comment by ngokevin** [comment]
Closing unless we have a reproducible test case
