### ISSUE TITLE
hand/tracked controls may freeze because sometimes invalid time is passed into the tick handler

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#2207]
**Description:**
hand/tracked controls may freeze because sometimes invalid time is passed into the tick handler
in debugging, utils.throttleTick is showing that it sometimes receives nonsensical values for time and delta (negative time -86576060... , delta 9626...) 
- A-Frame Version: 0.4.0
- Platform/Device: Windows Chromium
- Reproducible Code Snippet or Demo URL [highly encouraged]:
e.g. https://aframe.io/aframe/examples/showcase/tracked-controls/

**Comment by imgntn** [comment]
I'm also experiencing this bug with my Vive on Chromium with the tracked controllers.

**Comment by machenmusik** [comment]
latest commit to master should have fixed this for controllers, but not for physics (that would have required #2217)
