### ISSUE TITLE
Bump to Three.js r83

### ISSUE THREAD

**Issue by takahirox** [aframevr/aframe#2212]
**Description:**

Please let me file "Bump to Three.js r83" because `a-mmd` component I'm working on requires r83.

https://github.com/takahirox/a-mmd

**Comment by takahirox** [comment]
It seems like we need to update sound component for r83

**Comment by machenmusik** [comment]
Something seems wrong with this, I am getting complete failure running tests with npm run test:chrome --

```
Chrome 55.0.2883 (Windows 10 0.0.0) ERROR
  Uncaught TypeError: THREE.FileLoader is not a constructor
  at c:/Users/machenmusik/AppData/Local/Temp/src/core/a-assets.js:7:0 <- C:/Users/machenmusik/AppData/Local/Temp/6a19aa98df29983ee4a1b025a0ab1fa9.browserify:62279

Finished in 0.588 secs / 0 secs

SUMMARY:
√ 0 tests completed
```
