### ISSUE TITLE
Trigger re-render AFrame scene from DOM?

### ISSUE THREAD

**Issue by hyperdo** [aframevr/aframe#2218]
Does AFrame support re-rendering from the DOM? In other words, if the DOM is modified (say with Socket.io), can AFrame be triggered to reload the scene with information taken from the DOM? Thanks very much.

**Comment by dmarcos** [comment]
I'm not sure if I understand the question. Short story: yes, changes in the DOM will affect the render of the scene. Long story: The scene is rendered at the refresh rate of the device is presented to (60fps on a normal display, 90 fps on a Vive or an Oculus Rift). Changes on component properties in the DOM will modify the underlying Three.js Object3Ds and will be picked up by the render loop.

**Comment by hyperdo** [comment]
You're right -- my mistake. I made an error in the program and that was the reason why the objects weren't showing up. Sorry for the trouble.
