### ISSUE TITLE
What should coordinate.parse(null) return?

### ISSUE THREAD

**Issue by takahirox** [aframevr/aframe#2220]
**Description:**

coordinates null parse test in `coordinates.test.js` expects return value is `null`,
but it returns `undefined`.

    test('parses null', function () {
        assert.equal(coordinates.parse(null), null);
    });

To be more specific, it returns `defaultVec` if input value is non-parsable
(neither `string` nor `object`).
In the above case, `defaultVec` isn't given then it returns `undefined`.

@dmarcos mentioned returning `null` on input `null` is sensible.

https://github.com/aframevr/aframe/pull/2209#discussion_r93825269

Options in my mind now are...
- returns input  value (just pass  through) on non-parsable input
- returns `null` on non-parsable input
- returns `null` on `null` input and returns `defaultVec` on other non-parsable input
- keep the current impl (so we should modify  coordinates null parse test code)

Any other suggestions?
I'd like to fix the specification and update `coordinates.parse` impl.

- A-Frame Version: 0.4.0
- Platform/Device: any

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/2209 merged
