### ISSUE TITLE
<a-animation> doesn't animate on the Vive

### ISSUE THREAD

**Issue by hyperdo** [aframevr/aframe#2224]
**Description:**
\<a-animation\> doesn't animate on the Vive. When an animation is triggered, the entity teleports to the end location and doesn't animate through.
- A-Frame Version: Master (bleeding edge)
- Platform/Device: HTC Vive
- Reproducible Code Snippet or Demo URL [highly encouraged]:

Suppose we have the following code:
```
<a-entity id="user">
      <a-camera></a-camera>
      <a-entity id="vive-controls-switch">
          <a-entity vive-controls="hand: left"></a-entity>
          <a-entity vive-controls="hand: right" vive-cursor></a-entity>
      </a-entity>
</a-entity>
```
You would expect that when we animate `#user`, the whole bit would animate, like it does on other platforms. However, the animation seems to skip and teleport to the end. What could be causing this?

**Comment by ngokevin** [comment]
This is a known browser issue with Chromium and passing wrong timestamps to requestAnimationFrame.
