### ISSUE TITLE
add warning if entity is appended outside of a-scene

### ISSUE THREAD

**Issue by jsantell** [aframevr/aframe#2225]
**Description:**

It's not possible to add components programmatically to elements that are not yet mounted to the DOM. Discovered in ngokevin/aframe-react#52, if attempting to inject an element that contains components into the DOM, the `this.el.sceneEl` property in the component does not yet exist, causing an error in most components.

- A-Frame Version: 0.4.0
- Platform/Device: Chrome OSX
- Reproducible Code Snippet or Demo URL [highly encouraged]:

```js
var el = document.createElement('a-entity');
el.setAttribute('cursor', '');
document.body.appendChild(el);
```

`Uncaught (in promise) TypeError: Cannot read property 'object3D' of null`

**Comment by ngokevin** [comment]
You should be appending to the scene rather than the document.body. In the aframe-react bug, is that component mounted under the scene?

**Comment by ngokevin** [comment]
Also, yeah we should throw a warning for that

**Comment by jsantell** [comment]
Yes, in the aframe-react bug it is injected within the a-scene entity. Changing the STR to `document.querySelector('a-scene').appendChild(el)` does work in examples I just tried. Maybe it is aframe-react only, but not sure (yet) what in aframe-react could cause this

**Comment by ngokevin** [comment]
OK, repurposing the issue for the warning. Will try to investigate the react side later

**Comment by jsantell** [comment]
Thanks!

**Comment by imgntn** [comment]
seems that the object3D error is related to trying to append the ```cursor``` component -- added the warning but will also open a pull to try to handle the cursor error.
