### ISSUE TITLE
Sound component not triggered when collada model is loaded

### ISSUE THREAD

**Issue by thoragio** [aframevr/aframe#2232]
**Description:**

- A-Frame Version: 0.4.0
- Platform/Device: OS X 10.11.6, Chrome 55.0.2883.95
- Reproducible Code Snippet or Demo URL [highly encouraged]: https://github.com/zeekw/aFrameTests

For more background on this apparent bug, see the [SO post](https://stackoverflow.com/questions/41353368/play-sound-component-with-animation-using-a-frame).

When adding a sound component to an `a-collada-model` entity, the sound is not triggered after loading with an `on: model-loaded` listener, but `autoplay: true` does work.

Does not work:
`<a-collada-model src="#car-dae" sound="on: model-loaded; src: #car-sound">`

Does work:
`<a-collada-model src="#car-dae" sound="src: #car-sound; autoplay: true">`

**Comment by dmarcos** [comment]
Closing because we no longer support collada models and recommend glTF instead.
