### ISSUE TITLE
race condition with reusing material.src

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#2245]
When material.src is reused, possible race conditions may prevent the desired src from being visible.

- A-Frame Version: 0.4.0
- Platform / Device: multiple
- Reproducible Code Snippet or URL:

1. Find an image URL that takes a while to be loaded.
2. Set up a scene with an entity that loads material.src from that URL (directly via src, or indirectly via selector)
3. After material.src is set, but before the image URL finished loading, change material.src to something else (e.g. a canvas)

Expected result - the canvas will remain visible as material.src, and the image load will be ignored.
Actual result - despite material.src referencing the canvas, the image load will overwrite the canvas and remain visible.  In order to make the canvas visible again, some hijinx is required due to another issue I will file separately

**Comment by dmarcos** [comment]
That's because of the asynchrony. If there's a pending request when `src` changes we should ignore the resullt. It should be an easy fix
