### ISSUE TITLE
Try to make core components use only window globals rather than requires

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2258]
**Description:**

Core component source code currently use `require`s. If someone wants to copy/paste/fork a component to modify it to their needs, they'd have to change the `require`s to point to like `window.AFRAME` for utils.

If we make our components use the `AFRAME` global instead of `require`s, we ensure that our components aren't using any internal hidden API, and that they have same privileges as any other component in the ecosystem. It would also make components easier to copy/paste and they'd be able to work in a pure browser context.

**Comment by donmccurdy** [comment]
My vote would be to avoid this, and not determine project structure for the convenience of devs who are new to package managers. It also makes it impossible to preserve private APIs within A-Frame core. Some alternatives:

1. Document (on SO or official docs) "How to customize a component".
2. Write an `angle` utility to create a component by forking an official one.

But I recognize that neither of those is a good solution when then component depends on various utils or helpers.

Do we think this issue applies to many components other than controls (both for camera and tracked controls) ? If not then maybe we revisit some amount of abstraction around the controls api. I could see an option where we take #1248, make that into a new repo like aframevr/aframe-controls, and document how to customize controls for that framework. But #1248 doesn't include a clear story for tracked controls.

**Comment by machenmusik** [comment]
> It also makes it impossible to preserve private APIs within A-Frame core.

Can someone explain why private APIs within A-Frame core are needed, preferably with examples?

> But I recognize that neither of those is a good solution when the component depends on various utils or helpers.

Right, I think part of the idea here is to make utils and helpers exposed non-private, so that nontrivial new component functionality can be developed without having to be in core in order to depend upon private APIs.

**Comment by machenmusik** [comment]
To use a potentially flawed Windows analogy... do we see A-Frame core as Win32 API on which a variety of functionality and components can be developed?  Or as MFC where a framework and components are provided, and more can be created by following the paradigm?

**Comment by ngokevin** [comment]
This would only be for components, which I don't think should have access to private APIs. Using the global would be a way to enforce that, and sort of create separation/less coupling between the components and the core API. 

Yeah, sorry the controls refactor got backlogged. It could be promoted to `aframevr/` org to get it along the way.

**Comment by machenmusik** [comment]
@ngokevin so sounds like aframe non-component is like win32 API (private APIs may be required) and aframe components are like MFC atop public win32 API.  if so, gets my vote at present

**Comment by donmccurdy** [comment]
I don't follow the analogy, but in many projects it is necessary to have private helper methods that are used internally, but not exposed externally. Exposing a public API implies an agreement with developers: that method will not be changed in a backward-incompatible way without appropriate [SemVer](http://semver.org/) version increase, and the more public API surface you have, the harder your public releases become. When that contract is broken, it's hard for third-party developers to keep their packages compatible. Many components in awesome-aframe are already incompatible with 0.4.0... that's fine for now (churn is expected up until 1.0.0) but we'll eventually want to have a fairly stable API.

Everything in `src/utils/*` is exposed as public APIs, and are exposed to anyone as `AFRAME.utils`. This is a good and appropriate way to expose public utilities. If those are the only utilities needed by components, then that's great. Perhaps A-Frame's core components are fortunate enough to not need additional private helper methods; I don't know of any counter-examples.

**Comment by dmarcos** [comment]
If we remove all requires from the core components if forces us moving forward to make public any API, utility library or helper function used by more than one component. More API surface, more liability, harder to provide backwards compatibility, slower to change and innovate if we want... It's something we know pretty well at Mozilla with all the internal APIs that add-ons have been able to rely on.

**Comment by donmccurdy** [comment]
Aside: @ngokevin No problem on the PR, I'm not even convinced it should be in core at this point. Separate repo is worth discussing later though.
