### ISSUE TITLE
Consider putting gltf-model into core?

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2261]
Discussing how best to maintain `gltf-model` with @xirvr; perhaps either (1) merge it into aframe-extras.loaders, or (2) merge it into core.

Advantages of having `gltf-model` in core:

- glTF is (IMO) the most promising asset format for the web. If we want to see that gain traction, I think we need to be willing to treat it as a default early on (even if the popularity isn't there yet).

Disadvantages:

- Animation should be treated as format-agnostic, using THREE.AnimationMixer. Currently the `animation-mixer` component lives in aframe-extras, and it's not clear that we want more animation-related code moving into core. We could ensure that core/gltf-model exposes its animations in a way that is compatible with aframe-extras/animation-mixer.

Further discussion of animation: https://github.com/xirvr/aframe-gltf/issues/9

***

Proposed syntax for any THREE.AnimationMixer-compatible format, including glTF, with animation:

```html
<a-entity foo-model="src: homestar.foo"
          animation-mixer="clip: run"></a-entity>
```

**Comment by ngokevin** [comment]
Yeah, I'd agree with adding `gltf-model` to core. If we need to pull in a way of animating models, we can do that too.

**Comment by xirvr** [comment]
Nice.  I have pretty limited time this next few months, but do think this is super important for 3D web for all the reasons Don mentioned and we all already know :)

@ngokevin how do you suggest we do this?  There's very little in the component itself that's glTF specific, most of what's in the component I made is build tools and demo -- I would assume it's as easy as copy pasting the Collada component and changing a few lines to make glTF part of core?

**Comment by dmarcos** [comment]
How is the adoption of `gltf` so far? What's the status of exporters from popular tools: Blender, Cinema 4D, 3D Studio, Maya... What's the status of the three.js loader? I know that when we tried to use it for our demos everything looked pretty immature @feiss What do you think?

**Comment by ngokevin** [comment]
The common argument is that we help drive the adoption.

**Comment by donmccurdy** [comment]
I'm fairly confident about THREE.GLTFLoader. It was fully re-written over the last 6 months, the code is relatively clean, and both @takahirox and I have been contributing to its maintenance. It's fairly close to supporting all of the official glTF sample models — perhaps by THREE.js r84 or r85. 

There are some converters, I'm not sure how well they work. There's not much available for exporters. My vote would be for us (A-Frame, and THREE.js) to go out on a limb a bit to support that, in the hope that we drive adoption and encourage tooling to catch up.

**Comment by xirvr** [comment]
The command line Collada to glTF converter works quite well, but it's fairly tricky to set up.  There is an online converter that works for testing, but doesn't build to multiple files so binary data (even when not in binary mode) is baked in, making it giant / slow to parse.

Autodesk has an FBX to glTF converter, to my understanding coming out quite soon, which I expect to be pretty strong.  Autodesk also has a new project that is WebGL focused, which I'd be surprised if it didn't integrate glTF soon (Project Play).

Blender has an exporter plugin, but haven't used it -- I've only heard one person trying to use it, and I think they had problems with it.  

All things considered, I think the Collada to glTF converter is worth the headache of getting it running (just like most front-end developers are now used to the permission problems Node initially has when they are not used to a Linux system).

... but confess that I'm biased ;)

**Comment by xirvr** [comment]
Also, figured I'd point out that with Unity, you can make things like this:

[https://vimeo.com/181420338](https://vimeo.com/181420338)
[https://vimeo.com/192071365](https://vimeo.com/192071365)
[https://www.youtube.com/watch?v=tVHH3-bP-fE](https://www.youtube.com/watch?v=tVHH3-bP-fE)

It might be that a run-time focused library (i.e. ThreeJS + AFrame, Babylon, regl) won't catch up to what a compile time library (Unity, Unreal; leveraging Emscripten and soon Web Assembly) -- but if (Three/AFrame) it is to have a chance, the kind of shader, geometry, and animation work in the above three examples needs to be done by a designer and exported in a way the run-time libraries can use them -- trust me, trying to code these is insanity :)

One more side note on adoption, Babylon has support for glTF, and I believe someone is working on an importer for regl as well.

**Comment by donmccurdy** [comment]
@ngokevin @dmarcos thoughts y/n? glad to put together a PR if we want to see how much is involved, should be comparable to other formats though.

**Comment by dmarcos** [comment]
Yes, please go ahead.
