### ISSUE TITLE
"Merge Geometry Test" Console Warnings

### ISSUE THREAD

**Issue by darkwing** [aframevr/aframe#2262]
I'm seeing seemingly hundreds of "components:geometry:warn Geometry merge is only available for `THREE.Geometry` types. Check that both of the merging geometry and the target geometry have `buffer` set to false" errors within this demo, so two things:

1.  We should fix the demo's root issue, obviously
2.  We should consider implementing something like three.js whereby we cut off `console` statements after a given number of executions.

- A-Frame Version: 0.4.0
- Platform / Device: Chrome desktop
- Reproducible Code Snippet or URL:  The `/examples/test/geometry-merging/` demo within the repo

**Comment by mkeblx** [comment]
And, the geometries aren't getting merged, possibly because of a wrong property check (in merging demo the both have buffer=false).

**Comment by ngokevin** [comment]
We've removed mergeTo in favor of doing it manually in three.js (e.g., within a component) when needed. Instanced geometries is an alternative way to achieve the same draw call reductions. Quick resources on merging geometries in three.js:

https://stackoverflow.com/questions/30245990/how-to-merge-two-geometries-or-meshes-using-three-js-r71
http://blog.sandromartis.com/2016/11/16/merging-geometries/
https://stackoverflow.com/questions/36450612/how-to-merge-two-buffergeometries-in-one-buffergeometry-in-three-js
https://threejs.org/docs/#api/core/Geometry

We can provide more resources as we develop/evolve examples and code.
