### ISSUE TITLE
a-scene stats are too dark to read

### ISSUE THREAD

**Issue by mitchallen** [aframevr/aframe#2266]
**Description:**

Create an a-scene with stats (<a-scene stats ...). The text is black on dark gray. This is very difficult to read, especially on mobile devices where the font is smaller.

<img width="322" alt="screen shot 2017-01-10 at 1 10 47 pm" src="https://cloud.githubusercontent.com/assets/122875/21823120/13e86ab6-d737-11e6-810e-9c9eb7d01b0a.png">

- A-Frame Version: 0.4.0
- Platform / Device: Mac Chrome / iOS 
- Reproducible Code Snippet or URL: https://mitchallen.github.io/birdseye.html

**Comment by machenmusik** [comment]
you can also try
https://github.com/chenzlabs/stats-in-vr

**Comment by ngokevin** [comment]
Help wanted to change that text color to white.

**Comment by dmarcos** [comment]
@mitchallen would you like to help to tweak the colors?

**Comment by mitchallen** [comment]
@dmarcos, @ngokevin okay, I'll review the contrib guide and do that tomorrow.
