### ISSUE TITLE
[docs] getting started guide should add disclaimer about codepen that it won't work in VR

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2268]
Until they add the `allowvr` attribute to the iframes

**Comment by yjkimjunior** [comment]
I can add the following disclaimer: 

To get started playing now, open this CodePen example scene.

**Note:** You need to add the **allow-vr** attribute to a-frames to use the Codepen example with WebVR or on your VR device.

**Comment by yjkimjunior** [comment]
I can add the following disclaimer in the Getting Started Guide under Play With CodePen:

CodePen is a playground for front-end web development. We can edit HTML and JavaScript directly in the browser with its text editor, see changes live, and share code snippets. This is a fast way to dive in without having to download or install anything. Check out the official MozVR CodePens and the A-Frame Hello World CodePen:

**Disclaimer:** You need to add the **allow-vr** attribute to a-frames to use the Codepen example with WebVR or on your VR device.

**Comment by ngokevin** [comment]
It's actually CodePen that needs to add that attribute. We just need to say VR mode won't work right now until they add it to their I-Frames.

**Comment by yjkimjunior** [comment]
Oh I see, 

**Disclaimer:** VR mode won't work right now until the`allow-vr` attribute is added to CodePen's I-Frames.

How's that?

**Comment by ngokevin** [comment]
That's great. Some tweaks:

**Note:** VR mode currently won't work until the `allowvr` attribute is added to CodePen's I-Frames.
