### ISSUE TITLE
Initiating A-Frame scrolls document to top

### ISSUE THREAD

**Issue by HeyDonny** [aframevr/aframe#2273]
When `<a-scene>` is created, it scrolls the document to the top of the page. Note that the `embedded` attribute is also set.

- A-Frame Version: 0.4.0
- Platform / Device: Chrome / Firefox
- Reproducible Code Snippet or URL:

The below will create the scene after a 5 second interval. If scrolled to the bottom, the page will jump back to the top on initiation.

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<script src="https://aframe.io/releases/0.4.0/aframe.min.js"></script>
	<style>
		.bottom { 
			position: absolute;
			top: 4000px;
		}
	</style>
</head>

<body>
	<div class="bottom">
		<p>Bottom</p>
	</div>
	<div id="vr-scene"></div>
	<script>
		var initSceneInterval = setInterval(function(){ initScene(); }, 5000); //interval so will slide without interaction as well
		function initScene () {
			var vrScene = document.createElement("a-scene");
			var embedded = document.createAttribute("embedded");
			vrScene.setAttributeNode(embedded); 
			document.getElementById("vr-scene").appendChild(vrScene);
		}
	</script>
</body>
</html>
```

**Comment by ngokevin** [comment]
You're adding an element at runtime which will cause a reflow of the page. I don't think there's anything to be done on the A-Frame side. `<a-scene>` has some CSS rules that come with it, you can override as you need or add styles to your page to prevent it.
