### ISSUE TITLE
[docs] Write guide for "Adding Interactions in VR"

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2274]
**Description:**

We need a guide focused around adding interactions, primarily with tracked controllers in Vive and Touch. This guide will make heavy use of community components including: [aframe-physics-system](https://github.com/donmccurdy/aframe-physics-system) by @donmccurdy and [aframe-super-hands-component](https://github.com/wmurphyrd/aframe-super-hands-component) by @wmurphyrd

Possible guide outline might look like:

1. Adding Tracked Controllers to the Scene (`hand-controls`, `vive-controls`, `touch-controls`)
2. Listening to Tracked Controller Events 
3. Adding a Cursor to Tracked Controllers (https://github.com/bryik/aframe-vive-cursor-component by @bryik )
4. Grabbing Objects (super-hands)
5. Checking for Collisions and Colliding Objects (super-hands)
6. Scaling Objects (super-hands)
7. Adding Physics to Interactive Objects for Throwing and Hitting (super-hands + physics)

Inspiration: https://unity3d.com/learn/tutorials/topics/virtual-reality/interaction-vr

**Comment by imgntn** [comment]
@ngokevin i'm interested in helping out on this.  is there a reference/example guide to base it off of?  thanks!

**Comment by ngokevin** [comment]
**@imgntn is now working on this.**

**Comment by tejalavu96** [comment]
ya i will do it

**Comment by ngokevin** [comment]
https://aframe.io/docs/0.6.0/introduction/interactions-and-controllers.html
