### ISSUE TITLE
Android Black screen in VR mode

### ISSUE THREAD

**Issue by HFrifelt** [aframevr/aframe#2277]
When clicking the "Enter VR" icon (the goggle icon), to enter in VR mode, the screen periodically turns black. The issue seems to occur at random times.

We have tried using both A-Frame version 0.3.0 and 0.3.2., but with no difference in behavior.

Whether it fails (renders black or is successful) I recieve the following errors:

aframe.min.js:281 Uncaught TypeError: Cannot read property 'length' of undefined
at r (aframe.min.js:281)
at M.fireVRDisplayPresentChange_ (aframe.min.js:58)
at HTMLDivElement.s (aframe.min.js:58)

aframe.min.js:149 Uncaught (in promise) DOMException: 
A call to screen.orientation.lock() or 
screen.orientation.unlock() canceled this call.

index.html#/lobby:1 Uncaught (in promise)     
DOMException: screen.orientation.lock() is not available on this device.
The issue seems to vary in occourance depending on device.

Tested on: Samsung Galaxy S6/S6 Edge Nexus 6x One plus 3

Tested on Google Chrome: WebGL activated also tried with WebVR.

- A-Frame Version: 0.3.0 and 0.3.2
- Platform / Device: Android, Samsung Galaxy S6, Samsung Galaxy S6 edge, Nexus 5x
- Reproducible Code Snippet or URL:

<a-scene vr-mode-ui="" fog="type: exponential; color: #AAA; density: 0.00009;">

    <a-assets>
        <video id="video" src=""></video>

        <img id="skybox" src="img/lobby/skybox.jpg" />

        <img id="earth" src="img/lobby/earth.jpg" />
        <img id="sun" src="img/lobby/sun.jpg" />
        <img id="moon" src="img/lobby/moon.jpg" />

        <img id="frame-content" src="img/lobby/frame-content.png" />
        <img id="frame-selected" src="img/lobby/frame-selected.png" />
        <img id="button-play" src="img/lobby/button-play.png" />
        <img id="button-pause" src="img/lobby/button-pause.png" />
        <img id="button-stop" src="img/lobby/button-stop.png" />
        <img id="button-left" src="img/lobby/button-left.png" />
        <img id="button-right" src="img/lobby/button-right.png" />
    </a-assets>

    <a-entity id="lobby-content" visible="true">

        <a-sky src="#skybox" radius="6000">
            <a-animation ease="ease-in-out-sine" dur="200000" repeat="indefinite" attribute="rotation" fill="forwards" from="-240 360 0" to="120 0 0"></a-animation>

            
            <a-sphere src="#sun" color="yellow" position="0 -100 0" rotation="90 0 0" scale="10 10 10"></a-sphere>
            <a-light type="point" intensity="1.5" color="white" position="0 -500 0"></a-light>

            
            <a-sphere src="#moon" color="white" position="0 100 0" scale="5 5 5"></a-sphere>
            <a-light type="point" intensity="0.2" color="white" position="0 500 0"></a-light>
        </a-sky>

        
        <a-sphere src="#earth" position="0 -9.5 0" scale="9 9 9">
            <a-animation ease="ease-in-out-sine" dur="150000" repeat="indefinite" attribute="rotation" fill="forwards" from="5 0 34" to="5 360 34"></a-animation>
        </a-sphere>

        
        <a-entity position="0 2 -25" scale="1.2 1.2 1">
            <a-image src="#frame-content" scale="16 10 0"></a-image>

            
            <a-image class="clickable" button-prev position="-10 0.5 0" src="#button-left">
                <a-animation begin="cursortrigger" end="cursorabort" attribute="material.color" fill="forwards" from="white" to="#19DC19" dur="2000"></a-animation>
                <a-animation begin="cursorabort" attribute="material.color" fill="forwards" to="white" dur="200"></a-animation>
            </a-image>

            
            <a-image class="clickable" button-next position="10 0.5 0" src="#button-right">
                <a-animation begin="cursortrigger" end="cursorabort" attribute="material.color" fill="forwards" from="white" to="#19DC19" dur="2000"></a-animation>
                <a-animation begin="cursorabort" attribute="material.color" fill="forwards" to="white" dur="200"></a-animation>
            </a-image>

            <a-entity position="-3.5 2 0" scale="5 2.5 1">
                <a-image id="frame00" material="opacity: 0;" src="#frame-selected" position="0 0 0.1" scale="1.2 1.4 1">
                    <a-animation begin="focusstart" end="focusend" attribute="material.opacity" to="1" dur="200"></a-animation>
                    <a-animation begin="focusend" attribute="material.opacity" to="0" dur="200"></a-animation>
                </a-image>
                <a-image target id="video00" class="clickable" position="0 0 0.2"></a-image>
            </a-entity>

            <a-entity position="3.5 2 0" scale="5 2.5 1">
                <a-image id="frame01" material="opacity: 0;" src="#frame-selected" position="0 0 0.1" scale="1.2 1.4 1">
                    <a-animation begin="focusstart" end="focusend" attribute="material.opacity" to="1" dur="200"></a-animation>
                    <a-animation begin="focusend" attribute="material.opacity" to="0" dur="200"></a-animation>
                </a-image>
                <a-image target id="video01" class="clickable" position="0 0 0.2"></a-image>
            </a-entity>

            <a-entity position="-3.5 -2 0" scale="5 2.5 1">
                <a-image id="frame02" material="opacity: 0;" src="#frame-selected" position="0 0 0.1" scale="1.2 1.4 1">
                    <a-animation begin="focusstart" end="focusend" attribute="material.opacity" to="1" dur="200"></a-animation>
                    <a-animation begin="focusend" attribute="material.opacity" to="0" dur="200"></a-animation>
                </a-image>
                <a-image target id="video02" class="clickable" position="0 0 0.2"></a-image>
            </a-entity>

            <a-entity position="3.5 -2 0" scale="5 2.5 1">
                <a-image id="frame03" material="opacity: 0;" src="#frame-selected" position="0 0 0.1" scale="1.2 1.4 1">
                    <a-animation begin="focusstart" end="focusend" attribute="material.opacity" to="1" dur="200"></a-animation>
                    <a-animation begin="focusend" attribute="material.opacity" to="0" dur="200"></a-animation>
                </a-image>
                <a-image target id="video03" class="clickable" position="0 0 0.2"></a-image>
            </a-entity>

            <a-image lobby-play-button class="clickable" id="lobby-play-button" src="#button-play" visible="false" position="0 -6.5 0" scale="1.5 1.5 0">
                <a-animation begin="cursortrigger" end="cursorabort" attribute="material.color" fill="forwards" from="white" to="#19DC19" dur="2000"></a-animation>
                <a-animation begin="cursorabort" attribute="material.color" fill="forwards" to="white" dur="200"></a-animation>
            </a-image>
        </a-entity>
    </a-entity>

    <a-camera id="main-camera">
        <a-cursor hackursor color="#05669F">
            <a-animation begin="cursortrigger" end="cursorabort" easing="ease-in" dur="2000" attribute="scale" fill="forwards" from="2 2 1" to="1 1 1"></a-animation>
            <a-animation begin="cursorabort" easing="linear" dur="200" attribute="scale" fill="forwards" from="2 2 1" to="1 1 1"></a-animation>
            <a-animation begin="cursortrigger" end="cursorabort" easing="linear" dur="2000" attribute="material.color" fill="forwards" from="white" to="#05669F"></a-animation>
            <a-animation begin="cursorabort" easing="linear" dur="200" attribute="material.color" fill="forwards" from="white" to="#05669F"></a-animation>
        </a-cursor>
    </a-camera>

    <a-entity visible="false" id="buttons-control-frame" position="0 -4 -4" scale="0.5 0.5 0.5" look-at="#main-camera">
        <a-image src="#frame-content" scale="5 3 5"></a-image>
        <a-image control-button class="clickable" src="#button-stop" position="-0.6 0 6">
            <a-animation begin="cursortrigger" end="cursorabort" attribute="material.color" fill="forwards" from="white" to="#19DC19" dur="2000"></a-animation>
            <a-animation begin="cursorabort" attribute="material.color" fill="forwards" to="white" dur="200"></a-animation>
        </a-image>
        <a-image control-button id="buttons-play-pause" class="clickable" src="#button-pause" position="0.6 0 6">
            <a-animation begin="cursortrigger" end="cursorabort" attribute="material.color" fill="forwards" from="white" to="#19DC19" dur="2000"></a-animation>
            <a-animation begin="cursorabort" attribute="material.color" fill="forwards" to="white" dur="200"></a-animation>
        </a-image>
    </a-entity>

</a-scene>

**Comment by HFrifelt** [comment]
Inside:
<a-scene vr-mode-ui="" fog="type: exponential; color: #AAA; density: 0.00009;">

</a-scene>

Text editor won't make it appear for some reason.

**Comment by dmarcos** [comment]
Have you tried a-frame 0.4.0?

**Comment by HFrifelt** [comment]
For information: it's inside an a-scene, editor just wont allow it for some reason.

@dmarcos: Yes, I've also tried updating to 0.4.0, same problem.

**Comment by dmarcos** [comment]
Do the examples on aframe.io work for you?

**Comment by HFrifelt** [comment]
I just tried to run the showcase HelloWorld on the phone, works perfectly.

**Comment by dmarcos** [comment]
Then there's something wrong with your setup. You have to share your whole document and not only the `a-scene`

**Comment by HFrifelt** [comment]
It's built with Ionic / Angular.js, the scene can run independently, at least the VR mode can. Clicking VR-Mode works 50% of the times, and it's possible to use the Android back button and spam untill it is successful.

The scene I provided is a lobby scene which is a view for itself, I can provide the controller and service it uses, but as far as I can tell, it doesn't actually have anything to do with the VR-mode button.

Can you perhaps be specific in what you would like to see?

**Comment by dmarcos** [comment]
I don't know much a bout Ionic/Angular.js but it seems this is not an aframe bug (since the aframe examples work for you) but something with your integration. I recommend asking the question on stackoverflow  http://stackoverflow.com/tags/aframe/ or use the a-frame slack (some people use angular.js there) https://aframe.io/community/#slack 

I close this but please reopen if this ends up being an a-frame specific problem.
