### ISSUE TITLE
Why is the 0.4.0 version's resolution so bad in VR mode? 

### ISSUE THREAD

**Issue by nick-ye** [aframevr/aframe#2278]
Why is the 0.4.0 version's resolution so bad in VR mode? 
I did not change any rendering parameters! 
**version 0.3.2 is good!** 
Running on iOS 9.2.1 Cordova 4.3.1

 screenshot:
![img_3661](https://cloud.githubusercontent.com/assets/25084319/21899269/9f5a8f08-d92a-11e6-85bb-dea232510a8b.PNG)
![img_3662](https://cloud.githubusercontent.com/assets/25084319/21899270/a05ae330-d92a-11e6-865f-5d608264d7e2.PNG)

**Comment by dmarcos** [comment]
I think this is a dup https://github.com/aframevr/aframe/issues/2008#issuecomment-257905203
