### ISSUE TITLE
Consider allowing catching invalid values from property types, and then don't run lifecycle handlers

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2279]
**Description:**

If an error is thrown from a property type, don't run lifecycle handler method?

```js
schema: {
  foo: {
    parse: function (val) {
      if (!val) { throw new Error('val is required.'); }
    }
  }
}
```

**Comment by dmarcos** [comment]
What would be a more specific example of this? Do not properties have default values?

**Comment by ngokevin** [comment]
Like if we pass a string to the `number` type, we should ensure handlers don't get called if we do `setAttribute('foo', 'numProp', 'sdasfa')`.

**Comment by ngokevin** [comment]
Perhaps too much work, up to developers to make sure the data is good.
