### ISSUE TITLE
`this.el.setAttribute('mixin' , '');` should clear mixins. Currently tries to do queryselector on empty string

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2280]
**Description:**

I want to clear out the mixins component on an entity

[6:08]  
this.el.setAttribute('mixin' , '');

[6:08]  
is throwing an error "'querySelector' on 'Element': 'a-mixin#' is not a valid selector."

[6:09]
any ideas?

**Comment by ngokevin** [comment]
`removeAttribute('mixin')` doesn't also work.

We should also allow `.removeAttribute('mixin', mixinName)`

**Comment by BhuvanaMeenakshi** [comment]
I want to work on this

**Comment by BhuvanaMeenakshi** [comment]
this.el.setAttribute('mixin', this.data.mixin);

Hope this can resolve?

**Comment by dmarcos** [comment]
@BhuvanaMeenakshi Thanks for the interest. Can you open a PR with a test case fixing the issue?

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/2291
