### ISSUE TITLE
`look-controls` as cloned component breaks with `reverse-mouse-drag` — 0.4.0

### ISSUE THREAD

**Issue by evvvritt** [aframevr/aframe#2286]
Hi, I wanted to have a limited view in my app so I cloned the `look-controls` component according to this [SO answer](https://stackoverflow.com/questions/41038973/how-can-i-constrain-rotation-of-an-a-camera-aframe/41150640#41150640) by @ngokevin. But it breaks if `reverse-mouse-drag="true"`

0.4.0
Web / Desktop
[jsfiddle](https://jsfiddle.net/cuebtvLm/3/)

Any thoughts?

**Comment by ngokevin** [comment]
Try: `<a-entity camera cloned-look-controls="reverseMouseDrag: true">` rather than `<a-camera>` which has `look-controls` attached.
