### ISSUE TITLE
Consider exposing panner options on `sound` component.

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2287]
Documentation for [THREE.PositionalAudio](https://threejs.org/docs/index.html?q=positional#Reference/Audio/PositionalAudio).

Specifically, these options might be useful:

| property | default | description |
|---------|-------|----------|
| distanceModel | ~linear~ inverse | `linear`, `inverse`, `exponential` |
| refDistance | 1 | Reference distance for reducing volume as the audio source moves further from the listener. |
| rolloffFactor | 1 | Describes how quickly the volume is reduced as the source moves away from the listener. |
| maxDistance | 10000 | Maximum distance between the audio source and the listener, after which the volume is not reduced any further |

**Comment by wildaces215** [comment]
I am interested in the writing for the documentation for it.

**Comment by dmarcos** [comment]
@wildaces215 you are more than welcome to help

**Comment by takahirox** [comment]
I'm working on this except for documentation.

@donmccurdy 
Why do you think default distanceModel should be linear though
default PannerNode.distanceModel (= THREE.PositionalAudio.distanceModel) is inverse?
https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/distanceModel

**Comment by donmccurdy** [comment]
Oh, good point! `inverse` it is then.

**Comment by takahirox** [comment]
I see, thanks!

**Comment by takahirox** [comment]
@wildaces215 
Panner options has been added.
Do you wanna update the documentation for it? :D

https://aframe.io/docs/0.5.0/components/sound.html

**Comment by BhuvanaMeenakshi** [comment]
I want to work on this

**Comment by gurumukhi** [comment]
Hi @BhuvanaMeenakshi, it seems @wildaces215 is already working on this. If you dont see any updated from @wildaces215 in next few days, you can pick this one, till then feel free to explore other open issues :-)

**Comment by ngokevin** [comment]
I don't think anyone's working on it. It seems a lot of people are just commenting "i want to work on this" on a lot of issues and not doing anything. If people are interested and the issue doesn't seem to be active, I'd just create a PR versus a comment.

**Comment by wildaces215** [comment]
I've get caught up on things it free sorry about the inconvenience

**Comment by ngokevin** [comment]
No worries, not talking about anyone specific :)
