### ISSUE TITLE
Broken .wav link in guide

### ISSUE THREAD

**Issue by AndresCuervo** [aframevr/aframe#2295]
In the [**Adding Audio**](https://github.com/aframevr/aframe/blob/master/docs/guides/index.md#adding-audio) section of the official docs, the following source file link seems to be dead:

https://cdn.aframe.io/basis-guide/backgroundnoise.wav

If this isn't the correct repo for this issue, let me know where it should migrate to!

**Comment by dmarcos** [comment]
@ngokevin has the asset moved?

**Comment by ngokevin** [comment]
I forgot whether or not I added it. I'll get around to updating it.

**Comment by ngokevin** [comment]
Fixed, thanks! Typo in the guide.

It's at `https://cdn.aframe.io/basic-guide/audio/background-noise.wav`
