### ISSUE TITLE
Double-deeply nested dependency not set on DOM (hand-controls -> vive-controls -> tracked-controls)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2296]
**Description:**

1. Go to an example with `hand-controls`.
2. Do `document.querySelector('[tracked-controls]')` in console.
3. Says `null`, but should return entities with `hand-controls`.

Dependency synchronization with DOM works for the first dependency, but not further dependencies.

- A-Frame Version: 0.4.0
- Platform / Device: Desktop
- Reproducible Code Snippet or URL: https://ngokevin.github.io/kframe/scenes/aincraft/

**Comment by dmarcos** [comment]
`tracked-controls` is not a dependency of `vive-controls`. It is set only if there's a vive connected:
https://github.com/aframevr/aframe/blob/master/src/components/vive-controls.js#L138

**Comment by dmarcos** [comment]
If the vive controllers are present you should get something from `document.querySelector('[tracked-controls]')`

**Comment by ngokevin** [comment]
OK, thanks.

**Comment by machenmusik** [comment]
(same with `oculus-touch-controls`)
