### ISSUE TITLE
vive-controls component raising console errors for rotation and material of undefined

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe#2299]
**Description:**
Upon scene init, vive-controls component raises `Uncaught TypeError: Cannot read property 'rotation' of undefined`. Upon button press, vive-controls raises `Uncaught TypeError: Cannot read property 'material' of undefined`

Q are you using the built-in vive controller model?
A yes no change

Q do you inject controls / hands, or declare them a priori in your scene?  are tracked-controls there right off the bat (too early?) or does it wait for vive-controls or oculus-touch-controls to inject them?
A vive controls injected

- A-Frame Version: 0.4.0 (master 18-01-2017 commit #1b9bea1)
- Platform / Device: Windows 10 / Chromium 2016-12-23 build / HTC Vive
- Reproducible Code Snippet or URL: kfarr.github.io/aframe-city-builder

**Comment by machenmusik** [comment]
From Slack 2017/01/22
```kfarr [1:51 PM] 
@mchen fyi removing wasd controls prevents the `Uncaught TypeError: Cannot read property 'rotation' of undefined` however i still see many `Uncaught TypeError: Cannot read property 'material' of undefine` upon button presses```

**Comment by machenmusik** [comment]
@kfarr doesn't seem to happen in normal operation.

are other inadvertent invocations of onButtonUp/Down/TouchStart/TouchEnd/Event providing invalid button names?

what button name is appearing in 
https://github.com/aframevr/aframe/blob/master/src/components/vive-controls.js#L216
in your situation?

**Comment by ngokevin** [comment]
Does this reproduce with latest master? I remember model file names and stuff getting shuffled around and being temporarily broken.

**Comment by kfarr** [comment]
Yes using master. The culprit seems to be things related to vive trackpad. `onButtonTouchStart` and `onButtonTouchEnd` for example

**Comment by dmarcos** [comment]
There were several changes in both the model and the `vive-controls` and this does not seem to reproduce anymore. Please reopen if it's still a problem
