### ISSUE TITLE
Adding aframe to Rails Girls Summer of Code

### ISSUE THREAD

**Issue by gurumukhi** [aframevr/aframe#2301]
To add A-Frame to RGSoC, we need following info:

* Select Tasks or Features on which students can work within 3 months (github issue links).
* Skills required for each the issue.
* Mentors for each issue.

More info - http://railsgirlssummerofcode.org/guide/projects/

Deadline to apply - Jan 31st, 2017.

**Comment by dmarcos** [comment]
Thanks for filing this. @ngokevin @fernandojsg I'm going to put some thought on this. Any ideas? Maybe some features for the inspector or a-painter?

**Comment by vershwal** [comment]
Hey @dmarcos 

The idea list of outreachy is also out yet I cant find a project related to aframe. (https://wiki.mozilla.org/Outreachy)

Are there any pending projects related to aframe/aframe-inspector that can be added to the list?

Regards
Princi Vershwal

**Comment by ngokevin** [comment]
I don't think we have any mentorship spots open at the moment.

RGSOC has closed
