### ISSUE TITLE
Components added to primitives before appending to DOM are ignored.

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2303]
- A-Frame Version: v0.4.0
- Reproducible Code Snippet or URL:

This fails:

```js
var cylinder = document.createElement('a-cylinder');
cylinder.setAttribute('color', '#000000');
cylinder.setAttribute('height', `1.5`);
cylinder.setAttribute('position', `3 1 0`);
scene.appendChild(cylinder);
```

But this works:

```js
var cylinder = document.createElement('a-cylinder');
scene.appendChild(cylinder);
cylinder.setAttribute('color', '#000000');
cylinder.setAttribute('height', `1.5`);
cylinder.setAttribute('position', `3 1 0`);
```

Preferably both would work. Seems like a strange edge case that new users could easily be surprised by; I know the primitive init cycle is a bit troublesome but hopefully we can fix this case.

**Comment by dmarcos** [comment]
Yep, both cases should work

**Comment by takahirox** [comment]
On my environment, both works.

At Hello world example https://aframe.io/aframe/examples/boilerplate/hello-world/

I ran this on console

    var scene = document.querySelector('a-scene')

    var cylinder = document.createElement('a-cylinder');
    cylinder.setAttribute('color', '#888888');
    cylinder.setAttribute('height', '1.5');
    cylinder.setAttribute('position', '3 1 0');
    scene.appendChild(cylinder);

    var cylinder2 = document.createElement('a-cylinder');
    scene.appendChild(cylinder2);
    cylinder2.setAttribute('color', '#888888');
    cylinder2.setAttribute('height', '1.5');
    cylinder2.setAttribute('position', '-3 1 0');

Result

![image](https://cloud.githubusercontent.com/assets/7637832/22179865/13390270-e014-11e6-99c5-5cd34d8d804f.png)

Have I missed something?

**Comment by donmccurdy** [comment]
Hm I filed based on [this conversation](https://aframevr.slack.com/archives/questions/p1485046322874497).

<img width="902" alt="screen shot 2017-01-21 at 11 15 40 pm" src="https://cloud.githubusercontent.com/assets/1848368/22179948/90cba0e2-e02f-11e6-8ce3-f685e2322921.png">

But I can't reproduce the problem either. There were websockets involved, so probably the elements were added after scene init, but even so I can't reproduce this.

**Comment by ngokevin** [comment]
I guess she was on 0.3.2
