### ISSUE TITLE
Low framerate in Firefox nighly with stats UI active

### ISSUE THREAD

**Issue by schaer** [aframevr/aframe#2305]
If the stats UI element is active, the Framerate in Firefox Nighly drops below 10 fps, while Chrome maintains arround 47 fps.

Here is a side by side comparison:

![image](https://cloud.githubusercontent.com/assets/708137/22187166/c55eb8e4-e101-11e6-829f-a6876343cea1.png)

In addition, if the "w" key is pressed in Firefox Nighly, the camera starts to "jump": 

![f616df35-f30e-403f-ac1d-babfe13dda7a](https://cloud.githubusercontent.com/assets/708137/22187270/7b562e9c-e103-11e6-9635-f9d094ebba11.GIF)

I had this behaviour in my project, but this is also repoducable with the aframe hello-world demo.

Chrome: Version 55.0.2883.87 m (64-bit)
Firefox Nighly: Version 53.0a1 (2017-01-22) (32-bit)

- A-Frame Version: 0.4.0
- Platform / Device: Windows 10, Lenovo T560
- Reproducible Code Snippet or URL: https://aframe.io/aframe/examples/boilerplate/hello-world/

**Comment by ngokevin** [comment]
Works for me. Might've been a Nightly regression.
