### ISSUE TITLE
Tilt does´t work in ios touching screen

### ISSUE THREAD

**Issue by goltra** [aframevr/aframe#2306]
I have an ionic2 app with videosphere and in ios  touching vertically the screen I can´t get tilt effect (If I move my device it work). It doesn´t work in android neither. I try it in browser and works ok.

- A-Frame Version: 0.4.0
- Platform / Device: Ios 10 / Iphone 6S
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
What do you mean by `tilt` efect? You say if you move the device it works?

**Comment by goltra** [comment]
I mean, you can move videosphere touching your screen, can you? ... well, if you move right and left the vide move but if you move your finger up and down the video doesn´t move (tilt effect)... I hope I have explaind

**Comment by dmarcos** [comment]
Is there any error in console? does ionic expose the device motion APIs?

**Comment by goltra** [comment]
In the screenshot I have attached you can see warnings and error I have. In fact, last warning appear just when I touch the screen.. 
If I move the device vertical and horizontal movement works ... 

![aframe-error](https://cloud.githubusercontent.com/assets/1634767/22260149/5a538fc6-e268-11e6-8894-ed311266a40f.jpg)

**Comment by goltra** [comment]
@dmarcos you can try accessing with your mobile browser to https://aframe.io/examples/. You can check what I meaning

**Comment by ngokevin** [comment]
> If you move your finger up and down the video 

`look-controls` does not support vertical panning because it'll throw off the orientation axis. If you want to design for non-VR, you'd need to create your own controls to modify the camera.

**Comment by goltra** [comment]
@ngokevin I understand if you are in vr mode tilt doesn't work but if you aren't , in my opinion, it should work ... however could you make me an example about "play" with camera and vertical panning?

Thanks

**Comment by goltra** [comment]
I have implemented this and created a pr here
https://github.com/aframevr/aframe/pull/2315

Please take a look at this.
