### ISSUE TITLE
Screenshot function creates bad quality on Desktop, does not work on iOS

### ISSUE THREAD

**Issue by Maxisoft2** [aframevr/aframe#2308]
**Description: When the screenshot function is called, it creates an image without any anti-aliasing and in a poor resolution, no matter which resolution parameter (width/height) is passed. Also, taking screenshots on iOS 10 is not possible inside Safari / Chrome or Firefox.**

- A-Frame Version: 4.0
- Platform / Device: Any
- Reproducible Code Snippet or URL: http://www.abnahme.mxo.cc/milon/index_desktop.html 

![screenshot-milon q clubvr configurator-1485277659947](https://cloud.githubusercontent.com/assets/24720753/22258045/57e02bc6-e260-11e6-8eb9-2a06902f37d1.png)

**Comment by ngokevin** [comment]
Try `<a-scene antialias="true">`?

screenshot won't be supporting the mobile case. Take it from a desktop.

**Comment by ngokevin** [comment]
width/height parameters now work https://github.com/aframevr/aframe/pull/2474, `antialias="true"` will help.

**Comment by bryik** [comment]
> `antialias="true"` will help.

Does it? Here is a screenshot taken of [a CodePen](https://codepen.io/bryik/pen/pwGgWL) with `antialias="true" screenshot="width: 960; height: 500"`:

![screenshot-codepen - a-frame screenshot width-height-1499908475067](https://user-images.githubusercontent.com/12419712/28146350-286423fe-6747-11e7-889c-37b23b8c0a5a.png)


There is also distortion when taking a screenshot of the CodePen (CodePen's debug mode fixes this), but that's another issue.

**Comment by bryik** [comment]
Being able to set the size of the screenshot to 960x500 is nifty for making [bl.ock](https://bl.ocks.org/-/about) previews, but AA is kind of necessary for this.

I suppose I could take a 3840x2000 screenshot and then resize to 960x500.
