### ISSUE TITLE
Nexus 9 (and other tablets) entering in VR Mode and not using Gyroscope for movement by default

### ISSUE THREAD

**Issue by tinchoforever** [aframevr/aframe#2309]
**Description:**

- A-Frame Version: V4
- Platform / Device: Nexus 9
- Reproducible Code Snippet or URL: http://codepen.io/tinchoforever/pen/ZLyEbj
This on a tablet (nexus 7 or 9) or Ipad should be 
1) Enabling by default devicemotion camera 
2) on vr mode, go full screen. 
On Aframe 2.0, 1) works and 2) says your device doesn't support webvr mode. I have been checking Google WebVr Poly and it works there perfectly. My guess is that this is something inside how Aframe decides to use VR Mode and Gyroscope Control of the Camera by default.

**Comment by tinchoforever** [comment]
here with Aframe 2
http://codepen.io/tinchoforever/pen/ggROwL

**Comment by tinchoforever** [comment]
Aframe 4
![aframe-4](https://cloud.githubusercontent.com/assets/719504/22203403/acb54944-e14b-11e6-81d3-f91fe1efd0aa.gif)
Aframe 2 
![aframe-2](https://cloud.githubusercontent.com/assets/719504/22203404/acb68f66-e14b-11e6-977a-a68580f60e8f.gif)

**Comment by tinchoforever** [comment]
In Aframe 4, I'm only enable to move the camera using touch but no movement.


The expected behavior should be

1. Vr Mode should go to full screen on tablets.
2. Moving camera with Device Motion should be default on tablets too.

**Comment by tinchoforever** [comment]
I've discussed over Aframe Slack about this, we checked over Google WebVr Polyfill and there is no restriction for this on their lastest version. 
Our guess is that there is something where we ask ismobile but on a tablet is not.

An

**Comment by tinchoforever** [comment]
Any help is welcome we are happy to help to create the fix for this issue

**Comment by ngokevin** [comment]
1. If developers want full screen only, and not VR, I would create a fullscreen button that calls requestFullScreen, but I wouldn't put it to A-Frame.
2. Sounds good, if anyone wants to investigate tablet.

**Comment by tinchoforever** [comment]
@ngokevin do you have any idea why 2. was working on Aframe 2.0 but not on Aframe 4.0? Any ideas where to check?

**Comment by donmccurdy** [comment]
@tinchoforever can you tell if `AFRAME.utils.device.isMobile()` is returning `true` on your Nexus 9?

**Comment by tinchoforever** [comment]
Both return **false**
For some reason Aframe 2.0 let us use the accelerometer.

**Comment by tinchoforever** [comment]
Check the examples, now both have the alert with the result.
Aframe 4 : AFRAME.utils.device.isMobile()
Aframe 2 AFRAME.utils.isMobile()

**Comment by tinchoforever** [comment]
What do you think ? @donmccurdy

**Comment by dmarcos** [comment]
@tinchoforever What do you get when you do `navigator.userAgent` on console?

**Comment by tinchoforever** [comment]
Mozilla.50 Linux Android 6.0.1 Nexus 9, Apple WebKit, Chrome 49

**Comment by tinchoforever** [comment]
Mozilla/5.0 (Linux; Android 6.0; Nexus 9 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.105 Safari/537.36

**Comment by dmarcos** [comment]
That's the problem. Your userAgent string does not include the `Mobile` keyword. Apparently not all the Android tablets report the browser as mobile. I found some references to the problem:

https://meta.discourse.org/t/my-android-tablet-was-not-detected-as-a-mobile-device/26734/14

http://stackoverflow.com/questions/5341637/how-do-detect-android-tablets-in-general-useragent

**Comment by dmarcos** [comment]
@tinchoforever Can you try if https://github.com/aframevr/aframe/issues/2382 fixes your issue?

**Comment by tinchoforever** [comment]
@dmarcos testing now... finger cross

**Comment by tinchoforever** [comment]
Amazing, this fix the use of gyroscope but going to full screen mode is not possible :(
@dmarcos

**Comment by dmarcos** [comment]
Any error on console?

**Comment by tinchoforever** [comment]
No Errors.
