### ISSUE TITLE
Image asset is downloaded 3 times from Cloudfront

### ISSUE THREAD

**Issue by RSpace** [aframevr/aframe#2312]
**Description:**

I'm loading an OBJ model with a single color map/texture. I use the `<a-assets>` tag to load both the obj-file and the texture file.

For some reason, the texture is downloaded 3 times. It doesn't hit the cache any of those times:

![aframe_texture_download](https://cloud.githubusercontent.com/assets/5872/22287801/7801dc94-e2f4-11e6-8464-233bd3231774.png)

An additional problem, which made me aware of the issue, this seem to make the model unable to load and render in Safari (desktop and mobile), as it fails with with CORS related error the third time it attempts download the texture:

![image](https://cloud.githubusercontent.com/assets/5872/22287924/0626787c-e2f5-11e6-9fb9-32a90fa72cf6.png)

(It's not a general CORS issue, as it renders fine in other browsers, although the texture is still downloaded three times)

- A-Frame Version: 0.4.0
- Platform / Device: Any (Tested in Chrome, Safari and Firefox)
- Reproducible Code Snippet or URL: http://codepen.io/fabricius/pen/ZLJvoz

**Comment by trowbrsa** [comment]
Upvoting as this issue still exists in 0.5.0 within Chrome, Safari and Firefox.

**Comment by RSpace** [comment]
Good to hear it's not just me. Judging on the number of open issues I don't think the core team will get to this anytime soon then. A PR is probably needed to get this fixed, but I don't have bandwidth to debug and fix the issue at the moment either.

**Comment by ngokevin** [comment]
I was working on it yesterday to try to really improve caching and asset system. I'll be back Tuesday.

**Comment by ngokevin** [comment]
Merging issue with https://github.com/aframevr/aframe/issues/2472
