### ISSUE TITLE
[docs] Write guide on "Deploying and Publishing"

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2317]
**Description:**

Introduction should give a quick context on deploying on the Web. It's free, it's instant, no gatekeepers. Contrast that with native app stores that go through lengthy review processes that may end up in rejections. Publishing a VR experience with A-Frame is the exact same as publishing a web page. Note we want to deploy with `https://` due to WebVR SSL restrictions.

1. Publishing with GitHub Pages
2. Publishing with Neocities
3. Additional Guides for Publishing on AWS, Surge, Heroku, etc.

**Comment by akshit13** [comment]
Hey @ngokevin I can write the guide. I just wanted to know that what format should the doc be in?
Should it be a md file, doc file or any format would work?

**Comment by ngokevin** [comment]
Sorry, I've got a start on this already at https://github.com/aframevr/aframe/pull/2639, but please look over and send any improvements once I have it out :)

**Comment by ngokevin** [comment]
Merging with #2634, guide has been written in https://github.com/aframevr/aframe/pull/2639
