### ISSUE TITLE
[docs] When introducing CodePen, make sure to note that A-Frame script tag should be above the scene rather than in JS tab.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2318]
**Description:**

CodePen's JS tab will append to bottom of body which doesn't work for A-Frame.

**Comment by thoragio** [comment]
Done: https://github.com/aframevr/aframe/pull/2320

Please ask someone with access to the mozvr account on CodePen to change the example to my fork: http://codepen.io/thoragio/pen/jyGeEJ

With the `<script>` tag in the HTML panel, it is abundantly clear. Newbies to CodePen won't know about adding script tags in the gear menu.

**Comment by ngokevin** [comment]
@thoragio can you change the example to your fork? thanks!

**Comment by ngokevin** [comment]
Done!
