### ISSUE TITLE
Rotation component continuously updated on stillstanding camera entity

### ISSUE THREAD

**Issue by i3games** [aframevr/aframe#2322]
The rotation component is continuously updated on a static camera entity (possible performance implications?).

- A-Frame Version: 0.4.0
- Platform / Device: Mac / Firefox 51.0.1
- Reproducible Code Snippet or URL: 

[https://gist.github.com/i3games/80636bb3bf2b2aa7d09569013d1df123](https://gist.github.com/i3games/80636bb3bf2b2aa7d09569013d1df123)

check console.log

The new values for pitch, yaw and roll are the same as the old values (0,0,0).

**Comment by ngokevin** [comment]
Thanks for filing. I do expect the component to update on each frame, *but* the `componentchanged` event shouldn't fire if the data hasn't actually changed. Marked as `help wanted (easy)` to investigate if we are indeed checking that data has been changed.

**Comment by i3games** [comment]
`isSinglePropSchema` in line 202  of `aframe/src/core/component.js` for rotation is true which shortcuts the and-expression, so equality is not tested and the statement never returns. Then in 217 `el.emit('componentchanged', {` happens.

`isSinglePropSchema` is true, because in line 13 of `aframe/src/core/schema.js` 

```
if ('type' in schema) {
    return typeof schema.type === 'string';
}
```
`schema.type` is "vec3" so `typeof schema.type` is "string".

Maybe that points in some direction.
