### ISSUE TITLE
consider adding aframe-point-component to core

### ISSUE THREAD

**Issue by naugtur** [aframevr/aframe#2323]
Hi,

Point is a basic primitive of THREE.js but it's not available as `a-point` in core. I suggest putting it in core.

I'm the author of aframe-point-component
https://github.com/naugtur/aframe-point-component

Let me know if you're interested and I'll make a PR

**Comment by dmarcos** [comment]
Are you thinking about sharing your component in the registry? https://github.com/aframevr/aframe-registry

**Comment by naugtur** [comment]
Yes, sure I am. I'll publish this to registryif you say no. Just wanted to check if you'd consider including it in core, because it seems to me it belongs with sphere, box, circle etc.

I have another component in the making and I'll publish it soon.

**Comment by ngokevin** [comment]
We can have it on the Registry. If it proves useful to many scenes, we could include it.
