### ISSUE TITLE
0.4.1 missing on github?

### ISSUE THREAD

**Issue by jhsu** [aframevr/aframe#2326]
I see that 0.4.1 is published on [npm](https://www.npmjs.com/package/aframe) but I don't see it in the releases page her nor do I see the 0.4.1 tag.

Has the tag just not been pushed? I see that master's [package.json](https://github.com/aframevr/aframe/blob/652f23f3862c2b6622ed03fe0e2b1450ee49c4ab/package.json#L3) states 0.4.0.

Thanks!

**Comment by ngokevin** [comment]
It has an npm specific fix
