### ISSUE TITLE
3D Maps example using AFrame

### ISSUE THREAD

**Issue by AnandiY** [aframevr/aframe#2327]
Has drawing 3D maps using AFrame been tried before ?
If its been done before, can you provide an example code snippet ?

Thanks for your help!

**Comment by donmccurdy** [comment]
[Here's an example using Mapbox](https://github.com/jesstelford/aframe-map) to render the map, and then using that `<canvas/>` element to create a texture. I also recommend the [A-Frame Slack](https://aframe.io/community/#slack) to see what others are working on. :)
