### ISSUE TITLE
feat(raycaster): Raycaster doesn't trigger objects when recursive is set to false (refs: v0.4.0)

### ISSUE THREAD

**Issue by maissani** [aframevr/aframe#2329]
### Environment:
- A-Frame Version: 0.4.0 (refs: 87c934aae6c85ac05af48e3c569db584197fb946)
- Platform / Device: Tested on Chrome
- Reproducible Code Snippet or URL: 
### Editor : 
https://ide.c9.io/maissani/testvr
### Application: 
https://testvr-maissani.c9users.io
### Files: 
https://preview.c9users.io/maissani/testvr
ps: I introduced a console.log line 59310 in aframe-v4.js to reveal intersection value behavior

### Expected Behavior and Issue
Raycaster with recursive true currently working properly. 
Raycaster with recursive false is not working properly: it doesn't trigger on Objects. 
It seems that 
```JavaScript
intersections = this.raycaster.intersectObjects(this.objects, data.recursive)
```
Doesn't  return any intersection when set to false
This bug is probably related to Three.js or not

A simple workAround tho fix this is to set to true whatever ( and then rollback when it's fixed on three.js), and add a conditional check to get only the parrent object (only if he is the origin of intersection )

**Comment by donmccurdy** [comment]
Understand the confusion, but this is how THREE.Raycaster works. `THREE.Object`s do not have geometry: if recursive:false is set the children are ignored, so there's nothing for the raycaster to hit. Neither A-Frame nor Three.js will be able to change this behavior, in all likelihood. 

Your workaround is a good one, though, and perhaps a community component (`shallow-raycaster`?) should be created to allow it more conveniently.

**Comment by donmccurdy** [comment]
Ok, looking at this a bit more, here's a simpler [Codepen demo](http://codepen.io/donmccurdy/pen/EZoLRr). With no nesting whatsoever, and `{recursive:false}`, clicks on the box still don't go through because there's a wrapping THREE.Group around the mesh.

So, there is something to be fixed here. Either:

1. We remove the `recursive` property from the raycaster, because it should basically always be true.
2. Or, we try to implement shallow raycasting in a way that avoids these wrapping elements.

**Comment by machenmusik** [comment]
(is the wrapping that is done always only one level deep?)

**Comment by donmccurdy** [comment]
> (is the wrapping that is done always only one level deep?)

For stock geometries, yes. If there's a `collada-model` or something involved, there's also a good chance that the model introduces its own wrappers.
