### ISSUE TITLE
Custom-specified SDF fonts get inverted

### ISSUE THREAD

**Issue by jonikorpi** [aframevr/aframe#2339]
Every SDF font specified with a URL gets inverted. http://codepen.io/jonikorpi/pen/JELjgM

`font="sourcecodepro"` works normally
`font="https://cdn.aframe.io/fonts/SourceCodePro.fnt"` gets inverted

- A-Frame Version: [master @ 2ac766a95454467566cc001d700857daa4bfcb11](https://github.com/aframevr/aframe/tree/2ac766a95454467566cc001d700857daa4bfcb11)
- Platform / Device: Chrome/macOS
- Reproducible Code Snippet or URL: http://codepen.io/jonikorpi/pen/JELjgM

**Comment by jonikorpi** [comment]
Looks like setting `shader="sdf"` fixes it. (via mchen in Slack) 
Updated the example: http://codepen.io/jonikorpi/pen/JELjgM

**Comment by machenmusik** [comment]
this is due to late breaking changes in msdf support changing default shader to msdf, @ngokevin we should consider changing default shader back to sdf with msdf stock font / url convention detection and override
