### ISSUE TITLE
Entity event 'componentchanged' fires constantly for evt.detail.name === 'rotation'

### ISSUE THREAD

**Issue by chriscar** [aframevr/aframe#2344]
**Description:**
Position change is only firing when position actually changes. The rotation is firing constantly.

- A-Frame Version: 0.4.0
- Platform / Device: Chrome
- Reproducible Code Snippet or URL:

var entity = document.querySelector('a-camera');
entity.addEventListener('componentchanged', function (evt) {
  if (evt.detail.name === 'rotation') {
    console.log('rotation');
  }
});

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe/issues/2322
