### ISSUE TITLE
WebVR emulator triggers fullscreen, not VR presentation.

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2347]
Based on the screenshots and example video, the WebVR emulator ought to emulate both eyes. Clicking the toggle VR button in an A-Frame scene goes fullscreen, instead.

Not sure if that's something about how A-Frame detects the HMD, or if Jaume's examples were using the polyfill instead, but it would certainly be helpful for debugging if the extension were A-Frame compatible.

**Comment by cvan** [comment]
At the very least, I don't think clicking the *VR goggles* icons shoulder enter Fullscreen mode. There were a couple issues filed about adding a separate `Fullscreen` button, tweaking the `Enter VR` button. But, now I see that the tooltip text (even `alt`/`title`) text is now gone (per #1432) - even further misleading folks. Without context, upon loading an A-Frame, it's completely unclear that:

1. If on desktop and mouse-drag controls are enabled, that I can drag my mouse and pan around the scene.
2. I need a VR headset (or a mobile-polyfilled iPhone/Android headset) to interact with the scene.
3. Clicking the icon for the VR googles triggers Fullscreen mode when a browser does not natively support WebVR.

Suggested fixes:

1. A-Frame includes icons, tooltips, and helpful UI hints to indicate the camera controls.
2. A-Frame indicates on the page the system and device requirements to experience "immersive VR."
3. A-Frame exposes additional buttons (or tooltips) based on system/device capabilities.

See this screenshot of Facebook's UI indicators for its embedded 360° video support:

<img width="531" alt="screen shot 2017-02-04 at 3 03 44 am" src="https://cloud.githubusercontent.com/assets/203725/22618004/d60a2a8c-ea86-11e6-9874-0fd6e5efb8af.png">

**Comment by chenhaoact** [comment]
Encountered the same problem，how to triggers enter VR presentation?

**Comment by cvan** [comment]
A-Frame used to display text in a tooltip upon `:hover` of the "Enter VR" (icon of VR headset). I suggest we add some helpful text or graphic (à la the [Facebook example above](https://github.com/aframevr/aframe/issues/2347#issuecomment-277435874)).

**Comment by chenhaoact** [comment]
I use the last version chrome mobile browser，and it works！it seem to some browser does not support the VR presentation any more.

**Comment by cvan** [comment]
> I use the last version chrome mobile browser，and it works！it seem to some browser does not support the VR presentation any more.

Which other browsers are you referring to?

**Comment by ngokevin** [comment]
probably should be filed on the emulator, not sure if it's used much considering look-controls/wasd-controls (or orbit-controls) pretty much does the same thing
