### ISSUE TITLE
A-Frame breaks browser's extension popup

### ISSUE THREAD

**Issue by AmadeusW** [aframevr/aframe#2348]
**Description:**

When developing a web extension, presence of A-Frame's `<a-scene></a-scene>` causes Chrome to make the popup very narrow. It causes Firefox to crash. I've attached a link to minimal repro. 

In my extension I attempted to set the popup's width by setting `width`, `position` and other css styles on `body`, `a-scene` and other elements. In all cases, **Chrome sets width of the popup to its minimum**, yet A-Frame correctly renders the 3D objects in the scene - they're just hard to see in such a narrow window.

- A-Frame Version: 0.4.0
- Platform / Device: Chrome/Firefox on Windows 10
- Reproducible Code Snippet or URL: https://gist.github.com/AmadeusW/478b521e49bc4bbc612c623249a44fa8

- Chrome screenshot
![image](https://cloud.githubusercontent.com/assets/1673956/22581532/843f30ea-e995-11e6-9658-f1579a0faf81.png)
- Chrome screenshot without `<a-scene>`
![image](https://cloud.githubusercontent.com/assets/1673956/22581621/56075b34-e996-11e6-8172-d2659b859ab0.png)

**Comment by ngokevin** [comment]
Can't you override the styles A-Frame sets?

**Comment by AmadeusW** [comment]
Thanks for pointing me in this direction. It turns out that A-Frame sets `html`'s `display: fixed;` which breaks the Chrome popup.

I'm curious why A-Frame needs to change `html` display style. Does it have to do with `iframe` scenarios?

![image](https://cloud.githubusercontent.com/assets/1673956/22620885/2534ba12-eaca-11e6-80d3-26e62934ac0a.png)

**Comment by ngokevin** [comment]
If's for fullscreen purposes. If you want to allow `embedded` scenes `<a-scene embedded>`
