### ISSUE TITLE
Using mergeTo causes uncaught error

### ISSUE THREAD

**Issue by jonikorpi** [aframevr/aframe#2349]
Using mergeTo seems to always cause this error. The merging itself seems to work, but the error breaks other things in my app. 
`Uncaught (in promise) TypeError: Cannot read property 'isPlaying' of null`

http://codepen.io/jonikorpi/pen/EZLQoG
```html
<script src="https://aframe.io/releases/0.4.0/aframe.min.js"></script>

<a-scene>  
  <a-entity 
    id="mergeTarget" 
    position="0 1 -1"
    geometry="primitive: box; height: 1; width: 1; buffer: false; skipCache: true" 
    material="shader: flat; color: red;"
  />
  
  <a-entity 
    id="merger" 
    position="0 1.5 -1"
    geometry="primitive: box; height: 1; width: 1; depth: 1; buffer: false; skipCache: true; mergeTo: #mergeTarget"
  />
  
</a-scene>
```

- A-Frame Version: 0.4.0
- Platform / Device: Chrome/macOS latest
- Reproducible Code Snippet or URL: http://codepen.io/jonikorpi/pen/EZLQoG

**Comment by kennardconsulting** [comment]
Agreed. Seeing the same problem with 0.5.0

**Comment by derhuebiii** [comment]
+1, still getting the same error...

**Comment by KasparasAnusauskas** [comment]
+1 at 0.6.1

**Comment by psthmn-cnd** [comment]
+1 at 0.7.0

**Comment by ngokevin** [comment]
We've removed mergeTo in favor of doing it manually in three.js (e.g., within a component) when needed. Instanced geometries is an alternative way to achieve the same draw call reductions. Quick resources on merging geometries in three.js:

https://stackoverflow.com/questions/30245990/how-to-merge-two-geometries-or-meshes-using-three-js-r71
http://blog.sandromartis.com/2016/11/16/merging-geometries/
https://stackoverflow.com/questions/36450612/how-to-merge-two-buffergeometries-in-one-buffergeometry-in-three-js
https://threejs.org/docs/#api/core/Geometry

We can provide more resources as we develop/evolve examples and code.

**Comment by ngokevin** [comment]
I made a geometry merge component: https://github.com/ngokevin/kframe/tree/master/components/geometry-merger#aframe-geometry-merger-component
