### ISSUE TITLE
feat(component/a-assets/a-mixin): Sould be able to dataset passthrough.

### ISSUE THREAD

**Issue by maissani** [aframevr/aframe#2355]
**Description:**
Currently dataset is not pass through mixin component. 
document.querySelector('#my-first-cat').dataset (See example ) will result to contain only data-name. 

It will be powerfull to pass dataset through mixin (In a lot of case this is helpfull )
```
<a-asset>
            <a-mixin id="cat-mixin" 
            look-at="[camera]" 
            scale=".16 .16 .16" 
            data-eyes="brown"
           data-name="Nyancat" // will be the default data-name and overided by entity dataset
            text="value: miam"
            template="src: template/cat.template; type: html" ></a-mixin>
</a-asset>
<a-entity  id="my-first-cat" mixin="cat-mixin" data-name="Miaous" >

```
- A-Frame Version:
v0.4.0
- Platform / Device:
ALL
- Reproducible Code Snippet or URL:
NONE

**Comment by ngokevin** [comment]
Mixins are just for components. You can have a component set whatever you need. The template component also accepts component names that act as data contaners.
