### ISSUE TITLE
div.a-enter-vr is blocking cursor clicks and grabbing on desktop

### ISSUE THREAD

**Issue by clavis-magna** [aframevr/aframe#2359]
div.a-enter-vr is extending across the width of the window and blocking cursor clicks / cursor grabbing events passing to the scene

- A-Frame Version: 0.4.0 (and also tested on master: 0.4.0 (Date 27-01-2017, Commit #dd9e073))
- Platform / Device: desktop mac/pc Chrome and firefox
- Reproducible Code Snippet or URL: reproducible on https://aframe.io/examples/

![div-a-enter-vr](https://cloud.githubusercontent.com/assets/2109125/22719174/49caa39c-edf8-11e6-9f72-4b7b21899e59.png)

**Comment by clavis-magna** [comment]
overriding the style with an auto width has fixed it in the projects I am working on, but with limited testing across browsers thus far.

`<style>.a-enter-vr {width: auto !important}></style>`

**Comment by dye784** [comment]
I'll take this. I think it could be fixed just by removing the `width` and `height` from `.a-enter-vr`.
