### ISSUE TITLE
Entering then exiting VR mode removes icon on Chromium/Pixel

### ISSUE THREAD

**Issue by bethqiang** [aframevr/aframe#2360]
**Description:**
Entering VR mode, then exiting VR mode (via the small x in the top left corner), causes the enter VR icon to disappear, with the inability to enter VR mode again. Tested with a variety of apps, from our own to A-Frame's examples, with the same result each time.

When testing with [https://aframe.io/examples/](https://aframe.io/examples/), the following errors result when entering VR mode:
```
Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.
AndroidWakeLock.request @ wakelock.js:34
(anonymous) @ wakelock.js:7
module.exports.fireEvent @ index.js:50
(anonymous) @ a-node.js:215
value @ a-node.js:214
enterVRSuccess @ a-scene.js:161
```
and
```
aframe.io/:1 Uncaught (in promise) DOMException: The page needs to be fullscreen in order to call screen.orientation.lock().
```

- A-Frame Version: 0.4.0
- Platform / Device: 12/16/16 Android Chromium build on Google Pixel/Daydream
- Reproducible Code Snippet or URL: No code snippet, but can provide screenshots (?) if desired?

**Comment by Hermanya** [comment]
perhaps muting the video would help

**Comment by bethqiang** [comment]
@Hermanya I'm not sure what you mean - we were never playing video. We were just entering/exiting VR mode on a variety of apps.

**Comment by Hermanya** [comment]
`wakelock.js` is using a video under the hood to keep the device awake. `play()` fails because mobile chrome requires the user to tap on something on the screen in order to play a video. The only way around that is to mute the video, so that it's more like a gif and less annoying to the user.

**Comment by bethqiang** [comment]
So - I guess I'm confused now. Thank you for explaining the errors that were encountered! But, I'm not sure how they tie into the enter VR button disappearing after exiting VR mode, or how that can lead to a solution to it. Judging by what you've said, that's the source of the errors, but it appears the errors may be independent of what we were experiencing then - our main issue was that when you clicked the enter VR mode, and entered, then exited, there was no way to re-enter VR mode (the button disappears) without refreshing the page.

**Comment by ngokevin** [comment]
This should be fixed now that we listen to `onvrdisplaypresentchange` event
