### ISSUE TITLE
System schema bleeds into component schema.

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2365]
When a system and component are registered with the same name, the schemas are merged. Additionally, an instance of the component is created on the scene (as well as an instance of the system). Is my understanding correct, that systems are intended to support configuration on the scene element?

([JSFiddle](https://jsfiddle.net/donmccurdy/wnL5g1ux/))

```html
<a-scene transmogrifier="systemProp2: false">
  <a-entity transmogrifier></a-entity>
</a-scene>
```

```js
AFRAME.registerComponent('transmogrifier', {
  schema: {
    componentProp1: {default: true},
    componentProp2: {default: true}
  },
  init: function () {
    console.log('component.init: ', this.el.tagName, this.data);
  },
  update: function () {
    console.log('component.update: ', this.el.tagName, this.data);
  }
});

AFRAME.registerSystem('transmogrifier', {
  schema: {
    systemProp1: {default: true},
    systemProp2: {default: true}
  },
  init: function () {
    console.log('system.init: ', this.sceneEl.tagName, this.data);
  }
});
```

Result:
![screen shot 2017-02-08 at 6 55 58 pm](https://cloud.githubusercontent.com/assets/1848368/22763009/502914c0-ee30-11e6-8024-8f74ac01de72.png)

- A-Frame Version: v0.4.0
- Platform / Device: All

**Comment by ngokevin** [comment]
Thanks for the detailed issue. There's also https://github.com/aframevr/aframe/issues/1945

**Comment by ngokevin** [comment]
Scene should discern system vs. schema.

**Comment by machenmusik** [comment]
when you say `a-scene transmogrifier=...` you are creating a scene component.  systems are afaik not configurable in that manner...

**Comment by donmccurdy** [comment]
It is intended/documented to configure the system and not create a component (https://aframe.io/docs/0.4.0/core/systems.html#properties) but clearly a component has been created here :)

**Comment by ngokevin** [comment]
Yeah, systems actually are configurable on the scene (although updates currently don't work, needs a bit of a refactor). I'm going to keep poking at shadows if someone wants to look at this.

I think we have the scene wrap `initComponent` (https://github.com/aframevr/aframe/blob/master/src/core/a-entity.js#L339) to do a check to return if it's a component and a system is registered. If everything is OK, call initComponent as normal.

**Comment by machenmusik** [comment]
nowhere on that doc page do I see any example of syntax that would allow for configuring a system in the same manner one would configure. scene component.  so it is not at all clear to me, as a relative newcomer, that there is any expectation to be able to declare `a-scene systemName="systemProps: propValues"`

**Comment by ngokevin** [comment]
Yeah, the documentation is out of date on that part. We can add a section about that.

**Comment by machenmusik** [comment]
so if you are saying you want that behavior, i would strongly suggest namespace prefix e.g. `a-scene system:name="propNames: propValues"` to specify and disambiguate.

**Comment by dmarcos** [comment]
Should we say that components that have a system are not applicable to `a-scene`?

**Comment by ngokevin** [comment]
Yeah. If there's a system, then the scene can't have the component form. There won't be a case where you want both the system and component on the scene because in ECS, the components apply to entities and systems are global like the scene.

**Comment by machenmusik** [comment]
so what is the intended difference (if any) between system and scene component, except that systems get a reference injected into non-scene component instances, and do not need to be explicitly declared?

**Comment by ngokevin** [comment]
They might get extra features later on like lifecycle methods to manage subscribed entities. They are global singletons. They get initialized first. But the API itself is mostly the same as a component.

**Comment by ngokevin** [comment]
I'll take this.
