### ISSUE TITLE
document Entity.appendChild asyncrony in "Using JavaScript and DOM APIs"

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#2366]
- A-Frame Version: 4.1
- Platform / Device: windows
- Reproducible Code Snippet or URL:

```js
var scene = document.querySelector('a-scene');
var entity = document.createElement('a-entity');
scene.appendChild(entity);
entity.setAttribute('position', { x: 0, y: 1, z: 2 });

// returns undefined
console.log(entity.getAttribute('position'));

setTimeout(function() {
  // returns Object {x: 0, y: 1, z: 2}
  console.log(entity.getAttribute('position'));
}, 0);
```

Here's the pen http://codepen.io/caseyyee/pen/MJPamO

**Comment by ngokevin** [comment]
`appendChild` is async so we need to wait for the entity to attach and load.

This is not an issue if code is executed using components as recommended: https://aframe.io/docs/0.4.0/guides/using-javascript-and-dom-apis.html#where-to-place-javascript-code-for-a-frame

A note about this can be added here: https://aframe.io/docs/0.4.0/guides/using-javascript-and-dom-apis.html#adding-an-entity-with-appendchild

**Comment by dmarcos** [comment]
You could also do:
````javascript
var entity = document.createElement('a-entity');
scene.appendChild(entity);
entity.setAttribute('position', { x: 0, y: 1, z: 2 });
entity.addEventListener('loaded', function() {
  console.log(entity.getAttribute('position'));
});
````

**Comment by caseyyee** [comment]
@dmarcos @ngokevin As a note, I was setting up entities in a component and none of the attributes were available in `init` or `play` callbacks either.

So you would have to listen for the loaded event within the component itself to avoid this in the same way?

**Comment by ngokevin** [comment]
If the component depends on other components, you can set a dependency. Although we should maybe prioritize pos/rot/scale components. Try:

```js
dependencies: ['position'],
```

**Comment by caseyyee** [comment]
Alright thanks.   Last thing I will say is that this makes it quite inconvenient when dealing with collections of entities and have to work with them immediately.   Especially for cases where your generating content procedurally.

**Comment by dmarcos** [comment]
position, rotation and scale are `defaultComponents`. They should already initialize before than any other component.

**Comment by ngokevin** [comment]
Such is life when dealing with the DOM. Though the concept of systems is for exactly this, managing collections of entities. Possibly:

```js
AFRAME.registerSystem('foo', {
  handleEntityAdded: function (entity) {
    // Check or do whatever.
  },

  handleEntityRemoved: function (entity) {
    // Check or do whatever.
  }
});
```

Those handlers don't exist yet. But right now, you can manually have entities subscribe to systems:


```js
AFRAME.registerSystem('foo', {
  registerEntity: function (entity) {
    // Check or do whatever.
  }
});

AFRAME.registerComponent('foo', {
  init: function () {
    this.system.registerEntity(this.el);
  }
});
```

**Comment by caseyyee** [comment]
Oh cool.   Alright, that could be a solution.  Thanks!

**Comment by ngokevin** [comment]
#2529
