### ISSUE TITLE
Switch tracked-controls to use specific ID rather than idPrefix once browsers/SteamVR stabilize `OpenVR Gamepad` vs `OpenVR Controllers`

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2371]
**Description:**

https://github.com/aframevr/aframe/pull/2370

**Comment by machenmusik** [comment]
I do wonder whether there will actually be only one specific string, vs. "OpenVR Controller" "OpenVR Gamepad" "OpenVR Flight Stick" "OpenVR Tracker" -- it may be that we end up needing prefix support

**Comment by dmarcos** [comment]
Firefox is going to check the string to be consistent with Chrome

**Comment by dmarcos** [comment]
Using the string to identify controllers cannot be a long term solution. We have to come up with a better way. It might require changes in the Gamepad / WebVR APIs

**Comment by machenmusik** [comment]
agree.  may be a challenge to get consistent values across OS, as not all controllers have same ID namespaces like USB PID/VID

**Comment by ngokevin** [comment]
Closing for now as everything works, the prefix seems a bit more flexible. We can reevaluate strings later on.
