### ISSUE TITLE
Object.Assign causing error in React Native

### ISSUE THREAD

**Issue by LithodomosVR** [aframevr/aframe#2375]
Use of Object.Assign causes React-Native to throw this error:

> One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and no spec compliant.

I see the error itself inside the android emulator upon launch.

- A-Frame Version: 0.5.0
- Platform / Device: OSX / Android Emulator Samsung Galazy S7

```
import 'aframe';
import {Entity, Scene} from 'aframe-react';
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

export default class test2 extends Component {
  render() {
    return (
      <WebView
        source={{uri: '[URL]'}}
        />
    );
  }
}
```

AppRegistry.registerComponent('test2', () => test2);

Apparently the only solution is to revert to earlier versions of React Native. Is there another alternative? Can the same thing be achieved in a different way that won't cause this error?

References:
http://stackoverflow.com/questions/42196398/react-aframe-object-assign-error
https://github.com/facebook/react-native/issues/3634
https://github.com/facebook/react-native/issues/5507

**Comment by ngokevin** [comment]
```
 0
down vote
accepted

After a lot of messing about, I discovered that a lot of my issues were due to trying to test in the simulator.

When running on the device I was able to get an app running the latest version of a-frame working with the latest version of react-native, but only by setting up react-native to recompile the android project from source java, pulling from the current master.

I also had to enable hardware acceleration in the Android.Manifest.

Thanks to Chris Chen for the assist

```
