### ISSUE TITLE
Allow default lights to be disabled.

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2376]
It would be nice to have the option of disabling default lights, without providing my own. For example, lighting and shadows can be baked into textures.

Proposed syntax:

```html
<a-scene light="enableDefaultLights: false">

  <!-- ... -->

</a-scene>
```

**Comment by ngokevin** [comment]
`defaultLightsEnabled: false` sounds good (`*enabled` for consistency)
