### ISSUE TITLE
The screenshot component doesn't save the projection type as equirectangular in EXIF metadata

### ISSUE THREAD

**Issue by Utopiah** [aframevr/aframe#2386]
**Description:** The screenshot component doesn't save the projection type as equirectangular in EXIF metadata.

- A-Frame Version: 0.4.0 and above
- Platform / Device: all
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

**Comment by dmarcos** [comment]
We would have to write the exif header in JS. I actually wrote a parser / writer in the past (https://github.com/mozilla-b2g/exif-parser) but It might be overkilling to make it a dependency of aframe core

**Comment by Utopiah** [comment]
Reached the same conclusion, too heavy for that very specific use case, wondering if someone has a lighter solution.

**Comment by dmarcos** [comment]
If you want to do it in browser you have to be able to parse and write exif data. You can always download and add the meta data offline (http://www.sno.phy.queensu.ca/~phil/exiftool/)

**Comment by Utopiah** [comment]
Yes it's precisely what I did before cf https://twitter.com/utopiah/status/831496563780378625 so... in case others stumble upon the same issues:

1. `<ctrl>+<alt>+<shift>+s`
1. `exiftool -ProjectionType="equirectangular" myscreenshot.png`

Optionally if for Facebook
1. `convert myscreenshot.png myscreenshot.jpg`
