### ISSUE TITLE
Unable to start a-frame for local development 

### ISSUE THREAD

**Issue by sankasan** [aframevr/aframe#2387]
**Description:**

- A-Frame Version: 0.5.0
- Platform / Device: Linux (Solus)
- Reproducible Code Snippet or URL:
  * Followed these steps: https://github.com/aframevr/aframe#local-development
  * Try to run a-frame which results in an error: `npm run start`

```
$ npm run start

> aframe@0.5.0 start /data/Projects/a-frame/aframe
> npm run dev


> aframe@0.5.0 dev /data/Projects/a-frame/aframe
> npm run build && cross-env INSPECTOR_VERSION=dev node ./scripts/budo -t envify


> aframe@0.5.0 build /data/Projects/a-frame/aframe
> mkdirp build/ && npm run browserify -- --debug -t [envify --INSPECTOR_VERSION dev] -o build/aframe.js


> aframe@0.5.0 browserify /data/Projects/a-frame/aframe
> browserify src/index.js -s 'AFRAME' -p browserify-derequire "--debug" "-t" "[envify" "--INSPECTOR_VERSION" "dev]" "-o" "build/aframe.js"

[0000] info  Server running at http://172.16.1.89:9000/ (connect)
[0001] info  LiveReload running on 35729
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch examples ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/data/Projects/a-frame/aframe/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/data/Projects/a-frame/aframe/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/data/Projects/a-frame/aframe/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/data/Projects/a-frame/aframe/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/data/Projects/a-frame/aframe/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/data/Projects/a-frame/aframe/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 4.9.7
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! aframe@0.5.0 dev: `npm run build && cross-env INSPECTOR_VERSION=dev node ./scripts/budo -t envify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aframe@0.5.0 dev script 'npm run build && cross-env INSPECTOR_VERSION=dev node ./scripts/budo -t envify'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aframe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && cross-env INSPECTOR_VERSION=dev node ./scripts/budo -t envify
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aframe
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aframe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/Projects/a-frame/aframe/npm-debug.log

npm ERR! Linux 4.9.7
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! aframe@0.5.0 start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aframe@0.5.0 start script 'npm run dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aframe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aframe
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aframe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/Projects/a-frame/aframe/npm-debug.log
```

**Comment by donmccurdy** [comment]
Looks a lot like this error: http://stackoverflow.com/questions/34662574/node-js-getting-error-nodemon-internal-watch-failed-watch-enospc

I don't know if the accepted answer will work on Solus. If that is the problem, perhaps we can exclude some directories (\*cough\* node_modules) from the filesystem watch?

**Comment by sankasan** [comment]
The accepted answer works. After upping my inotify max watches I was able to run ```npm start``` and with active reloading and nodejs running stable.

For future reference this is the command used. You probably can also use ```npm dedupe``` to reduce the number of files that Grunt wants to keep an eye on. 

```echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p```

**Comment by beautifulmind** [comment]
Did not work for me:

sh: 1: mkdirp: not found

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! aframe@0.5.0 build: `mkdirp build/ && npm run browserify -- --debug -t [envify --INSPECTOR_VERSION dev] -o build/aframe.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the aframe@0.5.0 build script 'mkdirp build/ && npm run browserify -- --debug -t [envify --INSPECTOR_VERSION dev] -o build/aframe.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aframe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdirp build/ && npm run browserify -- --debug -t [envify --INSPECTOR_VERSION dev] -o build/aframe.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aframe
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aframe
npm ERR! There is likely additional logging output above.
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path npm-debug.log.2343658631
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.2343658631'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.2343658631']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.2343658631' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/aframe/npm-debug.log


I tried after executing the suggested command by @donmccurdy 

Regards.

**Comment by donmccurdy** [comment]
@beautifulmind looks like a permissions issue in your case, perhaps this? http://stackoverflow.com/a/16151707/1314762 

(based on the `npm ERR! Error: EACCES: permission denied` line.)

**Comment by beautifulmind** [comment]
Tried with changing the ownership & with root, but the issue still persists.
