### ISSUE TITLE
Add a way of hiding the "Enter VR" button via query-string param

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#239]
`http://localhost:9000/examples/cubes/?ui=0` or `http://localhost:9000/examples/cubes/?hide_ui=1` or something

Useful for when you want to `<iframe>` an A-Frame scene and perhaps want to enable some other method of entering VR - or you may not not even want the user to view the scene in VR.

**Comment by ngokevin** [comment]
I have pending work to move VR Mode UI to `vr-mode-ui` component where they can do

`<a-scene vr-mode-ui="enabled: false">`

But I can make it check querystring too.

**Comment by ngokevin** [comment]
Accidentally closed during merge

**Comment by dmarcos** [comment]
We now hide the ui via the component configuration. Is this still an issue?

**Comment by ngokevin** [comment]
Depends on the iframe use case if it's possible to have the button within the iframe be able to trigger VR, or whether we would need an outside button postmessage into the iframe. I don't know much about the constraints of iframe + entering VR to say for sure

**Comment by ngokevin** [comment]
ui=false

**Comment by trentontri** [comment]
Just in case anyone else is looking for the right syntax to show/hide the Enter VR "goggles" icon:
`<a-scene vr-mode-ui="false"> </a-scene>`

**Comment by blurymind** [comment]
> vr-mode-ui="false"

doesnt work :)

**Comment by dmarcos** [comment]
> 
> 
> > vr-mode-ui="false"
> 
> doesnt work :)

I recommend [checking docs for updated API](https://aframe.io/docs/1.2.0/components/vr-mode-ui.html#sidebar). It is `<a-scene vr-mode-ui="enabled: false">`
