### ISSUE TITLE
Cursor component doesn't have implementation for remove() function

### ISSUE THREAD

**Issue by codechikbhoka** [aframevr/aframe#2391]
**Description:**

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by donmccurdy** [comment]
Copied from Slack:

<img width="987" alt="screen_shot_2017-02-15_at_9 37 56_pm" src="https://cloud.githubusercontent.com/assets/1848368/22983322/bb394598-f36f-11e6-995a-aaa2dc5b2a55.png">

^There is no actual `cursor` component there, but regardless we should implement the `remove()` function. Just detaching the entire element should work in the case above.

**Comment by codechikbhoka** [comment]
These are my init and remove functions which worked for me. Basically I have removed the listeners in the remove() function. 

  init: function () {
    // this.id = Math.floor((Math.random() * 100000) + 1);
    // console.log("init cursor " + this.id);
    var cursorEl = this.el;
    var canvas = cursorEl.sceneEl.canvas;
    this.fuseTimeout = undefined;
    this.mouseDownEl = null;
    this.intersectedEl = null;

    // Wait for canvas to load.
    if (!canvas) {
      cursorEl.sceneEl.addEventListener('render-target-loaded', this.init.bind(this));
      return;
    }

    // Attach event listeners.
    this.binderMouseDown = this.onMouseDown.bind(this);
    this.binderMouseUp = this.onMouseUp.bind(this);
    this.binderRaycasterIntersection = this.onIntersection.bind(this);
    this.bindeRaycasterIntersectionCleared = this.onIntersectionCleared.bind(this);

    canvas.addEventListener('mousedown', this.binderMouseDown);
    canvas.addEventListener('mouseup', this.binderMouseUp);
    cursorEl.addEventListener('raycaster-intersection', this.binderRaycasterIntersection);
    cursorEl.addEventListener('raycaster-intersection-cleared', this.bindeRaycasterIntersectionCleared);
  },

  remove: function () {
    // console.log("remove cursor " + this.id);
    var cursorEl = this.el;
    var canvas = cursorEl.sceneEl.canvas;
    canvas.removeEventListener('mousedown', this.binderMouseDown);
    canvas.removeEventListener('mouseup', this.binderMouseUp);
    cursorEl.removeEventListener('raycaster-intersection', this.binderRaycasterIntersection);
    cursorEl.removeEventListener('raycaster-intersection-cleared', this.bindeRaycasterIntersectionCleared);
  },

**Comment by dmarcos** [comment]
@codechikbhoka thanks. do you want to open a PR?

**Comment by donmccurdy** [comment]
i can grab this unless someone has started

**Comment by dmarcos** [comment]
sure
