### ISSUE TITLE
Camera Y position off entering VR second time on Oculus Rift in Chrome

### ISSUE THREAD

**Issue by RSpace** [aframevr/aframe#2394]
**Description:**

1.  Go to an A-Frame example with a floor. https://ngokevin.github.io/kframe/components/text/examples/vaporwave/ is a good example.
2. Go into VR with the Rift. Observe how floor is at expected level.
3. Go out of VR and back into VR. Observe how floor is now at head level.

Looking at `document.querySelector('a-scene').camera.el.getAttribute('position')` clearly shows that the camera has a Y position at the correct head height the first time I enter VR, but that it has a Y position just above or below 0 the second time I enter VR.

I have to reload the page before I again get the floor positioned correctly, and again it's only the first time I enter VR it has the correct position.

I'm pretty sure this is an A-Frame bug and not a WebVR API or polyfill bug, as https://webvr.info/samples/XX-vr-controllers.html doesn't have the problem I describe. I rarely see this problem with the Vive, but it has happened a few times.

- A-Frame Version: 0.5.0
- Platform / Device: Windows 10, Chromium VR Feb 1 2017 build, Oculus Rift CV 1 with touch

**Comment by machenmusik** [comment]
If you set user height to 0 on the camera does the problem go away?

**Comment by machenmusik** [comment]
does this codepen exhibit the problem?

http://codepen.io/machenmusik/pen/QdewNZ

**Comment by RSpace** [comment]
@machenmusik Thanks for taking a look and sorry I've been slow to get back. I've upgraded to newest Chromium VR from Feb 17, but the issue remain:

* Changing the user height to 0 doesn't fix the problem
* The code pen does indeed have the problem. The first time I go into VR "Hello world" is at floor height as expected. The second time and subsequent times it is at head height.

I have a camera rig entity wrapping the camera entity, I've added a crude "reset camera" shortcut on the space bar in my app, which looks like this:

```
  // Press Space to reset camera view
  onKeyDown (event) {
    const resetPosition = { x: 0, y: 1.8, z: 0 }
    if (event.keyCode === 32) {
      const cameraPosition = this.cameraEl.getAttribute("position")
      const adjustedPosition = {
        x: resetPosition.x - cameraPosition.x,
        y: resetPosition.y - cameraPosition.y,
        z: resetPosition.z - cameraPosition.z
      }
      this.rigEl.setAttribute("position", adjustedPosition)
    }
  }
```

So now the camera is moved up 1.8 meters which is roughly my height, and I can go in and out of VR as many times as I want and the scene stays at the same height/Y position.

The same cannot be said for the X and Z position, but that seems to be an inherent problem with the WebVR API and Oculus SDK roomtracking, because non A-Frame demos like the WebVR roomscale example also has this problem - so out of scope for this issue.

I have a nagging suspicion that these positioning issues _could_ be related to the fact that the Rift has a sensor that automatically takes the headset in and out of VR. For now, the only way to get roomscale A-Frame with the Rift positioned correctly is to stand in the middle of the tracked space before putting on the Rift headset, and to reload the page or reset the camera using a wrapper when going into VR subsequent times.

**Comment by machenmusik** [comment]
interesting. if it still happens when user height is zero, that would seem to point the finger at @ngokevin's save/restore camera pose functionality... perhaps that is breaking the vr camera when it tries to restore a bad pose.

**Comment by RSpace** [comment]
So how do we fix this? And why does the Rift have this problem, and the Vive doesn't? There must be a difference in how they report the position - where would I even start to debug that?

**Comment by machenmusik** [comment]
My current guess is that it is a difference in timing behavior on entry into and exit from VR, especially with the Rift's automatic entry/exit on vrdisplayactivate -- I believe you mentioned that it does happen with Vive but much less often, which is consistent with my personal observations.

First workaround is to add a configurable property to disable the write in https://github.com/chenzlabs/aframe/blob/master/src/components/camera.js#L99

**Comment by machenmusik** [comment]
So from experimenting, a potentially promising fix would be to apply any manual offsets not to the THREE camera itself, but rather to the parent THREE Group that is added by A-Frame.  I will not be in a position to try this strategy until the weekend

**Comment by machenmusik** [comment]
Looking a little more closely, I can't currently verify with actual HMD, but:

The first time one enters VR, this line has never fired
https://github.com/aframevr/aframe/blob/master/src/components/look-controls.js#L215
and so the HMD offset applied will be the true HMD position.  However, it does not appear that `previousHMDPosition` is reset to have similar behavior the next time one enters VR.

It appears that `calculateHMDPosition` is called regardless of whether actually presenting in VR, and it is not clear to me whether one can expect correct values from THREE.VRControls when not presenting in VR.

So the two questions I have for the `look-controls` implementers are:
- Should `look-controls` have an `exit-vr` listener that zeroes `previousHMDPosition` for consistent behavior?
- Should `calculateHMDQuaternion` and `calculateHMDPosition` be called when not presenting in VR?

**Comment by RSpace** [comment]
Yes, I do see it occasionally on the Vive, maybe 1 out of 20 times I enter VR, and always when the page hasn't been reloaded since VR was last entered.

From my own testing, I'm pretty sure that A-Frame never modifies the Three.JS camera position inside or outside of VR, but always the camera entity. And the coordinates coming from the HMD are also applied to the entitiy, not to the Three.JS camera position which stays (0, 0, 0).

Makes sense that it's a difference in timing behaviour, at least if the coordinates coming from the HMD are applied relatively and not absolutely. (Again, where would I look for this? The WebVR polyfill?) If they are applied relatively, and the camera is offset *after* we have entered VR and started getting coordinates from the HMD, we would see an issue like this.

Would love to hear @dmarcos and @ngokevin 's insights on this, as they are main implementers of `look-controls`.
