### ISSUE TITLE
A-Frame Dev Sync Meeting Agenda (Hangout) 1th of March 9 AM PST

### ISSUE THREAD

**Issue by mkungla** [aframevr/aframe#2395]
**This issue opens following discussion:**  
**Would it be useful to have scheduled A-Frame hangouts/meetups for collaborators.**

Take-away from our Skype call and discussion (15th Feb), following questions were raised and best way to stress these is to have open discussion here. We need to determine whether we need or can gain something from such hangouts and what benefits that would bring for A-Frame release life-cycle. Currently A-Frame development discussions take place in [slack](https://aframe.io/community/#slack), under github [issues](https://github.com/aframevr/aframe/issues) and some face-to-face which has so far proven to be fairly productive in general and therefore questions and discussion here are to cover only the extra values what such meetups could bring. We reserved [9:00 am - 10:00 am Wed, Mar 1 2017](http://bit.ly/2l8YagC) to have our first hangout however date and time may change! After all goal of this issue here is also to determine format, schedule, agenda, time for first hangout.

**Questions to be answered**

- **What would be primary objectives for such hangouts**
take-away proposals from our session
  - Focus small pre selected subset of targets for upcoming release
  - Having productive and organized discussion about the roadmap
  - Discuss high priority issues
  - Discuss open pull requests
  - Discuss  short term goals of A-Frame e.g next version
  - Discuss long term goals of A-Frame e.g v1.0.0
  - Discuss features/issues to drop from milestone
  - ...

- **How often should we have such hangouts**
proposal was once a month

- **What would be the duration of the session**
proposal was 1 hour

- **What would be the agenda**
Agenda should be fixed here as result of open discussion .
  -  one of the ideas was to pick 5 topics before hangout and assign each topic to different person who leads the subject to be covered within 10 minutes during the session. these 5 topics can be anything specific issue, PR feature etc.

- **What would be the best weekday and time for it**
This is totally open and we should find the week day and time so that it would be possible to join as many interested participants as possible.

**Waiting for your proposals, ideas, suggestions and everything else related to the topic.**

**Comment by kfarr** [comment]
One suggestion for a topic: what are the goals for the impact that A-Frame has, outside of code base deliverables? For example, we would like to enable x number of web developers who have no prior 3D/VR experience to be able to rapidly prototype applications; or y number of useable A-Frame projects are built, or support for A-Frame on z devices. It doesn't need to be this specific to start, but it'd be very helpful even to have a basic discussion. The outcome of this discussion would be actionable items that regional advocates can implement to drive them forward, such as meetups or hackathons around topic  x, y, or z, and for a basic agreed upon mechanism to measure the progress of these efforts.
