### ISSUE TITLE
Fonts don't load when using aframe.min.js

### ISSUE THREAD

**Issue by jbreckmckye** [aframevr/aframe#2403]
**Description:**

When I develop locally using `aframe.min.js`, it doesn't look as though any of the SDF fonts get loaded. When I switch to `aframe-master.min.js`, the fonts are fetched by XHR. 

This confused me a little when first developing. Does this file need to be patched / updated?

- A-Frame Version: `aframe-v0.5.0.min.js` in `110055d`.
- Platform / Device: all browsers
- Reproducible Code Snippet or URL:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>A-Frame Demo</title>
    <script src="js/aframe.min.js"></script>
</head>
<body>
    <a-scene auto-enter-vr="display:all">
        <a-text
                id="textPrimitive"
                position="0 1 -4"
                align="left" anchor="left" width="5"
                value="anchor='left' (default align) 123456789012345678901234567890123456789012345678901234567890">
        </a-text>

        <a-entity
                position="0 2 -4"
                geometry="primitive: plane; width: 5"
                material="color: #333333"
                text="color: white; anchor: center; font: sourcecodepro;
                  value: anchor='center' (default align) SourceCodePro 123456789012345678901234567890123456789012345678901234567890"
        ></a-entity>

        <a-entity
                position="0 3 -4"
                text="color: white; baseline: top; anchor: right; width: 5; font: aileronsemibold;
                  value: anchor='right' baseline='top' (default align) Aileron-Semibold 123456789012345678901234567890123456789012345678901234567890"
        ></a-entity>

        <a-entity
                position="0 4 -4"
                text="color: white; align: left; width: 5; font: exo2semibold;
                  value: align='left' (default anchor) Exo2SemiBold 123456789012345678901234567890123456789012345678901234567890"
        ></a-entity>

        <a-entity
                position="0 5 -4"
                text="color: white; align: center; width: 5; font: kelsonsans;
                  value: align='center' (default anchor) KelsonSans 123456789012345678901234567890123456789012345678901234567890"
        ></a-entity>

        <a-entity
                position="0 6 -4"
                text="color: white; align: right; width: 5; font: monoid;
                  value: align='right' (default anchor) Monoid 123456789012345678901234567890123456789012345678901234567890"
        ></a-entity>

        <a-entity
                position="0 7 -4"
                geometry="primitive: plane; width: 8; height: auto"
                material="color: #0000FF"
                text="color: white; align: center; font: https://cdn.aframe.io/fonts/DejaVu-sdf.fnt;
                  value: a-plane align:center (anchor:align) DejaVu width 8 1234567890123456789012345678901234567890">
        </a-entity>

        <a-sky color="#222"></a-sky>
    </a-scene>
</body>
</html>
```

**Comment by machenmusik** [comment]
The font data is not contained within the aframe JS, they are loaded via CDN.

You raise a good point / question of whether the default font should be fully embedded, but doing that may increase the size of JS file as well as penalizing those that only want to use custom fonts.

**Comment by jbreckmckye** [comment]
@machenmusik - it wasn't that I expected the script to directly embed the font file; rather that I expected the script to fetch the font by AJAX, like the `master` bundle. I assume this is the intended behavior whatever the release.

**Comment by machenmusik** [comment]
if you are loading from file system, there may be a security permissions issue.
are you using a local server e.g. `npm start`? 

see this codepen which works with aframe.min.js:
http://codepen.io/machenmusik/pen/rjXNmq

**Comment by machenmusik** [comment]
per https://github.com/aframevr/aframe#builds ...

```To use the latest stable build of A-Frame, include aframe.min.js:

<head>
  <script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script>
</head>```

**Comment by jbreckmckye** [comment]
@machenmusik I was operating the page from a local webserver, yes. I didn't see any permissions issues in the console - in fact, the Chrome network tab showed no outbound XHRs for fonts at all.

In the end, I just used the stable 0.5.0 build. Might want to regenerate / destroy the other package, though.

**Comment by machenmusik** [comment]
I have never used the dist/aframe-v0.5.0.min.js file, not sure it is built correctly... @dmarcos @ngokevin?
When you said aframe.min.js, I thought you meant https://aframe.io/releases/0.5.0/aframe.min.js which seems to work fine as shown in codepen.

**Comment by ngokevin** [comment]
Can you provide the web console output using the broken build?

**Comment by jbreckmckye** [comment]
I cannot replicate the issue any longer.

See this jsbin - https://output.jsbin.com/becumezaya/1 - I'm pulling in the version of `aframe-v0.5.0.min.js` that was committed with the [0.5.0 release](https://github.com/aframevr/aframe/commit/110055d70ec0fa870ea566b9705406498431ab54#diff-374fe7cddd9a8e5ffec5bb33cc6f4c18) (#110055d). The fonts render absolutely fine, and are fetched in according to the network panel.

I'm really at a loss to explain my problem. The only thing that occurs to me is that I am working with a rather poor network connection locally - perhaps the font pngs just weren't coming back in a timely fashion?

I've seen delays in font rendering before - is there a way to make A-Frame wait for font assets before rendering? Would adding them as `a-asset-item`s work?

**Comment by ngokevin** [comment]
Cool. Yeah, adding `<a-asset-item>` should work.
