### ISSUE TITLE
feat(component/a-assets): Double-loading & XHR side Effects on events.

### ISSUE THREAD

**Issue by maissani** [aframevr/aframe#2404]
**Description:**

Hi bro's
Today, an another tricky question. 
I notice, asset managment system trigger for each asset ( img , video ....) an another XHR request making impossible to check each asset loading state
In extenso: 2 times img xhr make the first img ( dom element ) having complete state to true whereas the img is not complete. 
The second fact is that it makes 2 load from 2 initiator making event handling on loading state and ready state wrong anytime. 
2 solutions: Let dom handle Xhr's Requests for IMG and VIDEOS and then update three.js texture with img or video blob (making partial video stream possible ).
You will probably have to listen to DOMMutations on a-assets
The second one is to create diffrents Events for video and img loading and complete and attach those events on elements, but it won't correct Double Loading ( Thx to Aframe Asset Managment System ).

Cordialy, 
An Aframe Lover.

- A-Frame Version: 0.5.0 
- Platform / Device: All Platforms
- Reproducible Code Snippet or URL:
No need to have a complex reproduce, just put multiple img elements into a-asset and then look the network graph, also try to catch loaded events :).

**Comment by ngokevin** [comment]
Duping with https://github.com/aframevr/aframe/issues/2472

I have looked at this issue a couple times, but will fix soon, it's an important bug
