### ISSUE TITLE
Enable origin trials so aframe site works on Chrome

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#2405]
https://github.com/jpchase/OriginTrials/blob/gh-pages/developer-guide.md

**Comment by dmarcos** [comment]
I submitted a token request

**Comment by RSpace** [comment]
You should probably wait with adding the token until A-Frame has been fixed to work with WebVR in mobile Chrome. See https://github.com/aframevr/aframe/issues/2444.

**Comment by cvan** [comment]
@RSpace saw [your comment](https://github.com/aframevr/aframe/issues/2444#issuecomment-297645014) in issue #2444, thanks.

I did some tests, and when the `chrome://flags#enable-webvr` flag is enabled, the A-Frame examples do work for me with mobile Chrome (release channel M56 + M57) and Chrome Canary ("nightly" builds). Let me know if you're seeing something else. Thanks!

**Comment by jsantell** [comment]
Seeing [some issues](https://github.com/googlevr/webvr-polyfill/issues/199) here with regard to Chrome with native WebVR API on (via origin trials) where getVRDisplays() hangs and the polyfill does not polyfill.
