### ISSUE TITLE
Pool component creates the pool twice

### ISSUE THREAD

**Issue by clavis-magna** [aframevr/aframe#2407]
the pool component is creating the pool of entities twice. 

in init and in the update that runs after init. 

`if (oldData.mixin !== data.mixin || oldData.size !== data.size)` (line 43)  is returning true and triggering a second pool to be created. (I think because oldData has no value on this first run of update?)

- A-Frame Version: 0.5.0, 0.4.0
- Platform / Device: desktop browser tested
- Reproducible Code Snippet or URL: aframe/examples/test/pool (checking the pages html will confirm 20 'laser' entities instead of 10)

**Comment by dmarcos** [comment]
Good catch!
