### ISSUE TITLE
IDEA: add inline help into the data scheme for component/system

### ISSUE THREAD

**Issue by jeromeetienne** [aframevr/aframe#2409]
I think it would be nice if we could add a inline help into the data scheme for component/system. Thus devs can describe how to use each data field of their components and making them easier to reuse by others devs.

The format of the help string may be plaintext or markdown.

usecase: Thus one can easily extracts it. e.g. to be display in the inspector. to play with a component from the inspector is very nice to learn

usecase 2: automatic generation of documentation. e.g. we autogenerate a markdown output, and then copy that directly a github README.md

**Comment by ngokevin** [comment]
Unfortunately, that would increase the size of the JS. It's easier for now to document and read it externally on the READMEs, which the Inspector can one day consume if we enforce and curate the format for the README. Auto-generated documentation usually adds more maintenance work while producing less friendly docs.
