### ISSUE TITLE
Flesh out the Contributing Guidelines

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#241]
See [our `CONTRIBUTING.md`](https://github.com/MozVR/aframe/blob/master/CONTRIBUTING.md).

For inspiration, [three.js'](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md) is pretty good.

**Comment by cvan** [comment]
We should also describe `dev` (bleeding edge) vs. `master` (stable) à la https://github.com/aframevr/aframe-core/issues/702#issue-122857808

**Comment by cemkod** [comment]
Is the new CONTRIBUTING.md good enough? Any other concerns?

**Comment by ngokevin** [comment]
Good enough to close. We can modify if we want later.
