### ISSUE TITLE
processPropertyDefinition() should normalise the default value

### ISSUE THREAD

**Issue by delapuente** [aframevr/aframe#2412]
If the type is explicitly given or inferred, the normalisation procedure of a schema property should also normalise its default value making it pass through the `parse` function. This would allow using the attribute string representation as the default value (see bug #2410)

- A-Frame Version: master
- Platform / Device: all
- Reproducible Code Snippet or URL:

```html
<script>
  AFRAME.registerComponent('test', {
    schema: { v: {type: 'vec2', default: '1 1'} }
  });
</script>
<a-scene>
  <a-entity test></a-entity>
</a-scene>
<script>
  document.addEventListener('DOMContentLoaded', () => {
    var e = document.querySelector('a-entity');
    var def = e.components.test.schema.v.default;
    var shouldBeTrue =
      JSON.stringify(def) === JSON.stringify(e.getAttribute('test').v);
    console.log('Are equal?', shouldBeTrue);
  });
</script>
```

**Comment by dye784** [comment]
Cool. Will work on this one.

**Comment by ngokevin** [comment]
We now do a warning https://github.com/aframevr/aframe/issues/2511 if the default value doesn't match the type rather than trying to force parse. Thanks Damon!
