### ISSUE TITLE
what's `<a-scene>` ???

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [aframevr/aframe#2416]
what's this ? a custom element ?

```
<a-scene>
```

**Comment by donmccurdy** [comment]
@xgqfrms-GitHub welcome! Yes, it is a custom element based on [newer web APIs](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements). Much of A-Frame's syntax involves using elements like `<a-entity />` or attributes like `<a-entity foo bar />` to create relationships between [THREE.js](https://threejs.org/) objects. For example, `<a-scene />` is closely related to [THREE.Scene](https://threejs.org/docs/?q=scene#Reference/Scenes/Scene).

The [FAQ](https://aframe.io/docs/0.5.0/introduction/faq.html) and [Slack](https://aframe.io/community/#slack) are good options for learning more.

**Comment by xgqfrms-GitHub** [comment]
Thanks for your reply!
