### ISSUE TITLE
Clean way to detect inspector?

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2419]
Within a component, I'd like to check whether the inspector is active (for example, to disable pointerlock APIs, pause a web worker, etc.). Is there a good way to check that?

If not, a proposal:

```js
if ( sceneEl.is('editing') ) { ... }
```

**Comment by fernandojsg** [comment]
Currently you can do it by checking:
```
AFRAME.INSPECTOR && AFRAME.INSPECTOR.opened
```

**Comment by donmccurdy** [comment]
Excellent, thanks! That's working nicely.
