### ISSUE TITLE
Visually clean up (or remove) the Templates examples

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#242]
They're [quite](http://mozvr.github.io/aframe/examples/templates/boxes-inlined.html) [ugly](http://mozvr.github.io/aframe/examples/templates/lots-inlined.html). And the [subdirectory](http://mozvr.github.io/aframe/examples/templates/) could probably go too.

**Comment by ngokevin** [comment]
I think these examples and the subdir are gone.

**Comment by cvan** [comment]
solved by #338
