### ISSUE TITLE
Consider to move optimised serialisation logic from A-Frame inspector to A-Frame

### ISSUE THREAD

**Issue by delapuente** [aframevr/aframe#2422]
A-Frame inspector logic to export an entity (currently inside the [getClipboardRepresentation()](https://github.com/aframevr/aframe-inspector/blob/4a442d0ca566f7435519c090254d7bd8fb3a1c50/src/actions/entity.js#L142) action) could be simplified if optimisations based on removing implicit components and default values are in A-Frame. This way, the representation which depends on A-Frame entity internals is decoupled from the inspector.

**Comment by ngokevin** [comment]
I think it's fine to not move that complexity into A-Frame. The complexity is the result of trying to have an Export feature that tries to turn runtime code into source code, which is messy.
