### ISSUE TITLE
how to toggle switch the gyro

### ISSUE THREAD

**Issue by Super-Meng** [aframevr/aframe#2441]
i want to not use gyro ,just touch the moble to control the vr,
so how to toggle the gyro....

请问如何关闭陀螺仪、重力感应等东西，只使用手势来控制aframe
英文渣求救各路大神..

**Comment by ehsangazar** [comment]
I found this one related to my issue as well,
I want an ability to toggle the gyroscope on mobile or at least a feature to disable it,
How can I do it? I search entire website/issues and none of them seems working
