### ISSUE TITLE
WebVR Origin Trial breaks "cardboard mode" in Android Chrome

### ISSUE THREAD

**Issue by RSpace** [aframevr/aframe#2444]
**Description:**

When I add a WebVR origin trial token to my A-Frame application, the "cardboard mode" mode partly breaks. I still get a stereo image rendered, but the rotation of the phone is not translated to rotation in VR. As a result, the image is "stuck" in cardboard mode and the VR experience is broken.

I suspect this is related to some of the `isMobile()` checks in `look-controls` and elsewhere. It seems like A-Frame hasn't been updated to accommodate regular phones supporting the WebVR API yet.

Examples - must be opened in Chrome 56 on an Android phone to see the issue (enter VR mode):

- _Without_ the origin trial token (WebVR API is _not_ used): https://viewer.cimmerce.com/test/hello_world_regular.html
- _With_ the origin trial token (WebVR API _is_ used): https://viewer.cimmerce.com/test/hello_world_origin.html

Though these examples use A-Frame 0.5.0, my own app uses the newest master version of A-Frame, and has the same issue. I'd be happy to submit a PR, but I think some discussion is needed on how WebVR API support on phones should be handled going forward.

- A-Frame Version: 0.5.0
- Platform / Device: Chrome 56 on Android 6 (Samsung Galaxy S6)

**Comment by ngokevin** [comment]
We can force enable WebVR through the browser config on mobile to test, right?

**Comment by RSpace** [comment]
Yes, if I, in Android Chrome, enable WebVR at chrome://flags and visit
https://aframe.io/examples/ the issue is immediately appearant.

**Comment by RSpace** [comment]
I have just tested the A-Frame examples and my own A-Frame 0.5.0 app with Chrome 58 for Android with WebVR enabled in chrome://flags: It works!

I get a prompt to install Google VR Services when I enter the page, and after installing that, I can switch to "real" WebVR mode from the browser. Rendering is still not on par with the old "fake" WebVR mode, but hopefully the Chrome team is working on that.
