### ISSUE TITLE
Animation of hand-controls not playing

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#2445]
Some times it plays but it does not play the animation in reverse. Sometimes they get stuck in a pose. Probable causes: Models update, three.js update (maybe the animation API has changed)...

**Comment by ngokevin** [comment]
On Firefox Nightly, the first animation always plays smoothly. But then subsequent animations are instant / snap / don't interpolate smoothly.

Another issue I have is the poses get stuck until I manually push the trigger back to its resting state. I feel after you release the trigger, the button value isn't completely at `0`. But at a value close to 0. We need to introduce a threshold.

**Comment by machenmusik** [comment]
> I feel after you release the trigger, the button value isn't completely at 0. But at a value close to 0. We need to introduce a threshold.

Thresholding probably belongs in browser, but could probably be done in component as workaround.  Was doing this to synthesize touches, sounds like it may be needed to generate real button presses?
https://github.com/aframevr/aframe/blob/master/src/components/oculus-touch-controls.js#L178
(Assuming you mean Touch here, but not Vive?)

> The models are also a bit too bright. They look flat-shaded. Maybe we can make the material less shiny / reflective / darker?

I agree that less shiny would be better; can/should someone with better modeling chops change them to GLTF as well?

**Comment by ngokevin** [comment]
RE: Threshold. I meant for the Vive trigger. When I released, it wasn't all the way released, like it'd be 0.01mm off from the full resting state, so I had to pull it up to trigger a triggerup.

**Comment by machenmusik** [comment]
oh ok - so you want to steal the oculus-touch code and also apply threshold to buttons then?

**Comment by ngokevin** [comment]
Yeah, maybe...just a tiny threshold for what button value determines an event vs. 0 and 1.

**Comment by ngokevin** [comment]
Firefox will handle the setting of the threshold now.

**Comment by ngokevin** [comment]
I'm looking at this now. Here's a recording for tracked-controls example if you want to reproduce.

[recording.json.zip](https://github.com/aframevr/aframe/files/904156/recording.json.zip)
