### ISSUE TITLE
Cursor/Raycaster not listen on manual visibility changes

### ISSUE THREAD

**Issue by dominicrico** [aframevr/aframe#2447]
**Description:**

- A-Frame Version: 0.5.0
- Platform / Device: Mac / Chrome latest
- Reproducible Code Snippet or URL:

If I'm changing the visibility of an entity having children (ex. a-box,...)  the cursor is not able to click if the entity is set to visible.

Cursor
```
<a-cursor raycaster="recursive:true; objects: a-entity[visible='true'] *"  ... >
    ...
</a-cursor>
```

Entity
```
<a-entity visible="false">
    <a-box widht="2" height="2" depth="2" ...></a-box>
</a-entity>
```

Changing the visibility via JS and setAttribute('visible', 'true') no click events will be triggered.

Thank you for your help!

**Comment by ngokevin** [comment]
You can manually refresh the raycaster with `el.components.raycaster.refreshObjects()`. Can you re-post this answer to StackOverflow? Thanks!

**Comment by dominicrico** [comment]
Perfect! Thank you!
