### ISSUE TITLE
mergeTo fails with dynamic creation and positioned/rotated geometries

### ISSUE THREAD

**Issue by kennardconsulting** [aframevr/aframe#2459]
**Description:**

When creating entities dynamically, if you attempt to merge them, they appear to take their world position/rotation rather than their parent position/rotation.

Here's an example. I create two sets of merged geometries. One is done manually in the HTML. Even though it is embedded inside a positioned/rotated parent, it works fine.

The other set of merged geometries is created dynamically. I have tried to mimic the manual HTML exactly. However you can see that the second box in the set, rather than being embedded inside the first in the set, is positioned 1m to the right. I believe it is getting this from the world co-ordinates.

- A-Frame Version: 0.5.0
- Platform / Device: Chrome desktop
- Reproducible Code Snippet or URL:

```
<html>
<head>
	<script src="aframe-v0.5.0.min.js"></script>
	<script>
		AFRAME.registerComponent( 'dynamic', {
			init: function() {
				this.data.tick = 0;
			},
			tick: function() {
				this.data.tick++;
				if ( this.data.tick === 10 ) {
					var target2 = document.createElement( 'a-entity' );
					target2.setAttribute( 'id', 'target2' );
					target2.setAttribute( 'geometry', 'primitive: box; buffer: false; skipCache: true' );
					target2.setAttribute( 'color', 'green' );
					this.el.appendChild( target2 );
				}

				if ( this.data.tick === 20 ) {
					var target2Merge = document.createElement( 'a-entity' );
					target2Merge.setAttribute( 'geometry', 'primitive: box; buffer: false; skipCache: true; mergeTo: #target2' );
					target2Merge.setAttribute( 'rotation', '0 45 0' );
					this.el.appendChild( target2Merge );
				}
			},
		} );
	</script>
</head>
<body>
	<a-scene>
		<a-entity rotation="45 0 0" position="-1 0 0">
			<a-entity id="target1" geometry="primitive: box; buffer: false; skipCache: true" material="color: red"></a-entity>
			<a-entity geometry="primitive: box; buffer: false; skipCache: true; mergeTo: #target1"
				rotation="0 45 0"></a-entity>
		</a-entity>

		<a-entity rotation="0 0 0" position="1 0 0" dynamic>
		</a-entity>
	</a-scene>
</body>
</html>
```

**Comment by ngokevin** [comment]
We've removed mergeTo in favor of doing it manually in three.js (e.g., within a component) when needed. Instanced geometries is an alternative way to achieve the same draw call reductions. Quick resources on merging geometries in three.js:

https://stackoverflow.com/questions/30245990/how-to-merge-two-geometries-or-meshes-using-three-js-r71
http://blog.sandromartis.com/2016/11/16/merging-geometries/
https://stackoverflow.com/questions/36450612/how-to-merge-two-buffergeometries-in-one-buffergeometry-in-three-js
https://threejs.org/docs/#api/core/Geometry

We can provide more resources as we develop/evolve examples and code.
