### ISSUE TITLE
mergeTo fails to update clipping plane

### ISSUE THREAD

**Issue by kennardconsulting** [aframevr/aframe#2461]
**Description:**

In the example below, I create some boxes dynamically (you have to look down, step back to see them). The right-hand ones are merged with the leftmost one.

When using WASD to move around (and mouse to look) notice that as soon as the leftmost box goes out of frame the other boxes _also disappear._ It's as if the clipping calculation has (correctly) determined that the leftmost box no longer needs to be drawn, but then also stops drawing the others.

At a guess, perhaps the bounding dimensions of the merged group are still considered to be the same as the bounding dimensions of the first box?

**BONUS BUG:** in this example, the number of boxes that appear seems to be related to how quickly you start looking around (i.e. bring them into frame). If you wait a few seconds you get all 10. If you start moving immediately you may only see 3 or 4.

- A-Frame Version: 0.5.0
- Platform / Device: Chrome desktop
- Reproducible Code Snippet or URL:

```
<html>
<head>
	<script src="aframe-v0.5.0.min.js"></script>
	<script>
		AFRAME.registerComponent( 'dynamic', {
			init: function() {
				this.data.tick = 0;
			},
			tick: function() {
				this.data.tick++;
				if ( this.data.tick === 1 ) {
					var target2 = document.createElement( 'a-entity' );
					target2.setAttribute( 'id', 'target' );
					target2.setAttribute( 'geometry', 'primitive: box; buffer: false; skipCache: true' );
					target2.setAttribute( 'color', 'green' );
					this.el.appendChild( target2 );
				}

				if ( this.data.tick % 10 === 0 && this.data.tick >= 10 && this.data.tick < 100 ) {
					var target2Merge = document.createElement( 'a-entity' );
					target2Merge.setAttribute( 'geometry', 'primitive: box; buffer: false; skipCache: true; mergeTo: #target' );
					target2Merge.setAttribute( 'position', ( this.data.tick / 5 ) + ' 0 0' );
					document.querySelector( 'a-scene' ).appendChild( target2Merge );
				}
			},
		} );
	</script>
</head>
<body>
	<a-scene>
		<a-entity dynamic>
		</a-entity>
	</a-scene>
</body>
</html>
```

**Comment by ngokevin** [comment]
We've removed mergeTo in favor of doing it manually in three.js (e.g., within a component) when needed. Instanced geometries is an alternative way to achieve the same draw call reductions. Quick resources on merging geometries in three.js:

https://stackoverflow.com/questions/30245990/how-to-merge-two-geometries-or-meshes-using-three-js-r71
http://blog.sandromartis.com/2016/11/16/merging-geometries/
https://stackoverflow.com/questions/36450612/how-to-merge-two-buffergeometries-in-one-buffergeometry-in-three-js
https://threejs.org/docs/#api/core/Geometry
We can provide more resources as we develop/evolve examples and code.
