### ISSUE TITLE
mergeTo doesn't work with a-obj-model

### ISSUE THREAD

**Issue by kennardconsulting** [aframevr/aframe#2463]
**Description:**

Even though the `geometry` component appears to try and merge meshes, `mergeTo` seems to fail when trying to merge two `a-obj-model` entities.

- A-Frame Version: 0.5.0
- Platform / Device: Chrome desktop
- Reproducible Code Snippet or URL:

In this example, the second chair is not visible.

````
<html>
<head>
	<script src="aframe-v0.5.0.min.js"></script>
</head>
<body>
	<a-scene>
		<a-assets>
			<a-asset-item id="chair-obj" src="chair.obj"></a-asset-item>
		</a-assets>
		<a-obj-model id="firstChair" geometry="buffer: false; skipCache: true" material="color: red" src="#chair-obj"></a-obj-model>
		<a-obj-model geometry="buffer: false; skipCache: true; mergeTo: #firstChair" src="#chair-obj" position="0 0.1 0"></a-obj-model>
	</a-scene>
</body>
</html>
````

**Comment by kennardconsulting** [comment]
Here is the chair model used in the example.

[chair.zip](https://github.com/aframevr/aframe/files/822998/chair.zip)

**Comment by ngokevin** [comment]
We've removed `mergeTo` in favor of doing it manually in three.js (e.g., within a component) when needed. Instanced geometries is an alternative way to achieve the same draw call reductions. Quick resources on merging geometries in three.js:

- https://stackoverflow.com/questions/30245990/how-to-merge-two-geometries-or-meshes-using-three-js-r71
- http://blog.sandromartis.com/2016/11/16/merging-geometries/
- https://stackoverflow.com/questions/36450612/how-to-merge-two-buffergeometries-in-one-buffergeometry-in-three-js
- https://threejs.org/docs/#api/core/Geometry

We can provide more resources as we develop/evolve examples and code.

Note it probably only worked with geometry component before, not with a-obj-model.
