### ISSUE TITLE
obj-model dependency injects material component

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2464]
**Description:**

- A-Frame Version: 0.5.0
- Platform / Device: Chrome 56.
- Reproducible Code Snippet or URL:

Scenario: I have a simple component that does a thing to its host mesh. If the mesh is available at load, it applies then. If not, it waits for `object3dset`.

```html
<a-entity obj-model="obj: foo.obj; mtl: foo.mtl;" doer-of-things></a-entity>
```

```js
module.exports = AFRAME.registerComponent('doer-of-things', {
  init: function () {
    const mesh = this.el.getObject3D('mesh');

    if (!mesh) {
      this.el.addEventListener('object3dset', this.init.bind(this));
    }

    mesh.traverse(function(node) {
      // does things
    });
  }
});
```

Somewhat surprisingly, `mesh` is set from the beginning, and the warning `Material component properties are ignored when a .MTL is provided` *always* appears. This seems to be because `obj-model` depends on `material`, the `material` component gets added, and creates a Mesh for itself.

If I redesign `doer-of-things` to allow the underlying mesh to change, the problem goes away, but maybe there's enough of a gotcha here to be worth fixing. Ideas:

1. Does the `material` component need to create an empty mesh? Could it just hang onto a material reference until a mesh appears?
2. Should `obj-model` be allowed some sort of "optional" dependency on `material`, such that if the component isn't provided, it won't be added?

**Comment by ngokevin** [comment]
I think both 1 and 2 are valid.

1. We can change material to wait for `object3Dset` if it doesn't exist rather than `getOrCreateObject3D('mesh').

2. We can move the `material` initialization into the handlers. Detect if there's a material trying to be set, and wait for it.

**Comment by donmccurdy** [comment]
I think fixing (1) would be helpful, in any case. What do you mean by 'the handlers'? 

I'm also occasionally writing custom components to override properties on models (e.g. `envMap`, which PBR models expect but don't provide). Might be benefits to allowing the `material` component to override properties of existing materials rather than creating a new THREE.Material from scratch, but maybe out-of-scope or better to prototype as a separate component.

**Comment by ngokevin** [comment]
Lifecycle handlers*

**Comment by donmccurdy** [comment]
Another example of the problem:

http://stackoverflow.com/questions/43371917/how-do-i-access-the-attributes-of-buffergeometry-from-an-an-a-frame-component/43373818?noredirect=1#comment73820235_43373818

^Developer gets `el.getObject3D('mesh')` and, because it's a dummy mesh with empty geometry, it throws errors that a real model would not. E.g. `mesh.geometry.attributes.position.array` throws because `position` is undefined. IMO having a dummy mesh created by the material is unwanted behavior.
