### ISSUE TITLE
Components don't hold a reference to a system instance

### ISSUE THREAD

**Issue by belen-albeza** [aframevr/aframe#2465]
**Description:**

- A-Frame Version: 0.5
- Platform / Device: Mac OS X / Nightly

Components don't have a reference to their system at `this.system`, it's a reference to a function named `newSystem`. This happens when the system is registered _before_ the component is registered.

Changing the order of registration (so component goes first, system seconds) yields the correct behavior.

**Comment by dye784** [comment]
Hmm...not sure what you mean. I did this and they do `console.log` a similar object `NewSystem` containing `sceneEl`.
```
      AFRAME.registerSystem('system-before', {
        schema: {},
        init: function () {}
      });

      AFRAME.registerComponent('system-before', {
        init: function () {
          console.log('THIS SYSTEM BEFORE', this.system);
        }
      });

      AFRAME.registerComponent('system-after', {
        init: function () {
          console.log('THIS SYSTEM AFTER', this.system);
        }
      });

      AFRAME.registerSystem('system-after', {
        schema: {},
        init: function () {}
      });
```

**Comment by feiss** [comment]
Something related happened to me, when trying to cache a material via a system that holds it
```javascript
AFRAME.registerSystem('specialmaterial', {
  init: function () {
    var src = document.querySelector('#envmap').getAttribute('src');
    this.sceneEl.systems.material.loadTexture(src, {src: src}, setMap.bind(this));
   
    this.material = new THREE.MeshStandardMaterial({ color: 0x2b2b2b });

    function setMap (texture) {
      this.material.envMap = texture;
      this.material.needsUpdate = true;
    }
  }
});

AFRAME.registerComponent('specialmaterial', {
  init: function () {
    this.el.addEventListener('model-loaded', this.setup.bind(this));
  },
  setup: function (evt) {
    var material = this.system.material;

    evt.detail.model.traverse( function( node ) {
      if (node instanceof THREE.Mesh) {
        node.material = material;
      }
    });
  }
});
```

**Comment by belen-albeza** [comment]
Check out this codepen: http://codepen.io/anon/pen/PpdMxM

Popping out the console we can see that `this.system` is a function and not an object.

However, this other codepen (http://codepen.io/anon/pen/QpVeeK), which is exactly the same but with the system / component declaration reversed, we can see that `this.system` is the Object, as expected.

**Comment by ngokevin** [comment]
should work. scripts need to be defined before a-scene.
