### ISSUE TITLE
Cursor mouseleave not triggered when object hidden

### ISSUE THREAD

**Issue by MagicIndustries** [aframevr/aframe#2467]
Using cursor-hovering/mouseleave to change the colour of a cursor component on mouseover. I found if the object the cursor is over is removed from view, the mouseleave animation doesn't trigger. Not sure whether this is a bug or expected behaviour, but it makes this kind of animation trigger difficult.

- A-Frame Version: 0.5.0
- Platform / Device: OSX / android chrome

**Comment by ngokevin** [comment]
should work on master
