### ISSUE TITLE
Position, rotation, scale values does not update in inspector

### ISSUE THREAD

**Issue by jatskie** [aframevr/aframe#2468]
**Description:**
 When in inspector mode and moving/changing an entity position/rotation/scale the input boxes updates and shows the values but when copied to clipboard the values of the attributes does not show.

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:
![bug](https://cloud.githubusercontent.com/assets/10770341/23690564/8a8aeeee-03fd-11e7-9318-070335e55620.PNG)
![bug2](https://cloud.githubusercontent.com/assets/10770341/23690563/8a881606-03fd-11e7-9ddd-91fb73069efd.PNG)

**Comment by ngokevin** [comment]
https://aframe.io/docs/0.5.0/components/debug.html#component-to-dom-serialization
