### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: vrEnabled. Set `configurable` on webvr polyfill

### ISSUE THREAD

**Issue by derhuebiii** [aframevr/aframe#2469]
**Description:**
I am creating an editor for HTML content where one building block is for aframe blocks. 
For this I am using an iframe to which the HTML code gets pushed via document.open/write/close.

If I push an aframe scene the first time, this works all fine. If I do it a second time, I get the error:
```
Uncaught TypeError: Cannot redefine property: vrEnabled
    at Function.defineProperty (<anonymous>)
    at M.enablePolyfill (webvr-polyfill.js:7699)
    at new M (webvr-polyfill.js:7631)
    at Object.M.14../util.js (webvr-polyfill.js:5606)
    at s (webvr-polyfill.js:1)
    at e (webvr-polyfill.js:1)
    at webvr-polyfill.js:1
    at u (webvr-polyfill.js:1)
    at Object.<anonymous> (webvr-polyfill.js:1)
    at Object.50 (webvr-polyfill.js:7830)
```
 
I solved my problem by adding "configurable=true" to the aframe.js :

> WebVRPolyfill.prototype.enablePolyfill = function() {
>   // Provide navigator.getVRDisplays.
>   navigator.getVRDisplays = this.getVRDisplays.bind(this);
> 
>   // Provide the VRDisplay object.
>   window.VRDisplay = VRDisplay;
> 
>   // Provide navigator.vrEnabled.
>   var self = this;
>   Object.defineProperty(navigator, 'vrEnabled', {
>     configurable:true,

Anyway there should (or maybe is) another solution to fix that problem of reloading an  a-scene element?

Thanks!
Kr,
Gerd

- A-Frame Version: 0.5
- Platform / Device: Chrome (or probably any browser with WebVR polyfill)
- Reproducible Code Snippet or URL:

**Comment by ngokevin** [comment]
Can you pull request that to WebVR polyfill? Thanks!

**Comment by derhuebiii** [comment]
https://github.com/googlevr/webvr-polyfill/issues/200#issuecomment-287101643

Has been closed in WebVR Polyfill
