### ISSUE TITLE
Consider using THREE.Clock or performance.now in render(time)

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe#2470]
**Description:** 
Currently we use `requestAnimationFrame`'s timestamp as the time to be used on `scene.render`, to update the `TWEEN` and the scene itself.
The following code (https://github.com/aframevr/aframe/blob/master/vendor/VREffect.js#L186-L194) is used to detect which `requestAnimationFrame` we should call, if we've one HMD connected it will call the `vrDisplay`'s one. 

```javascript
this.requestAnimationFrame = function( f ) {
		if ( vrDisplay !== undefined ) {
			return vrDisplay.requestAnimationFrame( f );
		} else {
			return window.requestAnimationFrame( f );
		}
	};
```

The problem is that even if you have a HMD connected, it takes a while to init it so for a few frames it will call `window.requestAnimationFrame` and after that `vrDisplay.requestAnimationFrame`.
`window.requestAnimationFrame` will returns the timestamp since the page was **loaded**, but 
`vrDisplay.requestAnimationFrame` on firefox nightly returns the timestamp relative to the **first load of the browser** not the current page (@kearwood could correct me if I'm wrong here).
So that generates that jump in the timestamp that we see in nightly:
![image](https://cloud.githubusercontent.com/assets/782511/23706478/a1d26b20-040e-11e7-8f67-8fb3b09a871b.png)
We can see that:
- 0 is generated by https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L392
- Then we have 3 frames with 3xxx generated by the `windows.RAF`
- Finally `vrDisplay.RAF` jumps in and sends the, much higher, timestamp as I had the browser opened for a while.

So we have two problems:
- The jumps between these values generates incorrect deltas and can generate weird issues (Like the one we've seen in TWEEN: https://github.com/aframevr/aframe/issues/2175)
- The timestamp is typically used to control the timeline of the experience, and we're using an incorrect value for that.

So my proposal is to use `THREE.Clock` or `DATE / performance.now` directly on the render loop to be consistent across browsers and independent from the `RAF` being used.

**Comment by machenmusik** [comment]
just FYI, changes along these lines were rejected in the time of the Chromium bug (see #2217, this would be always fixing timestamps rather than detecting) -- but maybe folks will reconsider now that Nightly exhibits the issue...
