### ISSUE TITLE
Non-visible entity can still intersect with raycaster

### ISSUE THREAD

**Issue by ripitrust** [aframevr/aframe#2480]
**Description:**

In version 0.3.0, non-visible entity does not interact with raycaster,

but in 0.5.0, non-visible entity still interact with raycaster,

any reason why this is such a case ?

my scenario is that I have multiple scenes with multiple control entities, with version 0.5.0, I can't simply set those not-in-the-scene entities non-visible.

- A-Frame Version: 0.5.0
- Platform / Device: Chrome
- Reproducible Code Snippet or URL:

**Comment by weddingdj** [comment]
I think it is important that the raycaster is interacting with non-visible entities. For example if I want to show the cursor (attached to the camera) when it is entering an invisible sphere, I want exactly that behaviour. So you can create user interfaces where the cursor only appears when the user can trigger an action.

**Comment by ngokevin** [comment]
Use `raycaster.objects` property to filter what you want to intersect. If you no longer want to intersect, then remove the entity from the selector group, and refresh the raycaster manually (`el.components.raycaster.refreshObjects()`).

**Comment by ripitrust** [comment]
@ngokevin thanks kevin

so where should I call refreshObject() ?

**Comment by ArnaudRemi** [comment]
I did `AFRAME.scenes[0].querySelector('[raycaster]').components.raycaster.refreshObjects();`
works well.

hope it helps.
