### ISSUE TITLE
Camera userHeight offset is requiring some hacks.

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2487]
- A-Frame Version: 0.5.0

I'm having recurring problems stemming from the `userHeight` offset in `camera`.

1. It defaults to `0`, except if you don't include a camera in your scene, in which case it defaults to `1.6`. This is likely confusing for new users.
2. One of the less-awful locomotion mechanisms for mobile users is something like `checkpoint-controls`. I would like to do one of the following:

```html
<a-entity universal-controls="movementControls: checkpoint"
          checkpoint-controls="mode: teleport">
  <a-entity camera="userHeight: 1.6"></a-entity>
</a-entity>
```

^This breaks, because the camera's offset is inside the entity being rotated. Looking down moves the camera closer to the ground.

***

```html
<a-entity camera 
          position="0 1.6 0"
          universal-controls="movementControls: checkpoint"
          checkpoint-controls="mode: animate">
</a-entity>
```

^This mostly works with mobile, but breaks with roomscale devices, and all of the checkpoints need to include this 1.6 offset as their `y` values.

***

```html
<a-entity camera="userHeight: 1.6"
          universal-controls="movementControls: checkpoint"
          checkpoint-controls="mode: animate">
</a-entity>
```

This looks better, but fails in all the same ways as the last example – the camera is going to directly modify the position of the entity (which ideally a camera would not do...) and now the checkpoints need to somehow be device-aware and include or exclude the offset appropriately.

***

Getting into the longer discussion of #2265, but I wanted to give a concrete example of the difficulty. I'd like to be able to give people a default that more-or-less works with both mobile and roomscale, but it's not obvious how to do that without hardcoding userHeight in a lot of places.

**Comment by machenmusik** [comment]
so iy seems that you want a separate component that will apply default user height like camera, and use that instead of default camera behavior?

**Comment by donmccurdy** [comment]
I'm not sure. I think that these methods...

```
camera.removeHeightOffset()
camera.saveCameraPose()
camera.restoreCameraPose()
```

... would ideally be in `look-controls`, not `camera`. In that case I could implement my own component that handles the height offset without worrying about a camera that mutates itself.

**Comment by dmarcos** [comment]
yeah. probably look-controls is a better place for that logic

**Comment by machenmusik** [comment]
look-controls is used for more than just cameras, which is why i think carving off the mutating portion into a separate component may be safer...

**Comment by machenmusik** [comment]
to me, look-controls should only apply the orientation, and if there is some auto user height offset logic, that should be a separate component that can be used for that purpose (e.g. if someone wanted geometry or text to auto adjust to eye level)

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/3327
