### ISSUE TITLE
Elements wrapped into a-entity aren't displayed

### ISSUE THREAD

**Issue by Disorrder** [aframevr/aframe#2489]
Objects just in `a-scene` DOM are displaying good, but if wrap them into `a-entity` they disappear.

- A-Frame Version: 0.5.0
- Platform / Device: Google Chrome
- Reproducible Code Snippet or URL: https://codepen.io/Disorrder/pen/OpmWKJ

**Comment by dmarcos** [comment]
What kind of markup is that? Are you using any library? I see things being rendered. I'm not sure what you're expecting to see. Can you be more specific or provide a simpler example?

**Comment by ngokevin** [comment]
`%cA-Frame:warn %cPut the A-Frame <script> tag in the <head> of the HTML *before* the scene to ensure everything for A-Frame is properly registered before they are used from HTML.%c +0ms`

Put the A-Frame script above the scene.

**Comment by Disorrder** [comment]
@dmarcos [pug](https://pugjs.org) with no libs
@ngokevin thanks
