### ISSUE TITLE
Update Polyfill to 0.9.26

### ISSUE THREAD

**Issue by HalfdanJ** [aframevr/aframe#2495]
A new version has been released with some bugfixes for recent versions of chrome on android.

**Comment by ngokevin** [comment]
Note we currently have a couple of cherry-picked commits we need to pull in. Currently using a fork `dmarcos/webvr-polyfill#a02a8089b`

**Comment by HalfdanJ** [comment]
Created a PR on that fork: https://github.com/dmarcos/webvr-polyfill/pull/2

**Comment by dmarcos** [comment]
@HalfdanJ thanks

**Comment by dmarcos** [comment]
@HalfdanJ what bug fixes are missing?

**Comment by HalfdanJ** [comment]
This one for example is fixed in 0.9.26: https://github.com/googlevr/webvr-polyfill/issues/202

**Comment by ngokevin** [comment]
#2700
