### ISSUE TITLE
Expose `material.alphaTest` and `material.depthWrite` properties

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2497]
**Description:**

To configure depth testing.

In `src/components/material.js`.

http://stackoverflow.com/questions/42799420/why-is-the-opacity-different-depending-on-the-camera-angle/42822927?noredirect=1#comment72797756_42822927

**Comment by takahirox** [comment]
Let me take this.

**Comment by takahirox** [comment]
I think we should set `material.needsUpdate = true` in `updateMaterial()` if `alphaTest` value is updated, correct?

**Comment by alfa256** [comment]
:+1:  Was going to post this.
