### ISSUE TITLE
AFRAME.utils.device.checkHeadsetConnected() returns false 

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#2508]
**Description:**

It returns false in FF and Chrome, even if there is a Oculus DK2 connected and working.

- A-Frame Version: 0.5.0
- Platform / Device: Windows PC, FF, Chrome
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Is DK2 still supported by recent Oculus runtimes?

**Comment by weddingdj** [comment]
I still works, I don't know if it is officially supported. I just wanted to make sure checkHeadsetConnected() returns true.

**Comment by dmarcos** [comment]
In Firefox Nightly i see AFRAME.utils.checkHeadsetConnected() return `true` with a DK2 connected and using the following demo https://aframe.io/aframe/examples/showcase/anime-UI/.
Please reopen if this is still an issue.
