### ISSUE TITLE
a-animation fill="backwards" set attribute to undefined

### ISSUE THREAD

**Issue by Disorrder** [aframevr/aframe#2515]
Press `flashLight` button in example
Screenshot: https://gyazo.com/c6b620150e884cfc24fac9e9b9bb9d25

- A-Frame Version: 0.5.0
- Platform / Device: Google Chrome
- Reproducible Code Snippet or URL: https://codepen.io/Disorrder/pen/jBzExv

**Comment by ngokevin** [comment]
https://aframe.io/docs/0.5.0/introduction/faq.html#why-is-the-html-dom-not-updating-in-a-frame
https://aframe.io/docs/0.3.0/components/debug.html#component-to-dom-serialization

**Comment by Disorrder** [comment]
@ngokevin what? You say that a-frame doesn't update values in attributes, but it does! 
Animation goes good, but after animation DOM attribute value is set to undefined!
I mean, fill="backwards" doesn't work as expected, it breaks light after animation! I expect that a-animation will set "from" value to attribute, but not undefined 
If you don't understand our need another example, please let me know

**Comment by Disorrder** [comment]
@ngokevin 
[example one](http://codepen.io/anon/pen/dpmpJP) with aframe version *0.1.3*
[example two](http://codepen.io/Disorrder/pen/JWqWOx) with aframe version *0.5.0*
Please, compare cursor animation and reopen this issue! It's critical in using standart `a-animation` component :(
