### ISSUE TITLE
Infinite Loop on Component Update

### ISSUE THREAD

**Issue by protyze** [aframevr/aframe#2517]
**Description:**

The AFRAME.utils-Function "deepEqual" causes an Infinite-Loop leading to a Maximum Call Stack Error when a Component-Property is updated under the following circumstances:

--> The Property is an Entity (e.g. when Property-Type is "Selector" and an Entity has been loaded and needs to be compared for differences using deepEqual).

Since an Entity contains references to itself, deepEqual will end up comparing the same things over and over, resulting in an infinite loop.

- A-Frame Version: 0.5.0
- Platform / Device: All.
- Reproducible Code Snippet or URL:

SAMPLE-COMPONENT:

```
AFRAME.registerComponent('reproduce', {

    schema: {
        object: {type: 'selector', default: ''},
        other: {default:false}
    },

    init: function () {},

    update: function (oldData) {},
});
```

SAMPLE-HTML:

```
<a-scene>
    <a-entity id="test"></a-entity>
    <a-entity reproduce="object:#test; other:false"></a-entity>
</a-scene>
```

Steps to reproduce:
1. Load the Scene with the component
2. Change the Property "other" to "true"
3. Infinite-Loop happens

**Comment by ngokevin** [comment]
#2502
