### ISSUE TITLE
Angular CLI databinding for A-frame tags

### ISSUE THREAD

**Issue by HeinPauwelyn** [aframevr/aframe#2518]
## Description

- A-Frame Version:  0.5.0
- aframe-template-component version: 3.2.1
- Angular-CLI version: 1.0.0-beta.28.3
- Platform / Device: Windows 10 _(why will you know that?)_
- Reproducible Code Snippet or URL: code below

## Question and problem

I'm making a WebVR application with Angular-CLI. I load some static JSON data from the assets and will bind it to an A-frame element. Here is an example of my JSON data.

```json
{
    "id": 4,
    "image": "",
    "location": "Font",
    "nextScenes": [
        3,
        5
    ],
    "hotspots": [
        {
            "id": "obj1",
            "location": "2323.81 1305.90 -2400",
            "rotation": "-4.58 -48.7 -5.16",
            "scale": "150 150 150",
            "headerTitle": "",
            "body": ""
        },
        {
            "id": "obj2",
            "location": "3145.63 889.46 -2176.50",
            "rotation": "-4.58 -48.7 -5.16",
            "scale": "150 150 150",
            "headerTitle": "",
            "body": ""
        }
    ]
}
```

I'll load the `hotspots` in my HTML code with this code:

```html
<a-scene inspector="url: https://aframe.io/releases/0.3.0/aframe-inspector.min.js">
    <a-assets>
        <img id="sky" [src]="currentImageSource" alt="" />
    </a-assets>
    
    <a-sky src="#sky"></a-sky>
    
    <!-- problems with code below -->
    <a-entity *ngFor="let spot of currentData.hotspots; let i = index" [id]="spot.id" 
              [position]="spot.location" [rotation]="spot.rotation" [scale]="spot.scale" 
              visible="true" mixin="null" color="pink" 
              text="zOffset:0;value:S;height:100;width:100;align:center"></a-entity>
</a-scene>
```

Notice that `currentData` is equal to the JSON code above and `currentImageSource` contains the location of the image.

```ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
    selector: 'app-vrtour',
    templateUrl: './vrtour.component.html',
    styleUrls: ['./vrtour.component.scss']
})
export class VrtourComponent implements OnInit {

    data: any[] = require("assets/json/data.json"); // this will load the JSON data above
    currentData: any;
    id: number;
    currentImageSource: string = "";

    constructor(private router: Router, private route: ActivatedRoute) {

        route.params.subscribe(params => {
            this.load(+params['id']);
        });
    }

    load(id: number): void {
        if (id < this.data.length) {
            this.id = id;
            this.currentData = this.data[id];
            this.currentImageSource = `assets/360images/P${this.currentData.id}.tif`;
        }
        else {
            this.load(0);
        }
    }

    ngOnInit(): void {
        console.log(this.currentData.hotspots);
    }
}
```

The problem with code above is that the attributes `position`, `rotation` and `scale` wouldn't bind. In the rendered output are the variables empty but the `ng-reflect-...` attributes aren't empty.

Also if I inspect the code with <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>I</kbd>, the object got the `a-entity` tags the default values.

The databinding for the attribute `id` works.

How could I use databinding for A-frame tags?

**Comment by HeinPauwelyn** [comment]
After trying a workaround, I've found a solution that works. The issue of this code is that it didn't use databinding and I thing it is less performance that databinding but A-frame doesn't support it.

Here you could find the code I've added in my typescript code:

```ts
ngAfterViewInit(): void {

    for (let i: number = this.currentData.hotspots.length; i--;) {

        let spot: any = this.currentData.hotspots[i],
            el: any = document.getElementById(spot.id);

        el.setAttribute("position", spot.location);
        el.setAttribute("rotation", spot.rotation);
        el.setAttribute("scale", spot.scale);
    }
}
```

This code works if I give every `a-entity`-tag an unique ID. The HTML code of my component, is unchanged but it's possible to use this instead.

```html
<a-entity *ngFor="let spot of currentData.hotspots; let i = index" [id]="spot.id"
          text="zOffset:0;value:S;height:100;width:100;align:center"></a-entity>
```

**Comment by playground** [comment]
I'm running into the same issue, setAttribute works but when setAttribute('color', 'yellow') give different result on every load.

**Comment by BlackWidow1088** [comment]
to set attribute binding to aframe entities use [attr.position] = "1 1 1".
