### ISSUE TITLE
oculus-touch-controls / vive-controls / hand-controls should be able to define model URL

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2519]
**Description:**

In case you want to point to one locally.

**Comment by machenmusik** [comment]
you mean should be able to override base URL, right?

https://github.com/aframevr/aframe/blob/master/src/components/oculus-touch-controls.js#L5
hmm, `vive-controls` doesn't have a base URL.

There is a larger question here, IMO, of whether all of the cdn.aframe.io links that core components use should be able to have their base URL redirected for offline use, not just the models for tracked controllers

**Comment by machenmusik** [comment]
(e.g. fonts)

**Comment by ngokevin** [comment]
Yeah, but not exposed in the schema. I don't think we need anything magic, just a way to configure.

**Comment by machenmusik** [comment]
is it enough to export the base URL variables for whatever components need to do this?

**Comment by machenmusik** [comment]
(this is easy enough that we may want to find a willing first-time participant looking to jump in)

**Comment by ngokevin** [comment]
Export the base URL? I'm just thinking simple: expose schema property where you provide a full URL or path. Don't have to think about what strings are added together and such.

**Comment by machenmusik** [comment]
then you have to do it for left and right, obj and mtl, per instance... seems pretty tedious... and needs to be done for `hand-controls` too either way.

**Comment by ngokevin** [comment]
It's not too bad, you just make the constant a schema property default. Users don't have to define if they don't need, but in the case they do (e.g., work offline), they can.

**Comment by machenmusik** [comment]
not worried about schema, just that there are multiple urls that all need to be overridden together.

**Comment by machenmusik** [comment]
for the static use case, the filenames would all be the same, just need to change the base URL to something local.

**Comment by machenmusik** [comment]
more insidious is the case where someone is using `hand-controls` and not directly specifying oculus or vive... need to override for all instances, which putting in schema won't accomplish.

**Comment by dmarcos** [comment]
Yeah if you want to override the model you can disable the default one and use your own model as the `hand-controls` component does or the `paint-controls` on a-painter

**Comment by machenmusik** [comment]
yes but the use case mentioned here is how to embed the stock models for self contained usage.  in that case really you would need other cdn.aframe.io files as well

**Comment by machenmusik** [comment]
yes but the use case mentioned here is how to embed the stock models for self contained usage.  in that case really you would need other cdn.aframe.io files as well

**Comment by gurumukhi** [comment]
Hi @dmarcos @machenmusik @ngokevin, is this issue still being discussed? If not, can you please summarize how a newbie can work on this?

Thanks :-)

**Comment by jselmani** [comment]
Hey everyone! I am a new contributor and am looking for some issues to work on.  This one has piqued my interest and I would be open to understanding how I can help.  I noticed that there was a comment by @machenmusik that it is easy enough for a first-time participant to tackle it.  

How can I help?

**Comment by ngokevin** [comment]
Pattern at the moment is to set all *-controls to `model: false` and set model manually. We usually have a `controller` component
