### ISSUE TITLE
el.setAttribute('mixin', 'some-mixin-id') doesn't replace existing mixin

### ISSUE THREAD

**Issue by superdump** [aframevr/aframe#2532]
**Description:** calling `el.setAttribute('mixin', 'some-new-mixin-id')` on an element that already has a mixin attribute with a value does not swap out the existing mixin with the new one.

- A-Frame Version: 0.5.0
- Platform / Device: Chrome 57 macOS
- Reproducible Code Snippet or URL: http://codepen.io/anon/pen/zZMXrG

**Comment by dye784** [comment]
Weird. Going to try and fix it. 👍

**Comment by dye784** [comment]
Looks like it is changing the `mixin` property on the element but not the actual trains that the `mixin` has.

```html
<a-plane id="plane" mixin="zero" color="blue" position="0 2 -5" width="5" height="5" rotation="" scale="" visible="" material="" geometry=""></a-plane>

<a-plane id="plane" mixin="zero" color="blue" position="0 2 -5" width="5" height="5" rotation="" scale="" visible="" material="" geometry=""></a-plane>
```

**Comment by ngokevin** [comment]
https://aframe.io/docs/0.5.0/introduction/faq.html#why-is-the-html-dom-not-updating-in-a-frame

**Comment by dye784** [comment]
Oh thanks @ngokevin. So the component data doesn't update. But it should still update the scene right?

**Comment by dye784** [comment]
Is this not working because the invoked `setAttribute` method is on the html node and not A-frame's `setAttribute` method? Also instead of `setTimeout` don't we use the `tick` method instead?

**Comment by caseyyee** [comment]
I'm getting the same issue here.  The component updates, so the tests don't fail, but the scene doesn't update.  cc @dmarcos

**Comment by twastvedt** [comment]
I ran into this issue as well. I thought, "well that's fine, I'll just go fix it". I think I know what is happening now, but I do not think I have enough knowledge of the rest of the A-Frame internals to know the best way to go about fixing this. If the below is useful, great. If it suggests a path to a solution that is easy to explain I'd be happy to take a shot at making a PR, but at the moment it seems to me that a solution would need to go deeper than my level of understanding. If neither is the case, then this is just my documentation of my first foray behind the A-Frame [a-]scene!

My trail started in [a-entity.js](https://github.com/aframevr/aframe/blob/050cbaf249ec34bb378a3a3c304a4fe6e71c069b/src/core/a-entity.js#L459):
```
  updateComponents: {
...
      for (name in componentsToUpdate) {
        data = mergeComponentData(this.getDOMAttribute(name),
                                  extraComponents && extraComponents[name]);
        this.updateComponent(name, data);
        delete componentsToUpdate[name];
}
```
When `updateComponents` runs after changing the mixin id, `this.getDOMAttribute(name)` is returning the value of the attribute with mixins included. Thus `mergeComponentData` is giving precedence to the old mixin values and the new ones (contained in `extraComponents`) never get written. The comment on `getDOMAttribute` [here](https://github.com/aframevr/aframe/blob/050cbaf249ec34bb378a3a3c304a4fe6e71c069b/src/core/a-entity.js#L727) suggests that it should not be including mixins. 

The only relevant difference here between `getDOMAttribute` and `getAttribute` (which by its comment _is_ supposed to include mixin values) is that they look at `this.attrValue` and `this.data` respectively. However setting a mixin calls `updateComponents` which calls `component.updateProperties`, which updates both `this.attrValue` and `this.data`, so `this.attrValue` gets populated with mixin values, which looks to be incorrect.

So, assuming the above is correct, I'm not sure where to go from here. The comment on `getDOMAttribute` would suggest that we don't want to use `updateProperties` when updating a component with mixin values, but we do need to update the component's `data`, and I'm not sure how best to do that without `updateProperties`. Do we need a whole separate update path, starting with [the loop](https://github.com/aframevr/aframe/blob/050cbaf249ec34bb378a3a3c304a4fe6e71c069b/src/core/a-entity.js#L429-L433) in `updateComponents` which finds all mixin attributes? But then it seems like `updateProperties` is doing a lot of other useful stuff that should happen for mixin values as well. I'll stop speculating on things I don't yet understand.

**Comment by eoinapplaud** [comment]
Hey everyone

I'm having the same issue here. The new mixin is being applied but unfortunately the scene does not update.

Any help would be appreciated.

Eoin

**Comment by ngokevin** [comment]
Works for me on master using setattributes:

<img width="573" alt="screen shot 2019-01-30 at 3 13 41 pm" src="https://user-images.githubusercontent.com/674727/52019222-fa594600-24a1-11e9-9e73-82c775e1901a.png">
<img width="575" alt="screen shot 2019-01-30 at 3 14 06 pm" src="https://user-images.githubusercontent.com/674727/52019223-fa594600-24a1-11e9-8c11-8851a8a537cb.png">
