### ISSUE TITLE
Consider deprecating single-property schemas

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2536]
**Description:**

Advantages:

- Single-property components are inflexible in that you cannot add a new property to the schema without having it be a breaking change. I was looking at https://github.com/aframevr/aframe/pull/2297, and I couldn't add a new prop without a breaking change.
- Less confusing having to guess if a component is single-property or multi-property, for example, is it `hand-controls="hand: left"` or `hand-controls="left"` (some controllers are single-prop, some are multi)? Is it `gltf-model="src: #model"` or `gltf-model="#model"` (some loaders are single-prop, some are multi). It's been inconsistent so I've seen people make mistakes including myself
- Less documentation about schemas in the component API (https://aframe.io/docs/0.5.0/core/component.html#single-property-schema is a bit awkward to explain)
- Reduced API surface/branching in the component API (e.g., if you do this, then it's single prop, if you specify this, it's multi prop)
- Can delete a lot of code where we check isSingleProp in a lot of places in the core component code

If we do this, then we'd need to introduce a `default` property for cases such as position, rotation, scale that designates if the component value is used in single-prop mode:

```
schema: {
  position: {type: 'vec3', default: true}
}
```

**Comment by machenmusik** [comment]
suggest a new key in the schema to indicate whether to be used when single property is given -- can't use default since that refers to the default value.  maybe `singleProperty` -- and if no schema property has that set to true, then single property syntax is not allowed for that component.

```schema: {
  position: {type: 'vec3', default: {x:0, y:0, z:0}, singleProperty: true}
}```

**Comment by fernandojsg** [comment]
I agree with @machenmusik better use another property name to avoid confusion when using `default`

**Comment by donmccurdy** [comment]
How compatible is it to delete "a lot of code where we check isSingleProp" while maintaining cases like `position` and `rotation`? That sounds good if it's feasible; in any case I like the idea of having *fewer* single-property components. Models and controls probably need to be forward-compatible with adding properties.

**Comment by donmccurdy** [comment]
And if we do the last part of the proposal, do we need `el.getAttribute('position').position` to access that vector, or is the value still replacing the `data` object itself?

**Comment by ngokevin** [comment]
I hadn't thought about `getAttribute`...I think it's better instead we recommend being more careful with using single-prop when more properties in the future can be added and when it makes sense.
