### ISSUE TITLE
a-animation: scale-animation jumps if "from" not set on mouseenter/mouseleave (hover)

### ISSUE THREAD

**Issue by derhuebiii** [aframevr/aframe#2542]
**Description:**
If I use 'a-animation' on an object using a cursor to trigger it on mouseenter and mouseleave, this works in principle. After running the animation the first time there is a problem when I only "very quickly" hover over the object. It jumps suddenly to the scale set in the first animation in "to". 

You can check this error on first starting the animation and hovering out. Then quickly hover over the sphere and move again away from it. [JSFiddle](https://jsfiddle.net/c4cu639d/7/)

Does not appear when waiting until animationend.

```
  <a-scene vr-mode-ui>


      <a-sphere position="0 0 -5" radius="1" color="red">
        <a-animation begin="mouseenter" end="mouseleave" fill="forwards" repeat="0"
         direction="normal" attribute="scale" from="1 1 1"
         to="3 3 3" dur="1000"></a-animation>
         <a-animation begin="mouseleave" end="mouseenter" repeat="0" fill="forwards"
          direction="normal" attribute="scale"
          to="1 1 1" dur="1000"></a-animation>
      </a-sphere>


    <a-camera id="camera">
      <a-cursor color="#4CC3D9"></a-cursor>
    </a-camera>


  </a-scene>
```

- A-Frame Version: 0.5
- Platform / Device: Chrome
- Reproducible Code Snippet or URL: [JSFiddle](https://jsfiddle.net/c4cu639d/7/)

**Comment by MichaelHazani** [comment]
@ngokevin this can be closed, I believe. I'm able to repro behaviour in 0.5 but not in 7.0. (maybe @derhuebiii would like to confirm.)

**Comment by ngokevin** [comment]
Thanks. We've deprecated a-animation anyways. Try https://github.com/ngokevin/kframe/tree/master/components/animation and file issues, and component will be merged in in the future.
