### ISSUE TITLE
glTF models have bad stereo in Vive, aren't movable in inspector

### ISSUE THREAD

**Issue by pieper** [aframevr/aframe#2552]
I tried loading various glTF models but they never render right when I go into VR mode on the Vive.  They are in the correct place in space, but the location in the two eye views is very different so they are impossible to fuse.

This happens both with my own models and with models from [glTF examples repository](https://github.com/KhronosGroup/glTF-Sample-Models).

In the super simple example linked below the duck is on top of the plane in a regular webgl view, but is way off when you go into VR mode.

Perhaps related, when I go into the inspector the glTF models don't rotate with the rest of the scene and don't update when they are transformed.  I suspect they aren't being correctly added to the scene by the loader (or something).

- A-Frame Version: [0.5.0](https://aframe.io/releases/0.5.0/aframe.min.js)
- Platform / Device: Vive
- Reproducible Code Snippet or URL: [http://pieper.github.io/sites/gltf-question/](http://pieper.github.io/sites/gltf-question)
[source code](https://github.com/pieper/sites/tree/175aad3eadd62fdf9a339c24d4a1daefa65acaf9/gltf-question)

**Comment by dmarcos** [comment]
I tried the model below in the scene and it renders fine:

https://cdn.aframe.io/test-models/models/brainstem/BrainStem.gltf

There is probably something wrong with your models.

**Comment by pieper** [comment]
@dmarcos Thanks for checking, yes, brainstem model works.  But the ones that fail are not just my own models, I'm testing models from the glTF repository and they all seem to have the same problem.

The example uses the [the duck model](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/1.0/Duck/glTF-Embedded/Duck.gltf) from the glTF site.

I updated the page to include brainstem and the duck next to each other and they look fine until I go into VR (on Vive) or into Inspect mode.  http://pieper.github.io/sites/gltf-question

**Comment by donmccurdy** [comment]
Hi @pieper – this issue has been fixed in three.js, but the won't be released until r85. See: https://github.com/mrdoob/three.js/issues/9073

The problem specifically affects custom shaders in the GLSL file. If your model is using standard three.js materials (i.e. glTF's KHR_materials_common extension) then you'll be fine. When converting with COLLADA2GLTF, that means adding the `-k` flag.

**Comment by pieper** [comment]
Thanks @donmccurdy!  That looks like exactly the issue.  I'll doublecheck and then close this.

**Comment by pieper** [comment]
Confirmed.  Thanks again.
