### ISSUE TITLE
Array property type default share the same reference

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2554]
**Description:**

```
schema: {
  foo: {type: 'array'},
  bar: {type: 'array'}
}
```

The two arrays share the same reference. If you push to `bar`, it will also be seen as pushed to `foo`.

It's fixed if I specify my own array:

```
schema: {
  foo: {type: 'array', default: []},
  bar: {type: 'array', default: []}
}
```

- A-Frame Version: 0.5.0

**Comment by takahirox** [comment]
Could I try to fix this?

**Comment by ngokevin** [comment]
Yeah!
