### ISSUE TITLE
object property type

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2555]
**Description:**

I had a game state component where I wanted to just store a plain JavaScript object in the game state, via the schema. Don't need any of the HTML parsing pieces, but we could have that too.

```
schema: {
  foo: {type: 'object'}
}

// ... setAttribute('component', 'foo', {bar: 10})
```

Possible HTML form just in case, but won't be used often:

```<a-entity component="foo: {bar: 10};>```

**Comment by dye784** [comment]
Sounds reasonable. We store specific objects likes `vec2`, `vec3`, and `vec4` anyway. I don't see why a more broad `object` `type` would be bad.

**Comment by ngokevin** [comment]
Closed, see https://github.com/aframevr/aframe/issues/2555
