### ISSUE TITLE
Look-Controls are locked to one axis on Android Tablets

### ISSUE THREAD

**Issue by mannytan** [aframevr/aframe#2557]
I'm using the look-controls component on a Pixel C tablet and noticed that I can only pan left to right when dragging the screen around. This is also happening on the Hello WebVR example. 

On a related note, when I switch over to full screen/cardboard mode, the example has access to the Pixel C's gyroscope and responds accordingly.

I should have access to the gyroscope by default (like the way it's being handled on a pixel phone) but it's currently not the case.

- A-Frame Version: 0.5.0
- Platform / Device: Chrome / Android / Pixel C
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

**Comment by johnnyshankman** [comment]
I also have the same issue on iOS and Chrome mobile sims.

**Comment by dmarcos** [comment]
This is a design decision. If we enable touch rotation in the vertical direction you quickly lose the sense of what's up and down when paired with the gyro orientation

**Comment by chendabo** [comment]
@dmarcos Is there an option to turn it on?

**Comment by dmarcos** [comment]
No, panning on the vertical axis is not implemented

**Comment by chendabo** [comment]
What would be the best solution if some of the mobile browsers don't support gyro within aframe? (can I turn it into drag control mode with a button or automatically)

**Comment by dmarcos** [comment]
You could take look-controls as a starting point and implement your own component with vertical panning. It should not be too difficult. We focus on VR and our curent control schema assumes at least a device capable of magic window mode (gyro available)

**Comment by LorenzoVonMatterhom** [comment]
This should probably be supported in core AFrame but here is the code to replace in look controls:
`onTouchMove: function (evt) {
    var direction;
    var canvas = this.el.sceneEl.canvas;
    var deltaY;
    var deltaX;
    var yawObject = this.yawObject;
    var pitchObject = this.pitchObject;

    if (!this.touchStarted || !this.data.touchEnabled) { return; }

    deltaY = 2 * Math.PI * (evt.touches[0].pageX - this.touchStart.x) / canvas.clientWidth;
    deltaX = 2 * Math.PI * (evt.touches[0].pageY - this.touchStart.y) / canvas.clientHeight;

    direction = this.data.reverseTouchDrag ? 1 : -1;
    // Limit touch orientaion to to yaw (y axis).
    yawObject.rotation.y -= deltaY * 0.5 * direction;
    pitchObject.rotation.x -= deltaX * 0.5 * direction;
    this.touchStart = {
      x: evt.touches[0].pageX,
      y: evt.touches[0].pageY
    };
  },`
