### ISSUE TITLE
Can't Trace `components:x:` type Warnings

### ISSUE THREAD

**Issue by johnnyshankman** [aframevr/aframe#2558]
- A-Frame Version: 0.5.0
- Platform / Device: Safari
- Reproducible Code Snippet or URL:
```
components:sound:warn All the sounds are playing. If you need to play more sounds simultaneously consider increasing the size of pool with the `poolSize` attribute. +7s
```

How do I trace back this warning a specific entity? All I know is that it's some entity that has a sound component. 0 identifier being given and in many instances there are too many entities to reason out which one it is.

**Comment by ngokevin** [comment]
Thanks, I've patched the warning to log the entity. You can try it with https://rawgit.com/aframevr/aframe/14c9b5b/dist/aframe-master.min.js

**Comment by johnnyshankman** [comment]
@ngokevin awesome! Thank you.
