### ISSUE TITLE
Can't Play Sound On Fuse on Safari iOS (Including Demos)

### ISSUE THREAD

**Issue by johnnyshankman** [aframevr/aframe#2559]
- A-Frame Version: 0.5.0
- Platform / Device: iOS Safari
- Reproducible Code Snippet or URL:

https://aframe.io/examples/showcase/360-image-gallery/ on iOS

```
// Add this to any entity, taken from 360 example
sound="on: click; src: #click-sound;"
```

Any attempts at playing a sound using the `sound` component by leveraging `fuse` on the cursor to trigger the `click` handler does not work.

This shouldn't be the case. The user has made an explicit action/gesture to start audio. That's the only documented rule for iOS, so the implementation under the hood should be the issue to my knowledge. Problem is, the "explicit" action is staring in one place for an extended period of time, which Apple doesn't consider a user gesture.

**Docs:**

- https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html#//apple_ref/doc/uid/TP40009523-CH5-SW1

- https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/AudioandVideoTagBasics/AudioandVideoTagBasics.html#//apple_ref/doc/uid/TP40009523-CH2-SW1

This is different than autoplay audio, which is an issue with the iOS Safari implementation (imo) and not within the scope of this discussion.

The same code does play audio when downloaded to the homescreen. That's okay, but a considerably worse user experience that I'm currently not interested in.

_**Update**: Realized the issue is using `fuse`. Fuse doesn't propagate the same way a click does and therefore doesn't count as a user gesture. Updated the title + description. Worried the best that we can do is update the docs to warn that `fuse` causes audio to not trigger on iOS._

**Comment by johnnyshankman** [comment]
Also relevant https://www.ibm.com/developerworks/library/wa-ioshtml5/#N101DA

**Comment by johnnyshankman** [comment]
Also confirmed this happens with or without the use of `fuse` timeouts.

**Comment by ngokevin** [comment]
Yeah, fuse events are synthetic so they do not count as an explicit user gesture. An alternative to using fuse is to use the Cardboard button as a click/tap event. Otherwise, it's a bad limitation of iOS/mobile browsers.

**Comment by johnnyshankman** [comment]
@ngokevin very fair. Thank you!
