### ISSUE TITLE
Warning "Material component properties are ignored when a .MTL is provided" when loading .obj & .mtl

### ISSUE THREAD

**Issue by eng1neer** [aframevr/aframe#2572]
I'm trying to load a model with a material applied to it using the example from the docs https://aframe.io/docs/0.5.0/components/obj-model.html

However, it seems that material is not being applied and the warning is shown in the javacript console:

`components:obj-model:warn Material component properties are ignored when a .MTL is provided` 

I've also tried to run example from this repository (`examples/test/model`) and the above warning is also shown. Textures are applied correctly, but when I remove texture from .mtl file (`map_Kd crate.jpg`) the material described in .mtl seems to be not applied.

What exactly does the above warning mean?

- A-Frame Version: 0.5.0
- Platform / Device: Google Chrome

**Comment by ngokevin** [comment]
I think it's due to https://github.com/aframevr/aframe/issues/2464 (dupe). obj-model sets a dependency on `material` component to make sure it's initialized before the obj-model...*in case it's set*. If it's not set, then it'll throw that useless warning which we should fix.
