### ISSUE TITLE
asset and related property types should use getElementById when id selector form is used

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#2578]
Several property types (`audio`, `asset`, `map`, `model`) expect to support either an id selector string (`#` followed by `id` value to match) or arbitrary string that is often a URL (e.g. `https://cdn.aframe.io/foo`).  

However, the code to handle the id selector string uses `querySelector`, which is stricter on id values than necessary (e.g. can't start with digit), and also looser on actual selector values than necessary (e.g. would allow resolution of class selectors and others).

Per discussion in Slack, the suggested resolution is to change the id selector string resolution to use `getElementById` which should resolve both being overly strict on id and being overly loose on selector.  e.g. `.getElementById(selector.substring(1))` -- and also to update the property type documentation to clarify what is actually supported.

**Comment by machenmusik** [comment]
example: http://codepen.io/machenmusik/pen/rmNpjO

**Comment by ngokevin** [comment]
Sounds good!
