### ISSUE TITLE
The Vive Requirement link is broken in documentation

### ISSUE THREAD

**Issue by pjoulot** [aframevr/aframe#2586]
Hello,
The link "Vive recommended requirements" into the documentation is broken.
https://aframe.io/docs/master/introduction/device-and-platform-support.html#hardware-specifications

I think the page has been moved to https://www.vive.com/us/ready/

I did a pull request here: https://github.com/aframevr/aframe/pull/2587

**Comment by dmarcos** [comment]
Fixed by #2587
