### ISSUE TITLE
Submit A-Frame to 24 Pull Requests for contributor outreach

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#259]
[It](http://24pullrequests.com/)'s gotten quite popular lately.

http://24pullrequests.com/projects/new

**Comment by ngokevin** [comment]
Now time to wait a year.

<img width="1185" alt="screen shot 2016-02-18 at 6 28 02 pm" src="https://cloud.githubusercontent.com/assets/674727/13164891/75837cdc-d66d-11e5-8f09-a096ddd40e4c.png">
