### ISSUE TITLE
[doc] clarify position, rotation, scale order of transformation

### ISSUE THREAD

**Issue by andreasplesch** [aframevr/aframe#2591]
**Description:**

- A-Frame Version: all
- Platform / Device: all
- Reproducible Code Snippet or URL:

While I know that the position, rotation and scale values if given for a single entity are simply forwarded to three.object3d() and I happen to know that three does sensibly apply these transformations in the proper scale, rotation, then position order, I could not find a clear (or any) statement in the aframe docs which confirm that. aframe aims to be understandable without three.js knowledge.

Perhaps just a sentence in entity initial paragraph, or in the Parent-Child transform section.

**Comment by P00jaT** [comment]
I want to work on #2591 problem

**Comment by andreasplesch** [comment]
The end effect of position, scale and rotation depends on the order in which these are applied. Please verify that the order is indeed scale, then rotation, then position (translation).

**Comment by donmccurdy** [comment]
That (scale, rotation, position/translation) is the correct order for A-Frame. [Additions to the docs are welcome](https://github.com/aframevr/aframe/blob/master/CONTRIBUTING.md#update-documentation), perhaps on the pages for the `scale`, `rotation`, and `position` pages?

**Comment by gurumukhi** [comment]
Hi @P00jaT, I hope you are working on this. Feel free to work on this bug and create a PR, if you have any questions you can ask on #issues slack channel of a-frame (https://aframe.io/community/#slack). Keep us updated on this issue once you have made any progress.
