### ISSUE TITLE
Request: Add Freedom Locomotion Component

### ISSUE THREAD

**Issue by NeoVand** [aframevr/aframe#2592]
There is a great locomotion solution out there called [Freedom Locomotion](https://hugerobot.itch.io/freedom-locomotion-vr) ([video](https://youtu.be/LiQJS8ir9sQ)) that can be implemented as a camera/hand-controls component.

**Comment by dmarcos** [comment]
Thanks for the request. This kind of features are better supplied by 3rd party components (https://aframe.io/aframe-registry/(. We want to keep the core small with the functionality that most of the applications need.
