### ISSUE TITLE
a-frame inspector not working

### ISSUE THREAD

**Issue by HAZARDU5** [aframevr/aframe#2598]
For some reason the a-frame inspector has a breaking error while trying to hide the loader. This causes it to be unresponsive when launched.

See below:

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at NewComponent.hideLoader (https://cdn.rawgit.com/aframevr/aframe/v0.5.0/dist/aframe-v0.5.0.js:68558:13)
    at HTMLScriptElement.script.onload (https://cdn.rawgit.com/aframevr/aframe/v0.5.0/dist/aframe-v0.5.0.js:68583:12)
```

- A-Frame Version: v0.5.0
- Platform / Device: OSX 10.11.6 / Firefox 52.0.2 / Chrome 57.0.2987.133
- Reproducible Code Snippet or URL: https://58f6d0a253444.gladeye.org/prototype1/

I suspect that a broken version of the inspector JS has been pushed to the CDN as this is loaded independently of the a-frame JS file. The example URL was working earlier today and hasn't been touched since.

**Comment by HAZARDU5** [comment]
After further investigation it seems that it was partially caused by the bootstrap modal dialog box css that was running on the page. When using the current master branch of a-frame and disabling the dialog box html the inspector works as expected.

**Comment by HAZARDU5** [comment]
Would it be possible to change the css class applied by the inspector to something other than `modal`? e.g. `inspector-modal`? This would help prevent collisions with other CSS that may be on the page, especially since it's embedded in a `style` element, making it difficult to remove / adjust in certain cases where there are collisions.

**Comment by jaredpike** [comment]
It'd be nice if all of the inspector's styling was prefixed to prevent collisions from user styles. `button` -> `inspector-button`, etc.

**Comment by fernandojsg** [comment]
It's a issue already filed on the inspector but we still didn't address it :/ https://github.com/aframevr/aframe-inspector/issues/129 feel free if you believe you could help there!

**Comment by cvan** [comment]
(I assume this is the same issue, but correct me if I'm wrong.) Loading the Inspector from Docs doesn't work https://aframe.io/docs/0.5.0/guides/:

![screen shot 2017-05-05 at 4 02 35 pm](https://cloud.githubusercontent.com/assets/203725/25767255/8a5bebee-31ac-11e7-9899-a0a35b83f926.png)
![screen shot 2017-05-05 at 4 02 46 pm](https://cloud.githubusercontent.com/assets/203725/25767257/8a607326-31ac-11e7-9d97-60ad2bf68848.png)

The Inspector loads fine from the https://aframe.io examples though:

![screen shot 2017-05-05 at 4 03 28 pm](https://cloud.githubusercontent.com/assets/203725/25767256/8a5dfe16-31ac-11e7-9288-22f1ac9e899c.png)
![screen shot 2017-05-05 at 4 05 04 pm](https://cloud.githubusercontent.com/assets/203725/25767267/a5c53250-31ac-11e7-9dc1-62476ff55623.png)

**Comment by ngokevin** [comment]
Inline example/inspector has been removed from docs since.

Moving to https://github.com/aframevr/aframe-inspector/issues/129
