### ISSUE TITLE
user height is removed on desktop when entering full screen

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2605]
**Description:**

1. Open A-Frame scene on desktop.
2. Enter full screen (`f` or press goggles icon)

Expected:
Camera Y stays at 1.6

Actual:
Camera Y goes to 0

- A-Frame Version: Master
- Platform / Device: Desktop/Chrome
- Reproducible Code Snippet or URL: https://a-frobot.github.io/aframe/examples/test/geometry-gallery/

**Comment by cvan** [comment]
@caseyyee is this the same bug you were talking about?

**Comment by caseyyee** [comment]
Seems to work for me.   The user height issue was resolved a few weeks ago, and was due to stageParameters returning null.

**Comment by dmarcos** [comment]
I'm going to close this. Please reopen if someone can still reprodude
