### ISSUE TITLE
Enter VR button disappears after exit VR, in Samsung & Oculus browsers

### ISSUE THREAD

**Issue by mkeblx** [aframevr/aframe#2614]
Can observe it is momentarily shown before being hidden.

- A-Frame Version: 0.5 / master
- Platform / Device: Oculus Browser - Gear VR
- Reproducible Code Snippet or URL:
https://aframe-master.glitch.me

**Comment by cvan** [comment]
@machenmusik, @caseyyee, or @mkeblx (!) – someone who has a functional Oculus Browser device: can you take a looksie?

(I'm waiting on a new Samsung Gear VR case)

**Comment by mkeblx** [comment]
Will do.

**Comment by cvan** [comment]
thanks, @mkeblx. I'll debug it once I get my new Samsung Gear VR; if you (or someone else) can get to it before then, sweet!

**Comment by cutec-chris** [comment]
How is it possible to debug this ? 
Does entering VR work for someone ? For me the Oculus Browser only shows an Window with the Scene.

**Comment by weddingdj** [comment]
I tested aframe.io in the new Gear VR 2017 and the VR enter button disappears even before I can click on it to enter VR. The site loads, the button is visible for a brief moment, then it disappears. Mabye it has something to do with the mobile version / css of aframe.io

**Comment by machenmusik** [comment]
I wonder if the old code to auto-enter VR (by necessity) for Carmel Developer Preview is trying and failing with Oculus Browser.  But previously for me pages were loading in 2D with enter-VR button visible just fine with Oculus Browser.  Did this just change recently?

**Comment by dmarcos** [comment]
Can we test with 0.4.0?

**Comment by machenmusik** [comment]
On the assumption that most will be using Oculus browser now, maybe we should remove auto-enter-vr from default scene components, and those that need can add manually? @dmarcos if you like that approach I can do quick PR

**Comment by weddingdj** [comment]
I investigated and it looks like if the exit-vr event is not triggered.

**Comment by weddingdj** [comment]
When loading a scene:
![screen shot 2017-06-07 at 22 18 57](https://user-images.githubusercontent.com/3025886/26909579-b58af476-4bcf-11e7-8c33-a91c1b310402.png)

If I touch the touch pad of the controller:
![screen shot 2017-06-07 at 22 20 27](https://user-images.githubusercontent.com/3025886/26909587-c2d22c9e-4bcf-11e7-981c-3fdf270ba266.png)

No output when entering or leaving VR mode.

**Comment by dmarcos** [comment]
@weddingdj thanks for investigating! Is that with current master? `auto-enter` vr was disabled recently.

**Comment by weddingdj** [comment]
Yes, it is the current master. I put some debug statements into the exitVR method and it is never called. To me it looks like that the VR controller is exiting VR mode but a-frame still thinks it is in VR. That's why the camera rotation after exiting is the same angle as in VR before, and, of course, no enter VR button is shown.

**Comment by ngokevin** [comment]
Entering VR itself works fine though right?

**Comment by weddingdj** [comment]
Yes, entering VR works fine.

**Comment by dmarcos** [comment]
requestPresent is failing. Is this the Oculus Browser or the Samsung one

**Comment by weddingdj** [comment]
The Oculus Browser.

**Comment by dmarcos** [comment]
`requestPresent` is clearly failing saying that it requires user gesture. I don't understand how it's entering VR. Is it the polyfill taking over?

**Comment by machenmusik** [comment]
@dmarcos I don't think you merged #2707, was auto-enter disabled some other way?

**Comment by machenmusik** [comment]
Perhaps auto enter is attempted and fails in such a way that messes up subsequent exit after manually entering.  Try with #2707 included maybe?

**Comment by weddingdj** [comment]
I tried with #2707 but still no success. Is it possible that the click on the back button of the Gear VR controller is just not taken into account by a-frame? Any hint where I could debug in the code?

**Comment by dmarcos** [comment]
I would look into the `exitVR` button of `a-scene`: 

https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L229

Is `exitVRSuccess` ever called?

**Comment by weddingdj** [comment]
No, it is never called. These were my debug statements (non of them were called):

```
exitVR: {
      value: function () {
        var self = this;

console.log('0');
        // Don't exit VR if not in VR.
        if (!this.is('vr-mode')) { return Promise.resolve('Not in VR.'); }

console.log('1');
        exitFullscreen();

console.log('2');
        if (this.checkHeadsetConnected() || this.isMobile) {
console.log('3');
          return this.effect.exitPresent().then(exitVRSuccess, exitVRFailure);
        }
console.log('4');
        exitVRSuccess();
        return Promise.resolve();

        function exitVRSuccess () {
console.log('EXIT VR SUCCESS');
```

**Comment by dmarcos** [comment]
@weddingdj just curious. do you use a remote console or something to see the logs on GearVR?

**Comment by weddingdj** [comment]
Yeah, I use a remote console.

**Comment by weddingdj** [comment]
@ngokevin should I test your fix?

**Comment by ngokevin** [comment]
That'd be helpful! I will be around to test it in an hour.

**Comment by weddingdj** [comment]
I applied your changes but it did not work.

**Comment by ngokevin** [comment]
Yeah, I just tried myself. I guess it means Oculus Browser may not be firing `onvrdisplaydeactivate` as the WebVR API says it should. Asking them now in the PR. Or here. Does Oculus Browser implement `onvrdisplaydeactivate`, or is there another agnostic way to detect exit VR so A-Frame can handle it.

**Comment by DigiTec** [comment]
Why would we fire onvrdisplaydeactive? We aren't unmounting. The spec seems pretty clear here.

> onvrdisplaydeactivate A user agent MAY dispatch this event type to indicate that something has occured which suggests the VRDisplay should exit presentation. For example, if the VRDisplay is capable of detecting when the user has taken it off, this event SHOULD fire when they do so with the reason "unmounted".

We are firing or should be firing onvrdisplaypresentchange

> onvrdisplaypresentchange A user agent MUST dispatch this event type to indicate that a VRDisplay has begun or ended VR presentation. This event should not fire on subsequent calls to requestPresent() after the VRDisplay has already begun VR presentation.

**Comment by ngokevin** [comment]
Thanks, I'll use that.

**Comment by machenmusik** [comment]
Thx Justin

**Comment by the-max0r** [comment]
Just tested the example from https://aframe-master.glitch.me and now the enter vr button does not disappear. Tested on Samsung Galaxy S7 with Gear VR 2 in Oculus browser.

**Comment by weddingdj** [comment]
It does not work when testing https://aframe-master.glitch.me in Oculus browser, Gear VR with controller, Samsung Galaxy S7. The button still disappears and the camera rotation is wrong after leaving VR mode.

**Comment by the-max0r** [comment]
@weddingdj I tried it yesterday successfully. I also experienced weird caching behavior from the Oculus browser. Try to open the link in a private browser tab to avoid loading a cached version.

**Comment by the-max0r** [comment]
@weddingdj You are correct. I misread the issue title. When accessing the a-frame examples from https://a-frame.io (with a-frame 0.5.0) there was no enter vr button on Gear VR2 for me in the first place (couldn't enter vr mode at all).
When using a-frame master as in https://aframe-master.glitch.me, the enter vr button disappears after exiting vr mode (as this issue title suggests). Sorry for the misunderstanding. The entitled bug still persists.
