### ISSUE TITLE
No BlendCharacter in Three.js r85

### ISSUE THREAD

**Issue by takahirox** [aframevr/aframe#2616]
**Description:**

`THREE.BlendCharacter` has been removed from Three.js r85.

So maybe we need to rewrite our `blend-character-model.js` in reference to  [Three.js webgl_animation_skinning_blending example](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_animation_skinning_blending.html) or make our `THREE.BlendCharacter`.

**Comment by takahirox** [comment]
Related thread in Three.js https://github.com/mrdoob/three.js/pull/11152

**Comment by ngokevin** [comment]
We can still pull it from the examples directory through Node, right?

**Comment by takahirox** [comment]
I'm not sure Node well but is it possible to pull it from Three.js r84 example even if we bump Three.js into r85?

https://github.com/mrdoob/three.js/tree/r85/examples/js
(`THREE.BlendCharacter` has been removed from Three.js r85 example)

Even if we can, it's no longer maintained by Three.js so it wouldn't work with the latest Three.js someday.

**Comment by ngokevin** [comment]
Can we convert the model to glTF?

**Comment by donmccurdy** [comment]
> Can we convert the model to glTF?

Probably yes. If so, the animations can work similarly. Is upgrading to three.js r85 planned for 0.6.0, or waiting until next release?

**Comment by ngokevin** [comment]
I think it could wait, perhaps while post-processing support improves.

**Comment by takahirox** [comment]
I'd like to bump Three.js to the latest revision right after 0.6.0 release, before Three.js supports VR + Post-Processing. (Maybe we can't do that for 0.6.0 due to the last minute for the release)

Because I want to update `GLTF2Loader` as soon as possible, and I think it still takes a time til Three.js's post-processing support.

BTW I don't think I followed the discussion above. Would we convert the model to glTF and remove `blend-character-model.js`?

**Comment by ngokevin** [comment]
Yeha, we can do that. Ideally, we could get rid of blend-character-model, even buy in on an animation mixer component.

**Comment by donmccurdy** [comment]
> I'd like to bump Three.js to the latest revision right after 0.6.0 release, before Three.js supports VR + Post-Processing. (Maybe we can't do that for 0.6.0 due to the last minute for the release)

+1

> Because I want to update GLTF2Loader as soon as possible

Let's start a new issue to discuss how/when we want to make this transition. Opened #2693.

> Ideally, we could get rid of blend-character-model, even buy in on an animation mixer component.

+1 for moving `blend-character-model` out of core if we can. Adding `animation-mixer` to core is fine by me, although we don't really need it for just hand controls.

**Comment by takahirox** [comment]
OK, got it.
Let's close this issue when we remove `blend-character-model`.

**Comment by takahirox** [comment]
Note: Seems like `VRControls` and `VREffect` will be removed from Three.js in r86, r87, or later.
https://github.com/mrdoob/three.js/issues/11301

**Comment by donmccurdy** [comment]
Do we know an ETA on r86?

**Comment by takahirox** [comment]
Perhaps soon? I'm asking Ricardo now.

**Comment by takahirox** [comment]
Let's start working on this once we release 0.6.1

**Comment by donmccurdy** [comment]
Are there source files for `oculus-hands/v2/leftHand.json` and `oculus-hands/v2/rightHand.json`? I'd like to try converting them to glTF, but don't know of any way to import three.js JSON files back into Blender. 

/cc @feiss

**Comment by feiss** [comment]
What about using some threejs exporter?

**Comment by donmccurdy** [comment]
It looks like [most are geometry-only](https://github.com/mrdoob/three.js/tree/dev/examples/js/exporters) except MMD; I can give that a try though.

**Comment by donmccurdy** [comment]
Not seeing any real conversion options without the original models, so just going with #2876.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/2876
