### ISSUE TITLE
Opacity issues with text component

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe#2619]
I've just noticed that the `text` component `opacity` parameter is not working as expected:
When the opacity goes below a certain value (`~0.4`) the text abruptly disappears.

![2017-04-24_14-48-21](https://cloud.githubusercontent.com/assets/782511/25337754/5bb3fdf2-28fd-11e7-8fa3-e98427af963f.gif)

I've tried both in my original repo and on @bryik and it's working as expected so it should be something introduced in the custom sdf function (https://github.com/aframevr/aframe/blob/master/src/shaders/sdf.js)
@machenmusik do you mind taking a look at it or explain the changes you did on the `sdf.js` as I remember you commented something to improve rendering but I don't remember correctly. 
Maybe we could have both versions? the original sdf.js and the current one with another name as a modified version as fadein/out opacity is a very common feature that we should support correctly.

**Comment by machenmusik** [comment]
two questions to start:

what browser and os?
what font, and msdf or sdf?

**Comment by machenmusik** [comment]
looks like the msdf shader is incorrectly applying opacity before discards... sdf shader looks right... can you confirm sdf is ok and msdf (default) is broken?  if so, easy fix.

**Comment by fernandojsg** [comment]
@machenmusik sure
 
Steps to reproduce:
- https://aframe.io/aframe-inspector/example
- Add a new empty entity
- Add `text` component
- Set `value` to `TEXT`, leaving the rest of the parameters as default (shader is `sdf` by default)
- Modify the `opacity`

I've tried on Windows10 with Firefox 55.0a1 and Chromium 56.0.2910.0 and both seems to be broken

**Comment by fernandojsg** [comment]
@machenmusik I just saw your PR, but I'm having the problem on `sdf` that it's the default currently

**Comment by machenmusik** [comment]
no, actually msdf is the default text font/shader...  can you try #2620 and see if it fixes for you?  worked locally for me

**Comment by machenmusik** [comment]
(some more detail on default shader - because the default font is actually msdf, the shader actually used gets changed under the hood even when set to sdf)

**Comment by fernandojsg** [comment]
Ouch, I didn't know that, we should do something as right now it's misleading to see `sdf` but it's using `msdf`.
I'll give it a try later and let you know, thanks!

**Comment by machenmusik** [comment]
that was the result of discussions where only font that was msdf is the default one, every other font is sdf, and we didn't want to make everyone override shader as well as font.  maybe making default property something like auto-sdf would be clearer (pick sdf or msdf depending on font)
