### ISSUE TITLE
HIGH CPU USAGE

### ISSUE THREAD

**Issue by syedf** [aframevr/aframe#2622]
i am using videosphere on my project and have noticed high CPU usage in pc, usually causing heavy lags and on mobile, the mobile heats up really quickly and there is quick battery discharge due to this. is there any fix?

- A-Frame Version: 0.5.0 (Date 14-04-2017, Commit #417e890)
- Platform / Device: One plus 2 / Dell Laptop 4GB ram
- Reproducible Code Snippet or URL:

**Comment by ngokevin** [comment]
Not much to do. Videos in general are high CPU usage, more so as a texture. Up to the browser to optimize it.

Not much to do for mobile, they aren't super equipped to handle VR, and we'll using the WebVR polyfill so it's not a true optimized implementation.
