### ISSUE TITLE
Proposal: add Pointer Lock to look-controls only for desktop fullscreen mode without headset

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2625]
**Description:**

Pointer Lock is an easier way to look around on desktop than mouse-drag. Mouse-drag also has problems that it triggers clicks on time users move. We could add Pointer Lock to the default control scheme if:

1. User is on desktop
2. User does not have a headset detected
3. User enters fullscreen mode

It seems like Pointer Lock doesn't prompt permissions on Firefox and Chrome anymore too when I try Pointer Lock example on MDN with user gesture. So it's not intrusive, use the VR Button click as the user gesture.

We maintain the mouse-drag for now when not fullscreen.

**Comment by dmarcos** [comment]
A slightly tangential topic: Should we also consider a screen based raycaster when we're not in fullscreen? 
Another question: Do people use the fullscreen mode? I personally either go to VR or use it in non fullscreen. I see fullscreen useful for probably the embedded case if the preview is very small.

**Comment by ngokevin** [comment]
I don't like that screen-based raycasting conflicts with using the mouse to look around. `aframe-mouse-cursor-component` is available for those that want it. If you have a scene you can't look around or move and interact with mouse raycasting, it's almost the same as a 2D webpage?

If I were to engage in a site on plain desktop, I think I'd use full screen if it offered me Pointer Lock. Also makes it easier if people want to build traditional 3D sites (WASD + Mouse + wall collisions).

**Comment by banada** [comment]
Pointerlock would be really valuable for me, I'd be glad to help with the implementation!

Pointerlock on focus seems most natural to me. Mousedrag is a drag D;

**Comment by ngokevin** [comment]
What are the cases against just having Pointer Lock always? It used to be we didn't like the Permissions prompt, but if we use the User Gesture, the user has intended to interact with A-Frame and no permission will pop up.

**Comment by banada** [comment]
What if there are multiple Aframe scenes on a page, or lots of other content on the site to scroll through?

**Comment by ngokevin** [comment]
Multiple A-Frame scenes are not supported. Even so, would Pointer Lock be intrusive? Needing to hit ESC to disengage and continue on.

**Comment by banada** [comment]
The only other situation I can think of is if there is lots of content at the top of a page and an A-Frame scene at the bottom. The user could be confused as to why there is no pointer.

I am all for Pointer Lock, though. What is the current third-party component?

**Comment by ngokevin** [comment]
Pointer lock is only engaged if you click a scene, so that's not possible

**Comment by ngokevin** [comment]
The best component to look at is A-Frame Extra's Universal Controls.

**Comment by donmccurdy** [comment]
+1 from me for including pointerlock with `look-controls`, at least as an option.

Side note: I've needed a [small hack](https://github.com/donmccurdy/aframe-extras/blob/master/src/controls/mouse-controls.js#L123-L134) to disable pointerlock when in inspector mode. Probably want to do the same for `look-controls`.

**Comment by richardanaya** [comment]
I like this idea and think this really should be in by default.  It's painful to develop by dragging the mouse cursor around and really doesn't provide that great of an experience for desktop users checking out aframe experiences.

**Comment by ngokevin** [comment]
Yeah, I'm in favor of a Pointer Lock on by default. I shared some A-Frame stuff to people on desktop and the click-drag is not usable. For default desktop mode, I'd favor Pointer Lock/a-cursor versus Click-Drag/mouse-cursor (they conflict anyways).

There's no permissions hanger anymore since it's activated on click. Try: https://webvr.donmccurdy.com/checkpoints/
