### ISSUE TITLE
License for Examples

### ISSUE THREAD

**Issue by AndreaMonzini** [aframevr/aframe#2626]
Hello,

some examples are linked to Glitch only where I'm not able to read clear license for the examples.
I prefer to use Github for local development and where I can find a clear license ( MIT ).

Is it possible to have all examples on Github too if someone like me do not want to use Glitch?

Thank you.

**Comment by ngokevin** [comment]
Most of the examples are on GitHub too under MIT, including the one in the READMEs. I'll try to make sure to include LICENSES on Glitches too.
