### ISSUE TITLE
BUG: in registerPrimitive, "mappings" is case-sensitive

### ISSUE THREAD

**Issue by morandd** [aframevr/aframe#2629]
The keys in the "mappings" struct in registerprimitive are case-sensitive and must be lower case to work.
This is totally non-obvious. 

Could you either add a mention about this in the doc page 
  https://aframe.io/docs/0.5.0/primitives/#register-a-primitive

or resolve this in primitives.js.  I think that the DOM is returning the element attribute names using either lower case or whichever case the user happened to use, but there are a number of instances like "mappings[attr]" which is a case-sensitive lookup between the DOM attribute and the mapping name.

There is something about camelCase in addComponentMapping but it's not clear to me what this is.

- A-Frame Version:  0.5.0
- Platform / Device: all
- Reproducible Code Snippet or URL:

AFRAME.registerPrimitive('a-myNewComponent', {
	defaultComponents: {
		myNewComponent: {}
	},
	mappings: {
		width: 		'myNewComponent.width', // fine
		defaultColor: 'myNewComponent.defaultColor', // Should work, but fails
		lineopacity:	'myNewComponent.lineOpacity' // works if I do this
	}
})

**Comment by ngokevin** [comment]
We can document it. Note all HTML attributes are lower case on the Web.

**Comment by morandd** [comment]
thanks!

**Comment by ngokevin** [comment]
fixed
