### ISSUE TITLE
I can't use an entity attribute twice?

### ISSUE THREAD

**Issue by kurai021** [aframevr/aframe#2632]
I'm developing a Vocaloid viewer with a-mmd.js and ar.js but is not possible to reuse my entities twice not even removing it from the scene.

I hope the music and vmd file is reloaded, but only the mmd file is loaded again.

The script is located here: https://gist.github.com/kurai021/1187ec95e0f438d18ecd79b92f799c0c

What I'm doing wrong?

**Comment by dmarcos** [comment]
I'm not sure I understand the problem. What do you mean by using your entities twice. Can you come up with a simpler fully functional example?

**Comment by donmccurdy** [comment]
@kurai021 I would try cloning the element before re-attaching it. In jQuery: 

```js
$el = $el.remove().clone();
```

Hopefully that solves it, but in either case a simple example would be helpful. :)

See also:

* https://github.com/aframevr/aframe/issues/1444
* https://github.com/aframevr/aframe/issues/2425

**Comment by kurai021** [comment]
Hi. Both options create an entity with different attributes, but first remove the entity created with the other option (if exist).

**Comment by donmccurdy** [comment]
@kurai021 I don't understand what you mean, sorry. What options do you refer to? A simplified version of your script (showing only what's necessary to reproduce the problem) would be helpful.

**Comment by kurai021** [comment]
OK, I could solve it, the problem is that by default it is called THREE.Cache.enabled = true, that seems to prevent the reuse of textures, audio, images etc ... once they were already used and removed from the entity. Would not it be more practical to keep it disabled (I don't know if could be better to save memory) or to pass a method to configure the cache in Three.js?

**Comment by dmarcos** [comment]
What do you mean by preventing reuse? Can you be more specific so we can understand the problem and your use case? The THREE cache is going to store a downloaded file so you don't fetch it over the network multiple times. It is what you want in most cases and this is why is a sensible default.

**Comment by kurai021** [comment]
I mean, prevent reinitialization of entities. I don't have a simple example (with codepen as example) but you can check my use case in my repo https://github.com/kurai021/aframe_demos, open ar_vocaloid example. Disabling cache I can reuse sounds and textures without cloning, And I guess could be better for memory but bad for network as you say

**Comment by ngokevin** [comment]
I don't think there's anything to fix. If you have a technical question, you can head to http://stackoverflow.com/questions/tagged/aframe and clarify the question a bit.
