### ISSUE TITLE
Disabling look-control doesn't remove grab cursor 

### ISSUE THREAD

**Issue by a-barbieri** [aframevr/aframe#2633]
**Description:**

- A-Frame Version: 0.5.0 (Date 10-02-2017, Commit #110055d)
- Platform / Device: OSX 10.12 Chrome 57
- Reproducible Code Snippet or URL: https://codepen.io/deva/pen/eWgYeo

In my application I would like to remove the *look controls* and set some custom behaviours.

I removed controls from the camera as display below but I can still see the grab-cursor while clicking/dragging the scene.

```
<a-camera look-controls-enabled="false" wasd-controls-enabled="false">
```

**Comment by ngokevin** [comment]
In `src/components/look-controls.js`, the code should check to see if `this.data.enabled` before adding the class on the document body for the cursor. Help wanted!

**Comment by gurumukhi** [comment]
Created PR : https://github.com/aframevr/aframe/pull/2637

**Comment by gurumukhi** [comment]
Created new PR - https://github.com/aframevr/aframe/pull/2642/files

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/2642
