### ISSUE TITLE
a-grabbing class applied on 360 video on mouse mouse.

### ISSUE THREAD

**Issue by aminasyeda** [aframevr/aframe#2635]
I have a problem with the 'a-grabbing' class on a 360 video. 

Steps to reproduce: 
Right click on a 360 video. Click 'Inspect'. Without doing a mouse-click get the mouse back to the video. The video rotates with just the mouse mouse (with no grabbing/dragging of the mouse). One of the other ways to reproduce this issue is to click repeatedly on a video embedded in an iframe, drag the iframe and release the mouse on the video. Apparently, the 'a-grabbing' class gets added to the body element in such cases. 
The behavior is the same even if I try to remove the grabbing class by adding a mouseMove event listener. Please advise.

Please see the behavior on : https://aframe.io/examples/showcase/videosphere/

- A-Frame Version: 0.5.0 (Date 10-02-2017, Commit #bf8b8f9)
- Platform / Device: Windows/ Linux/ Chrome

**Comment by mkeblx** [comment]
Something like making `mouseDown` method only handle primary button should be all that's needed.. `if (event.button !== 0) { return; }`

**Comment by BhuvanaMeenakshi** [comment]
I want to work on this

**Comment by mkeblx** [comment]
BhuvanaMeenakshi this should be fixed in #2647
