### ISSUE TITLE
Primitives can't define component values in transform functions without defining equivalent mapping values

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#264]
This is problematic because we want primitives to be "smart" and able to configure components without exposing those components on the dom element.

For example, for the sphere primitive, I want a single simple `segments` attribute that sets both segmentsHeight and segmentsWidth for the user. So that `<a-sphere segments="10">` results in `segmentsWidth = value` and `segmentsHeight = value / 2`. I can't do that without creating `segments-width` and `segments-height` mappings, though. And when I adjust those values via a transform function, they are added to the primitive instance in the dom, which means we lose the magic-behind-the-scenes of `<a-sphere segments="10">`, and instead get `<a-sphere segments="10" segments-width="10" and segments-height="5">`

**Comment by ngokevin** [comment]
I think this is too magical. If we want features like that, it should handled at the component level.
