### ISSUE TITLE
Mixins not working with a-text primitive

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#2643]
Mixin is not properly applied to primitive.

```html
    <a-mixin id="textstyle-primitive" width="3" align="center" color="black"></a-mixin>

    <!-- color, width and alignment not applied -->
    <a-text value="Hello world!" mixin="textstyle-primitive" position="0 -0.25 0"></a-text>
```
Could also apply to other primitives as well, though I haven't checked yet.

- A-Frame Version: 0.5
- Platform / Device: All
- Reproducible Code Snippet or URL:
http://codepen.io/caseyyee/pen/vmmqpB?editors=1010

**Comment by ngokevin** [comment]
Mixins only work with the components. You can do `<a-mixin id="textstyle" text="width: 3; align: center; color: black">`

**Comment by caseyyee** [comment]
![image](https://cloud.githubusercontent.com/assets/1560884/25595596/232ac146-2e7a-11e7-9e19-c2877041042a.png)

Should probably make clearer how to use mixins in primitives.  I understand now why it works this way, but it's definetly a source of confusion.
