### ISSUE TITLE
Faster Adoption by Non-programmers

### ISSUE THREAD

**Issue by stevel4857** [aframevr/aframe#2644]
**Description:**

- A-Frame Version: 5
- Platform / Device: Windows 10 Gaming Rig
- Reproducible Code Snippet or URL: Not the Issue

 

Thank you for creating this coding language. I did learn three.js a few years ago and it was a monster. This should seriously be part of HTML specs. Amazing work. I can't thank you all enough. 

I'm posting here because it seems logical even though it could be considered a help issue. I have noticed on codepen that all of the experiments in AFrame stop dead at any interactivity. So, the assimilation and saturation is huge when just adding elements to a static scene. But once a person tries to add interactivity such as look here and teleport or click this and change that support falls apart. Suddenly it's assumed that one has years of programming experience or even has time to study it just to make simple interactivity. If I had to spend hours trying to learn back end languages in order to create an href tag I never would have become a web designer in 1991. 

So, my request is a code snippet section in GitHub. For instance, I borrowed simple code and read the docs and figured this out: 

To Teleport.

Header code:
```
<script>
  AFRAME.registerComponent('set-camera', {
    schema: {default:''},
    init() {
      const camera = document.querySelector('a-camera');
      this.el.addEventListener('click', () => {
       camera.setAttribute('position', this.data);
      });
    }
  });
</script> 
```

HTML code:

`<a-sphere color="#F44336" set-camera="0 2 -189"></sphere>`

To Set rotation:

Header Code:

```
<script>
AFRAME.registerComponent('set-rotation', {
    schema: {default:''},
    init() {
      const camera = document.querySelector('a-camera');
      this.el.addEventListener('click', () => {
       camera.setAttribute('rotation', this.data);
      });
    }
  });
</script>
```

HTML
`
<a-sphere set-rotation="0 90 0"></sphere>`

and on and on. Please add simple scripts as a link to aframe.io and examples. 

This will speed adoption much faster I believe. I am in the process of completely learning everything now because of what aframe can do. I believe once people can add interactivity it will inspire those that want to program at a higher level. Does this make sense?

**Comment by ngokevin** [comment]
Components are supposed to solve this. Bundles of JS that can be consumed via HTML.

Gaze Teleport: https://github.com/donmccurdy/aframe-extras/tree/master/src/controls
Set on Event Listener: https://github.com/ngokevin/kframe/tree/master/components/event-set

These can be found on https://aframe.io/registry/

I am updating docs now, thanks for the issue.

**Comment by stevel4857** [comment]
Thanks, Kevin. This is fantastic stuff. This was the issue I was having
that I didn't realise these components did that. If the event component was
part of the docs in a way for one would see that as the next step. So,
build a static environment, add interactivity by including this specific
component. Maybe drill down in a blog post about how the simpler component
using events was programmed so that someone could follow the logic. My fear
is that many web designers see javascript includes as walled gardens and
can't even figure out how the code actually works.

I am having an issue with the other link you sent me. I downloaded the
GitHub folder and found that the files are not in a position in relation to
the index.html pages.I assume it's a GitHub thing. I'll figure it out.

If you are ever in Denver look me up. Do you know anyone doing this work
here in Denver?

I'm also looking at starting a WebVR Meetup here and possibly just promote
A-Frame if I don't have any ReactVR fans locally. Thoughts on this idea?

Thanks again for a truly awesome tool.

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377

**Comment by ngokevin** [comment]
There's also https://aframe.io/school/, the docs have the 360 image gallery guide that goes over the interactivity and event setter with link to demos, and we're currently updating docs too

**Comment by stevel4857** [comment]
I will check out the school. Thanks. I'm working on this at the moment:
http://cablecenter.org/vr/chof2017/

I've used your events component for interactivity and it makes life simple
for sure. The only one complete is Steve Burke at the very beginning. If
you click on his picture it brings up text and videos. Off line the videos
work great but online the second video doesn't show up but does play. On
Android phones it doesn't play.

As you can see I'm not afraid of code and hack entire blocks of it to get
what I want. I do need to slow down, go back and cover the basics. I guess
this is how I learn, I jump in and realise what I don't understand later.

It looks like I need a true preloader for the videos and audio. The audio
intro gets messed up because of the video loading I believe.

I know someone has done experiments with YouTube videos and Mr. Doob had
examples a while back on adding YouTube videos three.js but this may be an
issue for me. I have 20 years x 6 videos that I wanted to add into the
exhibit. Ambitious, yah, maybe even crazy.

Still, this is what I have been waiting for. I'd be happy to help out in
any way I can. If you know anyone that I can pay to help with the video
aspects and preloading I do have a budget.

The events component is great. I'm wondering if the event component can do
animation? I see that event-set__8="_event: click; _target: #myitem;
position: 0 2 4;" But could I do aniamtion somehow like
event-set__8="_event: click; _target: #mycamera; animation.to: 0 2 4;"?

Thanks again!

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377
