### ISSUE TITLE
Aframe's asset caching breaks threejs loaders using ArrayBuffer or Blob responseTypes

### ISSUE THREAD

**Issue by eng1neer** [aframevr/aframe#2649]
I was trying to implement aframe wrapper around threejs ObjLoader2 (https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/OBJLoader2.js) and found an issue when an asset defined in a-assets tag and then used by ObjLoader2 was cached in a text format while the loader was requesting it as an ArrayBuffer:

https://github.com/aframevr/aframe/blob/v0.5.0/src/core/a-assets.js#L102

Loader received a string when it was expecting ArrayBuffer.

Other loaders from threejs examples may be affected too.

- A-Frame Version: 0.5.0
- Platform / Device: All

**Comment by ngokevin** [comment]
On A-Frame master, you can do `<a-asset-item response-type="arraybuffer" src="model.gltf"></a-asset-item>`
