### ISSUE TITLE
how to kill mouseenter trigger in an animation after playing once

### ISSUE THREAD

**Issue by shikuru** [aframevr/aframe#2650]
i have an object i want to go from state A to state B and stay there while being triggered by mouseenter, thing is it keeps rerunning the animation when you re enter the shape, is there any way to kill the trigger once the animation ends?

A-frame 0.50
pc
<a-animation easing="ease-in-out" begin="mouseenter" attribute="scale" dir="normal" dur="2000" to="1 40 1" repeat="0" delay="1000" ></a-animation>

**Comment by sachinaglave** [comment]
@shikuru  You can remove event handler which is responsible for starting an animation on animation end.

<a-scene>
      <a-image id="obj" src="xyz.jpg" position="0 0 -10" height="6" width="9" scale="1 1 1">
             <a-animation attribute="position" from="0 0 -10" to="-5 0 -10" begin="startAnim" dur="1000" fill="forwards">
      </a-image>
</a-scene>

---------------Javascript-----------------

var startAnimListener = function(){
   document.querySelector('#obj').emit('startAnim');
}

var removeAnimListener = function(){
    document.querySelector("#obj").removeEventListener("mouseenter", startAnim);
}
document.querySelector("#obj").addEventListener("mouseenter", startAnimListener);
document.querySelector("#obj").addEventListener("animationend", removeAnimListener);

**Comment by ngokevin** [comment]
We've deprecated a-animation. Try https://github.com/ngokevin/kframe/tree/master/components/animation and file issues, and component will be merged in in the future.

With animation component you can set `startEvents`, `pauseEvents`, and `resumeEvents`. The component will also automatically stop all related animations to not conflict.
