### ISSUE TITLE
Doing `.setAttribute(component, 'foo: bar')` may clobber properties

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2651]
**Description:**

http://stackoverflow.com/questions/43788105/issue-with-aframe-where-setattribute-reset-previous-proprieties

When passing a string as the second argument for a multi-prop component, A-Frame may be clobbering/resetting existing properties. Update `Entity.setAttribute` to consider this case.

- A-Frame Version: 0.5.0
- Platform / Device:
- Reproducible Code Snippet or URL: http://codepen.io/deva/pen/QvMeom

**Comment by BhuvanaMeenakshi** [comment]
I want to work on this

**Comment by gregfagan** [comment]
Hi @BhuvanaMeenakshi, I wasn't sure if you had a chance to take a look at this yet. It was in an area I recently studied so I thought I'd give it a go. Seeking feedback.

**Comment by BhuvanaMeenakshi** [comment]
Yes @gregfagan you may proceed!
