### ISSUE TITLE
Add Acknowledgements section to FAQ of underlying tech + prior art

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#2653]
I'd love to add a kind-of "Acknowledgements" section, or at the least give shout-outs to three.js, JanusVR, GLAM, SceneVR, which heavily inspired A-Frame's design (i.e., A-Frame's predecessors/inspiration/underlying tech).

FWIW, three.js is really only briefly mentioned in the FAQ under [`What is A-Frame?`](https://aframe.io/docs/0.5.0/introduction/faq.html#what-is-a-frame):

> Under the hood, it is a three.js framework that brings the entity-component-system pattern to the DOM.

<hr>

When the FAQ was moved from the [`aframe-site` repo](https://github.com/aframevr/aframe-site/blob/af9bba5/src/faq/index.md#why-was-a-frame-created) to this repo (afaict, in [commit `778d41e`](https://github.com/aframevr/aframe/commit/778d41ed749dc8be41d661d2ea34df708e8e1f0e#diff-5b8b9581f525ce4013e78375b6d2a544R25)), a few paragraphs were removed, namely this one:

> We felt WebVR development was too difficult and sought tools that would make it faster, easier, and more enjoyable. Over the course of 2015, the MozVR team was creating many WebVR experiments with three.js. To speed up workflows, we began to experiment with custom elements wrapping three.js. In creating these tools, we drew inspiration from both existing declarative 3D/VR tools (e.g., JanusVR, GLAM, SceneVR), and from game development best practices. As the tools matured, we felt that they might be able to address what we felt were gaps in the market, particularly around ease of use and webbiness.

I think it's fine to cut out the [huge list](https://github.com/aframevr/aframe-site/blob/af9bba5/src/faq/index.md#why-was-a-frame-created) about the motivating limitations/ambitions, but can we add back A-Frame's predecessors/inspiration/underlying tech?

It can go under a separate FAQ answer, but I think it probably makes sense to keep it under the `Why was A-Frame built?` answer. Thoughts?

**Comment by ngokevin** [comment]
I've removed that question in my branch to limit it to questions people actually people ask. three.js is mentioned often, I can give it more in the introduction. However, A-Frame's design is not at all similar to those libraries. Those were more of Josh's language since he was closer to them at the time.

**Comment by ngokevin** [comment]
original langusge is preserved in the initial public release blog post

**Comment by cvan** [comment]
Can we reconsider adding this? I think it's a common enough question to warrant sticking an answer in the FAQ.
