### ISSUE TITLE
GearVR Oculus Browser - Hides VR Button, but fails to enter VR

### ISSUE THREAD

**Issue by shaunmnemonic** [aframevr/aframe#2659]
**Description:**

When loading in the Oculus browser the 'EnterVR Goggles' get hidden because the `auto-enter.js` file tries to auto-enter-vr, but requires a user interaction and the goggles don't re-appear. 

- A-Frame Version: 0.5.0
- Platform / Device: GearVR, Oculus Browser
- Reproducible Code Snippet or URL: Any of the Aframe.io Examples

**Comment by mkeblx** [comment]
This doesn't occur on master.

**Comment by dmarcos** [comment]
@shaunmnemonic Please reoopen if you can reproduce on master
