### ISSUE TITLE
Big size ply model won't load

### ISSUE THREAD

**Issue by jues** [aframevr/aframe#2661]
Hi, how can I load the model like this?
[world - old.ply.zip](https://github.com/aframevr/aframe-boilerplate/files/986207/world.-.old.ply.zip)

- A-Frame Version: 0.5.0
- Platform / Device: edge or chrome with gtx 1060
- Reproducible Code Snippet or URL:

```

<a-scene>

<a-entity id="entity" ply-model="src: url(world - old.ply)" position="0 0 0" rotation="-90 0 0"></a-entity>

</a-scene>
```

**Comment by donmccurdy** [comment]
Hi! Posted a reply on the [other issue](https://github.com/donmccurdy/aframe-extras/issues/148). Going to close this issue out, since the `ply-model` component is only in aframe-extras.

Thanks,
Don
