### ISSUE TITLE
INSPECTOR BROKEN - 'asset' type schema property objects being re-parsed as URLs

### ISSUE THREAD

**Issue by NNskelly** [aframevr/aframe#2662]
**Description:**
As of ~11:30CST May 9, the latest a-frame inspector min.js as retrieved from unpkg.com e.g. by the A-Painter demo is now throwing errors whenever an entity is selected which has a material component with a src or other map (or asset?) property.  The error manifests as a "e.match is not a function" js error in an obscurely nested minified block in which e appears to be the actual parsed asset object, and the function appears to be attempting to re-parse it as a URL or asset ID, e.g. comparing "#"===e[0] and then looking it up as a # id if true, or attempting to parse it as a URL (using string .match) if false.

As a side-effect, many inspector fields for map/asset properties now show as empty boxes with [object] as the source, rather than as previews with the corresponding asset #id as the source.

Edit: in fact, upon further experiments with debugging off, the errors derail the whole Inspector and Scene refresh flow to the point where any material updates in the inspector become impossible.  Definitely a priority bug, I would think.

- A-Frame Version: aframe-inspector@0.5.2
- Platform / Device: Windows Chrome
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/a-painter/

**Comment by NNskelly** [comment]
a variety of other issues, likely related, also show up, some suggesting a corrupted/misfiled canvas context, others that sound like somewhere that _is_ expecting a valid parsed object are instead getting some earlier state e.g. a raw string, although I am having difficulty isolating deterministic repro steps.  Clicking between entities with different types of shader, or with and without materials, seems to re-trigger most types of error, somewhat arbitrarily.
![match_not_a_function](https://cloud.githubusercontent.com/assets/28572171/25866228/5e7e52fc-34bb-11e7-898e-c97832f198b0.png)
![callstack](https://cloud.githubusercontent.com/assets/28572171/25866231/608746d0-34bb-11e7-8178-13cc2a0138f6.png)

**Comment by NNskelly** [comment]
Just found the inspector's independent github.  Would it be worth closing this out here and re-opening it there, or is it already being ingested for action?

**Comment by ngokevin** [comment]
Yes, can you please re-file there? Thanks!
