### ISSUE TITLE
material.wireframeLinewidth has no effect

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2664]
Per [MeshStandardMaterial docs](https://threejs.org/docs/#api/materials/MeshStandardMaterial), the wireframeLinewidth is expected to be ignored on Windows. But I'm not seeing linewidth having any effect in OS X either, which is unexpected.

```html
<a-scene>
  <a-box position="0 1.5 -2"
         material="color: blue;
                   wireframe: true;
                   wireframeLinewidth: 10;"></a-box>
</a-scene>
```

<img width="560" alt="screen shot 2017-05-10 at 9 56 55 am" src="https://cloud.githubusercontent.com/assets/1848368/25910964/08284410-3567-11e7-90c7-df9adc20d4d5.png">

- A-Frame Version: 0.5.0
- Platform / Device: OS X
- Reproducible Code Snippet or URL: http://codepen.io/donmccurdy/pen/QvQzEX

**Comment by caseyyee** [comment]
This is a open issue with three using Chrome with OSX: https://github.com/mrdoob/three.js/issues/10357

It does work with Firefox though.  

Doesn't seem like something we can resolve with A-Frame unless we emulate the line-effect using geometry.

**Comment by donmccurdy** [comment]
Ah ok, thanks. I don't see an especially strong case for mesh-lines in core; `<a-tube/>` can already do that easily, and hasn't been used all that much. Fine with me to track it in three.js and close this issue.
