### ISSUE TITLE
(master) Touching Daydream trackpad causes "TypeError cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by gordonbrander** [aframevr/aframe#2669]
**Description:**

Touching Daydream touchpad causes `TypeError cannot read property 'length' of undefined`. Because of this TypeError, I also seem not to get `axismove` or `trackpadmoved` events.

This is apparently a bug that @dmarcos is familiar with because I was able to [find a fix he landed to try to work around it](https://github.com/aframevr/aframe/blob/2827f9c49934e9b11206bb8bdf1bcb0a82d618dc/src/components/tracked-controls.js#L296). I gather the empty touches array was added in https://github.com/aframevr/aframe/pull/2537 to avoid this problem, but somehow `touches` doesn't seem to make it on to the event? Here is the exact content of the `touchstart` event fired from the Daydream trackpad (captured in Chrome remote devtools):

```
CustomEvent {isTrusted: false, detail: Object, type: "touchstart", target: a-entity, currentTarget: Window…}
bubbles: true
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
detail: Object
eventPhase: 0
isTrusted: false
path: Array(6)
returnValue: true
srcElement: a-entity
target: a-entity
timeStamp: 128821.66500000002
type: "touchstart"
__proto__: CustomEvent
```

Changing https://github.com/aframevr/webvr-polyfill/blob/master/src/touch-panner.js#L48 to read

```javascript
TouchPanner.prototype.onTouchStart_ = function(e) {
  if (e.touches) {
    // Only respond if there is exactly one touch.
    if (e.touches.length != 1) {
      return;
    }
    this.rotateStart.set(e.touches[0].pageX, e.touches[0].pageY);
    this.isTouching = true;
  }
};
```

does solve the problem. After vendoring aframe and hacking that in, I get no more errors, and `axismove` and `touchmoved` events all work.

- A-Frame Version: master
- Platform / Device: Chrome Canary / Pixel XL/ Daydream Controller
- Reproducible Code Snippet or URL: any time Daydream Controller is connected

**Comment by machenmusik** [comment]
yes, there is actually a PR to aframe polyfill to fix this already, but perhaps it hasn't been merged into the version you are using.  @dmarcos do you recall where this stands?

**Comment by gordonbrander** [comment]
@machenmusik just a heads-up... I am using a-frame master from just a couple hours ago.

**Comment by machenmusik** [comment]
looks like this isn't merged / used yet
https://github.com/aframevr/webvr-polyfill/pull/4

the specific change is
https://github.com/chenzlabs/webvr-polyfill/commit/87130ae1ffb8d5c33fe78dc10ea4a0da279eb173

which should be built into
`chenzlabs/webvr-polyfill#avoid-touchstart-collision`

**Comment by gordonbrander** [comment]
@machenmusik note this change wont fix it, since `touches` is still referenced without a check below https://github.com/chenzlabs/webvr-polyfill/commit/87130ae1ffb8d5c33fe78dc10ea4a0da279eb173#diff-4c2e10343ad71eef9d298507c2d3dcadR48

**Comment by machenmusik** [comment]
so the odd part is that it had fixed it at least at one point, but clearly it won't now.  would you like to submit your change as separate PR, and I can close that one?

**Comment by gordonbrander** [comment]
@machenmusik oh oops, looks like we both just created a PR https://github.com/googlevr/webvr-polyfill/pull/228

**Comment by gordonbrander** [comment]
@machenmusik should I also submit a PR to aframevr/webvr-polyfill?

**Comment by machenmusik** [comment]
LOL I closed googlevr/webvr-polyfill#229 in favor of yours, but I left mine in aframevr/webvr-polyfill for now just in case you didn't base yours on the commit at which aframevr and googlevr diverged (and thus you might run into the problem I did with dragging in other changes unintentionally)

**Comment by gordonbrander** [comment]
@machenmusik oh dang, good point. I'm ok to go with either PR. If yours will produce a cleaner merge history then so much the better.

**Comment by machenmusik** [comment]
@gordonbrander if you can submit that to aframevr as well, and it doesn't drag in a bunch of other changes from googlevr, let me know and I will close mine

**Comment by gordonbrander** [comment]
@machenmusik let's just use yours if it has the cleaner commit history.

**Comment by machenmusik** [comment]
@gordonbrander just rebase yours on this commit and you'll be all set

https://github.com/googlevr/webvr-polyfill/commit/4787fe5546e33bb82b9a3981245f39d9e1e136ba

**Comment by machenmusik** [comment]
ok, closing my aframevr polyfill PR as well so you can do yours, thanks welcome aboard @gordonbrander !

**Comment by gordonbrander** [comment]
Interesting... just pulled up webvr.yoga on Daydream and I don't get the same TouchPanner touchstart TypeError.

webvr.yoga is using https://github.com/ryanbetts/aframe-daydream-controller-component rather than the daydream-controls component in `master` so there are likely to be differences.

**Comment by machenmusik** [comment]
The issue stems from how `tracked-controls` handles events.  daydream-controller doesn't use `tracked-controls` but instead runs its own copy of that functionality.  @dmarcos @ngokevin perhaps we should change the internal event names to avoid collision, at the risk of breaking some existing usage?

**Comment by dmarcos** [comment]
@machenmusik what collision are you talking about? I cannot tell by the previous conversation.

**Comment by machenmusik** [comment]
IIRC `tracked-controls` emits events named `touchstart` and `touchend` that clash with the actual mobile events, and mobile Chrome does not appear to allow CustomEvent to set the `touched` array which lies outside event detail.

**Comment by ngokevin** [comment]
Seems like fixed in polyfill.
