### ISSUE TITLE
inactive cameras with look-controls always respond to mouse movement

### ISSUE THREAD

**Issue by morandd** [aframevr/aframe#2671]
When a camera is set to active=false, it should call pause() on itself.

Currently a camera with look-controls will still move in response to mouse movements even when it is not the active camera.  This can be strange/problematic because then when you switch back to the look-control'ed camera it will be pointing in some random direction, since it's been controlled according to onscreen mouse movement even while inactive.

- A-Frame Version: 0.5.0
- Platform / Device: all
- Reproducible Code Snippet or URL:

**Comment by ngokevin** [comment]
The camera doesn't handle any of that logic. `active` just refers to the user's camera, but a camera can be inactive but still controlled. You can `.removeAttribute('look-controls')` temporarily.
