### ISSUE TITLE
Missing icon font inside inspector

### ISSUE THREAD

**Issue by HeinPauwelyn** [aframevr/aframe#2672]
**Description:**

- A-Frame Version: 0.5.0
- Visual inspector: 0.3.0
- Platform / Device: Windows 10
- Browser: Chromium
- Reproducible guideline: Just open the visual inspector on a computer where the icon font is not installed.

On the top on the right side, I could see three buttons for translate, rotate and scale. But I couldn't see the icons. I've seen that the inpector using this code:

```html
<a title="translate" class="button fa fa-arrows active"></a>
<a title="rotate" class="button fa fa-repeat"></a>
<a title="scale" class="button fa fa-expand"></a>
```

So I'm thinking that the icon font you're using is missing in the inspector. The icon font _(probably font awasome I think)_, is not installed on my computer.

![image](https://cloud.githubusercontent.com/assets/16222780/26054408/bb2e3e26-396c-11e7-9bff-9dc3309f7224.png)

**Comment by dmarcos** [comment]
I believe this should be filed against the inspector not aframe. @fernandojsg

**Comment by ngokevin** [comment]
Moved to https://github.com/aframevr/aframe-inspector/issues/475
