### ISSUE TITLE
How to overlay (partially transparent) <a-sky />, like doing that to <img />?

### ISSUE THREAD

**Issue by FateRiddle** [aframevr/aframe#2687]
**Description:**

- A-Frame Version: lastest
- Platform / Device:  web

We are building a tool for 3D view of home decoration, customers can click on a sofa and it will show or hide in the 3D view.

They provide me panorama images of the home background, and a sofa image of the same size but transparent except the sofa part. 

I tried: 
```
<a-sky src='background.jpg' />
<a-sky src='sofa.jpg' />
```
expecting them to overlay. But sofa image block the background, despite being transparent.

How am I going to achieve my goal?

**Comment by ngokevin** [comment]
Support questions should be asked at http://stackoverflow.com/questions/tagged/aframe, you will need to provide even more information that what was filed here in order for us to help.
