### ISSUE TITLE
Remove `scripts/gh-pages.js` script in favour of `ghpages` package

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#269]
It's great: https://www.npmjs.com/package/ghpages

(I use it for the [boilerplate](https://github.com/aframevr/aframe-boilerplate).)

<hr>

Also see aframevr/aframe-core#622.

**Comment by Zeouterlimits** [comment]
Took a quick look at this a few days ago.
Seems that the fourth command:
`npm run browserify -s -- --debug | exorcist dist/aframe.js.map > dist/aframe.js`
won't run on Windows, it errors out, but works on Unix, so I couldn't progress at the time.

Will give this task another go on my Mac (where I don't have the same issue) tomorrow.
