### ISSUE TITLE
Broken link on angle npm page.

### ISSUE THREAD

**Issue by jsimonson2013** [aframevr/aframe#2691]
**Description:**

Following links on the web to create a component, I landed on the [angle npm page](https://www.npmjs.com/package/angle). About halfway down the page, there is a link to the writing a component documentation that is broken. The link reads "how to write a component".

**Suggestion:**

The link should be replaced with this `https://aframe.io/docs/0.5.0/introduction/writing-a-component.html`

**Comment by ngokevin** [comment]
fixed
