### ISSUE TITLE
A-Frame demos crashing in Firefox for Android

### ISSUE THREAD

**Issue by AngelFQC** [aframevr/aframe#2698]
**Description:**
Testing the A-Frame demos with a Sony Z3C, Firefox for Android 53.0.2 crash with VR effect
Testing the demos from the WebVR polyfill, same Firefox works nice. The VR effect from original polyfill looks great in FF for Android

- A-Frame Version:
v0.5.0
- Platform / Device:
Firefox For Android in Sony Z3 Compact
- Reproducible Code Snippet or URL:
A-Frame demos

**Comment by dmarcos** [comment]
@AngelFQC Can I ask you to click through the three.js examples and see if you see any crashes (https://threejs.org/examples/)? I would like to discard that it's not a problem with the particular GPU / drivers that your phone has.

**Comment by AngelFQC** [comment]
I'm trying with the three.js examples, but I see a message saying my broswer does'nt support WebVR for the webvr section examples. There's no crashes
With the Google's WebVR polyfill examples, FF for android works very nice. There's no crashes
The VR effect works fine from A-Frame demos in Chrome

So... there is this bug filed Mozilla's Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1340876. I attached a video with the crash here

**Comment by dmarcos** [comment]
@AngelFQC what about no WebVR exampless? Can you click trough all of them and see if there's any crashes? I would like to see if the are any WebGL incompatibilites with your phone regardless of WebVR.

**Comment by AngelFQC** [comment]
All the no webvr examples works, no crashes :-)

**Comment by stevel4857** [comment]
Webvr crashes on everything I'm using except Chromium. Chromium just won't launch into VR but has a never ending loading. NVidea 1080ti on Win10. I don't expect to hear back since I've been complaining since Monday.

**Comment by ngokevin** [comment]
Chromium is actively being looked at https://github.com/googlevr/webvr-polyfill/pull/267 and we're actively testing browsers... thanks for being patient.

**Comment by dmarcos** [comment]
@stevel4857 Can you provide browser / links to demos you're trying? aframe.io works for me on Vive and Oculus / Windows 10 / Nightly. This issue is about Firefox for Android. Are you also testing on it?

**Comment by machenmusik** [comment]
@stevel4857 you may be having the nvidia driver issue I had - roll back to 378.92

**Comment by dmarcos** [comment]
I'm on 381.78 drivers and everything works for me (GTX 1080 / Windows 10 / Vive / Nightly)

**Comment by AngelFQC** [comment]
In Nightly for Android (Sony Z3C), there is no way to get the VRDisplay, so the WebVR is not so VR

**Comment by AngelFQC** [comment]
Solved now with version 0.6.1
