### ISSUE TITLE
你好可以出 中文文档吗

### ISSUE THREAD

**Issue by LiZheGuang** [aframevr/aframe#2699]

**Comment by dmarcos** [comment]
We would love to help. Could you also provide an English version?

**Comment by dmarcos** [comment]
I translated this in Google translate and it seems it's a request to have docs in Chinese. @ngokevin Who do we know in the Chinese community that could help?

**Comment by ngokevin** [comment]
We know a lot in Taiwan. 

@besteric from Ali translated some of the A-Frame site to Chinese a while back, but there's work involved on how to host that.

**Comment by besteric** [comment]
Yeah, multi-language docs need integrates into the docs

**Comment by takahirox** [comment]
If we also have docs in Japanese, I'll help.

**Comment by ngokevin** [comment]
There's some at http://www.a-framer.com/. I'll look into it after the 0.6.0 release.

**Comment by ngokevin** [comment]
Moving to https://github.com/aframevr/aframe-site/issues/380
