### ISSUE TITLE
Submit A-Frame bundles (uncompressed + minified) to jsdelivr/cdnjs CDNs

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#270]
https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by ngokevin** [comment]
https://github.com/cdnjs/cdnjs/commit/a595217aa3cfaf0efa4cdc2eb8d78f137a02b421

**Comment by ngokevin** [comment]
seems fixed https://github.com/cdnjs/cdnjs/commit/a595217aa3cfaf0efa4cdc2eb8d78f137a02b421
