### ISSUE TITLE
Performance problems when rotating camera

### ISSUE THREAD

**Issue by eng1neer** [aframevr/aframe#2705]
I've set up two simple test cases:

1) 1000 planes are rendered via `a-plane` tag
2) 1000 plane geometries are added via `new THREE.Mesh(new THREE.PlaneGeometry(1, 1))` and then `scene.add(plane)`

On my PC performance in roughly the same when the camera is still ~ 80 fps. However when I start dragging the mouse to rotate the camera the 1st test case shows a performance drop to 15fps, while the 2nd renders the same 80 fps.

Moving camera with wasd controls does not cause fps to drop.

What could be the reason for this performance drop?

The scene doesn't have a cursor, so I guess this cannot be caused by raycaster checking collisions.

- A-Frame Version: 0.5.0 and current master was tested

**Comment by ngokevin** [comment]
Thanks. I made a Glitch https://glitch.com/~abrasive-orchid for this

**Comment by ngokevin** [comment]
I don't get issues with 1000 `<a-plane>`s on my laptop or desktop. Can you check the Glitch and see if you reproduce or see what needs to be changed?

**Comment by eng1neer** [comment]
@ngokevin Thank you, actually, the issue is connected to react or aframe-react which I'm using, I will file an issue in the proper place
