### ISSUE TITLE
Raycaster only updates target objects when elements added/removed

### ISSUE THREAD

**Issue by gordonbrander** [aframevr/aframe#2708]
**Description:** Raycaster component caches raycatching objects by querying for them, then storing them on a property. However, this cache is [only updated/invalidated when an element is added/removed](https://github.com/aframevr/aframe/blob/6511a237a9c762347fbc65c3bcf98b2772691c24/src/components/raycaster.js#L41).

 I ran into this corner case when adding/removing the classname I'm using to mark elements for raycatching. Of course, adding and removing the class will not trigger the `child-attached` event and so the cache will remain incorrect.

**What should happen:** ideally, raycatching should happen on elements that have that class _at time of intersection_.

The caching of this DOM query looks to be a performance optimization. Do we know if the DOM query is actually a bottleneck here?

- A-Frame Version: master
- Platform / Device: all
- Reproducible Code Snippet or URL: n/a

**Comment by gordonbrander** [comment]
Also, stray thought: we should be able to filter out entities with `visible: false` by default, right?

**Comment by ngokevin** [comment]
Refreshing the objects involved query selector and processing through the objects. If you want to refresh the raycaster for corner cases such as these, you can call el.components.raycaster.refreshObjects on demand

**Comment by ngokevin** [comment]
I think the raycaster filters out objects with material.visible = false by default

**Comment by gordonbrander** [comment]
That seems reasonable. Thanks!
