### ISSUE TITLE
Submit A-Frame bundles (uncompressed + minified) to cdnjs

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#271]
https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20_library_name_%20&body=**Library%20name%3A**%20%0A**Git%20repository%20url%3A**%0A**npm%20package%20url(optional)%3A**%20%0A**License(s)%3A**%0A**Official%20homepage%3A**%0A**Wanna%20say%20something?%20Leave%20message%20here%3A**%0A%0A%0A%0A=====================%0ANotes%20from%20cdnjs%20maintainer%3A%0AYou%20are%20welcome%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20then%20just%20opening%20a%20request%20issue%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks!!

**Comment by ngokevin** [comment]
Merging into https://github.com/aframevr/aframe/issues/270 issue
