### ISSUE TITLE
Error in HTML file when exporting from visual inspector

### ISSUE THREAD

**Issue by alexfuser** [aframevr/aframe#2718]
**Description:** The HTML file that the visual inspector exports is wrong when it is opened in the browser. This does not show well the scene that was worked.

- A-Frame Version: 0.5.0
- Platform / Device: Firefox desktop for MAC OX

**Comment by ngokevin** [comment]
Should be filed on https://github.com/aframevr/aframe-inspector, but yeah HTML export is buggy
