### ISSUE TITLE
Ambient occlusion maps require second UV channel

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#2721]
In the process of testing baked occlusion/roughness/metallic, remembered there's a gotcha with three.js's AO implementation: the occlusion map requires a 2nd set of UVs.

Here's a sample model: [metal-rough-cube.zip](https://github.com/aframevr/aframe/files/1050005/metal-rough-cube.zip)

```html
<a-entity obj-model="obj: #metal-rough-cube"
          material="src: ./metal-rough-cube/metalRoughCube_DefaultMaterial_BaseColor.png;
                    normalMap: ./metal-rough-cube/metalRoughCube_DefaultMaterial_Normal.png;
                    roughnessMap: ./metal-rough-cube/metalRoughCube_DefaultMaterial_OcclusionRoughnessMetallic.png;
                    metalnessMap: ./metal-rough-cube/metalRoughCube_DefaultMaterial_OcclusionRoughnessMetallic.png;
                    ambientOcclusionMap: ./metal-rough-cube/metalRoughCube_DefaultMaterial_OcclusionRoughnessMetallic.png"></a-entity>
```

The AO doesn't show up (easier to see this if you only have ambient lighting).

I can "fix" that with this line:

```js
var geometry = mesh.geometry;
geometry.addAttribute( 'uv2', new THREE.BufferAttribute( geometry.attributes.uv.array, 2 ) );
```

That's a requirement I wouldn't expect most users to know about... Do we have any demos using AO through the `material` component? Not sure what we should do here. Some options:

1. Document this in the `material` component docs.
2. Try to detect this in the `obj-model` component and duplicate the UVs.
3. ~~Detect this in the `material` component and duplicate the UVs.~~
4. Remove `material.ambientOcclusionMap` and let the `*-model` components deal with it.

With THREE.GLTF**2**Loader we automatically duplicate UVs, so this is a non-issue. THREE.GLTFLoader, currently used by A-Frame, doesn't support PBR or AO.

**Comment by takahirox** [comment]
> Try to detect this in the obj-model component and duplicate the UVs.
> Detect this in the material component and duplicate the UVs.

I'm wondering if Three.js can do and opened an issue there https://github.com/mrdoob/three.js/issues/11672

Even if Three.js does that in r87, we need an workaround til then tho.

In the options Don suggested, I don't really like letting users manually do this so vote for 2 or 3.

**Comment by takahirox** [comment]
Note from the Three.js thread

> Also, the 2nd set of UVs do not honor offset/repeat

So just copying causes trouble sometimes.
We need to pre-calculate offset/repeat for uv2.

**Comment by donmccurdy** [comment]
> We need to pre-calculate offset/repeat for uv2.

Good to know, but IMO that seems like too much trouble for the `material` component; not enough value to justify it. Have any three.js loaders implemented that?

I lean away from (3) personally. Having the `material` component modify geometry sounds like a bad time.

Agreed that making users manually deal with this is non-ideal, but so far no one has actually reported the issue, which may mean that `material.ambientOcclusionMap` isn't being used enough to justify much work on our part. Perhaps the users who would want aoMaps prefer to use model loaders anyway.

**Comment by takahirox** [comment]
> but IMO that seems like too much trouble for the material component; not enough value to justify it. 

Agreed.

> Have any three.js loaders implemented that?

Not sure but maybe not?

**Comment by donmccurdy** [comment]
Opened #2911. I think documenting the requirements may be Good Enough For Now™.
