### ISSUE TITLE
Move template engine to an aframe-templates repo

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#273]
...and make aframe repo the place to compile the final build.

**Comment by ngokevin** [comment]
Proposing:

I imagine it as:

- **aframe** - What aframe-core is currently. Contains the basic ECS code.
- **aframe-templates** - A-Frame templating engine.
- **aframe-primitives** - Primitives (e.g., `<a-cylinder>`) created using the A-Frame templating engine.
- **aframe-boilerplate** - What "newbies" can clone. Combines `aframe` + `aframe-templates` + `aframe-primitives`. When they do `npm install`, they will get everything.

The allows us to have layers of abstraction such that a developer can jump in at the layer (of difficulty) that suits them. It also makes it more clear for this PR what module libraries should be depending on, `aframe`.

**Comment by ngokevin** [comment]
trying to write a project that has a build step depending on aframe, but aframe's templates and stuff that i'm not using require many extra build steps that core doesn't need.

**Comment by ngokevin** [comment]
Will think about templates later.
