### ISSUE TITLE
A-Frame cursor crashes when looking at some Collada models

### ISSUE THREAD

**Issue by juho-k** [aframevr/aframe#2731]
**Description:**

A-Frame crashes when having a cursor and a Collada model in the same scene, and looking at most parts of the model. For example [this model](https://3dwarehouse.sketchup.com/model/9437690f-9220-4abd-8235-93e2296a0644/Iskren-Marinov-Comp) crashes A-Frame when looking at the paintings. Seems to be the same problem as [here](https://stackoverflow.com/questions/40114053/collada-model-causes-a-frame-to-crash-when-panning-around).

- A-Frame Version: 0.5.0
- Platform / Device: Windows 10

**Comment by bryik** [comment]
[Same issue?](https://github.com/aframevr/aframe/issues/2319)

**Comment by ngokevin** [comment]
Yeah, duping with that. I'll put an update in that issue.
