### ISSUE TITLE
a-asset-item blocks scene loading, even after reaching default timeout of 3s

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#2737]
**Description:**

- A-Frame Version: master
- Platform / Device: chrome, desktop
- Reproducible Code Snippet or URL: http://dev2.ideaspacevr.org/public/test.html
Can be tested with bandwidth throttling on Chrome.

a-asset-item blocks scene loading, even after reaching default timeout of 3s, and even if I set the timeout to 0 on a-assets.

This behaviour is relevant if you want to create an asset-item loading indicator in VR. In order to see the loading indicator (eg. a-plane), the scene must start rendering before the a-asset-items are finished loading.

**Comment by vincentfretin** [comment]
When I tested with aframe 1.3.0 and master (2022-10-06), when the timeout is reached, the loader actually disappear and the model still loads but I have an error with stacktrace #5130

I think we can close this particular issue? The code surely changed since 2017.

**Comment by dmarcos** [comment]
closing this. obsolete
