### ISSUE TITLE
Add `source` path metadata to every relevant doc page to link to source code on GitHub

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2738]
**Description:**

Make the path relative to the GitHub root. For example, at top of every doc page:

```
title: laser-controls
type: components
layout: docs
parent_section: components
source: src/components/laser-controls.js
---
```

I will configure the aframe-site repo to build the URLs depending on the version of the documentation being viewed and show a View Source button.

For example, built URLs:

- **master:** https://github.com/aframevr/aframe/blob/master/src/components/cursor.js
- **0.5.0:** https://github.com/aframevr/aframe/tree/v0.5.0/src/components/cursor.js
- **0.4.0:** https://github.com/aframevr/aframe/tree/v0.4.0/src/components/cursor.js

**Comment by amitsin6h** [comment]
want to work assign me @ngokevin

**Comment by gurumukhi** [comment]
Hi @amitsin6h, thanks for stepping up for this bug. Feel free to work on this bug and create a PR, if you have any questions you can ask on #issues slack channel of a-frame (https://aframe.io/community/#slack).

**Comment by shanalily** [comment]
@ngokevin Are you just asking to change sources such as src/components/laser-controls.js to master/src/components/laser-controls.js, docs-v0.7.0/src/components/laser-controls.js, etc. in every doc page in all of the branches?

**Comment by ngokevin** [comment]
Sorry this was finished
