### ISSUE TITLE
system.update() not called via the web inspector

### ISSUE THREAD

**Issue by wizgrav** [aframevr/aframe#2740]
system.update() is not called when system attributes are modified via the web inspector while setAttribute() works as expected.

- A-Frame Version: master
- Platform / Device: All

**Comment by ngokevin** [comment]
Yeah, didn't really expect that to work. You can file at https://github.com/aframevr/aframe-inspector

**Comment by ngokevin** [comment]
Oops, browser inspector.

**Comment by donmccurdy** [comment]
System update is not called at all, right? I think this is the same as https://github.com/aframevr/aframe/issues/2612.
