### ISSUE TITLE
vr motion video

### ISSUE THREAD

**Issue by pranithkumar** [aframevr/aframe#2749]
I want to record a vr motion video of my house.
How can I do it?

**Comment by dmarcos** [comment]
We use github issues for bugs and feature requests. For questions please use stackoverflow:

https://stackoverflow.com/questions/tagged/aframe

or our slack channels:

https://aframe.io/community/#slack

**Comment by donmccurdy** [comment]
For posterity: https://stackoverflow.com/questions/44450241/recording-vr-motion-video
