### ISSUE TITLE
Remove some stale examples from the repo

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#275]
For launch, shall we remove these?

* https://github.com/aframevr/aframe/tree/master/examples/showcase-panoexplorer_OLD
* https://github.com/aframevr/aframe/tree/master/examples/showcase-mario
* https://github.com/aframevr/aframe/tree/master/examples/showcase-legos
* https://github.com/aframevr/aframe/tree/master/examples/animation-template-test
* https://github.com/aframevr/aframe/tree/master/examples/animation-aframe-logo

**Comment by jcarpenter** [comment]
Yes, agreed; we can remove these.

**Comment by cemkod** [comment]
Fixed by: https://github.com/aframevr/aframe/pull/338
We can close this.

**Comment by cvan** [comment]
thanks
