### ISSUE TITLE
VR mode renders terribly in Firefox Android

### ISSUE THREAD

**Issue by cuitingcheng** [aframevr/aframe#2761]
**Description:**
Hi,
I think there is a problem that VR mode is not rendered correctly in Firefox android browser, it has huge amount of aliasing and terrible resolution. the non-VR works fine and Chrome doesn't have this issue. Screenshots were taken with Aframe.io example.  
![screenshot_20170612-151101](https://user-images.githubusercontent.com/7551964/27051077-ccaad39a-4f82-11e7-89f8-678bcb816e96.png)
![screenshot_20170612-151108](https://user-images.githubusercontent.com/7551964/27051078-ccabc43a-4f82-11e7-9f01-1377c32f4c29.png)

- A-Frame Version: 0.5.0
- Platform / Device: Android 7.0, Firefox 53.0.2 on Galaxy S7 and Huawei P9
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
What phone?

**Comment by cuitingcheng** [comment]
@dmarcos Samsung Galaxy S7 and Huawei P9

**Comment by stevel4857** [comment]
It no longer works at all on nightly or firefox developer on my desktop and hasn't since Monday. Developer opens the page but crashes on click to VR and nightly just crashes on page load. Wish I hadn't updated now.

**Comment by Coder206** [comment]
I am also experiencing the same rendering issues as @cuitingcheng on a Nexus 6P.

**Comment by vrimaginar** [comment]
I also have this issue. Furthermore, the sensors are not being used in FF on Android, so we get al still picture (Samsung S7).

**Comment by HAZARDU5** [comment]
Confirmed I also have this issue on Firefox Android 7.0 on a Galaxy S7 Edge with A-Frame 0.5. In A-Frame 0.6 / 0.6.1 it's fine.

**Comment by mkungla** [comment]
This can be closed right?
