### ISSUE TITLE
simple in-vr stats component

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2768]
**Description:**

Barebones stats component, all it does is show one number: FPS.

```html
<a-scene stats>  <!-- 2D stats. --> 
  <a-entity stats position="0 0 -4" text="color: red"></a-entity>  <!-- Rendered stats. -->
</a-scene>
```

Most of the implementation:

```js
AFRAME.registerComponent('stats', {
  tick: function (t, dt) {
    this.el.setAttribute('text', 'value', 1000 / dt);
  }
});
```

**Comment by machenmusik** [comment]
hmm, was wondering whether potentially having to re-render glyphs every tick was going to be a performance killer, versus something like the FPS counter on https://webvr.info/samples/02-stereo-rendering.html

**Comment by ngokevin** [comment]
That seems like a canvas to texture render? I don't think updating a number has a big performance impact, the log component example I did was thrashing five different logging consoles with lots of text and it seemed fine.

**Comment by vincentfretin** [comment]
Similar feature request in #2077

**Comment by ngokevin** [comment]
https://github.com/ngokevin/kframe/tree/master/components/fps-counter#aframe-fps-counter-component

**Comment by kylebakerio** [comment]
Just adding this here for others who go down this route in google like I did--I ended up taking another old component and bringing it up to date [here](https://github.com/kylebakerio/stats-in-vr).
