### ISSUE TITLE
`npm install aframe@5.0.0` fails: fetchPackageMetaData error: pathspec 'a02a8089b' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#2771]
**Description:**

- A-Frame Version: 0.5.0
- Platform / Device: all
- Reproducible Code Snippet or URL:

Just run this install to `aframe` version `0.5.0`:

```sh
npm install aframe
```

<details>
<pre><code>0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.0.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'aframe' ]
2 info using npm@5.0.1
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 http fetch GET 200 https://registry.npmjs.org/aframe 734ms
7 silly pacote tag manifest for aframe@latest fetched in 776ms
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 silly install loadAllDepsIntoIdealTree
12 silly resolveWithNewModule aframe@0.5.0 checking installable status
13 http fetch GET 304 https://registry.npmjs.org/deep-assign 77ms (from cache)
14 silly pacote range manifest for deep-assign@^2.0.0 fetched in 79ms
15 silly resolveWithNewModule deep-assign@2.0.0 checking installable status
16 http fetch GET 304 https://registry.npmjs.org/style-attr 155ms (from cache)
17 http fetch GET 304 https://registry.npmjs.org/object-assign 158ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/three 91ms (from cache)
19 silly pacote range manifest for object-assign@^4.0.1 fetched in 175ms
20 silly resolveWithNewModule object-assign@4.1.1 checking installable status
21 silly pacote range manifest for style-attr@^1.0.2 fetched in 173ms
22 silly resolveWithNewModule style-attr@1.3.0 checking installable status
23 silly pacote range manifest for three@^0.83.0 fetched in 112ms
24 silly resolveWithNewModule three@0.83.0 checking installable status
25 http fetch GET 304 https://registry.npmjs.org/debug 229ms (from cache)
26 silly pacote range manifest for debug@^2.2.0 fetched in 231ms
27 silly resolveWithNewModule debug@2.6.8 checking installable status
28 http fetch GET 304 https://registry.npmjs.org/tween.js 47ms (from cache)
29 silly pacote range manifest for tween.js@^15.0.0 fetched in 50ms
30 warn deprecated tween.js@15.0.0: This package has moved to @tweenjs/tween.js. Please update your dependencies.
31 silly resolveWithNewModule tween.js@15.0.0 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/promise-polyfill 257ms (from cache)
33 http fetch GET 304 https://registry.npmjs.org/load-bmfont 263ms (from cache)
34 silly pacote range manifest for promise-polyfill@^3.1.0 fetched in 261ms
35 silly resolveWithNewModule promise-polyfill@3.1.0 checking installable status
36 silly pacote range manifest for load-bmfont@^1.2.3 fetched in 266ms
37 silly resolveWithNewModule load-bmfont@1.3.0 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/envify 308ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/present 310ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/browserify-css 324ms (from cache)
41 silly pacote range manifest for envify@^3.4.1 fetched in 316ms
42 silly resolveWithNewModule envify@3.4.1 checking installable status
43 silly pacote version manifest for present@0.0.6 fetched in 316ms
44 silly resolveWithNewModule present@0.0.6 checking installable status
45 silly pacote range manifest for browserify-css@^0.8.2 fetched in 328ms
46 silly resolveWithNewModule browserify-css@0.8.4 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/three-bmfont-text 162ms (from cache)
48 silly pacote range manifest for three-bmfont-text@^2.1.0 fetched in 164ms
49 silly resolveWithNewModule three-bmfont-text@2.2.1 checking installable status
50 info lifecycle document-register-element@0.5.4~prepack: document-register-element@0.5.4
51 silly lifecycle document-register-element@0.5.4~prepack: no script for prepack, continuing
52 verbose tar pack [ '/var/folders/zn/l4r1wmpj57q7h97088lcf6gw0000gn/T/npm-56448-5bf4136e/tmp/packing-6b2ac072/package.tgz',
52 verbose tar pack   '/Users/cvan/.npm/_cacache/tmp/git-clone-a2c71706' ]
53 verbose tarball /var/folders/zn/l4r1wmpj57q7h97088lcf6gw0000gn/T/npm-56448-5bf4136e/tmp/packing-6b2ac072/package.tgz
54 verbose folder /Users/cvan/.npm/_cacache/tmp/git-clone-a2c71706
55 info lifecycle document-register-element@0.5.4~postpack: document-register-element@0.5.4
56 silly lifecycle document-register-element@0.5.4~postpack: no script for postpack, continuing
57 silly pacote git manifest for document-register-element@github:dmarcos/document-register-element#8ccc532b7 fetched in 1728ms
58 silly resolveWithNewModule document-register-element@0.5.4 checking installable status
59 silly fetchPackageMetaData error for webvr-polyfill@github:dmarcos/webvr-polyfill#a02a8089b Command failed: /usr/local/bin/git checkout a02a8089b
59 silly fetchPackageMetaData error: pathspec 'a02a8089b' did not match any file(s) known to git.
60 verbose stack Error: Command failed: /usr/local/bin/git checkout a02a8089b
60 verbose stack error: pathspec 'a02a8089b' did not match any file(s) known to git.
60 verbose stack
60 verbose stack     at ChildProcess.exithandler (child_process.js:252:12)
60 verbose stack     at emitTwo (events.js:125:13)
60 verbose stack     at ChildProcess.emit (events.js:213:7)
60 verbose stack     at maybeClose (internal/child_process.js:887:16)
60 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
61 verbose cwd /private/tmp/atest
62 verbose Darwin 15.2.0
63 verbose argv "/usr/local/Cellar/node/8.0.0_1/bin/node" "/usr/local/bin/npm" "i" "aframe"
64 verbose node v8.0.0
65 verbose npm  v5.0.1
66 error code 1
67 error Command failed: /usr/local/bin/git checkout a02a8089b
67 error error: pathspec 'a02a8089b' did not match any file(s) known to git.
68 verbose exit [ 1, true ]</code></pre></details>

This is because in [`0.5.0`](https://github.com/aframevr/aframe/tree/v0.5.0) the [`package.json`](https://github.com/aframevr/aframe/blob/v0.5.0/package.json#L43) points to [`dmarcos/webvr-polyfill#a02a8089b`](https://github.com/dmarcos/webvr-polyfill/commit/a02a8089b).

Even though the [`dmarcos/webvr-poylfill`](https://github.com/dmarcos/webvr-polyfill) moved to [`aframevr/webvr-polyfill`](https://github.com/aframevr/webvr-polyfill), GitHub keeps the old remote URLs around (and just adds deprecation notices). But `npm` does not.

@dmarcos: can you delete https://github.com/dmarcos/webvr-polyfill and re-fork [`aframevr/webvr-poylyfill`](https://github.com/aframevr/webvr-polyfill/fork)?

(this may require you to delete your original fork from https://github.com/googlevr/webvr-polyfill, because GitHub doesn't allow forks of forks.)

**Comment by dmarcos** [comment]
I reforked the polyfill on my account: https://github.com/dmarcos/webvr-polyfill/

The hash https://github.com/dmarcos/webvr-polyfill/commit/a02a8089b exists now show npm should fetch it as expected. Just tried and it seems works. Please reopen if the problem persists

**Comment by cvan** [comment]
Thanks! I see that the commit resolves on GitHub, but I cleared my npm cache and it still won't install properly. I tried `npm cache clean`, `rm -rf ~/.npm`, `npm cache verify`,

<img width="1145" alt="screen shot 2017-06-13 at 6 42 29 pm" src="https://user-images.githubusercontent.com/203725/27111887-26faedf4-5068-11e7-86d5-b7f4f0da7a39.png">

Ideas?

**Comment by dmarcos** [comment]
That screenshot does not seem related to the polyfill. Try deleting your `node_modules` directory and run `npm install` again.

**Comment by dmarcos** [comment]
Below the result in my windows box:

![install](https://d3vv6lp55qjaqc.cloudfront.net/items/2j402d3h2Q450q270N1p/Image%202017-06-13%20at%206.50.39%20PM.png?X-CloudApp-Visitor-Id=402ef9a4b6ed079d2b4c220eb45be353&v=d217e0dd).

**Comment by cvan** [comment]
It says `Command failed: /usr/local/bin/git checkout a02a8089b`.

The commit in question is https://github.com/dmarcos/webvr-polyfill/commit/a02a8089b. So, it seems to still be the `webvr-polyfill` dependency it's fatal-erring on. I'll try on another machine and clearing my cache too. I just hope others aren't encountering the same problem of trying to install `npm install aframe` once and it not being fixed now.

**Comment by dmarcos** [comment]
Someone else is observing the issue. Additional info: npm `3.10.X` works but more recent versions `5.X.Y` fail.

**Comment by calrk** [comment]
So its an issue on my Windows 10 computer and a coworker's Windows 10, and our Alpine servers running docker.
However it works fine on a coworker's Mac and another Windows 10 computer. 
May be related to the new Windows 10 update? but that wouldn't explain your mac or our docker servers...

Fails:
Windows 10 : npm v5.0.0
Windows 10 : npm v5.0.3
Alpine/Linux : npm v3.10.10

Works:
Windows 10 : npm 3.10.8
Mac : npm (not sure)

Getting this on our servers as well, but they've been running updates for a while with no issues before now
npm ERR! error: cannot run ssh: No such file or directory
npm ERR! fatal: unable to fork

Still looking into it and will let you know if I find more.
Thanks

**Comment by ngokevin** [comment]
Fails for me on a Windows machine I haven't used in a while. We can cut 0.5.1 on npm, perhaps pointing to a fork on my username to be safe.

**Comment by ngokevin** [comment]
A workaround to this issue for anyone running into this today until we fix is `npm install aframevr/aframe@0.5.0`.

**Comment by calrk** [comment]
Thanks, been able to work around it using `npm install aframevr/aframe` for now.
It may have to do with the npm cache. I cleared mine earlier and the problem has come up for me, so might be able to replicate it by clearing it. I'll test this tomorrow on a computer that is currently working fine.

**Comment by DKvistgaard** [comment]
I've been testing `npm install aframe` today and I've tried with npm version 3.10 and 4.2 without success. Actually there were no issues to begin with, but as soon as I cleared my npm cache I started getting these errors:

```npm ERR! git rev-list -n1 a02a8089b: fatal: ambiguous argument 'a02a8089b': unknown revision or path not in the working tree.```

So after a lot of testing and searching, I've come up with this:
There's - as mentioned earlier - a dependency to the dmarcos/webvr-polyfill repository at a specific commit SHA number ([a02a8089b](https://github.com/dmarcos/webvr-polyfill/commit/a02a8089b)). This commit however doesn't seem to be associated with any branch, so that might be the reason why git can't locate this commit. After looking through the commits on all the different branches on the dmarcos/webvr-polyfill repository I found one commit that looks almost the same as the a02a8089b commit, and it's this one: [dmarcos/webvr-polyfill@ 9faf790](https://github.com/dmarcos/webvr-polyfill/commit/9faf790). It could look like a force push has been done to the dmarcos/webvr-polyfill repository, which has resulted in the SHA numbers to update, which is then causing the installation error where git can't locate the a02a8089b commit.

So, there shouldn't be any problem as long as you've previously installed aframe without issues and don't clear your npm cache - as the cache has remembered the reference to the a02a8089b commit. However if you either clean your npm cache or install a new npm version you will start getting errors.

**Comment by donmccurdy** [comment]
Same issue here. Installation fails with npm 5.X, so I've reverted to npm 4.X.

**Comment by ngokevin** [comment]
Currently fixing...the commit is on GitHub but no longer on the Git tree. Solution is to publish a fork of the polyfill to npm with the same changes and re-tag v0.5.1.

**Comment by dmarcos** [comment]
I don't think we nee a new tag anymore. I believe I solved the mystery. When I reforked the polyfill in my account the commit showed up on github (https://github.com/dmarcos/webvr-polyfill/commit/a02a8089b) but just realized that it does not exist in git. Github must have some sort of cache that in same cases is not consistent with the git data base itself. I had the missing commit on a local clone of my old fork that a pushed again to github. I believe that everything should be fine now without having to republish, re tag.

**Comment by dmarcos** [comment]
@clark @DKvistgaard can you confirm if everything is working now? You should not need any changes on your side. It should just work

**Comment by calrk** [comment]
@dmarcos Yes this is working fine on my local and deployment servers now. 

Thanks,
Clark

**Comment by dmarcos** [comment]
👏💃

**Comment by natesena** [comment]
npm install aframe fails again

**Comment by donmccurdy** [comment]
@natesena could you give npm and node.js versions? `npm -v` / `node -v`

**Comment by natesena** [comment]
npm -v
5.5.1
node -v
8.4.0

**Comment by dmarcos** [comment]
@natesena What version are you trying to install? I see a reference to your cache in the command out put you pasted. Clearing your cache with `npm cache clean` and reinstalling `npm install aframe` might solve the problem. Let us know.
