### ISSUE TITLE
Typo in Online Documentation: colon should be semi-colon and vice a versa 

### ISSUE THREAD

**Issue by kkruups** [aframevr/aframe#2774]
**Description:**
**Documentation Issue**
The paragraph (described below) in section indicated by link below has a typo:
https://aframe.io/docs/0.5.0/introduction/entity-component-system.html#syntax

**Excerpt of passage which needs correction:**

...This syntax takes the form with a **semicolon** (:) separating property names from property values, and a **colon** (;) separating different property declarations: ...

**Correction should be**:

...This syntax takes the form with a **colon** (:) separating property names from property values, and a **semicolon** (;) separating different property declarations: ...

**Comment by dmarcos** [comment]
Thanks! Do you want to try opening a pull request to fix it? We can help if you don't know how to

**Comment by donmccurdy** [comment]
Here are the steps for updating our docs, if you're interested, @kkruups — https://github.com/aframevr/aframe/blob/master/CONTRIBUTING.md#update-documentation

**Comment by kkruups** [comment]
Thanks i will update.  I 'll first read the docs.

BR/KK

**Comment by kkruups** [comment]
Done!  

**Pull Request Created:**
Docs: Corrected Typo changed word semicolon to colon and vice-versa **#2777**

**Comment by ngokevin** [comment]
Fixed #2777
