### ISSUE TITLE
Caching issue with a-assets. Images are re-downloaded every time.

### ISSUE THREAD

**Issue by hardiksurana** [aframevr/aframe#2775]
-**Issue**: 
I have a few images in <a-assets>, which are being used as the src for <a-sky>. I am also adding new images to <a-assets> dynamically, using javascript. Initially, when the page loads, all the images are downloaded. When I change the src of <a-sky> to an image which is already downloaded, it re-downloads the image again, instead of loading a cached version of the same. Also, once I add a new image to <a-assets> and change the src of <a-sky> to this, it downloads the image every time, instead of using the cached version.

Is there an event listener that can be used to keep track of whether an image is cached or not?

- **A-Frame Version**: 
0.5.0

- **Platform / Device**: 
Ubuntu 16.04

- **Browser**:
Google Chrome Version 59.0.3071.86 (Official Build 64-bit)

**Comment by donmccurdy** [comment]
@hardiksurana caching is managed through A-Frame's asset management system: https://aframe.io/docs/0.5.0/core/asset-management-system.html

If you're using inline URLs instead of `<a-assets/>`, you may be circumventing the caching. If you are already using the asset system, could you:

1. Test on the `master` branch of A-frame — we've already fixed some bugs in this area.
2. Add a Codepen or JSFiddle example.

Thanks!

**Comment by hardiksurana** [comment]
Thanks, @donmccurdy !
I figured out the error related to caching. 

I had another query. I am accessing the same set of images multiple times using <a-sky>. After the initial download, when the images are accessed, another request is being sent to the source of the image, which returns a 304 (not modified) status code. I wanted to know if there is a way in a-frame to keep track of how the requests for these assets is being made, and also what the response for such requests may be.

**PS**: I don't have any back-end code, nor am I using XHR requests. I want to know if we can access the status code of the response of the image (or other assets) being requested by aframe using client-side JS only.

**Comment by donmccurdy** [comment]
I think the extra requests were fixed here: https://github.com/aframevr/aframe/issues/2472

So, that fix is in the `master` branch, not 0.5.0, and will be released with A-Frame 0.6.0.

A-Frame doesn't give you direct access to the response status codes, but there should be only one request anyway after these fixes. Hope that helps!

**Comment by ngokevin** [comment]
I believe the 304 are just browser cache hits?

**Comment by hardiksurana** [comment]
Thanks, @donmccurdy !
I wanted to use the status code to check if an image is already downloaded and to choose whether to show a loader or an animation based on the browser response. If it's downloaded, then I would show an animation for changing the sky, else I would show a loader until the image downloads.
Any idea of how this can be checked and implemented in a-frame?

Also, yes @ngokevin 304 is Not Modified client redirection response code. It is an implicit redirection to a cached resource.

**Comment by ngokevin** [comment]
You can check `THREE.Cache` to see if it has been fetched or not

**Comment by hardiksurana** [comment]
Thanks, @ngokevin and @donmccurdy .
