### ISSUE TITLE
feature request: add vertexColors properties to material component

### ISSUE THREAD

**Issue by morandd** [aframevr/aframe#2779]
Small feature request: expose the vertexColors property in the `material` component. So users can do like
```
<a-entity myComponentThatGeneratesABufferGeometry="height: 1.23; radius: 4.56" material="opacity:0.5; vertexColors=2">
```
I'm building several such "myComponentThatGeneratesABufferGeometry" that use vertex coloring e.g. http://https://github.com/morandd/aframe-heatmap3d  It'd be cleaner to re-use the AFrame `material` component, if one is provided, rather than have the user pass in all the material properties to my component so I create the material internally.

thanks for considering

**Comment by ngokevin** [comment]
Added
