### ISSUE TITLE
Enter VR button not appearing anymore (Oculus browser), impossible to enter VR

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#2781]
**Description:**

- A-Frame Version: latest master
- Platform / Device: Gear VR, Oculus browser
- Reproducible Code Snippet or URL: http://aframe-master.glitch.me/

This regression happened after fixing #2614 
The enter VR button briefly appears, then disappears.

**Comment by dmarcos** [comment]
A PR to fix this landend last night: https://github.com/aframevr/aframe/pull/2751

Can you make sure you're using the very latest master?

**Comment by ngokevin** [comment]
The issue is different and mentions that pr

**Comment by machenmusik** [comment]
Can someone try #2707 and see if it is the old Carmel auto-enter attempt?

**Comment by weddingdj** [comment]
@dmarcos http://aframe-master.glitch.me/ uses the master which a-frobot commited just after #2751 has been commited (https://github.com/aframevr/aframe/commits/master).
