### ISSUE TITLE
TypedArray.prototype.slice is not supported in IE 11

### ISSUE THREAD

**Issue by kazandzhiro** [aframevr/aframe#2786]
**Description:**

- A-Frame Version: 0.5.0
- Platform / Device: Windows, Internet Explorer 11.1198.14393.0

Hi guys,
Thank you for the great framework. I am working on a project that requires support for IE11.
I have noticed an issue with the aframe 0.5.0 version. I am trying to make a screenshot of the current canvas. The operation fails at [this line](https://github.com/aframevr/aframe/blob/990e9272dc9ddc463a7707fae885c2afd26f9006/src/components/scene/screenshot.js#L224 ) in screenshot component. The issue is that TypedArray.prototype.slice is not supported in this version of IE. Would you consider supporting the functionality in IE 11?

Thanks.

**Comment by donmccurdy** [comment]
Hi @kazandzhiro —

See issues https://github.com/aframevr/aframe/issues/1475 and https://github.com/aframevr/aframe/issues/2758. For various reasons, we're not able to offer much support for IE11. Specifically in this case, the dependency on TypedArray.prototype.slice goes past A-Frame into some of our three.js dependencies.

That said, I thought this feature was in IE11. Does adding this meta tag in `<head/>` give a different result?

```html
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
```

You may also be able to add a [TypedArray polyfill](https://github.com/substack/typedarray) to your page. But generally speaking, we very much recommend using an evergreen browser (Microsoft Edge, Firefox, Chrome, or Safari) with A-Frame.

**Comment by kazandzhiro** [comment]
Hi @donmccurdy 
Thanks a lot for the suggestions and linked issues. I have checked the issues as well. I guess if new need to support it we will go with the polyfill. 
Thanks for your time and keep up the good work 👍 !
