### ISSUE TITLE
registered custom geometry update method is never called

### ISSUE THREAD

**Issue by andreasplesch** [aframevr/aframe#2797]
**Description:**

A-frame has the option to register custom geometries:
https://aframe.io/docs/0.5.0/components/geometry.html#register-a-custom-geometry
The documentation mentions and the expectation would be that there is an update life cycle method, similar to components.

However, the update method of a registered custom component seems to be never invoked. Instead, the geometry component calls the init method when attributes change. This works for the built-in geometries but may not work for custom geometries.

- A-Frame Version: 0.5.0
- Platform / Device: all
- Reproducible Code Snippet or URL: https://heavy-client.glitch.me/
There is an update method which prints to the console. It is never called, eg. not at the initial init nor after clicking the button.

Solutions may include to either clarify documentation (deprecate custom geometries update) or add hook into custom update in geometry component update.

**Comment by dmarcos** [comment]
init should br called since the geometry is recreated when the properties change. For advanced, more optimized geometry I would recommend creating a separate component instead of relying on extending the built in primitives

**Comment by andreasplesch** [comment]
https://aframe.io/docs/0.5.0/components/geometry.html#register-a-custom-geometry

now mentions update as a lifecycle method. I can prepare a short PR to clarify this doc section if desired.

**Comment by ngokevin** [comment]
Thanks! I recommend a custom component for now, the `registerGeometry` I think we should even make internal API just for the geometry component.

**Comment by andreasplesch** [comment]
Yeah, as it is, registerGeometry does not really provide advantages over registerComponent for custom THREE Geometries, as far as I can tell.
