### ISSUE TITLE
Document and expose scene's VR controllers

### ISSUE THREAD

**Issue by AndresCuervo** [aframevr/aframe#2799]
Get the `navigator.getGamepads()` to line up with controller entities in the scene markup. 

From @donmccurdy from the A-Frame Slack:

> A-Frame makes an assumption about which gamepad is right/left though (or maybe it's in the gamepad API?) so custom components have to match that.

It looks like [`this.controller` in `tracked-controls`](https://github.com/aframevr/aframe/blob/master/src/components/tracked-controls.js#L78) does this, but there's currently no component level way to pass along this information, so we're left doing something like `var controllers = navigator.getGamepads()`.

Since it pretty closely follows this issue: maybe there also oughta be a declarative way for handling button input and touch/pressed values? e.g. `leftTrackPadPressed = "LeftTrackPadPressedFn";`

**Comment by donmccurdy** [comment]
To clarify the use case, are you interested in events from the gamepad, getting current state of the buttons, position/rotation? Or some combination of those?

It looks like even within `tracked-controls`, there is no reference to which hand it is. We'd need to look at the `<device>-controls` component for that, which is inconvenient. 

One solution would be to include `hand: 'left' | 'right'` in the `controllerconnected` event.

**Comment by machenmusik** [comment]
Actually, the current vive-tracker PR may have some changes one is looking for here... especially regarding hand

**Comment by dmarcos** [comment]
Not all tracked controllers have the concept of handness so we include that on the vendor specific controls live `oculus-touch-controls` or `vive-controls` @AndresCuervo Can you share a bit more of your use case so we can recommend a solution? A code snippet / markup will help

**Comment by AndresCuervo** [comment]
re: @donmccurdy 

I'm interested in getting events from the gamepad, that ideally include information like current state of the buttons and position/rotation — for example, to make a component that vibrates the controllers when a certain button is pressed, it'd be nice to just listen to specific button presses and vibrate `this.el.controller`. ~I'm also in favor of passing `hand: 'left' | 'right'` in the `controllerconnected` event, to get a baseline assuming the controllers support handedness.~ Actually, @donmccurdy, in writing the below I found that `tracked-controls`
 events (anecdotally, off of `buttonchanged`, but we can assume WLOG) returns the hand info in `e.detail.target.components['tracked-controls'].controller.hand`. That's still pretty cumbersome, but it's worth maybe just documenting this for now?

---

re: @dmarcos 
I've been looking for something like a streamlined version of accessing `document.querySelector('a-scene').systems['tracked-controls'].controllers` with a mapping between an controller and the element it originates from. Right now to do, for example, a very arbitrary fire-on-every-button-change, vibration call, you'd do something like the following:

``` javascript
document.querySelector('[tracked-controls]').addEventListener('buttonchanged', function (e) {
   e.detail.target.components['tracked-controls'].controller.hapticActuators[0].pulse(e.detail.state.value  / 2, 100)
})
```

Now that I've dug down into it, I feel like this satisfies what I was originally asking for, but the ergonomics could be better, such as surfacing `e.detail.controller` in the event response or declaratively allowing a function to handle a given controller, for example:

``` javascript

function triggerHandler (controller, buttonValue) { /* do stuff with this information */}
function trackpadHandler (controller, buttonValue) { /* do stuff with this information */}
/*... etc.*/
----
<a-entity tracked-controls="controller: 0; idPrefix: OpenVR; triggerHandler: triggerHandler; trackpadHandler: trackpadHandler"></a-entity>
```

The example above is probably too vendor specific, but we can abstract it higher (gotta reference the WebVR and Gamepad API specs if I actually find the time to work on this) to handle buttons input. I've heard about controller/input support in 0.6.0, maybe this is redundant/can be coupled with that implementation?

**Comment by machenmusik** [comment]
IMO, seems like there are a few different topics this brings up:
(1) exposing hapticActuators for more convenient use
(2) declarative markup to respond to the events controllers generate
(3) stylistic difference between attaching event listeners ad-hoc that dispatch functions, and making components that contain the functions and are attached to the same entity

**Comment by dmarcos** [comment]
What controllers are you supporting? I recommend using the higher level controls that will give you the button mappings. if you use `vive-controls`, `daydream-controls`, `oculus-touch-controls`... you can listen to events like `triggerdown` , `touchpaddown` ... the handle to the entity will be passed to the handler. Look at `hand-controls` as an example https://github.com/aframevr/aframe/blob/master/src/components/hand-controls.js

**Comment by dmarcos** [comment]
IMO Declarative ways to attach handlers ends up being more confusing than helpful when applications get complicated since you have logic scattered between HTML and JS and it's unclear what is the scope and where those handlers live.

**Comment by dmarcos** [comment]
I agree that an haptics API is a different conversation

**Comment by dmarcos** [comment]
Is there anything actionable in this issue? I feel the requested functionality (besides haptics) is already provided by our vendor specific controls. As a general rule devs won't be interacting often with `tracked-controls` unless you want to integrate a controller that does not have built in support

**Comment by donmccurdy** [comment]
> if you use vive-controls, daydream-controls, oculus-touch-controls... you can listen to events like triggerdown , touchpaddown ... the handle to the entity will be passed to the handler. Look at hand-controls as an example 

This works; I think the OP also wants to know which hand the entity is associated with, and the entity doesn't give an easy way to identify that without iterating over `vive-controls`, `daydream-controls`, `oculus-touch-controls`... but that is not hard to work around, by attaching `id="left"` to the entity yourself.

But the tl;dr here is, if users want behavior attached to a specific hand, it's best to put that behavior in a component on that hand, rather than writing outside event listeners and trying to work backwards to get the Gamepad and hand references.

Other than maybe continuing the haptics conversation somewhere, I don't think changes are needed here then.

**Comment by machenmusik** [comment]
@donmccurdy agree although doc and example changes may still be relevant

**Comment by AndresCuervo** [comment]
Yeah, while working through the issues I brought up at the top of this, there doesn't seem to be much actionable work here, although getting the haptics API would be a different conversation that can be picked up later, in a different thread when appropriate. Also, now that I think about it, the complexity surrounding handling controller input is such that a declarative model would be more obfuscation than enlightening, thanks @dmarcos.

**Comment by machenmusik** [comment]
Re: declarative handling turning into obfuscation - yeah, often times the handling is placed in a component that is attached to the same entity (and sometimes the dependencies feature of components is used to ensure the right components are attached)
