### ISSUE TITLE
Raycaster issue: removing the whitelisted class does not work properly

### ISSUE THREAD

**Issue by gftruj** [aframevr/aframe#2803]
**Description:**
I have a properly working raycaster whitelisting `<a-entity class="trigger">` <br>via the `raycaster="objects: .trigger"` property. 

When the entities are initialized with the class attributes, everything is working as expected.

When i modify the class on the run, the raycaster is still working on entities which don't have the whitelisted class. Working fiddle [here](https://jsfiddle.net/x4un1gru/).

Moreover, when i add the whitelisted class on the run, it still is not working. Working fiddle [here](https://jsfiddle.net/x4un1gru/3/)

I tried changing the class insted of removing it, but I still got nothing.

I use setAttribute() to add classes, removeAttribute() to remove them, it's working since in the logs i see that the classes have been changed/removed.

- A-Frame Version: Master, 0.5.0 as well
- Platform / Device: PC firefox 53.0.3 (64 bit)/chrome version 59.0.3071.109 (official)

**Comment by vrimaginar** [comment]
You have to refresh the raycaster. So when you add or remove the trigger class do this:

var raycasterEl = AFRAME.scenes[0].querySelector('[raycaster]');
raycasterEl.components.raycaster.refreshObjects();

**Comment by gftruj** [comment]
Thank You very much, it works like a charm !
