### ISSUE TITLE
[Documentation] aframe master cursor example

### ISSUE THREAD

**Issue by vrimaginar** [aframevr/aframe#2804]
Hi,

the aframe master example regarding 'Adding visual feedback' is wrong;

a-animation begin="cursor-fusing" should be

a-animation begin="fusing"

**Comment by dmarcos** [comment]
@vrimaginar Do you want to open a PR?

**Comment by machenmusik** [comment]
I think @cvan called that out as a backward incompatibility in laser-controls PR...

**Comment by vrimaginar** [comment]
Still, when you use 'cursor-fusing' as the beginning of an animation the animation will not play.

**Comment by machenmusik** [comment]
Yes, I think the question is whether to accept the incompatibility and change docs to match the new name(s), or change back to backward compatible names and leave the docs.

**Comment by vrimaginar** [comment]
Ah, I see what you mean now.

In my opinion the dev has a choice which cursor (gaze, laser, w/e will be in the future) to use and can therefore set the appropriate cursor in code. When he / she needs a fallback to another cursor there can be a test for HMD that support laser (or other) cursors and if not choose another cursor like a gaze cursor?

**Comment by machenmusik** [comment]
I believe that the change made as part of laser-controls PR was to the raycaster event names, so not only impacting laser-controls.

**Comment by ngokevin** [comment]
I might just change it back. The states aren't used often in public API and thought it was ok but forgot about the cursor animation docs

**Comment by ngokevin** [comment]
Changed back
