### ISSUE TITLE
Consider rolling back cursor interaction with invisible objects

### ISSUE THREAD

**Issue by vrimaginar** [aframevr/aframe#2806]
In the past the cursor did not interact with invisible objects by default. This behaviour changed in 0.5.0. and now we have to do extra work to _not_ interact with invisible objects.

Consider the following scenario:

- A raycaster with the objects: .clickable attribute
- An image that, when clicked, will show another image
- The new image, when clicked, will show a graph and a close button that will close all but the first image

What we need to do with 0.5.0 is:

- Add the class 'clickable' on the first image
- When the first image is clicked, make the second image visible _and_  add 'clickable' to it's class
- When the second image is clicked we need to set the graph visible and the close button, and add the class 'clickable' to the close button
- When the close button is clicked we have to set 'visible=false' to the second image, the graph and the close button _and_ remove the class 'clickable' from various objects.
- I did not mention we need to refresh the raycaster each time the class 'clickable' is added or removed

Now consider the above scenario if the cursor does not interact with invisible objects.

When a dev needs interaction with an invisible object isn't it better to hide the object with 'opacity=0'?

Kind regards, and thank you for a great product!

**Comment by ngokevin** [comment]
Can you try `material="visible: false"`? I believe three.js changed to look at the material visible property rather than object3d visibility.

**Comment by vrimaginar** [comment]
Hi @ngokevin, still the same issue when I use:

**Comment by stevel4857** [comment]
I gave up on this myself. It would be nice.
