### ISSUE TITLE
Changing a-text value from javascript

### ISSUE THREAD

**Issue by postlund** [aframevr/aframe#2808]
**Description:**
I'm trying to change the text in an a-text dynamically with setAttribute from Javascript.  The example linked below simply just changes the text to another hardcoded text (compared to initial value) each tick. It works as I expect it too in Chrome ("my text" is shown), but not in Firefox or Safari ("text" is shown). I cannot really see what's wrong here, especially since it works in Chrome. Any ideas?

- A-Frame Version: 0.5.0
- Platform / Device: Firefox/Safari, macOS
- Reproducible Code Snippet or URL: https://pastebin.com/aWytFC2k

**Comment by ngokevin** [comment]
Fixed
