### ISSUE TITLE
`mixin` attribute does not merge non-object single-property components properly

### ISSUE THREAD

**Issue by delapuente** [aframevr/aframe#2809]
The line in charge of [extending components coming from mixins](https://github.com/aframevr/aframe/blob/master/src/extras/primitives/primitives.js#L81) will return an invalid value when the mixin component is a non-object single-property value such as an string:

```js
data[name] = utils.extendDeep(data[name] || {}, mixinComponents[name]);
```

This is caused by how [`deep-assign`](https://www.npmjs.com/package/deep-assign) works.

Try the following snippet:

```js
const deepAssign = require('deep-assign');
undefined
deepAssign({}, '[camera]');
{ '0': '[',
  '1': 'c',
  '2': 'a',
  '3': 'm',
  '4': 'e',
  '5': 'r',
  '6': 'a',
  '7': ']' }
deepAssign({}, 1);
{}
```

**Comment by ngokevin** [comment]
Nice catch
