### ISSUE TITLE
a-cursor to much faces 1280

### ISSUE THREAD

**Issue by 7dir** [aframevr/aframe#2821]
**Description:**
turn on `stats `
faces 1280 on blank scene

- A-Frame Version: 0.5
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
You can play with the segments property and see if you can find a lower value that feels good. PRs are welcome :) https://github.com/aframevr/aframe/blob/master/src/extras/primitives/primitives/a-cursor.js#L12
