### ISSUE TITLE
clone entity and children with cloneNode and innerHTML not working as expected

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe#2823]
**Description:**
Cloned entity and its children not showing as expected when using `cloneNode` or copying `innerHTML` with `flushToDOM(true)` when copying a parent entity with dynamically created children. 

- A-Frame Version: master
- Platform / Device: firefox nightly vive / windows chrome (non vr)
- Reproducible Code Snippet or URL:

error using cloneNode:
Output https://kfarr.github.io/streetmix3d/error-clone.html
Source https://github.com/kfarr/streetmix3d/blob/master/error-clone.js#L81

error using innerHTML:
Output https://kfarr.github.io/streetmix3d/error-clone2.html
Source https://github.com/kfarr/streetmix3d/blob/master/error-clone2.js#L92

expected behavior (workaround rerunning generator function multiple times):
Output https://kfarr.github.io/streetmix3d/error-workaround.html
Source https://github.com/kfarr/streetmix3d/blob/master/error-workaround.js#L69

**Comment by vincentfretin** [comment]
https://github.com/aframevr/aframe-inspector/pull/696 should fix this issue.

**Comment by kfarr** [comment]
@vincentfretin thanks. The original code that prompted the issue is in a long ago branch so I won't retest but will just close
