### ISSUE TITLE
3rd party triangulation lib

### ISSUE THREAD

**Issue by 7dir** [aframevr/aframe#2824]
geometry text with another triangulation
https://threejs.org/examples/?q=text

## Why?

Built-in THREE.js triangulation show error messages sometimes.

`THREE.ShapeUtils: Unable to triangulate polygon! in triangulate()`

**https://github.com/7dir/aframe-triangulation-component**

**Comment by donmccurdy** [comment]
Hi @7dir — Nice! Would you like to add your component to [awesome-aframe](https://github.com/aframevr/awesome-aframe)?

**Comment by dmarcos** [comment]
I don't think there's anything actionable on this issue.
