### ISSUE TITLE
A-frame examples' gyroscope is not working on Mozilla Firefox

### ISSUE THREAD

**Issue by chaad18** [aframevr/aframe#2825]
**Description:**
My project's gyroscope also isn't working on Mozilla Firefox. It's fine on Google Chrome though.

- A-Frame Version: 0.5.0
- Platform / Device: Firefox on Android
- Reproducible Code Snippet or URL: aframe.io

**Comment by Utopiah** [comment]
Please fill up the relevant information (version, device, URL) as it works well everywhere else I tried.

**Comment by chaad18** [comment]
Oh, sorry about that. I updated the info. The problem seems to exist only with Firefox on android.

**Comment by dmarcos** [comment]
@autonome Do you know if the fix ever landed on the polyfill? We can pull the fix in for `0.6.1` next week
