### ISSUE TITLE
images are being loaded twice resulting slow download speed

### ISSUE THREAD

**Issue by chendabo** [aframevr/aframe#2826]
**Description:**
When I use inspector/network to check the files that are being loaded, I noticed that a lot of the files, images are being loaded twice, sometimes 3 times, resulting in a slow downloading speed.

Can someone explain this ?

I thought it was my code at first, but I checked the official examples, and it is showing the same issue.

I don't know if anyone else sees this issue.

Thanks.

**Comment by ngokevin** [comment]
This has been fixed on aframe master branch in github

**Comment by nyteryze** [comment]
no it hasn't...
