### ISSUE TITLE
Cursor line visible despite raycaster showLine set to false

### ISSUE THREAD

**Issue by sz-piotr** [aframevr/aframe#2841]
**Description:**
The documentation of [cursor](https://aframe.io/docs/0.6.0/components/cursor.html) states it internally uses the [raycaster](https://aframe.io/docs/0.6.0/components/raycaster.html) component which has a property `showLine` that causes a line to be displayed. However the line is still visible even if that property is set explicitly. A fix i found is to add `line="visible: false"` on the cursor entity.

I am attaching two images. The first is a screenshot from VR mode in Xiaomi MI 5 on Google Chrome, where the effect is visible. The second shows the inspector in a desktop version where the line component has the `visible` property set to true despite the `showLine` property set to false on the raycaster component.

- A-Frame Version: 0.6
- Platform / Device: Xiaomi MI5 - Google Chome, GearVR (both only after entering vr mode)
- Reproducible Code Snippet or URL:
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>
      <a-camera>
        <a-cursor></a-cursor>
      </a-camera>
      <a-sky color="#0000FF"></a-sky>
    </a-scene>
  </body>
</html>
```
![aframe_cursor_line](https://user-images.githubusercontent.com/17070569/27831839-a5b66b36-60cc-11e7-8f5c-ae119cad3c0b.png)
![aframe_cursor_inspect](https://user-images.githubusercontent.com/17070569/27832176-05a4e3f0-60ce-11e7-8e07-26a883a9d130.png)

**Comment by ngokevin** [comment]
This was fixed at https://github.com/aframevr/aframe/commit/16e18f66f33d6615db44311b40e965fd3f25e0ff ... will have 0.6.1 out with bug fixes soon.

https://rawgit.com/aframevr/aframe/538439e/dist/aframe-master.min.js
