### ISSUE TITLE
a-animation for color requires from attribute

### ISSUE THREAD

**Issue by andreasplesch** [aframevr/aframe#2842]
**Description:**

The <a-animation> element with color as animated attribute does not use the parent element's color as from value. It is necessary to provide an explicit from value.

- A-Frame Version: 0.5.0, 0.6.0
- Platform / Device: all
- Reproducible Code Snippet or URL:

https://glitch.com/edit/#!/almond-taker?path=public/index.html:10:40
https://almond-taker.glitch.me/

The box color should interpolate from blue to red but resets to black as initial color at the start of the animation.

**Comment by takahirox** [comment]
Probably we should replace this line in `src/core/a-animation.js`

https://github.com/aframevr/aframe/blob/af3f89049d10b9037895b9059e5aa430c6f1bf81/src/core/a-animation.js#L465

```javascript
from = new THREE.Color(dataFrom);
```

with

```javascript
if (dataFrom === undefined) {
  from = new THREE.Color(el.getAttribute(attribute));
} else {
  from = new THREE.Color(dataFrom);
}
```

?

If this's correct, I'll make PR.

**Comment by andreasplesch** [comment]
dataFrom should already have gone through this check:

https://github.com/aframevr/aframe/blob/af3f89049d10b9037895b9059e5aa430c6f1bf81/src/core/a-animation.js#L95

But I am non sure why this line

https://github.com/aframevr/aframe/blob/af3f89049d10b9037895b9059e5aa430c6f1bf81/src/core/a-animation.js#L107

is placed afterwards, not before the getAnimationValues call.

It may be worthwhile to find out why it works for other attributes but not for color.

Following the code style, the proposed fix may be written as:

```
dataFrom = dataFrom || getComponentProperty(el, attribute);
from = new THREE.Color(dataFrom);
```
but I did not actually try this.

**Comment by andreasplesch** [comment]
https://reminiscent-tip.glitch.me/
applies @takahirox fix . It works for the example, and probably in general. Submit PR and wait for a response ? Perhaps there is a test to add ?

**Comment by andreasplesch** [comment]
https://github.com/aframevr/aframe/blob/master/tests/core/a-animation.test.js
It looks like the case when from is missing and from is the current entity value was not tested, so perhaps there is no need to add a test.
