### ISSUE TITLE
Procedural components and systems

### ISSUE THREAD

**Issue by feiss** [aframevr/aframe#2843]
The [environment component](http://github.com/feiss/aframe-environment-component) is useful in many cases when there is no 3d modelling knowledge and/or when something quick for testing and experimenting is needed.

So, why not more components, systems and tools for getting procedural content easy and fast? For example, they could be useful for:

* Creating and applying textures and materials (using https://github.com/mrdoob/texgen.js/ ?)
* Generating appealing color schemes
* Applying complex animations
* Creating 3d models out of basic primitives and operations
* Creating buildings and cities
* Creating simple avatars
* Creating advanced particle systems
* Creating furniture
* Creating spaceships

and much more!

**Comment by andreasplesch** [comment]
Many awesome components already do this ? rain, ocean, polygons, stars .. What is the new idea ?

**Comment by feiss** [comment]
Yeah, creating procedural content is not a new idea at all. I just thought that many aframe demos and experiences could benefit from it, and this thread could be a little bookmark of what kind of 'procedural' components could be done and open the subject to discussion and brainstorming.

**Comment by andreasplesch** [comment]
Ok, understood. To get started, what would distinguish 'procedural' from other components ? The number of properties ? So the topic could be about complex components with a large (>5?) number of properties?

**Comment by donmccurdy** [comment]
I think the 'rain' and 'ocean' components are good examples of this, and the goal for this issue would be to gather even more ideas. No need to distinguish categories of procedural-ness. :)

Similar to #2408, maybe a nice thing would be a component that can grab a random child from a model, rather than loading the entire model. So I could load a glTF file with 5 trees, and have 100 trees randomly drawn from the model, scaled, and scattered around the scene. (or does the environment component sort of already do this?)

**Comment by andreasplesch** [comment]
Ok, let's assume this is about larger, geometry generating components ? Or just generally about components ? Still a bit unsure.

Thinking a bit bigger here are some ideas.

I would like to see a generalized transformation component which would allow reprojection of coordinates (of any geometry) through custom or a set of predefined functions (not just trafo matrices), on the GPU. The particular use case would be GIS, for AR type applications, using proj4, once double fp on the GPU becomes commonplace.

A complex procedural component could be one which takes the scanned image of a floor plan, or plan of building foot prints of city blocks, and reconstructs 3d walls and doors and windows via image machine learning.

Any kind of geometry reconstruction from images as a component.

A planet generator based on our solar system plus categories of extra solar planets.

Practical domains for parameterized solid objects:
architecture, transportation, mechanical engineering, clothing, furniture, animals, avatars, tree of life, cities, mining, landscape, lab, sculpture, art, music, datamining. Potential guide for more specific brainstorming. A github search for 'generator JavaScript' ?

The label said brainstorming ...

**Comment by donmccurdy** [comment]
> Any kind of geometry reconstruction from images as a component.

Maybe getting a bit ahead of ourselves how about scoping to, "generating non-deterministic content in a scene". Computing content from scanned point clouds, photo clouds, and ML is a whole field of study on its own. 😉

> A planet generator based on our solar system plus categories of extra solar planets

+1 to this — could make our own little infinite space sim

**Comment by dmarcos** [comment]
What about signed distance field primitives a la shader toy? Has anybody experimented with them in WebVR?

http://iquilezles.org/www/articles/distfunctions/distfunctions.htm

**Comment by joshmarinacci** [comment]
Instead of creating more components how about some good documentation for how someone could do it? I've basically had to reverse engineer the ocean component to learn how to do dynamic geometry.

**Comment by dmarcos** [comment]
@joshmarinacci Have you read the component documentation? https://aframe.io/docs/0.6.0/core/component.html
How can we improve it? This issue is a brainstorming exercise to collect ideas for anybody to implement.

**Comment by donmccurdy** [comment]
I think what's missing from the components documentation (which might not make sense there anyway) would  be information about how to manipulate underlying three.js geometry. For example, I wrote the `<a-ocean/>` component while referencing [this tutorial](https://tympanus.net/codrops/2016/04/26/the-aviator-animating-basic-3d-scene-threejs/). 

That might be a common enough problem to be worth writing up somewhere. I've definitely pointed people to that code several times. But I think we'd also want to be clear that it's only recommended for dynamic stuff, and that if you want a model of an airplane (like in that tutorial) you should probably be using one of the modeling tools we list instead.

**Comment by ngokevin** [comment]
This is more in three.js's wheelhouse than A-Frame's domain. A-Frame's domain is more of the structure that houses three.js code. There are pages on how to interface with three.js within A-Frame. And modifying geometries is for advanced developers that know three.js.

But yeah, it'd be helpful for someone to create a Glitch example of a component modifying a geometry. Then we add it to the documentation sidebar under the Table of Contents to get live forkable examples.

To add to the doc, head to doc Markdown file header and add like:

```
examples:
  - url: https://glitch.com/~aframe-component-geometry
     title: Modifying three.js Geometry Component
```

**Comment by dmarcos** [comment]
A friend of mine ( @rlamana ) had actually started porting [the example](https://tympanus.net/codrops/2016/04/26/the-aviator-animating-basic-3d-scene-threejs/) that @donmccurdy pointed out to A-Frame. I've been begging him to finish it up. Ramoooon pretty please! :kissing_smiling_eyes: :kissing_smiling_eyes: :kissing_smiling_eyes: :kissing_smiling_eyes:

**Comment by Utopiah** [comment]
> Instead of creating more components how about some good documentation for how someone could do it? I've basically had to reverse engineer the ocean component to learn how to do dynamic geometry.
@joshmarinacci 

Reading [Writing a Component](https://aframe.io/docs/0.6.0/introduction/writing-a-component.html) in particular [Creating the Box Mesh](https://aframe.io/docs/0.6.0/introduction/writing-a-component.html#creating-the-box-mesh) describe precisely that. Maybe [<a-entity>.object3D](https://aframe.io/docs/0.6.0/core/entity.html#object3d) could be linked explicitly in [introduction](https://aframe.io/docs/0.6.0/introduction/) or [Developing with three.js](https://aframe.io/docs/0.6.0/introduction/developing-with-threejs.html). Alternatively the documentation could visually display the stack ([as I've done in a very ugly manner before](http://jsbin.com/yuwive/edit?html,output), as usual 😉) but apparently not everybody is a fan of that.

**Comment by rlamana** [comment]
@dmarcos actually it is practically finished... you can take a look at the code here: https://github.com/rlamana/a-aviator. I basically used your official documentation as my only source. This is the first time I use A-Frame so I guess there are probably better ways to do some of the things I did. I look forward to your feedback ;)

**Comment by fernandojsg** [comment]
@rlamana cool! Do you mind setting up `master` as the default github pages source and putting the link on the repo, so I believe it could be much easier for people to try it

**Comment by rlamana** [comment]
@fernandojsg done, https://rlamana.github.io/a-aviator/

**Comment by ngokevin** [comment]
Nothing actionable for A-Frame core here, continue to build procedural components and projects, and disperse them into the community. environment is pretty well adopted
