### ISSUE TITLE
GearVR controller right hand

### ISSUE THREAD

**Issue by gabrielperales** [aframevr/aframe#2844]
**Description:**
Controller doesn't appear when I set `<a-entity gearvr-controls="hand: right"></a-entity>` but they do if I set `hand: left`.

- A-Frame Version: 0.6.0
- Platform / Device: Samsung Internet 
- Reproducible Code Snippet or URL:

`<a-entity gearvr-controls="hand: right"></a-entity>`

**Comment by machenmusik** [comment]
The GearVR Controller has a handedness that is set when you pair it using the Oculus app.  (I believe the default is right hand.)  If you configured your controller to be left handed, then the GearVR Controller is exposed with left handedness, and so I would expect the behavior you are seeing.  Can you confirm whether that is the case?

**Comment by gabrielperales** [comment]
Hi @machenmusik, I have my controller set as right handed, to it should be exposed as right handed but I can only make it work setting `hand: lelft` or avoiding set `hand` and by default is on le left.

**Comment by clofts613** [comment]
Confirmed

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by machenmusik** [comment]
@gabrielperales can you confirm behavior with both Samsung Internet (in GearVR) and Oculus Browser?  I am wondering if this is a discrepancy in behavior between the two, or another issue specific to your use case, given that @clofts613 confirmed the expected behavior above.

**Comment by gabrielperales** [comment]
@machenmusik I just have bought the S8 and the Gear VR, so I'm not already familiar with the oculus system, but I think I have tried on both (both are called Samsung internet but one is through the oculus launcher, isn't it?) and I don't understand the difference between them.
Tomorrow I'll try it again and I will confirm that the issue is happening on both browsers.

**Comment by dmarcos** [comment]
The Oculus browser is included in Oculus Home. You have to open it with the button that says Internet in the bottom bar

**Comment by machenmusik** [comment]
@gabrielperales there is the Samsung Internet GearVR app, which I think you are using, and also a browser more integrated into Oculus Home https://m.vrheads.com/how-use-oculus-browser-gear-vr

**Comment by gabrielperales** [comment]
Ok, I will do more test tomorrow 'cause I don't have the device at home.

**Comment by vincentfretin** [comment]
I can confirm there is an issue with Samsung Internet (not Oculus browser) with Samsung S8 / Gear VR / Aframe 0.7.0. I put in bold what I think is wrong.
**It seems that Samsung Internet read the hand configured in preferences in reverse.**

With Samsung Internet with right hand configured in preferences:
- with `<a-entity gearvr-controls="hand: right">` the controller **doesn't show up**
- with `<a-entity gearvr-controls="hand: left">` the controller shows up on the left
- with `<a-entity gearvr-controls>` the controller shows up on the **left**

With Samsung Internet with left hand configured in preferences:
- with `<a-entity gearvr-controls="hand: right">`  the controller shows up on the right
- with `<a-entity gearvr-controls="hand: left">`  the controller **doesn't show up**
- with `<a-entity gearvr-controls>` the controller shows up on the **right**

With Oculus browser with right hand configured in preferences:
- with `<a-entity gearvr-controls="hand: right">` the controller shows up on the right
- with `<a-entity gearvr-controls="hand: left">` the controller doesn't show up
- with `<a-entity gearvr-controls>` the controller shows up on the right

With Oculus browser with left hand configured in preferences:
- with `<a-entity gearvr-controls="hand: right">` the controller doesn't show up
- with `<a-entity gearvr-controls="hand: left">` the controller shows up on the left
- with `<a-entity gearvr-controls>` the controller shows up on the left

**Comment by vincentfretin** [comment]
Is this an issue with A-Frame or Samsung Internet?
I don't really understand how the hand system config influence A-Frame here.
A-Frame appears to use `DEFAULT_HANDEDNESS: 'right'` always.
Do you guys have some pointers so we can maybe create a bug report to Samsung Internet?

**Comment by machenmusik** [comment]
if you can use the chrome remote web inspector while running Samsung Internet,
it would be great to understand what navigator.getGamepads() is returning;
Oculus Browser correctly populates the gamepad with a hand property matching left or right.
I wonder if what is happening is that Samsung Internet is not actually returning a hand string, or the wrong one...

**Comment by vincentfretin** [comment]
Thanks @machenmusik I'll try that this weekend.

**Comment by vincentfretin** [comment]
I put a `console.log(gamepads);` in `updateControllerList:` in `tracked-controls.js`
In Oculus browser with right hand in preferences:
![oculus_browser_right_hand](https://user-images.githubusercontent.com/112249/32133676-73d49f90-bbdd-11e7-9a06-c2581be5b7d6.png)

In Oculus browser with left hand in preferences:
![oculus_browser_left_hand](https://user-images.githubusercontent.com/112249/32133678-7f046508-bbdd-11e7-9896-18deeb4dc24c.png)

In Samsung Internet with right hand in preferences:
![samsung_internet_right_hand](https://user-images.githubusercontent.com/112249/32133638-c0edb9de-bbdc-11e7-9287-c15231d15439.png)
It shows `hand: "left"`!

In Samsung Internet with left hand in preferences:
![samsung_internet_left_hand](https://user-images.githubusercontent.com/112249/32133644-d5b098e6-bbdc-11e7-8283-128ad7369892.png)
It shows `hand: "right"`!

So it is definitely an issue in Samsung Internet.

**Comment by vincentfretin** [comment]
Now where is the issue tracker for Samsung Internet for VR... I'm searching it... Anybody knows?

**Comment by vincentfretin** [comment]
Found it, I created an issue there https://github.com/SamsungInternet/support/issues/22

**Comment by machenmusik** [comment]
@mkeblx ^^ ?

**Comment by mkeblx** [comment]
I'll have a look soon. Thanks

**Comment by dmarcos** [comment]
There seems to be a regression where gamepad extensions are disabled: https://forums.oculus.com/developer/discussion/comment/564429/#Comment_564429

**Comment by mkeblx** [comment]
For Samsung Internet handedness bug is resolved. Our next release will have fix in.

**Comment by dmarcos** [comment]
Excellent news. Thanks @mkeblx

**Comment by machenmusik** [comment]
Brilliant thank you!

**Comment by vincentfretin** [comment]
Thanks @mkeblx !
