### ISSUE TITLE
material.src not working in 0.6.0

### ISSUE THREAD

**Issue by madebynoam** [aframevr/aframe#2846]
**Description:**
Material.src appears to be broken in 0.6.0
Repro:
Set src on image primitive or
Set src in material="src: url"

Tried both with assets and as inline, but both get the same error in the console:
TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': No function was found that matched the signature provided.

- A-Frame Version: 0.6.0
- Platform / Device: Tested on desktop browsers (Chrome, Safari, Firefox)
- Reproducible Code Snippet or URL: 
https://free-harp.glitch.me/
https://glitch.com/edit/#!/free-harp

**Comment by ngokevin** [comment]
You'll want to use `<img>`, not `<a-asset-item>`

**Comment by madebynoam** [comment]
Strange I thought inline 'src' was also not working, but appears to work. Thanks for the tip!
