### ISSUE TITLE
Line component on a-cursor element is visible by default

### ISSUE THREAD

**Issue by jaydansand** [aframevr/aframe#2847]
After updating to 0.6.0 the cursor in VR mode has a visible (and green) line, even with implicit (default) or explicitly setting the raycaster component to `showLine: false`. This actually broke the [mouse-cursor](https://github.com/mayognaise/aframe-mouse-cursor-component) component we rely on: it no longer emitted `click` events when using the mouse or tapping the screen on an entity. It was solved by explicitly adding `line="visible: false"` to the `a-cursor`.

**Broken code (green line is visible in VR mode; mouse-cursor does not work correctly):**
```
<a-entity camera="userHeight: 1.6" look-controls mouse-cursor wasd-controls="enabled: false">
<a-cursor raycaster="showLine: false" geometry="primitive: ring; radiusInner: 0.02; radiusOuter: 0.03" />
</a-entity>
```

**Working (added `line="visible: false"` to `a-cursor`):**
```
<a-entity camera="userHeight: 1.6" look-controls mouse-cursor wasd-controls="enabled: false">
<a-cursor raycaster="showLine: false" line="visible: false" geometry="primitive: ring; radiusInner: 0.02; radiusOuter: 0.03" />
</a-entity>
```

- A-Frame Version: 0.6.0
- Platform / Device: Latest Chrome in Windows 10, iPhone 6S on latest iOS

**Comment by clofts613** [comment]
Makes sensr

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ngokevin** [comment]
dupe and fixed. https://github.com/aframevr/aframe/issues/2841
