### ISSUE TITLE
Camera rotation not being applied after updating webvr-polyfill

### ISSUE THREAD

**Issue by cuffers** [aframevr/aframe#2848]
I have been working on a VR tour of Lancaster castle and have been having some issues with camera rotation since updating from webvr-polyfill v0.9.25 to v0.9.35.

Previously, we were able to rotate the camera within the scene to point in the correct direction after transitioning from one scene to another in order to make the transition feel more natural however this has stopped working on mobile since updating the polyfill and the camera rotation we set seems to be overwritten by the physical rotation of the device, making the transition feel quite jarring.

Here is a link to the project: http://m.lancs.ac.uk/VR/

**Comment by ngokevin** [comment]
Use a wrapper entity or temporarily set look-controls to disabled. https://stackoverflow.com/questions/36677671/aframe-set-camera-position-at-runtime
