### ISSUE TITLE
Invisible <a-plane> when nested in a <a-box>

### ISSUE THREAD

**Issue by Leopoldthecoder** [aframevr/aframe#2851]
**Description:**

- A-Frame Version: 0.6.0
- Platform / Device: macOS / Chrome, Android / Chrome
- Reproducible Code Snippet or URL: https://jsfiddle.net/jn1e2eo7/

I'm attaching a white `a-plane` to each of the six sides of a black `a-box`, but only three of them are visible. The other three planes do exist because if I enlarge these three planes I can actually see them, but still they go invisible at some certain angles: https://jsfiddle.net/aca7yLno/.

I'm not sure what caused this.

**Comment by dmarcos** [comment]
You have to set `material="side: double"` https://jsfiddle.net/q2d2nxdo/
