### ISSUE TITLE
Double vision

### ISSUE THREAD

**Issue by Marchhill** [aframevr/aframe#2857]
**Description:**

- A-Frame Version: *Commit* 89d1de0782a06a06f022c464cb1c1a31ec18b9ee
- Platform / Device: Samsung Galaxy S7
- Reproducible Code Snippet or URL: https://aframe.io/examples/

Double vision on hello world example, when using a Samsung Galaxy S7, with google cardboard or class vr.

**Comment by dmarcos** [comment]
@Marchhill Can you try with master? Does the webvr-polyfill demo have the same problem? http://googlevr.github.io/webvr-polyfill/examples/basic/

**Comment by Marchhill** [comment]
@dmarcos same problem with the polyfill. Also [this](marchhill.github.io/VR-Maths-Shapes/) is my project that uses the latest A-Frame development version by including it with `https://rawgit.com/aframevr/aframe/538439e/dist/aframe-master.min.js`. It still has double vision.

**Comment by ngokevin** [comment]
What does double vision look like?

**Comment by Marchhill** [comment]
@ngokevin The vision is blurry, and the two images for both eyes do not merge into one. There is one cursor for each eye, so you can see two cursors. I tried this with an iPhone 6S+ and it was not an issue, only on the S7.
![screenshot](http://i.cubeupload.com/bhbmU9.png)

**Comment by coppercompton** [comment]
I was having the same problem with my S7. Noticed it did not happening with one or two of the examples on aframe.io. Hello Metaverse works. It is using version 0.5.0. Downgraded my project from 0.6.1 to 0.5.0 and it viewed without any issues on the S7, 0.6.0 does not view correctly either.

**Comment by machenmusik** [comment]
is there a difference in DPDB and maybe the specific model of phone has wrong/missing entry?

**Comment by clavis-magna** [comment]
I am having this same issue with Chrome on Galaxy S7 and aframe 0.6 and 0.6.1 . Latest stable Firefox is not having the issue, so assume it to be chrome related?

**Comment by dmarcos** [comment]
@clavis-magna Does this happen also with the `webvr-polyfill` example? http://googlevr.github.io/webvr-polyfill/examples/basic/

**Comment by clavis-magna** [comment]
@dmarcos yes, the webvr-polyfill example also displays incorrectly. I have attached screenshots of chrome (displaying incorrectly) and firefox (displaying correctly) on Galaxy s7. 

![screenshot_20170808-065651](https://user-images.githubusercontent.com/2109125/29046101-54ddc09e-7c09-11e7-88c9-cae257a1e920.jpg)
![screenshot_20170808-065808](https://user-images.githubusercontent.com/2109125/29046100-54d786e8-7c09-11e7-87c8-5bd9533dd2fd.jpg)

**Comment by clavis-magna** [comment]
Apparently Samsung changed the default resolution of the S7 in an update. [ https://github.com/googlevr/gvr-unity-sdk/issues/421 ] To fix the issue settings > display > screen resolution > WQHD (2560 x 1440) . No more double vision.
