### ISSUE TITLE
Nav Arrows Showing to No Effect

### ISSUE THREAD

**Issue by darkwing** [aframevr/aframe#2859]
**Description:**

- Platform / Device: Desktop Chrome
- Reproducible Code Snippet or URL:  https://aframe.io

These arrows show in the left navbar in Chrome Desktop and don't appear to do anything:

<img width="231" alt="arrows" src="https://user-images.githubusercontent.com/46655/28034421-bea864ec-6576-11e7-99f1-064ad0d6e90d.png">

**Comment by darkwing** [comment]
Error detail from console:

Uncaught TypeError: Cannot read property 'nextElementSibling' of null
    at getDestNavLink (examples.js:9)
    at HTMLAnchorElement.<anonymous> (examples.js:4)

**Comment by dmarcos** [comment]
I believe those arrows should only show up in mobile @ngokevin ?

**Comment by ngokevin** [comment]
Yeah, we can just hide these for desktop

**Comment by ngokevin** [comment]
The repo is on https://github.com/aframevr/aframe-site but the arrows work for me now

**Comment by ngokevin** [comment]
Never mind, they only don't work on the Logo example, but I moved the issue
