### ISSUE TITLE
Re-parenting the camera entity breaks camera movement

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#2860]
**Description:**

After moving the default camera to be inside another entity via a call to `.appendChild`, the camera is frozen and won't respond to `look-controls` movement nor VR-mode headset orientation. 
  
- A-Frame Version: New in 0.6.0, issue does not occur in 0.5.0
- Platform / Device: Nightly & Chromium, desktop & Vive
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/voracious-canvas

The example uses 'camera-ready' to trigger the re-parenting, but this does not appear to be a synchrony issue, as the same behavior can be seen by making the change via the console on a running scene. I found this because `super-hands` `a-locomtor` checks for scenes with the default camera and moves the camera to be a child of itself to enable movement. The feature ended up kinda hacky and re-parenting the camera already caused some strange behavior like losing the `userHeight` value and generating console warnings, so I'd already been thinking of dropping it; just reporting this FYI

**Comment by dmarcos** [comment]
Re parenting is tricky to achieve. Can you have two cameras and switch between them?

**Comment by wmurphyrd** [comment]
I think I'm going to move my check earlier in the setup and insert a `a-camera` in the DOM before aframe core checks if a default is needed if no other manually specified camera is found. 

So, I don't need a fix for this issue - just reported it to document it.

**Comment by dmarcos** [comment]
This is a dup of https://github.com/aframevr/aframe/issues/2425
