### ISSUE TITLE
Gaze problem in desktop and mobile hand held mode

### ISSUE THREAD

**Issue by Kumaresh-Rajalingam** [aframevr/aframe#2863]
Hello
I want to turn on the gaze only in **mobile VR mode** but the problem I am facing here is the gaze is turned on mobile hand-held mode also how to enable the gaze only in mobileVR mode

**code:
var cursorEl = document.querySelector('a-cursor');
if (!AFRAME.utils.device.isMobile()) {
  cursorEl.parentEl.removeChild(cursorEl);**

Thanks in advance

**Comment by dmarcos** [comment]
Please use StackOverFlow or the Slack channel for questions. Issues are just for bugs or feature requests.
