### ISSUE TITLE
Firefox Nightly non responsive after exiting VR mode (with Oculus Rift).

### ISSUE THREAD

**Issue by qster123** [aframevr/aframe#2864]
A-Frame 0.6.0
Windows 10 / Oculus Rift

After exiting VR mode in FireFox Nightly the desktop window of Nightly is white and non-responsive. It 
doesn't actually crash with a Windows error but I need to close and restart nightly to carry on.

This shot was taken just after exiting VR mode, shortly after it goes completely white. 

![image](https://user-images.githubusercontent.com/10384836/28130090-0c02c2c6-6736-11e7-8edc-fdebfd1b213f.png)

**Comment by dmarcos** [comment]
I can't reproduce this with Nightly + Vive

**Comment by qster123** [comment]
Seems resolved in the latest update.
