### ISSUE TITLE
Event on asset display or render

### ISSUE THREAD

**Issue by kassemEzz** [aframevr/aframe#2866]
Is there an event that emits when the image is actually displayed and not only only loaded.
As I just discovered, event "load" or "loaded" triggers before the image is displayed, specially if the image has a large size.

Thanks for the great work

- A-Frame Version: 0.5

**Comment by ngokevin** [comment]
`materialtextureloaded`

**Comment by kassemEzz** [comment]
Thanks very much.... it worked perfectly on sky element with image src.
