### ISSUE TITLE
Inspector loses some controls sometimes

### ISSUE THREAD

**Issue by autonome** [aframevr/aframe#2867]
**Description:**

- A-Frame Version: 0.50
- Platform / Device: Chrome on Mac
- Reproducible Code Snippet or URL: Remix a new glitch from https://aframe.io/examples/showcase/360-image-gallery/

The controls in two areas are missing:

* The row with "copy scene", "save to html", "add new entity"

* The row with "translate", "rotate", "scale" (the "local" bit is visible)

**Comment by autonome** [comment]
Sometimes a hard reload fixes the problem. Some kind of race condition maybe.

**Comment by dmarcos** [comment]
That particular boilerplate is not updated to the latest A-Frame Version (0.6.0). I opened an issue on its repo to upgrade: https://github.com/aframevr/360-image-gallery-boilerplate/issues/8

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector would also be a better place to file. Currently working on Inspector a bit now. Thanks!
