### ISSUE TITLE
Some pages in the docs dont have a link to the next page in that section

### ISSUE THREAD

**Issue by ShaguftaMethwani** [aframevr/aframe#2868]
**Description:**

- A-Frame Version: 0.6.0
- Platform / Device: Mozilla Firefox for desktop
- Reproducible Code Snippet or URL:  For example the page https://aframe.io/docs/0.6.0/core/mixins.html
![capturet](https://user-images.githubusercontent.com/6694476/28238701-28eab6ee-6977-11e7-882c-d509c369689e.PNG)

**Comment by AkshayIyer12** [comment]
Hi Can I work on this issue?

**Comment by dmarcos** [comment]
@Akshaylyer12 Sure! Open a PR when you have something ready.

**Comment by AkshayIyer12** [comment]
@ShaguftaMethwani @dmarcos I understand the changes to make but can you people me in the direction where is the file located. I'm unable to locate the file.

**Comment by ngokevin** [comment]
This is an issue that is already filed on the aframe-site. Unfortunately, we cannot hand-hold through the entire process. If you are unable to find it, I recommend to get acquainted with the codebase more and come back to it later.
