### ISSUE TITLE
Primitives should come before other components?

### ISSUE THREAD

**Issue by ShaguftaMethwani** [aframevr/aframe#2869]
**Description:**

- A-Frame Version: All
- Platform / Device: All
- Reproducible Code Snippet or URL: The sidebar index on docs. 
I guess it would be better if the primitives come before the other components orderwise.

![capturett](https://user-images.githubusercontent.com/6694476/28238821-c119b968-6979-11e7-9320-33aa9c5b2235.PNG)

**Comment by dmarcos** [comment]
We're trying to deemphasize primitives since they are just aliases over an entity + components and introduce a lot of quirks and inconsistencies.
