### ISSUE TITLE
Easy support for Google Blocks outputs

### ISSUE THREAD

**Issue by eordano** [aframevr/aframe#2877]
I've been playing with the Google Blocks tool and I'm totally amazed by it. I think that aframe will benefit a lot from an easy way to import objects from Blocks. Some points that would need to be discussed are:

- Are there any changes that need to be done for aframe to import Blocks? From the looks of it, it seems to export a pretty standard `obj`, but not sure about material/colors.
- Should we write a tutorial on how to import Blocks creations to aframe?
- It would be great to have a component that takes the URL of a folder with the decompressed contents of the zip exported by blocks and places that in the scene.

**Comment by donmccurdy** [comment]
> Are there any changes that need to be done for aframe to import Blocks?

Some Blocks will contain ngons (faces with >4 sides). The three.js OBJLoader can't render these, and whether it really should be fixed to do so, I'm not sure. The workaround is to triangulate the mesh in Blender, or perhaps some easier tool. We could, at minimum, document how to do this.

> It would be great to have a component that takes the URL of a folder with the decompressed contents of the zip exported by blocks and places that in the scene.

Mr. Doob has [added support in the three.js editor](https://github.com/mrdoob/three.js/commit/6cfda9b71b3456ff095233a70785fa30a7080526) (not core three.js) for loading Blocks directly from the .ZIP. We could consider doing the same in A-Frame, although IMO it's the sort of feature that would be nice for testing but bad for published code.

**Comment by ngokevin** [comment]
Support for ngons landed. Also https://archilogic-com.github.io/aframe-gblock/
