### ISSUE TITLE
a-animation of opacity or height forces from = 0 during repeats

### ISSUE THREAD

**Issue by andreasplesch** [aframevr/aframe#2883]
**Description:**

Using ` <a-animation> ` for material.opacity resets the ` from ` value to 0 for repeated animation cycles if ` from ` is not explicitly provided.

The first animation cycle works correctly. Subsequent animation cycles use a ` from ` value of 0 instead of the attribute value. Repeated cycles use self.initialValue for ` from `. initialValue appears to be set to an empty object which may not be the intention.

- A-Frame Version: 0.6
- Platform / Device: all
- Reproducible URL: https://glitch.com/edit/#!/plum-mayonnaise?path=public/index.html:11:11

The box opacity is animated from completely transparent to opaque but should be animated from only slightly transparent to opaque.

**Comment by andreasplesch** [comment]
The easy workaround is just to provide the from value as a-animation property.

Other component properties may also be affected.

**Comment by andreasplesch** [comment]
Here is the example using a first solution:
https://just-fly.glitch.me/

The used solution is:
```js
getTween: { ...
// Store initial state.
self.initialValue = self.initialValue || cloneValue(from); //currentValue);
...
function getForComponentAttribute () { ...
    if (dataFrom === undefined) {  // dataFrom can be 0.
      from[attribute] = getComponentProperty(el, attribute);
    } else {
      //from[attribute] = dataFrom;
      from[attribute] = typeof (dataFrom == 'object') ? dataFrom[attribute] : dataFrom ;
    }
```
probably not ideal and not thoroughly tested but a start.
[Why not rely on Tween for the repeats ?]

**Comment by andreasplesch** [comment]
I thought a little bit more about a more elegant, concise solution but could not immediately find one. The fixed glitch tests most kinds of animations with the proposed fix and they continue to work.

If desirable, I could prepare an initial PR for further review, first to see if travis testing picks up something ?

**Comment by ngokevin** [comment]
We've deprecated a-animation. Try https://github.com/ngokevin/kframe/tree/master/components/animation and file issues, and component will be merged in in the future.

In these cases, might need additional JS to control iterations of the animation.
