### ISSUE TITLE
query param for injecting motion capture and replaying recordings

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#2886]
**Description:**

We'll soon be integrating motion capture into the Inspector to make the workflow seamless for taking and replaying recordings as a developer. These tools make it easy to take recordings and upload them and get back a URL (myjson.com) for the recording. These recording URLs can be passed around easily, let's make it easy to consume them.

They could be consumed via the new Inspector tools, but there's the step of opening the Inspector, adding the recording, and hitting play. This also can't be done on mobile.

### Sharing / "Responsiveness"

What if you want to share your scene with a recording without having to modify or inject your actual scene code? A query parameter would make the workflow seamless for viewing and sharing recordings as a user.

Say a developer develops a 6DoF experience where they paint things, and want to share it as a URL so people can see them painting things. Their scene URL is `https://dev.com/aframe-paint-things/`. Without modifying the code (i.e., searching for the mocap component and setting up the `avatar-replayer`), they'd like to just do `https://dev.com/aframe-paint-things/?recording=https://myjson.com/bin/abcdef`.

Then perhaps someone else sees that cool scene and wants to do their own recording to share themselves painting things. They can take a recording themselves (using the Inspector), and share themselves without touching the scene code (because they can't). `https://dev.com/aframe-paint-things/?recording=https://someperson.com/myrecording.json`.

### Docs and Examples

For evangelizing/teaching A-Frame, it'd be useful so we can share and feature any scene with a recording without having to modify each scene to be able to replay them. I would add recordings to any 6DoF scenes we feature on the aframe.io homepage, or any examples in the docs that feature 6DoF. ```https://aframe.io/a-painter/?recording=fox.json```

### Bug Reporting

For bug reports, someone can take a recording and pass to you as a URL `https://dev.com/aframe-paint-things/?recording=https://tester.com/bug2.json`, and the developer just has to click and see the bug being reproduced.

## Implementation/API

Like the Inspector component, create a `motion-capture` component which main job is to listen to `?recording={URL}` query parameter. 

The `motion-capture` component will inject the motion capture components and set the `avatar-replayer` component. That's pretty much it, the `avatar-replayer` component will handle the XHR and auto play.

**Comment by donmccurdy** [comment]
I would have a concern about making this on-by-default in all scenes. Suppose I make a game in A-Frame; where players have persistent inventory of in-game objects and can trade with other players. If I can trick someone into clicking a shortened link that contains a malicious recording, that recording could potentially give away my inventory at 10x speed. Equivalent to in-VR XSS.

**Comment by ngokevin** [comment]
Solid point, thinking about that alone feels so futuristic. You've been body snatched!

Will think of other ways, like perhaps it shows a button.

**Comment by ngokevin** [comment]
wontfix
