### ISSUE TITLE
[feature] allow animated mixins

### ISSUE THREAD

**Issue by andreasplesch** [aframevr/aframe#2888]
**Description:**

Allow mixin assets to have animated components. Think rather than just a _red_ mixin for a material with a red color, allow _pulsating_red_ for a material with an animated color.

```html
<a-assets>
    <a-mixin id="red" material="color: red"></a-mixin>
    <a-mixin id="pulsating_red" material="color: red; opacity: 0.5">
        <a-animation attribute="material.opacity" from="0.5" to="1.0" repeat="100"><a-animation>
    </a-mixin>
</a-assets>
A few flashing signs
```

I think mutations to mixin attributes are already propagated to entities which use the mixin. It would be a natural and perhaps even expected feature to also allow mutations by mixin animation.

- A-Frame Version: future
- Platform / Device: all
- Reproducible Code Snippet or URL: NA

**Comment by andreasplesch** [comment]
Jotting down implementation thoughts: 
- add .isPlaying to a-mixin.js
- make .setAttribute for a-mixin.js similar to entities
- force DOM update to trigger MutationObserver
- or have additional onUpdate Tween callback for mixins which updates mixin users (the same as the MutationObserver callback)

**Comment by ngokevin** [comment]
I'd look for a component-based API https://github.com/ngokevin/kframe/tree/master/components/animation rather than adjust across A-Frame to account for `<a-animation>` API.

If you need to encapsulate entities, the template component is another option.

**Comment by andreasplesch** [comment]
across A-Frame ? Anyways, right, the animation component should work as a mixin.

**Comment by andreasplesch** [comment]
Well, the animation component also does not support mixins, currently: https://github.com/ngokevin/kframe/issues/90
