### ISSUE TITLE
Consider renaming `element` attribute for templates

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#289]
It can be confusing, especially with how we use the term `entity`.

You have to do

```html
<template is="a-template" element="a-image">
…
</template>
```

not

```html
<template is="a-template" entity="a-image">
…
</template>
```

It's probably worth calling out more explicitly in the [__`Core > Templates`__ docs](https://aframe.io/docs/core/templates.html).

See https://github.com/aframevr/aframe/blob/master/elements/templates/a-image.html for example.

<hr>

Discovered via https://twitter.com/jose_pedro_dias/status/677312263947177988

**Comment by ngokevin** [comment]
I suggested `name` awhile back.

**Comment by cvan** [comment]
> I suggested `name` awhile back.

I was afraid to use `name` because that's already a used HTML attribute. but, interestingly, it looks like it's been [deprecated in the HTML5 spec](http://www.w3.org/TR/html5/obsolete.html#attr-a-name) (as it was always used afaik as an alternative to `id`, useful for hashes and frame targets).

also, `name` is what the now-deprecated [`<polymer-element>`](https://pascalprecht.github.io/2014/07/14/inheritance-and-composition-with-polymer/) called it.

**Comment by ngokevin** [comment]
so should be okay to use `name`? does it throw warnings or anything?

**Comment by cvan** [comment]
> so should be okay to use `name`? does it throw warnings or anything?

no, so we can

**Comment by ngokevin** [comment]
Will be soon removing templates until we reach a better solution.
