### ISSUE TITLE
Links for version 0.6.1 broken

### ISSUE THREAD

**Issue by ShaguftaMethwani** [aframevr/aframe#2890]
**Description:**

- A-Frame Version:
- Platform / Device: All
- Reproducible Code Snippet or URL: https://aframe.io/docs/0.6.0/components/obj-model.html#troubleshooting refers to a page if more information is needed, and the page link has 0.6.1 in the URL and as a result gives a 404 error on clicking on it.

**Comment by ngokevin** [comment]
Yeah, that URL should be a relative one
