### ISSUE TITLE
Transparent PNG support should be built-in

### ISSUE THREAD

**Issue by autonome** [aframevr/aframe#2892]
**Description:**

- A-Frame Version: 0.6
- Platform / Device: all
- Reproducible Code Snippet or URL: https://stackoverflow.com/a/43947349/4096929

This functionality comes up regularly at events where we're introducing people to A-Frame. Registering and adding a custom component for it seems needlessly complicated.

Adding this to the default A-Frame set of features seems a pretty big win for users, in exchange for a tiny bit of code (per that example in the URL above).

**Comment by donmccurdy** [comment]
So we just need to add `alphaTest` to the `material` component, similar to `depthTest` which is already there?  Sounds like a good idea to me, +1.

**Comment by machenmusik** [comment]
Already there
https://github.com/aframevr/aframe/blob/master/src/components/material.js#L23

**Comment by donmccurdy** [comment]
Oh nice, so #2516 would have just gone live with v0.6... in that case let's add docs and call it good.

**Comment by autonome** [comment]
No fair going back in time and fixing things before I file them!!
