### ISSUE TITLE
Camera Rotation Animation

### ISSUE THREAD

**Issue by apiaget** [aframevr/aframe#2898]
I'm currently trying to animate a camera's rotation in a scene. The animation should occur after looking at a circle for 1 second.

First I tried to directly animate the camera, apart the fact that it doesn't seem to work on chrome mobile (v57), it seemed to "block" the ability to look on the floor. [Short screen capture of the problem](https://gfycat.com/SmoggyQuarrelsomeDavidstiger).

I then tried to animate a container containing the camera as suggested by kevin [here](https://github.com/aframevr/aframe/issues/2714#issuecomment-305892656). That second option produced an other problem, it seems that all the sky is displaced and I don't understand how to "correct" that. But on the other side, the second option (container) worked in mobile browser, in a cardboard.

My questions are :
- Are theses behaviors expected ?
- If so, any ideas or links to help me understand how to do what I am trying to do ?

My setup :
- A-Frame 0.6.1 & aframe-animation-component
- Windows 10, Chrome 59, Firefox 54
- Reproducible Code Snippet or URL:

Animation on the camera :
[https://codepen.io/apiaget/full/XgLzNQ/](https://codepen.io/apiaget/full/XgLzNQ/)

Animation on a container containing the camera :
[https://codepen.io/apiaget/full/MoMQzV/](https://codepen.io/apiaget/full/MoMQzV/)

I also posted the question on [StackOverflow](https://stackoverflow.com/questions/45194712/a-frame-0-6-1-camera-rotation-animation) but I was starting to think that the behaviour wasn't expected and that it may be a bug somewhere, that is why I am here.

Thanks
apiaget

**Comment by dmarcos** [comment]
First thing is that in VR you should not animate the camera and let the user have control of it. This won't work well in a headset.
In the case of the nested camera composing rotations is not a trivial business in 3D. The result you're getting is expected.
I don't think this is an issue on the A-Frame side. Let's leave the discussion to the SO question.

**Comment by Micah1** [comment]
dmarcos said on github "First thing is that in VR you should not animate the camera and let the user have control of it. This won't work well in a headset."
I beg to differ, please hear me out, in the Oculus Go app called Altspace VR the user has full control of the camera, but if you press up on the trackpad you get an arc teleport forward, if you press left on the trackpad you sort of teleport in your rotation to the left if you press right on the trackpad you teleport in your rotation to the right, if you press back on the trackpad you sort of teleport backwards one step. This navigation system is one of the best I have ever used in VR, and that includes on both systems with 3dof controllers and systems with 6dof controllers. This is what people want, and once you try the navigation system of AltspaceVR on the Oculus Go or the Mirage Solo I think you too will want to create this type of navigation control.
