### ISSUE TITLE
<a-scene background="">

### ISSUE THREAD

**Issue by mrdoob** [aframevr/aframe#2908]
three.js r87 will bring a optimized handling of `scene.background` and should work nicely in VR.

https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLBackground.js#L26-L108

I think a-frame should add support for this. Right now I see people creating spheres and adding them to the scene which is not the most optimal way of doing it.

Maybe `<a-background>` as a component could also work. That way one could add more logic to it like converting equirectangular to cubemaps (using `CubeCamera`) automatically.

**Comment by dmarcos** [comment]
👍

**Comment by MichaelHazani** [comment]
I'm thinking `<a-scene background='whatever'>` would be more in line with the existing API - @mrdoob , can you please elaborate about the reasoning for `<a-background>` and the automatic conversion? Is there already a way to do that in three or is that a proposed feature?
