### ISSUE TITLE
Click event not working in a-text

### ISSUE THREAD

**Issue by prabhatsinh** [aframevr/aframe#2919]
- A-Frame Version: 0.6.0
- Platform / Device: Desktop
- Reproducible Code Snippet or URL: https://codepen.io/prabhatsinh/pen/LjZPzv

Please check above code pen link, I have added two elements a-box and a-text. Click event is not working in <a-text> element. 

It is working fine in <a-box> element.

**Comment by ngokevin** [comment]
1. Need a geometry on the text.
2. `onclick` is not supported. Use event listeners. https://aframe.io/aframe-school/#/9/4

https://aframe.io/docs/0.6.0/components/text.html#limitations

**Comment by prabhatsinh** [comment]
Hi thanks for  quick replay,

but it's working fine in 0.5.0 version
https://codepen.io/prabhatsinh/pen/OjXBqb

Please check above link

**Comment by prabhatsinh** [comment]
It's working in 0.6.0, we need to a plane to make it work in text.

<a-text color="green" position="-1 2 -4" value="Home" class="clickable" align="center" width="3" geometry="primitive: plane; width: 1; height: 0.4" material="color: none"></a-text>
