### ISSUE TITLE
Device orientation not working in landscape w/ Firefox for Android

### ISSUE THREAD

**Issue by eviljeff** [aframevr/aframe#292]
Works in portrait, but flipping the device to landscape (as required obviously) makes the horizontal/vertical movement wrong (i.e. look up, the scene moves left).  Tried in dev edition; nightly wouldn't render at all so couldn't confirm.

**Comment by caseyyee** [comment]
@eviljeff what browser and OS?

**Comment by eviljeff** [comment]
Android 5.0.1

**Comment by supnah** [comment]
Experiencing the same on a Nexus 5x running 6.0.1

**Comment by caseyyee** [comment]
Yes, this is an issue that we are aware of and tracking down a fix for.

Also experiencing the same on my One+ device too.

**Comment by ngokevin** [comment]
Fixed with latest polyfill bump
