### ISSUE TITLE
strange png transparency behaviour

### ISSUE THREAD

**Issue by 1d10t** [aframevr/aframe#2923]
i used mesh traversing to make materials transparent and it was done, but not on both sides.
[see screenshot](http://f2.s.qip.ru/lRCWJw82.png)

- A-Frame Version: 0.6.1 RELEASE
- Platform / Device: Google Chrome @ Win64 Desktop
- Reproducible Code Snippet or URL: https://rawgit.com/1d10t/test/05e3fdfb71348aa2a00c1d7bf3b562ad12f95d80/a-frame-webcam-dae.html

**Comment by Utopiah** [comment]
Different from #666 ?

**Comment by donmccurdy** [comment]
It is the same thing, and unfortunately there is no perfect solution right now. Transparency and order-independent rendering are very difficult to get right. We would need things like https://github.com/mrdoob/three.js/issues/4814 to be solved.

But with luck you might find that `material="alphaTest: 0.5"` helps here, as mentioned in #666. Going to close this to merge the threads.

**Comment by akaSpy** [comment]
@donmccurdy 
Hello, can you give me some advice how I can use this parameter (alphaTest: 0.5) in case of using glTF 2.0?

**Comment by donmccurdy** [comment]
Can't guarantee it would work in your case, but yeah:

```js
var el = document.querySelector('#my-model');
el.addEventListener('model-loaded', function (e) {
  e.detail.model.traverse(function (node) {
    if ( node.isMesh ) node.material.alphaTest = 0.5;
  });
});
```

**Comment by akaSpy** [comment]
@donmccurdy 
Many thanks for your help, now it works!
