### ISSUE TITLE
Component selector fails to return element on dynamically created elements.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#2928]
given component:

```js
AFRAME.registerComponent('my-component', {
    schema: { type: 'selector' },
    update: function () {
      console.log('selected element', this.data);
    }
});
```

markup:

```html
<a-box></a-box>
<a-entity my-component="a-box"></a-entity>
```
console logs expected result:
![image](https://user-images.githubusercontent.com/1560884/28900878-12130238-77a9-11e7-811e-7f4fad4947c1.png)

when doing the same when creating element using js:
```js
var scene = document.querySelector('a-scene');
var createEl = document.createElement('a-entity');
createEl.setAttribute('my-component', 'a-box');;
scene.appendChild(createEl);
```

I get this:

![image](https://user-images.githubusercontent.com/1560884/28900918-640cf846-77a9-11e7-897f-4499cef83443.png)

- A-Frame Version: 0.6.1 (tested to work fine with 0.6.0)
- Platform / Device: Chrome, Firefox
- Reproducible Code Snippet or URL:
https://glitch.com/edit/#!/heartbreaking-deposit

**Comment by caseyyee** [comment]
I should point out that if I listen to the loaded event _then_ setAttribute to for component, it works fine.

**Comment by ngokevin** [comment]
We prescribe always putting JS into components, even a `main` component. This allows code to be executed at the proper time, when things are loaded and ready.

https://aframe.io/docs/0.6.0/core/scene.html#running-content-scripts-on-the-scene

https://aframe.io/docs/0.6.0/introduction/javascript-events-dom-apis.html#where-to-place-javascript-code-for-a-frame

Listening to the `loaded` event outside of a component is expected otherwise if flying loose outside a component.

**Comment by caseyyee** [comment]
It's happening inside components too @ngokevin 

As an example, this breaks:
https://github.com/aframevr/a-saturday-night/blob/master/src/components/states/dancing.js#L67

**Comment by ngokevin** [comment]
The code there is a bit more complex. Asynchronous operations with components running in non-deterministic order. Wiring is more necessary in those cases. Either:

- If a component A creates an element that component B needs, I'd have component A communicate an event when it's ready so component B knows when to run. 
- Component A can `setAttribute` that `selector` property of component B when it's created.
