### ISSUE TITLE
Change rayOrigin dynamically bug

### ISSUE THREAD

**Issue by stephanedemotte** [aframevr/aframe#2929]
**Description:**

- A-Frame Version: 0.6.1
- Platform / Device: Desktop / Mac / Chrome
- Reproducible Code Snippet or URL: [repro](https://jsfiddle.net/ro4e4mds/)

Hi !

We can change rayOrigin from `entity` to `mouse` but when we try to change from `mouse` to entity nothing append.

Step to repro in the jsfiddle.
1 - try to gaze objects... the status change ! yes !
2 - click on the blue button (to switch to mouse mode)
3 - try to click with mouse, the status change again ! yes !
4 - toggle one more time to switch in entity mode
5 - gaze not working.

Thanks !

**Comment by stephanedemotte** [comment]
no news ?
it's not a bug ?

**Comment by azmartone** [comment]
Happens for me too 
A-Frame Version: 0.7.1
Platform / Device: Desktop / Mac / Chrome

**Comment by azmartone** [comment]
Work around: I ended up destroying and re-creating a new cursor entity whenever, the rayOrigin changes.

**Comment by ngokevin** [comment]
Doesn't quite make sense to have the same entity do both since one is head-fixed and one is global on the scene.

You can have two cursor entities and enable/disable them as needed with `raycaster.enabled`.
