### ISSUE TITLE
Mouse Drag Stops Outside of Canvas

### ISSUE THREAD

**Issue by mattdesl** [aframevr/aframe#293]
Mouse dragging in Chrome (OSX) stops when you move outside the bounds of the canvas. This occurs on the demos as well:
https://aframe.io/aframe/examples/showcase-spheres-and-fog/

One solution is to add the mouse events to the window element, but then compute the x/y offset relative to the canvas. See [here](https://github.com/mattdesl/mouse-event-offset) for reference.

**Comment by cvan** [comment]
Yeah, good call. We'd need to address it here: https://github.com/aframevr/aframe-core/blob/52ddcc/src/components/look-controls.js#L44-L53

Related: we previously had this [issue with dragging with dragging beyond the canvas and releasing](aframevr/aframe-core#328).

**Comment by ngokevin** [comment]
Accidentally closed during merge

**Comment by ngokevin** [comment]
Fixed https://github.com/aframevr/aframe/commit/f420a45251f38f0c6484038c3c2db884a003c9bc
