### ISSUE TITLE
link with red color

### ISSUE THREAD

**Issue by Ai01** [aframevr/aframe#2930]
when create a link with js. l can't delete the red color in circle.
<img width="739" alt="bug" src="https://user-images.githubusercontent.com/18245929/28992903-5e80fb50-79db-11e7-8308-1f5d6c7d2c27.png">
thank you with much.
```js
    var entityEl = document.createElement('a-entity');
    entityEl.setAttribute('id',`link-${index}`);
    entityEl.setAttribute('link', {
      href: `chart.html?machineId=${item.name}`,
      title: item.name,
      color: getColor(item.status),
      image: 'src/img/sunrise.png',
    });
    entityEl.setAttribute('position', getLoaction(index));
    entityEl.setAttribute('text', {
      value: Math.round(item.data.temp).toString(),
      height: 5,
      width: 8,
      color: 'white',
      align: 'center'
    });
```

**Comment by dmarcos** [comment]
Do you have a codepen or a gltich illustrating the problem? What does `getColor(item.status)` return? What about if you do `color: 'green'` Does it work?

**Comment by rdub80** [comment]
The AFrame Magenta webgl shader color `vec4(0.93, 0.17, 0.36, 1.0) ` is hard coded in the link component https://github.com/aframevr/aframe/blob/v0.6.0/src/components/link.js#L343

**Comment by dmarcos** [comment]
Yeah. We should maybe expose it as a component property
