### ISSUE TITLE
aframe (template?) examples fail silently on CORS errors in Firefox (but not in Chrome)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#295]
Load `file:///opt/aframe/examples/template-sky/index.html`

### Firefox
![image](https://cloud.githubusercontent.com/assets/203725/11878260/7f4d0d46-a4a9-11e5-8c81-8c8cea527fdd.png)

### Chrome
![image](https://cloud.githubusercontent.com/assets/203725/11878365/2eb7dbf8-a4aa-11e5-8973-aff1e5a59e29.png)

Same issue with `file:///opt/aframe/examples/animation-generic-logo/index.html`

But somehow aframe-core's examples (`file:///opt/aframe-core/examples/texture/index.html`, for example) are throw proper errors in the Console in Firefox:

![image](https://cloud.githubusercontent.com/assets/203725/11878446/c979417c-a4aa-11e5-9a12-4841e56b1d75.png)

**Comment by mrdoob** [comment]
Update to the last `dev` version of three.js. https://github.com/mrdoob/three.js/pull/7661

**Comment by mrdoob** [comment]
Actually, may be unrelated.

**Comment by cvan** [comment]
fixed by PR #930 when templates are removed in favour of primitives. if we reintroduce templates defined in HTML, this will again be an issue (see issue #930).
