### ISSUE TITLE
a-image fails

### ISSUE THREAD

**Issue by jpnayak** [aframevr/aframe#2956]
**Description:**
a-image fails totally with the very same code as in the documentation. runs smooth with 020, but sucks completely with later versions as well as the master version. no image is visible, but is there in inspector.

- A-Frame Version: master
- Platform / Device: mozilla nightly-windows
- Reproducible Code Snippet or URL:

**Comment by ngokevin** [comment]
Can you add code or ask on Stackoverflow? Which example? Most likely you need to position it in front of the camera position="0 0 -4" or use side="double"

**Comment by jpnayak** [comment]
yeah. I just did that it worked.
