### ISSUE TITLE
Add proper CHANGELOG

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#296]
I like https://github.com/mattdesl/budo/blob/master/CHANGELOG.md and https://github.com/olivernn/lunr.js/blob/master/CHANGELOG.mdown

**Comment by mattdesl** [comment]
For large and long term projects it might be worth investing in some commit/release/changelog automation at some point:
https://github.com/semantic-release/semantic-release
https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md
http://commitizen.github.io/cz-cli/

(budo changelog drags behind regularly)

**Comment by cvan** [comment]
I looked into https://github.com/semantic-release/semantic-release; I think I'm going to go with that. writing manual npm `script`s is becoming a pain. thanks for sharing the other links. commitizen looks quite nice too.

**Comment by mattdesl** [comment]
The nice thing about npm scripts is they are easy to automate. For budo/browserify I've been using this:
https://github.com/mattdesl/quick-stub/blob/master/README.md

Also see `standardize` (I'd accept a PR for semistanfard) and @yoshuawuyts `initialize-engine`:  
https://www.npmjs.com/package/initialize-engine

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/817
