### ISSUE TITLE
Bug noticed in 0.6.0 while completing "Building a 360° Image Gallery" guide.

### ISSUE THREAD

**Issue by rttomlinson** [aframevr/aframe#2961]
**Description:**
I noticed a bug while going through the "Building a 360° Image Gallery" guide.
As of 0.6.0, if you mousedown outside of a box, drag over the box, drag outside of the box, and then mouseup outside of the box. The box will respond as expected per the "event_set" components. That is, scale up to "1.2 1.2 1" on mousenter and scale back down to "1 1 1" mouseleave. However, if the mousedown event occurs while already hovered over the box, the box will scale down to "1 1 1" as expected, but when the cursor is dragged outside the box and mouseup occurs, the box will scale back up to "1.2 1.2 1". We expect the box to stay at "1 1 1". This does not appear to be an issue in v. 0.5.0.

My next step is to see if the issue is related to the event_set component and 0.6.0 or with 0.6.0 itself.

- A-Frame Version: 0.6.0
- Platform / Device: Glitch, but only Cloud9(Linux)
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/married-glade
Upgrading from <0.6.0 to 0.6.0

**Comment by ngokevin** [comment]
updted / fixed
