### ISSUE TITLE
oculus-touch-controls seems to be off real controller by 45 degrees

### ISSUE THREAD

**Issue by snickell** [aframevr/aframe#2965]
I have a basic a-frame scene with oculus-touch-controls (same thing with laser-controls too). Its off the real angle of my controller by almost exactly 45 degrees. I'm not applying rotation to the controller or any of the parent entities, I've stripped my a-frame to just controller entitties and still have this issue.

![oculus-error](https://user-images.githubusercontent.com/223277/29228993-ee3610a0-7e90-11e7-8125-7eb33f22e765.png)

The blue 'cone' is showing the correct level "straight ahead" vector. Both the oculus controls and the laser ray are tipped 45 degrees relative to reality.

**Comment by snickell** [comment]
This is with A-Frame 0.6.1

**Comment by machenmusik** [comment]
My understanding - the pose data returned and leveraged for controllers is in line with the handle -- this is true across vive, touch, gearvr, and daydream to my understanding. 

The Touch controllers are currently unique in their pistol-style positioning of ideal selection beam for things like `laser-controls`... one could argue that for this use case, components like `laser-controls` would be the right place to apply this.  @dmarcos @ngokevin thoughts?

**Comment by ngokevin** [comment]
Yeah, intentional given the style of controller.

If you want to override it, you can use the origin/direction properties of the raycaster. https://aframe.io/docs/0.6.0/components/raycaster.html#properties_direction

You can pretty much copy/paste the laser-controls and modify those config values: https://github.com/aframevr/aframe/tree/v0.6.0/src/components/laser-controls.js

Or wait for `controllerconnected` for an Oculus Touch and set the origin/direction yourself once a Touch controller detected

**Comment by snickell** [comment]
IMO, this should be re-opened because: the model of the controller doesn't match the physical position of the controller. In this image I am holding the top surface of the controller level with the "correct" cone. But the model represents the controller as if this surface was tipped down by 45 degrees. But its not.

i.e. BOTH the direction of the laser AND the position of the controller are off by 45 degrees. 

I can understand that the direction of pointing could be potential, but the controller-as-displayed should match the orientation of the real controller, and its off by 45 degrees.

**Comment by snickell** [comment]
In other words: the controller model is way off representing the true orientation of the controller (way off by 45 degrees in one axis)

**Comment by dmarcos** [comment]
I will take a look

**Comment by machenmusik** [comment]
Reproduced with current Firefox.  I am pretty sure this has not always been the case.  Can someone also test with Chromium (my rig has Nvidia driver conflict issues there) to confirm whether this is browser specific behavior?

**Comment by machenmusik** [comment]
Current hypothesis - either Oculus or Firefox changed the orientation reported for touch controller to reflect pistol-grip offset, where previously it was being returned as in line with handle (for which the Touch model was previously designed and verified)

**Comment by machenmusik** [comment]
hey, so did anyone figure out who changed what?
looks like it was still working correctly when we were working on laser-controls...
https://github.com/aframevr/aframe/pull/2678#issuecomment-302583370

**Comment by machenmusik** [comment]
Confirmed that this does impact experimental Chromium with Rift 1.17 software at least.

**Comment by machenmusik** [comment]
If we merge #2583 then we may be able to use tracked-controls rotation from oculus-touch-controls to fix it
https://github.com/chenzlabs/aframe/blob/4e3fb0a938432bd10b91f7d9df5effdbf588ba86/src/components/tracked-controls.js#L28

**Comment by machenmusik** [comment]
Sounds like @dmarcos prefer an alternative he is working on to #2583, so what is the preferred avenue to solve this issue then?  Commit a new rotated version of model to assets and remove the adjustment in laser-controls?

**Comment by machenmusik** [comment]
@dmarcos ^^ ?

**Comment by snickell** [comment]
This is still an issue in 0.7.... its pretty disconcerting to have the controller in VR not match your actual hand position by 45 degrees.

**Comment by snickell** [comment]
Here's a workaround (and also contains the settings for a proper fix):
`    function fixOculusTouchPose() {
      AFRAME.components['laser-controls'].Component.prototype.config['oculus-touch-controls'].raycaster.direction.y = 0;

      document.addEventListener("DOMContentLoaded", function () {
        document.querySelector("a-scene")
          .addEventListener("loaded", function fixModelPoses() {
            Array.from(document.querySelectorAll('[oculus-touch-controls]'))
              .filter(el => el.components['oculus-touch-controls'].controllerPresent)
              .forEach(el => {
                el.addEventListener('model-loaded', () => {
                  console.warn("HACK ALERT: tweaking model pose for oculus touch see https://github.com/aframevr/aframe/issues/2965");              
                  var mesh = el.getObject3D('mesh');
                  mesh.rotateX(Math.PI / 4);
                  mesh.translateY(0.06);
                  window.lastEl = el;
                });
              });
        });
      });
    }`

**Comment by machenmusik** [comment]
I found that I had to do a slightly different workaround
https://glitch.com/edit/#!/gainful-pirate?path=oculus-touch-controls-hack.js:1:0

**Comment by Kif11** [comment]
I'm experiencing the same issue with a-frame 1.0.4.

**Comment by checksummaster** [comment]
In 1.0.4 oculus-touch-controls seem OK but hand-controls and laser-controls are 45deg off.

**Comment by checksummaster** [comment]
Using HTTP vs HTTPS gives a different result. I know that it should be https but the browser just give a warning and let us proceed but with wrong angles. It like we have config of webXR but some functionality of webVR.

**Comment by inoue0124** [comment]
@Kif11 @checksummaster 
In https://github.com/aframevr/aframe/blob/4a0ec71a60c6c34aac620f8d082137f373b12e20/src/components/oculus-touch-controls.js, changing
`rayOrigin: {origin: {x: -0.01, y: 0, z: -0.02}, direction: {x: 0, y: -0.5, z: -1}},`
into
`rayOrigin: {origin: {x: -0.01, y: 0, z: -0.02}, direction: {x: 0, y: 0, z: -1}},`
has solved the issue in my environment.
