### ISSUE TITLE
vr2vr traversal fails with Oculus Browser

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#2967]
A-Frame VR-to-VR link traversals fail at present with Oculus Browser.

See Slack discussion at https://aframevr.slack.com/archives/C0GG937RN/p1502489851298903

See #2966 for a workaround PR.

**Comment by vincentfretin** [comment]
Testing with https://wmurphyrd.github.io/aframe-super-hands-component/examples/portals.html
so with aframe 0.7.1 and latest oculus browser, it now loads correctly the scene when traversing a portal. It was not the case in september, it did quit the vr mode and there was some sort of infinite loop.
But after traversing two portals, it starts dropping frames, and eventually freeze...

**Comment by vincentfretin** [comment]
Well today it froze after 4 portals. Probably a memory issue? Is the previous scene freed when we enter a portal?

**Comment by dmarcos** [comment]
Freeing resources of the previous page on navigation should be task of the browser. Not sure what A-Frame can do.

**Comment by machenmusik** [comment]
depends whether a-frame is caching things that can be freed e.g. image pano textures

this magic incantation used to force that texture cache to be flushed 
`AFRAME.scenes[0].systems.material.clearTextureCache()`
but that may not be what you want

**Comment by vincentfretin** [comment]
I don't know if I can analyze the memory of oculus browser with the remote chrome debugger on my machine. I didn't try it yet, I don't have much experience with this memory recording stuff on chrome.
I know how to use the allocations recording on firefox though, so I can already try with firefox on my machine to see if the memory is increasing when traversing portals.

**Comment by vincentfretin** [comment]
@dmarcos you're right, the link component just do a `window.location = href` in the end.

I did some benchmarks with chrome profiling tool. I'm not seeing a real memory issue, only the usual increase and decrease of memory from the GC of camera position/rotation created objects and arrays (see #3183)
By looking at profiles and the code, I did find an optimization to do in the link component #3224 though.

I guess you can close the issue, the vr2vr traversal works great in itself. The freeze or crash of the Oculus browser is an issue of this browser.

**Comment by dmarcos** [comment]
@vincentfretin thanks for investigating. it is really helpful 🙏
