### ISSUE TITLE
Animate color + repeat => #NaNNaNNaN

### ISSUE THREAD

**Issue by etiennepinchon** [aframevr/aframe#2977]
Adding a animation on the color property and adding the repeat attribute cause the color to be set to #NaNNaNNaN on the next repetition.
The entity becomes white.. :/

- A-Frame Version: 0.6.0
- Platform / Device: MacOS - Chrome 60
- Reproducible Code Snippet or URL:

```html
<a-box transparent="true" color="#007AFF">
  <a-animation attribute="color" to="#000" dur="2000" repeat="Infinity" easing="ease-in-out-bounce">
  </a-animation>
</a-box>
```
Cheers!
Etienne

**Comment by bryik** [comment]
I don't think `Infinity` is a valid value of the repeat attribute. Perhaps you meant `indefinite`?

```html
<a-box transparent="true" color="#007AFF">
  <a-animation attribute="color" to="#000" dur="2000" repeat="indefinite" easing="ease-in-out-bounce">
  </a-animation>
</a-box>
```

**Comment by etiennepinchon** [comment]
@bryik same with any integers ;)

**Comment by bryik** [comment]
Try adding a `from` attribute:

```html
<a-box position="0 0 -5" transparent="true" color="#007AFF">
  <a-animation attribute="color" from="#007AFF" to="#000" dur="2000" repeat="indefinite" direction="alternate" easing="ease-in-out-bounce">
  </a-animation>
</a-box>
```

**Comment by etiennepinchon** [comment]
Awesome it works haha! Thank you! Although it would be great if this was done by default :)

**Comment by ngokevin** [comment]
Nice. Also try https://github.com/ngokevin/kframe/tree/master/components/animation if you have issues with the current animation, I will later propose to swap it out with this.
