### ISSUE TITLE
Raycaster line not truncating correctly on OBJs for 'raycaster' component

### ISSUE THREAD

**Issue by evhan55** [aframevr/aframe#2980]
**Description:**

- A-Frame Version: 0.6.1
- Platform / Device: Chrome / Google Pixel
- Reproducible Code Snippet or URL: https://slime-cereal.glitch.me

**Steps To Reproduce**

- Load URL on a Google Pixel device in Chrome
- Put on Daydream View Headset
- Calibrate Daydream controller...
- Point laser at orange/black striped model
- Expected: raycaster truncates at model
- Observed: raycaster shoots right through model, and also through two other OBJs I also tested

**Note**
- Raycaster line seemingly truncates correctly when using the `laser-controls` component but not the `raycaster` component

![screenshot_20170816-144602](https://user-images.githubusercontent.com/699840/29380029-5cbe618a-8292-11e7-971d-509f6ae38aae.png)

**Comment by evhan55** [comment]
Possibly related to this older issue: https://github.com/ngokevin/aframe-core/issues/797

**Comment by donmccurdy** [comment]
Thanks for the test example!

Found the problem: We typically think of the `raycaster.refreshObjects()` as needing to be called after the DOM changes, but actually `raycaster.objects` is caching the list of `Object3D`s associated with each entity, not the entity itself. So its cache needs to be cleared not just when the DOM changes, but when a model is added to an entity.

In this case, the [stub mesh created by the `material` component](https://github.com/aframevr/aframe/blob/master/src/components/material.js#L155) is what got cached. If I manually call `el.components.raycaster.refreshObjects()` after the model loads, everything works. That stub mesh has bitten me before (https://github.com/aframevr/aframe/issues/2464) — I wonder if we could do without it?

I'd like to find a more intuitive way to keep the raycaster up to date, but I'm not sure how to handle this case. Here's the [relevant snippet of code](https://github.com/aframevr/aframe/blob/master/src/components/raycaster.js#L122-L141). We could listen for `object3dset` on the scene, with a debounce?

**Comment by machenmusik** [comment]
Another approach, can raycaster attach listener for model loaded event to entities of interest?

**Comment by ngokevin** [comment]
We could have raycaster listen for `object3dset` on a opt-in flag?

Or provide harder documentation and Glitch examples how to manually refresh the raycaster as you need in docs. That'd be the most performant approach. Perhaps a component `raycaster-refresh="raycasterEl: [raycaster]"`.

**Comment by machenmusik** [comment]
I like the refresh component approach, fits the paradigm

On August 20, 2017 10:06:36 AM EDT, Kevin Ngo <notifications@github.com> wrote:
>We could have raycaster listen for `object3dset` on a opt-in flag?
>
>Or provide harder documentation and Glitch examples how to manually
>refresh the raycaster as you need in docs. That'd be the most
>performant approach. Perhaps a component
>`raycaster-refresh="raycasterEl: [raycaster]"`.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/aframevr/aframe/issues/2980#issuecomment-323587112

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by psthmn-cnd** [comment]
@machenmusik Yes, it can, I had the same problem, solved it this way:
```
  var raycaster = document.querySelector("#someCamera").components.raycaster;
  var someObj = document.querySelector("#someObj");
  someObj.addEventListener("model-loaded", () => {
    raycaster.refreshObjects();
  });
```

**Comment by donmccurdy** [comment]
I think we should switch back to caching the list of elements, rather than the Object3Ds they contain. Then at least we're back in a position when it's only DOM changes we need to worry about, rather than changes to the underlying three.js scene graph e.g. `object3dset`. The cost of iterating the list of children on each raycast seems low; THREE.Raycaster is going to be doing that anyway.

An automatic way to refresh the raycaster would be good too, but becomes easier if we only have to worry about DOM events. I think it could even be opt-out rather than opt-in at that point, since you only need to check new elements to see if they match `raycaster.objects`.

**Comment by donmccurdy** [comment]
Proposed fix: https://github.com/aframevr/aframe/pull/3070

I opted into more aggressive refreshing by default, but limited the refreshes to once per raycast.

**Comment by machenmusik** [comment]
Is it feasible to provide #3070 in the form of a component, that could become raycaster dependency or system post 0.7.0, or does it require surgery to existing raycaster and thus core PR?

**Comment by donmccurdy** [comment]
My preference would be to patch the raycaster. The current behavior is catching users by surprise, and I think we can make the default raycaster more friendly without materially affecting performance.

But if we decide that isn't the direction we want, and that the raycaster shouldn't watch the kinds of DOM changes it watches in #3070, then yes I'll make a separate component to do the refresh.

**Comment by machenmusik** [comment]
My only thought was that it might be good to refactor so the refresh policy was separable from the actual raycasting, so the default could be aggressive #3070 but other use cases could replace or entirely disable (e.g. for static scenes)

**Comment by donmccurdy** [comment]
Ok yeah. An option to turn off automatic refreshing and (manually) manage it elsewhere would be worth adding to that PR.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/3070
