### ISSUE TITLE
Fails to load a gltf 2.0 model

### ISSUE THREAD

**Issue by okdzhimiev** [aframevr/aframe#2982]
**Description:**

The model was converted from .obj to .gltf using [Khronos Blender glTF 2.0 exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter). See the [source files](https://community.elphel.com/files/gltf_test/).

- Firefox:
_TypeError: r.buffers[e.buffer] is undefined[Learn More]_
- Chrome:
 _Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined
    at GLTFLoader.js:977
    at i (GLTFLoader.js:570)
    at GLTFLoader.js:975
    at \<anonymous\>_

- A-Frame Version: 0.6.1
- Platform / Device: Kubuntu 16.04, Chrome and Firefox
- Reproducible Code Snippet or URL:
https://community.elphel.com/files/gltf_test/aframe.html

**Comment by dmarcos** [comment]
A-Frame 0.6.1 does not support glTF 2.0. It's a 0.7.0 feature.

**Comment by donmccurdy** [comment]
In the meantime, you can use the `gltf-model-next` component from A-Frame extras: https://github.com/donmccurdy/aframe-extras/tree/master/src/loaders
