### ISSUE TITLE
empty <a-animation> changes rotation to 'NaN 0 0'

### ISSUE THREAD

**Issue by gftruj** [aframevr/aframe#2988]
While playing around with this question on [SO](https://stackoverflow.com/questions/45805894/d3-js-makes-entity-disappear-while-using-animation-function-of-a-frame/45806052#45806052), I got into a weird bug, which I don't see reported anywhere.

When an empty` <a-animation>` is appended to a entity, its parent dissapears, because its rotation is changed to 'NaN 0 0'.

Normally i don't see a reason why anyone would append an empty `<a-animation>`, but in that case, it seems the empty entity is created on d3's `append("a-animation");` and I couldn't fix it by changing the rotation attribute, like i tried [here](https://jsfiddle.net/gftruj/soetzojt/2/).

A clean reproducible Code Snippet is [here](https://jsfiddle.net/gftruj/oss28zhs/).

- A-Frame Version: 0.6.1

**Comment by ngokevin** [comment]
Try using the animation component https://github.com/ngokevin/kframe/tree/master/components/animation which solves these problems by not having to do a createElement/setAttribute/appendChild just to add an animation
