### ISSUE TITLE
Loading gltf error，This gltf comes from threejs

### ISSUE THREAD

**Issue by ZTFtrue** [aframevr/aframe#2989]
**Description:**
Loading gltf error(the gltf have animation):
```
Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined
    at GLTFLoader.js:979
    at _each (GLTFLoader.js:570)
    at GLTFLoader.js:975
    at <anonymous>
```
- A-Frame Version:0.6.0
- Platform / Device: MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports) Chrome 60.0.3112.101(64)
- Reproducible Code Snippet or URL:
```
   <a-scene>
        <a-entity position="0 0 4">
            <a-camera></a-camera>
        </a-entity>
        <a-assets>
            <a-asset-item id="tree" src="./monster.gltf"></a-asset-item>
        </a-assets>
    </a-scene>

```
this is monster.gltf(https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/Monster)

**Comment by donmccurdy** [comment]
Hi @ZTFtrue — the examples in the three.js repo are using glTF 2.0. A-Frame's `gltf-model` component currently supports only glTF 1.0. The next version of A-Frame will have glTF2.0, or you can use the [gltf-model-next component from aframe-extras](https://github.com/donmccurdy/aframe-extras/tree/master/src/loaders) in the meantime.
