### ISSUE TITLE
Aliasing on high-resolution sky texture

### ISSUE THREAD

**Issue by markqvist** [aframevr/aframe#2990]
**Description:**

- A-Frame Version: 0.6.1
- Platform / Device: Chrome / Samsung Galaxy S8
- Reproducible Code Snippet or URL: 

I have created a scene with a 8192x4096 sky texture, which renders perfectly on desktops, and also in browser on a Galaxy S8, but when VR view is entered, the sky texture is extremely aliased, as if the filtering is dropped down to a "nearest" filter. If inspecting the actual texture object in the scene, the filtering is on the texture is specified as a THREE.LinearFilter.

The texture has been broken down into two 4096x4096 half-domes, since 4096x4096 is the maximum texture size the mobile GPU supports.

Any idea what could be causing this?

**Comment by markqvist** [comment]
It might be interesting to note, that if the scene is rendered with polyfill in firefox on the device, the texture is filtered correctly, and the aliasing is completely gone.

**Comment by machenmusik** [comment]
Question, when you say Chrome on S8 and VR, are you using Daydream?  Or did you mean one of Samsung Internet or Oculus Browser?

**Comment by markqvist** [comment]
Using daydream in Chrome. Also the same thing occurs in Chrome beta. Haven't tried it with Oculus/Samsung Internet/Gear VR, but I can give it a try as well.

**Comment by markqvist** [comment]
Here's an example where the issue occurs: https://superhelix.dk/vr/test1/

**Comment by markqvist** [comment]
Furthermore, if VR view is exited, by pressing the app button, the texture then also becomes very aliased in the normal view.

**Comment by markqvist** [comment]
I have tested the scene on a Vive headset through Firefox, and the aliasing does not occur here, so it is something specific to Chrome.

**Comment by markqvist** [comment]
Ok, I don't think this is fixable by a-frame as such. The problem occurs because Chrome's Daydream renderer apparently subsamples the rendering quite a bit. If I manually resize the rendering canvas, the aliasing disappears, but performance takes a hit.

I guess this should be closed, sorry for the noise ;)

If I am wrong, and this is actually caused by the way that a-frame initialises the rendering system, I'd be interested to hear about it.

**Comment by MichaelHazani** [comment]
@markqvist I don't have specific info but have anecdotally heard that AA is forcibly prevented on several mobile platforms. Not sure that you've encountered a bug rather than a "feature" (or, compromise...)
