### ISSUE TITLE
Show a screen when in VR but holding the phone in portrait mode

### ISSUE THREAD

**Issue by floostmodern** [aframevr/aframe#2992]
**Description:**

- A-Frame Version: 0.5.0
- Platform / Device: Any device where that has no dedicated display for VR
- Reproducible Code Snippet or URL: -

I am trying to get a message to show when a user has its mobile phone in VR mode but holds it inin portrait position.
I see that there is some code in `aframe/src/components/scene/vr-mode-ui.js:136` to do this.
Unfortunately, it is never triggered, because when entering VR the scene locks the phone in landscape mode (`aframe/src/core/scene/a-scene.js:246`)

Are there any plans to make this feature available again by not locking the orientation of the phone ? I believe it would be better from a UX perspective.

**Comment by ngokevin** [comment]
This should work:

![img_5523](https://user-images.githubusercontent.com/674727/29677790-180ec5fa-88b1-11e7-9c8f-e76bfe88ee1d.PNG)

Let us know if you have more details.

**Comment by floostmodern** [comment]
I have done further research and I think I understand now, I'll share its results here in case it helps some fellow developers.

The browser on which I want this feature to work is Chrome for Android.
With a vanilla version of the browser, I am able to reproduce the bug as shown here : 

![img_20170825_100036](https://user-images.githubusercontent.com/17003643/29711731-45447320-898e-11e7-9c64-1e5a3a555493.jpg)

But there is a caveat. When the WebVR flag (in `chrome://flags`) is enabled, the WebVR viewer changes : 
- When the flag is turned off, a bespoke viewer is used
![screenshot_20170825-123411](https://user-images.githubusercontent.com/17003643/29716271-a1a3a064-89a2-11e7-80ac-661a70715734.png)
- When the flag is turned on, the Cardboard Viewer is used
![screenshot_20170825-142655](https://user-images.githubusercontent.com/17003643/29716297-ba4659b8-89a2-11e7-82a7-beecb4676610.png)

The Cardboard Viewer will end up being the default one, and its behaviour cannot be changed via HTML code. So this feature cannot be implemented on it.
It might be interesting to implement it on the "bespoke" viewer, though.

**Comment by floostmodern** [comment]
@ngokevin any thoughts on the above ?
