### ISSUE TITLE
Appending a-abox in a-scene fails in Chrome

### ISSUE THREAD

**Issue by jgbarah** [aframevr/aframe#3001]
**Description:**

The code below works well in Firefox 55.0 (shows a white box on a blue sky), but fails in Chrome (I've tested in "60.0.3112.113 (Official Build) (64-bit)" (for Debian) and some earlier versions). In Firefox, I don't see anything remarkable in the console, but in Chrome I see the errors below.

The problem seems to be in:

```
browser.js:111 core:a-node:warn You are attempting to attach <A-BOX> outside of an A-Frame scene. 
Append this element to `<a-scene>` instead. 
```

which is weird, since I'm only getting the a-scene, building a minimal a-box, and then attaching the a-box to the a-scene...

Errors in Chrome console:

```
A-Frame Version: 0.6.1 (Date 19-07-2017, Commit #a4b91bc)
index.js:87 three Version: ^0.84.0
index.js:88 WebVR Polyfill Version: ^0.9.36
browser.js:111 core:a-node:warn You are attempting to attach <A-BOX> outside of an A-Frame scene. Append this element to `<a-scene>` instead. 
browser.js:111 core:a-node:warn You are attempting to attach <A-BOX> outside of an A-Frame scene. Append this element to `<a-scene>` instead. 
material.js:151 Uncaught (in promise) TypeError: Cannot read property 'registerMaterial' of undefined
    at i.setMaterial (material.js:151)
    at i.updateShader (material.js:101)
    at i.update (material.js:47)
    at i.updateProperties (component.js:271)
    at i.module.exports.Component (component.js:52)
    at new i (component.js:458)
    at HTMLElement.value (a-entity.js:377)
    at HTMLElement.value (a-entity.js:544)
    at e (a-entity.js:513)
    at Array.forEach (<anonymous>)
...
value @ a-entity.js:495
(anonymous) @ a-entity.js:306
(anonymous) @ a-node.js:117
Promise resolved (async)
value @ a-node.js:115
value @ a-entity.js:302
value @ a-entity.js:84
value @ a-register-element.js:150
value @ a-register-element.js:150
(anonymous) @ (index):11
three.js:19802 THREE.WebGLRenderer 84
```

- A-Frame Version: 0.6.1
- Platform / Device: "60.0.3112.113 (Official Build) (64-bit)" (for Debian) 
- Reproducible Code Snippet or URL:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <script src="https://aframe.io/releases/0.6.1/aframe.min.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
      var scene = document.querySelector('a-scene');
      var frame = document.createElement('a-box');
      frame.setAttribute('position', {x: 1, y: 2, z: -3});
      scene.appendChild(frame);
    });
    </script>
  </head>
  <body>
   <a-scene>
      <a-sky color="blue"></a-sky>
      <a-camera>
      </a-camera>
    </a-scene>
  </body>
</html>
```

**Comment by dmarcos** [comment]
You have to wait for the scene to load:
````javascript
document.querySelector('a-scene').addEventListener('loaded', function() { // your stuff goes here });
````

**Comment by ngokevin** [comment]
https://aframe.io/docs/0.6.0/introduction/javascript-events-dom-apis.html


https://aframe.io/aframe-school/#/9/3

**Comment by jgbarah** [comment]
Thanks a lot, and sorry for the noise. That makes a lot of sense.

However, I went carefully through most of the [Introduction](https://aframe.io/docs/0.6.0/introduction), including the [section on JavaScript](https://aframe.io/docs/0.6.0/introduction/javascript-events-dom-apis.html), and didn´t notice about that. Maybe it would be convenient to mention that early in that tutorial, since it can be very confusing when you're starting with A-frame. 

In fact, there is some code in the  [section on JavaScript](https://aframe.io/docs/0.6.0/introduction/javascript-events-dom-apis.html) that suggests that there is no need of waiting until the scene is loaded:

```javascript
var sceneEl = document.querySelector('a-scene');
var entityEl = document.createElement('a-entity');
// Do `.setAttribute()`s to initialize the entity.
sceneEl.appendChild(entityEl);
```

The text there comments about the importance of waiting until an entity is loaded for changing its settings, but says nothing about `a-scene`, which in the above code is assumed to be loaded.

In fact, the same happens with the code right below that one, where once again an entity is attached to `a-frame` without waiting for `a-frame` to be loaded.

I'm opening a pull request to that section stating all this: #3002.
