### ISSUE TITLE
Make all images used in examples be of power of two

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#301]
All images we use in the examples should be of power of two (for pef reasons):

![](https://pbs.twimg.com/media/CWc179zUkAAaCUC.png:large)

/cc @jcarpenter

**Comment by cvan** [comment]
dupe of #300

**Comment by alwell-kevin** [comment]
Is it still necessary today to convert images to power of two? @ngokevin

**Comment by dmarcos** [comment]
@alwell-kevin Is not a necessity but it will yield better performance
