### ISSUE TITLE
only use vrdisplay's requestAnimationFrame when presenting to reduce latency

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3020]
**Description:**

A-Frame is experiencing bad performance on desktop Firefox / Vive.

https://bugzilla.mozilla.org/show_bug.cgi?id=1394561

`- Make sure you are disabling the normal 2d display's requestAnimationFrame callback when the VR presentation has started`

Tip from @kearwood to disable the window's requestAnimationFrame in VR mode. There is some flux with three.js's removal of VREffect, but it would still be up to A-Frame to handle this switching as it has its own RAF.

**Comment by kearwood** [comment]
With OpenVR, you should see the VRDisplay's RAF callback occur about 4ms before the next vsync.  the frame submitted in this RAF callback will be presented in the vsync following, so you have more than 4ms to render it.  This timing optimizes for both lowest latency and tries to interleave the GPU utilization between the WebGL rendering and the VR reprojection / compositing.

It is not just the matter of getting sufficient refresh rate, but that the sub-frame timing is optimal.  I would suggest that the 2d mirrored display be rendered synchronously with the VRDisplay's frame, and let the browser handle the frame drops in the mirrored display to match up the framerate.

If physics, culling, and other CPU bound operations are not in a WebWorker, these things would be most optimally performed immediately after the submitFrame call in the VRDisplay RAF callback, preparing the next frame.  Ideally, the engine should be ready to perform the GPU heavy operations in response to the VRDisplay RAF callback, and only make minor adjustments to culling as needed to adjust for the updated headset pose at the start of the RAF.

**Comment by dmarcos** [comment]
I don't think we're using `window.requestAnimationFrame` in VR mode. We use the VREffect `requestAnimationFrame` (https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L643) that drives the component ticks as well. VREffect switches to `window.requestAnimationFrame` or `vrDisplay.requestAnimationFrame` depending if we're in VR mode or not: https://github.com/aframevr/aframe/blob/master/vendor/VREffect.js#L184

**Comment by ngokevin** [comment]
Yes, sorry, this does not seem to be the culprit. We will need to investigate more to see why A-Frame is suffering latency when the WebVR samples are OK.
