### ISSUE TITLE
Establishing more independent governance for A-Frame

### ISSUE THREAD

**Issue by larsbergstrom** [aframevr/aframe#3022]
As I mentioned in PR #3010 Mozilla’s high-level goal is to continue its official support, leadership, and involvement, as it has since A-Frame’s creation by our staff. We’d be open to making the following contributions explicit:

- Continued role as A-Frame mark holder and defender
- Administration and security of all of the A-Frame sites and services
- Supporting the employment of at least one full time staff member in a peer/maintainer role on A-Frame

There are several ways to formalize this support that we would be open to and willing to have our Legal team help draft. One example to start the discussion would be the Thunderbird model, which is now an independent project but has an explicit commitment from Mozilla to continue a particular level of staffing, funding, and involvement:
https://wiki.mozilla.org/Modules/Thunderbird
https://wiki.mozilla.org/Thunderbird/New_Release_and_Governance_Model

Additionally, it is Mozilla's goal to ensure others can continue to meaningfully contribute and help lead A-Frame's continued development, which has always been a part of what makes Mozilla projects successful.

Since the question has come up in the past, a completely hands-off approach like the one Mozilla used in the most recent governance model for the Rust project doesn't fit as well for A-Frame. That project required a higher level of independence in order to assure potential contributors and users that the Rust language would not transition from a systems programming language into a browser-specific programming language. Mozilla does not expect that model would be used with any projects in the future, excluding those in which we no longer expect to invest.

**Comment by ngokevin** [comment]
Cool, sounds good to emphasize Mozilla's support in the governance as long as contributors can continue to drive the project and community. Over its years of effort, A-Frame has thrived best organically, in a community-driven, hands-off, and transparent approach. I hope that continues to remain the case. It does feel awkward to have a community-oriented project's governance drafted by a legal team, and I don't wish to change the way A-Frame currently runs to match a different project like Thunderbird (which has a different scope and structure). But if necessary, Mozilla's legal team can draft a proposal that aligns with both Mozilla's interests as well as the broader community's. Thanks!

**Comment by ngokevin** [comment]
Hello, is there any update to this?

**Comment by larsbergstrom** [comment]
Sorry for the delay! I was out last week but am continuing to push this forward internally. As a quick update, I'm working with the folks who are looking to formalize Mozilla's involvement in projects that look like this - including Servo and several others. If there's a rapid timeline you'd like to close this down in, I can work to get something for A-Frame in place more quickly, but I believe that half of the A-Frame core team is on PTO and off the grid the next two weeks anyway :-)

Is there something you needed addressed sooner? Happy to work with your timelines if there's some deadline you're trying to meet, but I'm also sensitive not to rush this kind of work and leave time for some back-and-forth.

**Comment by ngokevin** [comment]
No problem, I was just looking for any form of update or response.

**Comment by ngokevin** [comment]
We should expedite this soon, past a month becomes worrisome to hold on important issues.

**Comment by larsbergstrom** [comment]
Yup, I'll get Diego working with our internal folks on Open Innovation who are working in the governance space in the next week or two. Thanks!

**Comment by mkungla** [comment]
@larsbergstrom what was the outcome?
