### ISSUE TITLE
MutationObserver does not work with components

### ISSUE THREAD

**Issue by delapuente** [aframevr/aframe#3028]
`MutationObserver` callback is not triggered when changing an attribute:
https://codepen.io/lodr/pen/LjoGwN

**Comment by donmccurdy** [comment]
There are some details in the documentation for the [`debug` component](https://aframe.io/docs/0.6.0/components/debug.html). In short, the DOM is not actually modified when calling `setAttribute`. MutationObserver can be relied upon to tell you when a component is added/removed, but not when its has changed unless the `debug` component is in use (which isn't recommended it production, for performance reasons).

**Comment by dmarcos** [comment]
@delapuente can you confirm that `MutationObservers` is working if you use the debug component?

**Comment by ngokevin** [comment]
Thanks for filing, there are events to help you detect when's component is changed initialized or removed https://aframe.io/docs/0.6.0/core/entity.html#events_componentchanged

**Comment by delapuente** [comment]
But they are throttled and the issue breaks a property of HTML elements (_to be observables with a MutationObserver_). I don't think this should be closed.

**Comment by ngokevin** [comment]
You can poll if you need more frequent updates. A-Frame does not aim to follow the 2D Web exactly. It's not worth the performance hits to enable mutation observers.

**Comment by delapuente** [comment]
Then I think it is worth to mention somewhere in the documentation because this is an unexpected behaviour if A-Frame is claiming it is tool agnostic for being built on the top of HTML.

**Comment by ngokevin** [comment]
https://aframe.io/docs/0.6.0/introduction/faq.html#why-is-the-html-not-updating-when-i-check-the-browser-inspector

https://aframe.io/docs/0.6.0/components/debug.html

**Comment by dmarcos** [comment]
It's commom in game development to favor polling over event driven programming. It makes things more explicit and gives control to the developer on when to obtain the most up to date information when needed. In A-Frame we want to make things easy in a way the encourages good practices that lead to good performance.

**Comment by delapuente** [comment]
I'm not saying that polling is not the way to go. I'm saying that if A-Frame claims to be built to be tool agnostic and to reuse the knowledge that web programmers already have, breaking HTML invariants or inherent properties is unexpected and should be warned. Anyway, I'll send a PR for clarifying the `MutationObserver` case in the FAQ.

**Comment by donmccurdy** [comment]
@delapuente could I suggest putting this note about MutationObserver in the *JavaScript, Events, and DOM APIs* documentation instead of the FAQ? I agree it is unexpected behavior to web developers, but it is not very frequently asked about. Thanks!
