### ISSUE TITLE
AFrame camera movement like React VR

### ISSUE THREAD

**Issue by darioodiaz** [aframevr/aframe#3033]
**Description:**

Hi! recently I was playing with react-vr and I saw that the camera moves as my phone rotates or as I rotate myself, my phone doesnt has gyroscope, I saw some Aframe examples and if I rotate myself the camera doestn move, I test the same example with a phone with gyroscope and it does, Will be Aframe has the same feature that react-vr? It based on device motion events or something else?

- A-Frame Version: all
- Platform / Device: All
- Reproducible Code Snippet or URL: Any sample React VR app

**Comment by dmarcos** [comment]
A-Frame already uses the device motion APIs as a fallback to rotate the camera on mobile phones. What browser and phone are you using? https://aframe.io/aframe/examples/ work on all my iOS and Android devices.

**Comment by darioodiaz** [comment]
I test both react-vr example and aframe examples on Chrome for Android in Android 4.4.2 on LG g3

**Comment by darioodiaz** [comment]
I rotate on myself and aframe dont rotate the camera, but in react-vr it does

**Comment by darioodiaz** [comment]
@dmarcos I look quickly on aframe source code and I see that it's using VR Controls to rotate the camera, I test a ThreeJS VR Controls example and if I rotate on my self the camera doesn't move but I use this example [https://threejs.org/examples/misc_controls_deviceorientation.html](url) and if I rotate on myself the camera also moves, so, if the device is mobile phone or some device with no gyroscope, it will be wrong use deviceorientation (like the example above) instead VR Controls?

**Comment by ngokevin** [comment]
I think I'm okay not supporting magic window on devices with no gyro. But perhaps a PR can be sent to https://github.com/immersive-web/webxr-polyfill
