### ISSUE TITLE
glTF 2.0 models not loading

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#3034]
While doing QA for `0.7.0` I realized that the models in the examples are not loading:

![gltf](https://d3vv6lp55qjaqc.cloudfront.net/items/3y0b0A2j1i1P1N1S3q3g/Image%202017-09-09%20at%2012.05.11%20PM.png?X-CloudApp-Visitor-Id=681eb91758819d0066e71ca9eb6d31d7&v=f73bb8e8)

No errors on console I could see. Screenshot above is taken with `/examples/test/model/` as is in the `master` branch

@donmccurdy Any leads on what I should look at?

**Comment by dmarcos** [comment]
The glTF loader is doing some stuff. It's not a network issue:
![gltfloader](https://d3vv6lp55qjaqc.cloudfront.net/items/0m1r1R2K2E2t322u0B0t/Image%202017-09-09%20at%2012.10.47%20PM.png?X-CloudApp-Visitor-Id=681eb91758819d0066e71ca9eb6d31d7&v=3ff6239e)

**Comment by donmccurdy** [comment]
Did a clean `git clone` `npm install && npm run dev` and can't reproduce this. Maybe you have a stray `npm link` on some dependency?

**Comment by dmarcos** [comment]
I just run an `npm install` and now it renders. Something weird happened I can't explain 😏 Closing this!
