### ISSUE TITLE
Microsoft Edge does not appear to support in-VR link traversal

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#3038]
(Using latest master.)
@dmarcos @leweaver @olga-microsoft can you confirm?

**Comment by NellWaliczek** [comment]
That's correct.  At this time, we still have concerns about the security implications of open-ended link traversal while within VR.  We're discussing how to address these concerns with the WebVR CG and are hoping to land on something everyone is comfortable with in the WebVR 2.0 design.
In the meanwhile, Microsoft Edge does not force an exit from VR when history.pushState() is called, so that might be an interesting approach to investigate for now.

**Comment by machenmusik** [comment]
Thanks @NellWaliczek - that rationale makes sense.  Let me know how/whether folks not on the browser call can participate... Will give the alternative strategy a try.

**Comment by machenmusik** [comment]
No luck with the workaround, as history.pushState() will not actually effect transition between two pages on same domain for example; using history.pushState() then history.go(0) appears to both fail to transition to the newly pushed location, and also to destabilize Edge.

**Comment by donmccurdy** [comment]
@machenmusik `history.pushState()` is not a drop-in replacement for page navigation; developers would need to use it alongside JS code for changing the DOM when the URL changes. The browser does not technically request a new page: this is most commonly combined with Single Page Application routers in React/Angular/Vue. In A-Frame, I think I think the History API is a good choice if you're using one of those frameworks already. If not, @ngokevin's state component might be easier to work with.

**Comment by machenmusik** [comment]
@donmccurdy yes, understood that `history.pushState()` is not a drop-in replacement, but really for a single page application there is no need to do it this way at all; there appears to be no workaround at present for anything except single-page applications.

**Comment by donmccurdy** [comment]
> there appears to be no workaround at present for anything except single-page applications.

Right, just meant to clarify that. The only way to stay in VR is to stay within a single page. History API just provides a way to persist state in the URL, for users who want to do that, as it can accomplish some but not all of the goals of traditional page navigation.
