### ISSUE TITLE
Use a third-party library for automating releases

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#304]
https://github.com/semantic-release/semantic-release looks good. I'll be able to remove many of the custom npm `script`s we have.

see https://github.com/aframevr/aframe/issues/296#issuecomment-165665650

**Comment by cvan** [comment]
holy react: https://github.com/facebook/react/wiki/Release-Process

**Comment by cvan** [comment]
Just found this - not sure if it's decent: https://github.com/bumped/bumped

**Comment by ngokevin** [comment]
@a-frobot for continuous releases (via rawgit).

Manually done for major releases
