### ISSUE TITLE
Add support for MediaStream in `sound` component

### ISSUE THREAD

**Issue by delapuente** [aframevr/aframe#3041]
Currently, only buffered audio files are supported by A-Frame but supporting [`MediaStream`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) sources would enable interesting scenarios such as positional WebRTC audio.

**Comment by ngokevin** [comment]
Closing for reasons in https://github.com/aframevr/aframe/pull/3042

This can be done more simply in a separate component. The primary reason was for multiuser, and I'm sure that these changes will not be the only changes needed for that in the future. In the `networked-aframe` issue, some people mentioned there are more things to be done. So faster to do separately. Thanks!
