### ISSUE TITLE
vrdisplayconnect event listener should be registered in a-scene

### ISSUE THREAD

**Issue by olga-microsoft** [aframevr/aframe#3045]
**Description:**
In a-scene there are 2 disconnect listeners registered, I believe one of them is supposed to be 'connect':
// Exit VR on `vrdisplaydisconnect` (e.g. unplugging Rift headset).
window.addEventListener('vrdisplaydisconnect', this.exitVRTrueBound);
// Exit VR on `vrdisplaydisconnect` (e.g. unplugging Rift headset).
window.addEventListener('vrdisplaydisconnect', this.exitVRTrueBound);

- A-Frame Version: master (4e984156f2f160015008e3f72adc09b71ba59d4c)

**Comment by dmarcos** [comment]
Good catch. Just fixed it on https://github.com/aframevr/aframe/commit/47875a0eb6b05f54acbcc1bb2c135be4b75fc33e

**Comment by olga-microsoft** [comment]
Thanks!
Below vrdisplayconnect listener is removed, but never added, remove too:
window.removeEventListener('vrdisplayconnect', this.enterVRBound);
~Olga
