### ISSUE TITLE
don't support nft？

### ISSUE THREAD

**Issue by brotherYoung** [aframevr/aframe#3048]
I have read "create with ar.js and aframe",I just find pattern & barcode marker, don't support nft?

**Comment by brotherYoung** [comment]
it should be create ar with ar.js and aframe,im sorry

**Comment by dmarcos** [comment]
To kick the tires. You can use one of the Google WebAR experimental apps: [WebAROnARCore](https://github.com/google-ar/WebARonARCore) or [WebAROnARKit](https://github.com/google-ar/WebARonARKit) and @chenzlabs AR component https://github.com/chenzlabs/aframe-ar

**Comment by dmarcos** [comment]
I'm closing this because this is not a bug o feature request but a question more suited to StackOverflow
