### ISSUE TITLE
Using 3D models

### ISSUE THREAD

**Issue by rafarq** [aframevr/aframe#305]
Is there any way os using 3D models generated with other software for using in more complex scenes?

**Comment by jcarpenter** [comment]
Yep, check out the model component: https://aframe.io/docs/primitives/a-model.html

It supports OBJ and Collada (DAE) files. With intent to add support for GLTF as soon as the Three.js importer and workflows are a bit more robust.

**Comment by jcarpenter** [comment]
We try to use GitHub for bug reports, feature requests, etc. In the future the best way to ping the team with questions is [@aframevr](http://twitter.com/aframevr) on Twitter, or via the A-Frame [Slack channel](https://aframevr-slack.herokuapp.com/)
