### ISSUE TITLE
Increasing offset when entering VR for non positional devices

### ISSUE THREAD

**Issue by DavidHGillen** [aframevr/aframe#3051]
**Description:** Every time the user enters the app or VR they are moved upwards by userHeight if one is anything other than 0. and if it is 0 then it is the default value of 1.6.

This bug is present on non positional devices like GearVR, chrome and firefox.

- A-Frame Version: 0.6.1+, not present in 0.6.0
- Platform / Device: Android Chrome, Android Firefox55, Gear VR. Not present w/ VIVE. Others not tested.
- Reproducible Code Snippet or URL:
```
<html>
<head>
	<script src="https://rawgit.com/aframevr/aframe/master/dist/aframe-master.js"></script>
</head>
<body>
	<a-scene>
		<a-plane position="0 -1.6 0" rotation="-90 0 0" width="1.8288" height="1.8288" color="#A48080"></a-plane>
		<a-plane position="0 0 0" rotation="-90 0 0" width="1.8288" height="1.8288" color="#A4A4A4"></a-plane>
		<a-plane position="0 1.6 0" rotation="-90 0 0" width="1.8288" height="1.8288" color="#80A480"></a-plane>
		<a-plane position="0 3.2 0" rotation="-90 0 0" width="1.8288" height="1.8288" color="#80C680"></a-plane>
	</a-scene>
</body>
</html>
```
https://youtu.be/awjY0GMPox8

**Comment by ngokevin** [comment]
Not quite understanding the issue. userHeight can't be disabled, not applyingl, incorrectly applying>

**Comment by DavidHGillen** [comment]
Here's a video if that makes it clearer:
https://youtu.be/awjY0GMPox8

**Comment by delapuente** [comment]
Confirmed. It's happening to me too:

![increasinf-offset](https://user-images.githubusercontent.com/757942/30964996-ed1239e0-a453-11e7-9b95-59c9c77bf4e4.gif)

**Comment by vincentfretin** [comment]
I can confirm there is an issue with 0.7.0 with GearVR and Oculus brower. No issue with 0.6.0 and 0.6.1.
In 0.7.0, no issue with `<a-camera user-height="0" />`, there is an issue with `<a-camera user-height="1" />` (or any value > 0), it increases each time by user-height when you enter, exit, enter vr.

**Comment by vincentfretin** [comment]
The regression should be in a commit between 19 july (post 0.6.1 release) and 14 september (date of this issue) I guess.

**Comment by vincentfretin** [comment]
issue with https://rawgit.com/aframevr/aframe/4487c28/dist/aframe-master.min.js 29 Aug
no issue with https://rawgit.com/aframevr/aframe/ba7d108/dist/aframe-master.min.js 25 Aug

**Comment by vincentfretin** [comment]
#3000 introduced the regression.
If I remove this line https://github.com/aframevr/aframe/pull/3000/files#diff-6285039eee70ed830f70f7d2f7b7dfa5R60 in the look-controls component, I don't have the issue anymore.

**Comment by vincentfretin** [comment]
Please reopen. The fix I did only fixed it for a camera set to userHeight 0. See my comment https://github.com/aframevr/aframe/pull/3105#issuecomment-333461108

**Comment by vincentfretin** [comment]
I really fixed the issue in #3111

**Comment by dmarcos** [comment]
This problem should be gone in master now. I will wait for a more through testing / confirmation before closing

**Comment by pandalion** [comment]
I am getting this same issue as of today in aframe 0.7.0. I am using
```
<a-entity camera="userHeight: 1.6" look-controls>
</a-entity>
```

**Comment by donmccurdy** [comment]
@pandalion the fix is in the master branch, if you want to test that, but otherwise you'd need to wait for 0.8.0.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/3327
