### ISSUE TITLE
[Mobile VR Controllers] Click actions on controllers not working

### ISSUE THREAD

**Issue by KrzysztofWrobel** [aframevr/aframe#3056]
**Description:**
I'm currently working on an application, which will support both Daydream and GearVR controllers.
I've noticed that in official source code method addEventListeners() for both Daydream https://github.com/aframevr/aframe/blob/34d1988430c7541f8e28978b31bb6278ca2b7df7/src/components/daydream-controls.js#L66 and GearVR https://github.com/aframevr/aframe/blob/34d1988430c7541f8e28978b31bb6278ca2b7df7/src/components/gearvr-controls.js#L67 is never invoked. As I understand that's the method, which should emit `trackpad` or `trigger` events to the component.

For now, to solve my issue I've ended up writing my own component, which setups those events for daydream and gearvr controllers, but I think it requires an open discussion on how we should map trackpad/trigger events to raycaster/cursor intersection clicks.

- A-Frame Version: 0.6.1
- Platform / Device: Daydream Controller, Gear VR Controller

**Comment by ngokevin** [comment]
They're called by a shared util https://github.com/aframevr/aframe/blob/master/src/utils/tracked-controls.js#L22

The cursors work OK with the mobile controllers. See `laser-controls` for an example
