### ISSUE TITLE
No exit button in VR mode on mobile

### ISSUE THREAD

**Issue by tbalouet** [aframevr/aframe#306]
When entering the VR mode on mobile, putting it back in portrait doesn't change anything, and there are no "exit VR" button, which makes it a bit difficult to exit VR on phones with no physical back button (in my case Motorola X 2nd gen)

**Comment by jcarpenter** [comment]
@caseyyee. Have you encountered this one?

**Comment by caseyyee** [comment]
All Android phones have back buttons.  In some cases, you may have to swipe up from the bottom to expose the soft-keys.    This could be the case with the MotoX?

We could put a Exit VR button as we have with IOS for, though I figure this would be a common UX for similar apps (ie: Gallery).

**Comment by tbalouet** [comment]
Yes, indeed that's the case for the motoX, you have to swipe to get the phone UI back. It wasn't very intuitive for me at first (when I started VR on this phone and being fullscreen all the time), so I figure it might be complicated for some users too, that's why I was suggesting adding a bit of UI, like in the webVR boilerplate, to simplify user experience.

**Comment by caseyyee** [comment]
Yeah OK, I agree, adding a back button will help for this.

**Comment by cemkod** [comment]
Two questions:

- Is the important label still appropriate as there actually is a way to exit VR mode?
- Should we move this issue to aframevr/aframe-core?

**Comment by dmarcos** [comment]
After more than 8 months I haven't heard many complains about this being an issue? Do you this this is something we should tackle? @ngokevin

**Comment by ngokevin** [comment]
Rotating to portrait and pressing the X works for now. That would satisfy case on both fullscreen scenes (where you could also just navigate away), and embedded.
