### ISSUE TITLE
The submenu on one documentation page doesn't seem to get highlighted on click.

### ISSUE THREAD

**Issue by kitsunde** [aframevr/aframe#3064]
**Description:**

If you click links in the bottom menu, they don't get highlighted. The bottom two here:

<img width="364" alt="screenshot 2017-09-18 17 27 27" src="https://user-images.githubusercontent.com/48965/30535998-cd5f102e-9c96-11e7-9a23-916d2016e047.png">

- A-Frame Version: 0.6.0
- Reproducible Code Snippet or URL: https://aframe.io/docs/0.6.0/introduction/javascript-events-dom-apis.html

**Comment by poshaughnessy** [comment]
I see the bottom menu highlight OK in Chrome 60:

<img width="303" alt="screen shot 2017-09-20 at 10 03 08" src="https://user-images.githubusercontent.com/151207/30635720-30ab1c22-9deb-11e7-9e64-cd838f641641.png">

But I've replicated the issue in Firefox 55. The 'Removing an Event Listener...' link does not get highlighted.

**Comment by kitsunde** [comment]
It might be a screen resolution thing. I have chrome 60 on my 15" Macbook. Similarly if I just scroll the page, the last link wont get highlighted cause presumably it doesn't know which link is active on my big screen. :P

<img width="1920" alt="screenshot 2017-09-20 17 21 04" src="https://user-images.githubusercontent.com/48965/30636461-19761998-9e28-11e7-8798-3737339a7976.png">

**Comment by ngokevin** [comment]
Yeah, it's because it's based on scroll position so if the page doesn't scroll down far enough, it won't highlight. Not sure if it's a big deal, but we could add a special case to detect if user has scrolled all the way down and highlight bottom at https://github.com/aframevr/aframe-site
