### ISSUE TITLE
json-model entity can't be clicked

### ISSUE THREAD

**Issue by yursile** [aframevr/aframe#3067]
when i use v0.6.0, the json-model entity can't be selected nor clicked
but v0.5.0 goes well.
so what is the best practice on v0.6.0?
any suggestion would be grateful

here is my code:
`
<a-entity id="bot" cursor-listener class="clickable" animation-control="clip: run; : .3" scale="3.5 3.5 3.5" position="0 -4 -2.5" rotation="0 0 0" animation-mixer="clip: idle"
            json-model="src: url(models/bot4.json);"></a-entity>
`

**Comment by donmccurdy** [comment]
I believe this is the same issue as #2980, the raycaster's cache must be cleared after models load. We're considering ways to do this automatically, but you can add a component in the meantime:

```js
AFRAME.registerComponent('raycaster-refresh', {
  init: function () {
    var sceneEl = this.el.sceneEl;
    sceneEl.addEventListener('object3dset', function () {
      var raycasterEl = sceneEl.querySelector('[raycaster]');
      raycasterEl.components.raycaster.refreshObjects();
    });
  }
});
```

```html
<a-scene raycaster-refresh>
  ...
</a-scene>
```
