### ISSUE TITLE
Examples not working on Motorola X

### ISSUE THREAD

**Issue by tbalouet** [aframevr/aframe#307]
I just tried aframe.io on my Motorola X (2nd generation) and the examples don't appear correctly (black screen as you can see in the printscreen, even after a while so not a loading problem). Maybe a lighting problem (as we can see first printscreen a little).

Using:
 - Motorola X 2nd generation
 - Android 6.0
 - Mozilla beta 43.0b10 and Chrome 47.0.2526.83 

![screenshot_20151217-103920](https://cloud.githubusercontent.com/assets/5400381/11866372/fecc919e-a4aa-11e5-8176-d0f16b5b2983.png)
![screenshot_20151217-103937](https://cloud.githubusercontent.com/assets/5400381/11866373/fed07138-a4aa-11e5-9843-c1f543d54db7.png)

**Comment by jcarpenter** [comment]
Thanks @tbalouet. Getting more consistent results on Android devices is a top priority for us. Bug reports like this are very helpful. :+1:

**Comment by benknight** [comment]
Same issue here.  Several examples just show a black screen as depicted in the screenshots above.

* Moto X 2nd Gen
* Android 6.0
* Chrome for Android 47.0.2526.83

**Comment by nylki** [comment]
Same for Alcatel Idol3, (Android 5.0.x) in Chrome and Firefox.
The helloWorld example works fine, but composite etc. (all with textures?) show a black screen only.

**Comment by jbroadway** [comment]
Same here with:

* HTC Sense 6
* Android 5.0.2
* Chrome 47.0.2526.83

Seems to be an issue with textures, although the Shopping example is partially working. I can see the person, but not the other textures.

**Comment by ngokevin** [comment]
Fixed at ceb5fa9a71ad75d637e4ebe53fd178aeb189f1f8
