### ISSUE TITLE
how to import complex textures

### ISSUE THREAD

**Issue by zzylovecode** [aframevr/aframe#3071]
i can' find my textures when I import complex model into scene

**Comment by donmccurdy** [comment]
Hi @zzylovecode — the [3D Models → Troubleshooting](https://aframe.io/docs/0.7.0/introduction/models.html#troubleshooting) section in the docs is the best general advice we can offer if your model isn't working as expected.

If you've gone through all of those steps and still aren't getting anywhere, then we would need to see a demo and the source model to help.
