### ISSUE TITLE
documentation of component tick method states that time is in ms

### ISSUE THREAD

**Issue by remkoboschker** [aframevr/aframe#3076]
https://aframe.io/docs/0.7.0/core/component.html#tick-time-timedelta

The number passed is a floating point number. Are they  seconds? The three.Clock() method divides the ms from Date.new() by 1000.

https://github.com/mrdoob/three.js/blob/master/src/core/Clock.js

**Comment by dmarcos** [comment]
It is miliseconds.

**Comment by dmarcos** [comment]
The documentation is correct
