### ISSUE TITLE
<a-link> images are flipped

### ISSUE THREAD

**Issue by greengiant83** [aframevr/aframe#3077]
360 photos displayed with <a-link> tag are rendered horizontally flipped. 

- A-Frame Version: 0.7.0
- Platform / Device: Windows 10 Firefox / Oculus Rift

To reproduce:
Take a 360 snapshot of A-Painter splash screen (https://aframe.io/a-painter/) using `<ctrl>-<alt>-<shift>-s`. Note that image is saved with the text facing the expected direction. Use this image in an <a-link>. Note that the image text is horizontally reversed.

**Comment by greengiant83** [comment]
@machenmusik you are correct. It is fixed now. Sorry about that

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/3079
