### ISSUE TITLE
Multiple Videos

### ISSUE THREAD

**Issue by chillichief** [aframevr/aframe#308]
Its not possible to have multiple different videos, because the ID of the Video being played is hard coded in the `a-video` template.

    id="video"

Maybe this should be replaced by an attribute.

    id="${videoId}"

**Comment by jcarpenter** [comment]
Yep, we need to fix this limitation. It may happen with an updated primitives implementation that we are currently exploring. @cvan

**Comment by staus** [comment]
Just ran into this bug as well

**Comment by ngokevin** [comment]
For people running into this issue, for now I recommend falling back to using raw entities and components. This is a bug on an abstraction layer.

https://aframe.io/docs/components/material.html#Defining_Textures

**Comment by cvan** [comment]
FWIW: I opened a PR that fixes this issue: https://github.com/aframevr/aframe/pull/323

**Comment by ngokevin** [comment]
Fixed
