### ISSUE TITLE
A-Frame 0.7.0 - Problems with Oculus Rift Controllers: hand-controllers and raycaster. (r.mixer is undefined)

### ISSUE THREAD

**Issue by superjose** [aframevr/aframe#3082]
**Description:**

- A-Frame Version: 0.7.0
- Platform / Device: Firefox 55.0.3 (32-bit)
- Reproducible Code Snippet or URL: (My own localhost)

Better to explain it with pictures:

A-Frame 0.7.0:
![A-Frame 0.7.0](https://user-images.githubusercontent.com/8230270/30769213-016a4e98-9fe3-11e7-8ef9-bf5104f9aa63.png)

A-Frame 0.6.1
![image](https://user-images.githubusercontent.com/8230270/30769211-f5c3329e-9fe2-11e7-96d8-dabe39503341.png)

In A-Frame 0.6.1 (No code was modified when upgrading to 0.7.0), the oculus rift touch controller used to work with the hands-controller component. In addition, I wasn't receiving this r.mixer is undefined.

If I use the raycaster with the mouse, there isn't any issue.  Any ideas?

Edit (10:16 PM ET): 
This is the code with the entity:
`      <a-entity id="ctrlRight" hand-controls="right" super-hands sphere-collider="objects: a-sphere" laser-controls="hand: right"
`

**Comment by dmarcos** [comment]
I suggest opening an issue on the [super-hands](https://github.com/wmurphyrd/aframe-super-hands-component) and determine there if it's an A-Frame or a `super-hands` . I don't know much on how `super-hands` is implemented. I encourage using the Slack channel as well since people that use `super-hands` hang out there.

**Comment by donmccurdy** [comment]
using `hand-controls` and `laser-controls` and `super-hands` all together looks iffy to me. I'm pretty sure you'd want to just choose one of those three. Could be some sort of race condition there and 0.7.0 just changed the loadout order.

Note that if something else is already loading a model (like `hand-controls`) then `laser-controls` might as well be `cursor` and `raycaster="showLine: true"`.

**Comment by superjose** [comment]
Thanks for the response!!!
