### ISSUE TITLE
Add a caveats section to warn about unexpected behaviour

### ISSUE THREAD

**Issue by delapuente** [aframevr/aframe#3093]
Following [this comment](https://github.com/aframevr/aframe/pull/3040#issuecomment-329412188) on #3040, add a caveats section to warn about HTML APIs not working as expected and linking the F.A.Q.

**Comment by delapuente** [comment]
@ngokevin the JavaScript section is no longer there in 0.7.0, is it right? Where should I add the caveats section?

**Comment by ngokevin** [comment]
The page is back, I just had to fix an error in the Markdown file and re-deploy.
