### ISSUE TITLE
buttons are not hightlighted on Gear VR controller

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#3103]
**Description:**

With Gear VR, when I press touchpad or trigger on the controller, the button is not highlighted like the code in gearvr-controls.js suggests.

In gearvr-controls.js, we get the mesh by name `controllerObject3D.getObjectByName('Trigger')` and `controllerObject3D.getObjectByName('Touchpad')` to be able to highlight the buttons when the button is pressed, but the three meshes in https://cdn.aframe.io/controllers/samsung/gear_vr_controller.obj are all called Default when you `console.log(controllerObject3D)`.
To fix it, simply edit in gear_vr_controller.obj the three lines `g Default` in the file to `g Base`, `g Trigger` and `g Touchpad` in this order. Can someone please edit the file on the cdn?

- A-Frame Version:0.7.0
- Platform / Device: Gear VR

**Comment by ngokevin** [comment]
Would it be easier to edit the code instead?

**Comment by vincentfretin** [comment]
Sure, accessing with children[2] and children[1] works too, PR #3110
