### ISSUE TITLE
synchronous event handlers with a `.subscribe` method

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3107]
**Description:**

Synchronous events would be more predictable/performant. 

**Entity.subscribe (name, callback)**

Adds a `callback` function to be run when `Entity.emit` is called with `name`.

`Entity.emit` can both continue to fire the `CustomEvent`, and also run through the list of registered callbacks and trigger them with the event detail.

We can also consider `Entity.publish (name, ...arguments)` that does not fire the `CustomEvent`, and is more flexible on the data passed. Currently `Entity.emit`'s event detail usually has to be a JavaScript object, which leads to memory overhead. It would be nice to do `Entity.publish(foo, data1, data2, data3)`.

**Comment by donmccurdy** [comment]
Some concerns:

1. If we continue to fire the `CustomEvents` as we already do, then there's no performance gain. If components begin using a `.publish()` feature heavily, to take advantage of the performance for specific event types, then we'll have an ambiguous split in how events are handled, and one of the two will be unavailable to JS frameworks like React.
2. For some events — `componentchanged` comes to mind — this seems like a performance regression. Components change often, and firing all of those callbacks during the animation frame could slow scenes down. (Aside, I'm curious if dynamic scenes would see measurable benefit from removing the `componentchanged` event entirely, or requiring a per-property `notify` opt-in).

It seems like the problem you're addressing is one that could also be handled by React/Flux state management, Angular services, etc... we could instead make a framework-agnostic `broadcast` System available as a non-core service:

```js
sceneEl.systems.broadcast.emit('foo-message', {message: 'hey'});
```

**Comment by dmarcos** [comment]
Not sure if I understand. Is not `Entity.subscribe (name, callback)` the same as `entityEl.addEventListener(name, callback)`? What makes the first form `synchronous`? What are the performance concerns of `CustomEvents` vs an ad-hoc `publish / subscribe` API?

**Comment by ngokevin** [comment]
If you `.subscribe`, the callback would fire immediately/synchronously after an event is emitted/published. There's a tiny bit of overhead for running Custom Events + event loop vs. a simple function call, but also developer ergonomics for having to do everything asynchronously.

You fire an action, then have to register an asynchronous event listener, meaning you have to create a function + closure + bind your methods. If you do things synchronously, you don't have to do things roundabout and get results happening immediately after events are fired.

**Comment by donmccurdy** [comment]
We're not really in new territory here; Browsers do a lot of work to align certain events right before the rAF cycle. Jake Archibald had some nice summaries recently: https://twitter.com/jaffathecake/status/912995275756773380

In Chrome, you can use `PointerEvent.getCoalescedEvents()` to get all events since the last paint. Not just synchronous, but also you don't need a callback function. 

> ... developer ergonomics for having to do everything asynchronously. You fire an action, then have to register an asynchronous event listener, meaning you have to create a function + closure + bind your methods.

Function+closure+bind requirement all still applies to `.subscribe()` approach though right? I don't think developer ergonomics are an issue here.

**Comment by ngokevin** [comment]
Closing for now, perhaps more gain into making other certain things synchronous-available (e.g., entity creation and removal).
