### ISSUE TITLE
Rendering text?

### ISSUE THREAD

**Issue by mattpolicastro** [aframevr/aframe#311]
I may be in a bit over my head, but are there any straightforward means of rendering text (a la [three.js and TextGeometry](http://threejs.org/docs/#Reference/Extras.Geometries/TextGeometry)) as part of a scene rather then relying on images? It would be pretty cool to provide dynamic labels on mouse/pointer events.

**Comment by ngokevin** [comment]
I'm working on an example text component implementation using TextGeometry at https://github.com/ngokevin/aframe-text-component

Also https://github.com/MozVR/aframe-core/issues/319

**Comment by mattpolicastro** [comment]
Woohoo! Thank you. Apologies for duplicating an existing topic.

**Comment by ngokevin** [comment]
https://github.com/ngokevin/aframe-text-component is working now. Requires that you register it but it's there :)

Eventually it will come out of the box. Thanks for filing!
