### ISSUE TITLE
User height offset is added multiple times when entering and exiting VR

### ISSUE THREAD

**Issue by KrzysztofWrobel** [aframevr/aframe#3113]
**Description:**
- A-Frame Version: 0.7.0
- Platform / Device: MobileVR - Cardboard, Daydream, GearVR
- Reproducible Code Snippet or URL:
`<a-entity camera="userHeight: 1.6" look-controls></a-entity>`
The same happens in an official exmaple:
https://aframe.io/examples/showcase/helloworld/

Every time I enter and exit VR mode on mobile device userHeight offset is added multiple times to camera Y position. I used a quick fix, as follows:
`<a-entity position="0 1.6 0" camera="userHeight: 0.01" look-controls></a-entity>`
This helped, as a very small offset is added to camera height, but I assume it will break things on Vive, Oculus and Windows Mixed Reality headsets. :/
Edit: My quick fix also breaks controller position on Daydream and GearVR.

**Comment by weddingdj** [comment]
In the "enter-vr" event listener I set the userHeight to 0 as a workaround. Works in Cardboard and Gear VR with controllers and I guess in the other HMDs as well.

I am not sure if this actually *is* a bug...

**Comment by machenmusik** [comment]
Is this the same as #3051 / #3111 (now closed) ?

**Comment by dmarcos** [comment]
Yes, this seems a dup of https://github.com/aframevr/aframe/issues/3051

**Comment by KrzysztofWrobel** [comment]
Thanks guys for your comments. Until PR referenced in #3111 is merged to master, I will check out the fix suggested by @weddingdj.
