### ISSUE TITLE
cursor="rayOrigin: mouse" does not work on touchscreens

### ISSUE THREAD

**Issue by ejnaren** [aframevr/aframe#3114]
**Description:**

- A-Frame Version: 
A-frame 7.0
- Platform / Device: 
Windows 10 - Firefox 55 and Chrome 61
Android - Chrome Browser 61
- Reproducible Code Snippet or URL:
https://jsfiddle.net/8jmcuaLw/4/

When using a touchscreen the 'click' event does not register properly. 
In above url try clicking the blue box on a touch screen.
Following would be expected:
 - When clicked the blue box should change to a random hue.
What actually happens:
- the 'touch'/'click' does not register on first touch.
- It registers second time but this time I can trigger the click event on the box by clicking anywhere on the screen. Even besides the box.

**Comment by wmurphyrd** [comment]
I can work on this. My changes in #2973 may be related and I'm working on a similar problem in 
wmurphyrd/aframe-super-hands-component#71

**Comment by ejnaren** [comment]
Awesome. You are a star. 
let me know if you need anything from me.

**Comment by ngokevin** [comment]
Merged, but will need a small tweak PR to make the touches not delayed.
