### ISSUE TITLE
Camera height changes every time user enters in VR mode

### ISSUE THREAD

**Issue by VitoMatarazzo** [aframevr/aframe#3118]
**Description:**

- A-Frame Version: 0.7.0
- Platform / Device: Chrome on Android phone

I have a scene with "a-camera" placed in the default position. When I enter VR mode on a mobile browser on different Android smartphones the camera automatically goes up of 1.6, while upon exiting VR mode the height doesn't return to the previous value. So the height increases everytime the user enters VR. I have tried to manually set the position of the camera and change the userHeight parameter but the problem remains.

I managed to solve this problem by resetting the camera to the default height -1.6 upon entering VR, but I don't think this is how the camera should work.

**Comment by dmarcos** [comment]
Thanks! This is a dup of https://github.com/aframevr/aframe/issues/3051

**Comment by alessandrocaprarelli** [comment]
I have the same issue in Chrome version 62 on Android phone with A-frame Version 0.7.1.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/3327

**Comment by TheDirigible** [comment]
It's still happening for me, what's the solution?
