### ISSUE TITLE
Trying to use Custom Elements v1 is a huge pain!

### ISSUE THREAD

**Issue by trusktr** [aframevr/aframe#3121]
I've been trying to make [my project](https://github.com/trusktr/infamous) work in Edge, and it's been a pain because v1 works with native classes, and it's a mess trying to transpile/not transpile. I've had no luck with Polymer's (Justin Fagnani's) shim yet. I'm going to also give Andrea's [babel-plugin-transform-builtin-classes](https://github.com/WebReflection/babel-plugin-transform-builtin-classes) a shot.

What are your guys plans, if any, on v1? Have you tried it? Maybe you don't want to. For me it's too late, I'm already settled on using native classes and not turning back, at least not right now.

**Comment by ngokevin** [comment]
It's not supported in all browsers so we will stick with the polyfill. Things will break with a straight switch to v1, and behavior will be inconsistent supporting both. Good luck.

**Comment by trusktr** [comment]
> Good luck

Yeah, it's been tough couple days with nothing working. No matter what I try (transpilation, no transpilation, document-register-element, @webcomponents/custom-elements with and without Justin Fagnani's native-shim, and every permutation of those, I simply always get the `HTMLElement can not be called without 'new'` error.

Well, except I've gotten it to work where CE v1 is natively supported, but that's about it.

@dmarcos made some changes to document-register-element. Do you know what for?

**Comment by ngokevin** [comment]
We monkey-patch the way document-register-element works a bit so we can have a hierarchy of classes that pretty much call `super()` on each other for various methods. I think there were a few other patches to fix bugs in the polyfill.

**Comment by trusktr** [comment]
With some tinkering, I've gotten v1 to work in IE and up (IE 10+, Edge 12+, Chrome, etc).

---

> so we can have a hierarchy of classes that pretty much call super()

I'm not sure what you mean? I have hierarchy of classes using vanilla `document-register-element` where these classes call `super.attributeChangedCallback`, `super.connectedCallback`, etc. Haven't had any problems with that yet.

**Comment by dmarcos** [comment]
Migration time has come. https://github.com/aframevr/aframe/pull/4167 moves A-Frame to Custom Elements V1. Thanks for patience.
