### ISSUE TITLE
laser-controls line does not respect intersection line length

### ISSUE THREAD

**Issue by DavidWyand** [aframevr/aframe#3124]
**Description:**
The line component that is part of laser-controls does not change its length to the intersection distance as determined by the raycaster component.  What should happen is the line component shortens itself to not extend past the nearest intersection point.  What ends up happening is the line component remains at the raycaster's far value.

- A-Frame Version: 0.7.0
- Platform / Device: Tested with Vive on Firefox 56.0, and GearVR with GearVR controller using Oculus' browser
- Reproducible Code Snippet or URL: May be seen in link-traversal showcase example

Spent a long time trying to figure out why the laser-controls component wasn't correctly changing its laser line length in my own project.  But then I found that the link-traversal example also exhibits the same issue: its laser lines go right through the link portals.

I've found a couple of reasons for this.  One I solved, and the other I worked around.

The first issue I found was that the raycaster stopped calling its drawLine() method as soon as there was a valid intersection.  The reason for this is due to a _return_ call in its tick() method.  Change the _return_ in this code block starting at line 218 in raycaster.js from:

```
// Emit intersection cleared on both entities per formerly intersected entity.
for (i = 0; i < prevIntersectedEls.length; i++) {
  if (intersectedEls.indexOf(prevIntersectedEls[i]) !== -1) { return; }
  el.emit('raycaster-intersection-cleared', {el: prevIntersectedEls[i]});
  prevIntersectedEls[i].emit('raycaster-intersected-cleared', {el: el});
}
```

to a _break_:

```
// Emit intersection cleared on both entities per formerly intersected entity.
for (i = 0; i < prevIntersectedEls.length; i++) {
  if (intersectedEls.indexOf(prevIntersectedEls[i]) !== -1) { break; }
  el.emit('raycaster-intersection-cleared', {el: prevIntersectedEls[i]});
  prevIntersectedEls[i].emit('raycaster-intersected-cleared', {el: el});
}
```

This allows for drawLine() to be properly called with the correct length, which should have been it.  Unfortunately, there appears to be a deeper issue with A-Frame for the next reason.

Within raycaster's drawLine() method there is the following at line 307:

    el.setAttribute('line', lineData);

As far as I can tell, this is perfectly fine.  The trouble is that the line component's update() method never gets called after this.  I've tried splitting out the _start_ and _end_ attributes into their own calls.  I saw someone mention in an issue calling setAttribute() twice to force an update.  I was never able to get the line component's update() method to trigger, so the line always ended up being the same length no matter what was sent to it.

My current work around to fix this is to modify the raycaster's tick() method to remove the line component just before calling drawLine():

```
      // Update line length.
      if (data.showLine) {
        if (intersections.length) {
          if (intersections[0].object.el === el && intersections[1]) {
            lineLength = intersections[1].distance;
          } else {
            lineLength = intersections[0].distance;
          }
        }
	el.removeAttribute('line'); // DAW: Heavy handed change to force a new line as a test
        this.drawLine(lineLength);
      }
```

This forces the line component to be rebuilt within drawLine(), and its attributes end up being correctly set.  I don't like the idea of having to rebuild the line component every tick, so hopefully this issue with setAttribute() can be resolved.

**Comment by ngokevin** [comment]
I think if you clone the vector, you can get it to run the `update` call. Can you try changing to `lineData.end = lineEndVec3.clone().copy(this.unitLineEndVec3).multiplyScalar(length);`? And then PR with the `break` fix? Thanks for investigating!

I think regressions from doing garbage collection optimizations. Ideally we don't clone the vector, perhaps a more proper way to get the update to run while not cloning is two have two vectors for updating the line, and alternate between them.

**Comment by vincentfretin** [comment]
@DavidWyand Thanks for investigating! I continued your work on this.
@ngokevin adding clone() indeed fixed the issue.
I created PR #3127 with the break and using two vectors to avoid unnecessary clone. It is working great.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/3127

**Comment by DavidWyand** [comment]
Thanks for taking care of this guys before I could get to it.  All of the changes are working at my end.
