### ISSUE TITLE
consider having raycaster only emit the start of intersections

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3129]
**Description:**

Currently, the raycaster seems to emit an event + object per tick per intersected entity, which is quite a bit. Even if the intersected entity was already intersecting on the last tick. So imagine you are just hovering over anything without moving, they'll get continuously pounded with events. I think we need only emit these events on the intersection start.

```js
    // Emit intersected on intersected entity per intersected entity.
    for (i = 0; i < intersections.length; i++) {
      // TODO: Check previousIntersectedEls to see if this is a new intersection.
      intersections[i].object.el.emit('raycaster-intersected', {
        el: el,
        intersection: intersections[i]
      });
    }
```

**Comment by machenmusik** [comment]
Is there a better way to understand when and how the intersection point changes?  I think that is the primary value of the subsequent events.  Use case - drawing a dot / placing an object on a plane or box where the intersection point is.

**Comment by machenmusik** [comment]
Maybe emit the first intersection, and then the recipient should register on the raycaster for further updates for that element?  At the moment, I don't think the intersections are objects that survive across raycasts and update live.

**Comment by ngokevin** [comment]
Hmm, I forgot about that. Perhaps a property to always keep emitting in case you need that...? Even then you might not need it for every object. Theoretically, it'd be most efficient to look up the intersection data yourself which is not too hard.

**Comment by ngokevin** [comment]
Maybe a subscribe method to put your entity on a list to get a callback for intersection updates?

**Comment by machenmusik** [comment]
I'm thinking use cases like - raycaster detects ground plane and also other objects in environment; if ground plane is first hit, you want live updates to highlight where you want the object placed, but if other objects, you don't highlight (and don't care where until).  For that use case, you want a property that will throttle the intersection count for which events are emitted (e.g. to 1, or 2 if you want to be able to point through objects if required)

**Comment by ngokevin** [comment]
Could be done like so, perhaps not worth maintaining an API for what can be done with a bit of JS?

```js
groundEl.addEventListener('raycaster-intersected', el => {
  this.intersectingRaycaster = evt.detail.el;
});

groundEl.addEventListener('raycaster-intersected-cleared', () => {
  this.intersectingRaycaster = null;
});

...

tick: () => {
  if (!this.intersectingRaycaster) {  return; }
  var intersectionIndex = this.intersectingRaycaster.components.raycaster.intersectedEls.indexOf(this.el);
  var intersection = this.intersectedRaycaster.components.raycaster.intersections[intersectionIndex];
}
```

**Comment by machenmusik** [comment]
I thought we wanted to discourage code from reaching into component internals directly (so the implementations can evolve as needed) - if we want this to happen more often, should accessor methods be defined to provide a clean API?

**Comment by ngokevin** [comment]
Nah, I don't discourage that. I do lookups like that often. Members/methods are fine to be public API, depends how it's documented.

**Comment by machenmusik** [comment]
actually, why not 
```
groundEl.addEventListener('raycaster-intersected', el => {
  this.intersectingRaycaster = evt.detail.el.components.raycaster;
});

groundEl.addEventListener('raycaster-intersected-cleared', () => {
  this.intersectingRaycaster = null;
});

...

tick: () => {
  if (!this.intersectingRaycaster) {  return; }
  var intersectionIndex = this.intersectingRaycaster.intersectedEls.indexOf(this.el);
  var intersection = this.intersectedRaycaster.intersections[intersectionIndex];
}
```

**Comment by machenmusik** [comment]
ohhhh wait, neither of our JS solutions are quite the same, because raycaster interval is not the same as tick frequency...  IMO biggest raycaster perf boost is throttling raycasts to use appropriate interval.

**Comment by ngokevin** [comment]
ticks can be throttled too.

I'm OK with just linking to this issue to the reference code above in the CHANGELOG. Upgrading your dependency is a deliberate step and comes with upgrade steps, so yeah, we can provide helpful instructions on upgrading, but not need to go as far as publishing a component.

**Comment by dmarcos** [comment]
We can have a `breaking changes` section on the changelog for people to consider when updgrading

**Comment by ngokevin** [comment]
Yeah, we've always had it, **Major Changes** + **Deprecations**

**Comment by dmarcos** [comment]
Deprecation = `something that is gone` 
Major Changes can include `outstanding` new features besides `breaking changes`
I was thinking more like a list you can just go down to know where your existing content might break

**Comment by machenmusik** [comment]
@dmarcos exactly.

@ngokevin so you're thinking not worth making a subscribe per https://github.com/aframevr/aframe/issues/3129#issuecomment-334773254 ?  I actually thought that was cleaner, and is a step toward knowing when no one is interested and avoiding emit entirely

**Comment by ngokevin** [comment]
I just called it Major before since in semver, major changes are breaking changes but we can add a subcategory.

@machenmusik I'm OK just having people do it manually versus maintaining something new. Where there's a will, there's a way.

**Comment by machenmusik** [comment]
@ngokevin ok - or maybe just add a method like getElementIntersection(el) on the raycaster that does the lookup.

**Comment by ngokevin** [comment]
Sounds good.

**Comment by ngokevin** [comment]
done

**Comment by vincentfretin** [comment]
@machenmusik FYI, in trying to port planes detection of aframe-ar to aframe 0.8.2, I tried some of the proposed code, this is fine to intersect only one object, groundEl in your example @ngokevin but in practice you have several planes, destroying and recreating during the session, and other objects in your scene you want to interact with. I'll give you an example that clearly is difficult to do with the current raycaster code in aframe 0.8.2. With a plane and a cube on the plane, the two are raycastable.
- you have the ray on the plane, raycaster-intersected on the plane, raycaster-intersection with the plane, fine
- then you hover on the cube, the ray intersects both the cube and the plane, raycaster-intersected on the cube, raycaster-intersection with the cube, good
- now you hover on the plane, raycaster-intersected-cleared on the cube good,  raycaster-intersection-cleared with the cube, but no other events for other existing intersections (the plane), how do I move a cursor along the plane now?
I even tried to do this to have a raycaster-intersected event again on the plane:

```
const cursor = document.getElementById("cursor");
const raycaster = document.querySelector("[raycaster]");
raycaster.addEventListener(
    "raycaster-intersection",
    (evt) => {
      var point = evt.detail.intersections[0].point;
      cursor.setAttribute("position", point);
      const el = evt.detail.els[0];
      el.setAttribute("follow-intersection", "follow:true");
});

  raycaster.addEventListener(
    "raycaster-intersection-cleared",
    (evt) => {
      evt.detail.clearedEls.forEach(el => {
        el.setAttribute("follow-intersection", "follow:false");
      });

      // if we still intersect an element, it becomes the one where we follow the reticle
      if (raycaster.components.raycaster.intersections.length > 0) {
        raycaster.components.raycaster.intersectionDetail.els =
          raycaster.components.raycaster.intersectedEls;
        raycaster.components.raycaster.intersectionDetail.intersections =
          raycaster.components.raycaster.intersections;
         raycaster.emit(
           "raycaster-intersection",
           raycaster.components.raycaster.intersectionDetail
         );
      }
  );
```
It did work, but sometime my cursor froze because the plane is destroyed and another one is created I guess, I'm not sure.
And I created a component like this:
```
AFRAME.registerComponent("follow-intersection", {
  schema: {
    follow: { default: false }
  },
  init: function() {
    this.el.addEventListener("raycaster-intersected", evt => {
      this.intersectingRaycaster = evt.detail.el.components.raycaster;
    });
    this.el.addEventListener("raycaster-intersected-cleared", () => {
      this.intersectingRaycaster = null;
    });
    this.cursor = document.getElementById("cursor");
  },
  tick: function() {
    if (!this.intersectingRaycaster) {
      return;
    }
    if (!this.data.follow) {
      return;
    }
    const intersection = this.intersectingRaycaster.getIntersection(this.el);
    if (intersection) {
      this.cursor.setAttribute("position", intersection.point);
    }
  }
});

```
In practice, you have several objects intersected, not only one, so I introduced a follow attribute to only enable the follow intersection behavior for only one intersected object. because updating the cursor from several components is not good at all. :)

So in the end, I gave up, too complex and I'm still having issues with cursor sometime not following on a plane.
I ended up reintroducing the raycaster-intersection event for all intersections, not only newIntersections.

```
index 6928c87..6b389ae 100644
--- a/src/components/raycaster.js
+++ b/src/components/raycaster.js
@@ -252,9 +252,14 @@ module.exports.Component = registerComponent('raycaster', {
     }
 
     // Emit all intersections at once on raycasting entity.
-    if (newIntersections.length) {
-      this.intersectionDetail.els = newIntersectedEls;
-      this.intersectionDetail.intersections = newIntersections;
+//    if (newIntersections.length) {
+//      this.intersectionDetail.els = newIntersectedEls;
+//      this.intersectionDetail.intersections = newIntersections;
+//      el.emit('raycaster-intersection', this.intersectionDetail);
+//    }
+    if (intersections.length) {
+      this.intersectionDetail.els = intersectedEls;
+      this.intersectionDetail.intersections = intersections;
       el.emit('raycaster-intersection', this.intersectionDetail);
     }
 ```

So what do you folks think about this? Do I keep my custom aframe build? Do we add back the raycaster-intersection event for all intersections like I did? An option to select this behavior?

**Comment by vincentfretin** [comment]
@wmurphyrd You're right super-hands seems to actually do exactly what I want for my third bullet point. You maintain an array of this.hoverEls, and on unhover on say the cube, you look at next target in this.hoverEls to start the hover on the plane. It appears I'm trying to reimplement what you did in super-hands indeed.
I'm just finding it unfortunate that I now need to add much complexity to my code or add an extra dependency to my project to do what used to work in aframe 0.7.1. I know all those changes are for performance reasons, and I appreciate all your work in this area.
I'll maybe retry this by looking at the super-hands code or using it as a new dependency on my project. But for now, I'll use my custom aframe build.

**Comment by machenmusik** [comment]
In the original plane-cube example, the problem is that the intersection is
being cleared on the cube but not being started on the plane reliably,
right?

nothing -> plane; plane fires
plane -> cube and plane; cube fires
cube and plane -> plane; cube fires, but plane does not

I don't think we want to fire redundant events per raycaster interval; it
does seem to me, however, that a consistent "intersection-set-has-changed"
event might be worth having, and the default behavior in response could be
to fire off the individual intersection-cleared and intersection events
that are deemed appropriate.

Maybe there should be a "closest" event, which would fire for plane after
cube is no longer intersected, which would solve this?

**Comment by ngokevin** [comment]
You can define two raycasters, one for plane, one for everything else, with separate intervals.

**Comment by machenmusik** [comment]
The aframe-ar-plane Glitch has a slightly different solution

**Comment by donmccurdy** [comment]
The intersection set should only change if a `raycaster-intersected` or `raycaster-intersection-cleared` event fires. You can then iterate over `el.components.raycaster.intersections` directly to find the remaining intersections. Or if you specifically care about the plane, call `raycaster.getIntersection(planeEl)` to see if it is intersected.

**Comment by machenmusik** [comment]
@ngokevin I don't think two raycasters will work well, but YMMV

@donmccurdy yes I know but if we're going to do that manual processing then why not move more complicated event emission out of raycaster?  The one by one for intersection is inefficient compared to the all in one for cleared, and when using the one by one paradigm I do think it is reasonable for folks to expect cleared events to be symmetrical, which they are not

**Comment by donmccurdy** [comment]
@machenmusik I'm not sure what you mean by "symmetrical", but yes, I'm not opposed to changing the events. But I do think use of the programmatic API will be necessary for certain use cases, and that's OK — `raycaster` should stick to something that won't add too much overhead. TBH I think the `cursor` component itself would be a little simpler if it accessed the raycaster component programmatically. 😅

**Comment by machenmusik** [comment]
Yeah, I'm thinking maybe we should have an option that turns off all the event emitting (except maybe one when intersections change) so if you want to customize by reading the internals, you don't have to incur the garbage and overhead from the rest.

**Comment by donmccurdy** [comment]
The current event API is only firing when the list of intersections changes, right? Except the occasional case where two objects lose intersection at the exact same time? Just have to listen for both events. 

Seems like a case where numbers or a motivating example would be best. If there's a measurable improvement to be made, an option is fine with me. But the current API is new enough that I feel like we should wait a bit.

**Comment by machenmusik** [comment]
looking at things starting from https://github.com/aframevr/aframe/blob/master/src/components/raycaster.js#L204
I can see that we want to filter out some data up to line 222.
But in cases where we're going to check things by ourselves later, especially the case where we are only interested with intersection with a single entity via getIntersection, there is a bunch of superfluous work and/or garbage from lines 224 through 260; I still think having a single emit would be helpful then (e.g. to avoid having to monkey-patch checkIntersections to match raycaster interval)

**Comment by ngokevin** [comment]
If there was an option to disable that event and look up intersection data manually, I would use it.
