### ISSUE TITLE
Bind mousemove to document for a better navigation experience

### ISSUE THREAD

**Issue by Dogfalo** [aframevr/aframe#313]
Whenever you click in any of the examples and drag around, if you leave the frame at all, it stops the rotation of the canvas and you have to click and hold again in the canvas to start panning again. This leads to a pretty annoying experience.

**Comment by cvan** [comment]
@Dogfalo thanks for filing. I think this behaviour is similar to the behaviour described in #293 - can you confirm if that's the same issue you're seeing?

**Comment by Dogfalo** [comment]
Yep it is.
