### ISSUE TITLE
string-trim primitive attribute values

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#3132]
**Description:**
For example: color=" #FF0000" throws an "THREE.Color: Unknown color  #FFFFFF" error. Would it make sense to trim the string?

- A-Frame Version: 0.7.0
- Platform / Device: -
- Reproducible Code Snippet or URL: https://codepen.io/anon/pen/wryJxK

**Comment by ngokevin** [comment]
Can you provide an example?

**Comment by weddingdj** [comment]
https://codepen.io/anon/pen/wryJxK

**Comment by ngokevin** [comment]
If you'd like to submit a PR, you can `.trim()` the values at https://github.com/aframevr/aframe/blob/master/src/extras/primitives/primitives.js#L92

**Comment by weddingdj** [comment]
ok will do.
