### ISSUE TITLE
Composite example not working on Nexus 5, Chrome 47.0.2526.83

### ISSUE THREAD

**Issue by chriscar** [aframevr/aframe#314]
The screen is black, although the googles icon shows up. I built a scene with a sky myself, same result, black screen. Other examples work, eg. Anime etc.

**Comment by ngokevin** [comment]
Hey thanks for reporting, we're currently resolving issues with some Android devices by bumping to a later version of three.js, look for it soon.

**Comment by chriscar** [comment]
Ok!

**Comment by apiaget** [comment]
Same on my Nexus 5 (Android 4.4.4., Chrome 47.0.2526.83). In the Chrome console, I get the messages : 
> THREE.WebGLRenderer 74dev
> THREE.WebGLRenderer: OES_texture_float_linear extension not supported.

**Comment by nylki** [comment]
@ngokevin Any update? :)
This is probably related: #307

**Comment by ngokevin** [comment]
I believe we have it fixed on our `dev` branches. We'll have to wait until we release the next version of A-Frame where we'll be shipping a lot of changes.

**Comment by nylki** [comment]
@ngokevin I checked out the `dev` branch from github. It's definetely not fixed there. ;)
Anyways, looking forward to the new release.

**Comment by ngokevin** [comment]
We haven't run a dist on the dev branch yet. Did you build aframe-core?

**Comment by nylki** [comment]
@ngokevin ah, thanks for the hint! Totally oversaw to checkout aframe-core. Just read through the instructions with `npm link` etc. Will try it out tommorow.

**Comment by apiaget** [comment]
I just runned `npm dist` on the dev branch. The `aframe.js` file produced allows me to use `<a-sky>` now. I do not have a black screen anymore on my Nexus 5 (Android 4.4.4, Chrome 47.0.2526.83) but Firefox 43.0 crashes.

**Comment by dmarcos** [comment]
Glad to know :)

**Comment by chriscar** [comment]
That's great!
