### ISSUE TITLE
issues/feature request -> audio

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [aframevr/aframe#3141]
**from my point of sight, it would be interesting for you to:**

- *including supercollider.js in your framework;*
- *porting libpd to javascript (perharps using emscripten)*
- *compiling csound for aframe*
- *including a Lisp Algorithmic composition framework in a framework such as PWGL*

---

**furthermore:**

- *using an implementation of fft in opencl (i have forked some in case you may want to take a look);*
- *use that to make an implementation of higher order ambisonics/emulating wave field synthesis in stereo;*

**Comment by dmarcos** [comment]
This experimentation can also happen as a 3rd party component.

**Comment by ngokevin** [comment]
Yeah, it's pretty specific and fairly complex, I'd encourage a separate component. Thanks!
