### ISSUE TITLE
Raycaster line does not shorten on intersection

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#3144]
**Description:** Starting in 0.7.0, a raycaster with `showLine: true` no longer updates the line length when finding an intersection. Stepping through, all the correct actions to update the line are performed, but it looks like the `line.data.end` and the `lineEndVec3 ` scratch variable in `raycaster.drawLine` are becoming the same object, preventing the checks in `line.update` from ever detecting a change.

- A-Frame Version: 0.7.0
- Platform / Device: Desktop
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/green-nitrogen

**Comment by ngokevin** [comment]
was fixed at https://github.com/aframevr/aframe/issues/3124

**Comment by wmurphyrd** [comment]
Sorry - I looked but missed that one
