### ISSUE TITLE
memory not released after scene is removed

### ISSUE THREAD

**Issue by ebhoren** [aframevr/aframe#3146]
Memory is not released after a scene is removed from DOM.

- A-Frame Version: 0.7.0
- Platform / Device: iPad/iPhone
- Reproducible Code Snippet or URL: https://codepen.io/ebhoren/pen/zEjYRO

Make a memory snapshot before adding a scene. 
Another memory snapshot after adding a scene.
Remove the scene and take another memory snapshot.

You will see the memory is not released and just keep increasing each time you remove a scene and add a new one.

Thanks

**Comment by dmarcos** [comment]
What is the use case for adding / removing scenes? It will be probably better to empty a scene and repopulate.

**Comment by ebhoren** [comment]
I'm adding/removing scenes because i splitted my app logic in 3 big scenes. 
Each scenes load around 30-40mb on textures and videos.

How can i achieve this by emptying the scene, and his assets, and repopulate it with new elements+assets in the assets manager?

**Comment by ngokevin** [comment]
Asset manager is just for blocking the scene on first load, it does not have any benefit after that. You can use inline URLs and have the same effect. But emptying/modifying the scene is the way to go, and we won't much support this use cases of attaching/reattaching scene. If you have any specific places where A-Frame can free memory, feel free to file an issue for that. Thanks!

**Comment by donmccurdy** [comment]
one quick comment i'll pull from #3137 - we should probably call WebGLRenderer.dispose() when a scene detaches
