### ISSUE TITLE
Downloading https://aframe.io/releases/latest/aframe.min.js results in a SSL error

### ISSUE THREAD

**Issue by chriscar** [aframevr/aframe#315]
wget https://aframe.io/releases/latest/aframe.min.js
--2015-12-20 20:02:49--  https://aframe.io/releases/latest/aframe.min.js
Resolving aframe.io (aframe.io)... 104.31.93.82, 104.31.92.82
Connecting to aframe.io (aframe.io)|104.31.93.82|:443... connected.
OpenSSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Unable to establish SSL connection.

**Comment by ngokevin** [comment]
Works in browser and with wget for me.

Probably an issue with your OpenSSL?

**Comment by chriscar** [comment]
hm, probably it is an issue with my OpenSSL, although I could wget https://code.jquery.com/jquery-2.1.4.min.js without problems - anyways I close the issue... thanks!
