### ISSUE TITLE
Better documentation on `AFRAME.registerShader()` needed!

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#3151]
Per discussion at https://aframevr.slack.com/archives/C0GG937RN/p1507678947000225
The functionality of `AFRAME.registerShader()` has improved to the point where it is pretty useful, but the documentation for shaders is buried inside `material`, and the documentation for `registerShader()` does not have an example of recent changes which allow very straightforward usage without dipping down into `THREE` materials:
```
/* global AFRAME */
// Grid along X and Z (horizontal planes).

AFRAME.registerShader('grid', {
  schema: {
    color: {type: 'color', is: 'uniform', default: 'white'},
    opacity: {type: 'number', is: 'uniform', default: 1.0},
    thickness: {type: 'number', is: 'uniform', default: 1.0},
    interval: {type: 'number', is: 'uniform', default: 0.01}
  },

  raw: true,

  vertexShader: [
    'precision mediump float;',
    'attribute vec2 uv;',
    'attribute vec3 position;',
    'uniform mat4 projectionMatrix;',
    'uniform mat4 modelViewMatrix;',
    'uniform float interval;',
    'varying vec2 coord;',
    'void main(void) {',
    '  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);',
    '  coord = vec2(position.x / interval, position.z / interval);',
    '}'
  ].join('\n'),

  fragmentShader: [
    '#extension GL_OES_standard_derivatives: enable',
    'precision mediump float;',
    'uniform vec3 color;',
    'uniform float opacity;',
    'uniform float thickness;',
    'varying vec2 coord;',
    'void main() {',
    '  vec2 grid = abs(fract(coord - 0.5) - 0.5) / fwidth(coord);',
    '  float line = min(grid.x, grid.y);',
    '  if (line > thickness) { discard; } else',
    '  gl_FragColor = vec4(color, opacity);',
    '}'
  ].join('\n')
});
```

**Comment by ngokevin** [comment]
Yeah, please add. Thanks!

**Comment by MichaelHazani** [comment]
Awesome!
Couple of assorted thoughts for useful info in that regard, some rehashed from the Slack debate:

- A general overview of how registerShader wraps around THREE.ShaderMaterial
- A quick explanation about the relationship between Schema and Uniforms, or at least an example
- An example or mention of tock() logic to demonstrate time-based shader code
- (Perhaps a nontrivial example showing how uniforms can be derived from dynamic data like mouse pos, etc.?)
- Best practices?


-useful, external links - depending on the type of service you want the docs to fulfill, but since A-frame is beginner-facing I think mentioning these would do a great service to many who encounter shaders for the first time through Aframe and the docs: 
[THREE.ShaderMaterial](https://threejs.org/docs/#api/materials/ShaderMaterial),
[The Book of Shaders](https://thebookofshaders.com/)
[The Cg Tutorial](http://developer.download.nvidia.com/CgTutorial/cg_tutorial_chapter01.html) ("Cg" is a bit of a misnomer - 99% of it is applicable to GLSL and despite its age it is still one of the best introductions to gpu programming. It's also free:)

**Comment by machenmusik** [comment]
Thanks @MichaelHazani - how does the current PR match up?  I think the time-varying one may be the most interesting of current examples.  Can you say more about `derived from dynamic data`?  Feel free to make a PR on my fork to include here, which may be easier.

**Comment by donmccurdy** [comment]
Thanks for these docs! They are indeed better.

For reference this is what i've done in the past for shaders: https://glitch.com/edit/#!/aframe-displacement-shader?path=client/index.js:1:0 (although i should use `object3dset` and not `model-loaded` there...).

I kind of lean toward the component+shader approach. Between missing `tick()`, missing uniform types, and no support for custom models, it feels very hard to recommend `registerShader` to new users for me.

**Comment by ngokevin** [comment]
Previous proposal going that route in https://github.com/aframevr/aframe/issues/2047, the API is half-baked and more to maintain.

**Comment by machenmusik** [comment]
So several discussions later, I am still leaning toward partitioning shader functionality into shader, and material functionality into the material component rather than continually requiring one-off replacements (see #3154 and #3155).

#3154 still includes the documentation on custom shader plus material component.  Note that both examples (grid-glitch and displacement)

**Comment by machenmusik** [comment]
See https://glitch.com/edit/#!/aframe-displacement-registershader
Seems cleaner to me.

#3155 will be useful even without custom shaders, assuming that we proceed.

**Comment by donmccurdy** [comment]
^BTW the glitch example has a leftover `time` reference where the noise should be updated.

> I am still leaning toward partitioning shader functionality into shader, and material functionality into the material component rather than continually requiring one-off replacements

Could you explain this more? You mean keeping a `registerShader` API that is used through the `material` component, I think?

**Comment by machenmusik** [comment]
Re: time reference - first line in vertex shader main computes time from time1000, so I think it still works?

Re: partitioning meaning registerShader and material component changes, yes I am still leaning that way.  The shader data schema makes it easy to change values for the shader, even if you want to make a separate component to doit, works the same as rest of a-frame

**Comment by donmccurdy** [comment]
> Re: time reference - first line in vertex shader main computes time from time1000, so I think it still works?

In your demo the model just [scales with constant noise](https://aframe-displacement-registershader.glitch.me/), whereas [in the original noise is updated with time](https://aframe-displacement-shader.glitch.me/). I assumed you were trying to reproduce mine with less code, yes?

**Comment by MichaelHazani** [comment]
Just had a chance to catch up on the new suggested docs - I agree, much better, thank you.
In terms of feedback, I think there's still ambiguity in time vs. tick - and the fact the regsiterShader() and registerComponent() examples are next to one another makes the distinction even murkier and less obvious. 

So in other words the one thing I'd love to see is a clearer distinction of when to use each. In that way, I think the docs reflect this ongoing discussion in that the answer to that question is not really obvious, some are doubting the actual need for "registerShader", and the whole thing is a bit up in the air...

For now I'm slightly leaning towards the "why have registerShader() to begin with when it's not fully implemented and this area relies so heavily on exposing threejs/glsl to begin with", but in terms of the docs, I think an opinionated example of when and why to use each would be a welcome clarification.

**Comment by machenmusik** [comment]
@donmccurdy thanks for heads up on the glitch error.
Duh, forgot to use `type:'time'` instead of `'number'`

**Comment by machenmusik** [comment]
@michaelhazani ok, updated with opinionated section and removed duplication. @donmccurdy that means I blew away the prior custom component examples, but hopefully you will see why... if not, we can always revert

**Comment by MichaelHazani** [comment]
Great stuff - thanks for doing all that. I think this is a huge step up and the examples are excellent and nontrivial. This is the kind of doc I'll be forwarding to beginners / onboarding devs for reference. Thank you!
