### ISSUE TITLE
Consider adding deferred and traversal / recursive application to `material` component.

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#3155]
Per Slack discussion
https://aframevr.slack.com/archives/C0GG937RN/p1507698939000005?thread_ts=1507678947.000225&cid=C0GG937RN

We may want the `material` component to act after `object3dset` or `model-loaded`, and to optionally traverse the model and its children, or apply recursively to the object hierarchy.  (Though we should consider whether to traverse into child A-frame entities then)

**Comment by donmccurdy** [comment]
I think the goals (if we do this) would be —

1. Bring the `registerShader` API closer to what component+ShaderMaterial can do.
2. Let developers use `material` on models, not just primitive shapes.

(1) is part of the discussion in #3151 and elsewhere of course.

(2) is definitely a common request, although I'm not sure how many people requesting it are familiar with UV wrapping. Applying an arbitrary material to an arbitrary model doesn't "just work", so practically what are the use cases for this?

Another concern, with (2), is that users may expect using `material="ambientOcclusionMap: foo.jpg"` would apply an AO map to their model's existing material. Merging materials seems hard in general, so I'm guessing we don't want to go that route? Using a material would entirely override any materials on the model?

> ...and to optionally traverse the model and its children, or apply recursively to the object hierarchy. (Though we should consider whether to traverse into child A-frame entities then)

I'd lean toward always traversing the model, and never the child entities. I think we could accomplish that by checking `object.el` while traversing, and not going further if it's defined.

***

Overall I'm undecided about this... My original concern, and reason for bringing this up, was about `getOrCreateObject3D` causing problems. But that can be avoided in other ways. We can continue the higher-level discussion about shaders first: this doesn't need to block #3154.

**Comment by machenmusik** [comment]
Maybe some interaction with #2408?

**Comment by ngokevin** [comment]
I think this can be done manually, not declaratively.

```
obj.traverse(node => {
  if (node.name === 'Mesh') {
    node.material = ...  // including el.components.material.material
  }
});
```
