### ISSUE TITLE
there is no way to load any gltf

### ISSUE THREAD

**Issue by nedol** [aframevr/aframe#3159]
**Description:**
%ccomponents:gltf-model:warn %cCannot read property 'color' of undefined%c  color: orange color: inherit color: orange
(anonymous function)	Uncaught (in promise) TypeError: Cannot read property 'color' of undefined

- A-Frame Version: 0.7.0
- Platform / Device:  Crome/Windows10
- Reproducible Code Snippet or URL:
<a-scene  embedded  id="scene" class="scene"
    style=" pointer-events: none; position:absolute; height:100%;  width:100%; margin: auto; top: 0;
        left: 0; right: 0; bottom: 0; z-index:2;"
    vr-mode-ui="enabled: false"  physics="debug: true" debug>
     <a-entity id="camera" class="camera" position="0 360 0"  rotation="-90 0 0">
        <a-camera  user-height="0" camera="active:true"
                  fov="30" wasd-controls-enabled="false" look-controls-enabled="false" >
         </a-camera>
    </a-entity>
    <a-entity id="kolobot" gltf-model="src: url(https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedCube/glTF/AnimatedCube.gltf);"
              rotation="-40 0 0" scale="1 1 1" position="0 0 0">
    </a-entity>
</a-scene>

**Comment by donmccurdy** [comment]
Hi @nedol — I've tested quite a lot of glTF files, it's certainly possible to do this.

Can you share your model, and ideally a demo showing the problem? Also note that A-Frame 0.7.0 supports glTF 2.0. If you have an older glTF 1.0 file, you need to use `gltf-model-legacy` from A-Frame Extras.

You may also want to check out our [troubleshooting section](https://aframe.io/docs/0.7.0/introduction/models.html#troubleshooting), and test your model with an [online viewer](https://gltf-viewer.donmccurdy.com/).

**Comment by nedol** [comment]
Hi donmccurdy. I've tested all my gltf models, and they all work fine with your online viewer. But I have a more complicated problem - I try to use aframe (v.0.7.0) as the top level layer, which is located above the openslayers map element in DOM. And in this case some 3d models (.dae, .json) work without problems, but loading the glTF 2.0 model I get an error ("Uncaught (in promise) TypeError: Cannot read property 'color' of undefined").

**Comment by nedol** [comment]
Hi @donmccurdy. I've tested all my gltf models, and they all work fine with your online viewer. But I have a more complicated problem - I try to use aframe (v.0.7.0) as the top level layer, which is located above the openslayers map element in DOM. And in this case some 3d models (.dae, .json) work without problems, but loading the glTF 2.0 model I get an error ("Uncaught (in promise) TypeError: Cannot read property 'color' of undefined").

**Comment by donmccurdy** [comment]
I don't know where to find the glTF model in that demo. It's better to test with minimal scenes, so that you can narrow down where the problem is coming from. Can you make a simpler demo to verify everything is working?

```html
<a-scene>
  <a-entity position="0 0 -4" gltf-model="my-model.gltf"></a-entity>
</a-scene>
```

Also make sure you're checking the JS console for errors, which would be important clues.

**Comment by nedol** [comment]
@donmccurdy. It seems I've  found out the source of the error - it appears when using glTF loader and webpack (import or require commands).  Needs more details?

**Comment by nedol** [comment]
@donmccurdy This is my model - https://nedol.ru/infodesk/alpha/src/ddd/kolobot.2.gltf. Now I can see the model on the map, but for unknown reason it looks translucent.

**Comment by donmccurdy** [comment]
Could you post both the file and its `.bin`? You can drag-and-drop .ZIP attachments into GitHub comments directly.

**Comment by nedol** [comment]
I use gltf 2.0 exporter for Blender with the settings that that doesn't give .bin file. This is another [example]( https://nedol.ru/infodesk/alpha/src/ddd/kolobot.flying.gltf) of model with the same problem.

**Comment by donmccurdy** [comment]
That second file looks correct to me in [this viewer](https://gltf-viewer.donmccurdy.com/) – no visible transparency.

The earlier file definitely is missing a `.bin`.

If the models appear correctly in viewers like https://gltf-viewer.donmccurdy.com/ and http://sandbox.babylonjs.com/ then something about your particular scene is introducing transparency. You'll need to reproduce the problem in a simple demo for us to help you.

**Comment by nedol** [comment]
After adding animation to blender's project I couldn't open new gltf in the viewer ('Invalid typed array length: 240'). But new .glb file it seems works fine in the viewer exept some texture problems. 
![image](https://user-images.githubusercontent.com/2842644/31652035-6d046b1a-b326-11e7-9f9b-327e2f71ab33.png).  The .glb animation doesn't work in aframe 
![image](https://user-images.githubusercontent.com/2842644/31652204-0a1a4280-b327-11e7-8614-e644c19a3713.png)

**Comment by donmccurdy** [comment]
More information about playing animation in A-Frame here: https://aframe.io/docs/0.7.0/introduction/models.html#animating-models

**Comment by nedol** [comment]
Just added a bone and made a head as a child of the bone and it spoiled the head location.
![image](https://user-images.githubusercontent.com/2842644/31858712-677f8082-b707-11e7-9d81-407b4216294a.png)
