### ISSUE TITLE
Optional (nullable) and any-type component properties

### ISSUE THREAD

**Issue by eng1neer** [aframevr/aframe#3161]
It appears that A-Frame doesn't allow to create properties that may not exist (or may have null values). For example, an integer or float value will always have a default numeric value, which may not always be appropriate. If I create a numeric property with a `{default: null}` it gets parsed as NaN. Strings with `{default: null}` work seemingly ok but issue a warning (though, inexistent string value may be designated by an empty string, this is not always appropriate).

Apparently, the problem stems from that every property type is made to be serializable to and parsable from a string. But A-Frame usage scenarios are surely not limited to creating an html with string-only attributes. `getAttribute`/`setAttribute` API allows to pass any javascript expression to aframe component properties. The aframe-react library provides a convenient way to pass javascript expressions directly from React components jsx code.

Is there a chance that A-Frame component schema will be extended to accommodate these use cases?

- A-Frame Version: 0.7.0

**Comment by dmarcos** [comment]
What is exactly your use case? Can you describe a specific scenario? You can always track internally in your component if a property has been ever set regardless of the default value.

**Comment by eng1neer** [comment]
I have several use cases. For example, I have a component that creates a carousel out of some given entities. It has a notion of a currently active element index, so it is an integer property, but it can also be a null (no active slide). I couldn't find a way to describe this in a schema without getting a warning from A-Frame. Currently, I use `{active: {default: null}}` but it gives a `core:schema:warn Default value `null` does not match type 'string' in component 'rotator'`

Another use case is for the second part of my original request. I need to pass a callback to a component: 

`<Entity camera look-controls roll-tracker={{callback: cameraRollCallback, threshold: 15}}>
...
</Entity>`

This component tracks camera roll angle and reports it back to the callback. A callback is of an object javascript type and there's no such equivalent in aframe compoenent prop types.

Surely there can be other use cases, but even in those, I find A-Frame component property type list is too restrictive to support these use cases.

**Comment by dmarcos** [comment]
For the callback use case I would emit an event from your component `rollchanged` that other entities can subscribe via `addEventListener`

For the carousel you can have a `selector` type property that references the selected entity of your carrousel

**Comment by eng1neer** [comment]
I don't need to pass the event somewhere else in an aframe ecosystem. Callback passing is an integration point with the outside world: I'm using React and Redux and the callback dispatches the Redux action. If I will emit the event to be subscribed somewhere else I will just move the problem to the other component, this will not solve the problem.

I think you miss the whole point. The point is that aframe component property types apparently are designed around the string representation of their values. And in the reality, no one will use just a string properties for an app bigger than a hello world. One will use React or Angular or anything else and this will require passing native javascript objects around to tie these two worlds. Why restrict that?

**Comment by dmarcos** [comment]
A-Frame component properties are designed to express data not logic. There are other mechanisms for that: component methods, event / listeners

**Comment by eng1neer** [comment]
Ok, what if data is a multidimensional array?

**Comment by dmarcos** [comment]
Can you describe a use case?

**Comment by eng1neer** [comment]
Thinking in the "data not logic" paradigm callback could be a design smell. I think I can subscribe to an event in a React component, this solves callback problem. Thank you for the hint.

Still, I think nullable properties and object/array data should be supported. There can be ways to overcome that, but this is the data, I don't see why restrict some forms of it.

**Comment by eng1neer** [comment]
For example, I have a component that duplicates the model in the desired positions. A column model that gets duplicated around the scene still being a single geometry to optimize a number of render calls.

The component gets passed an array of positions, this is not a permitted data type. 

Of course this is not a single use case.

**Comment by donmccurdy** [comment]
Also keep in mind that you can create your own property types by defining parser and serializers for them. You may want to try going down that path and see how it goes. For 3xN matrices that's likely best anyway. See: https://aframe.io/docs/0.7.0/core/component.html#custom-property-type

An example where I defined custom property types (although I did it differently than the documented way) here: https://github.com/donmccurdy/aframe-extras/blob/feat-state-machine/src/state-machine/transition.js#L17-L23

**Comment by eng1neer** [comment]
Custom property type is surely a solution, I somehow missed that. Thank you!

**Comment by eng1neer** [comment]
I would say that one thing that is missing is the ability to declare a custom value on a component level. I can create a custom component property type, but something like this (jsx): `instantiate-geometries={[{position: "1 0 0"}, {position: "2 0 0"}]}` is unsupported I guess.

**Comment by donmccurdy** [comment]
if you want to define a single value for the component, rather than multiple properties, you'd need to use your custom property type with a [single-property schema](https://aframe.io/docs/0.7.0/core/component.html#single-property-schema).
