### ISSUE TITLE
How do geometry sizes get updated (f.e. changing the radius attribute of a-sphere).

### ISSUE THREAD

**Issue by trusktr** [aframevr/aframe#3162]
Does it apply a scale to `Object3D.scale` based on the initial size of the mesh?  (this is just a complete guess)

I tried searching the source, but it wasn't easy to find.

**Comment by ngokevin** [comment]
It creates a new geometry since they default to Buffer geometries which can't easily be updated in-place. Geometries are cached + reused though. https://github.com/aframevr/aframe/blob/master/src/geometries/sphere.js#L18
