### ISSUE TITLE
Triangle primitive: vertexA, vertexB, vertexC, width, height attributes do not work 

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#3163]
**Description:**
It is not possible to change vertexA, vertexB, vertexC, width, height attributes of a triangle primitive. Using it with geometry works. Although triangle.js seems to be ok.

- A-Frame Version: 0.7.0
- Platform / Device: -
- Reproducible Code Snippet or URL: https://codepen.io/anon/pen/BwPgqQ

**Comment by jordanjmann1** [comment]
For some reason, it's slightly different to the geometry version.
You need to use vertex-a, vertex-b & vertex-c instead.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/a840dd6cde6ff2410e96dbce2f10228d84a6cd8c
