### ISSUE TITLE
remove newData and oldData from componentchanged event in documentation version 0.7.0

### ISSUE THREAD

**Issue by remkoboschker** [aframevr/aframe#3165]
Hi,

I think the documentation needs to be updated here https://aframe.io/docs/0.7.0/core/entity.html#event-detail 

As far as I can tell the ``newData`` and ``oldData`` properties are no longer present on the ``componentchanged`` event.

**Comment by donmccurdy** [comment]
Thanks! Docs fixed with #3167. This was a performance optimization added in #2950.

**Comment by jafetmorales** [comment]
Wait. So now to get the new data for position, for example, we do this?
evt.target.getAttribute('position')

**Comment by jafetmorales** [comment]
I updated two days ago and my code stopped working. I couldn't quickly find any documentation saying that now I have to do this: `event.target.getAttribute(event.detail.name)`. Anyways, thanks!

**Comment by ngokevin** [comment]
It'll be part of the release notes once it's released.

**Comment by machenmusik** [comment]
@ngokevin I wonder if we should add a warning message into the static evt.detail object for oldName or newName so that if this change breaks code relying on newData or oldData, and you look at the value you are getting, it tells you what you should do instead in human-readable form?

**Comment by jafetmorales** [comment]
Something along these lines maybe:
`warn('event.detail.newData is deprecated. Use event.target.getAttribute(event.detail.name) instead.');`
