### ISSUE TITLE
Scene incorrectly remains in stereo after exiting VR mode (WebVR Polyfill)

### ISSUE THREAD

**Issue by Pterko** [aframevr/aframe#3166]
**Description:**

When you exit from VR mode, the image is still stereoscopic. You can see it on attached videos.

- A-Frame Version: 0.6.0
- Platform / Device: iPhone/Safari (tested on iPhone 6 and iOS 11)
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

https://www.youtube.com/watch?v=TyEItePPoPA
https://www.youtube.com/watch?v=lk7ihgJwFQg

**Comment by cvan** [comment]
thanks for filing this. I noticed the exact same behaviour. looks like a recent regression. will fix soon - thank you!

**Comment by cvan** [comment]
see the discussions here: https://github.com/aframevr/aframe/issues/3160#issuecomment-337542073

I'll wait to hear from @NellWaliczek and @olga-microsoft on this.

p.s. thanks for the videos - they're very helpful! 👍

**Comment by dmarcos** [comment]
This is not a `0.7.0`. The problem was already present in `0.6.0` and is due to the polyfill not returning to mono mode after exiting VR

**Comment by cvan** [comment]
yep, you're right. `0.7.0` was just what I was testing with. (I didn't bisect it back to see when it first regressed.)

on `0.6.0`:

<img src="https://user-images.githubusercontent.com/203725/31803653-d7bf8784-b509-11e7-8579-50436f158b45.jpeg" width="500">

**Comment by dmarcos** [comment]
This does not reproduce anymore in A-Frame 0.8.2. Tested on iPhone X. Please open a new issue if you’re still affected.
