### ISSUE TITLE
Apply shader on final image

### ISSUE THREAD

**Issue by RangerMauve** [aframevr/aframe#317]
I'm planning on making a psychedelic game and one of the things I want to do is apply trippy filters on the entire screen when certain things happen. It'd be nice if there was a way to specify a fragment shader that would be applied on the final buffer before rendering it to the screen. Maybe it'd make sense to attach it to a camera?

**Comment by dmarcos** [comment]
Custom shaders are coming soon. Top in the features list.

**Comment by RangerMauve** [comment]
Awesome! Can't wait. Any clues as to what variables will be present? Or will it all be user defined. I think that having similar variables to shadertoy will improve the hackability

**Comment by ngokevin** [comment]
We have work tracking at https://github.com/aframevr/aframe/pull/861 and we will iterate on it over time. We are using shadertoy as inspiration.

For applying a shader to the entire scene, maybe try making a component that hooks into the renderer?
