### ISSUE TITLE
With 2 raycasters in scene, raycaster line does not shorten on intersection

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#3170]
**Description:** Shared closure objects between raycaster instances cause line end ~calculations~ assignments to malfunction

- A-Frame Version: Master (0ac2977)
- Platform / Device: Desktop FF/Chrome. Mobile Chrome
- Reproducible Code Snippet or URL: https://green-nitrogen.glitch.me/

This is occurring post #3127

**Comment by wmurphyrd** [comment]
I fixed similar issues in `super-hands` by changing the persistent setter objects (i.e. `lineEndVec3` and `otherLineEndVec3` in this case) to be component instance variables allocated in `init` rather than closure members. If that's how you want to address this, I'll be happy to do the PR

**Comment by ngokevin** [comment]
Yeah please do!

**Comment by ngokevin** [comment]
@wmurphyrd Still up for the PR? Should be a quick one.

**Comment by wmurphyrd** [comment]
Yes I just start on this yesterday. I'm having trouble replicating the
issue in a unit test. Would you accept this fix without a test?

**Comment by wmurphyrd** [comment]
Got the test working. Nevermind the above comment
