### ISSUE TITLE
How to reuse a ply model with mixin

### ISSUE THREAD

**Issue by alchemz** [aframevr/aframe#3172]
**Description:**
	<a-scene>
	<a-assets>
		<a-mixin id="corn" 
			geometry="primitive: box; height:1; width:1; depth:1"
			material="shader: standard"></a-mixin>
		<a-asset-item id="corn-ply" src="plants/corn.ply"></a-asset-item>

	</a-assets>
	<a-entity mixin="corn" material="src: #corn-ply"></a-entity>
	</a-scene>

- A-Frame Version: 0.7.0
- Platform / Device: Firefox
- Reproducible Code Snippet or URL:

The documentation for how to use the primitives like box, sphere, cylinder is very clear. But what if I want to reuse the ply model created by magica voxel? Can i do that with mixin?

**Comment by donmccurdy** [comment]
The PLY model is not a material — to load it you would need to use the `ply-model` component from [aframe-extras](https://github.com/donmccurdy/aframe-extras/tree/master/src/loaders). Any components attached to a mixin are reused (not just material and geometry).

However, that mixins are just a convenience feature — there's no performance benefit from reusing a model in this way.

**Comment by ngokevin** [comment]
Yup, use the `ply-model` component instead and should work.

**Comment by alchemz** [comment]
Ok. Thanks for the reply, but what I really want to do is to spawn a ply-model. I have been looking into this [aincraft ](https://github.com/ngokevin/kframe/blob/master/scenes/aincraft/components/intersection-spawn.js)example done by kevin. And for the intersection-spawn.js script, it uses mixin, and I do not know how to modify it to spawn ply-model.
