### ISSUE TITLE
Change examples to use `preload="true"`

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#3174]
See https://github.com/aframevr/aframe/blob/master/src/core/a-assets.js#L138 and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Attributes

`preload="true"` should be changed to `preload="auto"` (or `preload="metadata"` or `preload="none"`) in all the `<video>`s in the [Examples](https://github.com/aframevr/aframe/tree/master/examples).

Example URL where `preload="true"` is used on a `<video>`: https://aframe.io/aframe/examples/test/videosphere/

Examples:
- https://github.com/aframevr/aframe/blob/master/examples/boilerplate/360-video/index.html
- https://github.com/aframevr/aframe/blob/master/examples/test/video/index.html
- https://github.com/aframevr/aframe/blob/master/examples/test/videosphere/index.html

/cc @machenmusik

<hr>

Related issue: https://github.com/aframevr/aframe/issues/3173#issuecomment-337191996

**Comment by NameIsSoDiao** [comment]
ios11 Can not play VR video, .m3u8

**Comment by machenmusik** [comment]
Yes, there appears to be a regression in iOS 11 Safari behavior unfortunately, see discussion here: https://github.com/aframevr/aframe/pull/2830#issuecomment-338946580

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/blob/master/examples/test/video/index.html#L12
