### ISSUE TITLE
v0.7.0 in npm shows three.js r86?

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#3177]
Reported by a dev in Slack: In https://unpkg.com/aframe@0.7.0/dist/aframe-master.js, search for "REVISION" and it's still 86... on the other hand looking at https://unpkg.com/three@0.87.1/build/three.js i see r87. Something off with the npm build, perhaps?

**Comment by cvan** [comment]
@ngokevin would know best. But is it possible that a-frobot is on npm5 and is using a local `package-lock.json` which was pinned to `three@0.86.0`. Hmm… very odd indeed.

**Comment by cvan** [comment]
If I had to guess, from looking at 61fb844, aa76fb0, and 861b95, it seems the the dist was manually created from a local environment. If I had to guess, @dmarcos may have a `package-lock.json` locally, and `three.js` wasn't updated because `npm install` wasn't called in between those commits. That's just my theory right now. Could be totally off here…

**Comment by dmarcos** [comment]
I replied to the person affected on Slack. There was indeed a problem when those builds were generated. I recommend using the official release channel: https://aframe.io/releases/0.7.0/aframe.js Everything should be fine there. We can cut a 0.7.1 if there's more people affected.

**Comment by donmccurdy** [comment]
Hm I don't especially like the idea that a CDN is our official release channel and npm is somehow not recommended... this seems worth a patch release I would say, if we think we know what happened?

**Comment by dmarcos** [comment]
I believe what happened was my mistake. I probably run `npm publish` without updating the `package.json` to `THREE` to `r87`. I can cut a `0.7.1` later today.

**Comment by dmarcos** [comment]
I know what happened now. When I did `npm publish` for `0.7.0` I had a development branch using THREE r86 and when going back to master to publish the package I forgot to run `npm install` to update the dependencies.

**Comment by donmccurdy** [comment]
Ah that makes sense. We could add that to the `npm run prerelease` script just to be safe.

**Comment by cvan** [comment]
@donmccurdy: I think this command would work:

```sh
"(shx for pkg in `ls node_modules`; do npm uninstall $pkg; done) && npm install && ... "
```

Think that would handle the links too. Or something like that.

**Comment by dmarcos** [comment]
`0.7.1` is out. Both the CDN and npm builds should now contain THREE `r87`. Sorry for the inconvenience.
https://aframe.io/releases/0.7.1/aframe.js 
https://unpkg.com/aframe@0.7.1/dist/aframe-master.js

**Comment by donmccurdy** [comment]
Great, thanks!
