### ISSUE TITLE
Add utility for printing the three.js scene graph?

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#3178]
I suggested this at https://github.com/mrdoob/three.js/issues/10961 a while back, and it was decided that it didn't need to be in three.js core. I still find myself using those scripts a lot, and so wondering if we want to consider adding it here instead, either as part of the core library or the inspector?

The idea would be a utility function like: `AFRAME.logSceneGraph( el )` that will show the whole THREE.Scene hierarchy, not just the tree of entities.  For example output open the console on this page: https://gltf-viewer.donmccurdy.com/#model=https://vatelier.net/MyDemo/IMAL-BlenderSummer2017/Ex3Animation.gltf

Have used this to debug performance sometimes. User may have a model with hundreds or thousands of THREE.Object3Ds nested inside, and that wouldn't be obvious from the DOM, although this costs a lot of CPU time computing matrixWorld and such.

**Comment by ngokevin** [comment]
What about the three.js Inspector add-on?

**Comment by dmarcos** [comment]
What about a special view in the A-Frame inspector? A good use case for a plugin API?

**Comment by donmccurdy** [comment]
the three.js inspector Chrome Extension is unfortunately not so helpful for this:

| three.js inspector extension | actual tree |
|---|---|
| <img width="300" alt="screen shot 2017-10-18 at 11 16 42 am" src="https://user-images.githubusercontent.com/1848368/31735162-e2e8c568-b3f5-11e7-8367-0d1808dd6260.png"> | <img width="244" alt="screen shot 2017-10-18 at 11 17 29 am" src="https://user-images.githubusercontent.com/1848368/31735193-ff479874-b3f5-11e7-9c30-e42c741dd122.png"> |

See: https://github.com/jeromeetienne/threejs-inspector/issues/24

Fixing the chrome extension would help, or an inspector plugin would be a good option too if @fernandojsg is comfortable with the idea of allowing plugins.

**Comment by dmarcos** [comment]
This is a cool feature but not sure how much concern the core. Should we move this to the inspector repo?

**Comment by donmccurdy** [comment]
That would be fine I think, yes.
