### ISSUE TITLE
Play video from a video tag ID

### ISSUE THREAD

**Issue by RangerMauve** [aframevr/aframe#318]
It'd be cool if we could point to an arbitrary video tag in the markup for video playback. The specific use case would be for when you use `getUserMedia` or WebRTC to get video feeds. Currently only urls are supported from what I understand, but I think that supporting arbitrary video tags will let people make even cooler things.

**Comment by dmarcos** [comment]
You can pass a selector as ```src``` parameter of the material. Example:
https://github.com/aframevr/aframe-core/blob/dev/examples/video/index.html#L19

**Comment by RangerMauve** [comment]
Thanks for the pointer, didn't notice that. Does it handle the video changing content over time properly? For example if the `src` changed or if a MediaStream got attached?

**Comment by dmarcos** [comment]
Yes. I think it should just work.

**Comment by RangerMauve** [comment]
Cool! I'll play around with it when I get the chance. Thanks!
