### ISSUE TITLE
fast-tracking setAttribute('position'/'rotation'/'scale') 

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3183]
**Description:**

Updating position, rotation, scale are the most frequent operations. Done each tick on the camera position/rotation, controllers position/rotation, and any moving object. In many cases if I don't need to keep the position/rotation/scale data updated on the A-Frame level, I just skip A-Frame and directly do things in three.js (`object3D.position.set` has no overhead).

The overhead in A-Frame involves parsing (if it has to), running `buildData`, doing `utils.deepEqual`, and managing the `oldData` object.

For position, rotation, scale, there are many things we don't really care about (mixing properties with default data, checking mixins, keeping track of `oldData`, doing a `deepEqual`). 
 just want to take the position/rotation/scale, set it directly on the `object3D`, and update `this.data`.

Perhaps we special-case the code path for position/rotation/scale in `component.js` and give it a shortcut. It's special-casing, but position/rotation/scale are frequent and important enough. We should be able to shave some time off each frame.

### Other Benefits

We don't have to worry about skip type checking and parsing, we just always skip type checking and parsing for objects. And now this will work due to not running the `utils.deepEqual` check:

```js
pos = el.getAttribute('position');
pos.x += 5;
el.setAttribute(pos);
```

Perhaps will improve things like @donmccurdy's scene he mentioned something with tons of moving physics objects. We can use that as benchmark.

**Comment by donmccurdy** [comment]
Thanks for writing this up! I'll post the scene for benchmarking.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/3245
