### ISSUE TITLE
Removing attributes doesn't update component

### ISSUE THREAD

**Issue by vasturiano** [aframevr/aframe#3187]
This may well be me misunderstanding something, but it seems that from version 0.6 onwards, removing an `a-entity`'s attribute does not cause a component update. Its internal data caches the previous set value. I believe previous versions fell back to the default value if an attribute was removed. 
This makes it difficult to manage dynamic state components with optional props. Unless there is another way to signal/detect that change to the component?

This codepen highlights the example: https://codepen.io/vasturiano/pen/pWBXJa

`v0.7.1`:
```
(Initialize) undefined -> 0
(Setting prop=1) 0 -> 1
(Remove prop) 1 -> 1
(Setting prop=1) 1 -> 1
(Remove prop) 1 -> 1
(Setting prop=2) 1 -> 2
```

`v0.5.0`:
```
(Initialize) undefined -> 0
(Setting prop=1) 0 -> 1
(Remove prop) 1 -> 0
(Setting prop=1) 0 -> 1
(Remove prop) 1 -> 0
(Setting prop=2) 0 -> 2
```

- A-Frame Version: 0.6.0 and up
- Platform / Device: Chrome
- Reproducible Code Snippet or URL: https://codepen.io/vasturiano/pen/pWBXJa

**Comment by ngokevin** [comment]
Setting another property does not remove other properties. Use the clobber flag if you want to wipe other properties, https://aframe.io/docs/0.7.0/core/entity.html#setattribute-componentname-value-propertyvalue-clobber, or do `removeAttribute(componentName, property)`
