### ISSUE TITLE
hand-controls component with laser-controls has wrong model

### ISSUE THREAD

**Issue by jayber** [aframevr/aframe#3188]
- A-Frame Version: 0.7.0
- Platform / Device: Windows 10, Firefox 56 (64 bit), Oculus HMD and Oculus Touch Controllers
- Reproducible Code Snippet or URL: see attached file - index.txt

In 0.7.0 (this does not happen in 0.6.1) if an a-entity has a hand-controls component AND a laser-controls component then the Oculus touch model is displayed instead of the hand model.
[index.txt](https://github.com/aframevr/aframe/files/1406944/index.txt)

[Incidentally I originally created this example with the angle tool. However that is still generating files using version 0.6.1]

**Comment by ngokevin** [comment]
They're not to be used together. One is for 6DoF, one is for 3DoF, both prescribing models. If you want a line from the hand, set `cursor` ([these properties](https://github.com/aframevr/aframe/blob/v0.7.0/src/components/laser-controls.js#L67) and `raycaster="showLine: true"` (see laser-controls code for reference). Or copy/paste laser-controls to change the model to the hand.
