### ISSUE TITLE
Failed npm dist on ubuntu 14.04

### ISSUE THREAD

**Issue by cemkod** [aframevr/aframe#319]
Running npm run dist generated 0 byte files for dist/aframe.js and dist/aframe.min.js

While trying to debug the issue I found multiple problems with this line :
```
mkdir -p dist/ && npm run browserify -s -- --debug | exorcist dist/aframe.js.map > dist/aframe.js && uglifyjs dist/aframe.js -c warnings=false -m -o dist/aframe.min.js
```

```
npm run browserify  -s -- --debug
```
This command above runs and exits with exit code 0, but doesn't print anything to STDOUT

but this does print the browserified file:
```
npm run browserify  -s
```

Any ideas?

**Comment by mattdesl** [comment]
@cemkod What happens when you run this?

```sh
npm run browserify -- --debug
```

Also, what versions of npm and node are you on?

```sh
node -v
npm -v
```

@cvan What does the empty `-s` option do in this case? It looks like a typo that shouldn't be there?

**Comment by cemkod** [comment]
@mattdesl 

```
npm run browserify -- --debug
```
No output, exit code 0

node v0.10.25
npm 1.3.10

**Comment by mattdesl** [comment]
You need `npm@2.0` or higher for the `--` feature to work. Might be worth documenting in the AFrame readme.

https://docs.npmjs.com/cli/run-script#description

You can do something like this to install a newer version:

```sh
# latest version
sudo npm install npm@3.x -g

# or, v2 is also pretty good
sudo npm install npm@2.x -g
```

**Comment by cvan** [comment]
ah, I added the `npm` and `node` versions required in `aframe-core`'s [`package.json`](https://github.com/aframevr/aframe-core/blob/master/package.json#L80-L83), but I forgot to do it here for `aframe` proper's. will do. thanks, @mattdesl, @cemkod!

**Comment by cemkod** [comment]
Fixed! Thank you @mattdesl, @cvan
