### ISSUE TITLE
ios <a-videosphere>

### ISSUE THREAD

**Issue by NameIsSoDiao** [aframevr/aframe#3192]
Can not play video, only sound no video，why？

**Comment by NameIsSoDiao** [comment]
`<a-scene id="scene" vr-mode-ui="enabled: true">
		<a-assets>
			<video crossorigin="anonymous" id="v" webkit-playsinline="true" playsinline="true" autoplay="true" loop="true" src="07.m3u8" type="application/x-mpegurl"></video>
		</a-assets>
		<a-videosphere id="videosphere" ios10hls rotation="0 -90 0" src="#v" visible="true" autoplay="true" loop="true"></a-videosphere>
		<a-camera mouse-cursor wasd-controls-enabled="false">
		</a-camera>
	</a-scene>
<h1 id="touch">PLAY</h1>
	<script>
		// function isIOS() {
		// 	return /iPad|iPhone|iPod/.test(window.navigator.platform);
		// }
		window.addEventListener("load", function () {
			var video = document.getElementById('v')
			var touch = document.getElementById("touch")
			touch.addEventListener("click", function () {
				if (video.paused) {
					video.play()
				} else {
					// video.pause()
				}
			})
			// alert("is IOS"+isIOS())
		})
	</script>`

**Comment by NameIsSoDiao** [comment]
`	<a-scene id="scene" vr-mode-ui="enabled: true">
		<a-assets>
			<video crossorigin="anonymous" id="v" webkit-playsinline="true" playsinline="true" autoplay="true" loop="true" src="07.m3u8" type="application/x-mpegurl"></video>
		</a-assets>
		<a-videosphere id="videosphere" ios10hls rotation="0 -90 0" src="#v" visible="true" autoplay="true" loop="true"></a-videosphere>
		<a-camera mouse-cursor wasd-controls-enabled="false">
		</a-camera>
	</a-scene>`

**Comment by NameIsSoDiao** [comment]
Is there a cross-domain reason?

**Comment by ngokevin** [comment]
https://aframe.io/docs/0.7.0/introduction/faq.html#why-does-my-video-not-play-on-mobile

**Comment by NameIsSoDiao** [comment]
thank you very much，but ios11 Still can not play

**Comment by Hiphone-Du** [comment]
@ngokevin  ios11 Still can not play VR video too ，no matter which format

**Comment by Hiphone-Du** [comment]
i have solve the problem by creating a button to play

**Comment by AntonioScapellato** [comment]
@Hiphone-Du  I'm using a button to play too, but it  is still not working..
