### ISSUE TITLE
GLTF loader failure

### ISSUE THREAD

**Issue by twastvedt** [aframevr/aframe#3204]
**Description:**

- A-Frame Version: 0.7.0
- Platform / Device: Firefox 56.0.2, Windows 7
- Reproducible Code Snippet or URL: https://aframe-gltf-loading.glitch.me/

I'm sure I'm missing something, but I'm seeing something strange happen. In the glitch project linked above, the gltf model fails to load and the `a-assets` event `loaded` fires. However, if I change the `a-asset-item` tag to `a-asset`, the model loads and displays just fine, but the `a-assets` event `loaded` never fires.

To be clear, based on the documentation I would expect to be able to use the `a-asset-item` tag and have the `a-assets` event `loaded` fire after the page has loaded the model.

Thanks!

**Comment by dmarcos** [comment]
The `loaded` event fires when the file loads over the network not when your model renders

**Comment by dmarcos** [comment]
You’re probably attaching an event handler after the model has loaded and the event has already fired

**Comment by donmccurdy** [comment]
If you're specifically waiting on this model to load, the best option is waiting for a `model-loaded` event on the entity itself (not the asset item).

**Comment by donmccurdy** [comment]
Other problem here – the `.glb` asset is coming into the loader as a string, when it should be an ArrayBuffer. This can be fixed with:

```html
<a-asset-item response-type="arraybuffer" src="my_model.glb"></a-asset-item>
```

See https://github.com/aframevr/aframe/issues/2649. Offhand I can't think of a way to have that happen automatically (there is no file extension in Glitch, for starters) but maybe we could mention it in the `gltf-model` docs.

**Comment by twastvedt** [comment]
Thanks both for the fast replies! Good to know about the `response-type="arraybuffer"` bit. That solves this, and makes everything behave as I expected. It doesn't appear to matter what the tag name of the glb asset file is. I suppose that's known, though it was news to me.

**Comment by twastvedt** [comment]
Nevermind about `a-asset-item` working with any tag name. The model does load just fine with a different tag name (e.g. `<asdf-item>`), but the `loaded` event then never fires on `<a-assets>`.
