### ISSUE TITLE
Cursor event only trigerred after opening aframe inspector

### ISSUE THREAD

**Issue by tiagoernst** [aframevr/aframe#3208]
I've added a click and mouseenter listener on my cursor but it seems to only work after i open the aframe inspector ( ctrl + alt + i ), it also works using my mouse instead of the cursor (but then not compatible with phone or VR glases) .Any ideas why this could be happening ?

**Comment by marius-link** [comment]
I am facing the same problem. Did you find a fix for this? I noticed that with primitives it will work. Objects with custom models will have their size not matching the object size. This will cause the raycaster to not register the clicks. Try using the "geometry='primivitve: box'" on your custom model and you'll notice a tiny box on loading the scene. After opening the inspector it seems like it recalculates the width and height of the objects so the raycaster intersects properly with the objects.

**Comment by tiagoernst** [comment]
Thank you it worked ! I hope they get the problem fixed

**Comment by dmarcos** [comment]
Can you add a working example that reproduces the problem?

**Comment by tiagoernst** [comment]
Sure. 
Here is the code i use for the cursor (when the users on mobile)
cursor.setAttribute('id', 'cursor');
cursor.setAttribute('fuse', 'true');
cursor.setAttribute('fuseTimeout', '500');
camera.appendChild(cursor);	
cursor.setAttribute('raycaster','objects: .collidable');

and then the only thing i do is i create an a-obj-model tag that uses a .obj file to "render" ( not sure for the use of the word) like : 
-var b=document.createElement('a-obj-model');
b.setAttribute('class','collidable');
b.setAttribute ('src','media/pininfo.obj'); //src of my 3D object
// then i added it to the scenes (there are others attributes I set like scale, position, rotation, look-at and maybe some others). And also click event (that trigers with the fuse time out) 
The funny things is i just put an invisble cube in front of one my 3D obj to do the first interaction (with the click event) and then all 3D objects seem to work normally (there is maximum 10 3D obj in average in my scene). Hope it helps !

**Comment by dmarcos** [comment]
Sorry, I meant... Can you share a link to a working example that can be easily run? A glitch or a page hosted on gh-pages will do.

**Comment by tiagoernst** [comment]
Ah sorry i'm affraid i can't

**Comment by HistoriskAtlas** [comment]
I had the same problem and spend the last two days finding out what is going on. It seems that the internal array of the objects the raycaster tries to intersect with only gets populated once on startup. After that, the custom models are loaded, but the internal array of the raycaster does not get updated. My solution was to call raycaster.refreshObjects() AFTER the models had loaded.

**Comment by syntax42** [comment]
I had the same problem and spend the last two days finding out what is going on. It seems that the internal array of the objects the raycaster tries to intersect with only gets populated once on startup. After that, the custom models are loaded, but the internal array of the raycaster does not get updated. My solution was to call raycaster.refreshObjects() AFTER the models had loaded.

**Comment by ngokevin** [comment]
This should automatically be handled on A-Frame master build: https://rawgit.com/aframevr/aframe/3035117/dist/aframe-master.min.js
