### ISSUE TITLE
A-Video and mp4 videos, black appearing briefly in loop mode right before restarting and also briefly after activating first play

### ISSUE THREAD

**Issue by javismiles** [aframevr/aframe#3209]
Using latest versions of A-Frame on Android Mobile and iPhone iOS 11

Im using a-frame and a-video with videos in webm and mp4 formats, android and iphone.
With webm all good. With mp4 all good in both platforms also except for one thing that is causing me trouble. When I put the video in loop mode, loop is true, then when the video arrives to the end, and before restarting, the video texture goes black, black rectangle for like 1 frame and then restarts again from the beginning normally. Also when the video gets activated for the first time following the click on a button by a user, again for like half a second the video appears like a black rectangle and then starts playing well and normally. 

What happens when playing the video the first time I can understand as maybe after the button click the video is still loading and that´s why it appears black for half a second. If that´s the case how can prevent the video to show until it is fully loaded?

But the second  case I don´t understand. When the mp4 is set to loop, between end of video and beginning again, it  appears black for a frame or so. Why is that happening and how can I prevent it?
By the way I have noticed that these issues seem to happen more with the iphones than the android, although it happens in both. Thank you for any help

`  <a-video class="video" material="shader: chromakey; src: #video; color: 0 0 1" webkit-playsinline playsinline width=1 height=1 position="0 0 0" rotation="0 0 2" autoplay="true" loop="true"></a-video>`

**Comment by ngokevin** [comment]
What three.js does is just simply copy the frame from the video. So if there's a black screen, it's from the browser. I think what you can do to workaround is find out when the video is just about to end, and then reset it manually to the beginning.

Something like: 

`if (video.currentTime >= TIME_WHERE_VIDEO_ALMOST_ENDS) { video.currentTime = 0; }`
