### ISSUE TITLE
document how to disable default lights on dynamically inserted scenes

### ISSUE THREAD

**Issue by bitonic** [aframevr/aframe#3211]
**Description:**

I could not find a reliable way to reliably disable default lights on an `a-scene` which is inserted from JavaScript rather than already present in the HTML. The closest I could get is https://glitch.com/edit/#!/substantial-latex?path=index.html:14:0 , and that does not seem to work on Chrome.

- A-Frame Version: 0.7.0
- Platform / Device: Linux, Firefox developer edition and Chrome 61
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/substantial-latex?path=index.html:14:0

**Comment by donmccurdy** [comment]
From docs on the [`light` component and system](https://aframe.io/docs/0.7.0/components/light.html), you're looking for:

```html
<a-scene light="defaultLightsEnabled: false">
  <!-- ... -->
</a-scene>
```

**Comment by bitonic** [comment]
That does not work for dynamically inserted elements, which is why I opened this ticket. It only works for elements which are already in the HTML.

**Comment by donmccurdy** [comment]
Hm I see. I would have expected this to work...

```js
var scene = document.createElement("a-scene");
scene.setAttribute('light', 'defaultLightsEnabled:false');
scene.setAttribute('data-foo', 'bar');
document.body.appendChild(scene);
```

... but it does not. Only the `data-foo` attribute remains after initialization.

**Comment by JP-Dorman** [comment]
"Whenever we add any lights, A-Frame removes the default lights from the scene." - Could you add your own ambient and directional lights with intensity 0 by default, then in JS remove them on page load?
