### ISSUE TITLE
Unable to manually set rotation of camera on mobile devices

### ISSUE THREAD

**Issue by Lefortov** [aframevr/aframe#3216]
**Description:**

- A-Frame Version: 0.7.0, 0.7.1
- Platform / Device: Android 8, Nexus 6P, Iphone 6s+
- Reproducible Code Snippet or URL:

When you try to manually set rotation on camera it works fine on desktop, but has no affect on mobile devices, e.g.:
`  camera.setAttribute('rotation', {x:0, y:0, z:0});` wouldn't work

**Comment by dmarcos** [comment]
The motion of the device / head takes precedence. I would not recommend rotating the camera and let the user have control of it. If you need to rotate you can create a a parent entity and change the rotation there but as a heads up it's not easy to compose rotations and get predictable results. Another option is setting look-controls to disable `cameraEl.setAttribute('look-controls', 'enabled', false);` and then you have full control of it.

**Comment by Lefortov** [comment]
@dmarcos
Thank you, i know that it is bad practice to manually set rotation, but i make it when user does not see anything and seems that is the only possible way in my situation. The idea is to make it possible for user to look at the object closer in special scene and communicate with it using rotation controls. So when user entering this scene his camera should be rotated straight  on the object despite in what direction he was looking before. So this is workflow for interaction: User goes throw scene A -> User clicks on object -> Scene switching animation starts -> User and object got moved to some specific place (scene B) -> Camera rotations sets straight to new object position -> animation ends, user is watching closely on the object.
The problem is that even if I use `cameraEl.setAttribute('look-controls', 'enabled', false);` and the user moves a phone just a little bit camera rotation would be set to its previous rotation from scene A. I think that's because our device is still physically in position looking on object in scene A. Maybe there are some ways to reset initial gyroscope values? So after switching to scene B '0 0 0' values for gyroscope would be set for physical position in which the phone is.

**Comment by ngokevin** [comment]
Answered:

https://stackoverflow.com/questions/43576222/is-there-a-way-to-recenter-reset-orientation
https://stackoverflow.com/questions/47086432/a-frame-threejs-reset-gyroscope
