### ISSUE TITLE
gearvr controller not working with component

### ISSUE THREAD

**Issue by Marchhill** [aframevr/aframe#3225]
**Description:**

- A-Frame Version: 0.7.1
- Platform / Device: Samsung S7 gearvr with Oculus VR browser
- Reproducible Code Snippet or URL:

```
<html>
  <head>
    <title>Test Area!</title>
    <script src="https://aframe.io/releases/0.7.1/aframe.min.js"></script>
    <script>
        AFRAME.registerComponent('test', {
          schema: {},
          init: function () {
              var el = this.el;

              el.addEventListener("trackpaddown", function() {
                  document.getElementById("floor").setAttribute("color", "#"+((1<<24)*Math.random()|0).toString(16));
              });
          }
        });
    </script>
  </head>
  <body>
    <a-scene>
        <a-plane id="floor" rotation="-90 0 0" width="100" height="100" color="blue"></a-plane>
        <a-entity gearvr-controls test></a-entity>
    </a-scene>
  </body>
</html>
```

When I try to run this test snippet, the gearvr controller model does not show up and the 'trackpaddown' event is not being fired, I have tried this with multiple aframe versions but to no avail. I have posted this as an issue rather than a support question because [this](https://chenzlabs.github.io/gearvr-controls/) example (that the gearvr component came from) does not seem to work either.

**Comment by dmarcos** [comment]
It is a known regression on the Oculus Browser and Samsung Internet. More info here: https://github.com/aframevr/aframe/issues/2844#issuecomment-340829968
