### ISSUE TITLE
A-frame & Samsung note 3

### ISSUE THREAD

**Issue by mre30** [aframevr/aframe#3226]
**Description:**

- Latest version of A-frame
- Android

After some testing, i found the issue which i am getting when i try to use [I Am cardboard headset](https://www.imcardboard.com/cardboard-vr-v2-box-132.html) with [Samsung Note 3](https://www.gsmarena.com/samsung_galaxy_note_3-5665.php) .

The problem is that objects are duplicated, while it perfectly works with other devices having screen size under 5.7 in.

Any suggestions?

Thanks

**Comment by dmarcos** [comment]
@mre30 Do the `webvr-polyfill` examples work for you? http://googlevr.github.io/webvr-polyfill/examples/basic/

**Comment by ngokevin** [comment]
needs more info
