### ISSUE TITLE
PNG texture background of DAE/OBJ model is white

### ISSUE THREAD

**Issue by artemistint** [aframevr/aframe#3234]
When .dae / .obj / .json models used, the PNG textures transparency applied on those models is not presented, as in other viewers. 

![23600625_10155738955087092_470787031_o](https://user-images.githubusercontent.com/32671100/32894400-6318679c-cae5-11e7-8371-302cf5d53bc9.png)

- A-Frame Version: 0.7.1
- Platform / Device: Mac
- Model URL(.dae) with transparency: [Model.zip](https://github.com/aframevr/aframe/files/1479760/Model.zip)
- Reproducible Code Snippet or URL: 

<a-scene>
        <a-assets>
          <a-asset-item id="cave" src="assets/cave_main.dae"></a-asset-item>
          <a-asset-item id="foliage-obj" src="assets/untitled-scene.obj"></a-asset-item>
          <a-asset-item id="foliage-mtl" src="assets/untitled-scene.mtl"></a-asset-item>
        </a-assets>

         <a-entity collada-model="#cave" rotation="0 180 0"></a-entity>
         <a-entity obj-model="obj: #foliage-obj; mtl: #foliage-mtl" rotation="0 180 0" material="transparent: true"></a-entity>

**Comment by donmccurdy** [comment]
@artemistint the link isn't working for me, could you share the original DAE model? Note that GitHub lets you drag-and-drop ZIP files into comments.

**Comment by artemistint** [comment]
@donmccurdy Done

**Comment by donmccurdy** [comment]
@artemistint I'm not sure why the COLLADA file isn't getting transparency applied correctly. That may be an underlying issue in THREE.COLLADALoader, but when I load the DAE file in Blender I don't see transparency there either. I don't know enough about COLLADA to say if the file is correct or not.

I'd recommend trying glTF instead. You can convert the file using Blender, and apply an alpha mask there. I used a PBR cycles node like this:

![screen shot 2017-11-16 at 11 23 29 am](https://user-images.githubusercontent.com/1848368/32911308-a43c1612-cac0-11e7-9539-350c937a865e.png)

^Note that AlphaCutoff must be `0`.

After exporting, everything looks correct on https://gltf-viewer.donmccurdy.com/ —

![screen shot 2017-11-16 at 11 21 21 am](https://user-images.githubusercontent.com/1848368/32911323-b03752f6-cac0-11e7-95a8-d84c1bfee6f5.png)

Here are the final `.blend` and `.gltf` files:

[cave-deco.zip](https://github.com/aframevr/aframe/files/1479913/cave-deco.zip)

**Comment by ngokevin** [comment]
DAE removed, use GLTF ^
