### ISSUE TITLE
aframe.min.js causing src images to download twice and not letting the browser render the image until both images are downloaded

### ISSUE THREAD

**Issue by ugoel** [aframevr/aframe#3235]
**Description:**
a-frame elements with src attribute are download twice. The devTools show that the two requests are initiated by src-loader.js:102 and three.js:30486. This occurs with aframe.min.js versions 0.7.0 and 0.7.1

- A-Frame Version: 0.7.0 and 0.7.1
- Platform / Device: OSX El Capitan using Chrome 62, Firefox Quantum 57, and Opera 48 browsers
- Reproducible Code Snippet or URL: If you open https://www.utkarshgoel.in/webvr/test1.html or https://www.utkarshgoel.in/webvr/test.html and check the resources requested by the browser in the network tab in devTools, you will see that images PIA15482.jpg and earth_atmos_4096.jpg are requested twice. Further, if you observe the page load process closely, you will onserve that the image doesn't display until both requests for that image are completed.

From the chrome devTools, it appears that for the second request, the browser or the code is adding an "origin" header in the request, which is making the browser believe that the second request is different from the first one.

I'd appreciate if someone can investigate as to why aframe.min.js is causing two requests. Thanks

**Comment by dmarcos** [comment]
@ugoel I recommend adding your images to `a-assets` https://aframe.io/docs/0.7.0/core/asset-management-system.html

**Comment by ngokevin** [comment]
That. And also, three.js merged my patch for batching duplicate requests, so once we update three.js, it won't be any issue.

**Comment by ugoel** [comment]
@dmarcos @ngokevin : I tried using a-assets and the browser did not make two requests.  This works for img and video assets, but not for audio. Can you suggest how to prevent loading audio files twice?
