### ISSUE TITLE
Umlauts, euro symbol in a-text not showing

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#3240]
**Description:**
Umlauts are not rendered when used in an a-text.

- A-Frame Version: 0.7.1
- Platform / Device: -
- Reproducible Code Snippet or URL: https://codepen.io/anon/pen/eeebNx

**Comment by dmarcos** [comment]
The default fonts do not include special symbols. You can access additional fonts here: https://github.com/etiennepinchon/aframe-fonts
