### ISSUE TITLE
a-camera changed rotation by Vue data-binding method is not working

### ISSUE THREAD

**Issue by jason90929** [aframevr/aframe#3246]
v0.7.1
As title, if I use ```camera.setAttribute('rotation', '0 180 0')```, it changed and successfully triggered componentchanged event; But in case that I change by ```<a-camera :rotation="`${x} ${y} ${z}"></a-camera>```, it won't happen trigger anything. I remember it worked with v0.5.0. Could it possible fixed?

**Comment by dmarcos** [comment]
@jason90929 Can you share a working example with `0.5.0` and the broken one with `0.7.1`?

**Comment by ngokevin** [comment]
look-controls is overriding the rotation. Use wrapper entity instead.

Would not tie camera rotation to Vue, that's big overhead for something that needs to update rapidly. Will close as this is more Vue side than what A-Frame can do.
