### ISSUE TITLE
is line support width or radius?

### ISSUE THREAD

**Issue by dante11223344** [aframevr/aframe#3247]
How to change line width or radius??

a-entity line="start:0 0 -5; end: 5 0 -5; color:#fff;radius:1"

not working ..

thanks

**Comment by ngokevin** [comment]
Does not support radius. Use a cylinder instead.

**Comment by donmccurdy** [comment]
there is also an `<a-tube/>` primitive in aframe-extras if that helps: https://github.com/donmccurdy/aframe-extras/tree/master/src/primitives#usage

**Comment by donmccurdy** [comment]
or aframe meshline as long as i'm here 😅 https://github.com/andreasplesch/aframe-meshline-component
