### ISSUE TITLE
raycaster intersection/intersected get emitted every tick despite the intersection not getting cleared

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3248]
**Description:**

The `raycaster-intersection` event should only emitted when there are **new** intersections. Else most likely it would emit every frame which would not be very useful.

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/3250

**Comment by mattrei** [comment]
Hi Kevin,

my components are kind of relying on this behavior. May we have an API on the raycaster to clear the current selected intersections, so that a new gets thrown each timeout?

Thx

**Comment by ngokevin** [comment]
You can use a tick function and check el.components.raycaster.intersectedEls

**Comment by Pluto8195** [comment]
@ngokevin, using the method mentioned above would I be able to get the point of intersection aswell?
