### ISSUE TITLE
realistic render  in a-frame

### ISSUE THREAD

**Issue by reza-mazarlou** [aframevr/aframe#3251]
hi
I import model to a-fram with obj and mtl type  like this :  

`<a-obj-model src="models/ladybug.obj" mtl="models/ladybug.mtl" scale="0.03 0.03 0.03"></a-obj-model>
`

How Can I  render this model in a-fram with realistic quality like vray in c4d or similar render engin

**Comment by donmccurdy** [comment]
A-Frame is meant for building VR experiences, meaning our three.js renderer must run at >=90FPS. Renderers like you describe are not able to run fast enough for VR, and are not supported by A-Frame.

If you want to do this type of high-quality rendering on the web, you will probably want to use [three.js](https://threejs.org/) directly along with one of the third-party pathtracing renderers. See thread here: https://twitter.com/alteredq/status/932729847301967873
