### ISSUE TITLE
How does A-Frame prioritize multiple cameras all set to "active"?

### ISSUE THREAD

**Issue by trusktr** [aframevr/aframe#3261]
What's the policy for cases when multiple cameras have the "active" attribute set to true? Does A-Frame have a way of guaranteeing that one camera will be the winner based on some criteria? Or will the winner simply be the camera who had active set to true last after all others?

**Comment by donmccurdy** [comment]
There are some plans in the roadmap for supporting spectator cameras, which might affect the concept of an "active" camera. https://github.com/aframevr/aframe/blob/master/ROADMAP.md

In the meantime, I don't think there is any technical policy - multiple active cameras won't work, and is not guaranteed to have reliable results.

**Comment by trusktr** [comment]
The reason I was curious is because in creating an HTML spec (f.e. if w3c were to take ideas from A-Frame) I think there'd need to be a guaranteed definition of "if multiple cameras have the active attribute, which camera is deterministically chosen to be active?". The answer could possibly be something like "the first camera found in pre-order traversal" or something guaranteed like that. Such a mechanism would require an extra tree traversal before rendering, unless the Three WebGLRenderer is forked and the camera is detected during the render traversal, in which case the renderer call would be just `renderer.render(scene)` without the `camera` arg and would require scenes to contain cameras unlike current Three scenes.

The reason I ask is because I'm thinking about it at https://github.com/trusktr/infamous/tree/threejs which is similar to A-Frame in some ways (i.e. using Three.js behind the scenes for WebGL rendering).

**Comment by dmarcos** [comment]
The last to initialize would be the one that wins. It should be deterministic but I don’t know without trying what the order would be. As @donmcurdy pointed out I would not encourage having multiple cameras active simultaneously. Not sure if there’s anything actionable here. Closing it for now.

**Comment by machenmusik** [comment]
Given that A-Frame uses virtual DOM, I would be hesitant to adopt anything that requires updating / relying on full DOM for consistent behavior due to performance considerations.

At the moment, I've done spectator implementation using separate WebGLRenderer (for a traditional 2D spectator view on the PC while rendering to connected HMD, for example) - not sure where @dmarcos has gotten with his latest
