### ISSUE TITLE
Rift with 2 Touch controllers, laser-controls, mouseenter, mouseleve, click events

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#3262]
**Description:**
The events mouseenter, mouseleve and click are only triggered if the two rays of the controllers meet on the element. A single controller's ray does not emit any of these events.
Example:
https://codepen.io/anon/pen/gXZqNy

- A-Frame Version: 0.7.0
- Platform / Device: FF 64bit
- Reproducible Code Snippet or URL: https://codepen.io/anon/pen/gXZqNy

**Comment by wmurphyrd** [comment]
Does this reproduce in master (and do you still get the truncated ray) or with v0.6.0? There are several issues with the 0.7.x raycaster and cursor that have been resolved

**Comment by weddingdj** [comment]
Yes, it reproduces in master and the ray of the right controller is truncated. Using v0.6.0 either the left or right ray is truncated. It seems to be changing during a session. The controller which has not a truncated ray correctly triggers the events on the elements.

**Comment by wmurphyrd** [comment]
It sounds like the same thing is happening on all versions. v0.7.0 just has an issue where the line never shortens.

Could you try adding `"objects: [test]" to your raycasters? They may be colliding with each other's rays lines or with their own controller model as the current config in your example enables collisions on everything.

**Comment by weddingdj** [comment]
If It add objects: [test] to the raycasters, it works. Like in the laser-controls example by A-Frame. But it should work if collisions are tested on everything as well, or?

**Comment by wmurphyrd** [comment]
Did you ever try setting `raycaster.near`? I think I mentioned that on slack but  I'm not sure if you noticed it. That should help if the problem is colliding with the controller model itself. Could test that (using `near` instead of `objects`) and report back? If it helps, maybe we could suggest it be added to the default `laser-controls` config. 

However, it's never going to be perfect without setting the `objects` property because the rays will collide with each other's lines.

**Comment by weddingdj** [comment]
Thanks a lot! Using `near:1` worked, without setting the `object` parameter. I know that using `object` would be best practice for performance reasons. 

I am not sure if we should mention this solution in the docs.

**Comment by wmurphyrd** [comment]
@ngokevin it looks like we have an issue with the `laser-controls` raycaster colliding with its own controller model on Oculus Touch such that no ray will appear. Would you consider a PR to `laser-controls` to set `raycaster.near` to a small value by default to prevent this?

**Comment by dmarcos** [comment]
@wmurphyrd Is this still an issue on master?

**Comment by ngokevin** [comment]
We are prescribing more heavily to explicitly define `.objects`. There's a warning and it's called out heavily in the docs. So I think that's the way to go.
