### ISSUE TITLE
Issues with intermittent VR presentation when using Rift with Firefox / Nightly

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#3266]
- A-Frame Version: master
- Platform / Device: Windows 10 Build 17046, Rift w/latest Oculus (1.20), latest NVIDIA driver (388.43) ; both latest Firefox and Nightly
- Reproducible Code Snippet or URL: any A-Frame page; e.g. https://networked-aframe-synced-video-example.glitch.me

Both latest Firefox and Nightly show intermittent failures when pressing the goggles button to begin VR presentation.  With experimental Chromium, these failures do not occur.  First noticed with https://networked-aframe-synced-video-example.glitch.me but appears to occur with any A-Frame page.

My initial suspicion was that it happened when the Rift was not tracked / outside the play area when beginning VR presentation; however, I have also had (to a lesser degree) intermittent VR presentation failures when the HMD was clearly inside the play area and visible to cameras.

I'm now wondering whether there have been recent changes to the VR presentation logic as previously discussed with @dmarcos where an initial presentation request is made with dummy canvas, to preserve permission, and is followed by the proper presentation request made with real canvas -- and if so, whether that change in behavior is causing a race condition with browser and Rift initialization...

@larsbergstrom noted in Slack that @kearwood has mentioned similar issues, see https://aframevr.slack.com/archives/C0GG937RN/p1512411177000078

**Comment by ngokevin** [comment]
Can reopen if this is still an issue.
