### ISSUE TITLE
How to open the VR split screen mode?

### ISSUE THREAD

**Issue by cooper1x** [aframevr/aframe#3267]
**Description:**

- A-Frame Version:latest
- Platform / Device:PC
- Reproducible Code Snippet or URL:http://wow.techbrood.com/fiddle/35316

When I open this page, there is a button in the lower right corner.
![image](https://user-images.githubusercontent.com/9080789/33598267-0c3187c2-d9dd-11e7-8370-98b81a8fb316.png)
I want to use this button to achieve the sub screen effect of the next figure,What should I do?
![image](https://user-images.githubusercontent.com/9080789/33598339-54e659fc-d9dd-11e7-9b89-b97144aefeb8.png)
https://mozvr.com/webvr-demos/demos/nepal/

**Comment by dmarcos** [comment]
You need to have a VR headset connected on desktop or run it on a smartphone. Closing since this is not an bug or a feature request.
