### ISSUE TITLE
Unable to add labels or text to shapes

### ISSUE THREAD

**Issue by Kshukla** [aframevr/aframe#327]
Could not find any property to add labels or text to an existing shape.

1) If it exists please mark this as a question for answer / also please guide me how to find this information on my own in future and not bother you.
2) If not please suggest if this can be added as an enhancement.

Regards,
Kapil

**Comment by ngokevin** [comment]
You can use https://github.com/ngokevin/aframe-text-component for now.

Download the `dist` files in the repository. Include it after `aframe` JS file. Then:

```html
<a-entity text="text: HELLO"></a-entity>
```

We'll have official support for this soon. Thanks!

**Comment by Kshukla** [comment]
Super thanks.
