### ISSUE TITLE
Raycaster reports intersections with entities excluded by objects property when nested

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#3276]
**Description:**

Entities that are excluded by `raycaster.objects` can be reported as an intersected entity if they are a child of a selected entity. It makes sense that descendant meshes are included in the raycaster's search, but I would expect that the the parent which is specified in `objects` would be reported as the intersected entity in the `raycaster-intersection` event so that the reported intersections are exclusively with entities specified in `objects`

I can work on this if you agree

- A-Frame Version: 0.7.0 & master
- Platform / Device: desktop Firefox
- Reproducible Code Snippet or URL: https://cdn.rawgit.com/aframevr/aframe/c2f08cf0/dist/aframe-master.min.js

Only '#box' is included in `raycaster.objects`, but '#sphere` will appear as the event target when clicked.

**Comment by ngokevin** [comment]
Agreed, just ran into this bug.

**Comment by wmurphyrd** [comment]
Fixed in #3652
