### ISSUE TITLE
Object overlap

### ISSUE THREAD

**Issue by Kshukla** [aframevr/aframe#328]
Objects randomly overlap with each other 

Example : check out http://www.vuutu.xyz or if this is taking time for DNS replication, please check out http://www.justdeliver.us

login and you should be able to see your facebook photos as a curved image. If you mouseover a picture, it overlap.

**Comment by jcarpenter** [comment]
Thanks for flagging @Kshukla. I'm only seeing black, however. I checked with both Firefox Nightly and Chrome on my Mac Book Pro w/ El Capitan. Console confirms successful login with Faceook, but errors for jquery loading.

**Comment by cvan** [comment]
Likewise. I'm seeing this:

<img width="1316" alt="screenshot 2015-12-21 22 44 17" src="https://cloud.githubusercontent.com/assets/203725/11947416/61ba80b8-a834-11e5-83a2-f90fec860053.png">

**Comment by Kshukla** [comment]
Sorry about this trouble, been playing on this environment. Give me sometime and i will compile if nothign with some screen shots and some codes. Will provide more details.

**Comment by Kshukla** [comment]
Its most likely that i might be screwing it up somewhere , I am looking into it now but just wanted to keep you in loop as well :

I am looping through all the facebook photos as a curved image , The logic is simple

Each subsequent image position 'position="0 '+s+' 0"' where s += 2 (until R no of rows as defined by application are reached) and rotation is 'rotation="0 '+q+' 0" ' where q += 20

This way i am building towers high of the pictures each 20 degrees apart. However on the mouse over when i scale the image out it randomly sometimes comes in front and hides the object behind it (which i am expecting it to do ) but then sometime the image behind it appears on top of the scale out image

My object definition as it spits out from the script are below :

Example:

<a-curvedimage src="https://graph.facebook.com/10153728423046579/picture?access_token=CAAAABiP9…FNo9J6BLOziBmzJ9PAi46g4QyGFBP8sptGMGDZAS2HM9gW0E24Rq6rmLnKcFL8ZCovuQtgZDZD"  radius="3.7" theta-length="15"  position="0 -4 0"  rotation="0 -180 0" scale="1.5 1.5 1.5"><a-mouseenter scale="3 3 1" ></a-mouseenter><a-mouseenter target="#shadow" scale="2 2 0"  ></a-mouseenter><a-mouseleave scale="1 1 1"></a-mouseleave><a-mouseleave target="#shadow" scale="1 1 0"></a-mouseleave></a-curvedimage>

<a-curvedimage src="https://graph.facebook.com/10153600866101579/picture?access_token=CAAAABiP9…FNo9J6BLOziBmzJ9PAi46g4QyGFBP8sptGMGDZAS2HM9gW0E24Rq6rmLnKcFL8ZCovuQtgZDZD"  radius="3.7" theta-length="15"  position="0 -2 0"  rotation="0 -180 0" scale="1.5 1.5 1.5"><a-mouseenter scale="3 3 1" ></a-mouseenter><a-mouseenter target="#shadow" scale="2 2 0"  ></a-mouseenter><a-mouseleave scale="1 1 1"></a-mouseleave><a-mouseleave target="#shadow" scale="1 1 0"></a-mouseleave></a-curvedimage>

ps: Facebook requires an app review before others can use the site, I will keep you posted once the I have more details on availability for you to test.

**Comment by Kshukla** [comment]
Should be solved now. Try it please.

On Mon, Dec 21, 2015 at 7:44 PM, Chris Van <notifications@github.com> wrote:

> Likewise. I'm seeing this:
>
> [image: screenshot 2015-12-21 22 44 17]
> <https://cloud.githubusercontent.com/assets/203725/11947416/61ba80b8-a834-11e5-83a2-f90fec860053.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aframevr/aframe/issues/328#issuecomment-166497731>.
>



-- 
Regards

**Comment by cemkod** [comment]
I am looking at the site right now, but mouse over does nothing at all.

**Comment by Kshukla** [comment]
Cursor focus should.

**Comment by cvan** [comment]
Is there a still an issue here?

**Comment by Kshukla** [comment]
Yes, Do you want me to update the A-Frame version ? With the existing version it is still an issue.

You can check it out @ prototype : http://www.vuutu.xyz

**Comment by cvan** [comment]
okay, I signed in through FB and checked this out. pretty neat grid!

all the images initially appear at `1.5` scale.
when I hover over an image, it appears at `2` scale.
when I stop hovering that image, it appears at `1` scale. _(shouldn't this be `1.5`?)_

![image](https://cloud.githubusercontent.com/assets/203725/12248628/89617176-b86f-11e5-90a6-27eb05fc36c7.png)

also, I see `target="#shadow"`, but I don't see a `#shadow` element anywhere. _is this dead code?_

**Comment by Kshukla** [comment]
Dead code is fixed. I have for now disabled the scale property, until i can resolve the overlapping issue. Thanks. Will reopen the issue in case something from framework is missing. Thanks.
