### ISSUE TITLE
a-canvas not always fullscreen in iOS Chrome

### ISSUE THREAD

**Issue by tomegz** [aframevr/aframe#3282]
**Description:**
Scene doesn't take up whole screen. Even if it does initially, it breaks after changing device's orientation. In Safari it works alright - i expierienced it only on Chrome iOS. Chrome version: 62.0.3202.70
![25344290_1651791048206153_1585761493_o](https://user-images.githubusercontent.com/25149657/33893126-ffaae1a0-df5a-11e7-98e0-4be8fa0ed6ca.jpg)

- A-Frame Version: 0.5.0, i also expierenced it on my own demos with 0.7.0 version
- Platform / Device: iPad Air 2
- Reproducible Code Snippet or URL: https://aframe-gallery.glitch.me/

**Comment by tomegz** [comment]
I haven't dug into A-Frame's source code but it may be caused by fact that "orientationchange" event doesn't come with correct values at first (maybe just on iOS Chrome) - they update slightly after the event is emitted - hence it's resizing to wrong size. In my demos i have my own ui which resizes on "orientationchange" event - to prevent this from happening i would use something like this:

`function orientationChanged() {
        const timeout = 20;
        return new window.Promise(function(resolve) {
          const go = (i, height0) => {
            window.innerHeight != height0 || i >= timeout ?
              resolve() :
              window.requestAnimationFrame(() => go(i + 1, height0));
          };
          go(0, window.innerHeight);
        });
      }`
And use it like this:
`orientationChanged.then(function() { 
  resize();
});`

**Comment by arturitu** [comment]
It seems that the cause is known webkit bug: https://bugs.webkit.org/show_bug.cgi?id=170595
