### ISSUE TITLE
Camera position increases infinitely when entering VR in 2D mode.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3285]
**Description:**

Regression from VREffect removal.

Go to Anime UI without a headset, hit Enter VR, press one of the WASD. The camera should start moving uncontrollably towards one direction.

![camera](https://user-images.githubusercontent.com/674727/33913039-0bcc9068-df4d-11e7-9522-2d6128fe7b1b.gif)

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/3286

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/3286
