### ISSUE TITLE
text is broken

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3287]
**Description:**

See `text` example, text does not appear.

**Comment by machenmusik** [comment]
https://aframe.io/aframe/examples/test/text/ works for me in Safari and Chrome, can you be more specific?

**Comment by ngokevin** [comment]
On the branch, not on stable.

**Comment by machenmusik** [comment]
from https://a-frobot.github.io/aframe/examples/test/text/index.html
I see some new warnings, something else seems wrong...
```
A-Frame Version: 0.7.0 (Date 2017-12-12, Commit #1c3db47)
index.js:87 three Version: mrdoob/three.js#aa7557123d
index.js:88 WebVR Polyfill Version: ^0.9.40
three.js:21183 THREE.WebGLRenderer 89dev
three.js:5560 THREE.Color: Unknown color #98d8
three.js:5560 THREE.Color: Unknown color #3b532
three.js:5560 THREE.Color: Unknown color #2b490
three.js:5560 THREE.Color: Unknown color #5eda1
three.js:5560 THREE.Color: Unknown color #a0421
three.js:5560 THREE.Color: Unknown color #ef829
three.js:5560 THREE.Color: Unknown color #cde17
three.js:5560 THREE.Color: Unknown color #5d4c9
three.js:5560 THREE.Color: Unknown color #1a6ee
three.js:5560 THREE.Color: Unknown color #31798
three.js:5560 THREE.Color: Unknown color #4642f
three.js:5560 THREE.Color: Unknown color #afffb
three.js:5560 THREE.Color: Unknown color #ae4c5
```

**Comment by ngokevin** [comment]
The warnings are from the custom color animation code of that example, but not related to the text not appearing.

**Comment by machenmusik** [comment]
maybe we should only use stable versions of three.js (like webvr-polyfill) ?
not sure why we are using a specific commit that is rendered 89dev ...

**Comment by ngokevin** [comment]
Commit was for being able to get rid of VREffect and use three.js's more performant VR renderer. It could be the case that it's an intentional change on three.js part, we need to investigate the exact issue and determine from there (perhaps three.js bisect).

**Comment by mkungla** [comment]
should rename the issue lot of examples are broken and  issue was introduced by https://github.com/aframevr/aframe/commit/3d188db12742d162b2c9e60ffd0222f75acaffa1

**Comment by mkungla** [comment]
@dmarcos somewhere textures are not applied to scene

**Comment by mkungla** [comment]
@dmarcos seems that textures are not applied to renderer
```
-        this.animationFrameID = effect.requestAnimationFrame(this.render);
-        effect.render(this.object3D, this.camera, this.renderTarget);
+        renderer.animate(this.render);
+        renderer.render(this.object3D, this.camera, this.renderTarget);
```

**Comment by ngokevin** [comment]
The offending PR https://github.com/mrdoob/three.js/pull/12787
