### ISSUE TITLE
Docs for `getAttribute` API changes

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#3299]
With https://github.com/aframevr/aframe/pull/3245 there is a nontrivial API changes v0.8.0 — is still a good idea to use `AFRAME.utils.deepEqual` or `AFRAME.utils.diff`, or should we encourage users to go with three.js equivalents?

```js
var pos1 = el1.getAttribute('position');
var pos2 = el2.getAttribute('position');
assert(pos1.equals(pos2));
```

I answered a question in Slack recently about how to keep track of `oldData` and `newData` since they were [removed from the `componentchanged` event](https://github.com/aframevr/aframe/issues/3165). Here's what I suggested:

```js
var oldRotation = new THREE.Vector3().copy(el.getAttribute('rotation'));
var newRotation = new THREE.Vector3();
el.addEventListener('componentchanged', function (e) {
  if (e.detail.name !== rotation) return;

  newRotation.copy(el.getAttribute('rotation'));
  if (newRotation.equals(oldRotation)) return;

  console.log('rotation changed!');
  oldRotation.copy(newRotation);
});
```

Wanted to open an issue to make sure we flag this appropriately in docs and examples. I was using the `Vector3.copy()` trick before #3245 went in, and have been happy enough with that pattern.

**Comment by ngokevin** [comment]
Thanks, I'll make sure documentation is fully updated for 0.8.0.

I'd recommend using three.js patterns, you'd save a vector in that case. Definitely not use `.deepEqual` or `.diff` as those are heavier versus just comparing x/y/z values.

Though the improvements are more around *setting* of the transformations rather getting a vector/euler back.
