### ISSUE TITLE
Missing texture file for Oculus controller object

### ISSUE THREAD

**Issue by piede828** [aframevr/aframe#3307]
**Description:**

The Oculus controller object is missing the texture file and cannot be reproduced. 
Attached is the missing file.

![external_controller01_col](https://user-images.githubusercontent.com/10402462/34079120-d99ff460-e31e-11e7-958b-5fad5c7ec8de.png)

**Comment by dmarcos** [comment]
The textures load just fine for me. We host them on the assets repo https://github.com/aframevr/assets/blob/gh-pages/controllers/oculus/external_controller01_col.png
What example is not working for you?

**Comment by ngokevin** [comment]
Closed for inactivity, let us know if you have any updates
