### ISSUE TITLE
Event for WASD movement

### ISSUE THREAD

**Issue by RangerMauve** [aframevr/aframe#331]
I was thinking of making a component for setting constraints on where a person could walk based on a mapping of some sort. It'd be useful if the component could just be attached to something that already has the WASD component and listen to when the person gets moved.

It'd be nice if I could make code that'd look something like:

```js
this.addEventListener("move", handleMovement);

// ....

function handleMovement(event){
 var position = event.data.position;
 var previousPosition = event.data.previousPosition;

 if(!canMoveTo(position)){
   this.setAttribute("position", previousPosition);
 }
}
```

**Comment by ngokevin** [comment]
You can do el.addEventListener('componentchanged') and check the event is on wasd-controls.

**Comment by RangerMauve** [comment]
Thanks! Is there something in the docs related to that event that I must have missed?

**Comment by ngokevin** [comment]
It might have been added recently, but it's at the bottom of:

https://aframe.io/docs/core/entity.html#Events

**Comment by RangerMauve** [comment]
Ah! Totally didn't register that part. Thanks!
