### ISSUE TITLE
userHeight not applied when there are not stageParameters

### ISSUE THREAD

**Issue by MortimerGoro** [aframevr/aframe#3315]
**Description:**

- A-Frame Version: 0.7
- Platform / Device: 6DOF Mobile headset
- Reproducible Code Snippet or URL:

After https://github.com/aframevr/aframe/commit/3d188db12742d162b2c9e60ffd0222f75acaffa1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 it seems that userHeight is not applied in devices using null stageParameters and the camera is on ground level. 

Should this be fixed on A-frame or do we need to fix this in Three.js? https://github.com/mrdoob/three.js/issues/11619

I have a wip in the Three.js WebVRManager class to to handle standingTransform and could make a PR if you want the code to be there.

What do you think?

**Comment by MortimerGoro** [comment]
BTW where is stageParameters.sittingToStandingTransform used now for the headset camera? I only see references in tracked-controls.js file for handling gamepads

**Comment by dmarcos** [comment]
This should be fix on the A-Frame side. I have an API to fix this that introduces a camera rig to set the height of the user instead of using `stageParameters` in similar way than the THREE examples
