### ISSUE TITLE
Pass custom LoadingManager into glTF Model

### ISSUE THREAD

**Issue by maximeLong** [aframevr/aframe#3328]
I wanted to raise a question - would there be any drawbacks to updating the glTF-Model to have the ability to pass in a custom THREE.LoadingManager? This thought was brought up because I'm currently trying to handle relative paths in glTF files, and the best way I've found is using the @donmccurdy 's method in his custom glTF-Viewer which uses `THREE.LoadingManager.setURLModifier()` . 
Is there a reason that the LoadingManager is not available by default in Aframe? 

On a related note - @donmccurdy do you see any drawbacks to adding your relative URL interceptor code from your glTF-Viewer library into the official glTF-Model component directly (I could make a pull request depending on what you think)? I'm talking about this method: 
```
       //Intercept and override relative URLs.
        const manager = new THREE.LoadingManager();
        manager.setURLModifier((url, path) => {
          const normalizedURL = rootPath + url
            .replace(baseURL, '')
            .replace(/^(\.?\/)/, '');
          if (assetMap.has(normalizedURL)) {
            const blob = assetMap.get(normalizedURL);
            const blobURL = URL.createObjectURL(blob);
            blobURLs.push(blobURL);
            return blobURL;
          }
          return (path || '') + url;

        });
        const blobURLs = [];
```

- A-Frame Version: 0.7.1
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by maximeLong** [comment]
this was more difficult than I initially thought - I think a custom component will have to be written that can parse a map of files, rewrite their relative paths, and add them to <a-assets> .. I'll try and bring this up on Slack and see what people have to say.

**Comment by donmccurdy** [comment]
Yeah, I think this is a bit difficult to do with an all-HTML API... perhaps there could be a single manager exposed on the `<a-scene>` or `<a-assets>` object, and `*-model` components can be changed to reuse that? This would make some other things easier like displaying a loading bar, too. For the drag-and-drop use case, which is a bit trickier to implement, developers could do something like:

```js
var manager = sceneEl.manager;
manager.setURLModifier((url) => url.replace('foo', 'bar'));
```
