### ISSUE TITLE
rayOrigin: mouse - unexpected behavior on mobile

### ISSUE THREAD

**Issue by tomegz** [aframevr/aframe#3330]
**Description:**
Expected behavior: boxes scale up on click/touch.
  First example uses solely cursor="rayOrigin: mouse" - after i touch the box i expect the click to be emitted immediately, instead it emits after about 1500ms which might be fuseTimeout ( i didn't expect it to fuse after setting rayOrigin to mouse - i thought fuse is only for gaze based ). 
  The second examply uses cursor="rayOrigin: mouse; fuse: false". Again expected behavior is that click fires immediately on touch. Actual behavior: click fires after quick double tap, or tap once and then touchstart/drag anywhere on screen.

In both examples first box seems to be somehow initially selected - after touchmove anywhere on the screen it acts as clicked.

- A-Frame Version: 0.7.0
- Platform / Device: Android, Chrome Mobile
- Reproducible Code Snippet or URL: [Example 1](https://coral-crate.glitch.me/), [Example 2](https://private-scent.glitch.me/)
- Code: [Code example 1](https://glitch.com/edit/#!/coral-crate), [Code example 2](https://glitch.com/edit/#!/private-scent)

**Comment by xiongbinsh** [comment]
about tomegz's [Example 2](https://private-scent.glitch.me/), i  got same issue.

than i add some test js code like:  [codepen link](https://codepen.io/xiongbinsh/pen/vprMRK)

`sceneEl.addEventListener("mousedown",function(e){ console.log(e) ;
console.log(this.components.raycaster.raycaster.ray.direction);
}) ` 

step:
- in mobile chrome browser(or from desktop chrome "Ctrl-Shift-I, Ctrl-Shift-M" shortcut to mobile simulator )

- reload the codepen page metioned above and see logs in chrome dev console.

- tap anywhere in mobile screen

issue:
on the first time of tap, the ray direction in log is always {x: 0, y: 0, z: -1}
then tap more , each time the cursor ray 's direction( vector3 )  is not the data of current touch direction, but the previous touch data.

only found in mobile mode,  it seems  no same issue found in desktop mode of chrome.

**Comment by wmurphyrd** [comment]
Fixed this in #3201

**Comment by xiongbinsh** [comment]
@wmurphyrd  many thanks for the update

**Comment by mkungla** [comment]
@wmurphyrd should this issue be closed?

**Comment by wmurphyrd** [comment]
@mkungla yes

**Comment by mkungla** [comment]
@aframevr/a-team can you close it!

**Comment by dmarcos** [comment]
Closing now! Sorry, I'm a bit late on this.
