### ISSUE TITLE
Shader couldn't compile

### ISSUE THREAD

**Issue by AhambaliJ** [aframevr/aframe#3332]
I turned a nested entity invisible by using `visible="false"`, the console returned an error that the `shader couldn't compile`. Error coming from `aframe.js`.

If I set it visible to true, the error is not thrown. 

- A-Frame Version: master
- Platform / Device: Google Chrome 63.0.3239.132 / Desktop
- Reproducible Code Snippet or URL: https://fresh-palm.glitch.me/

**Comment by takahirox** [comment]
`alphaTest` should be `1.0` > `alphaTest` >= `0.0`.

https://fresh-palm.glitch.me/cursorbody.js

**Comment by dmarcos** [comment]
Is there any action to be taken on the A-Frame side here?
