### ISSUE TITLE
Support BufferGeometryLoader?

### ISSUE THREAD

**Issue by 3dgg** [aframevr/aframe#3336]
I would like to be able to load an json file <Geometry export >from threejs editor. This json file only include BufferGeometry (a box)     A-Frame support  registerGeometry  such as  THREE.BoxBufferGeometry into frame entity.     but  THREE.BufferGeometryLoader   doesn't work,  Thanks!

**Comment by donmccurdy** [comment]
I would try `json-model` and `object-model` from aframe-extras first: https://github.com/donmccurdy/aframe-extras/tree/master/src/loaders

I think that `object-model` should work. You can also export glTF from the three.js editor.

Registering new geometry types, as shown here, is likely to be a bit harder.

**Comment by 3dgg** [comment]
You say I have been using the object - model method, because the import object with a material, can't in aframe scene manually modify the material inside, this is very easy, in three so I want to import the geometry alone, without the import material method, custom geometry components in a - frame, then add material - override this component, so that the whole work conveniently.

**Comment by donmccurdy** [comment]
Hm I see. Yes if the goal is not just to load a JSON model, but also have it work with the `material` component, then being able to use `registerGeometry` to create a geometry type that loads custom models would be helpful.

Creating JSON models is its own problem (the three.js editor isn't really a modeling tool, and the three.js Blender exporter has a lot of open issues) but maybe a similar thing could also work for more common formats.

The reason this doesn't work, I think, is that the geometry system expects `this.geometry` to be set during the `init()` call, and so asynchronous loading isn't possible:

https://github.com/aframevr/aframe/blob/2fe545627f8487475b2be80c99f91a585cb93a92/src/systems/geometry.js#L92-L107

If we could make that asynchronous it would allow this, but might also affect how materials are applied etc., so maybe not a small change. Would be curious to see a PR implementing it if you have time. :)

**Comment by 3dgg** [comment]
Thank you again for your reply
Often encounter such a situation, import operators or aframe objects with production softwares 3 dmax, Maya, Blender these modeling software to see the display of the different of the scene, these may be the problem of the export plug-in, you said so designers prefer real time adding color material in the scene, so that the final effect is you need.

In THREE load object is usually only a object  json  file, because it is at the time of loading can be defined to replace the material.If  object -model  loading time A-frame can also modify the material   is pretty good, of course only load the geometry file without material, less data, the speed will be faster.

Think there is such a vr scene, a car inside, if you want to be a key to replace the wheel parts, or   a key to replace body material, no matter use what format loaded geometry, must use the geometry of the custom components.Of course the json as the default format of three, I think is the most appropriate.Continue to look forward to you and the community as early as possible for this function, thanks!

**Comment by ngokevin** [comment]
Can have as a component, just skip the registerGeometry API
