### ISSUE TITLE
The 360 Screenshot Bug

### ISSUE THREAD

**Issue by scheerio** [aframevr/aframe#3337]
**Description:**

There is a bug when doing the widely-used 360 screenshot (https://aframe.io/blog/screenshot/). You can take a screenshot, but when they come out, I mini 2D version of the world appears in the middle of the shot. Here is an example photo where you can see the issue. No solution yet identified.

- A-Frame Version: 0.7.0
- Platform / Device: All

![screenshot-wild-1515678861325](https://user-images.githubusercontent.com/26422030/34890630-9af1f784-f7ca-11e7-87d7-285f6bffc465.png)

**Comment by dmarcos** [comment]
I cannot see any problem in the provided screnshot. Do you have an alternative one  that shows the issue more clearly?

**Comment by wmurphyrd** [comment]
It's hard to see if you don't have a frame of reference for what the scene should look like. I've drawn a circle around the artifacts in this example: 
![inkedsticky_li](https://user-images.githubusercontent.com/10034859/35186869-06e7e3e2-fde1-11e7-9995-b5217ac0694d.jpg)

@scheerio is your scene using aframe-environment-component? I'm not sure, but I think the issue might be limited to when that component is in use

**Comment by scheerio** [comment]
Yes -- if you look in the middle of my photo, you can see mini bamboo shoots and white particles from the particle system. I am not actively using the environment component, so that shouldn't be the issue. The particle system always causes the problem, but those bamboo shoots are just cylinders and shouldn't cause problem. Any thoughts? I'm not the only one experiencing this it seems.
