### ISSUE TITLE
Gyroscope Movement Not Working

### ISSUE THREAD

**Issue by acm0055** [aframevr/aframe#3340]
**Description:**

When viewing the 360 video example on an iPhone6S, the gyroscope movement does not work. I have tested the video works on an Android phone I own. It may be a problem with the webvr-polyfill. I can also attest that the gyroscope works on other examples. It seems confined to this example.

- A-Frame Version: 0.7.1
- Platform / Device: iPhone 6S (Safari and Google Chrome)
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/videosphere/

**Comment by aadityak** [comment]
This is a major issue that needs a fix.

Tested on Samsung J7 NXT and Samsung S6 by visiting https://feiss.github.io/aframe-environment-component/ from the mobile browser.

**Comment by dmarcos** [comment]
This no longer applies. Can reopen if necessary
