### ISSUE TITLE
Raycast refresh isn't working?

### ISSUE THREAD

**Issue by jahardner** [aframevr/aframe#3342]
**Description: Raycast always triggers on objects, even with a manual refresh**

- A-Frame Version: 0.7.0 and 0.7.1
- Platform / Device: Firefox/Chrome
- Reproducible Code Snippet or URL:

I have a-frame scene with a menu that toggles visible/invisible, regardless of its visibility the raycaster always triggers though. So I edited the raycaster to only register .link objects, and I now change the objects classes when toggling the menu, and I also do a manual refresh of the raycaster. Still triggers. My controls:

```
<a-entity camera look-controls>
      <a-entity position="0 0 -3"
                geometry="primitive: ring; radiusOuter: 0.08;
                          radiusInner: 0.05; thetaLength: 360; thetaStart: 90;"
                material="color: cyan; shader: flat"
				        raycaster="objects: .link; recursive: false; autoRefresh: false"
                cursor="maxDistance: 500; fuse: true; timeout: 3000;">
        <a-animation begin="cursor-fusing" attribute="geometry.thetaLength" fill="forwards" from="360" to="0" easing="ease-in"></a-animation>
      <a-animation begin="mouseleave" attribute="geometry.thetaLength" fill="backwards" from="0" to="360" dur="0"></a-animation>
      </a-entity>
    </a-entity>
```

**Comment by donmccurdy** [comment]
Could you test your code with A-Frame master branch? There have been some fixes related to this.

**Comment by jahardner** [comment]
So, ah, for whatever terrifying reason my cursor stops working completely on master...

**Comment by wmurphyrd** [comment]
Is it possible that you're seeing the same thing as #3276?

**Comment by jahardner** [comment]
@wmurphyrd Possibly, though I don't believe so because I'm updating both the object's class and the template object's class (and I can see this in the inspector), the raycast just doesn't seem to acknowledge the change?

**Comment by ngokevin** [comment]
Should work now, try it out on master.
