### ISSUE TITLE
text not support chinese character

### ISSUE THREAD

**Issue by AlexZ33** [aframevr/aframe#3343]
**Description:**

- A-Frame Version: releases/0.7.0
- Platform / Device: PC 
- Reproducible Code Snippet or URL:

As the title, when I  use the following code ,it shows no '大库' 

 
`<a-entity id="text" position="-0.8 3.0 -5.0" text-geometry="value: 4大库;  style: italic; size: 0.5; weight: bold; height: 0; bevelEnabled: true; bevelSize: 0.04; bevelThickness: 0.04; curveSegments: 1"
                    material="shader: flat; color: white; transparent: false; opacity: 0.4"></a-entity>`

**Comment by dmarcos** [comment]
The default fonts don’t come with chinese glyphs. You need to use a font that comes with them. This project contains all the google fonts: https://github.com/etiennepinchon/aframe-fonts
I don’t know if any comes with chinese characters. It would be nice if someone finds one and makes it available for the community.

**Comment by arpu** [comment]
aframe could use  https://github.com/googlei18n/noto-fonts

**Comment by dmarcos** [comment]
Someone has to process them to be used as SDF fonts.

**Comment by donmccurdy** [comment]
See: https://github.com/aframevr/aframe/issues/3355

**Comment by donmccurdy** [comment]
I've put together a little web tool for generating these MSDF fonts. It will support special characters correctly, and you can provide your own fonts if you wish.

http://msdf-bmfont.donmccurdy.com/

^note, this requires the `negate: false` setting on A-Frame's `text` component, which is only available on the master branch and will be released with 0.8.0.
