### ISSUE TITLE
Camera and hand tracking is off

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3345]
**Description:**

On tracked-controls, the camera is too low, and the hands are off in the distance. Going back to before the VREffect removal / r88, the hands are in the right position.

On 0.7.1, the camera and hands are in the right positions.

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
What headset / browser?

**Comment by fernandojsg** [comment]
I can reproduce it with vive and firefox

**Comment by dmarcos** [comment]
This should be fixed by https://github.com/aframevr/aframe/pull/3312
