### ISSUE TITLE
Entering VR with WinMR crashes Edge browser window

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#3350]
Entering VR with WinMR crashes Edge browser window.

To reproduce:
0. Set up your WinMR environment and confirm it works fine.
1. Open an Edge window and go to aframe.io Hello WebVR -- or directly to https://aframe-360-video-example.glitch.me/
2. Notice that 360 video plays fine in browser window -- either inside or outside VR.
3. Click the goggles button to enter VR with WinMR.
4. Notice that you get the correct transition animation into WebVR, but that it drops you back to the Cliff House scene (perhaps with a dormant Edge window).  If you started outside VR, notice the Edge window is gone / has crashed.

FYI, that 360 video example is using A-Frame 0.7.1 but this can be reproduced with master as well.

**Comment by machenmusik** [comment]
(Note, my machine is running Insider Preview build)

**Comment by dmarcos** [comment]
I have not tried that specific example but https://aframe.io/aframe/examples/showcase/tracked-controls/ works fine for me on a Razer Blade 13"

**Comment by machenmusik** [comment]
Thanks @dmarcos - what Windows 10 build are you running?

**Comment by machenmusik** [comment]
The same occurs for me with https://webvr.info/samples/03-vr-presentation.html so it is not A-Frame specific, as it turns out

**Comment by dmarcos** [comment]
My windows version:

![winver](https://d3vv6lp55qjaqc.cloudfront.net/items/291D3U1R1c1e221W3a1b/Image%202018-01-23%20at%201.57.37%20PM.png?X-CloudApp-Visitor-Id=222920&v=d97ece4d)

**Comment by machenmusik** [comment]
Thanks again - for me it's 
`Version	10.0.17063 Build 17063`

Maybe I need to roll back for now...

**Comment by leweaver** [comment]
Hey, thanks for letting me know. I'll take a look around for known issues; but if there isn't something immediate, would you mind collecting a repro in the "feedback hub" app for us? this should collect logs.

https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app

**Comment by machenmusik** [comment]
(looks like there is a new build available, will try going forward first)

**Comment by machenmusik** [comment]
@leweaver just submitted as part of https://aka.ms/Fup824

**Comment by leweaver** [comment]
great thanks, will take a look!

**Comment by machenmusik** [comment]
will let you know whether build 17074 fixes it, may not know until later tomorrow though

**Comment by leweaver** [comment]
I have a hunch as to what bug was causing this; there is a bug in 17063 that could cause this. And the good news is that the fix exists in 17074 - so let me know how you go!

**Comment by dmarcos** [comment]
I'm closing this since it seems it is not specfic to A-Frame. We will reopen if there's any action to be taken on the A-Frame side.

**Comment by machenmusik** [comment]
For completeness - 
Windows 10 Insider Preview build 17063 is broken (see above).
Update to build 17074 which does NOT suffer from that problem.
Thanks @leweaver @dmarcos for helping to chase down!
