### ISSUE TITLE
Add cameraRig property to wasd-controls

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#3351]
After #3327, it will often be preferable for `wasd-controls` to move the camera rig rather than the camera itself, relative to the camera heading. Similar to `teleport-controls`, we should add a `cameraRig` property to enable this:

```html
<a-entity id="cameraRig" position="25 100 25">
  <a-entity id="head" camera position="0 1.6 0" look-controls wasd-controls="#cameraRig;"></a-entity>
  <a-entity teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
  <a-entity teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
</entity>
```

**Comment by dmarcos** [comment]
Instead of coding this in the component I would provide examples where we use the camera rig pattern: The controllers and camera wrapped in an entity where the wasd-controls is applied:
```
<a-entity id="cameraRig" position="25 100 25" wasd-controls>
  <a-entity id="head" camera position="0 1.6 0" look-controls></a-entity>
  <a-entity teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
  <a-entity teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
</entity>
```

**Comment by donmccurdy** [comment]
The problem with this pattern is that `wasd-controls` will always move in the `-Z` direction when pressing <kbd>W</kbd>, rather than matching the `#head` element's heading. An alternative to the `cameraRig` selector would be a `camera` selector to specify the element used to determine heading.

**Comment by machenmusik** [comment]
Some thoughts
- I think you want to move the rig, and let local roomspace offsets apply to the rig children
- I think you want wasd-controls attached to what it is moving, and it would be good to have a selector reference if you want to also take into account the orientation of a child (like HMD camera)
- when implementing wasd-controls steered by another element like HMD camera, a little care may be required to ensure the proper orientation to move in (as the rig may itself be rotated)

**Comment by donmccurdy** [comment]
How about this as proposed syntax, then:

```html
<a-entity id="cameraRig" position="25 100 25" wasd-controls="camera: #head">
  <a-entity id="head" camera position="0 1.6 0" look-controls></a-entity>
  <a-entity teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
  <a-entity teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
</entity>
```

The `camera` selector could default to `''` (for current element).

**Comment by machenmusik** [comment]
LGTM with some possible naming nits...

- there's no reason why the wasd-controls direction source needs to be a camera, so might want a more generic parameter name.

- there's no reason why the teleport-controls movement target needs to be a cameraRig, so might want a more generic parameter name.

- teleportOrigin seems a little verbose given that it's teleport-controls, but not a big deal

**Comment by machenmusik** [comment]
Sanity check - if you force camera position to `0 1.6 0` will that cause problems in 6DOF VR?

**Comment by dmarcos** [comment]
The position of the camera will be overridden with the headset position, hence the need of a camera rig

**Comment by dmarcos** [comment]
But the position of the camera is saved when entering VR and restored when exiting so you should get your `0 1.6 0` back

**Comment by machenmusik** [comment]
Great, confirming - no more user height parameter, entity with active camera will forcibly have position overridden in VR?  (E.g. if there is separate spectator camera, that one will NOT be overridden?)

**Comment by greengiant83** [comment]
I created pull request to address this issue:
https://github.com/aframevr/aframe/pull/3394

**Comment by ngokevin** [comment]
wontfixing for now...https://github.com/aframevr/aframe/pull/3394#issuecomment-483590639
