### ISSUE TITLE
Raycaster crashes scene when used with a-obj-model

### ISSUE THREAD

**Issue by banada** [aframevr/aframe#3358]
Running the code below will crash the scene.
The raycaster works just fine with `<a-box>`, and this happens with different .OBJ models

- A-Frame Version: 0.7.0
- Platform / Device: PC / Firefox 57.0.4

Console output:
```
TypeError: R is undefined [Learn More] three.js:16209:19
[41]</</Bt.prototype<.raycast</< three.js:16209:19
cr three.js:40276:2
intersectObjects three.js:40349:4
[95]</module.exports.Component<.tick</< raycaster.js:171:25
value a-scene.js:586:10
value a-scene.js:634:30
[189]</module.exports/</< bind.js:12:13
```

Steps to reproduce:

Run the example below with this object model in the local directory:
[dishwasher.zip](https://github.com/aframevr/aframe/files/1670480/dishwasher.zip)

What stops the bug? Either:
1. Remove `raycaster="objects: .pickup; far: 5"` on the controller entity
or
2. Remove or change `class="pickup"` on the a-obj-model

- Reproducible Code Snippet: 

```
<html>
	<head>
		<script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
	</head>
	<body>
	<a-scene>
		<a-assets>
			<a-asset-item id="dishwasher-obj" src="dishwasher/dishwasher.obj"></a-a-asset-item>
			<a-asset-item id="dishwasher-mtl" src="dishwasher/dishwasher.mtl"></a-asset-item>
		</a-assets>
		
		<a-entity id="cameraRig" position="0 0 0">
				<a-entity id="head" camera wasd-controls look-controls></a-entity>
				<a-entity id="left-hand" vive-controls="hand: left"></a-entity>
				<a-entity id="right-hand" laser-controls="hand: right" raycaster="objects: .pickup; far: 5"></a-entity>
		</a-entity>
		
		<a-obj-model class="pickup" src="#dishwasher-obj" mtl="#dishwasher-mtl" scale="0.045 0.045 0.045" position="0 0 -2"></a-obj-model>
		<!--<a-box color="red" class="pickup" position="0 0 -2"></a-box>-->
	</a-scene>
	</body>
</html>
```

Thanks!
Nathaniel

**Comment by banada** [comment]
This could be related to Issue #2158 

That codepen fails in the same way when I replace the box, cylinder, and sphere with my a-obj-model.

**Comment by banada** [comment]
I am able to dodge this issue using onclick to load the a-obj-model.
This suggests a race condition between the raycaster and a-obj-model.

Using window.onload or the 'DOMContentLoaded' event instead of onclick does not work.
I am also able to load the a-obj-model this way after a (relatively) long network call.

```
window.onclick = function() {
	let el = document.getElementById('scene');
	let obj = document.createElement('a-obj-model');
	obj.setAttribute('class', 'pickup');
	obj.setAttribute('src', '#dishwasher-obj');
	obj.setAttribute('mtl', '#dishwasher-mtl');
	obj.setAttribute('scale', '0.045 0.045 0.045');
	obj.setAttribute('position', '0 0 -2');
	el.appendChild(obj);
};
```

**Comment by ngokevin** [comment]
Should be fixed with new raycaster objects filtering.
