### ISSUE TITLE
Windows and Samsung Tablet Issue

### ISSUE THREAD

**Issue by sim3083** [aframevr/aframe#3360]
I asked this on the slack channel and @dmarcos advised me to open an issue.

When viewing a basic scene on a Microsoft Windows tablet (with no keyboard attached) or a Samsung tablet, I can scroll horizontally in Chrome and Firefox (but not vertically). In Edge, there is no scrolling allowed at all.

And there is no motion detection on these devices. 

If no vertical scrolling can be achieved is it possible to add a directional button to reproduce the movement?

Can this be rectified or is it just not able to work in these tablets like on an iPad at the moment?

- A-Frame Version: 0.7.0
- Platform / Device: Windows Tablet

**Comment by sim3083** [comment]
Anyone?

**Comment by dmarcos** [comment]
iPad and iPhone work fine. I don't have access to any Windows Tablet / Samsung Tablet to test. The only thing I can think of is the lack of DeviceMotion API available in the browsers running in your tablets. Does this example work? https://webvr.info/samples/03-vr-presentation.html?polyfill=1

You can add a vertical scrolling by writing your own component that implements the feature.

**Comment by sim3083** [comment]
I am charging to tablet now :) so ill let you know

Do you know of any pre-existing vertical scrolling components?

**Comment by dmarcos** [comment]
Possibly related: https://github.com/aframevr/aframe/issues/3427

**Comment by ngokevin** [comment]
"scrolling" as in camera rotation, you can modify look-controls to allow it.

"scrolling" as in 2D page, you can set `<a-scene embedded="true">`
