### ISSUE TITLE
Dynamically Attached Mouse Event Fails to Work

### ISSUE THREAD

**Issue by acm0055** [aframevr/aframe#3363]
**Description:**

When dynamically selecting and attaching a click based event listener to a plane, the event listener does not respond. It does not fire for some reason.

- A-Frame Version: 0.7.0
- Platform / Device: Firefox 58.0.1 (64-bit) (Macbook Pro)
- Reproducible Code Snippet or URL:

===================================
\<html>
    \<head>
        \<script src="https://aframe.io/releases/0.7.1/aframe.min.js"></script>
    \</head>
    \<body>
        <script>
         AFRAME.registerComponent('click', {
            init: function() {
                this.addEventListeners();
            },
           addEventListeners: function() {
              var el = this.el;

              el.addEventListener('mouseenter', function() {
                  el.setAttribute('scale', '1.25 1.25 1');
              });
         }
         });
         AFRAME.registerComponent('load', {
             init: function() {
                 temp = document.querySelector('#temp');
                 temp.setAttribute('click');
             }
         });
        </script>

        <a-scene load>
            <a-camera>
                <a-cursor>
                </a-cursor>
            </a-camera>

            <a-plane id="temp" color="red" position="0 0 -2">
            </a-plane>
        </a-scene>
    </body>
</html>
====================================

Not sure why the html code is messing up in github issues.

**Comment by acm0055** [comment]
Same problem occurs in the following scenario showing that it is not a entity loading after scene issue.

AFRAME.registerComponent('load', {
             init: function() {
                this.el.setAttribute('click');
             }
         });

...

\<a-plane id="temp" color="red" load position="0 0 -2">

**Comment by acm0055** [comment]
This issue can be closed. Maybe some documentation needs to be clarified or created.

When using setAttribute with an empty set of arguments, it must be called setAttribute('click', {})

**Comment by dmarcos** [comment]
@acm0055 Thanks. this is not A-Frame specific, it is how DOM APIs work. In order to set an attribute you need to pass a value: `el.setAttribute(“click”, “”) / el.setAttribute(“click”, {}`
