### ISSUE TITLE
Warning and stop working with Daydream at exit VR mode

### ISSUE THREAD

**Issue by arturitu** [aframevr/aframe#3366]
When exit VR., dispatch this error on every frame: 
'getFrameData must be called within a VRDisplay.requestAnimationFrame callback.'

- A-Frame Version: 0.7.0 (Date 2018-01-30, Commit #5243a56)
- Platform / Device: Google Pixel
- Reproducible Code Snippet or URL: /examples/boilerplate/hello-world

![image](https://user-images.githubusercontent.com/5744112/35669238-b34c2042-0734-11e8-8cf0-d4f635c356be.png)

**Comment by dmarcos** [comment]
This should be fixed in 0.8.2 Please reopen if it doesn’t
