### ISSUE TITLE
Objects' colors not appearing on mobile

### ISSUE THREAD

**Issue by HarlanStewart** [aframevr/aframe#3367]
We have several "Samsung Galaxy J3 Mission" phones. When using this mobile device to view any A-Frame VR scenes, including the official examples at aframe.io/examples, the objects appear black. The sky does have color. This occurs on all the devices, using any browser. This issue does not occur on my personal device which is a "Samsung Galaxy J3 Prime".

- A-Frame Version: 0.7.0
- Platform / Device: Android 7.0 / "Samsung Galaxy J3 Mission" (SM-J327VPP)
- Reproducible Code Snippet or URL:

**Comment by ngokevin** [comment]
Use `shader: flat` or `shader="flat"` for some devices with i guess older/weird chipsets
