### ISSUE TITLE
Improvement to pause/play properites

### ISSUE THREAD

**Issue by Adam4lexander** [aframevr/aframe#3373]
I think that pause/play can be changed to make the feature more useful. At the moment if I pause an entity and then open the inspector and close it again then the entity will be played. There's lots of cases where I might pause only part of the scene, such as pausing enemy spawners while the main menu is open, pausing entities in a pool, etc. In fact the current poolable component gets around this issue by wrapping the play() function and ignoring it.

If we took inspiration from Unity then each element could have a flag called: pausedSelf. When this is set true then it and all its children are paused. They remain paused even if their parents are played. Only by setting pausedSelf of that specific element to false will cause it and its children to be played.

It would be simple to create a 'paused' component implemented in a similar way to the poolable component. Any thoughts? I'm happy to pick this up

**Comment by ngokevin** [comment]
I usually have most of my components have an enabled property that I flip on/off if I want to say turn off the tick handler or return early from event listeners. Then how those are flipped are up to the application. Perhaps try as a third party component and see how it goes.

**Comment by Adam4lexander** [comment]
Ok will do, Ill just release my pause component to the registry
