### ISSUE TITLE
Broken tests due to Pointer Lock default disable

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3385]
**Description:**

https://github.com/aframevr/aframe/commit/334cd7eb7fccceb036c421dfbaa802d289cd4505 (cc @dmarcos)

**Comment by arpu** [comment]
on resent master vr-ui  is not shown and inspector does not load correct

**Comment by arpu** [comment]
my comment  have nothing to do with the Pointer Lock default -> please ignore it 
i will open a separate bug
