### ISSUE TITLE
Working on BMFont Text Component

### ISSUE THREAD

**Issue by mattdesl** [aframevr/aframe#339]
I'm currently working on implementing [three-bmfont-text](https://www.npmjs.com/package/three-bmfont-text) as a component.

It will look like this:

```html
    <a-entity bmtext="text: Hello, World!;
              font: demo/fonts/Exo2Bold.fnt"
              material="color: #66E1B4"
              position="0 2 0"></a-entity>
```

A couple problems have come up and I'm not sure whether AFrame can support it yet:

- The BMFont file specifies the path to the `map` texture, so the user should not need to specify `src` in the `material` attribute. However, it seems like AFrame expects this is the only way to set a map on a texture?
- `this.el.object3D.material.map` is undefined, so I can't even override it programmatically ? 
- Is there a way to handle async (resolve, reject) with AFrame components? Changing the font will trigger some XHRs that may or may not succeed
- Pure bitmap font is pretty useless in VR/3D, instead most users will want to use a SDF font. However, I am not sure how `material` can use a custom shader specifically for this component.
- `update()` is called immediately after `init()` with no `oldData` parameter, is that intended? 
- The default scale is huge since it is in pixel units (not world units). I could apply a scaling matrix to the geometry every time the text changes, but that is a bit expensive. Is there a way I could override this scale, maybe by attaching my text mesh to a parent Object3D with its own scaling, so that the user can expect that `scale=1.0,1.0,1.0` looks similar to the rest of their primitives
- This component expects some other defaults for `material` like `side: double` (not 100% needed but it will be the common case)

Maybe I should register a second component like `textmaterial`, `bmmaterial` or `bm-material` (is that valid HTML?), so that I can listen to changes in `color` and trigger updates in my custom SDF shader.

**Comment by ngokevin** [comment]
Material is undefined unless it's explicitly added by a component. We can do it through the DOM. Here's an encapsulated approach.

```js
init: function () {
  el.setAttribute('material', 'map', fontMap);
  el.setAttribute('material', 'side', 'double');
  el.addEventListener('componentchanged', function (evt) {
    if (evt.detail.name === 'material' && 'color' in diff(evt.detail.oldData, evt.detail.newData)) {
      updateSDFShader()  
    }
  });
}
```

I think it's up to you whether you want that in a new separate material component or within the font component, depending on use cases.

- A-Frame Core has Promise polyfills in the bundle.
- The `update()` called after `init()` is intended. The no `oldData` parameter is expected, but I'm up for suggestions to improve the API there.
- Nesting within another Object3D and internally scale sounds good.

**Comment by dmarcos** [comment]
Nice! Two things:
1.Components can declare dependencies. We use the mechanism on the cursor component:

https://github.com/aframevr/aframe-core/blob/master/src/components/cursor.js#L11

2. I think we should open a new repo ```aframe-components``` with a curated list of cool components that people can contribute to. The BMFont component could be a good first candidate

**Comment by ngokevin** [comment]
We have an API to register custom materials and shaders now!
