### ISSUE TITLE
fill = backwards makes material.color animation fail: THREE.Color: Unknown color #NaNNaNNaN

### ISSUE THREAD

**Issue by g0dd4rd** [aframevr/aframe#3393]
**Description:**
while fill = backwards in a-animation, material.color fails to render properly,
throwing THREE.Color: Unknown color #NaNNaNNaN error

- A-Frame Version: 0.7.0
- Platform / Device: fedora 27, firefox 58, x86_64
- Reproducible Code Snippet or URL:
http://www.dredwerkz.cz/aframe/burstbubbles.html

**Comment by ngokevin** [comment]
Try https://github.com/ngokevin/kframe/tree/master/components/animation

**Comment by ngokevin** [comment]
We've deprecated a-animation. Try https://github.com/ngokevin/kframe/tree/master/components/animation and file issues, and component will be merged in in the future.
