### ISSUE TITLE
No documentation available for pivot component

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#3395]
There doesn't appear to be any documentation for the `pivot` component. I actually just stumbled upon it today while inspecting the examples more closely. I thought maybe it was a custom component since I didn't recall ever seeing it in the docs, but nope. Seems to be a native component.

**Comment by dmarcos** [comment]
pivot is deprecated, that's why you don't see in the documentation. We kept it around for the few that were still using it before removal. I don't recommend relying on it.

**Comment by dsinni** [comment]
@dmarcos: Ah, okay. My mistake then. Thanks.

**Comment by theraccoonbear** [comment]
@dmarcos is there an alternative that should be used, or are there no out-of-the-box solutions for rotating an object around a point other than its own center?
