### ISSUE TITLE
Laser component points 45deg to the left

### ISSUE THREAD

**Issue by adammarcwilliams** [aframevr/aframe#3396]
I added the laser component to my right hand and it points about 45deg to the left of where it should.

[A-frame Laser pointing 45deg to the left](https://i.stack.imgur.com/R5PVh.jpg)

In this image I am pointing at the blue box above the tower using an Oculus Touch controller. As you can see the hand is pointing correctly and feels like it matches my real life hand position quite well but the laser is going about 45deg to the left.

If I rebuild the functionality of the laser component using a raycaster and a cursor component it works fine so I believe it to be a bug with the laser component itself.

- A-Frame Version: 0.7.1
- Platform / Device: Firefox Quantum 58.0.2 (64-bit) / Oculus Rift
- Reproducible Code Snippet or URL:  `<a-entity id="pointerHand" hand-controls="right" laser-controls></a-entity>`

**Comment by ngokevin** [comment]
`hand-controls` rotates the model a bit. It doesn't play well with laser-controls. 

Hand-controls are more for when you using pure 6DoF, laser-controls when you want support both 6DoF/3DoF. You can manually set the raycaster origin/direction in this case if you want to combine both.

Tell me if this is not the case. Thanks!

**Comment by adammarcwilliams** [comment]
Tried manually setting the raycast direction like this and it had no effect (tried a few different vectors, nothing changed):
`<a-entity id="pointerHand" hand-controls="right" laser-controls raycaster="direction: 0 0 0"></a-entity>`

I also tried the laser-control on it's own which fixes this issue (the laser points in the correct direction in relation to the controller model) but the Oculus controller models rotation doesnt match it's position in reality making you feel like you're waving around a broken wrist which you have to contort to select things.  I believe thats been well documented by other here in this issue: https://github.com/aframevr/aframe/issues/2965

I've managed to recreate the functionality I need by combining hand-controls, curors and raycaster together although I only get mouseenter/mouseleave on this pointer but I can work around that.

**Comment by ngokevin** [comment]
Yeah I think either copy/patching laser-controls is appropriate here since it's taking a path of combining with hand-controls. 

Can't set raycaster straight up because laser-controls will overwrite it on `controllerconnected` event. You could write a component that waits for laser-controls to set the raycaster, and then you overwrite that and set the raycaster.

**Comment by TitoVelasquez** [comment]
> Tried manually setting the raycast direction like this and it had no effect (tried a few different vectors, nothing changed):
> `<a-entity id="pointerHand" hand-controls="right" laser-controls raycaster="direction: 0 0 0"></a-entity>`
> 
> I also tried the laser-control on it's own which fixes this issue (the laser points in the correct direction in relation to the controller model) but the Oculus controller models rotation doesnt match it's position in reality making you feel like you're waving around a broken wrist which you have to contort to select things. I believe thats been well documented by other here in this issue: #2965
> 
> I've managed to recreate the functionality I need by combining hand-controls, curors and raycaster together although I only get mouseenter/mouseleave on this pointer but I can work around that.

how did you make it change direction? Currently struggling with it and I have no idea how to change the direction of the laser in any way whatsoever. Direction on the raycaster doesn't do anything at all.
