### ISSUE TITLE
aframe 创建自定义实体只能通过导入3d模型吗

### ISSUE THREAD

**Issue by empty-back** [aframevr/aframe#3397]
**Description:**
看了几天aframe 文档，想请教两个问题：
1.aframe如何创建一个自定义实体，例如一个工件，或者一个建筑之类的，只能通过maya、Blender之类的导出3d模型再导入到aframe吗，可以用aframe直接编码得到吗
2.aframe的点击事件只能是<a-camera>配合<a-cursor>模拟点击事件吗，如何通过获取实体dom，直接绑定事件
谢谢！
- A-Frame Version: 0.7.0
- Platform / Device: windows7
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Can someone translate :D ?

**Comment by dmarcos** [comment]
Google translate hints a problem with click events on 3D models but that's everything I can extract

**Comment by jason90929** [comment]
a simple translate:
1. How do aframe create a custom thing like a building or something, I can only render a 3d model to aframe from maya or Blender. Can I just use aframe code to get a model directly?
2. How do I use aframe to get a physical dom, to combine with event? Thanks!

**Comment by ngokevin** [comment]
Good questions for Stackoverflow

1. see model docs
2. there's cursor="rayOrigin: mouse", otherwise no
