### ISSUE TITLE
Docs master left menu does not contain links to individual component docs

### ISSUE THREAD

**Issue by mkungla** [aframevr/aframe#3398]
**Description:**

Seems that https://aframe.io/docs/master left menu does not contain links to individual component docs

- A-Frame Version: master
- Platform / Device:  Firefox DE
- Reproducible Code Snippet or URL: https://aframe.io/docs/master

**Comment by ngokevin** [comment]
Try https://github.com/ngokevin/kframe/tree/master/components/animation

**Comment by ngokevin** [comment]
Will redeploy.

**Comment by mkungla** [comment]
@a-frobot  docs-v0.7.0 _misbehaves_

**Comment by mkungla** [comment]
actually `0.7.0` is fine `master` is a issue

**Comment by rockwalrus** [comment]
Now the `0.8.0` docs are broken.

**Comment by mkungla** [comment]
@ngokevin what is the state of this issue? redeploy failed as I see.
