### ISSUE TITLE
VR Mode

### ISSUE THREAD

**Issue by proyb6** [aframevr/aframe#340]
Does this works as a VR HMD?

**Comment by dmarcos** [comment]
If you have an Oculus or Cardboard you can use it with a-frame. Does this answer your question?

**Comment by jcarpenter** [comment]
Documentation on using A-Frame sites with VR devices is here: https://aframe.io/docs/guide/entering-vr.html

**Comment by cvan** [comment]
Kindly closing as the question was answered. If there's anything else you need, please do let us know. Thanks!
