### ISSUE TITLE
Faces not being culled

### ISSUE THREAD

**Issue by benjaminleonard** [aframevr/aframe#3402]
Faces, vertices, and draw calls remain the same even when the object can no longer be seen

- A-Frame Version: 0.7.1
- Platform / Device: Google Chrome Desktop
- Reproducible Code Snippet or URL:
https://canyon-lentil.glitch.me/ (0.7.0 – works as expected)
https://canyon-lentil.glitch.me/alt.html (0.7.1 – faces, vertices, and draw calls stay constant)

**Comment by ngokevin** [comment]
How about 0.8.0?

**Comment by benjaminleonard** [comment]
Fixed now, thanks!
