### ISSUE TITLE
Line not being updated correctly

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe#3403]
**Description:**

On the following example: https://glitch.com/edit/#!/inconclusive-thrill I'm updating the line between to spheres:
```
line.setAttribute('line', {start: posL, end: posR});
``` 
It doesn't work as expected, but If I add `debug: true` to the scene, it works.

I guess it's something related to the latest changes to optimize the set/getAttribute?

**Comment by fernandojsg** [comment]
It works if I do:
```
    line.setAttribute('line', {start: posL.clone(), end: posR.clone()});
```

**Comment by dmarcos** [comment]
We save the reference to those objects in the `component.data` and when modified externally and passed to `setAttribute` the comparison with the old value will return that old and new are equal and the update method won't be called. The strange thing is that we have not caught this bug before. Does it reproduce on 0.7.1?
