### ISSUE TITLE
Get Camera Rotation Issue

### ISSUE THREAD

**Issue by CPSuperstore** [aframevr/aframe#3405]
**Description:**
I am running the following snippet in a while loop:
`alert(document.getElementById('camera').getAttribute('rotation'));`

This is camera:
`<a-camera id="camera" position="0 0 0" rotation="0 0 0">
    <a-entity id="marker" position="0 15 0"></a-entity>
    <a-plane src="images/cursor.png"  position="0 0 -4" rotation="0 0 0" width="4" height="4"  material="opacity: 1.0; transparent: true"></a-plane>
</a-camera>`

The first time through, it creates the alert box "0 0 0" as it should (the default camera rotation).
Then it will start returning "[object Object]"

I seem to be the only person on the internet to have this problem. I made this conclusion after many hours of tinkering, and searching the web.

- A-Frame Version: 0.7.0
- Platform / Device: Windows 10 x64bit

**Comment by donmccurdy** [comment]
Hi @CPSuperstore — before A-Frame has loaded, `getAttribute()` just just the plain HTML method, which always returns a string. After it loads, it returns a JavaScript Object that is much easier to work with. If you want to log the camera's rotation you should wait until the scene has loaded and then do one of these:

```js
var rot = el.getAttribute('rotation');
console.log( rot );
alert( rot.x + ' ' + rot.y + ' ' + rot.z );
```
