### ISSUE TITLE
Colision Detection

### ISSUE THREAD

**Issue by CPSuperstore** [aframevr/aframe#3406]
**Description:**

I am having problems developing collision systems between a sphere and plane. I have tried many different work arroumds, including generating a hitbox from points and dimensions without any luck.

There seems to be no docs on collision either.

If someone could give me a hand, that would be much appriciated.

- A-Frame Version: 0.7.0
- Platform / Device: Windows 10 x64

**Comment by dmarcos** [comment]
Thanks for filing. A-Frame itself does not cover collision detection. This is a question more appropriate for StackOverflow. We use Githug issues for bugs and feature requests.

**Comment by dmarcos** [comment]
To get a good answer on StackOverflow you will have to provide code samples and more details about the different solutions / approaches you tried.

**Comment by ngokevin** [comment]
https://www.npmjs.com/package/aframe-aabb-collider-component
