### ISSUE TITLE
Bug embedded scene mouse cursor ray-origin

### ISSUE THREAD

**Issue by tiagoernst** [aframevr/aframe#3410]
**Description:**

- A-Frame Version: 0.7.1 , 0.7.0
- Platform / Device: Desktop chrome version 64.0 .
- Reproducible Code Snippet or URL: 

//code starts here 
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Embeded scene mouse cursor bug</title>
    <script src="https://aframe.io/releases/0.7.1/aframe.min.js"></script>
  </head>
  <body style='height:800px;width:100%;'>
    <div class="" style='height:250px;width:450px;margin-left:100px;margin-top:300px;background-color:black'>
      <a-scene embedded='true' cursor="rayOrigin: mouse">
        <a-box id='box' position='0 0 -5' color='red'>   </a-box>
        <a-sky color='blue'></a-sky>
        <a-camera  >
        </a-camera>

      </a-scene >
      <script type="text/javascript">
          var box =document.querySelector('a-box');
          box.addEventListener('mouseenter',function(){
            this.setAttribute('scale','2 2 2')
          });
          box.addEventListener('mouseleave',function(){
            this.setAttribute('scale','1 1 1')
          });
      </script>
    </div>
  </body>
</html>

explanation :
There seems to be a bug with the embedded scene and the option of mouse cursor (rayOrigin: mouse),
i've put an mouseenter and mouseleave event on a box to change it's size. It works fine as long as the page is contained in the browser, but when the page is "scrollable" the events get messed up ( like showed in the gif). I don't know if I messed up somewhere but it seems that it comes from Aframe .

![bug_emebedded_scene](https://user-images.githubusercontent.com/29782161/36857031-c5060b00-1d77-11e8-987b-4fd8c7704185.gif)

**Comment by tiagoernst** [comment]
<a-scene embedded='true' cursor="rayOrigin: mouse">
        <a-box id='box' position='0 0 -5' color='red'>   </a-box>
        <a-sky color='blue'></a-sky>
        <a-camera  >
        </a-camera>

   </a-scene >

PS : html code

**Comment by tiagoernst** [comment]
body style='height:800px;width:100%;'>
    div class="" style='height:250px;width:450px;margin-left:100px;margin-top:300px;background-color:black'>
      a-scene embedded='true' cursor="rayOrigin: mouse">
        a-box id='box' position='0 0 -5' color='red'>   </a-box>
        a-sky color='blue'></a-sky>
        a-camera  >
        /a-camera>

      /a-scene >

PS : html code wasn't appearing (took off the '<' for it to be visible )

**Comment by mkungla** [comment]
indeed it is a bug: `/examples/test/embedded-cursor/` add style

```css
body {
  height:200vh;
}
```

and as you can see `raycaster` don't check scroll changes so your clicks get scroll offset

**Comment by viperphase1** [comment]
I'm getting the same issue. If the scene is off screen and then moved on screen you'll never be able to interact with the objects in the scene.
