### ISSUE TITLE
enterVR function does not work in setTimeout

### ISSUE THREAD

**Issue by pie-d** [aframevr/aframe#3414]
Calling `document.querySelector('a-scene').enterVR()` from within `setTimeout` does not work on Chrome for Android . Throws:

```
webvr-polyfill.js:6442 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
M.release @ webvr-polyfill.js:6442
A @ webvr-polyfill.js:1308

a-scene.js:178 Uncaught (in promise) Error: Failed to enter VR mode (`requestPresent`): Unable to present.
    at i (a-scene.js:178)
    at <anonymous>
```

and aframe does not enter in VR mode.

Actual code:

```
setTimeout(function(){
    document.querySelector('a-scene').enterVR();
}, 2000);
```

Although, if I type `document.querySelector('a-scene').enterVR();` from console, it works as expected.  

On Chrome (version 64.0.3282.186) for Linux (Elementary OS 0.4.1 based on Ubuntu 16.04): If I try this from `setTimeout`, aframe does enter in VR mode but not in fullscreen, from console without `setTimeout` it works as expected

- A-Frame Version: 0.7.0
- Platform / Device: Chrome on Android and Linux version 64.0.3282.137
- Reproducible Code Snippet or URL: https://codepen.io/JFarrow/full/pNmdXa/ (same issue happens on any web page)

If you need any more information pardon me and please ask.  
Thanks, a lot for this library.

**Comment by dmarcos** [comment]
You cannot enter vr automatically. it has to be triggered by user gesture like a mouse click.

**Comment by dmarcos** [comment]
Forgot to say `thanks for filing`, sometimes things pile up and one needs to cut corners 🙂

**Comment by pie-d** [comment]
Hi,  
Is it possible to delay entering vr moding after user clicks on enter-vr button?  
Thanks...

**Comment by fmagrosoto** [comment]
Hello every one...
I tried to load my scene in VR mode using enterVR() within a component:

```
AFRAME.registerComponent('do-something', {
  init: function () {
    var sceneEl = this.el;
   sceneEl.enterVR()
  }
});
```

**In Chrome for iOS (77.0.8685.103) works fine**, but in **Android, same Chrome version, do not works**... anybody has a solution?, or maybe an explanation?

By the way, Firefox for iOS or Android has the same issue. Does not work.

Thanks in advance

**Comment by dmarcos** [comment]
auto-entering VR (fullscreen in iOS) is not allowed by browser policies. It has to be triggered by a user gesture like a click or tap hence the need of a button.

**Comment by fmagrosoto** [comment]
Thanks. I understand but something is weird. Chrome on iOS works fine (just Chrome 77.x.x or previuos), Chrome for iOS +78.x.x does not work... But on Android, either Chrome and Firefox, and Firefox and Safari on iOS, does not works at all, even if a turn back the world. The question is, why Chrome for iOS works?

I been used the component describe above.

Weird, right?

**Comment by dmarcos** [comment]
Chrome for iOS might not be applying the [standard policy](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen)

**Comment by fmagrosoto** [comment]
Thank you, I will take it into account for future developments.

**Comment by fmagrosoto** [comment]
By the way...
I am developing a web app showing different 360 photos.

Everything was working great until version 78 of Chrome for iOS arrived and stopped working. The cardboard mode does not function anymore. I mean, one day, everything works properly, next day, the carboard mode stop to work. Same thing in version 78 of Chrome for Android.
Is the Chrome version who makes this mess?

**Comment by dmarcos** [comment]
Browsers are starting to enforce user gesture as well to access the motion sensors (DeviceMotionEvents). More context: https://github.com/aframevr/aframe/issues/4287

**Comment by fmagrosoto** [comment]
**Thank you.** I used the code that appears later. It works perfectly well in Chrome, Safari and Firefox for iOS. Is there a similar alternative for Android?

This is the code I used:

```
<button type="button" class="miBoton">
      Permisos
</button>
    
    <script>
    var miBoton = document.querySelector('.miBoton');
    miBoton.addEventListener('click', function () {
      DeviceMotionEvent.requestPermission().then(response => {
        if (response == 'granted') {
          window.addEventListener('devicemotion', (e) => {
          window.location.assign('/');
        })
      }
    }).catch(console.error)
   }, false);
      
    </script>
```

I understand iOS 13 require some permissions to works.
Any solution for Android works properly?

Thanks again.
