### ISSUE TITLE
Sound component causes DOM memory leak on page reload

### ISSUE THREAD

**Issue by Adam4lexander** [aframevr/aframe#3415]
If theres a Sound component in the scene the DOM memory is leaked on page reload. This is happening for me on chrome.

To reproduce load the anime-ui example in chrome and open the dev tools with performance monitor. Keep reloading the page and observe the number of dom nodes increasing. If the Sound components are removed from the scene then the dom nodes are garbage collected correctly.

**Comment by arpu** [comment]
where can i see the dom nodes? i try to reproduce the Problem
 https://aframe.io/aframe/examples/showcase/anime-UI/   (aframe aframe-master.min.js:569 A-Frame Version: 0.8.0 (Date 2018-03-09, Commit #c4f2425)
and chrome 65.0.3325.181 (Offizieller Build) (64-Bit)

for me the performance test looks normal

**Comment by Adam4lexander** [comment]
![image](https://user-images.githubusercontent.com/16426184/38341811-d948bb60-38bd-11e8-9cbd-3baf0fcdb9fa.png)

The DOM nodes are being dropped from the page but they're not being garbage collected. When reloading the page the whole aframe scene is being kept in memory. Eventually the browser tab will crash.

**Comment by Adam4lexander** [comment]
Still occurring for me with A-Frame Version: 0.8.0 (Date 2018-03-09, Commit #c4f2425)

**Comment by Adam4lexander** [comment]
This seems to be fixed now in 0.8.1 and 0.8.2. Cannot reproduce anymore. Im gonna close.
