### ISSUE TITLE
A-Frame master culling issues

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3416]
**Description:**

Everything is disappearing unless at the very edge of my right eye.

See latest: https://a-frobot.github.io/aframe/examples/boilerplate/hello-world/

**Comment by ngokevin** [comment]
Broken after three.js bumps

https://github.com/aframevr/aframe/commit/56dc163e23bec610c46506b22818a5ed84678b69

or 

https://github.com/aframevr/aframe/commit/5f196765f329b9478b75fb5a9f5620eb3302812f

**Comment by brianpeiris** [comment]
@dmarcos Looks like the builds aren't updated on the branch that aframe/master is currently pointing to: 
https://github.com/dmarcos/three.js/tree/r90vrfix/build

**Comment by brianpeiris** [comment]
Looks like this is resolved now?

**Comment by ngokevin** [comment]
Yeah
