### ISSUE TITLE
How can I load a 3d model in Aframejs? It currently works fine in threejs

### ISSUE THREAD

**Issue by omkarkhalipe** [aframevr/aframe#3419]
I have created a 3d animated model, which I managed to run in threejs
```
 var loader = new THREE.FBXLoader();
        loader.load( 'model.fbx', function ( object ) {

            object.mixer = new THREE.AnimationMixer( object );
            mixers.push( object.mixer );
           console.log(object.animations.length);
            var action = object.mixer.clipAction( object.animations[ 0 ] );
            action.play();

            object.traverse( function ( child ) {

                if ( child.isMesh ) {

                    child.castShadow = true;
                    child.receiveShadow = true;

                }

            } );

            scene.add( object );

        } );
```
It works perfectly on threejs, but how can I use it in aframe, I am trying to create AR app.
I am not getting enough documentation, in AFrame I can display obj model on marker but aframe-extras doesn't seem to work, but Threejs FBX loader works fine.

**Comment by dmarcos** [comment]
Thanks for filing. This is more appropriate for StackOverflow. We use github issues for bugs and feature requests

**Comment by omkarkhalipe** [comment]
https://stackoverflow.com/questions/49136441/how-can-i-load-a-3d-model-in-aframejs-it-currently-works-fine-in-threejs
I have asked here, hope someone can help here too
