### ISSUE TITLE
add missing three.js constructor options to geometry component

### ISSUE THREAD

**Issue by jan-thoma** [aframevr/aframe#3421]
For example three.js Box Geometry Constructor has some additional arguments to control the number of vertices which comes in handy when using displacement maps. It would be great if the geometry component could reflect the overall constructor options from three.js

**Comment by ngokevin** [comment]
Thanks for filing. In these cases where you need to interact more with three.js, I'd just create the geometry you need in a component. Like...

```
AFRAME.registerComponent('my-box-geometry, {
  schema: {
    width: {default: 1},
    height: {default: 1},
    depth: {default: 1},
    vertices: {default: 8}
  },

  init: function () {
    var geometry = new THREE.BoxGeometry(data.width, data.height, data.depth);  // etc.
    var mesh = this.el.getObject3D('mesh');
    if (mesh) {
      mesh.geometry = geometry;
   } else {
     mesh = new THREE.Mesh();
     mesh.geometry = geometry;
     this.el.setObject3D('mesh')
   }
  }
});
```

**Comment by jan-thoma** [comment]
I'm aware that i can register my own custom components. Creating primitives this way is no problem so far. 

We are working on a collaborative online editor/viewer based on aframe and meteor. The user needs to be able to changes various settings of the primitives on the fly. If we need to drop the current mesh and create a new one, the material drops too. I didn't found any hint in the docs how update custom geometries correctly.

**Comment by ngokevin** [comment]
Geometries aren't updated in A-Frame. They are recreated. If you receive an update to the geometry, update the mesh `mesh.geometry = newGeometry`.

**Comment by jan-thoma** [comment]
Ok thanks this is eventually working

````
AFRAME.registerComponent('box-custom',
{
    schema:
    {
        width: {default: 1},
        height: {default: 1},
        depth: {default: 1},
        widthSegments: {default: 1},
        heightSegments: {default: 1},
        depthSegments: {default: 1},
    },
    init ()
    {
        this.createOrUpdateGeometry = (data, el) =>
        {
            const geometry = new THREE.BoxBufferGeometry(data.width, data.height, data.depth, data.widthSegments, data.heightSegments, data.depthSegments)
            var mesh = el.getObject3D('mesh')

            if (mesh)
            {
                mesh.geometry = geometry
            }
            else
            {
                mesh = new THREE.Mesh()
                mesh.geometry = geometry
                el.setObject3D('mesh', mesh)
            }
        }

        this.createOrUpdateGeometry(this.data, this.el)
    },
    update ()
    {
        this.createOrUpdateGeometry(this.data, this.el)
    }
})
````

**Comment by ngokevin** [comment]
Oh, if you only need the segments properties. We would appreciate a PR to `src/geometries/box.js`! It would be a simple add. Sorry for the chase, I had mindset of doing most stuff in components so whenever I need something, I just make a component.

**Comment by jan-thoma** [comment]
I just saw it was just missing in the docs (geometry.md) see #3426.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/3426
