### ISSUE TITLE
How to hack the iOS >=9.2 WebKit limitation that blocks deviceorientation and devicemotion events access from cross-origin iframes?

### ISSUE THREAD

**Issue by gino8080** [aframevr/aframe#3422]
With iOS 9.2 WebKit now blocks deviceorientation and devicemotion event access from cross-origin iframes. [bug link](https://bugs.webkit.org/show_bug.cgi?id=152299)

- A-Frame Version: latest
- Platform / Device: Ios webkit >= 9.2

as a dirty solution I was thinking about using the iframe postMessage to send devicemotions to the child iframe
something like this:

Father page 
```javascript
if (window.DeviceMotionEvent) {

        /* Add a listener for the devicemotion event */
        window.ondevicemotion = function (deviceMotionEvent) {

            /* Get acceleration on x, y and z axis */
            var x = deviceMotionEvent.accelerationIncludingGravity.x;
            var y = deviceMotionEvent.accelerationIncludingGravity.y;
            var z = deviceMotionEvent.accelerationIncludingGravity.z;
            
             var coordinates = deviceMotionEvent.accelerationIncludingGravity;
            console.log(coordinates)
            /* Get the interval (ms) at which data is obtained from the underlying hardware */
            
            //send the accleration coordinates from parent to child iframe 
            //"*" used to avoid cors protection
            jQuery("#myChildIframe")[0].contentWindow.postMessage(coordinates, '*');
}
```

Children iframe 
```javascript
window.onload = function () {
    window
        .addEventListener('message', function (e) {
           //e.data are the accelerometer from father
           //now how to pass the devicemotions coordinates to aframe??
           
        })
}
```
but how to send the father devicemotion coordinates to the child iframe aframe?

**Comment by calrk** [comment]
You could try something like the following and see if it works for you.
```
...

.addEventListener('message', function (e) {
    var event = document.createEvent('Event');
    event.initEvent('ondevicemotion', true, true);

    event.accelerationIncludingGravity = e.data;

    window.dispatchEvent(event);
});

...
```

**Comment by dmarcos** [comment]
Thanks foe filing. I suggest reopening this question on StackOverflow. We use issues for bugs and feature requests.

**Comment by jdreetz** [comment]
There's an example of how to resolve this in the `cardboard-vr-display` repo. Turns out `FusionPoseSensor` already listens for fake devicemotion events using postmessage, you just have to send them with the right formatting - https://github.com/immersive-web/cardboard-vr-display/blob/master/examples/iframe.html
