### ISSUE TITLE
Raycaster Event Intersection Object Not Documented

### ISSUE THREAD

**Issue by rockwalrus** [aframevr/aframe#3430]
**Description:**

- A-Frame Version: 0.8.0

The `intersection` property in the event details for `raycaster` is not documented. From looking at the code, they appear to be the raw [three.js intersectObjects results](https://threejs.org/docs/index.html#api/core/Raycaster.intersectObject).  Without documentation it's impossible to know which fields are intended to be part of the supported API.

**Comment by vincentfretin** [comment]
About documentation of 0.8.0, it should be noted the intersection behavior has changed significantly in 0.8.0, the raycaster only emit the start of intersections, so if you previously used in 0.7.1 the event to show a ring on a plane like it's done in https://urish.github.io/web-ar-experiment/ you apparently need something like this https://github.com/aframevr/aframe/issues/3129#issuecomment-334779820 now. I didn't test this code yet. @ngokevin This probably should be referenced in the 0.8.0 changelog.

**Comment by ngokevin** [comment]
Okay I will update the changelog to note the breaking changes and migration requirements.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/ea836cffe7a994882f17024e97d934ca2860be8e
