### ISSUE TITLE
a-animation isn't triggered by state change

### ISSUE THREAD

**Issue by murasakikyabetsu** [aframevr/aframe#3436]
a-animation refers `evt.detail.state` in `onStateAdded` and `onStateRemoved`.
`addState` always sets a state value to `detail` of `emit` and it passed to onStateXXX as `evt.detail`.
So, the state is set to `evt.detail` and `evt.detail.state` is seemed always `undefined`.
This isn't an expected behavior, is it?

- A-Frame Version: master

**Comment by ngokevin** [comment]
Yeah, it changed to `evt.detail` to not have to create an object. I will update the release notes / change log. Thanks!

**Comment by murasakikyabetsu** [comment]
This topic closed but the issue hasn't been fixed yet in master e3d8975.
a-animation still checks `evt.detail.state` which is `undefined`.
Would you like me to make a pull request?
