### ISSUE TITLE
Make an example for sound component

### ISSUE THREAD

**Issue by cemkod** [aframevr/aframe#344]
Sound component was added in https://github.com/aframevr/aframe-core/pull/326/files . There are no examples on how to use it. Do we need changes to templates to be able to use it?

**Comment by jcarpenter** [comment]
Thanks for filing this, @cemkod. We weren't able to do this before launch. In interim you should be able to use the sound component on an `<a-entity>`. Docs are here: https://aframe.io/docs/components/sound.html

**Comment by cvan** [comment]
FWIW, in [aframe-core](https://github.com/aframevr/aframe-core/), we do have a example, the [Pano Explorer](https://github.com/aframevr/aframe-core/blob/1d07db6e/examples/panoexplorer/index.html#L17-L21), which makes use of the `sound` component. _(sidenote: those examples are not hosted online unfortunately [originally to minimise the size of the git checkouts]; see aframevr/aframe-core#689.)_

**Comment by cvan** [comment]
I would probably file an issue to have a sound example added to the site though: https://github.com/aframevr/aframe-site

There is a PR (#362) to merge aframe-core into this repo, so we would inherit the example with sound (Pano Explorer). But, IMO we should have an example dedicated purely to "sound" - hopefully nicely demonstrating positional sound. So, I would reopen this if you don't mind.

**Comment by cemkod** [comment]
I reopened the issue with comments from @cvan here: https://github.com/aframevr/aframe-site/issues/131
