### ISSUE TITLE
Invisible controllers

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#3441]
**Description:** Controllers activated via `vive-controls` component do not appear, but are otherwise fully functional. The models appear to be present, but fully transparent, as seen in the screenshot below where the transparency sorting issue causes them to make vive controller shaped holes in the torus knot behind them

- A-Frame Version: v0.8.0
- Platform / Device: Vive/FF
- Reproducible Code Snippet or URL: https://wmurphyrd.github.io/aframe-super-hands-component/examples/#events

![20180311211348_1](https://user-images.githubusercontent.com/10034859/37263227-1da7da18-2575-11e8-9ad5-25616722e706.jpg)

**Comment by wmurphyrd** [comment]
Narrowed it down to the `obj-model` rather than the controller component

https://glitch.com/edit/#!/reflective-stone

**Comment by wmurphyrd** [comment]
Also having this issue with some other `obj` files, but not all.

**Comment by RSpace** [comment]
I also have issues with some obj files, namely those using mtl files. Are you seeing this error in the console?

``
THREE.WebGLRenderer: .shadowMap.renderReverseSided has been removed. Set Material.shadowSide instead.
aframe-v0.8.0.js:50683:5
THREE.WebGLRenderer: .shadowMap.renderSingleSided has been removed. Set Material.shadowSide instead.
``

Then it's probably related to the issue described here: https://github.com/aframevr/aframe/issues/3428 - although it's currently not clear to me what the fix  for obj models is.

**Comment by RSpace** [comment]
Hm this `.shadowMap.renderReverseSided` warning seems to have nothing to do with transparent objs after all. Still there without any objs. A general issue in A-Frame 0.8.0 it would seem.

**Comment by RSpace** [comment]
Seems be a pretty bad bug in Three.js recently introduced by this commit: https://github.com/mrdoob/three.js/commit/ad9093801bbb48c919b82e8514a175d8c26c537d#diff-5f35124cf2254142299033b1b52ef2b8L465

Now any obj model using a material file with `Tr` specified for a material, will get the reverse effect - in most cases a completely transparent or "invisible" material.

It's fairly easy to fix, but this has to happen in Three.js. See my comment here:
https://github.com/mrdoob/three.js/pull/12862#issuecomment-375260770

**Comment by RSpace** [comment]
For anyone that need a quick work around while this is being fixed in Three.js and then rolled into A-Frame, you can add this to your `package.json`:

```
  "resolutions": {
    "three": "github:RSpace/three.js#fixMtlLoader"
  }
```

**Comment by donmccurdy** [comment]
Moving this to milestone 0.9.0 as the fix will require updating three.js. The alternative would be to include a patched version of `THREE.MTLLoader` without updating the rest of three.js. I think we should get 0.8.2 released without waiting for that, but would not be opposed to doing 0.8.3 with this fix if it seems urgent enough.

**Comment by RSpace** [comment]
I think this issue and https://github.com/aframevr/aframe/issues/3488 are two very critical issues in the current version of A-Frame. This issue at least have a work around by forcefully upgrading Three.js version, but the other one breaks many VR experiences quite badly. Getting out an 0.8.3 with those two issues fixed would certainly by worth in my opinion.

**Comment by joduffy** [comment]
Any news on when this Obj transparent issue will be fixed?

I was just wrapping up a project when this bug hit, and now it's sitting in limbo with a deadline approaching.

**Comment by donmccurdy** [comment]
+1 from me.

**Comment by dmarcos** [comment]
I bumped THREE on master with the commit of the MTL loader fix. @wmurphyrd can you verify that it's working now? https://github.com/aframevr/aframe/commit/5d30e926859cf31129b2a5b101db14bca0d78c13

@donmccurdy nice new gravatar picture 😎

**Comment by wmurphyrd** [comment]
@dmarcos it works. Thank you!

**Comment by joduffy** [comment]
After a long time research, and trial and error. I found a solution.

It involves using gltf exporter from Blender and the PBR (material node editor) in Blender with the Cycles Render.

The solution can be found here:

https://github.com/aframevr/aframe/issues/3234
