### ISSUE TITLE
a-videosphere broken in 0.8.0

### ISSUE THREAD

**Issue by Matukas123** [aframevr/aframe#3444]
**Description**:

 a-videosphere shows all white instead of playing video.  Worked previously on 0.7.0

Console warnings say:
THREE.WebGLRenderer: .shadowMap.renderReverseSided has been removed. Set Material.shadowSide instead.
THREE.WebGLRenderer: .shadowMap.renderSingleSided has been removed. Set Material.shadowSide instead.

- A-Frame Version:
 0.8.0
- Platform / Device:
Chrome & Firefox / Windows

- Reproducible Code Snippet or URL:

A-Frame's videosphere example from homepage modified to use 0.8.0:
Result: https://somber-scribe.glitch.me
Code: https://glitch.com/edit/#!/join/a2477d73-d71c-46ee-b127-4cf4f8700ab5

Potentially related to #3428

**Comment by jbreckmckye** [comment]
Having the same issue with skyboxes.

**Comment by machenmusik** [comment]
Note, just tried that glitch and it works on Samsung Internet and Chrome on S8 (after click to play)

**Comment by machenmusik** [comment]
Maybe this fixed it?  https://github.com/aframevr/aframe/issues/3428#issuecomment-372123237

**Comment by Matukas123** [comment]
Forgot to lock the glitch example; link updated above.

**Comment by machenmusik** [comment]
Ok, can see that it is broken but now can't see the source.  Multi-source version works but I assume you did not update the aframe version on that page

**Comment by machenmusik** [comment]
Can you try this? https://github.com/aframevr/aframe/issues/3428#issuecomment-372079493

**Comment by machenmusik** [comment]
@dmarcos @ngokevin FYI this is reproducible against master, you need to add `material="side:back"` (or double) to make it display correctly... see https://glitch.com/edit/#!/pepper-saxophone?path=index.html:6:0

**Comment by Matukas123** [comment]
Thanks @machenmusik  for looking into it :).   Might not be as relevant anymore but I did go back as per your suggestion to give the a-entity workaround a try and it works too:   https://glitch.com/edit/#!/accurate-daffodil?path=index.html:19:17

**Comment by machenmusik** [comment]
@dmarcos looks like we need the equivalent of https://github.com/aframevr/aframe/commit/ef810c2b924646808b5daf3edd3613a31db3bdb9 for `a-videosphere` as well

**Comment by machenmusik** [comment]
Thanks @ngokevin!
