### ISSUE TITLE
0.8.0 Raycaster Issue: Multiple intersected interactive elements along ray path

### ISSUE THREAD

**Issue by PButcher** [aframevr/aframe#3445]
I've been sitting on this problem for a couple of hours now and can't put my finger on what exactly is going on under the hood to cause the issue but the symptoms are easy to reproduce:

https://codepen.io/PButcher/pen/PRZGRr

Move the mouse cursor down over the blue plane (which sits behind the red plane), on to the red plane, then move the cursor left across the face of the red plane until the raycaster is not intersecting with the blue plane, then move the cursor back to the right. The raycaster emits a `mouseleave` and `mouseenter` event on the red plane as well as a `mouseenter` and `raycaster-intersected` event on the blue plane even though it is not the closest intersection. Furthermore, when you move the cursor upwards over the blue again, the raycaster emits a `raycaster-intersected-cleared` event but not a `mouseleave` event on the red plane.

Here's a terrible GIF of one of my apps that I was upgrading to 0.8.0 from 0.7.x that alerted me to the bug: https://streamable.com/ntaum

I know a lot of work went into optimising the raycaster for 0.8.0, but it looks like some logic was removed that stops events being emitted on new intersections that are further along the ray while there are currently other foreground intersections.

Cheers!

- A-Frame Version: 0.8.0
- Platform / Device: First noticed on Win10, Rift, Firefox. Debugged on Mac with Chrome 64.
- Reproducible Code Snippet or URL: https://codepen.io/PButcher/pen/PRZGRr

**Comment by donmccurdy** [comment]
Thanks! I think this is the same issue as https://github.com/aframevr/aframe/issues/3467, which should be fixed after https://github.com/aframevr/aframe/pull/3475.
