### ISSUE TITLE
Reverse Mouse Drag has no effect

### ISSUE THREAD

**Issue by stephanedemotte** [aframevr/aframe#3459]
Try to reverse mouse drag, but nothing happen.

- A-Frame Version: 0.8.0
- Platform / Device: Mac /Chrome
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/righteous-quit

**Comment by donmccurdy** [comment]
Confirmed. Looks we broke this with the major VRControls -> WebGLRenderer changes in #3152.

Demo: https://codepen.io/donmccurdy/pen/bveBVb

**Comment by donmccurdy** [comment]
From your [comment on SO](https://stackoverflow.com/questions/49387640/how-to-disable-tracking-position-in-aframe/49389033?noredirect=1#comment85794332_49389033) it looks like `hmdEnabled` functionality was lost with #3152 as well...

**Comment by jason90929** [comment]
fixed it in pr:3482
https://github.com/aframevr/aframe/pull/3482

**Comment by donmccurdy** [comment]
thanks all!
