### ISSUE TITLE
Cursor & Hover (interaction) does not work on mobile

### ISSUE THREAD

**Issue by AlexandreLeitao** [aframevr/aframe#346]
Just try the cursor & hover example on a mobile device and it does not work. Interaction does not work on mobile devices?

**Comment by cemkod** [comment]
Thank you for your report.
- Please specify your device make, model, operating system version, and browser.
- Please describe the problem in detail. Explain what happened, and what you expected would happen

**Comment by AlexandreLeitao** [comment]
Hello,

I have used the "demo" Cursor & Hover on iPhone 6, IOS 8.4 and Safari browser.
I expected to look at the object and see the transformation like it is working on desktop version.

How can i interact with a object?

Thanks

**Comment by dmarcos** [comment]
On mobile the cursor switches to fuse mode: You hover the element for a couple of seconds a click event triggers. @AlexandreLeitao Does this work for you: http://swimminglessonsformodernlife.com/aframe-core/examples/panoexplorer/

**Comment by cvan** [comment]
in response to https://github.com/aframevr/aframe/issues/346#issuecomment-169760743:

I'm on iPhone 6, iOS 9.1, Safari browser, and the [Cursor & Hover](https://aframe.io/examples/showcase/cursor/) demo works just as well on mobile as it does for me on desktop.

The orange cube is supposed to change color to a longer yellow rectangle on hover. Is that not happening for you? When you get a chance, could you please provide a screenshot?

**Comment by AlexandreLeitao** [comment]
This example works ok.
http://swimminglessonsformodernlife.com/aframe-core/examples/panoexplorer/
Can i see the source code?

But the example source code:
https://github.com/aframevr/aframe/blob/master/examples/interaction-cursor/index.html

Does not do the hover change.
Screenshot here.
![img_0159](https://cloud.githubusercontent.com/assets/12912643/12195779/b50a45da-b5f1-11e5-80b1-763d0114db54.PNG)

**Comment by dmarcos** [comment]
@cvan It seems that the hover is not playing well with the primitives

@AlexandreLeitao: this is the code of the working example. https://github.com/aframevr/aframe-core/blob/master/examples/panoexplorer/index.html

**Comment by cvan** [comment]
> @cvan It seems that the hover is not playing well with the primitives

how so?

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
