### ISSUE TITLE
0.8.1 release and tag are missing

### ISSUE THREAD

**Issue by mkungla** [aframevr/aframe#3461]
**Description:**

Latest published A-Frame version is `0.8.1`, but matching git tag is missing 
https://github.com/aframevr/aframe/releases
https://github.com/aframevr/aframe/tags

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
0.8.0 was hot fixed on the CDN with a couple of small patches so everybody benefits without having to bump versions. On npm though we cannot hot fix and had to bump the version.

**Comment by mkungla** [comment]
ok let's close it then while it would be nice to have versioning to follow some standards...
