### ISSUE TITLE
Random camera movement with webvr-polyfill ^0.10.3

### ISSUE THREAD

**Issue by tomegz** [aframevr/aframe#3465]
**Description:**
Camera moves slightly in every direction, whether I'm moving the device or not. Tested on master branch - with webvr-polyfill ^0.10.3 version.
- A-Frame Version: 0.8.1
- Platform / Device: LG X-Power II - Chrome v65
- Reproducible Code Snippet or URL: https://curved-actress.glitch.me/

![Random camera movement gif](https://media.giphy.com/media/zmTp1LVYEjjySTdVYm/giphy.gif)

**Comment by jsantell** [comment]
@tomegz what rate does this website report for you on that device? http://deviceorientation-rate.glitch.me

**Comment by jsantell** [comment]
Related: #3458

**Comment by tomegz** [comment]
@jsantell it oscillates around 15.0

**Comment by jsantell** [comment]
@tomegz that's unfortunately an issue in Chromium 65 -- there may be a patch before the next release, and I've noticed sometimes after restarting Chrome I'm able to get 55hz; other times, around 10.

Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=819413

**Comment by tomegz** [comment]
@jsantell the camera is moving even if I'm not moving the device at all, is that caused by this exact bug?

**Comment by jsantell** [comment]
@tomegz there are [two issues](https://github.com/immersive-web/webvr-polyfill/releases/tag/v0.10.3) with Chrome m65, one with devicemotion events lacking rotationRate requiring a deviceorientation fallback in the polyfill for only m65, and another of low rate of updates (~10hz) for both events

**Comment by dmarcos** [comment]
Closing to consolidate these on a single issue: https://github.com/aframevr/aframe/issues/3458
