### ISSUE TITLE
Problems including aframe in browserify

### ISSUE THREAD

**Issue by mattpolicastro** [aframevr/aframe#347]
Apologies if this is missing the obvious, but I'm trying to add aframe as a project dependency based on the instructions listed in the README:
````
$ npm install aframe
````
And inside `index.js`:
````
require('aframe')
````
However, when I try to run browserify (installed globally), I get errors related to dependencies:
````
$ browserify index.js
Error: Cannot find module 'polymerize' from '/test-aframe/node_modules/aframe'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
````
Again, apologies if this is barking up the wrong tree but I'm out of ideas.

**Comment by mareknowakowski1** [comment]
Hi,

It's because you don't have it in your node_modules directory I suppose. Go to you aforce node_module and then try npm install. This should install all dependencies from aforce directory. good luck!

**Comment by mattpolicastro** [comment]
Thanks for the pointer. I suppose I'm still wrestling with this: if someone adds Aframe to their project purely as a dependency, shouldn't Aframe install its own dependencies as well? I might be stretching here, but I think that's a reasonable expectation when adding a utility to a project.

**Comment by mareknowakowski1** [comment]
No problem :) Right it should be. I had the same problem. Unfortunately if you are adding it to your own dependencies then it doesn't run all other stuff - just downloading aforce. Thats it. 

Did you manage to handle that error ? :)

**Comment by mattpolicastro** [comment]
Yes, the tip you provided worked. However, I believe my point still stands: Aframe should install dependencies necessary to its functioning as part of the install process.

**Comment by cvan** [comment]
Very sorry about this; we'll be addressing this very soon. Thanks for filing!

**Comment by mattpolicastro** [comment]
Thanks @cvan! I've been poking around was thinking of moving some of the dependencies necessary for building from `devDependencies` to the regular `dependencies`—am I totally off-base? Happy to test and PR.

**Comment by mattpolicastro** [comment]
Took a stab at this—[I moved the dependencies.](https://github.com/mattpolicastro/aframe/commit/a72b7f17a31a3eb0819aa9ddc9574d245b6c784e) Can't say I've given it terribly rigorous testing, but:
1. Added my tweaked `aframe` as a local dependency
2. Parent project's `index.js` contains `require('aframe');` to make sure it bundles the necessary files
3. Ran `npm install` grabbed all of `aframe-core` as well as the browserify plugins
4. Ran `browserify index.js` and got a successful output

**Comment by cvan** [comment]
@mattpolicastro yep, that looks about right. could you open a PR for that (and change the tabs to spaces while you're at it)?

**Comment by cvan** [comment]
this should be working now - thanks, @mattpolicastro :)

**Comment by mattpolicastro** [comment]
Apologies for dropping off the map for the past few days—thanks for addressing, @cvan!
