### ISSUE TITLE
gyroscope last version chrome 

### ISSUE THREAD

**Issue by Adilmar** [aframevr/aframe#3471]
**Description:**

- A-Frame Version: v0.8.0
- Platform / Device: Android
- Reproducible Code Snippet or URL: 

in the last version it does not work

**Comment by timokorkalainen** [comment]
When not in VR mode, that is. While in VR, everything works perfectly. The issue is made worse by the look-controls touch mode not allowing vertical rotation, thus making zenith and nadir areas inaccessible on Android devices while not in VR.

**Comment by dancespiele** [comment]
In my case, in VR mode in Chrome only the gyroscope works vertically.

**Comment by dmarcos** [comment]
That's a known Chrome bug that will be fixed in m66. See https://github.com/aframevr/aframe/issues/3458

**Comment by dmarcos** [comment]
Closing as a duplicate.
