### ISSUE TITLE
Official logo/lockup?

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#3477]
Minor, but in logo clouds like this glTF ecosystem screenshot...

![screen shot 2018-03-19 at 8 47 36 am](https://user-images.githubusercontent.com/1848368/37606285-5a546048-2b52-11e8-8eba-abf945aaec7e.png)

.... the A-Frame "logo" (I think that's just the title from the website?) sticks out a bit. Maybe we don't need a logo per se, but an official version of the title with nice padding would be good for branding situations like this. Might also be interesting to try condensing the 3D hero "A" from the homepage into a smaller icon.

//cc @cvan

**Comment by cvan** [comment]
We have versions of standalone logo icon, standalone wordmark, wordmark with icon. Will provide vector files by end of week. Thanks for inquiring about this; I am glad the brand will be more consistent. :+1:

**Comment by cvan** [comment]
@caseyyee and I are finalising the logo treatment. we'll get a ZIP of the files posted in this issue by the end of week. thanks for following up on this!

**Comment by ngokevin** [comment]
Couple at:

- https://github.com/aframevr/aframe-presentation-kit/blob/master/materials/sticker-aframe1.png
- https://github.com/aframevr/aframe-presentation-kit/blob/master/materials/sticker-aframe2.png

PR any there if anyone wants to propose more.
