### ISSUE TITLE
Inconsistent recognition of clicks by the front object when multiple intersecting objects

### ISSUE THREAD

**Issue by rajnikantmrao** [aframevr/aframe#3485]
The use case is as follow:

There are multiple objects in the scene some partially hidden. If click events have been placed on all objects, one would expect that the front-most object picks up the click. However, in `0.8.0` this was not happening consistently. When I tried on glitch with a simple 2 objects, it works. But when there are say 10-15 objects it at times picks up and at times fails.

However, changing the aframe ver to `0.7.1` always picks the front-most object.

**Comment by donmccurdy** [comment]
Will be fixed by https://github.com/aframevr/aframe/pull/3475

**Comment by donmccurdy** [comment]
Fix merged, will be solved on next ~0.8.2 release.
