### ISSUE TITLE
VR mode takes over all cameras, not just main one

### ISSUE THREAD

**Issue by omgitsraven** [aframevr/aframe#3487]
**Description:**

- A-Frame Version: 0.8.0
- Platform / Device: Firefox / Rift
- Reproducible Code Snippet or URL: http://ravenworks.ca/witch/bugdemo/

I have a scene where I'm using a second camera that draws a separate scene into its own WebGLRenderTarget, to make a live flat texture in my scene with GLSL. The scene works perfectly in 2D mode; the big circle accumulates spots forever, in a way that has nothing to do with where the viewer is standing.

However, the moment that I enter VR, the second scene's camera starts following the user's head just like the main camera is. (The big circle will likely immediately become the color of the second scene's clear color, and if you wiggle your head around just right, you can eventually get a distorted view of the surface that the shader is running on.) 

Is there something I'm meant to do to indicate to A-Frame that a secondary camera is not meant to be driven by the user's head in VR mode?

**Comment by dmarcos** [comment]
In your tick method try the following:
```javascript
var renderer = this.el.sceneEl.renderer;
var vrModeEnabled = this.renderer.vr.enabled;
renderer.vr.enabled = false;
renderer.render( this.surfaceScene, this.surfaceCamera, this.surfaceTarget );
renderer.vr.enabled = vrModeEnabled;
```

**Comment by omgitsraven** [comment]
That works around it perfectly! Thanks so much!

(Unsure whether I should close the issue now, or leave it open until the workaround isn't needed? Up to you.)

**Comment by dmarcos** [comment]
Renderer doesn’t over all cameras but uses internally its own when in VR mode hence the need to disable / enar vr to use a render target. Closing this since no further action is needed
