### ISSUE TITLE
Camera Direction / Augmented Reality

### ISSUE THREAD

**Issue by peterhintondesign** [aframevr/aframe#349]
Rather than the scene being centred around how the user is holding the VR device I'd like to fix the scene based on compass directions (north, east, south, west') in order to use A-Frame for an augmented reality project.

I'm not sure whether this is possible and I haven't been able to find any info on the topic. Please can someone point me in the right direction?

**Comment by jcarpenter** [comment]
Hi Peter, we haven't looked at AR applications yet and we're focused on other priorities for the next few months (eg improving mobile support, fixing bugs, etc) but this is an intriguing idea. Perhaps it could be implemented as a custom component. Eg "ARcamera". I'd start by writing up a mini spec and circulating it here, on Twitter, and on the A-Frame Slack. You may find people jump in to help :)

**Comment by peterhintondesign** [comment]
Thanks for the quick reply Josh, although I've only just noticed it in the avalanche of Christmas emails.

I'll look into creating a mini-spec, it could be a useful AR tool for developers :)

**Comment by blairmacintyre** [comment]
Peter, I'd be interested in that too.  I've got "look at using A-Frame with our argon.js AR toolkit" on my todo list, but it'll be a bit till I can do it.

**Comment by ngokevin** [comment]
I think we should change it back such that the orientation is absolute, rather than centered at 0,0,0 based on how the user holds the phone when they load the page.

**Comment by cvan** [comment]
I tend to agree. I open my phone a lot when it's flat on my desk.

**Comment by ngokevin** [comment]
AR cameras and utilities: https://github.com/argonjs/argon-aframe for A-Frame

**Comment by cvan** [comment]
There's also https://github.com/jeromeetienne/aframe-artoolkit that's worth checking out

**Comment by blairmacintyre** [comment]
I suspect that aframe-artoolkit just uses the artoolkit, not device orientation, so it doesn't matter to them.  I would agree that we should definitely use the absolute real-world device orientation of the device if we have it.
