### ISSUE TITLE
Npm package not installing

### ISSUE THREAD

**Issue by Starlette** [aframevr/aframe#3491]
**Description:**

- A-Frame Version: 0.8.1
- Platform / Device: Windows 10

I'm experiencing an issue with the node package. It keeps freezing when I run `npm install aframe`. 
![image](https://user-images.githubusercontent.com/19154356/37822071-15ecd464-2e8e-11e8-9e12-97eb4e614327.png)

Any advice?

**Comment by Starlette** [comment]
Thank you @vincentfretin the internet at my office is rather slow so will try again at home tonight where I have a much faster line.

**Comment by hay** [comment]
Yup, doing a `yarn add aframe` or `npm i aframe` took me more than a minute, even on a pretty fast connection.

**Comment by petrovicstefanrs** [comment]
Aframe: v0.8.2
Node: v8.9.4
Having this issue as well.

Here is the log from --verbose flag.
npm install --save aframe --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--save',
npm verb cli   'aframe',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v8.9.4
npm verb npm-session e1123ca191fe3614
npm http fetch GET 304 https://npm.c-code.com/aframe 2591ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/envify 1078ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/@tweenjs%2ftween.js 1119ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/deep-assign 1147ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/present 1488ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/browserify-css 1633ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/three-bmfont-text 895ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/webvr-polyfill 979ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/style-attr 2426ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/promise-polyfill 2634ms (from cache)
npm http fetch GET 304 https://npm.c-code.com/load-bmfont 5154ms (from cache)
⸨░░░░░░░░░░░░░░░░░░⸩ ⠦ fetchMetadata: http fetch GET 304 https://npm.c-code.com/lo
d-bmfont 5154ms (from cache)

I managed to install Aframe v0.7.0 without problems.

**Comment by jersobh** [comment]
Me too. 0.7.0 installs fine.

**Comment by andresmoritan** [comment]
+1

**Comment by anton6** [comment]
wow... took me about 10 minutes to **npm i** aframe@0.8.2...

**Comment by ngokevin** [comment]
try a-frame master, we removed the examples dir from the package and now pointing to three.js proper. perhaps it was trying to fetch all three.js repo.
