### ISSUE TITLE
vive-controls not working on 0.8.0

### ISSUE THREAD

**Issue by etiennepinchon** [aframevr/aframe#3494]
On 0.8.0 the `vive-controls` component no longer works. The controllers are not present on the scene. Code (tested on Nightly 60 with HTC vive):

```html
<a-entity vive-controls="hand: left"></a-entity>
<a-entity vive-controls="hand: right"></a-entity>
```

Thanks!

**Comment by christophermorse** [comment]
I am also experiencing this same error—controllers are active (events fire) but models are not visible on screen.

**Comment by dmarcos** [comment]
This is a duplicate of https://github.com/aframevr/aframe/issues/3441

**Comment by christophermorse** [comment]
The suggested changes to Three.js in #3441 do not fix the error. I found instead that by saving the object models locally and manually attaching them to the controllers is the only way to get them to appear.

**Comment by donmccurdy** [comment]
When models do not appear, do you see network requests for them? Or any errors in the console?

**Comment by omolds** [comment]
try super-hands!
