### ISSUE TITLE
.flushToDOM() does not reflect transforms when set with three.js methods

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#3499]
When modifying `el.object3D.position` directly, incorrect/outdated TRS transforms are shown after calling `.flushToDOM()`. Not sure how much of a special case it's worth to fix this, but it would be nice for the debugging methods to work as expected here.

Example: https://jsfiddle.net/donmccurdy/gr2oo3um/

**Comment by JoshuaCrisp** [comment]
I think I am running 7. I will try on 8 and see if it works differently. I would love to show you a demo, but I have managed to create a rather fragmented node project that I don't know how to share without giving you 153 MB worth of files. Forgive me. I'm still suer new at this. I can send you just the html file if that helps?

**Comment by donmccurdy** [comment]
Ok no worries about the demo, I'm fairly sure it's 0.7 vs 0.8 causing the issue.

**Comment by ngokevin** [comment]
`.getAttribute` retrieves updated values now. Should fix?
