### ISSUE TITLE
Can Panorama image rotate by the position of MOUSE ?

### ISSUE THREAD

**Issue by wahengchang** [aframevr/aframe#350]
Can Panorama image rotate by the position of MOUSE ?

I have downloaded the example/template-sky,  with drag to rotate the sky panorama images. is there a way to rotate the image by the position x,y of mouse

**Comment by dmarcos** [comment]
Does the examples of the website work for you? https://aframe.io/examples/showcase/sky/

You should be able to rotate the panorama with the mouse

**Comment by cemkod** [comment]
I think what he meant was rotating by linked x,y coords of mouse as opposed to dragging.

**Comment by dmarcos** [comment]
Sorry for the misunderstanding. ```look-controls``` component only provides mouse dragging. Implementing a different component with a different control scheme is definitively possible.

**Comment by cvan** [comment]
Is there something actionable we want to do in this issue? Docs, create an example?

**Comment by cemkod** [comment]
@wahengchang: Have a look at this component I made. I may solve your problem:
https://github.com/cemkod/aframe-fps-look-component

**Comment by ngokevin** [comment]
You can use the third-party components that simulate or implement pointer lock. We have issues on file to evaluate the default mouse controls. Thanks!
