### ISSUE TITLE
Sphere img material not rendered properly in v 0.8.0

### ISSUE THREAD

**Issue by meNaveenKumar** [aframevr/aframe#3503]
Here is my code 

`<a-scene>
    <a-camera position="0 0 10" cursor-visible="false"></a-camera>
    <a-entity geometry="primitive: sphere;
                radius: 100;
                segmentsWidth: 64;
                segmentsHeight: 64;"
        material="shader: flat; src:#image;"
        scale="-1 1 1" side="double" opacity=".5">
    </a-entity>
</a-scene>`

With A-Frame v 0.8.0 the img materiel is rendered outside the sphere, I tried using side property to change it to inside but never worked. With the same code without using side attribute the materiel is rendered as expected inside the sphere with 0.7.1

**Comment by dmarcos** [comment]
The property side is part of the material component (https://aframe.io/docs/0.8.0/components/material.html#properties_side). It should be `material="shader: flat; src:#image; side: double"` Please reopen if this is still a problem
