### ISSUE TITLE
Sound component `name` and `id` not present in event details for `sound-loaded` and `sound-ended`

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#3505]
**Description:** When applying multiple sound components to an entity (e.g., `sound__click`), there doesn't seem to be an obvious way (or possibly any way) to identify the sound component's `name` and/or `id` (e.g., `sound__click` and `click`, respectively).

This makes listening for the `sound-loaded` and `sound-ended` events somewhat ineffective as the source component and audio are unknown.

- A-Frame Version: `0.7.*` - `0.8.0`
- Platform / Device: Firefox, Chrome, Edge on Windows 10 (all I've tested)
- Reproducible Code Snippet or URL: https://codepen.io/dansinni/pen/ZxvyLx

**Comment by koganei** [comment]
@dsinni What do you think of this PR? Instead of looking for ```e.target.id```, you would look for ```e.detail.id```, and it will give you the id of the sound being loaded/ended, even if there are multiple sounds on the a-box.

**Comment by dsinni** [comment]
Sounds good, @koganei. I only mentioned `e.target` because I couldn't figure for the life of me how to access that data. `e.detail` definitely seems more appropriate. Thanks.
