### ISSUE TITLE
Hosted examples have not been updated to 0.8.0

### ISSUE THREAD

**Issue by brianpeiris** [aframevr/aframe#3506]
**Description:**

The examples hosted at https://aframe.io/aframe/examples/animation/aframe-logo/, etc have not been updated and still use v0.7.0. They're often very useful for confirming bugs with the latest release, so it would be useful to update them.

- A-Frame Version: 0.8.0
- Platform / Device: N/A
- Reproducible Code Snippet or URL: https://aframe.io/aframe/examples/animation/aframe-logo/

**Comment by dmarcos** [comment]
Sorry for that. I just bumped the examples. Let me know if it does not work.

**Comment by brianpeiris** [comment]
:+1: looks good to me. Thanks

**Comment by machenmusik** [comment]
having some sort of latest-stable tag might be useful here

**Comment by ngokevin** [comment]
Latest stable is very bad because people will copy the examples, start using it, and then when A-Frame updates, everyone's scenes will break instantly.

**Comment by ngokevin** [comment]
Deploying examples also is more than the script versions, includes all of the modifications to examples + any new ones.

**Comment by machenmusik** [comment]
I agree with that, but the original comment was that they were useful for catching breakage / incompatibilities between versions, meaning the desire was in fact to see the breakage as canary.  I suppose there is the question of whether examples to be copied as you suggest should be moved to glitch or similar in general, and those should be locked to versions as they usually are now.  Relative path would probably work fine for example folders actually, like https://aframe.io/0.8.0/aframe/examples/animation/aframe-logo/

**Comment by dmarcos** [comment]
@machenmusik FYI You can easily try the examples of any version: https://rawgit.com/aframevr/aframe/master/examples/ (replace master with any tag or commit)

**Comment by arpu** [comment]
https://aframe.io/examples/showcase/videosphere/

still using aframe A-Frame Version: 0.7.1 (Date 18-10-2017, Commit #b9a751e)

**Comment by arpu** [comment]
@dmarcos 
the ide awas to test/help people in the bug report https://github.com/aframevr/aframe/issues/3507

**Comment by arpu** [comment]
examples/showcase/dynamic-lights/
same using A-Frame Version: 0.6.1 (Date 19-07-2017, Commit #a4b91bc)
