### ISSUE TITLE
iPhone browsers don't go fullscreen when entering VR-mode

### ISSUE THREAD

**Issue by HyvelTjuven** [aframevr/aframe#3508]
**Description:**
When entering VR mode on iPhone browsers the browser does not go fullscreen but instead keeps its bars present.

It looks like this and doesn't work well with cardboard:
![alt text](https://i.imgur.com/1HwResp.jpg "iPhone/A-frame")

- A-Frame Version: Master dist. 12d8721
- Platform / Device: iPhone SE (iOS 11), Chrome & Safari.

**Comment by DenadaPatron** [comment]
Same applies for all the androids I have tested this with so far (galaxy s7, htc m8 and one plus 5T) Unfortunately, I don't have access to any of these phones at the moment, thus unable to provide android versions.

**Comment by dmarcos** [comment]
This is a limitation of iOS. A website cannot enter fullscreen unless you add the page to homescreen.
