### ISSUE TITLE
location of external models (collada) only load from same server or from secured https

### ISSUE THREAD

**Issue by jonwaterschoot** [aframevr/aframe#351]
I started fiddling with the example on codepen, first thing I tried was adding a model from Blender. I uploaded that file on my own website's server, but it didn't load. At first I thought it was because I was exporting non valid files. SO I made various other models and exports.

However, I found that loading the tree1 model from the secured server from aframe did work ( https://aframe.io/aframe/examples/_models/tree1/tree1.dae) I then tried loading the same file from my server.
Loading the same file in codepen from my server doesn't work (http://www.jon-ibe.be/aframe/tree1.dae)

After loading an html file from the same folder on my own server with the same code as the codepen I saw the models loading correctly.

http://www.jon-ibe.be/aframe/aframetest.html
http://codepen.io/anon/pen/OMbmyz?editors=110

So hence I'm "blaming" this on the security restrictions.

Maybe it's a logical thing security wise, but I didn't see any documentation on this.

**Comment by cemkod** [comment]
Not a bug. Expected security behaviour of the browser.

It doesn't matter if the transport is http or https, the browser expects an access-control-allow-origin header to allow the resource to be loaded. 

aframe.io webserver returns this in the response header:
access-control-allow-origin:*

Your webserver doesn't have this field in response header. If you configure your webserver to send a response header that allows http://s.codepen.io or all domains (*), it will work.

Please see: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by jonwaterschoot** [comment]
Ok, thanks for the clarification. Makes sense now.
I have no idea where I could set this up on my websites server, I doubt I have access to this function. I'll ask the provider. 
For now I'll do my experiments on my own, I just liked the quick and easy way of editing a live Codepen.
I'll close the issue since it's not A-frame related.

**Comment by dragossido** [comment]
> Not a bug. Expected security behaviour of the browser.
> 
> It doesn't matter if the transport is http or https, the browser expects an access-control-allow-origin header to allow the resource to be loaded.
> 
> aframe.io webserver returns this in the response header:
> access-control-allow-origin:*
> 
> Your webserver doesn't have this field in response header. If you configure your webserver to send a response header that allows http://s.codepen.io or all domains (*), it will work.
> 
> Please see: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

Ok the problem is scr=... dropbox

if i put a local files no problem at all

i saw there is like access-control-allow-origin to put in the code, but i have not really understand where and how
