### ISSUE TITLE
gearvr-controls fires controllerconnected events for Oculus Touch

### ISSUE THREAD

**Issue by ericflo** [aframevr/aframe#3510]
This makes it hard to disambiguate between a situation where you just have one GearVR controller vs. whether you have two Oculus Touch controllers. However it could be desirable behavior since it'll make sure a lot of GearVR-oriented experiences work with Oculus Touch. Maybe this should be an explicit option?

- A-Frame Version: 0.8.0
- Platform / Device: Windows 10 / FF Nightly 61.0a1 (2018-03-31) (64-bit)
- Reproducible Code Snippet or URL:

this.el.setAttribute('gearvr-controls', { hand: 'right', model: false });
this.el.addEventListener('controllerconnected', evt => {
  console.log('controllerconnected', evt.detail.name);
});

Output:
controllerconnected oculus-touch-controls
controllerconnected gearvr-controls

**Comment by dmarcos** [comment]
`controllerconnected` should not fire with Touch if `gearvr-controls` is the only component

**Comment by machenmusik** [comment]
0.8.0 had a gearvr-controls bug that has been fixed in master, can you retry with latest?

**Comment by machenmusik** [comment]
More specifically, https://github.com/aframevr/aframe/pull/3489

**Comment by machenmusik** [comment]
Now merged into latest master
