### ISSUE TITLE
HoloLens Support

### ISSUE THREAD

**Issue by KJStrand** [aframevr/aframe#3513]
The new RS4 update for HoloLens enables WebVR in Edge, but Aframe does not correctly present immersive view. The basic three.js examples such as "cubes" (https://threejs.org/examples/webvr_cubes.html) work on HoloLens, however Aframe 8.0 examples enter full screen click/drag mode instead of vr presentation. With Aframe 7.0, "Enter VR" button does nothing in Hololens.

- A-Frame Version: 8.0
- Platform / Device: HoloLens Edge Browser
- Reproducible with basic Aframe 8.0 example: https://aframe.glitch.me/

**Comment by dmarcos** [comment]
Do you have access to console logs to see if there’s any error?

**Comment by KJStrand** [comment]
I am closing this issue; Aframe works correctly once the "Enable WebVR" experimental flag is checked in Edge for HoloLens under "about:flags." WebVR is not an experimental feature for Windows 10 desktop Edge browser so I forgot to check this.

**Comment by dmarcos** [comment]
Thanks for info

**Comment by DominicBoettger** [comment]
Is it by design of the hololens that there is no click event in immersive view? If there is a possibility to click can you please document that? I was unable to figure this out yet.

Thanks

**Comment by KJStrand** [comment]
@DominicBoettger I haven't been able to figure out the click event, but I did receive the following information from a Microsoft contact: 

> Currently both spatial controllers (for the WinMR on Desktop case) and hands (for HoloLens) are exposed via the standard W3C gamepad spec: https://www.w3.org/TR/gamepad/  
Here is documentation on how to use the gamepad API with WebVR:
https://docs.microsoft.com/en-us/microsoft-edge/webvr/input
With regards to HoloLens – you will be able to listen to gamepadconnected and gamepaddisconnected events, and check the button pressed state (on HoloLens – the select action via finger tap will come through as a button pressed state at index 1). This is similar to what you’ll have available with the HoloLens clicker.

**Comment by DominicBoettger** [comment]
Wow. Thanks a lot!
I will test this next week. Very interesting!

**Comment by KJStrand** [comment]
I haven't had a chance to revisit this, were either of you able to get the click working?

**Comment by rc1** [comment]
The click event is available on the Hololens via the GamePad API as @KJStrand mentions. 

It's available as `navigator.getGamepads()[4].buttons[0].value`. 

Note, you'll have to wait for `window.addEventListener("gamepadconnected", () => {})` for the gamepad to be available.

**Comment by wmurphyrd** [comment]
@rc1 I'd like to make a controller component for the Hololens. Could you share the full output of getGamepads?

**Comment by rc1** [comment]
@wmurphyrd it aligns with the Game Controller API. The specifics being:

- It's the fifth item in the returned array from `getGamepads`
- It has one button value 0 or, when airtapping, 1
- The pose position will be location of the hand or, when a hand is out of the gesture FOV, the pose position is `null`

I hope that helps

**Comment by rc1** [comment]
#3881

**Comment by DominicBoettger** [comment]
#3881
