### ISSUE TITLE
A sphere primitive: Theta and Phi doesn't work

### ISSUE THREAD

**Issue by staus** [aframevr/aframe#352]
When trying to make a dome I noticed that neither phiStart, phiEnd, thetaStart or thetaEnd have any impact on the sphere primitive (as otherwise described in the documentation: https://aframe.io/docs/components/geometry.html#Sphere)

Codepen:
http://codepen.io/anon/pen/wMgmYV

**Comment by dmarcos** [comment]
It's ```thetaLength``` and ```phiLength``` instead of ```phiEnd``` and ```thetaEnd```

**Comment by staus** [comment]
Ah, my bad got a little late
I still think the issue is there, though:
http://codepen.io/anon/pen/wMgmYV

**Comment by dmarcos** [comment]
The documentation is ahead of the released version. ```phiLength``` and ```thetaLength``` are still in the ```dev``` branch of [aframe-core](https://github.com/aframevr/aframe-core) this is why they're not working on your example. You can play with this example and see: http://swimminglessonsformodernlife.com/aframe-core/examples/cube/

If you're not going to use the primitives and you have some tolerance for quirks :) you can move to use dev branch of the core. Sorry for the inconvenience

**Comment by staus** [comment]
Ah, it's no problem for me right now. In my case I found I could use a cone in stead (I a cone also performs better as it has less segments), but thanks for looking into it and good it's on it's way :) Will definitely be useful!

**Comment by dmarcos** [comment]
@cvan We have to make sure that the published docs correspond to the
released version aka master branch. There's no ```thetaLenght``` and
```phiLength``` properties in the published version

**Comment by cvan** [comment]
Thanks for catching this. I'll need to start versioning our docs now. :+1:

**Comment by cvan** [comment]
blocked on aframevr/aframe-site#121

**Comment by cvan** [comment]
@ngokevin: can you confirm this is fixed in PR #883?

**Comment by ngokevin** [comment]
yeah
