### ISSUE TITLE
showcase/wikipedia not working should be removed

### ISSUE THREAD

**Issue by arpu** [aframevr/aframe#3521]
https://a-frobot.github.io/aframe/examples/showcase/wikipedia/
A-Frame Version: 0.8.1 (Date 2018-04-03, Commit #3820c9b)

Uncaught ReferenceError: mwNow is not defined

maybe the showcase can be removed?

**Comment by dmarcos** [comment]
Rather than removed it should be fixed since it's the example for embedded scenes

**Comment by arpu** [comment]
ok, i only mention remove, because there is no link to this showcase on aframe.io or on the embedded
documentation 

as example and for simple source code reading 
https://aframe.io/aframe/examples/test/embedded/

**Comment by dmarcos** [comment]
This is working on master
