### ISSUE TITLE
Gear VR touchpad crashes A-Frame when remote debugging

### ISSUE THREAD

**Issue by slhawkins** [aframevr/aframe#3524]
**Description:** When using A-Frame in the Oculus browser, connected to the Gear VR as a Remote Device, A-Frame will crash when tapping the touchpad. The URL below uses the log component showing that the touchpad fires the click event just fine, though no touch events are registered. One you remotely connect to the Gear VR for debugging through Chrome, it'll catch a touchstart event and then crash A-Frame.

- A-Frame Version: 0.8.0 (Date 2018-03-11, Commit #82934b02)
- Platform / Device: Note 8 - Gear VR
- Reproducible URL: [gvr.glitch.me](http://gvr.glitch.me)
- Reproducible Code: [glitch.com/edit/#!/gvr](https://glitch.com/edit/#!/gvr)

**Comment by DougReeder** [comment]
I can confirm the crash on a Gear VR with a Galaxy S6 running Android 7.0

**Comment by DigiTec** [comment]
We are also tracking this on the Oculus Browser side to see if this is our issue or a framework issue. Once we know more we may take over the task or supply further details.

**Comment by machenmusik** [comment]
thanks @DigiTec -- let us know if there is anything we can gather for you that would be helpful.

**Comment by DougReeder** [comment]
A component that may be of value here is my aframe-button controls (https://github.com/DougReeder/aframe-button-controls).  It implements the modern algorithm of listening for Pointer events if supported, falling back to Touch events, and if Touch events aren't supported, falling back to Mouse events.  It appear Oculus Browser implements Pointer events for the touchpad, but Samsung only implements (emulated) Touch events.

**Comment by ngokevin** [comment]
Oculus Browser / GearVR issue. Don't think this should be in A-Frame's court.
