### ISSUE TITLE
contextify: Command failed. on fresh yarn install 

### ISSUE THREAD

**Issue by arpu** [aframevr/aframe#3528]
on yarn install i get 
warning Error running install script for optional dependency: "/home/arpu/tmp/aframe/node_modules/contextify: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /home/arpu/tmp/aframe/node_modules/contextify
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/arpu/tmp/aframe/node_modules/contextify/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/arpu/.node-gyp/8.11.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/arpu/.node-gyp/8.11.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/arpu/.node-gyp/8.11.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/arpu/tmp/aframe/node_modules/contextify',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Verzeichnis „/home/arpu/tmp/aframe/node_modules/contextify/build“ wird betreten
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In statischer Elementfunktion »static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)«:
../src/contextify.cc:131:68: Warnung: »v8::Local<v8::Object> v8::Function::NewInstance() const« ist veraltet: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/arpu/.node-gyp/8.11.1/include/node/v8.h:26:0,
                 from /home/arpu/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/arpu/.node-gyp/8.11.1/include/node/v8.h:3851:52: Anmerkung: hier deklariert
   V8_DEPRECATED(\"Use maybe version\", Local<Object> NewInstance() const);
                                                    ^
/home/arpu/.node-gyp/8.11.1/include/node/v8config.h:318:3: Anmerkung: in Definition des Makros »V8_DEPRECATED«
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc:150:16: Fehler: »class v8::ObjectTemplate« hat kein Element namens »SetAccessCheckCallbacks«; meinten Sie »SetAccessCheckCallback«?
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^~~~~~~~~~~~~~~~~~~~~~~
                SetAccessCheckCallback
../src/contextify.cc: In statischer Elementfunktion »static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)«:
../src/contextify.cc:182:80: Warnung: »v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)« ist veraltet: Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
In file included from /home/arpu/.node-gyp/8.11.1/include/node/v8.h:26:0,
                 from /home/arpu/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/arpu/.node-gyp/8.11.1/include/node/v8.h:3404:30: Anmerkung: hier deklariert
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/arpu/.node-gyp/8.11.1/include/node/v8config.h:318:3: Anmerkung: in Definition des Makros »V8_DEPRECATED«
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc: In statischer Elementfunktion »static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)«:
../src/contextify.cc:209:67: Warnung: »v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)« ist veraltet: Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from /home/arpu/.node-gyp/8.11.1/include/node/v8.h:26:0,
                 from /home/arpu/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/arpu/.node-gyp/8.11.1/include/node/v8.h:3404:30: Anmerkung: hier deklariert
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/arpu/.node-gyp/8.11.1/include/node/v8config.h:318:3: Anmerkung: in Definition des Makros »V8_DEPRECATED«
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc:210:71: Warnung: »v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)« ist veraltet: Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
In file included from /home/arpu/.node-gyp/8.11.1/include/node/v8.h:26:0,
                 from /home/arpu/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/contextify.cc:1:
/home/arpu/.node-gyp/8.11.1/include/node/v8.h:3404:30: Anmerkung: hier deklariert
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/arpu/.node-gyp/8.11.1/include/node/v8config.h:318:3: Anmerkung: in Definition des Makros »V8_DEPRECATED«
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [contextify.target.mk:95: Release/obj.target/contextify/src/contextify.o] Fehler 1
make: Verzeichnis „/home/arpu/tmp/aframe/node_modules/contextify/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.14-300.fc27.x86_64
gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/arpu/tmp/aframe/node_modules/contextify

all works fine 

aframe master 80a3426b886f3f5df7be0855cd05c68cfd2efd08

**Comment by arpu** [comment]
the npm package is UNMAINTAINED
https://www.npmjs.com/package/contextify

**Comment by arpu** [comment]
the dependency comes from"mozilla-download": "^1.1.1",
 https://www.npmjs.com/package/mozilla-download

anyone an idea for what this is used?

**Comment by ngokevin** [comment]
`yarn add aframe` works for me

**Comment by arpu** [comment]
yes this works but if you clone the master git 
and try
yarn install
