### ISSUE TITLE
[idea] Improving support for webpack & other bundler

### ISSUE THREAD

**Issue by mattdesl** [aframevr/aframe#353]
Right now `aframe-core` depends on `browserify-css` as a browserify transform. It works magically when you depend on the CommonJS version from npm using browserify. But, other bundlers do not support this.

Tools like jspm/rollup/webpack/whatever need to rely on the UMD build. Webpack users can set up loaders (like `transform-loader` or `ify-loader`) to work with the CommonJS export, but this might not be immediately clear to consumers.

Eventually it might be worth transpiling the static assets (like CSS, GLSL, etc) on pre-publish so that webpack/browserify/jspm/etc users get the same CommonJS export.

One option which is currently a work in progress:
https://github.com/livejs/transpilify

Other ideas discussed here:
https://gist.github.com/mattdesl/aaf759da84cc44c22305

This issue is really just to discuss any other ideas/approaches, and how this might affect development workflow, etc. Or, maybe no change is needed, and docs just need to provide more details on other bundlers.

**Comment by cvan** [comment]
Been following your work here. Excited to see where this goes.

Also related: aframevr/aframe-core#699 and #347

**Comment by ngokevin** [comment]
Thanks for filing. We found this works: https://github.com/aframevr/aframe-core/pull/782

Let us know if you have better solutions.
