### ISSUE TITLE
How to prohibition gesture control?

### ISSUE THREAD

**Issue by MallTo-Silence** [aframevr/aframe#3532]
**Description:**
how to prohibition gesture control, only use sensors.

- A-Frame Version: 0.8.1
- Platform / Device: iOS

**Comment by dmarcos** [comment]
https://aframe.io/docs/0.8.0/components/look-controls.html#properties_touchenabled

Please use StackOverFlow or the Slack Channel (https://aframe.io/community/#slack) for questions. Github issues are for bugs and feature requests.
