### ISSUE TITLE
Update raycaster intersection data of previous intersected objects

### ISSUE THREAD

**Issue by feiss** [aframevr/aframe#3533]
It would be useful to get the new intersection position of the ray in the same intersected object among frames.

For example: imagine a single plane for a wall, and the user has a laser sabre in his hand, and we want to show the burn in the wall as he hits and moves the sabre on the wall. 

Right now this is impossible with current `raycaster`, because we only get one event `raycaster-intersected` on the first intersection, but on next frames we don't get any more events because the intersected object is the same as in the previous frames. It would be cool to have a `raycaster.getCurrentIntersection(obj)` to get the intersection data on that object *in current frame*.

Performance would not suffer too much, since right now `intersectObjects` is called with all raycastable objects. It would be just a matter of updating the new intersection data. (This behaviour could be enabled/disabled with a parameter in the component, too)

- A-Frame Version: 0.8
- Platform / Device: all

**Comment by vincentfretin** [comment]
https://github.com/aframevr/aframe/issues/3129#issuecomment-334779820 is relevant.
but actually @donmccurdy did just that, a getIntersection function 21 days ago, still on master
https://github.com/aframevr/aframe/commit/79cb1546836ab1fa7d402415459ea294c6c3d4b7

**Comment by donmccurdy** [comment]
I think we can do the 0.8.2 release soon. There's only one more issue on the milestone: https://github.com/aframevr/aframe/milestone/9

**Comment by ngokevin** [comment]
Cool ^^
