### ISSUE TITLE
isGearVR might  not be accurate anymore

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#3535]
We check the userAgent string to discriminate Oculus Browser and Samsung Internet and flip isGearVR to `true`. Before Oculus Go that was a fair assumption because those browsers were exclusive to GearVR. That's not the case anymore.

**Comment by Giorat** [comment]
I just created a function to enable Oculus Go detection.

Opened up a pull-request here: https://github.com/aframevr/aframe/pull/3685

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/3685
