### ISSUE TITLE
Bad rendering on mobile devices that does not have 16:9 aspect ratio

### ISSUE THREAD

**Issue by josu1502** [aframevr/aframe#3538]
On devices like OnePlus 5T, LG G6, Samsung S8 or other phones, where the aspect ratio is 18:9 (2:1) the rendering is off, making it impossible too focus using a cardboard headset. The phone needs to have an aspect ratio of 16:9 for correct rendering.

The fullscreen option should be locked to 16:9, so it does not fill the whole screen, on phones with different aspect ratio.

A work around for OnePlus 5T:
1. Go to: Settings->App->Full screen apps->[YOUR BROWSER]
2. Select: Compatibility mode (16:9) 

- A-Frame Version: 0.8.0
- Platform / Device: OnePlus 5T

**Comment by justaboredkid** [comment]
#3223

**Comment by leoncvlt** [comment]
As referenced in #3223, on the Galaxy S8 setting the phone's display to maximum resolution (2960x1440) in the settings fixes the issue - by default it's set to 2220x1080 to save battery. Which is weird because both resolutions have the same aspect ratio?

**Comment by justaboredkid** [comment]
This has not been updated for a long time. The rendering right now (at least on my 5T) is working. Can someone confirm this? If so, we can close this issue.

**Comment by dmarcos** [comment]
@justaboredkid thanks for reporting. We can close and will reopen if the issue comes back.
