### ISSUE TITLE
Allow rendering an animated gif as a texture

### ISSUE THREAD

**Issue by zreese** [aframevr/aframe#354]
I feel like this should work, but doesn't, and I'm not sure why. I can load a gif fine in an a-sky object, but it only displays the first frame instead of animating properly.

**Comment by dmarcos** [comment]
There's not support for animated gifs applied as textures. This is why you only see the first frame.

**Comment by zreese** [comment]
Thanks. Can I turn this into a feature request?

**Comment by dmarcos** [comment]
Sure!

**Comment by Shawireland** [comment]
I would also like the feature of playing .gifs on a surface.

**Comment by ngokevin** [comment]
https://github.com/mayognaise/aframe-gif-component
