### ISSUE TITLE
Using GearVr, video stops if getting in Vr mode

### ISSUE THREAD

**Issue by mikeb90** [aframevr/aframe#3544]
As the title, if I play a video and click on the vr-button, it pauses while entering in 360-view. The bug came out after the oculus browser 4.4.0 update of the 04/16/2018.

- A-Frame Version: 0.7.1
- Platform / Device: GearVr on Galaxy S6 - Android 7.0
-Browser version: Oculus Browser 4.4.0

**Comment by payamspot** [comment]
Could you please send me an example so that I can check that, too? I also have S6 & Gear VR.

**Comment by mikeb90** [comment]
What kind of example do you mean? A video example? If so, it gets stuck even in the "aframe video example" online, provided in the docs page.

**Comment by dmliao** [comment]
There was an issue with viewing WebVR videos in Oculus Browser 4.4.0, which was fixed in 4.4.1. Does this issue still persist if you update the browser?

**Comment by mikeb90** [comment]
@dmliao  thx for the advice, it's working now :)

**Comment by dmarcos** [comment]
Glad to see it's working 👍
