### ISSUE TITLE
Images with transparency placed within a-camera make images placed elsewhere not visible

### ISSUE THREAD

**Issue by HyvelTjuven** [aframevr/aframe#3545]
**Description:**
Images with transparency that are placed within a-camera will completely obstruct other images and objects placed elsewhere, only the skybox is shown through the transparent parts of an image and not other images.

This shows an image in the a-camera making parts of other objects invisible if they're within the transparent part of the image:
![alt text](https://i.imgur.com/3GCaHry.jpg)

- A-Frame Version: 0.8.2
- Platform / Device: Chrome, Windows & Android

**Comment by donmccurdy** [comment]
See https://aframe.io/docs/0.8.0/components/material.html#transparency-issues. Transparency in WebGL requires some careful setup.

**Comment by HyvelTjuven** [comment]
@donmccurdy that worked out great, thank you!
Closing the issue.
