### ISSUE TITLE
npm package dependency for 0.8.2 still links to supermedium/three is?r90

### ISSUE THREAD

**Issue by wjessup** [aframevr/aframe#3549]
Just check out package.json from: https://registry.npmjs.org/aframe/-/aframe-0.8.2.tgz
 

"three": "github:supermedium/three.js#r90fixMTLLoader",

**Comment by ngokevin** [comment]
@dmarcos maybe forgot to bump npm dist when you built?

**Comment by ngokevin** [comment]
Oh nvm yeah that's right. We bumped after

**Comment by ngokevin** [comment]
That's the right version for 0.8.2. Master has r91

**Comment by dmarcos** [comment]
That’s correct. 0.8.2 ships r90 + a couple of fixes. Master points to r92

**Comment by wjessup** [comment]
so whats the solution here? Documentation says r92 and it breaks things in my project because of the changes to the lights par glsl fragments so if you are modifying default shaders you'll get errors.

**Comment by dmarcos** [comment]
@wjessup you can use master:

https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js

Where did you see r92 in the docs? I don’t remember mentioning it

**Comment by azmartone** [comment]
I'm seeing issues with r90 in the latest version of
Android Chrome Version 69.0.3497.100.

Camera doesn't rotate until you get into VR mode. Similar to the symptoms of #3731

r94 seems fine.

**Comment by kumarahir** [comment]
The camera doesn't rotate by default and just able to pan the scene using touch.
The camera gets oriented with the gyroscope in VR mode
On exiting VR mode neither camera moves on the movement of phone nor the scene pans on touch.

am using following
https://aframe.io/releases/0.8.2/aframe.min.js
Android Chrome version: 70.0.3538.110
Android 6.0.1 Lenovo X3a40

reproducible code at
https://chrome-aframe-bug.glitch.me/
