### ISSUE TITLE
Camera not moving horizontally on Android

### ISSUE THREAD

**Issue by vkolova** [aframevr/aframe#3550]
On Android devices, the camera is not moving when rotating the device. If you tilt it, its moving correctly. Same functionality works without a problem on iOS devices.

- A-Frame Version: 0.6.1 / 0.7.1 / 0.7.1
- Platform / Device: Android 8.0.0 / OnePlus 5  (and other devices)
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/360-image-gallery/

**Comment by dmarcos** [comment]
Yes, this is causes by a Chrome bug. More info: https://github.com/aframevr/aframe/issues/3458
