### ISSUE TITLE
Raycaster ignores `visible="false"` rather than `material="visible: false;"` when no raycaster objects are defined

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#3552]
**Description:**

According to the A-Frame docs (https://aframe.io/docs/0.8.0/components/material.html#properties_visible), raycasters should ignore entities with `material="visible: false;"` rather than those with `visible="false"`.

It appears that the opposite is happening.

- A-Frame Version: `0.7.*` - `0.8.*`
- Reproducible Code Snippet or URL: https://codepen.io/dansinni/pen/bMEKxQ

**Comment by ngokevin** [comment]
Can you update the docs? Probably three.js changed the behavior?

**Comment by ngokevin** [comment]
This is a dupe.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/issues/3551
