### ISSUE TITLE
A-Frame is adding grey border around the opaque part of png image. 

### ISSUE THREAD

**Issue by deckewandboden** [aframevr/aframe#3554]
A-Frame is adding grey border around the opaque part of png image. Unable to figure out why this is happening. I would be glad to know if anyone has solved this issue.

- A-Frame Version: 0.8.0
- Platform / Device: ALL
- Reproducible Code Snippet or URL:

<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>decke wand boden TEST VR mit sky Ebenen</title>
    <meta name="description" content="decke wand boden TEST VR mit sky Ebenen">
    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    
    <script src="assets/aframe_min.js"></script>
    <script src="assets/aframe-animation-component-4-1-2.min.js"></script>
    <script src="assets/aframe-event-set-component-4-1-1.min.js"></script>
   </head>

        <a-assets>
			<img id="pano00" lazy-load="chunk: 0" crossorigin="anonymous" src="http://schneewind.decke-wand-boden.de/images/Panorama09-2.png">
			<img id="pano01" lazy-load="chunk: 1" crossorigin="anonymous" src="http://schneewind.decke-wand-boden.de/images/Panorama08-2.png">
		</a-assets>
	
	<a-entity>
		<a-sky id="Boden" src="#pano00" rotation="0 -130 0" radius="5000" transparent="true"></a-sky>
	</a-entity>

	<a-entity>
		<a-sky id="Raum" src="#pano01" rotation="0 -130 0" radius="5000" transparent="false"></a-sky>
	</a-entity>

      
    <a-entity laser-controls></a-entity>
        <a-entity camera="userHeight: 1.6; fov: 60" wasd-controls="true" look-controls mouse-cursor position= "" ">
            <a-cursor id="cursor" fuse="true" animation__click="property: scale; startEvents: click; from: 0.1 0.1 0.1; to: 1 1 1; dur: 150" animation__fusing="property: scale; startEvents: fusing; from: 1 1 1; to: 0.1 0.1 0.1; dur: 1000" animation__leave="property: scale; startEvents: mouseleave; to: 1 1 1" event-set__1="_event: mouseenter; color: #eab11c" event-set__2="_event: mouseleave; color: grey" raycaster="objects: .link" position="" rotation="" scale="" visible="" material="" cursor="" geometry="" color="grey"></a-cursor>
    </a-entity>

    </a-scene>

</body>
</html>

**Comment by dsinni** [comment]
@deckewandboden Maybe try adjusting the `material.alphaTest` property: https://aframe.io/docs/master/components/material.html#properties_alphatest

**Comment by dmarcos** [comment]
@deckewandboden Is this still a problem?

**Comment by dmarcos** [comment]
Closing because of lack of info / activity.
