### ISSUE TITLE
entity text is blurry in a-box element

### ISSUE THREAD

**Issue by CampoGrande** [aframevr/aframe#3557]
**Description:**

- A-Frame Version: 0.8.0
- Platform / Device: Desktops
- Reproducible Code Snippet or URL: 

Not sure if this topic belongs here but I have an a-entity text inside an a-box element and the text looks blurred out 

![words blurry why](https://user-images.githubusercontent.com/34080430/39238340-8955997c-48b0-11e8-998c-ddf2956fb049.JPG)

These are the lines the box is in
```
<a-box id="box1" material="src: img/info.svg; transparent:true;" position="0 2 -1.8" rotation="0 0 0" depth="0" width="1" height="1" scale="0.001 0.001 0">
    <a-entity id="info" width="1" position="0 0 0.6" text="value: This is the Mac desktop computer IXD has purchased to supply their students with adequate equipment so that they are capable of accomplishing projects even if they do not have their own Mac OS based system; color:#000;">
    </a-entity>
    <a-circle id="box1-close" radius="0.06" class="clickable" material="src: img/close.svg; transparent:true;" remove-yellow position="0.4 0.4 0.6" rotation="0 0 0" scale="1 1 0"></a-circle>
</a-box>
```
I suspect the problem may be with the anti aliasing but I have already manually turned it on in my a-scene

**Comment by aas395** [comment]
Also having this problem

**Comment by machenmusik** [comment]
Looks to me as if it is trying to antialias against black... but it also looks as though the the text is behind the svg texture on the box?  Unless the camera has been flipped around...

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/3764
