### ISSUE TITLE
Sound is only positional from the cameras starting position

### ISSUE THREAD

**Issue by staus** [aframevr/aframe#356]
Try to move the camera around:
http://codepen.io/anon/pen/eJvNvb

For me it seems as if the sound position is only calculated based on the cameras starting position/rotation. As soon as you move around or rotate the camera, it's no longer correct

**Comment by dmarcos** [comment]
This is a bug. I filed https://github.com/aframevr/aframe-core/issues/765 in core to track this problem.

**Comment by mkungla** [comment]
@ngokevin this issue seems to be solved but issue have left open since commit message was not correctly formatted to auto close this.
