### ISSUE TITLE
Mixins overriding previous `setAttribute` calls

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#3560]
**Description:** When making sequential calls to `setAttribute`, each setting a different subset of component properties, mixin values will override directly set values from prior calls. Is this the intended behavior?

- A-Frame Version: 0.8.2
- Platform / Device: Desktop Chrome
- Reproducible Code Snippet or URL:

```html
<a-mixin id="testMixin" material="visible: false"></a-mixin>
...
<a-entity id="testEntity" mixin="testMixin"></a-entity>
```
```js
const e = document.getElementById('testEntity') // material.visible === false
e.setAttribute('material', {visible: true}) // material.visible === true
e.setAttribute('material', {color: #FFF}) // material.visible === false
```

This occurs because the previous `attrValue` is incorporated before the mixins ([here](https://github.com/aframevr/aframe/blob/master/src/core/component.js#L373)) and then overwritten by mixins ([here](https://github.com/aframevr/aframe/blob/master/src/core/component.js#L391))

**Comment by ngokevin** [comment]
after refactoring the core, no longer seems to be an issue: https://github.com/aframevr/aframe/pull/3864
