### ISSUE TITLE
TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by oldpacklikez** [aframevr/aframe#3562]
71334 |   geometry.update(utils.extend({}, data, {
  71335 |     font: font,
  71336 |     width: computeWidth(data.wrapPixels, data.wrapCount, font.widthFactor),
> 71337 |     text: data.value.toString().replace(/\\n/g, '\n').replace(/\\t/g, '\t'),
  71338 |     lineHeight: data.lineHeight || font.common.lineHeight
  71339 |   }));
  71340 | }
 
start from this
  52 | tvSwitch() {
> 53 |   this.setState({
  54 |     tv: this.state.tv?false:true
  55 |   });

please help

**Comment by dmarcos** [comment]
Can you share a complete runnable example with for instance glitch.com? There’s not enough context to see what’s happening

**Comment by ngokevin** [comment]
ask at https://stackoverflow.com/tags/aframe
