### ISSUE TITLE
aframe is hyper-sensitive to movement, causing images to shake rapidly

### ISSUE THREAD

**Issue by Lissy93** [aframevr/aframe#3565]
**Description:**

On Android devices, across all browsers, some aframe examples shake like crazy at the smallest movement.
 
- A-Frame Version: 0.8.0 (and V 0.7.0/ 0.7.0 too)
- Platform / Device: Android (all, but tested on One Plus 5, Sony Xperia Z3 and Z5 Compact, Pixel 1 and Pixel 2)
- Reproducible Code Snippet or URL: Official [aframe videosphere Example](https://aframe.io/examples/showcase/videosphere/) or [aframe lights showcase](https://aframe.io/examples/showcase/lights/) 

[Here are some screen recording of the issue](https://photos.app.goo.gl/cFYv79UxouZsgKvF6)  _(Note that I was actually holding this device pretty still, not shaking it around!)_

[aframe-jolting-bug-video.mp4.zip](https://github.com/aframevr/aframe/files/1964161/aframe-bathroom.copy.mp4.zip)

**Comment by dmarcos** [comment]
This is due to changes / bugs in Chrome m65. Make sure you update to A-Frame 0.8.2 and Chrome m66. More info here: https://github.com/aframevr/aframe/issues/3476

**Comment by Lissy93** [comment]
Thanks for your reply 😄 

I'm using Chrome (Canary) 68.0.34, but the same issue exists in the latest version of Firefox also. 
The latest available version of aframe on the releases, and through Yarn is still 0.8.1, where this bug still persists.

When I manually updated aframe version, it worked in Firefox, but not Canary (both incognito/ private browsing version).

[Here's a video outlining the issue in Chrome ](https://photos.app.goo.gl/n4ncNM4hf7L5T4XX6)

**Comment by dmarcos** [comment]
@Lissy93 Upgrade to 0.8.2. It’s the latest published version:

https://www.npmjs.com/package/aframe

**Comment by cjboranp** [comment]
@Lissy93 I had the same issue after I checked out a new version of the library. I ended up backing up my files into a new folder and doing a pull of the repo. I don't know why that worked, but it did and I'm happy.

**Comment by Lissy93** [comment]
Yeah, it's fixed in 0.8.2. Thanks to Dmarcos and jsantell  for the polyfil 💯

**Comment by Fede-viale** [comment]
Hi all! 

something similar is happening. We tested in many different android devices and the result is something like this video I attached you.

Do you know if there is a bug reported like this again? 

https://user-images.githubusercontent.com/98468287/162204085-9422403d-0de1-4eae-b1f9-111782f800c6.mp4
