### ISSUE TITLE
package.json includes non-NPM dependencies

### ISSUE THREAD

**Issue by IntegersOfK** [aframevr/aframe#3566]
Hi, I am having trouble on-boarding A-Frame at my company because the security review process requires that all dependencies be downloaded from http://npmjs.com but the [package.json](https://github.com/aframevr/aframe/blob/master/package.json) includes two dependency libraries from Github.

```
"debug": "ngokevin/debug#noTimestamp",
"document-register-element": "dmarcos/document-register-element#8ccc532b7",
```

Is there any reason these two libraries are being pulled in from Github instead of traditional NPM?

It seems they are also available on NPM:

- https://www.npmjs.com/package/debug
- https://www.npmjs.com/package/document-register-element

I can make a fork and change that myself, but I'm worried there is some reason _these versions_ of `debug` and `document-register-element` are being used. Will it break something if I switch to the NPM versions? What's so special about these anyway?

Thanks for any advice.

**Comment by donmccurdy** [comment]
Both dependencies are forked versions of the original, as some changes were necessary for whatever reason. I don't recall the particular changes, but things will likely break if they're switched to the npm versions. We also occasionally need to reference a forked version of three.js, although that's usually a temporary thing.

If these changes don't make sense to merge into the official packages, I think the best option would be to just put both dependencies in scoped npm packages.

This could be done on our end, as `@aframe/debug` and `@aframe/document-register-element` or by your company. Would defer to @dmarcos and @ngokevin whether it seems OK to do this on our side.

**Comment by donmccurdy** [comment]
There are a couple more in devDependencies — are those not an issue for your security review?

**Comment by IntegersOfK** [comment]
That's a great idea! I would really appreciate if you would consider making the official A-Frame npm dependencies include scoped npm packages for those currently existing as github repos. I work at a very large firm and intend to expose thousands of users to A-Frame (already have lots of working demos) when I can finally get through this security review.

If you also include the devDependencies I personally pledge to contribute in a meaningful way (on company time!) to the project and rally similar support from developers on my visualisation team. Specifically, we are working on displaying infrastructure metrics and virtual representations of data centres in A-Frame's 3D environments, so I hope to on-board the library internally and come back with some interesting examples/contributions to this community. Thank you!

**Comment by dmarcos** [comment]
Ocasionally, we need to fix bugs or additional features in the dependencies and PRs in the original repos take time to be merged or are not accepted. 

Can you just point your application to the bundled a-frame? https://aframe.io/releases/0.8.2/aframe.js

Another solution is to take those forks, publish them in npm yourself and repoint the package.json

Just curious, What are the security concerns about npm only dependencies? npm does not have any security or review process that I know of.

**Comment by dmarcos** [comment]
I'm looking at scoped npm packages and we can definitively do it. Forked dependencies are an exception  . I feel pointing to github makes it clear and easier to follow through and see the changes. A package published on npm hides away the context and it's harder to trace back. A few issues / PRs and debugging have come from the community since the info is exposed in the package.json. @IntegersOfK We can definitively consider scoped packages but wondering if there's an alternative that we can explore that works for you

**Comment by dmarcos** [comment]
@IntegersOfK Thanks for escalating the problem. It's the first time we've heard of such an issue. We'll look into it. In the meantime, I think the described solution will work. You can republish aframe yourself in npm with the dependencies also pointing to npm published packages. Would that fulfill all your employer constraints? Is that an interim acceptable solution for you and your employer?

**Comment by dmarcos** [comment]
What about an internal CDN? @IntegersOfK Do you have an internal CDN where you can copy the A-Frame bundle where it's consumed from internally?

**Comment by IntegersOfK** [comment]
Ok so in conclusion it looks like I will have to re-publish A-Frame, while either making scoped packages from those Github repos or I might just take the release version and throw it into a package to publish it myself.

Thank you all for taking the time to learn about this rather silly corner-case of corporate development using A-Frame, I really appreciate it.

**Comment by IntegersOfK** [comment]
I have uploaded scoped copies of the required branches/commits from the github repositories, updated package.json + relevant imports, and re-uploaded a scoped version of A-Frame. Additionally, I copied roboto.css font into the package so there are no external downloads necessary whatsoever. 
https://www.npmjs.com/package/@ajwest/aframe

I will try to maintain any updates in my "captive" branch:
https://github.com/IntegersOfK/aframe/tree/captive

Thank you all for the suggestions, I hope this will help other people like me who need all dependencies to be contained within NPM directly.

**Comment by dmarcos** [comment]
@IntegersOfK That's awesome. Thanks for doing that work. I will definitively direct people with the same problem to your package.

**Comment by ShashankaNataraj** [comment]
@dmarcos @IntegersOfK @donmccurdy I have this exact same problem!

Our company has jenkins build jobs which can access a private NPM but the public NPM is inaccessible / against company policy. I will be trying out @IntegersOfK 's packages but they seem a bit out of date.

Has there been any better solution to this issue?
