### ISSUE TITLE
Increase resolution for Oculus Go

### ISSUE THREAD

**Issue by kevinsimper** [aframevr/aframe#3571]
I have tested out Aframe with Oculus Go and the experience is not as great in terms of resolution compared to React 360. I am not sure what it can be?

https://github.com/facebook/react-360

It is pretty difficult to debug since you can't see the developer toolbar in the Oculus Go webbrowser.

I have searched the docs and the issues and it seems to be something with similar to mobile devices asking about the resolution, but I am creating a new issue because I have not seen it compared to React360 (prev. ReactVR) where the resolution is good.

**Comment by dmarcos** [comment]
Thanks for sharing the info with us. Can you share a bit more detail? Any specific examples you can point? Do you mean text resolution? Are you referring to 360 video or real time 3D? I tested the A-Frame examples yesterday on the Go and they looked good to me.

**Comment by kevinsimper** [comment]
@dmarcos Thanks for replying

It is the aframe example with the 3 red, yellow, blue objects, where the straight lines on particular the blue square is really rought.

There is no anti-alias on that line as you can see the line drop down as if the pixels where that huge, but they aren't they are just rendered double the pixels and with no anti-alias

Here is the image on my macbook pro.
![image](https://user-images.githubusercontent.com/1126497/39716999-3fb75072-5232-11e8-8a19-884cdd20fd7b.png)

I can't record in full screen as it stops immediately after

![image](https://user-images.githubusercontent.com/1126497/39717201-d3837556-5232-11e8-889c-8f86363f8a01.png)

**Comment by kevinsimper** [comment]
Also the grey background is suddenly white when VR is activated down in the corner, which makes it super bright and unconfortable to look at, compared to the grey color.

**Comment by dmarcos** [comment]
The examples in aframe.io have antialias disabled by default on mobile for increased performance. You can enable it in your experiences by doing `<a-scene antialias="true">`

**Comment by kevinsimper** [comment]
@dmarcos I could not see that in the documentation, therefore I thought it did not exist anymore.

Should it exist on this page?

**Comment by kevinsimper** [comment]
Just tested it again and yeah that is what is needed.

**Comment by dmarcos** [comment]
Cool. Yeah it seems to be missing from docs. FYI, it will be replaced in next aframe version in favor of the renderer component:

https://github.com/aframevr/aframe/blob/master/docs/components/renderer.md

**Comment by kevinsimper** [comment]
@dmarcos Awesome, thanks for the help!
