### ISSUE TITLE
WebGLInfo: Renamed primitives since three v91 (info)

### ISSUE THREAD

**Issue by arpu** [aframevr/aframe#3573]
- A-Frame Version: A-Frame Version: 0.8.2 (Date 2018-05-07, Commit #050cbaf) three Version: 0.92.0 
- Platform / Device: Version 66.0.3359.139 (Offizieller Build) (64-Bit)
- Reproducible Code Snippet or URL: https://a-frobot.github.io/aframe/examples/performance/cubes/

https://github.com/mrdoob/three.js/commit/bd8f751f73a8c849540ffeb7346d697145c2b9f5#diff-489f2404e69a7f3736ada32f3af6c3c3

**Comment by dmarcos** [comment]
What is exactly the problem?

**Comment by arpu** [comment]
the stats Vertices and Faces are NaN
looks like the https://github.com/aframevr/aframe/blob/master/vendor/rStats.extras.js needs an update

**Comment by ngokevin** [comment]
A PR for that would be welcome!
