### ISSUE TITLE
Antialias not working in Gear in dynamically created scene DOM

### ISSUE THREAD

**Issue by bklava** [aframevr/aframe#3574]
In a dynamically created scene DOM, the antialias attribute seems to be ignored when viewing in the Gear VR:
- code: https://bklava.github.io/issues/aframe/gear-antialias/dynamic.html
- result: https://bklava.github.io/issues/aframe/gear-antialias/dynamic.jpg

Dynamic result detail:
![Dynamic](https://bklava.github.io/issues/aframe/gear-antialias/dynamic-detail.jpg)

Notice that the antialias attribute is set:
```javascript
scene.setAttribute('antialias', 'true');
```
This is not an issue if the scene DOM is statically created:
- code: https://bklava.github.io/issues/aframe/gear-antialias/static.html
- result: https://bklava.github.io/issues/aframe/gear-antialias/static.jpg

Static result detail:
![Static](https://bklava.github.io/issues/aframe/gear-antialias/static-detail.jpg)

Neither if AFrame is downgraded to 0.6.0: https://bklava.github.io/issues/aframe/gear-antialias/dynamic-6.html

Am I missing something?

- A-Frame Version: 0.8.2
- Platform / Device: Android / Samsung S7 + Samsung Internet + Gear VR
- Reproducible Code Snippet or URL: https://bklava.github.io/issues/aframe/gear-antialias/dynamic.html

**Comment by dmarcos** [comment]
@bklava Is the result the same on the Oculus Browser?

**Comment by bklava** [comment]
@dmarcos Yes, exactly the same. I've just checked it.
