### ISSUE TITLE
start all aframe animations by click

### ISSUE THREAD

**Issue by qxsch** [aframevr/aframe#358]
iOS devices wont play videos in case there was not a user click event.
So i use a start button.
Unfortunantely the animations already start uppon document.onload and are no longer in sync.

**Comment by ngokevin** [comment]
Could be configurable with a scene component.

**Comment by cvan** [comment]
@jcarpenter, @dmarcos we've talked about how to trigger/delay animations several times on and off weeks back. did we reach a conclusion of how we want to handle (either imperatively or declaratively) starting animations? we should probably put all the proposals together somewhere here in an issue to weigh the pros and cons and come to a conclusion.

a related issue: aframevr/aframe-core#761

**Comment by qxsch** [comment]
@ngokevin how can this be configured with a scene component?

@cvan sounds good. i also love the idea with different timelines. :-)

**Comment by ngokevin** [comment]
Not heavily documented yet, but components can be created for scenes. If we implement this, we might be having the scene wait for a event before starting the render loop. Clever way would be attaching a custom node that we control when it becomes loaded, which forces the scene to wait.

```
registerComponent('scene-wait-event', {
  schema: {
    eventName: { default: '' }
  },

  init: function () {
    if (!this.data.eventName) { return; }
    var node = document.createElement('a-node');
    el.appendChild(node);
    document.body.addEventListener(eventName, function () {
      node.load();
    });
  }
});
```

**Comment by ngokevin** [comment]
You can also use the `begin` attr to control when animations play https://aframe.io/docs/core/animation.html#Begin

**Comment by paulina-grunwald** [comment]
With begin i have to use integer (Delay (in milliseconds) or event name to wait on before beginning animation.) Is it possible to begin animation on click?
