### ISSUE TITLE
Normal map appears reversed

### ISSUE THREAD

**Issue by j-conrad** [aframevr/aframe#3580]
**Description:**
I have created a normal (bump) map in Substance Painter using a hard surface decal of a vent. When viewed in Painter with a light shining from above, it appears seemingly correct. This is further validated when exporting the map and viewing the same scene in Maya (StingrayPBR material). Lastly, when converting to a glTF (using the Facebook FBX2glTF converter) and viewing the scene in Don McCurdy's glTF viewer, it also appears correct. However, when loading that glTF into A-Frame and adding lights, the normal map appears reversed. (see attached images)
I have replicated this with a handful of normal maps, hand-painted or otherwise.

- A-Frame Version: 0.8.0
- Platform / Device: PC
![aframe_normalreversal](https://user-images.githubusercontent.com/31968496/39954826-997639a2-557a-11e8-8711-3c9bab4a75c9.jpg)

- Reproducible Code Snippet or URL:

**Comment by donmccurdy** [comment]
You’ll need to set `texture.flipY=false` when manually adding a texture to a glTF model.  This happens automatically for textures included in the model.

**Comment by j-conrad** [comment]
Actually, the FBX exported from Maya had its textures embedded before converting to glTF. And again, the glTF file appears correct— it’s only when it gets added to A-Frame that the normal gets flipped. Unless I’m misunderstanding what you mean by ‘textures included in the model’. Are you perhaps referring to a .glb vs .glTF?

**Comment by donmccurdy** [comment]
Oops, I should have looked at the images before replying. Never mind about the "textures included" thing. Does this scene use a mirror modifier by any chance? This looks like a bug from previous versions of three.js. You may be able to manually fix this after import with something like:

```
var el = document.querySelector('#my-model');
el.object3D.traverse((node) => {
  if (node.isMesh) {
    node.material.normalScale.y *= -1.0;
  }
});
```

**Comment by machenmusik** [comment]
what does this look like with 0.8.2 / latest master?

**Comment by j-conrad** [comment]
Upon further investigation, it appears that this bug is only occurring on Mozilla Hubs. Still troubleshooting what's causing it, but it's not an a-frame specific bug.

**Comment by colinfizgig** [comment]
Actually I'm seeing this Bug on all GLTFs and I can see that it happens in Three.js on import as well.  It seems to be something going on with the GLTF import? I've noticed that if I import a gltf into three.js editor , the y normal is upside down.  But if I convert that material to a phong and turn the same normal map back on it looks correct.  If I convert the material back to a standard material then its normal map looks correct.  This seems to be something in the conversion from Maya FBX to GLTF, perhaps in the FBX2GLtf converter I used provided by Facebook?  Here is an image to show what is going on.

![normal map issue with gltf](https://user-images.githubusercontent.com/7503097/47534559-c01a5000-d885-11e8-83e8-69f871f17717.jpg)

**Comment by donmccurdy** [comment]
@colinfizgig Could you start a new thread on the three.js repository or http://discourse.threejs.org/, if the problem seems to be more general than A-Frame? It would help to know more specifically what steps will reproduce this error in the threejs editor, and whether the normal map is inverted on http://gltf-viewer.donmccurdy.com/ and http://sandbox.babylonjs.com/.

**Comment by colinfizgig** [comment]
It was the difference between exporting Normal Maps for DirectX format versus OpenGL format.  I'll have to check my Substance Painter settings to see how to export the maps properly.
