### ISSUE TITLE
Accessing real time Vive controller position data

### ISSUE THREAD

**Issue by bday336** [aframevr/aframe#3582]
**Description:**

I have been searching for a while now through the various documentations, but I have yet to find if there is a way to obtain the real time position information for the controllers in the VR environment. Once the controllers are loaded and in the scene I have tried to obtain position data from

controller_left.getAttribute('position')

as well as

controller_left.object3D.position

However both always say that the controllers are at (0,0,0) even when I move them. It would seem the components I am using know where the controllers are so that sphere-collider and things like that work, however I would like to get the real time position data myself to see where the controllers are in the VR environment.

- A-Frame Version: 0.7.0
- Platform / Device: Firefox / Vive
- Reproducible Code Snippet or URL:

https://glitch.com/edit/#!/jolly-nurse?path=views/index.html:18:49

**Comment by dmarcos** [comment]
Can you open a question on StackOverFlow and post it on Slack? We use github issues for bugs and feature requests.

**Comment by dmarcos** [comment]
Not sure how `super-hands` work. Better to ask in [their repo](https://github.com/wmurphyrd/aframe-super-hands-component). The A-Frame [tracked-controls](https://aframe.io/aframe/examples/showcase/tracked-controls/) example works as expected. In console:
![hand](https://d3vv6lp55qjaqc.cloudfront.net/items/3U2B2X101t2v0F43382k/Image%202018-05-14%20at%202.01.58%20AM.png?X-CloudApp-Visitor-Id=222920&v=3149d6b2)

**Comment by dmarcos** [comment]
FWIW, the `super-hands` examples work also as expected. For instance: https://wmurphyrd.github.io/aframe-super-hands-component/examples/physics/
In console:
![super-hands](https://d3vv6lp55qjaqc.cloudfront.net/items/2r1U3n0O471a2U3K1D1P/Image%202018-05-14%20at%202.06.19%20AM.png?X-CloudApp-Visitor-Id=222920&v=cc9a819c)
