### ISSUE TITLE
Some A-Frame demos are cock-eyed in Oculus Go

### ISSUE THREAD

**Issue by ffxsam** [aframevr/aframe#3584]
Some of the demos on https://aframe.io/ are "cock-eyed" in the Oculus Go for some reason. For example:
* Hello Metaverse
* Snowglobe
* Animation (also extremely choppy)

Others work perfectly fine:
* Anime UI
* Shopping
* Hello WebVR

For the bottom list, I click on the Cardboard icon and they just work. For the first list, clicking on the cardboard icon zooms the screen up but it's still 2D, and I'm presented with several viewing options (3D, 360, 360 3D, 180, 180 3D). None of them look right.

![com oculus vrshell-20180515-083442](https://user-images.githubusercontent.com/12532733/40060318-ecbf1a9a-581b-11e8-8019-60f8cad10346.jpg)
![com oculus vrshell-20180515-083931](https://user-images.githubusercontent.com/12532733/40060327-f476d9bc-581b-11e8-9acc-f5b5eaaa7781.jpg)

**Comment by dmarcos** [comment]
Those examples you listed first are external demos we link that probably don’t have an up to datr A-Frame. The A-Frame
built in examples live in https://aframe.io/aframe/examples/ and those should all work as expected
