### ISSUE TITLE
Script at top vs script at bottom?

### ISSUE THREAD

**Issue by greggman** [aframevr/aframe#3587]
**Description:**

When I put the aframe script at the bottom I get this message

> A-Frame:warn Put the A-Frame <script> tag in the <head> of the HTML *before* the scene to ensure everything for A-Frame is properly registered before they are used from HTML. 
aframe.min.js:26:633

- A-Frame Version: 0.8.0 (Date 2018-03-11, Commit #82934b02)
- Platform / Device: N/A
- Reproducible Code Snippet or URL: N/A

What is really the issue here? It seems to work at the bottom. I'd think a-frame would scan the DOM on startup. Is there an example of a concrete issue that putting the script at the top solves? Just trying to both make sure it's not voodoo that it should be at the top and also understand the issues for my own knowledge of custom elements.

**Comment by dmarcos** [comment]
You have to put the script at the top so the A-Frame custom elements: a-entity, a-box... are registered when the DOM initializes. That’s how custom elements work. A-Frame does not scan / parse the DOM. Let us know if you have any other questions

**Comment by greggman** [comment]
Hmm, ok, well, putting at the bottom works just fine so I think maybe it's not doing what you think it's doing.

It would be good to know a concrete reason why I needs to be at the top vs just voodoo since it's working just fine at the bottom.

http://greggman.github.io/doodles/test/aframe-script-at-bottom/aframe-script-at-bottom.html
