### ISSUE TITLE
utils.diff() not working for arrays

### ISSUE THREAD

**Issue by harlyq** [aframevr/aframe#3591]
**Description:**
AFRAME.utils.diff() does not perform a deepEquals (i.e. per element check) on arrays. Is this deliberate?

- A-Frame Version: 0.8.2
- Platform / Device: PC
- Reproducible Code Snippet or URL:
```javascript
      var diff = AFRAME.utils.diff( {a:[0]}, {a:[0]} )
      console.log(diff) // shows {a:[0]}, expecting {}
```

Looking at the diff code:
https://github.com/aframevr/aframe/blob/master/src/utils/index.js#L232
```javascript
      isComparingObjects = aVal && bVal &&
                          aVal.constructor === Object && bVal.constructor === Object;
      if ((isComparingObjects && !deepEqual(aVal, bVal)) ||
          (!isComparingObjects && aVal !== bVal)) {
        diff[key] = bVal;
      }
```
the **constructor** for arrays is **Array**

**Comment by ngokevin** [comment]
Yeah, only for objects.
