### ISSUE TITLE
resolution drops on mobile when exiting VR-mode

### ISSUE THREAD

**Issue by markkorput** [aframevr/aframe#3592]
**Description:**
I’m having an issue with Aframe on mobile dramatically reducing the resolution after exiting vr-mode. Basically the resolution drops from 1080p to 360p (based on canvas.width/.height and renderer.getSize()). 

I can find other posts about issues with the resolution in VR-mode (like #3075 #3160 #3031 #2761) but for some reason I can’t find anything on this situation though it happens consistently for me on both Android and iPhone devices and for seemingly every aframe demo I can find online (not just my own app).

Image when entered into VR-mode;
![before](https://user-images.githubusercontent.com/205974/40299207-d80fd7be-5ce5-11e8-87a9-eba57133c954.png)

Image after exiting VR-mode;
![after](https://i.stack.imgur.com/FBzKV.png)

See also my stackoverflow post; https://stackoverflow.com/questions/50394308/aframe-resolution-drops-on-mobile-when-exiting-vr-mode 

- A-Frame Version: 0.8.2
- Platform / Device: Android/iPhone Firefox & Chrome
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

**Comment by bklava** [comment]
I had this problem before. Investigating I found that the renderer pixel ratio gets wrong when you exit VR mode. The solution for me was to add the following line after line 479 in a-scene.js https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L479

```javascript
this.renderer.setPixelRatio(window.devicePixelRatio);
```

Does it solve your problem?

**Comment by markkorput** [comment]
thanks @bklava that does seem to help! You aware if there was already made a pull request for this?

**Comment by azmartone** [comment]
Why was this closed? It doesn't seem like it was fixed in master.

**Comment by markkorput** [comment]
I guess I closed it inadvertently, want me to reopen?

**Comment by azmartone** [comment]
Sure. I was trying to track down the PR which you mentioned handled this, but couldn't find it.

**Comment by tomegz** [comment]
Seems like this is still a thing. Would `setPixelRatio` call on exiting VR be an overkill for this?

**Comment by TyrealGray** [comment]
Is there any fix for that? The issue still exists on mobile
