### ISSUE TITLE
<a-text> component, bold text

### ISSUE THREAD

**Issue by DaniAframe** [aframevr/aframe#3597]
**Description:**

Hello, i'm using the tag "a-text" because i wanna see some words on the browser canvas, for example

"hello: 1
 github: 2"

but i wanna show the words "hello" and "github" in bold, and the numbers. Like this:

"**hello**: 1
**github** : 2"

Does anyone knows how to do this?

Thanks

**Comment by donmccurdy** [comment]
Weights cannot just be added to fonts at display time in WebGL like they can in HTML — I think you'll need to generate a font with the weight you need. See https://aframe.io/docs/0.8.0/components/text.html#generating-sdf-fonts.

**Comment by ngokevin** [comment]
https://github.com/etiennepinchon/aframe-fonts
