### ISSUE TITLE
Performance on Oculus Go

### ISSUE THREAD

**Issue by kevinsimper** [aframevr/aframe#3598]
Awesome work with Aframe, really appreciates it!

I want to ask about performance on the Oculus Go, I am with the stats module only getting 46 fps for what is a really simple scene, also without the anti-alias attribute.

https://glitch.com/edit/#!/lunar-stealer?path=index.html:10:116

![image](https://user-images.githubusercontent.com/1126497/40458713-ca5bf278-5efd-11e8-89f4-e8f4c90905fa.png)

The image taken inside the Oculus weirdly says 63, must be the way it takes a screenshot that gives the browser more cpu time as the screen goes black while it does it, but the raf says correctly 24,5 which would be 1000/24,5=40,8 fps

I know it is probably premature optimization, but shouldn't it be able to get 60 fps and a raf of 16? Will this make the animation stutter if the scene just get a little more complicated?

**Comment by dmarcos** [comment]
Thanks for reporting. Just tried your demo on the Go and I was hitting 55-60 fps consistently in 2D mode and performance in VR mode looks good to me as well. We need additional information on what you're observing.

**Comment by banada** [comment]
In my experience, the perf tool itself has some overhead. Does it feel much smoother when you disable it?

**Comment by dmarcos** [comment]
The perf tool has some overhead but the numbers I got is with the tool enabled. I don't see any issues with perf on the Go with the provided example. I'm closing this but will reopen if there's additional info.
