### ISSUE TITLE
Broken build on ember-cli due to webvr-polyfill issue

### ISSUE THREAD

**Issue by gabrielgrant** [aframevr/aframe#3603]
**Description:**

Build of a project including AFrame fails with ember-cli (on Node) due to immersive-web/webvr-polyfill#322

Please update the dependency when immersive-web/webvr-polyfill#323 is (hopefully) merged

- A-Frame Version: 0.8.2
- Platform / Device: node 8.4.0

**Comment by machenmusik** [comment]
Is the problem here the screen global, or the function replacement with ES6 usage in the diff?  Or both?  A while back, I had issues where ES6 usage would break things if not transpired...

**Comment by gabrielgrant** [comment]
@machenmusik sorry, I'm not sure I follow what you mean about ES6 function replacement? AFAICT the issue is that the module gets imported into node, executing the code at global/module scope, which tries to access the (non-existent) `screen` variable, and errors. (but, full disclosure: i'm not intimately familiar with how the ember-cli/broccoli build process works)

**Comment by gabrielgrant** [comment]
The upstream PR has been moved to here: https://github.com/immersive-web/cardboard-vr-display/pull/25

**Comment by jsantell** [comment]
The change has landed downstream in webvr-polyfill `0.10.7` which no longer uses `screen`. The build/main export is an ES5 UMD bundle; any accessing of `src/*` files is up to the consumer to handle

**Comment by gabrielgrant** [comment]
pushed the fix into the PR at #3604

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/3604
