### ISSUE TITLE
hebrew texts are rendered in reverse

### ISSUE THREAD

**Issue by eyaler** [aframevr/aframe#3607]
text elements render hebrew text in reverse string order.
simply reversing the string is not sufficient because it will introduce errors for multilingual text, multi-digit numbers, and multi-line wrappings

**Comment by dmarcos** [comment]
There’s not `right-to-left` support in the text component. I opened a more general issue: https://github.com/aframevr/aframe/issues/3612
Any community help will be more than welcome
