### ISSUE TITLE
Hotspot related questions

### ISSUE THREAD

**Issue by yuehkchou** [aframevr/aframe#3611]
**Description:**

Hi, I was wondering if there is a way to create hotspots in aframe without utilizing the components like in the "360 Gallery" in the example page. And create hotspot via DOMElements to overlay on top of the canvas.

I stumbled upon this [link](https://www.youtube.com/watch?v=xOCNWqnuqoI): and was hoping to get some calrification if the "<a-hotspot>" tag exist at all in the current aframe?

Thank you in advance.

- A-Frame Version: v0.8.0 Latest
- Platform / Device: MacOSX High Sierra
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
You could create hotspots with regular DOM elements positioned with 3D transforms but they won’t render in VR mode when used in a headset. I recommend using StackOverflow to ask questions. We use Github issues for bugs and feature requests.
