### ISSUE TITLE
Videosphere frozen on first frame of video

### ISSUE THREAD

**Issue by temucher** [aframevr/aframe#3614]
**Description:**
Similar to #3507 except the video does not even play at all for me. Further, the videosphere just displays white for 0.5, 0.6, and 0.7. I tried using the `material="side: back"` from #3444 , to no avail.

I am also getting the same error as #3507 :

`core:a-assets-warn Asset loading timed out in 3000 ms`

- A-Frame Version: 0.8.0
- Platform / Device: Desktop Firefox and Chrome
- Reproducible Code Snippet or URL:

Code boiled down to just the video stuff: 
```HTML
<!DOCTYPE html>
<html>
  <head>
    <script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>
      <a-assets>
        <video id="base" data-dashjs-player loop="true" src="videos/Scene1_Take1.mp4" preload="auto" crossorigin="anonymous" playsinline webkit-playsinline></video>
      </a-assets>

      <a-videosphere id="videosphere" src="#base" rotation="0 180 0" material="side: back" play-on-verdisplayactivate-or-enter-vr play-on-window-click></a-videosphere>
    </a-scene>
  </body>
</html>

```

**Comment by machenmusik** [comment]
You have an extra right angle brace in there?  Also, looks like you are using some additional player bits, and sometimes (like video.js) they will wrap or modify the original video element given, which may break things without correction

**Comment by temucher** [comment]
@machenmusik  Whoops first one was a copy paste mistake. 

Removing the additional bits dont have any effect, it's still not playing the video.

**Comment by machenmusik** [comment]
maybe it's the video?  this glitch works, with a click to play handler where needed...
https://glitch.com/edit/#!/citrine-parenthesis

**Comment by temucher** [comment]
Hmm could the video potentially be too large? I couldn't find anything in the documentation about that. Or what else could be wrong with it?

**Comment by machenmusik** [comment]
So many things :-/
Recent problems seen and solved:
- wrong codec (original mpeg4 video, needed h264)
- CORS permissions (should not be the problem here)
- big MP4 video that doesn't have the "fast start" moov atom at the front, so the whole thing has to download on some browsers before playback starts

**Comment by machenmusik** [comment]
(Also the resolution of the video can be unsupported by the device...)

**Comment by temucher** [comment]
Looks like it was the click to play script that was needed. Pretty annoyed I didn't catch that sooner. But good to know about the other issues with videos, I am working on a project with lots of large videos and that info will come in handy, thanks!
