### ISSUE TITLE
Gyro doesn't function in Magic Window mode when WebVR flag set to true on chrome

### ISSUE THREAD

**Issue by akashkuttappa** [aframevr/aframe#3617]
**Description:**
I tried rendering out a scene with several models in it and enabled the WebVR flag to check it out on a daydream headset on a Samsung Galaxy S8, but the scene just froze and the gyro wasn’t functioning in Magic Window Mode. **I was able to pan the scene** with my finger in Magic Window Mode and **the gyro did function when I entered VR Mode**

I tried out the default A-frame scene which I have linked below and faced the same issue. Tested out the same on a Pixel 2 XL and a One Plus 6 and had the same results.

- A-Frame Version: 0.8.2
- Platform / Device: Galaxy S8, One Plus 6, Pixel 2 XL
- Reproducible Code Snippet or URL: https://lush-waitress.glitch.me/
- Chrome Version on Galaxy S8: 67.0.3359.158
- Chrome Version on One Plus 6: 67.0.3396.68 
- Chrome Version on Pixel 2 XL: 67.0.3396.68

**Comment by dmarcos** [comment]
Not sure I understand the problem. I just tried on Chrome 66 and 69 (Canary) on a Pixel 2 and the scene you pointed out enters VR mode as expected after enabling in `chrome://flags`. Can you describe exactly the steps you followed and what you expect vs. what you get?

**Comment by akashkuttappa** [comment]
VR Mode works just fine, I'm talking the gyro not working while opening the above scene and viewing it in basic 360 mode when the WevVR flag is enabled. The gyro works just fine when I enter VR but not when I'm in 360 mode.

Linked a video here : https://youtu.be/KBMdWM9opG0
