### ISSUE TITLE
Strange behaviour of mouseenter and mouseleave events on nested elements.

### ISSUE THREAD

**Issue by krzysztof-grzybek** [aframevr/aframe#3624]
Events `mouseenter` and `mouseleave` (from `cursor` component) are triggered each time on parent element when moving cursor between child and parent element. 

Shouldn't `mouseleave` be triggered only if cursor is moved away from parent and it's descendants? If no, maybe this beaviour should be documented?

- A-Frame Version: 0.8.2
- Platform / Device: Chrome / Firefox
- Reproducible Code Snippet or URL: https://codepen.io/anon/pen/jKrWEZ

**Comment by ngokevin** [comment]
Yeah, it's expected. The child and parent are their own entities. The events also bubble, use `evt.target` to get the specific target. `raycaster.recursive` property can also affect things.
