### ISSUE TITLE
Stereoscopic view mode on Desktop

### ISSUE THREAD

**Issue by luiguild** [aframevr/aframe#3627]
Document how to disable the stereoscopic view on desktop mode when using HTC Vive... Why it is default? Don't make sense to me...

- A-Frame Version: 0.8.2
- Platform / Device: Desktop
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

![image](https://user-images.githubusercontent.com/16566338/41078075-cffa16b2-69f0-11e8-8e65-6e8774e64f13.png)

**Comment by dmarcos** [comment]
In your page you can place a-scene wherever you want or hide it like any other HTML element. Mirroring is the default mode because its the simplest, most performant option. Showing something different would imply rendering the scene twice degrading performance in VR. You can opt into an alternative perspective by using a specator camera: https://aframe.io/docs/0.8.0/components/camera.html#properties_spectator

**Comment by luiguild** [comment]
Ok. How to use spectator? Don't exist documentation about it or any example... I set true to spectator and I continue see the setereoscopic mode on desktop... 

I continue talking about it, because I will present a talk in this weekend using an HTC Vive on stage and it's out of ideia using the stereocopic mode during the talk... I really need desable this... I don't want create a websocket server to replicate all my scene on another browser because of this...

**Comment by luiguild** [comment]
Page Not Found :(

**Comment by dmarcos** [comment]
The link works for me.

**Comment by luiguild** [comment]
<img width="1440" alt="screen shot 2018-06-08 at 15 49 35" src="https://user-images.githubusercontent.com/16566338/41175466-8f98199a-6b33-11e8-9953-81b21010fc9b.png">

**Comment by dmarcos** [comment]
This is what I see

![shot](https://d3vv6lp55qjaqc.cloudfront.net/items/1N3c2a2w2s341N121A3g/Image%202018-06-08%20at%2011.53.20%20AM.png?X-CloudApp-Visitor-Id=222920&v=32e17a9b)

**Comment by dmarcos** [comment]
The HTML is:
````html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello, WebVR! - A-Frame</title>
    <meta name="description" content="Hello, WebVR! - A-Frame">
    <script src="https://rawgit.com/aframevr/aframe/master/dist/aframe-master.js"></script>
  </head>
  <body>
    <a-scene>
      <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9" shadow></a-box>
      <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E" shadow></a-sphere>
      <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D" shadow></a-cylinder>
      <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4" shadow></a-plane>
      <a-entity camera look-controls position="0 1 0"></a-entity>
      <a-entity camera="spectator: true" look-controls position="0 1 0"></a-entity>
      <a-sky color="#ECECEC"></a-sky>
    </a-scene>
  </body>
</html>
````

**Comment by luiguild** [comment]
It works if I use > https://oceanic-market.glitch.me/ but I'm not test using Vive yet.

Thank for your time @dmarcos.
