### ISSUE TITLE
Gltf model

### ISSUE THREAD

**Issue by Bian-yx** [aframevr/aframe#3628]
**Description:**

-6.0/7.0/8.2:
- Chrome:
-https://upward.glitch.me/

On the project I am working on,
Gltf model can be only loaded in A-frame 6.0, never works on any newer version
For any one who has the same issue, the 6.0 Afrmae is here https://aframe.io/releases/0.6.0/aframe.min.js

**Comment by dmarcos** [comment]
In 0.7.0 A-Frame moved to glTF 2.0. Make sure your model follows the new spec.

**Comment by donmccurdy** [comment]
Archilogic uses an old version of glTF that we no longer support, yes. You may be able to use the `gltf-model-legacy` component in A-Frame Extras: https://github.com/donmccurdy/aframe-extras/tree/master/src/loaders
