### ISSUE TITLE
Cant move on IOS or android

### ISSUE THREAD

**Issue by Logabe** [aframevr/aframe#3629]
Description:
When I view my page on an i-pad it doesn't allow me to move. Is there a fix?

- A-Frame Version: 0.8.2
- Platform / Device: Chrome on IOS
- Reproducible URL: [HoverTech](hover-tech.glitch.me/journey.html)

**Comment by Logabe** [comment]
As you do with WASD of the arrow keys.

**Comment by dmarcos** [comment]
A-Frame does not come with built-in locomotion in mobile. Try @donmccurdy movement-controls component https://github.com/donmccurdy/aframe-extras/tree/master/src/controls
