### ISSUE TITLE
Give visual cues of keyboard controls (and possibly mouse, gamepad)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#363]
We should probably have little indicators (or some __`[?]`__ icon) to show the keyboard controls for WASD navigation (if the scene has it enabled), `f` for entering VR Mode, `z` for resetting sensor, etc.

These aren't the best examples to draw inspiration from for our use cases, but I thought they were interesting:

![image](https://cloud.githubusercontent.com/assets/203725/12195791/c8314f02-b5ae-11e5-9197-81f468af6e0b.png)

![image](https://cloud.githubusercontent.com/assets/203725/12195807/e265434c-b5ae-11e5-9563-850cfc1c42da.png)

**Comment by ngokevin** [comment]
This might be too prescriptive. I think this is up to designer/developer to do as controls can be different from scene to scene, have to handle whether scenes are desktop/mobile/both, they will generally want their own styling. Let me know what you think.

**Comment by cvan** [comment]
> This might be too prescriptive. I think this is up to designer/developer to do as controls can be different from scene to scene, have to handle whether scenes are desktop/mobile/both, they will generally want their own styling. Let me know what you think.

idk, unless you're a gamer, I'd be willing to bet most folks don't think WASD will move you through a scene. as a non-gamer, I would assume arrow keys would work, not WASD.

**Comment by ngokevin** [comment]
True but I still think it is on the developer to provide instructions. Not all scenes will have wasd and they might be the developers own custom controls. we can't ensure what hints to display and when

**Comment by cvan** [comment]
> True but I still think it is on the developer to provide instructions. Not all scenes will have wasd and they might be the developers own custom controls. we can't ensure what hints to display and when

if we want to put the onus on the developers, it'd be prudent to document best practices of [movement](https://www.google.com/design/spec-vr/designing-for-google-cardboard/physiological-considerations.html#physiological-considerations-user-control-of-movement) and visual cues for [Entering and Exiting VR](https://www.google.com/design/spec-vr/interactive-patterns/setup.html#setup-entering-exiting).

**Comment by ngokevin** [comment]
Best practices of movement and entering/exiting VR are slightly different from describing controls to the user. 

The best thing we could do is perhaps create sample images for common control schemes that developers can put in their scene wherever they want like http://vr.lasershop.ca/. But we can't prescribe that out-of-the-box because there's no good default place to display visual cues and no good way to know what controls to describe.
