### ISSUE TITLE
Tapping in vr mode on mobile not working.

### ISSUE THREAD

**Issue by Spencer1O1** [aframevr/aframe#3633]
**Description:**

- A-Frame Version: 0.8.0
- Platform / Device: I-phone
- Reproducible Code Snippet or URL: [JSFiddle](https://jsfiddle.net/Spencer101/u645omwj/)

I made an aframe vr world, and when you are not in vr mode, if you tap, it moves you forward. However, whenever I switch to vr mode on mobile, the tapping doesn't work. Also, what is up with the screen getting darker when you tap in any mode on mobile?

**Comment by dmarcos** [comment]
In VR mode the data from the sensors override your tap to move. Move a camera rig (parent of the camera entity). More info in the docs: https://github.com/aframevr/aframe/blob/master/docs/components/camera.md
