### ISSUE TITLE
oculus go support

### ISSUE THREAD

**Issue by comsyspro** [aframevr/aframe#3635]
**Description:**

- A-Frame Version: newest
- Platform / Device: Oculus Go or alternatives
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/360-image-gallery/

I'm looking for a portable VR headset which is supported by aframe.  So does anybody know if the Oculus Go can show the 360 image gallery example?

https://aframe.io/examples/showcase/360-image-gallery/

If yes, how can you upload the aframe code to the Oculus Go? Do you need a Wireless connection to the PC? Or must it be accessed by a browser - if so does Oculus Go have a inbuilt browser and internet connection?

Are there also any other portable VR headsets like Oculus Go (no cardboards, no smartphones) in the market which can be used with aframe? Any proposals?

**Comment by dmarcos** [comment]
Oculus Go has a built-in Web Browser that can display WebVR content. https://www.howtogeek.com/wp-content/uploads/2018/05/img_5aebc7ad49d28.jpg

**Comment by dmarcos** [comment]
Chrome for Android is also WebVR compatible. You should be able to use it with Daydream headsets

**Comment by kinnla** [comment]
The 360 image gallery example is not working on the Oculus Go (Version 88830.2550.0). Screen stays grey, selecting the VR button has no effect.
![com oculus vrshell-20180726-213451](https://user-images.githubusercontent.com/3518808/43284507-4ee363fa-911c-11e8-9b96-9fa44404d94d.jpg)

**Comment by comsyspro** [comment]
This example uses aframe Version 0.3.2. Could you try to use any other aframe html site with newer build 0.8.0. Also would it be possible to save aframe code local to oculus go and load it with the in-built broswer from the internal storage? (This would be required if there was no internet connection for any reason)

**Comment by kinnla** [comment]
A-frame 0.8.0 works fine on the oculus go. I just wanted to inform that the example discussed here doesn't work. Thanks for pointing out that the 360 image gallery is based on an older aframe version, so that should be the reason why it's not working on the oculus go. 

Probably it would be good to update the example.
