### ISSUE TITLE
.obj not displayed correctly

### ISSUE THREAD

**Issue by smout74** [aframevr/aframe#3639]
**Description:**
When using the following code for using an .obj file, this does not get correctly displayed.
Am I doing something wrong ?

- A-Frame Version: 0.8.2
- Platform / Device: Windows
- Reproducible Code Snippet or URL:
```
  <a-scene vr-mode-ui="enabled: false">    
    <a-assets>
      <a-asset-item id="ass-obj" src="./shop_3002.obj"></a-asset-item>
      <a-asset-item id="mat-mtl" src="./material.mtl"></a-asset-item>
    </a-assets>
    <a-entity camera look-controls>
      </a-entity>
        <a-entity id="target" obj-model="obj: #ass-obj; mtl: #mat-mtl" position="0 0 0" scale="0.001 0.001 0.001" rotation="-90 0 0">
      </a-entity>
   </a-scene>
```
![3002 - 3d builder](https://user-images.githubusercontent.com/39618522/41350812-a57c7212-6f14-11e8-887b-0dff05d78ec2.png)
![3002 - aframe](https://user-images.githubusercontent.com/39618522/41350813-a59a99c2-6f14-11e8-8844-36b8b9a02c9e.png)

[shop_3002.zip](https://github.com/aframevr/aframe/files/2098045/shop_3002.zip)

**Comment by donmccurdy** [comment]
There's something unusual about this model; it appears incorrectly in my native OSX quicklook plugin as well, and Cesium parses it as shown above in their converter.

You can try exporting differently from your tool (perhaps triangulate before export, if you haven't?). Otherwise the only thing that worked for me was importing the OBJ to Blender and exporting as glTF with https://github.com/KhronosGroup/glTF-Blender-Exporter.

**Comment by smout74** [comment]
Hi, I followed your instructions, it shows correctly after export from blender to gltf format.

What happens in your exporter that corrects this model ?? Or what is wrong in the model that you correct ?

Thanks

**Comment by donmccurdy** [comment]
I don’t know, unfortunately. It could be that the model uses a rare OBJ feature, or is slightly incorrect in some way. Often OBJ models contain n-gons (faces that aren’t triangles) and this breaks some tools, and triangulation happens automatically when converting to glTF which fixes this.
