### ISSUE TITLE
Document Slack invitation process

### ISSUE THREAD

**Issue by cemkod** [aframevr/aframe#364]
I still don't know how I can join slack.
Maybe we can add it to https://github.com/aframevr/aframe/blob/master/CONTRIBUTING.md ?

**Comment by cvan** [comment]
it's listed here: https://aframe.io/community/#A-Frame

we could add it to the Contributing doc as well

**Comment by cemkod** [comment]
Thank you.

I have added some instructions to CONTRIBUTING.md https://github.com/cemkod/aframe/commit/d27cb0938abaa83c4aee28c21f15fc9c3e56d8e1
