### ISSUE TITLE
New GLTF Loader for GLTF2 - unable to pass DracoLoader instance

### ISSUE THREAD

**Issue by ainian** [aframevr/aframe#3640]
Hi,
I have draco compressed GLTF images which needs to be loaded using aframe. When trying to load it using the new gltf-model component I am getting "components:gltf-model:warn THREE.GLTFLoader: No DRACOLoader instance provided." error. I hope this is because there is no option to specify the dracoloader which can be passed as argument to the threejs GLTFLoader -> setDRACOLoader function. Please help...

**Comment by donmccurdy** [comment]
In the current version of `gltf-model` there is no option to specify the draco loader. You could certainly fork the component (https://github.com/aframevr/aframe/blob/master/src/components/gltf-model.js) and add those lines of code:

```js
THREE.DRACOLoader.setDecoderPath( '/path/to/decoder' );
loader.setDRACOLoader( new THREE.DRACOLoader() );
```

We could add this in 0.9.0, but it would be a breaking change since there isn't currently a `src` property:

```html
<a-entity gltf-model="src: foo.glb; dracoDecoderPath: /path/to/decoder;"></a-entity>
```

**Comment by ainian** [comment]
Tried to check the above solution by hardcoding the decoder path instead of passing as a parameter. Now getting "defs.map is not a function" error in GLTFParser.prototype.getDependencies function. Seems like defs is an Object but the map function is available only for Array in javascript..Can some one help me to identify a solution for this?

**Comment by donmccurdy** [comment]
Does your model work on https://gltf-viewer.donmccurdy.com/?

**Comment by ainian** [comment]
Is there a way to check this offline as I will not be able to upload the model online.

**Comment by ainian** [comment]
Thanks for the suggestion. The model I had did not work in GLTF viewer as well. 
After some analysis, I came to know the information in the model was lost when using the gltf-pipeline master branch. 
Now I have used the 2.0 branch of the Gltf-pipeline with draco compression option and it worked fine. Once again thanks a lot for your guidance.

**Comment by donmccurdy** [comment]
Glad it's working! :)

**Comment by homerjam** [comment]
Hi @ainian 

Could you by any chance outline the steps you followed to get your gltf-pipeline optimised model working in the current version of a-frame?

My model loads in the gltf-viewer but isn't loading in my own test...

```
components:gltf-model:warn Cannot read property 'byteStride' of undefined 
aframe-master.js:55211 Timer 'GLTFLoader' already exists
```

Thanks in advance!

**Comment by gabrieljbaker** [comment]
I'd be really curious to see how you did this as well, @ainian !

**Comment by donmccurdy** [comment]
Re-opening this as a feature request. I'd like to provide some way of using Draco while still using the `gltf-model` component. TBD if that is possible without breaking `gltf-model="foo.gltf"` single-property syntax.

**Comment by imostafavi** [comment]
Would be great to see the gltf-model component supporting Draco compressed files.  Our a-frame project could really benefit from the compression on our models.

**Comment by donmccurdy** [comment]
Opened #3792.

**Comment by edsilv** [comment]
@donmccurdy Hi, I've followed the draco workflow, but am getting CORS errors:

```
Access to XMLHttpRequest at 'dracodecoderpath: assets/;' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy
```

I've tried hosting it on netlify with `Access-Control-Allow-Origin: *`, but same issue.

**Comment by donmccurdy** [comment]
@edsilv note that this fix is not in a released version of A-Frame yet, it will come out with 0.9.0.
