### ISSUE TITLE
Camera motion broken on Android WebView using Chrome Canary 69

### ISSUE THREAD

**Issue by Flip535** [aframevr/aframe#3642]
Android WebView using Chrome Canary (Chrome 69) breaks devicemotion event for aframe.io samples.

We are seeing this with our own app that uses android WebView, but testing it with an app called WebView from the play store shows the same issue. Get chrome canary. Go to your developer settings on your phone and set webviews to use chrome canary. finally use the webview app to go to aframe.io. looks like the device motion event is broken? 

- A-Frame Version: 0.8.2
- Platform / Device: Android WebView Running Chrome Canary (Chrome 69)

**Comment by dmarcos** [comment]
It seems a Chrome issue with the permissions granted to a WebView. I found this reference: https://bugs.chromium.org/p/chromium/issues/detail?id=852543

**Comment by ngokevin** [comment]
Seems to be resolved, but any case it's a Chromium/Google issue that A-Frame probably can't solve.
