### ISSUE TITLE
Does A-Frame work with React?

### ISSUE THREAD

**Issue by trusktr** [aframevr/aframe#365]
I'm curious to know, when React adds stuff to the DOM after it's diffing process, will that stuff be picked up by A-Frame?

**Comment by ngokevin** [comment]
Sure does!

https://github.com/ngokevin/aframe-react
https://github.com/ngokevin/aframe-react-boilerplate

**Comment by ngokevin** [comment]
https://github.com/ngokevin/threeschwifty
https://github.com/ngokevin/a-wakens

**Comment by trusktr** [comment]
@ngokevin

So without using aframe-react, if I have aframe and react from CDN loaded in the page (and that's all), then I can just start writing React components without needing to do anything special? For example

```js
class Foo extends React.Component {
  render() {
    return (
      <a-scene>
      </a-scene>
    )
  }
}
```

Do you know how A-Frame detects new elements in the DOM to read from (and then render based on what it sees)? Is it using some browser APIs? Or something custom?

EDIT: I answered my own question after looking at the source: It's using document.registerElement (the polyfill if not available)! This is awesome. So people can use anything like Mithril, Mercury, Om, CitoJS, etc, to output elements to the DOM (elements with names that match those registered by A-Frame) and then A-Frame will automatically detect those and update the rendering.

This is really cool!! This is probably the best use of `registerElement` I've ever seen, and a good idea that I'd like to borrow for what some of us are working on at http://infamous.io.

**Comment by ngokevin** [comment]
Yeah, we use the Custom Element API pretty heavily. I'd recommend using `aframe-react` so you can pass component data as props using plain objects. It's a very thin unopinionated layer. I have some more features in mind too to help pair along with A-Frame.

```js
const material = {color: 'red', metalness: 1};
<Entity geometry={{primitive: box, width: 5}} {...material}/>
```

**Comment by trusktr** [comment]
Cool. It's really awesome stuff!

**Comment by ngokevin** [comment]
Yeah, it's quite genius, bringing ECS to the DOM. @jcarpenter and @dmarcos idea.

**Comment by trusktr** [comment]
@ngokevin ECS?

**Comment by ngokevin** [comment]
Sorry, shouldn't be using acronyms :)

https://en.wikipedia.org/wiki/Entity_component_system

**Comment by trusktr** [comment]
Oh, yes, it's also what [Famous](http://famous.org) was doing before it got abandoned. A scene graph in Famous was made up of instances of a `Node` class (entity), and onto each Node could be added various components (tranforms, meshes, event handlers, etc) that could be independent or interact with other components on the same node. They were also making something called Famous Framework, which was their attempt to make a declarative HTML layer on top of their Engine. But they weren't using `document.registerElement`!

I wonder how I overlooked all this time that custom elements would be the perfect communication mechanism between a rendering engine (Three.js, Famous, Babylon, etc) and a DOM manipulation library (React, Mithril, etc).

**Comment by ngokevin** [comment]
Ah wow, yeah, that's very similar. I should read through that more and see if we can take any ideas from it.

Yeah, it's pretty agnostic. We found it works well with D3 too.
