### ISSUE TITLE
Video Issue

### ISSUE THREAD

**Issue by Siva-SteamRollEast** [aframevr/aframe#3654]
I tried to play a video when marker is detected but in aframe the video started to play when the page loads. Due to this, when marker is detected the video is not playing from beginning. And also the auto play is not working in IOS safari (mobile). I also want to hide and stop the video when marker goes out of the screen.
Is there any working event listener when the marker is detected?

@jhsu  @RSpace  @arpu @bnolan  @andygill

**Comment by dmarcos** [comment]
What do you mean by marker? Is it a marker as defined in `ar.js`?
