### ISSUE TITLE
Increase & decrease image size with two finger.

### ISSUE THREAD

**Issue by TTDN** [aframevr/aframe#3665]
I have a code like this, to display image on camera:

`<a-camera>
<a-image src="../images.png" width="0.5" height="0.5" position="0 0 -1"></a-image>
</a-camera>`

How to Increase & decrease image size when i put two finger and swipe on screen? Can you help me?

Sorry for my bad english. :(

**Comment by ngokevin** [comment]
https://github.com/ngokevin/kframe/tree/master/components/orbit-controls
