### ISSUE TITLE
Link component title sometimes disappears when used with look-at component

### ISSUE THREAD

**Issue by mirzu** [aframevr/aframe#3666]
We ran into a strange error with the Link Component and Look-at component. I'm posting this ticket for both because I'm not sure if this should be fixed in both or one of the components. 

When a link uses the look-at component the title disappears if it is in certain locations in the scene, but not in others. The underlying issues appear to be in the code that creates the view into the portal. 

In the example, you can look to the right and see the missing title. If you move away from the portal you can see the title reappear. The same error occurs when links are places at certain rotations around the user, but not in others.

- A-Frame Version: 0.8.2
- Platform / Device: Tested on Android Chrome and desktop 
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/near-equinox

![hello__webvr__-_a-frame](https://user-images.githubusercontent.com/251658/41869260-17abae1c-787e-11e8-9656-5096ed890bfb.png)

**Comment by dmarcos** [comment]
I think this should be file against the look-at component.
