### ISSUE TITLE
Event listener 'componentchanged' is only firing for 'rotation' and not 'position'

### ISSUE THREAD

**Issue by frankangelone** [aframevr/aframe#3667]
When trying to detect the movement of the camera's position, the only change I can detect is the camera's rotation.  To move the camera around, I'm using the [A-Frame Extras](https://github.com/donmccurdy/aframe-extras) library. 

- A-Frame Version: 0.8.0
- Platform / Device: Mac OS X Sierra (10.12.6)
- Reproducible Code Snippet or URL:

```
document.addEventListener("DOMContentLoaded", function(event)
{
        document.querySelector("a-entity[camera]").addEventListener("componentchanged", function (evt)
    	{
    	        // The console message outputs 'rotation' and never outputs 'position'
                console.log("Event name: " + evt.detail.name); 
    		if(evt.detail.name === "position")
    		{
    		    console.log("Camera has moved from " + evt.oldData + " to " + evt.newData); 
    		}
    		else
    		{
    		     console.log("position has not changed"); 
    		}
    	});
});
```

Here's my HTML: 

```
<a-entity id="rig" movement-controls position="0 0 0">
      <a-entity camera position="0 1.6 0" look-controls="pointerLockEnabled:false"></a-entity>
 </a-entity>
```

**Comment by ngokevin** [comment]
It iwll fire on the rig.

**Comment by frankangelone** [comment]
@ngokevin What portion of the code would I need to update so that the event fires on the rig?

**Comment by ngokevin** [comment]
`document.querySelector("#rig").addEventListener`

**Comment by frankangelone** [comment]
I had tried that before with no luck. Here's an example I put together and if you view the console, none of the console messages in the code will execute: [https://codepen.io/anon/pen/XYPLMP](https://codepen.io/anon/pen/XYPLMP)

**Comment by ngokevin** [comment]
Use a tick handler to detect changes in position, we've moved away from using pos/rot/scale components to manipulate pos/rot/scale, and instead using object3D directly, so that event may not always fire. https://stackoverflow.com/questions/38907857/how-to-listen-to-changes-in-the-rotation-of-the-camera-in-a-frame

**Comment by frankangelone** [comment]
Can the `tick` handler be used to get `position`?  It looks like this code is for `rotation`.  My hope is that as I use the WASD keys to move around the scene I can output to the console the X, Y and Z position of the camera.

**Comment by ngokevin** [comment]
Replace position with rotation. Player will almost always be moving especially in VR. Better to just always listen rather than rely on events. Can store previous position if you want to compare
