### ISSUE TITLE
Add events to know when assets (e.g., `<video>` and models) have loaded

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#367]
There are quite a few events: https://www.w3.org/TR/html5/embedded-content-0.html#media-controllers

We could let folks listen for the events on the `<video>` elements themselves. If the developer has created a `<video>` asset on the page, they could listen to that. But if we had to create the `<video>` ourselves, or if they want a more convenient way of querying the video, we could attach the `video` as a property to the `<a-entity>`. Developers could then do this, for example:

```js
document.querySelector('a-entity#frogs_video').video.onplaying = function () { … };
```

**Comment by cvan** [comment]
Also worth referencing #40

**Comment by cvan** [comment]
I know things have changed a lot, but as I last understood it, we block `<a-scene>` on rendering until everything in `<a-assets>` has loaded.

Templates in their current form (e.g., `<a-video>`) are exempt from this blocking.

@dmarcos, @ngokevin, do you have ideas on how/whether to continue to block on `<a-assets>`? and which types of events we may want to emit to give developers finer-grain controls over things such as videos?

**Comment by ngokevin** [comment]
I don't think `<a-assets>` does anything special at the moment. The most reliable way would be having the developer create the video tag themselves.

There aren't any guarantees on adding events or states on the entities because that is up the component developer.

**Comment by ngokevin** [comment]
Okay, we now have the `loaded` and `timeout` events on the assets element. We can explore providing more granular  events later on
