### ISSUE TITLE
Gampedap api issue with oculus remote

### ISSUE THREAD

**Issue by arthurmougin** [aframevr/aframe#3671]
On the latest version of Aframe, two fantom gamepads are declared even if using the CV1 remote.

- A-Frame Version: 0.8.2
- Platform / Device: oculus CV1 and Firefox (latest)
- Reproducible Code Snippet or URL: 

Vrsearch.arthur-moug.in

Console.log(navigator.getGamepads());

**Comment by dmarcos** [comment]
I see those gampads. `navigator.getGamepads` is populated by the browser not A-Frame. @kearwood @daoshengmu Do you know if Firefox is populating the gamepads list even if the controllers are not present in Oculus?

**Comment by daoshengmu** [comment]
it shouldn't happen. We enumerate the Oculus Touch with Oculus runtime. The amount of gamepads is according to the controllers that are turning on currently.

**Comment by WellanDraco** [comment]
https://github.com/wmurphyrd/aframe-super-hands-component/issues/140#issuecomment-401458291

In this issue you have pictures showing the issue

**Comment by dmarcos** [comment]
I cannot reproduce this issue anymore on Firefox 64
