### ISSUE TITLE
After page loading, there are two camera icon

### ISSUE THREAD

**Issue by mdeprezzo** [aframevr/aframe#3676]
**Description:**
I'm trying to use aframe 0.8.2, but i don't know why, there are two camera icon after the page loading
like that:
![doppia_icona](https://user-images.githubusercontent.com/6594262/42135340-f81a2a3a-7d49-11e8-9f66-a952d16ceb2a.png)

Any suggestions ?

- A-Frame Version: 0.8.2
- Platform / Device: Linux, Browser
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Do you have any link / steps to reproduce? What browser? I cant reproduce with any of aframe examples on Windows Firefox / Chrome / Edge

**Comment by mdeprezzo** [comment]
I fixed, with a-assets tag and i've loaded the img on a-sky from javascript. I've read an old issue about double download of img on load, so i tried and works.

**Comment by dmarcos** [comment]
Glad it worked.
