### ISSUE TITLE
Updating a line component using a cached THREE.Vector3 fails

### ISSUE THREAD

**Issue by InfiniteLee** [aframevr/aframe#3681]
A `line` component will not update if using a cached `THREE.Vector3` to call `setAttribute`. I believe this is because `deepEqual` is used in component to determine if an attribute was actually updated or not. As such, this probably affects other components that similarly allow (or at least don't explicitly disallow) the use of THREE vectors. 

Aside from updating the `deepEqual` method, another option may be to allow forcing an update via another attribute like `needsUpdate`. 

```
        init() {
          this.end = new THREE.Vector3();
        },
        
        tick() {
          this.end.set(Math.random(),  Math.random(),  Math.random());
          this.el.setAttribute("line", {end: this.end}); //will not update after the first tick
        }
```
- A-Frame Version: 0.8.2
- Platform / Device: any
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/heavenly-piranha

**Comment by ngokevin** [comment]
Yeah, unless we refactor the system and have some sort of forced dirty flag, they can't be updated with the same object.

An alternative is to flip-flop between two vector objects as you update.

**Comment by johnshaughnessy** [comment]
@InfiniteLee Another alternative is to save the object you get from `getAttribute`, change the value of `end`, and then use `setAttribute` with `clobber` set to `true`. e.g. https://github.com/mozilla/hubs/commit/4d5559d2cd57d82631d4308400265017b9eed1ef#diff-bafcf688d672a56b722fa967f5b16acbR51
