### ISSUE TITLE
[Docs] Links in introduction miss out "interaction & Controllers" and "3D models" on page navigation

### ISSUE THREAD

**Issue by AJDempsey** [aframevr/aframe#3684]
At the bottom of https://aframe.io/docs/0.8.0/introduction/writing-a-component.html the next page link jumps over the "Interaction & Controllers" and "3D models" pages straight to https://aframe.io/docs/0.8.0/introduction/visual-inspector-and-dev-tools.html.

The two pages missing from the navigation have no navigation links at the bottom either.

Sorry if this is the wrong format to raise this minor issue, I was looking to modify the pages myself but the navigation links don't appear in the source code in Github.

**Comment by Giorat** [comment]
I'll try to fix this today, thanks! 👍
