### ISSUE TITLE
 THREE.OBJLoader: Unexpected line: "<!DOCTYPE html>"

### ISSUE THREAD

**Issue by zhangjianbao** [aframevr/aframe#3686]
when i load .obj model,there is an error, anyone who can help me,thanks!
![image](https://user-images.githubusercontent.com/6321966/42410405-c4074ef4-821b-11e8-8783-dca4957f730b.png)

![image](https://user-images.githubusercontent.com/6321966/42410402-b3c3e70a-821b-11e8-9646-8ef46f601a78.png)

**Comment by dmarcos** [comment]
Can you share your OBJ model? It seems your OBJ model is not well formed. I will reply here but I'm closing this. We use github issues for bugs and feature request. For usage questions we use StackOverflow and you can share the link in the [Slack channel](https://aframe.io/community/#slack)

**Comment by qbmiller** [comment]
set path absolute
