### ISSUE TITLE
a-ring invisible from behind

### ISSUE THREAD

**Issue by remkoboschker** [aframevr/aframe#3689]
I have a scene with aframe 0.8.2 in Chrome 67 and in Firefox Quantum 60. I have an a-ring element within a a-sphere element.
````
 <a-sphere radius='2' color='${color}'>
      <a-ring radius-inner='0.9' radius-outer='1' color='black' position='0 0 -1.8'></a-ring>
 </a-sphere>
````
If I set the position to ``0 0 1.8`` all is fine, but when I position the ring on the other side of the sphere and then rotate the sphere 180 degrees the ring is invisible. If I rotate the ring by 180 degrees, then it become visible again.

So it seems the ring is invisible from behind. Is this intentional or is it a bug?

**Comment by donmccurdy** [comment]
Try adding `side="double"` — https://aframe.io/docs/0.8.0/components/material.html#properties. 2D objects are rendered only once (i.e. from one side) by default, which is more performant.

**Comment by remkoboschker** [comment]
Clear, thank you
