### ISSUE TITLE
Chrome + Ubuntu linux Issue

### ISSUE THREAD

**Issue by Kshukla** [aframevr/aframe#369]
THREE.WebGLRenderer: Error creating WebGL context.n.WebGLRenderer @ aframe.min.js:19t.exports.Object.create.setupRenderer.value @ aframe.min.js:30t.exports.Object.create.attachedCallback.value @ aframe.min.js:30o @ aframe.min.js:27
aframe.min.js:19 Uncaught TypeError: Cannot read property 'getExtension' of nullget @ aframe.min.js:19n.WebGLRenderer @ aframe.min.js:19t.exports.Object.create.setupRenderer.value @ aframe.min.js:30t.exports.Object.create.attachedCallback.value @ aframe.min.js:30o @ aframe.min.js:27
vuutuapp.html:29 statusChangeCallback

Instruction : open http://www.vuutu.xyz , its working fine in firefox but on chrome its giving error. (Version 47.0.2526.106 (64-bit))

**Comment by ngokevin** [comment]
Is it working now?

**Comment by ngokevin** [comment]
Needs more info / update
