### ISSUE TITLE
Oculus Go point - highlight - click trouble

### ISSUE THREAD

**Issue by mosesoak** [aframevr/aframe#3692]
**Description:**

- A-Frame Version: master
- Platform / Device: Oculus Go
- Reproducible Code Snippet or URL:

Hi, first let me say I'm really impressed by a-frame and have been really excited to create design prototypes with it. My single functional need for prototyping is to be able to point the beam, let the object (e.g. a button) get a 'mouseover' highlight and then receive a click.

My entity is set up like so,

```html
    <a-entity id="controllers" oculus-go-controls custom-controller raycaster="showLine: true; far: 4"
      line="color: white; opacity: 0.5">
    </a-entity>
```

And my custom controller is wired up to be able to detect touchpad and trigger presses, etc. – all working great, except the selection part.

I've tried adding event listener on the target element using various event types (`'click'`, `'mouseover'`, `'buttonchanged'`, etc.) with no response from the beam.

I see that the Raycaster exposes what its target objects are if you dig into it, but I was hoping for more out of the box point-and-click functionality, but it doesn't seem to be working in the current master release.

**Comment by Giorat** [comment]
Can you provide a full repository/example to test out this problem?

**Comment by mosesoak** [comment]
@Giorat 

Note how in my example code above I had not included a `laser-controls` component attribute which was why there is no hover/click functionality.

The docs are generally well written but there are a bunch of pain points that would be nice to address:

- The main one is that `laser-controls` is a master controller that does everything you need. This should be surfaced much higher in the long-form explanation at https://aframe.io/docs/0.8.0/introduction/interactions-and-controllers.html

- The laser controls page (https://aframe.io/docs/0.8.0/components/laser-controls.html) should be updated to include oculus-go-controls, at least once there are docs written for that component

- When describing 3dof & 6dof controls it might be mentioned that if you want interactivity just use `laser-controls`, using one of the examples shown (e.g. `<a-entity daydream-controls></a-entity>`) will only add custom events and other specifics without adding interactivity (which feels like an edge case).

- It doesn't seem possible to change the position of the oculus go controller in the scene. (The model disappears if you add position to its entity node.) The docs don't address this question at all - might be worth opening another issue around?

- The section on laser-controls has two code examples, and the 2nd one shows `hand-cursor` with `controller-cursor`, but nowhere in the docs is `controller-cursor` described, and at least with the go controller this example doesn't do anything at all (no model, beam, or events). It would be nice to flesh out that example a little and maybe explain what the differences are between `controller-cursor` and `laser-controls`. In short that 2nd example is really confusing and kind of a dead end in trying to pick through all of this.

**Comment by mosesoak** [comment]
@Giorat I figured out why this was so incredibly difficult for me, it's because I was originally using a `curved-image` as my click target, and that is not receiving the hover coordinates correctly. I'll file a separate issue.

**Comment by BVPlaten** [comment]
Do you have a simple example for A-FRAME with the oculus go as complete source-code ?

Thanks very much :-)
