### ISSUE TITLE
HoverRiding default cursor generate warning

### ISSUE THREAD

**Issue by WellanDraco** [aframevr/aframe#3698]
I changed the default geometry  and put new settings but it generate this warnings 

![image](https://user-images.githubusercontent.com/26094902/42953539-ab370366-8b48-11e8-80f4-69913095417e.png)

- A-Frame Version: 0.8.2
- Platform / Device: All
- Reproducible Code Snippet or URL: 

       ```
         <a-camera look-controls-enabled id="cameracontrolers" stereocam="eye:right">
            <a-cursor fuse="true" objects=".interactive" position="0 0 -1" geometry="primitive:circle;radius: 0.008; segmentsTheta: 32" material="color: #fff; shader: flat"></a-cursor>
          </a-camera>
```

**Comment by dmarcos** [comment]
I can't reproduce the issue: https://glitch.com/edit/#!/rainy-jester?path=index.html:15:37

A complete example will help. Your HTML might not be well formed.

**Comment by WellanDraco** [comment]
```
<html>

<head>
    <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
    <!-- <script src="test.js"></script> -->
</head>

<body>
    <a-scene>
        <a-camera look-controls-enabled id="cameracontrolers">
            <a-cursor fuse="true" objects=".interactive" position="0 0 -1" geometry="primitive:sphere;radius: 0.008;" material="color: #fff; shader: flat"></a-cursor>
        </a-camera>
        <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9"></a-box>
        <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E"></a-sphere>
        <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>
        <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
        <a-sky color="#ECECEC"></a-sky>
    </a-scene>
</body>

</html>

```

I just took the default page and added my code, It still cause warning

![image](https://user-images.githubusercontent.com/26094902/43004203-09348d94-8bfd-11e8-97bb-b384ef317330.png)

**Comment by dmarcos** [comment]
Those warnings are innocuous and come from the `<cursor>` primitive that has a [ring](https://aframe.io/docs/0.8.0/components/geometry.html#ring) geometry. Your HTML switches to `sphere` geometry that does not have `radiusOuter`, `radiusInner` properties. You can avoid the warnings by writing the cursor in the entity form:

```<a-camera look-controls-enabled id="cameracontrolers">
      <a-entity cursor="fuse: true" objects=".interactive" position="0 0 -1" geometry="primitive:circle; radius: 0.008; segments: 32" material="color: #fff; shader: flat"></a-entity>
 </a-camera>```
