### ISSUE TITLE
Setting the repeat property for MeshPhongMaterial throw's incorrect warning

### ISSUE THREAD

**Issue by Pluto8195** [aframevr/aframe#3699]
Setting a repeat value on a texture and making a MeshPhongMaterial out of it is sending the warning
`THREE.MeshPhongMaterial: 'repeat' is not a property of this material.`
But repeat does have the desired effect so it must be a property?
when I remove repeat the textures stretch and don't repeat

- A-Frame Version: 0.8.2
-Chrome

```

for (let key in MAP_TYPES) {
      maps[key] = new THREE.TextureLoader().load("/src/assets/"+texture+"/"+MAP_TYPES[key]);
      maps[key].wrapS = THREE.RepeatWrapping;
      maps[key].wrapT = THREE.RepeatWrapping;
      maps[key].repeat.set(hscale, vscale);
    }

    const mat = {
      color: material.color,
      map: maps.color,
      normalMap: maps.norm,
      shininess: 30,
      aoMap: maps.occ,
      aoMapIntensity: 0.5,
      repeat: 100,
    }

    //take mat params and create a new material
    obj.material = new THREE.MeshPhongMaterial(mat);

```

**Comment by dmarcos** [comment]
repeat is not a property of any THREE material but of [THREE.Texture](https://threejs.org/docs/#api/textures/Texture.repeat)
