### ISSUE TITLE
Cursor.js: Update canvas bounds on scroll

### ISSUE THREAD

**Issue by viperphase1** [aframevr/aframe#3700]
In cursor.js add 
`window.addEventListener('scroll', this.updateCanvasBounds)`
below the line
`window.addEventListener('resize', this.updateCanvasBounds)`

Solves #3410

**Comment by dmarcos** [comment]
@viperphase1 Thanks. A PR is more than welcome if you have bandwith.

**Comment by viperphase1** [comment]
Pulling my fork might get hairy. Are you able to edit cursor.js?

**Comment by viperphase1** [comment]
I've created a pull request. #3710

**Comment by keromonkey1** [comment]
Not to revive a closed topic, but I was experiencing similar problems during testing and was hoping to include:

"window.addEventListener('scroll', this.updateCanvasBounds)
below the line
window.addEventListener('resize', this.updateCanvasBounds)" 

to fix it. However, I don't have a cursor.js file present. Was there anywhere else you might recommend putting it, or should I scour the net, find it, download it, then add it? lol
