### ISSUE TITLE
Binding src in <a-sky> using Ionic 3

### ISSUE THREAD

**Issue by Ademking** [aframevr/aframe#3703]
**Description:**

Can someone help me, i'm trying to bind src in a-sky tag.. i'm using Ionic 3

` <a-sky  [src]="img_url" rotation="0 -20 0"></a-sky>`

the page is white.. after debuging, i didn't find the url .. i think binding is not working with aframe..

is there a solution ? (specific for Ionic.. not angular) 
sorry i'm a beginner and i'm new to Aframe.. it's a cool library ♥
Thanks

- A-Frame Version: latest
- Platform / Device: PC + Mobile

**Comment by Ademking** [comment]
Never mind.. i found a solution .. but it's not binding
code :

• __imageviewer.ts__

```
import { Component, ViewChild , ElementRef } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import {DomSanitizer} from '@angular/platform-browser';

@IonicPage()
@Component({
  selector: 'page-imageviewer',
  templateUrl: 'imageviewer.html',
})
export class ImageviewerPage {

// a-sky element ...
  @ViewChild('mysky') mysky : ElementRef;

  Gov_image:any;


  constructor(public navCtrl: NavController, public navParams: NavParams, private sanitizer:DomSanitizer) {
    this.Gov_image = navParams.data;
  }



  ionViewDidLoad() {
// the solution was 1 single line -_- i hate my life
      this.mysky.nativeElement.setAttribute('src',this.Gov_image);
  }
```

• __imageviewer.html__

```
<ion-content padding>

   <a-scene debug>
        <a-sky #mysky rotation="0 -20 0"></a-sky>
    </a-scene>

</ion-content>

```

**Comment by ejetzael** [comment]
Thank you!
