### ISSUE TITLE
Aframe <a-text> does not appear if i use three.js and aframe.js at the same time

### ISSUE THREAD

**Issue by AlbirrKarim** [aframevr/aframe#3704]
I try to make something with aframe.js then I try using three.js to interact with an object (change position) after that I want to make a text with <a-text> but the text doesn't appear.
condition:
1. script aframe.js and three.js I put together in one file HTML
![screenshot_2018-07-23_09-31-40](https://user-images.githubusercontent.com/29292018/43054344-4b22af0a-8e5b-11e8-93b2-ec3a40f53492.png)
The text not appear

2. just script aframe.js
![screenshot_2018-07-23_09-32-05](https://user-images.githubusercontent.com/29292018/43054379-6f1b6b04-8e5b-11e8-9565-2e0f1f0413cd.png)
The text is appear

- A-Frame Version: 0.8.0
- Platform / Device: Lenovo g40-45 Linux Xubuntu 18.04. chrome 67.0

**Comment by wmurphyrd** [comment]
three.js is bundled with A-Frame, so you shouldn't add it separately. You can access it via `window.THREE` instead.

**Comment by AlbirrKarim** [comment]
Thanks
