### ISSUE TITLE
vrdisplayactivate does not trigger enter-vr event on scene containing a-asset-items

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#3705]
**Description:**
Arriving in a scene from within VR via a link does not trigger the "enter-vr" event on the scene, if there are a-asset-items in assets.

On the other hand, listening to the "vrdisplayactivate" event on window is always triggered, if in `<head>`.

- A-Frame Version: 0.8.2
- Platform / Device: Oculus browser / Gear VR with controller AND Firefox / Rift
- Reproducible Code Snippet or URL: https://determined-birch.glitch.me/

**Comment by weddingdj** [comment]
Oculus browser on GearVR and the linking within VR works.

**Comment by dmarcos** [comment]
Sorry, I’m not sure I understand. If VR navigation is working `vrdisplayactivate` should be firing and `enter-vr` as well You might be attaching the eventLisener late and missing the events?

**Comment by weddingdj** [comment]
I tested it using a simple example and indeed, enter-vr is triggered even when linked to from within VR. The event listener for the vrdisplayactivate event needs to be in HEAD though, it is not triggered when defined in a component init function.

**Comment by weddingdj** [comment]
a-asset-item (which I use for loading obj, mtl files) was responsible for not triggering the enter-vr event on the scene. If I remove a-asset-items then it works. vrdisplayactive was allways triggered, if the listener is in <head>.

**Comment by weddingdj** [comment]
I made an example: https://determined-birch.glitch.me 

The two objects link to two different scenes, one scene without an asset, the other with an asset. You can see that the `enter-vr` event is triggered on the scene without the asset, on the other not.

**Comment by dmarcos** [comment]
`vrdisplayactivate` and subsequent `enter-vr` not captured by an init method is expected. init runs after the assets load and `vrdisplayactivate` is trigerred by the browser a soon as the page loads (it does not wait for a-frame). You can check for `sceneEl.is(‘vr-mode’)` at any time to determine if the page is in vr mode

**Comment by weddingdj** [comment]
I used `sceneEl.is(‘vr-mode’)` instead, thank you.
