### ISSUE TITLE
Click events don't work on entity children

### ISSUE THREAD

**Issue by viperphase1** [aframevr/aframe#3713]
Hello everyone. It seems since version 0.7.1 you can't click on objects wrapped in an a-entity tag.
[See fiddle](https://jsfiddle.net/9ex5Ljgp/22/)

**Comment by dmarcos** [comment]
Not sure what build you are using in your fiddle but 0.8.2 works for me(https://aframe.io/releases/0.8.0/aframe.min.js). Example: https://jsfiddle.net/tg5qorkc/3/

Closing this and will reopen if this is still a problem

**Comment by viperphase1** [comment]
So I guess this is a problem since 0.8.0

**Comment by sky790312** [comment]
I have the similar issue, but my case is that it can't trigger the click event second time by 'a-image'.
It needs to unfocus the 'a-image' by click other 'a-image' or drag..etc, then I can trigger the click event again.
I'm using the 0.8.2 version and I back to use 0.7.0 version it works. Any idea?

**Comment by lschatzkin** [comment]
Similarly, I need the fix that is in master for 0.9.0 for this sound bug: https://github.com/aframevr/aframe/pull/3631 , but it is disable all my click events.  How should a proceed adding the asset-sound-test branch to v0.8.2?

**Comment by lschatzkin** [comment]
Also, I have click events to play the sound. Now they play even if the object is not visible, which wasn't the case before.

**Comment by arpu** [comment]
updated fiddle to latest master looks working fine
https://jsfiddle.net/scy5prkd/3/

@donmccurdy this could be closed?

**Comment by donmccurdy** [comment]
Thanks!
