### ISSUE TITLE
Scene keeps spinning on Android/Google phones

### ISSUE THREAD

**Issue by jakecjones** [aframevr/aframe#3719]
Screen looks like helicopter crash on multiple Android/Google phones. Works great on Iphones but other phones are not handling aframe correctly. The scene keeps spinning out of control. Is there a fix for this?

- A-Frame Version: 0.8.0
- Platform / Device: Android / Google
- Reproducible Code Snippet or URL:  http://artgala.lamplightheritage.com/

**Comment by dmarcos** [comment]
That was a change in Chrome that was accounted for in [0.8.2](
https://aframe.io/releases/0.8.2/aframe.min.js). Upgrade your application. Let us know if it’s still a problem.
