### ISSUE TITLE
Infinite recursion in 0.8.2 with spectator camera

### ISSUE THREAD

**Issue by ryzngard** [aframevr/aframe#3720]
**Description:** 

Project page with 0.8.2: https://zest-sandal.glitch.me/ 
Same page using 0.8.0: https://amber-girdle.glitch.me/ 

Whether entering fullscreen or actually using VR, hitting the button in the bottom right results in an error in both Firefox and Edge.  `too much recursion[Learn More] three.js:4791`. I haven't determined if this is only related to spectator camera or if similar scenarios would produce the same result. 

- A-Frame Version: 0.8.2
- Platform / Device: Windows 1803
- Reproducible Code Snippet or URL: https://zest-sandal.glitch.me/

**Comment by dmarcos** [comment]
This is a [duplicate](
https://github.com/aframevr/aframe/issues/354) It’s fixed in the master branch. Available here: 
https://rawgit.com/aframevr/aframe/6888165/dist/aframe-master.min.js
