### ISSUE TITLE
stateadded/stateremoved documentation is wrong

### ISSUE THREAD

**Issue by InfiniteLee** [aframevr/aframe#3723]
Documenation for `a-entity` `stateadded` and `stateremoved` event says `evt.detail.state` contains the state that was added/removed, and the example shows the same: 
```
entity.addEventListener('stateadded', function (evt) {
  if (evt.detail.state === 'selected') {
    console.log('Entity now selected!');
  }
});
```
but  `state` is not actually defined on detail. Instead `evt.detail` is set directly to the state. https://github.com/aframevr/aframe/blob/030023f5aab128ce0cbe7aa24b83de5ec248cc04/src/core/a-entity.js#L750

Either the documentation is wrong or `a-entity` should be updated to emit `{state: state}`. A third option would be to imply that `addState` should be passed an object, but given nothing in a-frame does that, it is probably not correct.

- A-Frame Version: head
- Platform / Device: any

**Comment by dmarcos** [comment]
Thanks for reporting
