### ISSUE TITLE
cursor docs use incorrect event

### ISSUE THREAD

**Issue by joshmarinacci** [aframevr/aframe#3724]
**Description:**

- A-Frame Version: 0.8.0
- Platform / Device: desktop
- Reproducible Code Snippet or URL:

https://aframe.io/docs/0.8.0/components/cursor.html

At the bottom in the section on Adding Visual Feedback the animation triggers
on the `cursor-fusing` event. The correct event is `fusing`. (perhaps it was different in the past)?

The current example will not work correctly if the reader copy and pastes.

**Comment by dmarcos** [comment]
Good catch. Just corrected it
