### ISSUE TITLE
Screenshots broken in 0.8.2

### ISSUE THREAD

**Issue by stevehadley** [aframevr/aframe#3727]
**Description:**

- A-Frame Version: 0.8.2
- Platform / Device: HTC vive / Alienware R13 running firefox
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

To reproduce issue open the hello world example and take a screenshot using ctrl + alt + s to take a regular screenshot or ctrl + alt + shift + s to capture an equirectangular panorama as documented at https://aframe.io/blog/screenshot/

Equirectangular screenshots are blank and and regular screenshots are now split screen and off center

Equirectangular screenshot:
![screenshot-hello world a-frame-1534047324763](https://user-images.githubusercontent.com/34930772/43998529-e0ea2876-9e3a-11e8-86f6-71d61c52e3a8.png)

Regular screenshot:
![screenshot-hello world a-frame-1534047315918](https://user-images.githubusercontent.com/34930772/43998530-e64269c8-9e3a-11e8-992a-32fceb8a444c.png)

The off center issue is hard to see in the hello world example so here is one from my own project

![screenshot-wikimmerse-1534046948967](https://user-images.githubusercontent.com/34930772/43998535-ff768488-9e3a-11e8-8b07-f4bec35065ae.png)

**Comment by Sevrex** [comment]
Ah fair enough, in previous versions I've taken screenshots in VR using the vive buttons and they've turned out great. Is the intention to only support 2D screenshots? If that's the case I'll close this.
