### ISSUE TITLE
Use Motion JPEG stream as a source of 360 deg image

### ISSUE THREAD

**Issue by xeno14** [aframevr/aframe#3734]
**Description:**

- A-Frame Version: 0.8.2
- Platform / Device: Chrome/Oculus Go browser
- Reproducible Code Snippet or URL: please the bottom

I'm thinking of using Motion JPEG stream served via http as a source of 360 deg images, for example [mjpeg-streamer](https://github.com/jacksonliam/mjpg-streamer) which can capture JPEG frames from a web cam and streams via HTTP. However, currently `<a-sky src=...>` shows only the first frame of streaming. Is it possible to show Motion JPEG streams using aframe?

### Example
Tried streaming JPEG frames using mjpeg-streamer as described [here](https://github.com/jacksonliam/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/output_http/README.md).

This html shows only the first frame of JPEG streams while `<img src="/?action=stream">` works fine.

```html
<html>
  <head>
    <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>
        <a-sky src="/?action=stream"></a-sky>
    </a-scene>
  </body>
</html>
```

**Comment by ngokevin** [comment]
You can write a component that updates the material or texture (advance the frame, then set like `textureNeedsUpdate = true`.

**Comment by xeno14** [comment]
Thank you for your comment. I created a component like this and it worked. (this is the first time for me to use both aframe and three.js so it may not be an ideal code though).

```javascript
AFRAME.registerComponent('box', {
    schema: {
        width: { type: 'number', default: 1 },
        height: { type: 'number', default: 1 },
        depth: { type: 'number', default: 1 },
        color: { type: 'color', default: '#AAA' }
    },

    init: function () {
        var data = this.data;
        var el = this.el;

        this.loader = new THREE.TextureLoader();

        this.geometry = new THREE.BoxBufferGeometry(data.width, data.height, data.depth);
        this.material = new THREE.MeshPhongMaterial({
            map: this.getImage()
        });
        this.material.needsUpdate = true;
        this.mesh = new THREE.Mesh(this.geometry, this.material);
        el.setObject3D('mesh', this.mesh);
    },

    tick: function (time, timeDelta) {
        this.mesh.material.map.img = this.getImage();
        this.mesh.material.map.needsUpdate = true;
    },

    getImage: function() {
        return this.loader.load("/?action=stream");
    }
});
```

**Comment by Tariq96** [comment]
can i now hoe to implement this component to make it work ?

**Comment by ReedsHorton** [comment]
I am new to A-frame and HTMl in general. Looking at the above makes me think I want to run the below HTML script, but that doesn't work. When I navigate to http://IP:port/?action=stream I can see the streamed video fine...  Any suggestions of where I'm going wrong?

`AFRAME.registerComponent('foo', {
	schema: {
		width: { type: 'number', default: 1 },
		height: { type: 'number', default: 1 },
		depth: { type: 'number', default: 1 },
		color: { type: 'color', default: '#AAA' }
	},

    init: function () {
        var data = this.data;
        var el = this.el;

        this.loader = new THREE.TextureLoader();

        this.geometry = new THREE.BoxBufferGeometry(data.width, data.height, data.depth);
        this.material = new THREE.MeshPhongMaterial({
            map: this.getImage()
        });
        this.material.needsUpdate = true;
        this.mesh = new THREE.Mesh(this.geometry, this.material);
        el.setObject3D('mesh', this.mesh);
    },

    tick: function (time, timeDelta) {
        this.mesh.material.map.img = this.getImage();
        this.mesh.material.map.needsUpdate = true;
    },

    getImage: function() {
        return this.loader.load("http://IP:Port/?action=stream");
    }
});


<html>
  <head>
    <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>
 		<a-sky ></a-sky>
        <a-entity foo></a-entity>
    </a-scene>
  </body>
</html>`

**Comment by dmarcos** [comment]
@ReedsHorton I recommend opening a question in [Stackoverflow](https://stackoverflow.com/questions/tagged/aframe). We use Github issues for bug reports and feature requests.
