### ISSUE TITLE
Position, rotation, scale not updated when combining el.setAttribute and el.object3D syntax

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#3735]
If one wants to reset the value to a previously set position the component is not updated:

```javascript
el.setAttribute('position', '3 3 3');
el.object3D.position.set(5, 5, 5);
el.setAttribute('position', '3 3 3');
```

The oldData value will be `3,3,3` and the second call to `setAttribute` won't have any effect.

**Comment by ngokevin** [comment]
Really narrow edge case, I' prescribe to choose one route over the other, strongly towards the `object3D` API.

**Comment by wmurphyrd** [comment]
I could see this happening as a result of mixing different community components

**Comment by arpu** [comment]
add a console warning on setAttribute for position, rotation, scale?

**Comment by dmarcos** [comment]
Yep, I filed because the bug hit me so not a crazy use case 😄 I had an entity pool and one component was requesting entities and reseting the position at no effect. You cannot guarantee consistency of use  `setAttribute` or object3D direct manipulation specially when using 3rd party components.

**Comment by ngokevin** [comment]
Also because it's just more ergonomic. Change an axis individudally by changing a number, having access to the three.js Vector3/Euler suite for operations, vector copying and cloning, world-to-local space and vice-versa transforms. Can fix the bug, but would prefer to see setAttribute use for pos/rot/scale eradicated.

**Comment by ngokevin** [comment]
Yeah, not deprecate it...but would like to see it become a 100% adopted practice.
