### ISSUE TITLE
Text not visible through element with opacity zero

### ISSUE THREAD

**Issue by codeglow** [aframevr/aframe#3740]
**Description:**

- A-Frame Version: 0.8.0
- Platform / Device: Windows Chrome
- Reproducible Code Snippet or URL:

\<a-text value="text" color="black" shader="flat">\</a-text>
\<a-camera>
    \<a-box color="red" opacity="0" material="shader: flat; side: double"></a-box>
\</a-camera>

**Comment by machenmusik** [comment]
By default the text position is not in front of the camera, so I am not sure you would ever see it without moving the camera

See https://codepen.io/anon/pen/xabYMy

**Comment by codeglow** [comment]
Ok, in your codepen the text is working so I think i just haddend the newest version (0.8.0 --> 0.8.2).
