### ISSUE TITLE
VideoSphere Control

### ISSUE THREAD

**Issue by rose-maria** [aframevr/aframe#3747]
**How to perform an event in JS when a Videosphere reaches a particular instant in its time duration**

e.g. 
I want an alert when 360 video is at 8th second. Now this is significantly different than this :
```
AFRAME.registerComponent('foo',{
    init:function(){
    setTimeout(function(){
    alert("8 seconds reached");
    },8000);
```
Because I believe that in this case the time for downloading the ASSET(**video**) is not counted.
It will **just get executed in 8 seconds** whether or not video has loaded to play.
**Am I thinking correct** ?

**Comment by dmarcos** [comment]
I encourage to open the question on StackOverflow. It will get more visibility. We use github issues for bugs and feature requests.
