### ISSUE TITLE
Camera height and offset not applying.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3748]
**Description:**

Regression from https://github.com/aframevr/aframe/commit/e0c8ff7e4233e8554d56bf6147025d8cf40e636e

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by arpu** [comment]
i have still some problems after the  d404990  

reverting e0c8ff7 solve my problem with my avatar loading and physics 

what exactly should e0c8ff7 solve?

**Comment by arpu** [comment]
@ngokevin  plz reopen the bug (i will try to make a simple sample showing the problem)

**Comment by ngokevin** [comment]
Doesn't sound like a bug in A-Frame. You can file a new one. netpro2k mentioned it might be a physics issue.

**Comment by dsinni** [comment]
Just wanted to chime in to say that this is still an issue in
`fce54481970c5f34a3fe9fd2c130dcfc4e3bdb1b` as `0.9.0` testing is underway.

The camera height is still too high on the Go. No physics involved.
