### ISSUE TITLE
The mouse-cursor component is not working on Aframe 0.8.2 in all the browsers.

### ISSUE THREAD

**Issue by jayson04** [aframevr/aframe#3754]
**Description:**

- A-Frame Version: 0.8.2
- Platform / Device: All
- Reproducible Code Snippet or URL: https://github.com/mayognaise/aframe-mouse-cursor-component

**Comment by dmarcos** [comment]
Are you talking about the component or the built-in [cursor component](https://aframe.io/docs/0.8.0/components/cursor.html#properties_rayorigin) using the rayOrigin property? Can you provide an example to reproduce and what you get vs. what you expect?

**Comment by jayson04** [comment]
Hello it's about the component from https://github.com/mayognaise/aframe-mouse-cursor-component.

Here is the example. https://glitch.com/edit/#!/lapis-girdle?path=index.html:27:7

Click the cube using the mouse and it will turn to blue then click it again to turn it back to pink that was what I expecting but when I changed the version of  Aframe to 0.8.2 it will not work anymore. Thanks

**Comment by jayson04** [comment]
Hi @dsinni I have tried the demo in android Chrome  version 68.0.3440.91 in Huawei GR3 2017 Android version 7 and I can't change the color of the cube by touching or tapping it. I also inspect the Demo in Chrome Version 68.0.3440.106 in my laptop and I saw some warnings and errors. 
![touchissue](https://user-images.githubusercontent.com/22828729/44942564-03f15b80-ade7-11e8-94b7-b88646714641.png)

**Comment by dsinni** [comment]
@jayson04  I can confirm that I'm experiencing the same issue on Android with that demo, but I only forked your code and updated the cursor entity as an example of how to use `rayOrigin`.

I suspect the issue lies within some of the surrounding code, e.g., code not being properly encapsulated within components or systems, or placed in the wrong part of the document, etc.

I recommend wrapping your code in a component to see if you have better results.  

There's also a strange button script at the bottom of the body, which I'm not sure of its purpose. 

If I have time, I'll make another demo from scratch to see if I can reproduce the issue.

**Comment by dsinni** [comment]
@dmarcos: I can confirm that this is currently an issue in every Android browser that I've tested using both A-Frame `0.8.2` and the current `master` branch `d611e70`.

I created a simplified demo and tested in the current versions of Samsung Internet, Chrome, Chrome Dev, Canary, Firefox, Edge all with the same results. Touching only works sporadically and is either non-responsive or extremely laggy.

It works perfectly on PC, even on my touch screen, but no good on Android. I just tested with Safari on iOS as well with the same results as Android.

**Code**: https://glitch.com/edit/#!/abrupt-donkey

**Demo**: https://abrupt-donkey.glitch.me

**Comment by ngokevin** [comment]
Closing issue regarding mouse cursor: https://github.com/aframevr/aframe/issues/3754#issuecomment-417400062

The code above has some bugs (`aycaster`, mouse cursor being child of camera). Don't know how well mouse cursor would work as a child of a camera on a polyfilled device. Can create new issue if there is an example with code without errors.

**Comment by dsinni** [comment]
Thanks, @ngokevin. I removed the cursor from camera and fixed the typo, and the issue persists. I'll open a new issue with a more accurate title.

**Comment by dsinni** [comment]
@ngokevin @dmarcos Scratch that. It appears the cursor needs to be at the bottom of the scene. Simply removing it from the camera wasn't enough. I'm not sure if that's something that needs to be either addressed or documented.

After moving it to the bottom of the scene, it functions as expected: https://abrupt-donkey.glitch.me/
