### ISSUE TITLE
Click event not firing if mouse is not moved

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#3765]
**Description:**
The click event is not fired anymore if the mouse is not moved on the element. If the mouse moves a bit, then the event is firing again.

- A-Frame Version: 0.8.2 AND master
- Platform / Device: Desktop Firefox
- Reproducible Code Snippet or URL: 
After clicking on the start button, a navigation menu appears on bottom. Pose mouse cursor on right arrow without moving the mouse and click, and click again and again. Only the first click event fires and moves the white thumbnail indicator. If you slightly move the mouse between clicks, click events are fired.
http://dev2.ideaspacevr.org/gallery

**Comment by dsinni** [comment]
Hmm. Appears to be working for me in `0.8.2`.

I forked the boilerplate, added a click listener, and disabled movement and look controls and it is logging every click.

The sphere is the clickable entity, not that you'll have much choice in the matter. :D

**Code**:
https://glitch.com/edit/#!/safe-tiglon

**Demo**:
https://safe-tiglon.glitch.me/
