### ISSUE TITLE
Question: can I use fisheye projection with A-frame instead of equirectangular?

### ISSUE THREAD

**Issue by yieldnow** [aframevr/aframe#3769]
Hello! 
Can I use fisheye projection with A-frame instead of equirectangular?

**Comment by colinfizgig** [comment]
If you use UV maps laid out according to the fisheye projection it should work.  But that would involve creating your own UV map in a 3d program.  It would not work on a default primitive sphere in aframe.

These geometries may be of use to you.

https://github.com/AndrewHazelden/Panoramic_Geometry_Collection

**Comment by colinfizgig** [comment]
![image](https://user-images.githubusercontent.com/7503097/45931254-83330480-bf39-11e8-82c5-e67811eee3ee.png)

this mesh is laid out for thetaS  as an example.  https://github.com/AndrewHazelden/Panoramic_Geometry_Collection/blob/master/meshes/ricoh_theta_s_mesh.obj

**Comment by dmarcos** [comment]
We use StackOverflow for questions. You can move the discussion there. It will get more exposure. We use Github issues for bugs and feature requests.
