### ISSUE TITLE
componentchanged events no longer fire on camera

### ISSUE THREAD

**Issue by squaretone** [aframevr/aframe#3773]
**Camera component componentchanged no longer fire**

- A-Frame Version: 0.8.2
- Platform / Device: macOS all browsers
- Reproducible Code Snippet or URL: https://codepen.io/squaretone/full/WgqaqQ

This worked in versions prior to 0.8.2. In the above pen, we subscribe to the `componentchanged` event of the camera and write the rotation output to the a-text when the event fires.  The `componentchanged` event is never emitted. If you change the referenced version of A-Frame back to 0.8.0 the example works.

Are event listeners no longer supported on the camera or is there a possible bug?

Thanks.

**Comment by dmarcos** [comment]
This is expected behavior. `componentchanged` is not emitted anymore for rotation, position, scale for improved performance. You can read the values on a `tick` method in your component and update `a-text` accordingly:

```
tick: function () {
     var cameraRotation = this.el.sceneEl.camera.el.object3D.rotation ; // or this.el.sceneEl.camera.el.getAttribute('rotation'); this will return degrees not radians.
    textEl.setAttribute('value', 'x: ' + cameraRotation.x + ' y: ' + cameraRotation.x + ' z: ' +  cameraRotation.z
}
```
