### ISSUE TITLE
Inconsistent clipping on right eye

### ISSUE THREAD

**Issue by Pluto8195** [aframevr/aframe#3775]
Im working on a component that makes it intuitive to set up local clipping planes around geometries,
everything is working except that there is an inconsistency on what the right eye sees from the left

![clipping](https://user-images.githubusercontent.com/10274697/46055425-c2f81880-c100-11e8-9527-aed88b3b45f6.PNG)

- A-Frame Version: 0.8.2
- Platform / Device: all
heres a link to the glitch
https://clipping-planes.glitch.me/

**Comment by arpu** [comment]
maybe you can try this patch against threejs 
https://github.com/mrdoob/three.js/pull/14950

**Comment by Pluto8195** [comment]
That fixed it! It also fixed a similar issue with spot lights, strangely enough it didn't fix the frustum culling it was intended too.

**Comment by dmarcos** [comment]
Left eye camera frustum is used for culling both eyes in THREE. As you saw it has to be fixed on the THREE side first.
