### ISSUE TITLE
Camera spins down on Firefox

### ISSUE THREAD

**Issue by mirdaki** [aframevr/aframe#3778]
Hello all, when I go to the A-Frame site or any glitch project, if I try dragging my mouse on the scene to look around the camera starts spinning and points downwards. If I stop dragging the mouse it stays pointed down. If I try to readjust the camera view it starts spinning again.

I have tried disabling Tracking Protection, Privacy Badger, and HTTPS Everywhere, as those sometimes give me issues on other sites, but it doesn't seem to change anything here. 

It doesn't seem to happen on other WebVR things (such as [React's 360 here](https://github.com/facebook/react-360)). It also seems fine on Edge.

Let me know if there is anything else I can provide to help.

- A-Frame Version: Looking at the source for some of the A-Frame examples: 0.5.0, 0.7.1, and 0.8.2
- Platform / Device: Kubuntu 18.04 and Windows 10 on Firefox 62.0.2

**Comment by dmarcos** [comment]
Windows / Firefox is my work setup and never seen this issue. Can you also reproduce in a different machine?

**Comment by mirdaki** [comment]
I think I found the cause. It was happening on other computer's if I had signed into Firefox. So I looked through my `about:config` settings to see if anything I had set might be causing it. Turns out the `privacy.resistFingerprinting` was set to true. Once I set it to false (which is default) it stopped behaving that way. 

Not sure exactly what part of `privacy.resistFingerprinting` was affecting it, but here is the [list of things it does](https://wiki.mozilla.org/Security/Fingerprinting). Ideally both would work (considering other WebVR things seemed fine), but at least there is a workaround for now.

**Comment by dmarcos** [comment]
I see. I don't think we can do anything on the A-Frame side. `privacy.resistFingerprinting` probably introduces noise / imprecision in the data to prevent identifying the user. Thanks for reporting. I'm going to close this for now. Feel free to open a new issue if there's any known workaround.
