### ISSUE TITLE
THREE.WebGLRenderer: Context Lost

### ISSUE THREAD

**Issue by florentpeyrard** [aframevr/aframe#3779]
Hello,

I'm using A-Frame 0.8.2 with Vue.js 2.5.13 on Chrome 69.

In my scene, I have entities using gltf-model component, and an a-sky to have a 360 image as a background. In various cases (like having 10 entities at the same time, destroying/creating entities with v-for, destroying/creating the scene with v-if ), I get this error : 
 `THREE.WebGLRenderer: Context Lost`

The scene is broken, even reloading the tab doesn't help. Only opening a new tab allows recovering.

I had a look at https://github.com/mrdoob/three.js/issues/11435 and tried to apply this to my case, with no success : 

- listening to the `webglcontextlost` event on the `canvas` property of A-Frame scene object : it is fired properly.
- calling `forceContextRestore` on the `renderer` property of A-Frame scene object. Sometimes the scene object is `undefined`.
- listening to the `webglcontextrestored` event on the `canvas` property of A-Frame scene object : it is never fired.
- calling `reload` on the  A-Frame scene object : I get the `not a function` error.

Do you plan to manage this error at A-Frame level ? 
Anyway, how can I handle this problem which makes the experience very unstable ? 
Thanks in advance :)

- A-Frame Version: 0.8.2
- Platform / Device: Windows 10 on a laptop with a second display (which may trigger the error, as stated in the three.js issue mentionned above)
- Reproducible Code Snippet or URL:

**Comment by florentpeyrard** [comment]
I actually see two problems : 
- there is an "amount" of entities which triggers the error;
- destroying entities with vue.js reactive features (v-if, v-for) doesn't free the entities from the total amount : when new ones are created, the error is triggered.

**Comment by florentpeyrard** [comment]
The problematic number of entities is actually around 30, 20 MB each.

**Comment by florentpeyrard** [comment]
The error occurs when the RAM gets around 90% (my laptop GUI uses shared memory). I changed the code so that entities aren't destroyed/created, I rather have all the entities loaded at once, and I make each visible or not during the experience. Also a workaround is necessary :  after the experience is finished, I reload the page to free the RAM for the next experience.

Previously, I tried to set/remove `gltf-model` attribute on the pool of entities, but the problem still occured. I looked at `gltf-model` code : on `remove`, it performs `removeObject3D('mesh')`, which doesn't cause the RAM to be freed. The loader works like a charm, but we're missing an unloader, I guess :) This is a problem, because in a database-oriented SPA, you want to be able to dynamically load entities without getting closer and closer to a crash :) 

To sum-up, I see the following issues : 
- the gltf loader doesn't free the RAM at remove
- the _context lost error_ isn't managed

All that being said, thank you very much for this excellent piece of technology, which makes VR so accessible :)

**Comment by florentpeyrard** [comment]
Hi,

do you have any idea of when the "recover context lost" fix would be available ? And what about freeing the RAM when unloading a gltf model ?

Thanks !

**Comment by florentpeyrard** [comment]
Here's a workaround for the double-clicks leading to `Context lost`. On a-scene `loaded` event, we can do : 
```
let canvas = document.querySelector('a-scene').canvas
canvas.addEventListener('selectstart', function(e) { e.preventDefault(); return false; }, false)
```

**Comment by florentpeyrard** [comment]
Hi,
so how to unload a glTF model, so that RAM is freed ? This is key to having rich 3D experiences.

**Comment by florentpeyrard** [comment]
Hi,

so how to get the RAM freed, when detroying an entity with a glTF model attached to it ? This is key to having rich dynamic content, not just a few models in the whole experience.

**Comment by florentpeyrard** [comment]
The memory leak due to partial unloading is actually referenced by this open issue : https://github.com/aframevr/aframe/issues/3137

Still, recovering from lost context sould be addressed here.

**Comment by antoniohof** [comment]
I think I had a similar issue. 
I don't recommend using v-if to destroy your scene, as it has problems cleaning up the memory and the webgl context. Using the same scene and adding/removing entities should be ok.
You could try using `window.THREE.Cache.clear()` and/or
`AFRAME.scenes[0].renderer.renderLists.dispose()` to clean asset cache after removing an entity.

**Comment by florentpeyrard** [comment]
Hi @antoniohof ,
thanks a lot for the help ! I post my conclusions about dynamic loading in https://github.com/aframevr/aframe/issues/3137, so that the hereby issue remains focused on managing context lost, which is likely to happen in various cases. At least : managing unloading being tricky (and maybe impossible to achieve perfectly to date... to be confirmed), user selecting text.

**Comment by ngokevin** [comment]
Can be summed up to memory overflow?

I think can be solved by not destroying / recreating scene.

And using object pooling. https://aframe.io/docs/0.9.0/components/pool.html

**Comment by florentpeyrard** [comment]
A fix is still needed to manage `Context lost`, which can have various reasons, not only models unloading/loading (see [above ](https://github.com/aframevr/aframe/issues/3779#issuecomment-434997712) for another one, maybe others exist).

Regarding the models loading/unloading : pooling is not sufficient if you have many models. You have a limited quantity of RAM available at any given point in time, so you have to dynamically load only what you need right now and unload the rest. As mentionned [here](https://github.com/aframevr/aframe/issues/3779#issuecomment-451900301), I posted some more in depth analysis about this [here](https://github.com/aframevr/aframe/issues/3137#issuecomment-451915708). TLDR : I'm using a workaround for the time being, which is unfortunately failing to fully release the memory, so my app is still being exposed to memory overflow.

Also, in a SPA, when you navigate between pages all having their own scene, each  scene is destroyed/created each time, as the instance they live in is created/destroyed dynamically, so the idea of keeping the same scene throughout the user experience doesn't work.

So far, I really enjoy programming with A-Frame but to me, memory management is the really big downside that makes the engine unreliable for building ambitious projects. Really hoping for enhancements.

**Comment by code-bajju** [comment]
This is because of the lower version of ReactJS. I have also tried this and ended up facing this error.
I resolved it using Vite. I upgraded my project in Vite, then the error was gone and I successfully rebuilt my model.

**Comment by andrewhodel** [comment]
```
// https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextlost_event
canvas_element.addEventListener('webglcontextlost', function() {
  renderer.setAnimationLoop(null);        // pause the animation
});

// https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextrestored_event
canvas_element.addEventListener('webglcontextrestored', function() {
  renderer.setAnimationLoop(render_function);        // start the animation
});
```

**Comment by andrewhodel** [comment]
A problem is that a `try catch` in the render loop is slow, and `https://threejs.org/docs/?q=rende#api/en/renderers/WebGLRenderer.render` returns undefined.

If `render` returned an error status, you could call `renderer.setAnimationLoop(null)` there and restart the animation loop in `webglcontextrestored` but all documentation of three.js would need to be updated.

**Comment by andrewhodel** [comment]
The render loop iterates based on available FPS according to some writings I have read.

If that's true, it is possible that the FPS not being available causes the wait between iterations to be very short meaning that a processor is kept at 100% utilization.

**Comment by andrewhodel** [comment]
https://github.com/mrdoob/three.js/issues/29435

**Comment by andrewhodel** [comment]
Notice that the webglcontext events are missing, without those events the renderer will max a CPU at 100% utilization.

If this is in reference to https://github.com/aframevr/aframe/issues/3779#issuecomment-2357209140, then no, an empty requestAnimationFrame loop does not increase in frequency to fill all available CPU time. It is limited, among other things, by the refresh rate of the display.

That does not answer if the default frequency is CPU max or not.

I am certain that the CPU lock remains with the webglcontext events stopping the animation loop. That is why there is this issue - https://github.com/mrdoob/three.js/issues/29434
