### ISSUE TITLE
[docs] introduction HTML & Primitives

### ISSUE THREAD

**Issue by Perhelion** [aframevr/aframe#3780]
**Description:**
- A-Frame Version 0-8-0: example showcase helloworld screenshot https://aframe.io/docs/0.8.0/introduction/html-and-primitives.html
I've updated the JPG to PNG as JPEG has lower quality by larger file size.:  https://upload.wikimedia.org/wikipedia/commons/6/62/A-Frame_Hello_World_example.png
So it would be good if it could updated.
I could handle any small improvement suggestion, as I have the graphic with text-layers.

**Comment by ngokevin** [comment]
thanks, can you use the edit button the doc page to update it? you can get a URL by dragging the image into github issue.

**Comment by Perhelion** [comment]
Oh* ok, done, but it doesn't include a Github link, instead a Wikimedia link!?

**Comment by ngokevin** [comment]
Just drag the image into these text boxes.

**Comment by Perhelion** [comment]
hm*  done https://github.com/aframevr/aframe/pull/3800

**Comment by ngokevin** [comment]
Don't use cdn.aframe.io ... drag the image into the text box here to get a URL.

**Comment by dmarcos** [comment]
@ngokevin anything pending here?

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/23f8ceaa003ac7a4d1d0833a90758ca88b85c548
