### ISSUE TITLE
Erratic VR Camera - miscalibrated gyroscope/accelerometer output?

### ISSUE THREAD

**Issue by edanweis** [aframevr/aframe#3783]
**Description:**

- A-Frame Version: 0.7.1
- Platform / Device: Android 8.1.0 - POCOPHONE F1
- Reproducible Code Snippet or URL:
https://youtu.be/ms159WCMlqU
http://ourway.surge.sh/ 
https://github.com/edanweis/ourway

VR Camera is hypersensitive to device rotation using the POCOPHONE. See the YouTube video. Note this phone is missing from the Device Parameter Database `dpdb.json` ?  Same code works on NextBit Robin Android 6.x. 

How can I fix this?

**Comment by edanweis** [comment]
Apologies, just saw  #3565

**Comment by dmarcos** [comment]
No problem 👍 Closing this.
