### ISSUE TITLE
Play 360º video without wating

### ISSUE THREAD

**Issue by fedegonzal** [aframevr/aframe#3784]
I want to play a 360 video with Aframe. My video is mp4 format with 360 meta activated. The video has 5 minutes, if I put it into a normal http server, clients must to wait until the video download to browser.. a lot of time. Which strategy could be the best approach to resolve this?

**Comment by dmarcos** [comment]
I recommend using StackOverflow
to post your question. It will get more
visibility. We use github issues to track bugs and feature requests.
