### ISSUE TITLE
Uncaught TypeError: Cannot set property 'BUFFER_SCALE' of undefined

### ISSUE THREAD

**Issue by BoryaMogila** [aframevr/aframe#3788]
**Description:**

- A-Frame Version: 0.8.2
- Platform / Device: Windows 10 / Google Chrome 69
- Reproducible Code Snippet or URL:

Sometimes this code fail at aframe/src/index.js
`if (utils.device.isIOSOlderThan10(window.navigator.userAgent)) {
  window.WebVRConfig.BUFFER_SCALE = 1 / window.devicePixelRatio;
}`
Not

**Comment by benjaminleonard** [comment]
I get the same error on Chrome on a iPhone 8 running iOS 12.0.1.
Works fine in mobile Safari

**Comment by benjaminleonard** [comment]
This is fixed for me now

**Comment by dmarcos** [comment]
@benjaminleonard thanks for letting us know
