### ISSUE TITLE
Don't set grabbing class on the body. Causing 2ms style recalculations.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3790]
**Description:**

For look-controls, setting class on the body on each click, causing 2ms style recalculations. We should just set the style directly.

**Comment by krzysztof-grzybek** [comment]
Hi @ngokevin , can I take this one?

**Comment by ngokevin** [comment]
yeah sure. see look-controls.js and tests/components/look-controls.js and src/style.css
