### ISSUE TITLE
Rawgit.com is shutting down.

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#3803]
Via https://github.com/mrdoob/three.js/issues/15027.

Looks like we have examples and docs that rely on it: https://github.com/aframevr/aframe/search?q=rawgit&unscoped_q=rawgit

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/6cc9abcc2f0fcb4f14a8806e6d129dbe152d5a58

**Comment by donmccurdy** [comment]
That was quick 😅
