### ISSUE TITLE
commit  6deaea0 breaks aframe-physics-system.js with  Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by arpu** [aframevr/aframe#3808]
merge https://github.com/aframevr/aframe/pull/3772  breaks aframe-physics-system.js
with 

Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at NewComponent.initBody (aframe-physics-system.js:15646)
    at HTMLElement.module.exports.Object.create.emit.value (a-node.js:300)
    at emitLoaded (a-node.js:131)

https://codesandbox.io/s/vv6jm1l06l

**Comment by dmarcos** [comment]
This is the error I see: ![image](https://d3vv6lp55qjaqc.cloudfront.net/items/400Y41470i2p1F042D0z/Image%202018-10-18%20at%208.48.15%20AM.png?X-CloudApp-Visitor-Id=3e69d56f8460e022550044f6567633e0&v=bcbc8180)

**Comment by arpu** [comment]
yes you are right i see this error in firefox too and  the other error in chrome

**Comment by donmccurdy** [comment]
Stepping through code here, `this.data` in the `static-body` component evaluates to a string, "true". Not sure why that should be happening though..

**Comment by arpu** [comment]
yeahh this fixed it thx!  see static-body=""  works https://codesandbox.io/s/52oq8zx7z4

**Comment by donmccurdy** [comment]
Let’s keep this open, I think it’s a regression we’ll want to fix.

**Comment by ngokevin** [comment]
Empty attributes are not supported in React. I also don't recommend React.

**Comment by arpu** [comment]
ok thx for the information! i have done some small test 
https://codepen.io/anon/pen/qJGWJO?editors=0010

looks like react remove the attribute if its not set

**Comment by ngokevin** [comment]
Hard to say. It was a big change, but I think it is better that the error is present. It wasn't working before, something was just silently failing. This should never have worked:

![screen shot 2018-10-29 at 5 27 46 pm](https://user-images.githubusercontent.com/674727/47687939-10542380-dba0-11e8-94ff-75e9a696c3b9.png)

**Comment by donmccurdy** [comment]
Just to confirm, `static-body` and `static-body=""` should be allowed, but `static-body="true"` should not?  And the first two are both working before and after this change? If so I'm fine with that... but I think we want to keep `el.setAttribute('foo', '')` working since that is fairly common.
