### ISSUE TITLE
latest master build is not on cdn.jsdelivr.net aframe@0a679a1

### ISSUE THREAD

**Issue by arpu** [aframevr/aframe#3810]
https://cdn.jsdelivr.net/gh/aframevr/aframe@0a679a1/dist/aframe-master.min.js 

i get 404 not found 

https://github.com/aframevr/aframe/commit/006e8be2722009d2ee6bd7c3440ec7b562d316c1

**Comment by arpu** [comment]
rawgit works 
https://rawgit.com/aframevr/aframe/0a679a1/dist/aframe-master.min.js

**Comment by ngokevin** [comment]
It’s been fixed since, wait for a build
