### ISSUE TITLE
Font images not auto-loading due to missing period `.` before file extension

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#3815]
**Description:**

I was just testing the quasi-`0.9.0` `master` and I noticed that fonts such as `https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/allertastencil/AllertaStencil-Regular.json` are not auto-loading the font image as they were in `0.8.2`.

This appears to be because it's being converted to `https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/allertastencil/AllertaStencil-Regularpng`, which is missing a period (`.`) before the file extension (`png`).

![image](https://user-images.githubusercontent.com/4733018/47136161-df5f1f00-d280-11e8-8102-589ece120f36.png)

- A-Frame Version: ~ `0.9.0` `master` commit `fce54481970c5f34a3fe9fd2c130dcfc4e3bdb1b`
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by dsinni** [comment]
Upon further investigation, it appears that the missing period is not caused by A-Frame, but rather the value within the font `json` file.

```json
{"pages":["AllertaStencil-Regularpng"]
```

However, this behavior has changed since `0.8.2`, where the image was loaded automatically; this no longer appears to be the case (with the exception of maybe non-https):

Possible code in question:
https://github.com/aframevr/aframe/blob/master/src/components/text.js#L257

Was there a solid reason for the change? Any way around it?

Thanks.

**Comment by dsinni** [comment]
Also opened an issue with the font repo: https://github.com/etiennepinchon/aframe-fonts/issues/6

**Comment by donmccurdy** [comment]
See https://github.com/aframevr/aframe/pull/3651 — I think the ideal fix would be for the aframe-fonts repo to be regenerated.

**Comment by dsinni** [comment]
Agree @donmccurdy. Although, was wondering why the change in how it loads. Thanks.

**Comment by dsinni** [comment]
Thanks, @donmccurdy. I agree. Was just wondering why the change in A-Frame, but I think you just answered that. Haha. Better for the font image location to be explicit rather than implicit.

**Comment by dsinni** [comment]
Feel free to close unless you'd rather wait until resolved. Thanks!

**Comment by ngokevin** [comment]
Yeah, closing since it's an issue with the tool. A workaround is to manually add the dot. We'll get that repo regenerated soon.

**Comment by dsinni** [comment]
Thanks, guys.
