### ISSUE TITLE
cursor: "rayOrigin: mouse" detects wrong element

### ISSUE THREAD

**Issue by naraesk** [aframevr/aframe#3818]
**Description:**

I have a visualization with many occluded elements and onclick event handlers for every element. ```cursor="rayOrigin: mouse"``` is used to detect mouse clicks. But sometimes the event handler of an occluded element is called: box A occludes box B. When clicking on box A the event handler of box B is called, although it is hidden completely behind box A. Most of time it works corect (event handler of A is called). Just click around a bit in the attched visualization, sooner or later you will notice the wrong behaviour.

- A-Frame Version: 0.8
- Platform / Device: Desktop/Chromium
- Reproducible Code Snippet or URL:
[mouseray.zip](https://github.com/aframevr/aframe/files/2498070/mouseray.zip)

**Comment by arpu** [comment]
but there is problem with entities within groups (nested in an entity)  since this commit see commit user message 

https://github.com/aframevr/aframe/commit/8809e7fd5eccd4c4ce76892f4a5673b911dfd60f

**Comment by ComputerTime** [comment]
On this latest version of master, i can't get the objects array in a
raycaster to not be equal to an empty string or null, which means the whole
scenes children array is being used, so it seems to be fine now.

**Comment by dmarcos** [comment]
@ComputerTime Thanks for verifying. Closing and will reopen if the problem comes back.
