### ISSUE TITLE
animation of dae model

### ISSUE THREAD

**Issue by 544531645** [aframevr/aframe#3819]
Description:
How to load the animation of dae model? I use Ar. Js and AFrame to only show the model without any animation. How can I load the animation?
- A-Frame Version:0.8.0
- Platform / Device:Windows
- Reproducible Code Snippet or URL:

**Comment by donmccurdy** [comment]
You'll need to convert the model to glTF (try [COLLADA2GLTF](http://github.com/khronosgroup/collada2gltf) or http://cesium.org/convertmodel.html). Animation in COLLADA models is not currently supported, and note that [the collada-model component may be deprecated or removed in upcoming versions](https://github.com/aframevr/aframe/issues/3793).

**Comment by donmccurdy** [comment]
Once you've converted the model, use the `animation-mixer` component from A-Frame Extras to play animation: https://github.com/donmccurdy/aframe-extras/tree/master/src/loaders#animation

**Comment by 544531645** [comment]
![image 1](https://user-images.githubusercontent.com/15622364/47338529-da5bfe80-d6ca-11e8-9abb-1a2839cad9b3.png)
I convert happend this , this mean dae have question , but it work well in arkit for ios

**Comment by 544531645** [comment]
three.js/editor if okay ,I use it export no animatio

**Comment by 544531645** [comment]
@donmccurdy

**Comment by 544531645** [comment]
I use  COLLADA2GLTF not show material  ,only black broken line
![image](https://user-images.githubusercontent.com/15622364/47351473-9c6ed280-d6ea-11e8-9a10-f46678511dfc.png)

**Comment by donmccurdy** [comment]
If COLLADA2GLTF is giving results that don't match the original model, I think you'll need to file a bug on the COLLADA2GLTF repository: https://github.com/KhronosGroup/COLLADA2GLTF
