### ISSUE TITLE
The model material is flashing all the time

### ISSUE THREAD

**Issue by 544531645** [aframevr/aframe#3822]
**Description:**
![image](https://user-images.githubusercontent.com/15622364/47420197-71e74d00-d7b0-11e8-8eb5-bed8e53f30f3.png)
![image](https://user-images.githubusercontent.com/15622364/47420227-8a576780-d7b0-11e8-9aa1-eefe0f02a988.png)

![dbj1nja 18s_ b w8 jbumn](https://user-images.githubusercontent.com/15622364/47420141-52e8bb00-d7b0-11e8-9216-3943cf5ca74e.png)
It seems that FPS is very high and flickering all the time. Is there any solution?

- A-Frame Version: 0.8.0
- Platform / Device: window and siri

**Comment by 544531645** [comment]
![image](https://user-images.githubusercontent.com/15622364/47420255-97745680-d7b0-11e8-9014-41f98614a08d.png)
There is nothing under the eye normally, and the banana is not damaged

**Comment by donmccurdy** [comment]
Is this using ARjs? It sound like a known issue there (https://github.com/jeromeetienne/AR.js/issues/146), the camera's near/far planes are automatically chosen and too far apart.

If it is a glTF file, do you see the same problem on http://gltf-viewer.donmccurdy.com/?

**Comment by 544531645** [comment]
gltf but import to http://gltf-viewer.donmccurdy.com/  , it show this image

**Comment by 544531645** [comment]
![image](https://user-images.githubusercontent.com/15622364/47476601-d27b9600-d853-11e8-88e2-4f68cf1f9905.png)

**Comment by 544531645** [comment]
but my gltf is use fbx2gltf export ,
![image](https://user-images.githubusercontent.com/15622364/47476616-e7f0c000-d853-11e8-8b5e-11d52c18373f.png)
![image](https://user-images.githubusercontent.com/15622364/47476624-f048fb00-d853-11e8-8da4-116be53e0753.png)

**Comment by 544531645** [comment]
![image](https://user-images.githubusercontent.com/15622364/47485613-0add9d00-d871-11e8-8b91-a810bb8a60b6.png)
new Three.VREFFCT is can't find conasl

**Comment by donmccurdy** [comment]
This is an ARjs bug — that workaround appears to be outdated, and unfortunately I don't know if they have actually fixed the bug or can provide a newer workaround.. You may need to ask there.

It sounds like viewing the model on http://gltf-viewer.donmccurdy.com/  is probably not really part of the problem, but if you drag all related files including a `.gltf` or `.glb` file (in a ZIP, if necessary) you should be able to see the result with correctly-configured camera settings.

**Comment by vadermemo** [comment]
using antialias and logarithmicDepthBuffer on scene works for me:

<a-scene
      renderer="antialias: false; logarithmicDepthBuffer:true"
>
</a-scene>
