### ISSUE TITLE
Material.visible = false not working

### ISSUE THREAD

**Issue by dahqqin** [aframevr/aframe#3824]
Description:
I'm using the event-set component with an event that is supposed to hide a window in order to change the room in a virtual tour.
My idea is to make a virtual tour with each room in an entity, and when I hide the macro-entities (entities with entities inside them) anything happens, everything stays visible and clickable, and that's not the idea.

My workaround is for now dragging everything to position 99 99 99 in order to remove things from the window, but that isn't orthodox at all, I'd like a bit of help in here.

Thank you!

- A-Frame Version: 0.8.0
- Platform / Device: Windows 10
- Reproducible Code Snippet or URL: Don't have

**Comment by donmccurdy** [comment]
Could you provide an example to reproduce the problem?

**Comment by dahqqin** [comment]
Sure.

I'm using the event-set component to push some actions, and the punctual button that is not working has the following code:
`<a-entity geometry="primitive:box;" position="-8.5 1 5" material="shader:gif;src:url(https://media.giphy.com/media/JROrvHnpJis4U/giphy.gif);color:red;opacity:.8" rotation="0 30 0" **event-set__click="_event: click; _target: #ventana_inicio; material.visible: false"** `

You'll notice that the event I'm triggering should make all the material inside "ventana_inicio" entity invisible, but when I trigger the event, nothing happens there.

Ventana_inicio's code is this:

`<a-entity id="ventana_inicio">

      <a-entity id="qmark" template="src: #TMP_qmark" data-src="#cubes" data-thumb="#IMG_pregunta" position="3 2 -3"></a-entity>
    
      <a-entity id="navigation" template="src: #TMP_navigation" data-src="#IMG_second_nav_afu" data-thumb="#IMG_navigation" position="-6 -2 4" rotation="-90 0 -60" ></a-entity>

</a-entity>`

**Comment by ngokevin** [comment]
You need to target the entities with materials. ventana_inicio has no material. Try `visible`.

**Comment by dahqqin** [comment]
Hello, Kevin, thank you for your response.
The thing is that if I only trigger visible to false, the items will still be raycastable, and the point here is to hide them definitely. Any hint on this?

**Comment by ngokevin** [comment]
Raycasting should be handled separately from visibility. We could add a `collideWithNonVisible` flag though to raycaster.

I set `objects: [data-raycastable]` and add/remove the `data-raycastable` attribute with a bunch of helper components (e.g., aframe-state-component, or you could have a component that adds/removes that attribute based on visibility).
