### ISSUE TITLE
Mixin text dont override default and generate fantom attribute

### ISSUE THREAD

**Issue by arthurmougin** [aframevr/aframe#3825]
Mixin including `text__A="color:black"` dont override default value of targets setted as `text__A="value:my value" ` but generate a second component with the same id on the target (visible on the debuger)

- A-Frame Version: A-Frame Version: 0.8.2 (Date 2018-04-15, Commit #b20527f)
- Platform / Device: tested on opera, edge, firefox quantum,opera
- Reproducible Code Snippet or URL:

```
        <a-assets>
            <a-mixin id="vue" text__A="color:black" scale="1.5 1.5 1.5" geometry="primitive: plane; height: 0.1" material="color:white" ></a-mixin>
        </a-assets>
  <a-entity position="0 2 -2" text__A="value:new view" mixin="vue"></a-entity>
```

**Comment by ngokevin** [comment]
Sorry for the delay. What does the debugger show?

**Comment by arthurmougin** [comment]
Found the problem: 
  https://sleet-shock.glitch.me
  https://glitch.com/edit/#!/sleet-shock?path=index.html:7:72

I was using a-text and I couldn't find the text__Artibute to target my a-text. (found that i just had to use `text="color:red"`)
Is it possible to set that the class name (or the id) is used as text id (text_{set Id | class name Here})?

**Comment by ngokevin** [comment]
I see. You should either not use `<a-text>` and use `<a-entity>` with your preferred component ID...or also have plain ID-less `text` on your mixin.

**Comment by arthurmougin** [comment]
then a-text isn't reliable for scaling up :/ Thank you for the help :)
