### ISSUE TITLE
Normal Maps appear to be reversed when imported with GLTF Standard Materials

### ISSUE THREAD

**Issue by colinfizgig** [aframevr/aframe#3826]
When opening a GLTF that was converted from Maya FBX with FBX2GLTF the normal map appears to be inverted on the Y axis.  If I import the object into three.js editor.  The light looks like it is coming from below the object.  If I convert the materials to Phong and turn the imported normal map back on.  This fixes the problem.  If I then convert the Phong back to a Standard Material and turn the normal map back on, it appears correct.  HOWEVER,  When I export this "FIXED" model as a GLB from the Three.js Editor and reimport to check that the fixes stuck.  The normals are wrong again.  This means that whatever is flipping the normals on the Y is occurring in the GLTF export or conversion within Three.js.

Here is an image of imported GLB composited with the phong fix to show the difference...

![normal map issue with gltf](https://user-images.githubusercontent.com/7503097/47535356-42f0da00-d889-11e8-80f1-b29c9531ee15.jpg)

And here is a screen grab of the re-imported "Fixed" file with the normals wrong again.

![reexported](https://user-images.githubusercontent.com/7503097/47535404-7b90b380-d889-11e8-8e6b-6cf79baf9c84.JPG)

I believe this is the same issue as this... https://github.com/aframevr/aframe/issues/3580

- A-Frame Version: 0.8.0
- Platform / Device: Windows/Any
- Reproducible Code Snippet or URL:

**Comment by colinfizgig** [comment]
I think I figured out the problem.  My normal maps were setup for DirectX not OpenGL.  I'm assuming that WebGL requires OpenGL format Normal Maps?  I tried your gltf viewer, but it won't show the problem since the lighting is coming from directly in front of the object.  To see the problem it would need lighting from a more vertical light source.

Not sure why changing the shader to Phong in Three.js editor would fix the problem temporarily, but once I tried the normal maps on a primitive in Aframe I realized they were the problem and started looking for a solution.  Perhaps it would be good to point out that Normals should be setup in OpenGL format in the Aframe Docs?  It's easy to see the problem with Normalized Normal maps, DirectX appears to be underlit, while OpenGL appears to be lit from above.

DirectX Normal Map
![parthenonblocks_normal](https://user-images.githubusercontent.com/7503097/47577697-82fd9e80-d915-11e8-822a-284bc221fd4d.png)

OpenGL Normal Map
![parthenonblocks_normalinverted](https://user-images.githubusercontent.com/7503097/47577714-93157e00-d915-11e8-8b41-30a28e22d13c.png)

Thanks for the Help Don.

**Comment by donmccurdy** [comment]
This depends on how the model's UVs are authored, as well... glTF has a convention, other formats may have another convention or no convention at all. In general it will be easiest to use the GLTF presets in Substance (do those give the option of DirectX normals? I don't think they should...) but if you're loading a normal map independently of the model itself unfortunately there will be often be some background information or adjustment required. For any texture, not just normal maps, the *Textures* section here is relevant: https://threejs.org/docs/#examples/loaders/GLTFLoader.
