### ISSUE TITLE
The antialias="true" attribute doesn't work with Oculus Go

### ISSUE THREAD

**Issue by enheit** [aframevr/aframe#3832]
I've found an interesting issue with the `antialias` property using Oculus Go. If I open any glitch scene where `antialias` property is set to true (e.g. `<scene antialias="true"></a-scene>`), everything work okay. If I copy paste this code into my local project (Angular 6), the `antialias` property stop working.

Also, after my investigation, I've found that the `antialias` property works correctly with Oculus Go with A-Frame version 0.5.0.

- A-Frame Version: 0.8.0
- Device: Oculus Go
- Reproducible Code Snippet or URL: https://joyous-cup.glitch.me/ (works correctly with Oculus Go)

**Comment by dsinni** [comment]
Does `renderer="antialias: true;"` work?

Also, maybe try A-Frame `0.8.2` as it contains bug fixes.

**Comment by enheit** [comment]
@dsinni doesn't work :(

**Comment by enheit** [comment]
@dmarcos yes, it works without Angular.

**Comment by dmarcos** [comment]
antialias flag applies when the renderer initialize and cannot be changed / toggled afterwards. This is a limitation on how WebGL contexts work. Angular might be delaying the application of the HTML attributes after a-scene initialization. I don't know enough about Angular to suggest a workaround. Try to make sure in Angular land that a-scene attributes are applied before initialization.

**Comment by enheit** [comment]
Maybe is there any problem in the A-Frame? Because version 0.5.0 works great with Angular.

**Comment by dmarcos** [comment]
As far as I know nothing has changed on how anti-alias is applied. I'm not an Angular user and I don't know how its HTML attributes are processed and applied. If you have more insight please educate. Happy to look into it.

**Comment by Mic1974** [comment]
hi,
in my actual project using the aframe-master, the anti-alias has gone on oculus go. with 0.8.2 ist's working. any ideas? can't use 0.8.2 because playing audio on click-events doesn't work correctly in that version...

**Comment by dmarcos** [comment]
I just tested with examples and [master](https://cdn.jsdelivr.net/gh/aframevr/aframe@1c386389f471205ed65a473d4f9bf8e8b86e7c25/dist/aframe-master.min.js) / Oculus Go / Oculus Browser and this is working as expected. The syntax is  `<a-scene renderer="antialias: true">`

**Comment by Mic1974** [comment]
thanks, works perfect. i did use the "old fashioned" syntax before <a-scene antialias="true" ... which doesn't seem to work anymore :-p
