### ISSUE TITLE
Cursor component: events should contain mouse button

### ISSUE THREAD

**Issue by naraesk** [aframevr/aframe#3833]
**Description:**

I've added event listeners for the mousedown/mouseup/mouseenter/mouseleave events of the [cursor component](https://github.com/aframevr/aframe/blob/master/docs/components/cursor.md). The event object contains no information about which button was pressed to trigger this event, i.e. left, right, or middle mouse button. It is possible to get the information from the javascript mouse events and combine that information with the aframe cursor events, but this is needless complicated. It would be much easier if the events from the cursor components would contain an attribute button with value 1, 2, or 3.

- A-Frame Version: 0.8.2
- Platform / Device: Desktop/Chromium
- Reproducible Code Snippet or URL: https://codesandbox.io/s/n035zom4o4

**Comment by gftruj** [comment]
Hi, i've modified [src/components/cursor.js](https://github.com/gftruj/aframe/blob/feat-cursor-button-id/src/components/cursor.js) a bit, using `rayOrigin: mouse` adds the mouse button value to the event detail. 

The changes are within the [update](https://github.com/gftruj/aframe/blob/feat-cursor-button-id/src/components/cursor.js#L78-L83), [onCursorDown](https://github.com/gftruj/aframe/blob/feat-cursor-button-id/src/components/cursor.js#L228-L229), and [onCursorUp](https://github.com/gftruj/aframe/blob/feat-cursor-button-id/src/components/cursor.js#L261-L263) functions, but it seems to be working with `mouseenter` and `mouseleave` events as well.

You can check it out [here](https://jsfiddle.net/rvemwxkz/)

This feature doesn't seem VRy, still if it's worthwhile, I'd gladly make a proper PR.

**Comment by ngokevin** [comment]
If you are making a 2D/mouse-y app, then I think manually listening to mouse clicks, and then grabbing in the handler the cursor.intersectedEl or raycaster.getIntersection is good. Don't need we need to add to cursor.js. Thanks!

**Comment by naraesk** [comment]
@gftruj: Thanks, perfect! Would be glad to see it merged. 

@ngokevin: Not sure I understood. Do you mean to have something like a normal javascript document.onclick eventhandler and from there accessing the cursor.intersectedEl? That doesn't sound very robust. When the cursor moves fast enough cursor.intersectedEl will give me the wrong element or am I missing something?

**Comment by ngokevin** [comment]
Yeah, it's like 3 lines of code. The mouse cursor is mostly for testing purposes for me (especially since mouse drag is the default...it's hard to click stuff). The event detail object is the same case, the same object is reused and overwritten. It's fast enough.

**Comment by gftruj** [comment]
@naraesk  tried doing it Kevins way ([fiddle](https://jsfiddle.net/1aw05y4p/11/), but i keep getting callbacks from the cursor component (as well as the original MouseEvent). It can be easily filtered out, but something seems to be missing there..

**Comment by Hulkmaster** [comment]
> Yeah, it's like 3 lines of code. The mouse cursor is mostly for testing purposes for me (especially since mouse drag is the default...it's hard to click stuff). The event detail object is the same case, the same object is reused and overwritten. It's fast enough.

Could you, please, provide an example?
i also tried cannot achieve that

**Comment by Hulkmaster** [comment]
Actually if someone will try fiddle example - there is one line of code missing

```
    if (!(event instanceof MouseEvent)) {
      return;
    }
```

so basically "click" event triggers two times:
one is aframe CustomEvent (customClick)
and second one is native MouseClick

you should just filter Custom ones

but yes, i would prefer to have clicked mouse button in aframe event

**Comment by diarmidmackenzie** [comment]
It's a shame this suggestion was rejected.  It would be very useful, and while it's true that this can be implemented in an application, it's fiddly to do so, and tedious to have to rework things substantially, just to allow differentiation of different mouse buttons.

Like the other commenters, I'd be happy to create a PR for this if there was an indication it would be accepted.

**Comment by diarmidmackenzie** [comment]
A fix for this issue has now been merged.
https://github.com/aframevr/aframe/pull/5088
