### ISSUE TITLE
Z-flighting question 

### ISSUE THREAD

**Issue by 544531645** [aframevr/aframe#3836]
**Description:**How does a-frama change the value of z-near far in the code?

- A-Frame Version:0.8.0
- Platform / Device:winodws 
- Reproducible Code Snippet or URL:

https://stackoverflow.com/questions/21080619/three-js-webgl-large-spheres-appear-broken-at-intersection/21106656#21106656

**Comment by donmccurdy** [comment]
You've linked to the answer to a question; I'm not sure what this issue means sorry, or if you have a question. As that answer describes, you can change the near/far plane on the `camera` component in A-Frame.

**Comment by dsinni** [comment]
While this is easily searchable in the docs, the question is probably how to do this specifically in A-Frame rather than Three.

https://aframe.io/docs/0.8.0/components/camera.html#properties

https://aframe.io/docs/0.8.0/primitives/a-camera.html#attributes
