### ISSUE TITLE
`animation` `startEvents` not triggering animations in `master`

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#3838]
**Description:**
Using `animation="startEvents: ...;"` doesn't work in `master` (`843a67f`) as it did previously with `0.8.2` and the `aframe-animation-component`. The animation isn't triggered when the event fires.

- A-Frame Version: `master` (`843a67f`)
- Platform / Device: Windows 10 
- Reproducible Code Snippet or URL:
```html
<a-box color="#fff"
       position="0 1 -3"
       animation="property: object3D.position.x; from: 0; to: 10; startEvents: click;">
</a-box>
```

CodePen: https://codepen.io/dansinni/pen/NEKrja

Switching to `0.8.2` with the separate component works as expected.

**Comment by ngokevin** [comment]
Set `.objects` on your raycaster. The box is not set up as a raycast target and perhaps some asynchrony  from using a-box over a-entity. (e.g., `<a-cursor raycaster="objects: a-box">` (mentioned in https://aframe.io/docs/0.8.0/introduction/best-practices.html#performance).

**Comment by dsinni** [comment]
Ah, okay. I knew it was a best practice to set raycaster objects, but I didn't know that it was now mandatory. 

I left it out since the scene was ridiculously basic.

So, that is the case then? It's now mandatory to set raycaster objects?

**Comment by ngokevin** [comment]
It should be. But I'm looking why the raycaster didn't pick it up in the first place, but not problem with animation.

**Comment by ngokevin** [comment]
I have a fix coming to fix raycasters when defaulting to intersecting everything in scene. The wrapper entity threw it off.
