### ISSUE TITLE
VR-mode can't display cursor correctly

### ISSUE THREAD

**Issue by hdtk** [aframevr/aframe#3841]
I found a problem in VR-mode.
When the mode is normal, cursor exist center of the display, where you gaze in.
But the mode is VR, cursor goes somewhere.

If I apply aframe-master.min.js, this doesn't occur.

- A-Frame Version: aframe-master.js
- Platform / Device: Android
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Do you have an example to reproduce? In what headset, device?

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/3820
