### ISSUE TITLE
Some scenes don't load on latest version of Chrome on iOS

### ISSUE THREAD

**Issue by thfranco** [aframevr/aframe#3846]
I have an issue on the latest version of Chrome on iOS where my scenes are all blank. This works fine on Safari.
It seems that the aframe scripts are not even loaded.
This is also reproducible with the aframe samples, but some are still working.

- A-Frame Version: 0.8.2
- Platform / Device: iOS 12.1, iPhone SE, Chrome 70.0.3538.75
- Reproducible URLs: 

https://aframe.glitch.me/ and https://aframe.io/examples/showcase/sky/
Stays blank on chrome, loads on safari

https://aframe.io/examples/showcase/360-image-gallery/
Works on both chrome and safari

Chrome:
![image](https://user-images.githubusercontent.com/1555766/48056104-5f5a1400-e1b1-11e8-92f2-fa3abbeac910.png)

Safari: 
![image](https://user-images.githubusercontent.com/1555766/48056119-66812200-e1b1-11e8-9724-ea59c91965aa.png)

**Comment by dmarcos** [comment]
Is there any way to get console logs? Something has changed on Chrome side but hard to tell with more info.

**Comment by thfranco** [comment]
I debugged on windows with weinre.

I'm not able to see any console logs, like the all the script loadings:
A-Frame Version: 0.8.2
WebVR Polyfill Version: ^0.10.5
..

I successfully saw some logs on some other pages, but not on the pages that were blank. It might be linked to the weinre hook, so I'm not sure if aframe scripts are even loaded or not.
But I definitely didn't succeed to catch any error logs.

**Comment by i3games** [comment]
I can reproduce on an iPad (same versions as above). A workaround is to "Request Desktop Site" - displays both scenes correctly.

**Comment by thfranco** [comment]
Thanks for the tip, requesting desktop site is indeed displaying correctly, but it loses all the device motion events.
The scene won't move with phone orientation, and if I try to go to VR mode it just freezes the page.

But this is a good start to investigate, I tried to play with the user agent but didn't succeed to get motion events working.

**Comment by dmarcos** [comment]
Just fixed on master.
