### ISSUE TITLE
A-Frame inspector not working

### ISSUE THREAD

**Issue by fcor** [aframevr/aframe#3857]
I'm trying to run A-Frame's Inspector but apparently it's not working. 

I wasn't able to open it. Just tried on some demo scenes that I have and on some examples available online, like KFrame ones and `<ctrl> + <alt> + i` isn't working.

- A-Frame Version: Tested on 0.7.1 and 0.8.2 
- Platform / Device: Desktop

**Comment by dmarcos** [comment]
Can you point to a specific URL? Any errors in console?

A-Frame examples work fine for me: https://aframe.io/aframe/examples/

**Comment by fcor** [comment]
There is something weird happening on my keyboard apparently. I'm closing this issue.
