### ISSUE TITLE
`Enter VR` not working in Android browsers

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#3869]
**Description:**

Clicking the VR goggles icon doesn't enter VR in Android browsers; it instead raises the camera or rig height to an undesirable position without leaving magic window mode.

- A-Frame Version: `master` `826e983d989312fe7cd75b9cc92e58b7a5cc195f`
- Platform / Device: Android (possibly other platforms) / Firefox, Chrome, Samsung Internet, Edge...
- Reproducible Code Snippet or URL: https://bunker-bake.glitch.me

**Comment by dmarcos** [comment]
https://github.com/aframevr/aframe/pull/3870 will fix it.

**Comment by dmarcos** [comment]
Fixed on master. Can reopen if the issue is not fixed.

**Comment by dsinni** [comment]
Great! Thanks, @dmarcos. So far, so good.
