### ISSUE TITLE
`gltf`/`glb` models not loading in Microsoft Edge

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#3871]
**Description:**

`gltf` and `glb` models don't appear to be loading in Microsoft Edge on Windows, using the current A-Frame `master` branch.

Console says:
```js
 components:gltf-model:warn 'TextDecoder' is not defined 
```

and/or:

```js
[object Error]: {description: "'TextDecoder' is not defined", message: "'TextDecoder' is not defined", number: -2146823279, stack: "ReferenceError: 'TextDecoder' is not defined at THREE.LoaderUtils.decodeText (https://unpkg.com/aframe-extras@4.2.0/dist/aframe-extras.min.js:1:1300) at GLTFLoader.prototype.parse (https://cdn.jsdelivr.net/gh/aframevr/aframe@826e983d989312fe7cd75b9cc92e58b7a5cc195f/dist/aframe-master.js:56338:5) at Anonymous function (https://cdn.jsdelivr.net/gh/aframevr/aframe@826e983d989312fe7cd75b9cc92e58b7a5cc195f/dist/aframe-master.js:56286:6) at Anonymous function (https://cdn.jsdelivr.net/gh/aframevr/aframe@826e983d989312fe7cd75b9cc92e58b7a5cc195f/dist/aframe-master.js:36129:20)"}
description: "'TextDecoder' is not defined"
message: "'TextDecoder' is not defined"
number: -2146823279
stack: "ReferenceError: 'TextDecoder' is not defined at THREE.LoaderUtils.decodeText (https://unpkg.com/aframe-extras@4.2.0/dist/aframe-extras.min.js:1:1300) at GLTFLoader.prototype.parse (https://cdn.jsdelivr.net/gh/aframevr/aframe@826e983d989312fe7cd75b9cc92e58b7a5cc195f/dist/aframe-master.js:56338:5) at Anonymous function (https://cdn.jsdelivr.net/gh/aframevr/aframe@826e983d989312fe7cd75b9cc92e58b7a5cc195f/dist/aframe-master.js:56286:6) at Anonymous function (https://cdn.jsdelivr.net/gh/aframevr/aframe@826e983d989312fe7cd75b9cc92e58b7a5cc195f/dist/aframe-master.js:36129:20)"

__proto__: Object
```

- A-Frame Version: `master` `35384188aeac514aa23891f0daa8b5c9f7e4abfc`
- Platform / Device: Microsoft Edge / Windows 10
- Reproducible Code Snippet or URL: https://bunker-bake.glitch.me

**Comment by donmccurdy** [comment]
The quick fix is including a TextDecoder polyfill, like https://github.com/samthor/fast-text-encoding. 

But I'm not sure why that's necessary, so, could you try adding this tag to the page, and see if anything changes?

```html
<meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
```

**Comment by dsinni** [comment]
Please excuse the delayed response here, but adding the `fast-text-encoding` polyfill did work in Edge:
```
<script src="https://cdn.jsdelivr.net/npm/fast-text-encoding@1.0.0/text.min.js"></script>
```
That said, should A-Frame not work in Edge out of the box? Should the polyfill be included in core?

**Comment by donmccurdy** [comment]
I'm still not sure why the polyfill is even necessary... the relevant code in threejs is careful to check when it's available, and use a fallback:

https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/src/loaders/LoaderUtils.js#L9-L28

Perhaps that check is being stripped in minification somewhere?

**Comment by dmarcos** [comment]
IE 11 / Edge is working on master and GLTF models included in the examples work for me (anime-UI, shopping). The provided glitch link doesn't work for me on any browser.

**Comment by dsinni** [comment]
@dmarcos Hm, that's really odd because it's working for me in Firefox and Chrome, but not in Edge. I'm on Windows 10.

Note that there are 2 links, which are very similar:

- https://bunker-bake.glitch.me
- https://bunker-baked.glitch.me

The latter one should be working in Firefox and Chrome (at least I hope, as they are for me).

**Comment by dsinni** [comment]
Update: I updated A-Frame in the https://bunker-baked.glitch.me/ demo to the latest `master` build: `A-Frame Version: 0.8.2 (Date 2019-02-04, Commit #2c3ad68)`

The issue still persists in Edge for me. All other browsers tested work as expected.

**Comment by dsinni** [comment]
Congrats on the `0.9.0` release! Thanks for all the great work you guys have been doing.

Just wanted to let you know that this issue is still persisting in `0.9.0`.

I tried another `glb` model entirely, and I'm receiving the following error in Edge:

```js
2 %ccomponents:gltf-model:warn %c'TextDecoder' is not defined%c  color: orange color: inherit color: orange
```

**Comment by donmccurdy** [comment]
This was a bug in A-Frame Extras - the `fbx-model` component included a shim for older versions of three.js that broke something on Edge. If you update Extras to v5.1.0, Microsoft Edge will work correctly.

**Comment by dsinni** [comment]
Aha! That did it. Thanks, @donmccurdy!
