### ISSUE TITLE
mouse cursor not working, when a raycaster has its `showLine: true`

### ISSUE THREAD

**Issue by gftruj** [aframevr/aframe#3878]
**Description:**
having a `cursor='rayOrigin: mouse`  the mouse `click` event is not emitted if there is an entity with a `raycaster: showLine: true`. Setting `showLine` to false 'solves' the issue.
 
In the fiddle, the raycaster is attached to an entity in the camera, but you can throw it anywhere.

Its not happening with a `fuse` based cursor ([fiddle](https://jsfiddle.net/dm6Lk40g/8/))
- A-Frame Version: 0.8.2
- Platform / Device: PC
- Reproducible Code Snippet or URL:
https://jsfiddle.net/dm6Lk40g/6/

https://stackoverflow.com/questions/53447669/registered-component-click-event-in-aframe-version-0-8-2-and-master-isnt-workin?noredirect=1#comment93770346_53447669

**Comment by gftruj** [comment]
The cursor is working, when [this line](https://github.com/aframevr/aframe/blob/v0.8.0/src/core/a-entity.js#L173) is suppresed for a 'line' type. Actually the `line` component causes the issue, the `showLine` only creates one. 

fiddle [here](https://jsfiddle.net/dm6Lk40g/10/).

**Comment by dmarcos** [comment]
Thanks. I'll close and we can reopen if needed.
