### ISSUE TITLE
stop using document.registerElememt?

### ISSUE THREAD

**Issue by greggman** [aframevr/aframe#3880]
Chrome prints this message in the JS console

<img width="468" alt="screen shot 2018-11-27 at 15 45 40" src="https://user-images.githubusercontent.com/234804/49063770-c1abaf00-f25b-11e8-8ff1-62b8600ba7f5.png">

- A-Frame Version: 0.8.2
- Platform / Device: N/A
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

**Comment by dmarcos** [comment]
That’s an innocous message. native document.registerElelement will be deprecated but A-Frame functionality won’t be affected. We polyfill via Mutation Observers.

**Comment by arpu** [comment]
hmm looks like the message comes from here 
https://github.com/aframevr/aframe/blob/9a778cc499e4e7c509b3ff80abb8aa8e1267d8f4/src/core/a-register-element.js#L69

**Comment by dmarcos** [comment]
A-Frame uses the custom elements API v0 (document.registerElement) that will be deprecated next year in favor of V1. A-Frame has a polyfill for V0, the deprecation won’t affect any functionality. You can safely ignore that warning message.

**Comment by justinfagnani** [comment]
What's the plan to use the Custom Elements implementation that ships in Chrome, Safari and Firefox?
