### ISSUE TITLE
Some colors are incorrectly rendered

### ISSUE THREAD

**Issue by florentpeyrard** [aframevr/aframe#3882]
Aframe 0.8.2
Example : for instance in a-circle, #CC6600 is rendered yellow instead of orange. Both Firefox and Chrome. Also applies to aframe-environment-component.

**Comment by dmarcos** [comment]
Try with [flat shader](
https://aframe.io/docs/0.8.0/components/material.html#flat)

In general color depend on the shader, ilumination, angle of the surface with respect to lights. A color won’t yield the same consistent hue as you see in the 2D Web.

**Comment by donmccurdy** [comment]
Are you using the setting `renderer="gammaOutput: true"` by any chance? There are particular considerations for colors, if so, which I can explain further. We're working on improving that particular case, see https://github.com/aframevr/aframe/issues/3509.

**Comment by florentpeyrard** [comment]
Not using `gammaOutput : true`, but flat shader solved my issue, thanks, except regarding aframe-environment-component, so I opened https://github.com/feiss/aframe-environment-component/issues/56
