### ISSUE TITLE
exit vr while mobile rotating keep scene rotating around z axies

### ISSUE THREAD

**Issue by EslamNemr** [aframevr/aframe#3884]
![5](https://user-images.githubusercontent.com/42042051/49129645-00884600-f2ea-11e8-84e7-8de9e92dd8b2.jpeg)

if i exit vr while mobile rotating the scene back rotating around z axis and not back to initial angle
i think the problem from look controls.

**Comment by dmarcos** [comment]
What phone, browser? Can you provide link to example to reproduce?

**Comment by EslamNemr** [comment]
my glitch not working the code but https://glitch.com/edit/#!/join/187b6783-9ddc-4f98-8ef3-860cd0868e13
and for live http://www.eskanengineering.ae/VR/VR.html  
for live using last master
windows 10
browser chrome70.035
firefox 63.0.3
ie edge

and for mobile
iphone 7
ios 12 
safari and chrome

androied 5.1.1
firefox and chrome

**Comment by EslamNemr** [comment]
for phone ios
chrome version 70.0.3538.75
safari 12.1

androied
chrome 70.0.3538.110
firefox
63.0.2

**Comment by dmarcos** [comment]
Glitch provided uses 0.8.0 and link times out on asset loading. I cannot reproduce described problem in [current master](https://cdn.jsdelivr.net/gh/aframevr/aframe@17c6cd22faca18938dcfcfaf8ae0b4c24edcac34/dist/aframe-master.min.js)

**Comment by dmarcos** [comment]
Closing due to missing link to reproduce the issue. Can reopen if new info become available.
