### ISSUE TITLE
laser controls stop working when passed to new parent entity

### ISSUE THREAD

**Issue by jaronimoe** [aframevr/aframe#3885]
**Description:**
I have a scene with two cameras between which the user can switch.
the camera is contained within a "rig" entity that also houses a laser controller.
when I switch cameras, I want to pass the laser to the other rig with 
`rig.appendChild(laser)`
unfortunately, the laser controls don't work after appending them to the new rig.
however, they do work after I enter inspector mode and exit it again.

is this a bug or am I doing something wrong?
in either case, does someone have a suggestion how I properly could move the laser to the other parent?

- A-Frame Version: 0.8.2
- Platform / Device: firefox / htc vive
- Reproducible Code Snippet or URL:
https://glitch.com/edit/#!/economic-heart
(you will need a vive controller to test the demo. upon clicking with the mouse, the laser is set to a new parent)

**Comment by dmarcos** [comment]
Better to have a single camera, rig and laser controls. Moving the rig will have the same effect as switching cameras. Would that work?

**Comment by jaronimoe** [comment]
for now that would indeed work.
however, in the long run I would like to extract information from the respective other camera's view frustum (e.g., which objects are currently visible from the other perspective).

but now that I think about it I could have also a dedicated "laserless" camera and another one that keeps the laser and just switch the parameters when switching between cameras. I will give that a try, thanks!

**Comment by dmarcos** [comment]
Thanks for filing. I’m closing for now and can reopen if necessary.

**Comment by jaronimoe** [comment]
I wanted to implement that now, but actually my cameras are in different levels of the scene hierarchy.
from the "outer" camera I can rotate the scene.
the "inner" camera is supposed to be rotated together with the scene when I rotate the scene from the "outer" perspective - so I still need to change the parent (this time of the rig, not of the laser).

I guess, a workaround would be to have the laser without a parent and adjust its position according to which camera it is supposed to be attached to currently?
