### ISSUE TITLE
Update inspector with 0.9.0

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#3888]
Not exactly sure how inspector releases are managed, but there are some inspector bug fixes on the master branch that would be great to have available with 0.9.0 if possible. See https://github.com/aframevr/aframe-inspector/issues/559.

**Comment by dmarcos** [comment]
Yep, we usually cut an inspector build from master to go with the A-Frame release. @donmccurdy Have you been testing the inspector master? Are there any outstanding bugs we should be looking for in 0.9.0?

**Comment by ngokevin** [comment]
Yeah, we always cut a release. I've been releasing/publishing Inspector fixes as I make them (missed the glTFExporter changes, but not critical). Been actively developing master against master so it's good.
