### ISSUE TITLE
Vive scene Crash when raycast a GLTF model

### ISSUE THREAD

**Issue by jrivasg** [aframevr/aframe#3890]
**Description:**

- A-Frame Version: 0.8.2
- Platform / Device: HTC Vive
- Reproducible Code Snippet or URL:

I have this issue and is not working with the solutions from #2980, #3067, #3259 nor #3358 

It is not a problem of synchronization, as we see in the console log the "object 2" is the model gltf, and when there is an intereseccion with the model we obtain the face and the position of the point, but still the scene in the htc live crash

![crash gif](https://user-images.githubusercontent.com/5821130/49446715-1d82b480-f7d5-11e8-8899-08884003a757.gif)

![console log](https://user-images.githubusercontent.com/5821130/49446320-376fc780-f7d4-11e8-87db-484045d65cae.PNG)
 
This is the code:

```
<html>
<head>
    <title>Visor Biomodelos</title>
    <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
</head>
<body>
    <script>
        var raycaster;
        AFRAME.registerComponent('refresh-objects', {
            init: function () {
                var el = this.el;
                el.addEventListener("model-loaded", function () {
                    // Refreshing raycaster's objects on model loaded 
                    raycaster = document.querySelector('[raycaster]').components.raycaster
                    raycaster.refreshObjects();
                    console.log(raycaster.objects)
                    el.addEventListener('mouseenter', function (evt) {
                        console.log(evt.detail.intersection);
                    });
                });
            }
        });
    </script>
    <a-scene>
        <a-assets>            
            <a-asset-item id="corz" src="corazon.gltf"></a-asset-item>            
        </a-assets>
        <!-- Vive controllers -->
        <a-entity id="rightCtrl" laser-controls="hand: right" raycaster="showLine: true; far: 100" line="color: orange; opacity: 0.5"></a-entity>
        <!-- gltf model -->
        <a-gltf-model src="#corz" scale="0.01 0.01 0.01" position="-0.5 1 -1.3" refresh-objects></a-gltf-model>        
    </a-scene>
</body>
</html>
```

Thanks you for your responses

**Comment by ngokevin** [comment]
Is there an error message?

**Comment by jrivasg** [comment]
> Is there an error message?

Nothing, all the console log is that you can see. The browser window don't crash only go slower, but without error message.

**Comment by donmccurdy** [comment]
How large is the model? Note that raycasting is synchronous, and could block rendering for a while. If you don't need to raycast against the full-res model, you can use an invisible sphere or box around it instead.

**Comment by jrivasg** [comment]
> How large is the model? Note that raycasting is synchronous, and could block rendering for a while. If you don't need to raycast against the full-res model, you can use an invisible sphere or box around it instead.

The model is large, the .gltf file weighs 11mb. I'm trying to build a surgical simulator, so I have to be able to select faces and transform the mesh. I think that with the solution of the box or the sphere around it would be impossible, or am I wrong?

Thanks

**Comment by donmccurdy** [comment]
> I think that with the solution of the box or the sphere around it would be impossible, or am I wrong?

Hm, yeah that's true. Alternatives would be to divide the model into parts (so that raycasting will only use the bounding box for most of the parts) or to do raycasting in a Web Worker (which would take some custom JS work to do).

**Comment by donmccurdy** [comment]
But it's also possible the issue is something else... are you able to share a demo?

**Comment by jrivasg** [comment]
> Hm, yeah that's true. Alternatives would be to divide the model into parts (so that raycasting will only use the bounding box for most of the parts) or to do raycasting in a Web Worker (which would take some custom JS work to do).

Would there be any ways to do asynchronous raycasting, get the desired faces and then transform the mesh, without having to continuously render?



> But it's also possible the issue is something else... are you able to share a demo?

I'm going to try to set up a demo page.

**Comment by donmccurdy** [comment]
> Would there be any ways to do asynchronous raycasting, get the desired faces and then transform the mesh, without having to continuously render?

You have to continuously render in VR no matter what, but raycasting doesn't necessarily need to be continuous.  However, A-Frame doesn't provide non-render-blocking raycasting for large models for you, you'd need to get into writing code using [THREE.Raycaster](https://threejs.org/docs/#api/en/core/Raycaster) directly and create a component to do that.

**Comment by ngokevin** [comment]
I think you'd need to use octree collision (e.g., https://github.com/collinhover/threeoctree), split up your model, raycaster selectively based on bounding box collision, or yeah you'd need to pull a bunch of three.js code into a separate worker script.
