### ISSUE TITLE
Need options for browsers which don't support A-Frame. Or documentation stating how to add support.

### ISSUE THREAD

**Issue by erikwoods** [aframevr/aframe#3903]
**Description:**
[Based on A-Frame documentation I see](https://aframe.io/docs/0.8.0/introduction/vr-headsets-and-webvr-browsers.html#which-browsers-does-a-frame-support), I should expect that my basic "flat" scene will work in IE 11 (maybe even 10 and 9?).
```
For flat or plain 3D support, A-Frame supports all modern browsers, specifically those that support WebGL including...
```

And if not, I should have the ability to do something for these users. Whether it's a re-direct, or a message asking the user to upgrade/install another browser, or something along those lines. It's not clear to me today how to accomplish either of these things.

- A-Frame Version: 0.8.2
- Platform / Device: IE / Desktop
- Reproducible Code Snippet or URL: [See it on Glitch](https://spot-vise.glitch.me/)

If you load up my little test page in IE, you'll see that it simply shows nothing on the page. With no console errors, either.

![screen shot 2018-12-28 at 12 09 47 pm](https://user-images.githubusercontent.com/689000/50525372-0b7cf480-0aa9-11e9-9de8-a09f6e4552fa.png)

**Comment by dmarcos** [comment]
The above is a syntax error. Maybe one modern JS feature we use that is not supported in IE11?

**Comment by erikwoods** [comment]
Yeah, sure seems like it. Any ideas on what can be done for a fix? Or even a temporary fix?

**Comment by dmarcos** [comment]
I don't see that error in regular A-Frame examples: https://aframe.io/aframe/examples/showcase/anime-UI/

I see the lack of Promise support. A polyfill is needed.

FWIW, you are using an old aframe (0.8.0). Update to 0.8.2

**Comment by erikwoods** [comment]
Huh. Would ya look at that. I am at a loss for words. You're right about everything, and IDK how I got where I did. But it would seem simply using a polyfill for Promise does the trick.

PS, I updated my example to reflect the changes made in my test.

It seems like you could close this issue. I think.

**Comment by dmarcos** [comment]
There might be other road blocks after. A Promise polyfill would be the first thing and then see.

**Comment by erikwoods** [comment]
Yeah I've since realized that. Need a polyfill for customevents and maybe requestAnimationFrame....?
Either way, the a-frame docs don't seem to be accurate. To me, the docs imply that flat scenes work out of the box.

I'll update the docs if I figure it out. Or if we figure it out. I have no problem doing that. :)

**Comment by erikwoods** [comment]
Time for a new test.

I've got a simple scene with a spinning cube. [Hosted on Glitch.](https://spot-vise.glitch.me/)
I am not receiving any errors in the console in IE, but it's also not loading the scene. Or the asset. I'm really not sure.

I'm using polyfills for Promise, customEvents, and requestAnimationFrame.

Here's the console:
![screen shot 2018-12-28 at 12 09 47 pm](https://user-images.githubusercontent.com/689000/50525372-0b7cf480-0aa9-11e9-9de8-a09f6e4552fa.png)

**Comment by dsinni** [comment]
Some of this may be related to https://github.com/aframevr/aframe/issues/3871, which also affects Microsoft Edge.

**Comment by dsinni** [comment]
@erikwoods Try adding this script:
```
<script src="https://cdn.jsdelivr.net/npm/fast-text-encoding@1.0.0/text.min.js"></script>
```

**Comment by dmarcos** [comment]
FWIW, A-Frame 0.8.2 examples work for me on Edge (https://aframe.io/aframe/examples) @dsini In what scenarion do you need the `fast-text-encoding` polyfill?

**Comment by dsinni** [comment]
@dmarcos I believe it's when a `gltf/glb` model is used. @erikwoods' Glitch example above was a good reproduction of it, and was resolved by adding the polyfill.

**Comment by dsinni** [comment]
@dmarcos It would throw the error below:

``` js
components:gltf-model:warn 'TextDecoder' is undefined
```

**Comment by erikwoods** [comment]
@dmarcos thanks so much for adding support! Wooooo!
