### ISSUE TITLE
Failure loading node (vanilla)

### ISSUE THREAD

**Issue by beyerz** [aframevr/aframe#3920]
**Description:**

- A-Frame Version: 0.8.2 (Date 2018-12-01, Commit #a35c367)
- Platform / Device: OSX/Chrome
- Reproducible Code Snippet or URL:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sample Component</title>
    <script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@00d0a6502df911702bfeab8d7a23b6b848ba4eb9/dist/aframe-master.min.js"></script>
</head>
<body>
    <a-scene></a-scene>
</body>
</html>
```

Just loading the latest version, throws a console error.
```javascript
core:a-node:error Failure loading node:   TypeError: Cannot read property 'constructor' of undefined
    at extendProperties (component.js:671)
    at i.callUpdateHandler (component.js:389)
    at i.updateProperties (component.js:276)
    at HTMLElement.value (a-entity.js:478)
    at HTMLElement.value (a-entity.js:444)
    at a-entity.js:247
    at a-node.js:127
```

**Comment by dmarcos** [comment]
This is due to the line below (no time time investigate further): 

https://github.com/aframevr/aframe/blob/master/src/systems/camera.js#L124

load method on the default camera entity is invoked twice: normal one and the one forced by the camera system. That messes with component initialization.

**Comment by tsgouros** [comment]
Could my problem be related to this bug? Stack traces are almost identical.

https://stackoverflow.com/questions/59792018/a-node-js-typeerror-cannot-read-property-constructor-of-undefined
