### ISSUE TITLE
document.registerElement is deprecated

### ISSUE THREAD

**Issue by Hulkmaster** [aframevr/aframe#3923]
- A-Frame Version: 0.8.2 (Date 2018-04-15, Commit #b20527f)
- Platform / Device: Version 71.0.3578.98 (Official Build) (64-bit)

When i use aframe in chrome i get warning

```
document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
```

**Comment by dmarcos** [comment]
It’s ok. We will eventually move to the new custom elements API but we have a polyfill / fallback at the moment on top of Mutation Observers. A-Frame won’t break.

**Comment by byjoohyunpark** [comment]
I went into the same issue. When would the new custom API be released?
