### ISSUE TITLE
Font artifacts appearing in `text` component 

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#3924]
**Description:**

I'm not sure if this can be helped, but I noticed that artifacts are appearing in the letters of the `text` component, even when using the default font.

![image](https://user-images.githubusercontent.com/4733018/50109221-2926a000-0205-11e9-9a6e-f09f317cb642.png)

- A-Frame Version: `0.8.2` / `master`
- Platform / Device: All
- Reproducible Code Snippet or URL: https://text-artifacts-issue.glitch.me/

**Comment by ngokevin** [comment]
I think I'm gonna chalk it up to an issue with the font glyphs. I don't think it's too noticeable unless you get really close. If it's a widespread issue thru all fonts, please reopen!
