### ISSUE TITLE
fov is always 80 in vr-mode (bug? by design?)

### ISSUE THREAD

**Issue by eladrkatz** [aframevr/aframe#3925]
I set the camera fov to be 120. 
It shows correctly in normal mode but when I switch to vr-mode in mobile phone - it shows the scene with 80 fov.

- A-Frame Version: 0.8.2
- Platform / Device: android / chrome
- Reproducible Code Snippet or URL: 

https://glitch.com/edit/#!/skillful-popcorn?path=index.html:1:0

```
      <a-camera fov="120"></a-camera>
```

**Comment by dmarcos** [comment]
Answered on StackOverflow: https://stackoverflow.com/questions/53870608/setting-fov-120-in-aframe-doesnt-work-in-vr-mode
