### ISSUE TITLE
Image Gallery fails to load buttons / Not functional on any android device

### ISSUE THREAD

**Issue by honestly-funny** [aframevr/aframe#3926]
**Description:**

The buttons to move to different scenes have disappeared. (Note these have only disappeared on desktop but not on mobile devices). 

Furthermore, the gyroscope has super-high sensitivity on all android machines. Therefore, this is basically not compatible with all android devices. 

- A-Frame Version: 0.8.2
- Platform / Device: Desktop / Android Machines
- Reproducible Code Snippet or URL: https://aframe-gallery.glitch.me/

**Comment by dmarcos** [comment]
That link you shared is using A-Frame 0.5.0. The issues you described should be fixed in 0.8.2. Examples using 0.8.2: https://aframe.io/aframe/examples/
