### ISSUE TITLE
tigger animation startEvents error

### ISSUE THREAD

**Issue by 759325100** [aframevr/aframe#3935]
**Description:**

- A-Frame Version:0.8.2
- Platform / Device:PC
- Reproducible Code Snippet or URL:

a-sky add animation. i want tigger startevents , but failed.
i use vue framework
code is:
```
<a-sky src="#sky" id="sky"
             animation="property: object3D.rotation.y; startEvents:start; pauseEvents:stop; from: 0; to: 360; dur: 40000; loop: true; easing: linear">
</a-sky>

vue:
mounted(){
  var el = window.document.querySelector("#sky");
  el.emit('start');  // not working,animaton not running,console error:window.document.querySelector(...).emit is not a function
}
```

**Comment by 759325100** [comment]
codepen url: https://codepen.io/waroom/pen/KbQmVQ?editors=1111
codepen not support v0.8.2. so i using v0.7.1

**Comment by 759325100** [comment]
is my wrong

**Comment by GoldenPunk** [comment]
Did you figure it out? I am having the same problem with version 1.04.
