### ISSUE TITLE
mobile enable touch look-controls

### ISSUE THREAD

**Issue by 759325100** [aframevr/aframe#3937]
**Description:**

- A-Frame Version:0.8.2
- Platform / Device:IOS Mobile
- Reproducible Code Snippet or URL:not

How to disable the gyroscope on the phone and enable touch control. The default is to use a gyroscope, and you can't use the touch to control the top and bottom view.

**Comment by dmarcos** [comment]
Up and down touch controls is a deliberate decission to avoid real and virtual horizon disallignments that can be confusing. You can copy [look-controls](https://github.com/aframevr/aframe/blob/master/src/components/look-controls.js) and derive your own compinent `my-look-controls` with the behavior you want
