### ISSUE TITLE
Feature: Wedge

### ISSUE THREAD

**Issue by LukeTOBrien** [aframevr/aframe#3939]
Hello there,

I am interested in doing a scene with a ramp similar to the one in `a-frame extras` but looking at the [source code](https://github.com/donmccurdy/aframe-extras/blob/master/examples/playground/index.html) it is not a wedge shape but actually a rotated cube (box).

``` HTML
      <!-- Ramp -->
      <a-box id="ramp"
             color="#39BB82"
             width="1" height="10" depth="18.86796"
             position="0 -4.04 -6.33"
             rotation="30 0 0"
static-body></a-box>
```

In my project I am mapping 2D `SVG` shapes to `A-Frame`, so I can work out the coordinates, but not so easily the rotation needed to create a wedge shape.

I have tried using the [faceset-component](https://www.npmjs.com/package/aframe-faceset-component) for complex shapes in the past. However my project is automated and I still need to work on it more.

Would a wedge shape be easy to create?  
Could something like the faceset component be officially included in A-Frame in the future?

Thanks

**Edit:** [Wedge on Wikipedia](https://en.wikipedia.org/wiki/Wedge_(geometry))

**Comment by wmurphyrd** [comment]
You can create some tyoea of wedges with the cylinder geometry by altering the segmentsRadial and/or thetaStart and thetaLength properties. 

https://aframe.io/docs/0.8.0/components/geometry.html#cylinder

https://threejs.org/docs/#api/en/geometries/CylinderGeometry

**Comment by dmarcos** [comment]
Thanks for filing and the info. This is a feature more appropriate for a 3rd party component.

**Comment by LukeTOBrien** [comment]
Thanks you.

But I don't think that is the same thing as a wedge, as in defined in the
Wikipedia article.
I would like to request that this issue be be put on the backlog or
archived for a future release?

After-all I noticed you added the [`a-triangle`](
https://github.com/aframevr/aframe/issues/2535) despite there being ways to
do triangles "using the existing geometry and reducing the segment",
messing around with a cylinder and it's theta is not as straight forward
(or obvious) as `a-wedge`. - I think it would also make a nice little
addition.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
