### ISSUE TITLE
WebVR perf regression in Firefox 64 / 65

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#3941]
Filed as a reference. It hast to be fixed on Firefox / Gecko side:

https://bugzilla.mozilla.org/show_bug.cgi?id=1514417

**Comment by esaruoho** [comment]
thanks, looking forward to seeing what happens with this :)

**Comment by ngokevin** [comment]
resolved https://bugzilla.mozilla.org/show_bug.cgi?id=1514417

**Comment by dmarcos** [comment]
Reopening to keep it as a reference until the fix makes it to the different Firefox channels.

**Comment by arpu** [comment]
looks like it fixed in firefox beta 66b6 https://hg.mozilla.org/releases/mozilla-beta
