### ISSUE TITLE
Oculus Go pixel size is too large in VR mode

### ISSUE THREAD

**Issue by tlaukkan** [aframevr/aframe#3942]
A-Frame has larger pixels in VR mode than that of native resolution i.e. is the pixels are at least 3-4 times too big.

- A-Frame Version: aframe@cb4de2e19 (Latest master at time of reporting)
- Platform / Device: Oculus Go
- Reproducible Code Snippet or URL: Any scene viewed with Oculus Go

A-Frame master based scenes and examples at A-Frame site run with too large pixel size in all Oculus Go browsers:
* https://aframe.io/aframe/examples/boilerplate/hello-world/

Three.js examples run with correct resolution with Oculus Browser (did not test other browsers.):
* https://threejs.org/examples/#webvr_ballshooter

This could possibly be some problem with setting the canvas width/height when initializing VR mode.
Setting to scene renderer maxCanvasWidth and maxCanvasHeight to -1 does not have effect. Setting antialiasing to true alleviates the problem somewhat but the jagged edges and large pixels are still clearly visible.

I could tweak the display settings in firefox reality to get the content look quite ok when looked in normal browser mode but when entering VR mode the situation remains the same i.e. too large pixel size.

It looks like this was earlier reported but closed after reporter was happy after setting antialiasing=true which does address the root cause of pixel size:

https://github.com/aframevr/aframe/issues/3571

**Comment by dmarcos** [comment]
I have no Oculus Go to test at the moment. Is there a way to retrieve the canvas size when in VR mode?

**Comment by tlaukkan** [comment]
I am not sure. I could checkout master, add some debug log output and use firefox reality remote debugging which I hope gives access to console log.

**Comment by tlaukkan** [comment]
Evaluated in Oculus Go / Oculus Browse console using chrome remote debugging as requested by @dmarcos 
AFRAME.scenes[0].renderer.getSize();
>  {width: 2048, height: 1024}

Native resolution of Oculus Go is: 2560 x 1440

This image illustrates how the pixels look in VR mode all though its screen captured in normal browser mode (the pixel size is similar):
![image](https://user-images.githubusercontent.com/232774/50953076-fba6dc80-14ba-11e9-8456-b77edaf01bdc.png)

**Comment by tlaukkan** [comment]
Commenting out of this code did not have effect on the pixel size:
https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L514-L541

**Comment by dmarcos** [comment]
Thanks for investigating @IvoJager

**Comment by dmarcos** [comment]
@tlaukkan Can you confirm if antialias is working for you?

**Comment by tlaukkan** [comment]
I have that on but it only alleviates the problem as it hides some of the pixelation. However the pixel size is still too large.

**Comment by arpu** [comment]
looks like aframe should use the meta data like the model-viewer do it ? 
https://github.com/GoogleWebComponents/model-viewer/blob/master/src/utils.js#L114

setting it here https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L581

**Comment by IvoJager** [comment]
I can confirm that, on Oculus Go, turning anti-aliasing off results in much chunkier rendering of the outline of geometry than might reasonably be expected. Yet textures remain smooth.

I'm not sure if related, but text - regardless of anti-aliasing on/off - turns into a shimmering mess quite quickly at a distance (the same scene and text looks buttery smooth on a WMR headset).

Similarly a forced non-power-of-two texture exhibits the same sort of shimmering that I cannot replicate on other devices/headsets.

I'm not sure if it's the capabilities of the hardware either; I have a Mi5 here with the same SoC and it renders everything just brilliantly w/AFrame.

**Comment by IvoJager** [comment]
It's not _supposed_ to, no :) However I think what you and I are seeing in our Oculus Go units, is that without anti-aliasing pixel size seems to be much bigger than AA can account for. Correct me if I'm wrong?

**Comment by tlaukkan** [comment]
Please compare:
https://aframe.io/aframe/examples/boilerplate/hello-world/
https://threejs.org/examples/#webvr_ballshooter

If you observe closely you see that the pixels are larger in aframe. The threejs example has antialias on but I at least do still see the individual pixels and their size when antialias on. That is why you can't now run aframe without antialias on Oculus Go and even with antialias the picture quality varies from mediocre to bad depending on how much high contrast edges you have in the scene.

@dmarcos @ngokevin

**Comment by tlaukkan** [comment]
> It's not _supposed_ to, no :) However I think what you and I are seeing in our Oculus Go units, is that without anti-aliasing pixel size seems to be much bigger than AA can account for. Correct me if I'm wrong?

I think the pixel size does not change with the antialiasing on oculus go. The too large pixels are more obvious when antialiasing is not on.

**Comment by arpu** [comment]
@tlaukkan  do you find a solution  for the wrong  resolution size?

**Comment by arpu** [comment]
@ngokevin why is this closed? 

i get 

```
isvr-scene.js?bc25:16 enter-vr component
(anonymous) @ isvr-scene.js?bc25:16
emit @ aframe-master.js?b048:21904
enterVRSuccess @ aframe-master.js?b048:23324
Promise.then (async)
enterVR @ aframe-master.js?b048:23312
onEnterVRButtonClick @ aframe-master.js?b048:17892
bound @ aframe-master.js?b048:27452
(anonymous) @ aframe-master.js?b048:17982
aframe-master.js?b048:52851 WebGLRenderer: .getsize() now requires a Vector2 as an argument
WebGLRenderer.getSize @ aframe-master.js?b048:52851
(anonymous) @ isvr-scene.js?bc25:19
emit @ aframe-master.js?b048:21904
enterVRSuccess @ aframe-master.js?b048:23324
Promise.then (async)
enterVR @ aframe-master.js?b048:23312
onEnterVRButtonClick @ aframe-master.js?b048:17892
bound @ aframe-master.js?b048:27452
(anonymous) @ aframe-master.js?b048:17982
isvr-scene.js?bc25:19 Vector2 {x: 600, y: 450}```

**Comment by arpu** [comment]
looks like the canvas size should set from VRDisplay 
https://developer.oculus.com/documentation/oculus-browser/latest/concepts/browser-webvr-api/

```
   vrDisplay = displays[0];

      // We must adjust the canvas (our VRLayer source) to match the VRDisplay
      var leftEye = vrDisplay.getEyeParameters("left");
      var rightEye = vrDisplay.getEyeParameters("right");

      // update canvas width and height based on the eye parameters.
      // For simplicity we will render each eye at the same resolution
      layerSource.width = Math.max(leftEye.renderWidth, rightEye.renderWidth) * 2;
      layerSource.height = Math.max(leftEye.renderHeight, rightEye.renderHeight);

```

**Comment by dmarcos** [comment]
I don’t have any issues on Go. How does the problem manifest? There’s nothing special in the VR path of the Go with respect to other devices and browsers

**Comment by arpu** [comment]
for me it loos like the resolution looks not that nice as should be

**Comment by arpu** [comment]
have done more debugging on this
the render for vr is set in the WebVrManager 
THREEonVRDisplayPresentChange isPresenting:1024 1024   ->
the renderer on the oculus go is 2*1024 x 1024 

why is it not 2560x1440 ? like the display size is?
