### ISSUE TITLE
Look-controls component is resetting the rotation of entity

### ISSUE THREAD

**Issue by chetu3319** [aframevr/aframe#3951]
**Description:**
Adding look- controls is resetting the rotation of entitiy holding camera. This doesn't allow to set the view point in the desktop version. 

- A-Frame Version: 0.8.0
- Platform / Device:Desktop / MacBook Pro/ Mozilla/ Safari browser
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/reach-startbutton

In the project, after 5 seconds, which is basically adding the look-controls, it is resetting the rotation.

**Comment by ngokevin** [comment]
Set rotation on camera rig. See stackoveflow for some existing answers on setting camera rotation
