### ISSUE TITLE
Cannot enter VR on Oculus Go

### ISSUE THREAD

**Issue by IvoJager** [aframevr/aframe#3953]
I am not able to enter VR on Oculus Go on current master.

I'm not 100% sure, but this code seems a bit odd to me;
 
```
// WebVR polyfill
// Check before the polyfill runs.
window.hasNativeWebVRImplementation = !!window.navigator.getVRDisplays ||
                                      !!window.navigator.getVRDevices;
window.hasNativeWebXRImplementation = navigator.xr !== undefined;
```

Something to this effect seems to fix it;
```
// WebVR polyfill
// Check before the polyfill runs.
window.hasNativeWebVRImplementation = !!window.navigator.getVRDisplays ||
                                      !!window.navigator.getVRDevices;
window.hasNativeWebXRImplementation = window.hasNativeWebXRImplementation || navigator.xr !== undefined;
```

- A-Frame Version: master
- Platform / Device: Oculus Go

**Comment by IvoJager** [comment]
@dmarcos 
> Thanks for reporting. Try latest master and let
> me know if it works for you:
> [eca59c9](https://github.com/aframevr/aframe/commit/eca59c90329234f1ffa74b8da93be42d11dca9b8)

That fixes it. Thank you! That was super quick :)

> Are you affected by this issue?
> #3942

I am indeed. And still happens with antialiasing on. Seems like a version of the master of around 2018-12-28 does not exhibit this issue.

**Comment by dmarcos** [comment]
Fixed in master
