### ISSUE TITLE
[FEAT] add ability to disable logs

### ISSUE THREAD

**Issue by Hulkmaster** [aframevr/aframe#3954]
**Description:**

- A-Frame Version: 0.8.2

there are logs in aframe like this https://github.com/aframevr/aframe/blob/master/src/index.js#L85 which i want to disable in production, it would be great is there was an option to turn it off

**Comment by dmarcos** [comment]
You can make your own A-Frame build and comment those lines out. Logs are super useful to diagnose issues. We often fix or give people heads up to update A-Frame. What is the motivation to remove the logs? Even if we do disable them on the A-Frame side you will still see THREE logs.

**Comment by Hulkmaster** [comment]
yeah, i can make my own build and disable every log message manually, i also agree that logs are super useful, but

in some cases i don't want to expose some log levels to user, also there is great discussion on THREE logs https://github.com/mrdoob/three.js/pull/5835 :)
