### ISSUE TITLE
Oculus Go not entering VR mode but showing cardboard view

### ISSUE THREAD

**Issue by WorldSeso7** [aframevr/aframe#3957]
- A-Frame Version: 0.8.2
- Platform / Device: Oculus Go Browser
- Reproducible Code Snippet or URL: not available

**Description:**
When I try to click enter VR button with Oculus Go Browser the browser doesn't enter VR mode but shows me a screen like that:
![50227228_10219676886899584_6649160285368090624_o](https://user-images.githubusercontent.com/4233569/51309489-cf540880-1a44-11e9-8fc9-6a609d3de2b1.jpg)

Using Firefox reality browser it shows a full black screen.

I also tried with other devices/browsers:
- Chrome with Oculus Rift: it works perfectly
- Firefox with Oculus Rift: many times it shows infinetly the Firefox app loading screen, less times it works
- GearVR browser: I'll test it in some hours
- Android Chrome and iOS Safari: it works perfectly

**Comment by dmarcos** [comment]
Use master:

https://cdn.jsdelivr.net/gh/aframevr/aframe@056b2bce5d448f0c9e9e1855397ff7a40847d4c5/dist/aframe-master.min.js

**Comment by dmarcos** [comment]
I can't reproduce with [A-Frame examples](https://aframe.io/aframe/examples/). @WorldSeso7 Do you have a link to reproduce?

**Comment by WorldSeso7** [comment]
@dmarcos Using master it works fine!!!

**Comment by dmarcos** [comment]
Thanks for the update. Much appreciated!
