### ISSUE TITLE
GLTF errors Anime UI scene

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3959]
**Description:**

@donmccurdy Any ideas?
 
```
Uncaught (in promise) 
Event {isTrusted: true, type: "error", target: null, currentTarget: null, eventPhase: 0, …}
Promise.then (async)		
(anonymous)	@	GLTFLoader.js:3128
THREE.GLTFLoader.GLTFParser.loadNode	@	GLTFLoader.js:3119
THREE.GLTFLoader.GLTFParser.getDependency	@	GLTFLoader.js:1799
buildNodeHierachy	@	GLTFLoader.js:3234
(anonymous)	@	GLTFLoader.js:3316
Promise.then (async)		
buildNodeHierachy	@	GLTFLoader.js:3301
loadScene	@	GLTFLoader.js:3348
THREE.GLTFLoader.GLTFParser.getDependency	@	GLTFLoader.js:1795
(anonymous)	@	GLTFLoader.js:1871
THREE.GLTFLoader.GLTFParser.getDependencies	@	GLTFLoader.js:1869
THREE.GLTFLoader.GLTFParser.getMultiDependencies	@	GLTFLoader.js:1896
THREE.GLTFLoader.GLTFParser.parse	@	GLTFLoader.js:1697
parse	@	GLTFLoader.js:221
```

- A-Frame Version: master
- Platform / Device: chrome/ff
- Reproducible Code Snippet or URL:

**Comment by donmccurdy** [comment]
I can't reproduce this. You're running `npm run dev` and visiting http://localhost:9000/examples/showcase/anime-UI/, yes?

**Comment by dmarcos** [comment]
@donmccurdy did you run `npm install`?

**Comment by donmccurdy** [comment]
I did, yeah

**Comment by arpu** [comment]
here is the master example with same error 
https://a-frobot.github.io/aframe/examples/showcase/anime-UI/

A-Frame Version: 0.8.2 (Date 2019-01-26, Commit #3b64726)

**Comment by arpu** [comment]
on a fresh master local install i don get this error 
but 
A-Frame Version: 0.8.2 (Date 2019-01-26, Commit #26b8a0e5)
index.js:86 three Version: dmarcos/three.js#webXRSupport
index.js:87 WebVR Polyfill Version: ^0.10.8
three.js:22381 THREE.WebGLRenderer 101dev
three.js:39714 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
getContext @ three.js:39714
AudioListener @ three.js:40055
setupSound @ sound.js:151
update @ sound.js:49
initComponent @ component.js:306
updateProperties @ component.js:278
module.exports.Component @ component.js:61
NewComponent @ component.js:599
initComponent @ a-entity.js:326
updateComponent @ a-entity.js:483
updateComponents @ a-entity.js:451
entityLoadCallback @ a-entity.js:247
emitLoaded @ a-node.js:127
Promise.then (async)
load @ a-node.js:125
load @ a-entity.js:243
(anonymous) @ a-entity.js:85
emit @ a-node.js:263
emitLoaded @ a-node.js:128
Promise.then (async)
load @ a-node.js:125
load @ a-assets.js:83
bound @ bind.js:12
Promise.then (async)
value @ a-assets.js:62
attachedCallback @ a-register-element.js:160
2browser.js:111 components:sound:warn Sound not loaded yet. It will be played once it finished loading 
2three.js:40283 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
play @ three.js:40283
playSound @ sound.js:220
(anonymous) @ sound.js:83
(anonymous) @ three.js:39756
browser.js:111 components:gltf-model:warn Failed to load glTF model 

and the glTF model is not shown

**Comment by dmarcos** [comment]
Run the model through [the validator](http://github.khronos.org/glTF-Validator/). This is what I get:

```
{
    "uri": "engine.glb",
    "mimeType": "model/gltf-binary",
    "validatorVersion": "2.0.0-dev.2.7",
    "validatedAt": "2019-01-28T21:11:10.643Z",
    "issues": {
        "numErrors": 1,
        "numWarnings": 1,
        "numInfos": 0,
        "numHints": 0,
        "messages": [
            {
                "code": "VALUE_NOT_IN_LIST",
                "message": "Invalid value 'image/.png'. Valid values are ('image/jpeg', 'image/png').",
                "severity": 1,
                "pointer": "/images/0/mimeType"
            },
            {
                "code": "GLB_UNEXPECTED_END_OF_CHUNK_DATA",
                "message": "Unexpected end of chunk data.",
                "severity": 0,
                "offset": 428072
            }
        ],
        "truncated": false
    },
    "
```

**Comment by dmarcos** [comment]
@donmccurdy I re exported the model from the original collada file and it seems to have worked (https://github.com/aframevr/aframe/pull/3973).
