### ISSUE TITLE
Textures aren't shown in mobile devices with Adreno 300 series GPU

### ISSUE THREAD

**Issue by DIVITRIVI** [aframevr/aframe#3971]
Motorola E4 with Google Chrome 71.0.3578.99
![photo_2019-01-26_16-20-45](https://user-images.githubusercontent.com/46807417/51793507-18176a00-2187-11e9-83c1-f23ef8073485.jpg)

Xiaomi Redmi 5A with Mozilla Firefox 64.0.2
![photo_2019-01-26_16-23-07](https://user-images.githubusercontent.com/46807417/51793512-1ea5e180-2187-11e9-8c69-8eac526234cb.jpg)

- A-Frame Version: Master
- Platform / Device: Google Chrome and Mozilla Firefox / Motorola E4 and Xiaomi Remi 5A (Android)
- Reproducible Code Snippet or URL:

**Comment by arpu** [comment]
same with the latest master build?
https://a-frobot.github.io/aframe/examples/boilerplate/hello-world/

if yes,  some console log would be nice

**Comment by DIVITRIVI** [comment]
Still have the same problem
![photo_2019-01-26_18-50-33](https://user-images.githubusercontent.com/46807417/51794590-764e4800-219b-11e9-8e44-2ac4c6afef73.jpg)

Here's the console log
![remote console log](https://user-images.githubusercontent.com/46807417/51794603-ae558b00-219b-11e9-8d62-99aba9941bb1.png)

**Comment by dmarcos** [comment]
Adreno 300 series GPUs are notorously problematic (
https://github.com/mrdoob/three.js/issues/9988). Likely no fix at the A-Frame / THREE.js level.

**Comment by DIVITRIVI** [comment]
> 
> 
> Hi, I was having a similar problem (#15633) and i managed to solve it with the changes proposed in this comment:
> 
> [mrdoob/three.js#14137 (comment)](https://github.com/mrdoob/three.js/issues/14137#issuecomment-397843382)
> 
> Hopefully it also works for you!

In what file I'll add those lines, sorry, I'm new on this.
Anyway thanks for the advise.

**Comment by dmarcos** [comment]
@jagracar Thanks for the info

**Comment by dmarcos** [comment]
@DIVITRIVI Do these examples work in your device? http://swimminglessonsformodernlife.com/aframe/examples/

**Comment by DIVITRIVI** [comment]
> 
> 
> @DIVITRIVI Do these examples work in your device? http://swimminglessonsformodernlife.com/aframe/examples/

Sorry for the late reply, yes, those examples works but with some details:

Most of the examples works fine but I still have some errors in the console (in all examples).
![photo_2019-01-30_23-14-26](https://user-images.githubusercontent.com/46807417/52032572-24812700-24e7-11e9-98a6-88181e9fbf56.jpg)
![err1](https://user-images.githubusercontent.com/46807417/52032735-dddffc80-24e7-11e9-935d-5f4ab542ba94.png)

Some reflections are replaced with some black glitch
![photo_2019-01-30_23-16-40](https://user-images.githubusercontent.com/46807417/52032858-6f4f6e80-24e8-11e9-9119-46d83e185cb4.jpg)
![photo_2019-01-30_22-58-55](https://user-images.githubusercontent.com/46807417/52032799-2697b580-24e8-11e9-8c36-56cb4ba9122d.jpg)

In the example "shaders" the background is not displayed
![photo_2019-01-30_23-29-28](https://user-images.githubusercontent.com/46807417/52033232-d3266700-24e9-11e9-9a1c-0db57215d172.jpg)

In the example "animation-color" the texture has a strange performance
![photo_2019-01-30_23-03-44](https://user-images.githubusercontent.com/46807417/52033362-5a73da80-24ea-11e9-9a43-003ca9fd7477.jpg)

The rest of the examples works fine. Thanks for your hard work.

**Comment by gabrielgrant** [comment]
@dmarcos Thanks for finally getting around to tackling this at the aframe level, certainly didn't expect this issue to go quite so deep when I first started delving into it in #3523 and mrdoob/three.js#14137

To confirm, it looks like the change to default precision was reverted in #3988 and then a `precision` prop was added in #3989

To confirm (and for others finding this issue), the recommendation is to manually set precision to `mediump` on the `a-scene`'s `renderer` component, right?

Would it make sense to just set this by default on devices with this GPU (I know doing device-specific fixes shouldn't really be a-frame's responsibility, but this is such a sharp edge that it seems like it might be worth working around?)
