### ISSUE TITLE
Sensor access disabled by default in Safari from iOS 12.2+

### ISSUE THREAD

**Issue by richtr** [aframevr/aframe#3976]
AFrame VR will no longer work on iOS according to the release of iOS 12.2b without changing the default Safari settings on devices:

https://github.com/w3c/deviceorientation/issues/57#issuecomment-458464696

Both `deviceorientation` and `devicemotion` sensors will be disabled by default in Safari from iOS 12.2+. Users will need to enable Settings > Safari > Motion and Orientation access to continue to use AFrame.

AFrame relies on polyfilling WebVR from these sensors on iOS via its dependency on [`webvr-polyfill`](https://github.com/immersive-web/webvr-polyfill) (which in turn relies on [`cardboard-vr-display`](https://github.com/immersive-web/cardboard-vr-display)).

Blog post discussing change @ https://medium.com/@firt/pwas-on-ios-12-2-beta-the-good-the-bad-and-the-not-sure-yet-if-good-a37b6fa6afbf

Is there any plan to work around this change in AFrame?

**Comment by dmarcos** [comment]
Those are bad news. Without access to sensors not sure if there’s anything we can do.

**Comment by griffin2000** [comment]
There is a W3C thread on this here (specifically about adding a permission pop up) be sure to comment how important it is that this gets fixed! https://github.com/w3c/deviceorientation/issues/57

**Comment by geoffreygaren** [comment]
Does AFrame VR offer a fallback interaction model for desktop users and mobile users who choose not to allow sensor access?

**Comment by dmarcos** [comment]
Current conversation about spec: 
https://github.com/w3c/deviceorientation/issues/57

**Comment by dmarcos** [comment]
Also disabled now in Chrome. Console log on Chrome m74 for Android:

```The `devicemotion` event is deprecated on insecure origins and will be removed in M76, around July 2019. Event handlers can still be registered but are no longer invoked since M74, around April 2019. See https://www.chromestatus.com/feature/5688035094036480 for more details.```

**Comment by vin-ni** [comment]
8th wall does this:
![IMG_6547](https://user-images.githubusercontent.com/9806572/57851648-6bb6cd80-77e1-11e9-9d4a-2cef095246d4.JPG)

**Comment by dmarcos** [comment]
@vin-ni thanks for sharing. We have this conversation going on:

https://github.com/aframevr/aframe/issues/4149

**Comment by dmarcos** [comment]
For the record:

iOS now requires both enable device motion manually:

`Settings -> Safari -> Motion & Orientation access`

and page has to be served over http

**Comment by dmarcos** [comment]
Android also disables `devicemotion`. Reference to discussion: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/5yqfAXibz1I/wiLKUPLwDwAJ

**Comment by tinchoforever** [comment]
mmmm, is this supposed to be the standard? Not device motion anymore?

**Comment by dmarcos** [comment]
No `devicemotion` events enabled by default anymore for Chrome and Safari unless the user enables manually. API is standard but `https` enforcement or shipping it enabled is a particular decision of each browser vendor.

**Comment by tinchoforever** [comment]
Are there any alternatives? Or any roadpath?
this kind of kill Aframe on mobile.

**Comment by dmarcos** [comment]
It's an unfortunate decision and we cannot do anything on the A-Frame side. Only way to address is showing  message to the user to enable the API on settings. More info https://github.com/aframevr/aframe/issues/4149

**Comment by allancozart** [comment]
Looks like the API for requesting permission to receive device motion is available on IOS 13 developer beta. https://github.com/w3c/deviceorientation/issues/57#issuecomment-498417027

**Comment by dmarcos** [comment]
Thanks for the update. For reference the API is DeviceOrientationEvent.requestPermission

**Comment by chetu3319** [comment]
Unfortunately, on iPadOS, there is no such option of device orientation and motion access in the settings menu. Device orientation is not working in beta 1 on iPad Pro 2017 release.

**Comment by dmarcos** [comment]
@chetu3319 there’s a permissions API now that applications have to invoke `DeviceOrientationEvent.requestPermission`
and deviceorientation events wont’t fire when the devices is laying on a flat surface.

**Comment by jamesdigid** [comment]
Hello, I just started following this project again recently, and I'm highly interested in contributing and this seemed like some low hanging technical fruit to help me become familiar with this project. Looking forward to any feedback you may have for my PR, and any suggestions as well. 

Thanks

**Comment by SevenSystems** [comment]
Slowly but surely, this security and privacy bullshit is killing off technology as we know it. Maybe it should just stop?

**Comment by dmarcos** [comment]
Once iOS 13 ships things will be back to normal. A-Frame will be able to
request access to devicemotion API without any manual steps. https will be
required though

**Comment by Hailiax** [comment]
iOS 13 is out and A frame isn’t requesting devicemotion API access on 0.9.2

**Comment by davimello28** [comment]
Just to make sure, is this still a problem? I wasn't able to make the examples on aframe.io work in Safari.

**Comment by andersonholland** [comment]
It still seems to be a problem from what I can see, and my iOS is 13.1.3

**Comment by dmarcos** [comment]
Follow https://github.com/aframevr/aframe/issues/4287

**Comment by brianpeiris** [comment]
I think we can call this closed?

**Comment by dmarcos** [comment]
Correct 🎖 thanks
