### ISSUE TITLE
Re-re-export COLLADA models with fixed alpha maps.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#3978]
**Description:**

Current:

![](https://user-images.githubusercontent.com/1848368/51882913-75511e00-2335-11e9-8f8d-b6629b32fb35.png)

@donmccurdy had fixed alpha maps manually in Blender

https://github.com/aframevr/aframe/pull/3974#issuecomment-458396944

**Comment by donmccurdy** [comment]
Any reason not to just revert the tree models to my previous version? Was the anime-UI model the only one with the problem, were you seeing errors on others too? Wondering if it's something about checking binary files into Git... :/

**Comment by dmarcos** [comment]
@donmccurdy It was not just the anime-ui. All gltf models were not rendering.

**Comment by dmarcos** [comment]
@donmccurdy Do you have some bandwidth to reexport the trees from Blender? I can try too if you give me instructions.

**Comment by donmccurdy** [comment]
I don't think it was an export issue, I didn't use the same exporters for all of these models even.. let me try grabbing the working versions on my drive, validating them, and send those to you manually to confirm they work.

**Comment by donmccurdy** [comment]
@dmarcos the tree files on my hard drive from before the reversion pass glTF validation, could you test on your end?

[Archive.zip](https://github.com/aframevr/aframe/files/2820252/Archive.zip)

If that works OK then I think something went wrong checking them into Git...

**Comment by dmarcos** [comment]
@donmccurdy Awesome! It works. Fixed by a03547282138ef7532c2d9e4dae9193b802a97e1
