### ISSUE TITLE
Composite glTF model not rendering anymore as expected on master after re-exporting with latest COLLADA2GLTF

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#3990]
Below the results on master after re-exporting the [original collada model](https://github.com/aframevr/aframe/blob/v0.7.1/examples/showcase/composite/sculpture.dae)

![model](https://d3vv6lp55qjaqc.cloudfront.net/items/0v1o1w2l402c1P002I2v/Image%202019-02-01%20at%204.30.04%20PM.png?X-CloudApp-Visitor-Id=222920)

**Comment by dmarcos** [comment]
Below the model rendered as intended in 0.7.1:

![good model](https://d3vv6lp55qjaqc.cloudfront.net/items/311m1B0E3b2j2C0w0j0E/Image%202019-02-01%20at%204.35.18%20PM.png?X-CloudApp-Visitor-Id=222920)

On 0.8.2 does not render at all.

**Comment by dmarcos** [comment]
@donmccurdy Do you have a good version by any chance anywhere? Sorry for abusing your time.

**Comment by donmccurdy** [comment]
I have a copy yeah, will upload when I’m home

**Comment by dmarcos** [comment]
@donmccurdy Cool thanks. I can give it a try. If it comes from the same place as the others I'm sure it will work :)

**Comment by donmccurdy** [comment]
Ok, here's a good copy:

[sculpture.glb.zip](https://github.com/aframevr/aframe/files/2831034/sculpture.glb.zip)

**Comment by dmarcos** [comment]
Nice! It works! Thank you.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/commit/354e7c96bd24b4470a64b2886eef00e518bfe7fb
