### ISSUE TITLE
Gyroscope not working when i enable chrome://flags/#enable-webvr and not entering VR mode

### ISSUE THREAD

**Issue by albirrkarim** [aframevr/aframe#3991]
### Maybe this is a bug ?

**Condition 1:** 
If i enable the `chrome://flags/#enable-webvr` and not entering VR mode gyroscope is not working (only touch to rotate the Y axis), but when i entering VR mode gyroscope is working properly (web polyfill is working).

**Condition 2**
If i disable the `chrome://flags/#enable-webvr` and not entering VR mode gyroscope is working, but when i entering VR Mode, web polyfill doesn't work.

The condition I want is,
if enable `chrome://flags/#enable-webvr` and not entering VR mode gyroscope is working properly and when entering VR mode is working too (web polyfill is working).

Successfully entering VR mode (when enable `chrome://flags/#enable-webvr`)
![photo_2019-02-03_09-11-30](https://user-images.githubusercontent.com/29292018/52171685-b7de8480-2793-11e9-86af-2e3d1bf927e9.jpg)

Chrome Version:
![photo_2019-02-03_08-58-01](https://user-images.githubusercontent.com/29292018/52171587-e22f4280-2791-11e9-9510-1a9c5dc6cfc0.jpg)

- A-Frame Version: 0.8.2 and [master](https://cdn.jsdelivr.net/gh/aframevr/aframe@b0229d33ba176f2567003d49fca5d2b9049fbcab/dist/aframe-master.min.js)
- Platform / Device: android 8.1 oreo
- Reproducible Code Snippet or URL: https://glitch.com/~west-actor

**Comment by dmarcos** [comment]
What phone? Use [master](https://cdn.jsdelivr.net/gh/aframevr/aframe@b0229d33ba176f2567003d49fca5d2b9049fbcab/dist/aframe-master.min.js)

**Comment by albirrkarim** [comment]
still the same, i have try using [master](https://cdn.jsdelivr.net/gh/aframevr/aframe@b0229d33ba176f2567003d49fca5d2b9049fbcab/dist/aframe-master.min.js)
im using Asus Zenfone Max Pro m1

**Comment by dmarcos** [comment]
There are known issues with the gyroscope and your phone:

https://www.asus.com/zentalk/in/thread-215019-1-1.html

https://forum.xda-developers.com/asus-zenfone-max-pro-m1/help/gyroscope-t3784487

Update firmware and try again.

**Comment by albirrkarim** [comment]
i have try on Galaxy Note 8 (Android 9) still same problem

**Comment by rubxdev** [comment]
Hello, I know I'm late, but I was facing the same issue, then I installed Google VR Services from Google Play and now it's working!!!

**Comment by dmarcos** [comment]
With the transition to WebXR things should have smoothed out. I'm closing this but can reopen if necessary
