### ISSUE TITLE
SteamVR error loop / unresponsive Firefox browser if HMD not connected

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#3992]
**Description:** When loading an A-Frame scene (even the non-interactive one on aframe.io homepage) in Firefox 65.0 on a machine that has SteamVR (1.2.10) installed but not open and without the HMD connected, SteamVR automatically opens and gives an error message, `SteamVR has encountered a critical error`, and the entire browser is unresponsive. When dismissed via either option (restart or quit), the error returns momentarily and the browser remains unresponsive.

This behavior emerged recently (but before this current version of SteamVR), and my Firefox config has `dom.vr.autoactivate.enabled` set to false. If SteamVR is already open, the issue does not occur. This same behavior occurs with the WebVR sample, so it's not strictly an A-Frame issue, but I thought I'd start here and try to get guidance on where to report it next

- A-Frame Version: 0.8.2
- Platform / Device: Windows 10 Firefox 65 Vive
- Reproducible Code Snippet or URL: https://aframe.io/

**Comment by dmarcos** [comment]
There’s been Firefox regressions that are being worked out:

https://github.com/aframevr/aframe/issues/3941

Comment on the bugzilla bug if you have additional info. You can also open a new bug if you feel the bug is unrelated.

I keep this open as a reference

**Comment by dmarcos** [comment]
I think this is no longer an issue but can reopen if necessary.
