### ISSUE TITLE
Aframe doesn't work on Chrome iOS 72

### ISSUE THREAD

**Issue by fobchs** [aframevr/aframe#3999]
**Description:**

Aframe doesn't work on Chrome iOS 72. If you go Aframe.io, only a few examples are working.

It seems like only Image related scenes are working. 

such as:
Doesn't work
https://aframe.io/examples/showcase/helloworld/

Does work
https://aframe.io/examples/showcase/360-image-gallery/

- A-Frame Version: 0.8.2
- Platform / Device: iOS Chrome (iPhone X) 72.0.3626.74
- Reproducible Code Snippet or URL: aframe.io

**Comment by dmarcos** [comment]
I recommend using Chrome m71. Chrime m72 WebXR implementation is going through heavy changes. We have to wait until the dust settles. More info: 
https://github.com/mrdoob/three.js/pull/15604

**Comment by dmarcos** [comment]
This is fixed in master 
https://github.com/aframevr/aframe/issues/3846
