### ISSUE TITLE
VR mode not working in Chrome m72

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4002]
WebXR API is under heavy development on a daily basis. We will sync up once the dust settles. More info:

https://docs.google.com/document/d/1R8Bz0_vK9YmY5-ZhsbLtZ9-DDJpTOgNeibFD4SdUnbw/edit?usp=sharing

https://github.com/mrdoob/three.js/pull/15604

**Comment by arpu** [comment]
looks like 
navigator.xr.requestDevice() is not available 

https://github.com/immersive-web/webxr-samples/blob/master/input-tracking.html#L95

**Comment by GFargo** [comment]
Curious if the dust still being kicked up over on the WebXR API, or was a workaround determined for Chrome?

**Comment by dmarcos** [comment]
This issue no longer applies. WebXR shipped in Chrome m79 and A-Frame 1.0.4 is fully compatible.
