### ISSUE TITLE
Transparency issues when requesting transparent entities from pool

### ISSUE THREAD

**Issue by feiss** [aframevr/aframe#4004]
Pool component retrieves entities in the same order they were added to the DOM, but this can produce the classic transparency issue with depth buffer if the entities are transparent and positioned in the reverse order (deeper entities in DOM are positioned in front).

I think the pool component should have an additional parameter (for example reverse: true) that would retrieve entities in the reverse order they were added to the DOM.

**Comment by ngokevin** [comment]
I'm offering another solution is to change the scene to sort transparent objects manually (default three.js sorting with override) via `render-order` component. Better explicit than shuffling around HTML ordering.

```html
<a-scene render-order="layer1, layer2, layer3, layer4">
  <a-entity render-order="layer1"></a-entity>
  <a-entity render-order="layer2"></a-entity>
</a-scene> 
```

**Comment by ngokevin** [comment]
I think the `render-order` explicit approach is better way to go, since we can't guarantee reverse ordering of pooled objects is stable either as you start to shuffle the pool.
