### ISSUE TITLE
Networked Scene Doesn't work in cdn Master and 0.8.2

### ISSUE THREAD

**Issue by albirrkarim** [aframevr/aframe#4008]
![image](https://user-images.githubusercontent.com/29292018/52514010-fd41fc80-2c40-11e9-8410-e5811e13fcde.png)

This is [my project](https://glitch.com/edit/#!/adventurous-porcupine?path=public/index.html:9:4) on glitch.com. 

I was trying this [networked scene project ](https://glitch.com/~past-amusement) from kevin ngo.
the project is using aframe 0.8.0 sync position and rotation that working properly. but gyroscope is hyper sensitive rotation in mobile.

### Definition :
Which i call Mobile Movement Button is this, bellow scene
![photo_2019-02-09_07-34-05](https://user-images.githubusercontent.com/29292018/52513403-28c2e800-2c3d-11e9-822e-ad80551d3076.jpg)

### Error Case
![image](https://user-images.githubusercontent.com/29292018/52513546-14cbb600-2c3e-11e9-94d6-16b2703a33f3.png)
I try to change aframe version and that come with diferent error.

**Case 1:** (Using 0.8.0)
- Position sync properly (Desktop && Mobile)
- Rotation sync properly (Desktop && Mobile)
- Mobile Movement Button working properly (Desktop && Mobile)
- Gyroscope Hyper Sensitive
 
**Case 2:** (Using 0.8.2)
Then i try to change aframe version to 0.8.2 but only position can sync, the rotation is can't.
- Position sync properly (Desktop && Mobile)
- Rotation not sync (Desktop && Mobile)
- Mobile Movement Button working properly (Desktop && Mobile)
- Gyroscope working properly

**Case 3:** (Using Aframe [master](https://cdn.jsdelivr.net/gh/aframevr/aframe@b0229d33ba176f2567003d49fca5d2b9049fbcab/dist/aframe-master.min.js))

- Position not sync (Desktop && Mobile)
- Rotation not sync (Desktop && Mobile)
- Mobile Movement Button not working (Desktop && Mobile)
- Gyroscope working properly

#### Platform / Device: 
- (Mobile) Asus Zenfone Max Pro m1 (Android 8.1 and lastest firmware,Chrome Dev 73.0.3683.12)
- (Desktop) Lenovo G40-45 (Linux Xubuntu 18.04, Chrome Version 71.0.3578.98 (Official Build) (64-bit))
#### Reproducible Code Snippet or URL:
- [Demo](https://adventurous-porcupine.glitch.me/)
- [Code](https://glitch.com/edit/#!/adventurous-porcupine?path=public/index.html:9:4)

**Comment by dmarcos** [comment]
This should be filed against the networked-aframe repo: https://github.com/networked-aframe/networked-aframe

**Comment by dmarcos** [comment]
Also use A-Frame 0.9.0
