### ISSUE TITLE
vive-controls only one and hand-controls not working on 0.9.0?

### ISSUE THREAD

**Issue by smeybi** [aframevr/aframe#4013]
Hi

Probably issue with Vive-Controller on Aframe 0.9.0 (tested in Firefox 65, 66 and Supermedium, with SteamVR 1.2.10).
_

 `vive-controls` component not works correct. Only one controller is present on the scene. The whole, not just the model. 
```
<a-entity vive-controls="hand: left"></a-entity>
<a-entity vive-controls="hand: right"></a-entity>
```

_

`hand-controls` component no longer works.
```
<a-entity id="leftHand" hand-controls="left"></a-entity>
<a-entity id="rightHand" hand-controls="right"></a-entity>
```
**console error** three.js:
_THREE.ObjectLoader: You have to import LegacyJSONLoader in order load geometry data of type "Geometry".
TypeError: o is undefined_

_

Many thanks!

**Comment by arpu** [comment]
https://github.com/aframevr/aframe/pull/3932

**Comment by dmarcos** [comment]
@smeybi How is this example working for you? https://aframe.io/aframe/examples/test/laser-controls/
1 or 2 controllers?

**Comment by smeybi** [comment]
Only 1, the right hand.
![laser_controller](https://user-images.githubusercontent.com/47615808/52826453-33f49880-30c1-11e9-8c50-2237cacbf2f6.jpg)

![laser_controller_insp](https://user-images.githubusercontent.com/47615808/52826460-3820b600-30c1-11e9-8d39-991de39b6a5c.jpg)
