### ISSUE TITLE
FlushToDom causing the environment to crash in Aframe 0.9.0

### ISSUE THREAD

**Issue by aj019** [aframevr/aframe#4014]
**Description:**

- A-Frame Version: 0.9.0
- Platform / Device: Chrome Browser
- Reproducible Code Snippet or URL:   https://glitch.com/edit/#!/phase-station

**Comment by hars-shhh** [comment]
Any Response?

**Comment by albirrkarim** [comment]
![image](https://user-images.githubusercontent.com/29292018/54878273-ed7f2000-4e5c-11e9-82d4-a5e82acd4d1c.png)
Crash

**Comment by hars-shhh** [comment]
@albirrkarim What are you trying to show?

**Comment by albirrkarim** [comment]
Home page of aframe.io error, because it using master aframe script
