### ISSUE TITLE
a-frame environment not rendering on mac

### ISSUE THREAD

**Issue by rahirschi** [aframevr/aframe#4023]
Problem with mac.
It's a simple a-frame scene using the environment component. Works fine on cell phones and every pc I've tested it on. But on a mac purchased in 2014 it displays a dark screen with a bit of the ground horizon as a dark silhouette. The same mac works fine for a-frame galleries I've made that just display a photosphere.

It's a mac desktop w osx 10.7.5 with safari v 6.1.6 or chrome v 49.0. No joy with Firefox Nightly.
Here is the scene. It's running a-frame 9.0. He gets the same results on a-frame 8.2.
https://hetravel.space/vr/moon.html

**Comment by dmarcos** [comment]
Any errors in console?

**Comment by dmarcos** [comment]
What computer, GPU?

**Comment by dmarcos** [comment]
You’re running OSX lion. 6 years old OS / Browser. Is updating an option?

**Comment by dmarcos** [comment]
Unfortunately, It won’t be possible to support 7 years old OS and Browser. Web APIs have evolved and we don’t have access to machines with that configuration. Sorry for this.
