### ISSUE TITLE
Component.events to define event handlers that are automatically binded and attach/detach on scene play / pause.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#4025]
**Description:**

Proposed API:

```js
AFRAME.registerComponent('foo', {
  events: function () {
    click: function (evt) {
      this.el.setAttribute('material', 'color', 'red');
    }
  } 
});
```

**Comment by dmarcos** [comment]
Maybe too much extra API surface? What about just wrapping AEntity `addEventListener` and attach / detach automatically? Same API but does what you expect by default

**Comment by ngokevin** [comment]
`.events` feels more explicit, more concise, and able to see all the events in one place. Wrapping `addEventListener` also won't let you determine which events came from what component.

**Comment by ngokevin** [comment]
Also could do `this.addEventListener`, though I sort of like not having to create an `init` handler just to add events.

**Comment by ngokevin** [comment]
Think I'll start on this. Starting to feel the need for this as we have hot reloading now. Hot reloading lets us modify components and they will auto-reflect live. If you modify a tick or like an update handler, you'll see that behavior update live. Internally, this works when a component is updated, hot-module-replacement will swap out the module. Then `aframe-hot-loader` detaches all instances of those components, and reattaches with instances with the updated module (with the same properties). This allows rapid dev cycle with no need to reload.

The issue with event listeners is they take lot of manual work to keep in lifecycle that we usually don't bother. For hot reloading, this causes new component instance events to continue to get added while the old does not get destroyed. An `events` dict would solve the issue to auto-detach events on `play` / `pause` (as well as bind). Necessary to be defined on component since it's per-component-instance.

This also helps with things like Inspector or general scene pausing to make sure all events are 100% sure to detach on pause.
