### ISSUE TITLE
Ability to render Aframe on the server

### ISSUE THREAD

**Issue by lokiiarora** [aframevr/aframe#4026]
**Description:**

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

This isn't really an issue but rather a feature request for rendering Aframe experiences on the server.
Does anyone have any leads on this?

**Comment by dmarcos** [comment]
What’s your use case?

**Comment by lokiiarora** [comment]
The use case is that would like to export glb models on the server so that
people with low end devices can just stream that onto their device rather
than exporting the model on thier device itself.
Which would take way more time in case of complex models.
This is more like an experiment to get it working, a quirky idea we thought
would be cool.

**Comment by dmarcos** [comment]
Thanks foe the information. It will be hard to get good latency. Better to offer simplify models / textures suitable to mobile devices. In any case, this is something that could be explored independently. Render WebGL in server and stream frames. Not in scope of A-Frame itself.
