### ISSUE TITLE
vr-mode-ui component can't be reenabled after being disabled

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#4029]
**Description:**

- A-Frame Version: 0.9.0
- Platform / Device: Chrome on desktop
- Reproducible Code Snippet or URL:
https://aframe.io/aframe/examples/boilerplate/hello-world/

Open the console:
```
AFRAME.scenes[0].setAttribute('vr-mode-ui', {enabled: false});
undefined
AFRAME.scenes[0].setAttribute('vr-mode-ui', {enabled: true});
component.js:681 Uncaught TypeError: Cannot set property 'enabled' of undefined
    at extendProperties (component.js:681)
    at i.callUpdateHandler (component.js:393)
    at i.updateProperties (component.js:277)
    at HTMLElement.value (a-entity.js:478)
    at HTMLElement.value (a-scene.js:648)
    at HTMLElement.<anonymous> (a-entity.js:715)
    at HTMLElement.value (a-scene.js:487)
    at <anonymous>:1:18
```

The first time, in vr-mode-ui `update` function, it calls 
`this.remove();`
which executes `wrapRemove` (in src/core/component.js) with the line
`this.attrValue = this.oldData = this.parsingAttrValue = undefined;`

The second call will call (in src/core/component.js)
`extendProperties(dest, source, isObjectBased)`
with `dest` undefined (this.oldData)

The wrapRemove stuff was introduced in aframe 0.9.0 with the object pool.

**Comment by vincentfretin** [comment]
In aframe 0.8.2, this doesn't give an error, but the vr-mode-ui doesn't show back.

I'm having the error because I use aframe-xr and the xr system set it false in the init
https://github.com/mozilla/aframe-xr/blob/50326e45f17fdfc87c1704cc7a16510058fba4e8/src/systems/xr.js#L7
and eventually set it back to true.
I don't even use those buttons in my app, I don't even see them currently.
I'll just set enabled to true in the init to get rid of the error and move on.
Don't waste your time on this issue.

**Comment by Utopiah** [comment]
Well that's still an issue, why was it closed if it's not solved?

**Comment by vincentfretin** [comment]
I reopened. The issue exists since 0.7.0 or before. Setting `enabled: false` and later setting to `enabled: true` does not show up again the button.

**Comment by ngokevin** [comment]
The use case of `vr-mode-ui` is to provide your own button, not to toggle it. You can use normal CSS to toggle it.

**Comment by Utopiah** [comment]
As the behaviour is not predictable could be reflected in the documentation.
