### ISSUE TITLE
Canvas Element now above view

### ISSUE THREAD

**Issue by bknill** [aframevr/aframe#4046]
In 0.9.0 I can no longer click elements on the UI that are above the scene, the grab cursor canvas is in the way. 

My elements are rendered inside the scene as DIVs, via React (to reuse components as either Entities or DIVs depending on if in VR view or not)

This was working fine in 0.8.2, can the grab cursor be disabled? 

- A-Frame Version: 0.9.0
- Platform / Device: Windows 10
- Reproducible Code Snippet or URL:

**Comment by ngokevin** [comment]
If you want to overlay, add a div (not inside the scene), and add a large z-index, or set scene to be `embedded` and style as you wish.
