### ISSUE TITLE
Line layout broken in v0.9.0

### ISSUE THREAD

**Issue by HxxxxxS** [aframevr/aframe#4063]
**Description:**
After upgrading to v0.9.0 the line layout stops spreading child entities.
- A-Frame Version: **0.9.0**
- Platform / Device: **Windows10/Firefox65**
- Reproducible Code Snippet or URL:
   The [Official 360 Image Gallery](https://glitch.com/edit/#!/aframe-gallery?path=index.html) example glitch with only the version number bumped:  
   - Code: https://glitch.com/edit/#!/aware-color  
   - Preview: https://aware-color.glitch.me/
Recorded gif of how it appears on my end: https://i.imgur.com/xCTqo8K.gifv

**Comment by ngokevin** [comment]
I have updated the 360 image gallery guide! Which bumps the component version also. https://github.com/aframevr/aframe/commit/35a063abbcd6113fdb3af77378dcabde2cf08592
