### ISSUE TITLE
Screenshot function broken in 0.9.0

### ISSUE THREAD

**Issue by bknill** [aframevr/aframe#4068]
**Description:**

I'm assuming this is a bug, it was working fine in 0.8.2

> THREE.WebGLRenderer.readRenderTargetPixels: readPixels from renderTarget failed. Framebuffer not complete.
> 
> DOMException: Failed to construct 'ImageData': The source width is zero or not a number.

  ```
  const scene = document.querySelector('a-scene')
    scene.setAttribute('screenshot',{width: 1024, height: 1024})
    const imgData = scene.components.screenshot.getCanvas('perspective')
```

Comes from 

 `         imageData = new ImageData(new Uint8ClampedArray(pixels), size.width, size.height); // Hide quad after projecting the image.`

Seems size isn't being set, either with the default or the above method to set the size? 

- A-Frame Version: 0.9.0
- Platform / Device: Windows 10 Chrome 72
- Reproducible Code Snippet or URL:

**Comment by bknill** [comment]
I tried removing scene.setAttribute('screenshot',{width: 1024, height: 1024})

Didn't make any difference.

**Comment by dmarcos** [comment]
It needs additional information, link to reproduce. It works for me in deployed examples in both Firefox 65 and Chrome 72. 

https://aframe.io/aframe/examples/showcase/anime-UI/

Run the following command on console:

```
 document.querySelector('a-scene').setAttribute('screenshot',{width: 1024, height: 1024});
var imgData = document.querySelector('a-scene').components.screenshot.getCanvas('perspective');
```

**Comment by bknill** [comment]
Thanks I'll try and get a Glitch together, that example is working for me. 

Using the keyboard short cuts in my player has the same error: 

```
THREE.WebGLRenderer.readRenderTargetPixels: readPixels from renderTarget failed. Framebuffer not complete.
function.console.(anonymous function) @ :3000/static/js/5.chunk.js:341622
:3000/static/js/5.chunk.js:56452 Uncaught DOMException: Failed to construct 'ImageData': The source width is zero or not a number.
    at NewComponent.renderCapture (https://localhost:3000/static/js/5.chunk.js:56452:23)
```

This is with a video-sphere. I'll see if that's causing the problem.

**Comment by bknill** [comment]
Ahh.. 

I had  `<a-scene screenshot ...` left in from 0.8.2, removing this fixed the error.
