### ISSUE TITLE
"Warning: Tried to remove `Object3D` of type:  mesh which was not defined." How to avoid it?

### ISSUE THREAD

**Issue by asandersSAP** [aframevr/aframe#4070]
**Description:**
**Every** time we load entities into a scene at runtime we get the following warning, which is a mess with >100 entities: 

> THREE.MTLLoader: .setTexturePath() has been renamed to .setResourcePath(). aframe.min.js:442:484

> core:a-entity:warn Tried to remove `Object3D` of type:  mesh which was not defined.

Can you tell me how to avoid this warning? 

- A-Frame Version: 0.9 
- Platform / Device: MacOS Mojave

**Comment by ngokevin** [comment]
Hi, thanks for the report. In `src/components/obj-model.js`, want to make a PR to change to `setResourcePath`?

**Comment by asandersSAP** [comment]
Thanks! I was out of time the last few days
