### ISSUE TITLE
Camera not working when enter VR mode in 0.9.0

### ISSUE THREAD

**Issue by darkwave** [aframevr/aframe#4074]
Simply I cannot look around like I do when scene is not in vr-mode.

If I move the camera dragging using mouse like usually camera changes only after exiting vr-mode.

- A-Frame Version: 0.9.0
- Platform / Device: Desktop Chrome Version 72.0.3626.121 (Official Build) (64-bit)
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

**Comment by dmarcos** [comment]
Expected behavior. Mouse`look-controls` are disabled in VR mode to leave head orientation control of the camera and prevent motion sickness.
