### ISSUE TITLE
I can not join the slack channel with the message "token_revoked".

### ISSUE THREAD

**Issue by keropiyo** [aframevr/aframe#4077]
**Description:**
I tried to join the aframevr Slack community
https://aframevr-slack.herokuapp.com
Put an e-mail address in, but failed!
I can not join the slack channel with the message "token_revoked".

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL: https://aframevr-slack.herokuapp.com

![failed](https://user-images.githubusercontent.com/3609473/54196378-9d22cc80-4504-11e9-89e9-ed603a55f45c.png)

**Comment by dmarcos** [comment]
We replaced the link in the site. Use this one: https://aframe.io/slack-invite/

**Comment by Virtualmerse** [comment]
Hello, this site: https://aframe.io/slack-invite/ is also down.
