### ISSUE TITLE
Add text label element

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#408]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Thursday Aug 27, 2015 at 00:46 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/25_

----

Enables user to add text labels to their scene.

User can specify:

* Text color
* Background color
* Padding (top, bottom, left, right)
* Font
* Text content (specify as attribute, or within open/closing tags?)
* Scale

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Thursday Aug 27, 2015 at 08:17 GMT_

----

Look at reusing HIRO solution for this.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Sunday Sep 06, 2015 at 20:01 GMT_

----

@caseyyee I dug into our previous canvas-based solution in https://github.com/MozVR/hiro/blob/master/js/lib/vruikit.js, but it's a bit beyond my skills to port to our new component model. If you don't mind I'm going to transfer this to you, as creator of the original?

**Comment by ngokevin** [comment]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caseyyee](https://github.com/caseyyee)**
_Sunday Sep 06, 2015 at 21:58 GMT_

----

Sure, I'll get something going.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Wednesday Oct 07, 2015 at 17:23 GMT_

----

Should text be part of ```vr-markup``` or provided by ```vr-elements```?

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Tuesday Dec 22, 2015 at 00:18 GMT_

----

alternatively https://github.com/ngokevin/aframe-text-component

**Comment by gasolin** [comment]
whats difference between #578 and this?

**Comment by dmarcos** [comment]
This will be handled by 3rd party components.

**Comment by ngokevin** [comment]
https://github.com/bryik/aframe-bmfont-text-component has a case for standard since it works well. But component consumption story would solve it as well and give us less code to maintain.
