### ISSUE TITLE
A-link fails in 0.9.0 in Oculus GO Browser when next scene is too heavy

### ISSUE THREAD

**Issue by PlumCantaloupe** [aframevr/aframe#4081]
**Description:**
In A-Frame 0.8.2 one could recently traverse using the link component between scenes on the oculus GO using the Oculus browser, even if they were "heavier" scenes. Now in 0.9.0 the user will be stuck within a spinning ball screen waiting indefinitely for the next scene to load. If we then exit out of VR mode, refresh, and go back in it does load.

Below are the console logs from the GO when (1) first entering the "Reproducible Code Snippet or URL" given below, then (2) clicking on the link to move to load scene2, then (3) clicking in scene2's link to come back to the original scene where it gets stuck in the loading screen.

I have yet to dive into the code too far, but it seems to stem from THREE.js trying to request a different "size while VR device is presenting."

EDIT: with new changes, Vive now work with Firefox, and Oculus now just kicks out to 2D mode when entering a hyperlink.

**1.** <img width="1016" alt="Screen Shot 2019-03-14 at 12 28 32 AM" src="https://user-images.githubusercontent.com/264985/54331824-0b918880-45f2-11e9-977c-26f7d7a7d44d.png">
**2.** <img width="1022" alt="Screen Shot 2019-03-14 at 12 28 54 AM" src="https://user-images.githubusercontent.com/264985/54331865-324fbf00-45f2-11e9-8aea-91a295b96107.png">
**3.** <img width="1022" alt="Screen Shot 2019-03-14 at 12 29 16 AM" src="https://user-images.githubusercontent.com/264985/54331878-3976cd00-45f2-11e9-8a0d-987b8376e9bc.png">

Any ideas? :)

- A-Frame Version: 0.9.0
- Platform / Device: Oculus GO / Oculus Browser
- Reproducible Code Snippet or URL: https://glitch.com/~portal-test-af-1

**Comment by dmarcos** [comment]
`vrdisplayactivate` handler likely has a time limit to enter VR mode. We're maybe taking too long, stuck at loading and times out.

**Comment by PlumCantaloupe** [comment]
Thanks, I will take a look there as that seems a fruitful direction. The only thing I can note is that I tried replacing the version of three.js all way back to r93 and it was the same issues (r92 broke AF.0.9.0 in other ways).

**Comment by PlumCantaloupe** [comment]
Okay, so I was able to find a workaround by removing by commenting out loadingScreen in a-scene within an otherwise unmodified master. This also removes the warnings of determinant is 0, and can't resize while presenting. I will dig into loadingScreen.js to see what is causing the issue there but at least it is narrowed :)

**Comment by PlumCantaloupe** [comment]
Also, have noticed this isn't working on the Original Vive and Firefox 65.0.2. It does not report the same warnings as the GO though, and removing loadingScreen from a-scene.js does not seem to fix ... 

Anyone else confirm hyperlinks broken for PC headsets in 0.9.0 also?

**Comment by dmarcos** [comment]
Give this PR a try: https://github.com/aframevr/aframe/pull/4085
Try with the links examples

**Comment by PlumCantaloupe** [comment]
Thanks just tried and noticed a few strange things (also added to glitch above):

- Oculus GO no longer can enter VR
- When I used it with a-link examples no problem
- when I used within the glitch above selecting link leads to indefinite loading screen
- when I used in my own project would go through to other links but would randomly change resolution strangely. Screenshot attached.

Almost feel like there is some sort of race condition happening during the loading of heavy scenes?

![Screenshot 2019-03-16 20 50 45](https://user-images.githubusercontent.com/264985/54483760-6bc13e00-482f-11e9-9194-dad664fbb178.png)

**Comment by PlumCantaloupe** [comment]
Updated my comment above as I was accidentally trying to load A-Frame twice in Glitch (oops). So now it just causes the randomly low resolution glitch

**Comment by PlumCantaloupe** [comment]
Having difficulty chasing this down - going back to the A-Frame repo master. On the GO removing the LoadingScreen elements fixes the hyperlink issues; but on the Vive|FF removing loadingScreen results in a stuck SteamVR loading screen within the HMD. On the desktop it seems the page exited to VR (though exitVR was not called by a-scene), so just clicking on the enterVR button again gets you back into VR. Sometimes, albeit rarely, it does go in right away but I can't see any differences between getting in or not following the function calls.

The only major changes I see from a-scene.js 0.8.2 and 0.9.0 are the WebXR checks and the loadingScreen code so far. I'll have to study what went right with 0.8.2 more ...

**Comment by Artyom17** [comment]
So, yeah, Oculus Browser has a 5 seconds limit for requestPresent to be called during VR-to-VR navaigation.

**Comment by dmarcos** [comment]
@PlumCantaloupe Can you still reproduce in master any of the issues above?

@Artyom17 Thanks for the info

**Comment by PlumCantaloupe** [comment]
I will check again tonight.

**Comment by PlumCantaloupe** [comment]
Still getting kicked out on GO. Have yet to check Vive. So does the 5s timeout men’s everything needs to load within 5s before presentation? 

So basically no loading asynchronity and a slow internet connection will kick us out of VR if I understand correctly?

**Comment by dmarcos** [comment]
master calls `requestPresent` immediately so loading times should not affect. 

@Artyom17 In Firefox if requestPresent succeeds once then subsequent calls will also succeed (no user gesture requirement). Is Oculus Browser behavior different? A-Frame calls requestPresent early and then calls again once the renderer, canvas and the rest of the scene have been.

**Comment by PlumCantaloupe** [comment]
Can confirm that Vive now works. Thanks @dmarcos. Removing loadingScreen.js is a workaround for the Oculus GO browser for now at least.

**Comment by PlumCantaloupe** [comment]
And actually, though the Vive/FF is fixed even with removing loaderScreen.js on the new master it seems the GO will still kick you out of VR when loading these scenes. Since my focus is on GO HMD I will jump back to old changes for now as I can work around those at least.

If anything changes I'll report back.

**Comment by PlumCantaloupe** [comment]
To be more complete I want to note here that the error message being received when calling requestPresent on traversal is related to **VRLayer**. Maybe [maxLayers](https://developer.mozilla.org/en-US/docs/Web/API/VRDisplayCapabilities/maxLayers) in more than one? 

The PR ( #4107 ) above seems to fix this, but unsure how exactly as @dmarcos has kindly explained that the canvas parameter shouldn't matter in this case.

**Comment by PlumCantaloupe** [comment]
Closing this issue as PR #4199 (issue #4198 ) has now fixed this. Thanks!
