### ISSUE TITLE
.flushToDOM() does not update DOM values with A-Frame visual inspector  

### ISSUE THREAD

**Issue by iburguera** [aframevr/aframe#4084]
I'm having issues with flushToDOM() on my scene. I have a button that executes a script to update the modified values to the DOM. The function is only working (updating the values to the DOM) when I change the values on the right panel side of the editor and not when I use the visual editor.  Any clue why is that happening?

How to reproduce the issue:

 a) Not working - Click on the box using the visual editor to move the box using the arrows to any position and then press "update DOM". The position of the box should be updated with the new values but none are updated (check values with developer tools)

b) Working - Click on the box using the visual editor and then move the box using the right panel input values to any position.  Then press "update DOM" and check that DOM values are updated.

- A-Frame Version: 0.8.2
- Platform / Device: Chrome Browser
- Reproducible Code Snippet or URL: https://codepen.io/iburguera/pen/OqvGvo

There is a message on the console saying "THREE.BoxHelper: .update() has no longer arguments"  every time I move  the box around. Maybe the issue is related to this message.  

![Captura de pantalla 2019-03-15 21 58 15](https://user-images.githubusercontent.com/3015030/54462072-cd6da380-476e-11e9-9c0b-6e1e2cd7c7a0.png)

**Comment by iburguera** [comment]
Still getting the same issue on 0.9.0 and 0.9.2.  I guess there is some function that prevents updating those values when changing the value using the cursor for performance purposes. 

Can anyone help me? BR

**Comment by gearcoded** [comment]
The issue is still reproduced with the latest A-frame version.

**Comment by vincentfretin** [comment]
https://github.com/aframevr/aframe-inspector/pull/695 fixes it.

**Comment by dmarcos** [comment]
dup of https://github.com/aframevr/aframe/issues/4289 that has been fixed
