### ISSUE TITLE
WebXR broken in Chrome (m73)

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4087]
Implementation does not seem to match [latest spec](https://immersive-web.github.io/webxr/)

WebXR samples also broken: https://github.com/immersive-web/webxr-samples/issues/35

I couldn't find any working code sample to fix THREE / A-Frame.

**Comment by machenmusik** [comment]
Same when I looked last weekend, unfortunately

**Comment by mrhegemon** [comment]
Our team has yet to find a way around this. Any updates?

**Comment by dmarcos** [comment]
@mrhegemon There's no workaround. Chrome WebXR implementation is still experimental and the spec not finalized. Chrome implementation is evolving with the spec and going through lots of changes. Until the dust settles, I recommend using WebVR on Firefox or Supermedium on dekstop. 

To reset Chrome for 2D purposes click `Reset all to default` in `chrome://flags/`

**Comment by stevel4857** [comment]
OMG. I have been thinking it was me for a month now. Glad this was here. I can wait.

**Comment by dmarcos** [comment]
This is no longer applicable. Consolidating all WebXR / Chrome issues on https://github.com/aframevr/aframe/issues/4709
