### ISSUE TITLE
Gyroscope controls look-controls even when enabled: false;

### ISSUE THREAD

**Issue by pookage** [aframevr/aframe#4095]
**Description:**

With look-controls set to the following:
`look-controls="enabled: false; hmdEnabled: false; touchEnabled: false;"`

the device still uses the gyroscope.  Issue no-longer exists if `touchEnabled: false;` is removed.

- A-Frame Version: 0.9.0
- Platform / Device: Chrome & Brave / Google Pixel

**Comment by dmarcos** [comment]
I cannot reproduce this issue: https://glitch.com/edit/#!/jasper-licorice

If you can provide a link to reproduce we will reopen and look into it.

**Comment by pookage** [comment]
Apologies - looks like this only happens when placed on an aframe-react `<Entity />` - I'll whack a report over there instead.
