### ISSUE TITLE
Animation synchronization

### ISSUE THREAD

**Issue by Philosophist** [aframevr/aframe#4096]
**Description:**
The torus id'd: `s1e1`

In here:`<a-entity id="s1e1" material="color: #02e8f4"  rotation="0 90 0"; geometry="primitive: torus; radiusTubular: 0.004" >`

Has 2 animations attached to it. One for left to right movement, another for expanding and contracting.

**The issue:**

I would like these animations to synchronize so that the torus is expanded in the middle and contracted at the ends. It represents a visualization of an electron orbiting a single proton in a hydrogen atom. They get out of sync inevitably. I will attempt a work around with a tick component, but was suggested to submit this issue in case you want to allow for predictable synchronicity of actions for the developers.
- A-Frame Version: 0.9.0
- Platform / Device: webpage
- Reproducible Code Snippet or URL:
~~~~
<!DOCTYPE html>
<html lang="en">
<head>

  <!--  Meta  -->
  <meta charset="UTF-8" />
  <title>Alchem Figher!</title>

  <!--  Styles  -->
  <link rel="stylesheet" href="styles/index.processed.css">

  <!-- Scripts -->
  <script src="https://aframe.io/releases/0.9.0/aframe.min.js"></script>

    <script src="https://unpkg.com/aframe-particle-system@1.0.x/dist/aframe-particle-system-component.min.js"></script>
  <script src="jquery.js"></script>
  <script src="//cdn.rawgit.com/donmccurdy/aframe-extras/v3.8.0/dist/aframe-extras.min.js"></script>
</head>
<body>

<a-scene>
  <a-text value="Rational Bonding Presents" position="-3 7 -10" color="#EF2D5E">
    <a-text value="Alchem Fighter" height="30" width="20" position=".5 -.5 0" color="#02e8f4"></a-text>
  </a-text>
  <a-sphere id="proton" position="0 2.5 -6" radius=".05" color="#EF2D5E">
    <a-sphere id="eclouds1e1"  radius=".53" color="#02e8f4" opacity=".4">
    <a-entity id="s1e1" material="color: #02e8f4"  rotation="0 90 0"; geometry="primitive: torus; radiusTubular: 0.004" >
      <a-animation attribute="position" dur="250" from=".53 0 0" to="-.53 0 0" direction="alternate" repeat="indefinite"></a-animation>
      <a-animation attribute="geometry.radius"  dur="125" from=".01" to=".53" direction="alternate" repeat="indefinite"></a-animation>
    </a-entity>
  </a-sphere>
  <a-sky src="https://upload.wikimedia.org/wikipedia/commons/7/7b/Earth_Western_Hemisphere.jpg"></a-sky>
</a-scene>

  <!-- Scripts -->
  <script src="scripts/index.js"></script>
</body>
</html>
~~~~

**Comment by dsinni** [comment]
I can confirm that this is an issue, both when trying to sync the animations with the component itself, and when triggering the animations via emitted events from within a throttled `tick` handler.

The synchronization using `setInterval` was actually significantly more accurate.

**Comment by ngokevin** [comment]
Well for one, the code is using `a-animation` which no longer exists. Can use animation component `startEvents`. There's also the animation-timeline component.

**Comment by dmarcos** [comment]
I don't think there's anything actionable on A-Frame side. You can use `animation-timeline` as suggested. If you have any issues with it I encourage opening a question on [StackOverflow](https://stackoverflow.com/questions/tagged/aframe). Nice folks there to help.
