### ISSUE TITLE
Demo Aframe Scene Error in Homepage aframe.io, Aframe master and 0.9.0 crash

### ISSUE THREAD

**Issue by albirrkarim** [aframevr/aframe#4098]
Your homepage error,

## Aframe master error:
This is the error information, on chrome console

docsearch.min.js:2 Uncaught Error: Error: No input element in the page matches .docs-search-sidebar .search-field
    at Function.checkArguments (docsearch.min.js:2)
    at new DocSearch (docsearch.min.js:2)
    at Factory (docsearch.min.js:2)
    at (index):326
device.js:5 Uncaught TypeError: navigator.xr.requestDevice is not a function
    at Object.<anonymous> (device.js:5)
    at Object.173._process (device.js:141)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.176../bind (index.js:6)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.149.../package (index.js:25)
    at s (_prelude.js:1)
    at e (_prelude.js:1)

![image](https://user-images.githubusercontent.com/29292018/54909785-88d7ca00-4f1d-11e9-9687-e0157e58e462.png)

## Aframe 0.9.0 also error

- A-Frame Version: "/dist/aframe-master.min.js"
- Platform / Device: Linux Xubuntu 18.04.2 (Desktop) / Chrome browser Version 73.0.3683.86 (Official Build) (64-bit) / Lenovo G40-45

- Reproducible Code Snippet or URL: 
https://glitch.com/edit/#!/west-actor?path=views/index.html:5:4
https://aframe.io/

**Comment by dmarcos** [comment]
Have you enabled WebXR in `chrome:settings`? `navigator.xr` should not be available by default

**Comment by albirrkarim** [comment]
![Selection_048](https://user-images.githubusercontent.com/29292018/54974845-f2141780-4fc7-11e9-8671-51e59ab76e5f.png)

@dmarcos 
I have disable it, but still error

![image](https://user-images.githubusercontent.com/29292018/54974892-1b34a800-4fc8-11e9-9452-3d2911dc694a.png)

**Comment by albirrkarim** [comment]
Solved when I "Reset all to default"
![image](https://user-images.githubusercontent.com/29292018/54975560-0527e700-4fca-11e9-90ce-3aa0d59ac9cb.png)
and enable webVR
