### ISSUE TITLE
Aframe won't display in win10 desktop chrome Google Chrome Version 73.0.3683.86 (Official Build) (64-bit) version aframe 9. 

### ISSUE THREAD

**Issue by stevel4857** [aframevr/aframe#4102]
![Untitled-1](https://user-images.githubusercontent.com/376910/55072176-056ac580-5050-11e9-86f1-b0ee7e4061f2.jpg)
**Description:**

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by stevel4857** [comment]
Hello VR shows blank page.

**Comment by stevel4857** [comment]
I am using Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by stevel4857** [comment]
I did notify Google Chrome also just in case it's them.

**Comment by stevel4857** [comment]
I tried aframe version 5 from an old file and it also throws three.js errors. I do have most WebVR and XR flags on.

**Comment by dmarcos** [comment]
Click `Reset all to default` in chrome://flags/

More context in https://github.com/aframevr/aframe/issues/4087
