### ISSUE TITLE
event-set__enter not working with aframe 0.9.0.

### ISSUE THREAD

**Issue by lschatzkin** [aframevr/aframe#4104]
When I update to 0.9.0 from 0.8.2, event-set__enter no longer functions. I've made sure I have the latest version of aframe-event-set-component.js.

When I inspect the element, I no longer even see the event_set component listed.  Attached are screenshots from 0.8.2 and 0.9.0 versions of my project, respectively.

![event-set](https://user-images.githubusercontent.com/852512/55351650-bec40380-5473-11e9-8c27-c427c6d0be2c.png)
![no-event-set](https://user-images.githubusercontent.com/852512/55351656-c2f02100-5473-11e9-9933-dfe553fbda8a.png)

**Comment by dmarcos** [comment]
Thank you. Would you mind reopening in the repo where the component code lives? https://github.com/supermedium/superframe/issues
