### ISSUE TITLE
Feature Request Support DIY controllers

### ISSUE THREAD

**Issue by yuripourre** [aframevr/aframe#4108]
Hey guys, thank you for this awesome framework!

I am making DIY VR controllers (and I know [I'm not alone](https://github.com/TrueOpenVR/TrueOpenVR-DIY/blob/master/Controllers/Controllers.md)). This request might be useful to create input scenarios too.

I am trying to use these controllers with AFrame but I am having some issues.

What I achieved so far:

- [X] Fake Gamepad API events
- [X] Fake Gamepad API (extension) events with pose
- [ ] Fake AFrame events

A simple [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API) example could recognize a "fake" gamepad using this code:
```js
function connectGamepad(gamepad) {
  var event = new Event("gamepadconnected");
  event.gamepad = gamepad;
  window.dispatchEvent(event);
}
```

But when I try to call "controllerconnected", AFrame does nothing.

I tried to call it using: 
`window.AFRAME.components["hand-controls"].dispatchEvent(event);`
and
`window.dispatchEvent(event);`

```js
function connectGamepad(gamepad) {
  var event = new Event("controllerconnected");
  event.gamepad = gamepad;
  window.dispatchEvent(event);
}
```

Can you help me with that? There is a better way to do this, instead of creating fake events?

**Comment by dmarcos** [comment]
If your controller is reported through the gamepad API you need to create controls specific to your device. Similar to [vive-controls](https://github.com/aframevr/aframe/blob/master/src/components/vive-controls.js)

**Comment by yuripourre** [comment]
Thank you @dmarcos for a direction, I will take a look on that.

**Comment by yuripourre** [comment]
Just an update, I could successfully add my controllers overriding navigator.getGamepads() function.

**Comment by dmarcos** [comment]
Thanks for sharing
