### ISSUE TITLE
SteamVR + Firefox: VRDisplay is undefined when a-scene plays

### ISSUE THREAD

**Issue by johnshaughnessy** [aframevr/aframe#4110]
**Description:**
In desktop Firefox, the most recent version of steamvr seems to cause the `a-scene` to throw an error and the app fails to start after that.

I think this line:
```
utils.device.getVRDisplay().isPresenting
```
needs to guard on whether the VR display exists, i.e.
```
utils.device.getVRDisplay() && utils.device.getVRDisplay().isPresenting
```
at https://github.com/aframevr/aframe/blob/e3352177f6312551e1855bec68a2e763723a7698/src/core/scene/a-scene.js#L635

I am not sure what changed in SteamVR but it seems like this could happen for any device. Perhaps it was introduced after this patch : https://github.com/aframevr/aframe/commit/a3ac58e4084053c14706abc6ef37bde45086a33e

- A-Frame Version: I guess 0.9.0 ? It's in the latest version of the code as of this writing.
- Platform / Device: Desktop Firefox
- Reproducible Code Snippet or URL: Update to latest SteamVR then run in firefox

**Comment by dmarcos** [comment]
Does this reproduce in master too?

**Comment by PlumCantaloupe** [comment]
Also to note I have seen a similar error here when testing on the Oculus GO with the logs described in this PR with master and the PR ( #4107 ) but it didn't prevent me from entering VR, that I remember.
