### ISSUE TITLE
Camera Wrapper quaternions  rotation bug

### ISSUE THREAD

**Issue by yingbo-chen** [aframevr/aframe#4111]
**Description:**

- A-Frame Version: 0.9
- Platform / Device: PC chrome
- Reproducible Code Snippet or URL:

When wrapping camera in entity 
```
<a-entity id="CameraWrapper">
  <a-camera id="camera"></a-camera>
</a-entity>
```
while moving the camera with Threejs's  ```Object3D.quaternion.set(x,y,z,w)```  when pitching along x axis, the camera rolls forward-down in position instead of just rotating. 

if I set the target to #camera instead of CameraWrapper, the camera movement is correct, however, this causes some visual glitches.

**Comment by dmarcos** [comment]
Do you have a link to reproduce? Not fully understand the problem but what you're seeing might be expected. CameraWrapper will be used as the pivot point for the rotation. If you have a position applied to `<a-camera>` this is what will happen.

![pivot](https://cl.ly/ba7f47f8012e/Image.jpg)

Apply position and rotation to camera wrapper. Be mindful of rotation composition of the camera and wrapper (especially in VR mode to avoid motion sickness).

```
<a-entity id="CameraWrapper">
  <a-entity camera look-controls></a-entity>
</a-entity>
```

**Comment by yingbo-chen** [comment]
Thank you , I have figured it out that the camera applied 1.6 in y automaticly . rotation and positioning the wrapper made a pivot off the camera wrapper.
