### ISSUE TITLE
`isGearVR()` is returning true for Oculus Go

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#4112]
**Description:**
`AFRAME.utils.device.isGearVR()` returns `true` for Oculus Go, which is causing some confusion.

Oculus Go has its own utility detection method:
`AFRAME.utils.device.isOculusGo()`

- A-Frame Version: `0.9.0`
- Platform / Device: Oculus Browser / Oculus Go
- Reproducible Code Snippet or URL:

**Comment by dsinni** [comment]
For anyone who may need a fix for this right now, you can do the following to check for Gear and Go:
```js
const isGear = AFRAME.utils.device.isGearVR();
const isGo = AFRAME.utils.device.isOculusGo();

if ( isGear && isGo ) {
  console.log('This is Go!');
}

if ( isGear && ! isGo ) {
  console.log('This is Gear!');
}
```

**Comment by ngokevin** [comment]
Should fix: https://github.com/aframevr/aframe/pull/4033
