### ISSUE TITLE
Laser-controls GearVR touch pad press not triggering event (trigger button works)

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#4124]
**Description:**
The touch pad press does not emit mousedown, mouseup or click events. It worked with a-frame 0.8.2

- A-Frame Version: 0.9.0
- Platform / Device: GearVR
- Reproducible Code Snippet or URL: https://glitch.com/~brawny-pig

**Comment by dmarcos** [comment]
What browser?

**Comment by weddingdj** [comment]
Oculus browser

**Comment by ngokevin** [comment]
it changed to trigger.

you can copy / paste the component and change to trackpad if you like https://github.com/aframevr/aframe/blob/master/src/components/laser-controls.js#L86

**Comment by weddingdj** [comment]
Ok, but in Gear VR all other interactions can be either made with trigger or trackpad press. I think it is weird to only have the trigger only. Was there a reason for that?

**Comment by ngokevin** [comment]
Apps might want to use the trackpad to do things other things versus redundant button. No configuration is going to satisfy 100% of use cases, if it doesn't work, you can modify the component.

**Comment by weddingdj** [comment]
Thanks for your answer. I know that custom configuration is always possible, but I think it is confusing to not have a trackpad press available per default. If you hold the controller, it is more natural (at least for me) to click on the trackpad because it is similar to a mouse button click. To use the trigger beneath the trackpad is unusual, at least for me (I have no gun ;-)). 

But apps can still use the trackpad to do other things, even if a trackpad press triggers a click event in laser-controls.

Anyways, it would be cool to have the trackpad press in laser-controls again in master.
