### ISSUE TITLE
Link component navigation not working

### ISSUE THREAD

**Issue by weddingdj** [aframevr/aframe#4125]
**Description:**
If I click in Firefox (Desktop PC) on the box in the example below, the link does not work. If I use laser-controls in Oculus Browser in Gear VR the link does not work.

- A-Frame Version: 0.9.0
- Platform / Device: Firefox (Desktop PC) and Oculus Browser (Gear VR)
- Reproducible Code Snippet or URL: https://glitch.com/~brawny-pig

**Comment by dmarcos** [comment]
Two problems:

1. The `box` mixin is not applied to the entity that has the link component and hence ignored by laser-controls.
2. For in-vr navigation you have to link to non iframed WebVR experiences. Any of the [A-Frame examples will do](https://aframe.io/aframe/examples/)

Corrected glitch: https://glitch.com/~fringe-house

**Comment by weddingdj** [comment]
My issue in my app was that the link component was at a child entity and only the parent entity had the `collidable` class which the raycaster was looking for. This worked in v0.8.2 but not in v0.9.0. I added the `collidable` class to the child entity as well, and now it works. Thanks.
