### ISSUE TITLE
How to modify self-adaption ratio

### ISSUE THREAD

**Issue by leonsaber** [aframevr/aframe#4128]
**Description:**

How to make Aframe working on 2560x720(32:9) resolution? It now has a severe stretching phenomenon. Thank you very mcuh!
 
- A-Frame Version: 8.2.0
- Platform / Device: Android Chromium

**Comment by dmarcos** [comment]
What device? Do you have a link to reproduce? What do you mean by stretching? Can you share a screenshot of what you see? Is in 2D or VR mode? In 2D you can control the [camera FOV](https://aframe.io/docs/0.9.0/components/camera.html#properties_fov)

**Comment by leonsaber** [comment]
It's a customize AR device, which can working on VR mode. 

fov: 40,
interLensDistance: 0.063,
baselineLensDistance: 0.0315,
screenLensDistance: 0.20,
distortionCoefficients: [0, 0],
inverseCoefficients: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Please see screen shot, contents are squashed when it running on VR mode, actually these contents are equilateral cubes
<img width="1282" alt="Screen Shot 2019-04-18 at 1 21 37 PM" src="https://user-images.githubusercontent.com/11318667/56389135-9cedaf00-61dd-11e9-9e7b-1405ec251e2a.png">

**Comment by dmarcos** [comment]
Without access to the device will be hard to investigate. Where are those numbers coming from? Does the browser in your device implements the WebVR API? The camera information is passed to A-Frame and just applied. You would have to look into the numbers returned by the WebVR API and check if they make sense for your lenses, optics system.

**Comment by leonsaber** [comment]
Thank you dmarcos.
