### ISSUE TITLE
failed load object model mtl/obj file in Vue

### ISSUE THREAD

**Issue by harmnot** [aframevr/aframe#4131]
I have asked on Stackoverflow for my this problem but still doesnt get any answer, 

I have a modelling based in mtl and object 
on my plain HTML file it was working nice, but when I used on vue js, on a component, it doestnt  show and work 
the error i got is **Uncaught Error: THREE.OBJLoader: Unexpected line: "< !DOCTYPE html>"**

this is my asset item object in a-asset of a-scene 

```
<a-assets>
        <a-asset-item id="model-obj" src="./sofa-obj/sofa.obj"></a-asset-item>
        <a-asset-item id="model-mtl" src="./sofa-obj/sofa.mtl"></a-asset-item>
</a-assets>
```

and I call this modelling something like this 

  ```
<a-entity
                position="0 1 -6"
                obj-model="obj: #model-obj; mtl: #model-mtl"
                animation="property: rotation; direction: normal;to: 0 360 0; loop: true; dur: 10000; easing:linear;repeat: indefinite; fill:forwards">
    </a-entity>
```

it also get warning for CORS aswell, my inspect on my client keep red, :( I don't know this is happen :( 

is there any kind suggestion to fix this? am I wrong ??

**Comment by dmarcos** [comment]
You did the appropriate thing. We use Github only for for bugs and feature requests. StackOverflow will get more visibility. From the dev team and in general we discourage combining A-Frame with other frameworks like React, Angular or Vue. They were designed for different purposes and have lifetime management and initialization cycles that might be at odds with real time 3D applications.
