### ISSUE TITLE
Camera in VR mode

### ISSUE THREAD

**Issue by MaxwallXXL** [aframevr/aframe#4132]
**Description:**
If I really want modfiy Camera L&R angle. How should I can do in aframe.js?
- A-Frame Version:
0.8.0
- Platform / Device:
Android 
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Can you elaborate? What do you mean by L&R angle? What's your use case? What device are you targeting?

**Comment by MaxwallXXL** [comment]
I mean  left side camera and and  right side camera angle in VR mode the device is cardboard. when I enter vr mode, the content I saw has a superimposed ghost image. so I think may be through modify camera left and right maybe help.

**Comment by dmarcos** [comment]
What device? What do you mean by superimposed ghost image? Can you share a screenshot? The cardboard configuration for each device is contained in the [dpdb.json file](https://github.com/immersive-web/webvr-polyfill-dpdb) used by the [WebVR Polyfill](https://github.com/immersive-web/webvr-polyfill). You can try adding your device configuration to the dpdb.json and build your own A-Frame and WebVR Polyfill custom builds.

**Comment by MaxwallXXL** [comment]
My phone is razer which can not dectect on http://useragentstring.com. do we have easy way to modfiy shift angle in vr mode?
