### ISSUE TITLE
entity reAttach bug

### ISSUE THREAD

**Issue by Moon-ChangHyun** [aframevr/aframe#4133]
**Description:**
when i remove and reattach an entity, it's object is not rendered. And the el of that object is emptied to null. And the type of material of that object is changed to meshBasicMaterial as origin type is meshStandardMaterial. But the getAttribute('material') return same value.

- A-Frame Version: 0.9.1
- Platform / Device: all
- Reproducible Code Snippet or URL: https://jsfiddle.net/a9Lfvz4k/3/

**Comment by dmarcos** [comment]
[We recommend reparenting at the THREE.js level Attaching / reattaching](https://stackoverflow.com/questions/52318200/change-parent-of-component-and-keep-position) and re initializing components is costly and not always reliable (components have to account for a complex costly scenario that is relatively rare)
