### ISSUE TITLE
iOS 12.2 video HLS Wrong Color / Occasional black screen

### ISSUE THREAD

**Issue by fyuvb** [aframevr/aframe#4134]
Recently iOS version 12.2 was pushed to everyone and it seemed to break video playback of aframe.

Problem 1: Color not mapped correctly
iOS seemed fixed the color BRGA problem since iOS 11 for native HLS, [link](https://bugs.webkit.org/show_bug.cgi?id=179417) . However, aframe still apply the **ios10hls** shader for playback on iOS native hls. This is messing up the colors to a wrong one. Using standard "flat" shader should be good enough for color. 

Problem 2: Native HLS occasional black screen upon video Playback.
I have provided a sample code snippet. There is a certain chance such that canvas would display black screen. One finding is that when you change device orientation or enter / exit VR mode, the playback would become normal again. Could anyone advice how to fix this? Thanks!

Another thing that I found is that, some videos cannot play on iOS 12.2, like this one: https://github.com/mrdoob/three.js/raw/dev/examples/textures/sintel.mp4. While the example of aframe still works: https://aframe.io/examples/showcase/videosphere/. This is similar to Problem 2 that orientation change or enter / exit VR mode could put the playback back to normal. Could anyone advice? 

- A-Frame Version: 0.9.1
- Platform / Device: iOS 12.2 Safari
- Reproducible Code Snippet or URL:

```
<html>
  <head>
    <script src="https://aframe.io/releases/0.9.1/aframe.min.js"></script>
    <style>
      #overlay {
        position: absolute;
        z-index: 1;
        top: 0;
        left: 0;
        width: 100%;
        height:100%;
        display: flex;
        align-items: center;
        justify-content: center;
        opacity: 1;
        background-color: #000000;
        color: #ffffff;
      }
      #overlay > div {
        text-align: center;
      }
      #overlay > div > button {
        height: 20px;
        width: 100px;
        background: transparent;
        color: #ffffff;
        outline: 1px solid #ffffff;
        border: 0px;
        cursor: pointer;
      }
      #overlay > div > p {
        color: #777777;
        font-size: 12px;
      }
    </style>
  </head>
  <body>
    <a-scene>
      <assets>
        <video id="video" loop crossorigin="anonymous" webkit-playsinline src="https://bitmovin.com/player-content/playhouse-vr/m3u8s/105560.m3u8">
        </video>
      </assets>
      <a-videosphere src="#video" rotation="0 -90 0"></a-videosphere>
    </a-scene>

    <div id="overlay">
      <div>
        <button id="startButton">Click to Play</button>
        <p>Automatic video playback with audio requires a user interaction.</p>
      </div>
    </div>

    <script>
      var overlay = document.getElementById('overlay');
      var startButton = document.getElementById( 'startButton' );
      var video = document.getElementById('video');
      startButton.addEventListener( 'click', function () {
        video.play();
        overlay.style = 'display:none';
      }, false );
    </script>

  </body>
</html>
```

**Comment by esterlus** [comment]
can confirm that the `ios10hls` shader is no longer necessary.

**Comment by agosman** [comment]
I'm also experiencing problem #2: a-videospehere showing only black. (iPhone SE, iOS 12.3.1)
After rotating my device, the video always shows up immediately. 
Any advice on how to fix this woud be much appreciated.

**Comment by vkolova** [comment]
I suspect this is what 'fixes it' when rotating the device:

https://github.com/aframevr/aframe/blob/9785b6cd23eefec6113601ff28e91204c57c0c48/src/core/scene/a-scene.js#L141-L152

Calling `.resize()` on the scene didn't fix anything, though.

Any ideas if this is the right direction?

**Comment by konstantin55000** [comment]
Hello, have very same problem on ios 12.4.1 any latest major browser including Safari
Seams like red color have dropped away, so video on videosphere is only with blue yellow..
Does have any ideas how to fix that problem, or any demo's with videosphere where it work?

**Comment by Kulwinder-nvl** [comment]
Can confirm that HLS video does not play on IOS 12.4.1. Video color is different or just show a black screen. Same video works fine on OS under A-frame scene.

**Comment by andreyrd** [comment]
Seems like the call to `renderer.setSize()` is what fixes it on rotate:
https://github.com/aframevr/aframe/blob/9785b6cd23eefec6113601ff28e91204c57c0c48/src/core/scene/a-scene.js#L557

For some reason, the canvas is too small until you start playing the video? Not sure what's going on there, but my quick hack for now is this:

```js
      // Hack to fix bug with aframe & iOS video
      // https://github.com/aframevr/aframe/issues/4134
      function videoHackListener () {
        setTimeout(function () {
          $scene.renderer.setSize($scene.canvas.width, $scene.canvas.height);
        }, 500); // ugly but aframe's 100ms was not enough in my testing
        $video.removeEventListener('play', videoHackListener);
      }
      $video.addEventListener('play', videoHackListener);
```
where `$scene` is a reference to your `<a-scene>` and `$video` is a reference to your `<video`.

**Comment by andreyrd** [comment]
Turns out you should NOT do that, because while it works, it keeps making the renderer bigger and bigger until it eats all performance.

**Comment by antiantivirus** [comment]
I'm also experiencing the same issue with red channel not visible. Seems to be linked to `ios10hls`

**Comment by antiantivirus** [comment]
Is a-frame still applying the ios10hls shader on ios devices? I've had to revert to B&W video on mobile for the time being. Is there a fix that might be implementable for the red channel issue?

**Comment by fabien-lg** [comment]
I fixed it by creating a small component for `videosphere` that listens to `materialvideoloadeddata` and puts back the `flat` shader. `flipY` needs to be re-applied on the texture too.

**Comment by antiantivirus** [comment]
Ah nice, would you be able to share the code for this? Maybe we should bring this to attention of a-frame devs as something that needs a fix?

**Comment by fabien-lg** [comment]
@antiantivirus I'm using typescript:

```import { ComponentWrapper } from 'aframe-typescript-toolkit';
import * as THREE from 'three';

interface VideoSphereShaderSchema {
}

export class VideoSphereShader extends ComponentWrapper<VideoSphereShaderSchema> {
    constructor() {
        super('videosphere-shader', {});
    }

    public init() {
        this.el.addEventListener('materialvideoloadeddata', (e: any) => {
            console.log(e);
            this.el.setAttribute('material', 'shader', 'flat');
            e.detail.texture.flipY = true;
        });
    }
}

new VideoSphereShader().register();
```

And on the VideoSphere:

```
        <a-videosphere
            src="#video"
            videosphere-shader
        ></a-videosphere>
```

**Comment by antiantivirus** [comment]
cheers fabien. slightly adapted the code to make it regular old javascript. make sure you register the component in the header so that it's available to aframe when the a-scene loads.

```
      AFRAME.registerComponent('video-fix', {
        init: function(){
          let el = this.el;
          el.addEventListener('materialvideoloadeddata', e => {
            el.setAttribute('material', 'shader', 'flat');
            e.detail.texture.flipY = true;
            // this.detail.texture.flipY = true;
          })
        }
      });
```

and then on a component add the attribute `video-fix`

**Comment by b0ot** [comment]
As of today, I had the issue where the colors were off for HLS video. I applied the ios-video-fix component to the videosphere and it seems like it is working now. Thank you! 
Hopefully this fix gets incorporated into the AFrame codebase.
