### ISSUE TITLE
Exit Full Screen `TypeError: document not active`

### ISSUE THREAD

**Issue by sanjay-bhuva** [aframevr/aframe#4136]
**Description:**

- A-Frame Version: 0.9.0
- Platform / Device: Windows/Chrome 73.0.3
- Reproducible Code Snippet or URL: Not able to reproduce

I am not able to reproduce the issue but it's reported on bugsnag. It looks like issue occures when an user tries to exit full screen. Please find the attachment for more details. Any help would be appreciated. Thanks!

 ![document-not-active](https://user-images.githubusercontent.com/32540473/56687724-920eaf00-66f4-11e9-92cc-7fbed42ca26e.png)

**Comment by dmarcos** [comment]
Is it with WebVR or WebXR? What headset? What’s the error on console? Do you have a link where you saw the error?

**Comment by sanjay-bhuva** [comment]
@dmarcos it's in WebVR. I can also reproduce now with Linux/Chrome 74.0.3729.108. Error occures, when an user clicks on exit VR. Here is the console output.

![Screenshot from 2019-04-25 20-46-35](https://user-images.githubusercontent.com/32540473/56747561-d4d79200-679b-11e9-86b6-a90de51ea4cf.png)

**Comment by sanjay-bhuva** [comment]
@dmarcos here is the codepen having same issue - https://codepen.io/khlevon98/full/GzObKR

**Repro Steps:**

1. Go to -  https://codepen.io/khlevon98/full/GzObKR
2. Click on enter VR icon at bottom right
3. Press ESC to exit from full screen
4. See the console output.
