### ISSUE TITLE
Sound component startTime doesn't work since Aframe 8

### ISSUE THREAD

**Issue by smeybi** [aframevr/aframe#4166]
I'm not sure if it is a issue or it does not use it that way anymore.

It works with Aframe 7 to start a sound at a certain time with startTime. 
With Aframe 9.2 doesn't work, also since Aframe 8.
document.querySelector('#soundtest').components.sound.pool.children[0].startTime=5;
It starts at 0.

With offset starts at the certain time.
document.querySelector('#soundtest').components.sound.pool.children[0].offset=5;

Here is the demo:
https://glitch.com/~aframe-sound-component-starttime-demo

**Comment by dmarcos** [comment]
Not sure what you are trying to accomplish. Two options:

 - If you are trying to start the sound from a specific time wait for the scene to load: https://glitch.com/edit/#!/thread-particle?path=index.html:12:6 

- If you are trying to control when the sound starts playing use the [on property](https://aframe.io/docs/0.9.0/components/sound.html#properties_on) and fire the event when desired:  https://glitch.com/edit/#!/jet-lathe

**Comment by ngokevin** [comment]
Issue seems legitimate to me. Start a sound at a certain point.

**Comment by ngokevin** [comment]
Never mind, I see the Glitch.

**Comment by smeybi** [comment]
Yes, start a sound at a certain point, not on begin. For example, if the sound is 30 seconds, it should start at 10 seconds. Earlier(A 7), it worked with .startTime, now it does not work anymore. I noticed during update. I found out that it works with .offset, but I think .startTime should be for it.

**Comment by ngokevin** [comment]
@smeybi Yeah, in your example, I think it's because you need to wrap that code within a component and run it ideally after the sound component initializes (e.g., `play` handler should do it).

**Comment by smeybi** [comment]
Ah, ok!
