### ISSUE TITLE
PMD/PMX/VMD support with no external components

### ISSUE THREAD

**Issue by kurai021** [aframevr/aframe#4168]
Is possible to include support for this model objects with no external components and positional sound support? Takahirox made [a component](https://github.com/takahirox/a-mmd) that supports these formats a few years ago, but is no longer developing it and it would be interesting to have this feature within A-Frame

**Comment by dmarcos** [comment]
Thanks for filing. Those formats are not
very commonly used and support is better served with a 3rd party component. If Takahiro is not supporting the component anymore someone else can jump and help.
