### ISSUE TITLE
Fatal error if adding a new default camera in 0.9.2

### ISSUE THREAD

**Issue by andrewrutter** [aframevr/aframe#4170]
I am trying to update a project to 0.9.2 to see if it resolves another tweening issue we have but am running into the following fatal error when the scene loads:

core:a-node:error Failure loading node:   DOMException: Failed to execute ‘removeChild’ on ‘Node’: The node to be removed is not a child of this node.
   at removeDefaultCamera (http://localhost:8000/commons.js:88898:11)

I am just doing the following in the scene, is there a change needed in 0.9?

```
          <a-entity id="rig" rotation="0 90 0">
            <a-camera
              id="camera"
              look-controls
              data-aframe-default-camera
            />

          </a-entity>
```

**Comment by dmarcos** [comment]
The default camera is an aframe injected element. Not meant to be added by an application. Add a regular camera and don’t use self closing tags:

  <a-camera id=camera></a-camera>

No need to add look-controls component manually either they are built-in the primitive.
