### ISSUE TITLE
aframe 0.8.2 load VR as magic window/novr headset/ enter in vr without split screen

### ISSUE THREAD

**Issue by ks1505** [aframevr/aframe#4174]
**Description:**
I dont want to use normal magic window since some elements are not working in it since they are using raycaster through camera and that are working in vr mode so I want to enter the vr mode directly but not in split screen but like a magic window currently I am using this to directly enter the vr mode but i don't want to split screen 
document.querySelector('a-scene').enterVR()
- A-Frame Version: 0.8.2
- Platform / Device: Android 9.0  Pocophone F1 Google Chrome (latest version)

**Comment by dmarcos** [comment]
Not sure I understand the problem. Magic window mode should work at page load. The camera should move with the phone motion and rendering is mono. `Enter-VR` button triggers stereo mode and [you can disable it](https://aframe.io/docs/0.9.0/components/vr-mode-ui.html#sidebar)

Notice that latest version of Chrome and Safari on iOS come with `devicemotion` disabled by default. The user has to enable manually in `chrome://flags` and content has to be served via `https`. More info here: https://github.com/aframevr/aframe/issues/3976

Can you be more specific on what you mean by `some elements are not working`?

**Comment by ks1505** [comment]
i am using raycaster from camera element to change an objects position but whenever i am changing the position the object shows transparent triangles all over it but that doesnt happen in vr mode thanks for the link it solved the problem 💯 👍

**Comment by ks1505** [comment]
<a-scene vr-mode-ui="enabled: false"></a-scene> isn't working it doesnt even enter the vr mode now

**Comment by dmarcos** [comment]
A-Frame examples work fine for me on iPhone X and Pixel 3:

https://aframe.io/aframe/examples/

**Comment by ks1505** [comment]
I want to enter in vr without stereo mode

**Comment by dmarcos** [comment]
You can remove the `enter-vr` button and rely on magic window mode.

**Comment by ks1505** [comment]
I dont know why but it works as expected after exiting VR mode but not from the beginning it needs to enter VR once to work
