### ISSUE TITLE
AFrame 0.9.0 cubemaps don't apply to the first entity they're used on

### ISSUE THREAD

**Issue by whycobb** [aframevr/aframe#4175]
**Description:**

- A-Frame Version: 0.9.0
- Platform / Device: 
- Reproducible Code Snippet or URL:
`<a-entity id="Box1" geometry="primitive: box" position="1 0 0" material="color: #ffcccc; metalness: 1; envMap: #MyCube; roughness: 0.1"> </a-entity>`
`<a-entity id="Box2" geometry="primitive: box" position="-1 0 0" material="color: #ccffff; metalness: 1; envMap: #MyCube; roughness: 0.1"> </a-entity>`

Box2 is illuminated by the cube map, but Box1 isn't. If I add a Box0 earlier in the code than Box1, then Box1 gets the cube map but Box0 doesn't.

Opening the inspector fixes it, even after the inspector is closed, but the cube map is lost again if the page is reloaded.

**Comment by dmarcos** [comment]
Can you share link to complete example to reproduce?

**Comment by whycobb** [comment]
[Here](https://whycobb.github.io/AFrameCubemapBug/)

There's a Box0 that can be uncommented, to show that the problem isn't somehow inherent to Box1.

**Comment by whycobb** [comment]
My bad, I didn't realize I was behind on my AFrame version. This is fixed in 0.9.2.
