### ISSUE TITLE
Google Cardboard on iPhone

### ISSUE THREAD

**Issue by bistek** [aframevr/aframe#4178]
My goal is to use A-Frame on all possible devices, including Google Cardboard on Android and iPhone.

I've tested many a-frame scenes available on the web and on the main aframe.io repository, and I have reproduced some of them on my server, and I cannot understand why sometimes they work on Google Cardboard / iPhone and some other times not. In general the problem is that, when seen in the classical browser, rotation is allowed only horizontally, and in Cardboard it is completely locked.

For instance...

This works: https://apps.npr.org/rockymountain-vr/

The "helloworld" example works when run from your server, but when I clone it on my web page it does not: https://aframe.io/examples/showcase/helloworld/

This does not work: http://cms-aframe.web.cern.ch/

It looks like there is an issue if the scene is on a different server with respect to yours?

Thanks very much!

- A-Frame Version: all
- Platform / Device: Google Cardboard on iPhone
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Unfortunately, Chrome and Safari ship now with `devicemotion` API disabled by default. The user has to enable manually and content has to be served over `https` (notice that the CERN url is served over http). More info: https://github.com/aframevr/aframe/issues/3976

**Comment by bistek** [comment]
Hi, I transferred my test page to a https server and allowed motion and orientation on Safari on my iPhone, and it works like charm! Suggestion: tell this in places where inexperienced users might find it, like in A-Frame School etc.
Thanks very much for this incredibly useful tool!
