### ISSUE TITLE
Look controls are busted on mobile on localhost application

### ISSUE THREAD

**Issue by NFavareto** [aframevr/aframe#4179]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: Mobile
- Reproducible Code Snippet or URL: https://aframe-teste.herokuapp.com/

In localhost the look controls in vr scene, doesn't work, but the same scene in   https://aframe-teste.herokuapp.com/  the look controls  work in mobile device.

**Comment by dmarcos** [comment]
Unfortunately, Chrome and Safari ship now with devicemotion API disabled by default and content has to be served over `https`. More info https://github.com/aframevr/aframe/issues/3976

**Comment by NFavareto** [comment]
Oh! Thanks!
