### ISSUE TITLE
TypeError: Document not active after exiting full screen

### ISSUE THREAD

**Issue by sumleo** [aframevr/aframe#4180]
**Description:**

- A-Frame Version: 0.9.0
- Platform / Device: Version 74.0.3729.157 (Official Build) (64-bit)
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/videosphere/

Prove:
![image](https://user-images.githubusercontent.com/29517764/58153297-43c3e000-7ca1-11e9-86e9-a1786183a3be.png)

Reproduce:
1. Go to the URL
2. Click the button into full screen mode
3. Press Esc to exit full screen

**Comment by dmarcos** [comment]
Use A-Frame 0.9.2 You are in an old version. We can reopen if problem persists
