### ISSUE TITLE
Maximum call stack size exceeded after exiting WebVR emulator

### ISSUE THREAD

**Issue by sumleo** [aframevr/aframe#4181]
**Description:**

- A-Frame Version:  A-Frame Master
- Platform / Device: Chrome Version 74.0.3729.157 (Official Build) (64-bit)
- Reproducible Code Snippet or URL: https://apainter.webxrexperiments.com/

Prove:
![image](https://user-images.githubusercontent.com/29517764/58157432-dd43bf80-7caa-11e9-9b7b-a458da58197b.png)

Reproduce:
1. Open the url
2. Open WebVR (https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil?hl=en)
3. Activate HMD -> Disable HMD -> Crash

**Comment by dmarcos** [comment]
Last update of the emulator was in 2016. Most likely that emulated API is outdated

**Comment by sumleo** [comment]
I will test it with other device later. Thx. Btw I filed another issue.

**Comment by sumleo** [comment]
I retry it on MacOS with Chrome. It still crashes.

**Comment by dmarcos** [comment]
I’m not surprised there are quirks with the emulator. It’s an old code base probably not reliable as a tool as this point. Best is to file an issue on the project or reach out the maintainers
