### ISSUE TITLE
Failure loading node

### ISSUE THREAD

**Issue by RihabAlrefae** [aframevr/aframe#4186]
**Description:**

- A-Frame Version:0.8.2 (Date 2018-10-29, Commit #ebbc522e)
- Platform / Device: windows/Chrome
- Reproducible Code Snippet or URL:
```
`<script src="https://cdn.jsdelivr.net/gh/gftruj/aframe@3345da413edcee8430981197f1c8d1a636702b01/dist/aframe-master.js"></script>
<script src="../../Scripts/aframe-animation-component.min.js"></script>
<script src="../../Scripts/aframe-event-set-component.min.js"></script>
<script src="../../Scripts/aframe-layout-component.min.js"></script>
<script src="../../Scripts/aframe-template-component.min.js"></script>
<script src="set-image.js"></script>
<script src="../../Scripts/angular.min.js"></script>
<script src="../../Scripts/jquery-3.3.1.min.js"></script>
<script src="AframeAPI.controller.js"></script>
<div id="fulldiv" ng-app="app" ng-controller="AframeAPIController1">
    <a-scene  cursor="rayOrigin: mouse"></a-scene></div>`
```

and the console error is 
`core:a-node:error Failure loading node:   TypeError: l.getComputedAttribute is not a function
    at NewComponent.update (aframe-layout-component.min.js:1)
    at NewComponent.updateProperties (component.js:515)
    at NewComponent.module.exports.Component (component.js:258)
    at new NewComponent (geometry.js:53)
    at HTMLElement.value (a-entity.js:533)
    at HTMLElement.value (a-entity.js:689)
    at HTMLElement.value (a-entity.js:658)
    at entityLoadCallback (a-entity.js:454)
    at emitLoaded (a-register-element.js:17)`

**Comment by dmarcos** [comment]
The error comes from the aframe-layout-component that might be outdated. Best is to open an issue in its repo.

It might not fix your issue but I recommend updating to A-Frame 0.9.2, you are in an old version. You won't need the animation component anymore. A-Frame comes with [a built-in animation component](https://aframe.io/docs/0.9.0/components/animation.html#sidebar)

**Comment by DJPoland** [comment]
I'm getting the same issue when instantiating/constructing a new object with THREE.OrbitControls(). 
```
window.AFRAME.registerComponent('orbit-controls', {
  dependencies: ['camera'],
  
  schema...

  init: function () {
    var el = this.el;
    var oldPosition;
    var camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 1, 10000 );

    // this.controls = new THREE.OrbitControls(el.getObject3D('camera'),
    //                                         el.sceneEl.renderer.domElement);
    *** Issue here: this.controls = new THREE.OrbitControls(camera,
                                            el.sceneEl.renderer.domElement); ***

    oldPosition = new THREE.Vector3();

    this.bindMethods();
    other code .....
  },
.....
```

Im getting the following error only on Microsoft's Edge browser and not firefox or Chrome:  
```
core:a-node:error Failure loading node: TypeError: Object doesn't support this action 
```

Further expanding the issue: 
```
[object Error]: {description: "Object doesn't support this action", message: "Object doesn't support this action", number: -2146827843, stack: "TypeError: Object doesn't support this action at init (http://localhost:8000/dist/aframe-master.js:130207:5) at Component.prototype.initComponent (http://localhost:8000/dist/aframe-master.js:126670:5) at Component.prototype.updateProperties (http://localhost:8000/dist/aframe-master.js:126652:7) at module.exports.Component (http://localhost:8000/dist/aframe-master.js:126428:3) at NewComponent (http://localhost:8000/dist/aframe-master.js:127012:5) at initComponent.value (http://localhost:8000/dist/aframe-master.js:125176:7) at updateComponent.value (http://localhost:8000/dist/aframe-master.js:125339:7) at updateComponents.value (http://localhost:8000/dist/aframe-master.js:125307:9) at entityLoadCallback (http://localhost:8000/dist/aframe-master.js:125093:9) at emitLoaded (http://localhost:8000/dist/aframe-master.js:126021:21)"}
```

**Comment by dmarcos** [comment]
Share a link with a simple test case to reproduce. Hard to tell what's going on.

**Comment by DJPoland** [comment]
I solved the issue. I was registering the component on the bottom of the src/index.js, which was causing an issue with core/a-node.js.

**Comment by dmarcos** [comment]
@DJPoland thanks for the kind works and happy you found a solution. Is it ok if I close the issue?

**Comment by DJPoland** [comment]
@dmarcos of course.

**Comment by dmarcos** [comment]
Thanks

**Comment by k7n4n5t3w4rt** [comment]
>  I solved the issue. I was registering the component on the bottom of the src/index.js, which was causing an issue with src/core/a-node.js. Thanks for trying to help though! I'm really enjoying AFRAME.

@DJPoland Might you be able to elaborate a little? I'm encountering this issue and I'm wondering why "registering the component on the bottom of the src/index.js" was causing a problem.

**Comment by extralooping** [comment]
@k7n4n5t3w4rt I have the same issue. How did you solve it?

**Comment by dmarcos** [comment]
@extralooping I recommend sharing glitch with simple code to reproduce your issue:

https://glitch.com/~aframe

**Comment by k7n4n5t3w4rt** [comment]
@extralooping No, didn't solve it with A-Frame. I switched to https://www.npmjs.com/package/@react-three/fiber and then to just plain three.js.
