### ISSUE TITLE
Samsung Internet for Android is identified as a VR browser, not a mobile browser

### ISSUE THREAD

**Issue by DougReeder** [aframevr/aframe#4187]
**Description:**
AFRAME.utils.device.isMobile() returns true and AFRAME.utils.device.isMobileVR() returns true under Samsung Internet for Android  (Under Samsung Internet for VR, they return the same values, which are correct there.)

- A-Frame Version: 0.9.2
- Platform / Device: Android 7.0,  Samsung Galaxy S6 (SM-G920V)
- Reproducible Code Snippet or URL:
https://juniper-plot.glitch.me/

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/4188
