### ISSUE TITLE
Resizing embedded aframe doesn't trigger renderer resize without window size change

### ISSUE THREAD

**Issue by eyexpo-jeffrey** [aframevr/aframe#4189]
In my situation, I made the embedded aframe inside a div container that the aframe has 100% width and height to the container. When I just change the size of the container and keep the window size unchange, the aframe renderer does not get resizing and the model inside aframe get weird. Is there any way that I can trigger the renderer resize of embedded aframe when I change its size? Thank you.

- A-Frame Version: 0.9.0
- Platform / Device: Desktop

**Comment by dmarcos** [comment]
This is a question appropriate to [StackOverflow](https://stackoverflow.com/questions/tagged/aframe). We use Github for bugs and feature requests. Make sure to share a link to a simple runnable example that illustrates your use case.

**Comment by eyexpo-jeffrey** [comment]
I think it is a aframe bug because the aframe resize function will not be triggered when the embedded aframe size changes. It will only be triggered when the window size changes. May be I am wrong, I am not sure yet. I will find a work around solution to make it work. Thank you.

**Comment by dmarcos** [comment]
I recommend using iframes for embedded scenes that are going to change size dinamically.

**Comment by eyexpo-jeffrey** [comment]
Okay. Thank you for the suggestion.

**Comment by felipenmoura** [comment]
That's very interesting @zodywoolsey and I will try that.
And yes, cursors do NOT work properly after resizing the screen!
I have a button that triggers a `requestFullscreen` call and this makes all the clickable elements useless :/

I even asked this in a stackoverflow question:
https://stackoverflow.com/questions/58827452/hold-the-aframe-arjs-startup

**Comment by dotesfera** [comment]
Is there any fix on this? I'm trying to avoid using an iframe, and this is also happening to me.

**Comment by richardanaya** [comment]
I resolved this by having `a-scene` by width: 100% of its parent element and then:

<a-scene embedded style="height: 0; padding-bottom: 30%;">

This forces the frame to remain the same aspect ratio to its parent element width, here's why it works in more detail:

https://stackoverflow.com/questions/11535827/responsive-height-proportional-to-width/18164974

**Comment by clinuxrulz** [comment]
Call the ```resize()``` method on the a-scene element without any params also fixes it. But not a part of public API.
