### ISSUE TITLE
allow touch control up and down in aframe

### ISSUE THREAD

**Issue by fatimahamiye** [aframevr/aframe#4190]
touch control in aframe scene works only in the left and right, it does not work up and down using a mobile however using the desktop it works perfectly, in mobile, when I added touch control, look control is removed

how to add both of them at the same time

**Comment by dmarcos** [comment]
Limiting panning to the horizontal axis in touch screens is a design decision to keep virtual and real horizons always aligned. You can use [look-controls](https://github.com/aframevr/aframe/blob/master/src/components/look-controls.js#L13) to derive your own component with the functionality you need.

**Comment by marcin-dorosiewicz** [comment]
Sorry. I still can't understand why it's not possible to 'look' up or down on mobile devices?
I'm using Safari/Chrome/Firefox on mobile and my VR image doesn't work as on desktop browsers:

`<div class="vr-image-item">
                <a-scene embedded>
                    <a-sky src="{{ imageUri }}" rotation="0 -20 0"></a-sky>
                </a-scene>
            </div>`

Up and Down controls seems to be working as Left and Right instead.
Thanks for any advice.
