### ISSUE TITLE
White Screen/Blank Screen when loading an A-Frame Scene on iOS

### ISSUE THREAD

**Issue by DJPoland** [aframevr/aframe#4191]
- A-Frame Version: 0.9.2
- three-version: ^0.102..2
- Platform / Device: iPhone X iOS 12.2

A-Frame is not loading properly on iOS in the Safari browser. A simple scene such as: 
```
<a-scene>
    <a-sky src="valid_image.jpg"></a-sky>
    <a-entity></a-entity>
</a-scene
```
will not render. It however works perfectly on android.

This seems to be a WebVR Polyfill issue since many of the warnings are related to "No DPDB device match".

**Comment by dmarcos** [comment]
Can you share a link to a full runnable experience? The a-sky sample in the examples works fine for me on iPhone X / ios 12.3

https://github.com/aframevr/aframe/blob/master/examples/boilerplate/panorama/index.html

https://aframe.io/aframe/examples/boilerplate/panorama/

**Comment by DJPoland** [comment]
After using Safari's developer tools for diagnosing the issue on my iPhone, it's apparently a CORS issue. It's really odd since I'm only encountering this CORS issue on mobile, or more specifically iOS and not android.

**Comment by dmarcos** [comment]
If it’s a CORS issue there’s not much we can do on the A-Frame side. All apps have to comply with the rules browser vendors put in place.

**Comment by DJPoland** [comment]
It wasn't a CORS issue after all. For some reason I'm getting an ``` evaluating 'h.getContext("2d".drawImage' ``` . I discovered the issue in the three.js @ line 20309. Not sure why, but this looks like a three.js issue and not an aframe issue :(.

**Comment by dmarcos** [comment]
Base of your scene on the [A-Frame example](https://aframe.io/aframe/examples/boilerplate/panorama/) that works well on iPhone X for me. Glitch to illustrate:

https://glitch.com/edit/#!/grandiose-child?path=index.html:11:87

If the problem happens with a specific image make sure is valid and it doesn't exceed the maximum size. You can try make it smaller.

I believe there's nothing actionable on the A-Frame side. Closing this and can reopen if necessary

**Comment by usaurabh02** [comment]
Hi, I'm running with same issue. My image is loaded but it shows only white blank screen. Here is the code image and its output.
![image](https://user-images.githubusercontent.com/73464543/220624511-1b83b8a1-48b1-493e-bfe8-3b9b5ae1dbbd.png)
![image_480](https://user-images.githubusercontent.com/73464543/220624562-45298b73-20a2-4db9-a139-6a3eeeaac481.png)

**Comment by dmarcos** [comment]
@usaurabh02 Might want to share a simple runnable example with https://glitch.com/~aframe otherwise hard to know what's going on. best of luck

**Comment by usaurabh02** [comment]
> @usaurabh02 Might want to share a simple runnable example with https://glitch.com/~aframe otherwise hard to know what's going on. best of luck

I'm using Next.js and I have used a material-ui "modal" that takes  image file as input and pass it as URL in the "src" of the a-sky. Here is the full code. 
![image](https://user-images.githubusercontent.com/73464543/220626053-80811db7-0c04-42c7-8679-a4139200609b.png)

**Comment by dmarcos** [comment]
I'm not familiar with React / Next.js if it's a problem with A-Frame it should be reproducible with just A-Frame. In general not having code that people can run and debug it will make it harder to get help.

**Comment by dmarcos** [comment]
@usaurabh02 Also for usage questions I recommend [StackOveflow](https://stackoverflow.com/questions/tagged/aframe) and [Discord](https://discord.com/invite/tGYjkYr). We use github issues for bug reports. Best of luck.
