### ISSUE TITLE
Programmatically making screenshots freezes up aframe

### ISSUE THREAD

**Issue by ShadowMitia** [aframevr/aframe#4197]
**Description:**

Whenever I take a screenshot with the screenshot, aframe freezes up and I get in the console :

```
THREE.WebGLRenderer.render(): the forceClear argument has been removed. Use .clear() instead. three.js:23659:12
THREE.WebGLRenderer.render(): the renderTarget argument has been removed. Use .setRenderTarget() instead. three.js:23652:12
```
This happens when `getCanvas` is called.

If you launch the glitch example, you get a 3D scene, which can drag around.
There's a `setInterval` set for 2 seconds which tries to take a screenshot.
Before that happens the scene can be interacted with. After two seconds, it's all frozen up.

- A-Frame Version: 0.9.2
- Platform / Device: I believe all platforms are affected. Tested on chrome and firefox on Windows 10.
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/dolomite-buffer

**Comment by dmarcos** [comment]
This has been fixed on master:

https://github.com/aframevr/aframe/pull/4169

**Comment by ShadowMitia** [comment]
Sweet, thanks!

**Comment by kowalus23** [comment]
is it fixed? because i having the same issue while using screenshot combination with A-frame 0.9.2 :( on Desktop

**Comment by tharunoptimus** [comment]
I guess it's not. I tried it today and the getCanvas took almost 5 seconds (did with console.time I know it's not accurate but u get the idea) (windows 10 - chrome  108.0.5359)

And the renderer attribute that you can include in a-scene doesn't contribute to the canvas when using screenshot

And it's worst on smartphones (xiaomi 11 lite ne 5g) the phones just gets crashed. Not even the power button works when entering VR while this getCanvas is invoked
