### ISSUE TITLE
Add sound primitive

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#42]
Enables devs to add audio to their scenes.

User can specify:

* Source URL
* Position of sound
* Bounding box and falloff (not sure how to articulate this in values)
* Loop / play-once
* User triggered (true/false. If true, sound is played when user enters bounding box)

@nickdesaulniers created a component for this under the original architecture. We may be able to re-use some of that logic?

Is dependent on (or related to?) https://github.com/MozVR/vr-markup/issues/255

**Comment by cvan** [comment]
after @ngokevin's PR #883 is merged, we can do this with ease

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/1455
