### ISSUE TITLE
Gaze selection in Google cardboard box broken for iOS devices 

### ISSUE THREAD

**Issue by jamesdigid** [aframevr/aframe#4201]
**Description:**
I attempted to use the glitch example in this guide on my iPhone but was unable to make gaze selection in cardboard box mode only. I attempted this in both safari and chrome, and all my motion settings are turned on for browser. I'm able to look around but I'm not able to make a selection. Something I noticed is I would sometimes see the center focal circle is visible on the floor of the scene randomly while in google cardboard box mode. 

https://aframe.io/docs/0.9.0/guides/building-a-360-image-gallery.html

- A-Frame Version:
0.9.0
- Platform / Device:
iOS iPhone X 12.3.1 (Safari & Chrome)
- Reproducible Code Snippet or URL:
Open https://aframe-gallery.glitch.me/

In an IOS type device, select google cardboard box mode, and attempt to select one of the three items. It nearly makes it impossible for new developers attempting to leverage this as a solution to use it if the baseline guide is broken as such. 

Thanks

Video illustrating the bug
https://www.youtube.com/watch?v=JcndK9I4tbg

**Comment by jamesdigid** [comment]
I have resolved this enough for work around. The issue was with this specific guide in constructing camera/scene entities with generic entities, and some issues in looks-controller. 

Replacing 
```
 <!-- Camera + cursor. -->
      <a-entity id="camera" camera look-controls>
        <a-cursor
          id="cursor"
          animation__click="property: scale; startEvents: click; from: 0.1 0.1 0.1; to: 1 1 1; dur: 150"
          animation__fusing="property: fusing; startEvents: fusing; from: 1 1 1; to: 0.1 0.1 0.1; dur: 1500"
          event-set__mouseenter="_event: mouseenter; color: springgreen"
          event-set__mouseleave="_event: mouseleave; color: black"
          raycaster="objects: .link"></a-cursor>
      </a-entity>
    </a-scene>
```
with 

```
      <a-camera>
        <a-cursor></a-cursor>
      </a-camera>
```

Was able to show me a primitive working example for my needs. Hope this helps someone else out.

**Comment by irwinwilliams** [comment]
Had this issue on Android devices, too. I tested on a Nexus 6P and a Pixel 3a. 
@jamesdigid's solution worked for me as well.

**Comment by ngokevin** [comment]
fixed at https://aframe-gallery.glitch.me/

moved the template  script tag to head
