### ISSUE TITLE
THREE.LightProbe undefined

### ISSUE THREAD

**Issue by nigimaxx** [aframevr/aframe#4204]
**Description: In the current release of A-Frame `THREE.LightProbe` is undefined, but on the master branch it is not.**

- A-Frame Version: v0.9.2

As a temporary solution you could use the Github Version, but it is much larger than the releases from NPM, which affects install times drastically.

**Comment by dmarcos** [comment]
`LightProbe` is THREE r104 feature. 0.9.2 predates that release and ships with r103. [Master build](https://cdn.jsdelivr.net/gh/aframevr/aframe@3d029a4e746c844fe35ba27e5ff1a6db2b1a1978/dist/aframe-master.min.js) is only 10k larger than 0.9.2:

- 0.9.2 is [1.08 MB](https://github.com/aframevr/aframe/blob/v0.9.2/dist/aframe-master.min.js)
- master is [1.09 MB](https://github.com/aframevr/aframe/blob/master/dist/aframe-master.min.js)
