### ISSUE TITLE
a-assets CORS issue

### ISSUE THREAD

**Issue by sanjay-bhuva** [aframevr/aframe#4205]
_Access to image at 'https://d37tbwvv51fu9e.cloudfront.net/paperclip/vr_scenes/24/Ex0_Gx0.jpg' from origin 'https://s.codepen.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource._

- A-Frame Version: 0.9.2
- Platform / Device: All Browsers 
- Reproducible Code Snippet or URL: https://codepen.io/anon/pen/KjpMjB

As you can see here (https://codepen.io/anon/pen/rEVLRP), Image results in **CORS issue if Origin header is present**. I want to remove **Origin** header somehow to avoid CORS issue.

I tried the solutions specified in [#4145](https://github.com/aframevr/aframe/issues/4145) and [#2156](https://github.com/aframevr/aframe/issues/2156) but none of them is working. Please find the reproducable links below:

1. CORS issue simple HTML: https://codepen.io/anon/pen/rEVLRP
2. CORS issue a-frame: https://codepen.io/anon/pen/KjpMjB
3. Try to remove `Origin` using *ImageLoader* - https://codepen.io/anon/pen/WqvGwy
4. Try to remove `Origin` using *FileLoader* - https://codepen.io/anon/pen/RzPGZZ
5. Try to remove `Origin` using *TextureLoader* - 
https://codepen.io/anon/pen/orXzEB

I am using s3 as image source and cloudfront to cache and serve images from that s3 bucket and below are the configurations:

_S3 CORS configurations:_

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>300</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

_Bucket policy for CloudFront_

```
{
    "Version": "2008-10-17",
    "Id": "PolicyForCloudFrontPrivateContent",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E3U69JJRJ75AKK"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::aframe-cors-problem/*"
        }
    ]
}
```

Other S3 & Cloudfront configurations:

https://drive.google.com/open?id=1m_bNy5vUAkGao5bZVKBhBIvTnVflRBNR

As many users are facing the same problem, it would be better to have an option to remove **Origin** header while requesting an image using a-assets.

**Comment by dmarcos** [comment]
It looks that your server is still misconfigured. If you are requesting an image from a different domain than the server is hosted you have to set CORS headers accordingly. There are no possible workarounds on the A-Frame side. I recommend consulting Cloudfront / S3 doc and support resources
