### ISSUE TITLE
Background texture has not been rendered after exit WebVR mode

### ISSUE THREAD

**Issue by sumleo** [aframevr/aframe#4206]
**Description:**

- A-Frame Version: official demo
- Platform / Device:Windows, Mac OS( Firefox and Chrome)
- Reproducible Code Snippet or URL:https://aframe.io/examples/showcase/anime-UI/
Prove
![image](https://user-images.githubusercontent.com/29517764/59551457-55e92380-8fac-11e9-8cac-d2acfd2e176a.png)
Reproduce way:
1. Enter VR mode
2.Use keyboard move to the position shown in figure.
3.Exit VR mode

**Comment by dmarcos** [comment]
Thanks for filing. This is expected due to back face culling. The camera is moving outside of the model and the external face is not visible. Anime-UI is just a example, in a production application this would have to be handled gracefully.
