### ISSUE TITLE
Enable user to define color for <a-image>

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#421]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Saturday Aug 29, 2015 at 01:13 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/44_

----

To be displayed:

* Until image is done loading
* As the background color of images with transparencies (not sure if this will work with Three.js compositing)

If not specified, `vr-image` instances will be transparent until an image asset is loaded.

**Comment by cvan** [comment]
I'll consider #122 a dupe, even though this one was filed way back (back in the `vr-components` days)
