### ISSUE TITLE
Offline Use of Aframe models - e.g. with Kelson Sans font 

### ISSUE THREAD

**Issue by niebert** [aframevr/aframe#4216]
**Description:** Offline Scenes with Aframe & Cross-origin loading of resources vs. all resource local or loaded from one domain.

Offline use i.e. browsing Aframe models with a `file:///...` origine of files have a challenge due to the fact that rendering text relies on fonts loaded remotely CDN (see  `aframe/docs/components/text.md`. Is it possible to load the fonts like `KelsonSans` locally from the files system to prevent cross-origin loading and allow offline use?  This is also relevant for  defining a full aframe scene with an [AppCache manifest](https://en.wikipedia.org/wiki/Cache_manifest_in_HTML5) for offline use, e.g. with multiple `a-sky` 360 degree images in a VR environment explored by the user when online and then the user will be able to use the scene offline or in bandwidth constrainted environment or in remote area without internet access. This offline use is useful whenever VR with aframe is used to provide addtional digital exploration environments for the geolocation the user is currently exploring e.g. a [Real World Lab](https://en.wikiversity.org/wiki/Real_World_Lab). 

Is it possible to avoid the use of CDN resource in the future e.g. for text rendering and load the Aframe scene completely from the local file system without internet connectivity?

- A-Frame Version: ???
- Platform / Device: any

**Comment by dmarcos** [comment]
You can pass an url to the `text` component to reference your fonts: https://aframe.io/docs/0.9.0/components/text.html#properties_font

A-Frame is subject to browser policies as any other web application. For offline experiences on a regular browser check out [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) or alternatively frameworks like [Electron](https://electronjs.org/) or [Ionic](https://ionicframework.com/). I don't know when they're planning to support WebVR / WebXR. The topic is beyond A-Frame scope.

**Comment by niebert** [comment]
Thank you, for your reply,  tested electron but the binaries ship the whole Chrome browser. Aframe is lean in comparison to that. For compatibility with browser policy  "same origine" is the preferable design, but I can understand the reasons for using CDN. So using the font-properties will be way forward to stay within aframe.
