### ISSUE TITLE
Eye Tracking

### ISSUE THREAD

**Issue by ahomentc** [aframevr/aframe#4217]
With new devices such as Vive Pro Eye that support eye tracking, is there a plan for that to be integrated into AFrame? I believe eye tracking will be a very important feature for VR in the upcoming years.

**Comment by dmarcos** [comment]
Thanks for filing. A-Frame is a framework that builds on top of Web APIs. There’s no Web standard at the moment to expose eye tracking data to Web applications. There’s nothing we can do on the A-Frame side until that happens.
