### ISSUE TITLE
a-asset-item fails to infer correct response type if query parameters present 

### ISSUE THREAD

**Issue by Ely-S** [aframevr/aframe#4219]
**Description: Adding query parameters to the src of an a-asset-item will prevent the loader from correctly parsing glb/gltf files.**

I ran into this when trying to load a GLB file from a signed S3 url.

- A-Frame Version: 0.9.0
- Platform / Device: Version 74.0.3729.169 (Official Build) Built on Ubuntu, running on Ubuntu 16.04 (64-bit)
- Reproducible Code Snippet or URL: https://codepen.io/anon/pen/gNQeRB

In the example, try removing the `?key=2` from the asset item src to demonstrate the bug.

The problem is that aframe uses the file ending to determine the file type, but doesn't take into account any query parameters that may come after the file name.

**Comment by dmarcos** [comment]
Thanks for filing. Proper way to deal with this would be to determine format from file header / metadata / magic number when parsed.
