### ISSUE TITLE
Update a-register-element.js

### ISSUE THREAD

**Issue by ks1505** [aframevr/aframe#4221]
**Description:**

Warning fix for aframe Google Chrome,Firefox,IE,Safari (both desktop and mobile)
[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272
and
https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement
 for more details.
module.exports.registerElement @ a-register-element.js:69
index.js:83 A-Frame Version: 0.8.2 (Date 2018-04-15, Commit #b20527f)
index.js:84 three Version: github:supermedium/three.js#r90fixMTLLoader
index.js:85 WebVR Polyfill Version: ^0.10.5
three.js:20901 THREE.WebGLRenderer 90

**Changes proposed:**
In a-register-element.js
-Change document.registerElement to
window.customElements.define

**Comment by michael-small** [comment]
Hello @ks1505,

I noticed this issue too. Here is a [previous issue that makes note of this deprecation.](https://github.com/aframevr/aframe/issues/3923)

**Comment by dmarcos** [comment]
This is just a warning and in the case of removal A-Frame will fallback on the polyfill as @michael-small pointed out. There's a [WIP PR](https://github.com/aframevr/aframe/pull/4167) to move to custom elements V1
