### ISSUE TITLE
webVR doesn't work.

### ISSUE THREAD

**Issue by huhsame** [aframevr/aframe#4227]
**Description:**

- A-Frame Version: 0.9.2 
- Platform / Device: iPhone X, iOS 12.3.1
- Reproducible Code Snippet or URL: 

**1.** 
I tested samples of A-Frame.
Here is a video with iPhone X on A-Frame samples.
![20190715_112615](https://user-images.githubusercontent.com/9151382/61193013-7dd6be80-a6f3-11e9-821b-94a8cb02f1c9.gif)

And error messages in the console.
![image](https://user-images.githubusercontent.com/9151382/61193018-921abb80-a6f3-11e9-95a4-9bbd19d03c72.png)

**2.** 
I also tested on [webVRPollyfill demo](https://immersive-web.github.io/webvr-polyfill/examples/)
![20190715_113351](https://user-images.githubusercontent.com/9151382/61193151-a14e3900-a6f4-11e9-8705-70af733cf630.gif)
It has no error message.

**3.**
I tested various version of A-Frame on [glitch sample](https://stable-aframe.glitch.me/).
Sadly, it doesnt work in 0.9.2, 0.9.0, 0.8.2 and 0.8.0.

not only iPhone X, but other devices also don't work. 
Only Pixel2 works well.

**Comment by dmarcos** [comment]
Unfortunately, Chrome and Safari now ship with devicemotion events disabled by default. The user has to enable manually on settings:

- chrome://flags/#enable-generic-sensor in Chrome
- Settings -> Safari -> Motion & Orientation Access in Safari iOS

Content also must be served over https

**Comment by TheLouisHong** [comment]
There is no longer a "Motion & Orientation Access in Safari iOS" option any more in iOS 13 Beta 3

https://imgur.com/0QZ4ORB

**Comment by dmarcos** [comment]
As described in the [referenced issue](https://github.com/aframevr/aframe/issues/3976#issuecomment-500023818)
