### ISSUE TITLE
Model component should display loading indicator while asset is being loaded

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#423]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Saturday Aug 29, 2015 at 01:20 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/46_

---

Enables developer to display something in scene for user while asset is being pulled down. It's not uncommon for models to be multiple MB.

**Comment by autonome** [comment]
See also these, which should be cleared up as part of this work:

https://github.com/aframevr/aframe/issues/1154
https://github.com/aframevr/aframe/issues/1155

**Comment by ngokevin** [comment]
This could be done as a component. Display something until `model-loaded` fires.

```
<a-entity model>
  <a-entity indicator geometry material/>
</a-entity>
```

```
AFRAME.registerComponent('indicator', {
  init: function () {
    // Remove this entity when `model-loaded` fires.
  }
});
```

**Comment by autonome** [comment]
that's just a regular event? so something like this in indicator.init()
would work?

this.parentNode.addEventListener('model-loaded', function() {
  this.parentNode.removeChild(this);
});

**Comment by ngokevin** [comment]
Yeah. You can also check if the model is already there with getObject3D('mesh'). I'll see if I can get an example
