### ISSUE TITLE
Oculus Browser: new release is locked to 60fps

### ISSUE THREAD

**Issue by kennardconsulting** [aframevr/aframe#4232]
**Description:**

- A-Frame Version: 0.92
- Platform / Device: Oculus Quest with new update (333770.2680.0)
- Reproducible Code Snippet or URL:

When you enter an AFrame demo with the new update, the FPS is locked to 60fps. This gives a noticeable (to some people) flicker to the whole scene.

You can fix this using highRefreshRate. But it used to be automatic

**Comment by dmarcos** [comment]
Should we use [highRefresRate](https://aframe.io/docs/0.9.0/components/renderer.html#properties_highrefreshrate) by default in Oculus Browser?

**Comment by kennardconsulting** [comment]
Well, I think so. All I'm saying is you *used* to.

**Comment by kennardconsulting** [comment]
If it helps you decide, the webvr.info demos default to 72fps on the Quest (even with the new release)

**Comment by jhb** [comment]
I am quite suspectible to flicker, and wondered why suddenly the examples on https://aframe.io/examples/ made my eyes "hurt". Thanks for finding the bug, and I would strongly support 72fps by default.

**Comment by dmarcos** [comment]
We can default to 72fps but I’m not sure 60fps is the cause of flickering. All games
run at 60fps and 72 is opt in and designed for video I believe so frames align (24fps x 3)

**Comment by jhb** [comment]
Not sure either, but when I set highRefeshRate to the, everything is fine again. And I remember from the olden crt days that I see up to 70hz as flicker, and from  72 hz on everything is ok.

**Comment by kennardconsulting** [comment]
Pretty sure it's the cause of the flickering. For some people, at some refresh rates, they perceive a sort of 'background filter'. It doesn't look obvious like an old-time movie flicker, but it's enough to give you a headache after a while.

I fall into that unfortunate category, so does @jhb by the sounds of it. But if you don't then it's hard to describe. Anyway I now think it should go to 72fps by default, otherwise you'll have to rewrite all the examples.

**Comment by dmarcos** [comment]
Do you perceive similar flickering with native games? Those run at 60fps by default:

https://developer.oculus.com/documentation/unity/latest/concepts/unity-advanced-go/?locale=en_US#72-hz-mode

**Comment by kennardconsulting** [comment]
I will check. Note the sentence on that page describes it pretty well though:

"The resulting output has ... less flicker, which improves comfort and reduces eye strain."

**Comment by kennardconsulting** [comment]
Do you know of a game that definitely renders 60fps on the Quest? I think all the ones on the store have to be 72fps to pass Oculus' standards?

**Comment by dmarcos** [comment]
I would expect most games to run at 60fps, 72fps is opt-in. Do the flicker reproduces with Exokit and A-Frame examples? My worry is that 72fps might be masking a deeper issue (maybe a browser bug). We could do 72fps by default but that reduces frame budget making live harder for devs.

**Comment by kennardconsulting** [comment]
72fps is not opt-in. It is required to be listed in the Store:

"VRC.Quest.Performance.1 | The app displays graphics in the headset at 72 frames per second."
https://developer.oculus.com/distribute/latest/concepts/publish-quest-req/

**Comment by dmarcos** [comment]
Yes you're right. It's opt in in Oculus Go. Can you verify that https://github.com/aframevr/aframe/pull/4240 works?
