### ISSUE TITLE
VR default camera doesn't have look controls?

### ISSUE THREAD

**Issue by Jeremy-Bolella** [aframevr/aframe#4248]
In a plain scene with nothing much in it at all the default Camera does not work. The VR look around controls seem to be locked. The scene is similar to what is in the A-frame Hello World example. Which are also the same version as what I have on my server. The examples do respond to the gyroscope. Why would the default camera disable gyroscope controls on my instance but not the examples?

- A-Frame Version: 0.9.2
- Platform / Device: Android / IOS

**Comment by dmarcos** [comment]
https://github.com/aframevr/aframe/blob/master/docs/introduction/faq.md#why-is-the-gyroscope-not-working-on-ios

**Comment by Jeremy-Bolella** [comment]
Sorry I should have provided more information, here's the first example from the A-frame site, http://0ee07f65.ngrok.io/test.html. The gyroscope look controls don't work in my example. I can't from the code see any differences between the two.

**Comment by dmarcos** [comment]
Have you read the link to the FAQ I pointed out?

**Comment by Jeremy-Bolella** [comment]
I did the issue ended up being not serving over https traffic. I'm sorry about that I thought this was more of a bug then user error. If its relatively simple to add there should be a console warning when an app isn't served over https since that seems to be cause of the issue. Thanks a bunch for the help!
