### ISSUE TITLE
Feature: NPM version of aframe to use aframe-inspector from via node-modules

### ISSUE THREAD

**Issue by kang-chen** [aframevr/aframe#4251]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: Desktop
- Reproducible Code Snippet or URL: N/A

Hi team, really enjoy using a-frame. There are some parts of the inspector I'd like to customize in my project. I noticed we pull in a remote version of aframe-inspector from the aframe module itself. Would it make sense if we had aframe-inspector as a module dependency when using aframe via NPM? 

Unless there is an easy way of testing own custom version of the inspector, I'm up for ideas.

**Comment by dmarcos** [comment]
You can host your own investor and use it as follows:

`<a-scene inspector=“url: yoururl”>`
