### ISSUE TITLE
Scene fog not working on a-text

### ISSUE THREAD

**Issue by marcelpi** [aframevr/aframe#4261]
**Description:**

Fog applies to most entities I've tested it on but not to a-text. Surface remains flat.

- A-Frame Version: 0.9.2
- Platform / Device: macOS High Sierra, Macbook Pro
- Reproducible Code Snippet or URL: http://www.pirosca.com/a-frame-example/fog/fog.html

**Comment by dmarcos** [comment]
Probably the SDF shader doesn't take fog into consideration

**Comment by marcelpi** [comment]
Any way this can be resolved in the current version?

**Comment by arpu** [comment]
you can use https://github.com/lojjic/aframe-troika-text

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/5409
