### ISSUE TITLE
Default camera is not disabled

### ISSUE THREAD

**Issue by Maryasych** [aframevr/aframe#4262]
**Description:**

- A-Frame Version: 0.9.2 (Date 2019-05-06, Commit #f57a1fa)
- Platform / Device: MacOS 10.12.6 / Chrome 76.0.3809.100, Windows 7/ Opera 63.03368.53

```
<a-scene scene>
  <a-entity camera id="main-camera" look-controls position="0 5 0">
    <a-entity id="cursorPC" cursor="rayOrigin:mouse;" raycaster="objects: .raycasted"></a-entity>
    <a-entity id="cursorVR" cursor="fuse: true; fuseTimeout: 500;" raycaster="enabled: false; objects: .raycasted" position="0 0 -1" visible="false"
      animation__click="property: scale; startEvents: click; easing: easeInCubic; dur: 150; from: 0.1 0.1 0.1; to: 1 1 1"
      animation__fusing="property: scale; startEvents: fusing; easing: easeInCubic; dur: 1500; from: 1 1 1; to: 0.1 0.1 0.1"
      animation__mouseleave="property: scale; startEvents: mouseleave; easing: easeInCubic; dur: 500; to: 1 1 1"
      geometry="primitive: ring; radiusInner: 0.01; radiusOuter: 0.015"
      material="color: green; shader: flat">
    </a-entity>
    </a-entity>
  <a-sky color="#FFE4C4"></a-sky>
</a-scene>
```
![Знімок екрана 2019-09-03 о 22 04 42](https://user-images.githubusercontent.com/20214626/64201275-f3127480-ce96-11e9-8754-088c60d32568.png)
![Знімок екрана 2019-09-03 о 22 07 25](https://user-images.githubusercontent.com/20214626/64201446-64522780-ce97-11e9-9959-c407681bfcfe.png)

**Comment by dmarcos** [comment]
Not sure what the problem is. Default camera with provided HTML is not present: https://glitch.com/edit/#!/curvy-crustacean

**Comment by Maryasych** [comment]
Sorry, it was in fiddle but now its not. Now bug present only in Angular 8.2 project. My decision is     ```
document.querySelector('a-scene').addEventListener('loaded', function () {
      this.camera.el.setAttribute('camera', 'active: false')
    })
```

**Comment by ngokevin** [comment]
The default camera is not removed and the camera specified is not used, regressed as of 0.9.2: https://glitch.com/~aframe-gallery
