### ISSUE TITLE
add scale animation to a-sky 

### ISSUE THREAD

**Issue by fatimahamiye** [aframevr/aframe#4263]
I am trying to add animation for an  a-sky image once I click on a-entity.
so when i click on the entity, I emit the "animation_fadeout", which will make the image scale, however the problem is when scaling the image it gets flipped.
to solve this issue I am scaling the image to a negative x coordinate , but the x scale value stops at 0 and never become negative.
 
animation__fadeout="startEvents: fadeout; property: scale; from: 1 1 1; to:-1 1 3 ;  dur: 400"

**Comment by dmarcos** [comment]
Hard to tell with a runnable example. I recommend opening a question on [StackOverflow](https://stackoverflow.com/questions/tagged/aframe). We use issues for bugs and feature requests.
