### ISSUE TITLE
core:a-node:error Failure loading node:   Error: Unknown geometry schema `undefined`

### ISSUE THREAD

**Issue by snowwindsand** [aframevr/aframe#4270]
**Description:**
when I learned the guides(**Building a Minecraft Demo**) from aframe docsite, I met this error in the section **Random Color Component**.

the error will log in console. And the box never show.
- A-Frame Version: 0.9.2
- Platform / Device: Windows/ Chrome(76)
- Reproducible Code Snippet or URL:
https://codepen.io/mozillavr/pen/ryWKqy

and change the a-frame version from 0.5.0 to >= 0.9.0

**Comment by snowwindsand** [comment]
I have found the error, the example code is wrong.

**Comment by riebling** [comment]
Is there any more detail about what was wrong, and what change fixed it?
I am seeing this same exact error in another system. It was exciting to find this issue, but then
disappointing to find no help, explanation, or useful information or details
