### ISSUE TITLE
Link-traversal drops out of VR on Oculus Quest

### ISSUE THREAD

**Issue by dirkk0** [aframevr/aframe#4273]
**Description:**

- A-Frame Version:
0.9.2
- Platform / Device:
Oculus Quest
- Reproducible Code Snippet or URL:
https://curious-electric.com/w/experiments/aframe/link-traversal/

This might or might not be related to #4081  - on my Oculus Quest, the link-traversal always runs into the 5s timeout on Oculus Browser on 0.9.2 always, not on 0.8.2.

There are no heavy scenes involved, I created the smallest possible pages to reproduce this.
On 0.8.2 it works, although I think that it's not super fast either, but you don't drop out.

[EDIT]
I just saw that I left a link to rawgit resource in the code. Removing it made the 0.9.2 examples work. Still, loading just one resource created this problem.
Not sure how to proceed from here; the 0.8.2 behaviour seems more robust (because smaller?) and the 5 second timeout (is it only Quest and Go? Or everywhere?) should be documented, if real.
Also, the 5s timeout (there is one, right?) can be a showstopper for games.

So are we advised to not use link-traversal for non-trivial cases if we don't want to break VR immersion?

**Comment by craftecode** [comment]
I'm not sure if you've done more work on the example to make it function correctly but for me it did two different things in Firefox on Quest - one time it showed an intermediary area that was all black except for some rotating hoops and another time it was just temporarily black and then loaded the new page.

**Comment by dirkk0** [comment]
No, I didn't.
You are right, it works flawlessly in Firefox Reality Browser while the standard Oculus Browser (Chrome under the hood) keeps timing out ...

**Comment by dmarcos** [comment]
Try with A-Frame master and let me know if it still reproduces: https://github.com/aframevr/aframe/commit/d48ae3efd2c9fff7a6f00be971bf958992d0e566

**Comment by craftecode** [comment]
Hi dmarcos, that has fixed it! Thank you so much for all your work on Aframe!

Tested with: Oculus Quest using https://tinted-magician.glitch.me/
Oculus Browser version: 6.2.11.181027543
Chromium version: 74.0.3729.182

**Comment by dmarcos** [comment]
Great news. Thanks for letting us know

**Comment by dirkk0** [comment]
... confirmed - thanks!

**Comment by Chabloz** [comment]
Hi, 

Not working anymore with 1.0.3 (or i made something wrong? )

You can test it here: https://healthy-bicycle.glitch.me/

**Comment by dmarcos** [comment]
In-vr navigation didn’t make it to WebXR 1.0. Only browsers where it still works are Firefox desktop and Supermedium that still ship with WebVR

**Comment by Chabloz** [comment]
Ok, thanks for the quick reply.
