### ISSUE TITLE
GLTF-MODEL FAILED TO LOAD

### ISSUE THREAD

**Issue by ali2210** [aframevr/aframe#4274]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device:WEB
- Reproducible Code Snippet or URL: 
![Capture](https://user-images.githubusercontent.com/20568079/65174498-6f49b200-da6a-11e9-8f3d-b3f9218c1a42.JPG)

Sir i'm using a-frame on my website, perhaps website written in golang language. When my website load gltf model , it throw component gltf-model : warn failed to load. Please help me

**Comment by donmccurdy** [comment]
I'd recommend the troubleshooting steps here: https://aframe.io/docs/0.9.0/introduction/models.html#troubleshooting

And, does your model work correctly in https://gltf-viewer.donmccurdy.com/? More information would be useful – without the model, or the error, or a demo, we probably won't be able to help you sorry!

**Comment by ali2210** [comment]
![1](https://user-images.githubusercontent.com/20568079/65262754-733a0a80-db24-11e9-9919-5e6273ba1575.JPG)
![0](https://user-images.githubusercontent.com/20568079/65262755-733a0a80-db24-11e9-8b5e-4eac14876a27.JPG)
![code](https://user-images.githubusercontent.com/20568079/65262758-746b3780-db24-11e9-92f2-01b453385170.JPG)
I can change code myself just to play a card, but no error except timeout warning receive. However I try your method and update status.

**Comment by dmarcos** [comment]
You have to serve your models using a local web server. Web pages can’t access the file system: https://aframe.io/docs/0.9.0/introduction/installation.html#local-development

**Comment by ali2210** [comment]
This page already run on local server 
![0](https://user-images.githubusercontent.com/20568079/65264775-cada7500-db28-11e9-9730-3cc5f5ccd435.JPG)
![3](https://user-images.githubusercontent.com/20568079/65264776-cb730b80-db28-11e9-8a0b-76563e1098fe.JPG)
![1](https://user-images.githubusercontent.com/20568079/65264778-cb730b80-db28-11e9-8318-f47de63e0c84.JPG)
