### ISSUE TITLE
Can't modify properties with a-link primitive

### ISSUE THREAD

**Issue by nicolocarpignoli** [aframevr/aframe#4276]
Hi everybody

I tried to add a simple `<a-link>` primitive to a basic HTML, and tried to modify it with `.setAttribute` but I can't make it work with properties other than `title`, `href`, `src`.

Does it have something to do with this? https://github.com/aframevr/aframe/blob/v0.9.0/src/extras/primitives/primitives/a-link.js

Maybe what is not defined as a 'mapping' cannot be modified?

My aim is to instantiate an `a-link` with `visualAspectEnabled` set to `false`.

- A-Frame Version: 0.9.2
- Platform / Device: Android, latest Chrome

**Comment by dmarcos** [comment]
A per docs `visualAspectEnabled` is not exposed on the [a-link primitive](https://aframe.io/docs/0.9.0/primitives/a-link.html#sidebar)

You can access the component directly: `linkEl.setAttribute('link', 'visualAspectEnabled', false)`

**Comment by nicolocarpignoli** [comment]
@dmarcos 

Hi,
thanks for the answer but it does not work with certain properties.

I tried most of them:
https://aframe.io/docs/0.9.0/components/link.html#properties

borderColor and backgroundColor are working, but visualAspectEnabled and title don't.

any ideas?

**Comment by dmarcos** [comment]
It works for me: [example](https://gleaming-ocarina.glitch.me/) and corresponding [HTML](https://glitch.com/edit/#!/gleaming-ocarina?path=index.html:11:86)

**Comment by nicolocarpignoli** [comment]
@dmarcos the live example does not work https://gleaming-ocarina.glitch.me/

Anyway, I run it on local server, and if you set the visualAspetEnabled false instead of true, the a-link disappeared, as I said before. I was expecting that the 'visual' aspect goes away, not the entire entity.

**Comment by dmarcos** [comment]
That's the expected behavior. Disabling visual aspect, disables the link's default visual representation and it's up to you to render links in whatever way you see fit. [Example using a sphere](https://glitch.com/edit/#!/eminent-wakeboard?path=index.html:13:48).

**Comment by nicolocarpignoli** [comment]
ok thanks.

Yes, in my opinion docs need clarification. It is not clear that removing `visualAspectEnabled` it hides also the `title` property, as the title is a separate property.
