### ISSUE TITLE
Text not rendering when logarithmicDepthBuffer is enabled

### ISSUE THREAD

**Issue by Kershawj** [aframevr/aframe#4279]
Creating a scene with just a <a-text> entity in but then using logarithmicDepthBuffer set to true in the renderer settings works fine so like:

`<a-scene renderer="logarithmicDepthBuffer: true;">
            <a-text value="Some text please" color="black" position="0 0 -5"></a-text>
        </a-scene>`

However adding a plane behind the text whilst logarithmicDepthBuffer set to true causes text to not render over the plane.

`<a-scene renderer="logarithmicDepthBuffer: true;">
            <a-plane height="1" width="3" color="red" position="0 0 -5.2"></a-plane>
            <a-text value="Some text please" color="black" position="0 0 -5"></a-text>
        </a-scene>`

Switching to `logarithmicDepthBuffer: false;` then works as expected.
I have a scene which really needs this set to true for lots of other entities to render correctly and to reduce z-fighting but also need some generated text in there so I'm kinda stuck.
I'm guessing the text shader isn't aware of how to handle this correctly?

- A-Frame Version: 0.9.2
- Platform / Device: Chrome/Macbook

**Comment by Kershawj** [comment]
Just to say after more testing, it works as expected when using v0.8.0
`<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>`

**Comment by arpu** [comment]
does it work with the master version? 
``` <script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@ab9821761340fd6ee28171fc38f85a45c2ade514/dist/aframe-master.min.js"></script>```

**Comment by Kershawj** [comment]
No, same result.
I do get some additional warnings in the console log, here's both as a comparison. First using 0.9.2:
<img width="432" alt="0 9 2_log" src="https://user-images.githubusercontent.com/9318275/66109385-6e616600-e5bc-11e9-87c1-def16c9c9ffd.png">

Then with master:
<img width="424" alt="master_log" src="https://user-images.githubusercontent.com/9318275/66109398-74574700-e5bc-11e9-82f6-9daa7c110d99.png">

**Comment by arpu** [comment]
sorry i have no idea here best waiting for @dmarcos

**Comment by dzoech** [comment]
Any updates on this issue?  
I'm experiencing the same issues with AR.js that text is not rendered in front of other entities independent from their z-indices.

![image](https://user-images.githubusercontent.com/29693067/94540059-50b5f380-0246-11eb-8c9c-741249081f31.png)

**Comment by arpu** [comment]
@dzoech  meantime you can try/use https://github.com/lojjic/aframe-troika-text

**Comment by dzoech** [comment]
Thank you @arpu, works like a charme

**Comment by ttguy** [comment]
I also have exactly this issue with aframe 1.4.0

**Comment by Atlinx** [comment]
This is still an issue in aframe 1.4.2

**Comment by mrxz** [comment]
The problem lies in the fact that `logarithmicDepthBuffer` requires specific shader chunks in three.js. The text shaders in A-Frame don't include these and as a result will simply write to the depth buffer as if it was a normal z-buffer.

It should be relatively easy to update the shaders. At the same time the correct encoding and tonemapping chunks can be included as well.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/5409
