### ISSUE TITLE
WebXR device emulator error: TypeError: t.transform is undefined look-controls.js:202:10

### ISSUE THREAD

**Issue by PaulKElliott** [aframevr/aframe#4280]
**Description:**

When using the WebXR device emulator I'm getting this error when clicking the "start VR" goggles button:
TypeError: t.transform is undefined look-controls.js:202:10

- A-Frame Version: 
Latest:
"https://cdn.jsdelivr.net/gh/aframevr/aframe@ab9821761340fd6ee28171fc38f85a45c2ade514/dist/aframe-master.min.js"

- Platform / Device:
WebXR device emulator in Firefox

- Reproducible Code Snippet or URL:  
The boiler plate example:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello, World! - A-Frame</title>
    <meta name="description" content="Hello, World! - A-Frame">
    <script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@ab9821761340fd6ee28171fc38f85a45c2ade514/dist/aframe-master.min.js"></script>
  </head>
  <body>
    <a-scene>
      <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9"></a-box>
      <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E"></a-sphere>
      <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>
      <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
      <a-sky color="#ECECEC"></a-sky>
    </a-scene>
  </body>
</html>
```

**Comment by arpu** [comment]
try to add a camera rig 
```
<a-entity id="rig" position="25 10 0">
  <a-entity id="camera" camera look-controls></a-entity>
</a-entity>
```

**Comment by PaulKElliott** [comment]
Just tested.  Same same with this:
```
    <a-scene>
      <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9"></a-box>
      <a-entity id="rig" position="0 0 0">
        <a-entity id="camera" camera look-controls></a-entity>
      </a-entity>
    </a-scene>
```
Warnings and error at end:

THREE.WebGLRenderer: OVR_multiview2 extension not supported. three.js:15786:13

THREE.WebXRManager: setDevice() has been deprecated. three.js:23303:11

TypeError: t.transform is undefined look-controls.js:202:10

**Comment by arpu** [comment]
ok it looks like sceneEl.renderer.vr.getCameraPose();  gets a pose.views array back with right eye and left eye 

simple but not complete sure if this is right is using 
 poseMatrix.elements = pose.views[0].transform.matrix;
 in looks-controls 

@dmarcos  ^^

**Comment by arpu** [comment]
more infos here, it should be possible to use webxr api getViewerPose here 

https://github.com/immersive-web/webxr/blob/master/explainer.md

**Comment by dmarcos** [comment]
It looks like the emulator is not up to date with the standard. XRViewer derives from XRPose and should have a transformed attribute as [described in the spec](https://immersive-web.github.io/webxr/#xrviewerpose). I recommend opening an issue on the emulator repo.

**Comment by arpu** [comment]
this webxr emulator https://github.com/MozillaReality/WebXR-emulator-extension/issues ?

**Comment by arpu** [comment]
@PaulKElliott the bug should be fixed and i think this bug report can be closed

**Comment by dmarcos** [comment]
Thanks for filing the issue. Much appreciated

**Comment by PaulKElliott** [comment]
Thanks for the support!
