### ISSUE TITLE
Color names shouldn't be case sensitive

### ISSUE THREAD

**Issue by Pawper** [aframevr/aframe#4282]
Hello,

I am learning A-Frame while learning HTML and I have found that the color values must be in lower case to work. Many web resources do not provide color names in lowercase, so this was not intuitive and I had to figure this out by trial-and-error. It would be best if any case was valid.

Valid: `color="crimson"` like listed here https://developer.mozilla.org/en-US/docs/Web/CSS/color_value
![image](https://user-images.githubusercontent.com/22269691/66259788-ae664b80-e76a-11e9-9f1f-1fe5ee074e7c.png)

Not valid: `color="Crimson"` like listed here https://www.w3schools.com/colors/colors_hex.asp or here https://en.wikipedia.org/wiki/Web_colors#HTML_color_names 
![image](https://user-images.githubusercontent.com/22269691/66259794-c8079300-e76a-11e9-8398-14a0e9554e78.png)

Not valid: `color="CRIMSON"` like listed here https://htmlcolorcodes.com/color-names/ 
![image](https://user-images.githubusercontent.com/22269691/66259805-e7062500-e76a-11e9-99c6-6e2d2306e6a5.png)

Thank you.

**Comment by dmarcos** [comment]
Color strings are supported via [THREE.Color](https://threejs.org/docs/#api/en/math/Color). Capitalization should be probably dealt there. I suggest opening an issue on the repo: https://github.com/mrdoob/three.js

**Comment by dmarcos** [comment]
I think this is not something to be fixed on A-Frame side but handled on THREE.
