### ISSUE TITLE
Issues with 360 gallery example

### ISSUE THREAD

**Issue by twatzl** [aframevr/aframe#4283]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: Chrome Desktop and Chrome on Android
- Reproducible Code Snippet or URL: http://aframe-gallery.glitch.me/

Hello, 

I am trying to get started with aframe, however it seems that there are some bugs in the example application.

For me the cursor is off center on desktop. I tried it with Chrome 77 and Firefox 69 and for both the cursor is not aligned to the center of the screen and it is a guesswork to click the buttons.

On mobile (Android) I have the issue that the gyroscope does not work once i enter the Cardboard mode. Neither in Firefox or Chrome.

**Comment by gifff** [comment]
I also suffer the bug. But after some research, I found something's off in the code.
I change the camera tag from `<a-entity id="camera" camera look-controls>` to `<a-camera id="camera">` and then it just works.

Here is the edited sample project: https://glitch.com/edit/#!/heady-fahrenheit?path=index.html:38:51
Preview: https://heady-fahrenheit.glitch.me

**Comment by twatzl** [comment]
Thanks for sharing the info. Now it seems to work on Desktop, although it's quite blurry.

On mobile I still have the issue that the gyro won't work.

**Comment by ngokevin** [comment]
Fixed https://aframe-gallery.glitch.me/

the template script tag in a-assets didn't like it.

it is oddly blurry and i think maybe updating aframe version helps.
