### ISSUE TITLE
Calling destroy() on entities causes strange bugs when creating new entities 

### ISSUE THREAD

**Issue by Drugges** [aframevr/aframe#4284]
Hi,
I just updated to 0.9.2 from 0.8 and I read in the changelog that: "Detaching entity from scene will preserve component data.". In my project I add and remove a lot of nodes over time. So I thought I should start using destroy, to reduce memory usage, but it has caused some strange issues. 

In the project, the user "walks" around in many different rooms. Every room consist of an a-sky and some button that leads to a new room. When the user enters a new room, the old nodes are removed, and afterwards the new nodes are added to the scene.
I create a new a-sky node every time the user enters a new room, with: 
`document.createElement('a-sky'); // then I set radius etc`

Previously I have only been removing the nodes using: 
`skyNode.parentNode.removeChild( skyNode );`
But now I have tested with:
`skyNode.parentNode.removeChild( skyNode );
skyNode.destroy()`
After the user leaves a room and destroy is called, the next time I create a new a-sky it fails with warning:
`core:schema:warn Unknown property radius for component/system geometry`
When I check the data of the geometry on a-sky it appears to be "box" instead of "sphere".
When I remove the destroy() call it works as usual.

This is how the a-sky looks on the first room:
![image](https://user-images.githubusercontent.com/4995826/66261022-c9ff3f80-e7c6-11e9-8e79-af0f3e59d1dd.png)

And this is how it looks after I have removed the a-sky and created a new a-sky:
![image](https://user-images.githubusercontent.com/4995826/66261026-e7cca480-e7c6-11e9-9b96-88ec70668a72.png)

Do you think this is a bug? Or do I use destroy() in a wrong way?

Thanks!
Peter

- A-Frame Version: 0.9.2
- Platform / Device: Windows and Mac Chrome

**Comment by dmarcos** [comment]
I suggest sharing a single test case to reproduce to illustrate what you're trying to do. Glitch will do: https://glitch.com/~aframe

You shouldn't have to call destroy manually. It will be called for you when the child is removed.

I recommend avoiding recreating `a-sky` and modify it's properties instead.

FWIW, this is code removing and adding `a-sky` without issues: https://glitch.com/edit/#!/fire-lentil?path=index.html:11:41

We can reopen if this is still an issue.

**Comment by Drugges** [comment]
If I don't need to call destroy then I am fine. Then it works like expected. Thanks
