### ISSUE TITLE
A-Frame 0.9.0-2 crashing in Chrome

### ISSUE THREAD

**Issue by cwervo** [aframevr/aframe#4290]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: Chrome 77.0.3865.120, MacBook Pro, running MacOS Catalina (though I saw this on Mojave as well)
- Reproducible Code Snippet or URL: http://aframe.glitch.me/

I get the following whenever `navigator.xr.requestDevice is not a function` error whenever I visit an A-Frame 0.9.0 or 0.9.2 project in Google Chrome:

<img width="840" alt="Screen Shot 2019-10-13 at 2 28 12 AM" src="https://user-images.githubusercontent.com/5826638/66711844-a48faa00-ed61-11e9-925c-6f4b99a834a3.png">

Testing out on https://test-aframe-chrome-compat-cwervo.glitch.me/ it looks like this issue starts with [v0.9.0](https://test-aframe-chrome-compat-cwervo.glitch.me/testpage.html?v=0.9.0) because [v0.8.0](https://test-aframe-chrome-compat-cwervo.glitch.me/testpage.html?v=0.8.0) & [v0.8.2](https://test-aframe-chrome-compat-cwervo.glitch.me/testpage.html?v=0.8.2) load as expected.

**Comment by dmarcos** [comment]
We've seen a bug in Chrome where `navigator.xr` is defined when it shouldn't in some scenarios. Clicking `Reset all to default` in chrome://flags should solve the issue.

**Comment by cwervo** [comment]
@dmarcos  Hmmm, that didn't solve the issue — will try reinstalling Chrome & see if that fixes it. Thanks for the heads up though!

**Comment by arpu** [comment]
or you have the webxr emulator extention installed

**Comment by cwervo** [comment]
Ah! @arpu it was totally the [WebXR Extension](https://blog.mozvr.com/webxr-emulator-extension/) — thanks!
