### ISSUE TITLE
Controller Models for Quest/RiftS not included

### ISSUE THREAD

**Issue by Knochi** [aframevr/aframe#4297]
There is only the Gen1 model of Oculus Touch Controller available. I did a pull request for my gltf models of the new controllers to assets repo. ( [see reddit discussion](https://www.reddit.com/r/WebVR/comments/dh85mt/aframe_want_2nd_gen_oculus_touch_controller_models/?utm_source=share&utm_medium=web2x)  )

Suggestion would be to extend the model parameter to "Gen1, Gen2 or none" instead of boolean.

- A-Frame Version:0.9.2
- Platform / Device: Oculus Quest

**Comment by dmarcos** [comment]
A WIP https://github.com/aframevr/aframe/pull/4073. You’re more than welcome to share your thoughts there. Thanks for the models.
