### ISSUE TITLE
When exiting from VR mode, it stopped working

### ISSUE THREAD

**Issue by Leshao-Zhang** [aframevr/aframe#4300]
**Description:**
When exiting from VR mode, it stopped working.

Uncaught TypeError: Cannot read property 'length' of null
    at o.updateControllerList (aframe.min.js?v=336j4q:1060)
    at aframe.min.js?v=336j4q:1062
    at o.throttledUpdateControllerList (aframe.min.js?v=336j4q:1080)
    at o.tick (aframe.min.js?v=336j4q:1060)
    at HTMLElement.tick (aframe.min.js?v=336j4q:931)
    at HTMLElement.render (aframe.min.js?v=336j4q:931)
    at aframe.min.js?v=336j4q:1062
    at f (aframe.min.js?v=336j4q:134)
    at e (aframe.min.js?v=336j4q:132)

- A-Frame Version: 0.9.2 master.min
- Platform / Device: Android Chrome M77
- Reproducible Code Snippet or URL:

**Comment by klausw** [comment]
See also issue #4321 - if this is happening in AFrame 0.9.2 also, that means it's likely unrelated to recent WebXR-related changes on master.

@Leshao-Zhang  Do you have a URL for reproducing it? Was this using WebVR or WebXR, and did you enable WebXR and/or WebVR in chrome://flags ?

**Comment by Leshao-Zhang** [comment]
Guess we can close this issue now. WebXR is now basically not working anywhere. Have to stick with WebVR.

**Comment by klausw** [comment]
@dmarcos just fixed this issue via https://github.com/aframevr/aframe/issues/4321#ref-commit-7846f74 . 

FYI, WebVR was a draft standard and was never enabled by default in Chrome apart from an origin trial a long time ago, and Chrome M80 no longer supports it at all. WebXR will be enabled by default starting from M79. So I'd strongly recommend giving WebXR a chance. Yes, it's been a messy process getting here, but I think things are finally stabilizing.
