### ISSUE TITLE
screen.orientation.lock() is not available on Android Chrome M78

### ISSUE THREAD

**Issue by Leshao-Zhang** [aframevr/aframe#4301]
**Description:**
VR mode not working with the latest Chrome
Uncaught (in promise) DOMException: screen.orientation.lock() is not available on this device.

- A-Frame Version: 0.9.2 master
- Platform / Device: Android Chrome M78
- Reproducible Code Snippet or URL:

**Comment by klausw** [comment]
FYI, you don't need to lock the screen orientation when using native WebXR, and this will be active by default on Android starting from Chrome 79, assuming the phone supports Cardboard or Daydream.

**Comment by Leshao-Zhang** [comment]
> FYI, you don't need to lock the screen orientation when using native WebXR, and this will be active by default on Android starting from Chrome 79, assuming the phone supports Cardboard or Daydream.

Cool, but this function is called automatically when the lib is imported.

**Comment by klausw** [comment]
Only if WebXR is unavailable:

https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L338
```
if (!navigator.xr && self.isMobile && screen.orientation && screen.orientation.lock) {
  screen.orientation.lock('landscape');
}
```

**Comment by sumitkumardey91** [comment]
screen.orientation.lock() is not available on Android Chrome v80. how can i get this feature back.
