### ISSUE TITLE
Support for Chrome 79 with the WebXR device API

### ISSUE THREAD

**Issue by minchnew** [aframevr/aframe#4304]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: Chrome for macOS, Version 79.0.3945.16 (Official Build) beta (64-bit)
- Reproducible Code Snippet or URL: https://aframe.io/aframe/examples/boilerplate/3d-model/

I got an error `navigator.xr.requestDevice is not a function`. After a few searches, I found #4086 , #4087 and a three.js [issue](https://github.com/mrdoob/three.js/issues/16103). It turns out that Chrome 79 beta has enabled the Web XR device API by default and breaks aframe. [The stable version will be released on Dec 10.](https://www.chromestatus.com/features/schedule) Are there any plans to support WebXR API?

**Comment by dmarcos** [comment]
Already supported on master: https://cdn.jsdelivr.net/gh/aframevr/aframe@df3e8672b77568845e5e360f54f4456fd4829a38/dist/aframe-master.min.js

Let me know if it works for you

**Comment by minchnew** [comment]
It works. Thanks a lot!

**Comment by julianfrank** [comment]
I'm getting this error on windows 10 ever since chrome upgraded to 79!... I use npm to import the package ... What is the workaround?

**Comment by DanielTezolin** [comment]
i'm having the same problem after the google chrome 79 update.
I'm using npm to import aframe... did anyone fix this problem?
