### ISSUE TITLE
The a-frame cannot be used properly in Framewor7-Vue.

### ISSUE THREAD

**Issue by idreamin** [aframevr/aframe#4305]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: 
- Reproducible Code Snippet or URL:

When I use The a-frame in Framework7-Vue: https://framework7.io/vue/
It cannot be used properly.
Can the ignore tag be set so that The a-frame can be used normally ？
Below is the code and the error:

<img width="666" alt="1" src="https://user-images.githubusercontent.com/38604167/68224246-34570a00-0029-11ea-82aa-b0238ecd44f1.png">
<img width="826" alt="2" src="https://user-images.githubusercontent.com/38604167/68223877-95321280-0028-11ea-8656-c291571b3518.png">

**Comment by dmarcos** [comment]
I'm not familiar with `Framework7-Vue`. This looks like a usage question more appropriate to [StackOverflow](https://stackoverflow.com/questions/tagged/aframe). Nice folks there to help. There's nothing actionable on the A-Frame side.
