### ISSUE TITLE
CORS error loading local controller model

### ISSUE THREAD

**Issue by mindrones** [aframevr/aframe#4306]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: Windows 10, Firefox 70.0.1 (64-bit), Vive Pro
- Reproducible Code Snippet or URL:

```html
<a-scene>
	<a-assets>
		<a-asset-item id="controller-obj" src="models/vr_controller_vive.obj"></a-asset-item>
		<a-asset-item id="controller-mtl" src="models/vr_controller_vive.mtl"></a-asset-item>
	</a-assets>

	<a-entity
		id="leftHand"
		laser-controls="hand: left"
		obj-model="obj: #controller-obj; mtl: #controller-mtl"
	></a-entity>
	<a-entity
		id="rightHand"
		laser-controls="hand: right"
		obj-model="obj: #controller-obj; mtl: #controller-mtl"
	></a-entity>
</a-scene>
```

- Error: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.aframe.io/controllers/vive/vr_controller_vive.mtl. (Reason: CORS request did not succeed).`

It seems like [this line](https://github.com/aframevr/aframe/blob/05406c5ed92b7a202971c87c5b7f1cce08a1033a/src/components/vive-controls.js#L125) gets executed no matter if we passed a local model or not, which seems a bit weird to me (we might not want to use the controller model hosted on aframe.io).

**Comment by dmarcos** [comment]
To disable the default model you can do:

```
<a-entity
  id="rightHand"
  laser-controls="hand: right; model: false"
   obj-model="obj: #controller-obj; mtl: #controller-mtl">
</a-entity>
```

I added the missing property to the [docs](https://github.com/aframevr/aframe/blob/master/docs/components/laser-controls.md)

**Comment by mindrones** [comment]
Ah I see, that's great thanks a lot!
