### ISSUE TITLE
Entities scale down and change position on switch to VR mode on mobile

### ISSUE THREAD

**Issue by davidfstein** [aframevr/aframe#4313]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: Android
- Reproducible Code Snippet or URL: https://bony-tortoise.glitch.me/

When switching to vr mode on mobile, the entities move extremely far away and are positioned such that they can only be seen when looking straight down. When not in vr mode the entities are directly in front/to the right of the camera and are level with the horizon. I image to a certain extent entities are scaled down when entering vr mode, but these seem to be overscaled and im really not sure why the position is seemingly changing. 

The repository is here: https://github.com/davidfstein/hs19-var

**Comment by dmarcos** [comment]
Don't use the zoom property to get objects closer but move the camera rig instead. When in VR the camera matrix will be supplied by the WebXR / WebVR API and any configuration will be overridden.

**Comment by davidfstein** [comment]
Just to be clear, this phenomenon happens whether or not the zoom is applied. My real question is why are the sphere entities changing position when I switch to vr mode on mobile. Is this the expected behavior?
