### ISSUE TITLE
Customize parameters to WebXR requestSession?

### ISSUE THREAD

**Issue by klausw** [aframevr/aframe#4315]
Currently, AFrame uses hardcoded parameters for `navigator.xr.requestSession`:
https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L286

```js
            navigator.xr.requestSession(useAR ? 'immersive-ar' : 'immersive-vr', {
              requiredFeatures: ['local-floor'],
              optionalFeatures: ['bounded-floor']
            }).then(...)
```

Currently, the WebXR [features](https://immersive-web.github.io/webxr/#feature-dependencies) just correspond to reference space names, but in the future it's likely that there will be additional feature names to activate additional functionality, or potentially additional direct attributes for the init dictionary.

For example, I'm currently experimenting with using a DOM Overlay in AR mode, and the current prototype builds are using a feature named `dom-overlay-for-handheld-ar` for that. I've hardcoded this in a modified _aframe-master.js_ in https://klausw.github.io/a-frame-car-sample/index.html  , but I think there should be a way to add such options without needing core source modifications.

What would be an appropriate way to do that? Something like this maybe (handwaving on the syntax)?

```
<a-scene webxr="addOptionalFeatures: dom-overlay-for-handheld-ar;
                addInitAttribute: domOverlayElement=#example">
```

resulting in this call:

```js
            navigator.xr.requestSession('immersive-ar', {
              requiredFeatures: ['local-floor'],
              optionalFeatures: ['bounded-floor', 'dom-overlay-for-handheld-ar'],
              domOverlayElement: '#example"
            })
```

Alternatively, specific features could get enabled by a component, while the component implementation sets appropriate values in scene properties through JS APIs, for example for DOM overlay:

```
<a-scene dom-overlay="element: #example">
```

In any case, as long as new WebXR features are still in flux, I think it would be most useful to have a generic mechanism that allows enabling and testing features without needing to change core a-frame source.

**Comment by dmarcos** [comment]
There's a precendent of this with [requestPresent](https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L307) and the [renderer system](https://github.com/aframevr/aframe/blob/master/src/systems/renderer.js#L14) to set the foveationLevel and enable 72fps mode on the Oculus Browser. Maybe consolidating the webxr flags on a system / component might make more sense.

**Comment by dmarcos** [comment]
I'm going to move this for next milestone since it's for experimental purposes.

**Comment by sneha-belkhale** [comment]
@dmarcos hey, is there any update on this? I'm looking for a way to set the foveationLevel in WebXR + Oculus Browser.

**Comment by dmarcos** [comment]
You can already adjust foveation level https://aframe.io/docs/1.0.0/components/renderer.html#sidebar

**Comment by marlon360** [comment]
This would be nice for additional features like the new `'hand-tracking'` 👍

**Comment by klausw** [comment]
There's now a "webxr" system in master that can be used to configure required/optional features: https://aframe.io/docs/master/components/webxr.html

If you only need to request a feature, you can simply specify that:

```html
<a-scene webxr="optionalFeatures: hand-tracking"></a-scene>
```

Beyond that, it's intended to be extensible for more complex feature requests, for example it supports a WebXR DOM overlay element directly. Internally, it sets up a `sessionConfiguration` object that's used as the init arg for the `requestSession` call.

If you have a new feature, you can access that for experiments, for example in a custom `system` that modifies `this.el.sceneEl.systems.webxr.sessionConfiguration` before session start.

**Comment by dmarcos** [comment]
It looks like A-Frame master now supports the functionality originally proposed. I'm closing this but can reopen if necessary
