### ISSUE TITLE
Next stable Chrome (79) implementing WebXR Device API, will break aframe

### ISSUE THREAD

**Issue by nicolocarpignoli** [aframevr/aframe#4317]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: Chrome 79 (you can [try on Beta](https://www.google.com/intl/it/chrome/beta/), will be out first days of December 2019)
- Reproducible Code Snippet or URL:

Just open an aframe application with Chrome 79 beta.
Otherwise, look here:

* open this link, it's an app using latest aframe : https://nicolo-carpignoli.herokuapp.com/examples/places-name/

* open console

* you can see the error. it's from device.js file, error is in accessing `navigator.xr.requestDevice` that is not present. APIs are changed lately. Code needs to be changed simply with a sanity check.

This potentially breaks *every* aframe app. 

Thanks for the attention

**Comment by dmarcos** [comment]
WebXR is fully supported on master builds:
https://cdn.jsdelivr.net/gh/aframevr/aframe@8d0347f6865d303032be8509610cb600d382bd1d/dist/aframe-master.min.js

It will ship in next version once the standard stabilizes

**Comment by nicolocarpignoli** [comment]
@dmarcos is aframe version will be shipped *before* chrome 79 is out or may not?

**Comment by dmarcos** [comment]
@nicolocarpignoli Probably but there was a bit of churn still in the spec. We have to check. In the meantime you can start using master builds and let us know if everything works for you.

**Comment by nicolocarpignoli** [comment]
ok thanks

**Comment by arpu** [comment]
i still have a problem with the controller inputs with Webxr

**Comment by klausw** [comment]
I filed https://github.com/aframevr/aframe/issues/4322 about controller handling

**Comment by sureshwisdom** [comment]
I just added aframe-master.min.js file it shows some error.
![edit3](https://user-images.githubusercontent.com/18713981/69852105-578a7780-12be-11ea-93d1-ed9c5241e16d.JPG)

**Comment by dmarcos** [comment]
Use the CDN: https://cdn.jsdelivr.net/gh/aframevr/aframe@934b8d358a2c458efdc8d65fcb6946f7303f0b51/dist/aframe-master.min.js

**Comment by felipenmoura** [comment]
Can we reopen this issue?
As there are clear problems with raycaster in the last version:
https://github.com/aframevr/aframe/issues/4354

If I use 9.0.2, it works perfectly on Firefox, but crashes in Chrome, If I update to use the master you mentioned @dmarcos , it works on both Firefox and Chrome, but clicks/touches wont work in any of them.
Any update? This is critical and has suddenly broken a-frame experience and interactions!

**Comment by klausw** [comment]
@felipenmoura , can you please open a new issue for this? I suspect it may be a side effect of WebVR being tied to a canvas element, while WebXR uses a framebuffer object that doesn't receive DOMbevents. A glitch or other online example to repro this would be useful if possible.

**Comment by felipenmoura** [comment]
Hi @klausw 
I left a better description (and code) about it here:
https://github.com/aframevr/aframe/issues/4354#issuecomment-566792431

Then, I posted a "quick fix" for it here:
https://github.com/aframevr/aframe/issues/4354#issuecomment-567052948

But that fix is an ugly workaround and I ended up not being able to use the 1.0.0 version of a-frame!

**Comment by rajsite** [comment]
I hit this in a couple of apps I have deployed with aframe 0.9.2. Posting the error message for others to trace back:
```
Uncaught TypeError: navigator.xr.requestDevice is not a function
    at Object.<anonymous> (aframe-v0.9.2.js:79248)
    at Object.176._process (aframe-v0.9.2.js:79378)
    at o (aframe-v0.9.2.js:1)
    at aframe-v0.9.2.js:1
    at Object.179../bind (aframe-v0.9.2.js:79464)
    at o (aframe-v0.9.2.js:1)
    at aframe-v0.9.2.js:1
    at Object.152.../package (aframe-v0.9.2.js:77150)
    at o (aframe-v0.9.2.js:1)
    at r (aframe-v0.9.2.js:1)
```
Looking into updating to aframe v1 to workaround the Chrome 79 issue.

**Comment by dmarcos** [comment]
@rajsite Updating to 1.0.3 will solve the issue.
