### ISSUE TITLE
Checking for DeviceOrientationEvent breaks on Safari 13

### ISSUE THREAD

**Issue by nuel** [aframevr/aframe#4318]
**Description:**
I switched to master branch version of A-Frame to get the new `device-orientation-permission-ui` from #4303. Works great everywhere, except for Safari on desktop, where it throws the following error:

```
[Log] core:a-node:error Failure loading node:   (aframe-master.min.js, line 19)
ReferenceError: Can't find variable: DeviceOrientationEvent
init — device-orientation-permission-ui.js:33
initComponent — component.js:320
updateProperties — component.js:302
updateComponent — a-entity.js:490
updateComponent — a-scene.js:689
updateComponents — a-entity.js:463
https://cdn.jsdelivr.net/gh/aframevr/aframe
https://cdn.jsdelivr.net/gh/aframevr/aframe
promiseReactionJob
```

- A-Frame Version: 0.9.2 (Date 2019-11-19, Commit #21242616)
- Platform / Device: macOS 10.14.6, Safari 13.0.2
- Reproducible Code Snippet or URL: https://pumped-reward.surge.sh/

**Comment by dmarcos** [comment]
Thanks for testing. Does https://github.com/aframevr/aframe/pull/4320 fix the problem? Not a desktop Mac handy to test at the moment

**Comment by nuel** [comment]
No luck, I just built the branch you made and now it's breaking at line 37: (same error)
```js
// device-orientation-permission-ui.js:37
// Show dialog only if permission has not yet been granted.
    DeviceOrientationEvent.requestPermission().catch(function () {
```

**Comment by dmarcos** [comment]
I see thanks. Just pushed a change. What about now?

**Comment by nuel** [comment]
That did the trick! Working perfectly now

**Comment by dmarcos** [comment]
Thanks for testing and the quick turnaround. Much appreciated
