### ISSUE TITLE
Edge: a-sky with src set to a video asset throws error and won't load

### ISSUE THREAD

**Issue by gwynethgwenmorgan** [aframevr/aframe#4319]
**Description:**

- A-Frame Version:  0.9.2
- Platform / Device:  Microsoft Edge, 41.16299.1419.0  on Windows 10
- Reproducible Code Snippet or URL:

      <a-scene class="aframebox" id="aframebox" embedded>
          <a-assets>
              <video muted id="enter" src="panos/ENTER.MP4" crossorigin="use-credentials"></video>
          </a-assets>
          <a-sky id="photoSphere" src="#enter" rotation="0 -92 0"></a-sky>
...etc...

This works fine in Firefox and Chrome, but gives a black screen in Edge.  The following error is output to the Javascript console repeatedly:

 WEBGL11156: INVALID_VALUE: texImage2D: The data for this video is not available

Panoramic JPEG images work fine using a tag such as:  `<img` id="photo" src="panos/SCENE3.JPG">

Sorry if this is something that everyone already knows about, I'm relatively new to Aframe but I have searched for an answer and not found one.

**Comment by dmarcos** [comment]
Difficult to tell without more context. Better if you share a link that people can look at. Glitch is a good way: https://glitch.com/~aframe

**Comment by gwynethgwenmorgan** [comment]
Hi, sorry for the delay in replying.  This example, which is already out there on Glitch, doesn't work for me on Edge (but does in other browsers) and generates the same error in the Javascript console as I get with my own code.  Is it possibly something to do with my Edge settings?

https://glitch.com/~aframe-360-video-example

**Comment by dmarcos** [comment]
That example uses an old A-Frame version 0.7.1. Try with 0.9.2

**Comment by gwynethgwenmorgan** [comment]
Thanks, Diego.  I'll check once I get back to the office, but I imagine my app's on an up to date version myself.  
Meanwhile, I'm thinking it might be to do with my corporately-managed Edge settings or the version of Edge?  I just tested the glitch example above from my home PC, and also my application, and both worked fine (Microsoft Edge 44.17763.831.0, Microsoft EdgeHTML 18.17763)

**Comment by gwynethgwenmorgan** [comment]
Hi, I've tried upgrading to the new version 1.0.0 (A-Frame Version: 1.0.0 (Date 2019-12-14, Commit #dc7d6174)) and am still getting the same issue, so I conclude that it's something to do with corporately-managed Edge settings.
