### ISSUE TITLE
Framerate drops drastically when left mouse button is held to rotate the camera

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [aframevr/aframe#4327]
**Description:**

Framerate drops a lot if you rotate the camera (only on chrome and not inside VR) the issue seems to disappear either when you open and close the inspector, or when you drag the cursor over an html div.

- A-Frame Version: 0.9.2
- Platform / Device: Google Chrome 78.0.3904.108 / Windows 10 Laptop
- Reproducible Code Snippet or URL: Any big project (you can try it in moonrider.xyz)

**Comment by dmarcos** [comment]
What about Chrome Beta (79) or Canary (80)?

**Comment by mauriciomartinez-itesm** [comment]
Performance is better in 

Chrome Version 80.0.3974.0 (Official Build) canary (64-bit)

for moonrider.xyz, there are somoe other bigger projects that suffer from the same issue though...

**Comment by dmarcos** [comment]
I can't reproduce on Beta or Canary. It looks like some sort of Chrome regression maybe related to the `mousemove` event.

**Comment by mauriciomartinez-itesm** [comment]
As you said, it appears to be a Chrome regression... hope they fix it soon!
