### ISSUE TITLE
Dynamically updated text broken.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#4334]
**Description:**

Due to three.js bump.

`THREE.BufferAttribute: .setArray has been removed. Use BufferGeometry .setAttribute to replace/resize attribute buffers`

https://github.com/Jam3/three-bmfont-text

```
    // New versions of ThreeJS suggest using setArray
    // to change the data. It will use bufferData internally,
    // so you can change the array size without any issues
    if (typeof attrib.setArray === 'function') {
      attrib.setArray(data)
    }
```

- A-Frame Version: master
- Platform / Device: firefox, desktop
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Problem has to be fixed on [three-buffer-vertex-data](https://github.com/Jam3/three-buffer-vertex-data/blob/master/index.js#L68), dependecy of `three-bmfont-text`
