### ISSUE TITLE
`dracoDecoderPath` no longer working due to unexpected `THREE.setDecoderPath()` removal

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#4337]
**Description:**
Draco-compressed models are no longer loading within A-Frame scenes, using the included `DRACOLoader`.

This happened suddenly, and I'm locked in at A-Frame `0.9.2`. It appears breaking changes made their way into this version, causing unexpected failures.

Console displays: `THREE.DRACOLoader: The .setDecoderPath() method has been removed. Use instance methods.`

I'm assuming this means that `gltf-model="dracoDecoderPath: ..."` fails entirely due to the method being removed.

I noticed that when reverting to `0.9.1`, it seems to work as expected.

Adding a separate `THREE.DRACOLoader` also seems to have fixed the issue in `0.9.2`, but I imagine that every A-Frame `0.9.2` project out there using Draco compression is now failing immediately via CDN, or on build, if they're relying on A-Frame's included `DRACOLoader`.

And once restored, if that's the plan, I'm not sure if those `DRACOLoaders` will conflict, so unsure if it's a viable fix long-term.

Others are reporting the same issue, so it's not isolated. Any help is greatly appreciated.

Thanks!

- A-Frame Version: `0.9.2`
- Platform / Device: All
- Reproducible Code Snippet or URL: Anything using `gltf-model="dracoDecoderPath: ..."`

**Comment by dmarcos** [comment]
It's my fault. A-Frame 0.9.2 broke on Oculus Browser due to changes in the WebXR API and made a mistake while hot fixing it. I reverted the change and everything should be good now. Let me know if you still have issues.

**Comment by dsinni** [comment]
Ah, right on, @dmarcos. No worries. We all make mistakes. I'll check and make sure all is good. Thanks, man.

**Comment by dsinni** [comment]
I can confirm that it appears to be working now. Thanks, @dmarcos !

**Comment by dmarcos** [comment]
Thanks for verifying
