### ISSUE TITLE
"Request the mobile version of this site" popup on Oculus Quest

### ISSUE THREAD

**Issue by Squareys** [aframevr/aframe#4338]
**Description:**

- A-Frame Version: master  (d0d979a5f0a77affea523dc3eaa68c8704b00b18)
- Platform / Device: Oculus Quest

Hey guys,

on current master, the latest Oculus Browser gets a popup to "Request the mobile version of this site to enjoy in immersive mode", yet the immersive mode is no problem. Looking at the commit history, this is a very recent addition (and meant for iOS devices?).

Best,
Jonathan

**Comment by dmarcos** [comment]
Thanks for reporting

**Comment by Squareys** [comment]
@dmarcos Amazing, thanks for the rapid fix!
