### ISSUE TITLE
Add "warp" user movement

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#434]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Friday Sep 04, 2015 at 02:10 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/67_

---

Enables user to look at a position in the 3D world and "warp" to it.

**Comment by vladbalan** [comment]
Is this feature still considered or is there a workaround to achieve this behavior?
:+1:

**Comment by ngokevin** [comment]
Currently, Don's https://github.com/donmccurdy/aframe-extras has a component for this called `checkpoint-controls` for now.

**Comment by ngokevin** [comment]
https://github.com/fernandojsg/aframe-teleport-controls
