### ISSUE TITLE
[master|WebXR] rendering broken with embeded scenes

### ISSUE THREAD

**Issue by Squareys** [aframevr/aframe#4340]
**Description:**

- A-Frame Version: master (d0d979a5f0a77affea523dc3eaa68c8704b00b18)
- Platform / Device: Oculus Browser 7.0 on Oculus Quest
- Reproducible Code Snippet or URL: Add `embedded` to any VR scene and enter VR

When entering VR on an embedded a-frame scene, the rendering will smear. The effect is created by the viewport being offset to the bottom left (in my case, I am guessing this is probably dependent on the offset of the a-scene in the page) and the edges being smeared across the framebuffer, which is not being cleared outside of this incorrect viewport.

My current workaround is to make the scene non-embedded.

I hope you can reproduce, my brief investigation did not produce any more usable hints...

Best, Jonathan.

**Comment by dmarcos** [comment]
I think this is no longer applicable. [Embedded scenes](https://aframe.io/aframe/examples/test/embedded/) are rendering as expected on the Oculus Browser. We can reopen if necessary
