### ISSUE TITLE
[fix included] Vive Focus (3DOF) joypad, trigger not working

### ISSUE THREAD

**Issue by IvoJager** [aframevr/aframe#4344]
**Description:**

- A-Frame Version: all (e.g. current master, 0.9.2 and older)
- Platform / Device: Vive Focus, Firefox Reality store version and sideloaded latest build
- Reproducible Code Snippet or URL: any AFRAME experience

Any AFRAME experience that uses the Focus' joypad seems to be unusable. Interestingly, using the trigger works ok for the purpose of actioning, however also sends out a joypad event translating in a backward/down/south event as if originating from such a joypad click.

I am wondering whether the controls (trigger, joypad) are perhaps enumerated incorrectly in the component?

**Comment by IvoJager** [comment]
As I suspected, changing src/components/vive-focus-controls.js;

```
 /**
   * Button IDs:
   * 0 - trackpad
   * 1 - trigger
   */
  mapping: {
    axes: {trackpad: [0, 1]},
    buttons: ['trigger', 'trackpad']
  },
```

into 

```
 /**
   * Button IDs:
   * 0 - trackpad
   * 1 - trigger
   */
  mapping: {
    axes: {trackpad: [0, 1]},
    buttons: ['trackpad', 'trigger']
  },
```

fixes the issue and makes joypad and trigger work correctly.

**Comment by dmarcos** [comment]
Fixed. Thanks for reporting
