### ISSUE TITLE
a-video don't work black screen

### ISSUE THREAD

**Issue by brunosilvadaniel** [aframevr/aframe#4351]
**Description:**

- A-Frame Version: 0.9.2
- Platform / Device: Desktop 
- Reproducible Code Snippet or URL: https://brunosilvadaniel.000webhostapp.com/index.html

So i was trying a test using a-frame the goal is  very simple show a video in a marker but i am runing some problems (new programmer btw), i am using just the a-video component inside a hiro marker preset as the code below:

`<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false; detectionMode: mono_and_matrix; matrixCodeType: 3x3;'>`
`<a-marker preset="hiro">`
       `<a-video rotation="90 0 0"autoplay="false" loop="true" `src="src/video-test2.mp4"></a-video></a-marker>
</a-scene>`
my problem is that almost every time i run the index page the video won't show up, only a black square in top of the marker the error that run on console is that:

"WebGL: INVALID_VALUE: tex (Sub) Image2D: video visible size is empty"

but some times the video work just fine no error, but it starts automatic even with autoplay = "false", i am using webhost000 just for testing, maybe that is the reason.

**Comment by dmarcos** [comment]
I recommend reading the FAQ: https://aframe.io/docs/0.9.0/introduction/faq.html#why-does-my-video-not-play-on-mobile

If this doesn’t solve the issue I recommend opening a question in [StackOverflow](https://stackoverflow.com/questions/tagged/aframe). We use github issues for bugs and feature requests. Nice folks to help in SO. Remember to provide a link to a simple example that reproduces the issue.

**Comment by brunosilvadaniel** [comment]
I find out how to fix justing forcing the video to play by a js command, i found the awnser on here [https://github.com/jeromeetienne/AR.js/issues/285](url), thx to @dmarcos for helping here and stackoverflow!

Bruno Silva Daniel

**Comment by dmarcos** [comment]
I’m glad you got it working!

**Comment by brandon-verastegui** [comment]
> 
> 
> @brandon-verastegui you can copy the url [jeromeetienne/AR.js#285](https://github.com/jeromeetienne/AR.js/issues/285)

Hi Marcos, are you talking about this: https://github.com/jeromeetienne/AR.js/issues/285#issuecomment-520140180 ?
By the way thank you very much for your work, where can I buy a shirt to support y'alls work?

**Comment by dmarcos** [comment]
Thanks! Yes, that comment. Most browsers today don’t allow video autoplay. You need a user gesture to start playback. Best of luck
