### ISSUE TITLE
v1.0.0 aframe-inspector won't load

### ISSUE THREAD

**Issue by mkungla** [aframevr/aframe#4352]
**Description:**
A-Frame `v1` tries to load non existing inspector asset from [unpkg.com](https://unpkg.com/aframe-inspector@1.0.x/dist/aframe-inspector.min.js)

inspector needs release with `v1` tag or in this line `aframe-inspector` version should be set with static `const` or something.
 
https://github.com/aframevr/aframe/blob/4510fb574a97aa2b70087bd6a581517c46404e3a/src/components/scene/inspector.js#L18

**meanwhile following workaround can be used**

```js
const scene = document.querySelector('a-scene')
scene.setAttribute('inspector', {url: 'https://unpkg.com/aframe-inspector@0.9.x/dist/aframe-inspector.min.js'})
```
or

```html
<a-scene
  inspector="url: https://unpkg.com/aframe-inspector@0.9.x/dist/aframe-inspector.min.js">
</a-scene>
```

- A-Frame Version: v1.0.0
- Platform / Device: *
- Reproducible Code Snippet or URL:  https://unpkg.com/aframe-inspector@1.0.x/dist/aframe-inspector.min.js

**Comment by dmarcos** [comment]
Thanks. I had forgot to publish the 1.0.0 inspector on npm. It should work now.
