### ISSUE TITLE
v1.0.0 - error loading GLTF/ GLB models

### ISSUE THREAD

**Issue by elbobo** [aframevr/aframe#4353]
Hi, congratulations on the new version

It seems that something has changed re: loading `.glb` models, when I try to add them to the page using v1 I get the following error message

`components:gltf-model:warn Unexpected token g in JSON at position 0`

I have no problems with the exact same code reverting to 0.9.2. Perhaps the way to include them has changed?

I used to get the same error when trying to load models on glitch as they added extra characters to the URL of the model, confusing things. This is the not the issue here however, the model is loaded as follows;

```
<a-assets>
       <a-asset-item id="puffer" src="https://cdn.glitch.com/0d947784-480e-4de3-8a31-7be6858cba3e%2Fpuffer_final.glb">
       </a-asset-item>
</a-assets>

<a-entity gltf-model="#puffer"></a-entity>
```
and I still get the error.

- A-Frame Version: 1.0.0
- Platform / Device: Macbook, Chrome 79
- Reproducible Code Snippet or URL: https://purrfect-list.glitch.me/

**Comment by dmarcos** [comment]
Set `response-type=“arraybuffer”` in your `a-asset-item` e.g: https://github.com/aframevr/aframe/blob/master/examples/showcase/anime-UI/index.html#L13

**Comment by eyexpo-dan** [comment]
Can you explain why `response-type="arraybuffer"` is needed now?

**Comment by dmarcos** [comment]
Automatic logic has been reintroduced in master. It will ship in A-Frame 1.0.1. You can use master in the meantime: https://cdn.jsdelivr.net/gh/aframevr/aframe@f77bcc2bfec96283af6a301bedc68c0274941005/dist/aframe-master.min.js
