### ISSUE TITLE
[1.0.0][Chrome m79] Gyro not working - device orientation not taken into account

### ISSUE THREAD

**Issue by mako-lw** [aframevr/aframe#4355]
**Description:**

Device orientation is not taken into account anymore in non-VR mode (aka magic window).

Works on Chrome m78, breaks in m79.

Tested on
* Pixel 2 (Android 10) with Chrome m78.0
* Pixel 2 (Android 10) with Chrome m79.0
* FRD-L09 (Android 7) with Chrome m78.0
* FRD-L09 (Android 7) with Chrome m79.0
* Samsung S7 (Android 8) with Chrome m78.0
* Samsung S7 (Android 8) with Chrome m79.0

Logging the `deviceorientation` event produces correct result.
```js
document.addEventListener('deviceorientation', console.log);
```

- A-Frame Version: 1.0.0 (dc7d6174)
- Platform / Device: Chrome m79
- Reproducible Code Snippet or URL: https://aframe.io/aframe/examples/boilerplate/hello-world/

**Comment by dmarcos** [comment]
Any errors on console?

**Comment by mako-lw** [comment]
> Any errors on console?

![image](https://user-images.githubusercontent.com/56032749/70932245-8bdd9200-2039-11ea-8739-86a958b14581.png)

[aframe.io-1576520442513.log](https://github.com/aframevr/aframe/files/3969575/aframe.io-1576520442513.log)

Unfortunately, nothing about that...

A quick search for `deviceorientation` in the repo yields nothing, is ThreeJS handling everything? Maybe it's worth a repro with ThreeJS.

I'll do a git bisect as soon as I have some time.

**Comment by mako-lw** [comment]
For comparison, https://threejs.org/examples/misc_controls_deviceorientation.html works in Chrome m79.

**Comment by mako-lw** [comment]
If anyone wants to take a shot at it before I do, here are some starting points:

1. https://github.com/mrdoob/three.js/blob/master/examples/misc_controls_deviceorientation.html
2. https://cdn.rawgit.com/mrdoob/three.js/master/examples/js/controls/DeviceOrientationControls.js
3. https://github.com/aframevr/aframe/blob/master/src/components/camera.js#L44

**Comment by mako-lw** [comment]
DeviceOrientationEvent used to be handled by webvr-polyfill but we don't use it anymore in Chrome m79? That's why it's not working in Chrome m79 but works fine in other browsers.

**Comment by dmarcos** [comment]
Magic window tracking is also using the Polyfill and only enabled when WebXR is not available. After Chrome m79, ARCore devices come with WebXR enabled so we have to make sure the Polyfill also kicks in that case.

**Comment by manitito** [comment]
If you disable flag "WebXR Device API" m79 - then gyro is working

**Comment by mako-lw** [comment]
> If you disable flag "WebXR Device API" m79 - then gyro is working

It works if you disable WebXR because then it uses the polyfill. It's not a proper fix though as you just can't ask all end users to disable the WebXR. It's also counter productive as the goal is to support the actual WebXR spec.
