### ISSUE TITLE
Show message when an experience is served over HTTP

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4357]
I saw tons of confusion among devs and users that don't understand why a site is not entering VR over WebXR. We could show  a message next or above the VR button to indicate that the content is served over HTTP and that VR mode is only available over HTTPS.  @thedart76 @brendanciccone in case you're interested.

My crappy sketch: 

![Image from iOS (6)](https://user-images.githubusercontent.com/39342/70952029-e535c900-2019-11ea-9b66-69b2c18325ce.jpg)

**Comment by thedart76** [comment]
How about using a customisable modal, consistent with the _"This Immersive Website requires access to your device motion sensors"_ one?

The modal would be displayed whenever the user clicks on the VR icon, but VR mode is not entered because the content is being served over HTTP.
Basically, it would show up if the `enter-vr` event is not fired after clicking on the VR icon.

**Comment by mkungla** [comment]
Why not to add disabled state to vr button when not served over `https` and have a `(?)` icon to trigger modal which can be customized? 

I think that would be good new feature for component `vr-mode-ui `

**Comment by brendanciccone** [comment]
I like Marko’s idea quite a bit - I think the VR button should definitely have more than one state.

A modal triggered by something would be great because it’s reusable for whatever.

**Comment by dmarcos** [comment]
- The VR button should be still active / enabled and will trigger fullscreen over HTTP
- I think a modal might be too intrusive because the experience is still completely functional in 2D mode. The goal of the bubble / message is just to inform the user / dev why VR mode is not working as expected.

**Comment by brendanciccone** [comment]
Do you think the bubble will be too small on mobile/smaller devices? 🤔

**Comment by thedart76** [comment]
> ...too intrusive because the experience is still completely functional in 2D mode...
Good point.

If you care about not cluttering the screen, another option could be to display the bubble/message only when the VR button is clicked (since you can't hover on it on mobile devices).

By doing so:
**a)** If the user/dev is unsuccessfully trying to enter VR mode, they would receive the solution to their problem.
**b)** If the user/dev simply wants to enjoy the experience fullscreen, they would be provided with an educational reminder.

**Comment by thedart76** [comment]
Not sure if you are trying to find an alternative solution to the bubble/message itself, instead, because you believe that it might not be the best option.

**Comment by mako-lw** [comment]
IMHO it feels like we force the UX down the throat of the developer. I agree with @davimello28 who [said about the iOS 13 popup](https://github.com/aframevr/aframe/issues/4287#issuecomment-548208060):

> The DeviceMotion permission is something that the developer using the platform should deal with. It means that aframe itself should not be responsible to make this request.
> 
> Although, I think that we should do add the banner as an option to be inserted when aframe loads and use it in the exemples provided. This will help developers to get things done.

For example, in our build we use `window.AFRAME_OPTS` to optionally declare some options before we load A-Frame  (ie. disable the css). It's useful but maybe too complicated.

If this is to improve the development experience, can't we just get away with a fullscreen fallback and a warning in the console? Basically educate the developer without forcing any UX.

**Comment by dmarcos** [comment]
@mako-lw Notice that the device permission dialog is both CSS customizable or can be turned off all together with a single attribute: https://aframe.io/docs/1.0.0/components/device-orientation-permission-ui.html#sidebar

Nice defaults is one of the main A-Frame value propositions. Most devs tinkering with VR are not expected to know about the quirks and differences across browsers.

For the HTTP dialog. It’s been the most common question I’ve been answering the last couple of months from both users and developers. Why A-Frame is not entering VR in Chrome? Why gyro is not working in A droid / Safari? A hard to miss message will help clarify. If the content is served over HTTPS the message will stay out of the way. I’m leaning towards a model as @thedart76 @brendanciccone suggested either at load or when the enter VR is clicked

**Comment by thedart76** [comment]
> Nice defaults is one of the main A-Frame value propositions. Most devs tinkering with VR are not expected to know about the quirks and differences across browsers.

I like this approach. Giving the devs the possibility to choose what to display sounds like a more modular and effective UX, ensuring different levels of assistance for both 1st-time/non-dev users and less-experienced WebXR devs.

Think of it like the default settings you find in many racing simulations video games: they set most (if not all) the driving assists ON; then it's up to you to customise the driving experience by turning ABS, TCS, Automatic Transmission, Breaking Line, and anything else OFF.
