### ISSUE TITLE
[aframe 1.0.0] only one HTC vive controller appears

### ISSUE THREAD

**Issue by harlyq** [aframevr/aframe#4358]
Only one HTC Vive controller (right) appears in aframe 1.0.0, works correctly in 0.9.2

- A-Frame Version:1.0.0
- Platform / Device: firefox 71.0, supermedium (last updated 11 Oct 2019) / HTC Vive
- Reproducible Code Snippet or URL:

    <a-scene>
      <a-entity hand-controls="left"></a-entity>
      <a-entity hand-controls="right"></a-entity>
    </a-scene>

**Comment by harlyq** [comment]
Code snippet:
```
    <a-scene>
      <a-entity hand-controls="left"></a-entity>
      <a-entity hand-controls="right"></a-entity>
    </a-scene>
```

**Comment by harlyq** [comment]
Locally I tried vive-controls.js with a controllerIndex of 0 (i.e. no indexing) and both controllers appear (the "hand" in the Gamepad object was correct)

**Comment by dmarcos** [comment]
Thanks for reporting. This is fixed in master now:

https://cdn.jsdelivr.net/gh/aframevr/aframe@d55475e494ab1c1269dff8f894ef8575e4b21dbd/dist/aframe-master.min.js

Let me know if it works for you

**Comment by harlyq** [comment]
Works for me - thanks
