### ISSUE TITLE
Modal dialog design review

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4359]
The [Device orientation permission UI](https://aframe.io/docs/1.0.0/components/device-orientation-permission-ui.html#sidebar) is the only place it's used at the moment. Considering using the same dialog to indicate that a site is using [HTTP](https://github.com/aframevr/aframe/issues/4357)

Below is the visual design I had come up without too much thought. You can see it in action on Safari for iOS and the [A-Frame examples](https://aframe.io/aframe/examples/). @thedart76 @brendanciccone Any criticism, ideas to improve it?

![Image from iOS (3)](https://user-images.githubusercontent.com/39342/71033058-7ca72480-20cb-11ea-8b0a-516e752d7f63.png)

**Comment by thedart76** [comment]
**1st Pass**:
• Ending the sentence with a dot.
• Styling the buttons using the A-Frame institutional colors (#ef2d5e and #24caff).

![Device-Orientation-Permission-UI-v1](https://user-images.githubusercontent.com/30973948/71052569-a56b0080-2143-11ea-9cd0-a27d833e4c53.png)

**Comment by dmarcos** [comment]
Awesome! Much better. I just incorporated the improvements on master. Thank you very much again.

**Comment by thedart76** [comment]
Great! Always happy to help.
