### ISSUE TITLE
Provide a way for applications to opt out of VR or AR modes

### ISSUE THREAD

**Issue by klausw** [aframevr/aframe#4362]
**Description:**

Currently, A-Frame applications automatically get an "AR" button if it detects support for WebXR's "immersive-ar" mode, and unconditionally shows a "VR" button which uses a polyfill if there's no native VR support.

Applications should have a way to opt out of this automatic selection. I think the default should still be both since it's at least worth trying both modes - even if the camera image isn't visible, AR mode can still act as a fancier 6DoF "magic window" mode for a VR experience.

What would be a good way to do this? Maybe `<a-scene disable-ar>`, or `<a-scene xr-modes="vr ar">`?

- A-Frame Version: 1.0.0
- Platform / Device: Android, but also other WebXR sites going forward
- Reproducible Code Snippet or URL: n/a

**Comment by klausw** [comment]
FYI, a workaround in the current version would be to hide unwanted buttons via CSS if necessary, but I think it would be cleaner to have a more official way to do this. (This is also a bit tricky to do from Javascript since the buttons get added asynchronously.)

```css
/* div.a-enter-ar, */
div.a-enter-vr {
  visibility: hidden;
}
```

**Comment by dmarcos** [comment]
Probably via `vr-mode-ui` component: https://aframe.io/docs/1.0.0/components/vr-mode-ui.html#example

`<a-scene vr-mode-ui="arEnabled: false">`

**Comment by kylebakerio** [comment]
This can probably be closed now, yeah?

**Comment by dmarcos** [comment]
Yeah thanks!
