### ISSUE TITLE
[1.0.0][Chrome m79] 360 video and Image not working in VR mode

### ISSUE THREAD

**Issue by AntoineLucidWeb** [aframevr/aframe#4365]
Hello Aframe community !

with https://aframe.io/examples/showcase/sky/ or https://ribbon-shear.glitch.me/ when switching to VR mode with chrome on android I get a black screen, no video or image displayed. No luck with console, no error displayed. 

- A-Frame Version: 1.0.0 (Date 2019-12-14, Commit #dc7d6174)
- Platform / Device: 
Android Chrome 79 : pixel 2
Android Chrome 79 : galaxy s 7
Android Chrome 79 : note 4
- Reproducible Code Snippet or URL:
https://aframe.io/examples/showcase/sky/ 
https://ribbon-shear.glitch.me/

**Comment by MK-LucidWeb** [comment]
Working ThreeJS example: https://threejs.org/examples/#webxr_vr_video
