### ISSUE TITLE
device:error WebXR session support error: sceneEl is null

### ISSUE THREAD

**Issue by mkungla** [aframevr/aframe#4373]
**Description:**

Everything here needs `DOMContentLoaded` before right?

https://github.com/aframevr/aframe/blob/b9b681329e51afb3d79193ee687fdc77a58d4181/src/utils/device.js#L28

- A-Frame Version: `1.0.2`
- Platform / Device: Firefox/WebXR API Emulator
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
What URL, browser, headset?

**Comment by mkungla** [comment]
Firefox/WebXR API Emulator, haven't seen it with devices yet.

So I wrapped `src/utils/device.js` `if (isWebXRAvailable) ` with `document.addEventListener('DOMContentLoaded', () => `

https://github.com/aframevr/aframe/blob/b9b681329e51afb3d79193ee687fdc77a58d4181/src/utils/device.js#L28-L74

and `src/utils/tracked-controls.js` 

https://github.com/aframevr/aframe/blob/b9b681329e51afb3d79193ee687fdc77a58d4181/src/utils/tracked-controls.js#L163-L164

between these lines there is no error checking if `controller.profiles[n]` is undefined which is currently case with `WebXR API Emulator`

e.g. 
```js
if (!profiles[j]) { profiles[j] = 'oculus-touch' }
```

after adding  these dirty fixes emulator works fine - almost.

**Comment by dmarcos** [comment]
I fixed the first issue on https://github.com/aframevr/aframe/commit/7f017a3a47c7804f8041e00dcb494032c4714d03

Issue with controllers is something different. `controller.profiles` should be an array of strings. I believe existing entries with undefined values shouldn't happen. It looks like a bug in the WebXR implementation of the emulator.
