### ISSUE TITLE
AR Button does not appear

### ISSUE THREAD

**Issue by uurcankaya** [aframevr/aframe#4375]
**Description:**

- A-Frame Version: 1.2
- Platform / Device: Android
- Reproducible Code Snippet or URL: Aframe samples

 Hello WebXR example is not showing AR button on Chrome 79+ 
https://aframe.io/examples/showcase/helloworld/

**Comment by dmarcos** [comment]
You have to have an ARCore compatibld device and enable “WebXR AR Module” in chrome://flags
