### ISSUE TITLE
Add animated gifs

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#438]
<a href="https://github.com/nickdesaulniers"><img src="https://avatars.githubusercontent.com/u/1823839?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nickdesaulniers](https://github.com/nickdesaulniers)**
_Friday Sep 04, 2015 at 16:36 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/71_

----

three.js doesn't seem to resample from images when they're animated gifs.  I'm not sure if there's a turn this on easily or not.  In raw webgl, I could do this easily, but I don't know if I can feed three a WebGLTexture object.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Friday Sep 04, 2015 at 17:14 GMT_

----

An example: http://stemkoski.github.io/Three.js/Texture-Animation.html

Each frame of the animation is captured as a texture, which are then cycled through with offsets.

**Comment by ngokevin** [comment]
<a href="https://github.com/nickdesaulniers"><img src="https://avatars.githubusercontent.com/u/1823839?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nickdesaulniers](https://github.com/nickdesaulniers)**
_Friday Sep 04, 2015 at 17:35 GMT_

----

No, that example is using Texture Atlases, not animated gifs.
http://stemkoski.github.io/Three.js/images/run.png
http://stemkoski.github.io/Three.js/images/explosion.jpg

**Comment by ngokevin** [comment]
https://github.com/maxkrieger/aframe-draw-component

**Comment by ngokevin** [comment]
https://github.com/mayognaise/aframe-gif-component

**Comment by dparker2** [comment]
Are there any better libraries for gifs? The one posted hasn't been updated in a while and has various issues.
