### ISSUE TITLE
Drag in desktop VR Mode broken

### ISSUE THREAD

**Issue by AG-LucidWeb** [aframevr/aframe#4380]
Hello everyone !

Found this bug : 

**Description: On desktop, when switching to VR mode, it's not possible to look around anymore**

- A-Frame Version:from 1.0.2 to 1.0.3
- Platform / Device: Ubuntu 18.04.3 LTS/ Manjaro 18.1.5, Chromium Version 79.0.3945.79 , Firefox 71.0
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

**Comment by AG-LucidWeb** [comment]
looks like it also break the cursor on vr : https://lunar-blossom.glitch.me/

**Comment by AG-LucidWeb** [comment]
https://github.com/aframevr/aframe/issues/4383#issue-544193633 probably the same issue

**Comment by zone4182** [comment]
The problem is already introduced in the initial version 1.0.
