### ISSUE TITLE
Tablet is not recognized as mobile device [1.0.3]

### ISSUE THREAD

**Issue by salbanese** [aframevr/aframe#4381]
I tested the latest version on Chrome on a Galaxy Tab A tablet and I get a message saying I must request the mobile version to get the immersive mode. I don't have the issue on Safari on an iPad, what defines if a device is "mobile" or not? Is it something that can be fixed or does it depend on devices?

- A-Frame Version: 1.0.3
- Platform / Device: Android 9 / Samsung Galaxy Tab A

**Comment by dmarcos** [comment]
Safari for iPad (on latest iPad OS) and some other browsers for tablets request the desktop version of websites by default where the devicemotion API is not available. The message prompts the user to set the browser to request the mobile version. In safari for iOS is done in the menu behind the `aA` button in the url bar. I don’t know about Android tablets.

**Comment by salbanese** [comment]
Thanks, I just checked the tablet again and it was not related to the Desktop/mobile version, I had the problem on both modes. But I made a DeviceMotion test, and it appears that it's not supported by the device... I was somehow remembering I made it work a few months ago but it seems not, sorry!

**Comment by mkeblx** [comment]
I have been testing a few Android tablets and browser combinations, already in mobile version, and encounter the same popup. This popup display logic needs to be reworked a bit. I can submit a patch for and test on Android tablets.

**Comment by dmarcos** [comment]
Thanks for investigating. A PR will be more than welcom

**Comment by salbanese** [comment]
Hello,
Do you know if there was something done about this issue? I encounter the problem with a few tablets in v 1.0.5 and clearly the problem is the user agent detection function...

**Comment by dmarcos** [comment]
It's not a bug on the A-Frame side or something we can address without user intervention.

As described above, mobile browsers now offer a desktop mode that many tablets default too. A Website cannot set the browser mode and can only request the user to change it. 

Mobile browsers on desktop mode disguise the `userAgent` to look like a desktop browser. Some APIs like `DeviceMotion` used by A-Frame's magic window are only available in mobile mode. A-Frame uses a known hack (`window.orientation !== undefined` ) to detect those "fake" desktop browsers and prompt the user to change it to mobile mode. That's unfortunately the best we can do.

**Comment by arpu** [comment]
maybe  use some newer standards ? like https://user-agent-client-hints.glitch.me/ 
but the api is still in Draft https://wicg.github.io/ua-client-hints/

**Comment by dmarcos** [comment]
Thanks. The day that API becomes available will be indeed handy.
