### ISSUE TITLE
/refactor - Rewrite using WebComponents

### ISSUE THREAD

**Issue by LukeTOBrien** [aframevr/aframe#4382]
Hello there,

This idea would need to be a total rewrite of A-Frame, so would go on a new refactor branch.

I think A-Frame project was started before Web Components and [Custom Elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) were around, but now I think it would be good to keep up with the standard and to rewrite all of the components as Web Components.

When I write Web Components I tend to favour TypeScript, I sense the community might not like prefer TypeScript, but I think some kind of moduar way of working should be used.  
I like to keep my classes short and I noticed that `a-entity` is 932 lines for eg....

Just an idea :-)

**Comment by dmarcos** [comment]
Thanks for filing. A-Frame uses custom elements that is one of the APIs under the web components umbrella term. There’s a [WIP to move to the version 1](https://github.com/aframevr/aframe/pull/4167) of the standard but it’s just about code hygiene and getting rid of the polyfill. The rest of the Web Components APIs are not very relevant to 3D scenes.

You can write your application in your preferred language, A-Frame doesn’t impose any. A-Frame core code base is mostly only relevant to maintainers and contributors.
