### ISSUE TITLE
HUD/RIG/Cursor – not moveable with camera in VR on mobile

### ISSUE THREAD

**Issue by liewol** [aframevr/aframe#4383]
Hi there!

I have a HUD-problem in 1.0.3 and the masterbuild when entering VR-Mode on IOs or Android (Chrome, Safari). The plane (or a cursor) is not fixed to the camera in VR on mobile devices – on desktop it works as expected – also in VR-mode.
In previous aframe-versions I put the camera and a cursor (as a child) in a rig but this does not longer work in mobile vr. 
The example from the docs shows the problem on mobile after switched to vr.

https://aframe-hud.glitch.me/

- A-Frame Version: 1.0.3, master
- Platform / Device: only mobile-devices in vr (ios: 13.3, android: 9 )
- Reproducible Code Snippet: https://glitch.com/edit/#!/aframe-hud

The problem also occurs in the cursor example:
https://aframe.io/aframe/examples/test/cursor/

**Comment by dmarcos** [comment]
This is now fixed in [master](https://cdn.jsdelivr.net/gh/aframevr/aframe@e850be07c3a96fdfbafbd57c63cd2679fea0fcb1/dist/aframe-master.min.js)

Working glitch:

https://glitch.com/edit/#!/radical-titanium?path=index.html:5:125
