### ISSUE TITLE
Cannot get camera world properties in VR mode

### ISSUE THREAD

**Issue by rienheuver** [aframevr/aframe#4385]
**Description:**

- A-Frame Version: 1.0.3
- Platform / Device: Chrome for Android
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/resisted-carp?path=index.html:1:0

The example above uses `getWorldDirection()` on the camera-object. However, that value doesn't update when in VR-mode. In the example, the camera moves in the direction it is looking, but when you enter VR-mode you'll see that you'll just be moving in a straight line.

The world quaternion doesn't update either, so the following code from the documentation no longer works in VR-mode: https://aframe.io/docs/1.0.0/components/camera.html#reading-position-or-rotation-of-the-camera

Not certain which exact version this problem is introduced in, but at least it doesn't happen in 0.9.2 when using cardboard-mode.

**Comment by smeybi** [comment]
I can confirm, something with the position on camera doesn't work with A-Frame 1.0.3 (also 1.0.2), it works with 1.0.1. 
Tested with Vive/Firefox.

A added plane is not following the camera

`<a-entity camera look-controls>
  <a-entity geometry="primitive: plane; height: 0.2; width: 0.2" position="0 0 -1"
            material="color: gray; opacity: 0.5"></a-entity>
</a-entity>
`

**Comment by dmarcos** [comment]
This has been fixed on [master](https://glitch.com/edit/#!/political-mozzarella?path=index.html:18:53) by https://github.com/aframevr/aframe/commit/d3b9a30aeb812f91fd83a941c2f54dc0bfc24385

Corrected and working glitch:

https://glitch.com/edit/#!/political-mozzarella?path=index.html:18:53
