### ISSUE TITLE
AFRAME.ANIME does not animate in VR mode while served over https

### ISSUE THREAD

**Issue by disasteroftheuniverse** [aframevr/aframe#4386]
**Description:**

- A-Frame Version: 1.0.3
- Platform / Device: Oculus Quest
- Reproducible Code Snippet or URL: 

`AFRAME.ANIME({ ... })` does not work while in VR mode served over HTTPS. Components which use AFRAME.ANIME while in VR Mode do not animate, even with `autoplay: true` set in the configuration. All animations work after VR mode is exited. This behavior does not affect the animation component. It only affects components which call AFRAME.ANIME. It appears some promise is holding them back.

Content served via http appears to work as intended.

**Comment by dmarcos** [comment]
Link to reproduce?

FWIW, the [animation](https://aframe.io/docs/1.0.0/components/animation.html#sidebar) component uses [anime](https://github.com/aframevr/aframe/blob/master/src/components/animation.js#L167) underneath and the [animation examples](https://aframe.io/aframe/examples/test/animation/) work for me over HTTPS and in VR mode on the Quest / Oculus Browser.

**Comment by disasteroftheuniverse** [comment]
Here is a url where you can see this behavior:

https://flame-laser.glitch.me

The 'telekinesis' component has the AFRAME.ANIME. method in it. This problem only occurs in Oculus Browser. It does not seem to occur in Firefox Reality.

**Comment by dmarcos** [comment]
Code is pretty complicated. My hunch is that the problem is somewhere else and not directly related to ANIME since the animation component works. If you reduce to a simple example that instantiates AFRAME.ANIME and reproduces the issue it will be easier to investigate.

**Comment by disasteroftheuniverse** [comment]
That was my first instinct too. But this is actually stripped out of the full context. Let me simplify further.

**Comment by disasteroftheuniverse** [comment]
Updated. I stripped out everything except the stuff which isn't working. It functions as intended in Firefox Reality. It does _not_ work as intended in Oculus Browser.

**Comment by dmarcos** [comment]
I recommend checking browser console errors

**Comment by disasteroftheuniverse** [comment]
I checked the console. There were no additional messages that indicated any issues. 

As an alternate test, I imported the _tweenjs_ library, and it appeared to have the same problem. The animation simply would not play. 

My gut instinct is that some callback isn't firing because of some unresolved Promise, because the animation does occur, but only _after_ I have exited VR mode.

**Comment by dmarcos** [comment]
You have to use the A-Frame `tick` method to advance the animation. ANIME uses `window.requestAnimationFrame` to play the animation that doesn't fire when presenting in WebXR. 

[Example of ANIME using the tick method](https://glitch.com/edit/#!/longhaired-volleyball?path=my-animation.js:21:11)
