### ISSUE TITLE
Far clipping doesn't work properly in WebXR browsers

### ISSUE THREAD

**Issue by DougReeder** [aframevr/aframe#4387]
**Description:**
Objects > 1000m away, but within camera far clipping plane, should be visible. Under WebVR, they are. Under WebXR, they are not.

- A-Frame Version: 1.0.3
- Platform / Device: Android Chrome 79 on Galaxy S6, Oculus Browser 7.1.2 on Oculus Quest
- Reproducible Code Snippet or URL:
https://glitch.com/edit/#!/educated-slayer?path=index.html:16:41
This just has an a-sky with radius="9000" and a camera with far="10000"

The render state appears to be set with the baseLayer, but not depthNear nor depthFar
```JavaScript
session.updateRenderState( { baseLayer: new XRWebGLLayer( session, gl,
  {
    antialias: gl.getContextAttributes().antialias,
    alpha: gl.getContextAttributes().alpha,
    depth: gl.getContextAttributes().depth,
    stencil: gl.getContextAttributes().stencil
  }
) } );
```
https://immersive-web.github.io/webxr/#xrrenderstate-interface

It's also possible that the maximum far clip plane is only 1000 on these platforms (which is legal)

**Comment by dmarcos** [comment]
WebXR default is 1000 and there's no way to change it at the moment. We should incorporate a way to override the defauly in the [WebXRManager](https://github.com/mrdoob/three.js/blob/e840cb70447030d50d22a830f26ba918e62e4018/src/renderers/webxr/WebXRManager.js#L167)

**Comment by DougReeder** [comment]
Presuming a fix is made to Three.js, would it be preferable to cherry-pick the fix to super-three, or merge the latest version of Three.js?

**Comment by dmarcos** [comment]
It depends. Cheery-pick if we want to ship it in a minor version 1.0.X

Bumping THREE versions is disruptive and we can rebase for major versions 1.X.0

**Comment by dmarcos** [comment]
We can cherry-pick this for 1.0.4. Thanks for the effort on THREE
