### ISSUE TITLE
hand-controls hand model rotation no longer matches oculus quest touch controller rotation

### ISSUE THREAD

**Issue by dbradleyfl** [aframevr/aframe#4388]
**Description:**
The hand-controls hand model is now rotated roughly 90deg off of the proper rotation on the Oculus Quest touch controls. Seems to be related to #4331 (I will investigate)
- A-Frame Version: 1.0.1 and 1.0.2 and 1.0.3
- Platform / Device: Oculus Quest
- Reproducible Code Snippet or URL: https://glitch.com/~aframe-1-0-3-hands

**Comment by dbradleyfl** [comment]
Looks like a change was made to oculus-touch-controls that might cause the hand model rotation to no longer match #4374

**Comment by dala00** [comment]
Oh, this may be same for my issue. I just created a sample.

https://glitch.com/~aframe-model-test

On this sample, gun rotation differs between HTTPS (like glitch) and HTTP (local). Copy this code and save to html file and start local server, and access to it by Oculus Quest, rotation differs.
