### ISSUE TITLE
Oculus Quest browser breaks with 'embedded' flag set in scene

### ISSUE THREAD

**Issue by dirkk0** [aframevr/aframe#4394]
**Description:**

- A-Frame Version:
1.0.3 (Date 2020-01-06, Commit #d3b9a30a)
- Platform / Device:
Oculus Quest Browser
- Reproducible Code Snippet or URL:
https://curious-electric.com/w/experiments/aframe/minimal-quest-embedded/

Upon VR activation you land in a strange line soup.

Error on console is:
“Uncaught DOMException: Failed to execute ‘getPose’ on ‘XRFrame’: XRSpace and XRFrame sessions do not match.”

The problem happens when I had the embedded flag set in the scene - removing that made it work again.

Thanks for looking into this, and the great work, overall.

**Comment by michaelnebeling** [comment]
I'd say you just need to give the a-scene a non-zero width and height via css, that's it.

**Comment by dmarcos** [comment]
It works for me. The scene enters VR mode as expected. As @michaelnebeling you have to set a size on the scene to be visible in 2D mode. I think there's nothing actionable on A-Frame side but can reopen if necessary.
