### ISSUE TITLE
Cursor stops following camera orientation in VR mode on iOS

### ISSUE THREAD

**Issue by samesimilar** [aframevr/aframe#4399]
In a scene with a cursor attached to the camera:  When you switch to VR mode on iOS the cursor stops following the direction that the user is looking. 

A semi-related but possibly separate issue: after switching to VR mode on iOS and then back again, the camera y-position changes.

- A-Frame Version: 1.0.3
- Platform / Device: iOS 13.3, iPhone 11 Pro Max
- Reproducible Code Snippet or URL: https://glitch.com/~shaded-single

**Comment by dmarcos** [comment]
This has been fixed in master:

https://cdn.jsdelivr.net/gh/aframevr/aframe@e850be07c3a96fdfbafbd57c63cd2679fea0fcb1/dist/aframe-master.min.js
