### ISSUE TITLE
iOS Leaving VR mode causes tiny canvas

### ISSUE THREAD

**Issue by jconnolly-bond** [aframevr/aframe#4400]
**Description:**

iOS Safari (+ Chrome) - leaving VR mode with an embedded a-scene causes the scene canvas to resize to 100px x 100px. 

I believe it is related to this code taken from webvr polyfill https://github.com/aframevr/aframe/blob/master/src/utils/forceCanvasResizeSafariMobile.js
Although I don't believe they use this workaround anymore.

- A-Frame Version: 1.0.3, Master
- Platform / Device: Safari Chrome / iPhone 7 iOS 13.3 
- Reproducible Code Snippet or URL: https://large-scion.glitch.me/

**Comment by jconnolly-bond** [comment]
For anyone experiencing the same issue, this is the workaround I am using:
`
// On exit-vr
if (AFRAME.utils.isIOS()) {

    setTimeout(() => {

      const scene = document.querySelector('a-scene');
      if (scene) {

        scene.canvas.style.width = '100%';
        scene.canvas.style.height = '100%';

      }
    }, 300); // 300ms because existing workaround uses 200ms timeout
}
`

**Comment by dmarcos** [comment]
This is an iOS 13 regression. Moving conversation to https://github.com/aframevr/aframe/issues/4617
