### ISSUE TITLE
iOS does not support camera children in VR

### ISSUE THREAD

**Issue by jconnolly-bond** [aframevr/aframe#4401]
**Description:**

Camera entity children no longer track the camera's orientation in VR mode. Does however function as expected with magic window. I assume this is because Safari does not support WebXR. I've confirmed that this behaviour did work in 1.0.1 but something has broken it in 1.0.2 onwards. 

- A-Frame Version: 1.0.3, Master
- Platform / Device: Safari Chrome / iPhone 7 iOS 13.3
- Reproducible Code Snippet or URL: https://elfin-lobe.glitch.me/

**Comment by dmarcos** [comment]
Bug fixed in master. It will ship in 1.0.4 or you can use master builds now:

https://cdn.jsdelivr.net/gh/aframevr/aframe@e850be07c3a96fdfbafbd57c63cd2679fea0fcb1/dist/aframe-master.min.js
