### ISSUE TITLE
Cursor gone when on vr mode on mobile.

### ISSUE THREAD

**Issue by janel-miyens** [aframevr/aframe#4403]
**Description:**

How do I enable the cursor (a-cursor tag)/ add the cursor on the dual screen when I go to vr mode on mobile.
Why the cursor gone when I go to vr mode on mobile?

I look on the docu about vr mode ui, a-cursor, and a-scene on aframe docs but it has no info about it.

- A-Frame Version: v1.0.3
- Platform / Device: android
- Reproducible Code Snippet or URL:

Thanks for the response :)

**Comment by dmarcos** [comment]
Bug fixed on master. You can use master builds until A-Frame 1.0.3 ships: 

https://cdn.jsdelivr.net/gh/aframevr/aframe@e850be07c3a96fdfbafbd57c63cd2679fea0fcb1/dist/aframe-master.min.js
