### ISSUE TITLE
 Extend look-controls schema

### ISSUE THREAD

**Issue by jconnolly-bond** [aframevr/aframe#4404]
**Description:**

Magic window support is great but being able to enable and disable using schema would be nice. (The google photos 360 image viewer handles this nicely)

This and being able to remove the y axis limitation on touch move with the schema could also improve the component a lot.

- A-Frame Version: 1.0.3
- Platform / Device: Mobile
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
You can already disable touch on look-controls or disable the whole component all together:

https://aframe.io/docs/1.0.0/components/look-controls.html#properties_enabled

If you have different requirements than default behavior you can derive your own component from look controls. Constraining touch to the y axis is a deliberate decision

**Comment by jconnolly-bond** [comment]
I am referring to giving an option to disable the device orientation magic window controls. Not the component altogether. 
The reason I suggested this feature is that it is mirrored by touchEnabled so thought a magicWindowEnabled would be a good option to pair with it. Allowing the user to have touch only or device orientation only look-controls. 

I don't doubt these are deliberate decisions but copying a file to change one line didn't feel like a good approach.

I am happy to make a PR and let the reviewers decide if it is suitable.

**Comment by dmarcos** [comment]
What’s your use case that needs magic window disabled?

**Comment by jconnolly-bond** [comment]
Just feels like something that not everyone would want to have enabled by default. If I want to view a 360 degree photo in an app while my phone is on my lap or on a desk then the camera is stuck looking at the floor. My first reaction would be to drag the screen to look upwards but as discussed y-axis touch move is intentionally disabled.

**Comment by tiagovignatti** [comment]
FYI the very same situation described by @jconnolly-bond is a real case problem that our clients have been asking for.

We solved this by getting a reference of look-controls component and overriding onTouchMove - pretty much what some [other folks are also doing](https://stackoverflow.com/a/42636713/1415058). OTOH would be more convenient to just have a scheme to constrain or not the axes.

**Comment by dmarcos** [comment]
No publicly exposed but can disable `magic window` by hacking into the component: `cameraEl.components['look-controls'].magicWindowControls.enabled = false`. Below a working example. Notice:

`<a-scene background="color: #FAFAFA" disable-magicwindow device-orientation-permission-ui="enabled: false">`

https://glitch.com/edit/#!/inconclusive-eoraptor?path=disable-magicwindow.js:4:66

**Comment by theckdobbs** [comment]
so not allowing users to have magic touch and device only-not to sure [Grand Canyon [](tour](uhttps://www.grandcanyondestinations.comrl))
