### ISSUE TITLE
Going back and forth VR mode with laser controls break app on https

### ISSUE THREAD

**Issue by AG-LucidWeb** [aframevr/aframe#4406]
Hello Community !

With lazer controls, on Oculus Quest, Go and Google Daydream, going in VR mode then escaping then going back again crash aframe when app served over https

- A-Frame Version: 1.0.3 (and latest version on master/dist)
- Platform / Device: Oculus Quest, Go (oculus browser) and Google Daydream (chrome)
- Reproducible Code Snippet or URL: https://glitch.com/~lunar-blossom
Message in the console with Chrome and Google Daydream and Oculus browser on Quest
```
tracked-controls-webxr.js:102 Uncaught DOMException: Failed to execute 'getPose' on 'XRFrame': XRSpace and XRFrame sessions do not match.
    at i.tick (https://cdn.jsdelivr.net/gh/aframevr/aframe@2c5c131dccaab9d449fcd0383e98d027a5bc07f6/dist/aframe-master.min.js:907:2890)
    at HTMLElement.tick (https://cdn.jsdelivr.net/gh/aframevr/aframe@2c5c131dccaab9d449fcd0383e98d027a5bc07f6/dist/aframe-master.min.js:943:11885)
    at HTMLElement.render (https://cdn.jsdelivr.net/gh/aframevr/aframe@2c5c131dccaab9d449fcd0383e98d027a5bc07f6/dist/aframe-master.min.js:943:12419)
    at https://cdn.jsdelivr.net/gh/aframevr/aframe@2c5c131dccaab9d449fcd0383e98d027a5bc07f6/dist/aframe-master.min.js:1074:132
    at u (https://cdn.jsdelivr.net/gh/aframevr/aframe@2c5c131dccaab9d449fcd0383e98d027a5bc07f6/dist/aframe-master.min.js:134:27359)
    at XRSession.e (https://cdn.jsdelivr.net/gh/aframevr/aframe@2c5c131dccaab9d449fcd0383e98d027a5bc07f6/dist/aframe-master.min.js:132:12664)```

**Comment by dmarcos** [comment]
@Artyom17 Any feedback on this one? Following the error message I opened a PR to reset and request a new XRReferenceSpace when exiting and entering VR but still get the same message:

https://github.com/aframevr/aframe/pull/4408

**Comment by Artyom17** [comment]
@dmarcos Well, according to https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/xr/xr_frame.cc?type=cs&q=XRSpace+and+XRFrame+sessions&sq=package:chromium&g=0&l=62 you can't use XRReferenceSpace from a different session, need to request new one for each session.

PS. something got wrong with email notifications from github

**Comment by Artyom17** [comment]
What are the plans on fixing this issue, @dmarcos?

**Comment by dmarcos** [comment]
@Artyom17 I had opened a PR resetting the session when entering VR but I was getting the same error. Needs more investigation but haven't got around yet. Feel free to give a try. You might be able what we
're doing wrong quickly: https://github.com/aframevr/aframe/pull/4408/files

**Comment by Artyom17** [comment]
@dmarcos  I am not familiar with the A-Frame architecture. You need to make sure that referenceSpace is new for each session, whether it is used for controllers or for the head tracking. You definitely should not re-request reference space when you are exiting vr, just reset it to undefined or something (not sure what those 'enter-vr' / 'exit-vr' events are, though).
The safest place to request for the reference space is in requestSession success-callback.

**Comment by antoniohof** [comment]
hey people, do you know any workaround for this problem?

thank you

**Comment by dmarcos** [comment]
It's fixed in master. You can use [master-builds](https://cdn.jsdelivr.net/gh/aframevr/aframe@24fbb922b5960ba1a579a019afa0c9d64396057b/dist/aframe-master.min.js) until 1.0.4 ships.

**Comment by Artyom17** [comment]
Cool, thanks!
