### ISSUE TITLE
Investigate physics implementation

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#441]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Friday Sep 04, 2015 at 17:36 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/74_

---

Enables the developer to specify the physics properties of their scene.

For example:
- Collision behaviors (eg all objects default to rigid bodies w/ collision enabled by default?)
- Player movements (eg slower walking speed for underwater level)
- Gravity (eg low gravity for moon level)

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Friday Sep 04, 2015 at 17:36 GMT_

----

Related to #68

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Friday Sep 04, 2015 at 17:37 GMT_

----

Goal of this issue is to arrive at a long term solution for vr-markup, then implement the essential first few interactions for v1 release.

**Comment by ngokevin** [comment]
<a href="https://github.com/nickdesaulniers"><img src="https://avatars.githubusercontent.com/u/1823839?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nickdesaulniers](https://github.com/nickdesaulniers)**
_Friday Sep 04, 2015 at 21:40 GMT_

----

I'm taking a look at [cannon.js](https://github.com/schteppe/cannon.js) currently.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Saturday Sep 05, 2015 at 18:56 GMT_

----

Per @kearwood's advice, we should also make sure that collisions are relatively low-friction, so a user walking past a cube does not become stuck unnecessarily.

**Comment by ngokevin** [comment]
https://github.com/ngokevin/aframe-physics-components

**Comment by donmccurdy** [comment]
@ngokevin Have you all decided whether this will be a new physics implementation, or try to integrate cannonjs / oimojs / etc with A-Frame?

**Comment by RangerMauve** [comment]
@donmccurdy I think that's being discussed [here](https://github.com/ngokevin/aframe-physics-components/issues/7)

**Comment by donmccurdy** [comment]
@RangerMauve oh! Cool thanks I missed that.

**Comment by ngokevin** [comment]
And with Oimo https://github.com/JoshGalvin/aphysics

We'll compare which is more appropriate. Feel free to vote for an engine.

**Comment by bnolan** [comment]
I'd put a vote for cannon, I've found it predictable and reliable. If you set the global friction to 0.0, then you can slide past boxes when you run into them. The newest cannon supports running the physics at a lower frame rate than the renderer, and just interpolating the inbetween steps, which might be useful. Ammo is a beast, it's really big. Oimo is a pretty legit option, but cannon has better documentation, and @schteppe is a pretty responsive dude.

**Comment by dmarcos** [comment]
@bnolan Thanks for the breakdown

**Comment by ngokevin** [comment]
@bnolan thanks so much for input from your experience! We knew about the Cannon being better documented, Oimo being quick, and Ammo being big, but the notes about friction, framework, interpolation are great to know

**Comment by ngokevin** [comment]
I think we'll keep external at https://github.com/donmccurdy/aframe-physics-system for now (given the file size and not all scenes need physics). If it becomes more ubiquitous, we can naturally re-consider.
