### ISSUE TITLE
Oculus Touch controllers v2 support

### ISSUE THREAD

**Issue by connorshea** [aframevr/aframe#4410]
**Description:**

- A-Frame Version: 1.0.3
- Platform / Device: Oculus Rift S, Oculus Touch v2 controllers
- Reproducible Code Snippet or URL: 

My Oculus Touch v2 controllers render as Oculus Touch v1 controllers:

![image](https://user-images.githubusercontent.com/2977353/72670863-08301000-3a00-11ea-9027-1a4202bb26cd.png)

You can see the difference between the first and second generation controllers in the [Wikipedia article's History section](https://en.wikipedia.org/wiki/Oculus_Touch#History).

They work fine, but the model should be different. I'm not sure if this is a big enough problem to bother fixing, but I figured I'd open an issue since it bugged me a bit.

Worst case, I can just find a 3D model and override the model myself.

**Comment by dmarcos** [comment]
What browser?

**Comment by connorshea** [comment]
Firefox 72 on Windows

**Comment by connorshea** [comment]
I might just be dumb, let me check again tonight since I noticed there is a v2 model in the source. I could have sworn the controller was the old version, but I don't want to send you on a wild goose chase.

**Comment by dmarcos** [comment]
Firefox doesn't have a WebXR implementation and I believe doesn't discriminate between Oculus Touch v1 and v2. Oculus Quest and Oculus Browser should work as expected.

**Comment by dmarcos** [comment]
I believe there's nothing to do here on the A-Frame side. The correct model should be displayed once Firefox ships WebXR.
