### ISSUE TITLE
Unexplained a-node.js error in 1.0.3, identical stack trace to #3920

### ISSUE THREAD

**Issue by tsgouros** [aframevr/aframe#4411]
I get a console error that does not reference any code of mine. I assume this is my problem, but I cannot tell from the error what is the matter. Is there a way to improve the reporting?

- A-Frame Version: 1.0.3
- Platform / Device: Gives errors below in Firefox, Chrome, and similar in Safari (out-of-date version though).
- Reproducible Code Snippet or URL: See https://sgouros.com/explosion/index1.html for 1.0.3 version, https://sgouros.com/explosion/index2.html for 0.9.2 version.

Chrome error:
```
core:a-node:error Failure loading node:   TypeError: Cannot read property 'constructor' of undefined
    at extendProperties (component.js:734)
    at i.callUpdateHandler (component.js:414)
    at i.updateProperties (component.js:298)
    at HTMLElement.updateComponent (a-entity.js:490)
    at HTMLElement.updateComponents (a-entity.js:456)
    at a-entity.js:249
    at a-node.js:127
```

Firefox error:

```
core:a-node:error Failure loading node:   TypeError: "e is undefined"
    Aframe 7
        extendProperties
        callUpdateHandler
        updateProperties
        value
        value
        value
        value
```

The stack trace appears the same as in (closed) issue #3920 from version 0.8.2.

I have posted the question on stackoverflow, too, but no answers yet, except someone who asked me to upgrade, which I did, but it didn't help: https://stackoverflow.com/questions/59792018/a-node-js-typeerror-cannot-read-property-constructor-of-undefined

**Comment by arpu** [comment]
only a guess but try setting the assets timeout higher  <a-assets timeout="69000">
 looks like aframe assets loading timeouts on your big glb model

**Comment by tsgouros** [comment]
Thank you, that appears to have done it. Now that you point it out, I see that the timeout warning and the error are related, but the error came and went. I wonder if it would be possible for the code that failed to issue a warning message?

**Comment by arpu** [comment]
this can be hapen if the glb is loaded from cache  aframe has this 3sec assets loading timeout as default

maybe @dmarcos  has more information on this why
