### ISSUE TITLE
Docs still talk about A-Frame Registry and Awesome Aframe, both of which are discontinued

### ISSUE THREAD

**Issue by omgitsraven** [aframevr/aframe#4419]
**Description:**

- A-Frame Version: master
- Platform / Device: documentation
- Reproducible Code Snippet or URL: https://aframe.io/docs/master/introduction/writing-a-component.html

At the bottom of the page, the "publishing a component" section says that "you should publish it to the ecosystem via the A-Frame Registry and awesome-aframe!"

However, https://github.com/aframevr/aframe-registry says that the A-Frame Registry is discontinued, and https://github.com/aframevr/awesome-aframe says that Awesome A-Frame is discontinued :)

The "components" link on what's left of the Awesome A-Frame readme implies that the modern approach is just to publish an NPM package with the `aframe` keyword, but I'm not sure if that's still accurate? Are there any more recent instructions about this that the official docs could be updated to include?

**Comment by dmarcos** [comment]
Thanks. A PR to remove references will be appreciated

**Comment by omgitsraven** [comment]
What should they be replaced with, though?

**Comment by dmarcos** [comment]
I would just remove the references to the registry for now

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/4423
