### ISSUE TITLE
Y axis in AR mode different on iOS vs Android

### ISSUE THREAD

**Issue by riebling** [aframevr/aframe#4420]
When in AR mode, iOS (iPad) Y coordinates of the camera increase as you move the device closer to the ground, and decrease as you raise it skyward
The same scene on Android+Chrome reports the direction of positive Y the other way around, as expected

- A-Frame Version: 1.0.3
- Platform / Device: 
  -  Android+Chrome Canary+AR-enabling settings
  -  iOS+Firefox-iOS (webxr branch https://github.com/mozilla-mobile/firefox-ios/tree/webxr)
- Reproducible Code Snippet or URL:
  http://xr.andrew.cmu.edu/x/refactor

**Comment by dmarcos** [comment]
That’s probably a question better answered
by engineers working on the Firefox webxr implementation that it seems is under development. A-Frame simply applies the pose reported by the API and doesn’t apply any transformation. Behavior should be consistent with Chrome
