### ISSUE TITLE
Invalid character in v1.0.3 aframe.js

### ISSUE THREAD

**Issue by kennardconsulting** [aframevr/aframe#4428]
**Description:**

- A-Frame Version: 1.0.3
- Platform / Device: Windows
- Reproducible Code Snippet or URL:

Looking in `aframe/dist/aframe.js` on line 31,833 I see:

````
||Â material.isMeshPhongMaterial ||
````

This is causing my browser to fail with 'invalid character'

**Comment by dmarcos** [comment]
How do you get to that state? Recommended ways to use A-Frame the [CDN](https://aframe.io/releases/1.0.3/aframe.js), npm, [master builds](https://cdn.jsdelivr.net/gh/aframevr/aframe@130f5846ac7cb99dff0e30d703c15c046c066529/dist/aframe-master.min.js) or for aframe dev itself `npm start`

**Comment by kennardconsulting** [comment]
I installed A-Frame via npm. The bad file is what npm installed in my `npm_modules` folder

**Comment by dmarcos** [comment]
I can't reproduce. I did `npm install aframe` in an empty directory and pointed the hello world to it. Everything loads as expected. It has to be something with your build toolchain / setup.

```<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello, WebVR! • A-Frame</title>
    <meta name="description" content="Hello, WebVR! • A-Frame">
    <script src="node_modules/aframe/dist/aframe.js"></script>
  </head>
  <body>
    <a-scene background="color: #FAFAFA">
      <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9" shadow></a-box>
      <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E" shadow></a-sphere>
      <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D" shadow></a-cylinder>
      <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4" shadow></a-plane>
    </a-scene>
  </body>
</html>```

**Comment by arpu** [comment]
hm maybe same problem as here https://github.com/mrdoob/three.js/pull/18260 ?

**Comment by kennardconsulting** [comment]
Yeah I think so. It's a non-breaking space which makes it hard to 'see', and some browsers/tools are probably forgiving. But it's definitely there.

If I look in the binary of aframe.js I can see it. And if I download the 1.0.3 source ZIP I can see it too.

![image](https://user-images.githubusercontent.com/987314/73233051-72536c80-41d9-11ea-8ef0-1f25d14b235a.png)

**Comment by dmarcos** [comment]
In what browser do you see the error? Firefox and Chrome for Windows work fine for me

**Comment by kennardconsulting** [comment]
Firefox on Windows. But bear in mind it's been through webpack. So it's probably a combination of webpack and FF. Can you see the offending character in the src file I described above?

**Comment by dmarcos** [comment]
That character comes from the THREE.js bundled with A-Frame as @arpu mentioned  https://github.com/mrdoob/three.js/pull/18260 We will release 1.0.4 in a few days. In the meantime you can remove the character from the build and point webpack to a local copy of A-Frame.

**Comment by kennardconsulting** [comment]
@dmarcos thanks for the quick response. Yes, I have a workaround for now. Just wanted to see it fixed up for others.

Note I am not 100% convinced this is the same problem (does not appear to be the same line).
