### ISSUE TITLE
iOS / Safari artifact when returning from landscape

### ISSUE THREAD

**Issue by tiagovignatti** [aframevr/aframe#4438]
When changing the orientation to landscape (with and without touching the VR button) and then going back to portrait, it's possible to see an artifact on the bottom of the screen. It seems that the native navbar is messing up a bit and causing this incorrect render.

![image0](https://user-images.githubusercontent.com/1163553/73945268-d4475c80-48d2-11ea-93fc-1da440cc625e.png)

I haven't had time to hack the code to understand it fully (sorry!) but the things might be related with:
https://github.com/aframevr/aframe/issues/4400
https://github.com/aframevr/aframe/issues/3525

- A-Frame Version: 0.8.2 - 1.0.4
- Platform / Device: iOS (13+) using Safari
- To reproduce: http://aframe.glitch.me/

Thanks for looking into this, and all the great work.

**Comment by dmarcos** [comment]
It looks like an unaddressed Safari bug. None of the solutions suggested in the thread below worked for me:

https://forums.macrumors.com/threads/is-this-a-mobile-safari-bug-white-space-appears-at-bottom-after-rotating-iphone.2209551/

**Comment by dmarcos** [comment]
This is an iOS 13 regression. Moving conversation to https://github.com/aframevr/aframe/issues/4617
