### ISSUE TITLE
Landscape magic-window buggy on latest Chrome (80.0.3987.87)

### ISSUE THREAD

**Issue by tiagovignatti** [aframevr/aframe#4440]
**Description:**

Landscape magic-window is buggy using device sensor wrong information latest Chrome (80.0.3987.87). It wasn't an issue when using the same version of A-Frame previous Chrome (79.x.x.x).

In the following example, I'm moving my device horizontally then I rotate it to landscape and keep moving horizontally. You will notice that the device sensor is not tracking the right axis.

![ezgif-6-3a90650d8810](https://user-images.githubusercontent.com/1163553/73974728-9f9fc900-4903-11ea-8d22-08825cf53bd7.gif)

- A-Frame Version: 1.0.x
- Platform / Device: Android / Chrome (80.0.3987.87)
- Reproducible Code Snippet or URL: https://aframe.glitch.me/

**Comment by dmarcos** [comment]
Use 1.0.4. It should work fine.

**Comment by tiagovignatti** [comment]
> Use 1.0.4. It should work fine.

Hmm I'm not sure 1.0.4 is fine. I'm still able to reproduce the same issue. Could you please double-check it there? Here's the URL: https://earthy-puffin-ulzemzmkx.glitch.me/

**Comment by dmarcos** [comment]
If it only affects m80 something must have changed on the Chrome side. It would be interesting to check the release notes.

**Comment by klausw** [comment]
I just tried https://earthy-puffin-ulzemzmkx.glitch.me/ on Chrome Canary 82.0.4051.2, and in that version it's not reacting to device motion, but if I pan the scene using finger drag, it seems to get confused when moving from portrait to landscape. Is this possibly a separate issue with coordinate systems that's not directly related to orientation sensors?

**Comment by nbutko** [comment]
FYI: https://bugs.chromium.org/p/chromium/issues/detail?id=1050205

**Comment by dmarcos** [comment]
Thanks everybody for the info. It looks like it's a Chrome bug. I don't think there's any action to be taken on A-Frame side. I keep the issue open for references until it's fixed.

**Comment by klausw** [comment]
If I'm interpreting https://bugs.chromium.org/p/chromium/issues/detail?id=1048294 right, this should be fixed in future Chrome releases >= 80.0.3987.95 . (Current Chrome Stable is 80.0.3987.87 for Android according to https://omahaproxy.appspot.com/)

**Comment by tiagovignatti** [comment]
I can confirm that this issue is not present anymore on my Chrome / Android version  80.0.3987.99. Thanks everybody for the help!

**Comment by dmarcos** [comment]
Thanks for reporting
