### ISSUE TITLE
support WebXR Navigation permission 

### ISSUE THREAD

**Issue by arpu** [aframevr/aframe#4445]
in new OculusBrowser there is navigation support for webxr

![com oculus vrshell-20200210-225452](https://user-images.githubusercontent.com/14173/74237866-c9c30380-4cd4-11ea-8f51-c5243c12a344.jpg)

related  https://github.com/immersive-web/navigation

**Comment by dmarcos** [comment]
wow! good catch! I would’ve never expected to see navigation implemented so quickly. Oculus browser folks are doing an amazing job shipping experimental features. hat off 🎩 to @Artyom17 and any other Oculus friends involved.

**Comment by Artyom17** [comment]
Yes, we have it experimentally implemented. Note, that the "Default" setting allows only certain well-known domains, so, most likely you need to switch to Enabled state to make it work for all domains.

**Comment by dmarcos** [comment]
@Artyom17 I was testing the `sessiongranted` event and It didn't work as I was expecting. I'm navigating to the same page url after entering VR mode (with navigation setting to `Allowed`)

```window.location = "https://nova-childlike-leaf.glitch.me/```

and I was expecting the event to fire:

```
 navigator.xr.addEventListener('sessiongranted', function (evt) {
    console.log('SESSION GRANTED');
 });
```
Full working example: https://nova-childlike-leaf.glitch.me/ 
and code: https://glitch.com/edit/#!/nova-childlike-leaf?path=index.html:10:9

Am I missing anything? Thanks

**Comment by Artyom17** [comment]
You need to call requestSession in the listener of sessiongranted. An example code: https://github.com/Artyom17/webxr-samples/blob/gh-pages/tests/navigation.html

Working sample: https://artyom17.github.io/webxr-samples/tests/navigation.html

**Comment by Artyom17** [comment]
Actually, found a bug in my code that didn't allow to enable the XR navigation for any site. The fix is in the queue, the workaround is to switch the browser to single process mode via 'adb shell setprop debug.oculus.browser.singleproc 1' followed by 'adb shell am force-stop com.oculus.browser' commands. Note, the prop is not persistent and will be reset after reboot.

**Comment by Artyom17** [comment]
BTW, it was fixed a long time ago.

**Comment by dmarcos** [comment]
Awesome thanks. I’ll try later

**Comment by arpu** [comment]
@dmarcos  is there anything needed to change in aframe?
