### ISSUE TITLE
iPhone 11 Black screen until you rotate device

### ISSUE THREAD

**Issue by rogerwalsh** [aframevr/aframe#4449]
**Description:**

- A-Frame Version: 1.0.4
- Platform / Device: iPhone 11 iOS 13.3.1
- Reproducible Code Snippet or URL: https://livevr.io/live-events/touts/SXSW-2018/Latitude-30

Initially a black screen on videosphere play - you have to rotate the device in order for the video to show.

**Comment by dmarcos** [comment]
It works fine for me on an iPhone X with iOS 13.3.1. The video play as expected after clicking the play button in both landscape and portrait orientations

**Comment by rogerwalsh** [comment]
> It works fine for me on an iPhone X with iOS 13.3.1. The video play as expected after clicking the play button in both landscape and portrait orientations

Thanks for checking!

I found a fix for now - based on this issue - https://github.com/aframevr/aframe/issues/4134

It's still an issue but Ion can play I added

var $scene = document.querySelector('a-scene');
$scene.renderer.setSize($scene.canvas.width, $scene.canvas.height);

Thanks again

**Comment by dmarcos** [comment]
Duplicated. It's an iOS 13 regression. Closing in favor of https://github.com/aframevr/aframe/issues/4617
