### ISSUE TITLE
Gyroscope axis inverted on Honor 20 lite in landscape

### ISSUE THREAD

**Issue by giovannigiordano** [aframevr/aframe#4450]
On mobile, starting in portrait, when I rotate to landscape the gyroscope axis are inverted.
I am experiencing this issue even on the official example at https://aframe.io/examples/showcase/helloworld/

- A-Frame Version: 1.0.3
- Platform / Device: Android 9 - honor 20 lite con adroid 9
- Reproducible Code Snippet or URL: https://www.brumbrum.it/auto/usata/volkswagen/passat/BA070677

**Comment by dmarcos** [comment]
Chrome version?

**Comment by LuisHansen** [comment]
That's happening with me too. I'm using a Samsung S9+.
Chrome 80.0.3987.87, Android 10.

**Comment by dmarcos** [comment]
I think it’s a dup. There’s a known bug in Chrome m80. More info in https://github.com/aframevr/aframe/issues/4440
