### ISSUE TITLE
Cordova mobile app integration

### ISSUE THREAD

**Issue by benallfree** [aframevr/aframe#4451]
This is a planning ticket to discuss changes that are necessary or desirable in order to integrate aframe into a Cordova mobile app. There is a parent ticket for AR.js https://github.com/jeromeetienne/AR.js/issues/726 and a sample repo demonstrating various issues and successes https://github.com/benallfree/arjs-mobile-app-samples.

There is also a WIP PR #4452

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/4452
