### ISSUE TITLE
deep-assign deprecated - replace with lodash's _.merge?

### ISSUE THREAD

**Issue by benallfree** [aframevr/aframe#4453]
https://www.npmjs.com/package/deep-assign has been deprecated and recommends using `_.merge` from lodash.

Thoughts? Happy to do a PR for this.

**Comment by dmarcos** [comment]
If `deep-assign` does its job I would keep it. The package won’t be taken down from npm. it won’t receive any updates.

**Comment by benallfree** [comment]
It does not correctly merge object keys with ‘null’ values. I had to import lodash for that.
