### ISSUE TITLE
Inconsistent behaviour for missing mixin

### ISSUE THREAD

**Issue by abek42** [aframevr/aframe#4455]
**Description:**
When a missing mixin is encountered for a-sphere, WebApp crashes. However, for a-entity with line, the missing mixin doesn't trigger crash.

Either one of the behaviour could be valid, but needs to be consistent.

- A-Frame Version: 1.0.4
- Platform / Device: Win10/Firefox
- Reproducible Code Snippet or URL:
	```
	<a-entity id="axes">
			<a-entity id="origin_line" line="start: 0, 0, 0; end: 20000 0    0; color: red;   opacity:1" mixin="missing_mixin_no_error"><a-entity>
			<!--a-sphere mixin="missing_mixin_throws_error"-->	</a-sphere><!--uncomment to trigger crash-->
		</a-entity>
```

**Comment by dmarcos** [comment]
Share link to complete example to reproduce.

**Comment by abek42** [comment]
https://glitch.com/~judicious-morocco-9avsv2b5p

-- working.html has no error for missing mixin for line component
-- broken.html breaks due to missing mixin for a-sphere component
