### ISSUE TITLE
Fix problems with Magic Leap Controller

### ISSUE THREAD

**Issue by ericdacal** [aframevr/aframe#4458]
**Description:**

- A-Frame Version: 1.0.4
- Platform / Device: Magic Leap
- Reproducible Code Snippet or URL:
I have test Magic Leap Controller with Magic Leap 1, and when I used I find the following bug:
![error](https://user-images.githubusercontent.com/16444893/74533079-09862700-4f31-11ea-9aec-ee55ba7c65cb.png)
My code is very simple, I think that is sometime with the controller:
![code](https://user-images.githubusercontent.com/16444893/74536807-1a3a9b00-4f39-11ea-8399-2bf924545d9b.png)

Thanks

**Comment by dmarcos** [comment]
@atarng-magicleap I don’t have a device to test on. Do you have any ideas what it might be going on?

**Comment by ericdacal** [comment]
It seems that WebXR don't detect Magic Leap device correctly. I think is something like this. In this link explain how to access magic leap controls from WebXR.

[https://developer.magicleap.com/learn/guides/webvr-webxr]()

**Comment by atarng-magicleap** [comment]
Hi, correct. Magic Leap is currently still using a version of chromium that does not support input profiles. This should be supported in the next software update.

As far as that error it looks like the profiles field needs to be checked against, before checking against the length. (this may have been something that my previous patch neglected to do)

**Comment by atarng-magicleap** [comment]
As a workaround, inside the file tracked-controls.js, changing:
`if (profiles.length === 0) { return; }`
to
`if (!profiles || profiles.length === 0) { return; }`
should remove the error.
However full input profile support will be ready with the next software release which should be sometime in the next few weeks.

**Comment by dmarcos** [comment]
Thanks everybody. I would probably wait until the Magic Leap soft fix

**Comment by ericdacal** [comment]
Hi, there is a new software version for Magic Leap 1 and seems that now support profiles.  
https://developer.magicleap.com/en-us/learn/guides/webxr-overview
I probe with the new version and now there is not error but the controllers don't show the model and seems that don't work.  My code is simple:

![image](https://user-images.githubusercontent.com/16444893/80472948-bf182200-8945-11ea-98fc-23ef621f0413.png)



Thanks

**Comment by dmarcos** [comment]
Any errors on console?

**Comment by ericdacal** [comment]
There isn't any error in console. But finally I solved the error removing an if in utils/tracked-controllers. 
![problem](https://user-images.githubusercontent.com/16444893/81983532-d8062000-9633-11ea-9c33-f65a8b2ec39e.png)
Now the controller works perfectly.

**Comment by dmarcos** [comment]
That doesn't look correct. Are you defining two entities in your scene like this?
```
<a-entity magicleap-controls="hand: right"></a-entity>
<a-entity magicleap-controls="hand: left"></a-entity>
```
Controller handedness seems to be defined on Magic Leap but you probably don't have an entity that matches it.

**Comment by ericdacal** [comment]
I only have one, but when I print the value of controller.handedness and handednes, one was magicleap controller and the other right. I think that the values aren't related.

**Comment by dmarcos** [comment]
Does it work if you add two entities as above and remove the change in `utils/tracked-controllers`?

**Comment by dmarcos** [comment]
> I print the value of controller.handedness and handednes, one was magicleap controller and the other right

What are the exact values you see? Only `none`, `right` and left are valid as per [spec](https://immersive-web.github.io/webxr/#dom-xrhandedness-left). It's a browser bug otherwise

**Comment by ericdacal** [comment]
> Does it work if you add two entities as above and remove the change in `utils/tracked-controllers`?

I probe it and don't work.

**Comment by ericdacal** [comment]
> > I print the value of controller.handedness and handednes, one was magicleap controller and the other right
> 
> What are the exact values you see? Only `none`, `right` and `left` are valid as per [spec](https://immersive-web.github.io/webxr/#dom-xrhandedness-left). It's a browser bug if different

I see right. Magic Leap 1 use always Helios Browser.
