### ISSUE TITLE
Axismove event issue

### ISSUE THREAD

**Issue by EspaguetiMagic** [aframevr/aframe#4460]
Event listener "axismove" is triggered, but returns 0 on version 1.0.1 and upwards on Oculus Quest controls.

- A-Frame Version: 1.0.1 +
- Platform / Device: Oculus Quest

**Comment by dmarcos** [comment]
Link to reproduce?

**Comment by EspaguetiMagic** [comment]
Here's the demo on glitch: https://axismove-issue-demo.glitch.me/. For it to work, just change A-Frame release to 1.0.0 or lower.

**Comment by EspaguetiMagic** [comment]
Nvm, I've found that the values I was looking for were just in evt.detail.axis[2] and evt.detail.axis[3], instead of evt.detail.axis[0] and evt.detail.axis[1], where they were before.
