### ISSUE TITLE
Camera movement-controls doesn't work on Oculus Go since 1.0.1

### ISSUE THREAD

**Issue by evdem** [aframevr/aframe#4491]
**Description:**
Camera movement-controls (by touchpad) don't work on Oculus Go since 1.0.1 but all works e.g. in my VR BOX 2 + Chrome + joystick.

- A-Frame Version: > 1.0.0
- Platform / Device: Oculus Go
- Reproducible Code Snippet or URL:
<script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.1.0/dist/aframe-extras.min.js"></script>
  </head>
<body>
  <a-scene>
    <a-entity id="rig"
              movement-controls="speed:0.1">
      <a-entity camera
                position="0 1.6 0"
                look-controls="pointerLockEnabled: true">
      </a-entity>
    </a-entity>
    <a-box position="0 1.5 -1" color="#777777" rotation="45 0 0"></a-box>
  </a-scene>

**Comment by evdem** [comment]
sorry:
  <a-scene>
    <a-entity id="rig"
              movement-controls="speed:0.1">
      <a-entity camera
                position="0 1.6 0"
                look-controls="pointerLockEnabled: true">
      </a-entity>
    </a-entity>
    <a-box position="0 1.5 -1" color="#777777" rotation="45 0 0"></a-box>
  </a-scene>

**Comment by evdem** [comment]
Sorry [test_new.txt](https://github.com/aframevr/aframe/files/4238961/test_new.txt)

**Comment by dmarcos** [comment]
I recommend opening an issue on the [aframe-extras repo](https://github.com/donmccurdy/aframe-extras) cc @donmccurdy

**Comment by evdem** [comment]
https://github.com/donmccurdy/aframe-extras/issues/314
