### ISSUE TITLE
click events not working with latest version of aframe[1.0.3]

### ISSUE THREAD

**Issue by Likhita-711** [aframevr/aframe#4498]
Iam currently working with  A-Frame and ar.js , interactions part of 3d-models .My requirement is on every click of the object or primitive it has to increase its size.But the click events are not working with the current version of A-frame

- A-Frame Version: 1.0.3
- Platform / Device:
- URL: https://glitch.com/edit/#!/able-empress-iuumq1gj8n

**Comment by dmarcos** [comment]
FYI, latest version is also 1.0.4. We can reopen this if there's a way to reproduce without ar.js
