### ISSUE TITLE
Clicking and dragging in Firefox on Windows locks view to -y direction

### ISSUE THREAD

**Issue by AdaRoseCannon** [aframevr/aframe#4499]
To reproduce open the scene in Firefox on Windows, click and drag on the AFrame scene, view gets locked to -y and rotates around that point.

Expected behaviour: look around with click and drag.

- A-Frame Version: Tested on all demos on the homepage
- Platform / Device: Windows, Firefox
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

**Comment by dmarcos** [comment]
I can't reproduce the described problem on any of the [examples](https://aframe.io/aframe/examples/). Do you have any installed extension that might be interfering with the input?

**Comment by AdaRoseCannon** [comment]
Yeah it's only Firefox, it doesn't seem to be an extension, since it still breaks even in a private window, where all extensions are disabled.

I just inspected the camera rotation and it has valid values, no NaNs, they are just -PI/2 in the x axis, and it spin wildly in the y axis, making me think that some how the input is magnified but I can't place it.

**Comment by dmarcos** [comment]
Mmmh I cannot get to spinning wildly as
described. Do you have more concrete steps to reproduce? What version of Firefox are you using?

**Comment by AdaRoseCannon** [comment]
It's Firefox 73.0.1 (64-bit), 

It really is hard to put more steps in, for me any scene, at any point if I click and drag (in any direction) it will immediately lock onto looking at the floor, any further dragging rotating rapidly around the y axis.

**Comment by AdaRoseCannon** [comment]
Perhaps leave the issue open for now in case anyone else can reproduce, I wish I could work out the distinguishing factor.

**Comment by dmarcos** [comment]
For the record. Screen capture clicking / dragging on the [Hello World Example](https://aframe.io/aframe/examples/boilerplate/hello-world/) on Firefox 73.0.1 (64-bit) and Windows.

https://share.getcloudapp.com/Qwu7K8d6

It works as expected for me.

**Comment by AdaRoseCannon** [comment]
Glad it's working for you, hopefully I am the only one it's weird for. It's definitely synced between both my computers.

**Comment by dmarcos** [comment]
Is this still an issue?

**Comment by AdaRoseCannon** [comment]
Just checked it on the demos on the main website, it is still an issue.

**Comment by dmarcos** [comment]
Any steps to reproduce? Can anyone else reproduce? Everything works as expected on my machine (Windows / Firefox 76) and [A-Frame examples](https://aframe.io/aframe/examples/)

@AdaRoseCannon Do you have the WebXR / WebVR emulator installed / enabled? Do you have a second computer to test and discard anything particular to your setup? Thanks for investigating.

**Comment by AdaRoseCannon** [comment]
Solved it!!

In look-controls, between events you save the event object to measure the difference between screenX and screenY between movements.

For some reason in my particular browser configuration (firefox on all my windows computers), screenX and screenY both get set to 0 when read on the next frame. I'm not sure if this is a bug or part of some anti tracking measure.

I fixed this by writing screenX and screenY out to an object instead.

```
init () {
     ...
     this.previousMouseEvent = {};
}

mousedown() {
    ...
    this.previousMouseEvent.screenX = evt.screenX;
    this.previousMouseEvent.screenY = evt.screenY;
}


mousemove() {
    ...
    this.previousMouseEvent.screenX = event.screenX;
    this.previousMouseEvent.screenY = event.screenY;
}
```

**Comment by AdaRoseCannon** [comment]
If you want I will make a pull request tomorrow.

**Comment by dmarcos** [comment]
Thanks for investigating. Much appreciated. A PR will be more than welcome. Trying still to fully understand the issue. Do you have any custom flags on your Firefox instances?

**Comment by AdaRoseCannon** [comment]
As far as I can tell it's not a custom setting since it happens with all the extensions turned off and I haven't set any custom flags in about:config.

**Comment by AdaRoseCannon** [comment]
Since it's fixed, i'm goign to close this.
