### ISSUE TITLE
Add skybox primitive

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#45]
Enables devs to add skies to their scenes.

Dev can specify:
- URL of textures
- Radius (default should be very large (eg 5000) but less than default camera far clipping plane distance)
- Segments (number of times skybox box geometry is divided. Am not sure we need this).
- Color
- Effected by fog (boolean, default false)

URL of textures works as follows:

`<a-skybox url="images/city/city">`

The template then looks inside the directory specified for six images with the `city` filename and ending with `top`, `bottom`, `left`, `right`, `front`, `back`, respectively. Am not married to this implementation, but it worked well in the original pre-refactor skybox component.

By default the color is transparent, so that a PNG with transparency will appear comped against the background. When then user specifies a color value, the image instead appears comped against this color. The color is also visible while the image is being loaded, or if an image is not specified.

**Comment by cvan** [comment]
after @ngokevin's PR #883 is merged, we can do this with ease

**Comment by ngokevin** [comment]
Depends on cubemap support for material maps
