### ISSUE TITLE
A-Frame AR change webcam viewport size (when i tried to change heigth and width, goes back)

### ISSUE THREAD

**Issue by Invius** [aframevr/aframe#4502]
I used jquery to try and size the video component that it generated from the a-scene, and it changes the value from the <video> component, but i think that ar.js is triggering on resize event to ajust back to the window size.
I've tried to change the arjs attribute but nothing happens.
Is there a way to set a fixed size, instead of having it full screen/window sized? Or is this a bug from the framework?
- A-Frame Version: 0.7.1
- Platform / Device: Windows 10
- Reproducible Code Snippet or URL:
```
let videoComponent = $("video");
videoComponent.height(300);
videoComponent.width(300);
```
`<a-scene embedded arjs='sourceType: webcam; sourceWidth: 600; sourceHeight: 400; displayWidth: 600; displayHeight: 400; canvasWidth: 600; canvasHeight: 400; debugUIEnabled: false;' >
`

**Comment by dmarcos** [comment]
FYI, you are on an old version. Use 1.0.4. This is a question more appropriate for the [arjs maintainers](https://github.com/jeromeetienne/AR.js/)

**Comment by Invius** [comment]
This also happens in the version 1.0.4
I have reported to them too:
[ar.js git](https://github.com/jeromeetienne/AR.js/issues/750)

**Comment by dmarcos** [comment]
Thanks
