### ISSUE TITLE
hand-controls orientation incorrect in Rift S (Firefox)

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe#4505]
**Description:**

The hand orientation for `hand-controls` as of A-Frame `1.0.4` is incorrect in Rift S (and possibly elsewhere).

If the controller is held upright, with the ring opening to the ceiling, the model's fingers also point upward, which makes interaction much more awkward and uncomfortable. Fingers should be more perpendicular to the controller as they are in real life.

- A-Frame Version: `1.0.4`
- Platform / Device: Firefox Developer Edition / Firefox | Windows 10
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
What about chrome / WebXR?

**Comment by dsinni** [comment]
@dmarcos I just tried enabling `Oculus hardware support` in Chrome, and I still can't enter VR for whatever reason. This has been plaguing me for a while. If I get it working, I'll report back with the results.

**Comment by dmarcos** [comment]
To make Oculus headsets work on Chrome you have enable `OpenVR hardware support` and disable `XR device sandboxing`

**Comment by dsinni** [comment]
Thanks, @dmarcos! That did it. Not sure how I missed those settings.

I just tested and the hand orientation is correct in Chrome and incorrect in Firefox.

**Comment by dmarcos** [comment]
FWIW, orientation of controllers on Firefox + Rift is as expected. It might be a Firefox difference in the reported orientation of Rift S and Rift. I hope the discrepancy is corrected when Firefox ships WebXR

**Comment by dmarcos** [comment]
Rift and Rift S pose orientations appear to be consistent on Chrome / WebXR

**Comment by dmarcos** [comment]
I think there's nothing actionable here. We can reopen if necessary.
