### ISSUE TITLE
Add ability to pass single value to scale components

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#451]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Monday Sep 07, 2015 at 20:31 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/94_

---

Enables the dev to specify the scale value of an element without having to list the X, Y, and Z values separately. Most of the time that scale is invoked, it is proportional, and having to list all three values separately clutters the code unnecessarily.

Compare this:

``` javascript
<vr-model src="tree.dae" position="1 0 -4" scale="1.4 1.4 1.4"></vr-model>
```

With this:

``` javascript
<vr-model src="tree.dae" position="1 0 -4" scale="1.4"></vr-model>
```

Logic would be: if only one value is passed, apply it to all three values. If three values are passed, apply them to the X, Y, and Z axes as usual.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Monday Sep 07, 2015 at 21:25 GMT_

----

This can lead to confusion. Is one value changing just the x?

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Monday Sep 07, 2015 at 21:26 GMT_

----

We should allow one value also for position and rotation? What does it mean in that context? Just the x?

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Monday Sep 07, 2015 at 21:28 GMT_

----

Verbosity adds a bit of typing overhead but we avoid ambiguity.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Monday Sep 07, 2015 at 21:32 GMT_

----

Position and rotation behaviors would stay as they currently are. I think confusion would be minimal. Declaring a single value for a scale operation is common across content creation apps. The same is not true of position or rotation, so this shortcut would not be appropriate there.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Monday Sep 07, 2015 at 21:46 GMT_

----

Verbosity also adds a foot gun for screwups. It's _very_ easy to miss a value. This is from a scene I'm currently working on, for example:
```javascript
<vr-model src="models/sculpture/sculpture.dae" rotation="0 45 0" scale="0.005 0.005 0.005"></vr-model>
```
Repeating 0.005 unnecessarily makes the markup hard to read, and increases odds of a mistake.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Monday Sep 07, 2015 at 22:12 GMT_

----

Another example I'm currently working on:
```html
    <vr-model src="models/tree1/tree1.dae" position="3 0 0" scale="0.01 0.01 0.01"></vr-model>
    <vr-model src="models/tree2/tree2.dae" position="1 0 -4" rotation="0 30 0" scale="0.01 0.01 0.01"></vr-model>
    <vr-model src="models/tree1/tree1.dae" position="-1 0 -18" rotation="0 20 0" scale="0.01 0.01 0.01"></vr-model>
    <vr-model src="models/tree2/tree2.dae" position="-2.5 0 -7" rotation="0 300 0" scale="0.009 0.009 0.009"></vr-model>
    <vr-model src="models/tree2/tree2.dae" position="-3 0 1" rotation="0 15 0" scale="0.0095 0.0095 0.0095"></vr-model>
    <vr-model src="models/tree1/tree1.dae" position="-10 0 -1" scale="0.009 0.009 0.009"></vr-model>
```

**Comment by dmarcos** [comment]
I don't think the complexity added and chances of  misinterpretation (why I can pass one value to this component but not the others) to the feature justifies its value. Passing 3 values is a bit more verbose but clear and consistent with the rest of components. I'm happy to close this. @ngokevin what do you think?
