### ISSUE TITLE
Camera showing black screen when entering VR Mode

### ISSUE THREAD

**Issue by markcarandang** [aframevr/aframe#4510]
**Description:**

- A-Frame Version: 1.0.0
- Platform / Device: Google Pixel 3A / Laptop
- Reproducible Code Snippet or URL: https://lei-cdp.github.io/LEI-AR/SAVS/
- Marker: https://lei-cdp.github.io/LEI-AR/Markers/Heart-Marker.png

Hi all,

My camera is not able to show images on my device's screen when I enter VR mode. However, it's still able to identify the marker and show me the corresponding object. You may find screenshots of the issue attached to this post. Looking forward to your responses. Cheers!

Kind regards,
Mark

![Screenshot_20200304-153444](https://user-images.githubusercontent.com/45596155/75847080-25913000-5e2e-11ea-9e80-36f7386156d0.png)
![Screenshot_20200304-153427](https://user-images.githubusercontent.com/45596155/75847085-275af380-5e2e-11ea-803c-137aa95b99d2.png)

!

**Comment by dmarcos** [comment]
FYI, you are in an old version. Use 1.0.4

**Comment by dmarcos** [comment]
Can you reproduce without ar.js? It might be an integration issue and a more appropriate question for their maintainers.

**Comment by dmarcos** [comment]
FWIW, I don't think ar.js is meant to be used in VR mode but in hand held / magic window configuration. You can disable the button via [vr-mode-ui component](https://aframe.io/docs/1.0.0/components/vr-mode-ui.html#sidebar)

**Comment by markcarandang** [comment]
Hi @dmarcos , thanks for the reply! I tested it on an iPhone 8 and the VR worked well. I guess the Pixel 3a XL isn't able to handle the VR mode, probaby because it does not support daydream vr? Will investigate further with other devices and post my findings here. Cheers!
