### ISSUE TITLE
Stream 3d Canvas/a-canvas, to share between 2 users

### ISSUE THREAD

**Issue by Invius** [aframevr/aframe#4512]
So far i was able to capture the video component and share it with the other user with the first code below. 
But if i try to the same method with the canvas for the 3d stuff it simply return a trasparent image (PNG) or a black background(jpeg), you can see in the second code block. 
I also tried to capture like a screen shoot, but it destroy the experience on the user that sends the data, as you can see in ther third code block. 
Is there a way to do this?

Also asked in:
https://stackoverflow.com/questions/60544827/a-frame-ar-stream-3d-canvas-a-canvas-to-share-between-2-users

Also reported in:
https://github.com/AR-js-org/AR.js/issues/39

- A-Frame Version:1.0.4
- Platform / Device:Windows
- Reproducible Code Snippet or URL:

```
let videoComponent = $("video");
let restreamCanvas = $("#newCanvas")[0];
let context = restreamCanvas.getContext('2d');
context.drawImage(videoComponent[0],0,0, restreamCanvas.width, restreamCanvas.height);
let videoURL = restreamCanvas.toDataURL('image/jpeg', 0.5);
let socket = new WebSocket(url);//url defined in var, it will send text
socket.send(videoURL);
```

```
let canvasComponent = $(".a-canvas");
let URLGraphic = canvasComponent .toDataURL('image/png', 0.5);
```
```
//html
<a-scene embedded screenshot="width: 640; height: 320">
//javascript
let prespectiveCanvas = document.querySelector('a-scene').components.screenshot.getCanvas("perspective");
 let URLGraphic = prespectiveCanvas.toDataURL('image/png', 0.5);
```

**Comment by dmarcos** [comment]
Thanks for filing a question on SO. I’m closing this. We use issues for bugs and feature requests
