### ISSUE TITLE
in-VR navigation is not working in Oculus Browser with link component

### ISSUE THREAD

**Issue by Sujoy-Ghosh** [aframevr/aframe#4514]
**Description:**
in-VR navigation (traversal between different VR web pages in VR mode) is not working in Oculus Browser with a link component; it exits VR mode. 
It's working in Firefox Reality.
- A-Frame Version: 1.0.4
- Platform / Device: Oculus Browser in Oculus Quest
- Reproducible Code Snippet or URL: https://aframe.io/aframe/examples/showcase/link-traversal/

**Comment by arpu** [comment]
default a-frame use webxr default on OculusBrowser and navigation is not enabled on webxr 
there is work ongoing for this see https://github.com/aframevr/aframe/issues/4445

**Comment by Sujoy-Ghosh** [comment]
> default a-frame use webxr on OculusBrowser and navigation is not enabled on webxr
> there is work ongoing for this see #4445

Is there any option to switch to webvr mode on Oculus Browser? Would navigation work?

**Comment by dmarcos** [comment]
Only way to switch to WebVR mode is serving your page over http and that will only work on Oculus Browser. Unfortunately in-vr navigation is gone in WebXR. There’s discussions to reintroduce and you can experiment with it today as mentioned above. Don’t account for in-vr navigation for now in production experiences.
