### ISSUE TITLE
Audio not recorded or casted on Oculus Quest

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe#4515]
**Description:**
Audio is not emitted in Chromecast or video recording using Oculus Browser

Severity: low, experience is still useable as expected on the device

Steps to reproduce - Chromecast:
* Launch and turn on the Oculus Quest headset
* Sharing > Cast > (Choose a Chromecast destination)
* Navigate > Oculus Browser
* Enter URL https://webxraudiotest.glitch.me in the Oculus Browser
* Use the controller to press the "VR" button in the lower right-hand corner
* Listen to audio - correctly plays on Quest device, does not play on Chromecast device (only audio from Oculus OS UI buttons is audible in Chromecast)

Steps to reproduce - Recording:
* Launch and turn on the Oculus Quest headset
* Sharing > Record Video
* Navigate > Oculus Browser
* Enter URL https://webxraudiotest.glitch.me in the Oculus Browser
* Use the controller to press the "VR" button in the lower right-hand corner
* Listen to audio - correctly plays on Quest device
* Connect device to Mac or PC and copy captured mp4 file to machine ([instructions](https://support.oculus.com/2255729571307786/))
* Although you can hear OS button noises in the mp4 file, you cannot hear browser audio

- A-Frame Version: 1.4
- Platform / Device: Oculus Quest / Oculus Browser
- Reproducible Code Snippet or URL: https://webxraudiotest.glitch.me

**Comment by kfarr** [comment]
Also note previous behavior (approx 2 weeks ago) the same action as described above resulted in loud static (hard white noise) on recording or Chromecast. Browser appears to have been updated to instead silence browser audio, which is a better outcome.

cc @Artyom17

**Comment by Artyom17** [comment]
Yes, we are working on a proper fix, the "complete silence" thing is a temporary measure.

**Comment by dmarcos** [comment]
@Artyom17 Thanks. We will keep this open as a reference

**Comment by ryankoble** [comment]
I'm experiencing the same as above, although I'm still getting the hard static sound. My Oculus Browser is updated.

I'm also getting some audio distortion when using the Oculus Quest and Oculus Browser. It may be an issue with my particular audio files, but I'm not sure.

Thanks for taking note of this!

**Comment by ryankoble** [comment]
@Artyom17 @dmarcos 

I'm experiencing the same as above, although I'm still getting the hard static sound. My Oculus Browser is updated.

I'm also getting some audio distortion when using the Oculus Quest and Oculus Browser. It may be an issue with my particular audio files, but I'm not sure.

Thanks for taking note of this!

**Comment by Artyom17** [comment]
@ryankoble  It is not the Browser's issue; it is the system component's that does recording problem. Have you updated your OS recently?

**Comment by ryankoble** [comment]
@Artyom17 I updated my OS, and it is silencing the audio now. Thanks for the help!

**Comment by dmarcos** [comment]
@Artyom17 We got a report of this issue still reproducing. Is the bug supposed to be fixed on the latest OS release? I'll follow up with the user. Thanks for your help.

**Comment by kfarr** [comment]
Casting: This appears to work as expected now. Audio from the browser is mirrored on the chromecast device. 

Recording: The app appears to prevent recording via Oculus UI by design. A workaround is to use a third-party chromecast receiving app and to record the output.

Quest OS version 904120.13150.0
