### ISSUE TITLE
Image source is not loaded

### ISSUE THREAD

**Issue by azmeruq** [aframevr/aframe#4525]
Image is not loaded, there is no load as texture or background

- A-Frame Version: 1.0.4
- Platform / Device: web
I can't do the next code
https://github.com/aframevr/aframe/blob/v0.9.0/examples/boilerplate/panorama/index.html
or even the intro example.

**Comment by dmarcos** [comment]
Not sure what the problem is. You will have to share code. Make sure:

You’ve read https://aframe.io/docs/1.0.0/introduction/faq.html#why-does-my-asset-e-g-image-video-model-not-load

You’re using A-Frame 1.0.4 and use the examples as a starting point https://aframe.io/aframe/examples/
