### ISSUE TITLE
Aframe manual load glb model not use src attribute 

### ISSUE THREAD

**Issue by dtboy1995** [aframevr/aframe#4530]
**Description:**

- A-Frame Version: 1.0.0
- Platform / Device: Chrome

**Feature**

- common

```html
 <a-gltf-model src="models/chh.glb" ></a-gltf-model>
````

- feature?
```js
var loader = new THREE.FileLoader()
loader.load(
	'models/chh.glb',
	function ( data ) {
		// What should I do when I get the data 
	}
)
```
thank you very much for any help

**Comment by dmarcos** [comment]
I don't understand the problem / issue / feature request. Care to elaborate?

**Comment by dtboy1995** [comment]
> I don't understand the problem / issue / feature request. Care to elaborate?

@dmarcos  thanks for your reply. 

my requirement is that the GLB model file will be encrypted. So if you use the SRC attribute to load directly, it will fail. I want to manually load and decrypt the model file and assign it to the < a-gltf-model > element. Is there a solution? Thank you very much.

**Comment by dmarcos** [comment]
Yes you will have to implement your own gltf loader component. If I understood correctly you are seeking code advice. We use github issues for feature requests and bug reports. I recommend opening a question on [StackOverflow](https://stackoverflow.com/questions/tagged/aframe). Nice folks there to help. Mind to provide a full runnable example that illustrates your problem and solution attempt. It will help people understand you problem. Thanks for understanding.
