### ISSUE TITLE
componentchanged listener broken starting 0.9

### ISSUE THREAD

**Issue by michaelglu** [aframevr/aframe#4531]
**Description:**
componentchanged event listener never fires in versions after 0.8

- A-Frame Version: 0.9, 0.9.2 1.0-all
- Platform / Device:  Chrome browser on pc
- Reproducible Code Snippet or URL:
### AFRAME.HTML
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
     <script src="/socket.io/socket.io.js"></script>
     <script src="/js/aframe.js"> </script>
  </head>
  <body>
    <a-scene listener stats id="scene" background="color: #DDEBED">
        <a-plane position="0 0 0" rotation="-90 0 0" width="40" height="40" color="#DB1222" shadow></a-plane>
         <a-box position="0 0.5 -5" rotation="0 0 0" color="#55F25E" shadow></a-box>
         <a-box position="-0.5 0.5 -6" rotation="0 0 0" color="#CEF0D0" shadow></a-box>
         <a-box position="0.5 0.5 -6" rotation="0 0 0" color="#4CC3D9" shadow></a-box>

  <a-entity  look-controls wasd-controls id="user-cam" position="0 0 0">
  <!-- <a-entity oculus-go-controls id="controller" ></a-entity> -->
  <a-entity camera  id="user-cam-internal" position="0 1.5 0">
  <a-cylinder position="-0.5 -0.5 -0.5" rotation="90 0 0" radius="0.05" height="0.5" color="#FFC65D" shadow></a-cylinder>
  <a-cylinder position="0.5 -0.5 -0.5" rotation="90 0 0" radius="0.05" height="0.5" color="#FFC65D" shadow></a-cylinder>
  </a-entity>

  </a-entity>




    </a-scene>
  </body>
</html>
```
```javascript
AFRAME.registerComponent('listener',{
  init:function(){
    player=document.getElementById('user-cam');
    console.log(player==null);
    player.addEventListener('componentchanged',function(evt){
      console.log(evt);//nothing gets logged
    })
  }
})

<!-- If you have a support question, please ask at https://stackoverflow.com/questions/ask/?tags=aframe rather than filing an issue. -->

**Comment by dmarcos** [comment]
Without code to run is hard to investigate. FWIW, it works for me: https://glitch.com/edit/#!/trite-aerial-flyingfish?path=log.js:9:4 Notice that you also importing A-Frame twice in your HTML

**Comment by dmarcos** [comment]
Closing this. We can reopen if it’s still an issue

**Comment by michaelglu** [comment]
This only works if the component itself is responsible for changing the entity. When I comment out the tick function and add wasd-controls to the box entity nothing gets logged anymore? Maybe I'm missing something here, but shouldn't this.el give the entity (so in your example a-box). So then wouldn't this.el.addEventListener('componentchanged') fire whenever any of the components are changed?

This is a remix of your glitch with tick taken out and wasd-controls added
https://glitch.com/~irradiated-grey-soybean

**Comment by dmarcos** [comment]
wasd-controls is an exception. For components that are going to modify position, rotation, scale every frame we recommend bypassing `setAttribute` and modify `el.object3D` directly. More details on [performance guide](https://aframe.io/docs/1.0.0/introduction/best-practices.html#performance). Side effect is that `componentchanged` won't fire. In this case, we recommend monitoring the values in the tick method of your component.

```
 AFRAME.registerComponent('bar', {
       init: function () {
          this.monitorEl = document.querySelector('#yourel');
          this.oldPosition = new THREE.Vector3();
       }, 
       tick: function () {
           this.monitorEl.object3D.position;
           // you can keep track of the old value if you want to check for changes.
           this.oldPosition.copy(this.monitorEl.object3D.position);
       }
  });
```
