### ISSUE TITLE
Cannot use navigator.getVRDisplays if served over HTTPS

### ISSUE THREAD

**Issue by Kif11** [aframevr/aframe#4532]
This issues is related to #4336 

Getting the following error when serving an A-frame project over HTTPS which leads to no controller loading in my scene.

`Cannot use navigator.getVRDisplays if WebXR is already in use.`

- A-Frame Version: 1.0.4
- Platform: Oculus Quest Browser (Chromium  79.0.3945.126)

*Update March 30, 2020*

Sorry for initial rudimentary info.

Looks like the issue is only happening with WebXR Device API enabled.

## How to reproduce 

- On Oculus Quest go to https://codercat.tk/test/.
- Click enter VR (No controllers will be shown) end `Cannot use navigator.getVRDisplays if WebXR is already in use.` error will show if you connected over ADB to Chromium console.
- Now go to chrome://frlags
- Disable WebXR Device API and relaunch the Browser
- Now enter VR again (no error and controllers are working)

Disabling Web VR completely and keeping WebXR Device API enabled lead to the same result.
Code for the test project located [here](https://github.com/Kif11/monster-or-friend/tree/aframe-1.0.4)

**Comment by arpu** [comment]
what browser?   and a glitch example would be nice!

**Comment by dmarcos** [comment]
Link to reproduce? Browser used?

**Comment by dmarcos** [comment]
@Kif11 Your application is pretty complex. Is there a way you can provide a smaller example to reproduce based on https://glitch.com/~aframe?

All the A-Frame examples work fine on Quest https://aframe.io/aframe/examples/ 

FWIW, Your application is calling the old WebVR API. The code below is obsolete when using WebXR enabled over https

https://github.com/Kif11/monster-or-friend/blob/076ab20cd659c3447b935107cd10393815aa97cc/src/components/Utils.js#L2

Remove that code and can reopen if that doesn't fix the issue.

**Comment by Kif11** [comment]
@dmarcos Thanks for pointing that `navigator.getVRDisplays()` is obsolete. This is very helpful. I will investigate more how I can remove it from my project.

**Comment by sneha-belkhale** [comment]
@dmarcos , thanks for the pointer, we managed to get the controllers showing up by removing calls to deprecated APIs. However, we are still not able to move using the oculus-touch-control joystick. I believe it is related to #4472 -- which was fixed after 1.0.4 was released.

How can we use an a-frame build that reflects the most recent state?

**Comment by dmarcos** [comment]
You can use [master builds](https://cdn.jsdelivr.net/gh/aframevr/aframe@901286a8553d32c5e53d992843a5041a6001ef08/dist/aframe-master.min.js)

[See commits](https://github.com/aframevr/aframe/commits/master) for links in the future
