### ISSUE TITLE
a-frame scene is black

### ISSUE THREAD

**Issue by igorroman777** [aframevr/aframe#4536]
**On my page www.artwista.com I have in VR in i-frame 
built-in. In chrome browser on Galaxy Tab A and android see 
I mean a-frrame scene But almost everything is **black**.:**

- A-Frame Version: 1.0.4
- Platform / Device: Android 7.1 / Chrome 80.0.3987.149 / Galaxy Tab A 
- Reproducible Code Snippet or URL: www.artwista.com

**Comment by dmarcos** [comment]
Any errors on console? FYI, there's known issues on old devices and shaders using `highp` and Adreno 300 series GPU. More info:

https://github.com/mrdoob/three.js/issues/14570

https://github.com/aframevr/aframe/pull/3977

**Comment by igorroman777** [comment]
no errors on console

**Comment by dmarcos** [comment]
Closing due to lack of info to reproduce. We can reopen if necessary
