### ISSUE TITLE
One cursor does not trigger raycast in vr mode

### ISSUE THREAD

**Issue by vladikz** [aframevr/aframe#4537]
![7k1UL_tA-Lc](https://user-images.githubusercontent.com/23656880/78354380-cd7c5380-75bc-11ea-893d-0c5804cae01c.jpg)

Why right cursor not trigger raycast on white circle? Left cursor work correctly

**Comment by dmarcos** [comment]
Origin of raycaster is the camera position not the stereo cameras that are shifted from camera. It should work as expected when mounted on headset.
