### ISSUE TITLE
Stretching when armature is a part of my mesh

### ISSUE THREAD

**Issue by hassanshaikley** [aframevr/aframe#4538]
Seeing distortion only after making the mesh a child of my armature. 

<img width="800" alt="Screen Shot 2020-04-04 at 11 16 06 PM" src="https://user-images.githubusercontent.com/6746840/78471078-3f4ebd00-76e3-11ea-9fda-7530f0299eb7.png">

Master branch but I was experiencing this issue on an older version as well.
- Chrome on an up to date mac.
- [Glitch](https://glitch.com/~zigzag-juvenile-bambiraptor)

[Blender file: mage_dude_v2.blend.zip](https://github.com/aframevr/aframe/files/4433218/mage_dude_v2.blend.zip)

**Comment by hassanshaikley** [comment]
I was able to get past this but I'm not exactly sure how. I had to reimport + rerig the mesh three times. The third time I leveraged a lot of blenders built in features for simplifying a model and that seemed to help. I also updated from 2.8 to 2.82 on the third try. I'm not sure what the exact fix was.

**Comment by donmccurdy** [comment]
Have you tested these models in a standalone viewer like https://gltf-viewer.donmccurdy.com/? And when you say "after making the mesh a child of my armature", are you referring to modifying the model in A-Frame, or modifying it in Blender?

Many fixes were made to Blender's glTF skinning export between 2.80 and 2.82. It is likely to have been fixed there, I don't think this is an A-Frame bug.

**Comment by hassanshaikley** [comment]
Thank you! I'll go ahead and close this.
