### ISSUE TITLE
AFRAME content in <iframe> not working properly

### ISSUE THREAD

**Issue by dtboy1995** [aframevr/aframe#4539]
**Description:**

- A-Frame Version: 1.0.3
- Platform / Device: Chrome

### iframe
```html
let { document, AFRAME } = iframe.contentWindow
console.log(AFRAME.utils.deepEqual({ x: 0, y: 0, z: -4 }, { x: 0, y: 0, z: -4 })); // return false
```

### normal
```html
<script>
    console.log(AFRAME.utils.deepEqual({ x: 0, y: 0, z: -4 }, { x: 0, y: 0, z: -4 })); //  return true
</script>
```

### source
```html
<html>

<head>
  <script src="https://aframe.io/releases/1.0.3/aframe.min.js"></script>
</head>

<body>
  <a-scene device-orientation-permission-ui="enabled: false">
    <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9"></a-box>
    <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E"></a-sphere>
    <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>
    <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
    <a-sky color="#ECECEC"></a-sky>
  </a-scene>
  <script>
    console.log(AFRAME.utils.deepEqual({ x: 0, y: 0, z: -4 }, { x: 0, y: 0, z: -4 }));
  </script>
</body>

</html>
```

When I load this URL through iframe, I get contentwindow and find deepequals doesn't work
thanks for any help?

**Comment by dmarcos** [comment]
Without a link to simple example to reproduce is hard to tell what's going on.

**Comment by dtboy1995** [comment]
@dmarcos thanks

**Comment by dtboy1995** [comment]
Why can't setAttribute method and aframe.utils.deepequal of elements work normally after iframe?
thanks for any reply

**Comment by dtboy1995** [comment]
### more detailed error testing in `iframe`

```html
<script>
var a = document.querySelector("iframe").contentWindow.document.querySelector("[camera]");
// works well
a.setAttribute("position","0 13 25");
// got error
a.setAttribute("position", {x: 0, y: 13, z: 25} );
</script>
```

**Comment by dmarcos** [comment]
iframes have security constraints that limit accessing the DOM. Check the console for errors. That's why a link to reproduce is necessary to properly diagnose.

**Comment by dtboy1995** [comment]
@dmarcos thanks for your reply
I hope you can take a closer look at the test examples I sent. I have tested many times and there are some problems. In the example, the aframe API does not work properly in iframe scenarios.

**Comment by dtboy1995** [comment]
@dmarcos 
i provide the bug sample
[index.html](http://sample.ithot.org/)
[iframe.html](http://sample.ithot.org/iframe.html)

**Comment by dmarcos** [comment]
We use github issues for bug and a feature requests. Your question is about A-Frame usage across iframe boundaries. I recommend opening a question on StackOverflow. Nice folks there to help:

https://stackoverflow.com/questions/tagged/aframe

Thanks for understanding.
