### ISSUE TITLE
gyroscope in VR mode not working on iOS 13.4.1

### ISSUE THREAD

**Issue by xoesan** [aframevr/aframe#4542]
**Description:**
just updated my phone to ios13.4.1, and apparently the vr mode is not working properly, it doesn't change the view with gyroscope movement. it works fine before ios13.4.1 update or without turning on vr mode.
console report:TypeError: null is not an object (evaluating 'i.alpha')
- webvr-polyfill.js:2240

<img width="996" alt="屏幕快照 2020-04-09 上午4 37 49" src="https://user-images.githubusercontent.com/20508873/78831460-43991400-7a1c-11ea-8011-5027cbe4ec5e.png">
- A-Frame Version:
- Platform / Device:iPhone XS iOS 13.4.1
- Reproducible Code Snippet or URL:

**Comment by xoesan** [comment]
the view in vr mode just stuck in a certain aspect and position (if not rotate it by dragging.)
not sure its a bug of ios13.4.1 or an updated feature or something...

**Comment by dmarcos** [comment]
link to reproduce?

**Comment by dmarcos** [comment]
FYI, you need A-Frame 1.0.4 and serve your content over https to comply with Safari policies to access device motion APIs

**Comment by dmarcos** [comment]
We can reopen if necessary. A-Frame examples work as expected https://aframe.io/aframe/examples/

**Comment by xoesan** [comment]
Thank you very much for your response!
But I just tested the examples on aframe.io
and it all has the same issue here. I do host my content on https and my version of aframe is 1.0.4.

I think it has to be something with ios 13.4.1, because it works just fine before I updated and on other devices which is not updated

**Comment by dmarcos** [comment]
Just tested on iOS 13.4.1 / iPhone X and all examples work for me:

https://aframe.io/aframe/examples/

**Comment by xoesan** [comment]
Okay... thanks for help!

**Comment by xoesan** [comment]
> Just tested on iOS 13.4.1 / iPhone X and all examples work for me:
> 
> 
> 
> https://aframe.io/aframe/examples/

Okay... Thanks for help!

**Comment by dax72** [comment]
I just tested on iOS 13.4.1 and it does not work when you enter in VR mode!
It work correctly with motion sensor before you click on VR button.
I tried with an iPad and with an iPhone.

**Comment by xoesan** [comment]
> I just tested on iOS 13.4.1 and it does not work when you enter in VR mode!
> 
> It work correctly with motion sensor before you click on VR button.
> 
> I tried with an iPad and with an iPhone.

Yes, same issue here.

**Comment by machenmusik** [comment]
Hi folks, can you try the branch in PR #4548 and see if that fixes it?

@dmarcos can you reopen?

**Comment by CGriffoin** [comment]
Hi guys,

I've the same issue : iOS 13.4.1 ( iPhone 8 Plus ), aframe v 1.0.4 ( or master ) installed from npm

> TypeError: null is not an object (evaluating 'i.alpha')

I reproduce on [https://aframe.io/aframe/examples/](https://aframe.io/aframe/examples/)

**Comment by dmarcos** [comment]
This is a dup of https://github.com/aframevr/aframe/issues/4554

Magic Window mode works fine on iOS 13.41
