### ISSUE TITLE
Camera and Accelerometer not working in Chrome 80.0.3987.95 on latest IOS

### ISSUE THREAD

**Issue by nexflo** [aframevr/aframe#4550]
Open aframe.io and none of the examples work (some load, but no interactions can be done)
ar.js + aframe with location markers is stuck in webrtc issue navigator.mediadevices

All running via HTTPS

**Comment by dmarcos** [comment]
Link? All aframe examples work for me:

https://aframe.io/aframe/examples/

Use 1.0.4. Notice that aframe.io show cases some 3rd party experiences that might not be updatrd

**Comment by dmarcos** [comment]
For ar.js I recommend opening an issue on the corresponding repo

**Comment by dmarcos** [comment]
Also make sure your browser is on mobile mode
