### ISSUE TITLE
WebXR not working on Chrome desktop and Oculus headsets

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4558]
Chrome has disabled Oculus runtime support in favor of OpenXR. Oculus has not yet shipped OpenXR.
Oculus runtime can be reenabled manually via command line options when launching Chrome:

```--enable-features=OculusVR --disable-features=XRSandbox --force-webxr-runtime=OculusVR```

There's no action to be taken on the A-Frame side. Once Oculus ships an OpenXR runtime everything should work again. 

@Artyom17 Let us know if there's any ETA for this. Thanks

**Comment by De-Panther** [comment]
Replacing `OculusVR` to `oculus` worked for me.
`--enable-features=oculus --disable-features=XRSandbox --force-webxr-runtime=oculus`
Thanks

**Comment by iq3connect** [comment]
@De-Panther which version of Chrome worked? Thanks.

**Comment by De-Panther** [comment]
@iq3connect `83.0.4103.61`

**Comment by sec-henning** [comment]
Which SteamVR Version are you running?

**Comment by dmarcos** [comment]
@sec-henning FYI, The flags above are for the Oculus runtime not SteamVR

**Comment by iq3connect** [comment]
@De-Panther thanks. I can confirm its working with Rift S. FYI Quest with link cable is not working.

**Comment by De-Panther** [comment]
@iq3connect works for me with Quest and link cable...

**Comment by dmarcos** [comment]
Info no longer applicable. Closing in favor of https://github.com/aframevr/aframe/issues/4709
