### ISSUE TITLE
Cannot access AR/VR button on ARcore compatible device

### ISSUE THREAD

**Issue by vikilleaks** [aframevr/aframe#4561]
I am trying to run [spinosaurus](https://glitch.com/edit/#!/xr-spinosaurus?path=index.html%3A1%3A0) on my phone (Redmi Note 7 Pro).
I enabled the experimental WebXR AR module in chrome://flags and made sure webpage is served over HTTPS.
My chrome version is 81.0.4044.117.
The code uses Aframe version 1.0.3
Despite all this, AR button is not getting displayed on my phone.
Also, VR button is getting displayed but there is no effect on clicking it.
Can someone tell the reason for this?

**Comment by dmarcos** [comment]
I don't have a Redmi Note 7 Pro. I just have access to a Pixel 3 and it works fine. Make sure your Android is up to date.

**Comment by dmarcos** [comment]
AR Mode should be now available on Chrome without any additional flags and ARCore compatible Android devices. I haven't been able to reproduce this on any device. I'm closing this but can reopen if neccessary.
