### ISSUE TITLE
a-sky cannot load image with url in my service

### ISSUE THREAD

**Issue by youxiaomingbai** [aframevr/aframe#4562]
**Description:**

- A-Frame Version:1.0.4
- Platform / Device:iOS Mac
- Reproducible Code Snippet or URL:

I run the code that the src is my service image , it shows white view
`   <a-scene>
      <a-sky src="https://img0.tking.cn/vr/55d577f50cf2554aad14102e/5de5f52f8c5dda0efecde922/lg/2F7_17row1_39seat_odd.jpg" ></a-sky>
    </a-scene>`

when I change others  , it works . why?
`   <a-scene>
      <a-sky src="https://cdn.aframe.io/360-image-gallery-boilerplate/img/city.jpg" ></a-sky>
    </a-scene>`

**Comment by dmarcos** [comment]
Look at CORS issues. I recommend opening a question on [StackOverflow](https://stackoverflow.com/questions/tagged/aframe). Nice folks there to help. We use github issues for bugs and feature requests. Make sure to provide link to runnable example or it will be hard to help
