### ISSUE TITLE
Learn result of permission popup?

### ISSUE THREAD

**Issue by omgitsraven** [aframevr/aframe#4563]
I have an A-Frame app that is vr-only by design (requires hand tracking); is it possible to listen to the result of the "allow virtual reality access" permission popup, in order to display an error message until it's enabled?

- A-Frame Version: 1.0.4
- Platform / Device: Windows

**Comment by dmarcos** [comment]
Sites don't have access to that information. It's deliberate so the user is in control on what info is disclosed to the page. I don't think there's anything actionable on the A-Frame side.
