### ISSUE TITLE
Aframe v1.0.4 sky radius is 500 instead of 5000 v0.9.2

### ISSUE THREAD

**Issue by smeybi** [aframevr/aframe#4565]
- A-Frame Version: Aframe v1.0.4 and master

The radius of the sky element is 500 instead of 5000 (default value)
<a-sky></a-sky>

**Comment by dmarcos** [comment]
Yes, that's intentional. Far plane of the camera in VR mode was clipping the geometry. What's exactly the problem? Notice that you can set your own value if you need https://aframe.io/docs/1.0.0/primitives/a-sky.html#attributes_radius

I updated the docs to reflect the new value.

**Comment by smeybi** [comment]
Ok, I thought it was a issue. Earlier was the default value 5000 and also  in the docs. I just wanted to report that. I've already set it up for myself.
