### ISSUE TITLE
v 1.0.4 (master) no world position of the camera with Oculus Quest

### ISSUE THREAD

**Issue by smeybi** [aframevr/aframe#4568]
With the Oculus Quest you can get the world position of the camera (0 0 0). Only the camera has this issue, all other works. Only with the Oculus Quest, it works with the HTC Vive, you can get the camera world position.

`el.object3D.getWorldPosition()`

I'm not sure it's right place here to report this issue instead of three.js

- A-Frame Version: 1.0.4 + (master)
- Platform / Device: Oculus Browser / Oculus Quest
- Reproducible Code Snippet or URL:

Here is a demo, the entity in the camera get the world position, not the camera itself.

https://glitch.com/~world-position-cam-oculus-quest-example

**Comment by binzume** [comment]
I have the same issue. Also there is workaround:  `cameraEl.object3D.matrixAutoUpdate = true;`

**Comment by dmarcos** [comment]
getWorldPosition doesn’t work on VR mode. It’s a known THREE bug. See [this commit](https://github.com/aframevr/aframe/commit/1fc08e429cef92fe53042ae08846c209889c30e5) for alternative

**Comment by smeybi** [comment]
Ah ok, I hadn't seen it, thanks!
