### ISSUE TITLE
Oculus Go controls use touchpad events with WebXR, not trackpad as documented

### ISSUE THREAD

**Issue by andygill** [aframevr/aframe#4569]
Oculus Go controls issue touchpadchanged, etc, events when used with WebXR, in the standard Oculus browser. The documentation says the component should issue trackpadchanged, etc, events.

- A-Frame Version: 1.0.4
- Platform / Device: Oculus Go

There is an assumption in the current code that the axes name (trackpad or touchpad) is the same as the final event name, and I don't want to generalize common code for a corner case such as the oculus go controls.

I have a fix (map touchpadchanged, etc, events to trackpadchanged, etc events), but its clunky, because it clones events.

Should I push the pull request? Or should we document this, and migrate towards using touchpad as the prefix?

**Comment by andygill** [comment]
I've pushed #4570 which should fix this issue.

**Comment by dmarcos** [comment]
Addressed by #4570 Thanks for the effort.
