### ISSUE TITLE
WebXR not working in Iframe on Google chrome 81

### ISSUE THREAD

**Issue by nikhilrayaprolu** [aframevr/aframe#4571]
https://xr-spinosaurus.glitch.me/ WebXR is not working on Iframe in Google chrome 81? I couldn't find the AR option.

But the same AR option is available if I directly access the link on an ARCore supported Device.

**Comment by dmarcos** [comment]
I think WebXR is not available on cross domain iframes but I might be wrong @klausw might know more.

**Comment by klausw** [comment]
WebXR is controlled by a feature policy using "xr-spatial-tracking": https://immersive-web.github.io/webxr/#feature-policy

By default it's allowed for the source document but not for embedded iframes, and you need to specifically allow it.

https://w3c.github.io/webappsec-feature-policy/ has an example:

```html
<iframe id="frame" allow="fullscreen; xr-spatial-tracking"></iframe>
```

**Comment by dmarcos** [comment]
Thanks! I think there's nothing actionable on A-Frame side here.
