### ISSUE TITLE
How to make AR work in React Native

### ISSUE THREAD

**Issue by nikhilrayaprolu** [aframevr/aframe#4572]
How to make https://xr-spinosaurus.glitch.me/ work in a React Native WebView Component?

    import React, { Component } from 'react';
    import { WebView } from 'react-native';
    
    export default class MyWeb extends Component {
      render() {
        return (
          <WebView
            source={{uri: 'https://xr-spinosaurus.glitch.me/'}}
            style={{marginTop: 20}}
          />
        );
      }
    }

Right now adding this to react-native only shows VR option but not AR option.

If you access the link directly you could see VR and AR options but I couldn't find the AR option when run in a Web View component inside React-Native
But the same AR option is available if I directly access the link on an ARCore supported Device.

How to make this code also show the AR option in React-Native?

**Comment by dmarcos** [comment]
I recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/aframe) for usage questions. We use github for bugs and feature requests.
