### ISSUE TITLE
Mouseenter and mouseleave events get activated on load

### ISSUE THREAD

**Issue by snavas** [aframevr/aframe#4577]
**Description:**

- A-Frame Version: 1.0.4
- Platform / Device: Windows 10 and Google Chrome
- Reproducible Code Snippet or URL: https://codepen.io/navasmedrano/pen/MWarGdq

I tried to recreate the custom component for handling mouseenter and mouseleave events as stated in the [A-Frame documentation](https://aframe.io/docs/1.0.0/introduction/interactions-and-controllers.html#handling-events-with-javascript). I realised that those events get activated (both mouseenter and mouseleave) when the webpage is loaded, only when using custom 3D models, not when using the basic A-Frame geometric elements.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/commit/358068e4d21c9a064f6c9dee47bd10a8db4ecaf4
