### ISSUE TITLE
animation rotation from bug

### ISSUE THREAD

**Issue by Perhelion** [aframevr/aframe#4578]
For me only the first animation call works, if you don't specify the "from" value. It seems the isRawProperty recognition changed somehow after the first call.

~~If I specify `isRawProperty = true` there is an visible glitch on the start.~~

**Comment by dmarcos** [comment]
Link to reproduce?

**Comment by Perhelion** [comment]
Sorry unfortunately not yet, but I dug into it and found something strange:

The `setRawProperty` function sets a number instead of an euler value!?

https://github.com/aframevr/aframe/blob/e41651cb28d0e4c216254efae58b2ca9e716f54e/src/components/animation.js#L585

**Comment by dmarcos** [comment]
This is an example of rotation animation working as expected:

https://glitch.com/edit/#!/cactus-vivid-sale?path=index.html%3A11%3A109

Without simple code to reproduce will be hard to dig further on the problem

**Comment by Perhelion** [comment]
@dmarcos 
I take the example from the click docu:
https://codepen.io/Perhelion/pen/gOavybJ

The bug seems to appear as the green cube only rotates one time.

**Comment by dmarcos** [comment]
FYI, you’re using an old version of A-Frame. a-animation has been deprecated in favor of the [animation component](https://aframe.io/docs/1.0.0/components/animation.html#sidebar). Update to 1.0.4

**Comment by Perhelion** [comment]
No there is 1.04. The example is mixed and the  relevant part is 1.0.4, 
The original example is from 0.6.1 on the documentary for 1.0.0.
You could instead take my example as update...

**Comment by dmarcos** [comment]
That's expected as per [from documentation](https://aframe.io/docs/1.0.0/components/animation.html#api_from). If `from` is not provided the current entity value is used implicitly. The green cube animation plays once and hence rotation is set to `to` value. Second time around there's no animation because `from` and `to` are same. Set the `from` value for your animations if you want the to run multiple times.

**Comment by Perhelion** [comment]
Ok thanks, then it seems something other. I added an reset event to the example which confirms your claim (so the cube rotates endless).

**Comment by Perhelion** [comment]
I updated the example for the **camera**, the camera should always reset after click, but...
