### ISSUE TITLE
animation rotation works only once on camera

### ISSUE THREAD

**Issue by Perhelion** [aframevr/aframe#4584]
**Description:**
For me only the first animation call works, if you don't specify the "from" value (which is obviously unpractical on the camera). It seems the isRawProperty recognition changed somehow after the first call.

(As the initial issue was closed as invalid,  (#4578 4578) I open a new.).

- A-Frame Version: 1.0.4
- Platform / Device: desktop
- Reproducible Code Snippet or URL: https://codepen.io/Perhelion/pen/gOavybJ

**Comment by dmarcos** [comment]
Is it possible to elaborate the issue? Can you describe what you get vs. what you expect?

**Comment by Perhelion** [comment]
The camera should reset after every cube click rotation animation!? But instead it does it only once!? (I'm also not sure anymore about the initial bug, as it does not appear anymore due some other changes I made). But I found another very strange (animation and may rare) bug, maybe from threejs (which I open tomorrow).

**Comment by dmarcos** [comment]
Use a [camera rig](https://aframe.io/docs/1.0.0/components/camera.html#examples) if you want to animate the camera. `look-controls` will override the rotation.

**Comment by dmarcos** [comment]
FYI, also notice that your animation on the camera doesn't have a `from` value so it won't work with a camera rig or when removing `look-controls`.
