### ISSUE TITLE
not a issue but a question on the environment

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [aframevr/aframe#4590]
Hello my question is in the 3d environment it's self is there a limit on size? What i mean in the environment it's self if i was to move my camera position far away from a object is there a limit on how far i can really go into i reach the end.

Joseph

**Comment by dmarcos** [comment]
We use github for bug reports and feature requests. For usage questions I recommend StackOverflow, Slack, discord... Check out the [community resources](https://aframe.io/community/)
