### ISSUE TITLE
oculus-touch-controls component : some events are not working at all or as stated in the docs

### ISSUE THREAD

**Issue by thedigitalbiker** [aframevr/aframe#4595]
Events are not firing correctly or as expected, based on the docs at : https://aframe.io/docs/1.0.0/components/oculus-touch-controls.html

Full details are in the code comments, but short version is:
triggerchanged -- fires if there is a partial change in the depth of the trigger pull. pull trigger halfway to see LOTS of events fire
thumbstickchanged -- ignores any motion of the thumbstick, both when down or when up
griptouchstart -- only fires when grip button is actually pressed, not when touched
griptouchend -- only fires when grip button is actually released, not when touch ends
gripchanged -- fires if button is partially depressed. press button halfway to see LOTS of events fire

surface**** -- none of the surface events fire. No surface button or control according to https://developer.oculus.com/documentation/native/pc/dg-input-touch-haptic/

- A-Frame Version: 1.0.4 min
- Platform / Device: oculus quest / touch controllers
- Reproducible Code Snippet or URL: https://57frf.csb.app/ at codesandbox or https://asocmedia.com/vrtests/oculus-controls-test.html on my testing site.

**Comment by dmarcos** [comment]
I haven't tested on device. FWIR, `triggerchanged` adn `gripchanged` expected behavior is what you described. Both are analog buttons that return a value between zero and one and the event fires when it changes.

```
controllerEl.addEventListener('triggerchanged', function (evt) {
  console.log(evt.detail.state.value);
});
```

**Comment by dmarcos** [comment]
I think there's nothing actionable on the A-Frame side. Let me know if there any improvements we should do on the docs. PRs are always welcome.
