### ISSUE TITLE
Add grid primitive

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe#46]
Enables the dev to add a grid to their scenes.

Dev can specify:
- Color (default is gray)
- Size (width and height of grid in meters. Default is 10)
- Density (number of horizontal and vertical segments in the grid. Default is 10).

**Comment by donmccurdy** [comment]
WIP: https://github.com/donmccurdy/aframe-extras/blob/master/src/primitives/a-grid.js

A couple issues left:

1. If custom colors are important, maybe we can generate custom tile images using data URIs?
2. The `mappings` property for primitives sets up a 1:1 pairing of two properties, but here we need for width/depth to map to both actual width/depth and `repeat.x`/`repeat.y`. Maybe mappings accepts an array: `width: ['scale.x', 'material.repeat.x']`?
3. Density maybe isn't necessary for now, but if so we'd need `mappings` with custom functions or something, to get `width / density => repeat.x`.

**Comment by ngokevin** [comment]
You could also write a fragment shader for the grid: https://aframe.io/docs/core/shaders.html#Creating-a-Custom-Shader

**Comment by mkungla** [comment]
What is the state of that issue

**Comment by ngokevin** [comment]
Not sure if we need to add to core, but can point to Don's which is on the Registry: 

https://github.com/donmccurdy/aframe-extras
https://npmjs.com/package/aframe-extras.grid
<img width="982" alt="screen shot 2017-03-31 at 10 20 50 pm" src="https://cloud.githubusercontent.com/assets/674727/24575629/52bafb4c-1660-11e7-80ae-6d8552e33b53.png">
