### ISSUE TITLE
Can't use letter like ÃãÁáÂâÉéÊêÍîÎíÕõÔô

### ISSUE THREAD

**Issue by mattosluis** [aframevr/aframe#4600]
**Description:**

- A-Frame Version: **1.0.4**
- Platform / Device: **Web / Chrome 81.0.4044.138**
- Reproducible Code Snippet or URL: 
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello, WebVR! • A-Frame</title>
    <meta name="description" content="Hello, WebVR! • A-Frame">
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
  </head>
  <body>
    <a-scene background="color: #000">
      <a-text position="0 0.5 -3" value="HÃãÁáÂâÉéÊêÍîÎíÕõÔôH!"></a-text>
    </a-scene>
  </body>
</html>`

**Comment by dmarcos** [comment]
Default fonts don't contain special characters. You will have to use fonts that do or create your own. [Example of 3rd party fonts](https://github.com/etiennepinchon/aframe-fonts)

**Comment by mattosluis** [comment]
Ok @dmarcos, I'll try it. Thank you!

**Comment by UtilExe** [comment]
Did you find a way @mattosluis?
If so, are you willing to share it? :)

Thanks in advance!
