### ISSUE TITLE
entity becomes invisible when moved to a different node position

### ISSUE THREAD

**Issue by brunoNetId** [aframevr/aframe#4604]
**Description:**
It seems an entity is no longer rendered when an entity from its current node position is moved to a new position.
This makes the entity invisible.
This used to work with A-Frame version 0.8.0

- A-Frame Version: 1.0.4
- Platform / Device: Mac/Chrome
- Reproducible Code Snippet or URL:

let sphere1 = document.getElementById('sphere1')
let sphere2 = document.getElementById('sphere2')
sphere1.after(sphere2)

**Comment by dmarcos** [comment]
[We recommend reparenting at the THREE.js level](https://stackoverflow.com/questions/52318200/change-parent-of-component-and-keep-position) Attaching / reattaching and re initializing components is costly and not always reliable (components have to account for a complex costly scenario that is relatively rare)
