### ISSUE TITLE
Aframe Version 1.0.4 THREE JS is missing Class TransformControls

### ISSUE THREAD

**Issue by tripdragon** [aframevr/aframe#4605]
Aframe Version 1.0.4 THREE JS is missing Class TransformControls
https://threejs.org/docs/#examples/en/controls/TransformControls

Aframes THREE.REVISION is at 111dev
I see in THREE update logs the class up in source at r108 not sure when it actually was first placed in, either way it looks to have been in Aframes version then.

I did not test for other stuff missing

**Comment by dmarcos** [comment]
TransformControls are not built-in the THREE bundle. [They're extras in the examples directory](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/TransformControls.js) and have to be imported separately.

**Comment by tripdragon** [comment]
AH! my mistake, I was surprised to see they had docs for it being in the examples dir.
