### ISSUE TITLE
tracked-controls doesn't work on the Oculus Quest

### ISSUE THREAD

**Issue by smeybi** [aframevr/aframe#4610]
tracked-controls doesn't work on the Oculus Quest. No controller is assigned.

- A-Frame Version: 1.x
- Platform / Device: Oculus Browser/Quest
- Reproducible Code Snippet or URL:

`<a-entity tracked-controls="controller: 0; idPrefix: OpenVR"></a-entity> 
<a-entity tracked-controls="controller: 1; idPrefix: OpenVR"></a-entity>`

https://glitch.com/~aframe-tracked-controls-demo

**Comment by dmarcos** [comment]
Use [oculus-touch-controls](https://aframe.io/docs/1.0.0/components/oculus-touch-controls.html#sidebar). e.g

```
<a-entity oculus-touch-controls="hand: left"></a-entity>
```
