### ISSUE TITLE
Video sphere does not work much at all, WegGL error

### ISSUE THREAD

**Issue by tripdragon** [aframevr/aframe#4613]
- A-Frame Version: 1.0.4
- Platform / Device: OSX/ Windows

Each example below has the same video file, lowpoly fish swiming around camera. This is just a video file no rotation code. 

**Aframe:**
On first load the video might work, but autoplay is not working. On teh second reload the screen will be black and the console gives:
WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty

https://pumped-fluffy-llama.glitch.me/fishvidaframe.html

**THREE.JS:**
Testing THREE.JS video sphere example file has no issue
https://pumped-fluffy-llama.glitch.me/fishvidthreejs.html

I have also tried putting the url in the src in the entity instead but same issues

threejs example taken from here
https://threejs.org/examples/?q=video#webgl_video_panorama_equirectangular
Only changes are making the type <script type="text/javascript"> and replacing video

**Comment by vincentfretin** [comment]
@dmarcos I think you meant `autoplay` instead of `autoload`.
There is also playsinline and webkit-playsinline attributes :)
@tripdragon Can you look at how Hubs is creating a video tag to use a video texture here: 
https://github.com/mozilla/hubs/blob/7b5b00f073055fc1861c8dc993dc0001a8f5f31c/src/components/media-views.js#L117

**Comment by tripdragon** [comment]
oh nice! need to test thank you

**Comment by dmarcos** [comment]
I think there's nothing actionable on the A-Frame side. [A-Frame is setting the same attributes than Hubs](https://github.com/aframevr/aframe/blob/master/src/core/a-assets.js#L186) We can reopen if neccessary
