### ISSUE TITLE
White bottom space after exit from VR mode

### ISSUE THREAD

**Issue by jgutierro** [aframevr/aframe#4617]
**Description:**

- A-Frame Version: cd01cec35a01e03eb2d6a9272500a53de31d3828 master commit but also happening with 1.0.4
- Platform / Device: iOS 13.4.1
- Reproducible Code Snippet or URL: https://app.estudiocactus.com/clickandrender/

Once you enable de VR mode and exit to potrait again a white space at the bottom appears.
VIDEO: https://streamable.com/tw439e

**Comment by dmarcos** [comment]
This looks like an iOS regression. More info at https://stackoverflow.com/questions/62717621/white-space-at-page-bottom-after-device-rotation-in-ios-safari
