### ISSUE TITLE
aframe 3D model import, position off

### ISSUE THREAD

**Issue by uurcankaya** [aframevr/aframe#4622]
**Description:**

- A-Frame Version: 1.0.4
- Platform / Device: Web, Chrome 81+
 
When I import a file the default position is not the origin. Moving arrows appear at origin, but model itself is away from origin.

What would be the reason for this? Is it related to export?

**Comment by dmarcos** [comment]
Yes, probably related to the export. Make sure the object is centered on the origin when exported. We can reopen if still a problem. Thanks for filing
