### ISSUE TITLE
Attaching object to camera does not work in Oculus Quest

### ISSUE THREAD

**Issue by PlumCantaloupe** [aframevr/aframe#4626]
So, I have stumbled into something that appears to have recently started happening in my work. That the camera A-Frame entity and the Oculus Quest HMD camera are no longer in synch. Basically attaching a body model to a camera like this:

```html
<a-entity id="camera"
                camera
                position="0 1.5 0">
        <a-entity   class="avatar_head"
                    gltf-model="#Head_Model">
        </a-entity>
</a-entity>
```
will work in 2D modes on Desktop, Mobile, and even in the Oculus browser when you are not in "VR mode"; but as soon as you enter VR mode the attached geometry sits in the floor (screenshots below of a project that shows an avatar in front of a mirror).

![com oculus vrshell-20200616-123313](https://user-images.githubusercontent.com/264985/84802056-02018800-afce-11ea-94f3-21b4cdb11d98.jpg)

**All good :)**

![com oculus browser-20200616-123447](https://user-images.githubusercontent.com/264985/84802066-05950f00-afce-11ea-9fac-d36bbec99ab8.jpg)

**Not good :(**

Can anyone else visit this [glitch.com project](https://glitch.com/~aframe-mirror-and-avatar) and confirm they have the same issues? Or perhaps point out whether I did something incorrect or is this a new bug?

🦖 Thank you

- A-Frame Version: 1.0.4
- Platform / Device: Oculus Quest / Browser 17.0.0.244 (should be most recent)
- Reproducible Code Snippet or URL: [Glitch.com project](https://glitch.com/~aframe-mirror-and-avatar)

**Comment by dmarcos** [comment]
A [simple example](https://glitch.com/edit/#!/aspiring-supreme-shame?path=index.html%3A16%3A6) of a gltf model nested in the camera. It follows the camera as expected.

**Comment by dmarcos** [comment]
A lot of going on in the provided example. Remove the mirror and try again. It has its own camera and render loop. It might affecting the camera used to render VR

**Comment by PlumCantaloupe** [comment]
Yeah, you are right :/

The mirror code has effected it. This worked previously so I will take a another look and see if I can figure what has changed (or a workaround). Will comment later for anyone else.
