### ISSUE TITLE
Aframe - embedded not working Safari iPhone

### ISSUE THREAD

**Issue by lijualivenow** [aframevr/aframe#4627]
**Description:**
I am working with the 8th wall and aframe. I am using `<a-scene embedded>` for displaying UI. It is working perfectly in Android but it showing the loading page on iPhone Safari.  If embedded is removed is AR is working. But full Screen UI will not show. But embedded is working perfectly in Android.

**Comment by dmarcos** [comment]
More likely to get help via [8th Wall support channels](https://www.8thwall.com/resources). I don't think there's anything actionable on the A-Frame side but can reopen if that's the case.
