### ISSUE TITLE
Use of Mirrors Broken on Oculus Quest (Discussion: a feature request for a mirror component in A-Frame)

### ISSUE THREAD

**Issue by PlumCantaloupe** [aframevr/aframe#4629]
This might be a an Oculus device issue, or maybe an issue with the XR renderer/camera implementation in three.js ( https://github.com/mrdoob/three.js/pull/19666 ) as it works in Firefox Desktop with the Quest in Link mode but does not work in either the Oculus Browser or Firefox Reality in standalone mode. However, I figured this area is likely the best area to discuss it. I am not exactly sure when this stopped working, though I suspect it was the jump to the WebXR API, but mirrors appear to broken in the two ways.

- This mirror only appears in one eye (seems to be right eye consistently). This just started happening on the most recent Oculus Browser update. Doesn't appear to happen in Firefox Reality.
- When using another camera to render the mirror's texture (RenderTarget) the main camera breaks and will no longer reveal appropriate world matrices and will no longer allow elements to be parented to it (further information on this issue here: #4626 ).

Hopefully someone more familiar with the underlying systems might see the trivial errors I have made, or perhaps some workarounds as I am using mirrors in my VR research :D

**These are the warnings (no errors) I am seeing in the console on the Oculus Browser:**
![Capture_Cust](https://user-images.githubusercontent.com/264985/85780585-c748cf80-b6f2-11ea-8ff8-8c7685872d2e.PNG)

I have created two example scenarios to showcase:

- This one I have been fiddling with, building off other works ([three.js](https://github.com/mrdoob/three.js/blob/34fe461e2dd0fdaa18fd4271bb5f5965fb850144/examples/js/objects/Reflector.js) and  [aalavandhaann ](https://github.com/aalavandhaann/three_reflector)):
**--->** [https://glitch.com/~aframe-mirror-and-avatar](https://glitch.com/~aframe-mirror-and-avatar)
- And a simpler one that is a more direct implementation of [three.js's reflector component](https://github.com/mrdoob/three.js/blob/34fe461e2dd0fdaa18fd4271bb5f5965fb850144/examples/js/objects/Reflector.js): 
**--->** [https://glitch.com/~aframe-threejs-reflector](https://glitch.com/~aframe-threejs-reflector) - not sure why the head texture is black here but I don't think it is related.

Though I understand that the use of secondary cameras for special effects is more of a fringe case it could be indicative of a larger issue. Also, as important as [embodiment ](https://blogs.scientificamerican.com/guest-blog/a-brief-guide-to-embodied-cognition-why-you-are-not-your-brain/) is for connecting to avatars, and the [use of virtual mirrors to create a greater sense of embodiment](https://www.researchgate.net/publication/224129986_The_contribution_of_real-time_mirror_reflections_of_motor_actions_on_virtual_body_ownership_in_an_immersive_virtual_environment), I would love to see and help support a "reflector" being an included component in A-Frame if others agree.

- A-Frame Version: 1.0.4
- Platform / Device: Oculus Quest using Oculus Browser or Firefox Reality (Oculus Link works with Firefox Desktop)
- Reproducible Code Snippet or URL:  https://glitch.com/~aframe-mirror-and-avatar and https://glitch.com/~aframe-threejs-reflector

**Comment by dmarcos** [comment]
A mirror component would be probably better as a 3rd party / community one.

**Comment by PlumCantaloupe** [comment]
Okay, thank you. Will keep poking at this and see if I can gauge interest somehow.

 Is it possible that this issue is browser / WebXR spec. related @Artyom17?

I created a pure three.js example and noted it here (appears to have similar issues): https://github.com/mrdoob/three.js/pull/19666#issuecomment-650676991

Glitch example: https://glitch.com/~pure-threejs-mirrortest

**Comment by dmarcos** [comment]
I would have to look into it. Not an answer to your question but a possible alternative  would be to have a copy of the avatar model in front of the user and apply headset and controllers pose to them. Simpler and also better performance than rendering the scene multiple times.

**Comment by PlumCantaloupe** [comment]
Thanks for the “Mario64” suggestion @dmarcos :) I might have to do something like that if I am still stuck later in the summer.

I think my next attempt will be looking at the mirror code itself and comparing to how shadow-mapping cams render depth. Maybe there is something there that could help ...

**Comment by dmarcos** [comment]
I think there's nothing actionable on A-Frame side. If there's any fix to be done has to happen on the THREE side. Closing but we can reopen if necessary.

**Comment by PlumCantaloupe** [comment]
For any stragglers, finally found a workaround here: https://github.com/aframevr/aframe/issues/4806#issuecomment-861114767

**Comment by diarmidmackenzie** [comment]
An implementation of mirrors for A-Frame is available here:
https://github.com/diarmidmackenzie/aframe-multi-camera

Specifically:
https://diarmidmackenzie.github.io/aframe-multi-camera/examples/mirror-example.html

Currently they work great on desktop, but they are heavily pixellated in VR (on Oculus Quest 2, at least), and I haven't yet understood why, but some ideas for further investigation.
