### ISSUE TITLE
Oculus Go Browser not entering VR - shows cardboard view

### ISSUE THREAD

**Issue by bknill** [aframevr/aframe#4630]
**Description:**

Same problem as this but in latest browser and Aframe https://github.com/aframevr/aframe/issues/3957

- A-Frame Version: 1.0.4 or Master
- Platform / Device: Oculus Go Browser 10.0.0.3,43
- Reproducible Code Snippet or URL:

Attempt to enter VR via scene.enterVR(), shows the same view as described in the issue above.  Shows the Cardboard Vr and does not enter VR.

**Comment by dmarcos** [comment]
Entering VR mode requires user action like `clicking the VR button in the corner`. It cannot be triggered programmatically as per privacy and security browser policies.

**Comment by bknill** [comment]
hey @dmarcos this is on a button press. I've just tried running in https as well and still no different. I get the same view described in the above issue.

**Comment by dmarcos** [comment]
Are the A-Frame examples working for you? https://aframe.io/aframe/examples/

**Comment by bknill** [comment]
Thanks @dmarcos the issue was the enterVR was getting called from a function that got called by the click, putting it straight into the function from the click fixed it, and running in https

**Comment by Gllloria** [comment]
I see the same problem with my Oculus Go, Oculus browser 10.0.0.3.43.
Also happens sometimes with the A-Frame examples like A-painter.
![grafik](https://user-images.githubusercontent.com/63304724/87526092-ad176700-c68a-11ea-809a-c8e7e44e1d3e.png)

**Comment by dmarcos** [comment]
Browsers have transitioned to WebXR and deprecated WebVR. All content using A-Frame versions older than 1.0.0 won’t work like in the A-Painter case. All A-Frame built-in examples should work

**Comment by Gllloria** [comment]
Thank you for your fast answer, the a-frame build in examples seem to work.
But my application still has the same issue, using aframe 1.0.3.
I don't use https yet, but http, can this be the sole reason?

**Comment by dmarcos** [comment]
Correct, WebXR is only available over HTTPS. It's a restriction imposed by the browser.
