### ISSUE TITLE
error, camera locked on an axis in mobile 

### ISSUE THREAD

**Issue by osmandigitalmedia** [aframevr/aframe#4634]
**Description: Hello everyone, I hope you have an excellent day, it happens that in desktop mode it works perfectly but on mobile devices it only moves on a single axis and also does not detect gyroscopic sensors, the same thing happens in the latest version 1.0.4, which can it be and how can I solve it?

I was checking and not only happens with me, but also with all the examples from the official website and other people's recent projects**

- A-Frame Version: 1.0.4
- Platform / Device: Android
- Reproducible Code Snippet or URL: https://osmandigitalmedia.com/vrtour

**Comment by dmarcos** [comment]
Dup of https://github.com/aframevr/aframe/issues/3559
