### ISSUE TITLE
[Question] Playing stereo video?

### ISSUE THREAD

**Issue by KyungWonPark** [aframevr/aframe#4636]
Hello

I'd like to play stereo video in aframe
I couldn't find it in documentation so asking here
Specifically, can I play one stereo video(mp4) on texture of object, but in stereoscopic manner?
So aframe divides side-by-side video on its own, and plays each side on corresponding texture 

This is exactly what I want to do:
https://immersive-web.github.io/webxr-samples/stereo-video.html

Thank you

**Comment by dmarcos** [comment]
I recommend opening a question on [https://stackoverflow.com/questions/tagged/aframe] first. Nice folks there to help. You can also repost the questions in [Slack / Discord](https://aframe.io/community/) for increased reach. We use Github issues for bugs / feature requests. Thanks for understanding.
