### ISSUE TITLE
Aframe Laser Controls fires 2 clicks

### ISSUE THREAD

**Issue by bknill** [aframevr/aframe#4638]
**Description:**

- A-Frame Version: 1.0.4
- Platform / Device: Oculus Browser / Oculus Go
- Reproducible Code Snippet or URL:

Pretty sure this is a bug but might be a support issue. 

export const isHeadset = AFRAME.utils.device.getVRDisplay() || AFRAME.utils.device.isMobileVR()

```
<a-scene id='scene' events="" antialias="true" cursor-listener="" background="color: red"  
keyboard-shortcuts="enterVR: false"
 cursor={ isHeadset ? '' : 'rayOrigin: mouse'}} raycaster={isHeadset ? 'objects: [data-raycastable]' : ''}  
vr-mode-ui="enabled: false"  loading-screen={'enabled:false'}>
....

<a-entity id="rightHand" laser-controls="hand: right"  raycaster="objects: [data-raycastable];far: 4"
 line="color: red; opacity: 0.75"></a-entity>

```

I have some clickable entities that get loaded at runtime. 

With the mouse, they only fire one click event when clicked, with an intersection on #scene. 

With the laser pointer, I get 2 click events, the mouse event as above, the #rightHand event with no intersection. 

I'm probably configuring these wrong. 

This is .tsx from React. I don't think that's the problem, everything else is working.  

Oh same issue https://github.com/aframevr/aframe/issues/4494

My hack is 

        if(!e.detail?.intersection)
            return

**Comment by dmarcos** [comment]
I'm closing this because the Oculus Go has been discontinued and the Oculus Browser is no longer getting updates.
