### ISSUE TITLE
Use cursor with aframe-master.js

### ISSUE THREAD

**Issue by jamess922** [aframevr/aframe#4643]
I tried some demos of aframe find that If wants to use cursor it only works with aframe.min.js like<script src="https://aframe.io/releases/0.6.1/aframe.min.js"></script>[ Demo](https://codepen.io/Absulit/pen/WEKjqm)
not working with aframe.master.js .   So how to make cursor working with aframe.master.js

**Comment by dmarcos** [comment]
What do you mean by not working? Do you have a link to an example to reproduce?

**Comment by jamess922** [comment]
With that codepen Demo i linked ,just simply replace `src="https://aframe.io/releases/0.6.1/aframe.min.js">` with `https://raw.githubusercontent.com/aframevr/aframe/master/dist/aframe-master.js` we will see no camera no cursor and no boxs.I thought aframe-min.js are lite version of aframe-master.js

**Comment by dmarcos** [comment]
`a-animation` has been deprecated in favor of the (animation component)[https://aframe.io/docs/1.0.0/components/animation.html#sidebar]. The [equivalent example using 1.0.4](https://aframe.io/aframe/examples/test/cursor/) [full HTML also on Github](https://github.com/aframevr/aframe/blob/master/examples/test/cursor/index.html)
