### ISSUE TITLE
problem with oculus rift / chrome browser / a-frame

### ISSUE THREAD

**Issue by comsyspro** [aframevr/aframe#4644]
**Description:**

- A-Frame Version: from 0.8.0 to 1.0.4
- Platform / Device: Oculus Rift / Chrome
- Reproducible Code Snippet or URL:

Chrome does not work with the VR mode of a-frame with an Oculus Rift headset.

On Windows I run the following command:
`start chrome.exe --disable-features=XRSandbox --enable-features=oculus --force-webxr-runtime=oculus`

After visiting the a-frame website and clicking the VR Button the Oculus Rift wants to open the chrome application but it stays on loading state and doesn't start and show the VR content. Does anyone know how to get it work?

I also read somthing about "WebXR Device API Origin Trial" for Chrome browser but I don't know how to use this. Does anyone know how to enable the "Origin Trial" for Chrome browser?

**Comment by dmarcos** [comment]
Original Trials is for domains to opt-in to new APIs for experimental purposes. I don't think it will solve the issue. 

AFAIK, Chrome WebXR implementation on desktop is transitioning to OpenXR and I think Oculus has not yet shipped a compatible runtime. VR support over vendor specific APIs is on its way out and implementation might be suffering.

@klausw @Artyom17 Is there any available timeline for the transition of Chrome to OpenXR for Oculus headsets? Anyway to make Chrome work with Rift in the meantime? Thanks so much!

No expected changes on the A-Frame side for this issue.

**Comment by klausw** [comment]
@toji provided more info in this update: https://github.com/immersive-web/webxr-samples/issues/43#issuecomment-654350720
> As we gain better compatibility with other runtimes (such as OpenXR) we're trying to discourage casual disabling of the sandbox in the interest of user security. You can still achieve the same thing by passing command line flags, though, as [described here](https://immersiveweb.dev/chrome-support.html).
> 
> We know that this is a pain, but given that both Oculus and Valve are working on OpenXR runtimes and Microsoft already has one that's fully compatible with Chrome's WebXR implementation we're focusing our efforts on making that path as pain-free as possible.

If I remember right, SteamVR's OpenXR mode is currently mostly working in Chrome Canary on Windows, but still requires disabling the security sandbox. It'll need a change by Valve to support the XR_EXT_win32_appcontainer_compatible OpenXR extension, which is on their TODO list: https://steamcommunity.com/app/250820/discussions/8/2448217320134520064/

I don't know the current status for Oculus support. It should work through SteamVR and its OpenXR device, but may need extra work to get the sandbox-compatible appcontainer mode working.

**Comment by dmarcos** [comment]
@klausw Thank you very much. Super appreciated

**Comment by comsyspro** [comment]
Thanks for your reply. The problem is that Firefox can show the VR content on the Oculus Rift but has another problem with the needed WebRTC connection (perhaps it's also a bug or mssing support in Firefox). I'm developping a VR application which needs a WebRTC connection to the realtime visualization application Unreal pixel streaming and at the same time it should display the VR content for which you need the a-frame support. So with Chrome the WebRTC works fine but not the a-frame. And with Firefox the a-frame works but not the WebRTC connection. So both browser need some work to do for future VR applications.

**Comment by dmarcos** [comment]
@comsyspro Can you use Chrome / Rift through Steam / OpenVR with [appropriate flags](https://immersiveweb.dev/chrome-support.html)

**Comment by comsyspro** [comment]
The only thing I tried was this:

On Windows I run the following command:
`start chrome.exe --disable-features=XRSandbox --enable-features=oculus --force-webxr-runtime=oculus`

But Chrome doesn't show the VR content (the WebRTC connection is fine) and this command had no effect to get a-frame work. What do you mean with Steam / OpenVR? What is Steam / OpenVR?

Also what I achieved was to use the Chrome extension WebVR API Emulation and with that I simulated a headset and the rotation in 3d space. [visit url: WebVR API Emulation](https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil) and with this extension I could successfully connect the WebRTC connection to the Unreal pixel streaming and I got from there a realtime created stream of an 3D scene with realtime navigation inside this 3D scene (head rotation 360 degrees and walking through the scene). So my VR application is working but at the moment the browser support is the problem for such kind of application. I own only an Oculus rift but perhaps also other headset devices will work but this I don't know. Do you suggest to use other headset devices?

**Comment by dmarcos** [comment]
[Steam / OpenVR](https://store.steampowered.com/about/) is Valve's gaming / VR platform that has compatibility with all major VR headsets including Rift. 

You might have more luck than with Oculus software. You can launch Chrome with the Open VR options described [here](https://immersiveweb.dev/chrome-support.html)

```
--disable-features=XRSandbox --enable-features=openvr --force-webxr-runtime=openvr
```

**Comment by comsyspro** [comment]
1. installed oculus rift setup software
2. installed steam and steam vr software
3. started chrome with flags: chrome.exe --disable-features=XRSandbox --enable-features=openvr --force-webxr-runtime=openvr
4. started the a-frame [360 degree image example](https://aframe.io/examples/showcase/sky/) in chrome and confirmed headset access to chrome browser
5. after pressing the vr button, in the headset you get a little application window showing the chrome icon and the message "wait for chrome" but chrome is not starting and the a-frame content of the 360 degree image is not shown.

So I can't get it work.

**Comment by dmarcos** [comment]
Closing this in favor of https://github.com/aframevr/aframe/issues/4709 since info here is no longer relevant. Command line arguments are no longer applicable and Oculus and SteamVR are now shipping OpenXR implementations.
