### ISSUE TITLE
How to set animation complete callback on dynamic animations in AFrame

### ISSUE THREAD

**Issue by knightMash** [aframevr/aframe#4653]
**Description:**
I am trying to set a callback in a dynamically created animation in Aframe.js. I can easily find the examples of completion callback of animations in case of static animations, but can't find any lead on how to set the animationcomplete callback on this dynamic animation. Here is examaple:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello, WebVR! • A-Frame</title>
    <meta name="description" content="Hello, WebVR! • A-Frame">    
    <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>  
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://rawgit.com/mayognaise/aframe-mouse-cursor-component/master/dist/aframe-mouse-cursor-component.min.js"></script>
    <script src="arSam.js"></script>
  </head>
  <body>
    <a-scene  class="aframebox"  device-orientation-permission-ui="enabled: true" vr-mode-ui="enabled: false" emitevents="true"
          cursor="rayOrigin: mouse; fuse: true; fuseTimeout: 0;" embedded >

    <a-camera camera="fov: 80;"  rotation-reader >
 
    </a-camera>
</a-scene>
  </body>
</html>
```

JS

```
    var scene;
$(document).ready(function(){


  scene = document.querySelector('a-scene');
  showObj();

});

var bullet;
function showObj(){
     var entityEl = document.createElement('a-entity');

     entityEl.setAttribute('geometry', {
                primitive: 'box',
                height: 1,
                width: 1
              });
     entityEl.setAttribute('animation', {
                id : 'myAnim',
                property: 'position',
                to: '0 0 -7',
                dur: 1000,
                easing: 'linear',
                loop: false
              });
     entityEl.setAttribute('scale', '1 1 1');
     entityEl.setAttribute('position', '0 -1.6 -5');
     entityEl.setAttribute('material', 'color', 'red');      
     scene.appendChild(entityEl);
     setlistener();

}

function setlistener(){
  bullet = document.querySelector("#myAnim");
  bullet.addEventListener('animationend', (e) => {
      alert("hello");
  });
}
```
- A-Frame Version: 0.9.2
- Platform / Device: js/browser
- Reproducible Code Snippet or URL: https://glitch.com/~cloud-full-cotton

**Comment by dmarcos** [comment]
I recommend opening a question on StackOverflow. Feel free to also repost on Discord / Slack. More visibility and nice folks there to help. We use github issues for bugs and feature requests. Thanks for understanding

**Comment by dmarcos** [comment]
FYI, you are in an old A-Frame version. Use 1.0.4

**Comment by knightMash** [comment]
I already did [here](https://stackoverflow.com/questions/63059585/how-to-set-animation-complete-callback-on-dynamic-animations-in-ar-js), but without a reply .And In version  1.0.4, click does not work on 3d objects. Have a look at the comment to the answer [here](https://stackoverflow.com/questions/60266576/click-events-not-working-with-current-version-of-aframe-1-0-3). I faced the same issue with the click in version 1.0.4

**Comment by dmarcos** [comment]
[An example of cursor working with 1.0.4](https://aframe.io/aframe/examples/test/cursor/) If that doesn't help it could an [ar.js integration issue](https://aframe.io/aframe/examples/test/cursor/)
