### ISSUE TITLE
webxr-dom-overlay example 

### ISSUE THREAD

**Issue by lue** [aframevr/aframe#4658]
examples/boilerplate/webxr-dom-overlay/index.html

**Description:**

- A-Frame Version: 1.0.4 and master
- Platform / Device: Pixel 2 XL
- Reproducible Code Snippet or URL: examples/boilerplate/webxr-dom-overlay/index.html

This example does not show any DOM elements when you enter the immersive AR mode. 

Can please someone confirm that it does work?

Thank you!

**Comment by dmarcos** [comment]
Yes it does work on Chrome 83 / Pixel 2. Notice the text on the upper left corner.

![Screenshot (Jul 28, 2020 3 45 44 PM)](https://user-images.githubusercontent.com/39342/88729933-ccca7880-d0e9-11ea-908d-0a274ce22806.png)

**Comment by dmarcos** [comment]
We can reopen if it's still an issue.
