### ISSUE TITLE
Video primitive no longer renders when canvas is used as a src

### ISSUE THREAD

**Issue by azmartone** [aframevr/aframe#4659]
Version 0.8.2 allowed you to use a canvas id as the src of a video primitive. In Version 1.0.4, when you use a canvas id as a video src, the element doesn't render and there is no warning or error message.

- A-Frame Version: 1.0.4
- Platform / Device: Windows 10 Firefox 78.0.2, Chrome 84.0.4147.89
- Reproducible Code Snippet or URL: https://codepen.io/azmartone/pen/JjGqvzq

In the codepen, switch the aframe.min.js versions and you will see that it works for 0.8.2 and not 1.0.4

**Comment by dmarcos** [comment]
Video has never been designed to work with canvas. If it worked in the past it was a coincidence? FWIW, I get the same results with A-Frame 0.8.2 and 1.0.4. The video doesn't render

**Comment by azmartone** [comment]
I guess all canvas textures were loaded as video textures in the past according to this commit:
https://github.com/aframevr/aframe/commit/b47f20363ba366514b1c493d3a9dcb59e73c0426

**Comment by dmarcos** [comment]
Yes, it looks like canvas working the same as video was unintended. Canvas and video used to share same code path that is no longer the case.

**Comment by dmarcos** [comment]
More context on https://github.com/aframevr/aframe/pull/3599. In the PR there's a component that might help in your case:

```
AFRAME.registerComponent('canvas-updater', {
  dependencies: ['geometry', 'material'],

  tick: function () {
    var el = this.el;
    var material;

    material = el.getObject3D('mesh').material;
    if (!material.map) { return; }
    material.map.needsUpdate = true;
  }
});AFRAME.registerComponent('canvas-updater', {
  dependencies: ['geometry', 'material'],

  tick: function () {
    var el = this.el;
    var material;

    material = el.getObject3D('mesh').material;
    if (!material.map) { return; }
    material.map.needsUpdate = true;
  }
});

```

**Comment by azmartone** [comment]
Thanks @dmarcos, that's exactly what I needed.

**Comment by dmarcos** [comment]
It works. Your modified code: https://codepen.io/dmarcos-the-sans/pen/PoZvxVv

**Comment by dmarcos** [comment]
Closing since there are no changes to be made on the A-Frame side.
