### ISSUE TITLE
Error handling for scene.enterAR()

### ISSUE THREAD

**Issue by federico-camonapp** [aframevr/aframe#4660]
**Description:**

- A-Frame Version: 1.0.4
- Platform / Device: Honor 7X / Chrome 84
- Reproducible Code Snippet or URL: `scene.enterAR()`

On this device (I assume this might be happening as well on other devices) I'm getting an error when trying to enter ar-mode: "Could not create a session because: The runtime for this configuration could not be installed". 

It seems like some required feature of the session config is not available (there was only one, and I've tried with local, local-floor, unbounded and bounded-floor). If possible, would be great to have the chance to catch the error thrown (maybe enterAR & enterVR could return a Promise?)

**Comment by dmarcos** [comment]
FWIW, AR mode cannot be entered programatically. It has to be triggered by user action as per WebXR spec security constrains

**Comment by federico-camonapp** [comment]
Yes, I'm aware of that. I'm triggering the ar mode through an html button (It's working fine on Samsung Galaxy A50 and S8)

**Comment by dmarcos** [comment]
Call `sceneEl.enterVR(true);` The function [returns a Promise](https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L269)

**Comment by federico-camonapp** [comment]
Hi @dmarcos, I've tried that but it's not working. Here're some notes:
- enterVR(true) is being fired after tapping an html button (it's working fine in other devices)
- navigator.xr.requestSession(xrMode, xrInit) is being called, but inner requestSuccess is never called (which makes sense, this is the error I'm getting)
- based on https://developer.mozilla.org/en-US/docs/Web/API/XRSystem/requestSession, should the catch clause be added there?

**Comment by dmarcos** [comment]
Without simple code to look at is hard to tell

**Comment by federico-camonapp** [comment]
Sure: current enterVR:

```
enterVR: {
    value: function(useAR) {
        var self = this;
        var vrDisplay;
        var vrManager = self.renderer.xr;

        // Don't enter VR if already in VR.
        if (this.is('vr-mode')) { return Promise.resolve('Already in VR.'); }

        // Has VR.
        if (this.checkHeadsetConnected() || this.isMobile) {
            vrManager.enabled = true;

            if (this.hasWebXR) {
                // XR API.
                if (this.xrSession) {
                    this.xrSession.removeEventListener('end', this.exitVRBound);
                }
                var xrMode = useAR ? 'immersive-ar' : 'immersive-vr';
                var xrInit = this.sceneEl.systems.webxr.sessionConfiguration;
                navigator.xr.requestSession(xrMode, xrInit).then(
                    function requestSuccess(xrSession) {
                        self.xrSession = xrSession;
                        vrManager.setSession(xrSession);
                        xrSession.addEventListener('end', self.exitVRBound);
                        if (useAR) {
                            self.addState('ar-mode');
                        }
                        enterVRSuccess();
                    });
            } else {
                vrDisplay = utils.device.getVRDisplay();
                vrManager.setDevice(vrDisplay);
                if (vrDisplay.isPresenting &&
                    !window.hasNativeWebVRImplementation) {
                    enterVRSuccess();
                    return Promise.resolve();
                }
                var rendererSystem = this.getAttribute('renderer');
                var presentationAttributes = {
                    highRefreshRate: rendererSystem.highRefreshRate,
                    foveationLevel: rendererSystem.foveationLevel
                };

                return vrDisplay.requestPresent([{
                    source: this.canvas,
                    attributes: presentationAttributes
                }]).then(enterVRSuccess, enterVRFailure);
            }
            return Promise.resolve();
        }

        // No VR.
        enterVRSuccess();
        return Promise.resolve();

        // and continues..
    }
}
```

Suggestion:
```
navigator.xr.requestSession(xrMode, xrInit).then(
    function requestSuccess(xrSession) {
        self.xrSession = xrSession;
        vrManager.setSession(xrSession);
        xrSession.addEventListener('end', self.exitVRBound);
        if (useAR) {
            self.addState('ar-mode');
        }
        enterVRSuccess();
    }).catch(err => {
        // Handle error
    });
```

**Comment by dmarcos** [comment]
Is the Honor 7X an ARCore compatible device?

**Comment by federico-camonapp** [comment]
No it's not. But somehow `hasWebXR` is `true`, and it's trying to get the xrSession by calling `requestSession` from `navigator.xr`.

**Comment by dmarcos** [comment]
It seems that WebXR is available but only in VR capabilities. That explains why enterAR doesn't work.
