### ISSUE TITLE
Not so much an issue but a request or proposal for WWW.SideQuestVR.com 

### ISSUE THREAD

**Issue by ChibiBlaziken** [aframevr/aframe#4667]
![Screenshot (97)](https://user-images.githubusercontent.com/51828461/91014777-d6d38000-e59e-11ea-8d72-36373bbc60af.png)

www.SideQuestVR.com is a application hosting site for VR games, apps, educational content and more, it reaches all types of PC users as well as Oculus Quest users and it would be amazing to see if you could put your learning experience into a VR format for it, The site has a large and growing following as well which may help out along with a review system for feedback for bugs as well as suggestions you can reply to, If you are at all interested there is a ton of information about how it works and how easy it is to make and update a submission at, https://sidequestvr.com/listing-guide 
It also allows you to check graphs of installation numbers, hook right into the github so when you push updates to here it also updates on the SideQuest page and more that may help you reach more people.

In any case you have an awesome goal and application, i look forward to future updates and learning thank you very much.

**Comment by dmarcos** [comment]
Thanks. We love SideQuest. There's nothing actionable in the A-Frame side. It's up to devs on how to promote their experiences. Feel free to [spread the word in Discord / Slack](https://aframe.io/community/)
