### ISSUE TITLE
Replace the HTTPS check with `window.isSecureContext`?

### ISSUE THREAD

**Issue by maudnals** [aframevr/aframe#4672]
**Description:**
- A-Frame Version: latest
- Platform / Device: all
- Reproducible Code Snippet or URL: /

**Bug:**
When running an A-Frame app locally on `localhost.myapp:8080` on a browser that supports it e.g. Chrome, the alert saying that sensor APIs are not available is displayed. 
Expected behaviour: no alert, because `localhost.myapp:8080` **is** a `SecureContext`, so sensor APIs are available.

**Analysis/Assumption:**
- According to [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs), device sensors require a `SecureContext`. I.e. `localhost` (= `127.0.0.1`), or an app running on `https`.
- However, right now, the [check](https://github.com/aframevr/aframe/blob/7d289e8fb28f2c2895ba49200f502257110d5050/src/components/scene/device-orientation-permission-ui.js#L29) to display an alert is made "heuristically" / by looking at the URL as a proxy to determine whether this is a `SecureContext`.

**Other issue:**
- The alert text says "Access this site over HTTPS to enter VR mode and grant access to the device sensors" when in fact device sensor access is not about HTTPS (in my understanding!). Rather, it's about `SecureContext`s, which is a bit different.

**Suggestion:**
- Replace the [check](https://github.com/aframevr/aframe/blob/7d289e8fb28f2c2895ba49200f502257110d5050/src/components/scene/device-orientation-permission-ui.js#L29) with the dedicated call `window.isSecureContext`?
and
- Replace the alert text?

Let me know if this makes sense! Especially: is the [MDN list](https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs) comprehensive, or am I omitting a range of sensor APIs that do need `HTTPS`?

**Comment by dmarcos** [comment]
I always develop using `localhost:8080` and the dialog doesn't show up. What's different about `localhost.myapp:8080`?

**Comment by maudnals** [comment]
Nothing should be different, exactly, because it is a `SecureContext`: the dialog shouldn't show up.
But the check fails, because the implementation only checks against `localhost`:  `if (location.hostname !== 'localhost')` (https://github.com/aframevr/aframe/blob/7d289e8fb28f2c2895ba49200f502257110d5050/src/components/scene/device-orientation-permission-ui.js#L29).

**Comment by dmarcos** [comment]
I see. PRs are welcome

**Comment by dmarcos** [comment]
Commenting on the original issue. While window.isSecureContext might be the way. Changing the message will make things more confusing. Secure Context is not understood by the avg. user while http / https while technical is a more familiar term. I'm myself not sure of what a Secure Context means and I've been doing web dev for quite a while now :)

**Comment by theisen1337** [comment]
Since this is still open, please allow for a simple way to turn this off. So I can build serve on my workstations localhost, then test from my local network phone i.e. connecting to 192.168.1.69:8100

**Comment by machenmusik** [comment]
There already is a way to easily turn this off, right?
https://github.com/aframevr/aframe/blob/7d289e8fb28f2c2895ba49200f502257110d5050/src/components/scene/device-orientation-permission-ui.js#L22

**Comment by richarddunnebsc** [comment]
I am trying to access my camera feed from localhost in Chrome, but its blocked because Chrome says localhost is not secure
`isSecureContext` is false.  I have asked on sitepoint and codeforum, but no solution as yet, if any.

**Comment by Dirk-27** [comment]
Have you tried to use Chrome://flags: 'Insecure origins treated as secure' with value: 'http://localhost'?

If you use other port than standard (80) you have to add the port like this: 'http://localhost:port'

**Comment by richarddunnebsc** [comment]
Yes, it didn't work.

Sincerely,

Richard Dunne B.Sc.

**Comment by mrxz** [comment]
Normally `localhost` is always treated as a secure context. In theory it wouldn't be (guaranteed) secure if proxied, but Chrome doesn't allow that by default. Either way, you could try and see if it works in a different browser and/or when using `http://127.0.0.1`.

**Comment by richarddunnebsc** [comment]
Using 127.0.0.1 doesn't work in Chrome either. I changed the navigator
browser to firefox on wampmanager.conf but localhost it is still opening in
Chrome.

Sincerely,

Richard Dunne B.Sc.
