### ISSUE TITLE
Can not remove background of scene

### ISSUE THREAD

**Issue by NVFedorov** [aframevr/aframe#4676]
**Description:**
I'm trying to remove scene background the following way: ```scene.removeAttribute('background');```. The attribute gets removed, but nothing changes in the scene.
- A-Frame Version: 1.0.4
- Platform / Device: windows 10, chrome
- Reproducible Code Snippet or URL:
https://glitch.com/~innovative-chlorinated-chestnut

**Comment by dmarcos** [comment]
What are you expecting to happen? There's always going to be a background color. Would set it to the color you want would work? `sceneEl.setAttribute('background', 'color', 'yourcolor')`

**Comment by NVFedorov** [comment]
I thought there should be some default color or transparent color after this attribute is removed
