### ISSUE TITLE
Color of HLS video on ios devices seems to be broken

### ISSUE THREAD

**Issue by hkirat** [aframevr/aframe#4677]
**Description:**
On using HLS (.m3u8) video on apple devices, the color of the final video is distorted. 

**Original video -** 

<img width="1214" alt="Screen Shot 2020-09-08 at 3 54 59 PM" src="https://user-images.githubusercontent.com/8079861/92465047-b38a1100-f1eb-11ea-80a5-1a20bc8441f3.png">

**What we see inside Aframe -** 
![IMG_0110](https://user-images.githubusercontent.com/8079861/92464907-732a9300-f1eb-11ea-94e5-c11f5f3465b1.PNG)

- A-Frame Version: 1.0.4 (Latest)
- Platform / Device: IPhone 7/ IPhone X / IPhone XS / IPad 6th Generation
- Reproducible Code Snippet or URL:
https://honored-recondite-wolverine.glitch.me/
https://glitch.com/edit/#!/honored-recondite-wolverine?path=index.html%3A20%3A41

- Solution 
It seems like there is an extra check for `ios + hls` - https://github.com/aframevr/aframe/blob/4a44a804bbf7347e41fdc88daa6fa1d68756029d/src/systems/material.js#L159 which might not be needed anymore.  (Ref https://github.com/mrdoob/three.js/issues/9754#issuecomment-409720290 )

Commenting the check fixes the color on the video - 
```js
      if (this.sceneEl.isIOS &&
          isHLS(videoEl.src || videoEl.getAttribute('src'),
                videoEl.type || videoEl.getAttribute('type'))) {
        // Actually BGRA. Tell shader to correct later.
        //texture.format = THREE.RGBAFormat;
        // texture.needsCorrectionBGRA = true;
        // Apparently needed for HLS. Tell shader to correct later.
        //texture.flipY = false;
        //texture.needsCorrectionFlipY = true;
      }
```
https://brook-changeable-celery.glitch.me/
https://glitch.com/edit/#!/brook-changeable-celery?path=script.js%3A14%3A2

![IMG_0111](https://user-images.githubusercontent.com/8079861/92465725-9d308500-f1ec-11ea-81fd-9077c811c1a4.PNG)

Happy to file for a P.R. for removing the code if the maintainers feel that might be the right way to go.

**Comment by dmarcos** [comment]
Dup? https://github.com/aframevr/aframe/issues/4134
