### ISSUE TITLE
[docs] Links to "WebVR Guidelines" are broken

### ISSUE THREAD

**Issue by vikohone** [aframevr/aframe#4680]
**Description:**
I found [two links](https://github.com/aframevr/aframe/search?q=webvr-guidelines&unscoped_q=webvr-guidelines) in the docs pointing to **WebVR Guidelines** in Supermedium's blog which are no longer available:
1. `1.0.0 › Introduction › Best Practices › WebVR` [[https://aframe.io/docs/1.0.0/introduction/best-practices.html#webvr](https://aframe.io/docs/1.0.0/introduction/best-practices.html#webvr)]
2. `1.0.0 › Introduction › Hosting & Publishing › Sharing Media` [[https://aframe.io/docs/1.0.0/introduction/hosting-and-publishing.html#sharing-media](https://aframe.io/docs/1.0.0/introduction/hosting-and-publishing.html#sharing-media)]

What should we do about the links? Should we just remove them or append an updated version of the guidelines under the [Best Practices](https://aframe.io/docs/1.0.0/introduction/best-practices.html#webvr) part? The latest version of the blog post I was able to find is from June 2018, don't know if you guys have any newer version of it 😁 
https://web.archive.org/web/20180609200103/https://www.supermedium.com/blog/webvr-guidelines

**Comment by dmarcos** [comment]
We can remove those links. The WebVR standard is now deprecated. PRs are welcome to remove the links

**Comment by vikohone** [comment]
@dmarcos Yeah, I just liked what was written on that blog :) I've removed the links in https://github.com/aframevr/aframe/pull/4683
