### ISSUE TITLE
Video material goes black when shader updated in Chrome

### ISSUE THREAD

**Issue by bknill** [aframevr/aframe#4688]
**Description:**

- A-Frame Version:  1.0.4 - latest
- Chrome 85

I think this is similar to https://github.com/aframevr/aframe/issues/4687

We have a sphere material that has been fine for ages. We are running from master. 

Now when the material shader is updated the material goes black.  Material also goes black when video is paused and the shader has been updated. 

Doesn't happen in Firefox, just Chrome at the moment, on Windows and Mac. 

Problem doesn't happen in 1.0.4 either.

**Comment by dmarcos** [comment]
Can you provide a link to reproduce?

**Comment by bknill** [comment]
@dmarcos I applied the changes from outside of a component and got around the problem. 

Not sure what it is. I'll let you know if I can find another way of making it happen.
