### ISSUE TITLE
Pinching with hand-tracking-controls is inaccurate

### ISSUE THREAD

**Issue by cesmoak** [aframevr/aframe#4689]
**Description:**
Currently, the pinching gesture recognized by `hand-tracking-controls` is inaccurate for me. `pinchstarted` rarely fires as expected and when releasing an object that follows the pinch gesture, it unexpectedly follows the index finger (as it is separating from the thumb) until the gesture is ended.

I suggest two changes to the existing code:
- Increase the minimum distance between thumb and index finger needed to recognize a pinch (I found that increasing it from `0.01` meters to `0.02` meters significantly increases the frequency at which the gesture is recognized, probably partly because the finger tip positions are in the center of the fingers (and further apart than the pads of the fingers). This could also be a configurable property of the component.
- Use the position of the midpoint between the index fingertip and the thumb fingertip for pinch events so objects following the pinch position do not incorrectly move with the index finger as the pinch is released

If these sound good, I can submit a PR.

- A-Frame Version: master
- Platform / Device: Quest
- Reproducible Code Snippet or URL: https://bristle-curly-primula.glitch.me/ Both behaviors are exhibited here

**Comment by dmarcos** [comment]
Thanks. It sounds good. Feel free to open a PR
