### ISSUE TITLE
Scene is not getting paused when call pause on 'loaded' event

### ISSUE THREAD

**Issue by NVFedorov** [aframevr/aframe#4693]
**Description:**
If you add event listener to the ```loaded``` event of a scene and try to pause the scene inside, the scene will have not been paused. 
- A-Frame Version: 1.0.4
- Platform / Device: windows 10, latest chrome 
- Reproducible Code Snippet or URL: https://glitch.com/~good-jumpy-crowberry

Please have a look into the snippet. Scene will continue to respond to look around actions, moving controls and if you'll check in console ```document.querySelector('a-scene').isPlaying``` will be ```true```

**Comment by dmarcos** [comment]
Yeah. That's expected. `loaded` emits when assets, children and all their components have loaded. Play kicks in later. You can listen to the `play` event instead and pause the scene:

```
  var sceneEl = document.querySelector("a-scene");
    document.querySelector("a-scene").addEventListener('play', function(evt){
      if (evt.target === sceneEl) {
        alert("scene starts playing")
        document.querySelector('a-scene').pause();
      }
    });
```

Corrected [glitch](https://glitch.com/edit/#!/fearless-likeable-dish?path=index.html%3A25%3A7)
