### ISSUE TITLE
Doesn't work continuously in webxr mode on ios WebXR Viewer 2.0 app

### ISSUE THREAD

**Issue by kongminh** [aframevr/aframe#4699]
Run this example: https://aframe.glitch.me/
on this app: https://apps.apple.com/us/app/webxr-viewer/id1295998056
In AR mode it's working only from 10 to 20 seconds, and then it exited AR mode.
App WebXR Viewer run on iPhone 8 plus, iOS 13.7
Webxr example without aframe still working good in this app

**Comment by dmarcos** [comment]
It works for me on iPhone X and iOS 14.0.1 

FYI, As far as I know the webxr viewer is no longer maintained. The Mozilla team that used to maintain it closed down.

**Comment by kongminh** [comment]
Version 14.0.1 is running longer but still stops after about 1 minute.
My iPhone 8 Plus updated from 13.7 to 14.0.1, and it works for 1 minute.
Another phone iPhone XS Max, iOS 14.0.1 works for 1 minute and 15 seconds.
About WebXR Viewer, it is just move to new repository from version 2, now it is based on the Firefox for iOS source, on branch webxr:
https://github.com/mozilla-mobile/firefox-ios/tree/webxr
This is old repository (version 1):
https://github.com/mozilla-mobile/webxr-ios
Thank you for your attention.

I tried debug in enterAR function of a-scene.js file:
https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js
I see in this line (in enterVRSuccess function) maybe related to the problem:
```
self.renderer.setAnimationLoop(self.render);
```
And then I found in three.js document:
https://threejs.org/docs/#api/en/renderers/WebGLRenderer.setAnimationLoop
```
.setAnimationLoop ( callback : Function ) : null
callback — The function will be called every available frame. If `null` is passed it will stop any already ongoing animation.
```
I hope anyone canbe help me to make it clearer.
I will try debug in three.js

**Comment by aerchit** [comment]
> Run this example: https://aframe.glitch.me/
> on this app: https://apps.apple.com/us/app/webxr-viewer/id1295998056
> In AR mode it's working only from 10 to 20 seconds, and then it exited AR mode.
> App WebXR Viewer run on iPhone 8 plus, iOS 13.7
> Webxr example without aframe still working good in this app

Can you run this example on WebXR Viewer? [https://xr-spinosaurus.glitch.me/](https://xr-spinosaurus.glitch.me/)
I tested it, it worked on iphone 11

**Comment by dmarcos** [comment]
I cannot reproduce the issue on iPhone X after running https://aframe.glitch.me/ for 5 minutes+. It's likely a bug affecting only older phones. I don't think there's anything actionable on A-Frame side.

Unfortunately, the team at Mozilla that maintained the gecko view / webxr on ios and the webxr viewer shut down. There are no longer active maintainers and issues will likely remain unaddressed.

**Comment by aerchit** [comment]
> I cannot reproduce the issue on iPhone X after running https://aframe.glitch.me/ or https://xr-spinosaurus.glitch.me/ for 5 minutes+. It's likely a bug affecting only older phones. I don't think there's anything actionable on A-Frame side.
> 
> Unfortunately, the team at Mozilla that maintained the gecko view / webxr on ios and the webxr viewer shut down. There are no longer active maintainers and issues will likely remain unaddressed.

That sucks. My little  Web AR project relies on Webxr Viewer to run on ios... Hope ios can support WebXR soon.

**Comment by kongminh** [comment]
> > Run this example: https://aframe.glitch.me/
> > on this app: https://apps.apple.com/us/app/webxr-viewer/id1295998056
> > In AR mode it's working only from 10 to 20 seconds, and then it exited AR mode.
> > App WebXR Viewer run on iPhone 8 plus, iOS 13.7
> > Webxr example without aframe still working good in this app
> 
> Can you run this example on WebXR Viewer? https://xr-spinosaurus.glitch.me/
> I tested it, it worked on iphone 11

I ran it, but it took 1 minute only to stop

**Comment by aerchit** [comment]
Today I tested aframe ar on iphone 12/iphone XR. They all worked for 15~30 secs then freeze.

**Comment by aerchit** [comment]
> About WebXR Viewer, it is just move to new repository from version 2, now it is based on the Firefox for iOS source, on branch webxr:

Mozilla laid off WebXR team in August. Do you have any source about the project will be maintained?

**Comment by dmarcos** [comment]
The WebXR Viewer is no longer maintained and there's nothing we can do on the A-Frame side. 

Info about the WebXR Viewer code base can be found here: https://github.com/mozilla-mobile/webxr-ios
