### ISSUE TITLE
three.js loaders deprecated Dec 2020

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe#4703]
**Description:**
In console, threejs loader deprecation warning for draco, gltf, etc. 

DRACOLoader.js:1 THREE.DRACOLoader: As part of the transition to ES6 Modules, the files in 'examples/js' were deprecated in May 2020 (r117) and will be deleted in December 2020 (r124). You can find more information about developing using ES6 Modules in https://threejs.org/docs/#manual/en/introduction/Installation.

GLTFLoader.js:1 THREE.GLTFLoader: As part of the transition to ES6 Modules, the files in 'examples/js' were deprecated in May 2020 (r117) and will be deleted in December 2020 (r124). You can find more information about developing using ES6 Modules in https://threejs.org/docs/#manual/en/introduction/Installation.

OBJLoader.js:1 THREE.OBJLoader: As part of the transition to ES6 Modules, the files in 'examples/js' were deprecated in May 2020 (r117) and will be deleted in December 2020 (r124). You can find more information about developing using ES6 Modules in https://threejs.org/docs/#manual/en/introduction/Installation.

MTLLoader.js:1 THREE.MTLLoader: As part of the transition to ES6 Modules, the files in 'examples/js' were deprecated in May 2020 (r117) and will be deleted in December 2020 (r124). You can find more information about developing using ES6 Modules in https://threejs.org/docs/#manual/en/introduction/Installation.

- A-Frame Version: A-Frame Version: 1.0.4 (Date 2020-10-11, Commit #87930d4f)
- Platform / Device: Chrome Mac OS
- Reproducible Code Snippet or URL: https://aframe-signal-pcfont-crt.glitch.me/

**Comment by kfarr** [comment]
Related three.js discussion:
https://github.com/mrdoob/three.js/issues/20455

**Comment by dmarcos** [comment]
It looks `examples/js` won't be deprecated after all? https://github.com/mrdoob/three.js/issues/20455#issuecomment-706954770

**Comment by kfarr** [comment]
Agreed, seems like it's paused, so I would expect the deprecation notice to be removed in subsequent three releases, will mark as closed until it comes up again.

**Comment by arpu** [comment]
in  the long run would be nice to use the Named imports from three
