### ISSUE TITLE
Aframe Hit-test Enter AR not working from yesterday (13th oct 2020) Was working before.

### ISSUE THREAD

**Issue by dirrogate** [aframevr/aframe#4707]
This git was working until yesterday
https://github.com/stspanho/aframe-hit-test

- Platform / Device:   Samsung S8 with latest Chrome browser and Samsung Internet browser (both updated to latest versions)

On pressing AR button, all you get is an image with icon of phone from portrait to landscape with "Insert phone in cardboard" text. It does not enter AR mode. (this when pressing AR button not vr)
Filing this after twitter conversation 
https://twitter.com/dmarcos/status/1316115865121693696

**Comment by klausw** [comment]
Do you have a link to a testable example? https://github.com/stspanho/aframe-hit-test is the github repository itself, and I don't see a published version at https://stspanho.github.io/aframe-hit-test .

Also, could you add browser version numbers for completeness? Chrome has separate stable/beta/dev/canary channels, and new updates are rolled out incrementally, so "latest" can be ambiguous.

**Comment by dmarcos** [comment]
I pushed the example to gh-pages. You can test on: https://diegomarcos.com/aframe-hit-test/

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/commit/8036f714135380ca8767b701b447ddd94aa8fa64
