### ISSUE TITLE
Oculus Browser not entering VR mode in Quest 2

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4711]
I've seen some reports of people not being able to enter VR mode in Quest 2. I cannot reproduce in my personal devices.

It looks is related to desktop mode being default now in Oculus Browser. Some people were able to workaround the issue by setting the browser into mobile mode and clicking enter VR. The permission prompt to enter VR mode is displayed and once accepted everything works as expected.

**Comment by arpu** [comment]
i hit this if i am in vrmode and my dev server reloads the page automatic, after automatic leav the vr-mode , its not possible to reenter

chrome://restart ( in the adressbar helps)

**Comment by kelvissu** [comment]
I am still seeing the issue and have tried what both @dmarcos and @arpu suggested, but I'm stilll not able to fix this. Any update on this issue?

**Comment by dmarcos** [comment]
@kelvissu Is this link working for you? https://aframe.io/aframe/examples/boilerplate/hello-world/

**Comment by dmarcos** [comment]
I believe this issue is gone now. We can reopen if necessary

**Comment by Artis39** [comment]
> @kelvissu Is this link working for you? https://aframe.io/aframe/examples/boilerplate/hello-world/

Hi. That link doesnt work for me. I cant open anything from browser after windows reinstall. Im using Oculus Rift.
