### ISSUE TITLE
CSS3DRenderer support

### ISSUE THREAD

**Issue by KostaMalsev** [aframevr/aframe#4712]
Hi,
Unfortunately found out that the THREE CSS3DRenderer is not supported in aframe 1.0.4
(see ref: https://stackoverflow.com/a/51187136).
We would like to get the most of the flexibility of CSS with 3D objects in aframe. (Canvas elements options are very limited) 
Please add CSS3D support.
Thank you,
Kosta 

- A-Frame Version: 1.0.4
- Platform / Device: Safari,Chrome, Firefox
- Reproducible Code Snippet or URL: (ref: https://subscription.packtpub.com/book/web_development/9781783981182/1/ch01lvl1sec12/getting-started-with-the-css-3d-renderer)

**Comment by dmarcos** [comment]
Unfortunately the CSS3DRenderer [won't work in VR mode](https://aframe.io/docs/1.0.0/introduction/faq.html) that is the focus of the project.

**Comment by KostaMalsev** [comment]
I tried to add a CSS3DRenderer object into a project (with no VR mode) and it failed.

**Comment by dmarcos** [comment]
Switching renderers is not a trivial task. Most components assume a WebGL backend: shaders, materials, geometries... It would require gutting most of A-Frame core.

**Comment by KostaMalsev** [comment]
Thanks. I'd be happy to be posted on possible workarounds.

**Comment by dmarcos** [comment]
Incorporating a CSS3DRenderer is not something we're considering at the moment since it won't work in VR mode and that's the A-Frame focus. Thanks for the suggestion.
