### ISSUE TITLE
360 videos not running

### ISSUE THREAD

**Issue by Radicals360** [aframevr/aframe#4714]
There's been some weird problems going on with running 360 videos. 
Suddenly 360 videos not running anymore through android devices, but they work desktops and ios systems. I first think that problem was in our Amazon bucket where videos is or new Chrome update, but today videos also stop running with desktop and ios...
In desktop it's saying: WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty and it's hints to three.js
Some googleing say there was year ago same problems with chrome.

Been tested with couple fresh aframe versions and with different devices. Also use our old package (which work earlier) just make sure that problem wasn't some where else. And yes tested also with local videos to make sure that video host not be reason.

**Comment by dmarcos** [comment]
Link to reproduce? FYI, Browser policies now enforce a user gesture (tap or click) to start playing a video. This is a [working example](https://ruddy-chief-gigantspinosaurus.glitch.me/) on iOS 13 (iPhone X) and Android Chrome 86 (Pixel 3) and [code](https://glitch.com/edit/#!/ruddy-chief-gigantspinosaurus?path=index.html%3A15%3A23). We can reopen the issue if neccessary.
