### ISSUE TITLE
Safari - THREE.WebGLProgram: shader error: ERROR: unsupported shader version1: #version 300 es

### ISSUE THREAD

**Issue by bknill** [aframevr/aframe#4715]
**Description:**

- A-Frame Version: 1.0.4 master
- Platform / Device: Safari 
- Reproducible Code Snippet or URL:

Put issue on Stackoverflow, but then reverted to 1.0.4 stable and issue goes away

https://stackoverflow.com/questions/64672597/safari-three-webglprogram-shader-error-error-unsupported-shader-version1

Text doesn't render in latest with this issue. 

It seems to relate to the THREE.Meshline shader, but that is working fine in 1.0.4

![image](https://user-images.githubusercontent.com/7074483/98058269-1ecd2800-1ea9-11eb-8eac-9741f32c840d.png)

**Comment by dmarcos** [comment]
Can you try with [master](https://cdn.jsdelivr.net/gh/aframevr/aframe@dc8236cb378bc1f79cae813e2a59b0cbd5e21f24/dist/aframe-master.min.js)? Also do you have a link to reproduce?

**Comment by bknill** [comment]
Yes fixed on master thanks.
