### ISSUE TITLE
Can't limit scene objects a cursor raycaster intersects with by amount (rather than distance)

### ISSUE THREAD

**Issue by jtq** [aframevr/aframe#4724]
When using a raycaster in a cursor the raycaster always registers intersections with every object it encounters between `.near` and `.far` distance away, but there's no way to limit it to a specified max number of objects (eg, "only the closest object").

This isn't the end of the world if you're managing intersection events in the cursor/raycaster (because you can simply take the first X elements in the distance-ordered array of intersected elements returned by the `raycaster-intersection` event), but if you want to have components which manage their own reactions to being intersected-with (ie, by reacting to `raycaster-intersected` events) it becomes extremely difficult to do so in a modular/isolated/[least-knowledge](https://en.wikipedia.org/wiki/Law_of_Demeter) way.

A simple use-case for this would be a game where there are a number of interactable objects in the scene, with some occluding others, and the player is only supposed to be able to interact with the objects they can see, rather than the closest object and any objects behnd it that are blocked from their view.

A simple/naive approach would be to add an optional `maxObjects: {default: -1}` property to the raycaster, which only tracks/emits intersected and intersected-cleared events for the nearest `data.maxObjects` intersected objects, though this limits you to only choosing the _nearest_ X objects (a reasonable supposition as this is likely to overwhelmingly be the most common use-case, but possibly still overly-opinionated).

Alternatively, we could include the list of all intersected objects in each `raycaster-intersected` event so that objects can determine for themselves where they sit in the z-order of intersected objects (and hence whether they should react to the intersection or not).  This approach might also imply a similar change (for consistency) to `raycaster-intersected-cleared` events, though I'm not sure there's a definite use-case there that I can think of.

I already have a customised version of the raycaster component for the naive approach above that I can quickly turn into a PR, but I'm also happy to re-implement the functionality according to the second (or any other suitable) approach if preferred.

- A-Frame Version: 1.0.4
- Platform / Device: Confirmed Windows/Chrome, Android/Chrome, suspected all platforms
- Reproducible Code Snippet or URL: To be added

**Comment by dmarcos** [comment]
What about a component in the entities that have the cursor? This component would check for `raycaster-intersection`. It can look at distances, occlusion and any other criteria you need. When conditions are met I would emit an event on the relevant entities that they can use to react to.

**Comment by dmarcos** [comment]
Thanks for filing. I think there's nothing actionable here on the A-Frame side. There's a way to implement the described functionality with the existing API that seems to be more efficient. In general is better to centralize the raycaster filtering on the entity that owns the `cursor` / `raycaster` component vs. running potentially redundant logic in all the "interactable" entities. Closing for now. We can reopen if I misunderstood or new info becomes available.

**Comment by jtq** [comment]
Ah - I assumed that because you could already filter intersected objects using options like `far` and `near` that it made sense to also build more filtering options into the raycaster component, but if the best-practice way to hande it is to centralise logic in the cursor and use custom events then that could also work for me.  Thanks!
