### ISSUE TITLE
Camera shakes when device is still

### ISSUE THREAD

**Issue by federico-camonapp** [aframevr/aframe#4726]
**Description:**

- A-Frame Version: 1.0.3 / 1.0.4
- Platform / Device: iOS / iPhone XS, XS Max, 11, 11 Pro
- Reproducible Code Snippet or URL: any example from AFrame

If the device moves, the shakes goes away, but as soon as the device stands still, the shaking begins. (here's a video capture [RPReplay_Final1605612208.zip](https://github.com/aframevr/aframe/files/5553125/RPReplay_Final1605612208.zip))

**Comment by dmarcos** [comment]
Any steps to reproduce? I don't see the issue on an iPhone X / iOS 14.1 / Safari and any of the [examples](https://aframe.io/aframe/examples/)

**Comment by federico-camonapp** [comment]
No specific steps to reproduce, just open any example (iOS 14.1 / Safari (& Firefox) / devices mentioned above). 

Just tried something new: the annoying shake went away when I've turned off & on my devices.

**Comment by dmarcos** [comment]
So, this is no longer a problem?

**Comment by federico-camonapp** [comment]
Well, yes it is. After using the devices "for a while", it starts happening again (weird, i know)

**Comment by dmarcos** [comment]
Phone gyros and phone accelerometers accumulate drift over time. [Additional context](https://github.com/immersive-web/webvr-polyfill/issues/30). I believe there's nothing actionable on the A-Frame side. We can reopen if necessary.
