### ISSUE TITLE
VR mode not working on iOS

### ISSUE THREAD

**Issue by elise-s** [aframevr/aframe#4727]
**Description:**

- A-Frame Version: 1.0.4 and also tested on the latest commit of the master branch
- Platform / Device: iOS / 13.4
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

When entering VR mode on iOS the view rotates and freezes instantly. I stumbled upon this issue with my own VR project, but this issue occurs even on the examples of A-Frame, like HelloWorld.

![aframe-helloworld-stereo-ios](https://user-images.githubusercontent.com/50174829/99552036-d8a1b980-29bc-11eb-8f97-de20873975e6.png)

**Comment by dmarcos** [comment]
It works for me on Safari / iOS 14.1 / iPhoneX on the provided URL and [any of the examples](https://aframe.io/aframe/examples/). Make sure you clicked on allow when A-Frame asks for access to the device motion sensors.

**Comment by elise-s** [comment]
Since it worked for you on iOS 14.1, I have updated my iPhone to the latest iOS version (14.2). This has solved the freezing of the screen issue 🥳 

However, it still doesn't fully work as desired for cardboard users because the stereoscopic view is either not full screen, depending on the page on which the canvas is rendered, or the safari URL bar appears over the view. Do you know what causes these problems?

Looks like Safari issues to me. Should I create a new issue for these problems?

![incorrect-size-helloworld-example](https://user-images.githubusercontent.com/50174829/99650974-55cd3d00-2a56-11eb-83a6-55a2b6908187.png)
![not-full-screen](https://user-images.githubusercontent.com/50174829/99650975-5665d380-2a56-11eb-8834-81097a1b33c5.png)

**Comment by dmarcos** [comment]
Notice that cardboard needs to align the eye views with the holder lenses. Fullscreen is not a requirement. There's a large and increasing range of device screens and cardboard holders. Some devices might not work properly. Unfortunately, testing all devices in all holders is intractable. We're not focusing much resources at the moment since cardboard usage is declining.

**Comment by elise-s** [comment]
So what does this mean for the future of mobile VR?

**Comment by AntheusS** [comment]
@dmarcos, I understand that testing the stereoscopic alignment for all devices is not managable, but does this mean that the stereoscopic view will disappear over time or will it simply not be supported anymore for certain devices? In that case, without a stereoscopic view, how will the user perceive depth without a seperate camera angle for each eye?

**Comment by dmarcos** [comment]
Yes, cardboard is considered legacy but kept around because some users are still getting value out of it in the current state. Mainly A-Frame workshops where a cardboard is distributed.

You are correct, eventually cardboard will go away. No timeline yet. Magic window mode will remain as the fallback for mobile devices.

**Comment by AntheusS** [comment]
@dmarcos So if cardboard goes away, and with it the stereoscopic view for mobile devices, what is the future of WebVR (and A-Frame)? Because to me it sounds like in that case there isn't really a use for it anymore.

**Comment by dmarcos** [comment]
@AntheusS Cardboard usage is already marginal. The industry has moved away from phone based VR (e.g: GearVR or Daydream were discontinued) 

Magic window, AR (phone and headset based), and VR on headsets (Quest, Vive, Index, Rift...) is where the user, developer base and growth is.

**Comment by msitarzewski** [comment]
@AntheusS The world of #WebXR extends far beyond mobile phones. #WebXR is built into browsers available to every headset. Cardboard was a grand, inexpensive headset experiment. It proved that there was a market if the process was simple. Arguably, Cardboard led to Go, and the rest is history. #WebXR (and A-Frame by extension) allow devs like you to build without the platform constraints of the major headset vendors. It's open, and great!

**Comment by AntheusS** [comment]
I guess that makes it indeed a worthy option. Thanks for the clarification fellas. 👍

**Comment by dmarcos** [comment]
I think there's nothing actionable on the A-Frame side. Closing this but can reopen if necessary. Thanks everybody for filing and participating.
