### ISSUE TITLE
A-Frame Inspector fails to load with version 1.1.0 of aframe

### ISSUE THREAD

**Issue by thomasschuiki** [aframevr/aframe#4739]
**Description:**

- A-Frame Version: A-Frame Version: 1.1.0 (Date 2020-12-03, Commit #8aefd214) 
- THREE Version (https://github.com/supermedium/three.js): ^0.123.1 
- WebVR Polyfill Version: ^0.10.12
- Platform / Device: Firefox Desktop, Chrome Desktop, Chrome Mobile (Android)
- Reproducible Code Snippet or URL: 

I remixed the basic scene from the docs and changed to the newest release of aframe:
https://hexagonal-evanescent-violin.glitch.me

Trying to start the inspector with "<ctrl> + <alt> + i" results in an error message. "Error loading inspector"
The browser reports the following:
```
GEThttps://unpkg.com/aframe-inspector@1.1.x/dist/aframe-inspector.min.js
[HTTP/2 404 Not Found 219ms]
```

So I guess the URL for requesting the inspector is wrong, since the newest release of the inspector is 0.6.0?

**Comment by dmarcos** [comment]
Thanks. It should work now. We were in the middle of releasing 😄
