### ISSUE TITLE
Error in Enter VR / Exit VR Events 

### ISSUE THREAD

**Issue by stefanhuber** [aframevr/aframe#4740]
**Description:**

Entering VR triggers an error in Firefox in the console (no Error visible in Chrome). However, only the Enter VR Event is triggered. The Exit VR Event is not triggered. The same code snippet works fine with version `1.0.4`.  

Firefox console output:
![grafik](https://user-images.githubusercontent.com/5379359/101266816-dbd5cd00-3752-11eb-8ccb-85aa9edd7672.png)

- A-Frame Version: 1.1.0
- Platform / Device: Windows 10, Firefox and Chrome
- Reproducible Code Snippet or URL: 

```html
<html>
    <head>
        <script src="https://aframe.io/releases/1.1.0/aframe.min.js"></script>
    </head>
    <body>
        <script>
            AFRAME.registerComponent('toggle', {
                schema: {                    
                },
                init: function() {
                    this.el.addEventListener('enter-vr', () => console.log("enter vr"));
                    this.el.addEventListener('exit-vr', () => console.log("exit vr"));
                }
            });
        </script>    

        <a-scene toggle>            
        </a-scene>
    </body>
</html>
```
The above snippet works with version `1.0.4`.

**Comment by dmarcos** [comment]
Thanks. This should be fixed in master now:

https://glitch.com/edit/#!/checkered-obvious-bison?path=index.html%3A7%3A127

**Comment by adamholdenyall** [comment]
FYI, if anyone winds up having to use AFrame 1.1.0 for compatibility reasons, etc, you can run this code to apply the change made by @dmarcos above.

```
//This is a monkey patch of commit ea3e6809279fdc25d5448f57b363ca5183008dd1 for AFrame 1.1.0 that ensures the exit-vr method is called
var oldEnterVr = AFRAME.AScene.prototype.enterVR;

AFRAME.AScene.prototype.enterVR = function (useAR) {
    let self = this;
    oldEnterVr.call(self, useAR);
    if (useAR) {
        self.addState('ar-mode');
    } else {
        self.addState('vr-mode');
    }
}
```

Not sure if there's a better way, and YMMV, but worked for my needs
