### ISSUE TITLE
Missing texture when using ambient light

### ISSUE THREAD

**Issue by jure** [aframevr/aframe#4741]
**Description:**

I'm testing a scene with some baked lighting (which, I've tried, does not seem to affect this issue) and have noticed that if I set the light to be an ambient light (that's how the scene was set up initially), the textures disappear. Specifically these are normal maps.

![Screenshot 2020-12-06 031653](https://user-images.githubusercontent.com/238667/101269729-23b81c80-3772-11eb-9053-d213a4909b25.png)
![Screenshot 2020-12-06 031754](https://user-images.githubusercontent.com/238667/101269730-2450b300-3772-11eb-8472-260d4f6faa10.png)

Setting the light to point works and the textures reappear.

- A-Frame Version:
1.1.0
- Platform / Device:
Windows 10

I've tried upgrading Three.js from super-three to the latest upstream Three, which works quite OK (only throws one error about  `renderer.xr.setPoseTarget`), but it didn't change or improve anything.

What could be the cause of this bug? I'd be happy to dig in given a bit of guidance!

**Comment by dmarcos** [comment]
FYI, A-Frame 1.1.0 is already using the latest THREE release r123. 

No idea what it might be happening without access to the model. What format is it?

**Comment by jure** [comment]
I've zipped it and uploaded it here:
[Cube.002.zip](https://github.com/aframevr/aframe/files/5648585/Cube.002.zip)

It's a glTF, exported from Blender. I've tried to preview it using https://gltf-viewer.donmccurdy.com/ and it displays fine.

Ah, regarding the Three.js version, I see where I went wrong. I went to the repo https://github.com/supermedium/three.js and the default branch `dev` is 5k commits behind upstream, so I assumed that that's the latest branch - I now see there are other very recent ones - nice!

**Comment by jure** [comment]
I think I understand what's going on. It's impossible for an ambient light to show my material, as my material is only a normal map, no other texture is applied. Can't show a normal map with a non-directional light, right?

Anyway, closing this as it's surely my error.
