### ISSUE TITLE
Embedded breaks the loading screen

### ISSUE THREAD

**Issue by praguevara** [aframevr/aframe#4744]
**Description:**

- A-Frame Version: 1.1.0
- Platform / Device: Web

Using `embedded` breaks the loading screen.

Without embedded:
![image](https://user-images.githubusercontent.com/50140021/101611998-7449a700-3a0a-11eb-962b-b96205ed5280.png)

With embedded:
![image](https://user-images.githubusercontent.com/50140021/101612164-a22eeb80-3a0a-11eb-9055-b5415d523263.png)

**Comment by dmarcos** [comment]
Link to reproduce? Keep in mind you have to [style `a-scene` and give it a size](https://aframe.io/docs/1.1.0/components/embedded.html#example) when embedded.

```
a-scene {
  height: 300px;
  width: 50%;
}
```

It works fine on my side.

**Comment by praguevara** [comment]
My bad, I was using a code example from ARJS without styling the a-scene.
