### ISSUE TITLE
Add support for Oculus Quest 2 controllers

### ISSUE THREAD

**Issue by majkrzak** [aframevr/aframe#4745]
As I see in the sources and docs, only Oculus Go and Touch controllers are currently sported. 

Due to the fact Oculus Quest 2 was recently released it will be good to add support for its controllers.

**Comment by majkrzak** [comment]
With some help and clues I can handle this issue, somehow at beginning of 2021.

**Comment by dmarcos** [comment]
Oculus Quest 2 controllers are already via the [oculus-touch-component](https://aframe.io/docs/1.1.0/components/oculus-touch-controls.html#sidebar) on A-Frame 1.1.0. Notice that Rift, Quest 1 and 2 are all called `Oculus Touch` and the component automatically selects the appropriate 3D model depending on the device. You can try in https://aframe.io/aframe/examples/test/laser-controls/

**Comment by majkrzak** [comment]
Ok, I see now
https://github.com/aframevr/aframe/blob/master/src/components/oculus-touch-controls.js#L70-L82

In docs, only https://cdn.aframe.io/controllers/oculus/oculus-touch-controller-left.obj is mentrioned
