### ISSUE TITLE
Cannot Enter VR mode on FireFox

### ISSUE THREAD

**Issue by sulaemansantoso** [aframevr/aframe#4750]
clicking the VR button does nothing only produces error on console

The optional feature 'bounded-floor' is not supported
Uncaught (in promise) Error: Failed to enter VR mode (`requestSession`) undefined

- A-Frame Version: 1.1.0
- Platform / Device: Windows/ FireFOx
- Reproducible Code Snippet or URL:

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Example</title>
    <script src="https://aframe.io/releases/1.1.0/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>
    <a-box
        color="green"
        position="0 1.5 -3"
      ></a-box>
    </a-scene>
  </body>
</html>`

**Comment by dmarcos** [comment]
What headset? What version of Firefox? What about A-Frame 1.0.4?

**Comment by sulaemansantoso** [comment]
i'm using the webxr plugins on my firefox browser 83.0. aframe 1.1.0 and 1.0.4 does the same thing. it does not do this yesterday. but it does today.

**Comment by dmarcos** [comment]
What headset? What do you mean by `webxr plugins`?

**Comment by sulaemansantoso** [comment]
Im not using a headset. if you use the webxr firefox plugins you can use a headset emulator inside firefox. usually when i press the VR button it willl show a stereoscopic view of my application and i can navigate using the webxr plugins  

![image](https://user-images.githubusercontent.com/32254285/102182224-803bda00-3ede-11eb-8142-a0e2acf014d3.png)

**Comment by dmarcos** [comment]
It works for me with [the hello world](https://glitch.com/edit/#!/aframe) and selecting HTC Vive.

I can see the error you mentioned when selecting `Samsung Galaxy S8 (AR)` and clicking enter VR. AR mode works correctly. Any other headsets also work as expected.

It seems an issue with the emulator. Gear VR is compatible with Samsung Galaxy S8 and VR mode should work.

I think there's nothing actionable on the A-Frame side. I recommend opening an issue on the [WebXR emulator repo](https://github.com/MozillaReality/WebXR-emulator-extension/issues) to address the bug there.

![Screen Recording 2020-12-14 at 11 41 59 12 PM](https://user-images.githubusercontent.com/39342/102185771-923a6000-3e7f-11eb-8f6d-6171e7d73791.gif)

**Comment by sulaemansantoso** [comment]
Thank you .. yes its true the emulator is not compatible
