### ISSUE TITLE
Raycaster documentation says intersected not intersection

### ISSUE THREAD

**Issue by levexis** [aframevr/aframe#4755]
I'm new to this, seems that there is an error in the raycaster docs from maybe an old version....

This works with 'raycaster-intersect**ion**' etc not 'ed'

   // Use events to figure out what raycaster is listening so we don't have to
    // hardcode the raycaster.
    this.el.addEventListener('raycaster-intersected', evt => {
      this.raycaster = evt.detail.el;
    });
    this.el.addEventListener('raycaster-intersected-cleared', evt => {
      this.raycaster = null;
    });
  },

**Comment by dmarcos** [comment]
What docs are misleading? Can you provide a link?

Do you have some code that illustrates the issue?

Notice that both events fire as stated in [docs](https://aframe.io/docs/1.1.0/components/raycaster.html#events_raycaster_intersected):

- `raycaster-intersected` fires on the entity that have been intersected by the raycaster
- 'raycaster-intersection` fires when the raycaster entity intersects another entity.

**Comment by levexis** [comment]
My bad, thanks for the explanation - I understand what the example means now. It might make it clearer for people just starting out if it said <a-box raycaster-listen></a-box>. I'd skimmed the docs and missed the switching of context, RTFM and all that :)
