### ISSUE TITLE
cursor does not update raycaster's origin and direction when dynamically updated from 'rayOrigin: mouse' to 'rayOrigin:entity'

### ISSUE THREAD

**Issue by kylebakerio** [aframevr/aframe#4759]
As I posted on slack:

> So, I've been trying to dynamically set my cursor's raycaster's origin from mouse to entity within my app. What I've noticed is that by doing so in this order, if I have touched the mouse, then my termination point (the spot that is 'clicked', the raycaster component's lineData.end is wherever my mouse was on screen as opposed to the expected behavior (and the behavior I get if I start with rayOrigin: entity without having rayOrigin: mouse first, or if I do it this way but don't touch the mouse before changing rayOrigin), where the termination of the line is directly the center of wherever I'm staring.
> I think this should be regarded as a bug, right? Probably the rayOrigin just wasn't quite designed to handle an update from mouse to entity correctly?
> Going to go look in source code and maybe attempt a pull request if I figure it out, but thought I'd ask here at the same time.
> 1 reply
> 
> kylebaker.io  29 minutes ago
> yeah, seems raycaster origin (which I'd already realized wasn't being set right and had been manually updated) as well as direction are both not being updated when the parent cursor's rayOrigin is updated. setting direction in-app with raycaster.data.direction.set(0,0,-1)  instantly fixes the issue.

- A-Frame Version: 1.1.0
- Platform / Device: desktop
- Reproducible Code Snippet or URL: 

```html
<a-entity
              id="cursor"
              cursor=" rayOrigin:mouse;"
              position="0 0 -0.1"
              raycaster="showLine: true; far: 2; interval:50; near: 0.03; objects: [gui-interactable], .raycastable;"
          >
```
```js
// later:
let cursor = document.querySelector("[cursor]")

 cursor.setAttribute('cursor',{
                fuse: true,
                rayOrigin: 'entity',
})
```

running this fixes the issue for me locally:

```js
       console.warn("PATCHING CURSOR")

       vrgc.getComponent('cursor').updateOriginAndDirection = function() {
            console.warn("called custom updateOriginAndDirection")
            vrgc.getComponent('raycaster').data.direction.set(0,0,-1)
            vrgc.getComponent('raycaster').data.origin.set(0,0,0)
        }

       vrgc.getComponent('cursor').update = function(oldData) {
            console.warn("called custom cursor update")
            if (this.data.rayOrigin !== oldData.rayOrigin) {
                if (this.data.rayOrigin === "entity") {
                    console.warn("SWITCH TO ENTITY FROM MOUSE DETECTED")
                    this.updateOriginAndDirection();
                }
                this.updateMouseEventListeners();
            }
       }
```

This was how I tested my concept, adding this issue to refer to in pull request.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/4760
