### ISSUE TITLE
a-text doesnt render when positioned behind camera

### ISSUE THREAD

**Issue by mmnoo** [aframevr/aframe#4764]
**Description:**

Simple `a-text` elements dont show when positioned behind the camera.

- A-Frame Version: 1.1.0
- Platform / Device: MacOS 10.15.7, Chrome 87.0.4280.88 & Samsung Galaxy S7 Chrome 87.0.4280.101
- Reproducible Code Snippet or URL:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Label position troubleshooting</title>
    <meta name="description" content="Hello, WebVR! • A-Frame" />
    <script src="https://aframe.io/releases/1.1.0/aframe.min.js"></script>
  </head>
  <body>
    <a-scene background="color: #333">
      <a-entity
        light="type:directional; castShadow:true;"
        position="-2 10 0"
      ></a-entity>
      <a-plane
        position="0 -2 -4"
        rotation="-90 0 0"
        width="4"
        height="4"
        color="#cccccc"
        shadow
      ></a-plane>

      <a-sphere position="0 1 -2" radius=".1" color="#EF2D5E" shadow></a-sphere>
      <a-text value="in front of camera" position=" 0 1.2 -2" color="#000" ></a-text>
      
      <a-sphere position="0 1 2" radius=".1" color="#EF2D5E" shadow></a-sphere>
     <!-- this text doesnt show -->
      <a-text value="behind camera" position=" 0 1.2 2" color="#000" ></a-text>
    </a-scene>
  </body>
</html>
```
https://glitch.com/edit/#!/sore-probable-sunscreen?path=index.html%3A8%3A9

**Comment by dmarcos** [comment]
That's expected. By default 3D elements are not rendered when the back face faces the camera. Rotate the the element 180 degrees:

https://glitch.com/edit/#!/broken-coordinated-farmer?path=index.html%3A28%3A75

Notice that even if you disable backface culling you still have to rotate 180 degrees or the text will be mirrored

**Comment by mmnoo** [comment]
Beautiful! Thank you @dmarcos.
