### ISSUE TITLE
Non-CORS request for the same origin

### ISSUE THREAD

**Issue by nfyfamr** [aframevr/aframe#4768]
I found that aframe set anonymous CORS setting for all requests not except for the same origin.
[https://github.com/aframevr/aframe/blob/dcf92c95e2bcf8af6a7a15336b0ab973b89e0494/src/systems/material.js#L12](https://github.com/aframevr/aframe/blob/dcf92c95e2bcf8af6a7a15336b0ab973b89e0494/src/systems/material.js#L12)

However, this makes a fatal error under specific conditions.
Condition 1: iOS safari
Condition 2: Content provider checks credentials for access control about resources

I built a server that gives an aframe scene and private resources. To get the resources, a user should log in with his/her id/pw and get a session cookie. When the aframe scene is loaded, aframe loads the private resources described in aframe tags (e.g. <a-box material="src: /myimage.jpg">). Because aframe send all requests with anonymous CORS (session cookie is omitted), my server rejects the request. However, this rejection flow only occurs on iOS safari, because other browsers (checked in mac chrome and mac safari) still contain the session cookie in the request even though anonymous CORS. I think there should be a routine to determine the resource URL is whether the same origin. It seems that this routine is in a-assets, but I need for inline version.

Here is the original posting: [https://stackoverflow.com/questions/65606873/how-can-i-load-image-texture-without-cors-request-when-requesting-same-domain-re](https://stackoverflow.com/questions/65606873/how-can-i-load-image-texture-without-cors-request-when-requesting-same-domain-re)

- A-Frame Version: v1.0.4
- Platform / Device: iOS safari
- Reproducible Code Snippet or URL: 

I asked about this issue at slack and stackoverflow, but nobody suggested any reasonable answer to me.
So, I made this issue.

**Comment by dmarcos** [comment]
This looks like a server configuration issue?

**Comment by nfyfamr** [comment]
I resolve this issue after updating the iOS version. The issue occurred on iOS 13.0. After updating to iOS 14.3 (2021.01.18), this bug disappeared. The older iOS Safari seems to work weirdly about the `crossOrigin` attribute. I tested the following sample code on iOS Safari and Mac Safari:
```
// Case 1. request an asset in the same origin.
var img = document.createElement('img')
img.crossOrigin = true
img.src = '/assets/a/powder_annot1'

// Case 2. request an asset in other origin.
var img = document.createElement('img')
img.crossOrigin = true
img.src = 'https://i.imgur.com/1jMhs8F.jpg'
```
I could fetch the images in both cases 1 and 2 on Mac Safari. I could get the image of case 1 on iOS (13.0) Safari, but could not get the image of case 2. This says other browsers attach credentials (e.g., cookie) if the request is for same origin even though `crossOrigin` attribute is set as `anonymous`. But iOS Safari did not. However, after updating to iOS 14.3, the iOS Safari also does.

**Comment by dmarcos** [comment]
Thanks for info. Much appreciated.
