### ISSUE TITLE
<a-video> autoplay not works in chrome but Microsoft edge

### ISSUE THREAD

**Issue by ryanaltair** [aframevr/aframe#4772]
**Description:**
`<a-video src="abc.mp4">`  never autoplay in Chrome like [doc](https://aframe.io/docs/1.1.0/components/material.html#video-textures) said, but autoplay well in edge.
- A-Frame Version: 1.1.0
- Platform / Device:MacOS Big Sur in MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
- Reproducible Code Snippet or URL:
https://video-el-autoplay.glitch.me/ open in Microsoft Edge 87(chrounium based) and chrome 87

**Comment by martinhilary** [comment]
The autoplay works on both Microsoft Edge and Firefox but seems to bug out in Chrome. It is not able to render the video size in the function before the video plays. You could try declaring the video as an asset first before calling out its ID like in the docs as a temporary fix.  

 <a-assets>
    
    <video id="cubes" src="video.mp4" autoplay="true">
  </a-assets>

  <a-entity geometry="primitive: box" material="src: #cubes"></a-entity>

**Comment by dmarcos** [comment]
Different browsers might have different [video autoplay policies](https://faq.dailymotion.com/hc/en-us/articles/360025306594-Autoplay-and-Browser-Policies). [A button that the user clicks to start playing the video](https://aframe.io/aframe/examples/test/video/) will give the best compatibility across all browsers and policies. Code available in the [examples](https://github.com/aframevr/aframe/blob/master/examples/test/video/index.html#L8). Look at the [play-on-click component](https://github.com/aframevr/aframe/blob/master/examples/js/play-on-click.js) in particular

[I added some notes to the docs](https://github.com/aframevr/aframe/commit/ce93cfd75cfb5d2b24d5d16b2038d9467b8e939e)

**Comment by ryanaltair** [comment]
hi guys,
here is another workaround for me.
i modify the material component, 
add muted to the video element and add a listen to play the video,
see [here](https://github.com/xuelang-group/aframe/commit/8209f60360049c9f11b6a3aad78492b89c0b6111#diff-bce32be0cd45d6f30d1449a38ec4a7353e7f4dc38db2f432774714331c737e77)

seems work on both safari and chrome.
[this hacked one](https://video-el-autoplay.glitch.me/index_new.html) works.

happy to make a pr.
