### ISSUE TITLE
Add Support For Variance Shadow Map

### ISSUE THREAD

**Issue by Dante83** [aframevr/aframe#4776]
**Description:**

- A-Frame Version: Future
- Platform / Device: All
- Reproducible Code Snippet or URL: `<a-scene shadow="type: vsm"></a-scene>`

THREE.js now supports variance shadow maps, as per: https://threejs.org/docs/#api/en/renderers/WebGLRenderer.shadowMap

The constant for it being, THREE.VSMShadowMap

They create very beautiful shadows, but are sadly missing from A-Frame, which only supports basic, pcf and pcf soft shadows. Adding this in appears trivial, although they might require different initial bias choices to avoid shadow acne and other artifacts. I noticed they were missing while trying to integrate them in project as an option, only to find that it disables my ability to hide mesh from casting shadows in the shadow frustum. All the same as the appropriate way to set the shadow map in A-Frame is through the shadow attribute property, type.

**Comment by dmarcos** [comment]
Can probably implemented as a 3rd party component first. We haven't seen a lot of demand for this. I'm closing this but can reopen if necessary.
