### ISSUE TITLE
Uncaught Error: A a-node type is already registered    

### ISSUE THREAD

**Issue by uurcank** [aframevr/aframe#4777]
**Description:**

- A-Frame Version: Master
- Platform / Device: Chrome, Windows 10
 
 `aframe-master.js:2575 Uncaught Error: A a-node type is already registered
    at mt (aframe-master.js:2575)`

What would be the reason for this error?

**Comment by dmarcos** [comment]
Link to reproduce? It looks you're importing A-Frame twice in your code.

Closing. We can reopen if necessary.
