### ISSUE TITLE
adding a camera exits from inspector view

### ISSUE THREAD

**Issue by uurcank** [aframevr/aframe#4778]
**Description:**

- A-Frame Version: 1.1.0
- Platform / Device: Chrome 81+
- Reproducible Code Snippet or URL: https://aframe.io/aframe/examples/showcase/anime-UI/

To reproduce:

1. open inspector
2. remove camera
3. add a new camera

Cursor no longer works in inspector view. 

what would be the way to prevent this happening?

**Comment by dmarcos** [comment]
Two problems:

- The inspector should not let remove the last camera.
- Inspector should not switch to the camera that it's added.

The fix should be handled on the inspector repo https://github.com/aframevr/aframe-inspector
