### ISSUE TITLE
Problems with gltf textures

### ISSUE THREAD

**Issue by ericdacal** [aframevr/aframe#4780]
- **A-Frame Version:**: 1.0.4
- **Platform / Device**: PC

I am trying to create a scene with a particular glb model. I am having problems with some textures in the glb model. I have tried different light settings but the metal texture of the kitchen does not look right. I have tried with the same model with gtlf Viewer which also uses three.js. You can see the difference clearly.
**Aframe**
![aframe](https://user-images.githubusercontent.com/16444893/105990463-cc179c80-60a2-11eb-8b12-eae0eea8a8c0.png)
**Gltf Viewer**
![gltf-viewer](https://user-images.githubusercontent.com/16444893/105990477-d043ba00-60a2-11eb-8ff1-1ad4395c0f7c.png)

Thanks

**Comment by dmarcos** [comment]
Try `<a-scene renderer="colorManagement: true;">`

**Comment by ericdacal** [comment]
I probe with ```html <a-scene renderer="colorManagement: true;">```

**Comment by dmarcos** [comment]
Can you share a glitch with code and model? 
https://glitch.com/~aframe

**Comment by ericdacal** [comment]
Sure.
### Live site: https://aframe-3d-model-loader.glitch.me
### Code: https://glitch.com/edit/#!/aframe-3d-model-loader

**Comment by dmarcos** [comment]
Textures are fine I think. 

The gltf-viewer adds an environment map by default while A-Frame doesn't. You could add one but reconsider if your model actually needs one.

Also you need some lights inside the room:

https://glitch.com/edit/#!/iodized-juniper-hip?path=index.html%3A16%3A56

If you disable the environment map in the gltf-viewer the result is close.

**Comment by dmarcos** [comment]
I'm closing this because I think there's no action on the A-Frame side. We can reopen if necessary

**Comment by TheRealDigitalMaster** [comment]
My gltf models don't show up after downloading from sketchfab.com?

**Comment by dmarcos** [comment]
@TheRealDigitalMaster I recommend sharing code with https://glitch.com/~aframe or it will be hard to help. I encourage you to join the [discord](https://aframe.io/community/). Great people there to help. We use github issues for bug reports and feature requests. Best of luck
