### ISSUE TITLE
raycaster intersect invisible object

### ISSUE THREAD

**Issue by ryanaltair** [aframevr/aframe#4781]
**Description:**
due to [this](https://github.com/mrdoob/three.js/pull/18694)
raycaster now intersect invisible object
- A-Frame Version: 1.1.0
- Platform / Device:
- Reproducible Code Snippet or URL:

maybe we need to add  a layer enabled when [refreshObjects](https://github.com/aframevr/aframe/blob/438812c41acfb3393d27d7fac6f313ba6cd316cb/src/components/raycaster.js#L174)

**Comment by dmarcos** [comment]
Raycaster has always intersected invisible objects as far as I know (It's for example useful to create targets larger than the visible objects for better usability) . Not sure how the reference PR is relevant. Can you elaborate?

**Comment by ryanaltair** [comment]
hi @dmarcos , Before this [PR](https://github.com/mrdoob/three.js/pull/18694) , 

raycaster will ignore those object that non-visible, 

after this merge, 

raycaster will shoot object, (visible and non-visible).      


In my scenario, 

I add a `<a-entity raycaster="objects:[select]" />` ,

and add `select` attribute to those entities need raycaster.

And these will result in that even object is not visible, it could still be a raycaster target.

So I advise could we add a script before every shoot, 

that enable visible object layer 31
and disable  non-visible obejct layer 31

here is a [exmaple](https://github.com/xuelang-group/aframe/blob/e727bfa9949315645ecdc4363a0f1710bdf5418a/src/components/raycaster.js#L238-L247).

**Comment by dmarcos** [comment]
What is the use case? Any simple example you can provide illustrating the behavior you get vs. what you expect?

**Comment by ryanaltair** [comment]
I am building a scene editor(like aframe-inspector) but more rely on the scene xml data.

In my scenario, toggle the entity to non-visible, `raycaster`  component will still trigger the `raycaster-intersected` event on those non-visible entity. That is more strange when a big non-visible box contain a small visible box. 
Here is a [minimal live demo](url).
Current behavior: 
click on the red( the part in big box) still intersect to the hidden big box.
Expect behavior:
click on the red( the part in big box) intersect to the smaller red box in the hidden big box.

In further, I know that that's the great trick to make a non-visible bounding box contain a small complex 3d object to trigger raycaster, to get a higher performance, but that's not I expect. I just want to click the visible objects.

If possible, I won't turn to a gpu picker like this (https://threejs.org/examples/?q=raycast#webgl_interactive_cubes_gpu).

**Comment by dmarcos** [comment]
Can you provide a simple example of previous behavior where invisible entities where ignored by the raycaster? I think invisible entities have been always raycasted. Not sure how the referenced PR is relevant in this context. 

When setting an entity as invisible you can always for instance add / remove a class and [call refreshObjects](https://aframe.io/docs/1.1.0/components/raycaster.html#properties_objects)

**Comment by ryanaltair** [comment]
> Can you provide a simple example of previous behavior where invisible entities where ignored by the raycaster? I think invisible entities have been always raycasted. Not sure how the referenced PR is relevant in this context.
> 
> When setting an entity as invisible you can always for instance add / remove a class and [call refreshObjects](https://aframe.io/docs/1.1.0/components/raycaster.html#properties_objects)

You are right. Raycaster always raycast both invisible and visible objects.
> Exactly, after the referenced PR, Raycaster always raycast both invisible and visible objects. Detail is [here](https://github.com/mrdoob/three.js/wiki/Migration-Guide#r113--r114)

Seem like the gpu color picker is the only way to solve my problem.

**Comment by dmarcos** [comment]
I think you can still achieve what you want with the current API. Add / Remove a class to the entities you want raycasted / ignored.

Example: https://glitch.com/edit/#!/fierce-righteous-red?path=hide-on-click.js%3A14%3A28

Clicking on the sphere will set the sphere visible to `false` and the `interactable` class removed. It won't longer be raycasted.

**Comment by dmarcos** [comment]
I don't think there's anything actionable on the A-Frame side. We can reopen if necessary. Best of luck
