### ISSUE TITLE
Does  A-Frame work in Chrome 88

### ISSUE THREAD

**Issue by archgary** [aframevr/aframe#4783]
**Description:**

- A-Frame Version: 1.1.0
- Platform / Device: Chrome&Firefox / PC with HTC Vive
- Reproducible Code Snippet or URL:

I've been using A-Frame in FireFox(85.0) for a while, and it still works now. 
And I've update my Google Chrome to 88.0.4324. In that case, the THREE.JS part of the VR does work. But I cannot get my VR projects work (like Glitch) in Chrome and even I cannot run the aframe.io examples within VR. 

I know that I can switch back to FireFox to run the A-frame with Glitch, and go to Chrome for THREE.js VR in Chrome. I just wonder would it be possible to make both of them working in one browser. 

The basic problem I think is coming from the WebXR. 
Does anyone can give me a hint here?

Thank you for the answer in advance and appreciate it. 

Have a good one.

Best,
Gary

**Comment by dmarcos** [comment]
Can you try with A-Frame master? This is a glitch using the [latest master build](https://cdn.jsdelivr.net/gh/aframevr/aframe@bd271e7ee21e5407c2a732813d0488b7bfd8da3d/dist/aframe-master.min.js): https://glitch.com/edit/#!/scarce-brick-sock?path=index.html%3A7%3A127

**Comment by archgary** [comment]
Great! That does work!

So how would I be able to get the latest CDN of A-Frame?

I mean this:
<script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@bd271e7ee21e5407c2a732813d0488b7bfd8da3d/dist/aframe-master.min.js"></script>

Or where can I keep on track of the update? 
(I tried to go back here: https://aframe.io/examples/showcase/helloworld/, but it is not working.) 

Thanks for your answer and update. 
Appreciate it!

Best,
Gary

**Comment by dmarcos** [comment]
You can look at the commit messages for the latest builds:

https://github.com/aframevr/aframe/commits/master

**Comment by dmarcos** [comment]
This should be fixed in master now. Closing. We can reopen if necessary
