### ISSUE TITLE
[Feature Request] Make opacity work on 3D models, not just primitives

### ISSUE THREAD

**Issue by marcusx2** [aframevr/aframe#4785]
[This](https://stackoverflow.com/questions/49435707/how-to-add-fade-transitions-to-entities-in-aframe) doesn't work on a gltf model. I needed to do what's described on this [SO post](https://stackoverflow.com/questions/43914818/alpha-animation-in-aframe-for-a-object-model) to get it working. It would be nice if I could easily change the color/opacity of a 3D model without having to register a component. Fading 3D models is a common task.

**Comment by dmarcos** [comment]
A generic way to make opacity work out of the box for all models might not be tractable. Keep in mind that models can be composed of multiple different arbitrary materials and it's hard to anticipate and always do the right thing.

**Comment by marcusx2** [comment]
I know it's possible because there's a tool that does it, called ZapWorks Studio. Any model that you import in the tool, no matter how many materials, can change opacity.

**Comment by marcusx2** [comment]
@dmarcos And like on my mask request, fading in and out 3D models is also a frequently used effect on AR and VR experiences. It would be nice to have this feature out of the box. I am surprised it's not ;_;.

**Comment by dmarcos** [comment]
Transparency is a large topic in 3D. Not sure we can handle it in a generic way. Not familiar with ZapWorks but probably the tool introduce some constraints to make the problem tractable. Closing this and can reopen if necessary
