### ISSUE TITLE
[Feature Request] Mask component

### ISSUE THREAD

**Issue by marcusx2** [aframevr/aframe#4786]
It's a very common task on AR to have an object masking another. That is, an object that is invisible, yet blocks the visibility of others behind it as if it was visible. See [https://stackoverflow.com/questions/56192021/how-to-declare-a-mask-material-using-a-frame-js](https://stackoverflow.com/questions/56192021/how-to-declare-a-mask-material-using-a-frame-js). It would be nice if there was an official mask component, and it worked on 3D models in addition to primitives.

**Comment by dmarcos** [comment]
This looks too specific to be part of A-Frame core and would be more appropriate as a 3rd party component.

**Comment by dmarcos** [comment]
I don't think there's anything actionable on the A-Frame side. Closing this. We can reopen if necessary.

**Comment by marcusx2** [comment]
@dmarcos I don't see how this is too specific when it's so frequently used on many types of AR and VR experiences. But oh well.

**Comment by dmarcos** [comment]
Can you be more specific on what you mean by mask and what you're trying to achieve?

**Comment by marcusx2** [comment]
@dmarcos When you have an object that is invisible, but still ocludes what's behind it. It's used a lot for portal effects, where you have a plane with a hole in the middle as a window to another world.

[https://docs.zap.works/studio/advanced/masking-objects/](https://docs.zap.works/studio/advanced/masking-objects/)
[https://www.youtube.com/watch?v=371ZQW_Yzck](https://www.youtube.com/watch?v=371ZQW_Yzck)

I already figured it out how to do it with the help of the [SO post
](https://stackoverflow.com/questions/56192021/how-to-declare-a-mask-material-using-a-frame-js), but I think there should be an out of the box solution for this.

**Comment by dmarcos** [comment]
A-Frame core provides the minimal functionality to get devs started and relies on the component ecosystem for more advanced functionality.

Consider sharing your portal component with the community and on npm. It will make many devs super happy. Best of luck.
