### ISSUE TITLE
stereocubemap display renders empty scene when upgraded to v1.1.0 from v0.7.0 

### ISSUE THREAD

**Issue by Jogii** [aframevr/aframe#4787]
I have a project where i render stereocubemaps(12x1) using aframe v0.7.0. when i upgraded the aframe version to v1.1.0 the project does not work as expected, it displays a empty scene. I am running the same using **https** also **webXr flags** are enabled in chrome browser. Kindly have a look at the project and suggest.

Github repo:-
https://github.com/Jogii/stereocubemaps_VR/blob/master/final.html

- A-Frame Version: 1.1.0
- Platform / Device: Chrome browser
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
I'm not familiar with the stereocube.js code base. I recommend contacting the maintainers.

**Comment by Jogii** [comment]
@dmarcos i see aframe has a layer component that renders stereocubemaps,recently i also tried the same it didnt work for me. Do we have a reference example for the same?

**Comment by dmarcos** [comment]
The [WebXR layers API](https://immersive-web.github.io/layers/) is still experimental and only available in the Oculus Browser on Quest headsets and disabled by default (requires enabling via chrome://flags). [Demo](https://diegomarcos.com/render-the-metaverse/) and [code](https://github.com/dmarcos/render-the-metaverse)

**Comment by dmarcos** [comment]
I don't think there's anything actionable on the A-Frame. We can reopen if necessary
