### ISSUE TITLE
Animation "from" is not the initial value

### ISSUE THREAD

**Issue by Turtleted21** [aframevr/aframe#4788]
Hi, why with :
```
function myfunction() {
  setAttribute("animation", { property: "scale", from: "0 0 0", to: "1 1 1", dur: "500" });
}
```
animation scale only works once
animation scale don't go back to 0 the second time function is read, it stay at 1.

to work i must do :
```
function myfunction() {
// init scale to 0
  setAttribute("animation", { property: "scale", to: "0 0 0" });
// then start from 0 to 1
  setAttribute("animation", { property: "scale", from: "0 0 0", to: "1 1 1", dur: "500" });
}
```
Is this normal? it's a issue or my code?
aframe doc say "from" is the initial value, so why i need go back to 0 before play from 0 ?

 you can try my demo, do a mouseEnter on the gem, on the second mouseEnter animation not restart.
https://glitch.com/edit/#!/cloudy-shining-nose

Thanks

- A-Frame Version: 1.1.0
- Platform / Device: PC
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/cloudy-shining-nose

**Comment by dmarcos** [comment]
Use events to trigger the animation:

`animation="startEvents: mouseenter; property: scale; from: 0.5 0.5 0.5; to: 3 3 3;dur: 500"`

https://glitch.com/edit/#!/succinct-uncovered-camel?path=index.html%3A63%3A0
