### ISSUE TITLE
[Feature Request] Relativity Component

### ISSUE THREAD

**Issue by marcusx2** [aframevr/aframe#4790]
On A-Frame an entity is relative to its parent. If you move the parent entity, the child moves as well. That's great. But I think it would be great if there was a way to specify an entity to be relative to another entity, that is not necessarily its parent. Even to be relative to the screen. Here's a code snippet to show what I mean:

```
<a-entity id="entity1" position="0 0 0">
	<a-entity id="entity2" relative = ""></a-entity> <!-- "" or "#entity1" would make it relative to "entity1". This is the way it already works, so the relative component would have "" as the default value -->
	<a-entity id="entity3" relative = "#entity4"></a-entity> <!-- This makes "entity3" relative to "entity4", not "entity1" -->
	<a-entity id="entity5" relative = "#entity1 #entity4" relativeWeight = "0.5 0.5"></a-entity> <!-- This makes "entity5" half influenced by "entity1" and half by "entity4". But it could have other values like "0.8 0.2" or "1 0"(80% affected by entity1 and 20% by entity 4, then 100% affected by entity1 and 0% by entity4) -->
</a-entity>

<a-entity id="entity4" position="0 1 0">
</a-entity>

<a-entity id="entity6" relative="Screen"> <!-- I was thinking of some special values, like "Screen", "TopScreen", "BottomScreen", to make elements be relative to the center of the screen, top, bottom, etc.  -->
</a-entity>

<a-entity id="entity7" relative="#entity5"> <!-- This entity is relative to entity5, which in turn is relative to both entity1 and entity4. In practice, this makes entity7 be indirectly affected by entity1 and entity4 as well because of entity5. -->
</a-entity>
```

Of course, you would then be able to animate the relativeWeight component to smoothly transition an entity's relativity to another entity.

**Comment by dmarcos** [comment]
I recommend checking out the [layout-component](https://www.npmjs.com/package/aframe-layout-component)

**Comment by marcusx2** [comment]
@dmarcos This is not what my request is at all. It is more akin to [Unity Constraints](https://docs.unity3d.com/Manual/Constraints.html). But the relativity would affect position, rotation, and scale at the same time, like it already works for an entity that is a child of another.

**Comment by dmarcos** [comment]
@marcusx2 A-Frame is a community effort. I recommend joining the [Slack and Discord channels](https://aframe.io/community/) and engage with other A-Framers. Super nice folks there to ask questions and share your needs. There might be existing components with the same or similar functionality you need. if something you think is not covered is a also great opportunity to participate. The community will appreciate.

Your suggestions are great. Just A-Frame core only delivers the basics to get your application started. It's deliberately kept small to keep the code quality high and distribute the maintenance burden. We rely on the component community to supply more advanced features. A nice tip is to search for `a-frame` on [npm](https://www.npmjs.com/). Thanks for understanding.

Looking forward to seeing what you make.

**Comment by marcusx2** [comment]
ZapWorks Studio has this as well: https://docs.zap.works/studio/scripting/reference/node/functions/relativeto-setter/ and https://docs.zap.works/studio/scripting/reference/node/functions/relativetoprop-setter/ . It's an extremely useful feature I think.

An example usage of this, is having an UI that is relative to the tracking in an augmented reality experience, but if the user moves away from the tracking, the UI goes to the screen. The "relativeWeight" component could be animatable to make a smooth transition.

**Comment by marcusx2** [comment]
Potentially useful links:
http://learnwebgl.brown37.net/08_projections/projections_perspective.html
https://threejs.org/docs/#api/en/cameras/PerspectiveCamera
https://www.evermade.fi/story/pure-three-js-hud/

**Comment by diarmidmackenzie** [comment]
This component is available to solve this problem:
https://github.com/diarmidmackenzie/screen-display#blend-transforms
