### ISSUE TITLE
Camera zoom change has no effect iOS 14.4

### ISSUE THREAD

**Issue by Kershawj** [aframevr/aframe#4791]
Changing camera zoom level has no effect on this particular combination of iOS 14.4 on iPhone 7 using A-Frame version 1.2.0
Zoom change can be seen to work on Android Chrome and Desktop Chrome along with other combinations.
Suspect the ever changing, never following standards Safari browser on 14.4. Have not got enough devices and OS combinations to prove.

- A-Frame Version: 1.2.0
- Platform / Device: iOS / iPhone 7
- Reproducible Code Snippet or URL:

Any scene and using this:
`<a-entity id='scenecam' camera="zoom: 1" position="0 1.6 0" wasd-controls-enabled="false" look-controls="enabled: true;">`
Changing to:
`<a-entity id='scenecam' camera="zoom: 3" position="0 1.6 0" wasd-controls-enabled="false" look-controls="enabled: true;">`
For example, no effect seen in the combo given above, but can be seen on desktop and Android devices.

**Comment by dmarcos** [comment]
Zoom works for me on iOS:

https://glitch.com/edit/#!/valley-handy-dryer?path=index.html%3A31%3A31

**Comment by Kershawj** [comment]
I use A-frame ALL the time and can't tell you how much I appreciate all the work you have put in so last thing I want to do is waste your time.
Your right with a basic scene set up it does work and did for me, so had to start stripping back the current project which is displaying this problem to get a handle on it, and should have done this work before logging it really. Sorry about that.
It seems the problem is when I'm defining a video asset, so like
`<video id="channel1" src="./videos/channel1.mp4"></video>`
or `<video id="channel1" src="./videos/channel1.mp4" autoplay="false" webkit-playsinline muted></video>` as I do to try cover iOS stuff.
But either of these seems to stop the zoom on the camera from taking affect.
So I started suspecting the video file as the issue, so downloaded the one used in the example: https://aframe.io/aframe/examples/boilerplate/360-video/
And in my code defined it in exactly the same way
`<video id="video" autoplay loop crossorigin="anonymous" playsinline webkit-playsinline src="https://bitmovin.com/player-content/playhouse-vr/progressive.mp4"></video>`
And including this or not toggles the zoom working on the camera. Or at least it does for me!

**Comment by Kershawj** [comment]
@dmarcos  - Any update on this. Just really looking to know you are aware of the issue as now I know it's there it's easy enough to work around.

**Comment by Kershawj** [comment]
@dmarcos Another update on this and finding out more as I go along on this one.
So, on iOS 14.4 and using Aframe 1.2.0 including a video as described in the a-assets section not only causes zoom to stop working but it would seem also makes the camera ignore any change in its position.
However all these problems go away if you move the definition of the camera and any entity wrapper around it to above the assets section makes it all work again.
No idea why, just so you are aware really.

**Comment by dmarcos** [comment]
In order to move the camera a camera rig / wrapper is the recommended way as [stated in docs](https://aframe.io/docs/1.2.0/components/camera.html#examples)

As mentioned above zoom works for me in the [example shared above](https://github.com/aframevr/aframe/issues/4791#issuecomment-777931608)

If recommend providing a working example with [glitch](https://glitch.com/~aframe) that reproduces the bug if this is still an issue that needs investigation.
