### ISSUE TITLE
Rendering engine dependency injection

### ISSUE THREAD

**Issue by LukeTOBrien** [aframevr/aframe#4799]
Hello there,

This is more of a discussion rather than an 'issue'.

For awhile now I have been wondering if it might be possible to abstract the 3D library to allow for injection of a rendering engine of choice – Aka [Dependency inversion principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle).  
At the moment, A-Frame is dependent on ThreeJs, but what if a developer wanted to use [BabylonJs ](https://www.babylonjs.com/) or in the not too distant future someone created a Wasm 3D library?

I think this is an important thing to consider as Babylon is supported by Microsoft, so it is very professional looking and I have come across a few companies who are developing Wasm 3D libraries (they have existing C# or C++ libraries which they are looking to port).  
If A-Frame supported Dependency Injection then the community would expand.

I must also add that even though ThreeJs is great, I would like to use Babylon for commercial projects.

**Comment by dmarcos** [comment]
A-Frame relies on the community and interoperability of the components. While I see the potential benefits, making the engine swapable would also fragment the ecosystem. There are no plans at the moment to support other engines.

**Comment by dmarcos** [comment]
Closing this. There are no plans for now to make A-Frame engine swappable.
