### ISSUE TITLE
a-video: first frame is blacked when using partial content

### ISSUE THREAD

**Issue by PaulCombal** [aframevr/aframe#4800]
**Description:**

- A-Frame Version: 1.2.0
- Platform / Device: Chrome, PC
- Reproducible Code Snippet or URL: N/A

Hello,

I'm hosting a small AFrame app on Azure Blob storage. Everything works fine, except that the first frames of videos are black. 
This matters to me because I have videos on my scene with autoplay turned off.
I do not have this issue on my local web server. The only difference I could find between the two scenarii is that Blob storage serves the video with partial content (HTTP 206) at first.

When this glitch happens, the console is populated with `WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty`.

I use this workaround for now: `document.querySelectorAll('video').forEach(e => {e.play(); e.pause()})`.

Thank you

**Comment by dmarcos** [comment]
Different browser policies when serving from `localhost` perhaps?

**Comment by PaulCombal** [comment]
Any way I could test that out for myself and confirm this? I'm using stock Chrome on Windows (not a company PC with GPOs)

**Comment by dmarcos** [comment]
You mention it works in your `localhost://` but not remotely? Browser policies concerning WebXR / secure origins / autoplay sometimes don’t apply to `localhost`. Not sure if it’s your case

**Comment by dmarcos** [comment]
Do the video example works for you?

https://aframe.io/aframe/examples/test/video/

https://github.com/aframevr/aframe/blob/master/examples/test/video/index.html

**Comment by dmarcos** [comment]
Does it happen in any other browser than Chrome?

**Comment by PaulCombal** [comment]
I will be away for a month, sorry if I'm not active. I'll do further tests on different browsers, and provide a demo as soon as I get back. In the meantime can you please let the issue open?

Regarding the policies, there are no errors that are specific to the hosted version. When checking the Chrome network tab, every request succeeds for both hosted and local versions (no CORS issue). This could have something to do with autoplay on localhost, I'll investigate about it.

Thank you again for the support

**Comment by PaulCombal** [comment]
Hi again, your example does work, but the screen is black for a second or so before it loads. Anyway, I figured this might as well be related to slow internet in my case. 

Is there any way to force the preloading of assets before going through with the app? It doesn't matter if this implies a long initial loading time in my case. I've found a third-party repo which seems to do this but it's cumbersome and not maintained anymore.

**Comment by dmarcos** [comment]
@PaulCombal Is this still an issue? If you can provide a link to an example to reproduce we can look into it. Thanks!

**Comment by PaulCombal** [comment]
I'm really sorry I forgot to update you on this.. The project is finished now and I remember the issue "fixing itself", it might have been something to do with the proxy configuration or a chrome update; I just reloaded the project and the issue doesn't show in production. In the end the issue might have been on the development environment.

In any way I want to thank you for your amazing project and amazing support ❤️

Again sorry for not giving a follow-up, and have a wonderful day!

Feel free to close the issue at any time

**Comment by dmarcos** [comment]
Thanks so much. Glad to know you shipped the project successfully. Have a great day!
