### ISSUE TITLE
dracoDecoderPath is not getting defined in gltf registerSystem in React js

### ISSUE THREAD

**Issue by Karthikdb** [aframevr/aframe#4801]
I am working with A-frame + reactjs and
I am defining the path of dracoDecoderPath in a-scene but in the registersystem, the path is taken as Default.
How can I resolve this issue?? 

- A-Frame Version: 1.2.0
- Platform / Device: Web / PC and phone
- Reproducible Code Snippet or URL: 

`<a-scene shadow="type:pcfsoft"
                gltf-model="dracoDecoderPath: https://xyz.in/draco/"
                loading-screen="enabled:false"
                vr-mode-ui="enabled: false"
                renderer="colorManagement:true;
                  sortObjects: true;
                  physicallyCorrectLights: true;
                   maxCanvasWidth: 1920;
                   maxCanvasHeight: 1920;"
                fog="type: linear; color: #e5eeff; far: 350; near: 0;density:1"
                physics="debug: true"
            ></a-scene>`

**Comment by dmarcos** [comment]
Does it happen without react? Any link with simple code to reproduce?

**Comment by Karthikdb** [comment]
It is working properly in HTML but in react I am getting this issue .

**Comment by dmarcos** [comment]
It looks more of an issue with react than A-Frame. I'm not a react expert. If you share code that people can run it will be easier for people to help. Glitch is a great option https://glitch.com/~aframe

**Comment by dmarcos** [comment]
I see you opened a question on StackOverlow. That's a better avenue to get help with usage questions. Share a link to your sample code over there. Thanks!
