### ISSUE TITLE
aframe not rendering lottie json texture mapped to canvas, works in three.js

### ISSUE THREAD

**Issue by crayscrays** [aframevr/aframe#4805]
**Description:**

- A-Frame Version: 1.2.0
- Platform / Device: javascript, normal html browser
- Reproducible Code Snippet or URL:
1) unable to render in aframe (https://glitch.com/edit/#!/sun-innate-cupboard)
2) able to render in three.js (https://jsfiddle.net/crays/15cgbvsp)

Hi aframe, so basically i tried to reproduce the three.js canvas map of lottie.json into aframe but funny is that it never actually render, but the devtool mention that it does

**Comment by dmarcos** [comment]
We use github issues for bug reports and feature requests. I see you opened a [question on StackOverflow](https://stackoverflow.com/questions/66311314/aframe-not-rendering-lottie-json-texture-mapped-to-canvas-but-works-in-three-js) and it's being addressed there. Best of luck.

**Comment by mattrossman** [comment]
@dmarcos Just to clarify, [the latest documentation](https://aframe.io/docs/1.2.0/components/material.html#canvas-textures) states:

> The texture will automatically refresh itself as the canvas changes.

Wouldn't that make this a bug? The solution from StackOverflow is to manually refresh the texture while the docs say this should be automatic.
