### ISSUE TITLE
Aframe 360 video

### ISSUE THREAD

**Issue by eliaskh** [aframevr/aframe#4807]
Hello, i want to ask... is aframe working on ios? i test all the showcases no one work on my iPhone, i have 2 iPhone iPhone x and an iPhone 12 pro max... no showcase work on safari.
on vr mode , the gyroscope networking, and the top bar of the browser is still visible on vr mode .
can anyone help me ?

**Comment by dmarcos** [comment]
Unfortunately, Safari for iOS only allows fullscreen mode if a site is launched from the home screen. User must click on “Add to Home Screen”. What do you mean by gyroscope networking?

**Comment by dmarcos** [comment]
Make sure you are testing with A-Frame examples: https://aframe.io/aframe/examples/

**Comment by eliaskh** [comment]
Hello, yes i am testing those examples ... 
is Aframe compatible with react native?

**Comment by dmarcos** [comment]
@eliaskh What is not working with the examples apart from fullscreen? What did you mean by `gyroscope networking`? Magic window mode works or me on iPhone X if that's what you meant.

I have no experience with React Native. If DeviceMotion on iOS and a WebXR implementation on Android are available A-Frame should work as far as I know.

**Comment by eliaskh** [comment]
Hello.
where i can provide you video to understand?
when you say frame working on react native, you mean like web view ?

**Comment by dmarcos** [comment]
Record a video, upload it somewhere and paste the link here.

As I understand react native uses a WebView underneath. That WebView needs to have the DeviceMotion and/or WebXR APIs. As mentioned I have no experience with React Native. Better to ask the experts.

**Comment by dmarcos** [comment]
@eliaskh Is this still an issue that needs to be addressed?

**Comment by dmarcos** [comment]
Closing for lack of info and activity. Can reopen if necessary.
