### ISSUE TITLE
Aframe automatically assumes a video when supplying URLs for material.src

### ISSUE THREAD

**Issue by Raildex** [aframevr/aframe#4816]
**Description:**
I have model files which are downloaded.
These model files contain rectangles with textures.
These rectangles are built at runtime (no `<a-assets>`).

When I create these primitives (`a-img` or `a-plane`) and supply their textures,
A-Frame throws these warnings:

> `$s` is not a valid video {url to png file}

For a workaround, I download the png files as a `Blob`, create a `FileReader`, use  `readAsDataURL(blob)` and replace `application/octet-stream` with `image/png` within the resulting Data url.

It would be great if A-Frame could detect them as textures automatically.

- A-Frame Version: 1.2.0
- Platform / Device: Angular / Desktop
- Reproducible Code Snippet or URL:

Workaround:
```
const sceneRoot: Entity = document.createElement("a-entity");
buttons.forEach((b: ButtonV4) => {
    const button: Entity = document.createElement("a-image");
    const url: string = this.dataProvider.buildURL(b.image);
    //getDataFromURL is a simple angular http get without parameters
    this.dataProvider.getDataFromURL<File>(url,"blob").subscribe((blob: File)  => {
        const fr: FileReader = new FileReader();
        fr.readAsDataURL(blob);
        fr.onload = (e: ProgressEvent<FileReader>) => {
            console.log(e.target.result as string);
            let s: string = e.target.result as string;
            s = s.replace("application/octet-stream","image/png"); // remove this line and it will throw the warning and the images will be black
            button.setAttribute("material","src",`url(${s})`);
        };

    },(error: unknown) => {
        console.log(error);
    });
    button.setAttribute("position",new THREE.Vector3(b.x,b.y,b.z));
    button.setAttribute("rotation",new THREE.Vector3(0,0,b.rotation));
    button.setAttribute("width",b.width/5);
    button.setAttribute("height",b.height/5);
    sceneRoot.appendChild(button);
});
```

**Comment by dmarcos** [comment]
Do you have a link with simple code to reproduce?

**Comment by dmarcos** [comment]
Working example with glitch: https://glitch.com/edit/#!/aframe?path=index.html%3A14%3A28

**Comment by Raildex** [comment]
@dmarcos 
https://glitch.com/edit/#!/iodized-power-tortellini?path=index.html%3A11%3A14

There is a png asset uploaded without png extension.
My assumption is that even though the file is a `png` file, it's Content-Type is set to `application/octet-stream`.

Our own files are stored on S3 and also have `application/octet-stream` as Content-Type. This is something I can't control though (The responsibility for the data lies somewhere else)

It would be great if aframe could inspect the file (png, jpg and other file formats have a specific byte sequence) and decide on that

**Comment by dmarcos** [comment]
Content should be served with the appropriate MIME type. Trying to infer asset formats by parsing the file seems like error prone and a source of complexity and bugs. The scenario is not very common and is probably better handled on an individual case basis as you did with your workaround.
