### ISSUE TITLE
Screenshot created in 'perspective' projection mode is darker than expected

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe#4817]
**Description:**
Using A-Frame's built-in keyboard activated screenshot the output of perspective screenshots is darker than expected. It is also darker than equirectangular screenshots from the same scene.
 
To reproduce:
- Go to https://kfarr.github.io/3dstreet/#https://streetmix.net/kfarr/3
- Press ctrl + alt + s
- Press ctrl + alt + shift + s
- Compare the resulting output

Suggested fix:
- Note that equirectangular projection uses sRGBEncoding encoding ([link](https://github.com/aframevr/aframe/blob/master/src/components/scene/screenshot.js#L155))
- I think you can insert `       encoding: THREE.sRGBEncoding,` [before line 93](https://github.com/aframevr/aframe/blob/master/src/components/scene/screenshot.js#L93)

Normal ticket questions:
- A-Frame Version: 1.1.0
- Platform / Device: Mac OS Chrome Desktop
- Reproducible Code Snippet or URL: See above

Images for comparison
![screenshot--1615104581133](https://user-images.githubusercontent.com/470477/110233616-e7fc3280-7ed9-11eb-897b-4886a3385944.png)
![screenshot--1615104250109](https://user-images.githubusercontent.com/470477/110233621-eaf72300-7ed9-11eb-89c4-e6f2f7c7c725.png)

**Comment by dmarcos** [comment]
Nice thanks. If you have some bandwidth, a PR will be super appreciated

**Comment by kfarr** [comment]
Yes can do as soon as I fix this which is blocking upgrade to latest a-frame on my project:
https://github.com/supermedium/superframe/issues/290

**Comment by kfarr** [comment]
Ok just submitted a PR which works on my local machine but seems to trigger a build error on Travis CI
https://github.com/aframevr/aframe/pull/4821

The error is `    ✖ can use spherical env maps` but I don't understand how that test would be affected by the changes in the PR.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/commit/65f02cc81d8e73b6e36a41763a214ecacbb054c3

**Comment by Tim-Laeufer** [comment]
In Version 1.3.0 I get this bug too.
In the following pictures there is a clear color difference. I'm not sure if it may be the same problem.

![screenshot-1657290602100](https://user-images.githubusercontent.com/89784833/178012842-b46cd873-99b6-43e6-86bc-9409db0979aa.png)

![image](https://user-images.githubusercontent.com/89784833/178012906-52efe2c9-306d-40f0-8420-6dfd304822a3.png)

In version 1.2.0 this error does not occur:
![image](https://user-images.githubusercontent.com/89784833/178013808-ddfe0bec-aa96-4f25-b67d-72f2f03b582d.png)
