### ISSUE TITLE
Shaded material darker

### ISSUE THREAD

**Issue by Dirk-27** [aframevr/aframe#4818]
**Description:**

- A-Frame Version: 1.1.0 and 1.2.0
- Platform / Device: Browser, 
- Reproducible Code Snippet or URL: https://acute-proximal-dog.glitch.me/

The ocean-plane looks pretty good in aframe version 1.0.4.

![image](https://user-images.githubusercontent.com/45331389/110593855-637d0e80-817c-11eb-9100-f7c2c04b0231.png)

When changing to aframe version 1.1.0 or 1.2.0 it is expected that the scene doesn't change. But the ocean looks much darker (https://soft-faceted-jumbo.glitch.me/):

![image](https://user-images.githubusercontent.com/45331389/110594046-9aebbb00-817c-11eb-8397-47af02b4cfa8.png)

Adding the renderer colorManagement and physicallyCorrectLights options to the scene doesn't change it.

**Comment by dmarcos** [comment]
What browser? It works for me on Windows desktop: Chrome and Firefox

**Comment by Dirk-27** [comment]
Sorry, the last version of the glitch used aframe 1.0.4. Set it now to aframe 1.2.0 where the ocean is much more dark.

It doesn't work on windows 10 enterprise desktop and
* Firefox 87.0B6
* Chrome 88.0.4324.190

Android 7:
* Chrome 89.0.4389.86

**Comment by dmarcos** [comment]
Related to https://github.com/aframevr/aframe/pull/4747 because SphericalReflectionMapping is no longer supported by three and it's still used by our [standard shader material](https://github.com/aframevr/aframe/blob/master/src/shaders/standard.js#L127).

**Comment by dmarcos** [comment]
Fixed. You can use [master builds](https://glitch.com/edit/#!/fortunate-longing-haddock?path=index.html%3A13%3A127)
