### ISSUE TITLE
360 Video example camera goes down

### ISSUE THREAD

**Issue by jamess922** [aframevr/aframe#4820]
**Description:**
Just open [360 Video](https://aframe.io/aframe/examples/boilerplate/360-video/),the camera start with angle,and slowly starts to move down,also same performance in safari. 
- A-Frame Version:
- Platform / Device:IOS14.0.1/Iphone X

https://user-images.githubusercontent.com/28625879/110880000-e509a380-8318-11eb-9798-96fe1ca52fcd.mp4

- Reproducible Code Snippet or URL:https://aframe.io/aframe/examples/boilerplate/360-video/

**Comment by dmarcos** [comment]
That's how the video is recorded. In the first part of the video the camera is panning. Notice the next part (the car) the camera is centered in the driver's point of view

**Comment by dmarcos** [comment]
I don't think there's nothing actionable on the A-Frame side. Thanks for reporting.
