### ISSUE TITLE
Component's init function is not called

### ISSUE THREAD

**Issue by Raildex** [aframevr/aframe#4824]
**Description:**

Init function of component is not called.
Properties that should be initialized in the init function are undefined in functions of the component.

- A-Frame Version: 1.2.0
- Platform / Device: 
- Reproducible Code Snippet or URL:
https://glitch.com/edit/#!/component-test

**Comment by dmarcos** [comment]
For components to initialize you have to [add the entity to the scene](https://aframe.io/docs/1.2.0/introduction/javascript-events-dom-apis.html#adding-an-entity-with-appendchild) and wait for it to load. Corrected glitch https://glitch.com/edit/#!/swift-spectrum-rat?path=script.js%3A3%3A18

**Comment by Raildex** [comment]
It is nowhere documented that the entity has to be fully loaded. Docs only mention **_setAttribute_**

**Comment by dmarcos** [comment]
Component initialization is described in the [component docs](https://aframe.io/docs/1.2.0/core/component.html#init)

**Comment by Raildex** [comment]
Can you tell me where the paragraph is that says that the entity needs to be fully loaded?
