### ISSUE TITLE
Why is the logged build version always 1 version behind?

### ISSUE THREAD

**Issue by haydeng21** [aframevr/aframe#4830]
**Description:**

- A-Frame Version: 1.1.0
- Platform / Device: All
- Reproducible Code Snippet or URL:

Just curious why the aframe builds log the previous version to the console? 

When I look in `dist/aframe-v1.1.0.js` it logs the version as 1.0.4. 

When I look in `dist/aframe-v1.2.0.js` it logs the version as 1.1.0. 

Is this just a missed update by aframe devs or am I missing something fundamental here? Not a big deal, I just want to make sure I'm using v1.1.0 and not positive which dist file accomplishes that.

**Comment by dmarcos** [comment]
My mistake. The build is correct but the logged version is wrong. I just fixed it on master. Issue only affects the builds in the dist directory. [Those in the CDN](https://aframe.io/releases/1.2.0/aframe.js) are correct
