### ISSUE TITLE
Cannot take screenshot of AR scene

### ISSUE THREAD

**Issue by monkeyMax-SVG** [aframevr/aframe#4831]
**Description:**
I am developing web AR using aframe but I cannot get screenshot of gameplay.
It's wired. My web AR project is to place object on the floor markerless.
- A-Frame Version: 1.2.0
- Platform / Device: Android
- Reproducible Code Snippet or URL:
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ARcore Experience</title>
    <link rel="stylesheet" type="text/css" href="assets/css/android/android_arcore.css">
    <script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@e47f441/dist/aframe-master.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.1.0/dist/aframe-extras.min.js"></script>
    <script src="https://ghcdn.rawgit.org/chenzlabs/aframe-ar/8a7ee3b/dist/aframe-ar.min.js"></script>
    <script src="https://unpkg.com/merge-images"></script>
</head>
<body style="margin: 0px; overflow: hidden;">
    <!-- Next & Capture Button -->
    <div class="buttons">
         <button class="next-button">Next</button>
    </div>
    <a-scene ar raycaster-move="target:#intersection" >
         <a-camera user-height="0" cursor="fuse:false" ar-raycaster raycaster="objects:none">
         </a-camera>
         <a-sphere id="intersection" visible="false" radius="0.02" color="red">
         </a-sphere>
    </a-scene>
</body>
</html>
```

In some AR, I can see video tag to show streams from webcam but in this markerless AR, I cannot see video tag.
so I cannot merge picture from video and picture from 3d enviroment. 
Also I am using dom-overlay to show some UI buttons.
![image](https://user-images.githubusercontent.com/54302680/112054521-a97c9e00-8b90-11eb-80ab-2266172bd46e.png)

**Comment by dmarcos** [comment]
I don't think `aframe-ar` is longer necessary/

**Comment by dmarcos** [comment]
I don't know what android_arcore is. It should not be necessary either.

**Comment by monkeyMax-SVG** [comment]
Please ignore about android_arcore.js
It is my custom js

**Comment by monkeyMax-SVG** [comment]
> I don't think `aframe-ar` is longer necessary/

I am sorry, I don't understand. can you please tell me about this in detail?

**Comment by dmarcos** [comment]
I'm on a Pixel 3 / Chrome 88 / Android 11 and I can enter AR mode with the [Hello world example](https://aframe.io/aframe/examples/boilerplate/hello-world/) and take screenshots with Power Button + Volume down without issue. Not sure what's particular about your experience but A-Frame core seems to be operating as expected.

**Comment by monkeyMax-SVG** [comment]
Hello, dmarcos
Yes, of course, we can take screenshots with Power Button + Volumn down button without any issues. it is normal, no?
Any persons knows that way, even they are child.
I mean I wanna custom button over the screen to take screenshot.
I have seen many opened issues channel for this but I were not able to see good solutions.

**Comment by dmarcos** [comment]
What method are you using to take the screenshot?

**Comment by monkeyMax-SVG** [comment]
I tried to get screenshot with this
document.querySelector("a-scene").components.screenshot.capture("perspective");
but it returns only 3d environment with white backgound, It doesnot show webcam datas in AR
So:
First, I can get canvas from this.
document.querySelector("a-scene").components.screenshot.getCanvas("perspective");
Second, I am gonna get video tag (because i was thinking the webcam data is displayed on video tag).
let video = document.querySelector("video");
Third, after this, I can merge these two.

**Comment by dmarcos** [comment]
Thanks. That's expected behavior. The AR mode of the WebXR API doesn't allow a page to access the camera feed for security and privacy reasons. Not an A-Frame limitation but a constraint impose by the standard. There's nothing actionable on the A-Frame side.

**Comment by monkeyMax-SVG** [comment]
why you close this without my agreement? 
it's really unprofessional.
can you please show me any document for that?
and google model-viewer has own screenshot and record button. what do you think about this? they occupied security and privacy?

**Comment by dmarcos** [comment]
Sorry, not meant to be rude. We usually close an issue when it's not applicable or cannot act on it because it's not fixable on the A-Frame side.

This is the relevant part of the [WebXR standard stating that the camera feed is not exposed to the page](https://immersive-web.github.io/webxr-ar-module/#privacy-security)

> Implementations of the AR Module MUST NOT expose camera images to the content, rather they MUST handle any compositing with the real world in their own implementations via the XR compositor. Further extensions to this module MAY expose real-world information (like raw camera frames or lighting estimation), however they MUST gate this behavior on an additional feature descriptor that requires user consent.

Do you have a link if the model-viewer taking screenshots including the camera feed? Is it perhaps opening a 3rd party application in the background that takes the screenshot?

**Comment by monkeyMax-SVG** [comment]
thank you for your quote
You can open following link on mobile
https://modelviewer.dev/
https://modelviewer.dev/examples/augmentedreality/

**Comment by dmarcos** [comment]
What the model viewer is doing is opening the [Android built-in native Scene Viewer](https://developers.google.com/ar/develop/java/scene-viewer) via an intent. It's a separate app that offers a simple way to preview 3D models (Web APIs constraints don't apply in that context). It's equivalent to the [Quick Look viewer](https://developer.apple.com/augmented-reality/quick-look/) on iOS for USDZ models.

**Comment by dmarcos** [comment]
Feature request to implement a WebXR screenshot feature on the model-viewer itself: https://github.com/google/model-viewer/issues/1481 

It also depends on the WebXR standard to expose the camera feed that it's not available at the moment.

**Comment by monkeyMax-SVG** [comment]
Hi @dmarcos 
Thank you so much.
You saved my time a lot.
