### ISSUE TITLE
protecting my project.

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [aframevr/aframe#4833]
Hello Aframe is pretty much open to the public. But this might be a issue to me. I know this question comes up a lot and I'm also asking is there a way to protecting my project. For all the long times i have worked on it just to be ripped off by someone as there own? I already had it happen once to me and they used my work as there own.

Joseph

**Comment by Therealjosephchrzempiec** [comment]
I love aframe don't get me wrong. But i just don't know how to protect my own work.


Joseph

**Comment by dmarcos** [comment]
Sorry for what happened to you. Do you mean protecting code, assets, something else? Is not an A-Frame application similar to any other Web application?

**Comment by Therealjosephchrzempiec** [comment]
Hello what happen is that i was working on a aframe gamea friend of mine and me was makig. Not in glitch just online a small game mostly for racing cars. With the help of discord and the forums help We was able to figure out a lot of problems Thanks you everyone, Everything was great. Then one day a friend told me he found my race car game online someone has it and was selling the code to it. I went to see it and sure enough it was what i was working on no changes was made. someone was selling my work. Well i no longer have that project because i lost my server over christmas time because i was away from home. I should  backed it up but i didn't. 

I just want to protect my stuff for the next time. It's a aframe game. how can i protect my code the graphics as you would call it the cars Which i paid from cgtrader. I can get them back. But mostly i don't want to happen again. Found out a week ago that site was taking down for some rules broken by the hosting company. Makes me wonder how many copies was sold already.


Joseph

**Comment by dmarcos** [comment]
Minimizing the code is not working for you? Same techniques that people use for regular sites apply. Nothing special and particular about A-Frame or WebXR experiences.

**Comment by Therealjosephchrzempiec** [comment]
Hey dmarcos, What do you mean by Minimizing the code? What does that do? The problem is they viewed my source code and saw where everything is at. Then they pretty much saved everything like it was a open book for them. Everything is viewable. Sense it is in html and javascript it is open to the public. There are some way to protect javascript. But sense it comes from the aframe it's self as a example

example 
`
    <script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.min.js"></script>
    <script src="easyrtc/easyrtc.js"></script>
    <script src="https://unpkg.com/networked-aframe@^0.4.0/dist/networked-aframe.min.js"></script>

    <script src="https://unpkg.com/aframe-randomizer-components@^3.0.1/dist/aframe-randomizer-components.min.js"></script>
    <script src="https://unpkg.com/aframe-particle-system-component@1.0.5/dist/aframe-particle-system-component.min.js"></script>`

pretty much that is open. Also my cars all they have to do is find the path to them and it can be easly seen in html


Joseph

**Comment by dmarcos** [comment]
[Minification, Uglification are common techniques in Web development to make your code less readable](https://www.cloudflare.com/learning/performance/why-minify-javascript-code/). Notice the code referenced by script tags you shared. The code is not legible. You can do the same with your application code. That's out of scope of A-Frame and it depends on the your tooling of choice (browserify, webpack, your own). Search for tutorials / info on how to minimize / uglify your JS code. I don't think there's anything actionable on the A-Frame side. Thanks for filing

**Comment by Therealjosephchrzempiec** [comment]
I will search and try that thank you.

**Comment by dmarcos** [comment]
By the way. You're using A-Frame 0.7.0 that it's a very old version. I recommend using the latest 1.2.0

**Comment by Therealjosephchrzempiec** [comment]
That was just a example from the old examples i had at one time I'm redoing over. hehe
