### ISSUE TITLE
iOS safari address bar appears in vr-mode when phone is put to landscape

### ISSUE THREAD

**Issue by kbreynck** [aframevr/aframe#4839]
There is an issue with a "workaround" in aframe-v1.2.0.js line 73346 ff:
```
// Safari regression introduced in iOS 12 and remains in iOS 13.
// https://stackoverflow.com/questions/62717621/white-space-at-page-bottom-after-device-rotation-in-ios-safari
...
```
This workaround causes iPhones with modern iOS to display the Safari adresss bar even in vr-mode when you turn the phone into landscape.

- A-Frame Version: v1.2.0
- Platform / Device: Tested iPhone 8 // Current iOS >= 12
- Reproducible Code Snippet or URL: Any project that uses v1.2.0. due to the workaround (see above)

```
<!DOCTYPE html><html>
  <head><meta charset="utf-8"><title>Test</title><script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script></head>
  <body>
    <a-scene></a-scene>
  </body>
</html>
```

I don't know what kind of bugs you tried to fix with this workaround, but i fear you have to search and test for another solution. :/

**Comment by dmarcos** [comment]
That's expected behavior. Safari for iOS no longer allows websites to enter fullscreen mode unless the website is pinned / bookmarked to the homescreen. If launched from homescreen websites can then enter fullscreen mode.

**Comment by kbreynck** [comment]
> "Safari for iOS no longer allows websites to enter fullscreen mode" 

Excuse me @dmarcos, but it seems you completeley misunderstood my reported issue and also from our experience in the tested iOS environments your statement is simply wrong, Sir.

First, there is no issue to enter fullscreen on Safari iOS when starting the vr-mode with A-Frame and turning the iPhone to landscape.

The issue I am talking about is, that the workaround script forces Safari iOS to display the address bar. And that happens after 1 second (accordingly to the timeouts in the script). If you comment the script, then the fullscreen works fine. You only have to find another solution to properly display the vr/ar-buttons in the bottom of the page. (Like simply placing them to the top instead of the bottom)

The follwoing function call causes the adressbar to appear on iOS:
`window.scrollTo(0, 1);`

See full script here: https://aframe.io/releases/1.2.0/aframe.js Line: 73346 ff
```
// Safari regression introduced in iOS 12 and remains in iOS 13.
// https://stackoverflow.com/questions/62717621/white-space-at-page-bottom-after-device-rotation-in-ios-safari
window.addEventListener('orientationchange', function (event) {
  document.documentElement.style.height = `initial`;
	
  setTimeout(function () {
    if(window.innerHeight > window.innerWidth) { // kbreynck: Fixes iOS toolbar when entering vr-mode
      document.documentElement.style.height = `100%`;
      setTimeout(function () {
        // this line prevents the content
        // from hiding behind the address bar
        window.scrollTo(0, 1);
      }, 500);
    }
  }, 500);
});
```

Please reopen this issue, because the workaround may be a feature but it causes an annoying **BUG** in vr-mode.
You can simply reproduce it with a modern iPhone.
