### ISSUE TITLE
Transparent PNG images incorrectly occluding other PNG images, depending on DOM order.

### ISSUE THREAD

**Issue by diarmidmackenzie** [aframevr/aframe#4840]
**Description:**

- A-Frame Version: 1.2
- Platform / Device: Observed on Chrome on Windows, also Edge on Windows (may occur in other browsers too)
- Reproducible Code Snippet or URL: https://separated-square-result.glitch.me/

I have been experimenting with layering of transparent PNG images, and found an odd behaviour.

These images only work correctly if they are ordered back-to-front in the DOM.

If they are ordered front-to-back in the DOM, then the further back images get occluded by the ones in front.  Other 3D objects in the scene seem to be fine, and visible through the transparent parts of the images, but the other images are not.

Ordering the images "correctly" to avoid the problem is not a very good workaround, because if the user moves through the space and turns around, then from this different point of view, the objects will be ordered "incorrectly" again.

My understanding was that order in the DOM should not matter, and that A-Frame and/or three.js ought to take care of ensuring everything gets rendered in the correct order.  But with transparent PNG images that seems not to be happening.

**Comment by diarmidmackenzie** [comment]
What appears to be exactly the same problem can also be seen in this A-Frame Example.
https://aframe.io/aframe/examples/showcase/anime-UI/

Using WASD controls, nagivate to the end of the corridor, and look back towards your start point.  The images that are closest to you occlude the ones behind, so the effect of multiple layers of rings is not achieved in this reverse direction.

**Comment by dmarcos** [comment]
Transparency is complicated and a generic solution for all cases is intractable. You can manually control the render order with [render order component](https://www.npmjs.com/package/aframe-render-order-component)

**Comment by diarmidmackenzie** [comment]
Thanks - so this is pretty clear in the docs, I just didn't fine it.
https://aframe.io/docs/1.2.0/components/material.html#transparency-issues

I've also been pointed to this as a possible solution.
https://aframe.io/docs/1.2.0/components/renderer.html#sortobjects
