### ISSUE TITLE
Screenshot lighting/colors are too dark

### ISSUE THREAD

**Issue by samyH** [aframevr/aframe#4841]
So I've been using the screenshot component that ships with Aframe and have noticed some color variation between what is displayed on screen and what gets downloaded.  It's especially noticeable when envMaps are applied either to standard Aframe geometries or with GLTF models.  

Maybe some kind of encoding issue? Any known fixes/workarounds would be great to know. Thanks.

[Image comparison](https://ibb.co/5rgBKbr)

[code](https://violet-magical-blackcurrant.glitch.me)

- A-Frame Version: 1.2.0
- Platform / Device: Any

**Comment by dmarcos** [comment]
This has been fixed by https://github.com/aframevr/aframe/pull/4822 

It will ship in the next version. You can use [master builds](https://github.com/aframevr/aframe/pull/4822) in the meantime. 

Closing and can reopen if necessary
