### ISSUE TITLE
Hand tracking controls model needs update

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4848]
The hand tracking WebXR API has changed on how it reports the joint pose and the [model needs to be updated](https://github.com/aframevr/assets/tree/master/controllers/oculus-hands/unity).

Information I collected from 3rd party

> The left hand joints were rotated around the X axis by 180 degrees and then around the Y axis by -90. The right hand joints were rotated around the Y axis by 90.

**Comment by tonypapousek** [comment]
Howdy,

I'm seeing hand model alignment weirdness on the HoloLens 2. I'm fairly new to this framework, but think it might be related to this issue. Apologies in advance if I've posted to the wrong thread.

Video:

https://user-images.githubusercontent.com/962327/134826858-f6843622-a875-4e45-a0a9-81d180670256.mp4

If it helps, I found [a demo](https://gftruj-handstuff.glitch.me/) posted inside of an [aframe-hand-tracking-controls-extras issue](https://github.com/gftruj/aframe-hand-tracking-controls-extras/issues/2) that renders correctly on the HL2.

Technical Details:
* OS build `20348.1018`
* Edge `93.0.961.52`
* a-frame `1.2.0`

Please let me know if I can provide any logs or the like. 

---

Some things I'd love to be able to do with this component in the future:
* Define MODEL_URLs via attribute instead `hand-tracking-controls.js` hard-coding the path. In `1.2.0`, one's never  able to fully serve the application themselves; it always relies on hitting the a-frame CDN.
* Define a model style, similar to hand-controls (i.e. `lowPoly`, `highPoly` or `toon`).
* Define materials/textures to apply to the hand models.
