### ISSUE TITLE
Add an "arrow-enabled" property to the look-controls

### ISSUE THREAD

**Issue by Whystler** [aframevr/aframe#4849]
Background: 

Many of the older social VR experiences had (and those that exist, such as Activeworlds and others, still have) a movement system where the side arrow keys do not strafe.  Instead they rotate the camera view.  The first person shooter game-based experiences are the ones that used the mouse primarily for rotation.   The side arrow rotation is comfortable, especially for those of us who experience VR sickness and are accustomed to this kind of movement.  Furthermore, you aren't faced with that annoying situation where the mouse can't move any further in one direction on the screen, and repositioning takes away from your experience moving around.

Suggestion:

Add an "arrow-enabled" property to the look-controls, set to default as "false".  When set to "true", however, this property will enable smooth rotation movement around the Y axis (up/down) to the left with the left arrow key, and to the right with the right arrow key.  This property should not affect the use of the mouse for view rotation.

Thanks!

**Comment by dmarcos** [comment]
There are many possible input schemas that make sense. A-Frame core only implements most common functionality to get people started relying on the component community for additional functionality. The path I recommend is building your own component  (e.g: arrow-look-controls) using [look-controls](https://github.com/aframevr/aframe/blob/master/src/components/look-controls.js) as starting point and adding the functionality you need.

**Comment by dmarcos** [comment]
I recommend exploring this as a 3rd party component. Closing and can reopen if necessary
