### ISSUE TITLE
Look-controls on iOS cant be disabled 

### ISSUE THREAD

**Issue by willnnotdan** [aframevr/aframe#4851]
First of all sorry if this is because Im doing something wrong but from the documentation and stack I think Im doing the right thing. 

Basically I want to rotate the camera manually at certain points as Im doing a sort of experience project. For this I have created a rig around my camera and rotate that. 

It doesnt work off the bat but that makes sense as motion controls take precedent. However with all of the following the camera controls still work on iOS (controls are correctly locked on other platforms and the rotation works as well):

```
<a-entity id="camera" camera></a-entity>

<a-entity id="camera" camera look-controls="enabled: false;"></a-entity>

<a-entity id="camera" camera look-controls="enabled: false; magicWindowTrackingEnabled: false;"></a-entity>

<a-entity id="camera" camera look-controls="enabled: false; magicWindowTrackingEnabled: false; touchEnabled: false;"></a-entity>

```

- A-Frame Version: 1.3.0
- Platform / Device: iOS iPhone 6s & X

```
<a-entity id="rig" position="0 1.6 0"
                      animation="property: rotation; to: 0 -90 0; delay: 6000; dur: 4000;"
                      animation__2="property: rotation; from: 0 -90 0; to: 0 -180 0; delay: 12000; dur: 4000;"
                      animation__3="property: rotation; from: 0 -180 0; to: 0 -270 0; delay: 18000; dur: 4000;"
                      animation__4="property: rotation; from: 0 -270 0; to: 0 -360 0; dur: 1; delay: 1100; startEvents: start;">
    <a-entity id="camera" camera>
    </a-entity>
</a-entity>

```

**Comment by dmarcos** [comment]
It works for me

https://glitch.com/edit/#!/six-truth-dryosaurus?path=index.html%3A11%3A35

**Comment by willnnotdan** [comment]
Interesting, thanks for the quick response and sorry for wasting your time it must be something I have locally. Confusing! Let me know if you have any thoughts
