### ISSUE TITLE
Page freezes after entering the VR mode on Chrome for Android

### ISSUE THREAD

**Issue by gearcoded** [aframevr/aframe#4854]
I launch the local examples over HTTP on Chrome for Android. I inspect the device from the computer.
After entering the VR mode, I get 256 console warnings:
```
THREE.Matrix4: .getInverse() has been removed. Use matrixInv.copy( matrix ).invert(); instead.
```
After that, Chrome refuses to show any messages.
But more importantly, the page no longer responds(regardless of the Chrome Dev tools on PC opened). 
I have to reload the page. But to make the Dev Tools on PC working again, I have to close the browser and reopen it.

I commented the code that spams the error and other lines, but the page still hangs, and there are no other messages.
 

- A-Frame Version: 1.2.0
- Platform / Device: Sony Xperia XZ1, Chrome 90.0.4430.91
- Reproducible Code Snippet or URL:
Open `examples/primitives/boxes/ over HTTP` on Android device

**Comment by dmarcos** [comment]
FWIW WebXR only works over HTTPS as per standard security policy.

**Comment by gearcoded** [comment]
@dmarcos, thank you, that helps. However, I would at least see a warning message about that. Instead, I got tons of irrelevant messages, and that is really confusing.

**Comment by dmarcos** [comment]
Page shouldn’t freeze. If accessed via http A-Frame should show a message requesting the user to switch to https. What happens when you visit http://aframe.io/aframe/examples/showcase/anime-UI/

**Comment by dmarcos** [comment]
Can you provide a direct link to the example you were running?

**Comment by gearcoded** [comment]
I'm trying this file:
https://github.com/aframevr/aframe/blob/master/examples/primitives/boxes/index.html
So, in my case, I open this link:
http://192.168.0.107/aframe/1.2.0/examples/primitives/boxes/

Actually, I see this message:
> Access this site over HTTPS to enter VR mode and grant access to the device sensors.

But as VR mode works in Firefox, I thought I could ignore it at least for now.
Here is a video demo:
https://disk.yandex.ru/i/hT5XnYCjnN39jA

**Comment by dmarcos** [comment]
As per video the behavior is correct. The user is prompted to access the page over HTTPS. You have to serve a page over HTTPS so A-Frame can access the sensors and track the device pose (that's a constraint of Web standards, some APIs are not available over HTTP). You can see the hosted example working as expected:

https://aframe.io/aframe/examples/primitives/boxes/

For development you can for instance use ngrok to get an HTTPS end point: https://ngrok.com/

There's nothing to do on the A-Frame side. Closing and we can reopen if necessary.
