### ISSUE TITLE
Regression from aframe 1.0.4 to 1.1.0 and up

### ISSUE THREAD

**Issue by rajsite** [aframevr/aframe#4855]
**Description:**

I'm using similar techniques like in the [aframe-site/themes/aframe/source/examples/hello-metaverse](https://github.com/aframevr/aframe-site/blob/14fb0751160bfdad43e4fb3210433437b60f35bc/themes/aframe/source/examples/hello-metaverse/index.html) example. If I take the example and only make the change to upgrade from aframe 1.0.4 to 1.1.0 there is significant changes to how it is rendered. I don't see any clear errors in the console running the examples, any ideas about what may have regressed in newer versions of aframe?

Example of 1.0.4 [running](https://aframe110gltfchange.glitch.me/metaverse104.html) and [source](https://glitch.com/edit/#!/aframe110gltfchange?path=metaverse104.html%3A4%3A8):
![image](https://user-images.githubusercontent.com/1588923/116956384-c958b480-ac5a-11eb-9ba6-a7273837deb4.png)

Example of 1.1.0 [running with only the aframe version update](https://aframe110gltfchange.glitch.me/metaverse110.html) and [source](https://glitch.com/edit/#!/aframe110gltfchange?path=metaverse110.html%3A1%3A0):
![image](https://user-images.githubusercontent.com/1588923/116956424-dd9cb180-ac5a-11eb-9f65-07138a82b4a1.png)

- A-Frame Version: 1.0.4 vs 1.1.0
- Platform / Device: Win 10 Chrome 90
- Reproducible Code Snippet or URL:  See above

**Comment by dmarcos** [comment]
`<a-scene renderer="colorManagement: true;"></a-scene>`

**Comment by rajsite** [comment]
It doesn't look like enabling colorManagement made much of a difference ([source](https://glitch.com/edit/#!/aframe110gltfchange?path=metaverse110-colormanagement.html%3A1%3A15) + [render](https://aframe110gltfchange.glitch.me/metaverse110-colormanagement.html)):
![colormanagement](https://user-images.githubusercontent.com/1588923/117040741-cfd54380-accf-11eb-8cbb-cafebec534f0.PNG)

**Comment by rajsite** [comment]
If I take the 1.0.4 demo and remove all the sphericalEnvMap configurations ([source](https://glitch.com/edit/#!/aframe110gltfchange?path=metaverse104-noenvmap.html%3A25%3A117), [render](https://aframe110gltfchange.glitch.me/metaverse104-noenvmap.html)) then it renders just like 1.1.0 with the spericalEnvMap configuration unchanged (see initial post).

![image](https://user-images.githubusercontent.com/1588923/117045684-66583380-acd5-11eb-9866-9d5880abd703.png)

It looks like the regression may have been for sphericalEnvMap behavior from 1.0.4 to 1.1.0.

**Comment by dmarcos** [comment]
Environ maps are not loading because `THREE.SphericalReflectionMapping` has been deprecated in THREE. Issue is fixed on master and will ship in the next A-Frame version. In the meantime you can use a [master-build](SphericalReflectionMapping). Example fixed below:

https://glitch.com/edit/#!/catnip-wind-metatarsal?path=index.html%3A7%3A127

**Comment by rajsite** [comment]
Looks like the following PR discusses the same issue: https://github.com/aframevr/aframe/pull/4747

**Comment by rajsite** [comment]
@dmarcos thanks for the help! 🚀

**Comment by rajsite** [comment]
For any other readers here is the same example with the changes from master ([source](https://glitch.com/edit/#!/aframe110gltfchange?path=metaverse-master-sphericalEnvFix.html%3A13%3A13), [render](https://aframe110gltfchange.glitch.me/metaverse-master-sphericalEnvFix.html)). You can see a difference in behavior as the underlying change [switches to EquirectangularReflectionMapping](https://github.com/aframevr/aframe/commit/382296c6a69f280280f9516bcb0cdc609113f840), but that is not a huge deal for these demos and does not appear to be a huge issue in my apps. Does make for a funny name though :P
