### ISSUE TITLE
A-Scene DOM is not updating

### ISSUE THREAD

**Issue by epic-developer** [aframevr/aframe#4856]
I understand that the innerHTML within A-Scene is meant to act more as an initializer, but in my use case, I need the DOM (particularly the innerHTML) to update. In this specific scenario, I am using Aframe Inspector (the same issue occurs even if objects are moved without Aframe Inpsector). If I move objects in Aframe Inspector, the innerHTML of a-scene does not update. I need to utilize the innerHTML because I am writing changes to a MySQL database when a user selects "Save". Aframe-Watcher is not an option as it requires IDs for each element. I need a solution that can be easily implemented (such as getting innerHTML). I already finished the system, but the HTML inside of the scene is not updating which after a bit of debugging, I realized that the case. Because of the large number of components and component attributes, running getAttribute for every possible attribute for every element picked up by querySelector is not a viable solution. Please consider the ability to add an attribute to a-scene that makes the innerHTML update. Is there another efficient way to easily get every possible a-frame scene component and get every attribute for those components?

- A-Frame Version: 1.2.0
- Platform / Device: Windows 10 Google Chrome
- Reproducible Code Snippet or URL: N/A

**Comment by dmarcos** [comment]
https://aframe.io/docs/1.2.0/introduction/faq.html#why-is-the-html-not-updating-when-i-check-the-browser-inspector

**Comment by epic-developer** [comment]
> https://aframe.io/docs/1.2.0/introduction/faq.html#why-is-the-html-not-updating-when-i-check-the-browser-inspector

Thank you so much! That is very helpful. I assumed it didn't sync to the DOM for performance reasons and the flushToDOM method is perfect and still doesn't impact performance.
