### ISSUE TITLE
Is THREE.Cache handling in a-assets.js correct?

### ISSUE THREAD

**Issue by takahirox** [aframevr/aframe#4861]
**Description:**

- A-Frame Version: v1.2.0

I found two direct `THREE.Cache` accesses in `a-assets.js`.

```javascript
// Set in cache because we won't be needing to call three.js loader if we have.
// a loaded media element.
THREE.Cache.files[imgEls[i].getAttribute('src')] = imgEl;
```

https://github.com/aframevr/aframe/blob/v1.2.0/src/core/a-assets.js#L43-L45

```javascript
// Set in cache because we won't be needing to call three.js loader if we have.
// a loaded media element.
// Store video elements only. three.js loader is used for audio elements.
// See assetParse too.
if (el.tagName === 'VIDEO') {
    THREE.Cache.files[el.getAttribute('src')] = el;
}
```

https://github.com/aframevr/aframe/blob/v1.2.0/src/core/a-assets.js#L163-L169

They give me two questions.

1. Why don't we use [`THREE.Cache.add(key, file)`](https://threejs.org/docs/#api/en/loaders/Cache.add) method? I think using `Cache.add()` method is more proper API rather than directly accessing `Cache.files`.

2. From the comment "Set in cache because we won't be needing to call three.js loader if we have." I supposed we have like the following code

```javascript
let el = THREE.Cache.get(url);
if (!el) {
  const loader = new THREE.FooLoader();
  el = await loader.load(url);
}
```

but I couldn't find such codes although I ran `$ find ./src -print0 | xargs -0 grep "THREE.Cache"`. So I'm wondering if these elements cache are working expectedly.

**Suggestion**

I would like to suggest to use `THREE.Cache.add()` method or simply we can remove the lines.

**Comment by dmarcos** [comment]
Thanks. This is old code. I cannot remember the rational. Perhaps we wanted to bypass the enable / disable flag. I'm good with moving to get / add API if there are no side effects.

**Comment by takahirox** [comment]
> I'm good with moving to get / add API if there are no side effects.

`THREE.Cache.enabled` is `true` in A-Frame so there should be no functionality difference.

https://github.com/mrdoob/three.js/blob/r128/src/loaders/Cache.js#L7-L15

Only the side effects I came up with are very minor performance overhead caused by additional function call and additional `if ( this.enabled === false )` check but they shouldn't be big deal especially because `a-assets` is not a component frequently called.

**Comment by dmarcos** [comment]
Yeah. I think we could switch to the get / add API. PRs always welcome
