### ISSUE TITLE
How to use inner camera in gltf?

### ISSUE THREAD

**Issue by cylhah** [aframevr/aframe#4862]
I have a gltf model, which contains cameras, models and camera animations. After loading, they become an gltf entity. I can't use "secondcamera el. SetAttribute ('camera ','active', true ')" to change camera. How can I use the camera in it.

This can be modified in three. JS

this.content.traverse((node) => {

if (node.isCamera && node.name === name) {

this.activeCamera = node;

}

});

this.renderer.render( this.scene, this.activeCamera )

but, how to use inner camera in gltf in aframe?

**Comment by dmarcos** [comment]
Thanks! I see you’re getting answers on StackOverflow. I’m closing this. We use Github issues for bugs and feature requests.
