### ISSUE TITLE
Empty dialog with pink button in iPhone devices

### ISSUE THREAD

**Issue by SheikhZayed** [aframevr/aframe#4865]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Everything works fine, except a blank dialog with pink button which is really weird, please check the following image

![WhatsApp Image 2021-05-23 at 9 06 43 AM](https://user-images.githubusercontent.com/8774293/119249031-a01aac80-bba6-11eb-9c9f-4ad445b61e65.jpeg)

**Please mention other relevant information such as the browser version, Operating System and Device Name**
This dialog appears only in iPhone devices, every other browser works fine,

**What is the expected behavior?**
empty dialog should not appear

**Comment by dmarcos** [comment]
It works for me with the examples. e.i https://aframe.io/aframe/examples/boilerplate/hello-world/

**Comment by SheikhZayed** [comment]
Hi @dmarcos 

Thanks for your reply.. 

can u pls suggest anything spooky in the following code ?

`<html>
   <head>
      <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
	   <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
      <script src="./build.js"></script>
      <script src="./bustime.js"></script>
      <meta charset="UTF-8">
      <meta name="description" content="Get Bus Timings around your proximity in Augmented Reality">
      <meta name="keywords" content="ar,darb,abudhabi,dot,itc">
	  <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico"/>
      <meta name="author" content="ITC-GIS team">
      <title>Augmented Reality Bus Departure Timings in Darb</title>
      <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>
      <script>
         THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/AR-js-org/AR.js/master/three.js/build/ar.js'
      </script>
      <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
      <style>
         body{
         font-family: 'Roboto', sans-serif;
         color: #fff;
         font-size: 32px;
         }
         h1{
         font-size: 52px;
         }
         .dark{
         background-color: rgba(0,0,0,0.8);
         border-radius:50px;
         background-repeat: no-repeat;
         background-position: bottom right;
         padding: 40px;
         }
         .main{
         width: 700px;
         min-height: 100px;
         overflow: hidden;
         }
         .menu{
         width: 256px;
         height: 768px;
         text-align: center;
         }
         .menu ul{
         list-style-type: none;
         margin: 0;
         padding: 0;
         }
         a.button{
         display: inline-block;
         width: 100%;
         border-radius: 20px;
         background-color: #000;
         color: #fff;
         text-decoration: none;
         text-align: center;
         padding: 10px 0;
         margin-bottom: 20px;
         }
         a.button:hover{
         background-color: #fff;
         color: #888;
         }
         a.button:active{
         background-color: #fff;
         color: #888;
         box-shadow: 0px 0px 50px #00d2ff;
         }
         #page1{
         position: relative;
         height: 100%;
         }
         .slide{
         height:100%;
         }
         .slide:target #page1{
         display: none;
         }
      </style>
   </head>
   <body>
      <div class="slide">
               <a-scene vr-mode-ui='enabled: false'
                  embedded
                  arjs='sourceType: webcam; sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: false;'>
    
                <a-entity a-bustime="target:#box" visible=false id="main" class="screen dark main" htmlembed="ppu:256" position='0 2.5 -5' material='opacity: 0.5; side: double'></a-entity>

               </a-scene>
      </div>
	  <div id="dialog" class="dialog">
    <div>
        <label for="title">Select Platform for Stop..</label><br/>
        <input id="one" type="radio" name="add" class="terms">Platform A</input><br/>
        <input id="two" type="radio" name="add" class="terms">Platform B</input>
    </div>
</div>`

**Comment by SheikhZayed** [comment]
Thank you very much @dmarcos 

It was a css styling issue which has set white color for the body tag !!!

**Comment by dmarcos** [comment]
Thanks. Closing. We can reopen if necessary.

**Comment by SheikhZayed** [comment]
Additional tip for anyone who want to completely hide that weird dialog , add the following code to <a-scene tag

`device-orientation-permission-ui="enabled: false"
   loading-screen="enabled: false;"`

**Comment by dmarcos** [comment]
FYI, That dialog is necessary for magic window mode to function on mobile devices. Browsers require user permission to access the sensors. If you disable, magic window won't work.

**Comment by SheikhZayed** [comment]
@dmarcos what do you mean by magic window ? I'm sorry i don't know that.

**Comment by dmarcos** [comment]
In order for a a-frame to track the orientation of the device and move the camera accordingly the user has to give permission to access the sensors and hence the need of the dialog. No dialog === no device orientation tracking
