### ISSUE TITLE
Alter package.json engine allowances for NPM

### ISSUE THREAD

**Issue by cwadrupldijjit** [aframevr/aframe#4869]
**Description:**

- A-Frame Version: 1.2.0
- Platform / Device: Mac OS Big Sur, version 11.4; All browser platforms
- Reproducible Code Snippet or URL:
   ```shell
   $ npm install aframe@latest
   ```

I've encountered the error of `EBADENGINE` several times whenever installing with the latest versions of Node and NPM.  It's more an annoyance, as I've had no problems using either of those versions with AFrame (especially since it's a build-time situation).  To the best of my knowledge, the problem lies in the `package.json` under the `engines` object:

```json
"node": ">=4.6.0",
"npm": "^2.15.9"
```

While this won't cause any problems with my version of Node (16.2.0), it will be causing issues for any recent versions of NPM.

Is there any reason why it's locked to that specific version of NPM?  Could we change it to be a `>=` just like in the `node` field?

Thanks!

**Comment by dmarcos** [comment]
Thanks. We can indeed bump the node version. We just need to make sure there are no issues. I’m not sure there’s longer a reason to be locked to an old version.

**Comment by cwadrupldijjit** [comment]
Great!  Let me know if there's anything I could do to help.  I could even put in a PR for it if you want.

**Comment by dmarcos** [comment]
Thanks. Feel free to put up a PR. Thanks so much.
