### ISSUE TITLE
Monitor not displaying scene while in VR

### ISSUE THREAD

**Issue by wyzwon** [aframevr/aframe#4873]
**Description:**
In previous versions of A-frame, Entering VR would cause the monitor to start displaying the two headset views side by side. Now the monitor freezes on the last rendered frame before the "VR" button was pressed.

Possibly relevant info: Upon leaving VR I get 2 alerts that state "THREE.WebGLRenderer: Can't change size while VR device is presenting." from three.js:18786 

- A-Frame Version: tested in 1.2.0 and #bbd27c76
- Platform / Device: Windows 10, Chrome 91, SteamVR beta 1.18.2, HTC Vive gen 1
- Reproducible Code Snippet or URL: Any A-frame scene, I used the classic [Hello World](https://aframe.io/examples/showcase/helloworld/) scene

**Comment by dmarcos** [comment]
Unfortunately, the capability was lost in the transition to WebXR. The new standard doesn’t consider mirroring. You can do it via SteamVR https://youtu.be/VtcgVbZWhUA
