### ISSUE TITLE
Weird Wide Angle effect with AR on some phones

### ISSUE THREAD

**Issue by Whystler** [aframevr/aframe#4875]
**Description:**

- A-Frame Version: 1.1.0 and 1.0.4
- Platform / Device: Samsung Galaxy 10+
- Reproducible Code Snippet or URL: unphased.neocities.org/restaurant/test05a.html

Viewing Aframe AR experience: test05a.html on two different phones and yet the same browser (Google Chrome, and also Firefox)

My phone (Google Pixel 3) shows the overlay that happens on the marker properly.

My partner's phone (Samsung Galaxy 10+) somehow has a skewed camera. When pointing the camera at the marker, we see another part of the room/area altogether.  For example, the marker was on the couch seat, and in AR, the camera pointed at the back cushion.  When we move the his phone to look at someone's face in AR, it is clear also that the face has been skewed in shape. When viewing the camera of his phone regularly (not through the browser AR experience) , the camera behaves normally.  This behaviour was confirmed to happen when the website code used Aframe 1.1.0 , and also Aframe 1.0.4.

We had some chat about it in the Aframe slack channel, and it was discovered that his phone has three back facing cameras (I think).  In order of top to bottom (I think), it is: wide angle, standard, and telephoto.  I suspect that the AR grabs the wide angle camera and then ... only uses a portion of it?  I don't know.

Here is a picture of what happens: 

https://unphased.neocities.org/phone-issue-explained01.png

Here is the experience we tested it with:

https://unphased.neocities.org/restaurant/test05a.html

Using this marker:

https://unphased.neocities.org/restaurant/pattern-marker-test01gb.png

**Comment by dmarcos** [comment]
This is an ar.js issue. I’m not familiar with the code base. Beat it’s to reach out to the maintainers https://github.com/AR-js-org/AR.js
