### ISSUE TITLE
Aframe sphericalEnvMap bug

### ISSUE THREAD

**Issue by Aznbai** [aframevr/aframe#4877]
**Description: sphericalEnvMap does not work in Aframe 1.2.0  for me. Version 0.8.0 works fine**

- A-Frame Version: 1.2.0
- Platform / Device: chrome/opera/ff on win10
-  [Codepen reproducing the issue](https://codepen.io/aznbai/pen/wvdwOMx)

![image](https://user-images.githubusercontent.com/1290615/123559603-56bd0e80-d79d-11eb-884a-735650a57313.png)
![image](https://user-images.githubusercontent.com/1290615/123559637-866c1680-d79d-11eb-8f07-4094fd3d4be2.png)

**Comment by dmarcos** [comment]
Fix on master. It will ship in the next A-Frame version. In the meantime, you can use [master-builds](https://cdn.jsdelivr.net/gh/aframevr/aframe@52136de6a863f32d8cb806b65c3c3223f6b0f8a3/dist/aframe-master.min.js)
