### ISSUE TITLE
Canvas texture automatic updates

### ISSUE THREAD

**Issue by vtrykoz** [aframevr/aframe#4878]
Docs clearly say "The texture will automatically refresh itself as the canvas changes" – but why it says "automatically" while this never work without manual "material.map.needsUpdate = true"? What this sentence really mean?

- A-Frame Version: 1.2.0
- Platform / Device: any platform
- Reproducible Code Snippet or URL: https://aframe.io/docs/1.2.0/components/material.html#canvas-textures

**Comment by dmarcos** [comment]
Good catch. That’s no longer true for performance reasons. We need to update docs. Example on how to update the canvas

https://github.com/aframevr/aframe/blob/b164623dfa0d2548158f4b7da06157497cd4ea29/examples/test/canvas-texture/components/canvas-updater.js
