### ISSUE TITLE
[feature request] aframe gui

### ISSUE THREAD

**Issue by marcusx2** [aframevr/aframe#4889]
Something [like this](https://doc.babylonjs.com/divingDeeper/gui/gui#how-to-use-babylon-gui) would be really nice. Being able to define a UI in world space or screen space. I know about [aframe-gui](https://github.com/rdub80/aframe-gui), but it seems to only support world space.

**Comment by dmarcos** [comment]
Thanks for filing. That’s an excellent idea for a 3rd party component. There has been some
attempts as you’ve seen. Check also https://github.com/the-expanse/aframe-material-collection

The feature is though out of the scope of A-Frame core that is just the scaffolding for your application.
