### ISSUE TITLE
360 video demo report 404

### ISSUE THREAD

**Issue by yangkile** [aframevr/aframe#4895]
**Description:**

Access to video at 'https://bitmovin.com/player-content/playhouse-vr/progressive.mp4' from origin 'https://aframe.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by dmarcos** [comment]
The video is no longer available. We have to replace with another one. If you know of any that it's good quality and a license that let us use it on the A-Frame site it will be appreciated.

**Comment by jacob-willden** [comment]
It looks like the video on bitmovin.com is [available through the Web Archive website](https://web.archive.org/web/20170504043842/https://bitmovin.com/player-content/playhouse-vr/progressive.mp4), assuming that it's still allowed to be used. There are also some [Creative Commons-licensed videos on Wikimedia](https://commons.wikimedia.org/wiki/Category:360-degree_videos) that could possibly be used for the A-Frame 360 video example. Hope this helps!

**Comment by dmarcos** [comment]
I found the video in a different URL: https://bitmovin-a.akamaihd.net/content/playhouse-vr/progressive.mp4

Fixed by https://github.com/aframevr/aframe/commit/a109b197a04aa6950a1d4a9dd16bb1ed8dd333e2

**Comment by dmarcos** [comment]
@jacob-willden Thanks for the video references. Those might come handy
