### ISSUE TITLE
Click/hover event listener doesn't work after refresh (cursor-listener)

### ISSUE THREAD

**Issue by hassan-algo** [aframevr/aframe#4904]
**Description:**

- A-Frame Version: 1.2.0
- Platform / Device: Desktop
- Reproducible Code Snippet or URL: https://virtualcabin.ounodemo.co.uk

When site's loaded for the first time everything works fine but clickables/hoverables stops working after refresh. When Cache is cleaned everything start working again.

**Comment by dmarcos** [comment]
It's going to be hard to narrow down the issue in your application. Can you provide a simple scene that reproduces the issue? Glitch is great! https://glitch.com/~aframe Thanks!

**Comment by hassan-algo** [comment]
I made it work some how
the issue occurred because **I had dynamic scenes and the Raycast ends up loading before the data arriving.** 
So I made a PHP file that generates an html file of the scene and then I just show that file to every user
And I just run the file every time I do some changes in database
