### ISSUE TITLE
Support for glTF+Meshopt assets ("EXT_meshopt_compression")

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#4909]
Would we want to support glTF models with Meshopt compression? See https://github.com/google/model-viewer/issues/1164 for some discussions of the benefits, and https://github.com/google/model-viewer/pull/2706 for an example implementation; mostly we just have to load a 6 KB decoder script (e.g. from unpkg) similar to what we do for the Draco decoder. I'd be happy to make a PR here if we're interested.

**Comment by dmarcos** [comment]
It sounds like a great idea. PR always loved! ❤️
