### ISSUE TITLE
Support for glTF+KTX2/Basis textures ("KHR_texture_basisu")

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#4919]
The KTX2 (".ktx2") texture format uses Basis Universal compression to provide several benefits:

1. Much lower in-memory size for textures.
2. Much faster GPU upload for textures.
3. (Sometimes) Lower file/transmission size for textures.

In combination these make it possible to use more texture detail at lower performance cost in a scene, and these textures can also be embedded in glTF files.

Adding support in A-Frame would be straightforward (similar to https://github.com/aframevr/aframe/pull/4910) except for one issue —  KTX2Loader.js is in `examples/jsm` and there's no `examples/js` equivalent. Does A-Frame's three.js fork have an existing way of pulling in `examples/jsm` files? Or should we ask to have the `examples/js` version created on the three.js repository?

**Comment by dmarcos** [comment]
Thanks so much. Not sure what's the best way to handle. An `examples/js` version would be great is possible. Would that be something reasonable for the THREE folks?

**Comment by donmccurdy** [comment]
Let's give it a try! Opened https://github.com/mrdoob/three.js/pull/22485. If that gets merged we'll need to import `THREE.KTX2Loader` and its dependency, `THREE.WorkerPool`.

**Comment by dmarcos** [comment]
> Let's give it a try! Opened [mrdoob/three.js#22485](https://github.com/mrdoob/three.js/pull/22485). If that gets merged we'll need to import `THREE.KTX2Loader` and its dependency, `THREE.WorkerPool`.

It seems it got merged. Yeeeeah! Thanks so much

**Comment by XrayBravoGolf** [comment]
Is there any updates

> Let's give it a try! Opened [mrdoob/three.js#22485](https://github.com/mrdoob/three.js/pull/22485). If that gets merged we'll need to import `THREE.KTX2Loader` and its dependency, `THREE.WorkerPool`.

Were there any work-in-progress of the KEX2Loader being put into A-Frame right now? As of today my build out of the master branch (latest commit 9e0cea) still gives this warning:
> components:gltf-model:warn THREE.GLTFLoader: setKTX2Loader must be called before loading KTX2 textures 
, thus I assume it has not been made part of this project yet.

**Comment by XrayBravoGolf** [comment]
By the way, is the fact that A-Frame is using the super-three instead of the THREE directly from mrdoob/three.js going to affect this KTX2 loader issue?

**Comment by dmarcos** [comment]
@XrayBravoGolf No, the super-three fork doesn't have any changes concerning `KHR_texture_basisu`. Functionality should be identical to THREE

**Comment by jameskane05** [comment]
@donmccurdy @dmarcos I'm working on a PR attempting to add KTX2 texture compression support to A-Frame `gltf-model` using the same pattern used for Draco compression support:

https://github.com/jameskane05/aframe/pull/1/files https://github.com/jameskane05/aframe/pull/1

Trying to edit `examples/js/test/model.html` as an example in the above PR, but still getting an error about THREE.PoolWorkers() (which I can't find evidence of anywhere...) while trying to load the transcoder files from a CDN folder. Again, this is how it's handled for Draco, I'm assuming it's the same. And the three.js KTX2 example sets a relative path in the same way:

https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_texture_ktx2.html#L79

Seems close unless I'm missing something! Here's where I'm leaving it for tonight:

![image](https://user-images.githubusercontent.com/11968217/186551049-fa4d4efc-504e-4b58-a013-74049ea9a6e2.png)

**Comment by jameskane05** [comment]
@donmccurdy rereading your comment more closely from: https://github.com/mrdoob/three.js/pull/24398

"I think it may be easier just to make a custom KTX2Loader build for A-Frame if necessary."

Is that to say that the super-three version of the KTX2Loader is problematic w/ A-Frame for some reason? You mentioned WorkerPool specifically, which I'm already running into. That's here:

https://github.com/supermedium/three.js/blob/super-r141/examples/js/loaders/KTX2Loader.js

**Comment by donmccurdy** [comment]
The super-three version of KTX2Loader is OK I think, we've just stopped releasing new UMD (`examples/js`) versions of this loader, and future releases will just have the ESM (`examples/jsm`) versions. [WorkerPool](https://github.com/mrdoob/three.js/blob/dev/examples/js/utils/WorkerPool.js) would need to be included in the A-Frame builds alongside KTX2Loader.

**Comment by jameskane05** [comment]
Gotcha, so I do see WorkerPool in super-three: https://github.com/supermedium/three.js/blob/super-r141/examples/jsm/utils/WorkerPool.js

Trying to require() this as we're doing with the other scripts.

![image](https://user-images.githubusercontent.com/11968217/186681455-274846dc-665b-4a1d-a3c8-cccd410f1336.png)

But it complains about how this class is exported:

![image](https://user-images.githubusercontent.com/11968217/186681825-ac21f419-4337-4405-ace9-496b7df9a773.png)

If you look at the rest of the requires, the classes are wrapped in this function syntax, which.


![image](https://user-images.githubusercontent.com/11968217/186683083-6e84e0cb-7f16-4b9c-a845-1348e9d67274.png)


I get a little lost on the vagaries of intra-version JS, I assume this is some ES5 vs. 6 thing? Is there a better way to include the WorkerPool scrpt?

**Comment by donmccurdy** [comment]
I think you'll need to import the `examples/js` (UMD) version rather than the `examples/jsm` (ESM) version, since A-Frame doesn't support ES Modules in the build process. The UMD option just ensures that whatever you import gets attached to the global window.THREE object.

**Comment by jameskane05** [comment]
Got it working! Going to format the example a bit better and create a PR shortly 👍 

![image](https://user-images.githubusercontent.com/11968217/186695589-ad5b707b-3ea1-44a7-9445-55399d1dd424.png)

**Comment by vincentfretin** [comment]
@dmarcos you can close this issue.

**Comment by dmarcos** [comment]
thanks. closing as per request.
