### ISSUE TITLE
Add SVG loading ability

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#493]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Thursday Sep 17, 2015 at 23:15 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/158_

---

Enables the dev to use vector SVG elements. Add to either a generic vr-image component, to a new dedicated svg component, or do both?

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Wednesday Oct 21, 2015 at 18:50 GMT_

----

Interesting techniques: https://css-tricks.com/rendering-svg-paths-in-webgl/

**Comment by RangerMauve** [comment]
This would be pretty cool to have. Maybe if the component took the first child `<svg>` tag, then used the [data-uri trick](http://getcontext.net/read/svg-images-on-a-html5-canvas) to convert it into a texture?

**Comment by RangerMauve** [comment]
Mostly interested in this because it could be a declarative alternative to what's being worked on in https://github.com/aframevr/awesome-aframe/pull/41

**Comment by 7dir** [comment]
[https://threejs.org/docs/#Examples/Loaders/SVGLoader](https://threejs.org/docs/#Examples/Loaders/SVGLoader)

**Comment by 7dir** [comment]
### Welcome aframe-svgpath-component

[aframe-svgpath-component](https://github.com/7dir/aframe-svgpath-component)

[demo](http://7dir.ru/aframe-svgpath-component/)

**Comment by ngokevin** [comment]
Awesome thanks, will look to get it for the Registry! I've also done this before, but haven't released.

**Comment by 7dir** [comment]
@ngokevin maybe later

thanks to a-frame )

**Comment by 7dir** [comment]
` look to get it for the Registry` size (KB) seems too big now
IMHO

**Comment by 7dir** [comment]
I finished  load from SVG files
will publishing it later

**Comment by ngokevin** [comment]
You're including A-Frame in your bundle. I recommend using `angle` for a component template.

```npm install -g angle && angle initcomponent```

**Comment by morandd** [comment]
@7dir  - any update? Even rough code would be appreciated; save me from re-coding the wheel. Thanks

**Comment by 7dir** [comment]
@morandd Hi!
I did it for myself but forgot where.
Realease library become too big.

So U need only add ability to load svgPath data from file.

```js
AFRAME.registerComponent('svgpath', {
  schema: {
    color: {type: 'color', default: '#c23d3e'},
    svgPath: {type: 'string', default: 'M 15,1 29,37 H 15 L 1,1 Z'}
  },
  multiple: false,
  init: function () {
    var data = this.data;
    var el = this.el;
    var createGeometry = require('three-simplicial-complex')(THREE);
    var svgMesh3d = require('svg-mesh-3d');
    var meshData = svgMesh3d(data.svgPath, {
      delaunay: true,
      clean: true,
      exterior: false,
      randomization: 0,
      simplify: 0,
      scale: 1
    });
    this.geometry = createGeometry(meshData);
    this.material = new THREE.MeshStandardMaterial({ color: data.color });// Create material.
    this.mesh = new THREE.Mesh(this.geometry, this.material);// Create mesh.
    el.setObject3D('mesh', this.mesh);// Set mesh on entity.
  },
  update: function (oldData) { },
  remove: function () { },
  pause: function () { },
  play: function () { }
});
```

Remind me tomorow please https://github.com/7dir/aframe-svgfile-component

**Comment by 7dir** [comment]
updated https://github.com/7dir/aframe-svgfile-component

**Comment by 7dir** [comment]
@ngokevin ping
update regestry please
