### ISSUE TITLE
Cursor with rayOrigin mouse and ortho camera does not intersect entities as expected

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe#4935]
**Description:**

When in orthographic camera view, it is only possible to select an entity directly within the center of the canvas, clicking other entities in the scene does not select them.

(To reproduce go to inspector, choose top-down or other ortho view, click an entity directly in the center of the frame -- it works, click an entity outside the center of the frame -- it is not selected)

- A-Frame Version: 1.2+
- Platform / Device: Desktop
- Reproducible Code Snippet or URL: any a-frame scene, press ctl-alt-i to open inspector

**Cause:**

The cursor component updates the raycaster origin and direction at `onMouseMove`: https://github.com/aframevr/aframe/blob/b164623dfa0d2548158f4b7da06157497cd4ea29/src/components/cursor.js#L196

In this function, it sets origin and direction here:
https://github.com/aframevr/aframe/blob/b164623dfa0d2548158f4b7da06157497cd4ea29/src/components/cursor.js#L224

This corresponds to the three.js raycaster's perspective case:
https://github.com/mrdoob/three.js/blob/master/src/core/Raycaster.js#L34

But there is no corresponding case to handle ortho mode in the A-Frame cursor.

**Proposed solution:**
Copy the three.js solution to check for camera type to use separate origin and direction method for ortho and perspective.

Replace lines 224 and 225 here:
https://github.com/aframevr/aframe/blob/b164623dfa0d2548158f4b7da06157497cd4ea29/src/components/cursor.js#L224

Replace with:
```
      if (camera && camera.isPerspectiveCamera) {
        origin.setFromMatrixPosition(camera.matrixWorld);
        direction.set(mouse.x, mouse.y, 0.5).unproject(camera).sub(origin).normalize();
      } else if (camera && camera.isOrthographicCamera) {
        origin.set(mouse.x, mouse.y, (camera.near + camera.far) / (camera.near - camera.far) ).unproject(camera); // set origin in plane of camera
        direction.set(0, 0, -1).transformDirection(camera.matrixWorld);
      } else {
        console.error( 'AFRAME.Raycaster: Unsupported camera type: ' + camera.type );
      }
```

**Comment by kfarr** [comment]
This fix appeared to fix the issue on a local version, I can create a PR if helpful. Should I only commit changes to aframe/src/components/cursor.js or are there other files to commit as well?

**Comment by dmarcos** [comment]
Thanks! A PR on `cursor.js` will be super appreciated.
