### ISSUE TITLE
Define animations in seconds or milliseconds

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#494]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Friday Sep 18, 2015 at 00:59 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/159_

---

Enables devs to specify the timing unit of their choice. Defaults to seconds if no unit is specified.

Per [transition-duration](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration), we will enable devs to specify `1`, `1s`, or `1000ms`.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Wednesday Sep 23, 2015 at 01:07 GMT_

----

@dmarcos can you elaborate on why you don't want to see this (following up on your Slack comment)?

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Wednesday Sep 23, 2015 at 02:20 GMT_

----

Good APIs have a single way to do each thing. Pick ```ms``` or ```s``` but stick with one. Supporting multiple ways to do one thing is a high risk of introducing bugs (there are no conversions, no parsing and no contortions to compare and add values), compromises consistency, it clutters the code, increases maintenance and makes it harder to evolve. And the upside for the user is not as good as you would imagine. It's easier to teach and reason about when you say: Whenever you see time in this library is ms, full stop. You never have to stop and think. Is this ms or s? There's less risk of misuse or mixing units and shoot yourself in the foot.

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Wednesday Sep 23, 2015 at 05:56 GMT_

----

this has worked fine for [CSS transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration#Syntax). what if we enforced a unit? it must be `ms` or `s`.

my concern with going with `s` is that folks are going to have to do math (move decimal points). what's `50ms` in seconds? that's `0.05s`. idk, seems clumsy when both can be supported (or only `ms`). working in `ms` isn't as bad as working in `s` (in my CSS and JavaScript experience).

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Wednesday Sep 23, 2015 at 06:32 GMT_

----

Point taken, @dmarcos. Most content creation packages provide built in conversions. If my Illustrator scene is in meters and I specify a transform as 40cm, it converts it automatically to .4m. Cinema 4D does the same, as does AE. I envision enabling users to specify seconds if they really want, but defaulting to ms, and doing conversions behind the scenes.

Point also taken on math @cvan. Whether the user works in ms or seconds will depend on length of composition, desired precision, etc. 1050 is better than 1.05, maybe. But is `delay="32,500"` better than `delay="32.5"`? Etc. Here too, a solution is acknowledging that one size cannot adequately fit all, and judiciously allowing for some flexibility.

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Wednesday Sep 23, 2015 at 08:13 GMT_

----

Throwing a vote in, although I understand design-by-committee can be sometimes irksome. I'm in favor for mirroring the CSS3 transition spec, I would think that is what most web developers would expect. Although we should strive for a small API surface area, there are cases when we might make it too restrictive.

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Tuesday Oct 06, 2015 at 20:40 GMT_

----

FYI: I wrote the code to support `'s'` seconds and `'ms'` milliseconds (and default to milliseconds if no unit is provided). If anyone wants to eventually resurrect this, here's the original PR: https://github.com/MozVR/vr-markup/pull/208

**Comment by ngokevin** [comment]
Accidentally closed during merge

**Comment by dmarcos** [comment]
Not sure if logic to parse / convert units justifies the value. I'm happy to close this. @ngokevin ?
