### ISSUE TITLE
Text entities are broken - emits aframe error and will not render

### ISSUE THREAD

**Issue by cameronValtech** [aframevr/aframe#4943]
I've just tried adding text to my scene and immediately ran into an error that halted program/scene execution.

Console Errors...

**iOS / Safari**

Commit master @ 373af37
```
[Log] core:a-node:error Failure loading node:   (main.bundle.js, line 2346)
TypeError: Cannot call a class constructor without |new|
BufferGeometry — aframe-master.js:13951
TextGeometry — aframe-master.js:49538
createTextGeometry — aframe-master.js:49534
init — aframe-master.js:62667
initComponent — aframe-master.js:67259
updateProperties — aframe-master.js:67241
updateComponent — aframe-master.js:65921
updateComponents — aframe-master.js:65894
entityLoadCallback — aframe-master.js:65680
emitLoaded — aframe-master.js:66608
promiseReactionJob

```

**Android / Chrome**

```
aframe-master.js:2201 core:a-node:error Failure loading node:   TypeError: Class constructor BufferGeometry cannot be invoked without 'new'
    at new TextGeometry (main.bundle.js:49683)
    at createTextGeometry (main.bundle.js:49679)
    at NewComponent.init (main.bundle.js:62812)
    at NewComponent.initComponent (main.bundle.js:67404)
    at NewComponent.updateProperties (main.bundle.js:67386)
    at HTMLElement.value (main.bundle.js:66066)
    at HTMLElement.value (main.bundle.js:66039)
    at entityLoadCallback (main.bundle.js:65825)
    at emitLoaded (main.bundle.js:66753)
```

As far as I can tell, the first broken commit is at 5039c61 (at least based on changing the commit in package.json + `yarn && yarn start`). This particular commit merged and performed a dist build where a THREE version bump was made (see 411b407). Before this, text seemed to render just fine.

- A-Frame Version: 1.2.0 / master @ 5039c61 through 373af37 (and probably beyond)
- Platform / Device: 
  - Safari - Mobile + Desktop, 
  - Chrome / Desktop (responsive)
  - Chrome / Android - Samsung Galaxy S7
- Reproducible Code Snippet or URL:

The offending text entity:

```
<a-text
    value="Hello world!"
    font="exo2semibold"
    color="pink"
    ></a-text>
```

As alluded to above, I've installed aframe via yarn and it's been working fine until I tried adding text. I wish I could go back to the final working commit, but since then another (more) critical bug has been resolved, so I'm stuck at a relatively new version.

* `yarn add aframe` --> text works, but I've got my bug (the npm tag is rather old compared to master)
* aframe @ https://github.com/aframevr/aframe.git#373af37" --> current HEAD, broken, all the way back to 5039c61

The general layout of my application uses webpack and js modules, so I'm able to inject an aframe scene into the DOM and then add various objects into the scene as a network request completes. As I've said, that's been working fine. This is new.

I've seen some other comments about ray casters, but I didn't find a solution for my issue. That said, _I am making use of a raycaster for tap events_ (also works fine).

**Comment by dmarcos** [comment]
One extra note. If you are using the environment component make sure to use the 1.3.0 version

**Comment by dmarcos** [comment]
I think this should be fixed in master. You can try https://cdn.jsdelivr.net/gh/aframevr/aframe@9a611ec968ce8edfd2fa7da68ead0fe70dc0c0df/dist/aframe-master.min.js
