### ISSUE TITLE
Layers origin of coordinates

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4947]
In this example one can switch layers on and off by pressing thumbtstick:

https://aframe.io/aframe/examples/showcase/comicbook/

In previous versions of the Oculus browser non layered texture and layered quad used to overlap. There's now an offset in the vertical axis. That code hasn't changed in several months. I think something is different either in the layers API or the browser implementation. Trying to figure out.

@cabanier Are there any known changes in the coordinate system of the layers? This is where we set [XRRigidTransform](https://github.com/aframevr/aframe/blob/master/src/components/layer.js#L352)

Thanks so much and sorry to bother you.

**Comment by cabanier** [comment]
@dmarcos I'm not aware of any change in our implementation.
I'll take a look.

**Comment by cabanier** [comment]
@dmarcos could this be related to the [recent patch](https://github.com/aframevr/aframe/commit/364ae4e9b89aa9cf9a95310f0c7ea8a739ca4b58#diff-7aa6b04a29aef954c017c80ddb4e9a941dfed12e7c4a08a84cf3d604f64b8b83) which changes how orientation is calculated?

**Comment by dmarcos** [comment]
Thanks for looking at this. That patch has not been released yet. The code in the examples uses A-Frame 1.2.0 that hasn't changed sine February. The layer and non-layered texture in the example I pointed out used to overlap in previous browser versions. It's no longer the case:

https://aframe.io/aframe/examples/showcase/comicbook/

Maybe something in the layers spec or implementation has changed that we have to account for now. The offset is only in the y-axis. I was wondering if maybe the origin of coordinates for the layers has changed.

**Comment by dmarcos** [comment]
Yeah it's same behavior for both master and 1.2.0. 

Are we supposed to account for the floor height to position the layer?

We're now applying the world position of the camera. 

https://github.com/aframevr/aframe/blob/v1.2.0/src/components/layer.js#L352

**Comment by dmarcos** [comment]
@cabanier I did a bit more investigation. To position the layer in the same location as the non-layer texture I'm copying the position and quaternion of the matrix world over to the XRRigidTransform of the layer:

```
    // Non layered texture.
    el.object3D.updateMatrixWorld();
    position.setFromMatrixPosition(el.object3D.matrixWorld);
    quaternion.setFromRotationMatrix(el.object3D.matrixWorld);
    this.layer.transform = new XRRigidTransform(position, quaternion);
```

It's what expect except for an offset in the y axis. By removing the camera height it looks both layer and non-layer almost overlap. Code below:

```
      // Non layered texture.
    el.object3D.updateMatrixWorld();
    position.setFromMatrixPosition(el.object3D.matrixWorld);
    quaternion.setFromRotationMatrix(el.object3D.matrixWorld);
    // subtract camera height.
    position.y -= el.sceneEl.camera.el.object3D.position.y; 
    this.layer.transform = new XRRigidTransform(position, quaternion);
```

My current theory is that the browser is not honoring the XRRigidTransform transform set on the layer (I expect that to represent the world coordinate of the layer) and adding the camera offset afterwards. I think the behavior has recently changed in the Oculus Browser. Is this a possibility? Thanks so much for looking into this.

**Comment by cabanier** [comment]
I'm sorry that I didn't get to it yet. Other things took priority.

**Comment by dmarcos** [comment]
No problem. Thanks for the update. Let me know if there's anything I can do to help.

**Comment by snagy** [comment]
Hi @dmarcos !

I'm new to the Oculus Browser team and looked into this for a little bit; it seems that the cause of the offset is because the default XRReferenceSpace (for three.js and aframe) is "local-floor", but the comic book example is requesting "local" as the reference space for the layer.  Because of this, the main scene (where the object lives) and layer have a delta in the Y position of their reference spaces.  Switching the layer to use local-floor lines them both up precisely.

I'm not sure why this behavior may have changed; it seems like the current functionality is the correct behavior.

**Comment by dmarcos** [comment]
@snagy good catch! thanks! Sorry for taking your time. I should have thought about that too. I was just a bit confused that same code used to work. Thanks again.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/4991
