### ISSUE TITLE
VRLoader fails on `MessageChannel` when unsupported in stable Firefox, Chrome

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#495]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Friday Sep 18, 2015 at 19:08 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/162_

----

```
ReferenceError: MessageChannel is not defined
```

<img width="1039" alt="screenshot 2015-09-18 12 08 35" src="https://cloud.githubusercontent.com/assets/203725/9968543/e825e6f0-5dfd-11e5-979a-5e712a4a37e9.png">

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Friday Oct 23, 2015 at 00:45 GMT_

----

Is this one still relevant?

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Friday Oct 23, 2015 at 01:11 GMT_

----

yep

**Comment by cvan** [comment]
we're not using VRLoader anymore
