### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR 

### ISSUE THREAD

**Issue by gamedust-ph** [aframevr/aframe#4954]
**Description:**

- A-Frame Version: 1.2.0
- Platform / Device: web. mobile :android/iPhone, VR 
- Reproducible Code Snippet or URL:
- net::ERR_SSL_PROTOCOL_ERROR 200 (OK)

I have tried this in heroku and aws server .

Need help if you can provide information to fix this error.

http://3.91.208.147/

**Comment by gamedust-ph** [comment]
GET https://s3.us-east-2.amazonaws.com/hdfx-events.biz/hdfx-events.biz-product_view/amusement_land_ferris_wheelv2.glb net::ERR_SSL_PROTOCOL_ERROR 200 (OK)
load @ three.js:26961
value @ a-assets.js:109
value @ a-register-element.js:160
m @ document-register-element.js:2
l @ document-register-element.js:2
(anonymous) @ document-register-element.js:2
r @ document-register-element.js:2
(anonymous) @ document-register-element.js:2

**Comment by dmarcos** [comment]
This looks like a server misconfiguration not specific to A-Frame. Your URL is served over `HTTP` and you're trying to access a resource over `HTTPS`. More info:

https://stackoverflow.com/questions/43232686/how-to-deal-with-neterr-ssl-protocol-error

Serve your page over HTTPS.
