### ISSUE TITLE
Wrong Oculus Quest controller models (swapped over?)

### ISSUE THREAD

**Issue by diarmidmackenzie** [aframevr/aframe#4960]
**Description:**

As reported in this Stack Overlfow query...
https://stackoverflow.com/questions/69914097/oculus-quest-2-controller-models-do-not-properly-loaded-in-a-frame

- A-Frame Version: 1.1.0, 1.2.0 and master
- Platform / Device: Oculus Quest 2
- Reproducible Code Snippet or URL: https://aframe.io/aframe/examples/test/laser-controls/ 

When using this URL (or many others) on Oculus Quest 2, the Oculus Quest 1 controllers are visible.

Looking at this change, it appears that URLs for controller models are supposed to be...

https://github.com/aframevr/aframe/commit/4705cda1cb8bfab5219da6fab78c8825047996bb

https://cdn.aframe.io/controllers/oculus/oculus-touch-controller-left.gltf for Quest 1
https://cdn.aframe.io/controllers/oculus/oculus-touch-controller-gen2-left.gltf for Quest 2
https://cdn.aframe.io/controllers/oculus/oculus-touch-controller-v3-left.glb for Quest 3

But looking at what the CDN is serving (using this to check the GLTFs), the gen2 and gen1 models seem to be switched around.

https://cdn.aframe.io/controllers/oculus/oculus-touch-controller-left.gltf (intended to be Quest 1) looks like this...

![image](https://user-images.githubusercontent.com/16045703/141333213-a43b9617-519c-4335-b2df-c4322e207f88.png)

https://cdn.aframe.io/controllers/oculus/oculus-touch-controller-gen2-left.gltf (intended to be Quest 2) looks like this...

![image](https://user-images.githubusercontent.com/16045703/141333357-43007e51-54ff-463b-99d8-9747104ce1f1.png)

**Comment by dmarcos** [comment]
Nothing has changed and this used to work. Oculus Browser might have changed the [profileId reported by the WebXR API](https://github.com/immersive-web/webxr-input-profiles/tree/main/packages/assets/profiles)? Sorry don't have my quest to test with until Monday.

@rcabanier @snagy Does this ring a bell? Thanks!

**Comment by diarmidmackenzie** [comment]
OK, so based on comments here I've realized that...
"oculus-touch-controller" was the 1st Oculus Touch controller (for the Rift)
"oculus-touch-controller-gen2" was the 2st Oculus Touch controller (for the Rift / Quest 1)
"oculus-touch-controller-v3" was the 3rd Oculus Touch controller (for the Rift / Quest 2)

In that case I agree the models look aligned.

So it seems like the problem must be that my Quest 2 (and other Quest 2s) has started reporting itself as a Quest 1.

**Comment by diarmidmackenzie** [comment]
For reference, my Oculus Browser version at the time of seeing this problem is:
17.2.0.9.61.329948727

Chromium version:
93.0.4577.82

And in the Main Quest 2 settings:

System version:
20169900217500000

Version:
34.0.0.91.366.328965050

Runtime Version:
34.0.0.92.366.328963448

**Comment by diarmidmackenzie** [comment]
Confirmation that this is not actually an A-Frame issue - I see the exact same thing in this Babylon.js example.

https://playground.babylonjs.com/#9K3MRA

(I didn't test this previously so not 100% sure that it used the old controllers before, but it seems likely this is the exact same problem).

**Comment by diarmidmackenzie** [comment]
I've also noticed the same problem in the Firefox Reality browser.  Not just when browsing pages, but even in the Firefox Reality "overworld" when viewing pages, the controller is the same earlier (black) model.

I don't think Firefox Reality uses the Oculus Browser, so that suggests the problem is rooted at a lower level than that?

I have raised a ticket with Oculus Support, as I now think this an Oculus problem, not an A-Frame problem.  However if A-Frame can provide smoking gun diagnostics showing the problem, that could be useful.  I don't know how to trace the WebXR APIs.

**Comment by dmarcos** [comment]
@diarmidmackenzie thanks for the investigation! if you have some time can you check the profiles on the controller?

With the controller tracking you can do the following on the entity with the controller:

`controllerEl.components['tracked-controls-webxr'].controller.profiles`

It will probably be revealing to see what that array contains. Thanks again!

**Comment by diarmidmackenzie** [comment]
Sorry this took a while... controller profiles data looks like this:

![image](https://user-images.githubusercontent.com/16045703/142031687-c4d8fb32-b3ef-4c02-add9-cdb3daa53c3e.png)

So it's reporting oculus-touch-v2 (i.e. the Quest 1 controller) and so that's what A-Frame shows.

Not sure what we can do about this?

I have been in contact with Oculus Support, but so far the only advice I have received is to try:
- power cycling the device
- a factory reset.

So I don't think I'm going to be able to get any serious engagement from them.

**Comment by dmarcos** [comment]
This is a bug on the Oculus browser side where controllers are reported as Rift ones. Oculus folks already working on it and there will be a fix in the next browser version.

Thanks everybody for reporting and investigating

**Comment by dmarcos** [comment]
Has this been fixed already on the Oculus Browser side?

**Comment by diarmidmackenzie** [comment]
Yes, not seen this for quite a while.  Pretty sure it was fixed before 1 Dec.
