### ISSUE TITLE
Setting controller model color using laser-controls, oculus-touch-controls, etc

### ISSUE THREAD

**Issue by arvind-iyer** [aframevr/aframe#4961]
**Description:**
laser-controls has a parameter called defaultModelColor although it doesn't actually do anything. 
oculus-touch-controls allows you to set the button colors but not the color of the body itself. 

My app is pretty dark and my oculus controller shows as black by default in VR and I can barely make out any detail on it. 

- A-Frame Version: 1.2.0
- Platform / Device: Oculus Quest 2
- Reproducible Code Snippet or URL:
``` 
<a-entity laser-controls="hand: left; defaultModelColor: white"></a-entity>
<a-entity oculus-touch-controls="hand: right;"></a-entity> <!-- maybe a 'color' attribute might be handy here? --> 
```

**Comment by dmarcos** [comment]
defaultModelColor is the color of the controller default model. The controller default model is the fallback model used with a headset where we don’t have vendor specific controller model. There’s no way to change the controller color at the moment. You could edit it though in your 3D package of choice and load your custom one
