### ISSUE TITLE
Microsoft Hololens 2 Support

### ISSUE THREAD

**Issue by ericdacal** [aframevr/aframe#4968]
**Description:**

- A-Frame Version: 1.0.4
- Platform / Device: Microsoft Hololens 2
- Reproducible Code Snippet or URL:

Actually Microsoft Hololens doesn't have any support. Will it be included in aframe?

Thanks,

**Comment by dmarcos** [comment]
As far as I know the Hololens browser has WrbXR support. Make sure you are using A-Frame 1.2.0

**Comment by dmarcos** [comment]
Does A-Frame 1.2.0 work?

**Comment by dmarcos** [comment]
I think Hololens browser in its latest version + A-Frame 1.2.0 should work. Closing this and can reopen if necessary.
