### ISSUE TITLE
https://caniuse.com/webxr says it does not work and yet on my IOS Mobile Chrome, Safari and Firefox do work ?

### ISSUE THREAD

**Issue by gedw99** [aframevr/aframe#4981]
**Description:**

- A-Frame Version: latest examples on the web site
- Platform / Device: IOS Safari, chrome and firefox
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/helloworld/

https://caniuse.com/webxr says that webXR does not work on the browsers i tested and yet it does work.

I cant understand whats going on..

Can someone enlighten me ?

**Comment by dmarcos** [comment]
A-Frame ships with a polyfill providing basic compatibility with cardboard kind of devices.

WebKit (that all browsers on iOS use) doesn’t implement WebXR.

I hope that clarifies.

I recommend joining the [community in the Discord channel](https://aframe.io/community/) for questions.

We use Github issues for bug reports and feature requests. Thanks for understanding.
