### ISSUE TITLE
Colors washed out when setting background color

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4989]
The hello world [scene sets an off-white color as background](https://github.com/aframevr/aframe/blob/master/examples/boilerplate/hello-world/index.html#L10). Changes recently introduced in the background component trigger the generation of a background cubemap washing out the colors of the scene. 

I think in this case we wouldn't want to generate the cubemap and preserve the original colors. I [opened a PR](https://github.com/aframevr/aframe/pull/4990) changing the defaults of the background component. They fix the hello world scene but not sure if the fix is appropriate. 

@AdaRoseCannon Do you have any feedback? You're the expert on this 😃 Thanks so much

![image](https://p199.p4.n0.cdn.getcloudapp.com/items/2NuvyE9n/d49eb115-895f-4d6f-99ac-e7136fe756ad.jpg?source=viewer&v=8519d262f809e58ba672dc6a6c24991d)

**Comment by AdaRoseCannon** [comment]
I'd rather have the default behavior on to make materials with reflections default to looking correct. but since background isn't set by default I don't have a really strong preference, whichever you prefer. Although if it is off by default perhaps the name seems to be simpler, something like just `environment`?

**Comment by dmarcos** [comment]
About naming. Maybe something more specific? e.g `defaultReflectionEnvironment`

Yeah I agree that having materials with reflection work out of the box would be nice. Wondering if we should move the logic to a different component. Maybe [renderer](https://aframe.io/docs/1.2.0/components/renderer.html#sidebar) that it's always defined or a separate new component.

For basic scenes that one just want to play with basic colors the reflections get on the way. That makes me think about old conversations where some people thought that perhaps the A-Frame default materials shouldn't be `standard` aka PBR but something simpler, perhaps Phong. Any thoughts?

**Comment by AdaRoseCannon** [comment]
The reflection logic is pretty complex moving it to it's own component sounds sensible. I can do that a few weeks probably. (Can do it sooner if time is of the essence)

That's not a bad idea regarding changing the default material, if the default material was phong with reflectivity set to 0 then, it would be unaffected by reflection/refraction and it would be a significant performance improvement.

The only downside is that objects imported via gltf would appear with slightly more accurately lighting than the default objects.

**Comment by dmarcos** [comment]
Thanks for the feedback. Good point about possible inconsistencies when mixing primitives and models.

No rush about separating. It would be nice for code hygiene. More important would be what's best functionality-wise. I agree that it would be nice to have nice reflections by default when appropriate. Not sure yet how to handle the case with primitives and basic colors where reflections don't look as good. 

I'll disable for now the reflections by default for A-Frame 1.3.0 and can rethink for 1.4.0

**Comment by AdaRoseCannon** [comment]
Sounds good, btw the next version of THREE.js fixes the reflections in Lighting Estimation if I am reading this correctly. Once that is in AFrame I will probably refactor the code into a new component as I make the fixes.

https://github.com/mrdoob/three.js/issues/22236

**Comment by dmarcos** [comment]
I bumped A-Frame three fork to the latest `dev` THREE branch. Fixes should be in place if you want to go ahead.

I'm closing this issue and opened https://github.com/aframevr/aframe/issues/4992 to keep track
