### ISSUE TITLE
<a-video> with positional audio?

### ISSUE THREAD

**Issue by benallfree** [aframevr/aframe#4996]
Does anyone have an example of how to do this?

I've been working on a codesandbox to get the AudioContext of a video https://codesandbox.io/s/green-pine-zg6sm?file=/src/index.js

I assume there would be a way to then plug it into <a-sound>?

**Comment by dmarcos** [comment]
For usage questions I recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/aframe) or the [Discord, Slack channels](https://aframe.io/community/). Nice friends there to help. We use github issues for bug reports and feature requests. Thanks for understanding. Best of luck!
