### ISSUE TITLE
Please deploy patch version

### ISSUE THREAD

**Issue by juunini** [aframevr/aframe#4998]
A-Frame It's constantly committing.

But, in NPM, aframe version is only 1.2.0
No 1.2.1, 1.2.2, ...

Please deploy patch version.

![Screenshot_20220125-151333_Chrome](https://user-images.githubusercontent.com/41536271/150921281-27fd4c41-1964-4107-a3d7-b055c0ea4288.jpg)

When I want latest version of aframe,
There is no choice but to specify and install the commit hash.

**Comment by dmarcos** [comment]
A new version of A-Frame is coming really soon. Thanks for the patience
