### ISSUE TITLE
Please deploy gh-pages. current version of code.

### ISSUE THREAD

**Issue by juunini** [aframevr/aframe#4999]
https://aframe.io/examples/showcase/handtracking/

This example cause under issue.

![image](https://user-images.githubusercontent.com/41536271/150922703-63c1f388-7a1a-4f99-821e-0479ad4c9b58.png)

But, latest version of code is not cause this issue.

Please, deploy gh-pages. current latest version of code.

**Comment by dmarcos** [comment]
A new A-Frame version is coming out very soon. In the meantime you can use master builds. You can find the links in the commit messages
