### ISSUE TITLE
a-text links in docs broken and show 404

### ISSUE THREAD

**Issue by JGrotex** [aframevr/aframe#5013]
a-text links to the **examples** in docs are broken and show 404, but the `code` link still works.

- A-Frame Version: 1.3.0
- Platform / Device: all
- Reproducible Code Snippet or URL: https://aframe.io/docs/1.3.0/components/text.html

Screenshot ...
![2022-02-22_175915](https://user-images.githubusercontent.com/24936309/155181416-bc90f9d1-2c07-4d47-944b-cf8e1722bbb1.png)

Maybe someone can have a look, or just remove those broken links.

**Comment by dmarcos** [comment]
Thanks

**Comment by JGrotex** [comment]
do you have to regenerate the docs?
The link is here still not working: https://aframe.io/docs/1.3.0/components/text.html

> BTW: the Samples, that I could open from the GH change, look nice!
