### ISSUE TITLE
The version 1.3.0 a-frame does not work in WebView on Android when switching to VR mode

### ISSUE THREAD

**Issue by jhfrek** [aframevr/aframe#5020]
The version 1.3.0 a-frame does not work in WebView on Android 7 when switching to VR mode. Black screen. Without VR mode, it works. Version 1.0.1 works fine both in VR mode and without VR mode. No one knows if something needs to be done in WebView for the new version 1.3.0, or is this a-frame not working? Why does everything work in version 1.0.1, but does not work in VR mode in version 1.3.0?

When switching to VR mode, it shows this:

https://i.stack.imgur.com/eppJE.jpg

**Comment by dmarcos** [comment]
Android 7 seems to be pretty old and afaik it predates the WebXR API that now A-Frame supports. Have you tried in newer versions?

**Comment by ddaydd** [comment]
same,

https://aframe.io/docs/1.3.0/introduction/faq.html#why-is-my-experience-not-entering-vr-or-ar-mode
`If you are using A-Frame 1.3.0 or older you probably need to update to the latest.`

I do not understand the 1.3.0 is not the latest?

**Comment by dmarcos** [comment]
1.3.0 is the latest. We should probably reword the docs. Sorry for that.

FWIW `requestAnimationFrame` no longer fires in WebXR (as it did in WebVR) when in an immersive session. Using tick should work. But I have no context about your issue.

FYI, when I meant trying newer versions I meant newer versions of Android. Android 7 seems old ([2016 and last patch in 2019](https://en.wikipedia.org/wiki/Android_Nougat))

**Comment by jhfrek** [comment]
> Android 7 seems to be pretty old and afaik it predates the WebXR API that now A-Frame supports. Have you tried in newer versions?

Yes! Android 9 doesn't work either. Black screen.

**Comment by dmarcos** [comment]
Is WebXR available in a WebView?

**Comment by jhfrek** [comment]
> Is WebXR available in a WebView?

Yes, android webview does not support WebXR. This is very bad.

**Comment by dmarcos** [comment]
I don't think we can do anything on A-Frame side. Hopefully WebXR is one day available on a WebView context. Closing this and can reopen if necessary.
