### ISSUE TITLE
Mobile version issue 

### ISSUE THREAD

**Issue by dhaneshetraffic** [aframevr/aframe#5022]
I am facing the issue on mobile. I can't drags up and down on the mobile it just drag right to left. Please solve this issue ASAP.

**Comment by tomasbrownnz** [comment]
Use Lorenzo's comment here https://github.com/aframevr/aframe/issues/2557#issuecomment-791951803 to make your own custom look-controls component.

**Comment by dmarcos** [comment]
Yes. This is a design decision. You can derive your own component as @tomasbrownnz described.
