### ISSUE TITLE
Asset loading hangs forever when errors hit loading an asset.

### ISSUE THREAD

**Issue by diarmidmackenzie** [aframevr/aframe#5032]
**Description:**

- A-Frame Version: 1.3.0
- Platform / Device: All
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/assets-dont-timeout-on-error?path=index.html%3A29%3A92

When a URL referred to by an asset is not resolvable, A-Frame scene loading just hangs forever.

See linked Glitch, which is a modified version of this https://aframe.io/examples/showcase/modelviewer/ but with the GLTF URL set to an invalid value.

One reason why it would be nice to initialize the scene, rather than hang forever, is that it would allow application-specific error handling.

I have a potential fix for this that seems to work, which I'll present as a PR.

**Comment by vincentfretin** [comment]
Actually I looked at #2737 and #1155 those two should be closed really.

**Comment by vincentfretin** [comment]
If it's the big glb representing the whole scene that gave an error, I probably want to show the user a message "something went wrong, please try again later" instead of showing a white canvas. If it's smaller glb that may not be so important for the experience,  I may want to still enter the experience, yes, but this is a case by case thing.

**Comment by kylebakerio** [comment]
yes, you can put whatever handling you want there. you can see what element threw the error and handle accordingly. a basic option would be set `localStorage.retryCount = true;' and then `location.reload()`. then, if it happens again, you also have a check; if you see that you've already reloaded, then you just throw an error message to user saying "site is down for maintenance" or something.

and/or just ignore if file is small, which you can see by checking `el.src`.

**Comment by vincentfretin** [comment]
Ok, the choice of showing a message to the user or retry downloading an asset that gave an error can be done in your app. An external library that implement another loader can help with that too.
For aframe core, the logic is currently to load the scene after the timeout, so it actually hide loading screen, and some other glb may finish and appear after the timeout if understand it, at least the is the behavior I see currently.
To be consistent, it should indeed load the scene even if there was an error, which it doesn't do currently, the PR #5033 fixes that.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/commit/5189765cbbd81fc4eefe880045662e33aebd138f
