### ISSUE TITLE
hand-tracking-controls 1.5 y offset required?

### ISSUE THREAD

**Issue by HyroVitalyProtago** [aframevr/aframe#5034]
What is the reason behind the offset of 1.5 in y?

https://github.com/aframevr/aframe/blob/f38bf1545d6bbb3cc821719c355e0d63b0322c19/src/components/hand-tracking-controls.js#L132

https://github.com/aframevr/aframe/blob/f38bf1545d6bbb3cc821719c355e0d63b0322c19/src/components/hand-tracking-controls.js#L258

https://github.com/aframevr/aframe/blob/f38bf1545d6bbb3cc821719c355e0d63b0322c19/src/components/hand-tracking-controls.js#L275

https://github.com/aframevr/aframe/blob/f38bf1545d6bbb3cc821719c355e0d63b0322c19/src/components/hand-tracking-controls.js#L351

**Comment by mrxz** [comment]
I also don't see any reason for the offset. Logically it causes all y values to be under-reported by 1.5, hence the many `y += 1.5`. Didn't notice any regressions after removing it as part of #5298

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/5298
