### ISSUE TITLE
Oculus Quest 2 - how reassigning mesh materials with gltf model and ShaderMaterial 

### ISSUE THREAD

**Issue by spleennooname** [aframevr/aframe#5037]
hello to all, i hope for your help. in a aframe project i'm loading a gltf model; i would like to reassign the material of the mesh of which it is composed with a ShaderMaterial; the component that does this is 'spl-model' and it's in the a-entity node where gltf-model is too

![Schermata 2022-04-09 alle 17 46 25](https://user-images.githubusercontent.com/5708525/162581387-bddaf875-e8d7-4419-bcf5-e82a689db6b8.png)
What I di
splay on desktop in Chrome is what I expect: something like a colored gradient. In Oculus Quest 2 the surfaces remain completely black. Can anyone point me in the right direction? thanks

- A-Frame Version: 1.3.0
- Platform / Device: Oculus Quest 2 / Chrome 100 on Mac Osx (Catalina, 10.15.7)
- Reproducible Code Snippet or URL:

demo:
[https://caudio-webxr.surge.sh/webxr.html?spl=1&wirefame=1](https://caudio-webxr.surge.sh/webxr.html?spl=1&wirefame=1)

link to spl-model component
[https://caudio-webxr.surge.sh/scripts/aframe/components/spl-model.js](https://caudio-webxr.surge.sh/scripts/aframe/components/spl-model.jsl)

**Comment by spleennooname** [comment]
for anyone in the above scenario, i.e. rawshadermaterial applied in traverses to a gltf model

- it seems that setting `light="defaultLightsEnabled: false"` in `<a-scene`> solves the problem

**Comment by dmarcos** [comment]
Glad you found a solution. For the future I recommend joining the discord or using StackOverflow for usage questions. Nice folks there to help:

https://aframe.io/community/

We use github issues for bug reports and feature requests
