### ISSUE TITLE
Please deploy patch version to npm

### ISSUE THREAD

**Issue by juunini** [aframevr/aframe#5038]
AFRAME is continusly update commits.
But, AFRAME is not deploy patch version to npm.
If I want recently version of AFRAME, should insert commit hash when install dependency.
(ex: `npm install "git://github.com/aframevr/aframe.git#<commit>"`)

If not want to doing deploy patch version,
would you add how to install recently version of AFRAME in README?

**Comment by dmarcos** [comment]
You can find master build links in the commit links that can import via script tags:

https://github.com/aframevr/aframe/commits/master

Those are not QAed and are dev in progress so not suitable for NPM that we use for stable versions

You can also generate your own builds as described in the read me:

https://github.com/aframevr/aframe#generating-builds

You could fork aframe, generate new builds and point your npm to it based on commit as you described.

Sorry for the inconvenience but the friction to not use stable versions is deliberate to reduce devs exposure to bugs and unfinished APIs

**Comment by dmarcos** [comment]
I don’t think there’s anything actionable on A-Frame side. Closing this and reopening if necessary
