### ISSUE TITLE
Rift controllers are displayed in Quest 1

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#5041]
Reported by several users. I think the Oculus Browser is reporting `oculus-touch` [profile](https://github.com/immersive-web/webxr-input-profiles/tree/main/packages/registry/profiles/oculus) instead of `oculus-touch-v2`

I couldn't confirm because I don't have a Quest 1 around at the moment. 

@rcabanier Is this a known problem?

**Comment by dmarcos** [comment]
Dev confirmed that Oculus Browser on Oculus Quest 1 reports the controller profile array below:

```
[
  "oculus-touch",
  "generic-trigger-squeeze-thumbstick"
]
```

**Comment by carlosveny** [comment]
This is happening to me. Thought it was my fault but it seems it has nothing to do with me.

**Comment by cabanier** [comment]
This is a known issue on Oculus link but new for Oculus browser.

**Comment by dmarcos** [comment]
Reference to possible cause:

https://bugs.chromium.org/p/chromium/issues/detail?id=1313636

**Comment by dmarcos** [comment]
@carlosveny can you confirm if you were using the Oculus Browser or Chrome on desktop via Link? Thanks

**Comment by carlosveny** [comment]
Actually it only happens on Chrome and Edge using Link. In Oculus Browser works fine. Is there any fix for Link?

**Comment by cabanier** [comment]
> Actually it only happens on Chrome and Edge using Link. In Oculus Browser works fine. Is there any fix for Link?

You can. monitor the chrome bug to see when a fix will land

**Comment by dmarcos** [comment]
Is this still an issue?

**Comment by cabanier** [comment]
No, this was fixed earlier this year

**Comment by dmarcos** [comment]
thanks!
