### ISSUE TITLE
Aframe to windows app. 

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [aframevr/aframe#5044]
Hello, I'm trying to make the aframe windows app in visual studio But getting 4 errors in the Js code. I' adding link to images. But I'm not sure how to address these errors. Has anyone else ran into this problem? I used another program that converted html to wendows app and same errors showed up.

[001](http://deletethis.info/aframe/0001.png)
[002](http://deletethis.info/aframe/0002.png)
[003](http://deletethis.info/aframe/0003.png)
[004](http://deletethis.info/aframe/0004.png)

Joseph

**Comment by dmarcos** [comment]
I recommend using the Discord and StackOverflow channels for usage questions. We use Github issues for bug reports and feature requests. Closing this and thanks for understanding. 

I'm not familiar with Visual Studio and not sure how suitable is for Web dev. [VSCode](https://code.visualstudio.com/) and [Sublime](https://www.sublimetext.com/) are two popular options.
