### ISSUE TITLE
The component `mytarget` has been already registered.

### ISSUE THREAD

**Issue by QingHuanYuJiu** [aframevr/aframe#5046]
![image](https://user-images.githubusercontent.com/38201850/165451350-a0a4098a-88ba-4c2c-8960-a0008ad5e706.png)
My scenario may require multiple registrations of components. How can I delete the previously registered components

**Comment by dmarcos** [comment]
You cannot unregister a component at the moment. That's a not a need we've seen. Can you describe the scenario and use case where you need to register a component multiple times with the same name? I might be able to offer alternatives.

**Comment by dmarcos** [comment]
With info provided I don't think there's anything actionable on the A-Frame side. Closing this but can reopen if necessary
