### ISSUE TITLE
Core Schema Warning when following basic scene setup.

### ISSUE THREAD

**Issue by DDincBrent** [aframevr/aframe#5047]
**Description:**
When following the tutorial on building the basic scene, I get to the point where a component is registered. Once I create the component and set the schema up matching the tutorial and I run it from my webpack server I get a `core:schema:warn Default value '5 5 5' does not match type 'vec3' in component 'scale-on-mouseenter' `

More so just curious as to why the aframe library warns me that it doesn't match the type 'vec3' but still works.

- A-Frame Version: 1.3.0
- Platform / Device: Windows 10 - Chrome
- Reproducible Code Snippet or URL:
```<script>
		AFRAME.registerComponent('scale-on-mouseenter',
	{
		schema:
		{
			to:{ default: '5 5 5', type: 'vec3' },
		},

		init: function()
		{
			console.log('Component running');
			const data = this.data;
			const el = this.el;
			this.el.addEventListener('mouseenter', function() 
			{
				el.object3D.scale.copy(data.to);
			});
		},
	});
</script>
```

```
<body>
	<a-scene>
		<a-assets>
		</a-assets>

		<a-sky src="#skyTexture"></a-sky>
		<a-box src="#boxTexture" cursor-listener position="0 2 -5" rotation=" 0 45 45" scale="2 2 2" animation="property: object3D.position.y; to: 2.2; dir: alternate; dur: 2000; loop: true;" scale-on-mouseenter></a-box>
		<a-plane src="#groundTexture" rotation="-90 0 0" width="30" height="30" repeat="10 10"></a-plane>
		<a-light type="ambient" color="#445451"></a-light>
		<a-light type="point" intensity="1" position="2 4 4"></a-light>

		<a-camera>
			<a-cursor material="color:white;"></a-cursor>
		</a-camer>

	</a-scene>
</body>
```

**Comment by dmarcos** [comment]
This is a warning because as [stated in docs](https://aframe.io/docs/1.3.0/core/component.html#schema_vec3) vec3 are represented as follows

```
to: {type: 'vec3', default: {x: 0, y: 0, z: 0}}
```

It still works because A-Frame is able to part the string to the correct type. I recommend representing the vec3 as described in docs. It will be save unnecessary string parsings making your app more efficient.

**Comment by DDincBrent** [comment]
I see, I did try formatting it like that but as ```to: { default: {x:0, y:0, z:0 } , type: 'vec3'};``` and it didn't work. Maybe I had a type I didn't notice. I will try it again thanks!
