### ISSUE TITLE
android vr mode bug: middle white line not centered, ios vr mode bug: aframe only white screen

### ISSUE THREAD

**Issue by comsyspro** [aframevr/aframe#5048]
**Description:**
I have detected 2 problems with aframe in vr mode:
On many tested android smartphones the middle white line (shown in the vr mode between the left and right eye views) is a bit out of center and intersects with the left eye view. This line should be in the center. I tried this on many android phones with the aframe example scenes. Is this a bug?

Second I also checked actual ios phones and no one of them could display the vr mode and showed only a white or gray background (safari). Is this a known issue or a bug?

Will there be a fix soon?

- A-Frame Version: 1.2, 1.3
- Platform / Device: android and ios
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
What device / android version / browser? Stereo render works fine for me on Pixel 3 / latest Chrome

**Comment by comsyspro** [comment]
I tried it on many different android devices for example from Samsung S21, Motorola, Xiaomi etc. with newer android versions 11 and 12. In all devices the middle white line is not centered (as described). On ios devices I tested it on different of the newer devices, like iphone 12 and 13, and none of them worked in vr mode and only showed a white or light gray screen backgound. Because of that I'm developing in Unity now. But aframe would be much easier to develop with lesser effort for both android and ios devices, so I hope these issues will be fixed soon.

**Comment by dmarcos** [comment]
Try a browser with WebXR support like Chrome for Android. It should work as expected there. Unfortunately there's no browsers with WebXR on iOS.

Cardboard support without WebXR has become intractable due to the proliferation of screen sizes and densities and different browser quirks when resizing viewports and going fullscreen. Also cardboard holders are becoming harder and harder to come by and use of those available is very low. We should probably think about removing cardboard support if WebXR doesn't support it since it's not a good experience. Sorry for the inconvenience.

**Comment by comsyspro** [comment]
I think you shouldn't remove WebXR, because at least on Android it is usable (with this white line not exactly cetered problem - I found a similar post here: https://forum.unity.com/threads/google-cardboard-android-alignment-bug.831661/). 

On ios I only tested Safari and I also will test with Chrome in the next days, perhaps this will work then.

**Comment by dmarcos** [comment]
We would not remove Cardboard support but rely purely on native WebXR support. Now there are two paths:

1. Native WebXR support for cardboard. Only on Chrome for Android.
2. We have polyfilled cardboard support for browsers without WebXR. This is the one we would be remove.

**Comment by shabarito** [comment]
Hi. Regarding the line not being centered, it is related to the frontal camera of your android device. If you go to screen settings, you can choose which applications use or not the area where the camera is. Chrome by default seems to not use.

After changing, the line is centered. Not sure how to ask the users to fix that though. Or, why the center line uses the screen total width while the vr exhibition dont.

**Comment by dmarcos** [comment]
Thanks. It seems it's a settings issue with certain android phones. Perhaps those that have a notch / hole-punch camera? Not sure there's much we can do on A-Frame side.
