### ISSUE TITLE
WASD-Controls: Acceleration not resolved when axis dynamically changed

### ISSUE THREAD

**Issue by vulture-boy** [aframevr/aframe#5049]
The goal of the attached snippet is to allow for switching the WS axis so that users can move using the wasd controls in the vertical axis instead of the forward axis on the fly.

When switching the wasd-controls axis programmatically, the movement acting on the component remains at the time of the switch, resulting in, e.g., constant forward motion when switching from the z axis to the y axis. 

There should be a way to resolve this motion at the time of switching the axis to avoid endlessly drifting in a direction even after returning to the initial axis, perhaps by zeroing the current vector acting on the object when an axis change occurs.

- A-Frame Version: 1.3.0
- Platform / Device: Chrome (Windows)
- Reproducible Code Snippet or URL:  https://sink-float-controls-for-a-frame.glitch.me/index-old-example.html (use Space Bar)
- ```AFRAME.registerComponent('sink-float',{

  init: function() {
    var el = this.el;
    document.addEventListener('keydown', (event) => {
      var name = event.key;
      var code = event.code;
      
      console.log(name);
      
      if (name === " ") {
        el.setAttribute('wasd-controls', {wsAxis: 'y', wsInverted: true})
      }
    }, false);
    
    document.addEventListener('keyup', (event) => {
      var name = event.key;
      var code = event.code;
      
      console.log(name);
      
      if (name === " ") {
        el.setAttribute('wasd-controls', {wsAxis: 'z', wsInverted: false, acceleration: 60})
      }
    }, false);
    
  }});
```

**Comment by vulture-boy** [comment]
Here's a solution I put together: 
https://github.com/aframevr/aframe/compare/master%40%7B1day%7D...vulture-boy:master

Live example:
https://sink-float-controls-for-a-frame.glitch.me/index-beta.html

**Comment by dmarcos** [comment]
fixed by https://github.com/aframevr/aframe/pull/5050
