### ISSUE TITLE
By using the mobile device camera with aframe and threejs, I want to mark an object in a rounded and straight-line style image and record its gps location during recording. 

### ISSUE THREAD

**Issue by AxellH** [aframevr/aframe#5056]
Hello,

By using the mobile device camera with aframe and threejs, I want to mark an object in a rounded and straight-line style image and record its gps location during recording. With the Raycaster style, I can only connect points A and B. I also made a fool of multiple drawings. I need someone who can give a simple example on this subject or say that you will use water classes and do it, my friends. Thank you very much for your time in advance. I'm leaving an example on a different platform below as a gif. but I definitely want to complete it in webar.

![7nEW3](https://user-images.githubusercontent.com/13135298/169251123-7f9425b4-cb07-495f-8f65-d73f25de91d8.gif)

**Comment by dmarcos** [comment]
I recommend using the community resources (Discord, StackOverflow) for usage questions. Nice folks there to help. 

https://aframe.io/community/

We use Github for bug reports and feature requests. Best of luck!
