### ISSUE TITLE
threejs  current version

### ISSUE THREAD

**Issue by WelinkOS** [aframevr/aframe#5059]
threejs  current version    Will there be errors if you upgrade the latest version？

**Comment by dmarcos** [comment]
I bumped master to r141. You can try yourself with master builds. Links in the commits. eg:

https://cdn.jsdelivr.net/gh/aframevr/aframe@d8de4098e6985f604e36002e00bd3b6cc37c8385/dist/aframe-master.min.js

**Comment by dmarcos** [comment]
Let me know if r141 is working for you. I don't think there's any further action on the A-Frame side. Closing this but can reopen if necessary.

**Comment by arpu** [comment]
@dmarcos  the oculus controller change is a mistake? https://github.com/aframevr/aframe/commit/837023cca1a04b408b4acde4c09823e09dc58e6d
