### ISSUE TITLE
Still maintained and recommended?

### ISSUE THREAD

**Issue by derhuebiii** [aframevr/aframe#5061]
**Description:**
Dear all,

Is a frame still being maintained and recommended? Looks like there is not so much activity.

What would be the alternative?

Thanks!
Gerd

- A-Frame Version:
- Platform / Device:
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
A-Frame is maintained and recommended. Make sure you use the latest 1.3.0 version. Let us know if you have any issues or missing any features.
