### ISSUE TITLE
Textures are not loading in incognito mode on mobile devices

### ISSUE THREAD

**Issue by andrejsmelnikovs** [aframevr/aframe#5069]
Textures are not loading in **incognito mode** on **Android** on different browsers - Chrome, Edge.

[What the scene looks like in normal browser mode (Chrome, Android)][1]

[What the scene looks like in incognito browser mode (Chrome, Android)][2]

[Console errors from scene][3]

I also checked the same scene on a laptop - everything works fine there, even in incognito mode.

Code:

    <html>
    <head>
        <script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
        <script src="//cdn.jsdelivr.net/npm/eruda"></script>
        <script>eruda.init();</script>
    </head>
    <body>
    <a-scene stats>
        <a-assets>
            <a-asset-item id="product-1" src="assets/models/products/peppis-box/scene.gltf"></a-asset-item>
            <a-asset-item id="product-2" src="assets/models/products/peppis-diet-box/scene.gltf"></a-asset-item>
        </a-assets>
    
        <a-entity gltf-model="#product-1" position="1 1 -5"></a-entity>
        <a-entity gltf-model="#product-1" position="1 2 -5"></a-entity>
        <a-entity gltf-model="#product-1" position="1 3 -5"></a-entity>
        <a-entity gltf-model="#product-1" position="1 4 -5"></a-entity>
        <a-entity gltf-model="#product-1" position="1 5 -5"></a-entity>
        <a-entity gltf-model="#product-1" position="1 6 -5"></a-entity>
        <a-entity gltf-model="#product-1" position="1 7 -5"></a-entity>
        <a-entity gltf-model="#product-1" position="1 8 -5"></a-entity>
        <a-entity gltf-model="#product-1" position="1 9 -5"></a-entity>
    
        <a-entity gltf-model="#product-2" position="2 1 -5"></a-entity>
        <a-entity gltf-model="#product-2" position="2 2 -5"></a-entity>
        <a-entity gltf-model="#product-2" position="2 3 -5"></a-entity>
        <a-entity gltf-model="#product-2" position="2 4 -5"></a-entity>
        <a-entity gltf-model="#product-2" position="2 5 -5"></a-entity>
        <a-entity gltf-model="#product-2" position="2 6 -5"></a-entity>
        <a-entity gltf-model="#product-2" position="2 7 -5"></a-entity>
        <a-entity gltf-model="#product-2" position="2 8 -5"></a-entity>
        <a-entity gltf-model="#product-2" position="2 9 -5"></a-entity>
    </a-scene>
    </body>
    </html>

  [1]: https://i.stack.imgur.com/TXP5S.jpg
  [2]: https://i.stack.imgur.com/rUQo6.jpg
  [3]: https://i.stack.imgur.com/ANJSM.jpg

- A-Frame Version: 1.3
- Platform / Device: Android (Chrome, Edge)
- Reproducible Code Snippet or URL: https://melnikovs.dev/vr/test4.html

**Comment by dmarcos** [comment]
What about iOS or Firefox?
