### ISSUE TITLE
Hit error when removing "line__xxx" component

### ISSUE THREAD

**Issue by diarmidmackenzie** [aframevr/aframe#5080]
**Description:**

- A-Frame Version: 1.3.0
- Platform / Device: All
- Reproducible Code Snippet or URL: None provided.

Create a line components on an entity with a name like line__2, as per this example.
https://aframe.io/docs/1.3.0/components/line.html

Remove the line component.

You get this console error.
core:a-entity:warn Tried to remove `Object3D` of type:  line which was not defined.

Very simple bug.

[This line](https://github.com/aframevr/aframe/blob/2c4509aa1a9a3c447c08be9facfea0c7d6a9e156/src/components/line.js#L69) assumes the Object3D name used for the mesh is "line".  In fact it will be "line__2"

```
    this.el.removeObject3D('line', this.line);
```

Correct code should be:

```
    this.el.removeObject3D(this.attrName, this.line);
```

(matching [the earlier call to setObject3D](https://github.com/aframevr/aframe/blob/2c4509aa1a9a3c447c08be9facfea0c7d6a9e156/src/components/line.js#L31))

I will submit a PR for this.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/commit/32286e3e64aaed8c4d875e9b4f20f389c11111b9
