### ISSUE TITLE
Tests failing on Firefox

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#5094]
Thanks to @vincentfretin we now have running tests per commit again. 

Some of the tests introduced by https://github.com/aframevr/aframe/commit/36d5b99337481f03f1f9f3f499f2b4ee51e7bc40 are failing on Firefox @diarmidmackenzie

**Comment by diarmidmackenzie** [comment]
Sorry - looking at this now.  Looks like a problem woith TouchEvent

**Comment by diarmidmackenzie** [comment]
Sorry, my fault for not re-running tests on Firefox after making the last set of changes on 5088.

A fix here:
https://github.com/aframevr/aframe/pull/5095

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/5095
