### ISSUE TITLE
Mobile Version open aframe cannot drag up and drag down

### ISSUE THREAD

**Issue by alanwong0922** [aframevr/aframe#5097]
**Description:**

Problem: 
I want to using the a-sky to display my  panorama image. 
On the PC browser, it is success to  show the page and control the page 
However , it has some problem When I using the iphone to open the website with the following code,
The website would not allow me to drag(scroll) up or down. 
It only can drag left right. 

 

- A-Frame Version: 1.3.0
- Platform / Device: IOS : iphone X 
- Reproducible Code Snippet or URL:  HTML CODING 
```
<!DOCTYPE html>
<html>
<style>
    a-scene {height: ${winHeight}px; width: ${winWidth}px;}
    #myEmbeddedScene {height: ${winHeight}px; width: ${winWidth}px;}
</style>
<script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
<div id="myEmbeddedScene">

<a-scene vr-mode-ui="enabled: false">
<a-camera></a-camera>
    <a-assets >
        <img id="frodo" crossorigin="anonymous" src="${panoramaPath}">
    </a-assets>
    <!-- Using the asset management system. -->

    <a-sky  src="#frodo" rotation="${x} ${y} ${z}" radius="1000" ></a-sky>
    </a-entity>

</a-scene>
</div>
</html>
       ```

**Comment by dmarcos** [comment]
This is a design decision so virtual and real horizon are always aligned when combined with magic window. You can derive your own look-controls component from the built-in one and add the functionality.

**Comment by jarekczek** [comment]
Could you reconsider this design decision? I find it strange because:
1. Why mouse scroll works differently, allows vertical scroll?
2. Other applications to watch 360 photos allow for vertical scroll using mobile drag. For example Google Photos.
I think the default should be to allow both vertical and horizontal scroll with an option to work as it does now. I still doubt anyone would need it.

**Comment by dmarcos** [comment]
> 1. Why mouse scroll works differently, allows vertical scroll?

Difference is that on mobile we also have to play along gyro orientation.

There are no plans to change the default but implementing your own `look-controls` should be just a few lines of code. There's some info here:

https://stackoverflow.com/questions/48710938/creating-vertical-camera-rotation-touch-control-for-mobile-using-a-frame

Haven't tested that code but approach looks sensible. Copy existing `look-controls` component. rename to yours (e.g `my-look-controls`) and add vertical panning. Best of luck.
