### ISSUE TITLE
Minifier doesn't know about ES6

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#5106]
Not all the code is minified with `npm run dist` because we use an old minifier that doesn't support ES6 syntax.
```
uglify-js failed on src/components/hand-tracking-controls.js : SyntaxError: Unexpected token name «of», expected punc «;»
uglify-js failed on src/components/layer.js : SyntaxError: Unexpected token: name (x1offset)
uglify-js failed on src/utils/ios-orientationchange-blank-bug.js : SyntaxError: Unexpected character '`'
uglify-js failed on node_modules/super-three/build/three.js : SyntaxError: Unexpected token: name (EventDispatcher)
uglify-js failed on node_modules/three-bmfont-text/index.js : SyntaxError: Unexpected token: name (TextGeometry)
uglify-js failed on node_modules/super-three/examples/js/loaders/DRACOLoader.js : SyntaxError: Unexpected token: name (DRACOLoader)
uglify-js failed on node_modules/super-three/examples/js/lights/LightProbeGenerator.js : SyntaxError: Unexpected token: name (LightProbeGenerator)
uglify-js failed on node_modules/super-three/examples/js/loaders/MTLLoader.js : SyntaxError: Unexpected token: name (MTLLoader)
uglify-js failed on node_modules/super-three/examples/js/loaders/OBJLoader.js : SyntaxError: Unexpected token name «mi», expected punc «;»
uglify-js failed on node_modules/super-three/examples/js/utils/BufferGeometryUtils.js : SyntaxError: Unexpected token operator «=», expected punc «,»
uglify-js failed on node_modules/super-three/examples/js/loaders/GLTFLoader.js : SyntaxError: Unexpected token: name (GLTFLoader)
```

We use for-of in  `src/components/hand-tracking-controls.js`,
template literal in `src/utils/ios-orientationchange-blank-bug.js` and classes in super-three includes.

We should replace minifyify/uglifyjs https://www.npmjs.com/package/minifyify by uglifyify/terser https://github.com/hughsk/uglifyify so it can minify the ES6 code.
Note that ES6 code will stay ES6 code through the minifier. It doesn't convert to ES5. If you want to convert to ES5, you need https://www.npmjs.com/package/babelify

@dmarcos should I do some tests and propose a PR?

**Comment by dmarcos** [comment]
Thanks. I removed the template literals that I think are not necessary and I'll deal with `src/components/hand-tracking-controls.js`. For THREE code we can't control. If there's a surgical way to deal with it, it will be great.

**Comment by vincentfretin** [comment]
I tried various config with uglifyify but I wasn't able to make the source map work properly. I almost gave up...
I successfully made it working using directly terser without going through a browserify plugin.
See PR #5111
