### ISSUE TITLE
A-Frame & Vue: No DRACOLoader instance provided. 

### ISSUE THREAD

**Issue by andrejsmelnikovs** [aframevr/aframe#5107]
I'm having trouble creating an A-Frame scene in vue.js framework. I can't implement draco-compression for gltf models - the console displays an error `THREE.GLTFLoader: No DRACOLoader instance provided. `

How to solve this problem?

- A-Frame Version: 1.3.0

### Code with vue.js:

index.html:

```
<!DOCTYPE html>
<html lang="en">
  <head>
      <script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
```

MainComponent.vue:

```
<template>
  <a-scene gltf-model="dracoDecoderPath: https://www.gstatic.com/draco/v1/decoders/">
    <a-entity gltf-model="url(/shop/models/room/empty-shelf/scene-compressed.gltf)"></a-entity>
  </a-scene>
</template>
```

Result:

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/66255374/188312049-0dd16be7-464f-44ab-9df9-1490129f153a.png">

### Code without Vue.js (everything is ok):

index.html

```
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
</head>
<body>
<a-scene gltf-model="dracoDecoderPath: https://www.gstatic.com/draco/v1/decoders/">
    <a-entity gltf-model="url(/shop/models/room/empty-shelf/scene-compressed.gltf)"></a-entity>
</a-scene>
</body>
</html>
```

Result:

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/66255374/188311991-2bd7000c-4c4d-4eb0-9886-6cfaf0884f08.png">

**Comment by dmarcos** [comment]
This is more of a usage question. I'm not familiar with vue. I recommend joining the [community](https://aframe.io/community/) on Discord or StackOverflow. Nice folks there to help.

Closing this because we use github issues for bug reports and feature requests. Thanks for understanding

**Comment by izhoubin** [comment]
Same problem here.
If we setAttribute `dracoDecoderPath` after scene loaded,it works.
```javascript
let scene = document.querySelector("a-scene");
let dracoEl = document.querySelector('#draco')
scene.addEventListener('loaded',function(){
    scene.setAttribute('gltf-model',"dracoDecoderPath: https://www.gstatic.com/draco/v1/decoders/")
    dracoEl.setAttribute('gltf-model',"url(/shop/models/room/empty-shelf/scene-compressed.gltf)")
})
```
registerSystem('gltf-model'):
```javascript
init: function () {
    this.update();//dracoDecoderPath will always empty in vue
  },
```
relaced by:
```javascript
init: function () {
   this.sceneEl.addEventListener('loaded',this.update)
 },
```

**Comment by dmarcos** [comment]
You might want to try A-Frame 1.4.0 https://aframe.io/releases/1.4.0/aframe.min.js
