### ISSUE TITLE
Loading Screen Expansion

### ISSUE THREAD

**Issue by NathanPip** [aframevr/aframe#5113]
**Description:**
Currently there are no options for changing what is being rendered in the loading scene. I was looking to add options for rendering a rotating torus knot or cube instead of blinking dots. I'm aware the blinking dots communicate that the scene is loading a little more clearly than other options but that could be remedied by adding some "Loading..." text to the DOM overlay.

AFrame 1.3
Beyond grateful for the work you guys have done.

**Comment by dmarcos** [comment]
Thanks! You can [disable the loading screen](https://aframe.io/docs/1.3.0/components/loading-screen.html#properties_enabled) and implement your own. Can also grab the dom element class`.a-loader-title` and modify it.
