### ISSUE TITLE
Embedded a-frame inside a bootstrap modal, raycaster don't update on scroll

### ISSUE THREAD

**Issue by GHF-Hiricis** [aframevr/aframe#5121]
Hi, i was having a problem with the raycaster not working after a scroll on my page, in this case the a-frame is inside a modal, as i was searching for a solution i found that this problem was supposed to be fixed already according to this post:

https://github.com/aframevr/aframe/issues/3700

but i was still not working then i realized that my scroll is not on the "window" but in a specific div inside my modal, so i manage to fix by adding this code on the aframe.js 

"document.getElementById("myId").addEventListener("scroll", this.updateCanvasBounds),"

this works, but i know changing the aframe.js is not the best practice, so i want to know if there is a better way to do this?

- A-Frame Version: 1.3.0

**Comment by dmarcos** [comment]
Can you provide a runnable example to reproduce with https://glitch.com/~aframe? Preferably without Bootstrap. It adds some noise to debug and I'm not familiarized with it

**Comment by dmarcos** [comment]
Closing due to to lack of activity. Can reopen if necessary.
