### ISSUE TITLE
inspector is pretty broken on master right now

### ISSUE THREAD

**Issue by kylebakerio** [aframevr/aframe#5127]
**Description:**

- A-Frame Version: master branch
- Platform / Device: desktop
- Reproducible Code Snippet or URL: any, just use master

One thing that helps is just switching to using `MathUtils`

```js
      THREE.Math = THREE.MathUtils;
```
      
But there are other issues as well.

**Comment by vincentfretin** [comment]
You can create a PR in the https://github.com/aframevr/aframe-inspector repository.
The inspector indeed needs some love
https://github.com/aframevr/aframe-inspector/search?q=THREE.Math

**Comment by dmarcos** [comment]
Thanks. Yeah we need to adjust after bumping to latest THREE

**Comment by vincentfretin** [comment]
I did a PR https://github.com/aframevr/aframe-inspector/pull/637

**Comment by vincentfretin** [comment]
@kylebakerio Can you please test my PR and tell me if you find other issues I may not have seen?

**Comment by kylebakerio** [comment]
Looks really good to me! I tried to push it pretty thoroughly in the provided example, and the only issues I found were with A-Frame and with the environment component. I think this makes it better than it has been in a while!

Biggest issue is I did find an issue when attempting to update something on the environment component through inspector, but investigation showed that was an issue for aframe-environment-component. I'll go file an issue against that, has to do with an update in THREE in master.

**Comment by dmarcos** [comment]
Can we close this one?

**Comment by vincentfretin** [comment]
You can close. If we detect issues we'll create issues in the aframe-inspector repo.

**Comment by dmarcos** [comment]
Thanks
