### ISSUE TITLE
Can't import .glb files into aframe?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [aframevr/aframe#5133]
I am working on a house/backyard model, and it only lets me export into .glb not .gltf . So is there any way to either turn a .glb into a .gltf, or import a .glb into my other index.html file? Am I doing it incorrectly?

![Screenshot 2022-10-09 10 09 47](https://user-images.githubusercontent.com/112659665/194761510-2e75592e-cceb-4cdd-9bea-0b5eeefeb4c4.png)

- A-Frame Version: 1.3.0
- Platform / Device: Acer chromebook 315

**Comment by dmarcos** [comment]
I recommend sharing a full runnable example with https://glitch.com/~aframe otherwise it will be hard to tell what's going on

**Comment by dmarcos** [comment]
An example of A-Frame loading a gltf file:

https://glitch.com/edit/#!/adorable-developing-way?path=index.html%3A13%3A0

**Comment by TheRealDigitalMaster** [comment]
Thanks :)

**Comment by dmarcos** [comment]
Closing this since there's nothing actionable on the A-Frame side. We can reopen if necessary.
