### ISSUE TITLE
we lost the build command in the transition to webpack

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#5142]
https://github.com/aframevr/aframe/blob/v1.3.0/package.json#L9

cc @vincentfretin

**Comment by vincentfretin** [comment]
What do you need it for?
Previously this was only used by `npm run dev` to have a non minified build with INSPECTOR_VERSION=dev and run budo with it.
With webpack this is not needed, the build is done with INSPECTOR_VERSION=dev and kept in memory.
If you need a non minified build `npm run dist:min` will give you just that (but without INSPECTOR_VERSION=dev)

**Comment by vincentfretin** [comment]
If you need back a non minified build with INSPECTOR_VERSION=dev for a reason I don't know, you can use:
```
"build": "shx mkdir -p build && cross-env INSPECTOR_VERSION=dev webpack --config webpack.config.js --output-filename aframe.js -o build"
```

**Comment by dmarcos** [comment]
the build command was used for the bot for master builds. The dist command is for `official releases`

**Comment by vincentfretin** [comment]
Are you sure? The bot committed an url ending with aframe-master.min.js, so a minified build. The build command generated `build/aframe.js`, a non minified build.

**Comment by vincentfretin** [comment]
In https://github.com/aframevr/aframe/commit/c27d4a2156bde2ec249600fca4967ba49fecfdc3
`build/aframe.js`, `dist/aframe-master.js`, `dist/aframe-master.min.js` files were committed indeed. But `build/aframe.js` was only used with budo dev server really.
In your bot, I guess you used both `npm run build` and `npm run dist`? I think you should just remove the `npm run build` step in your bot. If you really want `build/aframe.js`, I put the line to add in https://github.com/aframevr/aframe/issues/5142#issuecomment-1293166902

**Comment by vincentfretin** [comment]
No, I misread, no there was no `build/aframe.js` file committed.
Is your bot code publicly accessible?

**Comment by vincentfretin** [comment]
The build folder is gitignored since before webpack.
The official releases are produced by the `prerelease` command it seems.
