### ISSUE TITLE
Meta Pro Touch Controllers not supported

### ISSUE THREAD

**Issue by AlbertoElias** [aframevr/aframe#5143]
I noticed the current oculus-touch-controls component is not forward compatible with the touch controllers, so hand-controls also don't work.

The main blocker is that it doesn't set `iterateControllerProfiles: true` in tracked-controls, and when running `checkControllerPresentAndSetup`. This way, it will at least work with the existing hand and touch models. With both the hand and touch models, though, they are positioned a bit further out on the z-axis than in reality.

The new Pro Touch models have been uploaded to https://github.com/immersive-web/webxr-input-profiles/tree/main/packages/assets/profiles/meta-quest-touch-pro

They do have a new profile id called `meta-quest-touch-pro`.

I'm happy to attempt a PR to add support, but I would like to know what approach you would like to follow. Creating a new component for these controllers or maybe some way of having oculus-touch-controllers support both ids? 

- A-Frame Version: 1.3.0
- Platform / Device: Meta Quest Pro
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Meta Quest Pro controllers already [supported on master](https://github.com/aframevr/aframe/commit/c9e41728c53ea2ebc73aabe1ba7a663acb82aab9) thanks to @felixtrz work
