### ISSUE TITLE
Aframe is crashing when used with Oculus Rift

### ISSUE THREAD

**Issue by mglatki** [aframevr/aframe#5147]
Hello, I am working on a WebXr project for Oculus Quest 2, but I have tried to run it on an older Oculus Rift. To my surprise, it hasn't worked. So I have tried [immersive-web.github.io](https://immersive-web.github.io/webxr-samples/), but it is working without any problem. Then I have tried examples on [aframe.io](https://aframe.io) and those haven't worked. 

Aframe is throwing some errors:
 - Uncaught TypeError: context is null
 - Uncaught TypeError: scope.dispatchEvent is not a function
 - Uncaught TypeError: camera is undefined

![obraz](https://user-images.githubusercontent.com/5540870/200331011-966eb600-c486-437f-bd50-ae0b60fab2fb.png)

- A-Frame Version: 1.3.0 I guess
- Platform / Device: Oculus Rift / Windows 10 / Firefox 106.0.5
- Reproducible Code Snippet or URL: [aframe.io sample](https://aframe.io/examples/showcase/helloworld/)

Also after aframe crush on one page, any page with WebXR is not working until Firefox is restarted.

Thanks in advance and sorry for bad english :) 
mglatki

**Comment by dmarcos** [comment]
I recommend using Chrome. Firefox never transitioned to the WebXR API (still on the old WebVR spec) and doesn't have a team maintaining or implementing the new standard.

**Comment by dmarcos** [comment]
Surprised that [immersive-web.github.io](https://immersive-web.github.io/webxr-samples/) worked at all since Firefox doesn't have a WebXR implementation

**Comment by dmarcos** [comment]
Are you perhaps running a WebVR / WebXR emulator in your browser?

**Comment by mglatki** [comment]
Thank you for quick response.

I was using WebXR emulator, but not on PC with Rift. It is not even installed there.

I am testing Chrome right now. I am able to start immerse view of "Hello WebVR" and "Model Viewer" from aframe.io and my sample project, but I have to restart Chrome every time. If I don't do it, the scene is trying to load but fails and SteamVR "room" is showing again.

Probably previous (before I raised the issue) bad experience with Chrome was caused with already "messed session".

If you have any more ideas how to improve "Chrome experience" I would appreciate them.

Thank you for help and for Aframe :)

**Comment by dmarcos** [comment]
On Firefox make sure you have the following flags enabled: `dom.vr.enabled` and `dom.vr.webxr.enabled`

https://aframe.io/aframe/examples/boilerplate/hello-world/ should worked. Someone for the community tested successfully via SteamVR

Chrome has quirks. Can see for workarounds in https://github.com/aframevr/aframe/issues/4709

**Comment by dmarcos** [comment]
Unfortunately Firefox is no longer a viable target. As far as I know they don't have staff working on a WebXR implementation. For problems related to Chrome and workarounds refer to https://github.com/aframevr/aframe/issues/4709 

Closing this but can reopen if necessary
