### ISSUE TITLE
Ar Vr placement issue

### ISSUE THREAD

**Issue by ctdlg** [aframevr/aframe#5158]
Entering AR or Vr buttons

- A-Frame Version: 1.3.0
- Platform / Device: oculus Quest 2, Samsung S7, OppoFind X3 pro, Samsung Tab
- Reproducible Code Snippet or URL:
Using aframe.min.js

AR and VR buttons overlap on smartphones and Oculus quest 2 browsers (problem appeared after browser upadates) Only if using embedded code !

I checked all your samples : you also get the same display problem. Your own example [HERE](https://www.stackoverflow.com/) does not display correctly on my oculus and my S7 !

Display is OK with Firefox.

We get ar/vr buttons overlap with Chrome or Oculus Quest 2 web browser.

[Example 1](https://clatique.fr/DJI/aframe/pbarvr.jpg)

[Example 2 ](https://clatique.fr/multimedia/Themes/VR/Sites-VR/P-100_0093.txt.html)on my website (use a smartphone...)

**Comment by dmarcos** [comment]
This is fixed in master now. Can make your own builds `npm run dist`

**Comment by ctdlg** [comment]
**Thank you very much dmarcos,**
It does display correctly now.
I did sponsor you : aframe is really great, I will use it a lot for VR + Oculus quest 2 !

Some more information for beginners ( I did search the meaning of _npm run dist_ and how to !)
1 downloading the 1.3.0 from github
2 reading the README.md, starting line 170 ### npm
3 installed npm on my archlinux system
4 git clone https://github.com/aframevr/aframe.git 
5 cd aframe
6 npm run dist
7 using aframe-master.js located in aframe/dist folder

**Comment by dmarcos** [comment]
@ctdlg Thanks. Much appreciated. Glad is working for you now.
