### ISSUE TITLE
oculus-touch-controls not working for Oculus Pro

### ISSUE THREAD

**Issue by Kershawj** [aframevr/aframe#5178]
No model shown or tracked to controls.
Looking at the source for that component it looks like they should and points to the correct controller models to download from the aframe CDN, but like I say it somehow doesn't detect these controllers correctly.

laser-controls work but they fall back to generic-tracked-controller-controls so you just see a sphere and the ray as it's cast (correctly for that control).

- A-Frame Version: 1.3.0
- Platform / Device: Quest Pro

```html
<a-entity oculus-touch-controls="hand: right;"></a-entity>
```

**Comment by dmarcos** [comment]
Support is on master. You need you checkout from the repo and [generate your own build](https://github.com/aframevr/aframe#generating-builds)
