### ISSUE TITLE
Quest 1 wrong controller and ray offsets

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#5183]
The Quest 1 controllers offset and ray offset are completely off when using laser-controls. Issue similar to Quest 2 that was fixed in #5141 by @felixtrz 

- A-Frame Version: master Dec 7, 2022 threejs r147
- Platform / Device: Meta Quest 1 on latest OS Version 47.0.0.282.341.428237303, Meta browser 24.4.0.22.60.426469926
- Reproducible Code Snippet or URL: `npm run start:https` and open in the Quest https://192.168.1.x:8080/showcase/ui/

I have no idea how to get the correct offsets to fix it.
It's been a long time this is like this, but I don't use laser-controls anymore in my projects, I'm using [handy-work](https://github.com/AdaRoseCannon/handy-work) that is using the webxr-input-profiles information and models where I don't have the issue.
I created the issue so you are aware of it before releasing aframe 1.4.0. If somebody could look at it to fix it or give me some instructions how to get the correct values, it would be great.

**Comment by dmarcos** [comment]
Might not be needed anymore. I don't have a Quest 1 to test. Can you try setting origin / direction to 0 on left and right and see if it makes a difference?

https://github.com/aframevr/aframe/blob/master/src/components/oculus-touch-controls.js#L60

**Comment by vincentfretin** [comment]
It's definitely in oculus-touch-v2, setting rayOrigin origin/direction to 0 make the ray disappear.
But first I'm trying to set the correct modelPivotOffset and modelPivotRotation
For modelPivotRotation `new THREE.Euler(-Math.PI / 4.5, 0, 0)` seems ok, now I'm tweaking modelPivotOffset by trial and error trying to match the system controller when I press the home button.
For now for the left I put `modelPivotOffset: new THREE.Vector3(0.005, 0, -0.037)` but not quite matching in y.
Is there a simpler way to find those values? This is too time consuming to test that by trial and error.
Moreover with handy-controls I have a perfect match between the system controllers and in VR. Maybe we should compare the two different models used here.

**Comment by dmarcos** [comment]
We're using grip space so those offsets should not bee needed anymore:

https://github.com/aframevr/aframe/commit/88e8db12deeb501bfaeb03fe015284197a1942e2

**Comment by dmarcos** [comment]
@felixtrz we can get rid of those offset, can't we? Thank you!

**Comment by vincentfretin** [comment]
Here #5190 are the values I need for the currently used Quest 1 models.
