### ISSUE TITLE
Hands model a little bit weird in hand-tracking showcase

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#5185]
**Description:**

The index finger on the hands is really weird, there seems to have a small rotation issue here.

- A-Frame Version: master Dec 7, 2022 threejs r147
- Platform / Device: Quest 1
- Reproducible Code Snippet or URL: `npm run start:https` and open https://192.168.1.x:8080/showcase/hand-tracking/ in your Quest and put your controllers on the ground to enable hands tracking

With [handy-controls](https://github.com/AdaRoseCannon/handy-work) used in [aframe-xr-boilerplate](https://github.com/AdaRoseCannon/aframe-xr-boilerplate) we have much better looking fingers with the white hand models.

**Comment by dmarcos** [comment]
API has changed and hence model has to be updated accordingly.

**Comment by dmarcos** [comment]
Thanks for noticing the issue and reporting

**Comment by vincentfretin** [comment]
Oh yes much better! Thanks.
