### ISSUE TITLE
`npm run prerelease` no longer works as it used to with webpack

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#5193]
This line doesn't work as it used to:

https://github.com/aframevr/aframe/blob/master/scripts/release.js#L21

Change the following command to a new "old version" and "new version" numbers:

https://github.com/aframevr/aframe/blob/master/package.json#L19

Then run `npm run prerelease`. We should see the "old version" removed "aframe-v1.3.0.js" and replaced with "aframe-v1.4.0.js" with the "new version". Now it just removes the old version and generates new builds with name "aframe-master.js". The file name doesn't get replaced.

@vincentfretin

**Comment by vincentfretin** [comment]
Indeed the script needs to be adapted. Let me take a look.

**Comment by vincentfretin** [comment]
Do you have a script that is not in this repository that uses the FOR_RELEASE environment variable? I don't understand what it was used for. I'll remove it in my PR.

**Comment by vincentfretin** [comment]
This is fixed in #5196

**Comment by vincentfretin** [comment]
Ah FOR_RELEASE may be used by one of your script to create
https://aframe.io/releases/1.4.0/aframe.min.js
?
I verified the last line, it's correct `//# sourceMappingURL=aframe.min.js.map` 
Did you edited it manually?

**Comment by dmarcos** [comment]
Yes. I edited it manually for this release.
