### ISSUE TITLE
Reenter VR on comicbook example crash

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#5197]
**Description:**

- A-Frame Version: 1.4.0 
- Platform / Device: Quest 1
- Reproducible Code Snippet or URL: https://192.168.1.15:8080/showcase/comicbook/

Steps:
- Open url
- Click VR button
- Exit
- Click VR button again

```
three.module.js:26018 Uncaught DOMException: Failed to execute 'updateRenderState' on 'XRSession': XRWebGLLayer was created with a different session.
    at WebXRManager.updateLayers (https://192.168.1.15:8080/dist/aframe-master.js:44804:673)
    at WebXRManager.addLayer (https://192.168.1.15:8080/dist/aframe-master.js:44804:359)
    at NewComponent.initQuadLayer (https://192.168.1.15:8080/dist/aframe-master.js:22703:25)
    at NewComponent.initLayer (https://192.168.1.15:8080/dist/aframe-master.js:22680:12)
    at NewComponent.tick (https://192.168.1.15:8080/dist/aframe-master.js:22659:12)
    at AScene.tick (https://192.168.1.15:8080/dist/aframe-master.js:34944:30)
    at AScene.render (https://192.168.1.15:8080/dist/aframe-master.js:34995:12)
    at bound (https://192.168.1.15:8080/dist/aframe-master.js:39945:17)
    at onAnimationFrame (https://192.168.1.15:8080/dist/aframe-master.js:44833:266)
    at XRSession.onAnimationFrame (https://192.168.1.15:8080/dist/aframe-master.js:44197:545)
```

My guess is a fix is needed in the aframe layer component.

**Comment by dmarcos** [comment]
We have logic to destroy / recreate the layer upon exiting / entering VR respectively? https://github.com/aframevr/aframe/blob/master/src/components/layer.js#L298 

Maybe something has changed at the WebXRManager level. Does it reproduce with 1.3.0?

**Comment by vincentfretin** [comment]
Yes, it reproduces on 1.3.0, and back to 1.2.0 and also 1.1.0.
Looking at the layer component code, indeed it destroys the layer and recreate it, I don't see anything wrong here. I'll need to put some console.log there to verify.

**Comment by vincentfretin** [comment]
https://github.com/aframevr/aframe/blob/d8fef14230b3311155d9a214e179c9ada5e85334/src/components/layer.js#L297 
has no effect because session is already null, so the condition here
https://github.com/supermedium/three.js/blob/super-r147/src/renderers/webxr/WebXRManager.js#L375-L380
evaluate to true and return right away before removing the QuadLayer from layers array.
Here is my debugging session:
![Capture d’écran du 2022-12-31 08-23-01](https://user-images.githubusercontent.com/112249/210129119-e714c789-7a65-46b9-a49f-14abb44bf232.png)

The 3 functions here https://github.com/supermedium/three.js/blob/super-r147/src/renderers/webxr/WebXRManager.js#L368-L387 are specific to our fork. You added those API in https://github.com/supermedium/three.js/commit/84b2da14686acbb7ee5f66883964109105273d21

The fix is to always remove from the layers array even if session is null like this:
```
          this.removeLayer = function(layer) {
              layers.splice( layers.indexOf(layer), 1 );
              if (!window.XRWebGLBinding || !this.layersEnabled || !session) { return; }
              this.updateLayers();
          };
```

I'll leave you edit the commit the next time your rebase to update super-three.

**Comment by vincentfretin** [comment]
I created https://github.com/supermedium/three.js/pull/9 if it's easier for you.

**Comment by dmarcos** [comment]
Fixed by https://github.com/supermedium/three.js/pull/9
