### ISSUE TITLE
tshirt link broken in Blog

### ISSUE THREAD

**Issue by ELI7VH** [aframevr/aframe#5208]
the link to purchasing t-shirts is broken in the docs. :) Was going to buy one.

https://aframe.io/blog/aframe-v1.1.0/

**Comment by dmarcos** [comment]
Sorry! You can buy one here https://cottonbureau.com/p/SX82KC/shirt/a-frame-og#/9479538/tee-men-standard-tee-vintage-black-tri-blend-s

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe-site/commit/bbb4bf37b2323d7a7b58f545447d1fec5551c675
