### ISSUE TITLE
a-cubemap not mentioned in A-Frame documentation

### ISSUE THREAD

**Issue by diarmidmackenzie** [aframevr/aframe#5209]
**Description:**

- A-Frame Version: 1.4.0
- Platform / Device: All
- Reproducible Code Snippet or URL: See docs

Since 1.1.0, cubemaps are the recommended way to do reflections in A-Frame
https://github.com/aframevr/aframe/issues/4977

There are some tests showing this function, e.g.  here:
https://github.com/aframevr/aframe/blob/master/examples/test/physical/index.html

but they aren't mentioned anywhere in the documentation.

I spotted this while working to retire `cube-env-map` from a-frame extras, and looking for something in the A-Frame docs to refer to.

I'll come back & do a PR for this in a few days, unless someone else gets there first...

**Comment by dmarcos** [comment]
Thanks! yeah a PR is super welcome. You're welcome to do it. Also gonna share this on Discord since this is a good one for beginners to contribute.
