### ISSUE TITLE
Update linting to enforce ES5

### ISSUE THREAD

**Issue by diarmidmackenzie** [aframevr/aframe#5218]
**Description:**

- A-Frame Version: 1.4.1
- Platform / Device: All
- Reproducible Code Snippet or URL: N/A

The project uses [semistandard](https://github.com/standard/semistandard) for linting.

However the project also aims to use ES5 only, and does not permit ES6 features like const/let, arrow functions etc.  Having rules for code submissions that are not checked automatically (when they could be) results in time wasted & unnecessary iterations on PRs.

Proposal
- move from [semistandard](https://github.com/standard/semistandard) to [standardx](https://github.com/standard/standardx), which allows overriding of specific standard rules
- update config to disallow JS features after 2015.
(based on standard's [eslint config](https://github.com/standard/eslint-config-standard/blob/master/.eslintrc.json) this probably just requires setting 
```
"parserOptions": {
    "ecmaVersion": 2015
   }
```
and
```
  "env": {
    "es2015": true
    } 
```
- fix up any pre-existing ES2016 violations (policing has been manual, so there may be some instances that slipped through).

Alternative Proposal:
- Change policy to allow modern JS in A-Frame.  However I believe that's been suggested before and ruled out...

**Comment by vincentfretin** [comment]
Recent comments on that was https://github.com/aframevr/aframe/pull/5103#issuecomment-1230841914 and https://github.com/aframevr/aframe/issues/5106#issuecomment-1233354515
I don't know if those learning javascript today knows about the different behavior of var hoisting compared to let/const:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#variable_hoisting
Anyway that was already been discussed.
FYI three.js repository uses javascript features up to ES2018 and removed babel from their build tool recently.

Current aframe code base uses ES6/ES2015 module only in `src/lib/three.module.js` to be able to import from jsm folder from three package, otherwise all the code is using `require`, no template literal, no `const/let` in `src` folder (except one let in `src/components/oculus-touch-controls.js` that slipped through in a recent PR and `src/components/layer.js`), in `tests` we use `var/const/let`.

**Comment by diarmidmackenzie** [comment]
Hit this again working on #5340 

I might look at a PR here, as getting as many of the project coding conventions established as linting rules would cut reviewing cycles for PRs.

Another rule we should consider encoded is: "no single letter variable names".  Some pointers for how that could be done [here](https://stackoverflow.com/questions/63586298/eslint-rule-to-ensure-minimum-variable-name-length-but-not-on-json)

**Comment by diarmidmackenzie** [comment]
I did some work on this: https://github.com/diarmidmackenzie/aframe/tree/improve-linting

Close to having something I could offer as a PR, but this has thrown up some interesting issues....

Originally we set up semistandard v9.  This is now at v17, with a bunch of changes here: https://standardjs.com/changelog.html

I don't think it makes sense to try to stick with the v9 version.  It's coupled to an old version of ESLint, so we'd be baking in legacy code.  Better to move to the latest code.

However the rules have changed quite a lot since v9.  I had to disable 23 rules to get the linting to pass with the current code.

A few of these we don't want (e.g. the rule to use let/var rather than const).  We can set exceptions for these.  Most of the others are stylistic & hygeine things, where it probably makes sense to update to the latest standard (we can review individual items on the list in due course).

Restricting the /src/ directory to ES5 threw up a few other issues:
- 3 places where ES6 syntax had slipped in - easily fixed.
- The big one is the use of classes in various modules:

The classes we have in the codebase are:
- ANode
- AAssets
- AAssetItem
- ACubeMap
- AEntity
- AMixin
- AScene

So the one blocking issue is this inconsistency between the principle that the code only uses ES5 constructs, and the fact that we make extensive use of ES6 classes in various parts of the code.

I had a brief look at the PR that introduced these classes, #5136.  I may have overlooked something, but I didn't see any discussion of the conflict between the use of classes and the ES5-only policy for the codebase.

Was it necessary to use classes to make use of the v1 CustomElements API?  What was the rationale for bring OK with ES6 features here, and not elsewhere?

In general you can skip an ESLint check using a comment like this:

```
// eslint-disable-next-line no-console
```

However in these cases, the linting error is not a "rule" (which could be easily skipped), but a parsing error, because we have instructed it to use the ES5 parser...

Because of this, the only workaround I can see is to enable ES6 parsing for those modules that need to use classes.  We could restructure the code to minimize the amount of code that has to have this ES6 exemption.

@dmarcos - What's your take on this?  My understanding is that you want to stick with the ES5-only policy for now.  So how does that align with the use of classes in various modules?

**Comment by diarmidmackenzie** [comment]
Reflecting on this, I'm assuming that we do want to use "classes" in A-Frame, even though they are not in ES5 - so if I want to move this forward I need to find a way to deal with that.

Best (and only!) solution I can see is to exempt the small number of modules that use classes from ES5 parsing.  This allows us to check > 90% of the codebase for ES5-conformance, which is a big step forwards, albeit not perfect.

That's the approach I've taken in #5432.

**Comment by dmarcos** [comment]
Can we close this?
