### ISSUE TITLE
setting position dynamically

### ISSUE THREAD

**Issue by jeannie2** [aframevr/aframe#5219]
**Description:**
-using latest version of aframe
-desktop

-location-based AR. x position doesn't seem to work, tried various ways as shown in code below. I also tried with createElement("a-entity") but couldn't get it to work. Any suggestions would be appreciated, thank you for your help

          function randomPosition() {
          let x = Math.floor(Math.random() * (9 + 1) + 1); 
          let y = Math.floor(Math.random() * (5 + 5) - 5); 
          let randomPosition = [x, y, 0];
          console.log("randomPosition: " + randomPosition);
          return randomPosition;
        }

          function createARText(transcript) {
          var sceneEl = document.querySelector("a-scene");
          var entityEl = document.createElement("a-text");
          entityEl.setAttribute(
            "gps-entity-place",
            "latitude:xxxxx; longitude:yyyyy"
          );
         
          entityEl.setAttribute(
            "position",
            "" +
              randomPosition()[0] +
              " " +
              randomPosition()[1] +
              " " +
              randomPosition()[2] +
              ""
          );
          // entityEl.object3D.position.set(5, 1.25, -3);
          // entityEl.setAttribute("position", "-0.9 1.7 -2.9"). -0.9 1.7 -2.9. 1 1 0. 50 50 50
          /* entityEl.setAttribute("position", {
                  x: 0,
                  y: 2,
                  z: 0.5
                }); 
           entityEl.setAttribute(
                  "position",
                  "{x:" +
                    randomPosition()[0] +
                    ", y:" +
                    randomPosition()[1] +
                    ", z:" +
                    randomPosition()[2] +
                    "}"
                ); */
          entityEl.setAttribute("scale", "10 10 10"); // "5 5 5"
          entityEl.setAttribute("rotation", "0 0 " + randomRotate + "");
        
          entityEl.setAttribute("value", transcript);
          entityEl.setAttribute("align", "center");
          entityEl.setAttribute(
            "font",
            "https://cdn.aframe.io/fonts/" + loadRandomFont()
          );
          entityEl.setAttribute("color", randomRGB());
          sceneEl.appendChild(entityEl);
          randomRotate += 30;
        }

**Comment by dmarcos** [comment]
For usage questions I recommend [joining the community](https://aframe.io/community/) on Discord or StackOverflow. Nice folks there to help. Closing this because we use Github issues for bug reports and feature requests. Best of luck and thanks for understanding.
