### ISSUE TITLE
Raycasting not working as expected AR usecase  (used Aframe and ARjs)

### ISSUE THREAD

**Issue by 228rajesh** [aframevr/aframe#5224]
**Description:**

- A-Frame Version:1.4.0
- Platform / Device:laptop(windows), mobile(Android)
- Reproducible Code Snippet or URL:

Issue description:
Raycasting property working fine in aframe for VR usecase but raycasting property not working as intended in AR usecase implemented using aframe and arjs.

My requirement is simple. I have created a cube and i have defined the click event(event listener)
If I click the cube it should perform rotation  animation.
It's perfectly working in VR (Aframe)
But its not working as expected in AR(Aframe + ARjs).

The problem I am facing is that when ever I clicked on the cube object it's not responding (cube not rotating) but if I click few centimetres away from the cube then it was responding (cube rotating).

According to my observation the ray is not moving in the proper direction.

Any help would be greatly appreciated.
Thank you.

**Comment by dmarcos** [comment]
This an issue that has to be fixed on the ar.js side. More info on https://github.com/AR-js-org/AR.js/issues/271

**Comment by 228rajesh** [comment]
Sure, will look into it
Thanks
