### ISSUE TITLE
Edge case in load order with <script defer> - TypeError: system is undefined

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#5228]
**Description:**

Pretty far on the edge, but I hit this while working on my experiments with Svelte + WebComponents for reusable A-Frame structures. 

While in a script that's loaded with the `defer` attribute, attempting to insert new entities into the page will cause the inserted entity to attempt to load prematurely and throw errors, in this case the `geometry` component is initializing before the systems have been initialized.

You'll see from the logs in the reprex that `document.readyState` is `interactive`, so it passes [this gate](https://github.com/aframevr/aframe/blob/master/src/core/a-entity.js#L65) in `connectedCallback` and tries to load immediately,  but also that the `system` has not yet been set so it fails.

Since [defer causes a script to run before](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer) DOMContentLoaded, but apparently after the switch to interactive readyState, this seems the be sneaking into a tiny chink in the A-Frame load order.

- A-Frame Version: 1.4.1
- Platform / Device: desktop chrome & FF
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/muddy-even-wave (this should render a box but doesn't)

**Comment by vincentfretin** [comment]
Did you try changing the condition to `document.readyState !== "complete"`? Does this fix your issue?
https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState

**Comment by wmurphyrd** [comment]
@vincentfretin changing AEntity connectedCallback the check to `document.readyState !== "complete"` would fix this issue, but that would open another gap in A-Frame's load order: any entities inserted after DOMContentLoaded but while `readyState === 'interactive'` would never initialize.

Any time you mix readyState with DOMContentLoaded events you end up leaving a gap. Best bet is to either do a pure readyState solution, like [this one from our immers-client](https://github.com/immers-space/immers-client/blob/f70c258216420aef8779a61e1d752fb62787d01f/oneLiner.js#L33-L41):

```
  if (/complete|interactive|loaded/.test(document.readyState)) {
    installHUD()
  } else {
    document.addEventListener('readystatechange', () => {
      if (document.readyState === 'interactive') {
        installHUD()
      }
    }, { once: true })
  }
```

Or do a pure DOMContentLoaded solution where you check against a global state that you flip in a DOMContentLoaded listener

**Comment by dmarcos** [comment]
What about if you encapsulate in a component? It's the recommended A-Frame recommended way to add logic anyways

**Comment by wmurphyrd** [comment]
@dmarcos sure that trivial example would work fine as a component, but let me show you what I'm really working on here, sort of A-Frame's answer to react-three-fiber: [Svelte A-Frame Web Components](https://github.com/immers-space/svawc)

I'm offering to make the fix here, I would suggest keep using DOMContentLoaded but set a flag on the global AFRAME object after it is called so you can check against that instead of readyState

**Comment by vincentfretin** [comment]
@wmurphyrd I didn't understand what your flag on global AFRAME would do... but please experiment, replace the DOMContentLoaded listener by readystatechange listener in all the places where it's used or another solution that would fix your issue, make all the tests pass and we can discuss it further.
