### ISSUE TITLE
Spelling error in light component docs

### ISSUE THREAD

**Issue by foobar404** [aframevr/aframe#5229]
[https://aframe.io/docs/1.4.0/components/light.html#directional](https://aframe.io/docs/1.4.0/components/light.html#directional)

shadow is misspelled (shdadow)

```javascript
<a-light type="directional" light="castShadow:true;" position="1 1 1" intensity="0.5" shdadow-camera-automatic="#objects"></a-light>
```

**Comment by vincentfretin** [comment]
@foobar404 Good catch, please edit the file https://github.com/aframevr/aframe/blob/master/docs/components/light.md directly on GitHub and create a PR with the changes, there is two occurrences to fix.

**Comment by foobar404** [comment]
okay, done [https://github.com/aframevr/aframe/pull/5231](https://github.com/aframevr/aframe/pull/5231)

**Comment by dirkk0** [comment]
Is this the most recent documentation? If yes, then the spelling error is still in it.

https://aframe.io/docs/1.4.0/components/light.html#directional
