### ISSUE TITLE
a-frame 1.4.1 no work, bug

### ISSUE THREAD

**Issue by jhfrek** [aframevr/aframe#5240]
Hi!
I found a bug in version 1.4.1. The picture "hotspot.png" is not displayed if you output it via "IFRAME.registerComponent". In version 1.3.0 everything works fine! I am sending the test code.

https://frill-glaze-bottle.glitch.me
https://glitch.com/edit/#!/frill-glaze-bottle

**Comment by Omegahed** [comment]
I can confirm that the Glitch works in with A-Frame version 1.3.0 but doesn't work in 1.4.1. I'm not sure what changed between versions; but it appears that you are trying to set the wrong property in your example. Please try the following on **line 16** in your Glitch:

Original
```javascript
this.el.setAttribute( "src", "#hotspot" );
```

Revised
```javascript
this.el.setAttribute( "material", "src", "#hotspot" );
```
It looks like you need to set the `src` of the `material` component, not the `src` of the `<a-image>` entity itself.

This does not appear to be an A-Frame bug.

**Comment by jhfrek** [comment]
Yes! Thank you very much! It's working! But it used to always work on older versions without "material". Now it is necessary to specify "material".
