### ISSUE TITLE
Aframe website documentation search hasn't been working for a while

### ISSUE THREAD

**Issue by samyH** [aframevr/aframe#5247]
Can't search the documentation on the Aframe website :(  It's been like this for a few months now any chance of a fix?

![image](https://user-images.githubusercontent.com/9335155/219412355-9c8884a8-2a87-4a88-9d59-4f15424d4a14.png)

**Comment by dmarcos** [comment]
dup https://github.com/aframevr/aframe/issues/5234 

Algolia crawler changed and gotta move to new infrastructure. As a workaround can search in version 1.3.0 https://aframe.io/docs/1.3.0/introduction/ and modify link for 1.4.0
