### ISSUE TITLE
Visual Inspector Crashing 1.4.0

### ISSUE THREAD

**Issue by heysmallfry** [aframevr/aframe#5257]
**Description:** Whenever I click on any primitives on the left side of the inspector, that whole panel just disappears. I realised this is happening because of an mp4 video file I'm using in the scene, because if I delete it the issue stops happening. I don't not know if this is happening with only 'a-video' or other primitives, because I haven't tested it thoroughly. Eventually, I switched to A-Frame 1.3.0 and the issue is completely dealt with.

- A-Frame Version: 1.4.0
- Platform / Device: Running Mac 10.14.6 and using Google Chrome to preview the project
- Reproducible Code Snippet or URL:

**Comment by vincentfretin** [comment]
Probably same issue as a-videosphere #5241 that needs to be investigated.

**Comment by vincentfretin** [comment]
You can reproduce the issue on https://aframe.io/examples/showcase/360-video/
by opening the inspector and clicking the a-videosphere.
![Capture d’écran du 2023-03-14 10-32-59](https://user-images.githubusercontent.com/112249/224960715-04a71124-4baf-43d9-bebd-f94971d8557e.png)
![Capture d’écran du 2023-03-14 10-35-21](https://user-images.githubusercontent.com/112249/224960755-f8604f4b-edb9-481c-961c-4e4577ce3769.png)
`value` is the video tag (`HTMLVideoElement`)
It should really be treated like `HTMLImageElement` getting `value.src`.

**Comment by vincentfretin** [comment]
This issue is fixed in PR https://github.com/aframevr/aframe-inspector/pull/680

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe-inspector/pull/680

It will ship in next A-Frame version. In the meantime one can make a custom build and use it as below

```
<a-scene inspector="url: https://your-url...">
```
