### ISSUE TITLE
<a-camera> does not attach to real iPhone camera. 

### ISSUE THREAD

**Issue by jessicachrist** [aframevr/aframe#5262]
Hi! What I try to to is getting the position and rotation from the camera of my mobile phone. Unfortunately it doesn't work and always stays at the same position and rotation. Even if I'd update the position (sidenote: how to update it to current mobile position according to distance to the marker based tracking?) manually, the position stays like the initial position. I think I don't get how positioning in real time works with A-Frame... Any hint is appreciated! Thanks

Using MindAR and React. 

- A-Frame Version: 1.13.0
- Platform / Device: iPhone SE, Safari
- Reproducible Code Snippet or URL:
- AFRAME.registerComponent('track-camera', {
    update: (function () {
        const position = new THREE.Vector3();
        const rotation = new THREE.Quaternion();
        const euler = new THREE.Euler();
        const matrix = new THREE.Matrix4();
        return function () {
            // local
            // var position = this.el.getAttribute('position');
            // var rotation = this.el.getAttribute('rotation');
            // console.log("Position: " + position.x + " " + position.y + " " + position.z);
            // console.log("Rotation: " + rotation.x + " " + rotation.y + " " + rotation.z);

            this.el.object3D.updateMatrixWorld();
            position.setFromMatrixPosition(this.el.object3D.matrixWorld); // Vector3
            rotation.setFromRotationMatrix(matrix.extractRotation(this.el.object3D.matrixWorld ));
            
            console.log("Position: " + position.x + " " + position.y + " " + position.z);
            console.log("Rotation: " + rotation.x + " " + rotation.y + " " + rotation.z);
        }
    })()
});
(https://glitch.com/edit/#!/instinctive-vaulted-regnosaurus?path=index.html%3A36%3A22)

**Comment by dmarcos** [comment]
This seems a question for the MindAR folks. We use github issues for bug reports and feature requests. For usage questions you might want to consider [StackOverflow](https://stackoverflow.com/questions/tagged/aframe). Thanks for understanding and best of luck
