### ISSUE TITLE
Collada model doesn't load

### ISSUE THREAD

**Issue by addy1997** [aframevr/aframe#5263]
**Description:**

- A-Frame Version: 1.2.0
- Platform / Device: Windows 11/ Bing
- Reproducible Code Snippet or URL: https://jsfiddle.net/adwait3301/ybupx53m/34/

Hi @jhsu, 
 
I am trying to replicate this [bounding box](https://github.com/gftruj/webzamples/blob/master/aframe/models/bounding_boxes.html) example. The browser I am using is Mozilla Firefox (latest version).

My aim is to load the stormtrooper.dae model, which I am not able to load due to the warning message shown below:

ERROR1: device:error WebXR session support error: Failed to execute 'isSessionSupported' on 'XRSystem': Access to the feature "xr" is disallowed by permissions policy.

ERROR2: Cross-Origin Read Blocking (CORB) blocked cross-origin response

Any help is appreciated.

Thanks,
Adwait

**Comment by jhsu** [comment]
@addy1997 that's not my example, did you mean to tag someone else?

**Comment by addy1997** [comment]
> @addy1997 that's not my example, did you mean to tag someone else?

@jhsu, apologies, it happened by mistake. Could you possibly help me with this?
