### ISSUE TITLE
Asset-Loading timeout

### ISSUE THREAD

**Issue by Dirk-27** [aframevr/aframe#5265]
**Description:**

Loading the image https://cdn.vrdoro.com/data/vrdoro/images/11-PANORAMA/1627655640671-medium.jpg (or any other image from this cdn) shows a timeout and blocks rendering the screen altthoug everything is loading quick. This happens since A-FRAME 1.4 and not with A-FRAME 1.3.

The browser log shows:
`core:a-assets:warn Asset loading timed out in   3000 ms`

- A-Frame Version: 1.4.0, 1.4.1 and master (@ae14e6d8f4685cd776e4c807d9ce70137e1d28d4)
- Platform / Device: Browser chrome, desktop.
- Reproducible Code Snippet or URL from Glitch: 
   - View: https://rectangular-subsequent-anatosaurus.glitch.me
   - Edit: https://glitch.com/edit/#!/rectangular-subsequent-anatosaurus

The asset loading timeout didn't appear with the image from `https://aframe.io/aframe/examples/boilerplate/panorama/puydesancy.jpg`
but appears with the image from
`https://cdn.vrdoro.com/data/vrdoro/images/11-PANORAMA/1627655640671-medium.jpg.`
or
`https://cdn.glitch.global/cc845320-aab0-42bd-a13a-b92d110c330c/pano1.jpg`

The timeout didn't appear in A-FRAME Version 1.3.0.

I add a screenshot with the differences in the response headers:

![image](https://user-images.githubusercontent.com/45331389/228785568-d7e14231-de4e-450a-b078-6db0156c9104.png)

**Comment by dmarcos** [comment]
It's loading for me. maybe your network is blocking that domain somehow?

![image](https://p199.p4.n0.cdn.getcloudapp.com/items/DOulBoKZ/8fbe2f72-5053-4d24-b376-6583f9ed5b2b.jpg?source=viewer&v=6a7867f9d6bc3bffdf2fca83978eb52c)

**Comment by Dirk-27** [comment]
That's right, it's loading. Everything loads immediately, but the asset system doesn't notice. It waits for the image to load. It may not be possible to observe this on slow networks.

![image](https://user-images.githubusercontent.com/45331389/229041819-b22e6146-3d23-494c-9865-cdd6a7130b76.png)

![image](https://user-images.githubusercontent.com/45331389/229041984-601502ac-0e76-482a-94ae-faadcd6b456c.png)

We have not seen this behavior on mobile Chrome or Firefox. Even on Chrome desktop, it works sometimes. But most of the time it does not.

This can not be observed with A-FRAME 1.3, so something must be different.

**Comment by vincentfretin** [comment]
Downloading 2.7MB in less than 3s on slow network is just not possible, You can increase the timeout to 30s really
`<a-assets timeout="30000">`

**Comment by Dirk-27** [comment]
Here is a new waterfall view from the network tab of the chrome inspector:

![image](https://user-images.githubusercontent.com/45331389/229078238-49b42f2f-4c7c-427d-a516-c76b35aa192e.png)

**Comment by vincentfretin** [comment]
I indeed reproduce what you've shown with a bigger timeout="20000", the image is downloaded but we still see the loading screen for about 15s.
I couldn't reproduce with aframe master, something may have been fixed after the 1.4.1 release. Can you please confirm it's fixed with 
```
<script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@2edc422bfed6f64bc1bed83f299815986b78f406/dist/aframe-master.min.js"></script>
```

**Comment by Dirk-27** [comment]
Unfortunately, this did not change anything. The error does not always occur, but for me it was the case in 19 out of 20 attempts.

![image](https://user-images.githubusercontent.com/45331389/229096818-a2f8c26a-817a-4366-9c9e-8a3496ec4c66.png)

**Comment by Dirk-27** [comment]
Again: The issue did not appear, when we switch back to aframe v1.3.

But, some strange thing: It also didn't appear in v1.4 or master when the Chrome inspector is not open!

**Comment by dmarcos** [comment]
Problem is only with that CDN? Anything special about it? Can we find another one where the problem reproduces?

**Comment by Dirk-27** [comment]
Yes, if we use the glitch cdn and load the image from here: `https://cdn.glitch.global/cc845320-aab0-42bd-a13a-b92d110c330c/pano1.jpg`.

I have changed the example to glitch.

Take a look: When you open the glitch `https://rectangular-subsequent-anatosaurus.glitch.me/` for the first time in an anonymous tab, you will see the timeout (3 seconds a blue loading screen) even if the inspector is closed! This will most likely be the first user experience.

This unfortunately increases the severity of the problem.

**Comment by dmarcos** [comment]
Try this glitch: https://glitch.com/edit/#!/curly-glittery-possum?path=index.html%3A7%3A33

**Comment by Dirk-27** [comment]
In your glitch I can't see the bug! But why do I see it on my glitch with the master https://cdn.jsdelivr.net/gh/aframevr/aframe@2edc422bfed6f64bc1bed83f299815986b78f406/dist/aframe-master.min.js (hash from 30.3.2023) which should contain the fix?

**Comment by vincentfretin** [comment]
@Dirk-27 I also mixed your glitch, even did an aframe master build with some console.log related to the different state img.complete, hasLoaded and so on, but I can't reproduce anymore.
https://glitch.com/edit/#!/vfretin-aframe-issue-5265
You can try using my aframe build in your glitch to see if there is some interesting logs with the time in seconds, maybe you can identify where it blocks if you reproduce.
Currently it's working fine:
![Capture d’écran du 2023-04-04 10-50-31](https://user-images.githubusercontent.com/112249/229740491-22bab8e0-9cc6-45ee-8c0a-5d559d4f0638.png)
![Capture d’écran du 2023-04-04 10-52-43](https://user-images.githubusercontent.com/112249/229740532-135c13ea-d6e4-4de6-b1e2-da8008567e37.png)

**Comment by Dirk-27** [comment]
@vincentfretin , @dmarcos : I can confirm that the master-min.js you added in the glitches has solved the problem!

The only question is: Why does the official master-CDN-URL not contains this fix?

Here is one of the relevant differences (left the master-cdn, right your master.js from the glitch).

![image](https://user-images.githubusercontent.com/45331389/229771602-55a95ba2-5271-45cb-82dc-d69f9893cf94.png)

It looks like the 'master build' you use is made from the development branch and the changes are not merged in master yet? Or how can we explain, that the oficial master CDN URL not contains the fix? Should we open another issue for this?

**Comment by vincentfretin** [comment]
Wait, you're right, the bot isn't committing anything, like for my latest merged PR, the bot didn't commit the modified dist
https://github.com/aframevr/aframe/commit/917cd02f8a5f7d939571e59fe1f73116bcc89657

**Comment by vincentfretin** [comment]
Yes neither @Dirk-27 or me reproduce the issue on master so it was indeed the changes in #5253 that fixed it.

**Comment by Dirk-27** [comment]
@dmarcos , @vincentfretin : I added a new issue: https://github.com/aframevr/aframe/issues/5269 and close this one. Will there be a new 1.4.2 version of aframe? If not, which master commit do you recommend as a stable build that contains the fix?

**Comment by vincentfretin** [comment]
@Dirk-27 use the latest commit really, you have other fixes since the 1.4.1 release.

**Comment by Dirk-27** [comment]
@vincentfretin : Is it somehow tested? We want to use it in production builds.

**Comment by vincentfretin** [comment]
Currently on master there are only bugfixes, no big updates. I'm only using master in production :)

**Comment by Dirk-27** [comment]
Thank you very much!
