### ISSUE TITLE
Component remove failed on null geometry

### ISSUE THREAD

**Issue by eherve** [aframevr/aframe#5266]
**Description:**

- A-Frame Version: 1.4.1
- Platform / Device: Google Chrome / Mac Book

When adding entity text in scene
```
<a-entity text="value: 10; color: #ffffff; font: roboto; width: 140; wrapCount: 2; baseline: center; align: right; lineHeight: 36;" position="344 190 -70" rotation="0 -90 0"></a-entity>
```
I have an error on removing the component when the scene document is destroyed.
It seems that the geometry in the Component is null so when calling ```this.geometry.dispose()``` in the Component remove function it fails :
<pre>
aframe-master.js:21557 Uncaught TypeError: Cannot read properties of null (reading 'dispose')
    at NewComponent.remove (aframe-master.js:21558:19)
    at AEntity.removeComponent (aframe-master.js:24891:15)
    at AEntity.disconnectedCallback (aframe-master.js:24617:12)
</pre>

I printed the component before dispose and i do have a null geometry :
```
attrName: "text"
attrValue: {value: '9', color: '#ffffff', font: 'roboto', width: 140, wrapCount: 2, …}
currentFont: {pages: Array(1), chars: Array(95), info: {…}, common: {…}, kernings: Array(396), …}
data: {value: '9', color: '#ffffff', font: 'roboto', width: 140, wrapCount: 2, …}
el: a-entity#text.ng-star-inserted
events: {}
evtDetail: {id: undefined, name: 'text'}
geometry: null
id: undefined
initialized: true
isObjectBased: true
isPlaying: false
isSingleProperty: false
isSinglePropertyObject: false
justInitialized: true
material: null
mesh: Mesh {isObject3D: true, uuid: 'fbb5806a-ad9e-489b-bda0-94ce2c740443', name: '', type: 'Mesh', parent: null, …}
nextData: {value: '9', color: '#ffffff', font: 'roboto', width: 140, wrapCount: 2, …}
objectPool: {pool: Array(5120), grow: ƒ, recycle: ƒ, size: ƒ, use: ƒ}
oldData: {value: '9', color: '#ffffff', font: 'roboto', width: 140, wrapCount: 2, …}
parsingAttrValue: {value: '9', color: '#ffffff', font: 'roboto', width: '140', wrapCount: '2', …}
previousOldData: {value: '9', color: '#ffffff', font: 'roboto', width: 140, wrapCount: 2, …}
shaderData: {alphaTest: 0.5, color: '#ffffff', map: Texture, opacity: 1, side: 1, …}
texture: null
throttledEmitComponentChanged: ƒ ()
```

I tried to manually add a geometry in the a-entity but with no luck.

**Comment by dmarcos** [comment]
What do you mean by "I have an error on removing the component when the scene document is destroyed" Can you share full runnable code with https://glitch.com/~aframe?

**Comment by dmarcos** [comment]
Closing for now but if you can provide runnable code to reproduce happy to reopen and look at it.
