### ISSUE TITLE
unexpected hit on raycaster

### ISSUE THREAD

**Issue by Utopiah** [aframevr/aframe#5268]
**Description:** copy/pasting the example from the documentation  https://aframe.io/docs/1.4.0/components/raycaster.html#example the console does display a hit.

The event is : 

```
raycaster-intersection { target: a-entity#player, isTrusted: false, detail: {…}, srcElement: a-entity#player, eventPhase: 0, bubbles: true, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
bubbles: true
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
detail: Object { els: (4) […], intersections: (4) […] }
eventPhase: 0
explicitOriginalTarget: <a-entity id="player" collider-check="" raycaster="">
isTrusted: false
originalTarget: <a-entity id="player" collider-check="" raycaster="">
returnValue: true
srcElement: <a-entity id="player" collider-check="" raycaster="">
target: <a-entity id="player" collider-check="" raycaster="">
timeStamp: 698
type: "raycaster-intersection"
<get isTrusted()>: function isTrusted()
<prototype>: CustomEventPrototype { initCustomEvent: initCustomEvent(), detail: Getter, … }
```

Which seems to return itself as a target.

Changing `objects` to a non present selector e.g `.abcdef` gives the same result.

- A-Frame Version: A-Frame Version: 1.4.1 (Date 2023-01-04, Commit #5183a179) index.js:95:8
- Platform / Device: desktop running Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0
- Reproducible Code Snippet or URL: https://aframecaster.glitch.me/

The inspector shows that the line and the cube do not intersect.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1076655/229539968-d27af9ba-3f47-43eb-b389-969f63a09fb2.png">

**Comment by dmarcos** [comment]
Example was wrong / outdated. `collider-check` has to be on the entity with the raycaster or otherwise the component dependency will add another raycaster to the player entity that it's the one that produces the undesired hits.

Just updated the docs. A glitch with the corrected code:

https://glitch.com/edit/#!/auspicious-weak-dream?path=index.html%3A11%3A91

**Comment by Utopiah** [comment]
Super, thanks a lot for the clarification and this super fast fix of the doc!
