### ISSUE TITLE
Master-Build from Master-CDN-URL is not in sync with master build

### ISSUE THREAD

**Issue by Dirk-27** [aframevr/aframe#5269]
**Description:**
In the issue https://github.com/aframevr/aframe/issues/5265 we found that the master from the master CDN URL (published here: https://github.com/aframevr/aframe/tree/master/dist) is not the current master with this hash.

The cause of the problem was mentioned at https://github.com/aframevr/aframe/issues/5265#issuecomment-1496212938.

- A-Frame Version: master
- Wrong content in this CDN-URLs: 
   - https://cdn.jsdelivr.net/gh/aframevr/aframe@2edc422bfed6f64bc1bed83f299815986b78f406/dist/aframe-master.min.js
   - https://cdn.jsdelivr.net/gh/aframevr/aframe@2edc422bfed6f64bc1bed83f299815986b78f406/dist/aframe-master.js

**Comment by dmarcos** [comment]
As mentioned it's because Github updated the SSH host key:

https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

**Comment by dmarcos** [comment]
This should be fixed now
