### ISSUE TITLE
Large videos not working correctly on macOs Safari

### ISSUE THREAD

**Issue by Alessioforlante** [aframevr/aframe#5270]
Large videos (100ish megabytes and up) struggle to load on macOS Safari. I've been testing for days now and the conclusion I have arrived at is that it is an issue with either Safari itself or A-Frame. The machine I am running it on is a m2 mac mini I have had for less than two weeks.

When are that large, it will struggle to load, even when hosted locally: It will stutter or freeze.

I have created a barebones project to confirm that my code was not causing it.

I am using this video as a test: https://www.youtube.com/watch?v=DzcVytVIzzs&t=1s 
The video can be downloaded in full quality here: https://www.demolandia.net/4k-video-test/brands/lg/page-2.html

- A-Frame Version: 1.4.0
- Platform / Device: Safari 16.4 on macOS Ventura 13.3 
- Reproducible Code Snippet or URL: 
-
<script src="https://aframe.io/releases/1.4.0/aframe.min.js"></script>

<script>

  //goes from main menu to lobby 
  AFRAME.registerComponent('start', {
    init: function () {
      this.el.addEventListener('click', function () {
        video.setAttribute('src', YOUR LARGE VIDEO LINK HERE)})}})

</script>

<a-scene>

  <a-videosphere id="video"></a-videosphere>

  <a-entity id="cursorObject" class="not_clickable" data-isButton="true" raycaster="objects: .clickable"
    position="0 0 -1" fuse="false" geometry="primitive: sphere; radius: 0.001" mouseCursorStylesEnabled=true
    material="color: #000000; shader: flat; opacity: 0.5" cursor="rayOrigin: mouse;">
  </a-entity>

  <a-image id="buttonStart" class="clickable" src="resources/images/shared/guiReady.png" material="alphaTest: 0.5"
    height="0.3" width="1" position="0 0.6 -2" start></a-image>

**Comment by polytropoi** [comment]
For it to stream you must encode to a streaming format, like HLS, and use the client software - https://github.com/video-dev/hls.js/ this works great in A-Frame on all platforms, including iOS.

**Comment by dmarcos** [comment]
@polytropoi thanks for the recommendation. you rock

**Comment by Alessioforlante** [comment]
@polytropoi Thanks alot for that! I just wanted to ask, would it work on videospheres? I

**Comment by polytropoi** [comment]
I'm pretty sure it would work for 360 video, and that's on my TODO list, but I haven't done it yet.  :)

**Comment by Derkades** [comment]
An example for using HLS.js with aframe (like a-videosphere) would be great, I can't find any documentation currently

**Comment by dmarcos** [comment]
I don’t think there’s anything specific to A-Frame that will render anything through a video tag. As stated in HLS.js readme:

`HLS.js works directly on top of a standard HTML<video> element`

**Comment by dmarcos** [comment]
I don't think there's anything actionable on the A-Frame side. Seems this is HLS.js usage and / or Safari limitations. Closing but can reopen if necessary.
