### ISSUE TITLE
Image rendering issues as spots

### ISSUE THREAD

**Issue by pemonter** [aframevr/aframe#5274]
I'm trying to create a scene with infospots and hotspots. On desktop and androids they render perfectly, but on iOS devices a black square is displayed instead of the spots.

Here you can access my testing code: [https://glitch.com/edit/#!/darkened-rain-wishbone?path=index.html%3A5%3A45](https://glitch.com/edit/#!/darkened-rain-wishbone?path=index.html%3A5%3A45)

- A-Frame Version: 1.0.4
- Platform / Device: iOS

**Comment by dmarcos** [comment]
You should be using the latest version: 1.4.1

**Comment by dmarcos** [comment]
Also I don't think you need to import the animation component or the inspector. I recommend code as simple you can make to reproduce the issue. It will be much easier to help and diagnose any issues. Best of luck.

**Comment by dmarcos** [comment]
Closing this. It this still reproduces with 1.4.2 happy to reopen.
