### ISSUE TITLE
The gltf model cannot reproduce the Dindahl effect

### ISSUE THREAD

**Issue by jiahuamld** [aframevr/aframe#5280]
**Description:**

- A-Frame Version: 1.4.1
- Platform / Device: iphone 12
- Reproducible Code Snippet or URL:

Use this module
https://aframe.io/docs/1.4.0/primitives/a-gltf-model.html

The gltf model cannot reproduce the Dindahl effect
<img width="130" alt="image" src="https://user-images.githubusercontent.com/11866846/235303392-8d2373e5-b7f5-4522-8088-cb9747fc906d.png">

**Comment by jiahuamld** [comment]
https://threejs.org/docs/#examples/zh/loaders/GLTFLoader

Is 1.4.1 or 1.4.2 using the latest gltf loader ?

**Comment by dmarcos** [comment]
A-Frame is on THREE r147. What is needed to render the Dindahl effect? Can you share an example to reproduce? Did you test your model in the [gltf-viewer](https://gltf-viewer.donmccurdy.com/)

**Comment by jiahuamld** [comment]
https://zh.wikipedia.org/wiki/%E5%BB%B7%E5%BE%97%E8%80%B3%E6%95%88%E6%87%89   
need this effect

**Comment by dmarcos** [comment]
closing for now. If there's additional info happy to reopen
