### ISSUE TITLE
A white screen appears instead of a camera when the site is opened in another tab

### ISSUE THREAD

**Issue by batelhi** [aframevr/aframe#5283]
**Description:**
A white screen appears instead of a camera when the site is opened in another tab. 
(The camera only works after reloading the site)

- A-Frame Version: https://aframe.io/releases/1.4.0/aframe.min.js
- Platform / Device: Android - chrome browser
- Reproducible Code Snippet or URL:  https://spacego.space-valley.com/

**Comment by dmarcos** [comment]
Not sure what stack are you using? Probably the camera permissions are not preserved when opening a new tab as per browser policies. Do you have a simple example to reproduce with https://glitch.com/~aframe?

**Comment by dmarcos** [comment]
Closing for now. If you have an example to reproduce. Happy to look at it.
