### ISSUE TITLE
Second UV map isn't shown correctly

### ISSUE THREAD

**Issue by dirkk0** [aframevr/aframe#5288]
**Description:**

- A-Frame Version: 1.4.1
- Platform / Device: PopOs/PC
- Reproducible Code Snippet or URL: (I can provide a Glitch but I think the case is clear)

I open this issue to show that THREE and glTF can have a second UV map. This is not working yet in A-Frame though, because the gltfLoader in this version of THREE isn't supporting it:

``` THREE.GLTFLoader: Custom UV set 1 for texture emissiveMap not yet supported.```

I think that this issue will go away automagically once A-Frame is updated to THREE r151.

This is how it looks like in Don's glTF Viewer:

![image](https://user-images.githubusercontent.com/625394/236387092-df23e602-5f40-42c6-ac46-f126c85e728a.png)

This is how it looks like with A-Frame 1.4.1:

![image](https://user-images.githubusercontent.com/625394/236387196-6cd39c15-d96f-4f1f-84ad-069d9c599f27.png)

And this is how the material is set up in Blender:

![image](https://user-images.githubusercontent.com/625394/236386928-e3458acf-8934-4ef5-956f-c73f0cec8a60.png)

For the record: I got an idea how to do this after watching this video by the Mozilla Hubs guys:
https://www.youtube.com/watch?v=YFV33iCXXmo

zip file with .blend and export.glb:
[gltf-test.zip](https://github.com/aframevr/aframe/files/11403691/gltf-test.zip)

**Comment by dmarcos** [comment]
Thanks. I'll bump three soon

**Comment by dmarcos** [comment]
Master is now on THREE r152. Can you give it a try? Thanks so much

**Comment by dirkk0** [comment]
yessiree!

![image](https://user-images.githubusercontent.com/625394/236614397-6cac9e66-f00a-48b0-9c29-a5fec739118b.png)

Thanks!!
