### ISSUE TITLE
Changing the layout for the loading-screen

### ISSUE THREAD

**Issue by atlllas** [aframevr/aframe#5291]
Is it possible to change the loading-screen altogether?

I'd like to skip the three dots page and swap it out for one of my own.

If it's not possible, I'd like to change the font of the title page at least! Thank you :)

**Comment by dmarcos** [comment]
You can disable the existing one and implement your own"

 `<a-scene loading-screen="enabled:false;">`

You might wanna read https://stackoverflow.com/questions/48032829/set-a-loading-animation-with-a-frame/73915508#73915508

Closing this. We use Github issues for bugs and feature requests. For usage questions I recommend [StackOverflow](https://stackoverflow.com/questions/tagged/aframe) and [Discord](https://discord.gg/rpWDHf9Y)

**Comment by dmarcos** [comment]
For the font alone you can use CSS:

https://aframe.io/docs/1.4.0/components/loading-screen.html#sidebar
