### ISSUE TITLE
Uncaught TypeError: e.xr.getEnvironmentBlendMode is not a function (three r152)

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#5292]
**Description:**

I got this error in aframe inspector master that uses aframe master build
```
Uncaught TypeError: e.xr.getEnvironmentBlendMode is not a function
```
and the scene stays black.

This is probably related to three r152 update.

- A-Frame Version: master on three r152
- Platform / Device: Chrome desktop
- Reproducible Code Snippet or URL: https://aframe.io/aframe-inspector/examples/

**Comment by dmarcos** [comment]
Thanks. PRs welcome

**Comment by dmarcos** [comment]
thanks. I think the webvr code path should only run if there’s a webvr implementation?

**Comment by mrxz** [comment]
> thanks. I think the webvr code path should only run if there’s a webvr implementation?

Not quite, the decision between `WebXRManager` and `WebVRManager` is made based on the presence of the _WebXR API_. If that isn't present, the `WebVRManager` is always picked. Normally this isn't an issue as without an actual WebVR implementation, it doesn't really do anything. But the recent changes in Three.js now unconditionally call into it (`renderer.xr.getEnvironmentBlendMode()`).

**Comment by vincentfretin** [comment]
Ah I got the error initially when running aframe-inspector locally with `npm start` because it doesn't use https. I don't have the error in https.

**Comment by mrxz** [comment]
> can you elaborate? in what scenario we’re trying to invoke that function if we’re not in immersive mode?

Three.js always invokes this function, regardless of immersive mode (see: https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLBackground.js#L48). So it isn't really something we're invoking ourselves. The implementation handles the absence/presence of a session.

**Comment by Matsxmats** [comment]
I have the error in Safari even when using https.  Both mobile and desktop, and it just gives me a white screen.

**Comment by mrxz** [comment]
@Matsxmats Safari doesn't support WebXR (yet), so that explains why you're seeing the error even when using https. A fix (https://github.com/supermedium/three.js/pull/11) has been merged in super-three, but this hasn't landed in aframe master yet. If you're feeling adventurous you can compile your own copy with the fix included, or stick with an older version for the time being.

**Comment by Dirk-27** [comment]
@Matsxmats : you can try the patched aframe-v1.4.2_ad40be-p1.min.js from https://worried-remarkable-modem.glitch.me (see #5306). For mobile devices, you need to pick up the device and search for the scene content, as the device orientation is taken into account.

**Comment by mrxz** [comment]
This can be closed as aframe master now uses a super-three version including the fix from https://github.com/supermedium/three.js/pull/11

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/commit/d74c46ffe0a81171a5a014dceba3e681affcd3d0
