### ISSUE TITLE
Warning about physicallyCorrectLights that was renamed to useLegacyLights (three r152)

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#5293]
**Description:**

```
THREE.WebGLRenderer: the property .physicallyCorrectLights has been removed. Set renderer.useLegacyLights instead.
```

I commented about this in https://github.com/aframevr/aframe/pull/5210#issuecomment-1520194017

- A-Frame Version: master on three r152
- Platform / Device: Chrome desktop
- Reproducible Code Snippet or URL: https://aframe.io/aframe-inspector/examples/

**Comment by dmarcos** [comment]
Thanks. PRs welcome
