### ISSUE TITLE
Warning mergeBufferGeometries renamed to mergeGeometries (three r152)

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#5294]
**Description:**

Warning 
```
THREE.BufferGeometryUtils: mergeBufferGeometries() has been renamed to mergeGeometries().
```

- A-Frame Version: master on three r152
- Platform / Device: Chrome desktop
- Reproducible Code Snippet or URL: https://aframe.io/aframe-inspector/examples/

**Comment by dmarcos** [comment]
Thanks. PRs welcome

**Comment by vincentfretin** [comment]
This one is actually in the environment component, see https://github.com/supermedium/aframe-environment-component/pull/86
