### ISSUE TITLE
Oculus Touch Controls Direction Alignment.

### ISSUE THREAD

**Issue by na-stewart** [aframevr/aframe#5296]
**Description:**

The forward direction of the Oculus controller since migrating to 1.4.0 has changed. This is noticeable in the direction of the teleportation-controls ray (dark blue line) compared to the laser-controls ray (light blue line). The child elements of the oculus controller are also affected by this as the position of the children objects are undesirable and match the teleportation-controls ray which is above the controller rather than sitting directly in front of the controller. Please create a way to configure the rotation orientation of the oculus controls or provide a fix.

To reiterate, the previous orientation worked with our project whereas the current orientation breaks it. This is why it needs to be changed.

A screenshot is attached to provide context, thanks!

- A-Frame Version: 1.4.0
- Platform / Device: Oculus Quest 2
- Reproducible Code Snippet or URL:
- 
      

      <a-entity
        id="player"
        rotation="0 145 0"
        position="8.012 0 -6.058"
        simple-navmesh-constraint="navmesh:.navmain;fall:0.5;height:0;exclude:.exclude-main;"
        movement-handler
        movement-controls="speed:0.15;camera:#camera;enabled:true;"
        scene-boundary
      >
        <a-entity
          id="camera"
          position="0 1 0"
          camera
          look-controls="pointerLockEnabled:true;"
        >
          <a-entity
            carry-position-handler
            look-at="[camera]"
            id="carry-position"
            position="0 0 -1.3"
          ></a-entity>
          <a-entity
            id="cursor"
            position="0 0 -0.1"
            geometry="primitive: ring; radiusInner: 0.001; radiusOuter: 0.002"
            material="color: black; shader: flat"
            cursor-handler
            cursor
            raycaster="objects:.interactable,.collidable;"
          ></a-entity>
          <a-box
            id="fade-box"
            scale="0.3 0.2 0.010001"
            color="black"
            shader="flat"
            side="double"
            visible="false"
          ></a-box>
        </a-entity>
        <a-entity
          id="right-hand"
          oculus-touch-controls="hand:right;"
          sound="src:url(media/oga/teleport.oga);on:teleported;"
          blink-controls="collisionEntities:.nav;landingMaxAngle:360;rotateOnTeleport:false;"
          laser-controls
          raycaster="objects:.interactable,.collidable;lineOpacity:1;lineColor:lightblue;"
          carry-controls
        >
          <a-plane
            id="info-hand-tablet"
            position="-0.05 0.1 -0.1"
            rotation="-50 10 0"
            scale="0.4 0.2 0"
            color="#222222"
            shader="flat"
            visible="false"
          >
            <a-text
              id="info-hand-text"
              position="0 0.01 2"
              scale="0.2 0.34 1"
              text="value:test"
              align="center"
              wrap-count="34"
            ></a-text>
          </a-plane>
        </a-entity>
      </a-entity>

![com oculus browser-20230602-153059](https://github.com/aframevr/aframe/assets/39848845/b4b8ab9a-8ea9-4731-8ed9-cdb6fa57226c)

**Comment by dmarcos** [comment]
I'm not familiar with your teleportation setup but the controller and laser orientation is now the correct one. We use the one reported by the WebXR API instead of a hardcoded one. It should match the models and laser of the native UI.

**Comment by na-stewart** [comment]
> I'm not familiar with your teleportation setup but the controller and laser orientation is now the correct one. We use the one reported by the WebXR API instead of a hardcoded one. It should match the models and laser of the native UI.

This doesn't really help. The laser-controls are therefor using an incorrect orientation. How would I configure to fix this?

**Comment by dmarcos** [comment]
The ray from laser controls should be correct. I would adjust teleport controls. Maybe I’m not understanding the problem

**Comment by na-stewart** [comment]
@dmarcos Maybe I'm getting confused as well. I made a simple fix where the blue ray vanishes when teleporting instead of worrying about configuration. Smooth enough for now, thanks!
