### ISSUE TITLE
Left eye used for camera position instead of center

### ISSUE THREAD

**Issue by mrxz** [aframevr/aframe#5299]
**Description:**
I noticed that the position and orientation of the active `<a-camera>` is taken from the left eye, as opposed to a central position between the eyes (as Three.js does by default). Turns out the custom changes to the `WebXRManager` in super-three are at fault. Pull request addressing the issue:  https://github.com/supermedium/three.js/pull/12

Creating this ticket in case anyone else encounters this issue before a fix lands or when running an older version.

In short, this means that any child of `<a-camera>` will not be centered around the "head", but around the left eye. Similarly for locomotion that rotates around the current head position, it actually rotates around the left eye. And any gaze based raycasting will also take originate from the left eye.

- A-Frame Version: 1.4.2
- Platform / Device: Quest 2
- Reproducible Code Snippet or URL: 
```HTML
<a-scene>
    <a-camera id="camera">
        <a-box color="gray" width="0.02" height="0.02" depth="0.02" position="0 0 -0.5"></a-box>
        <a-box color="red" width="0.01" height="0.02" depth="0.02" position="-0.0051 0 -0.501"></a-box>
        <a-box color="red" width="0.01" height="0.02" depth="0.02" position="0.0051 0 -0.501"></a-box>
    </a-camera>
</a-scene>
```
In the above example the gray box is viewed "head-on", with on the left and right sides red boxes slightly protruding. Currently looking through your left eye only shows a head-on view (sides not visible), whereas the right eye shows the right side. Expected is that both left and right views are mirrored images (left eye shows a bit of the red left side, right eye shows a bit of the red right side).

**Comment by dmarcos** [comment]
I see. only in immersive mode. thanks
