### ISSUE TITLE
Hotspot in vr mode

### ISSUE THREAD

**Issue by Roxcsas** [aframevr/aframe#5304]
**Description:**
I made an angular application with a-frame where the a-sky is a 360° image but when i enter in vr mode with the oculus GO the position of all a-entity is totally different from the position i see on the browser before entering in vr mode

- A-Frame Version: 1.4.2
- Platform / Device: browser/Oculus GO

**Comment by dmarcos** [comment]
Can you share a link to the example? otherwise hard to know what's going on.

Also FYI Oculus Browser and Go have been discontinued by Meta and no longer get any updates.

**Comment by Roxcsas** [comment]
I fixed it by adding a camera with a position
