### ISSUE TITLE
Bounding sphere of text is never updated, resulting in incorrect frustum culling

### ISSUE THREAD

**Issue by mrxz** [aframevr/aframe#5311]
**Description:**
The `text` component generates geometry using (a fork of) `three-bmfont-text`. The first frame that the text mesh is part of the scene graph its bounding sphere will be computed for frustum culling. Once computed any subsequent change that updates the geometry doesn't update the bounding sphere. This can lead to the text being frustum culled incorrectly if the text geometry ended up larger than it initially was.

Working on a fix for this, but creating this ticket as it spans multiple repositories

- A-Frame Version: master (7663c2f979445197960255692e2b5306230a5911)
- Platform / Device: Any
- Reproducible Code Snippet or URL:

**Comment by mrxz** [comment]
PR containing a fix: https://github.com/dmarcos/three-bmfont-text/pull/2
PR on the aframe side bumping the version and introducing a unit test covering this case: https://github.com/aframevr/aframe/pull/5312

**Comment by dmarcos** [comment]
Nice thanks very much. Noticed the issue never went down the path to investigate!
