### ISSUE TITLE
Docs: Search bar not working (no results for anything)

### ISSUE THREAD

**Issue by turbotimon** [aframevr/aframe#5322]
**Description:**

In the [documentation](https://aframe.io/docs/1.4.0/introduction/) the search bar does not show results for anything. This has been the case for at least a week and has been tested with several browsers:

![image](https://github.com/aframevr/aframe/assets/57718207/d4938671-a1b5-4397-96ab-cdc4cef56d85)

**Comment by dmarcos** [comment]
Algolia integration is broken at the moment. Can use older versions search for now as a workaround https://aframe.io/docs/1.3.0/introduction/

Sorry for the inconvenience.

**Comment by vincentfretin** [comment]
This is also reported at:
- https://github.com/aframevr/aframe-site/issues/527
- https://github.com/aframevr/aframe-site/issues/528

**Comment by msub2** [comment]
Is there anything we can do to help with this? Or is the Algolia integration something you're managing specifically

**Comment by dmarcos** [comment]
This is an algolia issue. algolia API was completely revamped and at some point stopped indexation of new pages. that's why search of old versions of a-frame still work. Any help appreciated but requires both work on the [front end](https://github.com/aframevr/aframe-site/blob/master/themes/aframe/layout/partials/search.ejs) and Algolia side. I'm in a free Algolia account anyone can play with it locally by replacing the apiKey.

**Comment by msub2** [comment]
Interesting, I'll see if I can take a look soon

**Comment by dmarcos** [comment]
In short if it was not clear. We need to move A-Frame website to the new Algolia API. The old one no longer indexes new pages.

**Comment by msub2** [comment]
It seems as though the new version of docsearch wants you to apply (and wants to verify you are the owner of the docs being indexed among other things) https://docsearch.algolia.com/apply/. Don't know if you've already seen this @dmarcos. Looks like under the hood it's using their Algolia Crawler which doesn't have the same restriction though.

**Comment by lainshiHenry** [comment]
> It seems as though the new version of docsearch wants you to apply (and wants to verify you are the owner of the docs being indexed among other things) https://docsearch.algolia.com/apply/. Don't know if you've already seen this @dmarcos. Looks like under the hood it's using their Algolia Crawler which doesn't have the same restriction though.

As long as the owner enables permissions to update, that sound work too.

"You must be the owner of the website, or at least have the permissions to update its content." (https://docsearch.algolia.com/docs/who-can-apply)

**Comment by dmarcos** [comment]
You can develop locally with your own account. I already did the application. Just haven’t had the time to migrate to the new API / infrastructure

**Comment by dmarcos** [comment]
This is fixed now. Thanks for the patience
