### ISSUE TITLE
VR broken after switch to THREE r154

### ISSUE THREAD

**Issue by nightgryphon** [aframevr/aframe#5330]
**Description:**
VR mode is broken. Some part of scene become attached to camera center of view. The other part of scene randomly rotates around. On other scene the whole scene rotates around viewer...
Non VR mode work fine.

- A-Frame Version: master starting from Jul3
- Platform / Device: Oculus Quest 2
- Reproducible Code Snippet or URL: examples/test/cube/ - cube always in center so you always look straight at cube while scene with lights rotates around

**Comment by vincentfretin** [comment]
I guess https://github.com/supermedium/three.js/pull/13 fixes it?

**Comment by nightgryphon** [comment]
Yeah. It is. 
I've manually replaced line within compiled module and it becomes fine... How can i replace broken three with the patched one while building aframe?

Also it seems official aframe builds use ungap 1.1.1 while latest is 1.3.0 and according to diff i miss some CSS while building...

**Comment by mrxz** [comment]
> How can i replace broken three with the patched one while building aframe?

You can use `npm link` for this. Simply clone and build super-three locally, run `npm link` in the root of it and then in your local copy of aframe run `npm link super-three`. This should connect the two so that building aframe will use your local copy of super-three.

**Comment by dmarcos** [comment]
This should be now fixed on master
