### ISSUE TITLE
Safari on Apple VisionOS Simulator crashes when any A-Frame app attempts to enter immersive mode.

### ISSUE THREAD

**Issue by DougReeder** [aframevr/aframe#5337]
**Description:**
Safari on Apple VisionOS Simulator (1.0 beta 3 & 4 - 21N5165f and 21N5165g) crashes when any A-Frame app attempts to enter immersive mode.

- A-Frame Version: 1.4.2
- Platform / Device: Safari on Apple VisionOS Simulator (1.0 beta 3 & 4 - 21N5165f and 21N5165g)
- Reproducible Code Snippet or URL:
For the sample apps:
Hello WebVR: immediate dialog "requires device motion"; crash on entering immersive mode
Model Viewer: immediate dialog "requires device motion"; crash on entering immersive mode
Hand Tracking: immediate dialog "requires device motion"; crash on entering immersive mode
Responsive UI: immediate dialog "requires device motion"; crash on entering immersive mode
360deg Image: immediate dialog "requires device motion"; crash on entering immersive mode
360deg Video: immediate dialog "requires device motion"; crash on entering immersive mode
Anime UI: immediate dialog "requires device motion"; crash on entering immersive mode
BeatSaber Viewer: doesn't work in flatscreen mode
Moon Rider (desktop): requires browser to request Mobile site
Moon Rider (mobile): "iOS is not supported"
Gunters of OASIS: doesn't work in flatscreen mode
Supercraft: doesn't work in flatscreen mode
Super Says: goes "fullscreen" instead of immersive
Towermax Fitness (desktop): requires browser to request Mobile site
Towermax Fitness (mobile): doesn't appear in list
A-Blast: goes "fullscreen" instead of immersive
A-Painter: immediate dialog "requires device motion"; crash on entering immersive mode
A-Saturday Night: goes "fullscreen" instead of immersive

As they worked under beta 2, this appear to be a regression in Safari - we'll have to keep checking the betas as they come out.

**Comment by dmarcos** [comment]
A-Frame working on Beta2 as expected for reference:

https://twitter.com/dmarcos/status/1671989929449254918?s=20

**Comment by dmarcos** [comment]
Also notice that old demos like A-Blast, A-Saturday-Night, supercraft... are not expected to work. They're on old A-Frame versions that pre-date the WebXR API.

**Comment by DougReeder** [comment]
We should add some notes to those apps, to reduce confusion.

**Comment by dmarcos** [comment]
Apple has released [Vision OS simulator Beta 3](https://developer.apple.com/documentation/visionos-release-notes/visionos-release-notes) and A-Frame now enters VR mode as expected.
