### ISSUE TITLE
Looking for my first contribution 

### ISSUE THREAD

**Issue by lainshiHenry** [aframevr/aframe#5345]
Creating this issue to look for my first contribution, based on the recommendation from Dmarcos.Eth on Twitter (X)

**Comment by dmarcos** [comment]
Welcome! Let’s try to find something. Do you have any particular area of interest (e.g 3d, inspector, tests, website)

**Comment by lainshiHenry** [comment]
Thanks Diego.

This would be the order of interest and proficiency for myself:
1. Website
2. Documentation
3. 3d (least amount of knowledge, but will love to go this direction once I get more familiar with the code base and AFrame

**Comment by dmarcos** [comment]
On the website the most important issue at the moment is https://github.com/aframevr/aframe/issues/5322 but might be a bit tricky because requires front-end work and also understanding how algolia works. Feel free to tackle it or we can look for something simpler.

**Comment by lainshiHenry** [comment]
After looking at algolia for a while last week, i'm getting stuck.

I'd like something simpler to start off then I would like to tackle this again afterwards.

**Comment by dmarcos** [comment]
Thanks. Yeah Algolia is a tad complex. Several moving parts.

Can't think of anything easy on the website at the moment. Maybe @vincentfretin has some ideas.

**Comment by dmarcos** [comment]
Congrats! You're now an A-Frame contributor 🏅
