### ISSUE TITLE
Comicbook example enter-vr broken

### ISSUE THREAD

**Issue by OfficialMichaelK** [aframevr/aframe#5347]
**Description:**

- A-Frame Version: 
- Platform / Device: oculus quest 2. version 56.0.0
- Reproducible Code Snippet or URL: 

examples/showcase/comicbook i get three loading dots that never resolve. This page was working just fine like 4 days ago.
I suspect something in the layer component but it's beyond my skill level to fix

**Comment by dmarcos** [comment]
This https://aframe.io/aframe/examples/showcase/comicbook/?

The three loading dots you refer to the loading screen? That one should go away before you can click the enter VR button. Nothing has changed on the A-Frame example side.

**Comment by mrxz** [comment]
I can reproduce the issue on my Quest 2, also running version 56 of the OS and version 28.3.0.6.53.500757388 of the Oculus Browser. The three dots aren't the loading dots of A-Frame, but the dots shown by the Quest itself while entering an immersive session. For some reason it stays in that state. No errors are logged to the console either (only upon exiting, but that seems to be a small pre-existing bug in the layer component).

Interestingly enough some (but not all) of the [WebXR Layers samples](https://immersive-web.github.io/webxr-samples/layers-samples/) exhibit the same behaviour, so it's likely this is a regression in the Oculus Browser.

@OfficialMichaelK Could you try and see if you get the same issue with this sample: https://immersive-web.github.io/webxr-samples/layers-samples/quad-select.html

**Comment by OfficialMichaelK** [comment]
Confirmed the issue is reproduced on the layer hit test.

**Comment by dmarcos** [comment]
As reference. Meta team confirmed there's a bug in the browser to be fixed soon.

They also pointed out that we only render the layer once (instead of every frame) and on a GPU reset it might not been redrawn. I also noticed that we actually [check the needsRedraw flag](https://github.com/aframevr/aframe/blob/master/src/components/layer.js#L214) and redraw the layer if necessary. @cabanier Can you confirm that the `needsRedraw` flag is set to true on a GPU reset? If that's the case may be we're not redrawing as expected for a different reason or there's a different browser bug?

They also recommended to [mark the layer as static](https://www.w3.org/TR/webxrlayers-1/#xrcompositionlayer-isstatic) but don't think will work for the comic book example where we want to update the layer when the user turns the page.

**Comment by OfficialMichaelK** [comment]
Note:
I maintained the previous change (<a-entity layer in the comicbook to an <a-plane) and I also have local copies of aframe-master.min.js and other local scripts (no CDNs) on my github project.

Issue:
As of today enter-vr and enter-ar no longer work on oculus browser again. Enter VR works with Firefox Reality. I don't believe Firefox Reality supports ar so not surprised my enter ar is not available.

Thoughts:
Seems like an additional regression/bug with oculus browser.

**Comment by dmarcos** [comment]
Just to make sure I understood. You mean that Meta browser doesn’t enter vr with any of the examples? 

https://aframe.io/aframe/examples/

or just the layers one? Thanks

**Comment by OfficialMichaelK** [comment]
Affirmative. With the examples at https://aframe.io/aframe/examples/ i went down the list and couldn't enter ar or vr on my meta browser. No updates available. 

Using FireFoxReality, all examples (except for the comicbook) enter vr. Link Traversal, however, use to seemlessly transition between .html pages, but now the links pull out of vr.

Cheers. This much is a bit over my head. I wish I could contribute a solution.

**Comment by msub2** [comment]
@OfficialMichaelK What version of Meta Browser are you on? You can check in `Settings > About`. Does this behavior persist even after a restart of the headset?

**Comment by dmarcos** [comment]
Thanks for double checking. So it seems nobody can now reproduce the enter vr / ar issue at the moment? Layers bug still standing

**Comment by cabanier** [comment]
> Thanks for double checking. So it seems nobody can now reproduce the enter vr / ar issue at the moment? Layers bug still standing

28.4 is going out now. I believe that will fix the layers bug

**Comment by dmarcos** [comment]
Can someone verify if this is still an issue? Thanks so much

**Comment by mrxz** [comment]
> Can someone verify if this is still an issue? Thanks so much

@dmarcos Can confirm that the issue is resolved :slightly_smiling_face:

**Comment by dmarcos** [comment]
confirmed as resolved
