### ISSUE TITLE
Destination link is broken in documentation

### ISSUE THREAD

**Issue by lainshiHenry** [aframevr/aframe#5348]
**Description:**
When clicking on the word "Primitives" from this line, "Add 3D entities (i.e., objects) with [primitives]"(https://aframe.io/docs/1.4.0/primitives/)

It results in a 404 page not found

<img width="872" alt="image" src="https://github.com/aframevr/aframe/assets/27880002/bda037fe-fd49-465d-abe0-3084088fc5ae">

- A-Frame Version: 1.4.0
- Platform / Device: Online
- Reproducible Code Snippet or URL: https://aframe.io/docs/1.4.0/guides/building-a-basic-scene.html

**Comment by lainshiHenry** [comment]
@dmarcos 
Let me know if I can work on this issue.

**Comment by vincentfretin** [comment]
So that would be changing the link to `../introduction/html-and-primitives.md` and the url ending with html is generated from that.

**Comment by dmarcos** [comment]
@lainshiHenry Thanks. you're more than welcome to submit a PR as @vincentfretin suggested
