### ISSUE TITLE
aframe 1.4.2 and arjs not working together : Uncaught TypeError: arContext.addEventListener is not a function

### ISSUE THREAD

**Issue by KaranRandhir** [aframevr/aframe#5350]
**Description:**

- version - 1.4.2
- platform - chrome on windows
- Code - https://github.com/KaranRandhir/aframe/blob/main/index.html

![image](https://github.com/aframevr/aframe/assets/42931487/200a699b-d709-417a-ac18-cbed97dda18f)

**Comment by dmarcos** [comment]
sorry, I'm not familiarized with ar.js. Probably work has to be done on the ar.js side

**Comment by dmarcos** [comment]
I don't think there's any work to be done on the A-Frame side. Closing but can reopen if necessary. Best of luck
