### ISSUE TITLE
Can't access component information for hand-tracking-controls

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [aframevr/aframe#5359]
**Description:**

The component **hand-tracking-controls** returns _undefined_ when trying to get any of the components' attributes

(works in A-Frame 1.3.0)

- A-Frame Version: 1.4.0 and 1.4.2
- Platform / Device: Windows
- Reproducible Code Snippet or URL:

`console.log(leftHand.components['hand-tracking-controls']);`

**Comment by dmarcos** [comment]
Can you share code to reproduce? https://glitch.com/~aframe is great

**Comment by mauriciomartinez-itesm** [comment]
Yes sorry!

https://salty-gainful-racer.glitch.me/

Check the console to see the "undefined" thing.

Thank you!

**Comment by dmarcos** [comment]
That's expected behavior. You have to wait until the scene and component have been loaded an initialized. Corrected glitch: https://glitch.com/edit/#!/shard-continuous-pirate?path=index.html%3A20%3A0 

I don't think there's anything to do on the A-Frame side. Can reopen if necessary
