### ISSUE TITLE
Reconsider AR and VR buttons

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#5369]
We're entering the mixed reality era and we might have to revisit again the buttons. VR and AR might not make sense anymore. I was thinking about replacing them with an XR button but not sure yet. It seems giving a choice to the user to enter VR or AR modes is making less and less sense. 

cc @thedart76 

Previous work for reference:

https://github.com/aframevr/aframe/issues/4326

**Comment by msub2** [comment]
We ultimately still have to decide whether to launch an immersive-vr or immersive-ar session. Perhaps adding another field to the `webxr` system like `sessionType`, with a default to immersive-vr?

**Comment by thedart76** [comment]
Happy to help with any new assets we may need for the button/s, @dmarcos.

**Comment by diarmidmackenzie** [comment]
I saw a recent discussion suggesting a pattern where apps should use AR or VR mode depending on whether the user was in passthrough or VR immediately prior.

This info is available to a webXR app (though I'd need to check back to discover exactly how).

This feels like a good default option.

On the other hand, some apps may only make sense in AR or VR, so for those cases it's still desirable to be able to force into that mode, regardless of the mode the user was in previously.

**Comment by dmarcos** [comment]
@thedart76 awesome to here from you. If you have still the original files of the buttons around. it looks we will need one `[XR]` button with same style at current ones. Thanks so much!

@diarmidmackenzie I was planning to leave current AR and VR buttons around but default to an XR one. Devs can opt-in to VR, AR or both as of now. Does it sound sensible?

**Comment by diarmidmackenzie** [comment]
So does pressing the XR button take the user into either AR or VR, depending on whether the user was in passthrough mode prior to pressing the button?

**Comment by dmarcos** [comment]
Not sure a page has a way to know what was the previous state. The XR button whould just enter immersive mode and developer decides if it's going to be `immersive-vr` or `immersive-ar`. The user no longer has a choice by default

**Comment by thedart76** [comment]
> @thedart76 awesome to here from you. If you have still the original files of the buttons around. it looks we will need one `[XR]` button with same style as the current ones. Thanks so much!

@dmarcos, sure, I'm sharing two versions of the new `XR` button, using either style (opaque or transparent).

In the screenshots below, I edited the `SVG` path details directly in the Inspector to preview how they would render.

![aframe-xr-buttons-2023](https://github.com/aframevr/aframe/assets/30973948/6c79961e-07ad-43cb-8687-a1e63e048a8e)

Downloadable `SVG` assets here:

- [aframe-xr-button-opaque](https://drive.google.com/file/d/1tY1vIECKLNeKvxNOBZB7iuKxHBsTyZsk/view?usp=share_link)
- [aframe-xr-button-transparent](https://drive.google.com/file/d/1BXntYqQvEmhhA4gYYGDE5aFtYtY-PpKv/view?usp=share_link)

You can count on me for any tweaking or iteration we may need/want to do.

> Not sure a page has a way to know what was the previous state. The XR button would just enter immersive mode and developer decides if it's going to be immersive-vr or immersive-ar. The user no longer has a choice by default

I vote for this approach as it would ensure good UX for either type of immersive app.

**Comment by diarmidmackenzie** [comment]
> Not sure a page has a way to know what was the previous state

My understanding is that it does have access to this info.  I read a discussion about this somewhere - will try and dig out a reference.

For experiences that support both modes, this would be a nice function to have.

**Comment by dmarcos** [comment]
@thedart76 thanks so much. you rock!

**Comment by dmarcos** [comment]
I made an attempt at this. Let me know what you think

https://github.com/aframevr/aframe/assets/39342/07a93f43-6211-40bf-aefa-ea7c8b2a36ac

**Comment by dmarcos** [comment]
Closed automatically but can reopen if needed

**Comment by thedart76** [comment]
> I made an attempt at this. Let me know what you think
> aframeUI.mp4

@dmarcos, solid UX flow!

I'd like to do a final readability test of both buttons in the headset (Quest 3) to validate or tweak the letter spacing, due to the different backgrounds (solid/transparent), color contrast, and font weight.

LMK when and where I can give it a try (feel free to DM on other platforms too).

PS: I might get back to you with some delay these days as I'm in Vienna for the AWE2023 :)

**Comment by dmarcos** [comment]
@thedart76 you can already try with master builds. See links in commits https://github.com/aframevr/aframe/commits/master

One piece of good criticism. Is that when we show one button we should still display `[VR]` or `[AR]` vs `[XR]` that is a less common known term.

**Comment by thedart76** [comment]
> One piece of good criticism. Is that when we show one button we should still display `[VR]` or `[AR]` vs `[XR]` that is a less common known of a term.

I agree, as the non-tech-savvy audience is more familiar with the terms like `[VR]` or `[AR]`.
In an ideal world, some A/B testing would give you enough empirical data to understand to what extent.

Apart from clarity, another point in their favour is that `[VR]` or `[AR]` are more specific terms, anticipating the type of immersive experience the user is about to enter.

That said and whichever final choice you'll make, I'm always happy to help and explore options, so ping me if needed.
