### ISSUE TITLE
Proposal: support a representation for simple 'terrain' based on a plane

### ISSUE THREAD

**Issue by Splizard** [aframevr/aframe#5372]
I'm looking to render a floor, or surface where I can plop objects on top of, I would like some height variance for this surface, rather than using a flat plane (too uniform/boring). My desired representation for this would look something like this:
```html
<a-scene>
<a-assets>
    <a-asset-item id="heightmap" src="heightmap.png"></a-asset-item>
</a-assets>
<a-terrain resolution="12" height="10" width="4" depth="4" map="heightmap">
    <a-box color="tomato" depth="2" height="4" width="0.5"></a-box>
</a-terrain>
</a-scene>
```
The `height` parameter controls the maximum height for the terrain and each pixel in the heightmap (presumably grayscale) is used to configure the desired height for each position in the plane. `resolution` controls the number of subdivisions of the plane.

My expectation would be that the box in this scene would then be positioned relative to the surface of the terrain at the X and Z coordinate of the box. Such that by changing the X and Z coordinates of the box (ie. by animating them), then the Y coordinate would remain relative to the surface of the `<a-terrain>`.

This enables the children of the `<a-terrain>` to be treated as if they were on a flat plane. 

If I were to write a renderer for this in GL, my approach would be to take the model-space (x=0,z=0) sample heightmap of this terrain in the vertex shader for each child and offset the height of this child accordingly. Any raycasts or culling checks made against the 'terrain' or these children will also need to be offset accordingly. This approach wouldn't require any expensive per-moving-object-per-frame raycasts or physics.

I believe it would be valuable to include this in A-Frame directly, rather than in a third-party extension as I believe the implementation would be dependant on support from the raycaster, material system and renderer. The representation is simple and I expect the performance profile to be appropriate for VR.

Without support from A-Frame, my alternative approach to representing terrain would be to construct a low-poly mesh for the surface and pre-bake all the positions and animations (ie. for each triangle traversed via movement) in the scene on the server. Which would be a bit of a hassle.

**Comment by dmarcos** [comment]
Thanks! This is out of the scope of a-frame core and it's something more appropriate as a 3rd party component (not something that it's commonly used). There's some prior work that might be worth to look at: https://anselm.medium.com/introducing-the-a-terrain-component-for-a-frame-f22a9c9d424d

You could still use the built-in material and raycaster components. Set the terrain as `el.setObject3D('mesh', mesh);`

I'm closing this because I think there's nothing actionable on the A-Frame side. Can reopen if necessary.
