### ISSUE TITLE
Dynamic switch between controller and hand models?

### ISSUE THREAD

**Issue by floe** [aframevr/aframe#5373]
**Description:**

- A-Frame Version: 1.4.2
- Platform / Device: Meta Quest 1
- Reproducible Code Snippet or URL: N/A

I've noticed that on a Meta Quest, both with Wolvic and the built-in browser, I always get the controller models shown for any `laser-controls`, even if I'm using direct hand tracking. Is there a way to switch to hand models, or is that information not actually reported by the hand tracking API?

**Comment by floe** [comment]
(I know the Quest 1 is fairly old, but the same thing also happens on Quest 2.)

**Comment by Splizard** [comment]
On Quest 3, I get white spheres.

**Comment by vincentfretin** [comment]
You need an aframe master build to have the Quest 3 models.

`laser-controls` is only to show controllers. You need to use `hand-tracking-controls` component if you want to show hands.
There is no dynamic switching between controllers and hands with the default aframe components as far as I am aware.

For dynamic switching, the `handy-controls` component from https://github.com/AdaRoseCannon/handy-work used in https://github.com/AdaRoseCannon/aframe-xr-boilerplate does it.

**Comment by dmarcos** [comment]
If you add both laser-controls and hand-tracking-controls to an entity it should switch to the one available. Let me know if that works for you

```
<a-entity laser-controls="hand: left" hand-tracking-controls="hand: left"></a-entity>
```

[Links to master builds](https://github.com/aframevr/aframe/commits/master) are on the commits. Copying below the latest for convenience.

https://cdn.jsdelivr.net/gh/aframevr/aframe@06449ac795892cd7bd7f189d0b94ed2bf9fe43a4/dist/aframe-master.min.js

**Comment by dmarcos** [comment]
We could also have a component that support both simultaneously but would have to find an interaction model that is common denominator. Gaze+click as in this demo I wrote could make sense:

https://glitch.com/~aframe-spatial-ui

Let me know what you think

**Comment by dmarcos** [comment]
Thanks for the patience. This should be now fixed on master. Builds can be found in the [commit messages](https://github.com/aframevr/aframe/commits/master)

Can you verify it works as expected in [this demo](https://glitch.com/edit/#!/complete-canary-burrito?path=index.html%3A4%3A127)? Thanks so much.
