### ISSUE TITLE
Add responsive cursor trigger (fuse or click)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#538]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcarpenter](https://github.com/jcarpenter)**
_Tuesday Oct 13, 2015 at 17:45 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/251_

----

Enables devs to deploy WebVR experiences that work across desktop mono, desktop VR, and mobile (Cardboard) contexts. 

The look based cursor should respond to clicks when a mouse is available, or ["fuse" timed events](https://www.google.com/design/spec-vr/interactive-patterns/controls.html) when viewed on mobile devices that lack an input.

Ideally the dev has some control over which scheme to apply, but that can potentially wait for a future release.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Wednesday Oct 14, 2015 at 05:21 GMT_

----

#256 proposes an implementation

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Wednesday Oct 14, 2015 at 05:24 GMT_

----

Depends on #129

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Wednesday Oct 21, 2015 at 04:41 GMT_

----

btw, @dmarcos added a working fuse-based cursor in #296:

https://mozvr.github.io/aframe-core/examples/panoexplorer/

if you don't want a fuse-based cursor, just do  `<vr-object … cursor>` instead of `<vr-object … cursor="timeout: 1500; fuse: true">`. (see issue #297 to add an example for that.)

**Comment by ngokevin** [comment]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caseyyee](https://github.com/caseyyee)**
_Tuesday Nov 10, 2015 at 19:39 GMT_

----

Cursor is in, but needs to be responsive between mobile/desktop.

**Comment by cvan** [comment]
@dmarcos: @ngokevin: @caseyyee: @jcarpenter: what did you folks want to do here? we decided not to go with my [solution here](https://github.com/aframevr/aframe-core/pull/518). what should we be telling users who want "responsive" cursor controls?

**Comment by dmarcos** [comment]
what does responsive mean? the cursor as it is now defaults to fuse on movile and on mouse click on desktop

**Comment by ngokevin** [comment]
Yeah, that might have been added later on. So this issue seems resolved.

Though we could improve code quality by doing:

```js
{
  fuse: {
    default: utils.isMobile()
  }
}
```

**Comment by dmarcos** [comment]
Yeah @ngokevin that's a good improvment

**Comment by ngokevin** [comment]
We should double-check it's working, but it looks like the code is there.

**Comment by cvan** [comment]
> what does responsive mean? the cursor as it is now defaults to fuse on movile and on mouse click on desktop

Sorry, what I mean is by declaratively having (without JS) cursor be fuse on mobile and click on desktop.

There are a ton of scenes that are designed for desktop consumption and work with only WASD (check out [http://drawvr.com/](DrawVR's projects), for examples).

Conversely, here's a [scene](http://chrismwaite.github.io/cardboard-dungeon/) where desktop support was abandoned because it was clearer how to just use Cardboard + a fuse-based cursor (and there is some JS, so he could've handled it technically):

Per [this tweet by the creator](https://twitter.com/chrismwaite/status/688809628147257345):

> Having fun with @aframevr - http://chrismwaite.github.io/cardboard-dungeon/ … (gaze at squares on ground to move, look down for compass) 

If we all agree that we don't want to support declarative, if there's some copy+pasteable JS snippets that folks can use, that's fine.

**Comment by cvan** [comment]
FWIW, my solution was to introduce a [`match-device` component](https://github.com/aframevr/aframe-core/pull/518/files#diff-68b5544f3cdb6b74d38ac2e61a2e2f74R46) (or you could do `match` or `match-size` as I describe in that comment below). Not sure if we want to revisit any of that, but it's worth mentioning.

**Comment by ngokevin** [comment]
It seems to be declarative and defaulting to the scheme proposed. Is that not right?

`match-device` would be good to publish as a component.

**Comment by cvan** [comment]
> It seems to be declarative and defaulting to the scheme proposed. Is that not right?

The confusion/limitation I think is that folks don't know they can do `cursor="timeout:500"` without `cursor="fuse: true; timeout:500"`.

**Comment by ngokevin** [comment]
Okay, I will bolster the docs to introduce more specific examples for the next release. Rather than just documenting components, I will add more examples with inline HTML.
