### ISSUE TITLE
include async / await in linter

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#5381]
linter is failing because of async / await use due to the WebXR Anchor module API. I think we need to include it in the list of exceptions. @diarmidmackenzie

**Comment by diarmidmackenzie** [comment]
You can include exceptions as required in [`.elintrc.json`](https://github.com/aframevr/aframe/blob/master/.eslintrc.json)

Here's an [existing example](https://github.com/aframevr/aframe/blob/513c5d0b303dc4fd7f9d161f5dc6bd381228f52f/.eslintrc.json#L52):
```
    {
      /* This module use ES6 classes, and so is parsed as ES6 to avoid errors. */
      "files": ["./src/extras/primitives/primitives.js"],
      "parserOptions": {
        "ecmaVersion": 6
      }
    },
```

**Comment by dmarcos** [comment]
Thanks! I think we should also make the linter part of the git pre-commit. I was able to commit without errors.

**Comment by diarmidmackenzie** [comment]
I thought it was already.  Maybe I broke that?  Will take a look.

**Comment by diarmidmackenzie** [comment]
Just tested this at master and it seems to be working fine.  The setup for this is pretty simple, so intermittent or platform-specific bugs seem unlikely:
- `precommit` is configured to run `npm run lint`
- `npm run lint` just runs `standardx -v | snazzy`, and I believe is working for you locally?

Is it possible that when you [merged the Anchors code](https://github.com/aframevr/aframe/issues/5368#issuecomment-1803301609), you didn't have all the recent linting changes on your branch, so the linting (which runs locally) didn't run the latest checks, but when everything was merged into main, then the linting checks failed?
