### ISSUE TITLE
[BUG] remove obb-collider component error -> e.hideCollider is not a function

### ISSUE THREAD

**Issue by dtboy1995** [aframevr/aframe#5385]
**Description:**

- A-Frame Version: 1.5.0
- Platform / Device: Chrome PC 119.0.6045.125

```html
<a-box id="box" obb-collider></a-box>
```

![image](https://github.com/aframevr/aframe/assets/19227547/65f87ec5-7cae-4202-af2a-72f156f1173b)
![image](https://github.com/aframevr/aframe/assets/19227547/7f4ecb20-ef7b-416a-808d-58535a1f97eb)

**Comment by dmarcos** [comment]
Thanks. This should be fixed now. Can verify with a master build?

https://cdn.jsdelivr.net/gh/aframevr/aframe@192293bfd36d49d3cc82e611fd9b415b53b60435/dist/aframe-master.min.js

**Comment by dtboy1995** [comment]
@dmarcos Thanks 

> https://cdn.jsdelivr.net/gh/aframevr/aframe@192293bfd36d49d3cc82e611fd9b415b53b60435/dist/aframe-master.min.js
works well

**Comment by dmarcos** [comment]
thanks
