### ISSUE TITLE
Models (glTF, OBJ) doesn't work in local

### ISSUE THREAD

**Issue by techno94** [aframevr/aframe#5393]
hello i test in chrome and Edge the web page : 
aframe-master/examples/test/model/index.html
it doesn't display correctly
![A_frame](https://github.com/aframevr/aframe/assets/2470466/2ef98e8d-e78d-4abb-aced-a0a21e5bf3af)

but the same web page here : 
https://aframe.io/aframe/examples/test/model/
display correctly
![online](https://github.com/aframevr/aframe/assets/2470466/b25e38fc-9e88-4949-ae1a-c95c7fc034bb)

have you any idea ?
Thanks a lot

**Comment by dmarcos** [comment]
Are you running a local server? More info https://aframe.io/docs/1.5.0/introduction/faq.html#why-does-my-asset-e-g-image-video-model-not-load

**Comment by ahmed-frq** [comment]
It seems that you opened the HTML file directly in the browser. However, the browser cannot access your local files. You should either open it using a Live Server or any other code editor's live previewer. If not, you can import the 3D model as a URL into your code, like this:

`<gltf-model src="https://yourmodel.glb"></gltf-model>`

**Comment by dmarcos** [comment]
I'm closing this but can reopen if necessary

**Comment by techno94** [comment]
Hello, i don't use a local server. browser access to lacal file like .js, or css and picture. 
why can't he access to the .mtl and .obj

**Comment by dmarcos** [comment]
Those are browser policies for privacy / security reasons that all web pages are subject to. Not an A-Frame decision or limitation.

 css / js / images are fetched and displayed by the browser and don't leave the sandbox. Textures (images displayed in webgl), models and other files are fetched via [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) requests and processed by the page (THREE / A-Frame in this case). Browsers don't allow arbitrary access to your local file system or a page could process and send that info outside of the machine without your consent or awareness.
