### ISSUE TITLE
Msdf font have a bad color space since update to v1.5.0

### ISSUE THREAD

**Issue by Turtleted21** [aframevr/aframe#5408]
Hello,
Since the update to v1.5.0 msdf font have a bad color space.
Before update shader msdf were like a shader flat.

On this screenshot we can see :
a msdf font :
       ` <a-mixin id="loading_text_audio_player_title" text="shader: msdf; font: custom-msdf/custom-msdf.json; negate:false; width:3.75; wrapCount: 20; letterSpacing: 1; color: #339966; align:center"> </a-mixin>`

a plane progress bar :
               `<a-mixin id="audio_player_progress_bar_green" material="color: #339966; shader: flat;" geometry="primitive: plane; height:0.075; width:2.6" pivot="-1.25 0 0" animation="easing: linear"></a-mixin>`

a image :
                `<a-entity id="audioguide_info_image" position="0 1.55 0.01" geometry="primitive:plane; width: 4; height: 2" material="shader:flat"></a-entity>`

All three had the same color before.

- A-Frame Version v 1.5.0:
- Platform / Device: all

![Untitled-12](https://github.com/aframevr/aframe/assets/46889785/f2fbf9f4-b4d6-4fc9-a6a2-65fd5c70a708)

Thanks

**Comment by dmarcos** [comment]
`<a-scene renderer="colorManagement: false">` ?

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/5409
