### ISSUE TITLE
Aframe app asks for "Insert phone into Cardboard Holder" when VR button is pressed

### ISSUE THREAD

**Issue by ruibinghao** [aframevr/aframe#5427]
I am not expecting to use a Cardboard holder for the AFrame VR app to enter VR mode.

- A-Frame Version: 1.4.x
- Platform / Device: IOS 17.2.1
- Reproducible Code Snippet or URL: https://fll60174.github.io/VR-apps/quest-book.html

**Comment by dmarcos** [comment]
This is old behavior. Your using A-Frame 1.3.0. Update to A-Frame 1.5.0

Closing this but can reopen if necessary.
