### ISSUE TITLE
Full 1.5.0 PDF Documentation

### ISSUE THREAD

**Issue by PebbleCat-Studios** [aframevr/aframe#5443]
I have an idea. I was looking to download the whole A-Frame 1.5.0's documentation in a pdf, but I couldn't find it. Is there such a file?

**Comment by dmarcos** [comment]
All the docs are in the repo in Markdown format: https://github.com/aframevr/aframe/tree/master/docs

You can play with it and try to generate a PDF.

**Comment by dmarcos** [comment]
We are not planning to produce a PDF version of the documentation. Anyone can do it though from the markdown. Closing this. Can reopen if necessary
