### ISSUE TITLE
Networked-A-Frame avatar issue

### ISSUE THREAD

**Issue by funing36** [aframevr/aframe#5456]
**Description:**

- A-Frame Version: 1.5.0
- Platform / Device: PC
- Reproducible Code Snippet or URL: https://funing36.github.io/WebVR-Chat/WebVR%20Chat/

This issue will be in the "Explore Worlds" with World Gallery.

Hello, I need help with Networked-A-Frame. I was working with this distro and I got everything working fine up until I needed to implement my avatars along with all the controls within it. I have a POV system (When you press "P", it'll toggle between 1st, 3rd, and 2nd person POV's) alang with character animation, an animation controller. I also have 2 cameras per avatar, one for the viewing, attached to a purple box, and a camera that rotates and moves, for positioning. I also stick the avatars to a navmesh and everything works "fine" until I needed to implement my avatar. Can anyone help me?

Repo with the issue lies here, it'll be under /"WebVR Chat"/worlds/00002: https://github.com/funing36/WebVR-Chat

**Comment by vincentfretin** [comment]
Please don't create aframe issue for support on a project. You already created https://github.com/networked-aframe/networked-aframe/discussions/452 and added the link to supermedium Discord. Please be patient that someone replies.

**Comment by funing36** [comment]
Ok, sorry, I'll shut down this post.
