### ISSUE TITLE
Hiding VR mode UI not working in 1.5.0

### ISSUE THREAD

**Issue by Elettrotecnica** [aframevr/aframe#5471]
Dear all,

I have noticed a possible regression in version 1.5.0:

setting **vr-mode-ui="enabled: false;"** on a-scene used to hide the pre-generated VR/AR button in a scene. Now, this seems to not have any effect.

In this simple glitch remix of the hello world one can see what I mean: https://foul-liberating-cobweb.glitch.me/

Reverting  to 1.4.2 seems to solve the particular issue.

I believe the problem may be related with  #5319

All the best

Antonio

**Comment by mrxz** [comment]
The `vr-mode-ui` component has been renamed to `xr-mode-ui` in 1.5.0, so using `xr-mode-ui="enabled: false"` should work ([docs](https://aframe.io/docs/1.5.0/components/xr-mode-ui.html)).

**Comment by Elettrotecnica** [comment]
I see, thanks a lot and sorry for the noise :-)
