### ISSUE TITLE
Support for transient input on Vision Pro

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#5507]
https://www.w3.org/TR/webxr/#transient-input

One can get gaze info on pinch gesture. This allows for basic gaze + pinch interactions.

**Comment by JL-Vidinoti** [comment]
The "click" event simply works with A-Frame 1.5.0 by using `cursor="rayOrigin: xrselect;"`. It is triggered with gaze + pinch on Vision Pro.

**Comment by dmarcos** [comment]
I don't think there's anything else to do on the A-Frame side but leave it open for a bit since I'm not 100% certain

**Comment by dmarcos** [comment]
`cursor="rayOrigin: xrselect;"` is good for now. We can expand / change and handled any improvements / bugs in a separate issue.
