### ISSUE TITLE
a-scene Chrome non-passive violation warnings for touchmove and touchstart event handlers

### ISSUE THREAD

**Issue by mitchallen** [aframevr/aframe#5510]
**Description:**

For a simple scene, Chrome is logging these warnings to the console:

```sh
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

```sh
look-controls.js:163 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

The error references: https://www.chromestatus.com/feature/5745543795965952

Links referred to in console for 1.5.0:

* https://github.com/aframevr/aframe/blob/v1.5.0/src/core/scene/a-scene.js#L882
* https://github.com/aframevr/aframe/blob/v1.5.0/src/components/look-controls.js#L163 

- A-Frame Version: 1.5.0
- Platform / Device: Google Chrome Version 123.0.6312.107 (Official Build) (arm64)
- Reproducible Code Snippet or URL:  

I think all you need to reproduce it is a `<a-scene />` - but here's an example using look-controls too:

```html
    <a-scene>
        <a-assets>
            <!-- TODO -->
        </a-assets>
        <a-entity id="rig" position="0 0 0">
            <a-camera id="camera" look-controls="enabled: true"></a-camera>
        </a-entity>
        <a-plane position="0 0 0" rotation="-90 0 0" width="4" height="4" color="#222222"></a-plane>
        <a-sky color="#333333"></a-sky>
    </a-scene>
```

**Comment by mrxz** [comment]
Thanks for reporting, interestingly enough I wasn't able to reproduce the warnings locally only in deployed versions. In any case, I've created a PR that sets the `passive` flag appropriately for every touch/scroll event listener (#5511). Note that several of them _aren't_ passive, but the warning should still be gone with this change.

**Comment by dmarcos** [comment]
Interesting. I can't see the warnings on Chrome 123 for Mac (neither locally served or deployed versions). It looks warnings should have been seen since Chrome 51. What should I do to reproduce?

**Comment by mrxz** [comment]
> What should I do to reproduce?

@dmarcos What worked for me was on desktop Chrome 122 visiting https://aframe.glitch.me/, opening the dev console and _then refreshing_. They didn't show up for me when opening the dev tools after page load, nor did they show up on Quest or Android smartphone with remote debugging. And never showed up locally for some reason. Hope this helps, no idea why this warning is so elusive.

**Comment by dmarcos** [comment]
Can't reproduce either on the glitch. Would be interesting to understand a bit more.

**Comment by mrxz** [comment]
Do you have the "Verbose" log level enabled? Just noticed that despite their warning colour/semantic, they are logged with the verbose level :neutral_face: 
![non-passive](https://github.com/aframevr/aframe/assets/8823461/00a318b9-b88b-4aa4-af4a-6bbce2ddeaf5)
