### ISSUE TITLE
light estimtion

### ISSUE THREAD

**Issue by Fatima-mnsuam** [aframevr/aframe#5524]
Hi, 
Is there any method to estimate light of the real environment? Actually, I want to add light depending upon lighting condition of real user environment.

**Comment by mrxz** [comment]
The built-in [reflection](https://aframe.io/docs/1.5.0/components/reflection.html) component uses light estimation data to adjust the lighting in the scene for AR. This requires the [WebXR Lighting Estimation API](https://immersive-web.github.io/lighting-estimation/), so it will only work on devices that support it (AFAIK, only Android smartphones).

You can always use the API directly if you need. If you do need light estimation on a different device, then I'm afraid there's no easy solution.

**Comment by Fatima-mnsuam** [comment]
Hi, Thank you for your comment. But I don't understand how reflection is working. My goal is to estimate the lighting conditions of the real environment and then dynamically project fake light if the light is low or stop projecting fake light if there's enough light, to enhance the realism of the AR experience. And I only want to do it for Android and IOS smartphones.

**Comment by vincentfretin** [comment]
@Fatima-mnsuam Please stop spamming all the possible repositories
https://github.com/hiukim/mind-ar-js/issues/531 (this lib doesn't use WebXR)
https://github.com/immersive-web/lighting-estimation/issues/61 (this is is not a support repo, that for the specs)
@mrxz gave you an excellent answer here. Light estimation is only available in an immersive-ar WebXR session on Chrome Android. You can read the code in https://github.com/aframevr/aframe/blob/master/src/components/scene/reflection.js to know how A-Frame is using the Light Estimation API.

**Comment by dmarcos** [comment]
I think there's nothing actionable on the A-Frame side. I can reopen if necessary
