### ISSUE TITLE
Geometry component warn

### ISSUE THREAD

**Issue by Roxcsas** [aframevr/aframe#5525]
After updating to a-frame 1.6.0 i noticed all my a-entity that have geometry="..." and material="..." are causing this warning in the console even if they are working

> core:component:warn Unknown property `width` for component `geometry`
core:component:warn Unknown property `height` for component `geometry`
core:component:warn Unknown property `radius` for component `geometry`
core:component:warn Unknown property `color` for component `material`

**Comment by dmarcos** [comment]
Thanks. Can you share an example with https://glitch.com/~aframe ?

**Comment by Roxcsas** [comment]
> Thanks. Can you share an example with https://glitch.com/~aframe ?

here is an example
https://glitch.com/edit/#!/ambiguous-basalt-point

"side" is the only property of the ones i used which don't cause a warn

**Comment by mrxz** [comment]
Surprised how this wasn't noticed before. The problem occurs with dynamic schemas, clobbering and style-string values, but that is the case when using the `geometry` or `material` components on `a-entity`. Using a mixin, primitive (e.g. `<a-box>`) or creating through code with objects doesn't trigger this.

In any case, I've created a fix for it: #5526

**Comment by dmarcos** [comment]
Fixed in master. It will ship in next version but can use master builds in the meantime (link below):

https://cdn.jsdelivr.net/gh/aframevr/aframe@45652572bfd5b8939e30d5d504e62bae717795a5/dist/aframe-master.min.js

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/pull/5526
