### ISSUE TITLE
webvr-polyfill default DPDB json domain is expired

### ISSUE THREAD

**Issue by pawelmaczka** [aframevr/aframe#5538]
Aframe uses default webvr-polyfill DPDB json (https://dpdb.webvr.rocks/dpdb.json), but its domain has expired so it's not accessible.

**Comment by dmarcos** [comment]
It seems you are in an old version. update to A-Frame 1.6.0. We no longer use the polyfill. Closing and can reopen if necessary

**Comment by vincentfretin** [comment]
We didn't remove WebVR support yet, we still use webvr-polyfill on master, #5451 is the PR to remove it.

**Comment by jarodium** [comment]
Hi all
https://dpdb.webvr.rocks/dpdb.json still appears in 1.6.0

**Comment by dmarcos** [comment]
@jarodium Polyfill was removed in https://github.com/aframevr/aframe/pull/5451 and will ship in 1.7.0

**Comment by jarodium** [comment]
Hi @dmarcos 

It is clear now. 
Thank you for your time :)
