### ISSUE TITLE
Creating a 360 video from a scene

### ISSUE THREAD

**Issue by atrauzzi** [aframevr/aframe#5553]
I would love to have the ability to dump what's going on in an aframe scene from a specific point as a 360 degree video.  Even better would be if I had a 360 video as a skybox, that its original quality would be preserved, with the rendering of the scene simply layered over top of it at full quality.

**Comment by mrxz** [comment]
The `screenshot` component allows you to render an equirectangular image of your scene. While not the most performant, you could use it to make them in succession and then later combine them into a video. Note that these are monoscopic, so best to use it for distant/far away scenery.

As for retaining "original quality" when using it as a skybox, that is a bit trickier. In any case using the WebXR Layers API to create an equirectangular layer should yield the best results. A-Frame does have some limited WebXR Layers support (see `layers` component), but no equirectangular support, so you'd have to implement that yourself.

**Comment by dmarcos** [comment]
and 360 gameplay video will most likely be very disorienting (unwatchable for most) do to camera movement.

**Comment by dmarcos** [comment]
I don't think there's anything actionable on the A-Frame side. I can reopen if necessary. Thanks
