### ISSUE TITLE
3D model issue while changing the aframe version

### ISSUE THREAD

**Issue by PratikPatel-113** [aframevr/aframe#5582]
**Description:**
I've shifted my 3D experience from version 1.2.0 to a newer version, either 1.4.0 or 1.5.0. However, my 3D model now appears very dark using the previous light settings and color change configuration. Could someone suggest what might be causing this significant change in the color display?
- A-Frame Version: 1.4.0
- Platform / Device: Web
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment]
Make sure you're using latest A-Frame 1.6.0. Also share code with https://glitch.com/~aframe or people will have a hard time to help you

**Comment by PratikPatel-113** [comment]
I was able to resolve the issue by adjusting the light settings and referring to this GitHub discussion for a better understanding: https://github.com/aframevr/aframe/issues/5383.

Thanks!

**Comment by PratikPatel-113** [comment]
Closed.

**Comment by dmarcos** [comment]
thanks. glad you found a solution
