### ISSUE TITLE
Tests failing locally

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#5590]
I have test failing locally and can't figure out why. Both on Chrome and Firefox. They seem to work on the repo test automation.

I narrowed down one of the issues. This test:

https://github.com/aframevr/aframe/blob/master/tests/components/gltf-model.test.js#L21

The gltf model loads but when setting the mesh object in this this line:

https://github.com/aframevr/aframe/blob/master/src/components/gltf-model.js#L48 

The `obj instanceof THREE.Object3D` test in the line below fails throwing an error and making the test fail: 

https://github.com/aframevr/aframe/blob/master/src/core/a-entity.js#L128

I can reproduce in console during the test execution but don't know why it's failing. I'm pretty puzzled because only happens in the context of the tests and cannot reproduce outside. Could be some of the polyfills or monkey patching we're doing

@vincentfretin Any ideas? Thanks

**Comment by mrxz** [comment]
FWIW, tests run fine for me locally as well. Both on Chrome (129.0.6668.89 stable) and Firefox (131.0.2). It seems likely that somehow two versions of three get loaded, causing the issue, though I'm not sure how that would happen in the tests.

To rule out that other tests play a role, could you try and run only the failing unit test to see if the issue persists?
Also worth trying removing your `node_modules` and `package-lock.json` to pull in all dependencies anew.

**Comment by dmarcos** [comment]
> What's the error? You didn't say

The error is that the test in question doesn't pass because `model-loaded` event is never emitted after the `if (!(obj instanceof THREE.Object3D)) {` test fails and corresponding error is thrown.

I'm already running only that test with `test.only`. Deleting `node_modules` and `package-lock.json` didn't make any difference.

This is pretty strange. I'm just on a vanilla Mac OS / chrome / firefox. Nothing exotic I can think of

**Comment by dmarcos** [comment]
`obj.isObject3D` might work but feels like a hack and need to understand what's going on

**Comment by dmarcos** [comment]
self.model is a well formed. what you would expect. Theory it’s instantiated with a different version of THREE is plausible but don’t understand how

**Comment by mrxz** [comment]
The code itself and the unit test both look sound. Something seems amiss with your local setup, possibly causing Three.js to be bundled malformed and/or multiple times when executing tests, though I have no clue why or how.

A stab in the dark, but what version of node are you using? 
For reference: the CI seems to use v20.x and I'm using v22.3.0.

**Comment by vincentfretin** [comment]
on my side:
```
$ find node_modules/ -name three
node_modules/three
$ npm -v
10.8.2
$ node -v
v22.7.0
```
so I really only have one version of three package here. What about you?

**Comment by dmarcos** [comment]
Thanks. I updated to your node / npm versions and problem persists. puzzling

**Comment by dmarcos** [comment]
Investigating. When debugging into the test.

three__WEBPACK_IMPORTED_MODULE_37__.Group used to instantiate the gltf object in the gltfParser is not the same as AFRAME.THREE.Group. the THREE.Group is instantiated with a different constructor than the AFRAME.THREE.Group that we later check against with `instanceof`

**Comment by dmarcos** [comment]
If I force this line https://github.com/supermedium/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L4342

to be `const scene = new AFRAME.THREE.Group();` instead of `const scene = new Group();` fixes the test. This confirms that somehow the Group that webpack is injecting is not the same that AFRAME exports but it looks only happens in the context of the tests

**Comment by mrxz** [comment]
If you can find another `three__WEBPACK_IMPORTED_MODULE_xx__` with a different number then it's certain Webpack includes two distinct copies in the bundle. For me there's only ever one, but interestingly it always seems to end up as MODULE_0.

Basically it would mean that the imports from `three` in `src/lib/three.mjs` and from `three/examples/jsm/loaders/GLTFLoader.js` are considered two different modules by Webpack on your machine during tests. The `karma.conf.js` _does_ alter the webpack configuration a bit, but I don't see how this could cause your problem :thinking:

**Comment by mrxz** [comment]
You should be able to see it with `npm start` as well, though obviously at that point you have access to source maps. But if you inspect the `/dist/aframe-master.js` file they should be there as well.

That screenshot reveals a lot, as it really shouldn't "expand" these imports to their individual file. For some reason it pulls in the three.js source files and not the build. For reference this is what is present in [aframe-master.js](https://github.com/aframevr/aframe/blob/master/dist/aframe-master.js):
```js
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   GLTFLoader: () => (/* binding */ GLTFLoader)
/* harmony export */ });
/* harmony import */ var three__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! three */ "./node_modules/three/build/three.module.js");
/* harmony import */ var _utils_BufferGeometryUtils_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../utils/BufferGeometryUtils.js */ "./node_modules/three/examples/jsm/utils/BufferGeometryUtils.js");
```
Only the three.js bundle and the separate `BufferGeometryUtils.js`.

**Comment by dmarcos** [comment]
he he. this is why I don't like webpack or bundlers in general. I don't understand what's going on :)

**Comment by dmarcos** [comment]
What do you see when you debug your tests? Put a breakpoint in this line

https://github.com/supermedium/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L4342

When running this test

https://github.com/aframevr/aframe/blob/master/tests/components/gltf-model.test.js#L21

**Comment by dmarcos** [comment]
Do you also see the same expansion to individual THREE files?

**Comment by mrxz** [comment]
When executing the test I don't see it being expanded, just two entries: one for the bundle and one for the `BufferGeometryUtils`.

I really don't see how it would expand to the individual source files in the first place. Like the exports field in `three/package.json` should all point to bundled files. Even if webpack would, say, pick the CJS bundle it still shouldn't expand to the source files.

**Comment by dmarcos** [comment]
do you have any global webpack configuration or something like that? I'm not aware of anything I might have that would change webpack behavior

**Comment by dmarcos** [comment]
To confirm I'm just on A-Frame master https://github.com/aframevr/aframe/commit/0161e1db2374b9aaa0c94627eef809a6ed7b8862 and have no local changes

**Comment by vincentfretin** [comment]
In some test files we use
`var THREE = require('lib/three');`
in some other files we use
`var THREE = require('index').THREE`
that points to our defined THREE object that's on AFRAME.THREE.
Some test files doesn't define that and is using global THREE that should normally be https://github.com/aframevr/aframe/blob/0161e1db2374b9aaa0c94627eef809a6ed7b8862/src/index.js#L39
In the case of `var THREE = require('lib/three');` the global THREE may be
https://github.com/aframevr/aframe/blob/0161e1db2374b9aaa0c94627eef809a6ed7b8862/src/lib/three.js#L3 without the additional modules.
Maybe we should first harmonize the test files to use 
`var THREE = require('index').THREE`
your issue may just disappear. :D maybe some issue related to the order of files being processed with glob or your specific file system...

**Comment by mrxz** [comment]
> do you have any global webpack configuration or something like that?

Not that I'm aware of. You don't happen to have any `npm link` active due to `super-three` or something?
Can you make sure that none of the parent folders leading up to your local aframe checkout don't contain any `node_modules/` or `package.json` in them. Quite a lot of tooling likes to climb up the tree to find the supposed "project root" that way.

> Maybe we should first harmonize the test files to use

While I agree with consistency, I certainly hope that Webpack can properly build the dependency graph regardless of the file order. If not we'd be at risk of running into this issue for prod builds as well. So even if it would magically make the issue go away, I'd want to get to the root cause either way.

**Comment by dmarcos** [comment]
don't have any npm link active and no node_modules in parent directories. I'm just in `/Users/dmarcos/Development/aframe`

**Comment by dmarcos** [comment]
I replaced all the `var THREE = require('lib/three');` with `var THREE = require('index').THREE` in the tests and problem persists

**Comment by vincentfretin** [comment]
Can you try adding `var THREE = require('index').THREE` to the files where the require is missing as well? The files with `/* global ... THREE */`

**Comment by dmarcos** [comment]
> Can you try adding `var THREE = require('index').THREE` to the files where the require is missing as well? The files with `/* global ... THREE */`

Yes. I'm only running the one test https://github.com/aframevr/aframe/blob/master/tests/components/gltf-model.test.js#L21
Does it matter?

**Comment by dmarcos** [comment]
I replaced all the `/* global ... THREE */` with `var THREE = require('index').THREE`, issue persists

**Comment by vincentfretin** [comment]
All the built files after running the tests are in the build directory.
You should indeed have in `build/commons.js`
```js
52621:/* harmony import */ var three__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! three */ "./node_modules/three/build/three.module.js")
```
similar to `aframe-master.js` as @mrxz said. And that's the only file that should include "node_modules/three" string in it.
That's so weird that you get each individual three/src/ files, we don't import three/src anywhere.
webpack should resolve from
https://github.com/supermedium/three.js/blob/d1b7e67c7be1dabc0dbee62bd982f1f501fb611a/package.json#L10
not https://github.com/supermedium/three.js/blob/d1b7e67c7be1dabc0dbee62bd982f1f501fb611a/package.json#L17
Reading again the documentation https://webpack.js.org/configuration/resolve/ I don't know what's going on on your machine.

**Comment by dmarcos** [comment]
I see this warnings but prob unrelated?

```
karma-webpack does not currently support custom entries, if this is something you need,
consider opening an issue.
ignoring attempt to set the entry option...

karma-webpack does not currently support customized filenames via
webpack output.filename, if this is something you need consider opening an issue.
defaulting aframe-master.js to [name].js.
```

**Comment by dmarcos** [comment]
Note that the issue is not webpack alone. I can run `npm start` and build A-Frame no issue locally. It's just wepback in the contest of the tests. maybe `karma-webpack` is the issue?

**Comment by dmarcos** [comment]
When I run `npm start` and inspect the A-Frame build I see what you expect

```
/***/ "./node_modules/three/examples/jsm/loaders/GLTFLoader.js":
/*!***************************************************************!*\
  !*** ./node_modules/three/examples/jsm/loaders/GLTFLoader.js ***!
  \***************************************************************/
/***/ ((__unused_webpack___webpack_module__, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   GLTFLoader: () => (/* binding */ GLTFLoader)
/* harmony export */ });
/* harmony import */ var three__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! three */ "./node_modules/three/build/three.module.js");
/* harmony import */ var _utils_BufferGeometryUtils_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../utils/BufferGeometryUtils.js */ "./node_modules/three/examples/jsm/utils/BufferGeometryUtils.js")
```

**Comment by vincentfretin** [comment]
The warnings can be ignored. Those come from node_modules/karma-webpack/lib/karma-webpack/controller.js and the code modify the webpack conf for the output filename, but don't really do any other changes as far as I can see.

**Comment by dmarcos** [comment]
This is the commit that broke the tests for me 

https://github.com/aframevr/aframe/commit/7ac47c0629aa257d72514ab#diff-728e6c3454f7b441786065d02f09e5cefeadfc2c007bf03b44d03f43dfc1a8c5

**Comment by dmarcos** [comment]
@vincentfretin any ideas?

**Comment by vincentfretin** [comment]
With my current knowledge of how module resolution work between cjs, esm, node and webpack, I have no idea why only you ends up having those src/three imports in the test built files.
Try renaming again three.mjs to three.module.js and modify the require in three.js to see if that changes anything?

**Comment by mrxz** [comment]
Even if webpack would somehow resolve it differently, I still don't really understand how it ends up at the individual source files. The exports in the `package.json` of `three` all point to bundle files.

You could add `stats: 'verbose'` to the `webpack.config.js` configuration ([docs](https://webpack.js.org/configuration/stats/)) and run the test again. That will generate a lot of output, but should give insights in how Webpack ended up including three, from where, why and how.

**Comment by dmarcos** [comment]
Renamed `three.mjs` to `three.module.js`and problem persists

**Comment by dmarcos** [comment]
I attached the log with `stats: verbose`  No idea how to interpret

[log.log](https://github.com/user-attachments/files/17511906/log.log)

**Comment by dmarcos** [comment]
see a lot of referneces to `harmony import specifier`

**Comment by mrxz** [comment]
Could you try changing the following in [`karma.conf.js:36`](https://github.com/aframevr/aframe/blob/master/tests/karma.conf.js#L36):
```patch
-webpackConfiguration.resolve.modules = ['src', 'node_modules'];
+webpackConfiguration.resolve.modules = [path.resolve(__dirname, '../src'), 'node_modules'];
```

**Comment by dmarcos** [comment]
> Could you try changing the following in [`karma.conf.js:36`](https://github.com/aframevr/aframe/blob/master/tests/karma.conf.js#L36):
> 
> ```diff
> -webpackConfiguration.resolve.modules = ['src', 'node_modules'];
> +webpackConfiguration.resolve.modules = [path.resolve(__dirname, '../src'), 'node_modules'];
> ```

That did the trick! Thanks so much for the patience and sticking for me. Super super appreciated!

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe/commit/b92c12fbf4aa2658ed06bd210fa5e0c1cee365aa

**Comment by mrxz** [comment]
Nice, so context for what was happening:

- The `karma.conf.js` added `src` as one of the folder names to search in.
- When `three.mjs` imports `three` it resolves to `node_modules/three/build/three.module.js` as it should
- When `three.mjs` imports the `GLTFLoader` it correctly resolves it to `node_modules/three/examples/jsm/loaders/GLTFLoader.js`.
- When `GLTFLoader` imports from `three` it resolved incorrectly to `node_modules/three/src/Three.js`
  - It starts crawling up the path from `node_modules/three/examples/jsm/loaders/GLTFLoader.js` till it finds either a `src/` or `node_modules/` folder.
  - When it finds the `src/` folder in `node_modules/three/` it checks if it can find "three", which it finds in the form of `node_modules/three/src/Three.js`

What strikes me as odd is that it accepts `Three.js` for the identifier `three` despite the capitalization difference. My guess is that under Linux it rejects it, but under Mac OS somehow accepts it. Either way, we don't want to search for _any_ `src` folder, but a specific one. Hence replacing it with an absolute path fixes it. (Relevant webpack docs: [resolve.modules](https://webpack.js.org/configuration/resolve/#resolvemodules))

**Comment by dmarcos** [comment]
thanks for the explanation

**Comment by vincentfretin** [comment]
The fix is right in the doc :D bravo for understanding the issue @mrxz
