### ISSUE TITLE
Texture is Immutable Error in A-Frame 1.6.0 when Changing Sky Image

### ISSUE THREAD

**Issue by alszeb** [aframevr/aframe#5593]
**Description:**

- A-Frame Version: 1.6.0
- Platform / Device: Edge on desktop
- Reproducible Code Snippet or URL: This example is from the a-sky a-frame docs. To reproduce, can modify version in the code here (see screnshot): [glitch linked to a-sky docs](https://glitch.com/edit/#!/aframe-changing-the-sky?path=index.html)

[a-sky docs referenced](https://aframe.io/docs/1.6.0/primitives/a-sky.html#main)

Example linked "Changing the Sky" works when in v1.5.0 (or earlier) but seems to break when in 1.6.0.  

Seeing this in console: `[.WebGL-0x1080dca3f00] GL_INVALID_OPERATION: Texture is Immutable.`

Note: there are other errors in the glitch (offset overflows texture dimensions) but in a local test I can observe the same issue while only seeing the "Texture is Immutable" log.

Errors observed when updating version to 1.6.0:
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/5efa8e8c-1388-4be7-b3c5-ef1712fcdbc5">

No errors and desired "image changing" behavior in version 1.5.0:
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/e7381bc0-6621-4dc1-a3f5-653f1b1cd437">

**Comment by dmarcos** [comment]
edge only?

**Comment by alszeb** [comment]
Thanks for checking! So far I've only had the chance to test the "change the sky" scene on Edge on mac but also tested our web app with chrome on windows which had the 'texture is immutable' output.

**Comment by mrxz** [comment]
@alszeb Could you try it with A-Frame master, the issue might've been resolved already.
Here's the URL for the latest commit: https://cdn.jsdelivr.net/gh/aframevr/aframe@9aa865c9f809f2db3de52fbcc1b32d6cbab27496/dist/aframe-master.min.js

**Comment by alszeb** [comment]
Will do, thank you!

**Comment by alszeb** [comment]
Just tested on https://cdn.jsdelivr.net/gh/aframevr/aframe@9aa865c9f809f2db3de52fbcc1b32d6cbab27496/dist/aframe-master.min.js and I did not see the issue 🚀. Appears to have already been fixed. Thank you for looking at this.

**Comment by dmarcos** [comment]
Closing. Can reopen if necessary
