### ISSUE TITLE
Display 180 fisheye video in half-sphere

### ISSUE THREAD

**Issue by RomanIvn** [aframevr/aframe#5596]
Thank you for the amazing library and effort!

![image](https://github.com/user-attachments/assets/ce9f4936-9366-404d-8cac-cc43c6e76f18)

Watching 180 degree will be very usefull in my case.  Trying to watch a fisheye security camera from withing webxr.

After alot of trail and error I had to capture the camera with ffmpeg, stitch a black square in the same size and then convert it to equirectengular like so:

```
ffmpeg -f dshow -framerate 30 -video_size 1920x1080 -i video="USB Camera" -f lavfi -i color=c=blue:s=1920x1080 -filter_complex "[1:v][0:v]hstack, v360=input=dfisheye:output=equirect" -preset ultrafast -tune zerolatency -r 30 -c:v libx264 -x264-params "keyint=60:scenecut=0" -f rtsp rtsp://localhost:8554/fishvideo
```
I than convert the rtsp to webrtc with [MediaMtx](https://github.com/bluenviron/mediamtx)
and watch the webrc through a video component that's attached to a-videosphere\a-sphere\a-sky (what ever).
Thats the only way I got something to work with.
This approach adds significant latency and hardware encoding\decoding (instead of using h264 from the source).

Is there a simpler way to bend a texture into a half sphere shape without applying equirect to it. Just drop the texture on the sphere and crop a circle out of it (to take only the circular fisheye data and ignore the black areas)

Thank you.

**Comment by dmarcos** [comment]
I'm not an expert in immersive video. We use Github issues for bug reports and feature requests. For other questions I recommend the WebXR discord server: https://discord.gg/webxr

There's an #aframe channel 

Best of luck!
