### ISSUE TITLE
Aframe doesnt remove the .a-fullscreen class when disconnecting a-scene

### ISSUE THREAD

**Issue by gunhaxxor** [aframevr/aframe#5600]
**Description:**

- A-Frame Version: 1.6.0
- Platform / Device: Chrome
- Reproducible Code Snippet or URL:

Aframe doesnt remove the .a-fullscreen class when disconnecting a-scene

**Comment by dmarcos** [comment]
What do you mean by "disconnecting"? Feel free to open a PR
