### ISSUE TITLE
Camera movement only affecting one eye in stereo rendering

### ISSUE THREAD

**Issue by lp85d** [aframevr/aframe#5613]
**Description:**  
Stereo rendering works for only one eye (right eye), and camera movement is not properly synchronized across both eyes when using device motion (gyroscope).

- A-Frame Version: 1.6.0
- Platform / Device: Mobile (Android)
- Reproducible Code Snippet or URL: [https://parspost.ru/VR/](https://parspost.ru/VR/)

**Comment by lp85d** [comment]
I want a dynamic picture to be displayed in both eyes, but as you can see in the built-in telegram browser, it is dynamic only in the right eye

![image](https://github.com/user-attachments/assets/3874caa6-fc2c-4de6-86c2-2ba34c1fa53b)

**Comment by mrxz** [comment]
A-Frame only does stereo rendering for WebXR. It seems you want to output stereo views without using WebXR. The issue tracker is meant for bug reports and feature request. A better place to ask your question would be the `#aframe` channels on either the WebXR (https://discord.gg/webxr) or the Supermedium (https://discord.com/invite/tGYjkYr) Discord servers.

In any case, my advice would be to either use a component like [`aframe-multi-camera`](https://github.com/diarmidmackenzie/aframe-multi-camera/tree/main), which allows you to define additional camera views and suppress the main camera render. Or integrate [IWER](https://meta-quest.github.io/immersive-web-emulation-runtime/) to make use of the WebXR code paths.

Just be aware that if the output is going to be viewed through lenses, you'd still need to apply lens distortion correction. Though without knowing your goal, hard to say if this is relevant in your case.

**Comment by dmarcos** [comment]
Yeah would be useful to understand overall goal here. Why stereo these days outside of a WebXR code path?

**Comment by lp85d** [comment]
> Да, было бы полезно понять общую цель здесь. Зачем стерео в наши дни за пределами пути кода WebXR?

The goal is to write a web version of the game, interact with the gyroscope so that you can run it on any smartphone with VRBOX glasses

**Comment by dmarcos** [comment]
You can use older versions of A-Frame like 1.3.0. We decided to move away from cardboard style devices. Experience is poor, low demand, hard to tract and maintain due to all the combos of viewers, devices and browser versions. Also viewers harder and harder to come by. 

I don’t think there’s anything actionable on A-Frame side. closing this and can move discussion to discord as pointed out earlier. thanks
