### ISSUE TITLE
Support text

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#578]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Saturday Oct 24, 2015 at 00:29 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/319_

----

http://povdocs.github.io/webvr-starter-kit/examples/text.html is quite good. Check the source for sample usage.

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Saturday Oct 24, 2015 at 00:30 GMT_

----

Also, see http://www.eventbrite.com/engineering/its-2015-and-drawing-text-is-still-hard-webgl-threejs/

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Monday Oct 26, 2015 at 23:23 GMT_

----

Using the typeface.js that ships with THREE.js:

http://mrdoob.github.io/three.js/examples/webgl_geometry_text.html
http://gero3.github.io/facetype.js/

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Tuesday Nov 10, 2015 at 04:08 GMT_

----

WIP from a few weeks ago: https://github.com/cvan/aframe-core/commit/dbc4919

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Tuesday Nov 10, 2015 at 23:17 GMT_

----

How come we didn't use http://threejs.org/docs/#Reference/Extras.Geometries/TextGeometry?

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Tuesday Nov 10, 2015 at 23:18 GMT_

----

> How come we didn't use http://threejs.org/docs/#Reference/Extras.Geometries/TextGeometry?

was stealing code from POVDocs/Hiro? we should.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Wednesday Nov 18, 2015 at 11:00 GMT_

----

TextGeometry from three would be a nice start for polygonal text.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Wednesday Nov 18, 2015 at 11:01 GMT_

----

@caseyyee Can you chime in here with what you've been working on for this?

**Comment by ngokevin** [comment]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caseyyee](https://github.com/caseyyee)**
_Wednesday Nov 18, 2015 at 12:35 GMT_

----

I think its useful to have both canvas text and polygonal text.   The solution that @cvan looks to be good. 

@jcarpenter My experiment was just a bitmap font reader.  Just for fun (8-bit demo I was whipping up)  I don't think its practical.

**Comment by ngokevin** [comment]
<a href="https://github.com/mattdesl"><img src="https://avatars.githubusercontent.com/u/1383811?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattdesl](https://github.com/mattdesl)**
_Thursday Dec 17, 2015 at 04:26 GMT_

----

Some more stuff:
https://github.com/Jam3/three-bmfont-text
https://github.com/mikolalysenko/vectorize-text
https://github.com/mattdesl/physical-text
https://github.com/mapbox/node-fontnik
https://github.com/mattdesl/text-modules

I also have some legacy modules/tools dealing with vector fonts that I've been meaning to clean up: [fontpath](https://www.npmjs.com/package/fontpath). I started this since Typeface.js is pretty lacklustre (no kerning!), but development stopped once I started moving toward bitmaps and SDFs. A more modern tool might be built on [Opentype.js](https://nodebox.github.io/opentype.js/) and only export metrics and outlines, rather than trying to encompass all aspects of the rendering stack.

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Saturday Dec 19, 2015 at 19:44 GMT_

----

Here's a usable one: https://github.com/ngokevin/aframe-text-component

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Monday Jan 04, 2016 at 22:21 GMT_

----

Resolution independent text rendering:

http://wdobbie.com/post/gpu-text-rendering-with-vector-textures/

**Comment by dmarcos** [comment]
This will be handled by 3rd party components
