### ISSUE TITLE
Investigate why Chrome doesn't know correct size of canvas when an HTML import exists on the page

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#579]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Saturday Oct 24, 2015 at 00:49 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/321_

----

For whatever reason, simply adding a `<link rel="import">` (without even an `href`) to the `<head>` of the page (even a `<link rel="import" async>`) causes Chrome to think `canvas.offsetWidth` and `canvas.offsetHeight` are both `0` at [this point in the scene creation/canvas (re)sizing](https://github.com/MozVR/aframe-core/blob/ca9d11c/src/core/vr-scene.js#L330-L331).

Even if we wait for `<vr-scene>`'s the `loaded` custom event to fire, it's still `0`.

We actually have to wait for the document to fire __`load`__; for some reason, __`DOMContentLoaded`__ is not late enough.

According to the [__HTML Imports__ spec](http://www.w3.org/TR/html-imports/#additions-to-tree-construction-algorithm):

> All import dependents __must__ be loaded before DOMContentLoaded is fired. See [Bug 23526](https://www.w3.org/Bugs/Public/show_bug.cgi?id=23526).

Firefox and other browsers aren't affected because HTML Imports are natively supported on only Chrome; elsewhere polyfills are being used.

I checked the [Chromium bugs](https://code.google.com/p/chromium/issues/list?q=html+import), and I couldn't find anything on file.

**Comment by cvan** [comment]
HTML imports are no longer an issue once we merge @ngokevin's PR #883 that introduces the newfangled primitives wherein `a-template` is removed. See relevant issue #930 re: reintroducing templates.

**Comment by cvan** [comment]
Reopening this to remove the Chrome-specific code in `attachedCallback` when PR #883 is merged.

**Comment by ngokevin** [comment]
removed html imports
