### ISSUE TITLE
[CLOSED] Raycaster should ignore intersections on invisible objects

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#592]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Friday Oct 30, 2015 at 03:21 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/350_

----

Currently, if I have an __invisible__ sphere in front of a __visible__ cube, clicking with gaze-based cursor results in a `click` event for the invisible sphere, not the cube. This was unexpected to me and was not the behaviour I desired.

If you want elements that can be intersected when "invisible" then I would recommend folks use `material="opacity: 0"`. Thoughts, @dmarcos?

**Comment by ripitrust** [comment]
Has this been fixed yet?
