### ISSUE TITLE
Do not start fuse-based cursor timeout until page is loaded/scene is interacted with

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#594]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Friday Oct 30, 2015 at 04:28 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/354_

---
1. Load http://mozvr.github.io/aframe-core/examples/panoexplorer/
2. Notice the fuse-based cursor starts and times out immediately when the page is loaded

Expected behaviour:
Only when I interact with the page does the cursor start doing stuff

Perhaps we should be delaying calculating intersections until the page is loaded/interacted with. I'm not sure.

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Tuesday Nov 10, 2015 at 04:28 GMT_

----

abandoned PR: #354

**Comment by dmarcos** [comment]
@ngokevin Should we close this?
