### ISSUE TITLE
Material rendering flat in Firefox Android.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#599]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [caseyyee](https://github.com/caseyyee)**
_Saturday Oct 31, 2015 at 19:12 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/366_

----

![image](https://cloud.githubusercontent.com/assets/1560884/10865435/909d63c6-7fc8-11e5-9147-b79964f1a6b2.png)

Running Nightly edition.

This was working previously, not sure what has changed.

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Saturday Oct 31, 2015 at 19:25 GMT_

----

might need to tone down the default ambient light a bit 

https://github.com/MozVR/aframe-core/pull/359

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Sunday Nov 01, 2015 at 00:05 GMT_

----

The lighting looks correct to me on desktop (Nightly, Mac):

![screen shot 2015-10-31 at 5 04 31 pm](https://cloud.githubusercontent.com/assets/1425497/10866570/8fd604ec-7ff1-11e5-9575-ead943797505.png)

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Sunday Nov 01, 2015 at 00:05 GMT_

----

Same result in desktop Mac Chrome also...

**Comment by ngokevin** [comment]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caseyyee](https://github.com/caseyyee)**
_Sunday Nov 01, 2015 at 03:13 GMT_

----

Yeah, looks fine on desktop.   Just FF Android it seems to be an issue.

Not sure why it would be different.

Casey

**Comment by ngokevin** [comment]
Fixed when we bumped three

**Comment by hodaielab** [comment]
Hi, my obj files are rendering flat in the following example (white object), is this a problem with my lighting? 
kliang3.github.io
