### ISSUE TITLE
cache textures in material component

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#606]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ngokevin](https://github.com/ngokevin)**
_Tuesday Nov 03, 2015 at 02:20 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/377_

----

**Comment by ngokevin** [comment]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caseyyee](https://github.com/caseyyee)**
_Wednesday Nov 18, 2015 at 17:51 GMT_

----

Definetly starts to add up.

A sample scene I have fetches model data for each instance:

`info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 1ms (static)
 info http: GET /examples/editor/models/pine.dae 200 1ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 1ms (static)
 info http: GET /examples/editor/models/pine.dae 200 1ms (static)
 info http: GET /examples/editor/models/pine.dae 200 1ms (static)
 info http: GET /examples/editor/models/pine.dae 200 1ms (static)
 info http: GET /examples/editor/models/pine.dae 200 1ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)
 info http: GET /examples/editor/models/pine.dae 200 0ms (static)`

**Comment by cvan** [comment]
@caseyyee your issue would be solved by #712
