### ISSUE TITLE
Cursor should render at intersected object depth

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#638]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [caseyyee](https://github.com/caseyyee)**
_Monday Nov 16, 2015 at 20:30 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/448_

---

Otherwise the cursor can be obscured by foreground element and rendered behind objects.

Also causes eye strain since it is basically floating in your gaze in front of everything.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Wednesday Nov 18, 2015 at 10:51 GMT_

----

Yeah, this is the standard approach. I recall first reading about it in the Team Fortress 2 VR conversion post mortem.

**Comment by ngokevin** [comment]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caseyyee](https://github.com/caseyyee)**
_Thursday Nov 19, 2015 at 04:58 GMT_

----

Just watched "Oculus Connect 2: Game Design Un-Rules: Examining Design Failures in Time Machine VR" https://www.youtube.com/watch?v=14p9mqs2LiQ

In this game, Instead of a specific target reticule.   The designers used concentric circles to form a holographic  tube.   They found that this:
- Avoids parallax eye un-focus issues.  Much more comfortable for users.
- The holographic/semi-transparent treatment proved less distracting to users.
- Surprisingly accurate.

**Comment by mkungla** [comment]
@caseyyee is that still valid?

**Comment by dmarcos** [comment]
I'm ok to close. I don't think this is easy to implement in a generic way and would probably better done in an external component.

**Comment by donmccurdy** [comment]
Crawling Cursor: https://github.com/jujunjun110/aframe-crawling-cursor
