### ISSUE TITLE
Raycaster returns a-entity instead of templated element

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#641]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [caseyyee](https://github.com/caseyyee)**
_Monday Nov 16, 2015 at 21:41 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/452_

----

Not sure what the proper behavior is, but It would be useful to have the option of returning the parent template element?

**Comment by ngokevin** [comment]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caseyyee](https://github.com/caseyyee)**
_Thursday Nov 19, 2015 at 04:52 GMT_

----

Raycaster also returns distance from the geometry face or BB (not sure which one) that is intersected with -- not the objects origin.   Again, unsure what the proper behaviour should be here.

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Wednesday Dec 02, 2015 at 08:13 GMT_

----

yeah, this is filed as MozVR/aframe#204. your issue is more explicit and descriptive of the issue though. a PR has been opened to "fix" this: MozVR/aframe-core#521

this evening @dmarcos and I discussed all the possible use cases, expected behaviors, caveats, and possible solutions to remedy this. we basically have templates that wrap single elements (entities), and we have templates that wrap multiple elements (entities). the events should be bubbling, but I think it's because the `cursor` code that sets the `hovered` state on the `<a-entity>` itself and not its parent template instance (`<a-cube>`). @dmarcos and I have to have some more discussions here, but yeah.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Friday Dec 11, 2015 at 09:51 GMT_

----

Updated title to reflect new naming.

**Comment by cvan** [comment]
fixed by PR #883. may be an issue again if we resurrect templates (issue #930).
