### ISSUE TITLE
Create an example that stress tests A-Frame

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#647]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Wednesday Nov 18, 2015 at 03:24 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/464_

----

It would be good to recreate http://alteredqualia.com/three/examples/webgl_cubes.html

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Wednesday Nov 18, 2015 at 10:47 GMT_

----

@cvan We should create a whole section of performance stress tests, perhaps?

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Wednesday Nov 18, 2015 at 19:12 GMT_

----

> @cvan We should create a whole section of performance stress tests, perhaps?

sure

**Comment by ngokevin** [comment]
@dkraeker has created http://drawvr.com/city/ which brings systems to its knees.

**Comment by cvan** [comment]
> @dkraeker has created http://drawvr.com/city/ which brings systems to its knees.

let's add links to these in the Examples
