### ISSUE TITLE
Support for shadows

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#651]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [caseyyee](https://github.com/caseyyee)**
_Wednesday Nov 18, 2015 at 19:02 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/470_

---

It doesn't seem that lighting casts any shadows.  Would be great to have this.

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Wednesday Nov 18, 2015 at 19:04 GMT_

----

Keeping a WIP at https://github.com/MozVR/aframe-core/pull/348

**Comment by caseyyee** [comment]
This would add a ton of depth to even basic scenes.   Would love to have this in the next release.

**Comment by ngokevin** [comment]
We have our plates full for the next release and need to fight off some feature creep, but definitely soon after. There's extra work involved in bumping three.js since they revamped shadows. And arguably, text + physics are more valuable features. But the component itself is fairly simple, though I had some trouble fine-tuning the shadows back in Nov

**Comment by donmccurdy** [comment]
@ngokevin I've updated your `shadow` and `shadow-light` components for A-Frame v0.2.0 and the THREE.js changes [here](https://github.com/donmccurdy/aframe-extras/tree/master/src/shadows). Performance seems OK with directional lighting, but [bad with point lights](https://github.com/donmccurdy/aframe-extras/issues/50). 

Having trouble with some of the parameters though – shadows have been offset or weirdly scaled in my tests so far.

**Comment by ngokevin** [comment]
Cool. Yeah, didn't get it merged last time because I had trouble tuning the shadows to look good, and then never got back around to it.

**Comment by msimpson** [comment]
@donmccurdy 
Try settings your shadow bias to `0.02` and increasing your map size to a width and height of `2048`. I find tweaking the bias stops the light bleed at the edge of objects and a higher map size will help that jagged look. Also, you may want to drop shadow darkness; it seems that it's legacy at this point.

**Comment by donmccurdy** [comment]
@msimpson thanks! that does look sharper but the shapes of shadows are still wrong. maybe i'm misunderstanding how directional lights should be positioned, but haven't found a good example yet.

Example here - the shadow seems to only come from the end of a longer object : /

<img width="775" alt="screen shot 2016-06-13 at 3 32 48 pm" src="https://cloud.githubusercontent.com/assets/1848368/16011280/992dbb74-317c-11e6-973d-a33e144ceefd.png">

**Comment by msimpson** [comment]
@donmccurdy 
That's really odd. I've not seen that before.

**Comment by msj121** [comment]
Not sure why it isn't working on codepen, but a similar scene I have working on my own webserver:
http://codepen.io/msj121/pen/gMMyrO

Try it for yourself:
```
<a-scene>
  <a-sphere shadow="cast:true;receive:true;" position="0 0.25 -4.5" radius="1.25" color="#EF2D5E"></a-sphere>
  <a-box shadow="cast:true;receive:true;" position="-1 -0.5 -3" rotation="0 45 0" width="1" height="1" depth="1" color="#4CC3D9"></a-box>
  <a-cylinder shadow="cast:true;receive:true;" position="1 -0.25 -2" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>
  <a-plane shadow="cast:true;receive:true;" rotation="-90 0 0" position="0 -1 -3" width="4" height="4" color="#7BC8A4"></a-plane>
  <a-entity shadow-light="type:spot;angle:45;castShadow:true;" position="15 25 15"></a-entity>
  <a-entity camera="active:true" wasd-controls="" look-controls="" position="0 0 0" rotation="0 0 0"></a-entity>
</a-scene>
```

**Comment by FrederickDesimpel** [comment]
I wouldn't complicate the light component any further with shadows. I have a pr in the works which uses three components: a shadow-scene, shadow-object and shadow-light component, to be used on the respective elements. With the shadow-scene you can globally set shadows on or off and set the type.

Will continue on it after aframe is updated to use the latest threejs.

**Comment by ngokevin** [comment]
Or an API like:

```
<a-scene shadow="type: soft">
  <a-box shadow="cast: false; receive: true"></a-box>
  <a-entity light light-shadow>
</a-scene>
```

Where `<a-scene shadow>` is defined as a system: `AFRAME.registerSystem('shadow', {})`

**Comment by takahirox** [comment]
Any update about shadow?
I really want A-Frame official shadow support~

**Comment by donmccurdy** [comment]
@takahirox I'm not sure about a roadmap for official support, but the bugs I mentioned above about `aframe-extras.shadows` have been fixed.

**Comment by takahirox** [comment]
@donmccurdy Yeah, I confirmed `aframe-extras.shadow` works now, thanks. But I found a bug and have a feature request so I'll send PR to it.

And it seems like shadow will get in 0.5.0, that sound p good to me :D

**Comment by donmccurdy** [comment]
@ngokevin +1 for that suggested syntax change, and having either a system or a scene-level component that configures the renderer. What do you think about aiming to include shadows in 0.5.0? Or would a registry package be best?

**Comment by ngokevin** [comment]
I support shadows for core, the PR is already tagged for the 0.5.0 milestone

**Comment by donmccurdy** [comment]
SG. Before I (or someone) opens a PR, here's a proposed structure:

```
extras/
├── ...
└── shadows/
    ├── components/
    │   ├── index.js
    │   ├── shadow.js
    │   └── shadow-light.js
    ├── systems/
    │   ├── index.js
    │   └── shadow.js
    └── index.js
```

Is this consistent with what you have in mind, @ngokevin @dmarcos @takahirox ? May be worth considering whether `shadow-light` should be a separate component or simply add some functionality into the `light` component. It [modifies the schema significantly](https://github.com/donmccurdy/aframe-extras/blob/master/src/shadows/shadow-light.js), but doesn't do all that much otherwise.

**Comment by ngokevin** [comment]
Slightly leaning towards putting the light's shadow parameters as a part of light since the shadow-light component needs a light, and the light component is very small so it doesn't hurt adding the shadow pieces.

**Comment by takahirox** [comment]
As for me(Three.js user/contributor and Web content creator),
adding the shadow stuffs into existing light is more natural than separating them.

**Comment by donmccurdy** [comment]
Cool, this sounds good to me (i just haven't had time to start yet).

I'll re-assign to myself and remove the 'help wanted' tag if my schedule frees up before someone else takes it. So this issue is still up-for-grabs now.

**Comment by fernandojsg** [comment]
I agree also that looks more convenient to add it to `light` instead of another component, it's typically how it works on 3d software, you add a light, click shadows and you're ready to go.
