### ISSUE TITLE
Establish a consistent default background-color for scenes

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#656]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Wednesday Nov 18, 2015 at 23:07 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/480_

---

It's currently `#fff` outside of VR mode but `#000` when you enter VR mode.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Monday Nov 23, 2015 at 18:58 GMT_

----

The canvas where we paint the scene has transparent background. When we go fullscreen we lose the default color of body and it's replaced with whatever the compositor puts in the background when an element goes fullscreen. How should we handle this?

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Monday Nov 23, 2015 at 22:19 GMT_

----

> The canvas where we paint the scene has transparent background. When we go fullscreen we lose the default color of body and it's replaced with whatever the compositor puts in the background when an element goes fullscreen. How should we handle this?

I thought we should enable `<vr-scene material="color: black">` - thoughts?

**Comment by ngokevin** [comment]
Accidentally closed during merge

**Comment by RangerMauve** [comment]
Personally, I think white or an off-white color would be most appealing as a default.

**Comment by ngokevin** [comment]
Use renderer `.setClearColor` in `src/core/scene/a-scene.js`. 

Off-white is appealing (`#DADADA`)...though also consider off-black `#111` to reduce eye strain in headsets.

Bonus points for making this configurable. `<a-scene renderer="clearColor: #222">`

**Comment by rensa** [comment]
What would be a good workaround for this in the mean time? A solid colour skybox?

**Comment by mkungla** [comment]
@ngokevin this is closed by #3277
