### ISSUE TITLE
Explore switching to new THREE.js animation system

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#667]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Saturday Nov 21, 2015 at 00:16 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/499_

----

**Comment by ngokevin** [comment]
Accidentally closed during merge

**Comment by dmarcos** [comment]
Reference to the three.js animation system:

https://github.com/mrdoob/three.js/tree/master/src/animation

**Comment by donmccurdy** [comment]
Unfortunately this new animation system doesn't have any docs yet :/

Experimenting with loading animations as part of a three.js JSON model a bit here: https://github.com/donmccurdy/aframe-extras/blob/master/src/loaders/three-model.js

**Comment by dmarcos** [comment]
I think this is not relevant anymore. We have to talk about moving the animation system out of the core.
