### ISSUE TITLE
Enable antialias automatically if the hardware can deliver 60fps

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#685]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dmarcos](https://github.com/dmarcos)**
_Friday Nov 27, 2015 at 00:50 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/542_

---

In the future it could be interesting to guess the performance of the hardware and set the antialias automatically based on it and if the user add the attribute antialias=auto to the `a-scene`

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Friday Nov 27, 2015 at 17:08 GMT_

----

One problem with disabling anti-aliasing: textures will still be anti-aliased, creating a smooth / jagged contrast. You can see what this looks like in FF on my Mac Pro. FF doesn't like my ATI video cards for some reason, so anti-aliasing is disabled. The contrast between jagged geometry and smooth images is quite unpleasant.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Friday Nov 27, 2015 at 19:38 GMT_

----

It might not be ideal but in VR performance takes priority over image quality. At the beginning people will have to be creative to provide compelling experiences with low-fi graphics quality.

**Comment by ngokevin** [comment]
<a href="https://github.com/jcarpenter"><img src="https://avatars.githubusercontent.com/u/1425497?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcarpenter](https://github.com/jcarpenter)**
_Friday Nov 27, 2015 at 19:39 GMT_

----

Yep, agreed. Just calling this out as an issue we're going to see.

**Comment by dmarcos** [comment]
We now always enable antialias by default on desktop systems. it remains disabled on mobile. We can revisit that decisions if we determine that performance is acceptable after testing. Closing this in favor of https://github.com/aframevr/aframe/issues/2666
