### ISSUE TITLE
Replace `release` npm command with `np` library

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#690]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Sunday Nov 29, 2015 at 04:37 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/551_

----

Makes it easier to not make mistakes when publishing new versions of the package: https://github.com/sindresorhus/np

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Thursday Dec 03, 2015 at 04:51 GMT_

----

Actually https://github.com/semantic-release/semantic-release looks better

[tween.js](https://github.com/tweenjs/tween.js) uses it, and it seems to work pretty nicely:
https://github.com/tweenjs/tween.js/commits/master
https://github.com/tweenjs/tween.js/blob/be0958/package.json#L24

and your release commit messages become part of what you seen in the __Releases__ sections:
https://github.com/tweenjs/tween.js/releases

Best I've seen so far. I don't like `release-it` when I've used it.

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Thursday Dec 03, 2015 at 04:51 GMT_

----

For now, my [`npm run publish`](https://github.com/MozVR/aframe-core/blob/dev/package.json#L52) has been working swell.

**Comment by cvan** [comment]
Let's keep #304
