### ISSUE TITLE
Support basic templating logic to templates

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#70]
Useful for loops and conditional logic.

[Polymer has `dom-repeat` and `dom-if`](https://www.polymer-project.org/1.0/docs/devguide/templates.html).

I've thought about just supporting [Nunjucks](http://mozilla.github.io/nunjucks/templating.html) (like Mustache, Handlebars but better; inspired by [Jinja](http://jinja.pocoo.org/)) outright.

**Comment by ngokevin** [comment]
Templates in their current form are no longer on the roadmap.

A-Frame templating libraries will be their own project.
