### ISSUE TITLE
Forgo `hasLoaded` in favor of a `when` method to detect when an event has been fired at least once

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#705]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Thursday Dec 03, 2015 at 09:21 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/585_

---

my browser crashed midway through typing a comment [here](https://github.com/aframevr/aframe-editor/commit/042d064#diff-806fed3130056adbc98407610072d4cfR20) (and I guess GitHub's `localStorage` recovery didn't work in this case), so I'll paste a screenshot of the part of the comment I could recover:

<img width="752" alt="screenshot 2015-12-03 00 58 11" src="https://cloud.githubusercontent.com/assets/203725/11556010/f21a3792-9958-11e5-9899-f6bf0c5f0570.png">

it all started in PR #330. I initially created a method `ANode.prototype.on`, and @dmarcos and I made the realisation that if your reference to the element (in this example: `this.scene`) is not yet a registered custom element with the new custom prototype and instead still has a `HTMLElement` prototype, the `on` method won't exist. :cry: times.

possible workarounds I've thought of:
1. override the native `addEventListener` method (only for any element that extends `ANode`, obviously) so that when the `this.scene.addEventListener` gets called first (i.e., "registered"), the listener callback function would get called immediately if we knew that particular event had already been fired internally by us (via `emit`). (I dislike this approach/hack the most.)
2. Extend `HTMLElement`'s prototype to add an `on` method. (This is the approach @dmarcos and I thought we'd try, and [I did it in the PR](https://github.com/MozVR/aframe-core/pull/330/files#diff-151c7cdafeca2782a05a053c10a06156R63), but I decided to merge against it. I dislike this a lot; it's bad practice to pollute the prototype of native nodes - likely resulting in side-effects galore.)
3. Expose some special listener that we could listen to and users could listen to in their JS. (In my original version of PR #330, I had code everywhere do `utils.on(this.scene, 'loaded', function () {})`. It's not great, but it solves the problem. Ideally, if we decide to tackle this again (and we'll likely need to since I've already had to do this exact same thing in the [Pano Explorer](https://github.com/MozVR/aframe-core/blob/ddf77ca/examples/panoexplorer/index.html#L98-L102)), we should simply expose a method like `when` like so (could even get fancy and do something with Promises, but seems unnecessary):

``` js
// Whenever the event gets loaded at least once.
aframe.when('loaded', this.scene, function () {});
aframe.when('loaded', 'a-scene', function () {});

// And the generic cases for *adding event listeners* (à la jQuery): `on`, `off,` `once`.
aframe.on('loaded', this.scene, function () {});
aframe.once('loaded', this.scene, function () {});
aframe.off('loaded', this.scene, function () {});
```

**Comment by cvan** [comment]
really think we should do this.

every few days someone asks a question about `loaded`, and the solution is pretty cumbersome:

https://gist.github.com/cvan/7872ca1489199e1b326e

**Comment by ngokevin** [comment]
```AFRAME.utils.when``` seems like the fastest and most predictable approach.

**Comment by cvan** [comment]
@ngokevin yeah that's what we were originally doing, but that doesn't give you the convenience of doing `document.querySelector('a-scene').when('loaded', …)`

**Comment by ngokevin** [comment]
AFRAME.utils.X isn't *super* bad since it is only a few characters more verbose. Would have to start documenting our utils.

Alternative, we can do it jQuery style to add some curated DOM helpers:

```js
AFRAME.A(myScene).when('loaded', function () {});
```

**Comment by cvan** [comment]
x-tag does this

```js
var itemArray = xtag.query(document.body, 'ul li');
```

**Comment by ngokevin** [comment]
Going to mark this as optional for 0.2.0 since it's an enhancement, but I understand how important and useful it is. It will be a priority.

**Comment by ngokevin** [comment]
Closing, this feature is not necessary since we prescribe using components for all JS, which is executed/initialized when everything loaded at the right time. Doing the check-loaded-else-wait-loaded is an anti-pattern.

**Comment by donmccurdy** [comment]
> Doing the check-loaded-else-wait-loaded is an anti-pattern.

I'm fine with closing this bug as wont-fix, but FYI would disagree with this line. Components may need to do setup only after the scene has loaded, and by default components initialize before that. And, components might be added dynamically, in which case the scene has already initialized. So check-loaded-else-wait-loaded is (while not very elegant) very much necessary if the component needs the scene to be initialized first.

My current approach is:

```js
init () {
  var sceneEl = this.el.sceneEl;
  if (!sceneEl.hasLoaded) {
    sceneEl.addEventListener('loaded', this.init.bind(this));
    return;
  }
  // ...
}
```

... which isn't too bad, but does make it unsafe to rely on the component via dependencies. If this really did become an issue we could add another lifecycle method. But I don't think that's justified at this stage.
