### ISSUE TITLE
Sound comes from only one ear in chrome, but both ears in firefox

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#709]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ngokevin](https://github.com/ngokevin)**
_Friday Dec 04, 2015 at 03:19 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/593_

---

does one browser have positional audio and the other doesn't?

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Monday Dec 07, 2015 at 18:11 GMT_

----

Just curious. Do you see the same problem in other WebAudio demos?

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Monday Dec 07, 2015 at 21:47 GMT_

----

It looks like the Audio was positioned different in chrome than Firefox

**Comment by TylerFisher** [comment]
Still seeing this in Chrome. Any progress or is this a browser issue?

**Comment by mkungla** [comment]
@ngokevin  Is that issue still there I'm not able to reproduce and experience this issue!?

**Comment by ngokevin** [comment]
I'll have to try again at some point and post a test case.

**Comment by feiss** [comment]
I found that if you position the sound at the level of your head, a bit forward, it sounds pretty fine:

``` 
<a-entity position="0 1.7 -0.5" sound="src: #soundAsset; autoplay: true;"></a-entity>
          ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ngokevin** [comment]
This happens when the audio source is exactly on the same plane as the camera and you move the camera cut across the plane perpendicularly.

e.g., `<a-entity sound position="0 0 0">` and `<a-camera position="0 1.6 0">`.
