### ISSUE TITLE
Automatically generate Markdown docs

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#710]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Friday Dec 04, 2015 at 03:41 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/594_

----

The A-Frame site uses Markdown (`.md`) docs and renders them to HTML in the build step. We will be slurping up __`aframe-core`__'s `.md` docs from this repo's `docs/` directory (and same goes for the __`aframe`__ repo's).

I was able to get JS Doc doc comments generated to Markdown using [jsdoc2md](https://github.com/jsdoc2md/jsdoc-to-markdown):

https://gist.github.com/cvan/f50ae50fd4cfb2101b9c#file-all-md

<hr>

### Research

https://github.com/jsdoc2md/jsdoc-to-markdown – not great, but the most promising
https://github.com/tj/dox – decent output, but returns JSON not Markdown
https://github.com/tjchaplin/mox – no
https://github.com/cbou/markdox – no
https://github.com/sutoiku/jsdox – no
http://jashkenas.github.io/docco/ – nouseful for only inline docs, not API reference docs
https://github.com/jamesramsay/hercule#advanced-use-default-placeholders – meh, but interesting
https://github.com/jsdoc3/jsdoc – nope, doesn't properly support Markdown (lots of bugs, tables don't work, and a bunch of other _useful_ Markdown syntax)

### Relevant examples of JS Doc for modules
http://usejsdoc.org/howto-commonjs-modules.html
https://github.com/olivernn/lunr.js/blob/master/lunr.js

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Saturday Dec 05, 2015 at 11:18 GMT_

----

There's also https://github.com/documentationjs

**Comment by cvan** [comment]
Not sure we need this or should do this anytime soon.

**Comment by ngokevin** [comment]
don't think we need this
