### ISSUE TITLE
[CLOSED] Video starts autoplaying if provided a `<video autoplay="false">`

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#725]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Tuesday Dec 08, 2015 at 21:19 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/627_

----

If I naïvely create a `<video autoplay="false">`, the video will still autoplay.

See http://codepen.io/team/mozvr/pen/6b5b73a9b78c8e3d315d6976723da3a1/

The `<video>` element has been [spec'd to be kind of weirdly](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Attributes).

It'd be nice to prevent such footguns (or handle logic in templates - but primitives will solve).

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Thursday Dec 10, 2015 at 05:28 GMT_

----

Fixed in https://github.com/cvan/aframe-core/commit/45cc4099e66850125d9f1d8923ba4c97fc021c98

**Comment by calumjamesgreen** [comment]
Hey I know this is closed but it appears the the issue reappears if someone is using Microsoft Edge as a browser on the first load. Not sure if this counts as a problem or not but thought I would mention it as is a bug for something I'm building for clients.
