### ISSUE TITLE
Rename a-mixins to a-class and use the attribute class instead of mixin

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#740]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dmarcos](https://github.com/dmarcos)**
_Tuesday Dec 15, 2015 at 18:05 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/663_

----

The goal is to make the concept of mixin easier to grasp by Web Developers. This is an example taken from Twitter bootstrap:
````html
 <div class="dropdown"></div>
````
Our entities would look like:
````html
<a-entity class="cube"></div>
<a-class geometry="primitive: box" material="color: red"></a-class>
````
Not 100% sure if this is a good idea because our mixins behave a bit differently than CSS classes. For instance, mixins are dynamic as opposed to classes being static. You can change the list of classes for a given element but you cannot modify an existing class at runtime.  Our classs will also be defined in the DOM and not in a style sheet.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Tuesday Dec 15, 2015 at 18:13 GMT_

----

We could provide primitives that help people getting acquainted with the E/C arquitecture.  It would be an ```a-frame bootstrap``` library with a set of mixins/classes to create basic elements. Specialization will still work as you would expect. If you want to make a green cube you would do:
````html
<a-entity class="cube" material="color: green"></a-entity>
````

**Comment by ngokevin** [comment]
I think mixin is more clear on what it does. We can still have the bootstrap idea but with mixins.

`class` might be used by developers for running querySelectors later rather than applying mixins, so we don't want to conflate the two.

Re-open if you think there's a good case for this.

**Comment by RangerMauve** [comment]
As a user, I agree that mixin is a better name for the same reasons.

**Comment by aubergene** [comment]
I'm just learning A-frame and was confused about what attributes you could use in a `mixin` and it seems that `class` isn't one of them. In the following example only the blue cube will have a `class`. Assuming this the correct behaviour it might be good to add a note to the documentation.

```html
<a-scene>
  <a-assets>
    <a-mixin id="red" class="red-things"></a-mixin>
    <a-mixin id="blue" material="color: blue"></a-mixin>
    <a-mixin id="cube" geometry="primitive: box"></a-mixin>
  </a-assets>

  <a-entity mixin="red cube"></a-entity>
  <a-entity mixin="blue cube" class="blue-things"></a-entity>
</a-scene>
```
