### ISSUE TITLE
Mobile Safari doesn't fully enter fullscreen until landscape orientation change

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#741]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [caseyyee](https://github.com/caseyyee)**
_Tuesday Dec 15, 2015 at 19:08 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/664_

---

Requires orientation change from portrait to landscape to trigger fullscreen.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Tuesday Dec 15, 2015 at 22:07 GMT_

----

Is there anything we can do on our side to change that behavior?

**Comment by ngokevin** [comment]
<a href="https://github.com/nhirata"><img src="https://avatars.githubusercontent.com/u/1091409?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nhirata](https://github.com/nhirata)**
_Wednesday Dec 16, 2015 at 00:04 GMT_

----

So if you start off in landscape before you enter the automation, you still run into this bug.

**Comment by ngokevin** [comment]
<a href="https://github.com/nhirata"><img src="https://avatars.githubusercontent.com/u/1091409?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nhirata](https://github.com/nhirata)**
_Wednesday Dec 16, 2015 at 03:39 GMT_

----

Just a reminder of what dmarcos found : there's an option on the 6s+ to show tabs which throws the patch off as well.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Wednesday Dec 16, 2015 at 05:15 GMT_

----

More precisely, It's ```Settings->Safari->Show Tab Bar```. This option seems to be available only on iphone6+/6s+ due to the larger displays.

**Comment by cvan** [comment]
Also, if you have portrait lock enabled (which I _always_ do because who would be crazy enough not to!?). I can imagine this being super confusing for some folks who also use portrait lock; they probably get stuck and don't know why "VR mode" isn't getting enabled.

We should also provide messaging btw in addition to "turn your phone sideways."
