### ISSUE TITLE
Use a browserify transform to inline SVG in CSS

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#743]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Wednesday Dec 16, 2015 at 00:55 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/669_

---

So we don't have to manually write data URIs :+1:

**Comment by ngokevin** [comment]
done long time ago

**Comment by ngokevin** [comment]
Nevermidn

**Comment by dmarcos** [comment]
@ngokevin anything pending?
