### ISSUE TITLE
Document how to write + publish + share third-party components

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#766]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Friday Dec 18, 2015 at 01:42 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/705_

----

1. Document how to use the methods we expose on `aframeCore`/`AFRAME` (e.g., `aframeCore.registerComponent`)
2. Publish the code on GitHub, deploy online somewhere (e.g., GH Pages, CodePen, Dropbox)
3. Open a PR against https://github.com/aframevr/awesome-aframe to get a link added to it
4. Write a case study on http://aframevr.tumblr.com (if you're so willing!)

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Saturday Dec 19, 2015 at 11:07 GMT_

----

it's been asked a few times on Slack too. again here on PH: https://www.producthunt.com/tech/aframe#comment-200325

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Saturday Dec 19, 2015 at 11:08 GMT_

----

also see aframevr/aframe#298

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Tuesday Dec 22, 2015 at 00:11 GMT_

----

https://github.com/ngokevin/aframe-component-boilerplate (for now it checks for both aframe and aframe-core in the browser build)

https://aframe.io/docs/core/component.html

and I will write a blog post soon

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Tuesday Dec 22, 2015 at 00:26 GMT_

----

and feel free to link in the Docs to your `aframe-component-boilerplate` or even move it under the `aframevr` org (if you'd like, up to you)

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Tuesday Dec 22, 2015 at 00:29 GMT_

----

Yeah I might move it under the org so it gets more attention. Probably likewise with the react stuff.

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Friday Jan 08, 2016 at 01:19 GMT_

----

I might plan on waiting until 0.2.0 to start heavily writing guides because of the changes to the component API and schema that are landing.

**Comment by cvan** [comment]
We should crosspost [Kevin's fantastic blog post](http://ngokevin.com/blog/aframe-component/). And we should also incorporate as much as we can into our [docs](https://aframe.io/docs/). It'd probably make sense to have a complete "Creating your own components" guide. And lots and lots of examples (hosted on CodePen) would be fantastic.

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe/issues/949

**Comment by ngokevin** [comment]
Will be included in the docs, I have a Codepen from the blog post, more examples will come in time
