### ISSUE TITLE
Are `<meta name="viewport">` tags injected too late?

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#769]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Friday Dec 18, 2015 at 02:53 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/708_

---

Jonas Sicking (of Mozilla) mentioned at Mozlando that Gecko (Firefox's rendering engine) has a fastpath if it detects a `<meta name="viewport">` in the `<head>`.

Because the aframe script is required to be in the `<head>` (see issue #146), I wonder if we're causing unnecessary delays in mobile viewport resizing by [dynamically injecting the `<meta name="viewport">` tags](https://github.com/aframevr/aframe-core/blob/2603f4e/src/core/a-scene.js#L793).

**Comment by cvan** [comment]
I've noticed the viewport be pretty wonky on many sites. We should investigate this along with #855.
