### ISSUE TITLE
Give visual cue when JSFiddle/JS Bin cannot enter VR/fullscreen because of no `<iframe allowfullscreen>`

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#781]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cvan](https://github.com/cvan)**
_Saturday Dec 19, 2015 at 14:11 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/725_

---

JS Bin, JS Fiddle, and many online code editors that embed pages do so using just an `<iframe>`. This means when we `requestFullScreen({vrDisplay: vrHMD})`, the browser blocks the ability to enter fullscreen/VR mode.

So actually when you click on the enter VR button, we enter stereo, the button disappears, but we don't actually enter fullscreen mode.

Load http://bl.ocks.org/enjalot/8be32e6f1f32920ba841 for example
And see the console:

> Request for full-screen was denied because at least one of the document's containing iframes does not have an "allowfullscreen" attribute.

<hr>

CodePen, thankfully, does `<iframe allowfullscreen="yes">` so we're good there :heart_eyes:. We should look into reaching out to JS Bin and JSFiddle seeing if they would be willing to allow bins to enter fullscreen. In just the past few days, I've seen many folks creating their own JS Bins even though we have a forkable CodePen ready to use. So, there's definitely folks out there who could benefit from this.

So, let's first fix the Enter VR button when we failed to actually enter VR. We can provide some error state - some icon with messaging. Then we can do do some outreach to get folks to allow codebin services to allow entering fullscreen on iframes. And hopefully sometime next year we'll have an API that replaces `requestFullScreen` so we don't have any of these issues.

**Comment by zalun** [comment]
AFAIR allowfullscreen was disabled in JSFiddle for fraud protection.

**Comment by remy** [comment]
I'm amazed that I've not removed this for fraud protection (as @zalun has done with jsfiddle), since jsbin seems to attract some pretty wonderful fraud.

Anyway, I digress. @ngokevin where would you expect to go to full screen? In an embedded bin or from the jsbin editor?

**Comment by ngokevin** [comment]
@cvan originally filed the issue. I haven't seen much use of embedded bins, but have seen some share the full editor around. It would be a bit more useful to fullscreen embedded scenes given their smaller size.

But the new WebVR API no longer depends on fullscreen which makes this less of an issue.

**Comment by remy** [comment]
@ngokevin Ah, cheers for clarifying. I got a notification from twitter (on a dead account I have under my name), from @darkwing. 

Worth closing the issue if it's not an issue anymore?

**Comment by oskarkrawczyk** [comment]
@zalun Correct. But now that it's impossible to remove JSFiddle embed UI in the embeddable it might as well be re-enabled.

**Comment by ngokevin** [comment]
API no longer depends on full screen. Don't think it should be A-Frame to handle runtime compat warnings with third-party playground sites. We are recommending Glitch/CodePen which does not have this problem.
