### ISSUE TITLE
cursor mouseleave not firing consistently?

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#786]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ngokevin](https://github.com/ngokevin)**
_Monday Dec 21, 2015 at 20:55 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/735_

---

Reported on Slack by enjalot: http://blockbuilder.org/enjalot/1fd196cd99f8d58a56d3

**Comment by ngokevin** [comment]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ngokevin](https://github.com/ngokevin)**
_Monday Dec 21, 2015 at 20:56 GMT_

----

Looks like animations get in the way of the mouseleave handler working

**Comment by dmarcos** [comment]
not sure if this is still relevant. @ngokevin
