### ISSUE TITLE
Positional tracking is not properly tracked to orientation of camera.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#802]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [caseyyee](https://github.com/caseyyee)**
_Friday Jan 08, 2016 at 00:07 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/772_

----

If I rotate the camera 90deg and move forward/back, I am moved left/right.

The position needs to be multiplied by the camera rotation.

**Comment by cvan** [comment]
Would it be possible to get this addressed for GDC?

**Comment by ngokevin** [comment]
For now, I wouldn't combine WASD + HMD. There's a bug with it. And WASD not recommended with VR, it's taboo!

**Comment by cvan** [comment]
I don't think this is about movement. This is about positional tracking.

**Comment by ngokevin** [comment]
I think the issue is about positional tracking when combined with movement.

**Comment by ngokevin** [comment]
Well, just thought of there are accepted VR navigation methods that would be affected by this. So yeah, relatively important.

**Comment by ngokevin** [comment]
OK, Diego and I confirmed. It's broken without movement. Will fix/look asap
