### ISSUE TITLE
Anti-aliasing is not working with Firefox

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#803]
<a href="https://github.com/caseyyee"><img src="https://avatars.githubusercontent.com/u/1560884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [caseyyee](https://github.com/caseyyee)**
_Friday Jan 08, 2016 at 00:24 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/773_

---

Anti-aliasing is not working with A-Frame examples in Firefox.

It appears to be a A-Frame issue since mozvr.com examples (that are not A-Frame) seem to work fine.

Using Windows 10, Firefox Nightly, Oculus 0.8 runtime.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Friday Jan 08, 2016 at 14:52 GMT_

----

Antialiasing is disabled. We saw a big performance boost by disabling it.
Performance takes priority over image quality.

**Comment by darkwing** [comment]
Disabling antialiasing was a method we employed to make Firefox OS TV games more performant.  Can we close this based on perf > image quality?

**Comment by ngokevin** [comment]
Disabled by default, can reconsider in a later issue if needed
