### ISSUE TITLE
[CLOSED] View a-video on mobile

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#805]
<a href="https://github.com/joshkpeterson"><img src="https://avatars.githubusercontent.com/u/2294194?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [joshkpeterson](https://github.com/joshkpeterson)**
_Friday Jan 08, 2016 at 21:54 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/775_

----

When viewing the example in the package at examples/template-video/index.html on mobile devices, all I see is a black rectangle where the video should be.

Chrome 47.0.2526.83 on Android 5.1.1 Samsung Note 5
Safari on iOS 9.0.2 on iPhone 6 

There are no javascript errors when running this on Android Chrome. 

The example at http://threejs.org/examples/#canvas_materials_video is giving me similar results, perhaps I should escalate to threejs? (Edit: created an [issue there too](https://github.com/mrdoob/three.js/issues/7932))

I've tried a bunch of different video file formats on different browsers/devices, and results are very uneven and scattered, but I couldn't get any video files to work on mobile whatsoever except I got this example to work in firefox on Android.

I could list out everything I've tried, but since sharing and working with video files is kind of cumbersome, let's see if we can get *just this one* video file to work on mobile chrome/safari first. 

Thanks!

**Comment by ngokevin** [comment]
<a href="https://github.com/joshkpeterson"><img src="https://avatars.githubusercontent.com/u/2294194?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joshkpeterson](https://github.com/joshkpeterson)**
_Saturday Jan 09, 2016 at 05:48 GMT_

----

Whoops thanks, that slipped by me. It would be great to have a little documentation or example on how to incorporate user input to trigger a play on a video, I tried quickly but must have had something wrong.

**Comment by ananthprabhum** [comment]
Hi @ngokevin @joshkpeterson - is this issue addressed? Any workaround for using a-video on mobile browser?
