### ISSUE TITLE
AFRAME.registerComponents ?

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#807]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ngokevin](https://github.com/ngokevin)**
_Sunday Jan 10, 2016 at 04:27 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/777_

----

batch registration feature:

```js
AFRAME.registerComponents({
  text: textComponent,
  lookAt: lookAtComponent,
  path: pathComponent
});
```

Useful if someone ships a component library that exports multiple components at once.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Monday Jan 11, 2016 at 15:29 GMT_

----

To increase reusability I prefer an API that encourages to have one file per component.

**Comment by cvan** [comment]
there's no `document.registerElements` (which I think is the function signature pattern that we're modeling this after), so I'd say it's probably not worth it.
