### ISSUE TITLE
Throw more errors if a component has typos in the syntax in the HTML attribute.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#812]
<a href="https://github.com/ngokevin"><img src="https://avatars.githubusercontent.com/u/674727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ngokevin](https://github.com/ngokevin)**
_Tuesday Jan 12, 2016 at 06:46 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/790_

---

If you make a small typo like `<a-entity geometry="primitive box;">`, it fails silently.

**Comment by nowa45** [comment]
Hi ngokevin,

Would following warn message be sufficient in this case:

*core:schema:warn Unknown component property: primitive box*

I would alter the code like this:

```
Object.keys(propData).forEach(function (propName) {
    if (!schema[propName] && !silent) {
-      warn('Unknown component property: ' + propName);
+      warn('Unknown component property: ' + (propName != '' ? propName : propData[propName]));
    }
  });
```

If you find it OK, I will create pull request for this.

**Comment by ngokevin** [comment]
We log the component name now, should be good.
