### ISSUE TITLE
look-controls movement axes are incorrect when device is not in portrait mode

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#814]
<a href="https://github.com/cemkod"><img src="https://avatars.githubusercontent.com/u/4003996?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cemkod](https://github.com/cemkod)**
_Wednesday Jan 13, 2016 at 00:50 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/792_

----

Device: Nexus 7 II
Browser: Firefox 43.0
Aframe-core: 0.1.3 Dev Branch
Aframe: 0.1.1 Dev Branch

On any example that uses look-control on camera, when device is oriented in landscape mode or reverse-portrait mode, controlling the camera with gyro does not behave like it should.

In reverse-portrait orientation, scene is drawn upside-down and behind the camera's starting orientation. Tiltin the device up, makes the camera look down and vice verse. Same with he horizontal axes.

In horizontal orientation, scene is drawn rotated 90 degrees around the Z axis. Tilting device side-by-side moves the camera up/down.

**Comment by dmarcos** [comment]
@cemkod I cannot reproduce this in any of my Android devices. Please reproduce if it's still a problem.
