### ISSUE TITLE
Constant stream of error messages in console log: "Invalid timestamps detected. Time step between successive gyroscope sensor samples is very small or not monotonic"

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#815]
<a href="https://github.com/cemkod"><img src="https://avatars.githubusercontent.com/u/4003996?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cemkod](https://github.com/cemkod)**
_Wednesday Jan 13, 2016 at 00:55 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/793_

---

Device: Nexus 7 II
Browser: Firefox 43.0

When running the examples, there is a constant stream of the following error message in console log:
`Invalid timestamps detected. Time step between successive gyroscope sensor samples is very small or not monotonic`

Gyro controls seem to be responsive with no lag.

**Comment by eskalera** [comment]
Same issue here. 
- Device: Epson Moverio BT-200
- Browser: Firefox 45

**Comment by dmarcos** [comment]
@eskalera Is this still an issue on master?

**Comment by eswara1997** [comment]
@dmarcos still having this error. I'm using a samsung s7 edge with firefox.

**Comment by perqa** [comment]
It is clearly related to WebVR polyfill. See webvr-polyfill.js:5706:

`    var deltaS = timestampS - this.previousTimestampS;
                if (deltaS <= Util.MIN_TIMESTEP || deltaS > Util.MAX_TIMESTEP) {
                    console.warn('Invalid timestamps detected. Time step between successive ' +
                    'gyroscope sensor samples is very small or not monotonic');
                    this.previousTimestampS = timestampS;
                    return;
                }`

**Comment by jsantell** [comment]
This appears to be still an issue: https://github.com/googlevr/webvr-polyfill/issues/201

If anyone can follow up there with more info (what are the timestamps? are they not updated or too small/large?), I'll check it out

**Comment by jsantell** [comment]
Closed via https://github.com/googlevr/cardboard-vr-display/pull/9 -- will be in the next polyfill release. To clarify, this just silences the messages and only displays once. In testing, was getting messages for this in iOS and Firefox for Android, but the pose estimation was still working just fine, so this clears out the console a bit. If anyone has issues with this warning AND poses are not working, would love to learn more!

**Comment by dmarcos** [comment]
@jsantell sweet! thanks.
