### ISSUE TITLE
Move some dependencies in production `dependencies` to `devDependencies`

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#820]
Notice we have `browserify-css` in both:

https://github.com/aframevr/aframe/blob/e4955258/package.json#L25-L68

And I think a lot of the production ones can be dev ones. Some of them changed with the merge (7c4e77e).

Thoughts, @ngokevin?

**Comment by ngokevin** [comment]
Now that we are pointing package.json to `dist`, I think we can move browserify-css to `devDependencies`. Otherwise, we would want browserify transforms in `dependencies`.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/840
