### ISSUE TITLE
Shopping example busted: images and animations off

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#826]
[http://localhost:9000/examples/showcase-shopping/](http://localhost:9000/examples/showcase-shopping/)

The positions for the images are wrong now:

<img width="1494" alt="screenshot 2016-01-13 16 53 57" src="https://cloud.githubusercontent.com/assets/203725/12312697/523c7c10-ba16-11e5-8183-d0784dbe21f1.png">
<img width="1494" alt="screenshot 2016-01-13 16 54 29" src="https://cloud.githubusercontent.com/assets/203725/12312696/523af99e-ba16-11e5-969b-ee903a677a30.png">

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe/issues/828
