### ISSUE TITLE
Video example busted in Firefox

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#827]
<img width="1494" alt="screenshot 2016-01-13 16 58 14" src="https://cloud.githubusercontent.com/assets/203725/12312759/d5ee209a-ba16-11e5-8a3a-7e9ac727db0b.png">

**Comment by cvan** [comment]
Possibly related to #828

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
