### ISSUE TITLE
Log JS exceptions using Raven or something

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#833]

**Comment by ngokevin** [comment]
I'd close to not add another dependency, not have anything pinging home, and I feel Raven is more of something you'd include in an application rather than a distributed library.

**Comment by cvan** [comment]
Yeah, sorry, I thought of this more as an opt-in, third-party component. And, it'd be smart to integrate the component on the examples when viewed from `<iframes>` on the [A-Frame site](https://aframe.io/) site. I've filed WebVRRocks/webvr-agent#28 to handle it within the WebVR Agent.
