### ISSUE TITLE
Fira font doesn't load on /examples/index.html

### ISSUE THREAD

**Issue by cemkod** [aframevr/aframe#841]
On https://github.com/aframevr/aframe/blob/dev/examples/index.html :
Loading https://cvan.io/Fira/fira.css fails with HTTP 522 Origin Connection Timeout.
Chrome 40.0 on Linux

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/842

**Comment by ngokevin** [comment]
It is deferred now, but @cvan might want to think about hosting it somewhere else?

**Comment by cvan** [comment]
handled in #842
