### ISSUE TITLE
Enter VR modal should not trigger on hover when invisible

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#846]
Only hovering over the actual button should trigger the Enter VR modal.

**Comment by ngokevin** [comment]
This is fixed, although the space where the modal is is still causing a dead space when trying to drag over it.

**Comment by cvan** [comment]
Oops, my bad. This means you cannot click on the "Learn more" link in the modal.

**Comment by ngokevin** [comment]
Accidentally closed during merge

**Comment by ngokevin** [comment]
Actually this works now
