### ISSUE TITLE
npm start problem on windows 8 (npm ERR! code ELIFECYCLE)

### ISSUE THREAD

**Issue by dihlo** [aframevr/aframe#849]
some npm start problem on windows 8. 

git log:

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! aframe@0.1.1 build: `mkdir -p build/ && npm run browserify -- --debug -o build/aframe.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aframe@0.1.1 build script 'mkdir -p build/ && npm run browserify -- --debug -o build/aframe.js'.
npm ERR! This is most likely a problem with the aframe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdir -p build/ && npm run browserify -- --debug -o build/aframe.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls aframe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user-55\vr\aframe\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! aframe@0.1.1 dev: `npm run build && node ./scripts/budo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aframe@0.1.1 dev script 'npm run build && node ./scripts/budo'.
npm ERR! This is most likely a problem with the aframe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && node ./scripts/budo
npm ERR! You can get their info via:
npm ERR!     npm owner ls aframe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user-55\vr\aframe\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! aframe@0.1.1 start: `npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aframe@0.1.1 start script 'npm run dev'.
npm ERR! This is most likely a problem with the aframe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls aframe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user-55\vr\aframe\npm-debug.log

**Comment by dmarcos** [comment]
This is because npm runs the npm directives through ```cmd.exe``` on Windows. We're using pure node scripts now on the (dev)[https://github.com/aframevr/aframe/blob/dev/package.json] brand and this problem will be fixed in the next release. Thanks for reporting.
