### ISSUE TITLE
Proposal: Separate look-controls into two parts, hmd-control and mouse-control

### ISSUE THREAD

**Issue by cemkod** [aframevr/aframe#850]
I think HMD-control should be its own component. When I was writing [fps look component](https://github.com/cemkod/aframe-fps-look-component), I found out mouse look and hmd look are coupled in a single component, so replacing one of them is not possible without duplicating code. 

[No click look controls](https://github.com/alexrkass/aframe-no-click-look-controls) also seems to hit this barrier and chose to duplicate the hmd tracking code in their component.

I think this should be more modular so that we can replace just the desktop look behaviour with a component.

**Comment by ngokevin** [comment]
@dmarcos Does this sound good to go ahead with?

**Comment by donmccurdy** [comment]
If separated, it would be important that it's still possible to use both on the same element. Otherwise we'd end up with demos that work either on HMD or desktop but not both. Is there a clean way for two separate components to know when the other takes precedence?

**Comment by dmarcos** [comment]
I would like to keep look-controls as they are. We can have other components like ```fps-controls``` that will be used instead of ```look-controls```. They will manage internally the different inputs mouse/hmd to move the entity accordingly.  I prefer to see purpose specific controls instead of a set of input method oriented ones. How you handle hmd/keyboard/mouse input is application specific.

**Comment by ngokevin** [comment]
If it's split up, can we create purpose-specific controls that use dependency components like hmd-controls and mouse-controls and fps-controls.

**Comment by dmarcos** [comment]
as @donmccurdy said making them composable is difficult. Composing rotations and translations in the way you want is tricky. It's better to just let each controls listen to the inputs they care about and handle the composition internally.

**Comment by ngokevin** [comment]
I think for now, we will recommend self-contained controls, even if they are duplicating logic for now.
