### ISSUE TITLE
Background appear black on a android mobile phone.

### ISSUE THREAD

**Issue by sergioroja** [aframevr/aframe#852]
At loading time on my website: www.sergioroja.com/test.html
![screenshot](https://cloud.githubusercontent.com/assets/13263255/12427063/e2aee5b0-be91-11e5-8a19-12fa62c39d08.png)

![screenshot-69](https://cloud.githubusercontent.com/assets/13263255/12380831/f1205d52-bd30-11e5-8902-2b5da2614c11.png)
Phone: Motorola moto e
Android: 4.4.4 
Browser: Chrome 47.0.2

console log:

aframe.js:58458 The key "shrink-to-fit" is not recognized and ignored.
aframe.js:35227 THREE.WebGLRenderer 74dev
aframe.js:39054 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
VM45 aframe.js:51328 Invalid timestamps detected. Time step between successive gyroscope sensor samples is very small or not monotonic

**Comment by cvan** [comment]
Thanks for filing! And very sorry about this issue.

> aframe.js:39054 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.

Hmm, that's very interesting considering we don't have any textures whatsoever in the Hello World example. It could be that the [blank `url()` for `<a-sky>`](https://github.com/aframevr/aframe/blob/e49552/src/elements/templates/a-sky/index.html#L13) is causing this. I'm not sure.

I see mrdoob/three.js#6606 mention similar issues but it seems to be related to only videos and cubemaps.

I wonder if this error is even what's causing the black error though. Will need to investigate some more.

**Comment by i3games** [comment]
Output from Chrome on Android Debug (Chrome 47, Android 6.01)

```
The key "shrink-to-fit" is not recognized and ignored.
THREE.WebGLRenderer 74dev
THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
```
 
Output from Desktop Chrome 
```
THREE.WebGLRenderer 74dev
```

**Comment by cvan** [comment]
@i3games: thanks for sharing that info - that helps. and sharing the snippet should help folks until this gets fixed in the upcoming release. appreciate it :+1:

**Comment by hwray** [comment]
@i3games Thanks for including a fix in your post! This just saved me after 2 hours of debugging on Android :)

**Comment by ngokevin** [comment]
is fixed on our dev branch, we will be releasing a patch today
