### ISSUE TITLE
iPhone 5s

### ISSUE THREAD

**Issue by nasodan** [aframevr/aframe#853]
In iPhone 5s/ios9.2 with all browsers full screen doesn't work. 
In Safari in particular, canvas doesn't resize right.

**Comment by cvan** [comment]
Thanks for filing! We'll take a look the second we get our hands on a 5S.

**Comment by vorg** [comment]
same as https://github.com/aframevr/aframe/issues/967

**Comment by ngokevin** [comment]
Going to dupe with https://github.com/aframevr/aframe/issues/967.
