### ISSUE TITLE
Remove `shrink-to-fit` from `meta[name=viewport]`

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#855]
> `aframe.js:58458 The key "shrink-to-fit" is not recognized and ignored.`

**Comment by eterry1388** [comment]
Why should this be removed?  It is needed so that layouts behave on iOS 9 and above.  Yes it won't be recognized on devices other than iOS, so thus the warning.  It is only a warning after all, not an error.

**Comment by cvan** [comment]
> Why should this be removed? It is needed so that layouts behave on iOS 9 and above. Yes it won't be recognized on devices other than iOS, so thus the warning. It is only a warning after all, not an error.

That warning was actually from the Safari remote debugger when I had connected my iPhone device.

Perhaps we should look into
https://github.com/bendrucker/meta-viewport-ios-9
https://github.com/gajus/scream
