### ISSUE TITLE
webvr-polyfill reporting `Invalid timestamps detected` on mobile (iOS + Android)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#856]
> `aframe.js:51328 Invalid timestamps detected. Time step between successive gyroscope sensor samples is very small or not monotonic`

Also see [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1217942#c9).

**Comment by cemkod** [comment]
see: https://github.com/aframevr/aframe/issues/815

**Comment by cvan** [comment]
Dupe of #815
