### ISSUE TITLE
`mouseleave` events don’t fire if the `mouseenter` event has yet to finish

### ISSUE THREAD

**Issue by misterburton** [aframevr/aframe#857]
`mouseleave` events don’t fire if the `mouseenter` event has yet to finish. so, in the following code example, if a user focuses their `a-entity cursor` on an object but leaves before the animation has finished, the`mouseleave` animation doesn’t play, at all:

```
<a-animation attribute="opacity" begin="mouseenter" to="1" dur="1000"></a-animation>
<a-animation attribute="opacity" begin="mouseleave" to=".25" dur="1000"></a-animation>
```

In tween.js, `override:true` might to be appended to the `props` argument to fix this.

**Comment by dmarcos** [comment]
@misterburton Can you provide an example to reproduce?

**Comment by misterburton** [comment]
live example: http://misterburton.com/local/ideo-sf-panorama/

switching to `<a-entity id="cube" geometry="primitive: box"…` now to see if it fixes the issue.

**Comment by ngokevin** [comment]
We believe it is a bug with the cursor. Manually registering the events, `mouseleave` still doesn't fire well.

**Comment by dmarcos** [comment]
I don't think this is a problem with the cursor. If you wait for the animation triggered on mouseenter to finish and then you move the mouse out of the object the animation triggered on mouseleave plays as expected. The problem only reproduces if you move the mouse out of the object before the mouseenter animation finishes. I think it's a problem with having two animations playing at the same time.

**Comment by misterburton** [comment]
Right, the expected behavior, in my mind, is that a `mouseenter` animation
that has yet to complete before the `mouseleave` event is fired should not
complete.

Example: if an opacity animation that is set from 0 to 1 has only reached
.5 on enter when the cursor then rolls off, it should animate from .5 back
to 0 on leave.

**Comment by misterburton** [comment]
both events fire here on quick rollover/out, but only if i use `<a-entity>`, not if i use `<a-cube>`:

```
document.querySelector('#cube').addEventListener('click', function () {
  document.querySelector('#cube').emit('fadeIn');
  console.log('click');
});

document.querySelector('#cube').addEventListener('mouseleave', function () {
  document.querySelector('#cube').emit('fadeOut');
  console.log('mouse leave');
});
```

the only remaining issue is that the fadeout animation simply doesn't fire on mouseleave, at all:

```
<a-animation attribute="material.opacity" begin="fadeIn" to="1" dur="1000"></a-animation>
<a-animation attribute="material.opacity" begin="fadeOut" to=".25" dur="1000"></a-animation>
```

full code updated & viewable here: http://misterburton.com/local/ideo-sf-panorama/

**Comment by coleholyoake** [comment]
Hi @misterburton, if you found a work around could you please share. I am going through the same issue. Cheers.

**Comment by misterburton** [comment]
Hey, @coleholyoake. There's no fix that I know of, particularly as this issue is still open. That said, I've yet to try the latest aframe build. Let me know if you happen upon a fix, and I'll be happy to do the same. Cheers.

**Comment by ngokevin** [comment]
We have logged this in our next milestone: https://github.com/aframevr/aframe/issues/1036

The two animations are colliding, so introducing an ```end``` event may help. Feel free to submit a PR!

**Comment by ngokevin** [comment]
Can do in https://github.com/ngokevin/kframe/tree/master/components/animation

Like: `startEvents: mouseenter; pauseEvents: mouseleave`
