### ISSUE TITLE
Minecraft and Theater scenes crashes on iOS

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#862]
http://drawvr.com/minecraft/
http://drawvr.com/theater/

Perhaps due to too many textures? Will need to connect via Safari and get logs.

**Comment by ngokevin** [comment]
Probably, need the systems API from @dmarcos so we can have a texture caching system.

**Comment by ngokevin** [comment]
Duping with https://github.com/aframevr/aframe/issues/606
