### ISSUE TITLE
Need a non-edge-clamping shader for raw fisheye video.

### ISSUE THREAD

**Issue by RAMilewski** [aframevr/aframe#869]
It would be useful to be able to wrap unreprojected images from a fisheye lens around objects.
Very wide angle (fisheye) lenses produce circular images within a rectangular video or photo frame.
While the video output of simple wide FOV cameras can be preprojected to equirectangular video, this is computationally expensive and is difficult to do in real time.

The edge clamping of most texture shaders distorts these images unacceptably when wrapping them around objects.

A shader which pins the the center of the image to a specified point on a sphere and wraps the image with no edge clamping would make it simple to take live video feeds from simple cameras and present them as non-stereo VR images.

Wrapping around various elipsoids would allow alternate map projections.

It would be useful to be able to specify a radius from the center at which an alpha channel clips the image.

**Comment by ngokevin** [comment]
Hi, we will support this with custom shaders https://github.com/aframevr/aframe/issues/880 alongside the extensibility with the custom component API we already have. These use cases can be implemented within the project rather than the core library. Thanks for filing!
