### ISSUE TITLE
a-assets based preload mechanism

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#873]
We can use Three.js XHR loader to prefetch anything included in the ```a-assets``` tag. This will block the render loop until everything has loaded.

**Comment by cvan** [comment]
Thanks for filing what we talked about today. Do we want close #779 then?

**Comment by cvan** [comment]
Heh, I also found this issue I filed back in December: #724

**Comment by cvan** [comment]
Do we want to prefetch or preload? Since we're not a browser we can't really prefetch, so it sounds like we want to do preloading.

**Comment by ngokevin** [comment]
Yeah, preload. 

For 0.2.0 MVP for asset management I plan:

```html
<a-scene>  
  <a-assets>
    <img/>
    <video/>
    <a-asset src="mymodel.dae"/>
  </a-assets>
</a-scene>
```

- Everything inside assets will block the render loop.
- Use img/video loaded event/states to check if they're loaded.
- Use XHR loader for generic `<a-asset>`s
- Move `<a-assets>` into the scene to plug into the scene's `loaded` logic. The scene will wait for all of its child nodes to emit `loaded` before loading itself. So if we move assets into the scene and call `load()` at the right time, we don't have to do any extra work.

**Comment by cvan** [comment]
also, consider `<audio>`.

> Use img/video loaded event/states to check if they're loaded.

whenever an `error` event is emitted by an `<img>` , `<video>`, or `<audio>`, can we skip that asset and move on to the next one?

also, be sure to check for same-origin issues; if a video is defined as `<video>` (not `<video crossorigin>`), we need to handle that type of error and skip the asset as well.

also, I could be wrong, but I believe you need to do `<img crossorigin>` to be able to use that image with a canvas.

similarly - and this probably warrants filing a separate issue, 

> Use XHR loader for generic `<a-asset>`s

I can see this name get confused with `<a-assets>`. 

> Move `<a-assets>` into the scene to plug into the scene's `loaded` logic. The scene will wait for all of its child nodes to emit `loaded` before loading itself. So if we move assets into the scene and call `load()` at the right time, we don't have to do any extra work.

I like this a lot :+1: 

will `<a-assets>` still emit `loaded` even if one or more assets were unable to be loaded successfully? which other events will get emitted?

**Comment by cvan** [comment]
also, https://w3c.github.io/preload/#h-early-fetch-of-critical-resources has a lot of great ideas to borrow inspiration from

**Comment by ngokevin** [comment]
Yeah, forgot to mention `audio`.

> whenever an error event is emitted by an <img> , <video>, or <audio>, can we skip that asset and move on to the next one?

Yeah, will skip erroring assets.

> also, be sure to check for same-origin issues; if a video is defined as <video> (not <video crossorigin>), we need to handle that type of error and skip the asset as well.

Will do.

> also, I could be wrong, but I believe you need to do <img crossorigin> to be able to use that image with a canvas.

Will check.

> I can see this name get confused with <a-assets>. 

Better name?

> will <a-assets> still emit loaded even if one or more assets were unable to be loaded successfully? which other events will get emitted?

Yeah. I think I'll introduce a configurable timeout and emit another event on top of loaded if a timeout occurs.

**Comment by cvan** [comment]
> Better name?

I was thinking of one and then I forgot. lol, my bad. `<a-preload>` and `<video a-preload>`?

**Comment by ngokevin** [comment]
video doesn't need any special tag. i think i would prefer a general asset class that we can extend the behavior of in the future. If it's just a naming issue to not conflate with `<a-assets>`, maybe just `<a-asset-item>`.
