### ISSUE TITLE
Add a help/info modal (or as a third-party component) that shows A-Frame version, webvr-polyfill version, etc.

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#874]

**Comment by ngokevin** [comment]
Seems like console.logging it is enough

**Comment by cvan** [comment]
No, this is for end users too, not developers

**Comment by ngokevin** [comment]
end users don't need to know the internal package versions as a modal. even so, that is very prescriptive.

**Comment by cvan** [comment]
okay, that's fine - useful for debugging. can be a third-party component per the title.
