### ISSUE TITLE
rStats tries to load rStats.css (when we don't need it to)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#876]
it looks like it's trying to load [http://localhost:9000/examples/style/rStats.css](http://localhost:9000/examples/style/rStats.css) when it should be [http://localhost:9000/style/rStats.css](http://localhost:9000/style/rStats.css).

Cause: https://github.com/aframevr/aframe/blob/253c56c/src/core/a-scene.js#L623

I thought we fixed this by bundling `rStats.css` in `src/index.js`? @ngokevin?

**Comment by ngokevin** [comment]
Yeah, I guess we can remove that line in RStats instantiation.

**Comment by cvan** [comment]
well, it's trying to load its version of `rStats.css`. and we're already loading our own fork of the `rStats.css`. so, yeah, I'm patching rStats right now.

**Comment by cvan** [comment]
https://github.com/spite/rstats/pull/16
https://github.com/spite/rstats/pull/14
