### ISSUE TITLE
NS_ERROR_STORAGE_CONSTRAINT in Nightly 44 and 45

### ISSUE THREAD

**Issue by hwray** [aframevr/aframe#887]
A-Frame fails to load in legacy builds of Firefox Nightly. It throws a `NS_ERROR_STORAGE_CONSTRAINT` error to the console from `line 56980`: 

```javascript
[56979] var ls = storage(); 
[56980] if (ls && (parseInt(ls.logs, 10) || ls.logs === 'true')) {
[56981]  debug.enable('*');
[56982] } else {
...
```

Temporary workaround: remove the variable initialization from `line 56979`: 

```javascript
[56979] var ls; 
```

Supporting old Nightly builds is probably low on the priority list for A-Frame (and understandably so). I thought I'd raise this issue anyways, in case it crops up in any other browser environments / edge cases. 

Repro: 
1. Install an [old build of Nightly.](https://ftp.mozilla.org/pub/firefox/nightly/) (I tested the issue in [44.0a1](http://archive.mozilla.org/pub/firefox/nightly/2015/10/2015-10-18-03-02-50-mozilla-central/firefox-44.0a1.en-US.win64.installer.exe) and [45.0a1](http://archive.mozilla.org/pub/firefox/nightly/2015/12/2015-12-09-03-02-28-mozilla-central/firefox-45.0a1.en-US.win64.installer.exe). Issue may also exist in earlier builds.) 
2. Visit [aframe.io.](aframe.io)
3. A-Frame fails to load - no canvas is created and the center of the page remains blank.

**Comment by ngokevin** [comment]
This is a Nightly issue, not A-Frame. You will get that error on most pages you will visit, and you will have to create a new Firefox profile. I ran into this.

**Comment by hwray** [comment]
Ahh, interesting. Thank you for the fast response!

**Comment by ngokevin** [comment]
No problem, sucks that it corrupts your profile.
