### ISSUE TITLE
Make animations components

### ISSUE THREAD

**Issue by i3games** [aframevr/aframe#888]
"Animations and transitions in A-Frame are defined using the <a-animation> element as a child." I would suggest to have animations as components.

**Comment by dmarcos** [comment]
Thanks for the feedback! Each entity can take one component of each type. If animations were components, How would you apply multiple animations to a single entity? How would an API to play animations in parallel or in sequence look like?

**Comment by i3games** [comment]
Makes sense. I was looking for a way to programatically set animations like `element.setAttribute('animation', {from: "0 0 0", to: "1 1 1" });` which seems not possible then. I can do `anim.setAttribute("from", "1 1 1")` which becomes pretty verbose.

**Comment by ngokevin** [comment]
We have https://github.com/aframevr/aframe/issues/732

I had an idea to refactor animations such that we create an imperative API and `<a-animation>` uses that API, but unfortunately we have a couple other priorities before we start to focus on improvements to the animation system.

**Comment by i3games** [comment]
Ok.
