### ISSUE TITLE
setAttribute not working for vec3 types

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#889]
For the following schema on ```my-component```:
{ position: { type: 'vec3', default: '0 0 0' } }

The following does not work as expected
````javascript
el.setAttribute('my-component', 'position', { x: 0, y: 1, z: 0 });
````
What I see on the DOM is 
````javascript
<a-entity my-component="position: [object Object]"></a-entity>
```` 
Something in the parsing/serialization logic of the component is not working properly.

**Comment by ngokevin** [comment]
Need to update Component.stringify() to run the property type's stringifier for each property. Currently the stringify is only working for single-prop schemas.

**Comment by dmarcos** [comment]
Fixed
