### ISSUE TITLE
Camera color not visible on mobile browser.

### ISSUE THREAD

**Issue by sergioroja** [aframevr/aframe#892]
Phone: Motorola moto e
android: 4.4.4
Browser: chrome 47.0.2

**Comment by sergioroja** [comment]
I fix this issue by changing shader: flat to shader: standard

 <a-entity visible="${cursor-visible}"
              position="0 0 -${cursor-offset}" 
              geometry="primitive: ring; radiusOuter: 0.016; radiusInner: 0.01"
              material="color: ${cursor-color}; shader: flat; transparent: true; opacity: ${cursor-opacity}"
              scale="${cursor-scale} ${cursor-scale} ${cursor-scale}"
              cursor="maxDistance: ${cursor-maxdistance};">
    </a-entity>

**Comment by ngokevin** [comment]
fixed when we bumped three, on our dev branch. we releasing a patch today
