### ISSUE TITLE
360 video example not working in Safari (OSX)

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#900]
![image](https://cloud.githubusercontent.com/assets/1560884/12593078/14f007ba-c424-11e5-811f-07936cbe676a.png)

**Comment by ngokevin** [comment]
I think this is Safari's problem, and I'm not sure we are supporting Safari. There are a lot of three.js issues about Safari where mrdoob suggests people contact Apple.

Regardless, I don't think this is actionable by us. It's either on three.js or Apple.

**Comment by cvan** [comment]
> Regardless, I don't think this is actionable by us. It's either on three.js or Apple.

Can you link to some issue or blog post or something? If there's a problem with a dependency or technology we use, it's our problem too.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
