### ISSUE TITLE
panorama demo shows black screen and goggles don't do anything on iOS

### ISSUE THREAD

**Issue by autonome** [aframevr/aframe#904]
Tested Safari and Firefox on iOS with:

https://mozvr.github.io/panorama-viewer/

**Comment by ngokevin** [comment]
That actually isn't using A-Frame. A-Frame examples are at https://aframevr.github.io/aframe or http://aframe.io/examples

**Comment by ngokevin** [comment]
The project is at https://github.com/MozVR/panorama-viewer

**Comment by cvan** [comment]
(Filed as MozVR/panorama-viewer#11)
