### ISSUE TITLE
Better document how to contribute to A-Frame 

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#918]
There's an open issue to flesh out the [Community page on the A-Frame site](https://aframe.io/community/): aframevr/aframe-site#16 

But we should also document in this repo (in the [`README.md`](https://github.com/aframevr/aframe/blob/dev/README.md) and/or the [`CONTRIBUTING.md`](https://github.com/aframevr/aframe/blob/dev/CONTRIBUTING.md)) so folks know how to contribute to A-Frame.

Folks can write tutorials, create new components, make new scenes and share them on [awesome-aframe](https://github.com/aframevr/awesome-aframe) and the [Made with A-Frame Tumblr](https://aframevr.tumblr.com/), file issues against this repo, help reproduce/fix bugs, write/translate documentation/the site, participate/share/teach in Slack + Reddit + Twitter, etc.

**Comment by cvan** [comment]
Also from @dmarcos:

> on the testing front there are things we need badly. More unit tests, and have in place something to measure coverage. In the coding front we have to start to flag some of the bugs with an ​*easy*​ tag for newcomers to get familiarized with the code and process. Anything about coding that interests you in particular? I can point you to some bugs to investigate/fix if there's something you're interested.

**Comment by ngokevin** [comment]
Going to dupe + merge with https://github.com/aframevr/aframe/issues/971
