### ISSUE TITLE
Bump three.js to r74

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#919]
See https://github.com/mrdoob/three.js/pull/7174/files

/cc @ngokevin

**Comment by dmarcos** [comment]
It seems that those changes were never merged.

**Comment by cvan** [comment]
ah, good catch. maybe mrdoob/three.js#7196. anyway, we obviously have to just wait this out. or upstream a fix ourselves.

**Comment by ngokevin** [comment]
Gonna bump threejs anyways since they released 0.74.
