### ISSUE TITLE
Rotating devices causes incorrect 90 degree rotation in Firefox (but not Chrome)

### ISSUE THREAD

**Issue by Miserlou** [aframevr/aframe#920]
Using this: https://2djdovx6f3.execute-api.us-east-1.amazonaws.com/beta/4/

Going into WebVR mode and rotating the device works flawlessly with Chrome (except for a mystery white line), but in mobile Firefox it causes the two images to be rotated 90 degrees, rendering it kind of unusable.

**Comment by Manzoor231** [comment]
give me the code reference where its present give a full link @ngokevin

**Comment by dmarcos** [comment]
We no longer have polyfilled cardboard mode and only have VR / AR mode on WebXR supported browsers. This no longer should be a problem
