### ISSUE TITLE
Document how to use theta-length

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#921]
see https://gist.github.com/cvan/eb86d3f45992575d9943

**Comment by ngokevin** [comment]
We're going to document *everything* we know :)

**Comment by ngokevin** [comment]
Going to track and do this as a part of https://github.com/aframevr/aframe/issues/921 . I got it documented

**Comment by felipenmoura** [comment]
Hi, I know this is an old issue, but the only place I found documentation about thetaLength was in geometry.
Like this:
```
<a-entity
  geometry="primitive: circle; radius: .2; thetaLength: 180; thetaStart: 45;"
  material="side: double"
></a-entity>
```

But it does not work on an `<a-circle>` element, or does it?
If I want to animate the `thetaLength` property, for example...how am I supposed to do so?

Thanks
