### ISSUE TITLE
Debounce setAttribute for components

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#922]
setAttribute update components but we don't need to change the element attribute on every single call. Keeping the element attribute updated is only useful for development when using the DOM inspector. We can limit the updates to one every 100/200ms and save a lot of component stringify calls.

**Comment by ngokevin** [comment]
Gave this a 10 minute shot, A-Frame didn't like the asynchrony it introduced. Will try again some other time.

**Comment by ngokevin** [comment]
Solved this by not flushing to DOM by default.
