### ISSUE TITLE
Throw warning when trying to do <a-animation ease> instead of <a-animation easing>

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#923]

**Comment by darkwing** [comment]
Is wanting this warning a result of an API change?  I know this is a simply attribute check but it seems like extra processing for something that probably doesn't happen very often.

**Comment by ngokevin** [comment]
No, it's just to assist with user/developer errors. I mess this up sometimes.

Although I sort of want to deprecate `<a-animation>` for better solutions in the future, so this is not too important.
