### ISSUE TITLE
Create a load spinner scene component

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#925]
We can provide a default spinner with a cool aframe logo animation shown while assets load. It also serves as an example for people to implement their own spinners if they don't want the default one. @cvan @ngokevin What do you think?

**Comment by elliotaplant** [comment]
Has anything like this been implemented yet? Is there an event that gets triggered when all the assets load?

**Comment by elliotaplant** [comment]
Nevermind, found the `loaded` event: https://aframe.io/docs/core/asset-management-system.html#Events

**Comment by donmccurdy** [comment]
I don't think this has been implemented. Just crossed my mind again; I've written up some thoughts on the component wishlist: 

https://github.com/aframevr/aframe-registry/issues/64

**Comment by dmarcos** [comment]
There's a work in progress https://github.com/aframevr/aframe/pull/2153

**Comment by donmccurdy** [comment]
Nice! I'd been thinking of something in CSS (quick and easy; could be done as a third-party component, etc.). I assume you chose canvas instead so the loading screen could be visible in VR? Good point...

**Comment by k1soltan** [comment]
great news

**Comment by dmarcos** [comment]
There’s one in master now.
