### ISSUE TITLE
Examples with templates/primitives no longer load in Safari

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#929]
1. Check out [dev](https://github.com/aframevr/aframe/tree/dev)
2. Load [http://localhost:9000/examples/boilerplate-helloworld/](http://localhost:9000/examples/boilerplate-helloworld/)
3. Notice this JS error in the Console:

```
TypeError: undefined is not an object (evaluating 'this.renderer.render')    a-scene.js:454
```

![screenshot of "Hello World" scene in Safari on OS X](https://cloud.githubusercontent.com/assets/203725/12841641/1f257384-cba2-11e5-8591-65a3cdea80d8.png 'screenshot of "Hello World" scene in Safari on OS X')

/cc @ngokevin

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
