### ISSUE TITLE
Cursor test example does not show cursor anymore

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#938]
[http://localhost:9000/examples/cursor/](http://localhost:9000/examples/cursor/)

<img width="1552" alt="screenshot 2016-02-05 02 42 14" src="https://cloud.githubusercontent.com/assets/203725/12844078/14c5e774-cbb2-11e5-9d08-c88fcf3fb783.png">

**Comment by cvan** [comment]
And in [http://localhost:9000/examples/visibility/](http://localhost:9000/examples/visibility/) too

**Comment by ngokevin** [comment]
fixed for me
