### ISSUE TITLE
Double-sided cylinders are borked

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#939]
[http://localhost:9000/examples/cylinders/](http://localhost:9000/examples/cylinders/)

<img width="1552" alt="screenshot 2016-02-05 02 43 41" src="https://cloud.githubusercontent.com/assets/203725/12844117/5972b424-cbb2-11e5-8622-2f69d7be2f55.png">

**Comment by ngokevin** [comment]
That's what it's always looked like since it was pulled from the aframe-core repo. You must be looking for the other cylinder example.

Also issue needs more detail.

**Comment by cvan** [comment]
Hmm, I pulled `master` and `dev` of the old `aframe-core`. And the double-sided cylinder looked the same. Is that correct? If so, why? Out of context, it looks pretty wrong/borked.
