### ISSUE TITLE
Lighting missing/busted in Geometries test example

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#940]
I don't remember this example looking like this.

[http://localhost:9000/examples/geometries/](http://localhost:9000/examples/geometries/)

<img width="1552" alt="screenshot 2016-02-05 02 44 50" src="https://cloud.githubusercontent.com/assets/203725/12844143/82d09034-cbb2-11e5-9b18-cebea1280247.png">

**Comment by cvan** [comment]
Same with [http://localhost:9000/examples/mixin/](http://localhost:9000/examples/mixin/)

**Comment by cvan** [comment]
Also [http://localhost:9000/examples/visibility/](http://localhost:9000/examples/visibility/). Noticed the same with a few other examples, but I assume it's the same issue everywhere.

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe/issues/694
