### ISSUE TITLE
Weird reflections in Geometry Gallery test example

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#941]
Is this expected?

[http://localhost:9000/examples/geometry-gallery/](http://localhost:9000/examples/geometry-gallery/)

<img width="1552" alt="screenshot 2016-02-05 02 44 50" src="https://cloud.githubusercontent.com/assets/203725/12844187/b287e99e-cbb2-11e5-934a-24c240f15830.png">

**Comment by ngokevin** [comment]
Wrong screenshot, but yes floor is marble so should have reflections
