### ISSUE TITLE
Model test example busted

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#942]
The scale and position look way off:

[http://localhost:9000/examples/model/](http://localhost:9000/examples/model/)

<img width="1552" alt="screenshot 2016-02-05 02 47 45" src="https://cloud.githubusercontent.com/assets/203725/12844218/e34c42b4-cbb2-11e5-9c42-ef5dad4b3384.png">

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/962
