### ISSUE TITLE
Images missing in Pano Explorer test example

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#943]
[http://localhost:9000/examples/panoexplorer/](http://localhost:9000/examples/panoexplorer/)

<img width="1552" alt="screenshot 2016-02-05 02 49 04" src="https://cloud.githubusercontent.com/assets/203725/12844245/09a8bd48-cbb3-11e5-8fa0-7d0cabe9ceaf.png">

**Comment by ngokevin** [comment]
fixed

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/commit/1dc345ceac96c95c43169d94819bc86adc311968
