### ISSUE TITLE
Default Primitives test example busted

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#944]
There are three empty entities. Why are these entities (`a-video`, `a-image`, `a-curvedimage`) here without `src`s?

[http://localhost:9000/examples/template-defaults/](http://localhost:9000/examples/template-defaults/)

<img width="1552" alt="screenshot 2016-02-05 02 54 12" src="https://cloud.githubusercontent.com/assets/203725/12844373/c45b71f8-cbb3-11e5-8a90-56d062293fb8.png">

**Comment by cvan** [comment]
This is definitely caused because the templates pass a `url()`. Interestingly fixed by @ngokevin's primitives PR #883, but I think we should fix this example regardless.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
