### ISSUE TITLE
Update 0.2.0 docs, guide

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#949]

**Comment by ngokevin** [comment]
I could do this when I start writing.

**Comment by cvan** [comment]
Okay, if you consider completing the guide part of 0.2.0 docs, sounds good to me. Didn't want to create a mega-bug assuming it's too much work.

**Comment by cvan** [comment]
Also don't forget

* `<a-cone>` (aframevr/aframe-site#127)
* `<a-ring>` (aframevr/aframe-site#128)
* Better document model options (aframevr/aframe-site#132)
* Improve Animation docs for `begin="{event}"` (aframevr/aframe-site#125)

**Comment by ngokevin** [comment]
yeah it's all docs to me. the guide is the lead-in to the docs.

check/check/check/check, i have all of those down in the PR. let me know if there's anything else i shouldn't forget, though i plan on brain dumping everything

**Comment by ngokevin** [comment]
Mostly done but will be modifying it further later
