### ISSUE TITLE
Include example of scene with a Service Worker for sweet perf

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#951]
It'd be a great example to showcase.

And, if we want to get even fancier, we can show off a [Progressive Web App](https://developers.google.com/web/progressive-web-apps). Chrome for Android will prompt a user to add a site/app to the homescreen if it detects a registered Service Worker, a W3C manifest, and three or more subsequent visits to the page.

So, what we'd need is something like this:

``` html
<link rel="manifest" href="manifest.json">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<script>navigator.serviceWorker.register('sw.js').then(function () { … }).catch(function () { … });</script>
```

**Comment by cvan** [comment]
Perhaps we could use this issue instead of #1759.

**Comment by ngokevin** [comment]
https://www.supermedium.com/blog/service-workers
