### ISSUE TITLE
Event Listener available types

### ISSUE THREAD

**Issue by chang47** [aframevr/aframe#955]
Hi,

For a project of mine, I'm using jquery to add event listeners onto my components to add my own logic, the only one that I was able to get to work was 'click', I would like to be able to use 'mouseenter' and 'mouseleave'. Are these not supported? And if they are, where might be able to find documentation on them and other available types?

Thanks!

**Comment by ngokevin** [comment]
They should be supported. Ping us on Slack for questions and let's see what's happening https://aframevr-slack.herokuapp.com/
