### ISSUE TITLE
A-Model and sky do not work on Android devices

### ISSUE THREAD

**Issue by tim-peters** [aframevr/aframe#956]
While on IOS devices everything works fine, on android sky and a-model elements are not getting displayed (there is just black space instead).

**Comment by tim-peters** [comment]
This issue might belong to #933

**Comment by ngokevin** [comment]
I think this is an addressed issue on the `dev` branch where we bumped 3js to fix Android shader bugs.

Today, I think I will try to publish a patch version to master to address Android. Sorry we have not done this earlier. Thanks for reporting!
