### ISSUE TITLE
Hover function doesn't work

### ISSUE THREAD

**Issue by mayognaise** [aframevr/aframe#957]
Hi, there are some bugs for hover function:
- hover works only with `<a-cube>`, not with other element such as `<a-plane>`
- `<a-entity geometry="primitive: box;”>` doesn’t work even though it creates same as `<a-cube>`
- `<a-cube>` doesn’t work if the position is far from origin

please check this video: 
http://cl.meowyo.com/f77r
http://cl.meowyo.com/f7Rb

**Comment by ngokevin** [comment]
I think you have set `color="yellow"` for the entity. Setting `color` on the entity won't do anything. I think for entity, you will have to manually register an event listener in Javascript to set the color. I don't think those declarative events can handle setting a component property.
