### ISSUE TITLE
look-at is not taking the parent element position into account.

### ISSUE THREAD

**Issue by masom** [aframevr/aframe#966]
```
<a-scene>
<a-entity position="0 1 0">
    <a-cube look-at="#focal" position="1 0 1" width="0.5" height="0.5" depth="0.5"></a-cube>
    <a-cube id="focal" position="0 0 0" width="0.5" height="0.5" depth="0.5" color="blue"></a-cube>
</a-entity>
  </a-scene>
```

The gray cube should be looking at the blue cube, it is actually not taking into account the 1 meter elevation of the parent.

http://codepen.io/masom/pen/YwBNvg

**Comment by andreasplesch** [comment]
Looks like THREE.js problem:

https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L264

**Comment by ngokevin** [comment]
Moved to https://github.com/ngokevin/aframe-look-at-component/issues/1
