### ISSUE TITLE
Mobile Safari immediately exits fullscreen mode on iPhone 5C

### ISSUE THREAD

**Issue by vorg** [aframevr/aframe#967]
![screen shot 2016-02-12 at 18 30 08](https://cloud.githubusercontent.com/assets/171001/13016449/b2f2782c-d1b6-11e5-8724-a31dfa84cb8f.jpg)

When visiting AFrame website on my iPhone 5C with iOS9 and switching to landscape mode it first enters the fullscreen and then immediately exists it. My own experiments and http://vr.chromeexperiments.com work fine so I guess it must be some code modifying DOM in your examples triggering change of layout.

Here is the video showing the behaviour: https://vimeo.com/155153964/48dd611c61

**Comment by klombomb** [comment]
You're going to have to pin it to your home screen and add these meta tags:
https://developer.apple.com/library/iad/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html

I have a 5C to and it works for me.

**Comment by cvan** [comment]
Still reproducible per https://twitter.com/marcinignac/status/709880816449544192

**Comment by cvan** [comment]
Ah, this will be solved by my PR: https://github.com/aframevr/aframe/pull/1112

**Comment by cvan** [comment]
#1112 is merged. this appears fixed to me from my iOS tests.
