### ISSUE TITLE
remove dev/master workflow

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#972]
Every time someone makes a PR then, it will auto-target the `dev` branch.

**Comment by cvan** [comment]
I'm kind of favour of this, but when people land on https://github.com/aframevr/aframe they're going to see the unstable (`dev`) version of A-Frame.

idk, I'm not a big fan of this `dev` vs. `master` workflow. I'd prefer to just do very regular releases.

**Comment by ngokevin** [comment]
Maybe that's fine if the people checking out Github are people that more interested in seeing what's happening or want to use the latest builds. If `dev` is `master`, then every PR is sort of an unstable release to the Github repo.

**Comment by cvan** [comment]
again, yeah, that's why I think `dev`/`master` workflow isn't the best system. it encourages breaking trunk and longer releases. I realise the intention may be to move faster, but it seems to do the opposite.

**Comment by ngokevin** [comment]
Okay, I agree, just have a single `master`. Bump dist when we feel ready. Publish NPM when we really feel ready

**Comment by cvan** [comment]
I like that

**Comment by JoshGalvin** [comment]
+1 on killing the dev/master workflow. One master, staggered releases. Maybe some feature branches for crazy people (though why not do that in your own fork?)

**Comment by ngokevin** [comment]
What would staggered releases look like?

**Comment by JoshGalvin** [comment]
I've seen projects just set monthly/quarterly milestones that bundle up all the changes made for that period.

**Comment by ngokevin** [comment]
@dmarcos Input? I'm currently for developing on master:

- More transparent
- Project looks more active
- People see latest code when they hit GitHub
- Many people already working off of dev branch
- The people that go to GitHub are interested in grabbing latest code + developing. Those that want to use Stable A-Frame will grab from CDN or NPM.

Master would then not be expected to be Stable. Which is fine since `dev` is arguably more stable than `master` at the moment with its mass amount of bug fixes.

**Comment by dmarcos** [comment]
I'm fine with converging development on master. Should the files on the dist directory reflect the stable version?

**Comment by ngokevin** [comment]
We can have both stable dist + nightly dist in the `dist` folder?
