### ISSUE TITLE
Extensible controls (Trouble using multiple controls, refactor controls)

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe#975]
There's a change on the dev branch that breaks one of my examples. Code:

``` html
<a-entity camera
          rotation="0 0 0"
          look-controls
          gamepad-controls>
</a-entity>
```

(actual scene i'm testing is [here](https://github.com/donmccurdy/sandbox-aframe/blob/master/examples/platforms/index.html), but has `look-controls` removed temporarily)

In that example there are three ways of rotating the camera: HMD (w/ `look-controls`), mouse (w/ `look-controls`), and gamepad right joystick (w/ `gamepad-controls`). In v0.1.\* this just worked, because my update() function in `gamepad-controls` was always called last, and I was careful to only update rotation when the gamepad was in use. On _dev_ that seems to have changed – `gamepad-controls.tick()` is called first, and `look-controls.tick()` overwrites my rotation regardless of whether any HMD or mouse events are happening. I've [tried to work around this in my code](https://github.com/donmccurdy/aframe-gamepad-controls/blob/feat-lock-rotation/gamepad-controls.js#L191), but it gets very messy quickly and I don't see a good solution without asking users of `gamepad-controls` to _also_ use some new custom version of `look-controls`.

I don't care much about the order in which component `tick()` calls should be made (that seems too complicated), but it would be great to make it easy for demos to support multiple input devices – I don't want to target a demo _only_ at users with an HMD and a gamepad, for example, and ideally the default controls with A-Frame would be passive when they're not in use.

Can think of a couple ways to get around this:
1. Controls should always export their state to position/rotation components, and not hide state internally. `wasd-controls` already does this, but it might be harder for `look-controls` because we want that dolly pitch/roll/yaw abstraction.
2. Controls should only update state if they're in use. E.g. if there's an HMD `look-controls` should be permanently in use, but between mouse events it should avoid overwriting `rotation`.

Would you take a PR for one of these, or can you think of another way to have controls play nicely together?

**Comment by dmarcos** [comment]
You can enable/disable components by
calling el.components.yourcomponent. pause() / play() 
What about handling the configuration of your controls in a separate component "my-controls" that sets up mouse-look, gamepad, hmd-controls... and enable / disable them based on the specific needs of your content? I'm trying to determine if we should handle controls collisions at the core or if it should br up to the application to manage it.

**Comment by donmccurdy** [comment]
Tried to enable/disable components in a branch [here](https://github.com/donmccurdy/aframe-gamepad-controls/blob/feat-lock-rotation/gamepad-controls.js#L191-L274). Short story, it didn't really work because once my component disables `look-controls`, I can't tell when to enable it again without tracking HMD and mouse movement myself.

Of my original two suggestions now, I'm feeling like #&zwnj;1 (export state) isn't worth the trouble, but #&zwnj;2 (passive when inputs aren't changing) would probably be safe and simple enough.

I like the idea of composing controls, though, would need to think a bit about how that could work.

**Comment by ngokevin** [comment]
Sorry, I'm a bit late to this issue. Is it possible to add controls to wrapper entities so they don't collide?

```html
<a-entity gamepad-controls>
  <a-entity camera look-controls></a-entity>
</a-entity>
```

**Comment by donmccurdy** [comment]
Sort of. Assuming I want to make a demo that supports a gamepad, but doesn't require it, I might add `wast-controls` to your example:

```html
<a-entity gamepad-controls>
  <a-entity camera look-controls wasd-controls></a-entity>
</a-entity>
```

That works if you use the gamepad for both movement and looking around, or if you use an HMD + WASD controls, but not for gamepad + HMD. And you can't switch between keyboard and gamepad, because you'll be rotating the camera relative to its translation vector.

A second (less important) issue is that gamepad controls needs to know the rotation of the element to get a heading for movement, but there's probably a workaround for that.

**Comment by donmccurdy** [comment]
I am starting to think that @dmarcos's suggestion about managing multiple controls from a separate component is the way to go eventually. Like, `wasd-controls`, `look-controls`, and `gamepad-controls` could *only* be tracking the state of user input, and some other component (`navigation-manager`?) can look at that state and figure out how to update the camera's position/rotation. That would seem much better when you get into more game-like demos with jumping and wall collisions, since you wouldn't want that collision logic distributed across all of the input components.

^That's all a bit more complicated though. I mostly just want to preserve optional gamepad support in v0.2.0 at the moment. 😬

**Comment by donmccurdy** [comment]
Reading through #1056, and thought I'd contribute a strawman to the discussion. Here's one possible approach to supporting multiple input methods in a way that should be [somewhat] extensible/customizable.

```javascript
AFRAME.registerComponent('navigation', {
  schema: {
    movementControls: { default: ['wasd-movement', 'touch-movement'] }, // order by precedence
    rotationControls: {default: ['hmd-rotation', 'pointerlock-rotation', 'mousedrag-rotation'] } // order by precedence
  },
  tick: function () {
    // Rotation:
    // (1) find first enabled rotation controller
    // (2) get rotation vector
    // (3) orient camera

    // Movement:
    // (1) find first enabled controller.
    // (2) get velocity vector.
    // (3) orient velocity by rotation/heading
    // (4) update position of camera
  }
});
```

*MovementControls Interface*

* `isEnabled()` – Returns true if component is enabled and supported by the client.
* `getVelocity()` – Returns a velocity vector, relative to any object rotation. if the `W` key were pressed, this might be `[0,0,1.0]`, regardless of any HMD orientation.

*RotationControls Interface*

* `isEnabled()` – Returns true if component is enabled and supported by the client.
* `getRotation()` – Returns a rotation vector, which will (1) orient the camera, and (2) orient the velocity.

### Default/stock controls

```html
<a-entity camera navigation></a-entity>
```

### Custom/extended case

To add a custom gamepad interface, I would define `isEnabled`, `getVelocity`, and `getRotation` and then decide how precedence should compare with other controllers:

```html
<a-entity camera
          navigation="movementControls: gamepad-controls wasd-controls touch-controls;
                      rotationControls: hmd-controls gamepad-controls pointerlock-controls;"
</a-entity>
```

**Comment by ngokevin** [comment]
Thanks for the proposal, will read through thoroughly once I have time.

**Comment by donmccurdy** [comment]
Alrighty so I went and built this.

* *Universal Controls*: parent component that manages the interface-specific components. Code [here](https://github.com/donmccurdy/sandbox-aframe/blob/master/src/universal-controls.js).
* Implemented an assortment of interface-specific controls, including all the default A-Frame components, plus gamepad, pointerlock, and touch-to-move. Code [here](https://github.com/donmccurdy/sandbox-aframe/tree/master/src/controls).

**Cons**

* The extra abstraction layer complicates things for new users, and I could see where that might be a deal-breaker for inclusion in the core library.

**Pros**

* Third-party controls (e.g. gamepad) play nicely w/ A-Frame's defaults, because only `universal-controls` actually gets to modify the entity's position/velocity.
* For game-friendly features like static collision detection (e.g. prevent player from walking through walls) in the core framework, the extra abstraction of `universal-controls` helps immeasurably. If gamepad, keyboard, and touch-to-move controls all modify player position directly, they also have to _all_ check for obstacles, and that's a mess.

Just for fun, [here is a demo](https://sandbox.donmccurdy.com/vr/obstacles/) implementing various controls (gamepad, keyboard, pointerlock, touch-to-move) with collision detection on the walls using CANNON.js. Code [here](https://github.com/donmccurdy/sandbox-aframe/blob/master/examples/obstacles/index.html).

**Comment by ngokevin** [comment]
@donmccurdy OK, that is awesome. I'm looking through it, and it might solve our controls story. Looks like we'd be able to register new controls and have them all concatenate correctly using an single interface. I love the separate velocity component, will be necessary for physics.

There could probably be further abstraction to have preconfigured control schemes?

**Comment by ngokevin** [comment]
@dmarcos Can you look through those controls when you have time? They are device-specific, but looks like they can be composed to create control schemes.

**Comment by ngokevin** [comment]
Will close for now to focus on WebVR and keep simplicity without the extra layer. But the `universal-controls` are still a great option and can reconsider layer or take some of its nice defaults (e.g., pointer lock, but only after entering fullscreen).
