### ISSUE TITLE
Prevent events from triggering on hidden elements 

### ISSUE THREAD

**Issue by auxdesigner** [aframevr/aframe#979]
My use case: Click X to show Y. Hover Y to do Z.
Y is set to hidden by default using visible = "false". X has a click event listener to show Y (set Y visible = "true"). Y has a hover event listener to do Z.

Problem is:
Even when Y is hidden, if I accidentally hover on the invisible area, it still triggers Z. In the example below, even if I don't click X, the hover events still works on Y.

Code:
//Click X to show Y
document.querySelector('#X').addEventListener('click', function () {
            document.querySelector('#Y').emit('show');
});

//Hover Y to show Z
document.querySelector('#Y').addEventListener('mouseenter', function () {
            document.querySelector('#Z').emit('fadein');
});

//Mouse leave Y to hide Z
document.querySelector('#Y').addEventListener('mouseleave', function () {
            document.querySelector('#Z').emit('fadeout');
 });

(BTW, I was a UX design intern at Mozilla in 2013 :-) Great job on A-frame!)

**Comment by masom** [comment]
@auxdesigner have you tried to determine if them target item was visible in the event listener?

You could decide to only emit when needed.

**Comment by ngokevin** [comment]
Set the material to visible for raycaster to ignore

`material="visible: false"`

**Comment by afvc** [comment]
I've had a similar issue.
I have the same structure as you but I can't get X to read my click event.
Both Y and Z are "visible: false".
