### ISSUE TITLE
Unable to load image/texture even after window is loaded

### ISSUE THREAD

**Issue by SantanMaddi** [aframevr/aframe#980]
In HTML:
`<a-assets>
  <img src='img-link' id='img-01'>
</a-assets>
<a-entity id='img-entity'>
</a-entity>`

In JS: 
`(function(){
var img = document.createElement('a-image');
  img.setAttribute('width', "1.5");
  img.setAttribute('src', '#img-01');    
  window.onload = function(){
    img.setAttribute('src', '#img-01');    
  };
  var entity = document.getElementById('img');
  entity.appendChild(img);
})();`

So I am trying to append a-entity with a-image on both document.onload and window.onload. However the image is black. An example is [here](http://codepen.io/SantanMaddi/pen/RrdRQq) for reference.

The fault is because texture is used even before it is loaded. If I am correct, the texture should be loaded/ready at least on window.onload. Unable to get around with this issue, any suggestions for it?

**Comment by ngokevin** [comment]
The a-image helper currently doesn't accept selectors. It will in the next version. Sorry about that, the docs might have been misleading

**Comment by ngokevin** [comment]
You can use `<a-entity material="src: #img-01">` if you are using 0.1.0. The `dev` branch will soon have a patch landing that will let you set that material component on the `<a-image>` element.

**Comment by SantanMaddi** [comment]
Thanks @ngokevin
