### ISSUE TITLE
style-attr module prevents from use of base64 uri as material src

### ISSUE THREAD

**Issue by maxkrieger** [aframevr/aframe#982]
A data-URI scheme for base64 images [consists of multiple characters, one being a colon (`:`), the other being a semicolon (`;`)](https://en.wikipedia.org/wiki/Data_URI_scheme#Examples).

Thus, one cannot use base64 urls directly, as the semicolon & colon are parsed as their own key-value set in a component. This could become a problem for many, including me, if they wish to dynamically generate images on the fly.

The problem is here, in the style-attr module, where the style attribute string wholesale splits the string by semicolon and colon:
https://github.com/joshwnj/style-attr/blob/master/index.js#L21

There needs to be some way to ignore semicolons within a `url()` property. I'll raise an issue in the style-attr repo for now.

**Comment by maxkrieger** [comment]
Raised an issue in style-attr: https://github.com/joshwnj/style-attr/issues/2

**Comment by ngokevin** [comment]
Yeah, should be doable to escape semicolons in url().

**Comment by maxkrieger** [comment]
Just got fixed. https://github.com/joshwnj/style-attr/pull/3

**Comment by ngokevin** [comment]
Want to make a PR to aframe#dev to bump the style-attr version?

**Comment by maxkrieger** [comment]
Semver sorted it out already, but I'll put it up there.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/985

**Comment by ngokevin** [comment]
Ah right, it still worked, but good to mark it down
