### ISSUE TITLE
Default position of camera or geometry is off (dev branch)

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe#993]
for the following:
````html
<a-scene>
  <a-camera></a-camera>
  <a-cube></a-cube>
</a-scene>
````

I see:
![image](https://cloud.githubusercontent.com/assets/1560884/13120944/fa935604-d564-11e5-89f7-e3bbe92b745d.png)

Expected to see nothing, since the camera and cube should be sharing the same position.  

This is only an issue on the dev branch.   Seems to be fine with 0.1.0

**Comment by RangerMauve** [comment]
As you can see [in the docs](https://aframe.io/docs/primitives/a-camera.html#Replacing_the_default_scene_camera), the default camera is actually offset a little and isn't directly in the center.

**Comment by RangerMauve** [comment]
Wait, nevermind, that's only when it's auto-injected. My bad.

**Comment by ngokevin** [comment]
I'm touching this right now. Might be that the scene doesn't catch `<a-camera>` initializing its camera, and it swaps to the default camera, disabling the set camera. setTimeout in camera setup code fixed for me.

**Comment by caseyyee** [comment]
FWIW, I tried setting the camera and cube object to position 0 0 0 and basically get the same as the screen capture.   It looks like the camera is set back and higher than the cube.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe/pull/883
