### ISSUE TITLE
Resolve Component.play() on initialization vs. component resume

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#994]
The states for sound component in relation to the Component.play() method is a bit hairy.

When a component is initialized, it will try to play. For the sound component, this means it will try to play even if autoplay is not set. And then when the sound is loaded, THREE.Audio will also play the sound if autoplay is set.

We could maybe get rid of the play() method for sound, but how do we handle resume? We need a way to detect when play() is being called as initialization vs. being called to resume. For the sound component, we don't want to call play(), but we do want a way to provide a resume if the scene was paused.

**Comment by ngokevin** [comment]
Also where does tick come into play?

**Comment by elliotaplant** [comment]
I'm taking a stab at this right now. I'm also trying to add a pause hotkey for 'p'. Would it make sense to add a resume() method to components?

**Comment by mkungla** [comment]
@ngokevin this seems to be solved with 'sound.playSound()' and `play()` calls `playSound()` if there is active buffer `this.data.autoplay` is true

**Comment by ngokevin** [comment]
`playSound` seems to solve it, thanks!
