### ISSUE TITLE
mixin properties should be merged not replaced

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#999]
I saw these `Primitive not supported: ` errors when I was testing [DrawVR's Tron scene](http://drawvr.com/tron/) against `dev`:

![image](https://cloud.githubusercontent.com/assets/203725/13156517/ae4292e6-d637-11e5-8c57-f05fac1e7d5c.png)

Source:

```html
<a-scene>

  <a-assets>
    <a-mixin id="build" geometry="primitive: box" material="shader: standard; metalness: 0.6"></a-mixin>
    <!-- … -->
  </a-assets>

    <!-- … -->
  <a-entity mixin="build" geometry="depth: 150; width: 150; height: 140;" position="110 69 1500" material="src: url(images/building2.png)"></a-entity>
    <!-- … -->

</a-scene>
```

Let's document this caveat in the [Mixin docs](https://aframe.io/docs/core/mixin.html).

**Comment by ngokevin** [comment]
ugh that's gross. we can try to fix it if it takes less than 20 mins, but if not we can doc and fix later

**Comment by ngokevin** [comment]
This has since been fixed at some point.
